### ISSUE TITLE
How to implement Redux with pages transitions?

### ISSUE THREAD

**Issue by nodegin** [zeit/next.js#100]
Hello,

Is there any example that showing how could Redux work with next.js pages?

Any help would be appreciate

**Comment by flybayer** [comment]
Have you seen this :point_right: https://github.com/zeit/next.js/wiki/Redux-example ?

**Comment by nodegin** [comment]
@flybayer Yes, this is only used in single page, but my question is how to keep the Redux state store across different pages

**Comment by jmfirth** [comment]
@nodegin I believe your redux store should be available in `window.store` after a client-side transition using `Link` from module `next/link`. The redux example appears to show this in `store.js->initStore`:
```js
export const initStore = (reducer, initialState, isServer) => {
  // if called server-side (initial navigation), build a new store
  if (isServer && typeof window === 'undefined') {
    return createStore(reducer, initialState, applyMiddleware(thunkMiddleware))
  } else {
    // if called client-side, try and grab the global `window.store` else if it doesn't exist create and set one
    if (!window.store) {
      window.store = createStore(reducer, initialState, applyMiddleware(thunkMiddleware))
    }
    return window.store
  } 
}
```

**Comment by nodegin** [comment]
@jmfirth I see, that make sense!
