### ISSUE TITLE
[2.0.0-beta.19 and later] Redux example fails with redux-devtools installed

### ISSUE THREAD

**Issue by Zaiban** [zeit/next.js#1003]
When using redux-devtools with 2.0 beta 19 or newer, the app fails with a message `TypeError: Cannot read property 'position' of undefined`. All previous versions of Next work with no problems.

Minimal reproduction from with-redux repo with DevTools added:
https://github.com/Zaiban/next-redux-devtools-test

**Comment by timneutkens** [comment]
@Zaiban Would it be an option to use this: 
https://github.com/zalmoxisus/redux-devtools-extension

Change your initStore to:

```js
export const initStore = (reducer, initialState, isServer) => {
  if (isServer && typeof window === 'undefined') {
    return createStore(reducer, initialState, applyMiddleware(thunkMiddleware))
  } else {
    if (!store) {
      store = createStore(reducer, initialState, compose(applyMiddleware(thunkMiddleware), window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()))
    }
    return store
  }
}
```

**Comment by timneutkens** [comment]
Closing this for now. Feel free to re-open if needed.

**Comment by Zaiban** [comment]
I'm aware of the browser plugin, however it is not supported besides FF and Chrome and I have to test on a lot of browsers. Besides that, installing a plugin for every browser just to use the devtools is a pain in the ass while the integrated version just works with no additional work. I do not have enough time at the moment to research this issue further so I leave it closed for now and just disable devtools in my app completely. I will reopen this when I have some spare time to research how to get it working.

**Comment by Zaiban** [comment]
The culprit behind to this seems to be https://github.com/zeit/next.js/commit/8b94534260d7589482c844758117415936fa0996 from https://github.com/zeit/next.js/pull/856

Reverting patch-react back to
https://raw.githubusercontent.com/zeit/next.js/cec8f9dd58f125110ea067676b493f2632cf7247/client/patch-react.js
fixes the issue.
