### ISSUE TITLE
Add --hostname argument to cli

### ISSUE THREAD

**Issue by jessehattabaugh** [zeit/next.js#1010]
In Cloud9 http servers have to be run with the hostname 0.0.0.0. The cli always starts on `localhost`.

**Comment by arunoda** [comment]
You can use our custom server for that.
See: https://github.com/zeit/next.js#custom-server-and-routing

**Comment by jessehattabaugh** [comment]
I _could_, but wouldn't it be nice to have an argument like how firebase-tools and other dev servers do? Here's a PR I made, but haven't tested yet because your build process is kinda strange to me. https://github.com/zeit/next.js/pull/1017

**Comment by arunoda** [comment]
Yeah. That's good too.  
I saw your PR. Let's take it.

**Comment by rauchg** [comment]
`-H` too?

**Comment by jessehattabaugh** [comment]
I changed it to -H

**Comment by timneutkens** [comment]
Fixed in #1017

**Comment by jessehattabaugh** [comment]
Woo hoo! Thanks y'all!
