### ISSUE TITLE
Can not run "next start"

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1014]
Even though I run "next build", I am not able to run "next start". 

I can confirm that a `.next` folder is created, but I get the following error - 

"Could not find a valid build in the '.next' directory! Try building your app with 'next build' before starting the server."

**Comment by khrome83** [comment]
Uses `"next": "^2.0.0-beta.22"`

**Comment by timneutkens** [comment]
Can you check if your `.next` folder has a `BUILD_ID`file?

**Comment by timneutkens** [comment]
Also, can you provide a sample repository?

**Comment by khrome83** [comment]
Where is the `BUILD_ID` at?

<img width="388" alt="screen shot 2017-02-06 at 8 33 37 am" src="https://cloud.githubusercontent.com/assets/1844739/22650997/04791bb4-ec47-11e6-9fcf-254bdd834ac2.png">

I won't be able to standup a sample repo currently. Here is a screenshot of the output.

**Comment by timneutkens** [comment]
@khrome83 It's located right inside `.next` (`.next/BUILD_ID`). From the looks of it this `.next` folder is from a `next` `dev` build. Which is strange because `next build` should remove the `.next` folder and then create a new one with the production build. Can you try manually removing `.next` and running `next build` again?

**Comment by khrome83** [comment]
Apparently it is not building a `.next` folder. I deleted the `.next` folder and confirmed that it was because of dev.

When I run `npm build` which in turn runs `next build` it just ends. It does not give me any output.

When I run `./node_modules/.bin/next build` then it does produce a production `.next` folder with a `BUILD_ID` inside.

This is not a issue only locally on my machine. I can confirm, that on `node 6.9.1` this is also happening on the GitLab-CI environment.

**Comment by nkzawa** [comment]
@khrome83 try `npm run build` instead of `npm build`.

**Comment by khrome83** [comment]
Ok that works locally. It's strange because `npm build` does not trigger unknown NPM command, and does not trigger unknown script error

**Comment by nkzawa** [comment]
Because it's a known command 😂 😂 😂 

https://docs.npmjs.com/cli/build

This is really confusing. Anyway closing now.
