### ISSUE TITLE
Port 3030 in use

### ISSUE THREAD

**Issue by nsantini** [zeit/next.js#102]
Looks like the next server is clashing with another service I have running on 3030. Whats the full list of ports needed to run next in production and how can they be changed?

**Comment by nkzawa** [comment]
`3030` is used to run webpack-dev-server only on development.
We'd like to support customizing the port number.

For production, there is no fixed port to be used.
You can change it when starting your app like:

```
next build
next start -p 8080
```

For development:

```
next -p 8080
```

**Comment by jayres** [comment]
Moreso, if you want to always load from that specific port without typing it in every time you can specify that in the startup script in your package.json.

`  "scripts": {
    "dev": "next -p 8080"
  },
`

**Comment by thisguychris** [comment]
@nkzawa is there any plan to add the cli options for next in the README.md ?

**Comment by melbayad** [comment]
Please, how to set `port` to `process.env.port || 3000` ? Thanks in advance.
