### ISSUE TITLE
React-intl example

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1022]
I saw some people wondering how to get react-intl working with Next.js, and so far it worked well in my app: https://github.com/relatenow/relate

So maybe it could be used as inspiration to create an example in the examples folder.

**Comment by sedubois** [comment]
Also see @ericf's WIP example which does a better job of loading only the active locale client-side: https://github.com/yahoo/react-intl/pull/844

**Comment by ericf** [comment]
I completed the example. This is my first time really digging into Next, so it would be great to get a review here: https://github.com/yahoo/react-intl/pull/844

Also I'm happy to move this example app to this repo. Or if we decide to leave it in React Intl's repo, it would be nice to add least add an `examples/react-intl/README.md` entry here.

**Comment by timneutkens** [comment]
@ericf looks good! I'd love to have this in the next.js repo 👍🏻👍🏻

**Comment by ericf** [comment]
@timneutkens @sedubois I opened PR #1055 to add it here.

**Comment by julmot** [comment]
The example is broken: https://github.com/zeit/next.js/issues/3386#issuecomment-362529940
