### ISSUE TITLE
Router.push should allow push with same "as"

### ISSUE THREAD

**Issue by finneganh** [zeit/next.js#1025]
I'm making a multi-step form and would like to be able to push the same "as" on the history stack with different internal queries.

However, the current implementation of Router short-circuits and doesn't call `pushState` if the "as" matches the current window.location.

Is it reasonable to change this behavior, or allow a `{force: true}` option to work around it?

**Comment by arunoda** [comment]
Our routes are idempotent. So, we don't allow to push the same route twice.
Can I know the reason for doing that?

**Comment by finneganh** [comment]
I'm making a multi-step form and I want the back button to work to go to a
previous page (hence wanting to push) but I didn't necessarily want a new
URL in the address bar because reloading mid-flow doesn't make sense.

I was using different queries but the same "as" URL.

I think I may bite the bullet and change the "as" and just do server-side
redirects if someone GETs those intermediate locations directly.

Am I right to try and avoid pushing to the history stack on my own? (For
example, using a library that could link the history to Redux) Is that
likely to confuse the Next.js runtime?

**Comment by arunoda** [comment]
I think in this case, you need to change the URL in some way. (May be a query string)
It's might cause issues when directly updating the state. But doable.

We write some state when the page loads and getting changes. See it with `history.state`. If you preserve the fields of that object and add what ever you need an do a pushState. I think that won't do any harm.

Like this:

```js
const newState = { ...history.state, time: Date.now() }
history.pushState(newState, null, location.href)
```
