### ISSUE TITLE
getInitialProps called twice

### ISSUE THREAD

**Issue by fat** [zeit/next.js#1031]
Hi,

I have the same issue as #524

Here's a bit more info if it's helpful…

I have a super basic express server with the following routes:

```js
  server.get('/u/:username', (req, res) => {
    User.getByUsername(req.params.username, (err, user) => {
      if (err) …do error stuff…
      return app.render(req, res, '/profile', {
        user: user
      })
    })
  })

  server.get('*', (req, res) => {
    return handle(req, res)
  })
```

and then the following "profile" page component:

```js
export default class extends React.Component {
  static getInitialProps ({ query: { user } }) {
    return { user }
  }

  render () {
    return (…)
  }
}
```

If i fetch `/u/guille` my server is correctly fetching the guillermo object and passing it down to my react component on first render…

However! once the javascript on the client loads - it is reinitializing the react component and calling getInitialProps a second time (this time with an empty user object, effectively wiping away all my data 😓).

Am I doing something wrong? Im a scrub so very possible.

**Comment by nkzawa** [comment]
@fat Is it possible to prepare a repository we can reproduce the issue ?

**Comment by fat** [comment]
hey @nkzawa yep!

Here's a github repo: https://github.com/fat/next.js-bug

seems to be somethign to do with nested data…

for example if the query data i pass is:

`{ id: 'foo' }` it's great.

if i pass `{ user: { id: 'foo' } }`  it causes the client to refresh and lose the initial render.

**Comment by fat** [comment]
ok… i think i was just misunderstanding how `getIntitialProps` is supposed to work…

i think im supposed to instead just pass the query string there of "username"… and then put the actual "fetch" of the data object in the `getInitialProps` method… which is my bad.

**Comment by nkzawa** [comment]
@fat thank you, I can reproduce now.

I don't know why it occurs yet, but we don't support `{ user: { id: 'foo' } }` since this is invalid as a parsed query string. It has to be `{ id: 'foo' }`.

**Comment by fat** [comment]
yep makes sense
