### ISSUE TITLE
Duplicate title tags in Head

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1039]
When using `<Head>` on a page, as well as specifying the `<title>` in `_document.js` inside `<Head>`, both create duplicate titles.

```
<head>
  <title class="next-head">Homepage - Welcome</title>
  <meta charset="utf-8" class="next-head">
  <meta name="viewport" content="initial-scale=1.0, width=device-width" class="next-head>
  <title>Homepage</title>
  <link href="/static/styles/sanitize.css" rel="stylesheet">
</head>
```

**Comment by khrome83** [comment]
Looks like issue resolves itself if `<head>` the default HTML5 tag, is used instead of `<Head>` from Next within the `_document.js` fragment. 

Should we be using `<Head>` or `<head>` within the `_document.js`.

If we should be using `<head>` then the glamor and other `_document.js` examples are incorrect right now.

**Comment by timneutkens** [comment]
@khrome83  This https://github.com/zeit/next.js/pull/668 would solve your issue 👍 will be released in 2.1

**Comment by timneutkens** [comment]
Regarding this question:

> Should we be using <Head> or <head> within the _document.js.

cc @arunoda

**Comment by arunoda** [comment]
@khrome83 I think using the title in the `_document.js` is not a good idea. Because it'll be static and cannot change with the client side.

Using the `<Head/>` inside your pages in the better option.

**Comment by timneutkens** [comment]
Using `<Head/>` with https://github.com/zeit/next.js/tree/master/examples/layout-component is the way to go in this case. Since we dedupe `<title>` in `<Head/>`

**Comment by code4aman** [comment]
`next@2.1.0` and still facing this issue.
Here is usage example inside of reusable component:
```
<div>
  <Header>
    <style key="transcribe" dangerouslySetInnerHTML={{ __html: stylesheet }} />
  </Header>
  ...
```
this `style` tag is being render on every component usage

**Comment by code4aman** [comment]
@khrome83 did you re-checked this behavior since `2.1.0`?

**Comment by khrome83** [comment]
I have not upgraded myself. Will upgrade this week and try and reproduce.

---
Zane Milakovic

**Comment by code4aman** [comment]
update: related PR is not merged yet

**Comment by chhuang** [comment]
Removing `<Head>` from `_document.js` does not render my styles from the server and it causes FOUC.

**Comment by mmiszy** [comment]
Did you get this @khrome83 working? I'm on next 5 in 2018 and it's still unclera for me how to use <Head> in _document.js and in my pages to avoid duplicate tags.

**Comment by khrome83** [comment]
I moved most of my stuff to my layout components, and pass the information to them from the pages. The only items I use <Head> for in _document.js are things that are universal across the site and do not change.
