### ISSUE TITLE
Babel not transpiling when using next@2.0.0-beta.24

### ISSUE THREAD

**Issue by angel200sdnot** [zeit/next.js#1042]
If i use the beta 24 babel stops transpiling the code and simply copies the original into the output folder, reverting back to beta 20 fixes this issue

i have this on my package.json
```Javascript
"babel": {
    "presets": [
      "next/babel"
    ],
    "ignore": [
      ".next",
      "build"
    ]
}
```

**Comment by timneutkens** [comment]
Can you try using `.babelrc` I believe we don't support having the config in `package.json`

**Comment by angel200sdnot** [comment]
I did try that and it still wasn't working

The config in package.json is working as intended because the custom server transpiling is being done by babel outside of next with the following command
```Javascript
"build": "node_modules/.bin/babel ./ --out-dir build --ignore node_modules && cp -r static build"
```
Then i build next using
```Javascript
"build-next": "cd build && next build"
```
and finally run the server
```Javascript
"start": "NODE_ENV=production PORT=9000 node build/server.js"
```
I didnt try using beta21-23, i will do that and post back the results

**Comment by arunoda** [comment]
@timneutkens We do support babel config in the `package.json` as well.

@angel200sdnot could you send us a sample repo and tell us the exact error you are getting.

**Comment by angel200sdnot** [comment]
@arunoda Here is the sample repo https://github.com/angel200sdnot/sample_repo
If you run the build script it wont transpile the code correctly, but if you roll back to next@2.0.0-beta.20 it will work correctly

**Comment by bukinoshita** [comment]
It works just fine on *next@2.0.0-beta.21*, beta22-24 doesn't work. Used the same example on the examples folder

**Comment by arunoda** [comment]
Okay. Here's what's happening.
You are using `next/babel` here to compile your own code.
But we don't transpile import/export code.

I've seen many cases like this. So, I'd like to fix this directly.

**Comment by timneutkens** [comment]
I'm going to close this issue. Same as the pr #1095
