### ISSUE TITLE
Error:  localStorage is not defined

### ISSUE THREAD

**Issue by johhansantana** [zeit/next.js#1043]
Hello, I'm trying to run http://back4app.com/ which is a parse server for my app.

Everything seems to work fine until I realize it has some issues with server side rendering.

When I try to run a query inside `componentWillMount()` it gives me `Error:  localStorage is not defined`

Is this an issue with next.js or parse?

*update*

Parse has a server side package for node as well but I get dependency errors when I do
`import Parse from 'parse/node'`

<img width="387" alt="screen shot 2017-02-08 at 6 15 20 pm" src="https://cloud.githubusercontent.com/assets/9933887/22763866/ad23fc78-ee3d-11e6-9428-09946dfffe57.png">

**Comment by sergiodxa** [comment]
@johhansantana `componentWillMount` is executed while server rendering.

But `localStorage` only exists in the browser, so you can't use it in `componentWillMount`. You can use it in `componentDidMount`.

**Comment by eezing** [comment]
Check out the docs: https://github.com/zeit/next.js#fetching-data-and-component-lifecycle

**Comment by sergiodxa** [comment]
The problem with `fs` module is because of Webpack, you can't use that module for a browser target. Also `fs` is not universal so you can't use it inside your React code.

**Comment by arunoda** [comment]
I think this question is well answered.
