### ISSUE TITLE
Component display names in react-devtools shows `_fn` [2.0.0-beta.24]

### ISSUE THREAD

**Issue by cvpcasada** [zeit/next.js#1045]
Recently updated to `2.0.0-beta.24`. It works fine before on `2.0.0-beta.17`.

<img width="480" alt="screen shot 2017-02-09 at 2 31 17 pm" src="https://cloud.githubusercontent.com/assets/1287624/22771911/aca58180-eed4-11e6-88db-9179367ab12a.png">

**Comment by arunoda** [comment]
Note: This might be due to our client side React patches.

**Comment by nkzawa** [comment]
@arunoda I guess so. I noticed properties are not enumerable when they are defined as `static`, so 'Object.assign' doesn't work for them.

https://github.com/zeit/next.js/blob/master/client/patch-react.js#L109

**Comment by arunoda** [comment]
Hmm. Interesting.
