### ISSUE TITLE
Will imported component get reused?

### ISSUE THREAD

**Issue by zhaoyao91** [zeit/next.js#1047]
For example, I have PageA and PageB, both import CompX.
If I load PageA first, then clik Link to go to PageB, will CompX be loaded from server again?

**Comment by timneutkens** [comment]
Common modules will get chunked together in the commons bundle.

Related: https://github.com/zeit/next.js/pull/941

**Comment by zhaoyao91** [comment]
@timneutkens thanks for this reference. So by the time this pr get merged, we can split out some npm modules to reduce the page size, right?

**Comment by timneutkens** [comment]
@zhaoyao91 right. Right now webpack handles that. But it almost never happens according to Arunoda. After that PR is merged you can define common modules yourself. This will reduce subsequent page sizes like you said.
