### ISSUE TITLE
require('next') not working

### ISSUE THREAD

**Issue by perjg** [zeit/next.js#1048]
npm install next
->installs next@1.2.3

In node REPL:
const next = require('next');
Error: Cannot find module 'next'

This works if I install next@2.0.0-beta.24 instead. Tested on node 6 and node 7.

**Comment by nkzawa** [comment]
It's correct, you need `beta` for that.

**Comment by perjg** [comment]
Is there no plan to fix this for 1.X?

There is no indication in any of the custom-server- examples that they will only work with the beta version.
https://github.com/zeit/next.js/tree/master/examples/custom-server-koa

**Comment by nkzawa** [comment]
@perjg No, since it's a new feature from `beta`. The current master branch including examples is for `beta`. There is a note about that on README.
