### ISSUE TITLE
next.js/examples/with-react-md/ gives checksum invalid error when rendering on client.

### ISSUE THREAD

**Issue by perjg** [zeit/next.js#1049]
Run the with-react-md as described in the README. When loading, it gives a checksum invalid error from React:

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ton></div></header><!-- react-empty: 15 
 (server) ton></div></header><span data-reactid="1

Expected behavior: Examples should show how to use isomorphic rendering properly, and not throw this error.

**Comment by frol** [comment]
Thank you for creating a separate issue. It was already reported in https://github.com/zeit/next.js/pull/940#issuecomment-277028621, and as a result of my investigations I have reported this issue to React-MD upstream: https://github.com/mlaursen/react-md/issues/236

**Comment by perjg** [comment]
@frol Thanks for the explanation.
As far as I can tell, the bug is triggered by NavigationDrawer.DrawerTypes.PERSISTENT_MINI

**Comment by timneutkens** [comment]
Closing this in favor of the upstream ticket.

**Comment by frol** [comment]
@perjg Yes, there is no warning when non-MINI drawer types are used.

**Comment by frol** [comment]
@perjg @alexedev Just for your info, the invalid checksum issue has been resolved in React-MD upstream, which is yet to release with 1.1.x line, but you can try using the master branch (it is quite stable yet the APIs of some components may change a little): https://github.com/mlaursen/react-md/issues/236
