### ISSUE TITLE
Question - Do we need to return doctype when using _document.js

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1054]
Do we need to return doctype when using _document.js

`<!doctype html>` won't work in `_document.js` jsx. Throws error. 

I see that we are appending it in `server/render`. Just want to check that when we use `_document.js` it is being included.

**Comment by nkzawa** [comment]
No, you don't, since with React, you can't create `<!doctype html>`. We automatically append it when you use `_document.js` too.

**Comment by nickdima** [comment]
Is there a way to avoid having the doctype by using a custom Document page?
I'm trying to use Next for rendering just some pieces of static HTML to be used somewhere else so I don't need to specify the doctype.

**Comment by khrome83** [comment]
I  don't think so.
