### ISSUE TITLE
Support for params in routing

### ISSUE THREAD

**Issue by bassbump** [zeit/next.js#1058]
I absolutely love Next and how it provides basic features without the boilerplate that comes with it in a vanilla react app; like server side rendering, webpack, etc..

I get that the creators want to keep its features as "minimal" as possible, but I feel that sometimes really obvious features are skipped too fast.

Parameters in routes is something that pretty much every app needs. If you check the issues it's pretty much the most common asked question. Even though the creators stated their view clearly on this subject multiple times, I still want to publicly voice my opinion that I think it would be greatly beneficial for Next.js that these kind of 99%-of-apps features are "automagically" baked into Next.

If you provide routes as a feature in Next, I feel it kind of makes sense that it support params out of the box.

If we are going to have to create custom packages for all such basic features, it will be just as bad as a vanilla react boilerplate after a while.

**Comment by timneutkens** [comment]
First of all, thank you very much for your feedback 👍 😄 
This issue has been discussed in great length in many threads. See below.
The outcome of every one of them is that you eventually keep coming back to the programmatic api.

https://github.com/zeit/next.js/issues/929
https://github.com/zeit/next.js/issues/291
https://github.com/zeit/next.js/issues/91
https://github.com/zeit/next.js/issues/59
https://github.com/zeit/next.js/issues/25

@fridays made an excellent package for routing using next.js which will most likely suite your needs https://github.com/fridays/next-routes.

**Comment by bassbump** [comment]
I have read every ones of these issues, and I am fully aware of fridays great work with next-routes.
This issue is not about fixing a problem that I can't solve more than it is about a way to voice my opinion to the Next.js community, I feel this should be allowed..

Thus I'm slightly disappointed that it immediately gets closed.

**Comment by timneutkens** [comment]
@bassbump I'm not trying to upset / disappoint you in any way, it's just that this has been discussed many times and in the end we came up with the programmatic api as a solution to fit everyone's application needs.

**Comment by timneutkens** [comment]
cc @arunoda @nkzawa

**Comment by rauchg** [comment]
@bassbump your voice was definitely heard. This is something we'll keep in mind for future releases or improvements to demos, examples, or documentations. Thanks for taking the time

**Comment by arunoda** [comment]
@bassbump custom routing is a pretty cool solution. With out current solution, you could basically use express as a way to define your routes with params. (And any other node server side router)

Here what we providing is a meta routing API. (That's our goal for 2.0)
The reason, it different developers need different routing APIs/solution. Now we live in a SSR, code splitted world. This is the what really works for all now.

Others have experimented different routing and they are pretty good. I also have some cool idea I'll try it out soon. So, that's a benefit of our meta API. If we figure this out, we'll make one of these as the official recommended way in a future release.

> The thing is we've discussed about this a lot in the other issues mentioned by @timneutkens 

We've seen similar ideas. Thanks. It's really great and we love it.
But we need to tackle things one by one.

**Comment by cztomsik** [comment]
BTW: You can do this in nuxt already... just sayin'
https://nuxtjs.org/guide/routing#dynamic-routes
