### ISSUE TITLE
Errors like undefined variable cause 500 in prod

### ISSUE THREAD

**Issue by troywith77** [zeit/next.js#1065]
In production mode, some tiny errors like ```x is undefined``` would throw 500 error, are you guys doing this in purpose? Because I think it is inevitable to avoid any errors, My site crushed for a undefined error.
are there any ways to avoid this?

**Comment by nkzawa** [comment]
It's in purpose. What else do you expect ?

**Comment by nikvm** [comment]
Add a linter like [eslint](https://github.com/eslint/eslint) to your build chain und [disallow undeclared variables](http://eslint.org/docs/rules/no-undef).

**Comment by arunoda** [comment]
It's a widely used best practice (security) to not to expose real error in production. We do this is in the dev mode.

as @nikvm mentioned, you should use a linter like `eslint` or [`standard`](https://github.com/feross/standard).

Just like that, you should capture and inspect production logs as well.
