### ISSUE TITLE
Don't clear terminal history when running `next`

### ISSUE THREAD

**Issue by leo** [zeit/next.js#1070]
The user should still see the history after using `ctrl` + `c` to stop the app.

cc @rauchg

**Comment by thangngoc89** [comment]
I can do this. So I just remove all the code that clear the terminal right? Really frustrating because of this "feature"

**Comment by leo** [comment]
It should be done [like this](https://github.com/zeit/micro/commit/ccd0b1616226e64d1785bb7958d820abbbb877b0).

**Comment by rauchg** [comment]
Yeah, basically we need to change the ANSI escapes friendly webpack plugin uses

**Comment by timneutkens** [comment]
Fixed it locally, works really well, only caveat is that it's dependent on https://github.com/bubkoo/get-cursor-position which has a native module bind. It does have windows support though and is super fast.

**Comment by timneutkens** [comment]
https://github.com/geowarin/friendly-errors-webpack-plugin/pull/18

**Comment by nkzawa** [comment]
@timneutkens `clearConsole: false` is not enough ?

**Comment by timneutkens** [comment]
@nkzawa that will stack the compile messages which turns into quite a mess when you do a lot of changes. Though `clearConsole` is another solution to this issue.
