### ISSUE TITLE
Lighthouse Performance issue

### ISSUE THREAD

**Issue by thomasledoux1** [zeit/next.js#10719]
# Bug report

## Describe the bug

I ran the 'npm run build' command, and then put my site live through 'now' command. When I run a Lighthouse audit on my website, I'm currently getting a performance hit, because of the following: 
"Consider using `<link rel=preload>` to prioritize fetching resources that are currently requested later in page load".
I can see the CSS is being loaded in the <head> tag as follows: <link rel="stylesheet" type="text/css" href="/_next/static/css/styles.282bad2c.chunk.css">. 
Is there a way to "resolve" this performance issue?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://website-thomas.thomasledoux1.now.sh/
2. Run a Lighthouse audit
3. Check the suggestions for Performance

## Expected behavior

With the default 'build' command and setup, I would expect the CSS to be loaded as efficiently as possible.

## Screenshots

https://snipboard.io/HCwVSX.jpg

## System information

- OS: Windows
- Browser (if applies) Chrome
- Version of Next.js: 9.2.2

**Comment by timneutkens** [comment]
Looks like nothing on the page is pre-rendered 🤔 Can you provide a repository.
