### ISSUE TITLE
Non-null initial state example?

### ISSUE THREAD

**Issue by thomaslindstrom** [zeit/next.js#1072]
I'm having a little trouble using custom routing with `app.render` and passing an initial state to it. I read the `with-redux` example, but it assumes an initial `null` state.  

What I'm looking for is some way for some content present on the server to be passed onto `getInitialProps`, and then saved onto the client as “`state`”.

```
const data = require('data.json')

// ...

app.render(req, res, filename, query, {
  state: {data}
})
```

```
export default class extends React.Component {
    static async getInitialProps ({state}) {
        return {state}
    }

    constructor (props) {
        super(props)
        this.state = props.state
    }

    render() {
        return (
            <div>Welcome to {this.props.state.page_title}</div>
        )
    }
}
```

I tried giving the `state` `data` object to the `query` parameter of `app.render` – and while that “worked” (for the initial render, only), it didn't seem to be the preferred way to do this.

Is there another way?

**Comment by thangngoc89** [comment]
@thomaslindstrom AFAIK, app.render only accepts 4 parameters like this 

`async render (req, res, pathname, query) { }`

So I think that you are doing it the right way.

See https://github.com/zeit/next.js/blob/master/server/index.js#L156 for more details

**Comment by thomaslindstrom** [comment]
Yes. My issue is not that `app.render` doesn't, AFAIK. allow me to do what i want to do. It's more a "how do I pass initial state from the server to the client through the server".

**Comment by nkzawa** [comment]
@thomaslindstrom You can pass props and create state from them instead. It's the common way when you use React.

**Comment by thomaslindstrom** [comment]
Where do I pass the props?

**Comment by nkzawa** [comment]
@thomaslindstrom on `getInitialProps`.

```js
const data = require('data.json')
export default class extends React.Component {
    static async getInitialProps () {
        return { data }
    }

    constructor (props) {
        super(props)
        this.state = props.data
    }
}
```

**Comment by thomaslindstrom** [comment]
@nkzawa The data isn't and won't be available in any of the components. I used a `data.json` import for simplicity, but it's an object that gets data from a private socket connection that I can't expose to the client.

I need to be able to do this through the custom routing function.

**Comment by nkzawa** [comment]
@thomaslindstrom Only data you can pass from custom server to component is `query`, others has be fetched on `getInitialProps`. You can check the environment like the following If data is available only on server. 

```js
const isServer = typeof window === 'undefined'
export default class extends React.Component {
    static async getInitialProps () {
        const data = isServer ? require('data.json') : null;
        return { data }
    }

    constructor (props) {
        super(props)
        this.state = props.data
    }
}
```

When you don't want to expose it to client, you'd like to setup the `external` options of webpack.

**Comment by thomaslindstrom** [comment]
As I said, passing data through `query` works but doesn't seem like the way it should be done. For one it's called `query`. But alright, if there's no other way to do this I guess I'll just do it that way.

**Comment by thomaslindstrom** [comment]
Is it out of the question to update the `app.render` method to allow this?

**Comment by nkzawa** [comment]
`query` is basically parsed query strings of urls, so you shouldn't pass something big or non strings.
Other way I just found is to set data to `req` like `req.data = require('data.json')`.

> Is it out of the question to update the app.render method to allow this?

We'd love to consider if it's useful or required. But I still don't know why you need server only data.

**Comment by thomaslindstrom** [comment]
It's not “server only data” – some of it is going to the client – but I have a socket connection on the server that receives objects from an API. Much of the socket data is “private”, so I'm not going to put the socket communication into the app. The objects from the socket contain meta information about what should be rendered.

**Comment by thomaslindstrom** [comment]
Tunneling through `req.data` works, too, but feels very hack-ish. Not more so than doing it through `query`, though, so thanks!

**Comment by nkzawa** [comment]
But then how do you render the component on client ? And `state` is useful only on client so it wouldn't make sent ? Anyway you're trying to do something special, I think we don't want to add a  feature to support it.

Closing for now.
