### ISSUE TITLE
Where to validate route parameters?

### ISSUE THREAD

**Issue by thangngoc89** [zeit/next.js#1073]
So I'm setting up an express server for custom routing. 
Suppose I have a route like this `/u/:username` . After parsing the query param,  I need to hit the database, find that username and decide whether I should render a profile page or an 404 page.

I have 2 places to do the validating in mind: 

- At express server
  
  - Pros: Sending correct HTTP_STATUS code because I can't find a way to send 404 status within the React app
  - Cons: Hit the database server twice because in the client side, I need extra information rather than just a validated username to render the page. Query all of the data in the express server and sending it via `ctx` would be super complicated. For clarification, I'm using Apollo Client for managing the data. 

- At React app
  - Pros: Hit the database server only one
  - Cons: Improper HTTP_STATUS code, complex error handling. (well, try catch everywhere! OMG)

**Comment by nkzawa** [comment]
https://github.com/zeit/next.js/issues/746#issuecomment-274850407 is the way we recommend.
Additionally, you can import the default error page as `next/error` and use it for rendering from the next release.

**Comment by thangngoc89** [comment]
@nkzawa oh nice. Thank you. I was worry for a while before posting the above post. Putting the logic in express mean I have to keep the code in sync manually.
