### ISSUE TITLE
getInitialProps for components deeper in the tree

### ISSUE THREAD

**Issue by michalwerner** [zeit/next.js#1074]
Is it somehow possible to use `getInitialProps` in components that are not the page itself?

I mean that for example we have `Index` component which is page. It renders `SomeSection` component and I would like `SomeSection` to use `getInitialProps`.

After few tests I assume that it remains unknown for next that `SomeSection` defines `getInitialProps`, am I right?

**Comment by nkzawa** [comment]
You have to define `getInitialProps` on the top level component, and pass down props to descendant components.

**Comment by iaincollins** [comment]
@michalwerner

So to be clear, if you have a page like this:

**pages/index.js**:

```javascript
export default class extends React.Component {
  render() {
    const myPropVar = "myPropValue"
    return(
      <div>
        <MyComponent myProp={myPropVar}/>
      </div>
    )
  }
}
```

You can have a component like this:

**components/my-component.js**:
```javascript
export default class extends React.Component {

  // You don't need to declare this but you can access props here
  constructor(props) {
    super(props)
    console.log(props.myProp)
  }

  // You can't have async calls in constructor() or render() but you can in these methods
  async componentWillMount() {} // Before rendering (server+client)
  async componentDidMount() {} // After rendering (client only)
  async componentWillReceiveProps(nextProps) {} // When new props are sent (before rendering)
  
  render() {
    return(
      <p>
        {{this.props.myProp}}
      </p>
    )
  }
}
```

There's more on this at https://facebook.github.io/react/docs/react-component.html

**Comment by sedubois** [comment]
You can make those react lifecycle methods async but that's dangerous because it won't wait for the promises to be resolved.

**Comment by iaincollins** [comment]
The best place for async operations is componentDidMount() - that's in fact the intent of it (as per the docs) - but you can also kick them off in componentWillMount(), if it doesn't impact rendering.

**Comment by michalwerner** [comment]
I know I can do it in lifecycle methods, but cDM won't happen on server and cWM only may happen. I was thinking about utilizing next features. 
Given it doesn't seem to be possible I ended up using `getInitialProps` on top level and passing data down to component that actually use it.
