### ISSUE TITLE
<Link> retains query string if href pathname is equal to current pathname

### ISSUE THREAD

**Issue by eezing** [zeit/next.js#1079]
Context:

starting url = `myapp.com/about?foo=bar`
click `<Link href="/"><a>home</a></Link>`
result url = `myapp.com`

vs

starting url = `myapp.com?foo=bar`
click `<Link href="/"><a>home</a></Link>`
result url = `myapp.com?foo=bar`

I would expect the latter to behave like the former. Thoughts?

**Comment by arunoda** [comment]
Yeah! I think we need to do something about this.
In this case, we need to change the URL.

**Comment by timneutkens** [comment]
I'll fix it 🙌🏻

**Comment by timneutkens** [comment]
@eezing just tested, I can't reproduce what you're seeing.

```
import Link from 'next/link'
import Head from 'next/head'
import React from 'react'

export default class extends React.Component {
  static async getInitialProps ({ query: { id = 0 } }) {
    return { id }
  }

  render () {
    console.log(this.props.id)
    return (
      <div>
        <Link href="/?id=1"><a>id 1</a></Link>
        <Link href="/"><a>home</a></Link>
        <h1>{this.props.id}</h1>
      </div>
    )
  }
}
```

**Comment by timneutkens** [comment]
I've also added some tests for this in #1084 just in case.

**Comment by eezing** [comment]
@timneutkens I jumped the gun on this one. It was a bug on my end. Should have done my due diligence by testing in a fresh project before posting. Sorry for waisting your time. Thanks for your prompt response.

**Comment by timneutkens** [comment]
@eezing cool, Well now this case is tested too, so if we break it in the future we'll know 😉 Thanks for checking ❤️
