### ISSUE TITLE
Is it possible to use styled-components with Next.js?

### ISSUE THREAD

**Issue by Ajar-Ajar** [zeit/next.js#1082]
[Styled-components](https://github.com/styled-components/styled-components) look like the next CSS-Modules
It works amazingly well with react and has many many advantages.
I think this is WAY better then using JS CSS' watch this [demo ](https://www.youtube.com/watch?v=qu4U7lwZTRI)to get a closer look
Will Next.js support this kind of solution to style react components?

**Comment by rovansteen** [comment]
There's an official example of using `styled-components` with next.js [here](https://github.com/zeit/next.js/tree/master/examples/with-styled-components).
Note that this uses 2.0 beta version.

**Comment by Ajar-Ajar** [comment]
Awesome news!
Any word on when version 2 will finally be released?

**Comment by timneutkens** [comment]
@Ajar-Ajar not yet. We'll keep you posted ❤️
