### ISSUE TITLE
Parameterized Routing deploy with Now

### ISSUE THREAD

**Issue by atilafassina** [zeit/next.js#1086]
Hello everybody,

As Parameterized Routing is something discussed extensively in a number of other issues, I apologize in advance if I failed to find a similar problem.

I've trying to deploy one testing app wrote with Now and deploy (`next start` , really) has been breaking regardless of my attempts.

I created a simple multi-page app with 3 routes, 2 of them are *parameterized routings* following the [example on the repository](https://github.com/zeit/next.js/tree/master/examples/parameterized-routing) with a custom server, while the 3rd is just a regular page.

Issue happens when I run the `now` command, the `require('next')` breaks accusing module to not be found. 

btw, app works fine on my local server, no issues.

Said testing app can be found at the following repository: [next-seo-test](https://github.com/atilafassina/next-seo-test)

Thanks in advance for the help.

**Comment by timneutkens** [comment]
I'll have a look when I get home 👍🏻

**Comment by ericf** [comment]
@atilafassina you have an older version of `next` in your `yarn.lock` file:
https://github.com/atilafassina/next-seo-test/blob/master/yarn.lock#L1800

**Comment by atilafassina** [comment]
oh crap!
totally overlooked that...

<img src="https://media.giphy.com/media/3xz2BLBOt13X9AgjEA/giphy.gif" width="200" />

thanks @ericf
