### ISSUE TITLE
Running `git push` triggers reloading

### ISSUE THREAD

**Issue by nkzawa** [zeit/next.js#1087]
reported by @rauchg

**Comment by timneutkens** [comment]
@nkzawa @rauchg just tried, can't reproduce 🤔, can you give some context.

What a did was:
1. run `next` inside a next.js project
2. change a file and commit it
3. push it to a remote repository

**Comment by rauchg** [comment]
Can't reproduce. Fake news by @rauchg

**Comment by timneutkens** [comment]
👍
