### ISSUE TITLE
Latest beta breaks the using-router example

### ISSUE THREAD

**Issue by svnlto** [zeit/next.js#1089]
Just bringing this to your attention.
I've followed the `using-router` example and get the following error:

```bash
Uncaught Error: No router instance found.
You should only use "next/router" inside the client side of your app.
```

and current usage is like so, from a `Link` component.

```js

import React, { PropTypes } from 'react';
import Router from 'next/router';

const onClickHandler = (href) => {
  return (e) => {
    e.preventDefault();
    Router.push(href);
  };
};

const Link = ({ children, href, ...props }) => (
  <a  href={href} {...props} onClick={onClickHandler(href)}>
    {children}
  </a>
);

Link.propTypes = {
  href: PropTypes.string,
  children: PropTypes.array.isRequired
};

export default Link;

```

I've seen some commits that change the router api. So this isn't really a surprise.

A documentation update would be nice tho :)

**Comment by svnlto** [comment]
I don't understand how #1094 is fixing this. I have a babelrc file that I'm using 

```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    "transform-decorators-legacy"
  ]
}

```

**Comment by arunoda** [comment]
That shouldn't be a problem.
What you might have something different.
Send us a sample repo (as an new issue)
