### ISSUE TITLE
Bundle some files only server-side

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1091]
I'd like to load i18n messages for a specific locale from some file, but only server-side. I would then pass it client-side as return value from `getInitialProps`. The issue is that if I just load them with something like:
```js
let messages;

getInitialProps(ctx) {
  if (!process.browser) {
    messages = require(`./intl/${locale}`); // eslint-disable-line global-require
  }
  return { messages };
}

constructor(props) {
  super(props);
  if (props.messages) {
    messages = props.messages;
  }
}

render() {
  return <IntlProvider messages={messages} />;
}
```

webpack will still also bundle the message files client-side despite being in an `if (!process.browser) {}`. This is problematic when there are many languages and messages, just makes commons.js bigger than it needs to be. (also, it might even bundle some unwanted files as it just matches the './intl/*' pattern).

How can I cleanly ensure that some files are only bundled server-side?

The with-intl PR https://github.com/zeit/next.js/pull/1055 loads the messages from an external API, but I'm trying to see if that's really necessary.

**Comment by arunoda** [comment]
I think we don't have something official way here. But I hope we could do this with a simple webpack config.

Introduce a webpack alias for those modules to load a fake module.

**Comment by sedubois** [comment]
In the above linked example is show the idea to use require.resolve, like:
```js
const messageFile = require.resolve(`../data/intl/${locale}`);
const messages = require('fs').readFileSync(messageFile, 'utf8');
```

But `require('fs')` yields `This dependency was not found in node_modules: fs`, even though this is executed server-side. @ericf works around that by putting that code in `server.js` instead of in some page, but again IMHO that's only a workaround (as he points out here: https://github.com/zeit/next.js/issues/860#issuecomment-277859684).

Technically, a custom server shouldn't be needed for this, and it prevents co-locating the logic within one HOC.

**Comment by nkzawa** [comment]
You can use custom webpack config and the externals option of webpack `https://webpack.js.org/configuration/externals/`

**Comment by sedubois** [comment]
I tried to add a dummy `fs` as follows:
```js
module.exports = {
  webpack: (config) => {
    config.externals = {
      fs: 'fs',
    };
    return config;
  },
};
```

Then I put this in my withIntl.js HOC:
```js
  static async getInitialProps(ctx) {
    if (!process.browser) {
      locale = getLocale(ctx);
      const messageFile = require.resolve(`../data/intl/${locale}.json`);
      messages = JSON.parse(readFileSync(messageFile, 'utf8'));
      ...
    }
    ...
  }
```

But it yields `Uncaught ReferenceError: require is not defined`.

**Comment by sedubois** [comment]
I also tried to stub using an existing module name, e.g `config.externals = { fs: 'react' }` (don't know if there's a better way), but it still yields the same error about `require`.

**Comment by nkzawa** [comment]
> messages = JSON.parse(readFileSync(messageFile, 'utf8'));

How did you define `reaFileSync` ?

**Comment by sedubois** [comment]
I used `import { readFileSync } from 'fs';`, but I get the same error with `const { readFileSync } = require('fs');`

**Comment by nkzawa** [comment]
I think you need to `require` it only on server ? You can't use `import` to do this.

```js
if (isServer) {
  const { readFileSync } = require('fs')
}
```

**Comment by sedubois** [comment]
Ah OK. I thought the webpack config would allow to import anywhere, it would just return a dummy value browser-side.

It works, thanks 👍
