### ISSUE TITLE
why webpack alias doesn't work as expected in nextjs? 

### ISSUE THREAD

**Issue by videni** [zeit/next.js#10929]
# Bug report

## Describe the bug

webpack alias doesn't work as expected . I created an descussion [here](https://github.com/zeit/next.js/discussions/10917), but I think this might be a bug, because it did work a few days ago.

## To Reproduce

I created a demo [here](https://github.com/videni/nextjs-examples.git)

## Screenshots

![image](https://user-images.githubusercontent.com/4058341/76298670-cc754080-62f4-11ea-8d5c-eb0014ab56cc.png)

**Comment by Exelord** [comment]
I did this in next config:
```
const config = {
  webpack(config) {
    config.resolve.alias[package.name] = path.resolve(__dirname, 'src');
    return config;
  }
};
```

So then I can import using by app name `import Input from 'my-app/components/input'`

**Comment by JazibJafri** [comment]
You also need to add it to tsconfig.json. You are using typescript with next.js. I got it working like this
My tsconfig.json
```
"baseUrl": ".",
"paths": {
     "@": ["src/"],
     "@/*": ["src/*"],
 }
```
My next.config.js webpack
```javascript
config.resolve.alias['@'] = path.join(__dirname, 'src')
```

Removing one or the other breaks it.

**Comment by videni** [comment]
@JazibJafri, it works,  thanks a lots.

**Comment by Exelord** [comment]
https://github.com/zeit/next.js/pull/11293
This will solve your issue better :)

**Comment by jesseaborden** [comment]
@Exelord You just saved me a whole lot of strife. Thannnnnk ya!

**Comment by dinesh-rapidops** [comment]
Thanks @Exelord , it really helped a lot !!!
