### ISSUE TITLE
Enable babel-plugin-transform-react-jsx-source on development

### ISSUE THREAD

**Issue by nkzawa** [zeit/next.js#1097]
https://babeljs.io/docs/plugins/transform-react-jsx-source/

**Comment by arunoda** [comment]
I think we've an issue for this already: https://github.com/zeit/next.js/issues/764

**Comment by arunoda** [comment]
BTW: It was assigned to me. It'll be great, if someone could work on this.

**Comment by timneutkens** [comment]
I'll do it @arunoda
