### ISSUE TITLE
Start testing Fiber

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#1098]
`react@16.0.0-alpha.2`
`react-dom@16.0.0-alpha.2`

We'll need to use the following:
`require('react-dom/fiber')`

**Comment by rauchg** [comment]
Here's an example on how to opt into low priority updates:
https://github.com/facebook/react/blob/master/examples/fiber/index.html#L136

**Comment by ravikiran438** [comment]
React 16 Beta is out now for public testing.

https://github.com/facebook/react/issues/10294

**Comment by sergiodxa** [comment]
I just tried Next.js with React 16 Beta and it throw this error.

![image](https://user-images.githubusercontent.com/1312018/28644197-360c2164-721e-11e7-813c-0fdd39d9e2a5.png)

It looks like Next.js is using a internal lib and React 16 doesn't expose them anymore.

**Comment by gaearon** [comment]
Yes, nothing in `/lib/` will be exposed in 16. Happy to discuss specific use cases for internals in https://github.com/facebook/react/issues/10294.

**Comment by arunoda** [comment]
@gaearon Thanks.
We've a PR for this: https://github.com/zeit/next.js/pull/2570/files

Basically we want to track errors happening inside the component.
In the ^^ above PR, is uses some method in Fiber.

Is that the way we should do it?

**Comment by arunoda** [comment]
@gaearon I started it here: https://github.com/zeit/next.js/pull/2659
Let me know I'm doing it good here.

**Comment by gaearon** [comment]
Seems reasonable to me. Note that this isn’t supported on server side yet (but normal `catch` works for it).

**Comment by arunoda** [comment]
Yeah! I got that. (Actually, that's good in a sense)
We've already catch errors on the server. So, I hope we are good to go.

**Comment by jamonholmgren** [comment]
This also happens when trying to switch to Preact (and using [the example](https://github.com/zeit/next.js/tree/v3-beta/examples/using-preact) provided).

```
 ERROR  Failed to compile with 1 errors                                                                                      7:40:58 PM

This module was not found:

* react-dom/lib/ReactReconciler in ./~/next/dist/client/next-dev.js

To install it, you can run: npm install --save react-dom/lib/ReactReconciler
> Ready on http://localhost:3000
```

**Comment by dmt-13** [comment]
So React 16 is out now, any updates about it? Because I still have an error: 
```
* react-dom/lib/ReactReconciler in ../node_modules/next/dist/client/next-dev.js

To install it, you can run: npm install --save react-dom/lib/ReactReconciler
```

**Comment by bntzio** [comment]
Yeah me too @dmt-13

**Comment by jesseditson** [comment]
@dmt-13 and @bntzio : as per latest README (not sure when it was updated), you'll either need to use `next@beta` to use react 16+, or if you want to use stable next, install react and react-dom `@15` (`npm i next react@15 react-dom@15` or `npm i next@beta react react-dom`)

**Comment by bntzio** [comment]
Yep, I just got it working, you need:

* react@16.0.0
* react-dom@16.0.0
* next@4.0.0-beta.2

**Comment by damusnet** [comment]
FYI, I just tried to update our app from Next.js 2.0 / React 15 to Next.js 4.0 / React 16, and except for a [few warnings](https://github.com/facebook/react/issues/1253#issuecomment-333067616) related to SSR / Client rehydration (on very edge cases, not critical at all), everything worked perfectly!

So, thank you to all contributors, this is amazing!

**Comment by timneutkens** [comment]
@damusnet great to hear ❤️ Closing this ticket 👍

**Comment by brendonco** [comment]
@timneutkens  Have you tried in IE11?
