### ISSUE TITLE
Support SASS

### ISSUE THREAD

**Issue by Robinfr** [zeit/next.js#110]
Is there any possibility to support SASS?

**Comment by dlindenkreuz** [comment]
This would be solved by allowing custom webpack configs (see #40). You'd then be able to use [sass-loader](https://github.com/jtangelder/sass-loader).

**Comment by Robinfr** [comment]
Alright, sounds good! I searched for SASS but couldn't find anything, hence this issue.

Op 27 okt. 2016 7:01 p.m. schreef Daniel Lindenkreuz <notifications@github.com>:

This would be solved by allowing custom webpack configs (see #40<https://github.com/zeit/next.js/issues/40>). You'd then be able to use sass-loader<https://github.com/jtangelder/sass-loader>.
