### ISSUE TITLE
Uncaught Error: No router instance found.

### ISSUE THREAD

**Issue by svnlto** [zeit/next.js#1100]
#1089

```bash
Uncaught Error: No router instance found.
You should only use "next/router" inside the client side of your app.
```

Sample Repo: [here](https://github.com/svnlto/svenlito.com/blob/next/components/Link.js)

**Comment by arunoda** [comment]
Hey thanks.
But I can't run the error.

It's kind a great, if we can have a isolated issue for this case. Then it saves everyone's time and we could have a look at more issues.

**Comment by svnlto** [comment]
I've tried to deploy this to `now` but having trouble with the installation there. But I've noticed when running `next build && NODE_ENV=production next start` locally the router seems to behave as intended.

**Comment by MarcMagnin** [comment]
that is weird, I got the same issue too. How can we make it work running dev?

**Comment by noway** [comment]
Instead of running global `next` which doesn't pick up localy installed npm packages run `npm run dev`

fixed for me

**Comment by nrako** [comment]
I ran through the same error while `npm linking` a package which had `next` as a dependency. Turns out the error goes away if the package is not linked. @noway's answer brought me to that direction!

**Comment by lancejpollard** [comment]
Running into this too, related to https://github.com/zeit/next.js/issues/3108 linking packages.

**Comment by spktklr** [comment]
Ran into this not having used `getInitialProps` on the page where the component was mounted.
