### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by BjoernRave** [zeit/next.js#11027]
When trying to import `@uppy/webcam` in next.js, so React with SSR, I get the following error: `ReferenceError: navigator is not defined`

This is my code

```
import Uppy from '@uppy/core'
import { Dashboard } from '@uppy/react'
import Webcam from '@uppy/webcam'
import { FC } from 'react'

const Upload: FC<Props> = ({ name }) => {
  const uppy = Uppy().use(Webcam)

  return <Dashboard uppy={uppy} plugins={['Webcam']} />
}

export default Upload

interface Props {
  name: string
}

```

**Comment by Rohitkrops** [comment]
@BjoernRave this is because the `navigator` object is present in browsers not in the node. To resolve your issue make sure to user Uppy once your component is mounted.
