### ISSUE TITLE
http-proxy-middleware can't handle POST request in next.js

### ISSUE THREAD

**Issue by yjisme** [zeit/next.js#11037]
> next.js version: 9.3.1-canary.1

I want to build middle tier server with next.js, so it must proxy all request with `api/*`.

To achieve this, I add file `pages/api/[...args].js` to an empty project, and write these simple code:

```js
import { createProxyMiddleware } from "http-proxy-middleware";
export default createProxyMiddleware({
  target: "http://yuanjin.tech:5100", //the data server
  changeOrigin: true
});
```

After testing, all get requests works well, but all POST requests has problems

```shell
# get request workds well
GET http://localhost:3000/api/movie
```

```shell
# post request has problems
POST http://localhost:3000/api/user/login
BODY loginId=xxx&loginPwd=xxx

# console info
API resolved without sending a response for /api/user/login, this may result in stalled requests.
```

When this error occurs, my data server does not actually receive any requests

Then i have found any request with body has same problem, even GET request

I don't know why the proxy request can't reach the data server, did i miss something?

**Comment by timneutkens** [comment]
Please don't double-post, only post in GitHub Discussions if you're posting a question. Answered here: https://github.com/zeit/next.js/discussions/11036
