### ISSUE TITLE
Changes not reflecting in env-config.js (universal-configuration)

### ISSUE THREAD

**Issue by nahue** [zeit/next.js#1103]
After making necessary changes to my app (following the universal-configuration example) i have this env-config.js

```javascript
const prod = process.env.NODE_ENV === 'production';
let backendURL;

if ('ENVIRONMENT' in process.env) {
  if (process.env['ENVIRONMENT'] === 'staging') {
    backendURL = 'http://stagingurl.example.com';
  } else {
    backendURL = 'http://localhost:5000';
  }
} else {
  backendURL = prod ? 'http://prod.example.com' : 'http://localhost:5000';  
};

module.exports = {
  'process.env.BACKEND_URL': backendURL
}
```

So if i run `yarn run build` i should get prod.example.com.
But if i run `ENVIRONMENT=staging yarn run build` should be stagingurl.example.com but hey NO! still prod.example.com, so frustating that i had to hardcode values to get it running in production till i figure this one out 😞 .

I've noticed that the only way this could change is by running `yarn clean` before each command. Seems like this is being cached and fails to update. Any thoughts?

**Comment by timneutkens** [comment]
Hmmmmm this is most likely due to babel-loader's caching behaviour. https://github.com/babel/babel-loader#options

cc @arunoda

**Comment by nahue** [comment]
oh ok so ill make a npm task to remove that cache before building.. that should do it at least for now

**Comment by timneutkens** [comment]
@nahue you can actually do this by using `next.config.js`:
```
module.exports = {
  webpack: (config, { dev }) => {
    // Perform customizations to config
    config.module.rules = config.module.rules.map(rule => {
      if(rule.loader === 'babel-loader') {
        rule.options.cacheDirectory = false
      }
      return rule
    })
    // Important: return the modified config
    return config
  }
}

```

**Comment by xekri** [comment]
I have the same problem with babel-plugin-inline-react-svg, which changes don't reflect in svg files.
Instead of disabling `cacheDirectory` option of babel-loader, I use `rimraf` package to remove any caches of babel-loader:
```json
"scripts": {
    "build": "rimraf node_modules/.cache/babel-loader && next build"
  }
```

**Comment by sedubois** [comment]
About env vars, also see https://github.com/zeit/next.js/issues/1488#issuecomment-289108931, allows to set up env vars at runtime
