### ISSUE TITLE
The Next Serverless Framework

### ISSUE THREAD

**Issue by mhrisse** [zeit/next.js#1104]
Hi!

Suppose I cannot use ```now``` for my project, but would like to ideally use Serverless Framework (www.serverless.com) with NextJS to deploy to AWS Lambda or later Google Cloud Functions or Microsoft Azure.

Anyone tried that yet?

**Comment by arunoda** [comment]
Since it's a node app it should be possible to do it. One thing you need to do it to run `next build` before pushing the code into the serverless env.

**Comment by rauchg** [comment]
This is not really related to Next.js. Please see the Deployment section in README
