### ISSUE TITLE
Latest code from examples  does not work

### ISSUE THREAD

**Issue by Mirodil** [zeit/next.js#1107]
I've got latest code from git/repo and try to run/start code in `custom-server-koa` folder. When I run application with `npm run dev` or with `next build`, I always get the following error:

```
 babel [BABEL] unknown: Generation end +1ms
{ Error: ./pages/a.js?entry
Module build failed: SyntaxError: Unexpected token (1:21)

> 1 | export default () => <div>a</div>
    |                      ^
  2 | 

Error
...
```

**Comment by arunoda** [comment]
This is because we've not released a new beta for the latest code. Let's do it.

**Comment by codyloyd** [comment]
ah.. I just upgraded to the latest beta (2.0.0.25) and I'm getting the same error in my code.  Am I doing something wrong here?  Should I target an earlier beta?

**Comment by timneutkens** [comment]
@codyloyd can you check the version in `./node_modules/next/package.json` Works for me with beta 25

**Comment by codyloyd** [comment]
@timneutkens yep.  can see the package.json _and_ the error in the screenshot.
![2_009](https://cloud.githubusercontent.com/assets/18574792/22897130/2c4abf70-f1e8-11e6-8028-dfacadf35653.png)

**Comment by arunoda** [comment]
@codyloyd May be this is something related to your `babelrc`. Send us the related `.babelrc` file. You see a note on which one we are using while starting the app.

**Comment by codyloyd** [comment]
```
{
  "presets": ["es2015"]
}
```

**Comment by arunoda** [comment]
@codyloyd okay.
I hope we could close this issue.
