### ISSUE TITLE
Preserving glamor rehydration

### ISSUE THREAD

**Issue by finneganh** [zeit/next.js#1108]
I’ve seen that glamor is deprecated, but I’d like to continue using it because I prefer its interface to styled-jsx. I notice that in next 2 glamor is still available, in particular there’s rehydration of glamor IDs in the client startup code.

Is glamor support going to be preserved? Or, if it’s removed, will there be a hook to apply rehydration before components are imported?

**Comment by nkzawa** [comment]
Eventually, glamor will be removed but you can still use it by setting custom document like https://github.com/zeit/next.js/tree/master/examples/with-glamor.

**Comment by finneganh** [comment]
That doesn't take into account the hydration step that needs to run on the client before components are imported.

**Comment by nkzawa** [comment]
I think it's doable, though you manually have to implement. It seems we should update the example to show how to do it.

**Comment by finneganh** [comment]
I think the tricky bit is getting a hook into the client startup code. Is
that available now?

On Mon, Feb 13, 2017 at 12:42 PM, Naoyuki Kanezawa <notifications@github.com
