### ISSUE TITLE
Support SEO optimizable routes with dynamic routing

### ISSUE THREAD

**Issue by BramDecuypere** [zeit/next.js#11171]
# Feature request

## Is your feature request related to a problem? Please describe.

What I'm trying to accomplish is with dynamic routing have a substructure as so:

Full path - for each subroute we would need a seperate page (specific page component as well)
`/[lang]/[overview-slug]/[brand]/[model]/[id]`
- Note that overview-slug is language specific

`/nl/overzicht`
`/nl/overzicht/audi`
`/nl/overzicht/audi/a3`
`/nl/overzicht/audi/a3/12430213-123-123123-123`

## Describe the solution you'd like

previous question

## Describe alternatives you've considered

Used to work with `next-routes`, but currently unable to export

## Additional context
Basic repository for reproduction: 
https://github.com/lizy-lab/lizy-basic-project

**Comment by timneutkens** [comment]
No question is asked 🤔 What's outlined works totally fine with dynamic routes.
