### ISSUE TITLE
CHANGELOG or github releases' details

### ISSUE THREAD

**Issue by iamstarkov** [zeit/next.js#1119]
there are two issues regarding CHANGELOG file:

* #180 is closed with updates to old releases and it was okay at that time.
* #303 with discussions about automated releases.

Anyway, right now its a problem to discover changes between releases. What should we do? (until solution to #303 is landed)

**Comment by arunoda** [comment]
We do GitHub releases, but not between beta changes.

**Comment by iamstarkov** [comment]
okay, got it. let me note, its difficult to decide whether do i need to update from beta-18 to beta-25

**Comment by arunoda** [comment]
@iamstarkov Basically you need to use the latest beta. We are fixing issues and building essential features (not usually public APIs)
