### ISSUE TITLE
link & router using "window.location.origin": IE11 incompatible

### ISSUE THREAD

**Issue by eezing** [zeit/next.js#1120]
References to [window.location.origin](http://devdocs.io/dom/htmlhyperlinkelementutils/origin) found in two places. window.location.origin doesn't exists in IE11.

[This](https://github.com/zeit/next.js/blob/master/lib/link.js#L87) in link:
```javascript
export function isLocal (href) {
  const origin = window.location.origin
  return !/^(https?:)?\/\//.test(href) ||
    origin === href.substr(0, origin.length)
}
```

[This](https://github.com/zeit/next.js/blob/master/lib/router/router.js#L286) in router:
```javascript
function getURL () {
  const { href, origin } = window.location
  return href.substring(origin.length)
}
```

IE11 compatible replacement:
```javascript
const origin = window.location.protocol + '//' + window.location.hostname + (window.location.port ? ':' + window.location.port: '')
```

We can either polyfill window.location.origin (not a huge fan of polyfills) or replace the line in both chunks.

**Comment by arunoda** [comment]
Okay. That's good.
Send a PR.

Add a common function inside the `lib` to do this.

**Comment by eezing** [comment]
@arunoda will do

**Comment by timneutkens** [comment]
Maybe implement https://www.npmjs.com/package/location-origin
