### ISSUE TITLE
Module not found: Error: Cannot resolve module 'next/document'

### ISSUE THREAD

**Issue by manuelro** [zeit/next.js#1123]
The framework accomplishes a very important milestone: server and client rendering with a single code base, which is great. However, while trying to create a custom `<Document>` I receive the following error:

`Module not found: Error: Cannot resolve module 'next/document'`

I just copy-pasted the sample code in the README file.

```
// ./pages/_document.js
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  static async getInitialProps (ctx) {
    const props = await Document.getInitialProps(ctx)
    return { ...props, customValue: 'hi there!' }
  }

  render () {
    return (
     <html>
       <Head>
         <style>{`body { margin: 0 } /* custom! */`}</style>
       </Head>
       <body className="custom_class">
         {this.props.customValue}
         <Main />
         <NextScript />
       </body>
     </html>
    )
  }
}
```

Is `next/document` bundled with the framework or is this an optional module? Any ideas? The Link and the other components are working fine.

NPM version: 3.10.9
Node version: v6.9.2

**Comment by arunoda** [comment]
I think you need to install the `beta` version of Next.js
Make this as the version of your package.json `^2.0.0-beta.25`

**Comment by manuelro** [comment]
Thanks. It seems to be working now.

**Comment by manuelro** [comment]
Installing this beta version solved the document issue, but presented more bugs. Is there any stable, production-ready version to use in a real-world project that can deliver up to IE11 without breaking anything else?
