### ISSUE TITLE
SSR caching combined with user-specific data

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1128]
Based on the ssr-caching example, I got SSR caching working properly when the user is logged out of my webapp (https://github.com/relatenow/relate). But when I log in and get redirected to the home page, the user data should appear in the page header but doesn't, as it renders the version which was cached when the user was logged-out. 

What would be the recommendation here? To have a separate cache for each and every user, and invalidate this user cache on login/logout?

**Comment by sedubois** [comment]
I have a similar issue regarding localization: when the user selects an alternative locale, page is reloaded from server but still serves the contents with original locale.

**Comment by sedubois** [comment]
I tried to change the cache key from `req.url` to:
```js
function getCacheKey(req) {
  return `${req.url}-${JSON.stringify(req.session.user)}`;
}
```

https://github.com/relatenow/relate/commit/82b8f811f78ad65cd1e52b73989b7fe84b24d3f9

But I'm still caching the page in the wrong locale.

**Comment by khrome83** [comment]
I have not done this, but I think it may be better to just not cache the part of the content that has user info.

For example, there is the progressive rendering example - 
https://github.com/zeit/next.js/tree/master/examples/progressive-render

Let's say you had a login box, that was replaced with the "Welcome Steve" message. Maybe wrap that in the progressive-render, or even a client side only render. Then your client does the logic. Just a thought. Not sure how well that will play with SSR caching.

**Comment by sedubois** [comment]
@khrome83 thanks, but that would basically mean I can't cache at all at the HTML level, so the server-side performance bottleneck would remain. I still hope to fix the issue (maybe I'm just doing something wrong).

**Comment by sedubois** [comment]
OK, my issue with locale refreshing was unrelated to the LRU HTML caching, but to my locale-specific cache 😄 I updated my code: https://github.com/relatenow/relate/commit/1d2ff0aa31c327fc74414f006715b1290d329a09

So it seems like changing to the key mentioned above works (for now at least, until something else outside of the session might influence the page appearance).
