### ISSUE TITLE
Example with custom webpack config

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1130]
I might have missed it, but didn't find an example showing the use of custom webpack config (except for the short snippet in the README). I'm trying to figure out how to stub 'fs' client-side so that I can still require that module server-side (https://github.com/zeit/next.js/issues/1091).

**Comment by albinekb** [comment]
Does this do: https://github.com/zeit/next.js/blob/master/examples/with-webpack-bundle-analyzer/next.config.js

It shows how you can set custom options to webpack @sedubois

**Comment by sedubois** [comment]
Yes that's a start 👍 Would be worth linking from the README section on custom webpack config then. @timneutkens
