### ISSUE TITLE
Style doesn't apply to h1, h2 after `npm run build`, while `npm run dev` works fine.

### ISSUE THREAD

**Issue by amio** [zeit/next.js#1132]
Here is the `pages/index.js`:
```javascript
export default () => (
  <div>
    <h1>h1</h1>
    <h2>h2</h2>
    <div>div</div>
    <style jsx>{`
      h1 {
        background: red;
      }
      h2 {
        background: red;
      }
    `}</style>
  </div>
)
```

https://fe-lenses-glbdtdmunb.now.sh/

While, the same code renders correctly in dev mode(`npm run dev`):
![image](https://cloud.githubusercontent.com/assets/215282/22932645/a7152882-f303-11e6-9f41-ec53269762f2.png)

**Comment by sedubois** [comment]
I experience similar symptoms as reported on Slack, so it prevents me from deploying latest changes: https://zeit-community.slack.com/archives/next/p1487081460009945

**Comment by timneutkens** [comment]
Might be fixed by https://github.com/zeit/next.js/pull/1114

**Comment by sedubois** [comment]
@rauchg could we please have a release? 😄

**Comment by rauchg** [comment]
Btw: volunteers are currently being sought for writing a script that we can run in CI that automatically publishes next to npm as `beta` every time we merge a PR whose tests passed

**Comment by timneutkens** [comment]
@rauchg I'll add it to my list of things 😉

**Comment by amio** [comment]
@sedubois Temporally I use [plain old React styles](https://github.com/amio/fe-lenses/commit/26f1011ff7ef62e8f41a67c3a5da9f4b331f702b#diff-e14ec8fd2b038fbccea5f8090d26ace4) to avoid this problem, you may have a try too.

**Comment by sedubois** [comment]
@amio it seems fixed for me with latest release: https://relate.now.sh/ 🎉

**Comment by timneutkens** [comment]
👍
