### ISSUE TITLE
Document next/error

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1134]
I don't think it's documented anywhere?

Also (unrelated to title, sorry), I guess it doesn't support any kind of message localization.

**Comment by arunoda** [comment]
Yeah! Let's add it.

**Comment by nikvm** [comment]
Isn't `next/error` just the default error page exported by `pages/_error.js`? It can be overwritten with a custom `_error.js` and is documented in [`README.md`](https://github.com/zeit/next.js#custom-error-handling).

Or am I missing something :confused:?

**Comment by timneutkens** [comment]
@nikvm https://github.com/zeit/next.js/pull/1040

**Comment by nikvm** [comment]
Yay, thanks! It's on the list. 🗒

**Comment by timneutkens** [comment]
Thank you very much @nikvm 👍

**Comment by timneutkens** [comment]
@nikvm added the in progress label.

**Comment by timneutkens** [comment]
Something like this should suffice.
```js
import React from 'react'
import Error from 'next/error'
import fetch from 'isomorphic-fetch'

export default class Page extends React.Component {
  static async getInitialProps () {
    const res = await fetch('https://api.github.com/repos/zeit/next.js')
    const statusCode = res.statusCode > 200 ? res.statusCode : false
    const json = await res.json()
    return { statusCode, stars: json.stargazers_count }
  }

  render () {
    if(this.props.statusCode) {
        return <Error statusCode={this.props.statusCode} />
    }

    return (
      <div>Next stars: {this.props.stars}</div>
    )
  }
}
```
