### ISSUE TITLE
Avoid deleting .next directory on build

### ISSUE THREAD

**Issue by thomaslindstrom** [zeit/next.js#1135]
To minimize service downtime, is it possible to avoid removing the `.next` directory on build? I get a good 1 minute of “Internal Server Error” when deploying, depending on the server.

https://github.com/zeit/next.js/blob/master/server/build/index.js
https://github.com/zeit/next.js/blob/master/server/build/clean.js

The current (now old) state of the app should be able to stay active until the new state is ready to be started. Would it be an idea to compile the resources into `.next-enifu723`, and then, when ready, rename it to replace `.next`? That way it won't affect the current directory, which may be used in the current app.

**Comment by nkzawa** [comment]
I think I don't fully understand how you deploy your apps, but usually you should just swap your servers with new ones, then deleting `.next` should not be a problem and there is no downtime.

**Comment by thomaslindstrom** [comment]
In this scenario I'm using `pm2` to deploy and manage my application. On deploy, an execution script fires that looks something like:

```
next build && pm2 restart client
```

Yet, during the time it is building the new version, the current one stops working because it removes some required `dist/` files and such.

**Comment by nkzawa** [comment]
Avoiding deleting `.next` directory wouldn't help since your app might load building state of `.next` anyway.
I think you should change how to deploy your app.

**Comment by thomaslindstrom** [comment]
No? If `next.js` built the new resources in a separate directory, this approach would work just fine.

**Comment by nkzawa** [comment]
Ah, that would work in most cases but I think there is downtime between moving two folders and restarting servers.  btw I'm assuming the problem occurs because next.js server dynamically load files according to page requests. I'm not sure if it's worth to support that.

**Comment by thomaslindstrom** [comment]
Downtime while renaming the two folders <<<<<<<<< downtime while building the new state.

**Comment by thomaslindstrom** [comment]
I'll do a PR on this, I guess, where `next build` builds the new state in a separate directory (`.next-12313`) before replacing `.next`.

**Comment by thomaslindstrom** [comment]
@nkzawa Maybe this makes the problem I'm outlining more clear: https://github.com/zeit/next.js/pull/1139

**Comment by thomaslindstrom** [comment]
Merged. https://github.com/zeit/next.js/pull/1139#event-962264425
