### ISSUE TITLE
Next Export Watch

### ISSUE THREAD

**Issue by nahtnam** [zeit/next.js#11360]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to develop a chrome extension using Next.js. The majority of development can be done with `next dev` and loading the webpage, however to access chrome extension-specific APIs you will need to export the app and open the dist folder as an extension in chrome. Every time you make a change you can to recompile the whole app.

## Describe the solution you'd like

It would be nice if we could have a command: `next export --watch` or something similar

## Describe alternatives you've considered

Current building with Create React App

**Comment by timneutkens** [comment]
We're not planning to support building chrome extensions at this point in time.

Same as https://github.com/zeit/next.js/issues/7315

**Comment by karellm** [comment]
@timneutkens Is there any update on this? I'm also wondering about using Next for a webextension.
