### ISSUE TITLE
Reload when clicking a link of current url

### ISSUE THREAD

**Issue by nkzawa** [zeit/next.js#1137]
It gets ignores for now, but we have to perform the equivalent of `location.reload()`

- `getInitialProps`
- trigger router events
- possibly unmounting / remounting

**Comment by arunoda** [comment]
Is this the exact same URL?
Then the routes should be idempotent.
There will be definitely an other way to do what we are doing.

**Comment by nkzawa** [comment]
The idea is to emulate the browser behavior by @rauchg . I think it makes sense since you might want to recall `getInitialProps` and reset `state` even if it's a same route.

**Comment by arunoda** [comment]
Okay. Then it's about removing [these lines](https://github.com/zeit/next.js/blob/master/lib/router/router.js#L153-L158).
@nkzawa That's it right?

**Comment by nkzawa** [comment]
@arunoda I think so.

**Comment by arunoda** [comment]
@nkzawa let me work on it.
