### ISSUE TITLE
Different babel config on server and client?

### ISSUE THREAD

**Issue by devmetal** [zeit/next.js#114]
Hi, this is just a question, but i thinking about new node LTS version that support so many es6 features. Actually we have a new preset for this: https://github.com/Salakar/babel-preset-node6, i not say this is the best, but i will be so happy if i can set a different babel config for server and client. Also it has a batter performance i think. Can i do this right now somehow, or it will be a feature?

**Comment by devmetal** [comment]
Noboby like to use different babel presets on server and client, or just server production?

**Comment by nkzawa** [comment]
You mean the babel config of next source right ? I think it would be worth to do.

**Comment by devmetal** [comment]
Thank you :) I mean the code of application that we write. So if i use in my code features like arrow method, const, let etc.. and i use node6.x i do not want to transpile the es6 code on server side, because the most a features is aviable native. I think that i want is related other issues with custom webpack config. The difference is, i think its enough for me, to set custom babel config for server and client side.

**Comment by nkzawa** [comment]
No, you can't do that for now.

Basically, all application codes are used on both client and server.
So if we want to separate the config of babel, we have to compile a same code twice.
I'm not sure if it's worth to do for now. At least, we should measure how fast app becomes if supported.

**Comment by pavel06081991** [comment]
Are you planning to add this feature? To have two separate configs would be great.

**Comment by arunoda** [comment]
Currently this is not possible by default. By you can tweak our babel custom config and experiment as you like.
