### ISSUE TITLE
Issues with context & styled-components in node module

### ISSUE THREAD

**Issue by rovansteen** [zeit/next.js#1144]
I'm running in to an issue where I am using a private node module that contains small components that use styled-components and expect a theme to be set by the package that includes it. This was working fine in `next@2.0.0-beta.17` but after upgrading to beta 26 it stopped working. The theme passed in to the component from the external package is just empty.

I've tried to reproduce this outside my project but failed to do so because it works fine when you define the components that use the theme _inside_ the project itself. I've narrowed it down to a specific version, it works in beta 18 but breaks in beta 19. I've tried looking at the [changes](https://github.com/zeit/next.js/compare/2.0.0-beta.18...2.0.0-beta.19) made in that release but couldn't find anything that would explain this.

Do you might have an idea what's changed that would have this effect?

**Comment by arunoda** [comment]
Try to reproduce it with the npm modules. You can install npm modules locally with `file://<path-to-module-dir>` (Doesn't work with yarn)

Those paths can be relative urls as well.
With this, we may could see the real problem.

**Comment by rovansteen** [comment]
I've been digging in the code of styled-components a bit and I think the issue is related with context. It subscribes to a "channel" on the context named `__styled-components__` but that appears to be missing in the component loaded from my private npm module.

So basically [this](https://github.com/styled-components/styled-components/blob/ab229c80b5671e7f22cdb5c40b50c4ee64d897f8/src/models/StyledComponent.js#L48) if statement fails, and then it looks for a theme passed in as prop, which is obviously not there, resulting in an empty theme.

Did the bump from beta18 to beta19 caused any changes to the context that could cause this?

**Comment by timneutkens** [comment]
@rovansteen https://github.com/zeit/next.js/commit/8b94534260d7589482c844758117415936fa0996 this was added in beta.19. I'm not sure if it is related. But there were some fixes on it since then. So could you please try the latest beta?

**Comment by rovansteen** [comment]
@timneutkens unfortunately it's still broken. I've tried something simple with the styled-components example in the repo and it breaks when you add a theme. I created a separate issue for that https://github.com/zeit/next.js/issues/1416 I hope that fixing that also fixes this problem.

**Comment by rovansteen** [comment]
Closing this for now because I am not able to setup a minimal reproduction of the issues I ran into. Might try `next.js` for this project later, keep up the good work!
