### ISSUE TITLE
link to future directions in README

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1152]
Don't know if important, but there's a half-broken link at bottom of https://zeit.co/blog/next:

https://github.com/zeit/next.js/blob/master/README.md#future-directions

There's no section future-directions in the README.

**Comment by timneutkens** [comment]
cc @nkzawa could you update the blog? ❤️

**Comment by nkzawa** [comment]
Thanks for the report ! It's going to be fixed on the next release of our website 👍
