### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1153]
I'm not familiar at all with HTTP/2, but it's advertised as being a great improvement to HTTP/1.1 (e.g in the Zeit Now docs). 

So does Next.js support HTTP/2? Does something need to be configured? Should it be added to the docs? Is it automagically happening when deploying a Next.js app to Now? What about localhost development? 

I don't see HTTP/2 locally (running my app with `yarn dev`: https://github.com/relatenow/relate):

<img width="982" alt="screen shot 2017-02-15 at 14 46 43" src="https://cloud.githubusercontent.com/assets/4217871/22975066/e0697c20-f38d-11e6-8908-83a9e3f5abca.png">

**Comment by sarukuku** [comment]
HTTP/2 in most browsers works only over https so if you're f.ex. using Chrome on local dev machine you'd have to configure your dev to use SSL. Also it needs to be configured / enabled on the server side too and this depends of the server you're using.

**Comment by sedubois** [comment]
OK indeed, the version deployed on Now seems to use HTTP/2:

<img width="1074" alt="screen shot 2017-02-15 at 16 37 26" src="https://cloud.githubusercontent.com/assets/4217871/22978894/26c8fb64-f39d-11e6-96c6-43119bcabb19.png">

**Comment by timneutkens** [comment]
@sedubois when you run your app on `now` it will handle your requests using http2 automatically 😄 👍. We don't have to change anything next.js side for this. For other hosting solutions you might want a proxy in front of your app that handles http2.

**Comment by timneutkens** [comment]
Lol, didn't see your comment before submitting.

**Comment by Faradey27** [comment]
@timneutkens what about http2 push? can i use it with nextjs?

**Comment by oliviertassinari** [comment]
Right, can't we use HTT2 push to increase time to interaction? Using script preload is already a nice improvement.
```html
<link rel="preload" />
```
But can't we make it so we don't event have to wait for the HTML to be parsed by the browser to start loading the initial scripts?
![capture d ecran 2018-05-04 a 10 49 35](https://user-images.githubusercontent.com/3165635/39619635-df23d4a2-4f88-11e8-83fb-ee428055be26.png)

**Comment by Faradey27** [comment]
@sedubois can we re-open issue?

**Comment by timneutkens** [comment]
We already add `<link rel="preload" />`. There's no need to re-open this issue. If you want to implement server push inside Node.js you can create a custom server to handle this.

**Comment by oliviertassinari** [comment]
@timneutkens Still, can't we make the client download the JavaScript while the server is generation the page? Right now, one has to happen after the other. It could easily save 100ms for first visits.

**Comment by timneutkens** [comment]
We should probably create a new feature request for investigating the `Link` header yeah.

```
Link: https://example.com/other/styles.css; rel=preload; as=style`
```
