### ISSUE TITLE
how to supply a proxy in next

### ISSUE THREAD

**Issue by thisguychris** [zeit/next.js#116]
say if I wanted to proxy a 3rd party api?

**Comment by nkzawa** [comment]
You can run a server which proxy 3rd party API with cors enables.
We're working on #25 which will support this too.

**Comment by thisguychris** [comment]
@nkzawa thank you for your response.  From what I understand, the code that we'll be adding for that proxy is only on the server side and not on the client side?

**Comment by Alireeezaaappp** [comment]
tnx
