### ISSUE TITLE
Hapi example broken: inconsistent server promises

### ISSUE THREAD

**Issue by finneganh** [zeit/next.js#1170]
It looks like #1099 left Hapi in a broken state with main.js and common.js modules. The various `render*` methods in server/index.js are inconsistent about whether they return a promise, so what’s happening now is that the `defaultHandlerWrapper` is closing the response before the `renderStatic` method actually renders anything, since it returns `void` without any `await`.

Note the ”Content-Length: 0“
<img width="600" alt="screen shot 2017-02-15 at 8 08 49 pm" src="https://cloud.githubusercontent.com/assets/260837/23002767/99dd0c40-f3ba-11e6-810a-287d26eb4d02.png">

My proposed fix for this, which I can put a PR together for, is to make sure (and document and/or test) that all the methods of `Server` are consistently returning promises that don’t resolve until they have written their complete output.

**Comment by rauchg** [comment]
Sounds good. Apologize for merging a bad example. My knowledge of Hapi is limited

**Comment by rauchg** [comment]
@finneganh I added you as a collaborator in case you want to own all the Hapi-related PRs

**Comment by finneganh** [comment]
I'm not much of an expert but I'm willing to take a look at them.

**Comment by finneganh** [comment]
@rauchg Looks like the Hapi change wasn't itself the problem, it was the Hapi change followed by the removal of Gzip. 

Fix available in #1172, which tries to be defensive against async things not being captured going forward.
