### ISSUE TITLE
Feature Request: Use the filesystem as server API

### ISSUE THREAD

**Issue by mingfang** [zeit/next.js#1171]
Enrouten (https://github.com/krakenjs/express-enrouten) is an express module that automatically route requests based on the filesystem.  Using this creates a nice synergy with using the filesystem to route pages.

**Comment by rauchg** [comment]
You can use this in combination with `node server`. No need to bundle! Express example:
https://github.com/zeit/next.js/tree/master/examples/custom-server-express

**Comment by mingfang** [comment]
I know that. I was making a case that something like enrouten should be made default.
I've never had an issue closed so fast on github.
Your behavior is making be reconsider supporting this project.

**Comment by arunoda** [comment]
@mingfang we've discussed a lot related to this here: https://github.com/zeit/next.js/issues/25
So, instead building this we went with this: https://github.com/zeit/next.js/issues/291

Docs: https://github.com/zeit/next.js#custom-server-and-routing

We suggest to build these features in the userland won't be available in the core.

**Comment by mingfang** [comment]
@arunoda I tried searching the issues before posting but missed the ones you sent. Thanks.
