### ISSUE TITLE
Add option to prefetch props via <Link> component

### ISSUE THREAD

**Issue by ads1018** [zeit/next.js#1175]
Per @rauchg's [suggestion](https://github.com/zeit/next.js/issues/740#issuecomment-272947691), this option should be explicit:
```javascript
<Link prefetchProps={true} />
```
Adding the ability to prefetch props has some seriously cool implications, the most obvious being that it essentially sounds the death knell for loading indicators.

![high-five-cat_o_646881](https://i1.wp.com/cdnjs.cloudflare.com/ajax/libs/galleriffic/2.0.1/css/loader.gif)

**Comment by gmaliandi** [comment]
Hi! We just [blogged about a way of doing this](https://www.scaleapi.com/blog/increasing-the-performance-of-dynamic-next-js-websites) by adding a caching layer and calling `getInitialProps` when prefetching a page.

**Comment by timneutkens** [comment]
@gmaliandi lets add it to the readme under FAQ 😄

**Comment by ads1018** [comment]
Brilliant!

**Comment by gmaliandi** [comment]
And today we published this in NPM: [data-prefetch-link](https://www.npmjs.com/package/data-prefetch-link)!

**Comment by timneutkens** [comment]
Going to close this issue. Core support is not needed thanks to @gmaliandi's brilliant work 👍
