### ISSUE TITLE
[RFC] Improve testing

### ISSUE THREAD

**Issue by sakulstra** [zeit/next.js#1186]
Hello,
currently we have a lot of examples(37 as for today) without any tests in the codebase which break from time to time. As most people will probably try to get started with one of the examples this is suboptimal.

I'd like to help improve this, but i'm not quiet sure where/how to start. We could probably add render tests to check if the application renders without errors for all the examples, but then we had to run yarn install/npm build 37+ times and we would still only catch "big errors" ;)? Any ideas? Eventually this doesn't make sense at all and we should better just improve the core tests? e.g. add tests for react-patch?

**Comment by arunoda** [comment]
@sakulstra This is a good point. I think we could simply use our core test tooling for this.
See the `test` directory of these apps: https://github.com/zeit/next.js/tree/master/test/integration

One question is this might actually slow down the test time. One option is to use travis's parallel testing. (With diff env vars)

**Comment by timneutkens** [comment]
I'm going to close this due to inactivity. One thing Arunoda and me talked about is moving the examples into their own repository.
