### ISSUE TITLE
Allow 'getStaticProps' and 'getServerSideProps' on the same page

### ISSUE THREAD

**Issue by abidk** [zeit/next.js#11919]
At the moment it's not possible to use getStaticProps and getServerSideProps on the same page. It would appear you have to use getStaticProps and then do client side requests to handle the dynamic data.

I think there is a valid use case, where you want to build a page with initial static data and then allow SSR on page requests where the data is dynamic.

**Comment by timneutkens** [comment]
Sounds like you're asking for https://github.com/zeit/next.js/discussions/11552 instead.
