### ISSUE TITLE
Dynamic API routes cannot be called in 'getServerSideProps'

### ISSUE THREAD

**Issue by abidk** [zeit/next.js#11921]
It's not possible to calling dynamic api routes in 'getServerSideProps'. A 404 error is returned instead.

Steps to reproduce:
1. Create an /api/products/data.js etc.
2. Call endpoint 'http://locahost:3000/api/products/data' in getServerSideProps.
3. 404 returned

Calling the api endpoint in a browser works as expected.

**Comment by paales** [comment]
`getServerSideProps` already runs on the server, maybe you can call that code directly?
