### ISSUE TITLE
Styled-components v2 requires an update to the example

### ISSUE THREAD

**Issue by mschipperheyn** [zeit/next.js#1192]
The api for styled components has changed in v2.

    import Document, { Head, Main, NextScript } from 'next/document';
    import styleSheet from 'styled-components/lib/models/StyleSheet';

    export default class MyDocument extends Document {
      static async getInitialProps ({ renderPage }) {
        const page = renderPage();
        const style = styleSheet.getCSS();
        return { ...page, style };
      }

      render () {
        return (
          <html>
              <Head>
                  <title>My page</title>
                  <style dangerouslySetInnerHTML={{ __html: this.props.style }} />
              </Head>
              <body>
                  <Main />
                  <NextScript />
              </body>
          </html>
        )
      }
    }

**Comment by timneutkens** [comment]
Someone already made a PR to upgrade to v2. https://github.com/zeit/next.js/pull/1038. Lets track changes around v2 there.
