### ISSUE TITLE
Suggestion for with-redux example: using higher-order component to replace repeated codes.

### ISSUE THREAD

**Issue by huzidaha** [zeit/next.js#1193]
The [example](https://github.com/zeit/next.js/tree/master/examples/with-redux/pages) of next.js with redux has repeated codes in every page, but wouldn't it be better to use higher-order component to replace this kind of repeated codes. For example:

next-connect.js:

```javascript
import React, { Component, PropTypes } from 'react'
import { Provider, connect } from 'react-redux'
import { createStore, applyMiddleware } from 'redux'
import thunkMiddleware from 'redux-thunk'
import reducer from './reducer'

let store = null

const wrapWithProvider = (PageComponent) => class extends Component {
  static propTypes = {
    initialState: PropTypes.object
  }

  static async getInitialProps (ctx) {
    const { req } = ctx
    const isServer = !!req
    const props = PageComponent.getInitialProps ? await PageComponent.getInitialProps(ctx) : {}
    if (isServer && typeof window === 'undefined') {
      store = createStore(reducer, {}, applyMiddleware(thunkMiddleware))
      props.initialState = store.getState()
    }
    return props
  }

  constructor (props) {
    super(props)
    if (!store) {
      store = createStore(reducer, props.initialState, applyMiddleware(thunkMiddleware))
    }
  }

  render () {
    return (
      <Provider store={store}>
        <PageComponent {...this.props} />
      </Provider>
    )
  }
}

export default (mapStateToProps, mapDispatchToProps) => (PageComponent) => {
  PageComponent = connect(mapStateToProps, mapDispatchToProps)(PageComponent)
  return wrapWithProvider(PageComponent)
}
```

In every page you can easily use next-connect.js and connect to store like using redux normally:

index.js:

```javascript
import nextConnect from './next-connect'

class Index extends Component {
  // ...
  render () {...}
}

export nextConnect((state) => state, null)(Index)
```

You can gain the same abilities like `with-redux` example does but with convenience.

Just a suggestion, feel free to close.

**Comment by huzidaha** [comment]
And considering this kind of higer-order component might be commonly used in every next.js project, I wonder if it's a good idea to make it a next.js third-part library?

**Comment by katopz** [comment]
I think @borellvi and @arunoda try to [keep it same as `mobx` example](https://github.com/zeit/next.js/pull/691)
Maybe you could try PR as `with-redux-thunk` instead.

**Comment by huzidaha** [comment]
It's still simple (event simpler). It just changed the code structure of the original version of `with-redux` example. They're aim for the same purpose. @katopz

**Comment by katopz** [comment]
@huzidaha I know it's easy and made sense and it's a way to go for real life using but in case you introduce another dependency `redux-thunk` so it should be more clear to new comer if it present separately as `with-redux-thunk`.

And also FYI : https://github.com/zeit/next.js/pull/1196
BTW don't get me wrong I like your example and really hope it get PR in somewhere. :)

**Comment by huzidaha** [comment]
@katopz Actually `thunk` thing was copied from the `with-redux` example :P https://github.com/zeit/next.js/blob/master/examples/with-redux/store.js . I just wanted to keep it same as original version.

Seems that somebody has made this idea out as a library. https://github.com/kirill-konshin/next-redux-wrapper just after a few hours after this issue.

**Comment by huzidaha** [comment]
OMG, he has a quick hand...

**Comment by timneutkens** [comment]
cc @kirill-konshin

**Comment by huzidaha** [comment]
I actually want to make a PR. But I am wondering if it's polite to replace his example...

**Comment by huzidaha** [comment]
I create a PR https://github.com/zeit/next.js/pull/1201 which uses the package [next-connect-redux](https://github.com/huzidaha/next-connect-redux) I am working on and it's base on the idea above.

I will finish the docs of [next-connect-redux](https://github.com/huzidaha/next-connect-redux) as soon as possible.

**Comment by kirill-konshin** [comment]
`next-connect-redux` actually makes exactly the same thing as `next-redux-wrapper` that was merged yesterday. Same ideas are flowing in the air.

@huzidaha it's pure coincidence, I haven't seen this issue before today, I was working on my stuff for last couple of days, and as you see, I use slightly different approach.

https://github.com/huzidaha/next-connect-redux/blob/master/lib/index.js#L15 you have a bug on this line because redux will ignore default state coming from reducer, default state has to be undefined.

Also where is the store memoization, so that on a client there will be just one instance? Have you tested it?

**Comment by huzidaha** [comment]
@kirill-konshin I am really sorry for the misunderstanding. And thank you for the suggestions. :P

**Comment by rauchg** [comment]
@kirill-konshin the PR description referencing the issue made me think his implementation _predated_ yours. I will revert.

**Comment by rauchg** [comment]
Also, maybe to have the best of both worlds, @kuzihada, you can PR later a little note on the README saying that there's another package available and link to yours ?

**Comment by rauchg** [comment]
@kirill-konshin apologize for the confusion

**Comment by kirill-konshin** [comment]
No worries.

**Comment by huzidaha** [comment]
@rauchg I really appreciate for that.
