### ISSUE TITLE
Syntax error on eval-script.js (22,1) for IE11

### ISSUE THREAD

**Issue by manuelro** [zeit/next.js#1207]
There is a syntax error in one of Next's dependencies. The file's name is `eval-script.js` and is located at `next/dist/lib/eval-script.js`. This only happens on IE11 and previous versions. 

The code this is prompting as buggy is at line 22 of the aforementioned file.
```
function evalScript(script) {
  var module = { exports: {} };

  eval(script); // eslint-disable-line no-eval
  return module.exports;
}
```

Next version: `next@^2.0.0-beta.25`

Any ideas how to make this IE11 compatible?

**Comment by khrome83** [comment]
Have you tried a more recent version to see if the error still exists?

**Comment by manuelro** [comment]
I've updated Next package to `2.0.0-beta.31` but the error persists.

**Comment by timneutkens** [comment]
cc @arunoda @nkzawa I wonder if we should even do that eval in production mode.

**Comment by arunoda** [comment]
@timneutkens with the current setup we've to use eval. But I'd like to use something different is later versions.

**Comment by timneutkens** [comment]
Okay 👍🏻

**Comment by timneutkens** [comment]
Closing this in favor of #1301
