### ISSUE TITLE
uWebSockets as HTTP interface

### ISSUE THREAD

**Issue by flagello** [zeit/next.js#1214]
According to https://github.com/uWebSockets/uWebSockets/issues/397#issuecomment-277237968, `uws.http` is considerably faster than `http`.

<br>

> <img src="https://github.com/uWebSockets/uWebSockets/raw/master/images/wrk_benchmark.png">
> 
>
> [`uWebSockets/blob/master/nodejs/http_sillybenchmark.js `](https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/http_sillybenchmark.js)
> [`uWebSockets/blob/master/nodejs/http.js`](https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/http.js)
> 
> Performance is still very good as long as writeHead is not called in a hot path (this function is very slow). If you only res.end('some data here'); you get 230k requests per second.
> 
> from https://github.com/uWebSockets/uWebSockets/issues/397#issuecomment-275276648

<br>

Currently and only in [v.0.13.0a6](https://github.com/uWebSockets/uWebSockets/releases/tag/v0.13.0a6) (since a1). Near drop-in replacement for Next's use case? May need to be tested and benchmarked in a production environment.

**Comment by arunoda** [comment]
Could you tell me where exactly you suggest to use this?

**Comment by arunoda** [comment]
Anyway, since do support [custom servers](https://github.com/zeit/next.js#custom-server-and-routing) I hope this is doable in the userspace.

**Comment by flagello** [comment]
[master/server/index.js#L4](https://github.com/zeit/next.js/blob/master/server/index.js#L4)

from

```JavaScript
import http, { STATUS_CODES } from 'http'
```

to

```JavaScript
import http, { STATUS_CODES } from 'uws.http'
```

It could indeed be a user choice, but if the benchmarks get confirmed, the transition is seamless, and it doesn't cause significant maintenance overhead, why not?

**Comment by flagello** [comment]
[v.0.13.0 was released the other day.](https://github.com/uWebSockets/uWebSockets/releases/tag/v0.13.0) @arunoda Could you reopen the issue to allow for a thorough evaluation?
