### ISSUE TITLE
Cannot read property 'Component' of undefined if error occurs in componentDidMount

### ISSUE THREAD

**Issue by kandros** [zeit/next.js#1216]
i had a call to an undefined function inside of componentDidMount. it errors `Cannot read property 'Component' of undefined` instead of notify that the function is undefined

also a  manual throw an error inside componentDidMount shows `Cannot read property 'Component' of undefined`

**Comment by timneutkens** [comment]
Duplicate: https://github.com/zeit/next.js/issues/1061. Was fixed yesterday :smile:
