### ISSUE TITLE
Difference between directory Bundles and dist?

### ISSUE THREAD

**Issue by lenny0702** [zeit/next.js#1217]
Since I wanna write some my own logic in custom web pack file, I need to know the basic file flow of original web pack config

I found out that there will be a abc.json and also a abc.json, in Bundles and Dist directory separately. take "abc" is a module for example. What's their difference? Thanks!

**Comment by arunoda** [comment]
bundles has files the different entrypoints in your app (basically pages) which is loaded by the browser dynamically.

dist directory has those pages for the use of SSR.

**Comment by lenny0702** [comment]
Thanks! @arunoda 
I have two last question:
1. Whicn lines of code of webpack.js in build directory are to config the compilation of the xxx.json file in Bundles directory?
2. If I want to write my own webpack.js with original function , Do I have to copy the original content of webpack.js?

**Comment by arunoda** [comment]
1. That's [this](https://github.com/zeit/next.js/blob/master/server/build/plugins/json-pages-plugin.js)
2. Not sure about it.

**Comment by lenny0702** [comment]
Thanks so much!  @arunoda
