### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#1218]
This is due to a Promise not resolving error when doing the routing.
See:

![screen shot 2017-02-20 at 9 00 17 pm](https://cloud.githubusercontent.com/assets/50838/23131406/e131fe5e-f7af-11e6-9eb9-dfdecece16df.png)

This is we are running our `shared_modules` example.

**Comment by timneutkens** [comment]
Duplicate #975 @arunoda

**Comment by arunoda** [comment]
Oh! Sure it is.

**Comment by timneutkens** [comment]
@arunoda We have so many issues, it's easy to create a duplicate 😉
