### ISSUE TITLE
Get browserstack account for Next.js

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#1219]
Would be neat to quickly try out issues in IE.
https://www.browserstack.com/pricing

**Comment by arunoda** [comment]
I didn't notice there's a FREE plan for OSS.
@rauchg any thoughts on this?

**Comment by fabienheureux** [comment]
Saucelabs a free OSS plan:
https://saucelabs.com/open-source

**Comment by eezing** [comment]
Microsoft provides free to use VM images for testing IE: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by fabienheureux** [comment]
Saucelabs is really great to setup automated tests, you can set them up using JS (I think like CasperJS, never used this one), and it runs automatically, can make diff based on screenshots etc. 
I have not used it a lot, but felt really powerful and quite easy to use

**Comment by vernondegoede** [comment]
@arunoda Browerstack does offer free OSS plans.
