### ISSUE TITLE
<Link> manipulating history even clicking the same one

### ISSUE THREAD

**Issue by nodegin** [zeit/next.js#122]
Hello, I found that `<Link>` is manipulating browser history even clicking the same link.

For example I have the link `<Link href="/test">Go test</Link>` which appears in path `/` and `/test`, then if I click this link within `/test` page, it will also pushes itself to browser history, where native `<a>` will not act like this.

Is there any solution in order to prevent this weird behavior?

**Comment by nkzawa** [comment]
That sounds a bug. I think `<Link />` should behave like `<a/>`.
