### ISSUE TITLE
Use TypeORM with Next.js

### ISSUE THREAD

**Issue by jmaister** [zeit/next.js#12254]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to configure TypeORM in server.js
When I run the server (node server.js), as the entities are defined in TypeScript, there is an error:

    import {createConnection} from "typeorm";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

## Describe the solution you'd like

I would like to have a better way to initialize other libraries that I use along with Next.js instead of writing my own server.js.

Define the convention of a file in JS or TS for initializations.

## Describe alternatives you've considered

I tried to create the connection on every place that I use the database connection.

**Comment by timneutkens** [comment]
If you want to create API endpoints it's recommended to use API routes: https://nextjs.org/docs/api-routes/introduction. API routes are automatically compiled through Next.js' compilation pipeline and allow you to use import/export syntax and a bunch of other syntax that hasn't landed in Node.js yet, similar to pages.

If you use a custom server you're basically handing off a request to Next.js and Next.js is unaware of the server existing, it also boots up after the server boots up, meaning we can't compile the server, hence why you can only use Node.js features and Node.js currently does not compile `import` syntax.

**Comment by jmaister** [comment]
Definitely, I don't want to use the custom server, I want to keep all Next.js functionality as it is now.

Adding the connection code to the api-routes makes me to create a new connection on each of the API calls. And that is something I would like to avoid.

**Comment by timneutkens** [comment]
> Adding the connection code to the api-routes makes me to create a new connection on each of the API calls. And that is something I would like to avoid.

**Comment by jmaister** [comment]
Sorry, I can't find how to define the connection in the global scope in Next.js documentation.

**Comment by timneutkens** [comment]
Something like this:

```
// lib/db.js
function setupConnection(username, password) {
  return db.initialize(username, password)
}

export default setupConnection('hello', 'world')

```

```
// pages/api/user.js
import connection from '../../lib/db'

export default () => {
  const result = await connection.query(`SELECT * FROM 'hello_world'`)
}
```

**Comment by kandros** [comment]
> > Adding the connection code to the api-routes makes me to create a new connection on each of the API calls. And that is something I would like to avoid.
> 
> If you add it in the global scope it's not re-initialized except for if you use serverless functions (eg when hosting on Vercel).

for some reasons I always believed the same as @jmaguirrei, that /api routes were always treated as target serverless and would not share execution context, (thus being unable to share a DB connection)

well I'm happy to discover I was wrong 
here's a little example 
https://github.com/kandros/nextjs-api-routes-demo

**Comment by jmaister** [comment]
Not sure why this happens but queries only work for the first request, the next request fail of finding the Typescript classes.

    RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?
        at new RepositoryNotFoundError (C:\workspace\fcputbol\node_modules\typeorm\error\RepositoryNotFoundError.js:11:28)
        at EntityManager.getRepository (C:\workspace\fcputbol\node_modules\typeorm\entity-manager\EntityManager.js:660:19)
        at Connection.getRepository (C:\workspace\fcputbol\node_modules\typeorm\connection\Connection.js:343:29)
        ...
