### ISSUE TITLE
Heroku: Warning: No build cache found. Please configure build caching for faster rebuilds.

### ISSUE THREAD

**Issue by TheoMer** [zeit/next.js#12286]
# Bug report

## Describe the bug

I'm receiving the above mentioned error message when deploying a build to heroku. I've checked the docs at [No Cache Detected](https://github.com/zeit/next.js/blob/master/errors/no-cache.md) but no configuration is available for heroku. 

How do I resolve this?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. git subtree push --prefix app-name master

## Expected behavior

Builds are currently taking an inordinate amount of time to complete. I expected the deploy to build without errors.

## System information

- OS: Windows 10 Pro
- Version of Next.js: 9.3.5

**Comment by Timer** [comment]
https://devcenter.heroku.com/articles/nodejs-support#custom-caching
