### ISSUE TITLE
Please tone down the error screen

### ISSUE THREAD

**Issue by christiannaths** [zeit/next.js#123]
Beauty is in the eye of the beholder, unfortunately my retinas are burned out...

Seriously though, is it a jerk move to ask for some basic accessibility on the error screen? This is "exceptionally" hard on the eyes (pun intended). After only second or two on this screen, my vision is temporarily discoloured, making it hard to work. Happy to do a PR if I get a thumbs-up from a maintainer.

![screen shot 2016-10-27 at 8 47 04 pm](https://cloud.githubusercontent.com/assets/11584/19793047/e78b1bce-9c87-11e6-9cde-8c053025453b.png)

**Comment by nodegin** [comment]
Just did some modification

![](https://cloud.githubusercontent.com/assets/8536244/19793434/31915b44-9cff-11e6-85bb-6d63b4bb86df.png)

**Comment by christiannaths** [comment]
Wups, just did a PR. Either yours or mine is much better 👍

**Comment by christiannaths** [comment]
Closed mine in favour of yours. Thanks!!!

**Comment by nkzawa** [comment]
👍  I think it's reasonable. 
@rauchg thought ?

**Comment by rauchg** [comment]
Responded in the PR. Very reasonable
