### ISSUE TITLE
Use developit/unfetch as our fetch implementation

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#1241]
See: https://github.com/developit/unfetch

**Comment by impronunciable** [comment]
Does @developit think that `unfetch` is solid enough now?

**Comment by developit** [comment]
2.0 should be out today, which fixes cors+credentials and some other stuff.  It's definitely solid enough to use, just you have to decide if you need to polyfill `Headers` and `Request`, or just the typical `fetch()` interface.

**Comment by arunoda** [comment]
> if you need to polyfill `Headers` and `Request`
@developit that means?

**Comment by developit** [comment]
Unfetch only polyfills `fetch()` and uses plain objects to do so. If you're manually working with other fetch-related APIs like `new Headers().set('foo', 'bar')`, it won't work.  It's a minimal implementation only of the `fetch()` functionality.

**Comment by arunoda** [comment]
@developit got it.
I think we don't (and not expecting) to use them.

**Comment by developit** [comment]
Most people find that to be true :)

**Comment by developit** [comment]
I released 2.0.0 last night, which has a polyfill entry.

**Comment by impronunciable** [comment]
Thanks @developit for the lib and the comments :) We'll try to merge the pr soon
