### ISSUE TITLE
Next.js/Webpack unable to resolve linked module

### ISSUE THREAD

**Issue by vernondegoede** [zeit/next.js#1244]
As discussed in Zeit's community Slack, I tried to locally link a module (using both Yarn and NPM). When I try to import this module in my Next.js project, I get the following error:

```
ERROR  Failed to compile with 1 errors                                                                                                             13:36:21

This dependency was not found in node_modules:

* hedron

Did you forget to run npm install --save for it?
```

After a quick discussion with @timneutkens it seems like this error is being thrown by the Webpack plugin that checks dependencies. 

If someone could point me in the right direction I could try to fix this one myself.

**Comment by impronunciable** [comment]
@vernondegoede I put together a [silly example](https://dron-eqsnclsxld.now.sh) using hedron along with next.

it seems to be working as expected and you can [see the code](https://dron-eqsnclsxld.now.sh/_src/?f=package.json).

Maybe it has something to do with your specific project, in that case sharing a snippet of your app would be helpful.

**Comment by arunoda** [comment]
Thanks @impronunciable.
@vernondegoede send us a sample repo and re-open if you didn't find @impronunciable 's example helpful.

**Comment by dcalhoun** [comment]
@impronunciable @arunoda I'm attempting to use a `yarn link` module in a Next.js 5 project and hitting this issue as well. The referenced example links are now dead. Was there a specific resolution to using a linked module within Next?
