### ISSUE TITLE
Feature request: Add support for hosted fonts

### ISSUE THREAD

**Issue by siddharthkp** [zeit/next.js#1248]
Ref: https://github.com/KyleAMathews/typefaces

Need to add font loader in webpack config

**Comment by sedubois** [comment]
You can customize the webpack config yourself?

**Comment by siddharthkp** [comment]
@sedubois Can, but it would be cool if next has in built support.

What do you think?

**Comment by sedubois** [comment]
I believe Next.js' aim is to be minimalistic. Specific custom webpack config can be done by each user according to their specific needs.

**Comment by siddharthkp** [comment]
Sure, that makes sense

**Comment by tlvenn** [comment]
Could someone share a snippet on how to actually do that ? Thanks
