### ISSUE TITLE
Module Loader with Config

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1252]
How do I do this, and is it possible or needed?

```
{
    module: {
        loaders: [{
            test: /\.json$/,
            loader: 'json'
        }]
    }
}
```

I want to use a babel plugin found here - https://www.npmjs.com/package/babel-plugin-markdown-react so that I can render markdown into React Components

The example of `next.config.js` does not make it clear to me how to modify loaders.

**Comment by maticzav** [comment]
in `next.config.js` you define `exports`:
```js

module.exports = {
  webpack: (config, {dev}) => {
      config.module.loaders = [
        // Here's where you define loaders
      ]
      return config
  }
}

```

**Comment by arunoda** [comment]
@khrome83 you don't need to include the json loader.
We have it by default.

You can learn more about the state of webpack loaders in Next.js here.
See: https://github.com/zeit/next.js/issues/544

**Comment by khrome83** [comment]
ok sounds good!
