### ISSUE TITLE
Rewriting entry function in custom next.config.js or client/npm-dev.js & client/index.js

### ISSUE THREAD

**Issue by lenny0702** [zeit/next.js#1254]
I want to write some my own logic in client js (client/index.js & client/npm.dev.js). So I am trying to change the MainJS's path in entryies of webpack.js to compile my own version of client js.

Is it possible to do this?

Actually I tried to rewrite the entry function in custom next.config.js. But it never been called.

Thanks!

**Comment by arunoda** [comment]
You can access the full webpack config object with `next.config.js` and using `webpack()` function. Here entry is an object and try to log it and change as you need it.

**Comment by lenny0702** [comment]
@arunoda Thanks for your response. 
But when I try to log the entry object in my next.config.js, I got this:

next.config.js:
![image](https://cloud.githubusercontent.com/assets/2850927/23287197/f388834c-fa76-11e6-80dc-67f858da022e.png)

Output:
![image](https://cloud.githubusercontent.com/assets/2850927/23287166/be6e863e-fa76-11e6-97b1-84f9e58460e7.png)

Apparently, it's a function when it's logging. Is there some thing I did wrong?

**Comment by arunoda** [comment]
Actually, it's a async function now.
See: https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L39

Now you need to do something like this:

```js
module.exports = {
  webpack: function(c) {
    const original = c.entry
    c.entry = function () {
      return original()
        .then((entry) => {
          // do something with it
          console.log(entry)
          return entry
        })
    }
    return c
  }
}
```
