### ISSUE TITLE
Cannot find module 'next/router' (missing router.js file with npm).

### ISSUE THREAD

**Issue by siansell** [zeit/next.js#1255]
Hi guys,

Thanks for a great library, I'm really enjoying working with next.js.

Just a heads-up that the version being pulled down from npm is missing the [router.js](https://github.com/zeit/next.js/blob/master/router.js) file, unless I'm missing something obvious.

**Comment by antoinerey** [comment]
I'm not sure, but `next/router` is probably in the 2.x.x release. As explained in the readme :

```
NOTE! the README on the master branch might not match that of the latest stable release!
```

You can `npm install next@2.0.0-beta.32` to get the beta version.

**Comment by siansell** [comment]
Yep, my bad! Thanks.
