### ISSUE TITLE
SSR: rehydration broken for React.Context

### ISSUE THREAD

**Issue by AndrewSB** [zeit/next.js#12579]
# Bug report

## Describe the bug

On initial renders, rehydration doesn't seem propagate React.Context correctly down the component chain.

## To Reproduce
Here's a minimal repro: https://github.com/AndrewSB/reduced-context-bug
To see the bug:
Load the page with the window less than 800

## Expected behavior

The page should show "Compact"

## Actual behavior

The page shows "Normal"

## Screenshots

See video in README of linked repo

## System information

- OS: macOS
- Browser (if applies) repros in chrome, safari
- Version of Next.js: 9.3.6

**Comment by mohsen1** [comment]
This probably has to do with how `react-use` that you're using detects server/client environment:

https://github.com/streamich/react-use/blob/1c7a000735ef05c7391de8078cdfe9ca87d877ec/src/util.ts#L1

**Comment by AndrewSB** [comment]
that makes sense. What might be a better way to handle this kind of server/client detection?
