### ISSUE TITLE
getInitialProps in children components

### ISSUE THREAD

**Issue by jordanell** [zeit/next.js#1258]
I have a use case when I have a page concerning some object, say a "Book". I use `getInitialProps` to load the book. On the book page I also have tabs to display some `hasMany` relationships like "Authors". The "Authors" tab is a child component of the "Book" page component and ideally I would like to only load authors once the tab is clicked and this child component is mounted.

Are there any plans to allow `getInitialProps` in child components? Is there a workaround to this issue I am not seeing?

**Comment by timneutkens** [comment]
> Are there any plans to allow getInitialProps in child components? Is there a workaround to this issue I am not seeing?
TLDR is no. the long answer is described here: https://github.com/zeit/next.js/issues/192

In your case you can actually just use `componentDidMount` to do the fetching when the Authors component is loaded.

**Comment by arunoda** [comment]
@timneutkens Thanks for the reference
