### ISSUE TITLE
Issue with styled-components and custom routes

### ISSUE THREAD

**Issue by scf4** [zeit/next.js#1259]
I'm using this example: https://github.com/zeit/next.js/tree/master/examples/with-styled-components along with https://github.com/fridays/next-routes but get the following error:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client)  --><div class="sc-bdVaJa fjWbHC" data-r
 (server)  --><div class="sc-bxivhb Pcwbe" data-re
```

Running `next dev` instead of the custom `server.js` works fine with no error, but of course I need custom routes.

I just started using Next.js so any advice would be great. Thanks!

**Comment by timneutkens** [comment]
Can you provide an example repository?

**Comment by scf4** [comment]
It seems the problem was using the styled-components 2.0 beta. Never mind, thank!
