### ISSUE TITLE
Custom routing

### ISSUE THREAD

**Issue by kirill-konshin** [zeit/next.js#1261]
Per article https://github.com/zeit/next.js#custom-server-and-routing custom routing has to be done on server side. But how to let client know that there are custom rules?

Normally server sends some JSON portion, but in case of custom routes the entire HTML of new page is being sent.

The problem is that when the path is `/pages/contact.html` for example, and it's handled by server renderer, and when clicked from client: `/_next/-/pages/pages/contact.html`.

As a result I get the error `SyntaxError: Unexpected token < in JSON at position 0`.

**Comment by arunoda** [comment]
We don't support `.html` inside pages in the first place.
Client doesn't know about routing rules at all. Have a look at the examples mentioned in "custom-server-and-routing" section of the docs.

And there's are third party modules to do client aware routing.
See: https://github.com/search?utf8=%E2%9C%93&q=next.js+router&type=Repositories&ref=searchresults

**Comment by kirill-konshin** [comment]
The `.html` is used for rewrite. The rule is simple: `/pages/(:slug).html -> /pages/page?slug=slug`.

I have found an easy way to do it:

```js
        const route = getRoute(routes, pathname); // does all the matching

        if (route) {
            parsedUrl = parse(route.path + '?' + stringify(Object.assign({}, query, {slug: route.slug})), true);
        }

        handle(req, res, parsedUrl);
```

So instead of calling `app.render` (like in example) just reassemble the new URL + query and pass it to `handle`.

Unfortunately, it does not let the client know anything about it.

Since URL rewriting is a very basic concept of web, I hope eventually it will become a part of the core, instead of 3rd party modules.
