### ISSUE TITLE
Issue with <style jsx> styles not injected by server render when using custom server setup 

### ISSUE THREAD

**Issue by stephentan** [zeit/next.js#1262]
I'm using custom express server where I import 
`const next = require('next')`

and have my custom routes.

However for those handled by 
```
server.get('*', (req, res) => {
    return handle(req, res)
  })
```

`<style jsx>` doesn't seem to be added properly when rendered by server.

With the example/basic-css running next produces
`<style id="__jsx-style-845480676">.hello[data-jsx="845480676"] {font: 15px Helvetica, Arial, sans-serif;color:#FF0000;}.hello[data-jsx="845480676"]:hover {background: #ccc;}</style>`

while running with custom server, this is not injected.

**Comment by timneutkens** [comment]
Can you Provide an example repository?

**Comment by stephentan** [comment]
@timneutkens after upgrading to the latest version.
It works fine now!!! thanks a lot!

**Comment by timneutkens** [comment]
@stephentan great :shipit: 🚀
