### ISSUE TITLE
override webpack config to work with happypack

### ISSUE THREAD

**Issue by joehua87** [zeit/next.js#1263]

**Comment by sedubois** [comment]
What is the question? Custom webpack config is possible, please check the README.

**Comment by joehua87** [comment]
Sorry I've guess I'm in search box before pressing cmd + enter :)

**Comment by sedubois** [comment]
@arunoda I don't know happypack, should it be used by Next.js for faster builds?

**Comment by joehua87** [comment]
@sedubois It's good for development experience with faster built time
It's used in https://github.com/ctrlplusb/react-universally
I think is not hard to config it within this repo

**Comment by arunoda** [comment]
@sedubois yes. We are looking at it.
