### ISSUE TITLE
Request scheme 'chrome-extension' is unsupported

### ISSUE THREAD

**Issue by pdw207** [zeit/next.js#1269]
Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported
    at sw.js:formatted:279
<img width="1035" alt="screen shot 2017-02-24 at 3 02 41 pm" src="https://cloud.githubusercontent.com/assets/4714249/23318895/524ebdbc-faa2-11e6-99f1-fd9a5fea44d2.png">

**Comment by naiborhujosua** [comment]
if (handler) {
  event.respondWith(handler(event.request));
} else if (router.default && event.request.method === 'GET') {
  event.respondWith(router.default(event.request));
}
That else if clause should probably check the protocol of event.request to confirm that it's https: as an additional condition.

check this answer https://github.com/GoogleChrome/sw-toolbox/issues/171
