### ISSUE TITLE
Classname Props and other props on <Link/> except 'href' do not work

### ISSUE THREAD

**Issue by cungminh2710** [zeit/next.js#127]
The title says it all.

**Comment by impronunciable** [comment]
@cungminh2710 it is an API design decision. You can add styles to children (you can even have an anchor as its children)

**Comment by bransbury** [comment]
I came across this also, a solution as described might look something like:

`<Link href="/"><a className={style(styles.linkDefault)}>my link text</a></Link>`
```
const styles = {
    linkDefault: {
       color: '#009900',
     }
}
```

**Comment by luisrudge** [comment]
this is super weird.. we probably should accept className and style as props in the link component

**Comment by Huglo** [comment]
I totally agree with @luisrudge 
Ex: if I have a nav with a list of Link and I want a border for all Link but the last one, if I cannot style the link, it becomes quite hard to do what I would usually do:
```css
.navItem + .navItem { ... }
```
 or 
```css
.navItem:not(:last-child) { ... }
```

**Comment by flybayer** [comment]
@impronunciable what are the downsides of not accepting props like `className` on `Link`?

It seems very odd to have to pass an anchor element as a child to `Link` just so we can style it.

**Comment by tdurand** [comment]
Would be super interested in having the className working with <Link> also or having a good understanding of why this is a bad idea ;-) .

My current use case is the following, i use semantic ui for my app and i can do something like that to render semantic default element as a Link for the next/router to catch the route, but this is trashing the layout cause Link doesn't set the semantic Menu className.

`<Menu.Item as={Link} to='/page1' />`

I do a workaround using onClick - e.preventDefault() - url.pushTo('page1') , but this is not ideal.

Thanks anyway for the great work here

**Comment by tmayr** [comment]
@flybayer You can always style it from the parent instead of trying to pass more elements down with Link.

Having Links with classes however, seems like a common practice, specially in any of the frameworks around. A simple example, Links that show up as buttons.

I'd be interested in knowing any downsides to allowing different props to pass down to the `<a>`element rendered.

**Comment by nhanco** [comment]
@tdurand  do you pass this bug now ? Can you tech me how please.
