### ISSUE TITLE
Force pass down href to child

### ISSUE THREAD

**Issue by browniefed** [zeit/next.js#1271]
When using things like StyledComponents or Styletron you may do something like.

`const NavLink = styled("a", {})` This will break link and not pass down the href even though it still should.

Can there be some sort of override to force the `href` to be passed down.

**Comment by browniefed** [comment]
Alternatively could do something like.

`const NavLink = styled(Link, {})`however it does not appear that `Link` passes down any other props besides the one it crafts.

**Comment by arunoda** [comment]
@browniefed I'd like to see how a fix will be.
Additionally, you could use or imperative [API](https://github.com/zeit/next.js#imperatively).

**Comment by timneutkens** [comment]
It's because of this line: https://github.com/zeit/next.js/blob/master/lib/link.js#L98
I wonder if we should allow `<Link href="/" passHref />` or something similar.

> Happy to submit a PR to pass down all props (except for onClick/href), however I think the onClick should be proxied and still allowed.

This decision has been made before. The only thing `<Link>` should do is add the onClick, and href on `<a>`. It should not pass `className` etc 👍

**Comment by browniefed** [comment]
Not passing props through Link is an interesting choice, and I believe a much cleaner one in this case. Not sure why you wouldn't pass them down as you're already using `cloneElement`.

Adding a `passHref` would be fine in my book though.

**Comment by browniefed** [comment]
Added PR

**Comment by timneutkens** [comment]
@browniefed I'll have a look into this 😄

**Comment by browniefed** [comment]
Explicitly adding in the `href` as Guillermo recommended to the Styled Component anchor seems to be working fine.
It's a little extra verbose as I have to add it in 2 places but it technically works.

**Comment by rauchg** [comment]
Yeah I wonder if this is one of those cases where apply "DRY" would actually hurt us. FWIW this is what it'd look like if we had do expressions, which you can add a babel transform today:

```jsx
{
  do {
    const url = '/a/b/c/d'
    <Link href='/…' as={url}>
      <A href={url}>hi there</A>
    </Link>
  }
}
```

**Comment by browniefed** [comment]
I'm actually in favor of closing this issue. I'm just busting things out into separate components to pass in both `as`, and `href` and just rendering and adding `href` to the child.
Not a big deal.

If you want to continue working on this by all means, however I say close it.

**Comment by rauchg** [comment]
Thank you @browniefed

**Comment by timneutkens** [comment]
Awesome, I'm totally fine closing this 😄
