### ISSUE TITLE
CMD click breaks with nested tags

### ISSUE THREAD

**Issue by browniefed** [zeit/next.js#1272]
In the event you add a nested tag 

```
<Link>
<a><span>Something</span></a>
</Link>
```
The `e.target.nodeName` comparison will be `SPAN`. So the `e.target.nodeName === 'A'` will not fire.

This causes CMD clicks not to not open in a new window. 

I'm not sure that the check for the Anchor tag is totally necessary. If you believe it to be then maybe check the `children` type like is done in render? 

Looking at how react-router handles this it just checks modified events, it doesn't care about the tag.

**Comment by timneutkens** [comment]
Fixed in https://github.com/zeit/next.js/pull/1233. This has not been released yet afaik.
