### ISSUE TITLE
Running jest example

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1273]
I cloned the Next.js repo, and in `examples/with-jest` I ran `npm install` and `npm test`. But it just outputs this, and nothing more happens even after waiting several minutes:
```
$ npm test

> with-jest@ test /Users/sdubois/Documents/next.js/examples/with-jest
> jest

```

Nothing is printed either, when using `jest --verbose`. `jest -h` prints the help properly. But it's also stuck when running `jest -v`.

I'm new to Jest, so don't really know how to debug. 

node v7.6.0.
macOS Sierra 10.12.3.

**Comment by sedubois** [comment]
Somehow, `sudo npm test` works!
```
$ sudo npm test
Password:

> with-jest@ test /Users/sdubois/Documents/next.js/examples/with-jest
> jest

 PASS  __tests__/index.test.js
  With Enzyme
    ✓ App shows "Hello world!" (14ms)
  With Snapshot Testing
    ✓ App shows "Hello world!" (10ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   1 passed, 1 total
Time:        3.612s
Ran all test suites.
```

**Comment by sedubois** [comment]
Closing as it's nothing related to Next.js, will investigate on Jest's side...

**Comment by sedubois** [comment]
OK really weird issue, but fixed it with `brew uninstall watchman`. Hat tip to https://github.com/facebook/jest/issues/2305#issuecomment-267754387

**Comment by bryandowning** [comment]
I'm running into a similar problem. Jest does run, but it fails on the JSX syntax as if it isn't passing through babel.

From the `examples/with-jest` directory, I ran `yarn`, then `yarn test`. This is the output I'm getting:

```
$ yarn test
yarn test v0.24.5
$ jest
 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    /bryan.lo/test/next-js-framework/examples/with-jest/__tests__/index.test.js: Unexpected token (11:24)
         9 | describe('With Enzyme', () => {

        10 |   it('App shows "Hello world!"', () => {
      > 11 |     const app = shallow(<App />)
           |                         ^
        12 |
        13 |     expect(app.find('p').text()).toEqual('Hello World!')
        14 |   })
```

Running `sudo yarn test` works.

I also ran `brew uninstall watchman`, but that didn't help.

I'm using node version 6.10.3 with `n` and have verified that my user owns `/usr/local/bin/node`

I have no idea what's going on here, as this seemed to be working a few days ago. The only thing I can think of that might have impacted this is that I just updated macOS to version 10.12.5 yesterday.

Any thoughts would be appreciated.
