### ISSUE TITLE
with-apollo example webpack break?

### ISSUE THREAD

**Issue by katopz** [zeit/next.js#1274]
![screen shot 2017-02-25 at 20 26 37](https://cloud.githubusercontent.com/assets/97060/23331755/eada81b8-fb9e-11e6-80dc-760f0b4256d0.png)

And I think it make `HMR` breaking there. Is this only me?

**Comment by sedubois** [comment]
Hmm I don't have that issue when running the example (using `2.0.0-beta.32`). Can you look at what throws the error?

**Comment by katopz** [comment]
@sedubois I'm trying `2.0.0-beta.32` with nearly same error result
![screen shot 2017-02-25 at 21 34 52](https://cloud.githubusercontent.com/assets/97060/23331938/4b815638-fba2-11e6-82bc-6c5f699085c2.png)

**Comment by sedubois** [comment]
About the prefetch errors, go to chrome://serviceworker-internals and unregister the next-prefetcher.js. That mechanism has been removed recently.

**Comment by katopz** [comment]
@sedubois Weird enough clear cache, app cache, local storage did the trick (I'm using chrome extension to clear them all so I'm not so sure which one causing this)

Thanks!
