### ISSUE TITLE
next/link silently ignores params in case of typo

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1275]
If I use `<Link href='/' prefetc>` (notice the typo), there's no error message. Possibly similar comment for other params and other Next.js APIs.

**Comment by arunoda** [comment]
Actually, it's good dev only feature. We expose few APIs like this, so we might need to have them for  those as well. 

Anyway, I'd like to see this as a linter something externally. Anyway, this is something I'd love to see.

**Comment by timneutkens** [comment]
The flow types would actually catch this. I noticed the prefetch tag is missing though.
https://github.com/zeit/next.js/blob/master/examples/with-flow

**Comment by timneutkens** [comment]
Some ideas over here https://github.com/facebook/react/issues/1587

**Comment by timneutkens** [comment]
Seems like the best option is https://github.com/airbnb/prop-types `forbidExtraProps`

**Comment by timneutkens** [comment]
Seems like ljharb released it as separate package: https://github.com/airbnb/prop-types-exact pretty cool 👌 I'll experiment with it.
