### ISSUE TITLE
Expose next-test-utils

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#1289]
We are doing this in a different repo since we need to add some dependencies where usually doesn't need by `next`.

With that, anyone could use the internal integration testing tool-kit we are using for Next.js

**Comment by sedubois** [comment]
I suggest to do this in a different NPM package but for the sake of keeping things easy to manage I'd still put the code in the `next.js` repo itself, e.g in a `packages/` subfolder.

As e.g React does: https://github.com/facebook/react/tree/master/packages

**Comment by arunoda** [comment]
That's something we've not decided yet. But seems like a good solution.

**Comment by KingScooty** [comment]
Has any progress been made on this?

**Comment by andrewholsted** [comment]
@arunoda - is there still a plan to open these up?

**Comment by DullReferenceException** [comment]
I'm confused; are you not allowing external contributions? How do we write/run integration tests without this module being installed?

**Comment by pantharshit00** [comment]
@arunoda is there any plan? I need to mock much stuff while testing.

**Comment by timneutkens** [comment]
@DullReferenceException @pantharshit00 we're still planning to release them at some point, but not the ones inside Next.js, rather the ones we use for our internal testing (a newer, but similar version of the tools inside Next.js, which use puppeteer instead of chromedriver).

**Comment by pantharshit00** [comment]
@timneutkens I meant the library would provide mocks and helper Providers for router and other stuff. End to end testing is not that painful. I use Cypress personally.

The router gives serious problems while unit testing. It gives can't use next/router outside client. I have some mocks written by my own to deal with it now. Looking forward to this library.

**Comment by timneutkens** [comment]
> After trying it out, looks like the tests somehow run, I'm just not sure how it works or how to see what those test utils do exactly.

@DullReferenceException FYI it's because NODE_PATH is used when running the tests.

**Comment by timneutkens** [comment]
I'm going to close this issue for now as we're not going to focus on next-test-utils in the short term (the issue has been open over 1,5 years).

**Comment by ivan-kleshnin** [comment]
I don't get – what it the official position on this? 

Anybody has a working example of page (with getInitialProps) testing? The search yields no results and I don't want to spend days trying to run something that's was never meant to work 😞
