### ISSUE TITLE
remove regenerator in server code

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1291]
I see stuff like this in server code (e.g `next/dist/server/build/index`): `var _asyncToGenerator2 = require('babel-runtime/helpers/asyncToGenerator');`

Now that async/await is available in Node 7.6.0, should it be removed for better performance?

**Comment by arunoda** [comment]
Yep in the future as we add the `babel-preset-env` support. But for now, we'll keep the setup like this.
