### ISSUE TITLE
"On-demand entries" is slow and broken

### ISSUE THREAD

**Issue by dizlexik** [zeit/next.js#1296]
I just updated to 2.0.0-beta.33 and I'm not having a great dev experience with the new "on-demand entries".

My project is small. I have only 5 pages and I'm using dynamic routing for one of them so everything is running through Koa, which has been working perfectly in beta-32.

I'm experiencing the following issues:

**Speed:**

- beta.32
  - build time: 12s
  - initial page load: 200ms
- beta.33
  - build time: 10s
  - initial page load: 7s

Each page takes 7'ish seconds to load the first time, which is pretty unbearable. And after a handful of seconds sitting on a page I see "Disposing inactive page(s): ..." in my terminal and it takes another 7 seconds to navigate to to the disposed pages.

**Broken navigation:**

Another problem is that when I click a link to another page I get the 7 seconds of loading and then my current page just refreshes; it doesn't take me to where I was trying to go. I can only navigate to the desired page after clicking a second time (within the auto-dispose period).

Any ideas on what could be causing these issues for me? I had no problem with how everything was working before, and I actually preferred it. I'd love it if there was an option to opt out of this. Or even better if this was an opt-in feature since I imagine the majority of users won't ever have enough pages to make this worth all of the extra complexity. Thoughts?

**Comment by arunoda** [comment]
@dizlexik Thanks for the issue.
Yeah! I think we should make this opt-in.
I'll do that.

In the meantime, I want to debug the reload issue.
Could you send me a [HAR report](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting) of the network requests?
So, I can investigate it.

**Comment by rauchg** [comment]
Well, we need to look into why the page would take 7s to load *every time*, even if you don't make changes first.

**Comment by rauchg** [comment]
The "slowness" piece is the one that's relative. You'll either pay the price of compiling the 5 pages _ahead of time_, or you'll do it _on demand_.

**Comment by rauchg** [comment]
@dizlexik two things please:
- can you share how long a rebuild would take of a page that now takes 7s to navigate to, with previous beta?
- can you share a minimal test case of the broken navigation? I can't reproduce it

**Comment by dizlexik** [comment]
Could you clarify exactly what you'd like me to test in beta-32?

Regarding the minimal test case of the broken navigation, I've recreated it with this:

**index.js**
```js
export default () => <div>index</div>;
```

**_error.js**
```js
export default() => <div>error</div>;
```

**a.js**
```js
import Link from 'next/link';
export default () => <Link href="/b"><a>b</a></Link>;
```

**b.js**
```js
import Link from 'next/link';
export default () => <Link href="/a"><a>a</a></Link>;
```

I start `next` and navigate to http://localhost:3000/a and click the "b" link. It refreshes the page on the first click and only navigates to "b" once I click a second time.

It took me some trial-and-error to get this minimal example to fail. I'm testing now and it seems like if I delete any one of those four pages the issue goes away. I have no idea why and I don't have time to dig any deeper right now, but hopefully this is helpful for you guys.

**Comment by arunoda** [comment]
> I start next and navigate to http://localhost:3000/a and click the "b" link. It refreshes the page on the first click and only navigates to "b" once I click a second time.

This sounds like you clicked before loading JS code. Anyway, I've fix some related code fix and it'll come with Beta 34.

**Comment by rauchg** [comment]
Thank you @dizlexik, that's super helpful 👌 On-demand entries will soon be fast and great. We also have performance optimizations coming up for the individual bundles. A lot of the prod complexity can be 100% eliminated during dev. If after a few iterations it's still not great, we'll add a flag to make this opt-in (next --lazy)

**Comment by dizlexik** [comment]
That sounds good @rauchg. I'm definitely excited to see how this goes.

@arunoda, were you able to reproduce the issue using the code I provided? I just tested out beta-34 and I'm still experiencing the same behavior.

**Comment by arunoda** [comment]
@dizlexik Thanks. I can reproduce it now running with your example.
On it.

**Comment by rauchg** [comment]
@dizlexik check `2.0.0-beta.35`

**Comment by dizlexik** [comment]
The navigation issue is resolved in beta.35, thanks @arunoda!

**Comment by arunoda** [comment]
@dizlexik nice.
We'll work on the speed-up to the rebuild time soon.
BTW: Could you send me a list of NPM modules(client side) you are using in your app.

**Comment by dizlexik** [comment]
Sure, currently I'm using `apollo-client`, `graphql-tag`, `moment`, and `react-bootstrap`.

**Comment by arunoda** [comment]
I can't find a pretty large slowdown with those modules. (General case).
If you can send me a way to reproduce it, I could fix the slowness quickly.

**Comment by dizlexik** [comment]
Doing more testing with beta.36 I've found that initial load speed has improved quite a bit. Takes only a couple of seconds now, as does each subsequent page. It's certainly more manageable now and I can deal with it, although I'd still prefer to eat that time upfront and have a more instant experience navigating around during development. I'd still vote for this to be opt-in or opt-out, but thanks so much for your hard work on this! I can definitely see value in using this approach in projects with a large number of pages. It's just not paying off for me right now on my small project.

**Comment by rauchg** [comment]
@dizlexik the key is that according to my _back of the envelope_ calculations, for most projects we should be able to spend only around 500ms on webpack stuff. It's a matter of continuing to optimize.

So, the page transitions would still be instant, and you can scale with the exact system to thousands of pages and components, without flags.

**Comment by dizlexik** [comment]
Sounds awesome to me! Can't wait :)
I think we can consider this closed then. Thanks again!

**Comment by rauchg** [comment]
Thank you for keeping us on our toes!

**Comment by bryan** [comment]
Apologies for bumping up this thread, but is on-demand still in the works? I recently upgraded a medium-sized project to the latest beta version 39 and realized extremely how slow it was loading, so I reverted back to the latest non-on-demand version beta 32, which is how it was before. 

I would very much prefer making this an opt-in but seen that has been scrapped but no reason was provided on that issue https://github.com/zeit/next.js/pull/1299, may I ask why?

**Comment by rauchg** [comment]
The reasoning has been explained above. The idea is not to build an entire project (which could be hundreds of thousands of components) ahead of time, if we can slice up the work and do it lazily.

There are a lot of optimizations we still have yet to do to the webpack pipeline so that the on-demand approach is significantly faster. We can add a flag to make the old behavior opt-in `--all`. 

I very much welcome PRs for both lines of work: optimizing compilation during dev time, and adding `--all`.

Some ideas to help make compilation faster:
- Do less work during dev. We don't have to transpile as much if we're targeting Chrome only
- Perhaps forego sourcemaps for the first pass (I believe this is what adds a lot of time atm)
- Ship the static bundles PR 
- Turning off common chunks plugin during dev

There's still a lot of work to be done to make pages compile faster.
