### ISSUE TITLE
How to select children in JavaScript CSS?

### ISSUE THREAD

**Issue by nodegin** [zeit/next.js#130]
As what topic stated, I have tried something like:
```js
const style = css({
  position: 'absolute',
  '@media (min-width: 1000px)': {
    ':hover': {
      '> div': {
        background: '#fff',
      },
    },
  },
})
```

**Comment by impronunciable** [comment]
Hi @nodegin we are using https://github.com/threepointone for css (the default export is just an alias to the `style` method in glamor. I'm closing this since it's a question on glamor

**Comment by impronunciable** [comment]
It also seems that this is the answer https://github.com/threepointone/glamor/blob/master/docs/howto.md#child-selectors

**Comment by nodegin** [comment]
@impronunciable Got it, thanks!

Here is a sample usage:
```js
import css, { merge, select } from 'next/css'

const test1 = css({
  color: '#00f',
})
const test2 = merge(test1, css({
  padding: 4,
}), select('> li', {
  listStyle: 'none',
}))
```
