### ISSUE TITLE
Get rid of our use of eval

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#1301]
Related to: https://github.com/zeit/next.js/issues/256
We use eval to evaluate JSON pages. We should use JSONP instead.

Here are the the set of things we need to do:

* [ ] Save JSONP like data with the webpack plugin
* [ ] Send the initial JSONP with the data
* [ ] Fetch the JSONP from the router
* [ ] Handle 404 pages
* [ ] Handle status codes

**Comment by timneutkens** [comment]
Also related: https://github.com/zeit/next.js/issues/1207

**Comment by rauchg** [comment]
We should also evaluate strategies that would allow us to just use `<script>` and load regular `.js` files

**Comment by arunoda** [comment]
@rauchg Since this is not just data, that's what we've to do.

**Comment by arunoda** [comment]
Fixed with https://github.com/zeit/next.js/pull/1700
