### ISSUE TITLE
Global styles added to _document.js are stripped when going to prefetched page

### ISSUE THREAD

**Issue by timmywil** [zeit/next.js#1308]
Steps:

1. Add `<Link prefetch href="/route" />`
2. Add `<style jsx global></style>` to `_document.js`. I'm using this for critical path CSS that is universal to all pages.
3. Click the link to `/route`. Styles from the global style tag are lost.

Is there a better way to insert inline critical path CSS? Do I need to wrap every page component or create an HOC? That would be tedious.

**Comment by timneutkens** [comment]
@timmywil you can use `<style>` in document. You shouldn't use `styled-jsx` in this case.

**Comment by timmywil** [comment]
@timneutkens problem with that is it gets HTML-escaped and I lose things like autoprefixing.

**Comment by timneutkens** [comment]
Right, best thing you can do in that case is wrap the pages in a HOC or a layout component like https://github.com/zeit/next.js/tree/master/examples/layout-component

**Comment by timmywil** [comment]
Okay, that's what I was afraid of.

**Comment by timmywil** [comment]
Actually, it's not so bad since I already had `HEAD` tags for page titles. I'm fine with the Layout solution. Thanks.
