### ISSUE TITLE
version 9.4.1 `npm run build` is not working on digitalocean (ubuntu). Says: Error: > Build directory is not writeable. https://err.sh/zeit/next.js/build-dir-not-writeable

### ISSUE THREAD

**Issue by nimitwalia89** [zeit/next.js#13091]

**Comment by theCuriousOne** [comment]
@nimitwalia89 What Node.js version do you have? I experience the same error with Node.js 8 but not with Node.js 10 (or greater)

**Comment by nimitwalia89** [comment]
@theCuriousOne updating works. thanks :)

**Comment by vaibhav1802** [comment]
I was facing similar error (directory doesn't exist error errno: -2, code: 'ENOENT', syscall: 'mkdir') in next build because of old nodejs version (8). Updated to 12 and issue got fixed.
