### ISSUE TITLE
babel-plugin-module-alias@1.6.0: WARNING: This project has been renamed to babel-plugin-module-resolver. Install babel-plugin-module-resolver for new features

### ISSUE THREAD

**Issue by kdeng** [zeit/next.js#131]
there is a warn message during installing next.

babel-plugin-module-alias@1.6.0: WARNING: This project has been renamed to babel-plugin-module-resolver. Install babel-plugin-module-resolver for new features

**Comment by nkzawa** [comment]
Closed via 990e39b13eb54a597ad25cc7a30dd2dac94d1f90
