### ISSUE TITLE
Webpack SSR bundle differs from client-side bundle using module replacement

### ISSUE THREAD

**Issue by wilmervanheerde** [zeit/next.js#13136]
## Describe the bug

Using a module replacement plugin, similar to Webpack's [NormalModuleReplacementPlugin](https://webpack.js.org/plugins/normal-module-replacement-plugin/), the replaced modules appear only in the client-side bundle and not in the server-side bundle.

This causes the application to display wrong components on the SSR output which then gets replaced when client-side JavaScript takes over.

 * Webpack plugin used is [@deity/normal-module-override-webpack-plugin](https://www.npmjs.com/package/@deity/normal-module-override-webpack-plugin)

Webpack config:
```
const NormalModuleOverridePlugin = require("@deity/normal-module-override-webpack-plugin");

module.exports = {
  webpack: (config) => {
    config.plugins.push(
      new NormalModuleOverridePlugin({
        "package/path/to/component": "src/custom/component",
      })
    );

    return config;
  },
};

```

## Expected behavior

Replaced modules should appear in both bundles so the SSR output is rendered correctly.

## System information

- OS: Windows 10, Ubuntu 20.04
- Version of Next.js: 9.3.6
- Version of Node.js: 12.16.3

**Comment by timneutkens** [comment]
Not sure what you're trying to achieve exactly but node_modules are not passed through webpack for the server-side.

**Comment by wilmervanheerde** [comment]
Hmm, is there a way to include them? Package X exports component Y, with the replacement plugin we want to replace Y with our own component. Component Y is being referenced by other components in package X and those references are updated with this plugin.
