### ISSUE TITLE
Ability to opt in/out of Incremental Static Regeneration on a per route basis on dynamic route group

### ISSUE THREAD

**Issue by pranaypratyush** [zeit/next.js#13152]
# Feature request
Ability to opt in/out of Incremental Static Regeneration on a per route basis on dynamic route group
## Is your feature request related to a problem? Please describe.
When `getStaticProps` is used in combination with dynamic routes we need a method `getStaticPaths` that returns `{paths: [{params:{...}], fallback: true|false}` but I want to be able to choose ISR on a per path basis.

## Describe the solution you'd like
Change the config object type to `[{params:{...}, fallback: true|false}, {params:{...}, fallback: true|false}, ... ]`

**Comment by Timer** [comment]
You can choose this in the return value within `getStaticProps`.

**Comment by pranaypratyush** [comment]
One `getStaticProps` is common for one dynamic group. Then how can we do that there?
