### ISSUE TITLE
with-prefetching example is not prefetching

### ISSUE THREAD

**Issue by coluccini** [zeit/next.js#1322]
Hi,
I just downloaded the example code and ran it as is and I'm not seeing any kind of prefetch (nor the "prefetch using the declarative API" or the "imperatively prefetch on hover"). There is something I should to do so it starts working? (I was trying to make prefetch work in my code and after I failed I download this just to see how is was made). I've tried in Chrome, Safari and Firefox.

![1](https://cloud.githubusercontent.com/assets/20334179/23465364/57ecaa8c-fe98-11e6-9b39-2c850595b0a7.png)

**Comment by sergiodxa** [comment]
Prefetching uses ServiceWorkers, and as far as I know SW requires HTTPS to work, try deploying to [now.sh](https://now.sh).

**Comment by coluccini** [comment]
Well, that was the issue :)
The weird think is that everywhere says that "[during development you'll be able to use service worker through localhost](https://developers.google.com/web/fundamentals/getting-started/primers/service-workers)"  🤔 

If the prefetch depends totally on SW, **it means that it will not work at all on iOS and/or Safari?** Is not a way to achieve some similar preloading of those files?

**Comment by coluccini** [comment]
Just found out this thread: https://github.com/zeit/next.js/issues/436 😞 
To leave that really high percentage of user on iOS/Safari/IE without the amazing (almost critical) prefetch feature, do you think with can achieve something [like this stackoverflow answers](http://stackoverflow.com/a/40391232)?

**Comment by arunoda** [comment]
> Prefetching uses ServiceWorkers, and as far as I know SW requires HTTPS to work, try deploying to now.sh.

@coluccini @sergiodxa We no longer use SW and prefetching should work everywhere.
But now it only works on production. (next dev && next start)

**Comment by coluccini** [comment]
I'm so happy to read that @arunoda ! thanks so much (for the answer and for your awesome work on next)! :)

**Comment by arunoda** [comment]
So, I'm closing this issue.
Re-open if the issue exist still.
