### ISSUE TITLE
Initial router.query is empty when URL query is set

### ISSUE THREAD

**Issue by Regaddi** [zeit/next.js#13220]
# Bug report

## Describe the bug

When using the parsed `query` object from `useRouter` the initial value is always `{}`.
When a next.js app is opened with URL query parameters it should instead return the correct query, otherwise some IMO unnecessary state logic has to be built around.
I would imagine that it should be possible to read and parse the URL query before first render, so that `useRouter` can expose the correct query on first render.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

- Go to https://4g5yg.sse.codesandbox.io/?abc=def
- Open Browser DevTools console
- You should see 3 logged items:
  - `initial query: {}`
  - `subsequent query: {}`
  - `subsequent query: {abc: "def"}`

The corresponding codesandbox is here: https://codesandbox.io/s/hungry-edison-4g5yg

## Expected behavior

The initial query should already contain `{abc:"def"}`

## System information

- OS: any
- Browser: any
- Version of Next.js: 9.4.2
- Version of Node.js: probably doesn't matter

## Additional context

I'll have to read a token from the URL when the application launches on any route and decide (based on the token and its validity) wether or not a redirect should happen. I could solve this with some additional state (something like `isTokenCheckPending`), but this is surely a workaround and doesn't compliment the overall ergonomics.

**Comment by illuminist** [comment]
> The query object will be empty during prerendering if the page is statically optimized.

https://nextjs.org/docs/api-reference/next/router#router-object
