### ISSUE TITLE
Custom server with express not working in production mode

### ISSUE THREAD

**Issue by Goluis** [zeit/next.js#1326]
I was running my project with express, then I saw an issue in production mode so I replicated the `custom-server-express` example and the same issue was there:

![issue](https://cloud.githubusercontent.com/assets/4278345/23487153/30b66376-feb2-11e6-9ce4-30250e6e6c53.png)

(using nextjs beta 36) It is only happening with `npm run start`. everything seems to be fine in dev.

**Comment by aranajhonny** [comment]
You could create a repo in github with the code or create a gist.

**Comment by Goluis** [comment]
it is from the examples in next: https://github.com/zeit/next.js/tree/master/examples/custom-server-express

**Comment by arunoda** [comment]
@Goluis is this persist even you reload the page?

**Comment by Goluis** [comment]
@arunoda Yes, but only when I'm using `NODE_ENV` in' `production`, when I switch to dev everything works fine, except that the initial page load is always 1.5s or more

**Comment by arunoda** [comment]
Okay. This happens when you run `npm run start` without `npm run build`
If you just run `npm start` just after `npm run dev`, you running dev build with production server.
Which doesn't work pretty well.

Re-open if this's not the case.

**Comment by timneutkens** [comment]
@arunoda, Should we show a warning in this case?

**Comment by timneutkens** [comment]
We Already do in 'next start'

**Comment by dmmz** [comment]
When running in production mode with 'next start', custom routes in the server side do not work. It seems it ignores server.js.

This is the case even in https://github.com/arunoda/learnnextjs-demo.git. Where urls like http://localhost:3000/p/hello-nextjs won't work from the server side.

If we run the run in production mode with 'NODE_ENV=production node server.js', custom routes work fine.

**Comment by reel** [comment]
The reason is `next start` only runs the next.js part.. 

You should `next build` then start with `NODE_ENV=production node server.js`

You can also trigger the build programmatically from `dist/server/build`

**Comment by timneutkens** [comment]
@reel FYI https://github.com/zeit/next.js/issues/1326#issuecomment-283563364 has been fixed 👌 If there is no build it'll show a warning when using custom server to 😄
