### ISSUE TITLE
next/link does not like nofollow

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1329]
I tried to set a nofollow link up with next. But I get a server crashing issue because "rel"

<img width="947" alt="screen shot 2017-03-02 at 2 54 05 pm" src="https://cloud.githubusercontent.com/assets/1844739/23526566/246941a0-ff58-11e6-96bc-32321fa2e1d4.png">

How do we create `rel="nofollow"` links with next?

```js
      <NextLink href={href}>
        <a className={`link`} title={title} rel="nofollow">{ children }</a>
      </NextLink>
```

What is best practice? Thanks!

**Comment by timneutkens** [comment]
I can't reproduce this 🤔 I'm seeing the `rel="nofollow"` rendered correctly.

**Comment by timneutkens** [comment]
Wrong button 😅

**Comment by khrome83** [comment]
Doh, I had a type-o. I was using variable spread and was trying to assign `attrs[rel] = 'nofollow';` instead of `attrs['rel'] = 'nofollow';`.

Total Facepalm Moment!

/facepalm

**Comment by timneutkens** [comment]
Well that explain :smile: Thanks for reporting anyway 👍 ❤️
