### ISSUE TITLE
Style elements added to _document or to <Head> component are being escaped

### ISSUE THREAD

**Issue by clementoriol** [zeit/next.js#1337]
(Using Next.js 2.0.0-beta.36)

Trying to add global styles to my app, especially @font-face rules (for self-hosted fonts).
When adding styles to `pages/documents.js` (via the style prop) or via the `next/document/head` component, the appended CSS is escaped.

Which results in broken fonts.

Is this a bug, or is this intended ?
What could be a workound to output working @font-face rules ?

An excerpt of my css : 

```
@font-face {
    font-family: 'Roboto Slab';
    font-style: normal;
    font-weight: 300;
    src: local('Roboto Slab Light'), local('RobotoSlab-Light'),
         url('/static/fonts/roboto-slab-v6-latin-300.woff2') format('woff2'),
         url('/static/fonts/roboto-slab-v6-latin-300.woff') format('woff');
  }
```

The output : 
```
@font-face {
  font-family: &#x27;Roboto Slab&#x27;;
  font-style: normal;
  font-weight: 300;
  src: local(&#x27;Roboto Slab Light&#x27;), local(&#x27;RobotoSlab-Light&#x27;),
      url(&#x27;/static/fonts/roboto-slab-v6-latin-300.woff2&#x27;) format(&#x27;woff2&#x27;),
      url(&#x27;/static/fonts/roboto-slab-v6-latin-300.woff&#x27;) format(&#x27;woff&#x27;);
}
```

Tried in a simple static project, the "clean" CSS works, the escaped one doesn't.

**Comment by timneutkens** [comment]
This is a React thing. You can use something like this:

```
<style dangerouslySetInnerHTML={{__html: `
    .styled { color: blue }
`}} />
```

https://medium.learnreact.com/the-style-tag-and-react-24d6dd3ca974#.fpm62sn1u

**Comment by clementoriol** [comment]
That was it ! Thank you.
