### ISSUE TITLE
Idea: support URL objects

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#1341]
Everywhere we support string `href`, we can support a `pathname` + object/string `query` object:

```jsx
<Link href={ pathname: '/aaa', query: { a: 'b' } }>
```

```jsx
Router.push({ pathname: '/woot', query: { test: 2 } })
```

Would make many lives easier. AMA

**Comment by timneutkens** [comment]
I created a wrapper to do this, let me see when I get back to my laptop :)

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/issues/1118#issuecomment-279556698

**Comment by rauchg** [comment]
Yep I thought about a wrapper, but was bringing up the discussion of supporting it directly. Seems awfully common, and also has a "symmetry" with `app.render` receiving a query object.

**Comment by timneutkens** [comment]
Yep, and with how other routing packages do it, like react-router. Just wanted to drop it in here as reference 👍 I'm not opposed to this. I've seen *many* examples of people wrapping `<Link>` to do this exact thing, especially when they had a lot of query params.

**Comment by arunoda** [comment]
Fixed with https://github.com/zeit/next.js/pull/1345
