### ISSUE TITLE
Dynamic Import returns LoadableComponent instead of Module

### ISSUE THREAD

**Issue by renatodex** [zeit/next.js#13417]
# Bug report

## Describe the bug

When I try to load Phaser using `dynamic imports` in a JSX component, it fails to load the `Phaser` object.
Instead, the loaded object is a `LoadableComponent`, and when I try to create the Phaser object, I receive this error:

`TypeError: Phaser.Game is not a Constructor` (see screenshot below)

## To Reproduce

I've created a sample repository to make it easy for anyone to reproduce the error:
https://github.com/renatodex/react-phaser-issue

The repo has 2 a `components` folder with 2 files using different techniques to import `Phaser`.

### 1. components/this_module_works.js

This file is a simple JS module, and I've used an `await` import on the `phaser` module to retrieve it only in client side (i check for `typeof window !== 'undefined'`)
It's imported on the `index.js` page and it works normally.

### 2. components/this_component_is_broken.js

Here, the idea is to make it a Component to be used on the main page.
I tried to use the `dynamic import` to retrieve the `phaser` module, but it always returns a `LoadableComponent` instance, instead of returning the `Phaser` object.

As a result, the page throws an error when you try to import it.

## Expected behavior

The error happens because the Dynamic Import returns a `LoadableComponent`, and I was expecting it to return the `Phaser` object as a result.

The TypeError is basically thrown because `LoadableComponent` is not the `Phaser` object.

## Screenshots

![image](https://user-images.githubusercontent.com/68507/82956291-e08d1d80-9f86-11ea-8fbf-ca04254f81d0.png)

## System information

- macOS
- chrome
- Version of Next.js: 9.4.2
- Version of Node.js: v12.14.1
- Version of Phaser: 3.23

## Additional context

The repository is a simple Next app. You can run the server using `yarn run dev` or something.

**Comment by Timer** [comment]
`next/dynamic` is only for components, not any dynamic imports. You should be using pure `import()`!
