### ISSUE TITLE
Duplicated head using apollo

### ISSUE THREAD

**Issue by Goluis** [zeit/next.js#1347]
I'm seeing that the contents of Head `(next/head)` are doubling when I use apollo, it doesn't seem to have any negative effects but I wanted to let you know.

![issue](https://cloud.githubusercontent.com/assets/4278345/23579834/bec8da8c-00c3-11e7-8b35-ca7be982117c.png)

[link to the repo](https://github.com/Goluis/next-with-apollo-repeated-head)

the head is duplicated because of this:
```js
if (!process.browser) {
  const app = (
    <ApolloProvider client={client} store={store}>
      <Component {...props} />
    </ApolloProvider>
  )
  await getDataFromTree(app)
}
```
btw if I use `Head` multiple times, there should be no problem right ? (in the repo I'm using it only once)

**Comment by impronunciable** [comment]
@Goluis Can you try using `<style jsx global>` instead of `<style>` here https://github.com/Goluis/next-with-apollo-repeated-head/blob/master/pages/index.js#L11 ?

**Comment by Goluis** [comment]
@impronunciable with `<style jsx global>` the styles are not duplicated, but they were not loading the first time, only after reloading the page.

I also added some `<meta>` from [facebook open graph](https://developers.facebook.com/docs/sharing/webmasters) and they are getting duplicated
![issue](https://cloud.githubusercontent.com/assets/4278345/23580899/96fb2e64-00d8-11e7-9d83-000972760274.png)

**Comment by acorcutt** [comment]
@Goluis - Same problem here, does this help...

`export default withApollo(({initialState}) => (<div>{initialState && <Head><title>Only render once</title></Head>}</div>)
`

On the `getStateFromTree` render `initialState` is empty so just skip outputting the `<Head>`. Also, only outputting on the main render should mean you have any data you need for any dynamic titles, meta etc.

Inside deeper components I just check that the data from a gql query has loaded, I guess you could pass the initialState through props if needed.

**Comment by Goluis** [comment]
@acorcutt I tried your solution and It works, thank you :D.

**Comment by sedubois** [comment]
@ads1018 should this concern the `with-apollo` example too? Haven't checked

**Comment by acorcutt** [comment]
@Goluis - I noticed that using `<style jsx global>` inside of the initialState check does not render - it must be checking for duplicate renders itself, so maybe keep that outside or use standard `<style>` tag.

@sedubois - yes I'm using code based on `with-apollo` I guess it applies to anything that causes the head code to run more than once.

**Comment by Goluis** [comment]
@sedubois `with-apollo` isn't using the `Head` from `next/head` which I use for meta tags, fonts, etc. It should be ok.

@sedubois I'm using the styles outside the head to avoid that kind of problems.

**Comment by ArthurMauricioDelgadillo** [comment]
Hi i'm having the same issue, is this will be fixed in the last with-apollo sample?. I created a project from the with-apollo sample and I have duplicated Head & style tags
Please any help @Goluis  , @acorcutt

**Comment by acorcutt** [comment]
@ArthurMauricioDelgadillo it looks like initialState was changed to serverState in with-apollo but above fix should still work try...
`export default withApollo(({serverState}) => (<div>{serverState && <Head><title>Only render once</title></Head>}</div>)`

**Comment by ArthurMauricioDelgadillo** [comment]
ohh :P thanks @acorcutt  ...probably there should be a sample with Head in the with-apollo. Again thanks :)
