### ISSUE TITLE
The server side code on NPM contains coverage instumentation

### ISSUE THREAD

**Issue by 0xR** [zeit/next.js#1349]
For example `node_modules/next/dist/bin/next-start`
```js
#!/usr/bin/env node
'use strict';

var cov_1a1a6li199 = function () {
  var path = '/Users/NaoyukiKanezawa/github.com/zeit/next.js/bin/next-start',
      hash = '0394589d2ffeaf446f5cdd73b8f29b3e89379928',
      global = new Function('return this')(),
      gcv = '__coverage__',
      coverageData = {
    path: '/Users/NaoyukiKanezawa/github.com/zeit/next.js/bin/next-start',
    statementMap: {
      '0': {
        start: {
          line: 21,
```

This has a negative impact on performance.

**Comment by timneutkens** [comment]
This is only the case in 1.x of Next.js. It has since been fixed in 2.0 beta. I would highly recommend using `next@beta`. It is going to be released as 2.0 🔜

**Comment by 0xR** [comment]
Thanks! 

Note I can imagine since 2.0 is a breaking change people still running on 1.x would also like to have the fix. You could consider merging the fix back to the 1.x branch as a patch release.

**Comment by sedubois** [comment]
@0xR there is no 1.x branch 😛  but 2.0 is 🔜 ™️ 😄
