### ISSUE TITLE
on demand entries question

### ISSUE THREAD

**Issue by abstracthat** [zeit/next.js#1364]
Is there anyway to prevent my console from filling up with `Fetch complete: GET "http://localhost:3003/_next/on-demand-entries-ping?page=/".` while in development? With a new ping every 5 seconds my console gets quite noisy rather quickly.

**Comment by rauchg** [comment]
I'm thinking we can use `new Image().src` maybe instead of XHR just to avoid the horrible XHR logs?

**Comment by arunoda** [comment]
@abstracthat what's your browser?
In chrome, we can't see this GET request in the console, but in the network tab.

@rauchg Even we use an image, it's the same doing fetch. Network request will be there and when there's a 404 error, it'll log into the console.

**Comment by abstracthat** [comment]
Chrome 56. I don't believe I've configured anything special to show those requests. Typically I enjoy seeing what requests are being made.

![image](https://cloud.githubusercontent.com/assets/5805280/23710002/3ebe9934-03e9-11e7-93a4-3a9b3bd09c5c.png)

I've found I can also hide these without too much trouble but for a new user I could see it being a bit annoying.

![image](https://cloud.githubusercontent.com/assets/5805280/23710098/883e0c02-03e9-11e7-831c-e3b05c01a8b9.png)

**Comment by albinekb** [comment]
Why is this not done over sockets? 🤔

**Comment by arunoda** [comment]
@albinekb because of the custom server support, creating WS server inside the same port seems challenging.
But I like to introduce a new port and server for this.

**Comment by aesopwolf** [comment]
Adding `^((?!on-demand-entries).)*$` to the network filter is my solution for the time being.

![image](https://user-images.githubusercontent.com/6847633/29685136-5e6505ba-88c9-11e7-8590-d5f654d3b051.png)

**Comment by bhavin-prajapati** [comment]
Is there a way to prevent these calls from happening?

**Comment by timneutkens** [comment]
@bhavin-prajapati no there isn't. If this relates to your other comment, this is disabled in production mode too 😄

**Comment by donaminos** [comment]
Hi guys, I am using Next for my project and I went through this issue that I do not understand quite well. 
Could someone explain to me please the purpose of `on-demand-entries-ping` ? 
Thanks

**Comment by albinekb** [comment]
It is there to ping for updates when you change your code to make it faster from changed code to updated code running in your browser @donaminos

**Comment by donaminos** [comment]
Thank you very much @albinekb

**Comment by ghengeveld** [comment]
The Regex checkbox seems to be missing in newer versions of Chrome. You now need to add a leading and trailing slash to use Regex:

![](https://user-images.githubusercontent.com/321738/34555677-4dcd3af6-f133-11e7-8545-561aa67c903a.png)

I'll update the [Wiki page](https://github.com/zeit/next.js/wiki/Filter-on-demand-entries-from-Network-tab).

**Comment by timneutkens** [comment]
Not sure if this still an issue. Chrome now squashes multiple requests to the same url 🤔

**Comment by TrebuhD** [comment]
Yeah, still an issue, at least in the network tab. I think Chrome only squashes console logs.

**Comment by timneutkens** [comment]
Any other implementation (like @rauchg's suggestion for an `<img>` tag) would still end up in the Network tab.

**Comment by albinekb** [comment]
Sockets would only show up as one connection (on page load) I think @timneutkens

**Comment by ghengeveld** [comment]
I suggest long polling or server sent events instead of websockets.

**Comment by rauchg** [comment]
Prioritizing this now.

**Comment by albinekb** [comment]
See #4495
