### ISSUE TITLE
Hot Loading still happening on production?

### ISSUE THREAD

**Issue by tgoldenberg** [zeit/next.js#1366]
Not sure why this is happening. I'm sure that it's slowing down the server. 

I have two other apps on heroku that work just fine, and this never happens. For some reason, this one logs the hot loading information even in production (with `NODE_ENV=production`).

Any ideas why this might be happening? Thanks!

<img width="835" alt="screen shot 2017-03-06 at 4 27 50 pm" src="https://cloud.githubusercontent.com/assets/10930134/23630672/ecb8171a-0289-11e7-8825-6bd184148965.png">

**Comment by rauchg** [comment]
Can you re-open with more information? This doesn't really contain reproduction instructions.

**Comment by tgoldenberg** [comment]
That sounds reasonable. If I find an answer, I'll post here as well.
