### ISSUE TITLE
Link does not work for custom routing with express

### ISSUE THREAD

**Issue by Filipvdb321** [zeit/next.js#1367]
When I configure my express server like this:
```
const app = next({ dev });
const handle = app.getRequestHandler();
app.prepare()
  .then(() => {
    const server = express();

    server.get('/restaurant/:address', (req, res) =>
       app.render(req, res, '/restaurant', req.params)
    );

    server.get('*', (req, res) => handle(req, res));

    server.listen(3000, (err) => {
      if (err) throw err;
      console.log('> Ready on http://localhost:3000');
    });
  });
```

I can manually browse to the link: '/restaurant/restaurant-name' and it works fine. But when I go to the same link with next/Link it gives a page 404. The same happens with next/prefetch.

If I use the url with query parameters it works: /restaurant/?address=restaurant-name

I have a "restaurant.js" in the pages folder.

**Comment by sedubois** [comment]
How do you "go to the same link with next/Link"? Need to pass `as`. Actually I don't see in README the `as` documentation for declarative <Link> API. @timneutkens do you see it?

**Comment by Filipvdb321** [comment]
Hi @sedubois,
Thanks for the tip.
If construct the link like this it works:
```
<Link
          href={`/restaurant?address=${restaurant.address}`}
          as={`/restaurant/${restaurant.address}`}
        >
```

This could be indeed useful to mention in the documentation!

**Comment by timneutkens** [comment]
Yep. We need to document it.

**Comment by sedubois** [comment]
@timneutkens created https://github.com/zeit/next.js/pull/1378
