### ISSUE TITLE
How to enable Sourcemaps? 

### ISSUE THREAD

**Issue by easyrider** [zeit/next.js#137]
How to enable Sourcemaps?

**Comment by nkzawa** [comment]
Unfortunately, It's not supported for now.

**Comment by reflog** [comment]
Can you elaborate why? Any plans when this will be added?

**Comment by nkzawa** [comment]
It's just low priority. We'd like to add it sooner or later, or a PR will be appreciated 😄

**Comment by pksjce** [comment]
This could be solved by #40?

**Comment by kunokdev** [comment]
Any way to use source map as of Next.js v 2.4.0 ? It's kinda hard to debug with generated filenames and code...

**Comment by michelalbers** [comment]
any news on this?

**Comment by timneutkens** [comment]
Going to lock this. It's an issue from 28 october 2016. Latest canary has many improvements to sourcemaps.
