### ISSUE TITLE
Update Preact Example

### ISSUE THREAD

**Issue by kurtextrem** [zeit/next.js#1374]
Preact supports hot loading: https://github.com/developit/zero-to-preact/commits/master

(It seems to work anyway. I just removed React from the `using-preact` example and HMR still does its thing)

**Comment by kurtextrem** [comment]
Also `using-preact` is missing a `.babelrc` file (which is mentioned in the readme).

**Comment by lukeed** [comment]
The `.babelrc` isn't needed anymore. React is dropped via `module-alias` + the `next.config.js` changes.

**Comment by jgoux** [comment]
Hello,

@kurtextrem I just tried using preact + next.js, but removing all the conditional `if (dev)` give me this error : 
```
This module was not found:
* react-dom/lib/ReactReconciler in ./~/next/dist/client/next-dev.js
```

Here is a gist of all my files : https://gist.github.com/jgoux/e188f17f0b121684b3a6bbc0189e0cb5

What did I miss ?

**Comment by lukeed** [comment]
@jgoux You're missing `react-dom`. Next.js still requires a React environment in order to build & develop. As pointed out in #1564, the final output actually still includes React in the client bundle.

**Comment by jgoux** [comment]
Oh I miss this one, thanks for the quick reply @lukeed ! 👍
