### ISSUE TITLE
Preact + Express can't render server-side

### ISSUE THREAD

**Issue by kurtextrem** [zeit/next.js#1375]
If I call
```
app.renderToHTML
```

it will use `react-dom`'s `renderToStaticMarkUp` or `renderToString`. However, Preact doesn't have those, so aliasing doesn't do anything. Is there anything to make it work? (error: `Error: Cannot find module 'preact-compat\lib\ReactComponentTreeHook'`)
But there is the module `preact-render-to-string` - how could I implement that?

**Comment by timneutkens** [comment]
Is this based on https://github.com/zeit/next.js/tree/master/examples/using-preact?

**Comment by kurtextrem** [comment]
Yes, but I wanted to combine it with SSR caching (https://github.com/zeit/next.js/blob/master/examples/ssr-caching/server.js). Hence the `app.renderToHTML`.

**Comment by kurtextrem** [comment]
When I don't switch to Express / renderToHTML everything works fine.

**Comment by remkl** [comment]
@kurtextrem Would love to see a gist/example if you managed to resolve this issue? I am looking to do something similar

**Comment by kurtextrem** [comment]
Sure, that would be great :)

Am 15.04.2017 04:21 schrieb "Rem" <notifications@github.com>:

@kurtextrem <https://github.com/kurtextrem> Would love to see a
gist/example if you managed to resolve this issue? I am looking to do
something similar

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zeit/next.js/issues/1375#issuecomment-294266385>, or mute
the thread

**Comment by kurtextrem** [comment]
Sorry, I've misread your comment - no, I haven't solved it. However, there
are other boilerplates out there for Preact only SSR.

Am 15.04.2017 10:25 schrieb "Jacob G" <kurtextrem@gmail.com>:
