### ISSUE TITLE
[beta.21 and later] Setting timezone on the server (TZ env variable) does not work anymore

### ISSUE THREAD

**Issue by Zaiban** [zeit/next.js#1376]
It seems that on beta.21 and later the TZ env variable is not working, which causes server rendering to print incorrect time values.

Example: My app lives in a +2 timezone (Finland). Before beta.21 I could set TZ=Europe/Helsinki and everything would work fine (SSR and client displayed same values). But now, even though console.log(process.env.TZ) still prints "Europe/Helsinki" on the server console correctly, the values printed by moment(value).format('L') are 2 hours earlier on server than on the client.

**Comment by arunoda** [comment]
We need clear re-production info to test this.
Anyway, you have no way to access `process.env.TZ` in the client.
I suggest you to try some other timezone independant design and I'm pretty sure this is not related to Next.

Try to create a re-producible app with the issue.
If it's a Next.js one let's fix it.

In the meantime, I'll close this.
Reopen with the ^^^ info.
