### ISSUE TITLE
get current Route 'url' and 'as' info

### ISSUE THREAD

**Issue by Filipvdb321** [zeit/next.js#1377]
I see that the Router has some properties: pathname, query, ....
Is it possible to expose a method to get the current 'url' and 'as' ? 

That way you could for example save this in the state to navigate later to this location with Router.push(url,as);

Or is there already a better way to achieve this functionality?

**Comment by tpreusse** [comment]
Check out https://github.com/fridays/next-routes

Then you can reverse it with `(url.pathname || Router.route).replace(/^\//, '')` and `(url.query || Router.query)`. `url` refers to the property that page components get.

**Comment by arunoda** [comment]
Currently it's not supported. Not exactly(or just only) these APIs. We should provide some ways to improve this.

This is one step towards that: https://github.com/zeit/next.js/pull/1345

**Comment by tpreusse** [comment]
Also make sure to look at https://github.com/BDav24/next-url-prettifier

I think it would be great if something like `next-routes` api wise and `next-url-prettifier` feature set wise (multi language pretty urls) would be part of the core.

**Comment by matthewmueller** [comment]
I'm also looking for a way to access `as`, it seems like `document.location.pathname` and `Router.router.as` only gets updated after getInitialProps() has finished.

**Comment by Wolke** [comment]
I am looking,too

**Comment by arunoda** [comment]
Gonna close this since I'm going to close this pretty close: https://github.com/zeit/next.js/issues/1843
