### ISSUE TITLE
Display 404 error when using `next/link` for route that doesn't exist

### ISSUE THREAD

**Issue by leo** [zeit/next.js#1385]
At the moment, clicking on a `Link` component whose `href` attribute is a page that doesn't yet exist will show this:

<img width="302" alt="screen shot 2017-03-11 at 16 03 39" src="https://cloud.githubusercontent.com/assets/6170607/23824308/4db5d028-0674-11e7-9d7f-879cf9011f10.png">

When reloading the page, it shows this:

<img width="407" alt="screen shot 2017-03-11 at 16 03 47" src="https://cloud.githubusercontent.com/assets/6170607/23824312/585acd9e-0674-11e7-96ec-0a34c1f662da.png">

In my opinion, it should show the 404 error directly (without the user having to reload).

**Comment by arunoda** [comment]
Hey, I can't re-produce this.
Could you send me a sample or exact steps?

**Comment by rauchg** [comment]
@leo is this prod or dev mode?

**Comment by aranajhonny** [comment]
@rauchg @arunoda  in prod at zeit.co 
![zeit](https://cloud.githubusercontent.com/assets/9091881/23829573/a4d5f1ba-06b2-11e7-84d2-85ed0fa0deff.gif)

**Comment by leo** [comment]
Both.

**Comment by aranajhonny** [comment]
![next-bug](https://cloud.githubusercontent.com/assets/9091881/23833006/e881ca7a-0715-11e7-9335-ec7e19a1bf51.gif)

**Comment by aranajhonny** [comment]
In react dev tools. Shows that statusCode is null.
![captura de pantalla 2017-03-12 a las 7 07 18](https://cloud.githubusercontent.com/assets/9091881/23833193/a1b3dfd6-0718-11e7-9a77-fe4d9961d46c.png)
After recharging.
![captura de pantalla 2017-03-12 a las 7 07 40](https://cloud.githubusercontent.com/assets/9091881/23833209/cb3dfa12-0718-11e7-895e-49917bb6149a.png)

**Comment by aranajhonny** [comment]
I was reviewing, install all betas versions, testing this configuration and the last time this worked perfectly was with 2.0.0-beta.26. From that to the last, show this error.

**Comment by rauchg** [comment]
👍 We need to look at the diff then!

**Comment by timneutkens** [comment]
Believe I found the root of this issue. The documented `xhr` in the `ctx` of `getInitialProps` was removed in beta.27 and replaced by `jsonPageRes`. The error page is dependent upon `xhr`.
https://github.com/zeit/next.js#fetching-data-and-component-lifecycle

Writing a fix now.

**Comment by leo** [comment]
Awesome! Thx for fixing. 👌🏼

**Comment by timneutkens** [comment]
@leo ❤️
