### ISSUE TITLE
Next provides two URLs with different behaviors when page names are capitalized

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#139]
E.g if `pages/index.js` is renamed to `pages/Index.js`, it seems HMR doesn't work any more.

**Comment by impronunciable** [comment]
@sedubois It only doesn't work for the index. Good catch

**Comment by CompuIves** [comment]
Is this only the case for files with the name `index.js`?

**Comment by sedubois** [comment]
@CompuIves no, symptoms are the same with other page names, e.g `pages/About.js`.

But actually the bug description is inaccurate. If I create `pages/About.js` and run `next`:
- data is visible at both `http://localhost:3000/About` and  `http://localhost:3000/about`
- if I change the code, HMR works in `http://localhost:3000/About` but not in `http://localhost:3000/about`
- even if I manually reload `http://localhost:3000/about`, it does not show the new data

IMHO it's common practice to capitalize React component files, but they should only map to lowercase URLs (with proper HMR).

**Comment by eezing** [comment]
@sedubois

It does seem common practice to capitalize React component files. I've adopted this practice with one additional caveat: Capitalize files for reuseable components only.

A route file usually behaves as an entry point or container that has a very specific purpose, rarely ever being used more than once. Following the above practice, we wouldn't capitalize a route file.

**Comment by sedubois** [comment]
@eezing agreed, and now I stick to that. I opened the bug however, because it's still a bug 😄 and can get people confused
