### ISSUE TITLE
Optimized build

### ISSUE THREAD

**Issue by cia48621793** [zeit/next.js#1390]
I wanted to optimize my production build, but it seems like next.js really hates react-optimize...

~~Also, is there any options for me to enable JS (namely UglifyJS) compression?~~

**Comment by sergiodxa** [comment]
Next.js already use Uglify in production builds -> https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L122

**Comment by cia48621793** [comment]
@sergiodxa k...but how do you enable production build of next.js? Whenever I passes NODE_ENV as production, the bundle itself is still dev, and in next.config.js, still dev too.

**Comment by timneutkens** [comment]
You have to run `next build` and then use `next start` 👍 Regarding babel-preset-react-optimize. We have looked into adding this by default, but it gives a lot of issues with external dependencies. We do include the propTypes stripping babel plugin though.

**Comment by cia48621793** [comment]
With some tweaking, I got react-optimize working. idk, maybe partially.

**Comment by timneutkens** [comment]
Closing this. Please see https://github.com/zeit/next.js/pull/1075 for reasons 😄
