### ISSUE TITLE
_next not found when using express example

### ISSUE THREAD

**Issue by rgbkrk** [zeit/next.js#1391]
I've been using a setup based on the express example and noticed while in dev mode that e.g. `/_next/-/main.js` is not found. What needs to be added to an express configuration to pass more through to next.js?

**Comment by rgbkrk** [comment]
To partially answer my question, we'll want:

```
server.get("/_next*", (req, res) => handle(req, res)); 
```

Noting that you can't pass `handle` straight through because only the first two parameters match.

After doing this, there's a new 404 for webpack hmr which I haven't been able to work around. 
¯\\\_(ツ)\_/¯

**Comment by arunoda** [comment]
Use this too:

```
server.get("/_webpack*", (req, res) => handle(req, res)); 
```

**Comment by rgbkrk** [comment]
Thanks! It seems like something I'd love to add as documentation, yet is off the beaten path from the express example.
