### ISSUE TITLE
How do I get the cool loader bar like in the Zeit blog?

### ISSUE THREAD

**Issue by cia48621793** [zeit/next.js#1393]
It looks like Pace (or NProgress) ! So cool man!
But there isn't any isomorphic loading bar component out in the React ecosystem. Yes, I tried to make one, but it just feels un-natural, and I couldn't figure out how to place loading bar during AJAX/REST request...😂

**Comment by timneutkens** [comment]
@rauchg has mentioned he is going to do a write-up of how this was achieved soon. Closing this as duplicate of #88

**Comment by sedubois** [comment]
Isn't this answered by https://github.com/zeit/next.js/tree/master/examples/with-loading ?

**Comment by cia48621793** [comment]
＠sedubois Oh yeah!😂 I'm too lazy to find it out. 

But I couldn't make it shared across all pages. I've tried putting the router code on the `pages/_document.js`, but it didn't do anything.

**Comment by sedubois** [comment]
You need to use a HOC. Can check my example app: https://github.com/relatenow/relate

**Comment by mike3run** [comment]
@sedubois where should i look in your app for the proper example 😄 ?

**Comment by sedubois** [comment]
See withLayout HOC: https://github.com/relatenow/relate/blob/master/hocs/withLayout.js#L25

Wrapped this way:
https://github.com/relatenow/relate/blob/master/pages/index.js#L6
