### ISSUE TITLE
Address hosting on other cloud providers in the FAQ

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#1410]
Just got this question on slack:

> 1) How much control (if any) do you have over deployment to your own infrastructure ( say on AWS with Lamda—or has next been designed to work with `now`)

I feel like we should document that people can use `next` without using `now`, but still give a preference to `now` obviously 😉

**Comment by arunoda** [comment]
Yeah! I think this great.
Adding much more information to the README won't be working great.

So, my suggestion is create a Wiki Page and link it in the Deployment section.
In that, we can add more about deployment tools.
