### ISSUE TITLE
Using next.js with victory.js issue

### ISSUE THREAD

**Issue by alikhani** [zeit/next.js#1412]
Trying out next with victory and getting stuck in an infinite error loop.
<img width="1278" alt="screen shot 2017-03-14 at 13 11 03" src="https://cloud.githubusercontent.com/assets/1507144/23900110/36013ab2-08b8-11e7-8408-8f721163c034.png">

My page code looks like:
```
import { VictoryBar } from 'victory'

export default () => (
  <div>
    <VictoryBar />
  </div>
)
```

Running chrome on mac

**Comment by sedubois** [comment]
Which version of Next? 
Have you got code to reproduce the issue?

**Comment by alikhani** [comment]
I'm on the latest beta.. 
Here is an example: https://github.com/alikhani/next-victory

**Comment by cia48621793** [comment]
I was able to reproduce this problem:
```js
TypeError: Cannot read property 'props' of undefined
```
Seems more like a problem on the client side

**Comment by alikhani** [comment]
The issue seems to be a combination of both.
I've used victory with react-boilerplate before and haven't had any issues. Filed an issue there too: [#516](https://github.com/FormidableLabs/victory/issues/516)

next.js shouldn't get stuck in an error loop, even if the issue is in victory..

**Comment by arunoda** [comment]
This seems like an issue in our `patch-react.js`

**Comment by boygirl** [comment]
Victory uses an [inheritance inversion pattern](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/add-events.js#L4) to enhance components. I think that's what's not playing nicely with Next. I believe Radium uses this pattern as well. Let me know if there's something simple that can be done in Victory to ease the friction.

**Comment by arunoda** [comment]
Actually, it's because we are patching react.
But now we are going to remove it.
See: https://github.com/zeit/next.js/pull/1420

**Comment by arunoda** [comment]
@alikhani We released a new beta.
Try now with the latest beta.

**Comment by alikhani** [comment]
Yes works good now. Great job!
