### ISSUE TITLE
Analytics <script> in <Head/> cause syntax error for valid JS

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1413]
I have a analytics statement from Heap. When I tried to past this into the `<Head>` in `_document.js` or within any pages, it gets spit out as text on the site.

It gives me a module syntax error. But this is valid Javascript within the <script> tags. Is there something I need to do to make this work?

```
<script type="text/javascript">
    window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
      heap.load("00000000");
</script>
```

**Comment by impronunciable** [comment]
Hi @khrome83 you need to wrap your analytics code inside the `dangerouslySetInnerHTML` property, otherwise the code will be escaped. The following code for a sample page works for me:

```js
import Head from 'next/head'

export default () => <div>
  <Head>
    <script dangerouslySetInnerHTML={{ __html: `
    window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
      heap.load("00000000");
   `}} />
  </Head>
  <h1>Hola</h1>
</div>
```

Feel free to reopen the issue if you have more questions.

**Comment by khrome83** [comment]
awesome thank you

**Comment by moroshko** [comment]
From what I can see, adding a `<script>` using `dangerouslySetInnerHTML` just adds the code to the page, but doesn't execute it. Am I missing something?

Can we add an example of adding a `<script>` with content (like [above](https://github.com/zeit/next.js/issues/1413#issuecomment-286449156)) to [this list](https://zeit.co/blog/next2#more-examples)?

**Comment by khrome83** [comment]
@moroshko - we don't need it to be executed, we need it to be rendered from the server so when the page loads, the browser can execute it. This is no different than PHP and having PHP generate a inline script to be run when the page loads. 

This worked fine. We have used it multiple times since, both for third party and first party code we need to inline.

**Comment by moroshko** [comment]
@khankuan I see. It makes sense for SSR. In my case, I need the script to be executed when users navigate to a page on a client.

**Comment by khrome83** [comment]
@moroshko - just place it in a IIFE. When it loads it will run. You will need to have it in the <Head> component for the page that needs it. If you are loading it from _document.js and just want to call it when on that page, have the component that depends on it call a function off of window that runs that code. Once the code is in the site, it's just plain old vanilla JS. Don't need anything fancy.

https://developer.mozilla.org/en-US/docs/Glossary/IIFE
