### ISSUE TITLE
How to set env that can be accessed both by server and client?

### ISSUE THREAD

**Issue by zhaoyao91** [zeit/next.js#1415]
In Meteor, we can use the `SETTINGS` env.
In create-react-app app, we can set `REACT_APP_XXX`.

How to do similar things in Next.js?

**Comment by timneutkens** [comment]
Please have a look at https://github.com/zeit/next.js/tree/master/examples/with-universal-configuration 😄

**Comment by sedubois** [comment]
But I do think this raises a valid concern, that something easier ought to be baked-in. Why Next.js couldn't have a similar env var?

**Comment by zhaoyao91** [comment]
I have tried this in my app, but it complains:
![image](https://cloud.githubusercontent.com/assets/3808838/23906930/7ca58be2-090a-11e7-8f42-6f9eeea76022.png)

project structure
![image](https://cloud.githubusercontent.com/assets/3808838/23906981/9f200f76-090a-11e7-88a2-8ae196594520.png)

.babelrc
![image](https://cloud.githubusercontent.com/assets/3808838/23906984/a47c1f96-090a-11e7-9ef9-09eef9b3aed0.png)

env-config.js
![image](https://cloud.githubusercontent.com/assets/3808838/23906990/a9914042-090a-11e7-8bfa-d4421cd702f9.png)

usage in settings.js
![image](https://cloud.githubusercontent.com/assets/3808838/23906996/ade24b6e-090a-11e7-832c-0f8775e5d116.png)

**Comment by timneutkens** [comment]
Lets re-open it then.

**Comment by arunoda** [comment]
Here's how to fix this problem.

You need to have a value for "APP_SERVER_URL" always. So, do something like this:

```js
module.exports = {
  APP_SERVER_URL: process.env.APP_SERVER_URL || 'http://some.url'
};
```

And make sure to clean the babel cache by:

* Running `rm -rf node_modules/.cache` or 
* Changing the content inside the page.

**Comment by arunoda** [comment]
@zhaoyao91 Reopen again, it this doesn't fix your app.

**Comment by pauldariye** [comment]
I'm also getting the same error @arunoda . This issue might stem from a recent commit/update.

**Comment by arunoda** [comment]
@pauldariye did you follow my steps here: https://github.com/zeit/next.js/issues/1415#issuecomment-286489055

If that didn't work well, send me a sample repo.

**Comment by ex3ndr** [comment]
Can cache cleaning be avoided?

**Comment by timneutkens** [comment]
Check https://github.com/zeit/next.js/tree/canary/examples/with-universal-configuration-runtime

**Comment by griffithtp** [comment]
This might be what you are looking for ?
https://github.com/zeit/next.js#exposing-configuration-to-the-server--client-side
