### ISSUE TITLE
run `next start` in different environment variable

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1421]
How do we run `next start` with a different environment variable?

Right now it is set to `production` automatically. But in staging and development servers I would like to give it a different environment variable, because analytics requires a different include.

Is there a way to override the default behavior or `next start`?

**Comment by timneutkens** [comment]
Please see these 2 files. Setting `NODE_ENV` to production is just a default. You can override it.
https://github.com/zeit/next.js/blob/master/bin/next-build#L8
`NODE_ENV=staging next build`
https://github.com/zeit/next.js/blob/master/bin/next-start#L8
`NODE_ENV=staging next start`

**Comment by sarkistlt** [comment]
Hi, I still quit didn't get it what to override?
