### ISSUE TITLE
Alternative Router

### ISSUE THREAD

**Issue by DylanPiercey** [zeit/next.js#143]
Let me start by saying that I think this project is excellent and exactly what developers need to make isomorphic javascript 10x easier. The following is a shameless, but hopefully helpful, plug for my own library which I think is a perfect match for this module and could lighten up the codebase.

Alright - so it's called [Rill](https://github.com/rill-js/rill) and it is a router that was built from the ground up to be both familiar (Koa/Express like) and isomorphic. It brings a node style http server into the browser and allows developers to pretend they are writing 'server only' code but actually makes code that is suitable for and runs well in the browser.

I see this library providing a few cool features to Next.js should the two operate together and I couldn't help but propose them here.

---

### No more `<Link>`s.
Rill makes this easy for developers by intelligently intercepting all `<a>` clicks and `<form>` submissions and pumping them through a local router. This means that developers get to write the same old forms and navigation they were used too. It also works perfectly should javascript fail since these links and forms can also be handled by Rill in the server side.

### Awesome middleware/plugins.
Rill exposes the same style of middleware system many developers are familiar with which is similar to Express/Koa. There is already a decent list of [plugins](https://github.com/rill-js/rill/wiki) and the beauty of it is that they are all 100% isomorphic.

Also Rill provides the ability to run middleware both before and after rendering a page which can be tremendously useful.

### Supports multiple template engines.
Currently Rill supports [react](https://github.com/rill-js/react) and also supports [plain html](https://github.com/rill-js/html) (which does diffing similar to react) and allows for all sorts of template engines such as handlebars, pug, ejs, or anything else that outputs html.

---

Feel free to close this issue as I definitely understand that this would lead to some breaking API changes and probably a decent chunk of work from both parties.

**Comment by rauchg** [comment]
> Rill makes this easy for developers by intelligently intercepting all <a> clicks and <form> submissions and pumping them through a local router.

I like explicit over implicit. Higher-order components like `<Link />` can also be composed, like we plan to do with `next-link-prefetch` to trigger automatic prefetching on the background.

Thanks for taking the time to write this!
