### ISSUE TITLE
Problem is custom server

### ISSUE THREAD

**Issue by Andrei997** [zeit/next.js#1431]
Hey there, I am having a custom server for next with this configuration

`const express = require('express');
const next = require('next');
const axios = require('axios');
const credentials = require('./config/credentials');

const dev = process.env.NODE_ENV !== 'production';
const app = next({dir: '.', dev});
const handle = app.getRequestHandler();

//api
const api = require('./routes/api');

app.prepare().then(() => {

    //initalizing the server
    const server = express();

    //setting up the routes
    server.use('/api', api);

    //todo: redirect to video in case of video path!
    server.get(/recordings/, (req,res,next)=> {
        if(req.path.indexOf("/recordings/video") > -1){
            let paramsString = req.path.substr(18);
            let category = paramsString.substr(0,paramsString.indexOf('/'));
            let date = paramsString.substr(paramsString.indexOf('/') + 1);
            date = date.substr(0,date.length - 4);
            res.redirect(`/video?category=${category}&date=${date}`);
        }
        else next();
    });
    server.get('*', (req,res)=> handle(req,res));

    //listening on port
    server.listen(9000, err=> {
        if (err) throw error;

        console.log("App running on port 9000");
    })

}).catch((err)=> {
    console.log(err);
    throw error;
});`

For some reason when navigating to pages i am getting this error: 

> 
Client pings, but there's no entry for page: /recordings
> Building page: /recordings

This doesn't happen when starting the app with next, any idea what it might be ?

**Comment by retrospct** [comment]
@Andrei997 did you figure out why you were getting this error? Could you post the resolution for others who come across this problem?

I seem to be getting it too and haven't figured out what it is yet. Thanks!

**Comment by Andrei997** [comment]
@retrospct My problems were coming from an external script, videoJS in this case, and I managed to fix it by adding the script in the html file not in the next Head component. However I stopped using next as it was a bit of an overkill for my project
