### ISSUE TITLE
How do I make tests in next.js apps?

### ISSUE THREAD

**Issue by renatorib** [zeit/next.js#1434]
Since next uses webpack under the hood, I can't integrate jest, ava, etc. because my files are written in babel syntax without explicity transpiling (webpack will transpile)
Has anyone done tests on an app using next?

I wonder how it was done.

**Comment by sergiodxa** [comment]
In the examples folder there is one with Jest
https://github.com/zeit/next.js/tree/master/examples/with-jest

**Comment by renatorib** [comment]
Lol, I searched as "with-test" and "test" in examples and found nothing. I'll take a look.

**Comment by timneutkens** [comment]
@renatorib we have a slack integration in a slack channel with 2200 people 😅 Feel free to join https://zeit.chat/
