### ISSUE TITLE
How can I change a url like `profile?id=nkzawa` to a pretty url `/nkzawa`

### ISSUE THREAD

**Issue by rickypaun** [zeit/next.js#144]
Probably It's a beginner question. But I would use a base page with parameters but set a pretty url.

**Comment by dstreet** [comment]
I believe what you are currently looking for is being explored in #59 and #91

**Comment by TooTallNate** [comment]
Back in the PHP days you'd use nginx and `rewrite`, but as @dstreet mentioned it looks like there's built-in alternatives being considered.

**Comment by nodegin** [comment]
Take a look at PR #147

**Comment by rauchg** [comment]
Like @tootallnate mentioned, a front-proxy would *already* solve your problem. For example, nginx+lua could look up `/:username` and re-write it to `/user?id=`. That said, we're already working on exposing the underlying request/response server primitives on #25
