### ISSUE TITLE
IE11 styles are not working when navigating between pages

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1444]
When using the Router (imperative) to push a user to a new page, the user does not see any styles on the next page for components that are loaded within the content section of that page. 

```
    Router.push(href).then(() =>
      window.scrollTo(0, 0)
    );
```

Scenario - 
* User users address bar to navigate to Page A, sees everything correct.
* User clicks link to navigate to Page B, Header/Footer render correct, all content inside are missing styles.
* User refreshes Page B, everything is rendered correctly.
* User clicks link to navigate to Page A, Header/Footer render correct, all content inside are missing styles.

**Comment by arunoda** [comment]
@khrome83 could you send us a sample project to re-produce this locally.

**Comment by khrome83** [comment]
@arunoda - sure done!

https://github.com/khrome83/ie11-styling-issues

When making this, I realized that I used the default next/link from the hello world example. The imperative approach does the same thing as the default link. 

I also realized that I am using a `_document.js` where I received some help to flush the old styles. I included that as well. 

I validated that this project also causes the same bug, by using `ngrok` and testing on SauceLabs. 

When you enter the first page on IE11 (Windows 8.1 & Windows 10 verified), it will show the text as the correct color. When navigating, it will show it plan text, un-styled.

IF you navigate before the page finishes downloading (spinning circle in tab), then you can see the behavior where it does a full page refresh and appears to work correctly. Make sure you wait for the page to full render before you navigate.

**Comment by khrome83** [comment]
@arunoda we made a work around where we test if IE11 or lower and use a regular link. 

We had already abstracted a <Link> component around the <NextLink> for styling purposes and some other reasons. So the 1 line of code made it easy. If we detect IE11, we use normal link, and the site is treated like a static site for all IE users.

**Comment by philipheinser** [comment]
@arunoda I get the same error on zeit.co when i go to the home page on ie11 and then click on blog there are no styles.
![zeit](https://user-images.githubusercontent.com/3705499/26842898-a43d21ee-4aee-11e7-88a9-c70537810665.PNG)

**Comment by philipheinser** [comment]
@khrome83 can you post how you implemented the workaround? we need something like this.

**Comment by timneutkens** [comment]
I wonder if the styled-jsx upgrade fixed this 🤔

**Comment by khrome83** [comment]
We have not tried to remove this line below to see if it works. But we did create our own link, which then uses Route directly. This allowed us to do a number of things we needed (remapping urls to render correctly, supporting dynamic link modification for localization. 

The following code checks if it's a IE11 or lower device, and then set the incoming URL to the window.location.href. We do this before we do any router events. IE11 users will make the call coming directly from the server.

```
if (!!window.MSInputMethodContext && !!document.documentMode) {
      window.location.href = url;
      return;
}
```
When i get a chance i can see if this is resolved for older browsers by commenting out that line.
