### ISSUE TITLE
Building for production with custom server

### ISSUE THREAD

**Issue by Andrei997** [zeit/next.js#1445]
Hey there, quick on the question. I am running next build in the project directory and then starting my custom server in production mode `NODE_ENV=production node server` but I am getting tis error 

> Error: Cannot find module '/Users/andreiungureanu/WebstormProjects/internal-issuuinfo/.next/build-stats.json'

Any ideas on what to do ? Or is there any other way to set the production mode ?

**Comment by impronunciable** [comment]
@Andrei997 did you run `npm run build` before?

**Comment by arunoda** [comment]
As @impronunciable mentioned, you need to build your app first.
