### ISSUE TITLE
File-loader as default

### ISSUE THREAD

**Issue by SeeThruHead** [zeit/next.js#145]
Even if/when you add custom webpack config, having image/font loading as default would be a great addition to this project.

React-create-app is a great example of this default working really well in the wild.
Users who want to use the feature opt in by importing files with appropriate extensions in their JS, everyone else is completely unaffected.

**Comment by nkzawa** [comment]
I'm not a fan of these loaders since it's webpack specific.

**Comment by rauchg** [comment]
I don't think it's the job of webpack nor the framework to load images or fonts. We do automatically expose `static/`. Is that not sufficient?

**Comment by SeeThruHead** [comment]
It's definitely an opinion, albeit a popular one. Since it doesn't affect anyone that doesn't want to use the feature, I'm sure many people would consider it a welcome addition.

**Comment by nkzawa** [comment]
I think users would feel using the loader is recommended if we add it as default.
Close for now since we're not sure if it's really needed. We can reconsider if got many requests.
