### ISSUE TITLE
Css not being applied with react-md

### ISSUE THREAD

**Issue by ammark47** [zeit/next.js#1451]
I am trying to setup react-md for my project by following the example. Unfortunately, the css was not being applied. I tried cloning the example but I am running into the same issue.

The image below is the example running on my computer. 

<img width="958" alt="with-react-md" src="https://cloud.githubusercontent.com/assets/12992026/24054716/875f81fe-0b13-11e7-9628-4f32ddfe2531.PNG">

**Comment by arunoda** [comment]
Could you check the example in this repo: https://github.com/zeit/next.js/pull/940?
You may also want to define the user-agent on the server [like this](https://github.com/zeit/next.js/blob/13ccf784986107a339218b3d43a7e4ce3bdfd919/readme.md#fetching-data-and-component-lifecycle).

**Comment by ammark47** [comment]
Thanks @arunoda, that worked

credit to @alexedev
> cd into static and then run ln -s ../node_modules/react-md/dist/react-md.light_blue-yellow.min.css react-md.light_blue-yellow.min.css 

Also, whats the signif of this >You may also want to define the user-agent on the server like this. ?
