### ISSUE TITLE
Disable React Dev Tools in Production

### ISSUE THREAD

**Issue by vimcat** [zeit/next.js#1452]
Users should not be able to use React Dev Tools in Production sites. Please disable if not in dev:

https://github.com/facebook/react-devtools/issues/191

**Comment by arunoda** [comment]
As mentioned in this comment(https://github.com/facebook/react-devtools/issues/191#issuecomment-138426283) this has no real effect.

But, If you wanna do it you can do it.
Use our [custom Document](https://github.com/zeit/next.js#user-content-custom-document) feature.

**Comment by vimcat** [comment]
Hasn't React loaded by the time it gets to _document.js ?

**Comment by sergiodxa** [comment]
@vimcat `_document.js` is only rendered server-side, you can write the line to disable the devtools inside an script before `NextScript`, that way it's executed before React.
