### ISSUE TITLE
Custom source directory

### ISSUE THREAD

**Issue by cia48621793** [zeit/next.js#1455]
We should be able to set a special location for our source files, e.g. 'src/', rather than spreading our sources linearly.

**Comment by timneutkens** [comment]
Is this what you mean? https://github.com/zeit/next.js/pull/936

**Comment by arunoda** [comment]
@cia48621793 could you explain a bit more about what you are saying. We don't have too strict rules on page layout.

We only have the `pages` directory to put your pages.

But, you can do a lot of configurations with the [custom server API](https://github.com/zeit/next.js#custom-server-and-routing).

**Comment by cia48621793** [comment]
Given base project folder '/', I would rather put my page components in '/src/pages', rather than '/pages', since all my other components are also in '/src'
And yea, it's exactly #936, dup
