### ISSUE TITLE
React-loadable

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1460]
Could it be used somehow to improve loading and simplify the codebase?
https://medium.com/@thejameskyle/react-loadable-2674c59de178#.gu0karf8q

**Comment by arunoda** [comment]
Actually, what's going on here in the dynamic `import` functionality.
React loadable is a simply wrapper to use it with React component.

Webpack do support it. Current Next.js is not supporting that.
But we've a experiment branch [here](https://github.com/zeit/next.js/tree/import-then).

It support SSR as well. (You need to send the component with `getInitialProps()`)

Here's an [example](https://github.com/zeit/next.js/tree/import-then/examples/with-dynamic-import).

This will be a post 2.0 feature and we are [tracking it here](https://github.com/zeit/next.js/issues/728).
