### ISSUE TITLE
Provide an API to make next extensible

### ISSUE THREAD

**Issue by wagerfield** [zeit/next.js#1461]
Firstly, `next` is absolutely awesome—thank you so much for creating such a great framework.

However, I would really like to see an API for third parties to hook into and extend it.

There are a lot of great examples in the repo using Inferno, Preact, Styletron, Aphrodite, Glamor etc. but they typically require a custom server ([which has some ramifications](https://github.com/zeit/next.js/pull/1388)), a `.babelrc` and `next.config.js`. Though configuration of these libs is pretty straightforward, it is something that has to be repeated from project to project and detracts from Next's purity.

When using React and Styled JSX _everything just works_. I would like the same experience out of the box for my preferred setup of libs x, y and z and given the number of aforementioned examples in the `next.js` repo, it would seem this is a shared feeling.

Proposal: `next` presets and plugins.

My preferred flavour is Inferno + Styletron since they are the 2 most performant libs out there for rendering HTML and styling it.

I started creating a package with the aim of swapping out React for Inferno (during production) BUT without the need for adding a custom server, `.babelrc` and `next.config.js` in user-land code. As I mentioned above, I wanted to create the same experience you get with Next in it's purest form, but with Inferno and possibly Styletron—no project level configuration necessary.

The package is called `neno` (next + inferno) and my idea was that you called `neno` in place of `next` from your package scripts (or command line). Doing so would set the module aliases for next's server (mapping `react` to `inferno-compat`), configure babel and webpack then forward on `process.argv` to `next`. You would continue to use `next` in your source code, importing modules like `Link`, `Router` etc. from it.

https://www.npmjs.com/package/neno

However having spent some time looking through Next's source I realised this wasn't going to be possible since so much of next is hard coded to reading a few very specific files (`.babelrc`, `next.config.js`, `pages/*`, `_document.js`, `_error.js`) in the `cwd`. There is currently no API, or opportunity to hook into this pipeline (at least as far as I can tell).

I thought about reimplementing next's simple CLI in `neno`, building the webpack config, compiler etc. from `next/dist/server/build/webpack.js` and trying to insert my config in the middle so that it extended next's but still allowed the user to overwrite it in their project...but that quickly started to feel like I was crowbarring stuff in and repeating code unnecessarily. I wanted `neno` to be a very lean wrapper around `next`—essentially just configuring it in a neat package rather than in a project.

So what might a solution look like?

Well in the same way that `babel`, `eslint` etc. have both a `preset` and `plugin` ecosystem, I thought that `next` should both enable and promote a similar interface so that third parties could create packages for it.

These plugins and presets could be easily configured in your package.json using a `next` field like so:

```json
{
  "scripts": {
    "dev": "next"
  },
  "next": {
    "presets": [
      "inferno",
      "styletron"
    ]
  },
  "dependancies": {
    "next": "latest",
    "next-preset-inferno": "latest",
    "next-preset-styletron": "latest"
  }
}
```

Preset authors would be able to easily override babel and webpack, setup aliases and the like. 

Plugin authors could augment `next` modules, add new ones etc.

Would love to what your thoughts are on this 😄

**Comment by arunoda** [comment]
It's unlikely we are not going to change the `.babelrc` behaviour since that's the standard for any project. 

And I like to have following API options with next's programmatic API.

* Option to set the default `Document`
* Option to set the default `Error`
* Path to look for the Next.js config

Since you are using next in your own source code. You can alias modules like React in the server.
Also since we allow to pass a custom path for the Next.js config, you could do anything with Webpack as well.

I think with ^^^ options you could do a lot.
Other than that, we don't think of having a plugin system.

**Comment by PanJ** [comment]
@arunoda 
I am thinking of this as well. First of all, Next is an awesome work. I have just deployed it in production. For me, the part that adds friction adopting Next in production that it is opinionated, while the whole React ecosystem is unopinionated. It is true that you can still follow the examples to add this and that to your Next project. But not knowing the magic behind, it makes me feel I am having less control.

In my fancy dream, we could extract the parts that Next was doing out of its core. The core's functionality is just to pass data between parts. Those parts could consist of

- **Router**: maps the url into component (The existing opinionated Router maps url to `pages` directory structure)
- **Rendering**: takes in the url params and component from Router and render to HTML.
- **Styling**: Process and inject inline style to HTML and/or compile styles into css files
- **State Hydration**: Transfer server-side state to client.
- **Hooks**: Any internal event can be pre/post hooked by external plugins. Getting some configs can also be an event (webpack, `.babelrc`). This could make those examples a one-liner.

I know that the internal magic behind is very complicated but if we could dissemble the parts like so, it will be highly extensible and unopinionated. I am already excited what could it achieve.

**Comment by arunoda** [comment]
Now we've a way to pass the Next.js config purely as an option: https://github.com/zeit/next.js/pull/2058/

**Comment by timneutkens** [comment]
I'm going to close this as we have next-plugins now, they'll be more powerful in the future.
