### ISSUE TITLE
Add resolver to root dir

### ISSUE THREAD

**Issue by guidiego** [zeit/next.js#1463]
Guys, Next today not working with non-relative paths. I was thinking in implement something using that: https://github.com/tleunen/babel-plugin-module-resolver

The big deal is: When use a custom server, with a custom DIR, where in next can I edit the babel settings for look the root as the config dir and not the original root dir?

**Comment by arunoda** [comment]
Are you looking for something like [this](https://github.com/entwicklerstube/babel-plugin-root-import)?

Anyway, could you explain a bit more about what you are trying to achieve?

**Comment by guidiego** [comment]
@arunoda I think that both have the same solution with different approaches. The point here, is why not do this in Next `.babelrc` point to the root dir of the project. :thinking:

**Comment by arunoda** [comment]
> The point here, is why not do this in Next .babelrc point to the root dir of the project

Sorry. I didn't get this?

**Comment by guidiego** [comment]
The last time that I try, next not have module-resolver in your core @arunoda. I have to use relative paths every where, in a structure with many namespaces, we need to use much `../../../` and this can be a little confuse. My ideia is implemente ono of this plugins in next to point the root of the project for people can call modules direct from root and stop to using relative :)

**Comment by fdaciuk** [comment]
@guidiego you can make your own webpack configuration, [adding alias](https://github.com/zeit/next.js/blob/master/examples/using-preact/next.config.js#L9-L12) to solve this problem.

To use this in server side, just use [`module-alias`](https://github.com/zeit/next.js/blob/master/examples/using-preact/server.js#L7-L8).

This way worked for me =)

**Comment by arunoda** [comment]
I think there's something similar too.
We are not going to do this in the core.

Just simply add a babel-plugin. I prefer this: https://github.com/tleunen/babel-plugin-module-resolver

And @fdaciuk mentioned some other cases too.
We'll may think something about this later on.  But not now.
