### ISSUE TITLE
How to selectively include/exclude a set of react components by viewport size?

### ISSUE THREAD

**Issue by Ajar-Ajar** [zeit/next.js#1464]
Hi all,

Is there a way to use SSR and render a different set of components on the first render 
depending on the user's viewport width like we do in CSS media queries?

My guess is there isn't since you need JS/CSS to first run on the client and determine that...
So how would you go about rendering a different set of components on different media queries without loading those, to begin with? is there a way to selectively lazy load them or any other way you see as relevant?

Obviously, the underlying motivation to do so in the first place is to have the optimal performance, so if you think this is not a bit issue if you load two sets of components as long as you render only one of them - I would like to hear your opinion too.

Thank you 
Ajar

**Comment by arunoda** [comment]
@Ajar-Ajar I don't think that's possible.
Even if you find a way to do so, browser will download all the components used in that page.
So, I don't find any performance improvement in that.

**Comment by Ajar-Ajar** [comment]
Thank you @arunoda :)

**Comment by sergiodxa** [comment]
@Ajar-Ajar you can verify (manually) what's the minimum required server-render for all possible viewports and only server render that, then in the browser you render the rest using progressive render (https://github.com/zeit/next.js/tree/master/examples/progressive-render), similar to Netflix.

The client is still download all components, but you can reduce the amount of server-rendered components, and the amount of HTML you send to the browser.
