### ISSUE TITLE
Import jQuery to next.config.js

### ISSUE THREAD

**Issue by diskokevin** [zeit/next.js#1465]
Hi,

Is there any way to add a new providerPlugin to the next.config.js file and make a plugin accessible from anywhere in my app. 

Example: This is my next.config.js

```
const webpack = require('webpack');

module.exports = {
  webpack: (config, { dev }) => {

    config.plugins.push(
      new webpack.ProvidePlugin({
        '$': 'jquery',
        jQuery: 'jquery'
      })
    );

    return config
  }
}
```

And if I try to console.log(jQuery) from my index.js file: 
```
import React from 'react';

module.exports = () =>
  console.log(jQuery);
```

I still can't access jQuery on the server side, so I get an exception: 
``` ReferenceError: jQuery is not defined ```

In the end my goal is to import Foundation which has a jQuery dependency and then can't be imported properly in my app.
Thanks for the help!

**Comment by arunoda** [comment]
@diskokevin Try to do this with a babel plugin.

**Comment by diskothibautha** [comment]
Here is my workaround for loading foundation:

```
//next.config.js

const webpack = require('webpack')

module.exports = {
  webpack: (config, { dev }) => {
      console.log('try: ',config);
  config.plugins.push(
      new webpack.ProvidePlugin({
              '$': 'jquery',
                'jQuery': 'jquery',
          })
  )
    return config
  }
}
```

```
//index.js

import React from 'react';
import $ from 'jquery';

export default class Index extends React.Component {

  componentDidMount(){
    let foundation = require('foundation-sites');
    $(document).foundation();
  }
}
```
Work with next.js 2.0.0

**Comment by arunoda** [comment]
Since @diskothibautha's solution is pretty great, I'm gonna close this.

**Comment by diskokevin** [comment]
Thanks @diskothibautha! Amazing ;)

**Comment by baruchvlz** [comment]
When trying to use @diskothibautha 's solution, I'm running into this little ordeal.

<img width="2115" alt="screen shot 2017-08-21 at 19 32 48" src="https://user-images.githubusercontent.com/14321495/29531166-a5d1c1b4-86a7-11e7-9ec8-1be5e723b2ac.png">
