### ISSUE TITLE
Safari Error

### ISSUE THREAD

**Issue by mikearnaldi** [zeit/next.js#1466]
In development mode using safari navigation through pages output this:

`TypeError: null is not an object (evaluating 'publicInstance.updater')
forceUpdateIfPending@http://localhost:3000/_next/-/main.js:26231:33
traverseRenderedChildren@http://localhost:3000/_next/-/main.js:26209:11
traverseRenderedChildren@http://localhost:3000/_next/-/main.js:26216:33
traverseRenderedChildren@http://localhost:3000/_next/-/main.js:26212:29
traverseRenderedChildren@http://localhost:3000/_next/-/main.js:26212:29
traverseRenderedChildren@http://localhost:3000/_next/-/main.js:26212:29
traverseRenderedChildren@http://localhost:3000/_next/-/main.js:26212:29
traverseRenderedChildren@http://localhost:3000/_next/-/main.js:26212:29
traverseRenderedChildren@http://localhost:3000/_next/-/main.js:26216:33
traverseRenderedChildren@http://localhost:3000/_next/-/main.js:26212:29
traverseRenderedChildren@http://localhost:3000/_next/-/main.js:26212:29
deepForceUpdate@http://localhost:3000/_next/-/main.js:26244:27
componentWillReceiveProps@http://localhost:3000/_next/-/main.js:35671:22
measureLifeCyclePerf@http://localhost:3000/_next/-/main.js:28067:14
updateComponent@http://localhost:3000/_next/-/main.js:28602:29
receiveComponent@http://localhost:3000/_next/-/main.js:28539:25
receiveComponent@http://localhost:3000/_next/-/main.js:5884:38
_updateRenderedComponent@http://localhost:3000/_next/-/main.js:28746:39
_performComponentUpdate@http://localhost:3000/_next/-/main.js:28716:34
updateComponent@http://localhost:3000/_next/-/main.js:28637:35
receiveComponent@http://localhost:3000/_next/-/main.js:28539:25
receiveComponent@http://localhost:3000/_next/-/main.js:5884:38
updateChildren@http://localhost:3000/_next/-/main.js:27906:41
_reconcilerUpdateChildren@http://localhost:3000/_next/-/main.js:32689:46
_updateChildren@http://localhost:3000/_next/-/main.js:32793:56
updateChildren@http://localhost:3000/_next/-/main.js:32780:27
_updateDOMChildren@http://localhost:3000/_next/-/main.js:29951:26
updateComponent@http://localhost:3000/_next/-/main.js:29769:28
receiveComponent@http://localhost:3000/_next/-/main.js:29731:25
receiveComponent@http://localhost:3000/_next/-/main.js:5884:38
_updateRenderedComponent@http://localhost:3000/_next/-/main.js:28746:39
_performComponentUpdate@http://localhost:3000/_next/-/main.js:28716:34
updateComponent@http://localhost:3000/_next/-/main.js:28637:35
receiveComponent@http://localhost:3000/_next/-/main.js:28539:25
receiveComponent@http://localhost:3000/_next/-/main.js:5884:38
_updateRenderedComponent@http://localhost:3000/_next/-/main.js:28746:39
_performComponentUpdate@http://localhost:3000/_next/-/main.js:28716:34
updateComponent@http://localhost:3000/_next/-/main.js:28637:35
receiveComponent@http://localhost:3000/_next/-/main.js:28539:25
receiveComponent@http://localhost:3000/_next/-/main.js:5884:38
performUpdateIfNecessary@http://localhost:3000/_next/-/main.js:28551:39
performUpdateIfNecessary@http://localhost:3000/_next/-/main.js:5916:46
runBatchedUpdates@http://localhost:3000/_next/-/main.js:3119:45
perform@http://localhost:3000/_next/-/main.js:15451:24
perform@http://localhost:3000/_next/-/main.js:15451:24
flushBatchedUpdates@http://localhost:3000/_next/-/main.js:3141:26
flushBatchedUpdates@[native code]
closeAll@http://localhost:3000/_next/-/main.js:15517:29
perform@http://localhost:3000/_next/-/main.js:15464:24
enqueueUpdate@http://localhost:3000/_next/-/main.js:3169:36
enqueueUpdate@http://localhost:3000/_next/-/main.js:17212:29
enqueueElementInternal@http://localhost:3000/_next/-/main.js:17404:18
http://localhost:3000/_next/-/main.js:20323:46
scrollMonitor@http://localhost:3000/_next/-/main.js:20311:19
_updateRootComponent@http://localhost:3000/_next/-/main.js:20322:29
_renderSubtreeIntoContainer@http://localhost:3000/_next/-/main.js:20409:40
_callee3$@http://localhost:3000/_next/-/main.js:25788:38
tryCatch@http://localhost:3000/_next/-/main.js:12466:44
invoke@http://localhost:3000/_next/-/main.js:12701:30
step@http://localhost:3000/_next/-/main.js:2117:30
Promise@http://localhost:3000/_next/-/main.js:7219:15
http://localhost:3000/_next/-/main.js:2114:33
tryCatch@http://localhost:3000/_next/-/main.js:12466:44
invoke@http://localhost:3000/_next/-/main.js:12701:30
step@http://localhost:3000/_next/-/main.js:2117:30
Promise@http://localhost:3000/_next/-/main.js:7219:15
http://localhost:3000/_next/-/main.js:2114:33
onError@http://localhost:3000/_next/-/main.js:21320:14
tryCatch@http://localhost:3000/_next/-/main.js:12466:44
invoke@http://localhost:3000/_next/-/main.js:12701:30
step@http://localhost:3000/_next/-/main.js:2117:30
http://localhost:3000/_next/-/main.js:2130:17
run@http://localhost:3000/_next/-/main.js:7115:29
http://localhost:3000/_next/-/main.js:7128:31
flush@http://localhost:3000/_next/-/main.js:6642:11`

In chrome & firefox is working fine. In production mode outputs a 505.

**Comment by mikearnaldi** [comment]
was an unrelated error, I was using a functionality of the DOM that safari doesn't support.

**Comment by martinhorsky** [comment]
@mikearnaldi Can I ask about details? I am getting same error and i dont know what I am doing wrong. Thx
