### ISSUE TITLE
Universal configuration on files in the /static folder?

### ISSUE THREAD

**Issue by czzarr** [zeit/next.js#1471]
Hi,

I have followed the universal configuration example (https://github.com/zeit/next.js/tree/master/examples/with-universal-configuration) and it works well but it seems not for a `js` file in the `/static` folder.
How can I make this work?

The reason I have to serve this `js` file is because I'm using the google javascript api for authentication and as it maintains state by itself I chose to have it completely separate from my react app.

Thanks

**Comment by arunoda** [comment]
As @sergiodxa mentioned we don't do that for static files.
If you wanna a export some keys, try to set it to the window by writing a [custom document](https://github.com/zeit/next.js#custom-document).
