### ISSUE TITLE
How to scale next.js

### ISSUE THREAD

**Issue by cia48621793** [zeit/next.js#1477]
Seems like a simple cluster+custom handler wouldn't work in this case...

**Comment by arunoda** [comment]
Why not?
One you build the app, it's a typical Node.js app.
Try using with the custom server API.

Also, you could use docker and any other scaling solution to scale your app.

**Comment by arunoda** [comment]
You may need this too: https://github.com/zeit/next.js/wiki/Deployment

**Comment by arunoda** [comment]
If this didn't helped you, reopen with steps to reproduce any deployment related issues.
