### ISSUE TITLE
How would I implement an authentication workflow?

### ISSUE THREAD

**Issue by roderik** [zeit/next.js#148]
I usually do a "onEnter" on React Router to check and redirect to a login page.

Running the check in getInitialProps? But that does not feel right...

**Comment by sedubois** [comment]
React-Router v4 solves this by using the React component lifecycle directly (`componentWillMount` etc). I raised the same question here: https://github.com/zeit/next.js/issues/91#issuecomment-257079677

**Comment by sedubois** [comment]
Actually I correct that, it's solved like this: https://react-router.now.sh/auth-workflow

**Comment by nkzawa** [comment]
https://github.com/zeit/next.js/issues/25 would resolve this issue too, since you can have any auth logics on your server.

**Comment by mcassie566** [comment]
Thanks, game time.

**Comment by rauchg** [comment]
Also, to be perfectly clear, for most use cases you *don't need* #25. That'd be only necessary if you don't even want to ship the component _code_ (not _data_) according to authentication rules.

We perform authentication on `zeit.co` by re-using an `authenticate` method in `getInitialProps` across all the pages that require authentication.

**Comment by rauchg** [comment]
Logged as #153

**Comment by nkzawa** [comment]
@rauchg A problem is you can't properly redirect unauthorized requests.

**Comment by jaredpalmer** [comment]
@rauchg You store your sessions on api.zeit.com rather that on zeit.com correct?

**Comment by luisrudge** [comment]
@rauchg what you do when the user is not authenticated?

**Comment by bhurlow** [comment]
@rauchg can you elaborate on how you manage authentication in `getInitialProps`? 

This makes sense to me for client side auth – could store token in browser. What about for when pages are rendered server side? E.g. with a `<Link/>` tag

**Comment by luisrudge** [comment]
@bhurlow you'll probably need a cookie.

**Comment by bhurlow** [comment]
@luisrudge I ended up having the backend API manage the cookie placement

**Comment by timneutkens** [comment]
Closing in favor of #153
