### ISSUE TITLE
Serving a next.js app from a subroute

### ISSUE THREAD

**Issue by robstolarz** [zeit/next.js#1482]
I want to serve a next.js app from inside a node module, to be included as an Express route in a larger application. I can route requests to the next app pretty easily, and server-side rendering works well. However, it gets the links wrong (e.g. linking to `/about` rather than `/<subdir>/about`) and the `/_next` folder is not routed properly which messes up the app.

How would I go about serving a next.js app from a subroute?

**Comment by arunoda** [comment]
Currently that's not possible.
We are tracking it here: https://github.com/zeit/next.js/issues/257
