### ISSUE TITLE
Immutable, multi-environment Docker deployments 

### ISSUE THREAD

**Issue by keeth** [zeit/next.js#1488]
Hello! I just finished porting a small universal app from [React Server](https://react-server.io/) to next.js. Yay! Loving it so far. 🎉

One feature I'm missing from React Server is the ability to pass environment-specific config (e.g. a REST API endpoint) into the app at start time.  Keeping environment configuration out of the build artifacts means I can have a single Docker image which can be tested on a staging cluster and then deployed to production, without having to rebuild.

React Server's way of doing this is described [here](https://react-server.io/docs/guides/production), (scroll down to _If you want to pass per-environment configuration settings to YOUR application_). It's not the most elegant solution but it does solve this problem.

The `with-universal-configuration` example suggests using the transform-define babel plugin to inject configuration into the app, but this freezes config at build time, producing environment-specific artifacts.

Is there a mechanism for conveying environment variables into a next.js app at start / run time, to both client and server?  If not, with some initial guidance I could probably look into adding this feature to next.js.

Thanks!

**Comment by arunoda** [comment]
Using something like ` transform-define` to do pass config in the build time is our recommended method.

If you want to do it on the server, try to pass those configs via `getInitialProps` or use [custom document API](https://github.com/zeit/next.js#custom-document) to set it to the `window`. So, you can access it from the client.

But we won't be providing a built-in method to do that.

**Comment by keeth** [comment]
Thanks for your reply! I found a pretty good solution using the document API.

For posterity here's how I did it, pretty straightforward

1. Create an `env.js` file with config for all environments in it:

```
const envConfig =  {
  prod: {
    GRAPHQL_ENDPOINT: "https://prod-host/graphql"
  },
  qa: {
    GRAPHQL_ENDPOINT: "https://qa-host/graphql"
  },
  dev: {
    GRAPHQL_ENDPOINT: "https://dev-host/graphql"
  }
};

const currentEnv = (process.browser ? window.ENV : process.env.ENV) || 'dev';

export default envConfig[currentEnv];
```

... and create a `pages/_document.js` that sets window.ENV:

```
import Document, { Head, Main, NextScript } from 'next/document'
import flush from 'styled-jsx/server'

export default class MyDocument extends Document {
  static getInitialProps ({ renderPage }) {
    const {html, head} = renderPage();
    const styles = flush();
    return { html, head, styles };
  }

  render () {
    const script = `window.ENV = '${process.env.ENV || 'dev'}';`;
    return (
      <html>
      <Head>
        <script dangerouslySetInnerHTML={{__html: script}}/>
      </Head>
      <body>
      <Main />
      <NextScript />
      </body>
      </html>
    )
  }
}
```

then when I need the var

```

import env from '../env';

console.log(env.GRAPHQL_ENDPOINT);

```

seems to work.

**Comment by sedubois** [comment]
Would be great to update the with-universal-configuration example with this 🙂

**Comment by sedubois** [comment]
See https://github.com/zeit/next.js/pull/1747

**Comment by steida** [comment]
`const script = `window.ENV = '${process.env.ENV || 'dev'}';`;`

@keeth I think this can be dangerous. Sooner or later someone will put server only secret like DB password there, and it will be auto-propagated to a client.

`env-config` is more granular. `PUT_IT_TO_CLIENT_AND_YOU_WILL_BE_FIRED_DB_PASSWORD` is better. That's problem (solvable) of isomorphic design where code is shared.

Maybe even better solution. Use process.env.SECRET in the server only code.



I like env-config because it prevents accidentally leaking server only secrets like DB password, which should never be part of the code.

**Comment by keeth** [comment]
@steida ya it seems smart to keep your isomorphic config vars separate from server-only vars.  There are lots of good solutions for server-only config (like `env-config` as you mentioned).  Although I find personally that I don't need to keep secrets in my universal apps at all, I try to keep the UI layer very simple and do the heavy lifting elsewhere (e.g. behind a GraphQL endpoint in a separate service, written in Go :).

**Comment by jth0024** [comment]
The example used here will rewrite the env variable every time _document.js renders, meaning that it will default to 'dev' whenever _document is rendered client-side.

**Comment by keeth** [comment]
@jth0024 ya now that you mention it, that's what I'd expect to happen! but for some reason when I do client-side navigation the the window.ENV variable does not get reset. not sure if it's a bug or a feature :)

**Comment by jth0024** [comment]
@keeth That's definitely interesting. Perhaps I had a different issue that caused that behavior. Either way, did you consider using babel-plugin-transform-define and environment presets in the .babelrc to ensure process.env.NODE_ENV is defined correctly on client and server? This allows the same universal configuration as your example would, but it feels a little less hacky to me because you can just use process.env.NODE_ENV anywhere. https://www.npmjs.com/package/babel-plugin-transform-define

**Comment by keeth** [comment]
@jth0024 see the initial post.  this issue is about doing immutable deployments, where the same artifacts are deployed in staging and prod, in the spirit of Docker and [12 Factor](https://12factor.net/).  Baking environment-specific config into the app artifact (effectively locking it to a specific environment) goes against these principles.  The beauty of immutable deployments is that once you have QA'd your app, you deploy the exact same artifacts (minified js/css, etc) to prod without rebuilding anything, so you avoid any bugs that might be injected by the build process.

**Comment by simplynutty** [comment]
@keeth did you commit `env.js` to your repo?  One of our devOps wants to override env config via CLI.  Ultimately I'd like an immutable deploy we can override via CLI and I'm torn between your solution and dotenv. 🤔

**Comment by keeth** [comment]
@simplynutty yes I do commit env.js but it's not necessary to do so. also you could have a base env in source control and a local env file that isn't.

**Comment by keeth** [comment]
@simplynutty main the limitation of the above technique is that it only passes the env id (dev,prod,etc) through to the client, so it assumes that the config vars themselves are baked into the JS on both server and client.  if you wanted more control over individual vars, or to use something like dotenv, you'd probably need to pass the whole config to the client (using the script tag in _document).  that might ultimately be a better, more flexible solution.  you'd just need to decide which env vars get propagated this way.  maybe you could prefix env vars you care about with NEXT_ or something.

**Comment by jth0024** [comment]
@keeth I found a decent solution to this problem that allows you to control individual variables at runtime and avoids the specific limitations you mentioned. 

**__document.js**

```
import h from 'react-hyperscript';
import DefaultDocument, { Main, NextScript } from 'next/document';
import config from '../config';

export default class Document extends DefaultDocument {
  static getInitialProps({ renderPage }) {
    const { chunks, errorHtml, head, html } = renderPage();
    return { chunks, errorHtml, head, html };
  }

  render() {
    return h('html', {}, [
      h('body', [
        h('script', {
          dangerouslySetInnerHTML: {
            __html: `${config.GLOBAL_VAR_NAME} = ${JSON.stringify(config)};`,
          },
        h(Main),
        h(NextScript),
      ]),
    ]);
  }
} 
```


**config.js**

```
const _ = require('lodash');

function getConfig() {
  const isClient = typeof window !== 'undefined';
  const globalVarName = '__NEXT_APP_CONFIG__';

  if (isClient) return window[globalVarName];

  const config = {
    // Common values are either:
    //    1) fixed for all environments
    //    2) set at runtime via process args for each specific environment
    common: {
      GLOBAL_VAR_NAME: globalVarName,
      HOST: _.get(process, 'env.HOST', 'http://localhost:3000'),
    },

    // Development values are used when the app is run locally via "next"
    development: {
      LOGGING_ENABLED: true,
    },

    // Production values are used for any deployment environment (qa, staging, prod, etc.)
    // when the app is built via "next build" and run via "next start".
    production: {
      LOGGING_ENABLED: false,
    },
  };

  return _.extend({}, config.common, config[process.env.NODE_ENV]);
}

module.exports = getConfig();
```

**Comment by davidnguyen179** [comment]
How about define it in `next.config.js` with `webpack.DefinePlugin`?

**Comment by djskinner** [comment]
That would be awesome @davidnguyen179 but I've not had any success getting it working on both client and server. I read this is not possible in some other issue that I can't find now.

Are there any other ideas worth trying? The caveat on https://github.com/zeit/next.js/tree/canary/examples/with-universal-configuration is really nasty.

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/pull/3578 will make it possible to use webpack.DefinePlugin 👍

**Comment by dav-is** [comment]
Webpack sets build time variables doesn’t it? That would require a rebuild between staging and production.

**Comment by davidnguyen179** [comment]
here is how I solved multiple env

[https://medium.com/@nndung179/nextjs-multiple-environment-builds-e8b2ccb11c04](https://medium.com/@nndung179/nextjs-multiple-environment-builds-e8b2ccb11c04)

**Comment by timneutkens** [comment]
@dav-is runtime variables version: https://github.com/zeit/next.js/tree/canary/examples/with-universal-configuration-runtime

**Comment by biot023** [comment]
@keeth 
Thank you, thank you, thank you, thank you!

**Comment by biot023** [comment]
Argh. I spoke too soon. Now I'm trying to launch with `NODE_ENV=test`, but it's not working.
The express server bit reports (initially) that NODE_ENV == 'test', but then the client reports 'development'.
I've removed any explicit setting of NODE_ENV to 'development' from my code, so I'm guessing this is being introduced by babel somewhere, or maybe cached. I tried deleting the `.next` directory but that didn't fix it.
Would you be able to explain how the example you posted works, @timneutkens ? I can't see where `window.__ENV__` is coming from.

**Comment by timneutkens** [comment]
@biot023 it's coming from `pages/_document.js`. The _document.js file is only rendered on the server side. So we use it to expose the environment variables defined there. It's what we use for https://zeit.co 👍

**Comment by biot023** [comment]
@timneutkens 
Ah, okay, thanks for that.
Unfortunately, in my example, `window.ENV` gets set to "development", whereas the server is started with `NODE_ENV="test"`.
However, I've had a bit of a rethink and decided that for a really small inconvenience my front-end dev and test environments don't really need to be differently configured, so I'll just stick to assuming the environment will be either "development" or "production".
I'll revisit this issue maybe when I've got rather more Next.js experience under my belt! :)
Thanks again!

**Comment by Vadorequest** [comment]
@biot023 you can bypass this issue by sending back the environment in the `getInitialProps` return data. This way the client gets its env from the server

**Comment by timneutkens** [comment]
This is a new feature that will be introduced with Next 5.1: https://github.com/zeit/next.js#exposing-configuration-to-the-server--client-side

You can already use it on next@canary.
