### ISSUE TITLE
How can I have lint alerts on build?

### ISSUE THREAD

**Issue by phenrigomes** [zeit/next.js#1493]

**Comment by sedubois** [comment]
Can you precise the question? You want something like `"build": "eslint . && next build"`?

**Comment by phenrigomes** [comment]
I want the lint errors during compilation on dev and build time. Is it possible?

**Comment by arunoda** [comment]
You can customize the [webpack config](https://github.com/zeit/next.js#customizing-webpack-config) and add a preloader for linting.

**Comment by comerc** [comment]
Yes, like Create React App:
![2017-03-28 12 02 13](https://cloud.githubusercontent.com/assets/1025241/24397275/7553024e-13ae-11e7-9ee5-4056c1bf044a.png)

**Comment by arunoda** [comment]
I hope you can use this: https://github.com/MoOx/eslint-loader

Try to prepend this to the beginning of the rules.
