### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by jcsmesquita** [zeit/next.js#1494]
When running from a production deployment (`next build` + `next start`), my app is throwing an error in the browser console `TypeError: Cannot read property 'replace' of null` on every route change.

Digging into the source, I see the culprit is the following:
`
function o(t) {
   return t.replace(/\/$/, "") || "/"
}
`

Which I believe relates to [this line in lib/router/router.js](https://github.com/zeit/next.js/blob/228bbbef74cb79952b2d598110b67a32776ee9dd/lib/router/router.js#L378)

This error isn't causing my app to fail but it's polluting the console log and I'm worried that I might've missed something perhaps in my `<Link ...>` components. Any idea what could be causing it?

This is using next@2.0.0-beta.36

**Comment by jcsmesquita** [comment]
Nevermind, this was due to an invalid <Link> component in my code which didn't have a href prop set.

**Comment by gragland** [comment]
@danjebs I came across the same issue and it was because I was using next link with a mailto href and accidentally left prefetch enabled.

```<Link href="mailto:me@gmail.com" prefetch><a>Emaile me</a></Link>```

**Comment by danjebs** [comment]
Thanks @gragland I can't remember what I did but I fixed it
