### ISSUE TITLE
HMR does not recover from errors

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#150]
E.g create `components/MyComp.js` with 

```
import React from 'react';
return () => <div>My comp</div>; // `return` is incorrect, should be `export default`
```

and add `import '../components/MyComp'` to `pages/index.js`: properly yields error page "Error in ./AppHead: Module build failed: SyntaxError: 'return' outside of function (12:0)". 

But if I then replace `return` with `export default` and save, error page does not disappear. I need to stop and restart `next` to clear it.

**Comment by rauchg** [comment]
Yep, this is a bit priority to fix.
