### ISSUE TITLE
Cloudinary npm package not working dependency fs not found

### ISSUE THREAD

**Issue by johhansantana** [zeit/next.js#1501]
<img width="376" alt="screen shot 2017-03-24 at 8 47 30 pm" src="https://cloud.githubusercontent.com/assets/9933887/24317874/1ece7c60-10d3-11e7-978a-e2a468e652b2.png">

I'm having trouble with this [cloudinary npm package](https://www.npmjs.com/package/cloudinary).

When I `import cloudinary from 'cloudinary';` it gives me that error.

EDIT:
Also tried [React-cloudinary](https://github.com/cloudinary/cloudinary-react) but when I 

`import {Image} from 'cloudinary-react';`

and add the example:
`<Image cloudName="demo" publicId="sample" width="300" crop="scale"/>`

I get 
`Module build failed: Error: ENOENT: no such file or directory, open '/projectName/node_modules/cloudinary-core/node_modules/lodash/lodash.js'`

**Comment by arunoda** [comment]
You can't use `cloudinary` because I hope it's a server side file issue.

About the `cloudinary-react` issue, I hope that's related to the package.
Anyway, create minimal repo with the error and re-open the issue with that.

**Comment by johhansantana** [comment]
@arunoda thanks for the reply.

I've made a small repo with just the `cloudinary` package and with a version of next `2.0.0-beta.40`

https://github.com/johhansantana/cloudinary-error

The error with this version of next seems a bit different but it doesn't crash the page from loading.

<img width="395" alt="screen shot 2017-03-26 at 1 06 10 pm" src="https://cloud.githubusercontent.com/assets/9933887/24333391/1506e58e-1225-11e7-94f1-dbf25f83d6c9.png">

**Comment by johhansantana** [comment]
I was able to fix this via doing the following:

created a `next.config.js` file and added:
```javascript
module.exports = {
  webpack: (config, { dev }) => {
    // Perform customizations to config
    config.node = {
      fs: 'empty'
    };
    return config
  }
}
```

and in the page:
```javascript
import React, { Component } from 'react';
import cloudinary from 'cloudinary';
class Home extends Component {
  constructor() {
    super();

    this.upload = this.upload.bind(this);
  }
  upload() {
    console.log('clicked');
    cloudinary.config({
      cloud_name: 'cloudname',
      api_key: 'apikey',
      api_secret: 'secretkey'
    });
    cloudinary.uploader.upload(
      "https://www.google.com.pr/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
      function(result) {
        console.log(result)
      }
    )
  }
  render() {
    return (
      <div>
        <button onClick={this.upload}>Upload</button>
      </div>
    )
  }
}
export default Home;
```

**Comment by alexofob** [comment]
@johhansantana 
Is it possible to use the cloudinary npm module to upload images? In this case, where are the images stored?

**Comment by ShivaprasadSuvarna45** [comment]
@johhansantana 
HI, where you added that next.config.js? Did u refer that file anywhere in the js files?

**Comment by hephzaron** [comment]
Did same but not working. Error message fs.createReadStream is not a function

**Comment by tuanhuu** [comment]
> I was able to fix this via doing the following:
> 
> created a `next.config.js` file and added:
> 
> ```js
> module.exports = {
>   webpack: (config, { dev }) => {
>     // Perform customizations to config
>     config.node = {
>       fs: 'empty'
>     };
>     return config
>   }
> }
> ```
> 
> and in the page:
> 
> ```js
> import React, { Component } from 'react';
> import cloudinary from 'cloudinary';
> class Home extends Component {
>   constructor() {
>     super();
> 
>     this.upload = this.upload.bind(this);
>   }
>   upload() {
>     console.log('clicked');
>     cloudinary.config({
>       cloud_name: 'cloudname',
>       api_key: 'apikey',
>       api_secret: 'secretkey'
>     });
>     cloudinary.uploader.upload(
>       "https://www.google.com.pr/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
>       function(result) {
>         console.log(result)
>       }
>     )
>   }
>   render() {
>     return (
>       <div>
>         <button onClick={this.upload}>Upload</button>
>       </div>
>     )
>   }
> }
> export default Home;
> ```

i tried but it doesn't works ???
