### ISSUE TITLE
Absolute import paths with Atom js-hyperclick

### ISSUE THREAD

**Issue by comerc** [zeit/next.js#1503]
babel-plugin-root-import does not works
but
babel-plugin-module-resolver works fine!

.babelrc
```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    ["module-resolver", {
      "root": [""]
    }]
  ]
}
```
package.json
```
{
  "moduleRoots": [
    ""
}
```
example:
```jsx
import MyComponent from 'components/MyComponent'
import MyPage from 'pages/MyPage'
```

**Comment by timneutkens** [comment]
@comerc I don't follow, this seems like an issue to be raised at the js-hyperclick repository, which is located here https://github.com/facebooknuclide/hyperclick

**Comment by arunoda** [comment]
I'm using `babel-plugin-root-import` and it's working pretty well for me.
For that, you need to import like this: `~components/MyComponent`.

Please reopen with a sample repo to reproduce.

**Comment by comerc** [comment]
@timneutkens [js-hyperclick](https://atom.io/packages/js-hyperclick) - a hyperclick provider that lets you jump to where variables are defined. 

@arunoda js-hyperclick does not know about `~components/`, but `babel-plugin-module-resolver` resolves root.
