### ISSUE TITLE
Making next.js work with Socket.io

### ISSUE THREAD

**Issue by sunnixx** [zeit/next.js#1504]
I was following this example and make it work with next.js
https://socket.io/get-started/chat/

The problem comes on this line

```
<script src="/socket.io/socket.io.js"></script>
<script>
  var socket = io();
</script>
```
How can we import the client side version of socket.io ? Because next.js takes files from the Static folder.

**Comment by renehauck** [comment]
I would do it like this:

In the page folder:

```
render() {
        return (
            <div>
                <Head>
                   <script src="/socket.io/socket.io.js"></script>
                </Head>
              <myContent />
            </div>
        );
    }
```

and in the "myContent"-Class:

```
var isBrowser = typeof window !== 'undefined';
if(isBrowser)
var socket = io();
```

**Comment by sergiodxa** [comment]
You can get the client of socket.io from npm using `socket.io-client`. Try importing it and running `const socket = io()` inside `componentDidMount`.

**Comment by sunnixx** [comment]
I downloaded the client side file from the their [Git ](https://github.com/socketio/socket.io-client/blob/master/dist/socket.io.min.js). The problem still persists. 
After consulting a fellow developer, we've come across the problem being this line: 

`server.get('*',(req,res) => {
    return handle(req,res);
  })`

So I have a work around this but still I am not sure if this works or not. 

`server.get(/^\/(?!socket.io).*/,(req,res) => {
    return handle(req,res);
  })`

**Comment by renehauck** [comment]
What happens, if you keep this line:

`server.get('*',(req,res) => { return handle(req,res); })`

and append this:

```
var io = require('socket.io')(server);
io.on('connection', function(client) {  
    console.log('Client connected...');

    client.on('join', function(data) {
        console.log(data);
    });

});
```

**Comment by sunnixx** [comment]
I keep getting this error in my browser console. 

`socketio.js:2 GET http://localhost:3000/socket.io/?EIO=3&transport=polling&t=LiOf19O 404 (Not Found)`

**Comment by durongzhang** [comment]
I have the same mistake

**Comment by arunoda** [comment]
It's totally possible to connect the a socket via the custom server. Try to initiate the socket.io server first and next pass requests to next.js.

But for a real app, we suggest to run your data server outside of Next.js app. Next.js should only do the UI.

Then you can load the socket-io client in `componentDidMount` hook in your page/pages and do anything you would like.
