### ISSUE TITLE
[Question] Page transitions using css transitions addon

### ISSUE THREAD

**Issue by kybarg** [zeit/next.js#1507]
Shortly: How to make page transitions work?
**Explanation of situation:**
In order to implement such structure I've wrapped every into HOC with sidebar and header as suggested in [example](https://github.com/zeit/next.js/tree/master/examples/layout-component), where content area uses `<ReactCSSTransitionGroup>` wrapper. But it is clear that content area transitions can't work this way as changing page causes the whole layout to re-render.
What are the ways to solve this issue in **next,js**?
![example](https://cloud.githubusercontent.com/assets/4588778/24325719/b2c02944-11a7-11e7-8b65-1842a529d8f1.gif)

**Comment by arunoda** [comment]
We are talking about this here: https://github.com/zeit/next.js/issues/88

**Comment by Orecic** [comment]
hello， @arunoda  How to persist layout between page changes？Is there example code? I tried several methods are useless, thanks.
