### ISSUE TITLE
Support loading JSON without extension

### ISSUE THREAD

**Issue by leo** [zeit/next.js#1508]
Currently, this is is needed for importing a JSON file:

```js
import {LEO} from '../../lib/team.json'
```

However, IMO, it should be this (which can be achieved by telling webpack about the ext):

```js
import {LEO} from '../../lib/team'
```

**Comment by lawrencetvo** [comment]
I will work on this!

**Comment by lawrencetvo** [comment]
It seems like this issue is actually been fixed.

**Comment by leo** [comment]
The branch was closed. So no, it's not yet fixed... 😊

**Comment by lawrencetvo** [comment]
In `~/server/build/webpack.config`, there is a json loader. I also made a quick Hello World app with imports from a json file and everything seems to be running pretty fine.

**Comment by captDaylight** [comment]
Sorry about the confusion with the closed branch, updated ^^

**Comment by lawrencetvo** [comment]
@captDaylight seems like your branch is ready to go besides the jsx errors?

**Comment by captDaylight** [comment]
@lawrencetvo honestly I'm a bit puzzled by the tests failing, it's passing on my machine. What do you mean the jsx errors?

**Comment by arunoda** [comment]
@leo I just tested and .json files works as they expected (Just like it in Node.js)
We even have a test case for [that](https://github.com/zeit/next.js/blob/master/test/integration/basic/test/rendering.js#L56).
