### ISSUE TITLE
Creating a SPA with a Video Player

### ISSUE THREAD

**Issue by helguita** [zeit/next.js#1509]
Hi guys,

As the title says, I've been struggling to have a Video Player that doesn't reload every time I click on a different link. 

Take a look here: https://hello-world-xkfbpbmted.now.sh/

Is this something doable with next?

**Comment by kybarg** [comment]
@helguita I think this is related to #88. An this is what we all struggle of 😢

**Comment by arunoda** [comment]
@helguita This is a good one.
As @kybarg mentioned, we are dealing this with #88.

I'd like to experiment with some proper method as we shipped v2.

**Comment by helguita** [comment]
thanks guys for your response.  😃
