### ISSUE TITLE
Next applies margin around content

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#151]
Don't know if it is intended.

```
import React from 'react';
import css from 'next/css';

export default () => (
  <div className={css({ border: '1px solid red' })}>
    bla!
  </div>
);
```

<img width="594" alt="screen shot 2016-10-29 at 16 03 07" src="https://cloud.githubusercontent.com/assets/4217871/19829692/42eac252-9df1-11e6-9f76-2e2fd055b7f0.png">

(I saw it when I had a global style `html, body { height: 100%; width: 100% }`, which would shift everything slightly to the right.)

**Comment by nodegin** [comment]
The default user agent stylesheet has 8px padding. This is a browser-related issue not next itself. It can be fixed by adding `body { margin: 0 }`

**Comment by danielbh** [comment]
Also you could try adding normalize.css
