### ISSUE TITLE
Navigation in dev yields "cannot read property call of undefined"

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1510]
I got this error when upgrading next from beta 36 to 40, running my project with `yarn dev` and navigating from `/` to `/discover`.

<img width="994" alt="screen shot 2017-03-26 at 20 04 16" src="https://cloud.githubusercontent.com/assets/4217871/24333383/96679346-125f-11e7-9e53-14de1c0e1e00.png">

<img width="614" alt="screen shot 2017-03-26 at 20 21 47" src="https://cloud.githubusercontent.com/assets/4217871/24333520/e8540de0-1261-11e7-9980-75b4362c5644.png">

Here's the code on that line: 
```
modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
```

Project source code: https://github.com/relatenow/relate/tree/3c9212fac02c94a4c0c6e3f8425a8867f9feb75d

Deployment: https://relate-gqqbryqkoy.now.sh/

**Comment by rauchg** [comment]
We reverted for now. Looking into how the tests didn't catch it. Thanks @sedubois

**Comment by ithinco** [comment]
My project uses material-ui and antd. 

When I was using next@beta, it works fine.

After I uses custom route, got the same error like above.  The click/touchTap event doesn't get called.

![image](https://cloud.githubusercontent.com/assets/1669761/24937351/b9f36078-1f62-11e7-9e18-0034ba5829dd.png)

Then I upgrade next from beta to ^2.1.1, still doesn't work.

And at this time, when I run npm run start, I got this error. I'm using "with-url-object-routing"'s configuration.

![image](https://cloud.githubusercontent.com/assets/1669761/24937366/cd39dcac-1f62-11e7-8697-8612b35cce28.png)

Thanks

**Comment by tz5514** [comment]
Same problem as this.
I was using [next-routes](https://github.com/fridays/next-routes)
