### ISSUE TITLE
Specify a different build directory instead of .next

### ISSUE THREAD

**Issue by abstractpoint** [zeit/next.js#1513]
I am trying to deploy next to Firebase functions, and It looks like the .next build directory is ignored by firebase cli.

Firebase cli seems to ignore all hidden files, so I want to use a differently named directory.

The directory seems to be hardcoded in 3 places:
`/dist/bin/next-start`
`/dist/server/build/clean.js`
`/dist/server/build/index.js`

**Comment by alexnewmannn** [comment]
Would this be something that would like to be added via config? maybe next.config? If so, I can take a look at this?

**Comment by arunoda** [comment]
Yep. That's the api we could do it.

**Comment by alexnewmannn** [comment]
Im having a look at this now. Is there any standards or practices against config? For sake of testing it out im running the following in `next.config`:
```
module.exports = {
  options: {
    dest: 'dist'
  }
}
```

Have any other ideas?

**Comment by arunoda** [comment]
I'd like to see it like this:

```js
module.exports = {
  options: {
    dist: '.next'
  }
}
```

**Comment by alexnewmannn** [comment]
no worries, got some of it done last night. WIll continue with it tonight 👍

**Comment by alexnewmannn** [comment]
Pr incoming for this; just updating documentation.

**Comment by alexnewmannn** [comment]
@abstractpoint @arunoda https://github.com/zeit/next.js/pull/1599 Opened a PR for it; let me know if any issues. 
Cheers

**Comment by alexnewmannn** [comment]
@abstractpoint this is now merged if you want to try on latest master.

**Comment by abstractpoint** [comment]
@alexnewmannn Working great, super useful. Thank you for putting in the time! (Still battling with Firebase being too slow running next, but that's not really related)
