### ISSUE TITLE
Experiencing issues trying to share components via an npm package

### ISSUE THREAD

**Issue by possibilities** [zeit/next.js#1514]
I'm trying to separate some shared components to separate npm module but when I interact with a `Link` that is sourced from the separated module the following error is thrown:

```
(unknown) Uncaught Error: No router instance found.
You should only use "next/router" inside the client side of your app.


    at throwIfNoRouter (eval at evalScript (http://localhost:4444/_next/-/main.js:10697:3), <anonymous>:8717:11)
    at Object.SingletonRouter.(anonymous function) [as push] (eval at evalScript (http://localhost:4444/_next/-/main.js:10697:3), <anonymous>:8698:5)
    at Link.linkClicked (eval at evalScript (http://localhost:4444/_next/-/main.js:10697:3), <anonymous>:11304:37)
    at Object.module.exports.ReactErrorUtils.invokeGuardedCallback (http://localhost:4444/_next/-/main.js:11963:16)
    at executeDispatch (http://localhost:4444/_next/-/main.js:11492:21)
    at Object.executeDispatchesInOrder (http://localhost:4444/_next/-/main.js:11515:5)
    at executeDispatchesAndRelease (http://localhost:4444/_next/-/main.js:5647:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:4444/_next/-/main.js:5658:10)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:4444/_next/-/main.js:16051:9)
```

I've been unable to figure out why `SingletonRouter.router` is `undefined` [here](https://github.com/zeit/next.js/blob/master/lib/router/index.js#L52) even though it seems like `createRouter` is getting invoked [here](https://github.com/zeit/next.js/blob/master/client/index.js#L35).

You can see this in action following these steps

```
rm -rf /tmp/next-link-issue
cd /tmp
git clone https://github.com/possibilities/next-link-issue.git

cd next-link-issue/dependency
npm install
npm run build
npm link

cd ../app
npm install
npm link next-link-issue-dependency
npm run dev
```

Now if you click on one of the links you'll see the above error in the console. I imagine the solution for this is something in the configuration of my module either in terms of `babel` or something else is flawed with the way I'm packaging it. Thanks in advance for any help troubleshooting this!

Source code is here https://github.com/possibilities/next-link-issue

**Comment by arunoda** [comment]
This happens when there is two next versions (packages) in your app.
Could you check for that?

**Comment by possibilities** [comment]
Ah, interesting...

The npm module has it's own dependency on `next` because it relies on `babel/next`. It's set as a `devDependency`. https://github.com/possibilities/next-link-issue/blob/master/dependency/package.json#L13

And the next app has it's own dependency on `next` as well. https://github.com/possibilities/next-link-issue/blob/master/app/package.json

So they're the same version but I think this still might qualify in terms of what you're asking?

**Comment by arunoda** [comment]
> So they're the same version but I think this still might qualify in terms of what you're asking?

Yes.

**Comment by possibilities** [comment]
Seems like a conundrum though? I _think_ I have to transpile the package with `next/babel` before publishing or `next` will choke on the source. Is there some way I can use `next/babel` at publish time but not include the extra `next` module?

**Comment by arunoda** [comment]
What do you mean by "extra next module?" ? We don't add anything via the babel-config.
See: https://github.com/zeit/next.js/blob/master/server/build/babel/preset.js

**Comment by possibilities** [comment]
By "extra next module" I mean (from my first response) there seem to be two `next` modules in play: one from my npm module's `node_modules/` and one in the `node_modules/` of the app that depends on it. I thought you were confirming that the fact that I have two `next`'s in my app's `node_modules/` tree was causing the reported issue, no?

**Comment by arunoda** [comment]
Got it. I hope you can do some babel hack or webpack hack and ask Next.js to use the same Next.js module everywhere.

**Comment by possibilities** [comment]
That give me some hope, I imagine when I better understand the internal babel config I'll find a workaround... That said this seems like something that would be interesting to either solve in next or provide best practices otherwise it's arbitrarily hard (or at least unclear what the approach is) provide a 3rd party library that references anything inside the `next` package (e.g. `next/link` or `next/babel`). Again maybe my understanding will change when I solve my particular issue but this seems like a scenario that should be easily supported to encourage next-specific 3rd party resources delivered via npm.

Thanks for all your input!

**Comment by possibilities** [comment]
After some evolution of my package I no longer need to depend on the next package directly. Thanks.
