### ISSUE TITLE
router the serviceWorker promise not captured

### ISSUE THREAD

**Issue by durongzhang** [zeit/next.js#1515]
![image](https://cloud.githubusercontent.com/assets/15725537/24346102/900234d8-1305-11e7-8bcf-76a8d9375fec.png)
The following problems are found
router.js
![image](https://cloud.githubusercontent.com/assets/15725537/24346120/9fb1f5f8-1305-11e7-8730-8d4be81862f9.png)
add catch

version: 2.0.0-beta.42

**Comment by arunoda** [comment]
@timneutkens could you have  look at this?

**Comment by timneutkens** [comment]
Great catch. This error is caused when running Next.js on `http`. `localhost` has support for serviceworkers for testing purposes. Linking `next.dev` to `127.0.0.1` in `/etc/hosts` was enough to reproduce. The best way to handle this is indeed catching the error. Cause it's of no use to us 👍
