### ISSUE TITLE
The 'hello-world' example is not working out of the box

### ISSUE THREAD

**Issue by Pablo-Merino** [zeit/next.js#1518]
Hello everyone! I was going to start researching if using Next for our project was a good choice, but I couldn't get the ['hello-world'](https://github.com/zeit/next.js/tree/master/examples/hello-world) example working. I've followed exactly as the `README` says, but it won't work. I've also followed the guide on [Next's Readme](https://github.com/zeit/next.js/blob/master/readme.md#setup), but I've got the same results.

Am I doing anything wrong? Perhaps with my environment?

Thanks and sorry if this is duplicated (found similar issues, but didn't help me).

This is the error:

```
ERROR  Failed to compile with 1 errors                                                                                                                                      15:25:47

 error  in ./pages?entry

Syntax Error: Unexpected token (3:2)

  1 | import Link from 'next/link'
  2 | export default () => (
> 3 |   <div>Hello World. <Link href='/about'><a>About</a></Link></div>
    |   ^
  4 | )
  5 |


 @ multi ./pages?entry
```

**Comment by sedubois** [comment]
Could you please share a repo that allows to reproduce the issue?

**Comment by arunoda** [comment]
When you are starting the app, there'll be log saying which `.babelrc` file is using for your app. I hope it's a wrong file.

Add a file called `.babelrc` in your app root with following content:

```js
{
   "presets": ["next/babel"]
}
```

**Comment by Pablo-Merino** [comment]
@arunoda thanks! That worked. Maybe it should be in the readme?

@sedubois it was the 'hello-world' example dir, 100% untouched. Fixed by adding a `.babelrc`

**Comment by arunoda** [comment]
@Pablo-Merino good point.
