### ISSUE TITLE
[proposition] Make /page/foo.js behave the same way as /page/foo/index.js

### ISSUE THREAD

**Issue by gahissy** [zeit/next.js#152]
It'd greatly help keep a clean folder structure:
```
/pages
--/feature1/index.js
--/feature1/create.js
--/feature1/details.js

--/feature2/index.js
...
```

**Comment by impronunciable** [comment]
@gahissy I think it works that way now. Can you specify more the desired behavior?

**Comment by gahissy** [comment]
@impronunciable 
My mistake. Yes it works. The issue was on my side.
