### ISSUE TITLE
Using fuse-box instead of webpack?

### ISSUE THREAD

**Issue by formula349** [zeit/next.js#1522]
I love Next.js, and I have been testing it out for some time now. Reading the 2.0 release notes, it seems like developer experience is a priority (which it should be).

I ran across fuse-box a few months back and was really impressed how fast the browser would hot reload the page. I've never seen anything this fast! It was well under 100ms.

fuse-box has some other nice features, and it feels like it would pair really well with next.js. Does anyone have any experience with fuse-box?

https://github.com/fuse-box/fuse-box

**Comment by arunoda** [comment]
Next.js is pretty much based on Webpack. Although fuse-box sounds so great, we hope there are a lot we can do to make webpack fast.

And it's the most adopted and we are not looking to replace it in the near future.

**Comment by oliviertassinari** [comment]
Fuse box looks promising. I hope it will incentivise Webpack to improve the rebuild time.
