### ISSUE TITLE
Built-in CSS dosen't work when refresh page.

### ISSUE THREAD

**Issue by kenshero** [zeit/next.js#1523]
It work by click Link tag.  But when refresh built in css dosen't work. Can you help me ?

**Comment by knipferrc** [comment]
Are you seeing errors or what do you mean by not working?

**Comment by kenshero** [comment]
It not error. I mean css built-in disappear when i refresh page. and Css comeback when i click Link swap page .

**Comment by knipferrc** [comment]
You have an example you could share?

**Comment by kenshero** [comment]
oh i found it. problem is "space" .
styled-jsx if i have space after style tag like this it will built-in css is failed.
      <style> {`
        .red-box {
          height: 350px;
          background-color: red;
        }
      `}
      </style>

must remove space like this. 
      <style>{`
        .red-box {
          height: 350px;
          background-color: red;
        }
      `}
      </style>

haha eat 2 day for me.
