### ISSUE TITLE
Standard Prettier

### ISSUE THREAD

**Issue by steida** [zeit/next.js#1527]
An idea:

- Next.js should prefer `"` over `'` everywhere. `'` is a relic.
- No semicolons once Prettier will support it.
- Add CLI task to fix code via prettier.

**Comment by arunoda** [comment]
We won't have built in linting tools. 
Exising tools are much simpler to use. 
And with out custom webpack config, you could plug it into webpack process as well.

**Comment by steida** [comment]
@rauchg Whatever, but Next.js code should be prettified anyway I suppose.

**Comment by arunoda** [comment]
@steida We use standard and some of the eslint rules.
And I don't think we don't need more than that.

**Comment by steida** [comment]
Give Prettier a chance for a minute in your IDE :-)

**Comment by timneutkens** [comment]
I'm +1 on implementing prettier + xo like all other ZEIT projects. For consistency, and there's a lot of PRs that had a failed build cause of style stuff prettier catches 👍

**Comment by timneutkens** [comment]
cc @rauchg

**Comment by steida** [comment]
@rauchg Prettier is awesome. 

That's what I am using as npm script

```js
"prettier": "prettier --bracket-spacing --single-quote --tab-width 2 --trailing-comma all --parser babylon --print-width 80  --write \"{{components,epics,lib,mutations,pages,reducers,scripts,test,themes,types},__{tests,mocks,generated}__}/**/*.js\"",
```

Maybe we should take whole current dir, and ignore node_modules and .next

**Comment by xedef** [comment]
> @rauchg Prettier is awesome.
> 
> That's what I am using as npm script
> 
> "prettier": "prettier --bracket-spacing --single-quote --tab-width 2 --trailing-comma all --parser babylon --print-width 80  --write \"{{components,epics,lib,mutations,pages,reducers,scripts,test,themes,types},__{tests,mocks,generated}__}/**/*.js\"",
> Maybe we should take whole current dir, and ignore node_modules and .next dirs.

This is not compatible with styled jsx
