### ISSUE TITLE
Bug? The setState callback isn't being called.

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#1528]
I have `setState(state, callback)` called from `componentWillMount()`, but the callback isn't being called as I'd expect.

Does Next somehow prevent this?

**Comment by arunoda** [comment]
We don't do anything special. Could you send us a sample repo?

**Comment by tashburn** [comment]
I somehow managed to get it working, and made the mistake of changing lots of things, so I'm not sure what my problem was. But, it appears it's not a Next bug, which is good :-).
