### ISSUE TITLE
Use an external SCSS

### ISSUE THREAD

**Issue by DominikLevitsky** [zeit/next.js#1530]
I am trying to use a single SCSS file, that includes all the other files. I don't want to include CSS code in my JS files. How can i compile this using Webpack? Is it actually possible here?

**Comment by timneutkens** [comment]
Please check https://github.com/zeit/next.js/tree/master/examples/with-global-stylesheet. It has an
 example for `.scss` 😄

**Comment by pulkitnandan** [comment]
can this done for components too but scoped. this example fails on linux

https://github.com/zeit/next.js/tree/master/examples/with-external-scoped-css

**Comment by warrenday** [comment]
The example works with files with the  .sass extension but compiles nothing for .scss files, even when .scss is added to the extensions array in the .babelrc file. Any idea why?

**Comment by aviramga** [comment]
@warrenday Im having the same issue, were you able to solve it?

**Comment by warrenday** [comment]
@aviramga Sorry had no luck with that!

**Comment by gbrlsnchs** [comment]
@aviramga @warrenday I see the example has `indentedSyntax` set to `true` in the `pre-processor.js` file. According to the `node-sass` [README](https://github.com/sass/node-sass#indentedsyntax), this option should be set `true` when compiling SASS.

I'm not sure if removing that line or setting that option to `false` might solve your problem, but you should give it a try!
