### ISSUE TITLE
Questions about Parameterized routing in conjunction with SSR

### ISSUE THREAD

**Issue by afterburn** [zeit/next.js#1532]
I'm using the express version of next.js which I'm using in conjunction with redux.
I've tried several approaches but I'm unclear as to what the best practice in regard to how my router should function is. What I'm trying to accomplish is being able to have my users navigate to /profile/:username and serve a SSR rendered document so it gets picked up by search engine crawlers for SEO purposes. 

Ideally I'd like for my application to be able handle route **/:username** and still have route **/about** display _pages/about.js_ instead of looking for a user called _about_, just like facebook does but that's not what this question is about.

This is what my router currently looks like:

```javascript
const { parse } = require('url');
const pathMatch = require('path-match');
const route = pathMatch();

// Parameterized routes.
const profileRoute = route('/profile/:username');
const newsRoute = route('/news/:article');

((exports) => {
	
	platform.server.get('*', (req, res) => {
		const parsedUrl = parse(req.url, true);
		const { pathname, query } = parsedUrl;
    	
    		// Get parameter(s) if available.
    		let profileParams = profileRoute(pathname);
    		let newsParams = newsRoute(pathname);

    		// Route matching.
		if(pathname.indexOf('/profile/') !== -1) platform.app.render(req, res, '/profile', profileParams);
		else if(pathname === '/news/:article') platform.app.render(req, res, '/news', newsParams);
		else if(pathname === '/about') platform.app.render(req, res, '/about');
		else platform.handle(req, res);		
	});

	console.log("> Routing initialized");

})(module);
```

I'm guessing that since I'm sending the parameters for let's say user **John** to be picked up by a component and  then have redux fetch the user's data from the back-end is not truly SSR. I also find it inconvenient how I'm currently defining parameterized routes and having to create a variable for each route's parameters. Obviously I don't like having to use **indexOf** on _pathname_ to detect someone's requesting a profile. Hopefully someone can point out what I could possibly do different.

**Comment by arunoda** [comment]
I suggest you use [express to define routes](https://github.com/zeit/next.js/blob/master/examples/custom-server-express/server.js).

If you wanna handle /:username routes. Do this:

This is the code you can use:
(This is a sample code. Not tested)

```js
// Handle core Next.js routes
['static', '_next', '_webpack', '__webpack_hmr']
  .forEach(function(path) {
    app.get(path, function (req, res) => {
      handle(req, res)
    })
  })

app.get('/about', ...)
app.get('/:user', ...)
```

**Comment by afterburn** [comment]
Thanks for your reply, I've tried to implement your code and assumed this is what you mean by using express to define routes:
```javascript
['static', '_next', '_webpack', '__webpack_hmr']
.forEach(function(path) {
	console.log(path);
	platform.server.get(path, (req, res) => {
		handle(req, res);
	});
});

platform.server.get('/', (req, res) => {
	platform.app.render(req, res, '/');
});

platform.server.get('/about', (req, res) => {
	platform.app.render(req, res, '/about');
});
```

where platform.server is my express app, and platform.app is my next js instance which might've been poorly chosen names.

This approach however causes the following errors to occur when navigating to http://localhost:3000
![e07afdad52d057a27e4d758e37915d57](https://cloud.githubusercontent.com/assets/10757768/24548319/d922e236-1614-11e7-97b7-8a96d420d724.png)

**Comment by fridays** [comment]
It should work if you add wildcards to the paths:
```
['static*', '_next*', '_webpack*', '__webpack_hmr*']
```
You could also use [next-routes](https://github.com/fridays/next-routes) where it's done similarly.

**Comment by arunoda** [comment]
@fridays thanks for the updated example.
