### ISSUE TITLE
Next 2.0 `next init`

### ISSUE THREAD

**Issue by thierrybgentile** [zeit/next.js#1536]
Has Next 2.0 broken next init? I installed next globally to try that and every attempt to run `next init` gives me 
`react not found. Please install react using 'npm install react'
react-dom not found. Please install react-dom using 'npm install react-dom'`
I even tried running `npm install react react-dom` in a new directory and running next init (which kind of defeats the purpose of running that command) and it still gives me the same error.

**Comment by timneutkens** [comment]
@thierrybgentile good catch! here's the PR https://github.com/zeit/next.js/pull/1543

**Comment by thierrybgentile** [comment]
![next init bug](https://photos-3.dropbox.com/t/2/AADz1P4Gn5wTWCwN80Ic28aHE_3VkNJ-o3O8XzuOCjOXhA/12/63511397/png/32x32/1/_/1/2/Capture%20d'%C3%A9cran%202017-03-30%2020.00.46.png)

It still doesn't seem to work am I doing it wrong?

**Comment by dortzur** [comment]
@thierrybgentile It doesn't work for me when next is installed globally, remove global installation and install locally only.
