### ISSUE TITLE
TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by Larry850806** [zeit/next.js#1547]
My `next` version is `2.0.0`. I'm trying to run `next build` but I got this error message. Because of the failure of building. It doesn't generate the `.next/` directory and I can't run `next start` to deploy. 

 ```
(node:75113) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'source' of undefined
(node:75113) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sedubois** [comment]
Can you provide repo to reproduce issue?

**Comment by timmywil** [comment]
This the error I got. Does this look familiar @Larry850806? https://github.com/zeit/next.js/issues/1545

**Comment by Larry850806** [comment]
@sedubois OK, I trying to make a repo to reproduce this issue.

**Comment by Larry850806** [comment]
@timmywil @sedubois Here!! 

https://github.com/Larry850806/next-error-reproduce

Clone this repo and run `yarn && yarn run build` to install the dependencies and build. This is my `package.json`

```json
{
  "name": "Testing",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^2.0.0",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}
```

**Comment by arunoda** [comment]
@Larry850806 thanks for the repo.
I just did a fix for this: https://github.com/zeit/next.js/pull/1569

Wait for the new release.
