### ISSUE TITLE
cdn.zeit.co is returning 404 for version 1.0.2 of next.js

### ISSUE THREAD

**Issue by jeffbski** [zeit/next.js#155]
FYI. I just installed next.js 1.0.2 and when using the production mode it is 404'ing for the next.js bundle from cdn.zeit.co.

https://cdn.zeit.co/next.js/1.0.2/next.min.js

Might want to add a note to always update the CDN after publishing. 

Thanks for the great work in creating this!

**Comment by nkzawa** [comment]
Released, thanks !

**Comment by jeffbski** [comment]
Awesome!!
