### ISSUE TITLE
Fix HMR related issues

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#1551]
Currently, there are some issues don't recover with HMR.
We need to fix them.

**Comment by skellyb** [comment]
Does this include endless rebuilding and page refreshing? I can't figure out what's triggering this or how to debug.

**Comment by arunoda** [comment]
@skellyb We are also going to address that.

**Comment by arunoda** [comment]
Fixed with https://github.com/zeit/next.js/pull/1592
