### ISSUE TITLE
Allow extra scripts to be part of the main bundle

### ISSUE THREAD

**Issue by ptomasroos** [zeit/next.js#1556]
We load a error detection library, bugsnag for instance. It would be real valuable to be able to make it become of the main bundle which is packed and return to the client instead of sync letting it be part of the header.

It follows some work you did on making the bundle become one output @arunoda

**Comment by arunoda** [comment]
Here's one way to it.
Create a custom webpack config and put append that library into the [main.js entry](https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L43).

Something like this:

```js
module.exports = {
  webpack: function(c) {
    c.entry['main.js'].push(
      ...<you libs>
    )
    return c
  }
}
```

(Didn't test this code)

**Comment by ptomasroos** [comment]
Thanks for the lead, will report back.

**Comment by isBatak** [comment]
Is there any other way to achieve that? 
Because `c.entry` is now async function, and your example does not work anymore...

**Comment by isBatak** [comment]
OK, I figured it out...
```js
module.exports = {
  webpack: function(config) {
     const configEntry = config.entry;
     config.entry = async () => {
        const entry = await configEntry();
        entry['main.js'].push(require.resolve('./example.js'));
        return entry;
     };
  }
}
```

**Comment by timneutkens** [comment]
@isBatak you can use https://github.com/zeit/next.js/blob/canary/server/build/webpack.js#L48

```
// next.config.js
module.exports = {
    clientBootstrap: [require.resolve('./example.js')]
}
```

**Comment by isBatak** [comment]
@timneutkens thx, I saw that line in the code and I tried it and it did not work ... now I see that this was added in 4.2.0-canary.1 but I'm on version 4.1.4...

**Comment by timneutkens** [comment]
🙌

**Comment by arunoda** [comment]
Hello all, 

We are going to remove `clientBootstrap` in the future. Simply because we can simply use our custom webpack config.
Checkout this example: https://github.com/zeit/next.js/pull/3568
