### ISSUE TITLE
Create running production server documentation

### ISSUE THREAD

**Issue by ptomasroos** [zeit/next.js#1557]
React-server has a exceptional running production server guide over here. I think next.j should have something similar. https://github.com/redfin/react-server/blob/master/docs/guides/production.md

**Comment by arunoda** [comment]
Actually we don't have such a set of knobs/options.

`npm run build` and `npm run start`.

There's nothing you need to tune-up.
That's the whole idea.

If you need changes, you can do that via webpack config / babel config / custom server.
