### ISSUE TITLE
Supporting aliases / allowing custom Babel configuration for server-side files

### ISSUE THREAD

**Issue by ide** [zeit/next.js#1565]
My use case is that I want to alias module paths using Webpack's `resolve.alias` field and Babel's `module-resolver` plugin. I'd like to override Next's server-side Babel configuration (here: https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L206) so that I could add new aliases to it.

Would you be open to a small PR that lets next.config.js override the server-side Babel configuration? Ex:

```js
  if (config.serverBabel) {
    console.log('> Using "serverBabel" config function defined in next.config.js.')
    babelConfig = await config.serverBabel(babelConfig, { dev })
  }

  const transpiled = babelCore.transform(content, babelConfig)
```

**Comment by ide** [comment]
I tried adding the `module-resolver` plugin to .babelrc and it worked for modules under the Next project directory, but not for modules outside of it. My directory structure looks like this:
```
.
├── nextjs
│   └── .next
└── other
```

From within the nextjs directory I want to write `require('other/some-module')` and have it be aliased to `require('../other/some-module')` for the Webpack build but `require('../../../other/some-module')` for the server-side Babel build, since those files get placed under `.next/dist`. This is why I was looking to make changes specifically to the server-side Babel configuration.

**Comment by arunoda** [comment]
@ide how about the use of [module-alias](https://github.com/zeit/next.js/blob/master/examples/using-preact/server.js#L2) package.

**Comment by timneutkens** [comment]
This is tracked in another issue.

**Comment by dizlexik** [comment]
@timneutkens What is the other issue?
@ide Did you ever get this working? I have the same need in a project right now.

**Comment by ide** [comment]
I didn't get this working. I might work on it soon though (or get stuck).

**Comment by dizlexik** [comment]
Alright, after a bunch of hours I've whipped up a hack that is working for me.

**.babelrc**
```json
{
  "presets": ["next/babel"],
  "plugins": [
    ["module-resolver", {
      "alias": {
        "other": "../other"
      }
    }]
  ]
}
```

**next.config.js**
```js
const { NormalModuleReplacementPlugin } = require('webpack');
module.exports = {
  webpack: (config) => {
    config.plugins.push(new NormalModuleReplacementPlugin(
      /^(\.\.\/){3,}other\//,
      resource => resource.request = resource.request.slice(6)
    ));
    return config;
  }
};
```

I'm sure this could be improved but I'm completely spent at this point. An edge case I can see right away is that this will break if you have an `other` directory within the Next project and you attempt to access something within it from a few directories deeper than it. Very edge, but still...

Let me know your thoughts and if you have any ideas on how to do this in a more elegant way.
