### ISSUE TITLE
The main editor does not support styled-jsx syntax

### ISSUE THREAD

**Issue by MinJieLiu** [zeit/next.js#1566]
I think it is a waste of time to write css in this way. Because it does not support syntax prompts. 
I recommend using the `css modules` scheme instead.🤓

**Comment by timneutkens** [comment]
Please see https://github.com/zeit/styled-jsx#syntax-highlighting

**Comment by hegelstad** [comment]
I agree- the suggested extension for VS Code doesn't work either, and it is missing autocomplete.. Thanks for the recommendation!
