### ISSUE TITLE
Graphql-Server and Next.js HTTP 500 response

### ISSUE THREAD

**Issue by JustasPolis** [zeit/next.js#1574]
Hello,

### Buggy Behavior

with custom graphQL server errors, I receive 500 HTTP response from graphQL server when using next.js, I expect to get HTTP 200 response and handle errors myself, that happens on Create-react-app for example, using same back-end. 
Everything is fine if there is data and no errors.

example code:

```javascript

const resolverThatThrowsError = (root, params, context) => {
  throw new Error('Test')
 }
```
That's what I get when running query with apollo, using withApollo example.

![image](https://cloud.githubusercontent.com/assets/20723848/24538810/09accafa-15f4-11e7-847d-89ad9201955f.png)
![image](https://cloud.githubusercontent.com/assets/20723848/24538840/372a0c22-15f4-11e7-9803-11a7bfc43b21.png)

As you see in this picture, everytime there is an error we'll get 200 response with data and errors if there are some, but never 500 http response.

![image](https://cloud.githubusercontent.com/assets/20723848/24538651/37dca45a-15f3-11e7-835f-04124f29a04f.png)
![image](https://cloud.githubusercontent.com/assets/20723848/24538899/84ead720-15f4-11e7-9366-536817ece4ad.png)
![image](https://cloud.githubusercontent.com/assets/20723848/24538902/9000eb86-15f4-11e7-8455-05c238b8780b.png)

If needed can reproduce this with Creacte-react-app and next.js, maybe that would help ?

**Comment by arunoda** [comment]
Create a sample repo(s) with the error and add them here.
So, we can have a look at and find out the error.

**Comment by JustasPolis** [comment]
https://github.com/JustasPolis/nextjs-error-not-working
https://github.com/JustasPolis/CRA-Error-Working

If you encounter some problems running, just let me know, i'll fix it in a sec :). 

## How to run both examples
In order to run CRA with a server, first start the next.js example, and CRA will proxy to next.js server backend.

## What to look for: 
As you can see I can output the server error in CRA example, but in next.js example i'll get that "red screen of doom" and can't handle errors myself ;).

**Comment by jaydenseric** [comment]
I just encountered this. If it's not something I'm doing wrong, it's a pretty big deal. It means no custom error messages inline on the page if anything goes wrong with data fetching. Just a red screen of death.

**Comment by JustasPolis** [comment]
Yes, totally agree, I'm handcuffed to do authentication because of that ;/, 
Well with 2.1 version released today, I've been able to render error on the page initially, but on second refresh, ill get that red screen of death again :).

**Comment by ooade** [comment]
@JustasPolis @jaydenseric It's a different thing over [here](https://github.com/ooade/GraphQLPlayground).... Works fine with a 200 status code

**Comment by JustasPolis** [comment]
There is an option to customize errors by creating _error.js file @jaydenseric :).
@arunoda  You can close this :).

**Comment by JustasPolis** [comment]
@jaydenseric  you can customize by creating _error.js file ;). Check docs.

**Comment by jaydenseric** [comment]
@JustasPolis Few things with that.

- Would that mean errors still take over the whole page, and that you couldn't have in-context error content?
- I can't get `_error.js` to work anyway. Maybe it is because of the custom `withData` HOC used for Apollo Client and Redux.

**Comment by JustasPolis** [comment]
@jaydenseric  Sorry for delay. Haven't implemented it yet, got caught up with other things. I just checked react devtools that we have available GraphQLError message prop on error component, so figured it out we would be able to pass it on custom _error.js.
I'll try to test it today, but regarding your first point, probably the error will take over the whole page, and that's a bummer.

**Comment by jaydenseric** [comment]
I discovered you need to silently catch Apollo errors when doing SSR data fetching. The SSR still has the errors as data props, it just means a data fetching error will not crash the whole SSR. I should update the Apollo example here with what I have in my `withData` HOC:

```js
if (ssrMode) {
  // Recurse the component tree and prefetch all Apollo data
  // queries to populate the Apollo Client Redux store. This
  // allows an instant server side render.
  // See: http://dev.apollodata.com/react/server-side-rendering.html#getDataFromTree
  try {
    await getDataFromTree(
      <ApolloProvider client={client} store={store}>
        <Component {...initialProps.component} />
      </ApolloProvider>
    )
  } catch (error) {
    // Catch any Apollo Client GraphQL errors as they crash
    // SSR. Errors are handled via data.error in the JSX.
  }
}
```

**Comment by JustasPolis** [comment]
Yes ! that would be really helpful. good job :).
