### ISSUE TITLE
Add an example with cerebraljs

### ISSUE THREAD

**Issue by tezhub** [zeit/next.js#1577]
Since examples folder have `with-redux` and `with-mobx` so it would be nice to have an example with cerebraljs also.

- https://github.com/cerebral/cerebral
- http://cerebraljs.com/docs/get_started/

A release article, comparing Cerebral to Mobx and Redux, http://www.christianalfoni.com/articles/2017_03_19_Cerebral-2

**Comment by impronunciable** [comment]
@tezhub We'll gladly accept pull requests :)
