### ISSUE TITLE
Errors not showing up in 2.0 with custom server

### ISSUE THREAD

**Issue by qwang06** [zeit/next.js#1584]
I just followed `Custom server and routing`  and everything works as is. 

I decided to add some custom code and I forgot to import a module. It says it compiled successfully but nothing shows up in the browser and no errors in the console. Doesn't even get to

`console.log('> Ready on http://localhost:3000')`

**Comment by Kocisov** [comment]
Hello, which module did you forget to add?

Also, console.log('> Ready on http://localhost:3000') **appear only once before first compiling** (before you locate **http://localhost:3000/** in your browser).

**Comment by qwang06** [comment]
I was just trying to add body-parser for express but didn't import it.

`server.use(bodyParser.urlencoded({ extended: false }))`

It doesn't matter what module. No errors come up whatsoever. If I try to access an undefined object, it still won't throw an error.

`console.log(undefinedObj.value);`

**Comment by Kocisov** [comment]
Can you please make gist with your package.json and server.js code.

It seems to me that I can't reproduce this error.

**Comment by qwang06** [comment]
https://gist.github.com/qwang06/c30089ef15e21faed11902d19b1014b9

Just added line 12 to `custom-server-express`. Using exact same package.json.

**Comment by Kocisov** [comment]
It's working properly for me.
![screen shot 2017-04-02 at 10 48 54](https://cloud.githubusercontent.com/assets/7074196/24585736/21d0c98e-1792-11e7-8cf5-44e6f99a9b11.png)

**Comment by arunoda** [comment]
@qwang06 you can always catch the error and print it as well as as well.
