### ISSUE TITLE
Router error occurs when use async getInitialProps in _document.js

### ISSUE THREAD

**Issue by hieuhlc** [zeit/next.js#1585]
Hello guys, I encountered this bug today with these code

```javascript
export default class MyDocument extends Document {
  static async getInitialProps({ renderPage }) {
    const { html, head } = renderPage()
    const styles = flush()
    return { html, head, styles }
  }
```

This error appears in console when I navigate to other pages and back to home (using browser's back function)

<img width="790" alt="screen shot 2017-04-01 at 17 11 29" src="https://cloud.githubusercontent.com/assets/4828178/24577770/47c7d5b8-16fe-11e7-9d24-d58b485b8ed9.png">

However the error is gone when I remove the `async` from `getInitialProps `. What caused this?
The purpose: I need to detect user agent in `_document.js`. I need to get `req` from `getInitialProps`.

Thank you!

**Comment by arunoda** [comment]
@hieuhlc can we have a sample repo for this.
Please re-open with that.
