### ISSUE TITLE
Creating `components` folder not making effect until server restart

### ISSUE THREAD

**Issue by Flamefork** [zeit/next.js#1587]
STR:

1. Create new next.js app
2. Run the dev server
3. Create `components` folder and some component
4. Use it in the page

Expected:
Component wires up into the page

Actual:
```
Error in edit/pages/index.js?entry
Module not found: Error: Can't resolve '../components/Header' in 'edit/pages'
ModuleNotFoundError: Module not found: Error: Can't resolve '../components/Header' in 'edit/pages'
    at factoryCallback (edit/node_modules/webpack/lib/Compilation.js:260:39)
    at edit/node_modules/webpack/lib/NormalModuleFactory.js:243:19
    at onDoneResolving (edit/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at edit/node_modules/webpack/lib/NormalModuleFactory.js:132:20
    at edit/node_modules/async/dist/async.js:3799:9
    at edit/node_modules/async/dist/async.js:360:16
    at iteratorCallback (edit/node_modules/async/dist/async.js:934:13)
    at edit/node_modules/async/dist/async.js:844:16
    at edit/node_modules/async/dist/async.js:3796:13
    at apply (edit/node_modules/async/dist/async.js:21:25)
```

The component works fine after a dev server restart.

**Comment by zigzactly** [comment]
This just happened to me earlier using those exact steps and same error. After a couple of restarts it finally decided to work. 

when i had the error, i noticed my components folder was not showing up in .next/dist/ which probably explains why it cannot resolve

**Comment by aranajhonny** [comment]
@arunoda I followed the steps he says and no error occurred. But note that this often happens when the first letter of the file you imported file is in uppercase. And in the folder is in lowercase or vice versa.

**Comment by timneutkens** [comment]
Same happens when a file is moved around inside pages.

**Comment by eezing** [comment]
Looks like route change clears the error. Still not ideal, but at least we don't have to restart.

Example:

Given an error when importing non-existing file ```./components/Foo.js``` from ```./pages/about.js```
And current route equals ```localhost:3000/about```
When I create file ```./components/Foo.js```
And I change route to ```localhost:3000/contact```
And change route back to ```localhost:3000/about```
Then the file import is error free

**Comment by Neorama** [comment]
Trying learnextjs tutorials and the same error occurs and cant be resolved. restarted server and I  have no clue what else to do.

**Comment by sergiodxa** [comment]
I tried this with the latest version of Next.js and I can't replicate it, I tried it with the first comment workflow and changing the name of a page file.

**Comment by timneutkens** [comment]
Going to close this because of inactivity and Sergio checking if it was solved 🙏
