### ISSUE TITLE
`with-amp`example. Internal server error on browser refresh.

### ISSUE THREAD

**Issue by vdesbarres** [zeit/next.js#1595]
Hi,
`with-amp` example pop an `Internal server Error`on browser refresh, in dev mod.
React Developper tools do not mount.

Terminal:
` Invariant Violation: injectDOMPropertyConfig(...): You're trying to inject DOM property 'amp' which has already been injected. You may be accidentally injecting the same DOM property config twice, or you may be injecting two configs that have conflicting property names.
`

**Comment by hieuhlc** [comment]
I tried this example and figured out if I remove the `injectDOMPropertyConfig` amp is still functioning. Don't really know why.

**Comment by arunoda** [comment]
@impronunciable any help on this?

**Comment by impronunciable** [comment]
Interesting. I can take a look as soon as I have some time

**Comment by impronunciable** [comment]
@vdesbarres thanks for the report and sorry for the so late answer, I just submitted a PR
