### ISSUE TITLE
Misleading Router.push error message

### ISSUE THREAD

**Issue by pungggi** [zeit/next.js#1596]
**Maintainer Notes:**

It's pretty great if we can show a meaningful error, if there's no such page.
It currently show a 404 when the URL includes a root slash like "/not-exisiting-page" .
But in the following case it won't work.
We need to fix that.

---

I am using next/Router (ver 2.0.1)

with Router.push('somePage') from within a HOC.

It works, bu**t between the pagetransition** this errors shows up:
![image](https://cloud.githubusercontent.com/assets/5635709/24586015/13166722-1798-11e7-90da-269eeef41e9b.png)

**Comment by pungggi** [comment]
Sorry, my fault  
Corrected ` Router.push('somePage') `
to ` Router.push('**/**somePage') `

**Comment by Flamefork** [comment]
Happened to me too.
The error displayed is misguiding, seems like a good area for improvement.

**Comment by arunoda** [comment]
@Flamefork yes it it.
Let me reopen this issue.

**Comment by pungggi** [comment]
@arunoda 
Is this by design that the following is working:
`<Link href="about"><a>here</a></Link>`
exactly like
`<Link href="/about"><a>here</a></Link>` ?

**Comment by arunoda** [comment]
@pungggi That's working because it'll add the relative url to that.
But `Router.push()` can't do that.
