### ISSUE TITLE
Ability to use with Mithril and other non-react-like client frameworks?

### ISSUE THREAD

**Issue by balupton** [zeit/next.js#1602]
Late last year I used next.js for a project and loved it. Earlier this year I used [Mithril](https://mithril.js.org) v1 for a project and loved it. However, using Mithril on the client with Next for the wrapper, would be the best.

I know there are examples currently with Inferno and Preact, however they maintain a react-like API adapters, which Mithril does not.

How easy it would it be to swap out React for another client-side-framework which concepts may or may not map cleanly to react? Or should it be done as a complete fork or inspired project, in the way that nuxt.js is to next.js.

**Comment by arunoda** [comment]
Currently our focus is only for React. We like to support non-react frameworks. But not in the near future.

We've a lot of things yet to be done for Next.js and it's easy for us to focus on a single UI framework to build those.

**Comment by balupton** [comment]
Ok thanks!
