### ISSUE TITLE
how to solve parse 

### ISSUE THREAD

**Issue by Wolke** [zeit/next.js#1603]
as question 
In parse sdk
I have to use "parse/node" in server side;
and "parse" in client side;

but if I import "parse/node" in getInitialProps scope , it always show 
===========
These modules were not found:

* child_process in ./~/xmlhttprequest/lib/XMLHttpRequest.js
* fs in ./~/xmlhttprequest/lib/XMLHttpRequest.js, ./~/options/lib/options.js and 1 other
* tls in ./~/ws/lib/WebSocketServer.js

============

**Comment by arunoda** [comment]
Seems like some kind of server only code used in your app. That's why webpack throws an error. 

We'd like to have a sample repo where we can reproduce this issue.

**Comment by Wolke** [comment]
find a way to solve by myself
use custom-server-express
use parse/node in there and write api for pages/
and in pagse/index.js
on getInitialProps to call fetch /api to get data then render ;

**Comment by arunoda** [comment]
That's another a way to do it.
Closing this issue.
