### ISSUE TITLE
Children in <Link> cause Invariant Violation #143

### ISSUE THREAD

**Issue by flagello** [zeit/next.js#1605]
**Code**
```html
<Link prefetch route='route' params={{param: '1'}}>
  <a><span>string</span></a>
</Link>
```

**Error**

`React.Children.only expected to receive a single React element child.`
[_`Invariant Violation: Minified React error #143`_](https://facebook.github.io/react/docs/error-decoder.html?invariant=143)

**Environment**

Production-only, `v2.0.1`

**Add-on**

[`fridays/next-routes`](https://github.com/fridays/next-routes)

**Workaround**

`Router.prefetch`

**Comment by flagello** [comment]
Within my environment the error can be reproduced with something as simple as:
```javascript
// test.js
import Link from 'next/link'

export default props => (
  <div>
    <Link href='/'>
      <a>example</a>
    </Link>
  </div>
)
```

```javascript
import Test from './test'

// render
// ...
   <Test />
// ...
```

Still production-only.

**Comment by jonaswindey** [comment]
Are you sure you don't have adjacent items in your link?
```jsx
<Link>
   <div>...</div>
   <img />
</Link>
```

for instance, won't work.

**Comment by flagello** [comment]
@jonaswindey Thanks for the reply Jonas.

Yes, it throws even with a single standard <a> child. There must be something else going on.

**Comment by arunoda** [comment]
@flagello can we have a sample repo for that.
I can't re-produce the issue.

**Comment by arunoda** [comment]
Reopen when you add it.

**Comment by wzalazar** [comment]
@arunoda , Hi, I have the same issue, this is my component. It's very simple. Only I need repeat a list with routes. Recently, install NextJS version 2.2.0

```
import Link from 'next/link';
import { Component } from 'react';
import PropTypes from 'prop-types';

export default class List extends Component {
  static propTypes = {
    items: PropTypes.arrayOf(PropTypes.shape({
      name: PropTypes.any.isRequired,
      href: PropTypes.any.isRequired,
    })),
  }

  static defaultProps = {
    items: [],
  }

  render() {
    const { items } = this.props;

    return (
      <ul>
        {items.map((item, key) => {
          return <li key= { key }>
                    <Link href= {item.href}> <a>{item.name}</a> </Link>
                 </li>;
        })}
      </ul>
    );
  }
}
```

**Comment by jonaswindey** [comment]
I've seen that error before and restarting the server helped.

@wzalazar: are you also only having the error in production mode?

**Comment by jonaswindey** [comment]
I was able to reproduce the error
```js
<Link prefetch href={{item.href}}><a>{item.name}</a></Link>
```
**works**, but
```js
<Link prefetch href={{item.href}}> <a>{item.name}</a> </Link>
```
**doesn't** and gives the error you mentioned.

Notice the spaces before and after the <a> tags

@arunoda it seems like React considers the inner spaces as elements (or as null) which throws the error `Invariant Violation: React.Children.only expected to receive a single React element child.`

Error also occurs with only one space.

**Comment by jonaswindey** [comment]
It seems like this error is expected behaviour: https://discuss.reactjs.org/t/jsx-newline-bug/3242

Spaces are preserved in JSX so they are considered as child elements.

**Comment by wzalazar** [comment]
@jonaswindey you're right, that is the reason of bug :)

**Comment by joelburget** [comment]
I have a scenario where this is pretty inconvenient -- in my blog I parse and render markdown with [remark](https://github.com/wooorm/remark) and [remark-react](https://github.com/mapbox/remark-react), which tends to call `<a>` with something like `["link text"]` as children. This bypasses the `if (typeof children === 'string') {` check in `next/link` and then throws at `const child = Children.only(children)`.

I was able to [work around](https://github.com/joelburget/blog.next/commit/feccb9dd574aa96053398c78e5b3fa23beaa3cab) in this case with:

```javascript
function MyLink({ children, href, as }) {
  let validChildren = children;
  if (Array.isArray(children) && children.length == 1) {
    validChildren = children[0];
  }
  const props = {children: validChildren, href, as};
  return <Link {...props} />;
}
```

... but it would be wonderful if this just worked :)

I'm not sure exactly who's at fault in this case:
* `remark-react` for passing an array? This seems okay to me.
* `react` (15.5.4) for throwing on a single-element array? Possibly.
* `next` for calling `Children.only`? It's not clear to me why next calls `Children.only`...

**Comment by jonespen** [comment]
@joelburget I'm having the same issue (I think), but with [js-lingui](https://github.com/lingui/js-lingui). I'm trying to [create a simple example using next.js and js-lingui](https://github.com/jonespen/next.js/tree/with-js-lingui/examples/with-js-lingui), but getting the `Invariant Violation: React.Children.only expected to receive a single React element child.` error when using a `Link` inside a js-lingui [`Trans`](https://lingui.github.io/js-lingui/ref/lingui-react.html#component-Trans) component. All other components works fine. I guess it does something like remark-react. 

So, who's to "blame"? Did you figure out anything @joelburget?

**Comment by joelburget** [comment]
@jonespen I didn't take this any further after I figured out my workaround.

**Comment by prakharrke** [comment]
My problem got solved by putting a Text tag within the link and then adding the text inside the Text tag.

Instead of,
<Link to="/some-link">Some Link</Link>

Try,

<Link to="/some-link"><Text>Some Link</Text></Link>

Hope this helps.
