### ISSUE TITLE
onRouteChangeComplete with anchor link

### ISSUE THREAD

**Issue by sarovin** [zeit/next.js#1609]
With 2.0.0-beta.35 i can use the onRouteChangeComplete function with the anchor link but with 2.0.0-beta.36 the onRouteChangeComplete not work if the anchor is in the same page.
Is it normal?

I have a global menu with links to others pages and anchor links. If i go from `/progetto` to `/index#a`, the onRouteChangeComplete does work but if i go from `/index` to `/index#a` onRouteChangeComplete does not work.

**Comment by arunoda** [comment]
@sarovin yes. This should be the correct behavior. We don't do it for hash changes.

**Comment by sarovin** [comment]
I want control the hash change because i must set as active the link in menu and scroll in the anchor...what is the right way?

**Comment by arunoda** [comment]
@sarovin for that you need to get the hash directly from the browser. `location.hash`

**Comment by sarovin** [comment]
Thank you @arunoda ;)

**Comment by anomaly44** [comment]
@sarovin What's your solution? I have the same problem as in your gif, but i have no idea how to solve it.

**Comment by sarovin** [comment]
You cannot control the hash change woth nextjs
