### ISSUE TITLE
Question: Support for JSX file extension

### ISSUE THREAD

**Issue by timReynolds** [zeit/next.js#161]
Does next.js support the jsx file extension? From trying locally under dev it seems that only .js files are loaded not .jsx? 

If this is the case is not supposing .jsx in the loader a deliberate design choice? 

Thanks

**Comment by impronunciable** [comment]
@timReynolds next.js does not support the jsx file extension. There are many reasons for limiting to js files being simplicity for pages detection and linting configuration some of them.
