### ISSUE TITLE
Support for purifycss

### ISSUE THREAD

**Issue by bobvanderlinden** [zeit/next.js#1613]
[Purifycss](https://github.com/purifycss/purifycss) removes unused css rules based on html pages. It reduces the size of css frameworks like bootstrap or semantic-ui significantly.

Would it be possible to use purifycss with next.js when using external css files?

**Comment by lednhatkhanh** [comment]
+1 This is exactly what I'm looking for!

**Comment by timneutkens** [comment]
Might be possible with static exports. An pull request with example is welcome 😄
