### ISSUE TITLE
HapiJs process.binding is not supported

### ISSUE THREAD

**Issue by renehauck** [zeit/next.js#1614]
Hi,

I use HapiJs on the server-side and I have this function:

```
 this.server.route({
            method: "POST",
            path: Routes.Login,              
            handler: (request, reply) => {
               ...
            }
        })
```
If I add a validation to this function:
```
 this.server.route({
            method: "POST",
            path: Routes.Login,
                config: {
                   validate: {
                       payload: {
                           email: Joi.string().email().required(),
                           password: Joi.string().min(5).max(100).required(),
                       }
                   },
               },
            handler: (request, reply) => {
               ...
            }
        })
```
i get always this error-message:

> process.binding is not supported
>     at Object.process.binding (browser.js?2c72b87:173)
>     at Object.eval (eval at evalScript (eval-script.js?c3c3587:22), <anonymous>:6779:25)
>     at Object.893 (eval at evalScript (eval-script.js?c3c3587:22), <anonymous>:6857:30)
>     at __webpack_require__ (bootstrap 2796216…?8ce1719:693)
>     at fn (bootstrap 2796216…?8ce1719:110)
>     at Object.eval (eval at evalScript (eval-script.js?c3c3587:22), <anonymous>:3158:22)
>     at Object.601 (eval at evalScript (eval-script.js?c3c3587:22), <anonymous>:4753:30)
>     at __webpack_require__ (bootstrap 2796216…?8ce1719:693)
>     at fn (bootstrap 2796216…?8ce1719:110)
>     at Object.<anonymous> (string.js?d42dd4f:5)

Is this a bug, or what am I doing wrong?

Thank you :smiley:

**Comment by renehauck** [comment]
Little Update:

it works when I write the validation like this:

```
...
 config: {
                validate: {
                    payload: {
                        email: require('joi').string().email().required(),
                        password: require('joi').string().min(5).max(100).required()
                    }
                },
            },
...
```
when I import like this:

`import * as joi from 'joi'`
or
`import joi from 'joi'`
or
`const joi = require('joi');`
it doesn't works

very strange

**Comment by jonaswindey** [comment]
Can't reproduce this.

Did you add joi as a dependency?
It works for me when I use `const Joi = require('joi')`
Validation:
```js
config: {
      validate: {
        payload: {
          email: Joi.string().email().required()
        }
      }
    }
```
Using joi `"^10.4.1"`

**Comment by renehauck** [comment]
Sorry for the late reply.
[The solution](https://github.com/hapijs/joi/issues/1149#issuecomment-305956651)
