### ISSUE TITLE
Add glob dependency

### ISSUE THREAD

**Issue by millette** [zeit/next.js#1618]
Since glob is a peer depency on glob-promise, should glob be added to next's package.json, either as a dependency or as a peer dependency? In the first case, the warning would go away; in the latter, it would be slighly more explicit and a user would add glob himself to his dependencies.

**Comment by arunoda** [comment]
@millette I think we should add it as a dependency.
I wonder why I didn't see that warning. 
May be I'm using a newer NPM version.

**Comment by arunoda** [comment]
BTW: Could you send a PR?

**Comment by millette** [comment]
I'm using yarn 0.21.3 - PR coming up.
