### ISSUE TITLE
Feature Request: build mode which outputs all html files

### ISSUE THREAD

**Issue by danielberndt** [zeit/next.js#162]
Hey there! First off: thanks a lot for putting this library online. The community will definitely benefit from having such an easy path to super-performant pages 👍

I was actually evaluating next.js for creating a docs for one of my github repos, but only later I realised that the next.js build process doesn't output any html pages which can be used for e.g. gh-pages. This would actually be a really nice option to have and I guess a common enough use case!

In case it's helpful, I'll link [to this library](https://github.com/markdalgleish/static-site-generator-webpack-plugin) which I successfully used to do something very similar.

**Comment by ugiacoman** [comment]
`wget --mirror` Thank @jamo

**Comment by danielberndt** [comment]
Thanks @ugiacoman for the tip! Not ideal but a good hack!

Also I just realised it's a duplicate of #70. So closing this. Sorry for the noise!
