### ISSUE TITLE
Deploy all the examples to now.sh

### ISSUE THREAD

**Issue by paulmolluzzo** [zeit/next.js#1621]
The links to the deployments can be added to the README.

Alternatively, only add a "Deploy with Now" button to all the READMEs.

**Comment by timneutkens** [comment]
I like the second option 👌🏻

**Comment by paulmolluzzo** [comment]
Is there a "Deploy with Now" button? I remember seeing one someplace but can't find it now.

// @leo

**Comment by timneutkens** [comment]
https://deploy.now.sh/

**Comment by timneutkens** [comment]
I see you already found it 😄

**Comment by paulmolluzzo** [comment]
You can now deploy subdirectories with deploy.now.sh!

Each README would get a button like: [![Deploy to now](https://deploy.now.sh/static/button.svg)](https://deploy.now.sh/?repo=https://github.com/zeit/next.js/tree/master/examples/basic-css)

Code would be: 
`[![Deploy to now](https://deploy.now.sh/static/button.svg)](https://deploy.now.sh/?repo=https://github.com/zeit/next.js/tree/master/examples/basic-css)`
