### ISSUE TITLE
Next + IPFS

### ISSUE THREAD

**Issue by thisbejim** [zeit/next.js#1622]
Using Next with [js-ipfs-api](https://github.com/ipfs/js-ipfs-api) throws an error on the client side: `Uncaught TypeError: Object prototype may only be an Object or null: undefined`. Here is a minimal [repro](https://github.com/thisbejim/next-ipfs).

The IPFS people have a browser example up that works with webpack ([webpack-node-ipfs-api-demo](https://github.com/VictorBjelkholm/webpack-node-ipfs-api-demo)) but I was unable to figure out the differences in next's config that could be causing this error.

Any ideas? Cheers.

**Comment by sedubois** [comment]
Why did you close, can you explain if you found a solution?
