### ISSUE TITLE
use in component  <style jsx>， repeat output

### ISSUE THREAD

**Issue by durongzhang** [zeit/next.js#1623]
I have a problem

Use of a component <style jsx>, loop this component repeat output

A.js
```js
export default () => (
  <div>
      11111
      <style jsx>{`
         .content{padding: 10px}
     `}</style>
  </div>
)
```

index.js
```js
import A from 'A';

const arr = [1,2,3]

export default () => (
  <div>
    2222222
    arr.map((obj, key) => {
    return  <A  key={key}  />
  })
</div>
)
````
Where the contents of the <A /> component <style  jsx> will be exported 3 times;

How to avoid this problem?

**Comment by timneutkens** [comment]
@durongzhang Could you submit this issue to https://github.com/zeit/styled-jsx?

**Comment by durongzhang** [comment]
ok，thank you
