### ISSUE TITLE
a old webpack problem; make bundle file bigger

### ISSUE THREAD

**Issue by Wolke** [zeit/next.js#1625]
for example:
in the example of react-md ,
if I  copy pages/index,js to pages/a.js
it will make the bundle file be double.
but I think it should be have a way to different page to get different bundle file , not just use same bundle file. 
it always make the bundle file bigger and bigger.

**Comment by frol** [comment]
@Wolke Hey, react-md example author is here!

Your description is not quite clear, so I will need to clarify a few points here (please, consider to be more elaborative in future):

1. Do you run the app in development mode (`npm run dev`) or in production mode (`npm run build && npm run start`)?
2. Which bundle do you refer to?
