### ISSUE TITLE
[question] how to add custom header for resource  response

### ISSUE THREAD

**Issue by foxundermoon** [zeit/next.js#1626]
i am writing a embed page for one mobile app, and it need https and must behind approved  domain.

so i am  use nginx to proxy https to http then by ssh-remote-forward to forward request to local

and than the normal resource(html,js css....) can load but HMR (webpack hot middleware) client  can not load
```
GET https://my.domain/_next/-/commons.js net::ERR_CONTENT_LENGTH_MISMATCH
bootstrap b0645f2…?4e27764:693 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap b0645f2…?4e27764:693)
    at fn (bootstrap b0645f2…?4e27764:110)
    at Object.553 (main.js:7)
    at __webpack_require__ (bootstrap b0645f2…?4e27764:693)
    at webpackJsonpCallback (bootstrap b0645f2…?4e27764:23)
    at main.js:2
```

i am found the solution
**steps**
1. turn off `nginx cache` and `buffing`
2. set http version 1.1 and `connection` header ''
3. add response  header `X-Accel-Buffering: no`

after step 2, it load success.
step 3 is no need but I also want  how to add custom header for  resource load  `/_next/-/*`

**Comment by arunoda** [comment]
Use our custom server: https://github.com/zeit/next.js#custom-server-and-routing
