### ISSUE TITLE
Handle _next and other core routes automatically 

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#1627]
Currently user have to specify a set of custom routes to define for some internal URLs. 

That's not nice and we should work on a solution which does not break the current API.

**Comment by fridays** [comment]
It would be great if it would export an array of reserved paths:
```javascript
const nextPaths = [
  '/_next',
  '/_webpack/',
  '/__webpack_hmr',
  '/static/'
]
```
[next-routes](https://github.com/fridays/next-routes) currently has it hardcoded and checks it like so:
```javascript
isNextPath (url) {
  return nextPaths.some(path => url.startsWith(path))
}
```

**Comment by arunoda** [comment]
@fridays I have a idea which works without any user intervention.

**Comment by sergiodxa** [comment]
@arunoda with this it's not required to do `app.get('*', (req, res) => handle(req, res))` anymore to handle Next internal URLs?

**Comment by rauchg** [comment]
You still need to do that. This simplifies situations where you want to make `/:anything` work, and that `anything` you have to make sure doesn't interfere with internal Next.js routes.
