### ISSUE TITLE
next dev output transience can make can make debugging difficult 

### ISSUE THREAD

**Issue by possibilities** [zeit/next.js#1629]
Server side console.logs show for a moment and then dissappear. Often I have to scroll to read the output because it shows only briefly. Would you be willing to introduce a cli flag to disable this?

**Comment by aranajhonny** [comment]
Usually happens. Is really uncomfortable.

**Comment by arunoda** [comment]
Yes. This is something we can improve.
If anyone could help us to do this, this is great.

**Comment by possibilities** [comment]
I dug around a bit but I'm not 100% what code governs this. Seems like it might all be handled by fly which doesn't immediately lead me to any obvious configuration on that side that would resolve it. Am I headed in the right direction? Any tips!? (:

**Comment by aranajhonny** [comment]
This happens. When build the first time.
![captura de pantalla 2017-04-08 a las 22 51 30](https://cloud.githubusercontent.com/assets/9091881/24831265/d571fc5c-1c64-11e7-8a52-52d5d12b1f05.png)

**Comment by arunoda** [comment]
@possibilities this is done by the friendly errors plugin.
See: https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L128

So, we may need to do something about it.

**Comment by gcpantazis** [comment]
That being the case, why not just leave this as-is and fix using `next.config.js` if you dislike it?

```
module.exports = {
    webpack: (config, {
        dev
    }) => {
        config.plugins.forEach((plugin, idx) => {
            if (plugin.constructor.name === 'FriendlyErrorsWebpackPlugin') {
                config.plugins.splice(idx, 1);
            }
        });
        
        return config
    }
}
```

**Comment by timneutkens** [comment]
I agree with @gcpantazis. If any this should be fixed in `FriendlyErrorsWebpackPlugin`.
