### ISSUE TITLE
app.js on slow connections

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1630]
The new version of next inlines `NEXT_DATA` and downloads `app.js` in production. 

This is really nice that it is deferred and the page is usable.

The problem that I have ran into is that I have a few basic things that I need available before `app.js` downloads.

Is there a way to "escalate" JS code to be rendered earlier, preferably inline?

**Example -** 

Menu Button on mobile requires JS to open. 
Menu is not clickable until app.js is downloaded.

**Question -** 

What are the ways others have solved this problem?

**Concerns -** 
Can't use `<HEAD>` because that is performance negative, and is before any dom elements have been mounted. Can't get access to traditional react states, like componentDidMount.

**Comment by impronunciable** [comment]
@khrome83 not sure if this is what you need but you can override the whole document by providing your own `pages/_document.js` https://github.com/zeit/next.js#custom-document there you can add your own scripts

**Comment by arunoda** [comment]
@khrome83 if you use Links there links are clickable.
The problem you mentioned is unique for SSR enabled SPAs.
What I recommend is to show a message on for users, only if it's rendered via SSR and remove it with the client render.

Not exactly the same, we are doing something related here: https://github.com/zeit/next.js/pull/1611

**Comment by khrome83** [comment]
I think that is a pretty terrible experience.

Next is all about SSR experiences. The page downloads and you can't interact with it. Yes link will work.

But the JS placed into a component to expand/collapse a menu that contains link does not.

The time difference between loading page (small payload) and loading app.js (larger payload) is pretty significant. Showing a message saying loading... and then removing it seems less than idea for really really basic functionality. Full widgets that query database and render maps, sure users are use to waiting for that. But the really really basic button to open a menu, makes the site feel broken.

What I am saying, is that we need a way to identify components that should be bundled earlier.

If I was able to bundle my menu, the expander, and a single section component (deep) i would not have that issue.

Is there a better way to solve this that allows us to work with components (state) and still not cause this problem.

Remember before we deferred the app.js loading, the page was not complete. Additionally before we had two bundles, one for my code and one for next. If we deferred the next code by loaded mine non deferred that may solve the issue. Thoughts?

---
Zane Milakovic

**Comment by khrome83** [comment]
@arunoda - i don't understand the connection to #1611 

Can you take a second to explain?

**Comment by reezon** [comment]
a problem with me too. there is our website built by next.js: https://www.hanfeiziphoto.com

the top slider and the popup sub menu don't work until the images loaded.

because of the app.js loading at the end of the html file.
