### ISSUE TITLE
Is it kosher to require modules during componentDidMount?

### ISSUE THREAD

**Issue by makeitrein** [zeit/next.js#1631]
I'm trying to incorporate http://codemirror.com/ into my application, tricky since CodeMirror does not play nicely with SSR... "_window is not defined_" errors out the wazoo.

To fix this issue, I required CodeMirror during componentDidMount so it had access to the window object... see below...

```
export default class CodeMirrorEditor extends React.Component {

    static async getInitialProps ({query}) {
        return {}
    }

    componentDidMount () {
        initCodemirror(window, "codemirror")
    }

    render () {
        return <div id="codemirror"/>
    }
}


function initCodemirror(window, elementId) {
    window.CodeMirror = require('codemirror');
    require('codemirror/mode/javascript/javascript');

  // TODO: Some API calls to populate editor...

    window.CodeMirror(document.getElementById(elementId), {mode: 'javascript', lineWrapping: true });
} 
```

It works! I'm a bit concerned whether this is a best-practice or not... does Next.js handle code-splitting and prefetching for things that aren't top-level imports? 

Secondly, is it even worth it to get CodeMirror to work server-side? 

As it is, I could probably create something in JSX/CSS that looks just like the editor, populate the editor with content in getInitialProps, then CodeMirror could be initialized client-side to make it functional.

**Comment by arunoda** [comment]
I think that's how code-mirror works. (Not tested)

> Secondly, is it even worth it to get CodeMirror to work server-side?

That's depend on your requirment :) 
Codemirror is kind a big one. It might affect the CPU usage in the server.
So, if I'm doing it, I won't render it on the server.
