### ISSUE TITLE
~50% unused bytes in app.js with Chrome Dev Tools Coverage

### ISSUE THREAD

**Issue by flagello** [zeit/next.js#1633]
[Chrome Dev Tools code coverage utility](https://twitter.com/addyosmani/status/848907772318015488)

—

<img width="698" alt="screen shot 2017-04-06 at 02 23 23" src="https://cloud.githubusercontent.com/assets/649779/24732472/69db0ad2-1a71-11e7-862f-3b46c8a14314.png">

In production, of course.

—

Apart from the CSS (first time using `styled-jsx` and will need to improve shared styles design or use something like `styletron`) — have I misunderstood the automatic code splitting feature?

To give some context, I use a HOC to wrap each page, and I'm passing both methods and props that don't necessarily get used by each page. Additionally: I may have been careless here and there with some imports; I use [re-base](https://github.com/tylermcginnis/re-base) which currently imports all of Firebase (not necessary in my use case).

Am I possibly mixing webpack's `automatic code splitting` with `static analysis and tree shaking` a là rollup? If so,

1. Should Next perform tree-shaking and dead code elimination?

2. If not, do you have any suggestions regarding how to approach and solve this problem? Chrome Dev Tools coverage results [cannot be exported trivially just yet](https://twitter.com/addyosmani/status/849263908720267264) and therefore I'm not sure how to identify unused code paths and imports with the minified output.

3. Would using something like [webpack-rollup-loader](https://github.com/erikdesjardins/webpack-rollup-loader) be possible and make sense?

4. Can any of this lead to improvements to the already awesome way Next works?

Thanks!

**Comment by arunoda** [comment]
I assume this is because how webpack handles tree-shaking.
It needs ES2015 modules. I hope React doesn't provide that and that's why this is.
But I would like to experiment here. Any ideas/improvements welcome.

**Comment by flagello** [comment]
Possibly related to [webpack#2867](https://github.com/webpack/webpack/issues/2867)?

**Comment by sedubois** [comment]
Linked from that thread, here is apparently a utility to test if tree shaking happens properly in Webpack: 
https://github.com/halt-hammerzeit/es6-tree-shaking-test
