### ISSUE TITLE
FOUC with SVG path fill by url

### ISSUE THREAD

**Issue by flagello** [zeit/next.js#1634]
Given the following within an SVG's `<defs>`

```html
<linearGradient id="a068ba7e-9000-4c49-af42-88079d82b121" ...>
  <stop offset="0" stop-color=... />
  <stop offset="1" stop-color=... />
</linearGradient>
```

and

```html
<path id="e92ace38-35e5-42da-b99a-2be3e7652e52" d=...
      style="fill:url(#a068ba7e-9000-4c49-af42-88079d82b121)" />
```

`<path>` is unstyled just until app.js finishes loading. Is there any way to adjust the urls or Next routing to allow for standard behavior?

**Comment by arunoda** [comment]
May be `<linearGradient />` is rendered via the `app.js`. I'd like to have a sample repo for this.
Re-open when you have it.
