### ISSUE TITLE
2x size of the initial bundle load

### ISSUE THREAD

**Issue by mohitgupta1918** [zeit/next.js#1637]
I am using next.js with express server.

I have created a single page(pages/index.js) that has a extremely long text( 9 Mb size ).

when i am running the application 
{
  "scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  }

after running npm run build, npm run start
The browser is loading a 18.5 Mb bundle.

[image](https://drive.google.com/file/d/0B-iTTjge8bqtS29wTmRERkpxOWc/view?usp=sharing)

after running the webpack-bundle-analyser I have identified
{
      "name": "dist/pages/index.js",
      "size": 9771946,
      "chunks": [],
      "chunkNames": [],
      "emitted": true,
      "isOverSizeLimit": true
    },
 {
      "name": "bundles/pages/index.json",
      "size": 9771839,
      "chunks": [],
      "chunkNames": [],
      "emitted": true,
      "isOverSizeLimit": true
    },
[Repo link :](https://github.com/pulkitnandan/web-frameworks-performance/tree/master/reactjs/expressHtml9MB)
Can someone explain  ?

**Comment by bringking** [comment]
@mohitgupta1918 this PR should address this - https://github.com/zeit/next.js/pull/1611. Essentially, next 2.0 inlines the current route bundle and component bundle into the `__NEXT_DATA__` object so it can be bootstrapped by the app on the client. @arunoda's PR moves the components into JS bundles that are loaded as plain script tags that are async. Does that make sense?

**Comment by arunoda** [comment]
Anyway, @mohitgupta1918 18MB is so wrong. I assume you are sending a lot of data via getInitialProps.

**Comment by arunoda** [comment]
Wow. That component is 9MB :) 
Don't load it as a component. Use a HTTP API or similar to load chunk by chunk. I hope no one is going to read that 9MB at once.

Anyway, #1611 should fix double loading issue.
