### ISSUE TITLE
Fabric CSS + Next.js document is not defined

### ISSUE THREAD

**Issue by rohmanhm** [zeit/next.js#1639]
I using [Fabric React by Microsoft](https://github.com/OfficeDev/office-ui-fabric-react) in my Next.js application. For first time load I got `document is not defined`, but for 2 or maybe 3 times I try to reload that pages it works. How it can be? How can I solve this problem, so I never see `document is not defined` everytime I restart my server.

**Comment by aranajhonny** [comment]
Could you provide an repo with example?

**Comment by luisrudge** [comment]
not a nextjs issue. please look here: https://github.com/OfficeDev/office-ui-fabric-react/issues/616

**Comment by rohmanhm** [comment]
@aranajhonny here's my repo https://github.com/rohmanhm/nextjs-fabric
when you run `npm run dev` for first time it will throw an error `document not defined` but if you load the page it will success without any errors.

**Comment by rohmanhm** [comment]
@luisrudge I'm not sure, so why it's just throw an error when I open the page after restart my server?

**Comment by luisrudge** [comment]
Not sure. what I'm sure is that you have to follow the lib's instructions to make it work with SSR

**Comment by rohmanhm** [comment]
First, take a look my repo https://github.com/rohmanhm/nextjs-fabric
I followed all instructions in here https://github.com/OfficeDev/office-ui-fabric-react#rendering-fabric-components-on-the-server-ssr

I just confused about this line
```javascript
import * as React from 'react';
import * as ReactDOMServer from 'react-dom/server';
import { Button } from 'office-ui-fabric-react/lib/Button'; 
 
let body = ReactDOMServer.renderToString(<Button>hello</Button>);
 
console.log(
  `
  <html>
  <head>
    <style>${ _allStyles}</style>
  </head>
  <body>
    ${ body}
  </body>
  </html>
  `);
```

How I can implement `renderToString` in nextjs

**Comment by aranajhonny** [comment]
It happens that the SSR is not working, I am reviewing your example.

**Comment by aranajhonny** [comment]
Turn off javascript in the browser, and you'll see it does not work.

**Comment by aranajhonny** [comment]
I think for now this will not work with next.js there are many  [things](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/utilities/src/scroll.ts)  incompatible with ssr.

**Comment by rohmanhm** [comment]
How can I handle `document not defined` in next.js?

**Comment by timneutkens** [comment]
Probably works when you use dynamic imports in `next@beta` https://github.com/zeit/next.js#dynamic-import

**Comment by andrasfodor** [comment]
Yes it's work fine, but with dynamic import is very slow. any other solution?
