### ISSUE TITLE
Path to webpack config

### ISSUE THREAD

**Issue by motleydev** [zeit/next.js#1641]
I'm incorporating Styleguidist to my app and want to reuse the next.js webpack config. I can define a path to my projects config file but I can't seem to figure out what that would be with next. There are several component documenting libs that need this type of ability - perhaps creating some kind of api for accessing the config object for merging into the styleguidist config file?

**Comment by arunoda** [comment]
Use this: https://github.com/zeit/next.js#customizing-webpack-config
With that, you can access our webpack config.

**Comment by motleydev** [comment]
Hi @arunoda - thanks for the reply! Both here and in Slack. Unfortunately as we discussed there, and as you advised to open an issue here, it doesn't solve the issue.
I need to be able to explicitly import the webpack config so that Styleguidist is able to re-use the settings. It's a separate server process and so things like conf and dev are not available envs.

What I need is to basically have /path/to/config.js

does that make sense?

https://github.com/styleguidist/react-styleguidist/blob/master/docs/Webpack.md#reusing-your-projects-webpack-config

**Comment by sapegin** [comment]
Looks like [there’s no config](https://github.com/zeit/next.js/blob/ea77b41570c7ce1755482a7a9e07254d1559fc5b/server/build/webpack.js ) that you can reuse in Styleguidist unless it will be extracted to a separate module.

@motleydev Could you find a workaround?

**Comment by motleydev** [comment]
Yes, recreate the webpack env manually. :) I think there might be a solution hidden in the fact that there's some kind of "parent" function that consumes the next.config.js file and is able to pass the entire config into the webpack function here https://github.com/zeit/next.js/#customizing-webpack-config - but I haven't taken the time to figure it out as I'm attempting to keep my code base as "vanilla" as possible and so recreating the config didn't represent substantial overhead.

**Comment by trungdq88** [comment]
Can we reopen this?

**Comment by renancouto** [comment]
I was able to get Styleguide running with just this piece of config:

```js
// styleguide.config.js
module.exports = {
    components: './components/**/*.js',
    webpackConfig: {
        module: {
            loaders: [{
                test: /\.js(\?[^?]*)?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    cacheDirectory: true,
                    presets: ['react'],
                },
            }],
        },
    },
};
```

But when I run `styleguide:build` I get an error:

```bash
Building style guide...

clean-webpack-plugin: .../styleguide/build has been removed.
Failed to compile.
Error in build/bundle.1aa4b834.js from UglifyJs
Unexpected token: punc (}) [build/bundle.1aa4b834.js:6019,31]
```

Any ideas? @sapegin ?

**Comment by sapegin** [comment]
@renancouto UglifyJS doesn’t support ES6, you need to transpile your JS to ES5.

P. S. What this part of regexp does — `(\?[^?]*)?`? :-|

**Comment by renancouto** [comment]
@sapegin not sure, I just copied from next.js webpack config.

**Comment by sapegin** [comment]
I see now — it’s an optional query string, like `foo.js?bar=42` ;-)

**Comment by renancouto** [comment]
Cool! BTW, adding `'es2015'` to `query.presets` and `babel-preset-es2015` as a dependency works like a charm! Thanks @sapegin for pointing that out.

```js
// styleguide.config.js
module.exports = {
    components: './components/**/*.js',
    webpackConfig: {
        module: {
            loaders: [{
                test: /\.js(\?[^?]*)?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    cacheDirectory: true,
                    presets: ['react', 'es2015'],
                },
            }],
        },
    },
};
```
Looks like this config is enough to run `styleguidist server` and `styleguidist build`.

**Comment by sapegin** [comment]
Or better babel-preset-env with uglify option ;-)

**Comment by renancouto** [comment]
Ah, even better! Thanks again @sapegin 😉

**Comment by billgloff** [comment]
I'm having an issue when trying to incorporate react-styleguidist into a NextJS 3 app:   

![image](https://user-images.githubusercontent.com/106020/29192466-2afc1c78-7de7-11e7-9968-bc3de6a66c39.png)

I even used the webpackConfig mentioned above.   

Anyone see this before or is there something else I have to do to get it to work?   Thanks in advance for the help.

**Comment by sapegin** [comment]
@billgloff Looks like something is overwriting our webpack aliases. I need a repo that I can debug to say more.

**Comment by hmontes** [comment]
So. I need to customize webpack config or not?

A tutorial would be nice. Styleguidist and Storybook are great tools to React Design

**Comment by woro83c** [comment]
The following styleguide.config.js did the trick for me:

```
module.exports = {
  components: 'components/**/*.js',
  webpackConfig: {
    module: {
      rules: [
        {
          test: /\.js(\?[^?]*)?$/,
          exclude: /node_modules/,
          loader: 'babel-loader'
        }
      ]
    }
  }
};
```
