### ISSUE TITLE
Replace babel-preset-latest with babel-preset-env

### ISSUE THREAD

**Issue by osartun** [zeit/next.js#1647]
I'm currently in the process of setting up next.js and got this notification:
```
$ npm install next react react-dom --save
npm WARN deprecated babel-preset-latest@6.24.0: 💥  preset-latest accomplishes the same task as babel-preset-env. 🙏  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env 👌. And let us know how you're liking Babel at @babeljs on 🐦
```
I'm assuming this comes from here: https://github.com/zeit/next.js/blob/6e0e2307dab46eeeda8fd761986f33350a811cee/package.json#L61

I have no idea if you're already aware of this. I've briefly searched the open issues and didn't find anything that related to this, so I figured I better open an issue for this. If you're already aware of this or have even solved it somewhere, I'm sorry – this is my first time setting up next.js so I have no experience or involvement with the project whatsoever.

**Comment by arunoda** [comment]
Yep. Would like to fix this issue.
