### ISSUE TITLE
Getting actual urls of page components on getInitialProps on client

### ISSUE THREAD

**Issue by nkzawa** [zeit/next.js#1650]
It seems there is no way to do that, since `ctx.pathname` and `ctx.query` are of file based route ones, and `location.href` is of previous page. Do we need this ?

**Comment by arunoda** [comment]
I think it's great if we can have `ctx.as` and `ctx.href` both.

**Comment by nkzawa** [comment]
`ctx.as` sounds good to me. I need `as` as an entire url string for now. I don't know if we need an object like `as.pathname` and `as.query`.

**Comment by arunoda** [comment]
> I don't know if we need an object like as.pathname and as.query.
Yeah! We don't need that.
