### ISSUE TITLE
TypeScript Definitions in DefinitelyTyped

### ISSUE THREAD

**Issue by jupl** [zeit/next.js#1651]
I have been working on typings for Next with TypeScript. I was about to add it to DefinitelyTyped, but any feedback to it first would be appreciated. https://github.com/jupl/DefinitelyTyped/tree/add-next/types/next

**Comment by sammkj** [comment]
@jupl Did you submit it to DefinitelyTyped already? Why was this closed?

**Comment by jupl** [comment]
@sammkj Sorry about that. I actually got things more or less ready to submit a PR to DefinitelyTyped, but wanted to get feedback on the typings first. If you want to see/try it out check it out here. https://github.com/jupl/DefinitelyTyped/tree/add-next/types/next

**Comment by sammkj** [comment]
@jupl nice! It looks pretty complete! Wouldn't it be better if the definitions live in this repo? It takes a lot of time and effort to get things done in `DefinitelyTyped` repo

**Comment by mattferderer** [comment]
It appears the context object is missing:
`getInitialProps` receives a context object with the following properties:

- `pathname` - path section of URL
- `query` - query string section of URL parsed as an object
- `asPath` - the actual url path
- `req` - HTTP request object (server only)
- `res` - HTTP response object (server only)
- `jsonPageRes` - [Fetch Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) object (client only)
- `err` - Error object if any error is encountered during the rendering

I can add this with a PR unless this is somewhere else that I haven't found yet.  Though I do agree it would be nice for the definitions to be in this repo instead.

**Comment by philcockfield** [comment]
Having type definitions in the repo/NPM module would be totally wonderful.

**Comment by sbking** [comment]
@jupl How about typings for next.config.js? Something like:

**Comment by timneutkens** [comment]
@arunoda what's your take on this?

**Comment by timneutkens** [comment]
Lets keep them in definitelyTyped.

**Comment by rohmanhm** [comment]
seems missing `getInitialProps` type

**Comment by HelloEdit** [comment]
seem to me always missing

**Comment by jonasblumer** [comment]
@mattferderer The Context object still seems to be missing. Did you ever make that PR?

**Comment by terencechow** [comment]
any plans on adding the context object? I'm new to typescript so not entirely sure how to do it otherwise I'd do it myself...

**Comment by jthegedus** [comment]
@terencechow I was going to PR something to DefinitelyTyped this weekend. I do want to solicit feedback so will link the PR here once it's up :+1:

**Comment by jthegedus** [comment]
A PR is open here for help and feedback. If you have experience with Typescript Types and/or the Next.js source please contribute code or discussions here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24231

**Comment by rouxfeur** [comment]
Has anyone found a way to have getInitialProps working with TypeScript? Or how to just silence the warnings? It feels like Next.js+TypeScript is a quite popular combo, how come so few people have encountered this issue? Isn't getInitialProps quite vital for Next.js workflow?

**Comment by resir014** [comment]
@jthegedus Any news on this? The PR seems to be closed. I'm also beginning work on typing the `renderPage` method if you still want to get this into the typings.

**Comment by resir014** [comment]
Will do, thanks!

**Comment by resir014** [comment]
@jthegedus Alright, I've pushed my changes into your fork: https://github.com/jthegedus/DefinitelyTyped/pull/1

Basically, I've adjusted some types that should be optional, made the object types more explicit, and finally added the `renderPage()` property. Should work with the examples on this repo which uses said function.

**Comment by ricklove** [comment]
@resir014 I am not seeing getInitialProps function working yet. Am I doing something wrong?

**Comment by resir014** [comment]
@ricklove `getInitialProps` can be manually typed

```ts
public static async getInitialProps(context: NextContext): Promise<any>
```

**Comment by ricklove** [comment]
@resir014 Sorry, I don't understand. 

Where would you put that? Also, there is no NextContext in the @types/next that I see (I only could find it in the pull request that was rejected).

**Comment by ricklove** [comment]
I see what you mean though, but that would only work with a React component class. How would you do this with a Stateless Component like the tutorial?

https://nextjs.org/learn/basics/fetching-data-for-pages/fetching-batman-shows

Also, it would be ideal to have getInitialProps as part of the object because then when creating an arrow function, the type for the context parameter is already inferred.

**Comment by resir014** [comment]
@ricklove Yeah, you can copy @jthegedus' fork of the typings [here](https://github.com/jthegedus/DefinitelyTyped/blob/master/types/next/index.d.ts) and include it in you project. It hasn't been merged yet, so this is how you'll have to do it for now.

And sorry, I haven't tried typing `getInitialProps` in stateless components. But you can get started extending React's `StatelessComponent<P>` interface.

I'll have time to look into this in the weekend.

**Comment by resir014** [comment]
@ricklove Here you go. Will PR this alongside the rest of these changes now.

```ts
interface NextStatelessComponent<P = {}> extends React.StatelessComponent<P> {
  getInitialProps?: (ctx: NextContext) => Promise<any>;
}
```

**Comment by chanlito** [comment]
Merging this anytime soon?

**Comment by rohmanhm** [comment]
@chanlito Apparently PR on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25711 has a conflict and need to be resolved.

**Comment by camiloei** [comment]
Any news about this? I'm having issues with getInitialProps too

**Comment by resir014** [comment]
Happy to announce that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25711 has been merged! 🎉 

Typings for `next/app` will soon be available via DefinitelyTyped.

**Comment by codinronan** [comment]
This is still incorrect. `getInitialProps` needs to be added to the component type received by App.

![image](https://user-images.githubusercontent.com/13020457/41751961-faec492c-7589-11e8-83ec-05ccd02d9ca0.png)

I may submit a PR if I can get some time.
