### ISSUE TITLE
Symbol in dirname cause break HMR 

### ISSUE THREAD

**Issue by kievechua** [zeit/next.js#1652]
One of the junior project path is as follow `~/projects/api (1)/`
When start the project using `next` it won't auto reload.
If change to `~/projects/api/`, everything work fine.
Actually it also break nodemon, so not sure it's require a fix.

**Comment by arunoda** [comment]
Simply don't use symbols.

**Comment by AleksandarDev** [comment]
@arunoda Are you serious? Can we atleast try to resolve this issue? 
I'm want to use directories with `.` prefix for generated content (eg. `.dist` and `.release`).

Everything works great but changes are not detected. If you don't intend to fix this issue, please reference it in docs.
