### ISSUE TITLE
when click 'back' in Safari, the req in getInitialProps is null

### ISSUE THREAD

**Issue by reezon** [zeit/next.js#1655]
I have 2 pages in my project: 
a.js

````
export default class PageA extends Component {
    static async getInitialProps({req, res, xhr, pathname, query, err}) {

      const headers = req ? req.headers : {};

            return {headers};
    }

    render() {
        return (
          <div>
            <div><a href='/b'>jump to b</a></div>
          </div>
        );
    }
}
````

b.js:

````
    export default class PageB extends Component {
    static async getInitialProps({req, res, xhr, pathname, query, err}) {
      const headers = req ? req.headers : {};

      return {headers};
    }

    render() {
        return (
          <div>
          <div><a href='/a'>jump to a</a></div>
          </div>
        );
    }
}
````

* in Safari, i open localhost:3000/a first;
* then click the href jump to b;
* then i click the 'back' button of Safari. 

I found the req of getInitialProps in a.js is null

the version of Safari is 10.0.3

**Comment by pesakitan22** [comment]
on the readme req and res is server only

**Comment by reezon** [comment]
@pesakitan22 but chrome works well. how could i figure out this problem? because all the fetching operations are in the getInitialProps

**Comment by arunoda** [comment]
req is server only.
You need to write your data fetching logic in an universal way.
