### ISSUE TITLE
Router Link problem

### ISSUE THREAD

**Issue by hchoriq** [zeit/next.js#1657]
Anyone have a Link problem where you click on a Link like such:

<Link href={`/${variable}/link`}><a>Text here</a></Link>

And router tries to fetch http://localhost:3000/_next/-/pages/link before it fetches http://localhost:3000/(variable)/link?

It seems like these lines may be causing the problem:

      var buildId = window.__NEXT_DATA__.buildId;

      var url = '/_next/' + encodeURIComponent(buildId) + '/pages' + route;

      return (0, _unfetch2.default)(url, {
        method: 'GET',
        credentials: 'same-origin',
        headers: { 'Accept': 'application/json' }
      });

**Comment by arunoda** [comment]
@hchoriq provide a sample app and re-open this issue.
