### ISSUE TITLE
decorators not working

### ISSUE THREAD

**Issue by pungggi** [zeit/next.js#1660]
hello any help appreciated on that issue. My babel config: `{
  "presets": [
      "next/babel"
  ],
  "plugins": [
      "transform-decorators-legacy",
      "styled-components"
  ]
}`

Decorators not working when **deploying to now**, but on my machine all works..
![image](https://cloud.githubusercontent.com/assets/5635709/24815725/838e2016-1bd6-11e7-9534-3c6d77609217.png)

**Comment by sgnl** [comment]
fwiw, my mobx injection looks like this:

`export default inject("store")(observer(({ store }) => {`

**Comment by sergiodxa** [comment]
Did you installed your Babel plugins as devDependencies? AFAIK Now doesn't install them, that's probably why it's not parsing your decorators.

**Comment by pungggi** [comment]
i tryied with moving from devDependencies to Dependencies but no luck

**Comment by sgnl** [comment]
reference this: https://mobx.js.org/refguide/api.html#-inject-mobx-react-package

**Comment by pungggi** [comment]
@sgnl the implementation with mobx decorators does work when next builds locally. So why not when deployed?

**Comment by arunoda** [comment]
It should work. 
Create a sample repo and send to us.

**Comment by arunoda** [comment]
Please re-open when you do so.

**Comment by pungggi** [comment]
hmm so stupid. i was ignoring the .babelrc file because of a rule in gitignore...
