### ISSUE TITLE
app version by git sha

### ISSUE THREAD

**Issue by steida** [zeit/next.js#1673]
It's good to have app version as git commit sha for error reporting. I'm not sure where to put this:

`const sha = childProcess.execSync('git rev-parse HEAD').toString().trim();`

Is the env-config.js the right place?

**Comment by arunoda** [comment]
Yeah! That's a good place to put this.

**Comment by steida** [comment]
Hmm, this can't work, because git is not installed in now and there is no commit sha anyway.

**Comment by arunoda** [comment]
Then try to build the app locally or send the hash via an env variable.

**Comment by steida** [comment]
@arunoda That's exactly what I am doing in Este. Will try in Next Este. Thank you.
