### ISSUE TITLE
nested-components : parent component being rerendered

### ISSUE THREAD

**Issue by Robbilie** [zeit/next.js#1674]
i am working on a project which used react-router for the routing, in that project i didnt have SSR and redux and such and so i was searching for an easy way to get all that, which next.js offers.

now my page was basically the pages basic structure with changing content (kinde like the nested-components example)

the router there looked like this:
```
<Router history={history}>
	<Route path="/" component={App}>
		<IndexRoute component={HomePage} />
		<Route path="alliances/:id/" component={AlliancePage} />
	</Route>
</Router>
```

now since each page in next.js is a file you have to put the <App> wrapped around the pages content, index.js render looking like this basically:
```
render () {
	return (
		<App>
			<HomePage />
		</App>
	);
}
```

now if i switch to a different page (like the Alliance Page) it looks like this:
```
render () {
	return (
		<App>
			<AlliancePage />
		</App>
	);
}
```

react with react-router would not rerender the <App> because it doesnt change and would only update the inner Page, next.js rerenders the complete thing, creating a new instance of <App> which wastes reacts functionality (and makes it completly useless for me)

any ways around this?

**Comment by sergiodxa** [comment]
Next.js doesn't rerender the complete thing, if you check the react component tree using the React DevTools you can see Next wrap your page inside various internal components, when the route change it calls `getInitialProps` and render only the page component, if some internal component doesn't change then React doesn't touch it.

**Comment by Robbilie** [comment]
so switching from home to alliance should not rerender <App> ?
under what condition would it not rerender <App>? 
the constructor is always being called atm so i must be doing something wrong then…

**Comment by Robbilie** [comment]
ok after trying the react dev tools, the component that is the page itself changes on each page change therefore a wrapping component is replaced and so everything is rerendered, from the looks of that, there seems to be no way to have a persistent component across multiple pages…

anyone who can give me an example that proves me wrong? :3

**Comment by arunoda** [comment]
I think we are talking about this in #88
