### ISSUE TITLE
Could use bundle.js in HTML file?

### ISSUE THREAD

**Issue by flyingpath** [zeit/next.js#1677]
Hi:

Is it possible to simply use

>   <body>
>     <script src="./.next/app.js"></script>
>   </body>

in an HTML file after build?
If not, is there a simple way to do like that?

Thanks very much!!!

**Comment by arunoda** [comment]
We keep all of our files under `.next` direct after you invoke `next build`.
So, you can import it as you like.

But I suppose, it won't work just including it. You may need to have a DOM element and other stuff.
Anyway, you can try.

**Comment by flyingpath** [comment]
Hi:

It said 'module is not defined'
What the other stuff could help me?

Thanks!

**Comment by MaolinYang** [comment]
I have the same problem.

I want to my project deployed to the server,then I can use the domain name to repalce localhost。

Can you help me?
Thanks!
