### ISSUE TITLE
Overriding the root element client-side

### ISSUE THREAD

**Issue by mtford90** [zeit/next.js#1679]
Hello there,

I'm attempting to integrate `react-notification-system` with next.

`react-notification-system` requires you to have this component at the root of the app. Given that next.js apps are organised in pages it seems to be impossible to do this. If `react-notification-system` is initialised on each individual page then you lose the notifications when routing between pages.

I attempted to initialise this within `pages/_document.js` but it appears that this is only used server side for the initial render.

Is there any way to hook into the `App` or `Container` component at the root?

For now i've had to add a rather hacky `ReactDOM.render` which is less than ideal...

**Comment by arunoda** [comment]
Currently not.
You can use a wrapper component for each and every page of your app.
In that, you can include your component.

**Comment by mtford90** [comment]
@arunoda Unfortunately that doesn't help. Using a wrapper component means that the component provided by `react-notification-system` is re-rendered everytime the user navigates which seems to destroy the notifications.

**Comment by arunoda** [comment]
Then this is a duplicate of #88 
Currently there's no good way to deal with this.

**Comment by mtford90** [comment]
Cool, I shall subscribe to that thread.

Cheers

**Comment by arunoda** [comment]
Awesome.
I'd also like to see it gets fixed soon. Let's see.
