### ISSUE TITLE
routing to Pages sub directories

### ISSUE THREAD

**Issue by MrLoh** [zeit/next.js#1681]
I really like that next uses the file system to set up routes, just like HTML files in folders work. But it's very limited with not even supporting sub directories. 

I set up a custom server that just reads all js files in pages and sets up routes based on that. 

```js
import { sync as glob } from 'glob'

const getRoutes = () => {
    const paths = glob('pages/**/*.js', {ignore: ['**/index.js', '**/_*', '**/_*/**']})
        .map(path => path.substr('pages'.length, path.length-('pages.js'.length)))
    const indexPaths = glob('pages/**/index.js', {ignore: ['**/_*/**']})
        .map(path => path.substr('pages'.length, path.length-('pages.js'.length)))
    let routes = {}
    paths.map(path => routes[path] = path)
    indexPaths.map(path => routes[path.substr(0, path.length-'index'.length)] = path)
    return routes
}

const routes = getRoutes()
```

I can then set up routes in an express server like so: 

```js
    for (let path in routes) {
        server.get(path, (req, res) => {
            const { params, query } = req
            return app.render(req, res, routes[path], {...params, query})
        })
    }
```

This even allows me to set up parameters I. Routes by just creating a `blog/:slug.js` file. 

Maybe something like this would give next some more basic functionality while staying pretty simple. And is useful for a lot of people. 

As a bonus, to make using links easier I can make my routes available by just writing them to a JSON file that can be accessed from react to automatically parse `as` and `href` props. 

```js
writeFile('static/routes.json', JSON.stringify(routes, null, 2))
```

Do you think something like this could be interesting for the future of next js?

You can see my full implementation [here](https://github.com/KijaniNGO/website)

**Comment by arunoda** [comment]
We've already discussed this with this is our solution: https://github.com/zeit/next.js#custom-server-and-routing

But feel free to implement these in the user-land. Just like [next-routes](https://www.npmjs.com/package/next-routes)
