### ISSUE TITLE
dev hot reload server not updating without restart when using tutorial

### ISSUE THREAD

**Issue by davidjnelson** [zeit/next.js#1683]
I'm playing around with next.js. Very cool stuff!

When I run ```npm run dev```, often times the code does not update without restarting the dev server, which is not so great.

For instance, going through this step of the tutorial:

https://learnnextjs.com/basics/create-dynamic-pages/special-prop-url

I wasn't getting the props to the child content component.

Since the source maps don't allow breakpoints inside stateless functional components that immediately return jsx, I modified them to be non fat arrow functions so I could set a breakpoint, ie:

```

import Layout from '../components/Layout.js'

const Content = function(props) {
	const toReturn = (
		<div>
			<h1>{props.title}</h1>
			<p>This is the blog post content.</p>
		</div>
	);

	return toReturn;
};

export default function(props) {
	const toReturn = (
		<Layout>
			<Content title={props.url.query.title}/>
		</Layout>
	);

	return toReturn;
};

```

Ideally, hot reload would pick this up without a page refresh and all would be well.  However, even with a page refresh, the source maps show the old code, and the application appears to be using the old code.

If I restart the dev hot reload server, it fixes it.

I am using next v2.1.0 on osx 10.12.3.

**Comment by mike3run** [comment]
I'm having that same issue 😢

**Comment by arunoda** [comment]
I have OSX 10.12.4 and I can't reproduce this issue.
@mike3run what's the OS you've.

**Comment by mike3run** [comment]
Same OS and version

**Comment by arunoda** [comment]
@mike3run Try using `v2.2.0`?

**Comment by mike3run** [comment]
I'm using now the latest next version with same results 😢

**Comment by mklemme** [comment]
@mike3run not having this issue anymore. I was trying revert to older versions and changed my `package.json`'s dev from `"dev": "next"`command to `"dev": "node server.js"`. Hot-reloading is working again.

**Comment by mklemme** [comment]
It's also worth noting that it looks like HMR happens when the files you're working on are inside `/pages`. Is that right, @arunoda?

**Comment by caffo** [comment]
I'm also having similar issues here.  Even on server starting, I don't get props into my child components. I see this when when I run the server or reload the page manually:

```
client.js?05d798a:67 [HMR] connected
client.js?05d798a:199 [HMR] bundle rebuilding
client.js?05d798a:207 [HMR] bundle rebuilt in 123ms
```

If I change anything in any component (including components outside the `pages` directory) I see this:

```
[HMR] Updated modules:
process-update.js?05d798a:102 [HMR]  - ./components/layout.js
process-update.js?05d798a:102 [HMR]  - ./pages?entry
process-update.js?05d798a:107 [HMR] App is up to date.
```

And props are passed in.  

Using `2.3.1`, with `"dev": "next"` as server.

**Comment by timneutkens** [comment]
@caffo can you please provide an example repository in a new issue.

**Comment by babenzele** [comment]
#1910 for reference
