### ISSUE TITLE
2.1.1 is latest release but only 2.1.0 is published to NPM

### ISSUE THREAD

**Issue by frankhale** [zeit/next.js#1686]
I wanted to update my app but found that NPM didn't have the latest version of Next published:

Latest Next release -> https://github.com/zeit/next.js/releases/tag/2.1.1

![next-211-on-github](https://cloud.githubusercontent.com/assets/190154/24863550/45c5412e-1dcf-11e7-9985-ba50b38764e1.PNG)

https://www.npmjs.com/package/next -> Only 2.1.0 is published on NPM

![next-210-on-npm](https://cloud.githubusercontent.com/assets/190154/24863547/402ce578-1dcf-11e7-8600-9b4f7ba8a2fb.PNG)

**Comment by d0whc3r** [comment]
`$ npm info next versions | grep "'2.1"`
![image](https://cloud.githubusercontent.com/assets/1378986/24863754/67f2cf40-1e02-11e7-90a7-11ae894c91e5.png)

It is in npm repo... probably in "beta" ?

**Comment by frankhale** [comment]
Thank you, this works!

**Comment by sedubois** [comment]
Nevertheless @rauchg 2.1.1 should be published as main I guess.

**Comment by sedubois** [comment]
or @leo?

**Comment by leo** [comment]
Fixed in https://github.com/zeit/next.js/commit/2337827c40d4d0e866fe72067b2c92ff4cbc5870 and updated the npm repo to make 2.1.1 the latest!

**Comment by timneutkens** [comment]
❤️

**Comment by frankhale** [comment]
Thank you!
