### ISSUE TITLE
Updating styles (HMR) not working properly in Safari(-like)

### ISSUE THREAD

**Issue by flootr** [zeit/next.js#1687]
I think I have found a bug which is occurs when using next.js in a development environment which includes:

- Safari
- mobile Safari
- Chrome using Apple devices in responsive mode (dev tools)

I was able reproduce this bug using the _basic css_ example from this repo. If I am changing styles within a `<style jsx />` component, HMR does not work properly (as I saw the `data-jsx` attributes from the component and the actual style tag are getting _"out of sync"_ or differ).

[Here's a link reproducing the bug in action](https://bug-ppnasmpgvd.now.sh/) (webm).

Please tell me if you think this issue should rather be opened on the styled-jsx repo.

**Comment by arunoda** [comment]
Yep. I can re-produce this.

**Comment by pietrasiak** [comment]
I've observed interesting thing:

When I modify the content of `<style jsx>` itself (change css), styles will get _'out of sync'_ and stop working. But if after that I'll modify the content of component itself eg. add some text to it - text will be added and **new styles** will be applied too.

**Comment by timneutkens** [comment]
I think this has been fixed since then, I've been styling with HMR on my iPad all week and didn't run into specific issues with HMR.

**Comment by probablyup** [comment]
I'm running into this on nextjs latest. Only Safari... which is pretty strange. Not sure exactly what to provide for debugging...
