### ISSUE TITLE
Route client to custom error page

### ISSUE THREAD

**Issue by nealalpert** [zeit/next.js#1688]
I have implemented custom error handling as per https://github.com/zeit/next.js#custom-error-handling and it seems to be working fine in the case of a 404 error.

How do I route the user to the custom error page along with a custom error message in the case that I have caught an error in my code?

**Comment by nkzawa** [comment]
You can require and render your custom error page like the following:

```js
import React from 'react'
import ErrorPage from './_error'

export default class Error extends React.Component {
  ...

  render () {
    if (this.props.statusCode) {
      return <ErrorPage statusCode={this.props.statusCode} message="error!" />
    }
    
    ...
  }
}
```

**Comment by arunoda** [comment]
> How do I route the user to the custom error page along with a custom error message in the case that I have caught an error in my code?

We don't have a built in functionality to route users to such a page. But as @nkzawa mentioned, you can import the ErrorComponent and render anywhere you want.
