### ISSUE TITLE
"An unexpected error has occurred" in Safari  9.1 (11601.5.17.1)

### ISSUE THREAD

**Issue by reezon** [zeit/next.js#1698]
when i surf my website: https://www.paipaix.cn in Safari  9.1 (11601.5.17.1)

when website loading, it seems fine.

after app.js loaded, the website suddenly jump to a blank page, which has "An unexpected error has occurred" in it 

then i try to surf this page in Chrome or IE edge, it goes fine

**Comment by arunoda** [comment]
That's it works fine in my box.
What's you safari version?

**Comment by arunoda** [comment]
I tested your app and the error happened on the Safari 9.1.
Try to do this:

Update your next version to the latest. (2.1.1)
Then try to load it on safari and check the browser console for the error message.
I assume, it's some NPM module or code used in your app.

I tested few Next.js apps we have a they work pretty well.

If you feel it's a Next.js after you got the error message, feel free to re-open this issue.

**Comment by reezon** [comment]
@arunoda My Safari Version is Safari 9.1 (11601.5.17.1). but it works fine in 10.0.3 (12602.4.8)

**Comment by reezon** [comment]
@arunoda I have found this error comes from react-intl because of polyfill
