### ISSUE TITLE
Hope to support the secondary directory domain name

### ISSUE THREAD

**Issue by durongzhang** [zeit/next.js#1699]
Now I want to post to a secondary directory domain name （example： https://www.xxxx.com/xx/xx/ ）
But many addresses can not be changed
```js
router.js
```
![image](https://cloud.githubusercontent.com/assets/15725537/24947149/4a3dcae4-1f98-11e7-9dc5-b9c7d4f4c428.png)
```js
document.js
```
![image](https://cloud.githubusercontent.com/assets/15725537/24947240/98577d7e-1f98-11e7-96fe-3f2992b705a8.png)

**Comment by arunoda** [comment]
I hope you are looking to deploy into a directory under your domain.
We do not support it.
