### ISSUE TITLE
Throws TypeError in dev mode

### ISSUE THREAD

**Issue by octet-stream** [zeit/next.js#1702]
When I'm returning webpack config as an array from next.config.js, app crashes with the following error:

```
(node:3243) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'chunks' of undefined
(node:3243) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This error throws right [here](https://github.com/zeit/next.js/blob/2337827c40d4d0e866fe72067b2c92ff4cbc5870/server/hot-reloader.js#L82), because in this case webpack is invoking this callback with [MultiStats](https://github.com/webpack/webpack/blob/813053ef554a8dffe05e041847d4858f2bc0b743/lib/MultiStats.js#L11).

I can patch this issue, if you don't mind.

System information:
- OS: macOS 10.12.4
- Node: v7.8.0
- Next.js: v2.1.1
- Webpack: v2.3.3

Thanks for your amazing framework!
Regards, Nick K.

**Comment by arunoda** [comment]
I'd like to see a PR with a fix.
But I wonder why I didn't get this error.

**Comment by octet-stream** [comment]
If you want to reproduce this issue, you can create project with webpack@2.3.3, next.js@2.1.1 and next.config.js file with the following content:
```
module.exports = {
  webpack: cfg => [cfg]
}
```

Then run next.js in dev mode.
