### ISSUE TITLE
Updating states (HMR) not working properly

### ISSUE THREAD

**Issue by ghigt** [zeit/next.js#1705]
```js
import { Component } from 'react';

export default class Articles extends Component {
  state = {hello: 'hello'}

  render() {
    return <div>{this.state.hello}</div>;
  }
}
```

Changing the state doesn't update the page view, but reloading the page does.

**Comment by arunoda** [comment]
As I remember class properties might not work with React HMR. Could you initialize state inside the constructor. Then let's see whether it's working or nor.

**Comment by ghigt** [comment]
Not working either with a constructor like:
```js
constructor(...args) {
  super(...args);

  this.state = { hello: 'hello world' }
}
```

**Comment by arunoda** [comment]
Yep. This is an bug. Let's see how to fix this.

**Comment by cia48621793** [comment]
Can confirm:
```
import React from 'react'

export default class extends React.Component {
  constructor(props) {
    super(props)
    this.test = 123
  }

  render() {
    return <div>Hello world {this.test}!</div>
  }
}
```
When I changed the variable `this.test` the state in browser didn't update either. But there were DOM updates, seems strange to me.

**Comment by kengres** [comment]
I'm having the same issue. any update on this!!!

**Comment by jaytrovare** [comment]
having the same issue as well

**Comment by danielmohr** [comment]
Same issue here. Sometimes even reloading the page doesn't do the job.

**Comment by saiqulhaq** [comment]
having same issue, I have to restart server to make any changes
I just installed nextjs btw

**Comment by pixelhijack** [comment]
same here, with latest next 5.1.0, have to stop server and next build on every change, source maps not refreshing, HMR not working

**Comment by pvtri96** [comment]
same with me. I am using material-ui and when I change a JSS style. The page didn't reload properly. I have to reload the page manually to reload the style.

**Comment by timneutkens** [comment]
This should be fixed since Next v6 as we no longer use react-hot-loader.
