### ISSUE TITLE
Route props

### ISSUE THREAD

**Issue by christiannwamba** [zeit/next.js#1708]
React router which I'm used to, passes route information via props to contained components.

I was hoping to access route payload information via props in Next but it turns out props is an empty object by default.

Is there a way to get information about the current page route like location, param, etc?

**Comment by kandros** [comment]
Router is a singleton, so you can import from next/router it and get his properties

https://github.com/zeit/next.js/blob/af1afa472be7e8ab15711c84545a92c2a07d223b/lib/router/index.js#L60

**Comment by christiannwamba** [comment]
Great. Thank you @kandros
