### ISSUE TITLE
importing images

### ISSUE THREAD

**Issue by conor909** [zeit/next.js#171]
One thing I don't understand is how to import images,  what does the src url look like?  Anything I try fails with a `404 (Not Found)`

**Comment by ugiacoman** [comment]
Not tested, but they should be available through `/static/{filename}` from what I've heard.

**Comment by sedubois** [comment]
Yes you can put images in `static/` beside your `pages/` folder and refer to them in CSS with `url(static/myimage.jpg)` or html `<img src="static/blah.png">`. I did the former here: https://github.com/sedubois/realate/blob/master/components/Header.js#L12
