### ISSUE TITLE
Support for module.exports

### ISSUE THREAD

**Issue by cia48621793** [zeit/next.js#1715]
I cannot:
```
module.exports = function() {
    return <div>Hello World!</div>
}
```
Currently I have to:
```
module.exports['default'] = () => (<div>Hello World</div>)
```
As to mimic the ES6 export functionality.

**Comment by dannav** [comment]
FYI, you can also `exports.default ...` which is a bit cleaner.

**Comment by timneutkens** [comment]
I wonder why we would need to support this 🤔. This would only happen on top level pages.
We default to ES2015 module system.
`export default () => <div>Hello World!</div>`

cc @arunoda

**Comment by arunoda** [comment]
@timneutkens That's true.
But we check many places for normal JS exports as well.
It's something nice to have.

**Comment by arunoda** [comment]
I think we are not going to support this. We need to have a default export.
