### ISSUE TITLE
a little bug about  production the app

### ISSUE THREAD

**Issue by Wolke** [zeit/next.js#1716]
If I do not command
node server.js
before the 
NODE_ENV=production node server.js        
it will show
module.js:471
    throw err;
    ^

Error: Cannot find module '.next/build-stats.json'

**Comment by sergiodxa** [comment]
For production usage you must always run `next build` and then `next start` or `NODE_ENV=production node server.js`.

**Comment by arunoda** [comment]
Thanks @sergiodxa for the help.
