### ISSUE TITLE
css is not minified when view page source

### ISSUE THREAD

**Issue by nndung179** [zeit/next.js#1718]
I am using nextjs for my project. And I use css style:

```css
<style dangerouslySetInnerHTML={{ __html: stylesheet }} />
```

As I investigated that when I use "View Page Source" to look at my html source code. This actually is not minified at all. Is there any solution for this case?

**Comment by kandros** [comment]
i find it normal that there's no minification of inline styles, nor vendor prefix injection, try using [styled-jsx](https://github.com/zeit/styled-jsx)? instead

**Comment by timneutkens** [comment]
@kandros is right. We shouldn't handle this case, since our default styling solution (styled-jsx) handles minification / automatic prefixing. However there are some examples that implement external css files with preprocessing / postcss https://github.com/zeit/next.js/tree/master/examples
