### ISSUE TITLE
Debugging node_modules

### ISSUE THREAD

**Issue by khankuan** [zeit/next.js#1721]
Hi, I'm getting an error that is deep inside a node module. I've tried diving into the source in node_modules but it seems like changes made to the files there are not reflected. Are there any hidden caches that are holding the actual files used for compilation?

**Comment by impronunciable** [comment]
@khankuan Can you provide more info? Which module is breaking your app?

**Comment by khankuan** [comment]
I'm using apollo with isomorphic-fetch and graphene. It turns out that the graphql endpoint was returning the graphiql html as the response hence fetch could not parse it from json. The main confusion I had was not being able to debug and get any useful information about the error on the client application, as well as not able to pin point which library is breaking since changes to node_modules does not seem to do anything.

**Comment by khankuan** [comment]
I am now facing another library that does not seem to be working: https://github.com/fridays/next-routes/blob/master/src/index.js

I wanted to dive in to node_modules and debug but next is not recognize the file changes there.

**Comment by timneutkens** [comment]
We don't watch `node_modules` for changes. So if you make changes inside of a module you'll need to restart next. As far as `hidden caches` we use `babel-loader` its output cache. Which is located in `node_modules/.cache`.

**Comment by khankuan** [comment]
Restarting next does not seem to be using the updated file either.

**Comment by Fumler** [comment]
@timneutkens is it possible to override the watch config in next? We have all our components in an NPM package, and we develop locally with `yarn link`. But I can't figure out how to make next watch the changes made in `node_modules/our-components-package`

**Comment by timneutkens** [comment]
@Fumler will be easier when universal webpack lands, https://github.com/zeit/next.js/pull/3578
