### ISSUE TITLE
PSA: PropTypes is depreached in React v15.5.0

### ISSUE THREAD

**Issue by cia48621793** [zeit/next.js#1727]
So I have updated to the latest version of React and found this in my inspection console:
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead
```
Probably because of the pavement for React Fiber, React v15.5.0.
But honestly nothing was broken (yet).
[
Read more about this React update here.](https://facebook.github.io/react/blog/#migrating-from-react.proptypes)

**Comment by queckezz** [comment]
This has already been fixed in 8e6615dcf925a2bfb67e79c0b68e55b86670643d. Just have to wait for a release.
