### ISSUE TITLE
Using node modules

### ISSUE THREAD

**Issue by Dalas** [zeit/next.js#173]
Hello!

I'm trying to use node module in my page.

```js
import fs from 'fs'
import React from 'react'

export default class extends React.Component {
        static async getInitialProps({ req }) {
            const isServer = !!req;
            if (isServer){
                // how!?
            }
            return {
                isServer: isServer
            }
        }

        render() {
            return (
                <div>test</div>
            )
        }
    }
```
But it doesn't work. What I need to do to use node modules in my page?

**Comment by dstreet** [comment]
@Dalas Node modules are not available to your component when rendered client-side.

**Comment by Dalas** [comment]
@dstreet how can I access them on server side?

**Comment by dstreet** [comment]
@Dalas The short answer is you can't. Currently, your best bet would be to find some isomorphic implementation of the module you need. However, I don't know of any for `fs`.

**Comment by Dalas** [comment]
@dstreet thank you.

**Comment by sergiodxa** [comment]
You can in your server make a HTTP request to an API who use the `fs` module and get the content of a file (or do whatever you want to do) and return you the result, then you don't need to use the `fs` module directly.

**Comment by nkzawa** [comment]
```
const isServer = 'undefined' !== typeof window
if (isServer) {
  const fs = require('fs')
  ...
}
```

I wonder if this kind of workarounds doesn't work.

**Comment by dstreet** [comment]
@nkzawa that fails during the bundling. It works perfectly well for modules like '
`path`, but not `fs`, which requires an actual filesystem.

**Comment by cdock1029** [comment]
```javascript
const isServer = typeof window === 'undefined'
if (isServer) {
  const fs = eval('require("fs")')
  ...
}
```

This is probably bad right? Works though..
Need similar workaround for `firebase-admin` on server

**Comment by nkzawa** [comment]
You can exclude modules from bundling by the setting of webpack like the following on v2 (you can try with `next@beta` now).

```js
// next.config.js
module.exports = {
  webpack (config) {
    config.externals = config.externals || {}
    config.externals.foo = 'foo'
    return config
  }
}
```

**Comment by nyura123** [comment]
I was also trying to get firebase-admin working, and ended up needing to use a custom node server: [next-example](https://github.com/nyura123/mobx-firebase-store/tree/master/examples/next-example)
