### ISSUE TITLE
Next.js returned rendered version from another user

### ISSUE THREAD

**Issue by phongmh307** [zeit/next.js#1731]
Hi guys,

We are developing a React application and just added `next.js` for server side render recently. This framework is awesome but we are facing an issue recently.

Our app is serving around 9k-17k requests/sec. Since we deployed server side rendered version using `next.js`, we are receiving 1-5 reports each day complains about (userA) is logged into a random account (userB) on initial load because server returns rendered version from another user. Only until userA presses refresh (F5), the app will return correct render for their account. We switched from koa to express but the issue still happening. We are running dozen servers for server side render (using pm2) and round robin balanced using nginx

Did anyone ran into this issue or any ideas to fix this.
Thank you and best regards!

**Comment by scf4** [comment]
and you're not caching rendered pages?

**Comment by ooade** [comment]
I made that mistake without knowing when creating this [PR](https://github.com/zeit/next.js/pull/1740). Maybe reading through the comments might help. The main point is not to persist server-related things on the client or it will mess up user sessions.

**Comment by jonaswindey** [comment]
What kind of user data is being shared through Next and how do you manage sessions? (db, in-memory, redis)?

Can you reproduce the error by doing API calls directly through the server (without going through next)?

**Comment by phongmh307** [comment]
Our API is working without issue. The error happened when user A takes jwt from cookie to request rendered version from next.js server. At same time, if user B requests to that endpoint, the result from user A and user B will be swapped. This only happen during our peak hours.

Currently, we have to request data from client after initial render. It takes longer time to load but the issue no longer happens

Rendered pages are not cached also

**Comment by jonaswindey** [comment]
Are you sending the JWT token as a cookie or as request auth header?

**Comment by phongmh307** [comment]
We sent JWT token as a cookie

**Comment by scf4** [comment]
> The error happened when **user A takes jwt from cookie to request rendered version** from next.js server.

Can you be more specific about how this happens? And maybe share some of the server code?

**Comment by arunoda** [comment]
I hope this is totally because of caching or something else.
If you still think this is a next.js issue, reopen this with a way to reproduce the error.
