### ISSUE TITLE
Execute random front-end code after page is rendered

### ISSUE THREAD

**Issue by elgubenis** [zeit/next.js#1732]
is there a recommended way of executing client-side js whenever a page got rendered? actually i'd prefer adding it to the pages/_document.js because I want to load some javascript, but its important that in the moment i execute, the `__NEXT_DATA__` already exists and i'd prefer not to use setTimeout to wait for that.

**Comment by elgubenis** [comment]
in the meanwhile this works in the `_document.js`:

```html
<Main />
<NextScript />
<script dangerouslySetInnerHTML={{ __html: 'alert(1);' }}></script>
```

but not sure if thats the best thing to do

**Comment by timneutkens** [comment]
@elgubenis https://github.com/zeit/next.js/tree/master/examples/layout-component might help
