### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by balibou** [zeit/next.js#1739]
I tried the second example of fetching, and I get this error (nextjs version: 2.1.1):

```js
const Page = ({ stars }) => <div>Next stars: {stars}</div>

Page.getInitialProps = async ({ req }) => {
  const res = await fetch('https://api.github.com/repos/zeit/next.js')
  const json = await res.json()
  return { stars: json.stargazers_count }
}

export default Page
```

<img width="1184" alt="screen shot 2017-04-16 at 18 47 56" src="https://cloud.githubusercontent.com/assets/7440159/25073025/4983fc50-22d5-11e7-9f72-600547cc385b.png">

**Comment by arunoda** [comment]
You may need to import a package like this: https://www.npmjs.com/package/isomorphic-unfetch which works both on the server and client.

Follow this tutorial: https://learnnextjs.com/basics/fetching-data-for-pages
