### ISSUE TITLE
 React.createClass is deprecated warnings

### ISSUE THREAD

**Issue by andrewmclagan** [zeit/next.js#1745]
seems related to the react upgrade.

are there internal uses of the ` React.createClass` deprecated api?

https://github.com/zeit/next.js/pull/1675

**Comment by arunoda** [comment]
Hmm. Nope. There's none.

**Comment by arunoda** [comment]
May be check your app code or a NPM module.

**Comment by andrewmclagan** [comment]
apologies was a dependant library
