### ISSUE TITLE
can I write doms outside the _document.js

### ISSUE THREAD

**Issue by Wolke** [zeit/next.js#1746]
for google suggest css link way
[https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery)
```
<html>
....
</html>
<link rel="stylesheet" href="small.css">

```
so how to do it?

**Comment by impronunciable** [comment]
@Wolke where in that document does google suggest to add the css after the `</html>`?

**Comment by sergiodxa** [comment]
@Wolke The google recommendation is to load your main CSS inside an style tag (that's how it works already) and then your not-critical CSS in an link at the end. But Next.js only render the most important CSS when you use styled-jsx and nothing more (styled-components, styletron, and other CSS in JS solutions did the same), if you eventually (client side navigation) need more CSS it's going to be generated at the moment.

If you want to load static CSS files you can put it before `</body>` and it's the same. The idea it's to load that CSS at the end of your document. It's not necessary to place it outside the `<html>` tag.

**Comment by Wolke** [comment]
maybe the suggest content; its only show on the Chinese version?
but thx a lot
=========== 
您即可像下方這樣嵌入重要 CSS 屬性：

<html>
  <head>
    <style>
      .blue{color:blue;}
    </style>
    </head>
  <body>
    <div class="blue">
      Hello, world!
    </div>
  </body>
</html>
<link rel="stylesheet" href="small.css">
系統會在網頁的 onload 事件後載入原始 small.css。應用程式的 CSS 規則順序是由所有透過 JavasScript 插入文件的 <style> 和 <link> 元素所維繫。

不內嵌大型資料 URI

嵌入 CSS 檔案中的資料 URI 時，請務必注意。選擇性使用 CSS 中的小型資料 URI 是比較合理的做法，而嵌入大型資料 URI 可能造成不需捲動位置的 CSS 大小過大，從而增加網頁轉譯的時間。

**Comment by arunoda** [comment]
I think we can close this now.
