### ISSUE TITLE
process.env.NODE_ENV is always 'production'

### ISSUE THREAD

**Issue by vdanchenkov** [zeit/next.js#175]
As defined in server/build/webpack.js
```jsx
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify('production')
}),
```

Is it intentional? Can we redefine it to development when hotReload === true ?

**Comment by nodegin** [comment]
This seems to be a bug with #97

**Comment by ccunniff** [comment]
if you want me to base the boolean logic off `hotReload` instead of passing the `dev` boolean around let me know.
