### ISSUE TITLE
Please add semantic ui example

### ISSUE THREAD

**Issue by nhanco** [zeit/next.js#1752]
Please add semantic ui (http://react.semantic-ui.com/ ) example it's will be good for beginners.

**Comment by sergiodxa** [comment]
🤔 I think you need to install `semantic-ui-react` and load the styles in `pages/_document.js` from the [CDN](http://react.semantic-ui.com/usage#content-delivery-network-cdn) or building your own [themed styles](http://react.semantic-ui.com/usage#semantic-ui-package) and loading it from `/static` directory.

**Comment by impronunciable** [comment]
@nhanco Added PR https://github.com/zeit/next.js/pull/1753
