### ISSUE TITLE
Module is not defined

### ISSUE THREAD

**Issue by jasmineY** [zeit/next.js#1758]
After invoking next build，I add a index.html in .next folder,

 > <script src="./.next/app.js"></script> // index.html

I want to using domain name to access index.html and through the index.html loading app.js

But the index.html console.log an error:> module id not defined

I need your help.
 @arunoda  @kinesivan

**Comment by khrome83** [comment]
@jasmineY why are you doing this. On my project `.next` is considered holy and I don't edit it because it can change with each build... app.js is applied through the default implicit `_document.js` or by using a custom `_document.js`

**Comment by sergiodxa** [comment]
I'm with @khrome83, why are you doing that? Just create an index.js inside pages and put your page code there. You don't need to create an index.html file.
