### ISSUE TITLE
Blame with-redux example

### ISSUE THREAD

**Issue by Rokt33r** [zeit/next.js#1760]
Most of my friend stuck when implementing redux to Next.js. Eventually most of them already gave up to using Next.js.

We need much an elegant example. The current example looks fine itself. It depends on [`next-redux-wrapper`](https://github.com/kirill-konshin/next-redux-wrapper).

Here comes the critical problem. The package is:

1. poorly written (`Cmp.getInitialProps.call(Cmp, ctx)`, Seriously?)
2. poorly maintained (Junk files in installed module, coverage report and config of WebStorm?)
3. tested with snapshots only(It should needs full functional tests and e2e tests to ensure working)

I couldn't understand how this package could be tagged v1.x.

**If Zeit present an official example, it should be a blazing of glory.**

I'm also hacking this problem. The most important issue is how to provide initial state for Redux store from server-side.

With respect.

**Comment by arunoda** [comment]
You've a valid point. Thanks.

But non of those points are critical.
And you can simply send a PR and help the maintainer.
(Edit: I saw your comments on the repo)

Then I suggest to try to work a proper version and send us a PR with that version.
I like to discuss with code rather pure comments.

**Comment by Rokt33r** [comment]
I understood. I'll inform you when my code is ready.

**Comment by Rokt33r** [comment]
![apr-22-2017 17-10-18](https://cloud.githubusercontent.com/assets/5865853/25302691/c827da10-277e-11e7-9ea4-63ec6152d545.gif)

This is my solution. It hydrates the initial redux store state. I actually don't like because it looks quite hacky.

https://github.com/CarbonStack/carbonstack/blob/session-login-demo/lib/redux/lib/withReduxCreator.js

Specs:
- Get both initial store state with session cookie and props for page when first rendering(No client fetch is needed)
- Sign in via Github
- Sign out

It does:
- Use fake store and connect function when SSR. It does calculate state only.
- Pass initial state via <script> tag
- Fetch `getInitialProps` of Page component and fetch method for redux store concurrently

Here comes what I need:
1. Could you tell me **how should I test this**?
2. How can I see **a valid stack trace**?(is it possible to generate sourcemap?)
3. **Replacement for this hacky solution**

**Comment by Rokt33r** [comment]
I've just found I don't have to use <script> tag just like next-redux-wrapper's doing. You could ignore this issue.

**Comment by lulalachen** [comment]
@Rokt33r I'm stuck with SSR redux problem as well....

**Comment by Rokt33r** [comment]
@lulalachen The example for Mobx is way better. You should check it. The implementation of Redux is almost same to it.
