### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by jasmineY** [zeit/next.js#1765]
> 
   ` ` `<a onClick={handler}>ClickBtn</a>` ` `
   const handler = (id) => {
       Router.push({
         pathname: '../../user/circle_user/userInfo',
          query: { id: '123' }
       })
 }

---
The consolse.error in router.js and asyncToGenerator.js
> 
Unexpected token < in JSON at position 0  -- router.js
Uncaught(in promise) Unexpected token < in JSON at position 0 -- asyncToGenerator.js
---

After a monment，the error remind disappear and success to 'http://localhost:3000/user/circle_user/userInfo'

When ` ` ` npm run build, npm run start ` ` `，the page show 'An unexpected error has occurred'

**Comment by drxwskx** [comment]
What's the solution for this?
