### ISSUE TITLE
How do i set default language on /examples/with-react-intl

### ISSUE THREAD

**Issue by nhanco** [zeit/next.js#1768]
Anybody please help me set default language to other language (not en). Thanks for help me.

**Comment by ptomasroos** [comment]
Its reading from the browser. Alternative you can change over there.
https://github.com/zeit/next.js/blob/master/examples/with-react-intl/server.js#L44

But this is no issue, please ask questions on stackoverflow or Slack.

**Comment by nhanco** [comment]
Thanks i was got it. i will carefull at next question.

**Comment by ikhsanalatsary** [comment]
how to change language dynamically by user?
