### ISSUE TITLE
Per page global styles

### ISSUE THREAD

**Issue by nvartolomei** [zeit/next.js#177]
When using gamor's `insertRule` in a page != from index.js for example and opening index the insertRule will do nothing. If you open the page where you have `insertRule` with global styles (ie reset) and then navigate to index you will see `insertRule`s being preserved.

I'm looking for a way to add some global styling to html/body, but only for specific pages.

Also looking for a way to add reset to all pages, without re-importing reset for every page. Looks like #88 would help.

**Comment by dstreet** [comment]
Though not terrible ideal, you can have per-page global styles using `Head`

```javascript
// pages/first.js

import React from 'react'
import Head from 'next/head'

export default (props) => {
    return (
        <Head>
            <style>{globalStyle}</style>
        </Head>
    )
}

const globalStyle = `
body {
    background-color: red;
}
`
```

```javascript
// pages/second.js

import React from 'react'
import Head from 'next/head'

export default (props) => {
    return (
        <Head>
            <style>{globalStyle}</style>
        </Head>
    )
}

const globalStyle = `
body {
    background-color: green;
}
`
```

When navigating to `/first` the background will be red. When navigating to `/second` the background will change to green

**Comment by impronunciable** [comment]
Now we are using `styled-jsx` so you can do

```
<style jsx global>
  This is global :)
</style>
```

The above example will also work :)
