### ISSUE TITLE
Remove `next build`?

### ISSUE THREAD

**Issue by tuckerconnelly** [zeit/next.js#1770]
What if `next start` checked if there were any differences in contents of `./`, and re-built before running only if necessary?

**Comment by timneutkens** [comment]
That way you wouldn't be able to deploy to `now`, since at the server start it won't be able to write files. https://zeit.co/now

**Comment by arunoda** [comment]
@tuckerconnelly that's because it's a two different things.
Usually we build the project once and then run many times for different times with many containers.
