### ISSUE TITLE
with-universal-configuration is not practical

### ISSUE THREAD

**Issue by pencilcheck** [zeit/next.js#1772]
with-universal-configuration example is only applicable if it works on the production. 

Right now this only works in local development because of caching issue as shown in this issue.
https://github.com/zeit/next.js/issues/1666

Let me describe the issue:

Now in order to run in production, next applications have runs two commands - `npm build` and `npm start`. The first command will create the cache and then the second command will error out because the script env-config.js will not be run and thus the ENV is not defined.

If there is a means to make it work after running the command with cache then this would be useful.

**Comment by sunnixx** [comment]
I would agree @pencilcheck. I am currently running a Next.js application on a Azure server, and before uploading in the cloud I have to do `next build` and then upload files to the server.
