### ISSUE TITLE
Is it possible to disable SSR during development?

### ISSUE THREAD

**Issue by thesunny** [zeit/next.js#1773]
In order to keep development very snappy, my hope was to disable SSR during development relying solely on the hot-module-reload to serve the client's React code.

This way the server restarts only have to load the data fetching bits.

I would turn SSR back on during production.

Is there a way to do this in next.js?

**Comment by sergiodxa** [comment]
No, but you can (manually) use `react-no-ssr` to achieve this like in the example https://github.com/zeit/next.js/tree/master/examples/progressive-render

**Comment by thesunny** [comment]
Hi sergiodxa,

Thank you for the (ridiculously) quick reply.

In this scenario, we are still parsing all the React code correct?

I'm looking more for a way to not have the React code loaded on the server at all during development. I would imagine this would dramatically speed up server reloads.

If you or anybody else have any other suggestions, I would be very thankful.

**Comment by HaNdTriX** [comment]
Maybe you can check out Dynamic Imports https://github.com/zeit/next.js/pull/1750

**Comment by sergiodxa** [comment]
@HaNdTriX that would work, but is not yet merged, also is going to create a new chunk file for each module and is not development only.
