### ISSUE TITLE
Does next.js the support code spliting in production mode ?

### ISSUE THREAD

**Issue by akiran** [zeit/next.js#1781]
I was going through next.js code and found this.
https://github.com/zeit/next.js/blob/master/server/document.js#L62-L65

Docs says automatic code splitting is supported but when I tried production build only app.js file is created

**Comment by impronunciable** [comment]
@akiran Per page code splitting should work as expected. What are we doing in production mode is to [combine those 3 js into 1](https://github.com/zeit/next.js/blob/ea77b41570c7ce1755482a7a9e07254d1559fc5b/server/build/webpack.js#L133) but the code splitting feature remains the same
