### ISSUE TITLE
other js file in `.next` folder will be deleted

### ISSUE THREAD

**Issue by loatheb** [zeit/next.js#1782]
I'm using `next.js` with the [Monaco editor](https://github.com/Microsoft/monaco-editor). The editor has bundled by AMD. So that I use the `copy-webpack-plugin` to load the both file into the `dist`.

here is the `next.config.js`

```
module.exports = {
  webpack: config => {
    config.plugins.push(
      new CopyWebpackPlugin([
        {
          from: 'node_modules/monaco-editor/min/vs',
          to: 'show/vs',
        }
      ])
    )
    return config;
  }
}
```

so that, every time I build. a folder in `.next` will copy the files under `/monaco-editor/min/vs` into the `.next`. 

But when I open the `localhost:3000` , all the js file into the `.next/show/vs`(which I build by webpack) will be delete. I don't know what happened. So that I couldn't load something from it.

That's really weird, I don't know why the JS file under `.next/show/vs` will be deleted when I open the site.I tried many times but nothing helpful to me.So I create the issue.Sorry for troubling.

**Comment by impronunciable** [comment]
@loatheb The `.next` folder is intended to be used only by the framework. If you want to use the `webpack-copy-plugin` you can just place the resulting file into the [static folder](https://github.com/zeit/next.js#static-file-serving-eg-images).

Please feel free to reopen if I'm not answering the question you were asking

**Comment by geovanisouza92** [comment]
I'm trying the same, with this `next.config.js`, but it didn't worked:

```
const path = require('path')
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
  webpack: (config) => {
    config.plugins.push(
      new CopyWebpackPlugin([
        { from: 'node_modules/monaco-editor/min/vs', to: path.resolve(__dirname, 'static/vs') }
      ])
    )
    return config
  }
}
```

**Comment by loatheb** [comment]
@geovanisouza92  I think the reason is something error with the webpack plugin. Finally I use it without the next.js, just a simple webpack config.It works well.

**Comment by geovanisouza92** [comment]
@loatheb do you mean the `copy-webpack-plugin`?
