### ISSUE TITLE
Access Router pathname on server

### ISSUE THREAD

**Issue by jonaswindey** [zeit/next.js#1785]
I'm trying to highlight the current item in my menu by checking the Router.pathname but I'm getting the error 

```javascript
No router instance found. You should only use "next/router" inside the client side of your app.
Error: No router instance found.
You should only use "next/router" inside the client side of your app.
```
When I remove the code and add it after my page has loaded the code is working(with HMR). However, when I refresh the page it gives me that error.

To reproduce:

```js
import Router from 'next/router'

export default () => (
  <header>
    {JSON.stringify(Router.pathname)}
  </header>
)
```
Using next `2.1.1`

**Comment by sergiodxa** [comment]
With `getInitialProps` you can access to the pathname server and client side, use that, next/router only works client side because It's used to navigate client side in an imperative way.

**Comment by sedubois** [comment]
This is duplicate of https://github.com/zeit/next.js/issues/141?

**Comment by jonaswindey** [comment]
Correct, the discussion can continue there.
