### ISSUE TITLE
Hot reloader polling?

### ISSUE THREAD

**Issue by supernintendo** [zeit/next.js#1787]
Hello.

Is there a way to override `poll` for webpackDevMiddleware? I'm trying to enable polling for a project I'm migrating to next.js as it needs to run within a Vagrant box (without `poll: true`, next.js does not compile upon file system events in the host OS).

Thank you so much.

**Comment by visualfanatic** [comment]
Without [this PR](https://github.com/zeit/next.js/pull/823) (which was ready in January) there is no other way than fork this repo and enable it by yourself.

**Comment by supernintendo** [comment]
Thanks @visualfanatic. I'll keep an eye on that PR.
