### ISSUE TITLE
Run example/with-firebase serverCredentials

### ISSUE THREAD

**Issue by t42ji2ji** [zeit/next.js#1790]
serverCredentials: {
    // TODO service account json here
}

I dont know what should i fill in this ?
If any body have some sample JSON?

**Comment by micahbrich** [comment]
@t42ji2ji This is actually a non-next.js thing, but if you check out the Firebase docs (https://firebase.google.com/docs/admin/setup), they'll walk you through getting the credentials – it's basically a JSON file you have to download from your own Firebase project's console.
