### ISSUE TITLE
Already read Error

### ISSUE THREAD

**Issue by michaeltomasik** [zeit/next.js#1792]
Hello, i have problem with routing. When i'm redirecting via 

```Router.push({ pathname:`/overview.html`, query: { id } }, `/${id}/overview.html`) ```
(file is named overview.html.js)

I'm getting "Already Read" 
```
  server.get('/:id/*', (req, res) => {
    const path = req.path.replace(`/${req.params.id}`, '')
    app.render(req, res, path, req.params)
  })
```

![image](https://cloud.githubusercontent.com/assets/7786627/25337344/d8657ea4-28fb-11e7-88da-5257cf955f9f.png)
![image](https://cloud.githubusercontent.com/assets/7786627/25337961/f4bdb2ae-28fd-11e7-9e8b-000d522679b7.png)

But when I reload page with given url, it will work

**Comment by Goluis** [comment]
I can confirm that I have the same problem but when I redirect several times very fast with `Router.push()`.
+1

**Comment by AugustinLF** [comment]
It also happens if you click several times on a `<Link/>` while the server is building the corresponding page.

**Comment by arunoda** [comment]
Could you update Next to the latest 2.2.0, we've fixed this issue. (Actually replaced the logic of the source of this issue)?

Let me if it's still the same.

**Comment by supernintendo** [comment]
@arunoda FWIW, upgrading to 2.2.0 fixed this bug for me. It would be nice to maybe add a `console.warn` indicating that the page for a link is still loading upon click; the current implementation is a bit jarring.

**Comment by michaeltomasik** [comment]
@arunoda I upgraded it to 2.2.0 , now "Already read" error is not occuring but 404
```
Uncaught (in promise) Error: Page does not exist: /d5492639-de4a-4311-aac6-241d2e9ed314/overview.html(…)
```
and after it reloads automaticaly and show page correctly
