### ISSUE TITLE
Ordering multiple <style jsx global> components

### ISSUE THREAD

**Issue by KidkArolis** [zeit/next.js#1795]
I'm trying to rely on multiple <style jsx global> to be ordered correctly. E.g.:

```js
<GlobalStyle />
<BlogStyle />
```

Where I'd like BlogStyle to tweak stuff like body background image and text color. But it looks like tags get ordered certain way irrespective of their order in the component (probably based on the hash?).

If "I'm doing it wrong", then how would you adjust body bg image, color, default text and link color for a specific page (e.g. dark zeit home page vs white blog)? Without having to duplicate all of the global styles into 2 js modules.

E.g. I'd be ok with adding a class to <body>, but not sure how to do that from within the `<BlogLayout />` component.

**Comment by jaydenseric** [comment]
Use props to control style variations, rather than global styles. For example, a button might have a `variant='dark'` prop. Top level components can then trickle down style related props.

**Comment by KidkArolis** [comment]
Right, so I get that for nested elements. But what about styles of the body and html elements?

**Comment by jaydenseric** [comment]
What sort styles would you like to set on them?

**Comment by KidkArolis** [comment]
Background Color and text color (just like zeit.co does between Blog and Now pages)

**Comment by jaydenseric** [comment]
You can set both of those as rules for your page component element. Depending on the effect you are after, you might set a `min-height` on it so the `body` background won't appear below a short page on a tall screen. When scroll bouncing the `html` and `body` background can appear, but that is a different kettle of fish.

**Comment by KidkArolis** [comment]
That's the kettle of fish I'm after though ;) I want to control the color of the overscroll area on a Mac. I think that's just the body color. Hmm

**Comment by jaydenseric** [comment]
It's a different kettle of fish because each user agent displays overscroll differently. Some inherit from `html`, others `body`, others have a native style, and others don't bounce at all. I set a neutral background-color on `html`, usually white. Whatever theme that is on the page gets a consistent overscroll look. Most devs don't even know or think about overscroll.

**Comment by KidkArolis** [comment]
I'm closing this issue, since it's not very critical. But would be happy to hear how zeit.co team did it on their own site ;)

Right now, I'm gonna try one of:
1. Toggle body class in componentDidMount.
2. Duplicate all css between <GlobalStyles /> and <BlogStyles />.
