### ISSUE TITLE
Not finding nested modules/all imports failing

### ISSUE THREAD

**Issue by LordBastor** [zeit/next.js#1796]
Greetings everyone!

I apologize if the questions seems a bit too stack-overflowy but I'm having issues with the module imports being resolved.

For some reason nested imports are not being respected at all. I have no trouble running `index.js` and rendering stuff - works awesome!

But when I try to import a custom router which handles what gets shown (just for example) - it doesn't wish to resolve or import the module - 
`import Router from 'components/layout/Router/Router';`

(the components directory is inside pages so it is as follows:

Root
-pages
--index.js
--components
---layout
----Router
-----Router.jsx
)

And it's failing with the following error:

```
These modules were not found:

* components/layout/Router/Router in ./pages?entry
```

Same goes for me trying to include a css file or any other components that are nested. Am I missing something very obvious here?

Sorry if the question/issue seems bafoonish, I've only used webpack before in a client-side type of bundling so I'm pretty new to universal javascript - I just used rules, tests and loaders to make sure the js I need is being included and is "importable" so to speak.

**Comment by tkh44** [comment]
try `./components/layout/Router/Router` notice the `./` at the beginning.

**Comment by LordBastor** [comment]
@tkh44 Hey, thanks for the quick response, but it doesn't seem to be picking it up.

Tried the following:

`import Router from './components/layout/Router/Router';`
`import Router from '/components/layout/Router/Router';`
`import Router from 'components/layout/Router/Router';`
`import Router from '~/components/layout/Router/Router';`

Last one was with module resolver setup.

**Comment by LordBastor** [comment]
Okay guys I was being bad at reading the docs - turns out the `.jsx` imports were failing - as they should be.

`.js` rename worked like a charm!
