### ISSUE TITLE
Regression in client-side handling of error pages since v2.1.1

### ISSUE THREAD

**Issue by gcpantazis** [zeit/next.js#1798]
After upgrading to v2.2, I noticed that, on production builds, Next is rehydrating the routes for pages that errored during SSR. Steps to reproduce:

1. Make a trivial page to trigger an error state:

```
import React from 'react'

export default class NewTest extends React.Component {

    static async getInitialProps({ res }) {
        throw new Error('Test Error');

        return {foo: 123};
    };

    render() {
        return <div>
            This page should always throw an error: {this.props.foo}
        </div>
    }
}
```
2. Navigate to this page via ` Link` on client-side. You should see the error page as anticipated.
3. Refresh the page, allowing SSR to take over.

Observations:
* Error is displayed quickly, then is replaced by the output of `render()` in the view above.
* `this.props.foo` is not filled, leading me to think `Next` is skipping `getInitialProps` for initial rehydration purposes, thus missing the error.
* ...but, I wouldn't expect it to run this view at all if the server wasn't able to render it. I never want users to see a flash of content, and it makes tracking the issue more difficult.
* Backing up to v2.1.1 fixes the issue, but I haven't isolated further than that.

**Comment by gcpantazis** [comment]
@arunoda this appears to have been introduced with #1700

**Comment by arunoda** [comment]
@gcpantazis That was a huge change.
Let me check.

**Comment by arunoda** [comment]
I tested. I couldn't reproduce it with 2.2.0
![pctvesg0zt](https://cloud.githubusercontent.com/assets/50838/25366271/473dc468-298c-11e7-9581-e50616524833.gif)

Would you mind sending me a sample repo?

**Comment by gcpantazis** [comment]
@arunoda that's dev, I think? This is only happening on production, dev looks fine (like your vid)

**Comment by arunoda** [comment]
Let me check.

**Comment by arunoda** [comment]
I can reproduce this.
Thanks.
Let's see what we can do about this.

**Comment by arunoda** [comment]
@gcpantazis we'll have the fix in the next patch release.

**Comment by gcpantazis** [comment]
Thanks @arunoda! `assetPrefix` is a huge help for us, so this is very much appreciated 🙇
