### ISSUE TITLE
Automatically parse string to int for CLI port arg

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#1799]
It would be greate if this could work:

```
"scripts": {
  "dev": "zoo next -p $PORT"
},
```

This approach fails as [zoo](https://github.com/jsonmaur/zoo/issues/2), and most other `.env` file loaders, treat everything as a string. The result is a `Invalid listen argument` error.

Apparently most libraries, Express, Koa, etc. allow setting the port with a string.

**Comment by arunoda** [comment]
I think we already talked about this: https://github.com/zeit/next.js/issues/577

**Comment by jaydenseric** [comment]
That's a different concept, this is issue is not specifically about reading from `process.env.PORT`. It is about setting port via`'3000'` (string) instead of `3000` (int) not working.

**Comment by arunoda** [comment]
Basically, this is not something related to Next.js. I guess it's `zoo` or something.
This is working:

```js
{
  "dev": "next -p $PORT"
}
```

**Comment by jaydenseric** [comment]
So you have tested setting the port via a string and it works.

**Comment by arunoda** [comment]
@jaydenseric Yep. You need to run it like this: `PORT=7842 npm run dev`

**Comment by jaydenseric** [comment]
You just set an int again, not a string. I just again tested both `PORT="3003" npm run dev` zoo next -p '3000'" and both fail.

**Comment by jaydenseric** [comment]
Looks like [here](https://github.com/zeit/next.js/blob/master/server/index.js#L196) should be `this.http.listen(parseInt(port, 10), hostname)`.

**Comment by arunoda** [comment]
We are handling string parsing with https://github.com/substack/minimist.
You should use `PORT=3000`  but not `PORT="3000"`

**Comment by TooTallNate** [comment]
> You should use `PORT=3000` but not `PORT="3000"`

These are identical as far as `process.env.PORT` is concerned. Env variables are _always_ strings:

```
$ PORT=3000 node -p '`${process.env.PORT}, ${typeof process.env.PORT}`'
3000, string
$ PORT="3000" node -p '`${process.env.PORT}, ${typeof process.env.PORT}`'
3000, string
```

**Comment by arunoda** [comment]
Thanks @TooTallNate 
Anyway, @jaydenseric it should fine.
