### ISSUE TITLE
Add example with linting

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#18]
Under `examples`, with `standard` + jsx support

**Comment by sorahn** [comment]
What do you want the example to do?

**Comment by rauchg** [comment]
Basically just the ability to run `npm run lint`. Just in case someone wants a starting point example with linting.

Obviously linting has to work with jsx etc.

**Comment by leo** [comment]
@rauchg XO? We have it on all of your projects atm... 😊

**Comment by rauchg** [comment]
I believe we did this @impronunciable ?
