### ISSUE TITLE
Index page as folder

### ISSUE THREAD

**Issue by pietrasiak** [zeit/next.js#1801]
I'd like to have `index` page defined as `/pages/index/index.js` instead of `/pages/index.js`.

The reason is I'd like to have all index page components, styles, business logic etc files in the same folder as page definition itself. eg

```
pages/index/style.css
pages/index/components/indexWelcome.js
pages/index/index.js

pages/otherPage/style.css
pages/otherPage/components/otherPageSpecificButton.js
pages/otherPage/index.js
```

In the structure like above, I don't want to see anything 'specific' for given page to be visible from 'global' `pages` folder.

It works fine with other pages eg. `/pages/testPage/index.js`

Futher reading: 
https://medium.com/@alexmngn/how-to-better-organize-your-react-applications-2fd3ea1920f1

**Comment by Goluis** [comment]
you can try using an external package for routes like [next-routes](https://github.com/fridays/next-routes). It's very good specially if you need named routes.

**Comment by albinekb** [comment]
I would also love to have my pages as folders, so i can store stuff that's just used on that page in the same folder.

**Comment by arunoda** [comment]
@pietrasiak unfortunately, you must provide a `/pages/index.js`. You can't have `pages/index/index.js`.
It's kind a hard to change with our current setup.
I suggest you to move rename you `index` page as `home` and just import it from `pages/index.js`.

@albinekb We can have pages as folders like `pages/foo/index.js`. But you can't have both `pages/foo.js` and `pages/foo/index.js`.
