### ISSUE TITLE
runtime error (invalid build id)

### ISSUE THREAD

**Issue by durongzhang** [zeit/next.js#1802]
![image](https://cloud.githubusercontent.com/assets/15725537/25380524/19694c18-29e3-11e7-8aeb-d4c00ac89a4a.png)

**Comment by arunoda** [comment]
Have a look at this: https://github.com/zeit/next.js/wiki/Deployment
And this: https://learnnextjs.com/basics/deploying-a-nextjs-app/build-your-app-locally
