### ISSUE TITLE
Custom distDir: Error when loading route: /_error

### ISSUE THREAD

**Issue by ivome** [zeit/next.js#1803]
I cannot get the custom distDir to work. Whenever I add a next.config.js file and set the distDir as described in the documentation

```javascript
module.exports = {
  distDir: 'build'
};
```

the build is created in that directory, but there is always an exception being thrown in the browser when loading the page. 

```
Error when loading route: /_error
Error: Error when loading route: /_error
    at HTMLScriptElement.script.onerror
```

What am I missing? This is reproducible with the simple hello world example.

**Comment by gokaygurcan** [comment]
Same here.

**Comment by briva** [comment]
Same for me :)
