### ISSUE TITLE
Pass state between pages

### ISSUE THREAD

**Issue by mikeriley131** [zeit/next.js#1805]
I'm having trouble determining how I would share state between page components. Since they are top-level components, I don't believe there's a way to do a Flux or Redux style architecture where data comes in through a top-level component and gets passed to children via props. Am I missing something?

For example, I have a Profile "page" component where a user can log-in. I am setting userId state in that component, but I want that state available to other page components. Is this possible?

**Comment by Goluis** [comment]
It's very easy to use Redux or Apollo with Next, here are some examples:

https://github.com/zeit/next.js/tree/master/examples/with-redux
https://github.com/zeit/next.js/tree/master/examples/with-apollo-and-redux

using `getInitialProps` you can create the store in both server and client, but in the client you can do something like:
```js
let reduxStore = null

export const initStore = () => {
  if (process.browser && !reduxStore) {
    reduxStore = createStore()
  }
  return reduxStore
}
```
the example `with-apollo-and-redux` can help you a lot.

**Comment by mikeriley131** [comment]
Thanks for pointing me in the right direction, @Goluis.

**Comment by arunoda** [comment]
Thanks @Goluis.
Closing this since, we've an answer.
