### ISSUE TITLE
How to use loading spinner when page reload ?

### ISSUE THREAD

**Issue by kenshero** [zeit/next.js#1806]
How i can use Loading spinner when click another page  ?

**Comment by Goluis** [comment]
https://github.com/zeit/next.js#router-events

**Comment by vinaypuppal** [comment]
And you can refer this example: https://github.com/zeit/next.js/tree/master/examples/with-loading

**Comment by kenshero** [comment]
i will try. thank you

**Comment by kenshero** [comment]
it work. thank you.

**Comment by arunoda** [comment]
Closing since this is resolved.

**Comment by hugotox** [comment]
Hi all, any ideas how to use the example to render a simple react component like a spinner instead of using nprogress?
