### ISSUE TITLE
Make Server accept config as one of the constructor arguments

### ISSUE THREAD

**Issue by viczam** [zeit/next.js#1809]
Hey guys,

What do you think about giving the possibility to pass the config object as one of the Server's constructor main object keys?

I'm facing a situation where I need more dynamic control over that config object and I can't rely on next.config.js.

I can create a PR for that if you think it's a good idea.

**Comment by arunoda** [comment]
I hope you can make the `next.config.js` dynamic. We like to keep it like this.
But I'm looking for more input and ideas on this area.
Could you provide what exactly in your mind?

**Comment by timneutkens** [comment]
`next.config.js` gets passed `process.env.NODE_ENV` `development` when you  run next in dev mode and `production` when you run `next build`. Any config should be done at compile time. If you can provide us an expanded usecase I can re-open this issue if relevant. Thanks! 👍
