### ISSUE TITLE
Use with Now Secrets

### ISSUE THREAD

**Issue by thisbejim** [zeit/next.js#1815]
I'm trying to deploy a next app to now using [now secrets](https://zeit.co/blog/environment-variables-secrets), however the environment variables are always undefined.

e.g. 
```
now secrets add url "https://www.google.com"
now -e URL=@url
```
Then in-app `process.env.URL` will be undefined. 

Even just `now -e URL="https://www.google.com"` will be undefined.

I am definitely missing something, any ideas? Cheers.

**Comment by sedubois** [comment]
Server environment variables aren't accessible client-side.

See https://github.com/zeit/next.js/tree/master/examples/with-universal-configuration.

**Comment by thisbejim** [comment]
Awesome, thanks! Any idea how to keep those configs secret rather than hard coding them?

**Comment by sedubois** [comment]
Referring to the with-universal-configuration example, I think it works to refer to process.env.MY_VAR from `env-config.js`. So you could define it it in Now secrets, then access it from there.

**Comment by thisbejim** [comment]
Brilliant, that works - thanks again!
