### ISSUE TITLE
How to ignore .spec.js files during build?

### ISSUE THREAD

**Issue by pietrasiak** [zeit/next.js#1820]
I've got tests for each components etc. in the same folder as component itself, but with name like `components/SomeComponent/index.spec.js`, during `next build` I've got error:

```
Failed to build on /var/folders/h7/j60zmc9x2jl8zvdmlw1n53c00000gn/T/1b20864c-5b57-4792-8fd5-a7e8651c64ef
{ Error: ./~/enzyme/build/react-compat.js
Module not found: Error: Can't resolve 'react/addons' in '[PROJECT_DIR]/node_modules/enzyme/build'
```

**Comment by arunoda** [comment]
Can I have sample repo for this?

**Comment by timneutkens** [comment]
Closing this. Please create a new issue when you have a repository we can use to reproduce.
