### ISSUE TITLE
issue with cutom routes in v2.2.0

### ISSUE THREAD

**Issue by MrLoh** [zeit/next.js#1821]
I encountered a very strange issue, that I could pin down to some change that must have happened in `2.2.0`, since it still worked in `2.1.1`. 

I have a setup with custom routes and express, my pages directory looks like this

```
pages
├── blog
│   ├── index.js
│   ├── test.js
├── index.js
```

Unfortunately the route `/blog/` route doesn’t work anymore in a 
```js
<NextLink href="/blog/index/" as="/blog/">
    link
<NextLink/>
```

while the route `blog/test` still works. Any idea, what could be causing this?

**Comment by spencersmb** [comment]
Have you tried just using /blog? I was thinking it may automatically route to index.js?

**Comment by MrLoh** [comment]
Is nested routing a feature that was introduced in 2.2.0?

**Comment by arunoda** [comment]
@MrLoh try using just `/blog` instead of `/blog/`

**Comment by timneutkens** [comment]
Please try
```
<NextLink href="/blog/index" as="/blog">
    link
<NextLink/>
```

If the issue persists we will re-open. I'm pretty sure this is not a bug though.
