### ISSUE TITLE
_document.js do not include bundle file "app.js"

### ISSUE THREAD

**Issue by Wolke** [zeit/next.js#1824]
I just combine the two example "with-amp" , "with-react-md".
so because the project do not know the correct bundle file "app.js" path , so I can not work well for react-md drawer.
[https://github.com/Wolke/with-react-md-amp](https://github.com/Wolke/with-react-md-amp)

**Comment by arunoda** [comment]
Could you give us more info about the issue?

**Comment by Wolke** [comment]
if I use example "with-react-md"
when I run "next build" and "next start"
I can see the "app.js" in the website link
but when I use example _document.js that is "with-amp" way to solve amp problem
and the  _document.js  do not have app.js link
====
so I can not use component like drawer

**Comment by arunoda** [comment]
You could do it like this: https://gist.github.com/arunoda/2fca5797fccfaee7334bbf46a9c48b72
But I don't think it's a good idea to have dynamic content in an AMP app anyway.

May be @impronunciable help you more.

**Comment by impronunciable** [comment]
As @arunoda said, it's not a good idea to use the app.js along with the amp example. AMP allows only a very strict subset of javascript and it's better to generate it in a different way. As I said in another issue you can add a custom script and include it inside `<Head>`

**Comment by arunoda** [comment]
I hope we could close this issue.
