### ISSUE TITLE
use node's path in registerPage/__NEXT_REGISTER_PAGE 

### ISSUE THREAD

**Issue by DavidSvetlik** [zeit/next.js#1828]
Hello,
it seems that nextjs' router has a trouble on Windows filesystem, generating code like this:

`window.__NEXT_REGISTER_PAGE('/page\subpage', function() { ...`

which ultimately leads to syntax error "Invalid Unicode escape sequence"

I am quite new when it comes to node, so I might be wrong, but fix should be in using nodejs "path" utility and its "normalize" or "resolve" functions to generate paths like these. See https://shapeshed.com/writing-cross-platform-node/#use-path-normalize-to-create-reliable-paths

Thank you,
David S.

**Comment by DavidSvetlik** [comment]
Note: I created temporary patch for me, editing /next/dist/server/build/plugins/pages-plugin.js, adding after line 42 this following one: 

`routeName = routeName.replace(/\\/, '/');`

**Comment by arunoda** [comment]
@DavidSvetlik we should fix this.

**Comment by orhanmaden** [comment]
I had the same issue. Applied your fix and it works now. Thanks!

**Comment by kunal-mandalia** [comment]
Can confirm, experiencing same issue with `next@2.3.1` (and `next-redux-wrapper@1.1.2`) on Windows

**Comment by arunoda** [comment]
I think this is a duplicate of #1841 and we are fixing it with #1930 
Anyway, thanks for the detailed report.
