### ISSUE TITLE
_document.js - TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by nndung179** [zeit/next.js#1831]
**nextjs: version 2.2.0**

When I used `_document.js` like document mentioned. I have this issue. Is there any solution for this case?

I tried some examples using `_document.js`. It is still the same

**Comment by arunoda** [comment]
@nndung179 is it possible to have a repo with a way for us to reproduce?

**Comment by nndung179** [comment]
Hi @arunoda 

Here is an example: https://github.com/zeit/next.js/tree/master/examples/with-external-scoped-css

**Comment by aranajhonny** [comment]
@arunoda I try this example using "next": "2.2.0" works fine.

![captura de pantalla 2017-04-30 a las 9 23 44](https://cloud.githubusercontent.com/assets/9091881/25557719/fae7dbe2-2ce4-11e7-8200-8e16ddab4de2.png)

But using "next": "latest", apparently install "2.3.0-alpha1", and tends to fail.

![captura de pantalla 2017-04-30 a las 9 27 59](https://cloud.githubusercontent.com/assets/9091881/25557721/ff02692c-2ce4-11e7-848b-1e232a500bc2.png)

**Comment by aranajhonny** [comment]
Adding this in _document.js works fine. [source](https://github.com/zeit/next.js/blob/2.3.0-alpha1/server/document.js#L10)
```javascript
static getInitialProps ({ renderPage }) {
    const {html, head, chunks} = renderPage()
    return { html, head , chunks}
  }

**Comment by tz5514** [comment]
This problem will occur when nextjs version is 2.3-alpha1,
working goods when 2.2.0.

**Comment by arunoda** [comment]
I assume this is same as this one: https://github.com/zeit/next.js/issues/2435
Always, try to add the correct stuff for getInitialProps of the custom docs. (Always refer to docs)

Or use this:

```
import Document from `next/document`

static getInitialProps (ctx) {
   return Document.getInitialProps(ctx)
}
```

**Comment by lehtu** [comment]
With these fixes in this thread I can get the example running, but it aint doing anything with the sass/scss.
