### ISSUE TITLE
Why is app.js a combination of commons.js, manifest.js and main.js?

### ISSUE THREAD

**Issue by mxs** [zeit/next.js#1836]
I see that for production builds combines the common chunks of commons.js, manifest.js and main.js into a app.js. [Here.](https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L133)

I would have thought that by splitting these up and maybe even going further to have another 'vendors.js' would improve caching. A single change in a common module would require a completely new version of app.js. Since the rate of change between these chunks are would vary greatly, by intuition makes sense to serve them separately.

So it would be really helpful to know what is the rationale behind having app.js with all these chunks combined?

**Comment by arunoda** [comment]
@mxs that's a good point.
But one counter argument is having a single file is better than three.

And we've some more files to be downloaded in the future.
We can have something for this pretty soon. Let's see.

**Comment by mxs** [comment]
Some more food for thought if following [with-global-stylesheet](https://github.com/zeit/next.js/blob/master/examples/with-global-stylesheet/pages/index.js) example.

The component which has `<style dangerouslySetInnerHTML={{ __html: stylesheet }} />` would most likely be a shared `<Page>` component which would be split into the `commons.js` and hence `app.js` bundle. If you using something like semantic-ui or blueprintjs the app.js would be a rather large file on initial load.

Would really appreciate any suggestions other than putting the large third party css on to a CDN. Thank you!

**Comment by nndung179** [comment]
I think it is a good idea. For me, I am developing multiple product and we are using: redux, react for all product. It is nice to have this feature to improve caching and reduce main js file at client to be downloaded.
