### ISSUE TITLE
Redirection with original URL

### ISSUE THREAD

**Issue by Rokt33r** [zeit/next.js#1839]
I made a custom handler for handling http error when `getInitialProps` executing. 
If a user get 401 error when fetching data, error handler should redirect to Login page with the original URL.

1. pushed to `/nouveau` by a guest
2. 401 error received from server
3. redirect to `/login?redirectTo=/nouveau`

You could see my approach from the below link. It should be wrong way because I redirect when rendering.
https://github.com/CarbonStack/carbonstack/blob/master/lib/hocs/withHttpErrorHandler.js

So, I've tried to mimic the way in the test of Next.js.
https://github.com/zeit/next.js/blob/master/test/integration/basic/pages/nav/redirect.js

When server-side rendering, there was no problem. However, when client-side rendering, I should resolve the original URL by `context.pathname` and `context.query`. This means, if I do parameterized routing, I couldn't resolve the original url because parameters are passed as a query.

How should I tackle this? IMO, setting `url` to context should be one of easy solutions. (Although It looks a little dumb.)

**Comment by arunoda** [comment]
@Rokt33r you have a valid point.
Closing this with this new issue: https://github.com/zeit/next.js/issues/1843
