### ISSUE TITLE
navigating to "sub pages" in 2.2.0+ on windows

### ISSUE THREAD

**Issue by aktxyz** [zeit/next.js#1841]
from slack channel

> aktxyz [12:36 PM] 
> I just updated my nextjs to the latest 2.3.0-alpha1 ... and my <Link> navigation tags stopped working, I tried older versions one by one, and the <Link> nav components stopped working on the jump from 2.1.1 to 2.2.0
> before digging around ... any thoughts on what may be causing this?
> aktxyz [12:43 PM] 
> the routeChangeStart event fires, but the routeChangeComplete never fires
> aktxyz [1:25 PM] 
> it looks like the <Link> issue I am seeing is limited to subdirectories under pages ...
> this works <Link href="/about"><a>About</a></Link>
> this fails <Link href="/App/about"><a>About</a></Link>
> [1:25] 
> where pages/about.js AND pages/App/about.js both exist

This ended up being related to back slashes, I solved by changing this line 

https://github.com/zeit/next.js/blob/master/server/build/plugins/pages-plugin.js#L15

from 

`const routeName = `/${pageName.replace(/[/\\]?index$/, '')}``

to 

`const routeName = `/${pageName.replace(/[/\\]?index$/, '')}`.replace(/\\/g, '/')`

There is probably a more elegant way or place to do this, can someone chime in on thoughts for this?

**Comment by aktxyz** [comment]
just noticed the html Link example I pasted in earlier got munged... here it is again

```
aktxyz [1:25 PM] 
it looks like the <Link> issue I am seeing is limited to subdirectories under pages ...
this works <Link href="/about"><a>About</a></Link>
this fails <Link href="/App/about"><a>About</a></Link>
```

**Comment by arunoda** [comment]
Yep. We need to work on this a bit.
Is it possible for you to send me a example app in a repo?
So, I can fix this quickly.

**Comment by orhanmaden** [comment]
@aktxyz, @arunoda  Is this the same issue as https://github.com/zeit/next.js/issues/1828

**Comment by arunoda** [comment]
I guess it is. Need to verify anyway.

**Comment by arunoda** [comment]
@aktxyz Thanks for the report and for the fix.
I sent a PR #1930 and going to take it soon.
