### ISSUE TITLE
[Question]: Is it possible to configure a `sourceDir`?

### ISSUE THREAD

**Issue by Industrial** [zeit/next.js#1842]
Hi!

In my projects I like to put all source files in `src/` and compile it all to `build/` with gulp with babel, sass, copy (static files), etc and when that is done, run Browserify or Webpack on `build/client/index.js` to `build/client/bundle.js` and then run the server from `build/server/index.js`.

I have several questions:
1) Is it possible to have your server code written such that it uses the .babelrc config?
2) Can I split directories into `src` and `build`?
3) Can I split my source directories into `client`, `common` and `server`?

This would be awesome to be able to override in the `next.config.js`.

**Comment by arunoda** [comment]
1) Currently, that's kind a hard to do. What you could do is, use some environment variables to use different babelrc config for nextjs build time, server code and etc.
2, 3) Basically we only need  a `pages` directory. Other than than you could places code anywhere you want.

**Comment by arunoda** [comment]
You
