### ISSUE TITLE
Uncaught TypeError: Cannot read property ‘call’ of undefined in Chrome

### ISSUE THREAD

**Issue by perjg** [zeit/next.js#1847]
I get this issue on page load (next compiled in dev mode only, only in Chrome. Using next.js 2.2.0)

Uncaught TypeError: Cannot read property ‘call’ of undefined
   at __webpack_require__ (bootstrap a817da8…?f27e374:693)
   at fn (bootstrap a817da8…?f27e374:114)
   at Object.556 (main.js:7)
   at __webpack_require__ (bootstrap a817da8…?f27e374:693)
   at webpackJsonpCallback (bootstrap a817da8…?f27e374:25)
   at main.js:2

When I run in production mode, the app works fine. It also works fine in Safari in dev mode.

**Comment by arunoda** [comment]
May be it's related to a package you are using.
Anyway, I'd like to have a sample repo to check it out locally.

Reopen when you have it.

**Comment by erikras** [comment]
I'm getting this, too. For me it happens when I switch to a new page that includes modules that the first page did not.

**Comment by markthethomas** [comment]
Getting this same thing still w/ 2.4.1, node 8, and Chrome (also latest)

**Comment by brianyan** [comment]
Hm, I am getting the same thing. I temporarily fixed it when I don't import the component that is causing the issue. In my case, it is likely due to the props not matching up.

**Comment by jwaala** [comment]
any thoughts on how to isolate what is causing this (ie is it a rogue component)?

**Comment by hyperparsa** [comment]
Yeah I'm getting this too

**Comment by brenohq** [comment]
same error here

**Comment by mariannafld** [comment]
Hello, 
There is a long thread here with this problem:
Bug: Runtime TypeError ("Cannot read property 'call' of undefined") #6196.
Maybe salvation will come from your thread?

Thank you in advance
