### ISSUE TITLE
Cannot install via npm

### ISSUE THREAD

**Issue by Stas-Buzunko** [zeit/next.js#185]
Is this because of node v7.0.0?
![image](https://cloud.githubusercontent.com/assets/12331100/19950853/4f182f60-a16b-11e6-9978-e2835f6f4359.png)

**Comment by sedubois** [comment]
Very naive question but has this got anything to do with the fact that your directory/project itself might be called `next` too?

**Comment by Stas-Buzunko** [comment]
It's just a folder I created to try Next.js. I doubt it.

**Comment by nkzawa** [comment]
@Stas-Buzunko I guess it occurred because the name field of the package.json is `next`.

**Comment by sgnl** [comment]
Yeah it's the folder name:

🐛 reproduce error:
```
mkdir next && cd $_ && npm init --yes && npm install next
```

🌈 happy path
```
mkdir next_demo && cd $_ && npm init --yes && npm install next
```
