### ISSUE TITLE
page can't loading...i-e Disposing inactive page(s)

### ISSUE THREAD

**Issue by Maklik123** [zeit/next.js#1859]
I am facing a problem that after running the server it shows this message. Disposing  inactive page(s)

npm run dev

> testing@1.0.0 dev C:\Users\Umair\Desktop\testing
> node server.js

 DONE  Compiled successfully in 4408ms2:21:12 PM

> Ready on http://localhost:3000
> Building page: /
 DONE  Compiled successfully in 1231ms2:21:17 PM

 WAIT  Compiling...2:21:18 PM

 DONE  Compiled successfully in 128ms2:21:19 PM

> Disposing inactive page(s): /
 DONE  Compiled successfully in 107ms2:21:47 PM

> Building page: /
 DONE  Compiled successfully in 285ms2:22:26 PM

> Disposing inactive page(s): /
 DONE  Compiled successfully in 211ms2:22:53 PM

> Building page: /
 DONE  Compiled successfully in 121ms2:23:45 PM

> Disposing inactive page(s): /
 DONE  Compiled successfully in 222ms2:24:13 PM

**Comment by arunoda** [comment]
Can we have a sample repo of your app?

**Comment by timneutkens** [comment]
Please open a new Issue with an example repository, thanks! 👍
