### ISSUE TITLE
Error PropTypes update React v15.5.4

### ISSUE THREAD

**Issue by miguelcast** [zeit/next.js#1861]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

In this version of React PropTypes is Deprecated, see: [https://github.com/facebook/react/releases/tag/v15.5.4](url)

**Comment by sedubois** [comment]
This has been fixed already: https://github.com/zeit/next.js/pull/1684

If you still have issues, make sure to upgrade your other dependencies. (In my case I got it fixed by re-generating `yarn.lock`.)

**Comment by miguelcast** [comment]
Thanks!
