### ISSUE TITLE
Downloaded MP4 over and over from zeit.com/blog/next

### ISSUE THREAD

**Issue by KyleAMathews** [zeit/next.js#187]
Perhaps cause I had disable cache enabled in my devtools?

<img width="914" alt="looping" src="https://cloud.githubusercontent.com/assets/71047/19951111/17416310-a119-11e6-9800-ea493fedfb0f.png">

**Comment by nkzawa** [comment]
It looks that's how chrome and video tag works.

http://stackoverflow.com/questions/13883569/chrome-re-downloads-video-every-loop
