### ISSUE TITLE
rerender page when disposing the previews page

### ISSUE THREAD

**Issue by FilipMessa** [zeit/next.js#1870]
When I going from the Page1 to the Page2 in dev mode,  and i do nothing this Page2 will rerender after while, i terminal i can see `Disposing inactive page(s): /Page1` Why this happens?

**Comment by FilipMessa** [comment]
This issue has been compromised by third-party components

**Comment by Coobers** [comment]
Do you know which ones?

**Comment by FilipMessa** [comment]
it was react-click-outside, this problem only occurred in dev mode, in production it is working ok.

**Comment by theednaffattack** [comment]
@FilipMessa Are there any hidden side-effects from this? I'm getting the same thing and I think it's caused by my use of the Ant Design package. If I can't use it, it'd be a major setback.

Just wondering if, after a month you've come across any other gremlins.

**Comment by FilipMessa** [comment]
Hi @theednaffattack,  I ended  on this project so I do not know nothing new.
