### ISSUE TITLE
"<Link>" in _document.js doesn't do client-side transitions

### ISSUE THREAD

**Issue by Reggino** [zeit/next.js#1874]
First: thanks for this guys, this is awesome.

Second: It seems any React onClick-event handlers aren't installed client-side when given via the `_document.js`-file. This way, for example [`Link.onClick`](https://github.com/zeit/next.js/blob/master/lib/link.js#L117) isn't fired for elements in the `_document.js`. Or in nested elements, e.g. in a menu on all pages...

This may be expected behaviour, but it took me a while to figure out why all `<Link>`'s would initiate a server-side transition.

**Comment by sedubois** [comment]
The custom document is not meant to contain `<Link>`s, but e.g to customize the <html> and <body>.

**Comment by Reggino** [comment]
But i think its tempting to add something like a menu if that should be on all pages...

Maybe add a warning to the documentation?

**Comment by sedubois** [comment]
Yes, I think a pull request to clarify that could be helpful. `_document.js` isn't meant to serve as a shared app layout. You can get that behaviour by wrapping each page in a HOC e.g like https://github.com/relatenow/relate/blob/master/hocs/page.js.

**Comment by arunoda** [comment]
Thanks @sedubois for helping out.
Yeah! Having something in the docs would be nice.
It'd be great, if you can send us a PR.
