### ISSUE TITLE
Pages name index.js causing error after render

### ISSUE THREAD

**Issue by fat** [zeit/next.js#1878]
If you have a page named `index.js`… and render it from server like this:

<img width="538" alt="screen shot 2017-05-04 at 10 08 19 am" src="https://cloud.githubusercontent.com/assets/169705/25716317/8192b1d6-30b3-11e7-9867-2768c9a519b8.png">

I get the following error once the page renders…

`Route name should start with a "/"`
The page does successfully render from server, but then once client loads, i get the error…

I did some debugging and saw: `route.replace(/index$/, '').replace(/\/$/, '');` that code to be stripping it out…`Route name should start with a "/"`

**Comment by arunoda** [comment]
Thanks. 
I think I know how to fix this.
Will do it soon.

**Comment by arunoda** [comment]
Now we've a fix for this with `2.3.1`.
Thanks for the bug report!
