### ISSUE TITLE
Route introspection API? (e.g. for a directory index)

### ISSUE THREAD

**Issue by elliottsj** [zeit/next.js#1880]
I want to implement a sort of "directory index" page which automatically generates a list of links to other pages on the site, for example an index page for a blog site which links to all of the blog posts.

In a static site generator like Jekyll, we can [do this](https://jekyllrb.com/docs/posts/#displaying-an-index-of-posts):
```erb
<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
```

Is something like this possible in Next.js? I couldn't find anything similar in the examples or other GitHub issues.

**Comment by arunoda** [comment]
Nope currently it's not possible. You may need to generate a your own `.json` file all these routes and then import in your page and do something ^^^

**Comment by danielbayerlein** [comment]
Has anyone found a solution?

**Comment by timneutkens** [comment]
@danielbayerlein this can be achieved using something like https://github.com/zeit/next.js/blob/96182bc18054af5099c613ebd5b7b37de782c3cc/examples/with-babel-macros/pages/index.js
