### ISSUE TITLE
How to render data received from a REST service in Next.js?

### ISSUE THREAD

**Issue by valnub** [zeit/next.js#1885]
I want to receive data via a REST service call in my Next.js-based app using fetch() and then render the result server-side into JSX like this:

```jsx
class VideoPage extends Component {
  componentWillMount() {
    console.log('componentWillMount');

    fetch(path, {
      method: 'get',
    })
      .then(response =>
        response.json().then(data => {
          this.setState({
            video: data,
          });
          console.log('received');
        })
      );
  }

  render() {
    console.log('render');
    console.log(this.state);
    if (this.state && this.state.video) {
      return (
        <div>
          {this.state.video.title}
        </div>
      );
    }
  }
}

export default VideoPage;
```

Unfortunately, the output is this:

```
componentWillMount
render
null
received
```

Which does make sense because the call to fetch is asynchronously and `render()` finishes before the call to the REST service has finished.

In a client-side app this would be no problem because a change of state would call `render()` which then updates the view, but in a universal app, especially with JavaScript turned off on the client, this is not possible.

How can I solve this?

Is there a way to call the server synchronously or delay `render()`?

**Comment by mikenikles** [comment]
It is recommended to use `getInitialProps()` to fetch data. You can read more about that at https://github.com/zeit/next.js#fetching-data-and-component-lifecycle.

**Comment by arunoda** [comment]
Thanks @mikenikles .
@valnub you can follow this guide too: https://learnnextjs.com/basics/fetching-data-for-pages

**Comment by valnub** [comment]
Thanks a lot guys!
