### ISSUE TITLE
Unlink on non-empty directory

### ISSUE THREAD

**Issue by tomasz89nowak** [zeit/next.js#1886]
When I'm trying to build application on my server (hosting: mydevil.net) I'm getting this error:

> > { [Error: EPERM: operation not permitted, unlink '/usr/home/my_login/domains/my_domain/public_nodejs/.next']
  errno: -1,
  code: 'EPERM',
  syscall: 'unlink',
  path: '/usr/home/my_login/domains/my_domain/public_nodejs/.next' }
npm ERR! FreeBSD 10.3-STABLE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.7.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! react-next-site@1.0.0 build: `next build`
npm ERR! Exit status 1

The provider support suggests that this is a framework build system fault because it is trying to make unlink on non-empty directory, which is unauthorized operation no matter what permissions.

Additional info:
-application works well on heroku.
-.next directory is not empty, it contains /dist, main.js etc.
edit:
-building https://github.com/zeit/nextgram throws the same error

**Comment by arunoda** [comment]
How it'll be non-empty directory? 
EPERM is all about permission.

I think that has to deal with there permissions in your service provider.
Not a direct problem with Next.js

**Comment by timneutkens** [comment]
We've seen this before when the user executing the build doesn't have read rights on the full path. This maybe be the issue in your case.

**Comment by tomasz89nowak** [comment]
Thanks. It seems that the only way to solve the problem is to change the service provider...

**Comment by timneutkens** [comment]
Be sure to check out https://zeit.co/now 😉

**Comment by tomasz89nowak** [comment]
I tried :D

>now
>Enter your email: tomasz89nowak@gmail.com
> Error! Authentication error – Verification error: 500 – {"err":{"code":"internal_server_error","url":"https://zeit.co/errors/internal_server_error","message":"An unexpected error occurred"}}
