### ISSUE TITLE
How to disable auto-refreshing when on error page?

### ISSUE THREAD

**Issue by pietrasiak** [zeit/next.js#1888]
When there is 404/500 page rendered, the browser is auto-refreshing. It's very annoying, especially during the development of error page with dev tools and inspector.

**Comment by arunoda** [comment]
This is a good point. I want to fix this.

**Comment by arunoda** [comment]
This should fix this issue: https://github.com/zeit/next.js/pull/2437

**Comment by pietrasiak** [comment]
@arunoda great! I think this issue can be closed now.
