### ISSUE TITLE
The next/babel preset should enable 'import/export' syntax transpilation for testing

### ISSUE THREAD

**Issue by jcheroske** [zeit/next.js#1890]
Currently, the `next/babel` preset turns off ES6 module syntax transpilation in all cases:
```
  presets: [
    [require.resolve('babel-preset-env'), {
      modules: false
    }],
    require.resolve('babel-preset-react')
  ],
```
This does not play nice with AVA. If the preset module looked at BABEL_ENV, like:
```
  presets: [
    [require.resolve('babel-preset-env'), {
      modules: process.env.BABEL_ENV === 'test'
    }],
    require.resolve('babel-preset-react')
  ],
```
or something like that, then you could just use `"babel": "inherit"` in your AVA config, and launch AVA with `BABEL_ENV=test ava`.

**Comment by sergiodxa** [comment]
Check the Jest example, you should add the plugin for imports if the environment is `test`.
https://github.com/zeit/next.js/blob/master/examples/with-jest/.babelrc#L9-L13

**Comment by jcheroske** [comment]
I came up with something similar and think it's the right way to go. I'll close this.

**Comment by dogada** [comment]
I tried to use following config to enable transpilation of `node_modules/shared` and `node_module/lodash-es`:

```
{
  "presets": [
    ["env", { "modules": "commonjs" }],
    "next/babel"
  ],
  "only": [
    ".next/*",
    "node_modules/shared/*",
    "node_modules/lodash-es/*",
    "pages/*"
  ]
}
```
But it still fails with `SyntaxError: Unexpected token export`. Does Next.js allow to transpile code from node_modules?

**Comment by lucianlature** [comment]
@dogada Not yet. See https://github.com/zeit/next.js/issues/706
