### ISSUE TITLE
 next/babel preset has no way to toggle the "modules" option on babel-env

### ISSUE THREAD

**Issue by jcheroske** [zeit/next.js#1891]
Currently, the `next/babel` preset turns off ES6 module syntax transpilation in all cases:
```
  presets: [
    [require.resolve('babel-preset-env'), {
      modules: false
    }],
    require.resolve('babel-preset-react')
  ],
```
This does not play nice with AVA. If the preset module looked at BABEL_ENV, like:
```
  presets: [
    [require.resolve('babel-preset-env'), {
      modules: process.env.BABEL_ENV === 'test'
    }],
    require.resolve('babel-preset-react')
  ],
```
or something like that, then you could just use `"babel": "inherit"` in your AVA config, and launch AVA with `BABEL_ENV=test ava`.

**Comment by sergiodxa** [comment]
Duplicated #1890
