### ISSUE TITLE
Flying blind in React Developer Tools

### ISSUE THREAD

**Issue by babenzele** [zeit/next.js#1892]
When rendering my next.js app in the browser, I look in the [react devtools extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) and don't see much in the way of help since I'm using pure functional components. If I right-click a node and click show source, I get dumped somewhere minified. I'd at least like to know what file the react component lives in so I can find it. 

How do you debug your code in the browser if you're flying blind in react devtools?

**Comment by arunoda** [comment]
This [PR](https://github.com/zeit/next.js/pull/1895) might be the reason for that.
We will fix this and will do a release around Monday.

**Comment by babenzele** [comment]
Sorry, I saw minified source when testing with the [rauchg.com](https://rauchg.com/essays) blog, which would be in production. 

In my local app, when I go to source I am taken to this function in `patch-react.js` (line 150): 

```javascript
var _fn = function _fn() {
  for (var _len6 = arguments.length, args = Array(_len6), _key6 = 0; _key6 < _len6; _key6++) {
    args[_key6] = arguments[_key6];
  }
  return around.call.apply(around, [this, fn].concat(args));
};
```

**Comment by arunoda** [comment]
@babenzele May be you are using older version of Next.js.
We don't use `patch-react` anymore.

**Comment by babenzele** [comment]
I was on `next@beta`. I upgraded and things do look better now. I'll familiarize myself with this.

Thanks for the help!
