### ISSUE TITLE
Request: explain in docs which pieces of react lifecycle are called on server or client

### ISSUE THREAD

**Issue by Kielan** [zeit/next.js#1896]
The biggest change next.js implements on anyone migrating an app is the Router. Qanting to implement Router listeners there is no documentation explaining where is valid to place these listeners inside of your components or accessible so that it is only processed on the client and not the server

**Comment by Goluis** [comment]
Mmm, I haven't had any problems by using `process.browser` and `componentDidMount`

**Comment by arunoda** [comment]
@Kielan basically that some React stuff and Next.js have to do nothing about that.
Basically only the constructor and the [componentWillMount ](https://facebook.github.io/react/docs/react-component.html#componentwillmount)only runs in the server.

You can refer https://facebook.github.io/react/docs/react-component.html for more info.
