### ISSUE TITLE
How to enable polling inside webpack watch?

### ISSUE THREAD

**Issue by dillonraphael** [zeit/next.js#1899]
I'm running a VM inside Vagrant and everything works as expected, EXCEPT the hot reload. 

I've come across this issue with other webpack projects and the fix was simply turning on polling.

http://andrewhfarmer.com/webpack-watch-in-vagrant-docker/

How can I enable this in my next.config.js 

``` module.exports = {
	webpack: function (config, {dev}) {

		if (dev) {
			watchOptions: {
				poll: true
			}
			return config
		}

		return config
	}
}

**Comment by aranajhonny** [comment]
polling is already on. https://github.com/zeit/next.js/blob/master/server/hot-reloader.js#L137

**Comment by dillonraphael** [comment]
Oh interesting. So this is an actual issue then because my hot reload isn't working inside of vagrant. My host machine is windows

**Comment by dillonraphael** [comment]
#823
