### ISSUE TITLE
Apollo query batching and Next.js SSR

### ISSUE THREAD

**Issue by Zn4rK** [zeit/next.js#1900]
Hi!

I noticed that my initial render was taking a long time and narrowed it down to the network layer. I thought that Apollo's query batching network layer would work with Next.js and the example `with-apollo` straight out of the box, but I cannot get it to work.

I've set up a [crude reproduction of the problem here](https://github.com/Zn4rK/next.js-with-apollo-batching). On refresh one can see that two sequential requests are made instead of one. 
Adding a comment on [this line](https://github.com/Zn4rK/next.js-with-apollo-batching/blob/master/lib/withData.js#L24) disables the data fetching server side, and it only does one request with two queries client side.

I'm pretty sure it has something to do with Next (and the current implementation of the Apollo example) and not Apollo itself. I tried the same thing with their example app [GitHunt](https://github.com/apollographql/GitHunt-React), and that only makes one request.

I've been trying to figure out what's happening but I can't seem to narrow it down more... Does anyone know why this is happening?

**Comment by timneutkens** [comment]
@ads1018 could you have a look

**Comment by Rowno** [comment]
You probably just need to switch from `createNetworkInterface` to `createBatchingNetworkInterface`. Here's the documentation: http://dev.apollodata.com/core/network.html#query-batching

**Comment by Zn4rK** [comment]
No, the batching network interface [is in use](https://github.com/Zn4rK/next.js-with-apollo-batching/blob/master/lib/initClient.js#L14).

**Comment by hiei189** [comment]
this works fine

```
import { ApolloClient, createBatchingNetworkInterface } from 'react-apollo'

function _initClient (headers, initialState) {
  return new ApolloClient({
    initialState,
    ssrMode: !process.browser,
    networkInterface: createBatchingNetworkInterface({
        uri: env.GRAPHQL_ENDPOINT,
        batchInterval: 10,
    })
  })
}
```

**Comment by Zn4rK** [comment]
It is starting to look like an Apollo bug after all. It might be intended behaviour, but it feels like a bug.

**Comment by ads1018** [comment]
@Zn4rK I'm not sure. Someone in the apollo slack channel might know what's going on.

**Comment by ooade** [comment]
@Zn4rK Works only on [supported servers](http://dev.apollodata.com/core/network.html#query-batching) like [graphql-server](https://github.com/apollostack/graphql-server). Tried it out on my [Playground](https://github.com/ooade/GraphQLPlayground), and it worked out fine.

**Comment by langpavel** [comment]
I'm just ensuring myself.. is Apollo state serialized and transferred with initial http request?

**Comment by Zn4rK** [comment]
@ooade, That's because the queries live together. If you have a query in an HOC, it would wait for that query to finish before running the wrapped query. Dunno if that's intended behaviour just yet, kinda trying to figure that out with https://github.com/apollographql/react-apollo/issues/698.

**Comment by ooade** [comment]
@Zn4rK Okay, It's cool you've taken it to react-apollo :+1:
