### ISSUE TITLE
Styled Components Example renders multiple style tags

### ISSUE THREAD

**Issue by spencersmb** [zeit/next.js#1904]
Similar issue to Aphrodite and CXS examples where two style tags were getting rendered where only one should be getting rendered.

This is what currently gets rendered in the head tag:

```
<style>.LHBhC { 
  color: red;
  font-size: 50px;
 }
</style>
<style type="text/css">.LHBhC { 
  color: red;
  font-size: 50px;
 }</style>
```

**Comment by aranajhonny** [comment]
@spencersmb This was corrected. Please update your local repo.
