### ISSUE TITLE
nextjs + redux container not update.

### ISSUE THREAD

**Issue by kenshero** [zeit/next.js#1911]
I have Navbar component for every pages. 
this code
 ```
 <Link as="/product/fashion" href="/product?category=fashion" >
      <a className="nav-item">
           fashion
       </a>
 </Link>
<Link as="/product/gadget" href="/product?category=gadget" >
     <a className="nav-item">
          gadget
     </a>
 </Link>
```

when i change page.Redux Connect not update so display product not correctly.
I think because constructor function not process.
 but my store updated correctly after change page but page display data not change. 

sorry for weak english. Can you help me ?

**Comment by arunoda** [comment]
Checkout our example apps: https://github.com/zeit/next.js/tree/master/examples
