### ISSUE TITLE
Can't redirect on windows but works on Fedora

### ISSUE THREAD

**Issue by HadiAkmal** [zeit/next.js#1917]
Hi,

I 'am using Next Link and Next Router. My problem is link and router will not redirect me to other page when I click it. However I can open the page if I type the page URL in URL bar directly such as this. hello.com/about or run the server on linux (fedora)

It used to work on windows but not anymore. The page does redirect on linux though.

Example code:
```
          <ul>
            <li><Link prefetch href='/about'><a>About Page</a></Link></li>
          </ul>
```

```
  assetInfo() {
    Router.push('/login');
  }
```

I'm using Next ^2.3.1

Where should I start to fix this problem? Thanks in advance.

**Comment by arunoda** [comment]
It's hard to say like this. We test these on linux and it works well generally.
If you can work on a minimal repo, I can help on this.

**Comment by arunoda** [comment]
Feel free to re-open when you have it.
