### ISSUE TITLE
Possibility to disable code splitting

### ISSUE THREAD

**Issue by jgautheron** [zeit/next.js#1920]
It's not always useful, ex. for projects with only 2-3 pages on mobile.

**Comment by timneutkens** [comment]
I'm not sure why it's not useful. The code itself is prefetched when you use `<Link prefetch href="">`.

**Comment by jgautheron** [comment]
Once the bundle is loaded, pages would be immediately accessible.
Prefetching a page does not necessarily finish before going to the next page.

**Comment by arunoda** [comment]
If you've only have 2,3 pages there's no much effect on code splitting.
A module will be marked as a common module, if it's used on at-least 1/2 of the modules in your app.

So, most of the time all of your modules will be marked as common modules.
Anyway, we don't have any plans to turn this feature off.
But you can always try our custom webpack configuration to tinker our default webpack config.

**Comment by Yugloocamai** [comment]
Code splitting is not useful when you need to associate each chunk with a particular module.  This might be useful for security purposes, allowing or disallowing particular files to be loading depending on the client's authority.
