### ISSUE TITLE
Load module nextjs

### ISSUE THREAD

**Issue by vmdao** [zeit/next.js#1923]
Hi Pro,
I use next with antd(ant.design). when import antd, size common.js is too big( from 4mb to 14mb).
I don't know this problem of next or antd or feature.
Thankyou!

Code here:
```import React from 'react';
import Head from 'next/head';
import { Icon } from 'antd';
export default () => (
  <div>
    <Head>
      <title>2 My page title</title>
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <link href="https://cdnjs.cloudflare.com/ajax/libs/antd/2.10.0/antd.css" rel="stylesheet" type="text/css" />

    </Head>
  </div>
) 
```

<img width="1440" alt="screen shot 2017-05-09 at 10 50 41 am" src="https://cloud.githubusercontent.com/assets/15071651/25834983/9e3b9fb4-34a5-11e7-999b-d27a15b4805e.png">

**Comment by Ehesp** [comment]
Hey check out https://github.com/zeit/next.js/pull/1817

**Comment by vmdao** [comment]
Thank Ehesp 👍
