### ISSUE TITLE
Change /_next/webpack url of webpack 'file-loader'

### ISSUE THREAD

**Issue by pietrasiak** [zeit/next.js#1926]
I'm using file loader like:

```
    // handle images
    config.module.rules.push({
      test: /\.(ico|gif|png|jpg|jpeg|svg|webp)$/,
      use: [
        {
          loader: 'emit-file-loader',
          options: {
            name: 'dist/[path][name].[ext]',
          },
        },
        {
          loader: 'file-loader',
          options: {},
        },
      ],
    });
```

Later on, I import files like:

`import img from './someImg.png'`

Resulting URL is like: `/_next/webpack/ef89065b898bb1e3e802c62e4b264417.png` and it works but it's ugly :) Is it possible to customize it to make it more like `/static/images/ef89065b898bb1e3e802c62e4b264417.png` etc

**Comment by paulobarcelos** [comment]
@pietrasiak, do you mind sharing your project where you got this to work? I can't find a way to get the file loader to work at all...

**Comment by pietrasiak** [comment]
@paulobarcelos , @all I've noticed it'll work in development build (`next`) but not with production one (`next start`)

**Comment by arunoda** [comment]
@pietrasiak We can't do this because we can't use this in SSR. We'll do something about images in the future.

**Comment by glemiere** [comment]
This problem occurs only with png files. Weird.

**Comment by glemiere** [comment]
I fixed it by changing `__webpack_public_path__ = assetPrefix + '/_next/webpack/'; //eslint-disable-line` to `__webpack_public_path__ = assetPrefix; //eslint-disable-line`

**Comment by glemiere** [comment]
I made a PR to correct the prefix in production.
https://github.com/zeit/next.js/pull/4072

**Comment by glemiere** [comment]
I fixed this problem in my [nextjs starter](https://github.com/glemiere/nextjs-starter). You can check the `next.config.js` file there.
Any suggestion is welcomed btw.
