### ISSUE TITLE
can nextjs be used in a non-javascript framework ?

### ISSUE THREAD

**Issue by sandys** [zeit/next.js#1933]
hi guys,
nextjs is something that we have watched with a lot of excitement. However, the big issue we had was that our api stack is already in python+flask. We want to build several admin dashboards and we are seriously considering nextjs... but it is not obvious on how this will work. 

is nextjs supposed to be used as the view layer of a non-javascript stack : say flask or rails ? Somewhat like this - https://realpython.com/blog/python/the-ultimate-flask-front-end/

or is it intended to be a javascript framework ?

**Comment by impronunciable** [comment]
I don't know if I'm answering your question but next.js is not supposed to replace your backend. Next is a client-side framework that happens to have a server-side component to allow features like `HMR` and `SSR`. You can definitely combine it with your flask app.

**Comment by timneutkens** [comment]
The best description to give Next.js is a frontend server. It can communicate with any backend using `getInitialProps` 😄 This is a good example: https://github.com/zeit/next.js/tree/master/examples/data-fetch

**Comment by sandys** [comment]
hi Dan,
thanks for the answer!

does nextjs need to "run" using a nodejs instance... or can it be built as
a static page with everything coming from a CDN ? we would rather not bring
in a nodejs dependency into an existing stack.

I think I am looking at this - https://github.com/zeit/next.js/issues/604 .
If this gets done, then the nextjs code gets compiled as a pre-build step
and deployed with the flask app (where it gets served as a static asset).
no nodejs dependency!

I think this issue can be closed - basically, we are looking at server side
reactjs to have zero dependency on nodejs.

**Comment by sandys** [comment]
hi Tim,
I think that description is going to change after
https://github.com/zeit/next.js/pull/1576 gets released right ? Because
then the "server" part goes away and so does getInitialProps (maybe
replaced with getStaticInitialProps)

**Comment by impronunciable** [comment]
@sandys exactly. You'll be able to use next export and just use it without the nodejs side. AFAIK there are people already using that branch

**Comment by timneutkens** [comment]
Exactly like Dan said 👍

**Comment by rgbkrk** [comment]
What would the best way to provide CSRF tokens and base URL to the next app? Query parameters?
