### ISSUE TITLE
IE9: Object doesn't support property or method 'replaceState'

### ISSUE THREAD

**Issue by brendanbowidas** [zeit/next.js#1936]
I was getting this error in the console with my site on Internet Explorer 9. All the navigation links worked but this error seemed to break all my onClick handlers. After adding [html5-history-api](https://github.com/devote/HTML5-History-API) polyfills to the project, everything worked properly. I was wondering if anything can be done about this in a future release as the docs suggest that IE9 is supported.

**Comment by timneutkens** [comment]
@brendanbowidas could you point me to where the docs say IE9 is supported? 🤔

**Comment by timneutkens** [comment]
https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by brendanbowidas** [comment]
Apologies, it's not in the docs. I forgot where I had seen it. I was referring to this comment I saw when browsing issues for a solution: https://github.com/zeit/next.js/issues/436#issuecomment-269888128

**Comment by arunoda** [comment]
IE9+ doesn't in lude IE9.

**Comment by finneganh** [comment]
I found "IE9+" confusing. That reads like "IE9 and up" not "only above 9"

**Comment by luisrudge** [comment]
yeah.. should be IE10+ if it doesn't support IE9
