### ISSUE TITLE
Don't dispose previous pages in dev mode

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1939]
In dev mode, when navigating from e.g index page to page B, it will then after a while destroy the index page: `Disposing inactive page(s): /`. Why not keeping it in memory, at least as long as there aren't too many pages built?

Rather than disposing on timeout, it appears better to me to dispose pages when there are too many of them in memory.

This would allow to then have fast client-side transitions (after the first load), which allows to have a feel of these transitions without needing to deploy to prod.

**Comment by arunoda** [comment]
"too many pages" is kind a hard to decide.
What we can do is to provide an option on asking how many pages to buffer in the memory.

I like that and we can default that to 2.

**Comment by IhostVlad** [comment]
Is there any way for disable disposing pages or set it count to infinite? Yes, it can potentially affect memory usage, but I want to disable it unconditionally. 
Any solution, except implicit next.js library code patching, is appropriate. Thanks in advance.

**Comment by sedubois** [comment]
@timneutkens could maybe comment on why this was closed?

**Comment by timneutkens** [comment]
@sedubois inactivity. I went through all inactive issues.

**Comment by tz5514** [comment]
This problem also bother me. Is there any solution recently? thanks.

**Comment by kunokdev** [comment]
has anything changed related to this issue so far?

**Comment by timneutkens** [comment]
@kunokdev it's configurable now in v4 beta https://github.com/zeit/next.js#configuring-the-ondemandentries
