### ISSUE TITLE
Error: Cannot find module C:\Users\Phillip\desktop\nextjs\hello-next\.next\dist\pages\_error

### ISSUE THREAD

**Issue by pldrake26** [zeit/next.js#1945]
Just started trying out Next.js last night on Windows 10 Creators update and I am getting the following error:  Error: Cannot find module C:\Users\Phillip\desktop\nextjs\hello-next\.next\dist\pages\_error

But, when following this path, the file is there.  I am following the Getting Started section from the Next.js website.  Any help would be appreciated.

**Comment by fxh615** [comment]
windows not work , i have the same problem . compare to nuxt the next api is so bad.

**Comment by timneutkens** [comment]
Arunoda fixed this in https://github.com/zeit/next.js/pull/1930. Will be fixed with the next release.

**Comment by arunoda** [comment]
Try the latest Next.js release. It has the fix.
