### ISSUE TITLE
Cannot deploy project with images to production without hard-coding full absolute asset paths

### ISSUE THREAD

**Issue by tastycode** [zeit/next.js#1946]
Given this code

```
  <img src="/static/image.png"/>
```

When we inspect the tag in the rendered html, it shows a full asset path.

```
   <img src="http://localhost:5200/static/image.png"/>
```

When we deploy to another environment (using `yarn build`), we end up with this
```
   <img src="demohost.ourworld.com//static/image.png"/>
```

Can you point me to the docs that shows in detail how asset (re)writing works and how to troubleshoot it (or disable it)

**Comment by arunoda** [comment]
This is weird and it's impossible to be it like that.
Can you send us a sample repo to see what has went wrong?
