### ISSUE TITLE
Next.js Digital Ocean

### ISSUE THREAD

**Issue by tavo379** [zeit/next.js#1947]
Hi people, how can i use PM2 in in project hosted in digital ocean, the problem is that i need to point PM2 to the file that has the server, but sincerly i dont know where is that file in next js build, so i run next start with a terminal, but in the moment that ia close the terminal the next start is close to, how can i use PM2  with next js in digital ocean?

**Comment by timneutkens** [comment]
This comment shows how to use `npm start` as script
https://github.com/Unitech/pm2/issues/1317#issuecomment-220955319
