### ISSUE TITLE
config webpack filename [hash] error

### ISSUE THREAD

**Issue by jason-ivy** [zeit/next.js#1948]
next.config.js
```
webpack: (config, { dev }) => {
    config.output.publicPath = ''
    config.output.filename = '[name].[hash].js'
    return config
  }
```

the error mssage:
> Using "webpack" config function defined in next.config.js.
(node:11216) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'source' of undefined

**Comment by timneutkens** [comment]
@jason-ivy I don't follow what you want to do. We have cache invalidation built into Next.js 😄 no hashes needed.

**Comment by edwardfhsiao** [comment]
@timneutkens 
i think what he wants to do is to change 
![image](https://user-images.githubusercontent.com/11728228/38234724-48af093c-3751-11e8-9f20-7a011d7e9e49.png)
to
![image](https://user-images.githubusercontent.com/11728228/38234770-6ed50ce2-3751-11e8-8937-23563ba744e8.png)

![image](https://user-images.githubusercontent.com/11728228/38234804-89d638fe-3751-11e8-889f-bc326b2ee659.png)
to
![image](https://user-images.githubusercontent.com/11728228/38234899-dd45725c-3751-11e8-9920-d968778347d1.png)

and how to achieve this? How to append the hash to those files?

**Comment by timneutkens** [comment]
You can't right now. Eventually we'll implement that.

**Comment by edwardfhsiao** [comment]
Hi, @timneutkens can you give us a hint when this hash thing implemented?
