### ISSUE TITLE
Issue with browser back button

### ISSUE THREAD

**Issue by plxel** [zeit/next.js#1953]
I created test repository with my problem - https://github.com/plxel/test-nextjs .

 When you are on index page and changing counter or repository - url changes and when press browser back - getinitialprops is called. 

When you are doing the same on "other" page - getInitialProps is not called on back button. why?

The reason why I need this - I need to restore redux state on browser back. Maybe there is different approach?

**Comment by arunoda** [comment]
Try using shallow routing: https://github.com/zeit/next.js#shallow-routing
