### ISSUE TITLE
[Help needed] Material ui and tab to navigate between pages

### ISSUE THREAD

**Issue by MarcMagnin** [zeit/next.js#1955]
Hi,

Can we use the Tabs component of material ui to navigate between pages? 
http://www.material-ui.com/#/components/tabs

Thanks for the help!
Marc

**Comment by timneutkens** [comment]
@MarcMagnin based on the example given on that page. You could use the imperative router api to change the routes in `handleActive` https://github.com/zeit/next.js#imperatively
```jsx
import React from 'react';
import {Tabs, Tab} from 'material-ui/Tabs';
import Slider from 'material-ui/Slider';

const styles = {
  headline: {
    fontSize: 24,
    paddingTop: 16,
    marginBottom: 12,
    fontWeight: 400,
  },
};

function handleActive(tab) {
  alert(`A tab with this route property ${tab.props['data-route']} was activated.`);
}

const TabsExampleSimple = () => (
  <Tabs>
    <Tab label="Item One" >
      <div>
        <h2 style={styles.headline}>Tab One</h2>
        <p>
          This is an example tab.
        </p>
        <p>
          You can put any sort of HTML or react component in here. It even keeps the component state!
        </p>
        <Slider name="slider0" defaultValue={0.5} />
      </div>
    </Tab>
    <Tab label="Item Two" >
      <div>
        <h2 style={styles.headline}>Tab Two</h2>
        <p>
          This is another example tab.
        </p>
      </div>
    </Tab>
    <Tab
      label="onActive"
      data-route="/home"
      onActive={handleActive}
    >
      <div>
        <h2 style={styles.headline}>Tab Three</h2>
        <p>
          This is a third example tab.
        </p>
      </div>
    </Tab>
  </Tabs>
);

```

**Comment by MarcMagnin** [comment]
cheers @timneutkens sorry for the late reply, I'll give a shot!

**Comment by MarcMagnin** [comment]
Btw quick question around that, does imperative routing prevents the auto prefetching provided by `<Link/>`?

**Comment by MarcMagnin** [comment]
Hi there, I've tried to implement it but onActive of tabs get called once on startup for all pages and that's it... I'm looking on material ui docs but if someone can get a working example that's great!

**Comment by mattapperson** [comment]
@MarcMagnin You can use onChange from the Tabs component

**Comment by tgrrr** [comment]
[Here's the full component to change the React route 4 to match the MaterialUI tab](https://gist.github.com/tgrrr/c5c63c175c5c8f3fb63b929f19615ca1)

Eg. Tab One  path="/one"

You need to control it with onChange like @mattapperson said

Control it in Tab rather than individual Tabs

Use the handler to update history:

````
this.props.history.push(tabSelected);
````

And withRouter _might_ then be required to get around [Blocked Components that you might want to control](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md)

````
export default withRouter(TabsRouter);
````

**Comment by yoramcz** [comment]
ll;l';l';l'l;
