### ISSUE TITLE
_error.js doesn't run react

### ISSUE THREAD

**Issue by aesopwolf** [zeit/next.js#1956]
## Expected Behavior:

A custom `_error.js` page will run react and it's lifecycle methods. For example, I should be able to add some logging code inside `componentDidMount`. Or have click handlers within my `render` function so I can reload the page or submit a support form, etc.

## Actual behavior:

The error page is server rendered (👍) but no interaction is available. `componentDidMount` doesn't run, nothing (👎)...

You can also see the following error in the console while in dev mode:

`Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.`

## Steps to reproduce:

1. Clone this repo, cd into `examples/data-fetch`
1. Modify the `fetch` call with an invalid url
1. Add a custom `_error.js` to the `pages` folder and add a `componentDidMount` method with an alert or console.log etc.
1. run `npm dev` and visit the index page
1. Be sad when your logic inside `componentDidMount` doesn't run.

**Comment by williamkunz** [comment]
@aesopwolf Do you happen to be running [next-routes](https://github.com/fridays/next-routes)? This was my problem. @fridays

**Comment by timneutkens** [comment]
This has been solved a while ago. Keep in mind that `_error.js` is not rendered in development mode for errors, only in production mode.
