### ISSUE TITLE
Glamor global styles sometimes don't update until you restart the server

### ISSUE THREAD

**Issue by silvenon** [zeit/next.js#1957]
You should be able to reproduce this in your glamorous example. Try changing values [here](https://github.com/zeit/next.js/blob/9754395426123ee906b2b062e011bb1d478419c9/examples/with-glamorous/pages/index.js#L13) – sometimes it will hot reload, sometimes you'll have to refresh the page and sometimes you'll have to restart the server. The last one scares me. 😄 

I'm not sure whether this is an issue with Next.js or glamor, I'm very new to server-side rendering.

**Comment by andrewwong97** [comment]
I've had similar issues, here is my post #2210 
Have you had any success since you last posted?

**Comment by silvenon** [comment]
@andrewwong97 I've since switched to styled-components, which sometimes prints this warning:

`React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server`

I have yet to figure out what it means because I'm an SSR newb. 😅

**Comment by bliitzkrieg** [comment]
Does anybody have a fix to this - I am experiencing it with style component and the issue was closed without any solution it seems.

**Comment by silvenon** [comment]
@bliitzkrieg if you're in a hurry to move forward with whatever you're doing, you could try [emotion](https://github.com/tkh44/emotion), which has a similar syntax, but not all of the features of styled-components. There is an up-to-date [example of using it with Next.js](https://github.com/zeit/next.js/tree/master/examples/with-emotion), it works very well with SSR.

**Comment by bliitzkrieg** [comment]
I'll check it out - thanks!

**Comment by ctrlplusb** [comment]
@bliitzkrieg did you have any luck with emotion? I am experiencing the same thing.

Paging @threepointone & @kentcdodds - any insight here?  I really don't want to move away from glamorous.

**Comment by kentcdodds** [comment]
Weird.. I don't remember having any trouble like this with the glamorous website...

**Comment by ctrlplusb** [comment]
@kentcdodds very strange, have just gone through the glamorous website and don't notice anything discernibly different to my configuration. I'll try pull it down later and run some tests.

**Comment by ctrlplusb** [comment]
FYI everyone the reason my hot reloading wasn't working was because some invalid CSS rules were being generated - specifically a media query lacking the closing ")".  Strangely the CSS didn't break on the first load, or even the first HMR - it started breaking on the second HMR.  Le strange.  I'll try to lint my CSS-in-JS in the future.
