### ISSUE TITLE
Pages in sub-directory not working correctly

### ISSUE THREAD

**Issue by tsupol** [zeit/next.js#1958]
If I create a folder in **/pages** and put a .js file there like this
```
 - pages
 ------ auth
 ---------- login.js 
```

By using **Link** with **href="/auth/login"** it won't even navigate on client-side and if you call it from the server-side it won't render correctly.

Everything works perfectly fine if I move the file directly to the **/pages** folder. 

Any help or explanation would be appreciated.
I'm on Windows by the way.

**Comment by impronunciable** [comment]
Just tried the same structure and it's working for me. I develop on OSX, this is a working demo https://weird-xhvwfohmca.now.sh you can see the code at https://weird-xhvwfohmca.now.sh/_src can you try to see if my code works on your windows machine? just to see if this is a windows-related issue

**Comment by tsupol** [comment]
@impronunciable thank you for your reply. Unfortunately, using your code, the same problem still persist in my Windows machine. I tried both npm and yarn but nothing changed. I've also tried many next.js repos as well but none seem to works.

Details:
- Windows 10 x64
- node v.7.10.0
- npm v.4.2.0

**Comment by timneutkens** [comment]
@tsupol @impronunciable I'm pretty sure Arunoda fixed this in https://github.com/zeit/next.js/pull/1930.

**Comment by timneutkens** [comment]
It has not been released yet :)

**Comment by tsupol** [comment]
@timneutkens I'm really looking forward to it. thank you guys.

**Comment by timneutkens** [comment]
I'm closing this 👍 The next release it'll be there 🙌
