### ISSUE TITLE
Component named exports and code splitting

### ISSUE THREAD

**Issue by standayweb** [zeit/next.js#1962]
I am making all components in my components directory accessible through an index file so I can import them like this rather than seperately importing each one.
```js
import { Banner, Main, Layout } from '../components';
```
I am wondering whether doing this will mess with the code splitting and bring in all the components on every page (or chunk all the components) rather than correctly fetching them as they are needed.

**Comment by arunoda** [comment]
@standayweb I guess that's the case. It'll mark as a common module.
This is no the way to do this. Access components directly.
