### ISSUE TITLE
React DevTools Chrome extension warns that React is in development mode even when NODE_ENV=production

### ISSUE THREAD

**Issue by nfriedly** [zeit/next.js#1975]
I'm not sure what the root cause is here, but when I view my site in Chrome, the React DevTools extension warns that it's in development mode.

I have:
* `NODE_ENV=production` in my `npm start` script
* I check `process.env.NODE_ENV` in my express server.js script and set `dev` to false for `next({ dev })`
* I tried setting `NODE_ENV=production` for the build script, but it didn't seem to make any difference.

Am I missing anything?

My code is at https://github.com/nfriedly/user-agent.io if you'd like to take a look. I get the same warning both locally and when running on Bluemix.

**Comment by arunoda** [comment]
Have you build your app with "next build"

**Comment by nfriedly** [comment]
Yep, I tried `next build` and `NODE_ENV=prod next build`

**Comment by arunoda** [comment]
I would like to have a look at this.

**Comment by nfriedly** [comment]
Thanks, I'd appreciate that. I've tried everything I could think of, right down to inspecting the minified JS (although, I'm not really sure what's different about prod vs dev react, so I wasn't entirely sure what to look for...)

**Comment by arunoda** [comment]
This is a result of the `react-google-ad` component. 
It comes with a it's own copy of React.

Try to use something else for that.

**Comment by nfriedly** [comment]
Oh, gosh. Thank you! 

And, I'm sorry for wasting your time on something that really had nothing to do with you...

**Comment by arunoda** [comment]
No problem. I was a good learning experience.
