### ISSUE TITLE
Download javascript in parallel with HTML?

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1977]
Hi and thanks so much for the work with Next.js, the latest release is getting quite more performant 🙂

I see that the app.js bundle downloads after the HTML document has finished downloading. I wondered (sorry for the noob question), is it somehow possible to accelerate this by telling browser right away to download it in parallel, or is this an inherent web limitation?

**Comment by arunoda** [comment]
No. it's not.
They download in parallel. 
See: 
![screen shot 2017-05-16 at 1 13 11 pm](https://cloud.githubusercontent.com/assets/50838/26094963/804af88a-3a39-11e7-84a8-ebe0d6e1e558.png)

**Comment by sedubois** [comment]
Good point. I was looking at a site with an older version of next.js. Thanks for the feedback 👍
