### ISSUE TITLE
next export _document getInitialProps documentation update

### ISSUE THREAD

**Issue by tom2strobl** [zeit/next.js#1978]
Just a quick reminder to not forget to update the docs so that the default `getInitialProps` in `_document.js` should return chunks, as `next export` breaks without supplying the chunks `TypeError: Cannot read property 'map' of undefined at Head.getPreloadDynamicChunks (./node_modules/next/dist/server/document.js:145:20)`

This code snippet from the docs:

```javascript
static getInitialProps ({ renderPage }) {
    const {html, head} = renderPage()
    const styles = flush()
    return { html, head, styles }
}
```

should be changed into this:

```javascript
static getInitialProps ({ renderPage }) {
    const { html, head, errorHtml, chunks } = renderPage()
    const styles = flush()
    return { html, head, errorHtml, chunks, styles }
}
```

**Comment by arunoda** [comment]
Thanks. Just updated the docs.

**Comment by hilarykitz** [comment]
Hey, https://github.com/zeit/next.js/tree/master/examples/with-external-scoped-css needs to be updated for this as well

**Comment by timneutkens** [comment]
@hilarykitz Created a PR #2905
