### ISSUE TITLE
update the component from a dynamic import (SPA related)

### ISSUE THREAD

**Issue by MarcMagnin** [zeit/next.js#1981]
Using dynamic import I'd like change the imported Component on the fly by clicking on a button ie:
Something like: 
```javascript
...
this.props.currentComponent =  '../hello1'
...
render () {
  const DynamicComponent = withImport(import( this.props.currentComponent ))
  return ( 
<div>
 <DynamicComponent/>
 <div>Click <span onClick={() => {
                this.props.currentComponent = '../hello2'
              Router.push('/?test=1','/?test=1' , { shallow: true })}
        }>here</span> to change the component
</div>
</div>
  )
}
```
Is such thing doable?

**Comment by arunoda** [comment]
What you want to do is doable.
But you can't import like this.
The component name of dynamic import should be a string but not a variable.

So, `import( this.props.currentComponent )` does not work but `import( "../components/my-component-name")`

Have a look at [this code](https://github.com/zeit-day/nextjs-dynamic-comp-chat/blob/master/pages/index.js#L9), here's a way to do it.

**Comment by MarcMagnin** [comment]
Awesome!! I'll have a look at it and close that issue.

**Comment by MarcMagnin** [comment]
Great! It work like a charm. So now we basically got proper SPA with this right?

**Comment by arunoda** [comment]
> Basically is there is any drawback within this technique or having a long list of dynamic(import(...))?
Many thanks.

Nope. There's not.

> So we got proper SPA with this right?

Yeah! You can say that :)

**Comment by MarcMagnin** [comment]
@arunoda I was wondering if getInitialProps can be called in a dynamic component?

**Comment by sergiodxa** [comment]
@MarcMagnin `getInitialProps` is for pages,  you fetch the props in your page and then send that props to `DynamicComponent`, when it finish loading it would pass that props to your component.

**Comment by MarcMagnin** [comment]
@sergiodxa cheers. I was wondering if there is a way to get data from the server before dynamically loading a component. My problem is that I have the root page which is basically the menu of the website. Then inner "pages" are DynamicComponents changed when navigating using the menu.

**Comment by arunoda** [comment]
@MarcMagnin check this too: https://github.com/zeit/next.js/issues/2069#issuecomment-304176823

**Comment by arunoda** [comment]
And try [async-reactor](https://www.npmjs.com/package/async-reactor)

With this you won't get SSR support.

**Comment by MarcMagnin** [comment]
Cheers,
My current setup is like :
```javascript 
const Components = [
  {text: 'page1', component : dynamic(import('../system/page1'))},
  {text: 'page2',    component : dynamic(import('../system/page2'))},
]
  getComponent (item) {
    return Components.find((c)=>c.text === item).component
  }

  handleChangeList = (value) => {
    this.content = value
    Router.push('/?p='+value,'/?p='+value , { shallow: true })
  };

...

render(){
 const DynamicComponent = this.getComponent( this.content)

...

return(
 <div>
         <AppNavDrawer  {...this.props} 
              components={Components}
              onRequestChangeNavDrawer={this.handleChangeRequestNavDrawer}
              onChangeList={this.handleChangeList}
             open={navDrawerOpen}>
             <Menu {...this.props}/>
        </AppNavDrawer>
        <DynamicComponent/>
</div>
)}
```

I've tried something such as  
```javascript
DynamicComponent.getInitialProps = async (ctx) => {
      if (isServer) {
        console.log("Dynamic from server")
        // do something
      } else {
       console.log("Dynamic from client")
        // do something
      }
    }
```
But I can't get this working.
