### ISSUE TITLE
re-call getInitialProps to get updated props?

### ISSUE THREAD

**Issue by tamagokun** [zeit/next.js#1982]
I know this can be built using an HOC, but i've been searching to see if anyone else has needed this, or perhaps that is a _better way_.

Often times in `getInitialProps`, I fetch API data, and then return those values as props for my component. However, there are times when I want to "refresh" that data, but since the data is in `props`, I can't exactly just update that data without offloading the data into `state`, making the same API calls and then updating `state` again. Seems a pain to do, and sort of defeats the simplicity of using `getInitialProps`.

So, the idea here is that there would be a way to call `getInitialProps` from your component, it would re-call that function and the component would get new props through the typical lifecycle (`componentWillReceiveProps`, etc..)

Thinking an HOC could look like..

```js
const refreshProps = (ComposedComponent) => {
  return class extends React.Component {
    static async getInitialProps (ctx) {
      return {
        ...await ComposedComponent.getInitialProps(ctx)
      }
    }

    constructor (props) {
      super(props)
      this.state = {initialProps: props}
    }

    refreshProps = async () => {
      const ctx = {} // create context somehow
      this.setState({initialProps: await ComposedComponent.getInitialProps()})
    }

    render () {
      const props = {...this.state.initialProps, refreshProps: this.refreshProps}
      return <ComposedComponent {...props} />
    }
  }
}
```

**Comment by arunoda** [comment]
We won't explicitly implement this feature. But you can re-route to the same url using our `next/router` API. Then it'll run getInitialProps again.

**Comment by tamagokun** [comment]
Yessss, that's so simple! Thanks!
