### ISSUE TITLE
visual indication of 'start of interactivity'

### ISSUE THREAD

**Issue by sidorares** [zeit/next.js#1987]
Trying to find if there is example/documentation/best practices discussion  on this topic before I start implementing my solution.

Problem: with SSR initial page is rendered almost instantly followed by 0.5 to 10 (depending on network and cache state) seconds until full loading + react render is complete. My interactive elements visually look ready to be used at initial page load because of css hover / active / focus states and users start to press buttons etc before javascript kick off and expect controls to be interactive because they look like interactive. 

Would be great to have something built-in (or documented as example) to help with this - for example, page when rendered on server can have 'no-js' class or something similar which is then removed after page is mounted. Components (those that expect JS to behave properly) would have a special style when inside `.no-js` page:

```js
  // components/Button
     <style jsx>
      {
        `
         /* loaded state styles */

         /* before JS loaded or 'js disabled' styles */
          :global(.no-js) button {
            background-color: ${disabled};
            cursor: default
          }
     `}</style>


    // pages/index (or maybe _document.js):

      componentDidMount() {
         this.setState({ loaded: true });
      }

      render() {
          return (
                <div className={!this.state.loaded && 'no-js'}>
                    // ...
                </div>
          );
      }
```

**Comment by rauchg** [comment]
This is a great discussion to start! I really don't think we need a Next.js feature, but it would be great to share best practices here. 

The technique you suggest is a good one, and one I've used in the past

**Comment by sidorares** [comment]
just tried this using `_document.js` and it didn't work because as far as I see `Document` is not mounted after initial server render and lifecycle hooks not executed. Seems to work fine if I move ` this.setState({ loaded: true });` into each individual page `componentDidMount`

**Comment by timneutkens** [comment]
I'm going to close this due to inactivity
