### ISSUE TITLE
Several _document.js for Open Graph markup

### ISSUE THREAD

**Issue by LeeTwelve** [zeit/next.js#1989]
Hi,
I'm trying implement og markup to my site. Main page have a type _business.business_ type and prefix is a `<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# business: http://ogp.me/ns/business#">`, but Article's pages in the blog have a type _article_ and prefix is a `<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">`.
How can I handle the head prefix or is possible use several **_document.js**?

**Comment by jpsc** [comment]
I think you can use this [this](https://github.com/zeit/next.js/tree/v3-beta/examples/layout-component) for that.

**Comment by LeeTwelve** [comment]
Nope, its wrong way, I trying add prefix to <head>

**Comment by impronunciable** [comment]
@LeeTwelve on `getInitialProps` for `_document.js` you get the `req` object, holding the url. You can then take decisions on `render` to add the prefix into head

**Comment by LeeTwelve** [comment]
@impronunciable thx, this is work
