### ISSUE TITLE
this.props.url.push with params not working.

### ISSUE THREAD

**Issue by malikimprowised** [zeit/next.js#1995]
When i try to redirect or change the route using `this.props.url.push` i got 404 error.
i followed this [`this.props.url.replace(/abc?param=value)` But it
 should not throw 404 error. 
I have attached the screenshot of console in browser. 
![screen shot 2017-05-17 at 7 28 51 pm](https://cloud.githubusercontent.com/assets/16553661/26157629/511e4ce8-3b37-11e7-9280-294ad45e6df6.png)

**Comment by arunoda** [comment]
Please use `next/router` APIs.
These APIs are not supported.
