### ISSUE TITLE
Empty _document.js causes next to crash

### ISSUE THREAD

**Issue by reel** [zeit/next.js#1996]
If you have a `_document.js` file that is empty, react throws an invariant error which is not really meaningful:

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.`

This can be tricky to catch and take some time to figure out. (ex: forgot to save the content of _document)

**Comment by arunoda** [comment]
Yeah! This is something we can do. Basically we need to check it's not empty when we are using it.
If so, we need to throw an error.

If you've free time (or someone else) feel free to send us a PR.
Thanks.

**Comment by xuezhma** [comment]
Just made a PR
