### ISSUE TITLE
Support for pluggable renderers

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#20]
Like `inferno` or `preact`.

From the end user perspective, it would work as follows.
Configure `package.json`:

``` js
{
  "dependencies:" {
    "next": "x.y.z",
    "next-preact": "x.y.z",
    "preact": "x.y.z"
  }
}
```

Then we transform JSX to the pragma that, in this example, `next-preact` would need.
The rendering pipeline would similarly be pluggable.

**Comment by developit** [comment]
Willing to help on this, any pointers for where to start?

**Comment by PaulBGD** [comment]
@developit I made a list of files importing React that are not tests, examples, or benchmarks:
https://github.com/zeit/next.js/blob/4b74c70cc9f55a19d4f8305214d2840186af0155/pages/_error.js
https://github.com/zeit/next.js/blob/4b74c70cc9f55a19d4f8305214d2840186af0155/client/head-manager.js
https://github.com/zeit/next.js/blob/4b74c70cc9f55a19d4f8305214d2840186af0155/server/render.js
https://github.com/zeit/next.js/blob/4b74c70cc9f55a19d4f8305214d2840186af0155/lib/side-effect.js
https://github.com/zeit/next.js/blob/4b74c70cc9f55a19d4f8305214d2840186af0155/lib/eval-script.js
https://github.com/zeit/next.js/blob/4b74c70cc9f55a19d4f8305214d2840186af0155/client/next.js
https://github.com/zeit/next.js/blob/4b74c70cc9f55a19d4f8305214d2840186af0155/lib/head.js
https://github.com/zeit/next.js/blob/4b74c70cc9f55a19d4f8305214d2840186af0155/pages/_error-debug.js
https://github.com/zeit/next.js/blob/4b74c70cc9f55a19d4f8305214d2840186af0155/lib/document.js
https://github.com/zeit/next.js/blob/4b74c70cc9f55a19d4f8305214d2840186af0155/lib/app.js

**Comment by trueadm** [comment]
I'm also totally down to getting Inferno fully working with Next as this project is beyond awesome in my opinion. Great work guys :)

**Comment by rektide** [comment]
I threw together the bare minimum changes to tell Webpack to use preact-compat. 2/2 of the builtin next.js examples that I tried worked! Sweet.
https://github.com/rektide/next.js/tree/preact-compat

**Comment by rauchg** [comment]
Very impressive @rektide ! Looking forward to seeing this evolve. Ideally we get it down to 2 imports (`next-preact` and `preact` peer dep) and 1 tweak on the config :)

**Comment by matthewmueller** [comment]
Piggybacking off @rektide's work, I was able to get it working by...

```
git clone https://github.com/zeit/next.js next
cd next
npm install
npm install -i preact-compat/react preact-compat/react-dom
# comment out HTMLDOMPropertyConfig
npm build # this will fail on the tests, but will still give you a dist/client
# copy that dist/client to whatever app you've got next running on
```

Some additional work needs to be done to figure out how to make HMR play nice with non-react things. react-hot-loader does some crazy stuff. @developit has minimalist way to make HMR work more universally.

**Comment by lukeed** [comment]
@matthewmueller Tests pass for me!

**Comment by rauchg** [comment]
That's really amazing (and simple) @matthewmueller

**Comment by lukeed** [comment]
Both `inferno` & `preact` lack a `HTMLDOMPropertyConfig` component, but I'm not sure that they should need to offer one...

**Comment by rauchg** [comment]
Paging @nkzawa and @arunoda. I think we should think about even documenting in the Wiki what the API surface that we depend on from React is. This will allow people to keep experimenting with engine improvement and minimization :)

**Comment by rauchg** [comment]
This is already possible with simple webpack overrides.
