### ISSUE TITLE
 Problems using Next.js with npm

### ISSUE THREAD

**Issue by IgorVieira** [zeit/next.js#2000]
I started to develop an app, at first I had a stack in angular, but it was very verbose and full of bad practices, as I 'm free to make the decisions of choosing the project, decide that I would opt for Next.js, and really I started to use it, I knew a little of React and I started the project, although at the beginning I had a hard time using the actual design, Next.js asked me to install the react-hot-loader and I did not understand why, And soon after I tried to run from the application and it did not work, but I was able to use the next one with the yarn automatic generator, I'll give you all the information about OS, node version, npm and hope it helps in some way Thank you for your time.

OS: Ubuntu 15.10
Nodejs: 6.9.1
NPM: 4.6.1

**Comment by sergiodxa** [comment]
That's weird, Next.js automatically install `react-hot-loader` because it's a dependency, it only require you to install `react` and `react-dom` so you can provide your own version of both of them.

**Comment by arunoda** [comment]
This is pretty weird. Could you send us a sample repo?
I tested (many times) it works fine for me.

Could you follow this guide: https://learnnextjs.com/basics/getting-started ?

**Comment by IgorVieira** [comment]
Here: https://github.com/IgorVieira/sample_nextjs
And no I don't follow this guide, sorry  =/
I just  did a setup described on github

**Comment by sergiodxa** [comment]
@arunoda can it be a problem with the beta version?
@IgorVieira have you tried to use the latest stable version? (2.4.0)

**Comment by arunoda** [comment]
Guys, this is working pretty well for me.
If you are using a NPM proxy or something try to disable it.
I really can't think something other than that.
