### ISSUE TITLE
Massive bundle with next export

### ISSUE THREAD

**Issue by craig-mulligan** [zeit/next.js#2005]
Hey, I've been using https://github.com/zeit/next.js/pull/1576 fork for a little using next export. And with that approach it my app.js bundle was 140kb.

With the the `v3-beta` it's outputting a 1.2mb bundle. 

I've checked webpack isn't running in dev mode during the build, but wondering if you have ideas on what might be happening?

**Comment by davscro** [comment]
Put webpack-bundle-analyzer into your project and check is there any suspicious module which shouldn't be there. Take a look at example below:
https://github.com/zeit/next.js/tree/v3-beta/examples/with-webpack-bundle-analyzer

**Comment by craig-mulligan** [comment]
Thanks for the pointer! It was actually an issue with a local mono-repo managed by Lerna, still not exactly sure why it's so bloated but must have something to do with the linking.
