### ISSUE TITLE
query & pathname do not accompany xhr in getInitialProps during client request

### ISSUE THREAD

**Issue by rickysahu** [zeit/next.js#201]
During client side navigation via Link from next/link, getInitialProps does not receive query or req, it only gets xhr.

    export default class extends React.Component {
      static async getInitialProps({pathname, query, req, res, xhr, err}) {
      ...

It looks like the docs say query and pathname should be sent both client and server side. How do we get the query parameters within an async getInitialProps request in order to call an API with those query values?

**Comment by rickysahu** [comment]
It looks like the react components are rendering twice.  the first time the url query / pathname are undefined and the render fails. after constructor is called they get populated. we should add a way to prevent the first render call.

**Comment by nkzawa** [comment]
hmm, I can't reproduce. Can you tell how to it happens and the version of next.js ?

**Comment by nkzawa** [comment]
I think we found and fixed the cause. Please try 1.1.1 😄
