### ISSUE TITLE
Using next with new Firebase cloud functions Hosting

### ISSUE THREAD

**Issue by jasan-s** [zeit/next.js#2017]
Firebase recently introduced the feature for server side rendering using cloud functions. ANy guide of how to implement next with it Next +redux progressive web app?

**Comment by timneutkens** [comment]
This question was asked yesterday on the community slack too. Here's my answer:

<img width="1275" alt="screen shot 2017-05-20 at 00 03 27" src="https://cloud.githubusercontent.com/assets/6324199/26268512/d0550114-3cef-11e7-8ccc-4f1cbdeff86b.png">

**Comment by timneutkens** [comment]
cc @arunoda what's your take on this?

**Comment by arunoda** [comment]
I haven't try that (and has no plans anytime sooner).
So, give it a try and share your experience.

**Comment by jthegedus** [comment]
I've been working on a solution to this Next.js on Firebase for the last month or so. Sorry I haven't posted here sooner, but I had some issues stopping me from posting. Here's my solution https://github.com/jthegedus/firebase-functions-next-example and an accompanying [blog post (as part of my series)](https://medium.com/@jthegedus/next-js-on-cloud-functions-for-firebase-with-firebase-hosting-7911465298f2) that explains how I got this all working. I had help from @geovanisouza92 and collaborated on partial solution late last month here [serverless-firebase](https://github.com/geovanisouza92/serverless-firebase)
