### ISSUE TITLE
Feature request: Allow supporting custom browser/node versions

### ISSUE THREAD

**Issue by benhjames** [zeit/next.js#2021]
At the moment, running `babel-preset-env` with no `targets` runs all of the transformations available in `es2015`, `es2016` and `es2017`, like `const` -> `var`.

However, most modern browsers support a large subset of these, making these transformations generally unnecessary (and probably worse in terms of performance too).

We could ship less code to people's browsers if we could target, say, the last two browser versions and node 7+!

I'm not suggesting to do this by default, but it would be great to have a field in `next.config.js` that would be passed through to `babel-preset-env`'s `targets` to define some custom browser/node versions to support e.g.

```js
//next.config.js
{
  "targets": ["node": 7, "browsers": "last two versions"]
}
```

**Comment by sergiodxa** [comment]
There is already a PR for that #1808. It makes the babel next preset configurable.

**Comment by benhjames** [comment]
Oops, nice!

**Comment by jaydenseric** [comment]
This is still an unresolved issue and should be reopened for visibility and prioritization. The linked PR has not been merged yet; not every PR gets merged.

It's crazy we can't set our browserslist or engines for transpilation, such a low hanging fruit.
