### ISSUE TITLE
Preloaded scripts warning

### ISSUE THREAD

**Issue by nealalpert** [zeit/next.js#2022]
We're working on upgrading Next.js from 2.1.1 to 2.3.1 after reading about all the speed optimizations.  We're receiving the following warning about the three preloaded scripts that are now included in the head of the page:

![screen shot 2017-05-19 at 4 07 10 pm](https://cloud.githubusercontent.com/assets/2166663/26266953/5c46f10c-3cad-11e7-8c9c-b05a15284209.png)

Did we misconfigure something that's causing these scripts to wait on something else to load?

**Comment by arunoda** [comment]
I haven't seen this before. Tell me a way to reproduce this.
Browser, OS, and app to test.

**Comment by arunoda** [comment]
Please re-open once you've them.

**Comment by khrome83** [comment]
@arunoda - This was Chrome 58, on OSX. We are using a custom `_document.js` but we stopped making a call to `<NextScript />` because it was duplicating the insert of the call to the scripts. 

We did nothing special to make this happen. It may just be the latest version of Chrome? You may also not having warnings enabled in your console. 

```
<link rel="preload" href="/_next/512eec5c-baf2-4688-b78d-feed85936330/page/" as="script">
<link rel="preload" href="/_next/512eec5c-baf2-4688-b78d-feed85936330/page/_error" as="script">
<link rel="preload" href="/_next/d282b8275bc2041a61eba101ddbbef48/app.js" as="script">
```

As far as we can tell they are formatted correct.

**Comment by arunoda** [comment]
> but we stopped making a call to <NextScript /> because it was duplicating the insert of the call to the scripts.

I didn't get this?

**Comment by khrome83** [comment]
@arunoda - I think we had removed `<NextScript>` seeing it in viewsource as a duplicate src reference. I was mistaken that we did need it. Because of that we stopped seeing the warning.

**Comment by khrome83** [comment]
@nealalpert - can you close this?

**Comment by sojungko** [comment]
Is there a way to suppress these warnings?
