### ISSUE TITLE
Preloaded page/ script waiting on app.js

### ISSUE THREAD

**Issue by nealalpert** [zeit/next.js#2023]
After upgrading from 2.1.1 to 2.3.1 we noticed the changes to how our app loads its scripts as per the [excellent article](https://jsmantra.com/faster-leaner-and-better-next-js-ea40afb94907) by Arunoda.  

We noticed that our react app js is loading in `page/` and that first paint happens after `page/` finishes loading.  However our js in `page/` doesn't seem to take effect until `app.js` finishes loading.

![screen shot 2017-05-19 at 4 21 51 pm](https://cloud.githubusercontent.com/assets/2166663/26267404/821a025a-3caf-11e7-81aa-c3effb63a89a.png)

On a good connection this difference is pretty hard to notice but when testing for a high latency environment its definitely noticeable.  

An example of this would be a modal that is opened by a function in a react class cannot be opened until `app.js` loads even though the element renders immediately after `page/` loads and the minified code that opens the modal is included in `page/`.

Is this a misconfiguration issue on our part?

**Comment by arunoda** [comment]
No, this is the way it is.
`app.js` is the code for common chunks and for main app logic. So, it's required.
We only download files in parallel.

BTW: Try to enable caching for your assets. That'll fix the issue in some way.

**Comment by khrome83** [comment]
@arunoda - it's safe to do a far out cache date, because the build and the build-stat id act as a form of cache busting?
