### ISSUE TITLE
Add advanced styled-jsx examples to readme

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#2024]
https://github.com/zeit/styled-jsx has a lot of great examples, eg: `:global`, `importing css` etc. These should be added to the readme under a dropdown using the `<details>` tag (https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)

**Comment by mohitgarg** [comment]
I would like to help with this issue. 😃

**Comment by timneutkens** [comment]
@mohitgarg sure go ahead. Thanks ❤️

**Comment by mohitgarg** [comment]
I am a beginner in OSS so just wants to make sure we are on the same page. Do I need to put the examples in the readme file under the `<details>` tag right?

**Comment by timneutkens** [comment]
Just one for each :)

**Comment by mohitgarg** [comment]
I think I messed up. You were talking about the readme in this repo right?

**Comment by mohitgarg** [comment]
[Is this what you had in mind?](https://github.com/mohitgarg/next.js). Please review before I do a PR. I got over excited before sorry 😀

**Comment by arunoda** [comment]
@timneutkens I don't think this is necessary. It's a different project and anyone can go to the README of styled-jsx and discover it.

**Comment by arunoda** [comment]
Thanks @mohitgarg but let's not do this.

**Comment by arunoda** [comment]
But @timneutkens we can have a single statement saying styled-jsx can these, these and link them.

**Comment by timneutkens** [comment]
I talked about it with @rauchg 😄
