### ISSUE TITLE
Multiple event listeners per event on Router

### ISSUE THREAD

**Issue by ivome** [zeit/next.js#2033]
Right now, it only seems to be possible to attach one event listener to the router for each event, since this is defined as a single property on the Router singleton instance: 

```javascript
// Add listener
Router.onRouterEvent = myCallback;

// Remove
Router.onRouterEvent = null
```

I think it would be nice to be able to add an arbitrary number of event listeners in any part of the application. Suggested API: 

```javascript
// Add event listener
Router.on('routerEvent', callback);

// Remove event listeners
Router.off('routerEvent', callback);
```

Or is there already a way to do that that I missed?

**Comment by arunoda** [comment]
@ivome Currently you've to do it yourself. We didn't do it because there's no standard event listener API.

**Comment by ivome** [comment]
@arunoda Would you be open to a pull request?

**Comment by arunoda** [comment]
I think we didn't wanted to do that. I hope @rauchg can answer this more.

**Comment by ivome** [comment]
It can also be implemented as an add on or external package, but I think the uses cases where you need a feature like that are quite common: 

- Loading indicator in react components + any logic that needs to listen to router events (data fetching, authentication, redirects etc.)
- Loading indicator in multiple components

**Comment by iamdevonbutler** [comment]
Being able to hook into router events could be useful for auth - allowing you to listen for route change events, authorize the user's request, then either proceed or redirect on the client.

**Comment by acanimal** [comment]
Any news on this issue? Anybody has made a custom implementation?

**Comment by paprikka** [comment]
@acanimal not sure if that helps but I've posted a question with an example implementation on SO: https://stackoverflow.com/questions/46770364/multiple-event-listeners-in-next-js-router/46770365#46770365

I'm using rxjs and recompose, but you could easily replace them with a singleton event emitter and regular component lifecycle hooks.

**Comment by jaydenseric** [comment]
@arunoda @rauchg This *really* needs to be reopened. This API limitation is not obvious to a consumer and neither is a workaround. We are not able to publically publish components that rely on router events when consumers are already using the events themselves or have implemented custom workarounds.

I have a global loading indicator component that taps into `onRouteChangeComplete`. I also have to use the same listener to [record gtag.js page load events](https://developers.google.com/analytics/devguides/collection/gtagjs/single-page-applications).

Whichever code runs last works, overwriting the functionality of the other. I guess I'll have to come up with some sort of global singleton module setup.

**Comment by jaydenseric** [comment]
https://github.com/zeit/next.js/blob/4.1.0/lib/EventEmitter.js could be replaced with something like https://github.com/scottcorgan/tiny-emitter.

**Comment by jaydenseric** [comment]
Got a workaround working:

Create `router-events.js`:

```js
import Emitter from 'tiny-emitter'
import Router from 'next/router' // If using next-routes: import { Router } from '../routes'

const emitter = new Emitter()

Router.onRouteChangeStart = url => emitter.emit('routeChangeStart', url)
Router.onRouteChangeComplete = url => emitter.emit('routeChangeComplete', url)
Router.onRouteChangeError = (error, url) =>
  emitter.emit('routeChangeError', error, url)
Router.onBeforeHistoryChange = url => emitter.emit('beforeHistoryChange', url)
Router.onAppUpdated = nextRoute => emitter.emit('appUpdated', nextRoute)

export default emitter
```

In `components/foo.js`:

```js
import routerEvents from '../router-events.js'

const handleRouteChangeComplete1 = url => console.log(url)
const handleRouteChangeComplete2 = url => console.log(url)

routerEvents.on('routeChangeComplete', handleChangeComplete1)
routerEvents.on('routeChangeComplete', handleChangeComplete2)
routerEvents.off('routeChangeComplete', handleChangeComplete1)
```

**Comment by jaydenseric** [comment]
I published [`next-router-events`](https://www.npmjs.com/package/next-router-events) to make this easier for everyone.

**Comment by timneutkens** [comment]
Thanks @jaydenseric!
