### ISSUE TITLE
Aborted because of declined dependency

### ISSUE THREAD

**Issue by Rokt33r** [zeit/next.js#2034]
After upgrading to v2.4.0, I keep getting these error.

![screen shot 2017-05-21 at 22 11 23](https://cloud.githubusercontent.com/assets/5865853/26284292/74e2f6b8-3e72-11e7-865c-33466af46f5b.png)

When going to unbuilt pages, routing is blocked and shows the error message. But, after the page built, routing works normally untill next.js trying to build the page again.

.babelrc
```
{
  "presets": [
    "next/babel",
    "stage-0"
  ],
  "plugins": [
    ["transform-define", "./universalEnv.js"],
    "inline-react-svg"
  ]
}
```

**Comment by arunoda** [comment]
Could you set up a sample repo and send it to us?
Also let us know steps to re-produce it.

**Comment by Rokt33r** [comment]
Sorry for bothering you. It disappeared suddenly. I'll re-open if it occurs again.
