### ISSUE TITLE
Dynamic imports with dynamic filenames

### ISSUE THREAD

**Issue by kylesuss** [zeit/next.js#2037]
I am working from next version 3.0.0-beta5. I have setup a demo application here: https://github.com/kylesuss/next-dynamic-issue

What I would like to do is to dynamically import components, but the filename to dynamically import will not be constant. For example:

```javascript
loadDynamicComponent = (event) => {
  const componentName = event.target.dataset.component;
  const DynamicComponent = dynamic(import(`../components/${componentName}`))
  this.setState({ dynamicComponent: <DynamicComponent />  })
}
```

https://github.com/kylesuss/next-dynamic-issue/blob/eb999951ed8e00134b192ea44b7f15b81f382706/pages/index.js#L10-L14

Is such a thing possible? Currently, I get an error:

`TypeError: Cannot read property 'call' of undefined`

![screen shot 2017-05-21 at 2 31 43 pm](https://cloud.githubusercontent.com/assets/3035355/26287146/3b7479dc-3e32-11e7-9dac-d6ff1fe7d65e.png)

When I change the code to hardcode the component path, all is well:

```javascript
loadDynamicComponent = (event) => {
  const DynamicComponent = dynamic(import(`../components/dynamic`))
  this.setState({ dynamicComponent: <DynamicComponent />  })
}
```

This seems to defeat my purpose for dynamic components. I understand there are concerns with module loading & server side rendering, but what's the best way to achieve something like this? Am I missing the point? Is this a bug / not yet implemented?

Thanks.

**Comment by arunoda** [comment]
No you can't do that. 
But this how you can achieve the same thing. 
See: https://github.com/zeit-day/nextjs-dynamic-comp-chat/blob/master/pages/index.js

**Comment by arunoda** [comment]
There's a similar issue in this issue list. Just search for that for more info.

**Comment by kylesuss** [comment]
I see. Thanks for the link! Makes sense.
