### ISSUE TITLE
Async/await with import fails on navigation between pages

### ISSUE THREAD

**Issue by designgeef** [zeit/next.js#2042]
Using `next@beta`

### Steps to reproduce:

1. Create a `Index.js` page with a link to a `Component.js` page
2. Create a `Component.js` page
3. Add the following code in `Component.js`:
    ```
    const Component = ({ name, SelectedComponent }) => <div>{name}<SelectedComponent /></div>;

    Component.getInitialProps = async (context) => {
       const name = context.query.name;
       const SelectedComponent = await import(`../lib/components/${name}`);
       
       return { name, component: SelectedComponent };
    };

   export default Component;
   ```

4. Run in dev mode (`next`)
5. Navigate from Index page to the Component page

### Expected behaviour:
Page navigates from `/` to `/component` with the dynamically loaded Component rendered (once it is available after the `await` call)

### Error seen:
```
Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://localhost:3000/_next/-/manifest.js:694:30)
    at fn (http://localhost:3000/_next/-/manifest.js:115:20)
    at SameLoopPromise.cb (http://localhost:3000/_next/-/page/component:653:48)
    at SameLoopPromise.runIfNeeded (http://localhost:3000/_next/-/commons.js:41260:12)
    at SameLoopPromise.then (http://localhost:3000/_next/-/commons.js:41190:12)
```

### Additional info:
I tried installing some additional Babel plugins to enable async/await with import as instructed [here](https://webpack.js.org/guides/code-splitting-async/#usage-with-babel-and-async-await) but no luck. The resulting `.babelrc` config file looks like this:
```
{
  "presets": [
    "next/babel",
    "stage-0",
    "es2017"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-async-to-generator",
    "transform-regenerator",
    "transform-runtime",
    ["wrap-in-js", {
      "extensions": ["css$"]
    }]
  ]
}
```

Please guide if I have missed something.

**Comment by ruohki** [comment]
Have you tried using node 7.10? async await works like charm for me

**Comment by arunoda** [comment]
You can't do this: `await import(`../lib/components/${name}`)`
the import module needs to be static. Using variables inside is not possible.
Please re-open if the issue persists even after that.

**Comment by arunoda** [comment]
Related: https://github.com/zeit/next.js/issues/2037
