### ISSUE TITLE
When using a custom apollo server, next/link doesn't trigger data fetch

### ISSUE THREAD

**Issue by devboell** [zeit/next.js#2054]
Please see this minimal example app:
https://with-apollo-mfwujvhmbt.now.sh
(code: https://with-apollo-mfwujvhmbt.now.sh/_src)

I combined the next examples with-apollo and custom-server-express, and added 'graphql-server-express' (an Apollo module).
Instead of using withData() in the index.js, I want to use it in about.js. I modified about.js so it imports a 'connected' apollo component called Films.js.

When I run the app and navigate to about using the header links, the apollo data is not fetched. It does work if I enter https://with-apollo-mfwujvhmbt.now.sh/about directly in the browser.

**edit:**
I am trying to debug this, but I can't figure it out.
When the Link is clicked, the withData hoc is created. I noticed that in `getInitialProps` the process.browser equals true, so it never enters the part where `getDataFromTree(app)` is called. 

So this explains why there is no serverState, but I don't understand why it is set up this way or how to overrule this.

**Comment by keeth** [comment]
Seeing the same thing, the first page loads fine, but on subsequent pages Apollo does not load any data over the network. Using Redux Dev Tools I can see that Apollo is executing the queries, but no requests are made to the graphql server, and in my props() hooks the response data is undefined.

**Comment by keeth** [comment]
Ok I debugged this a bunch and it looks like in my case it was my own fault. :) On full reload the server fetches the data and the GraphQL-connected component is rendered once with all data available.  When you do client-side routing via Link, the component will be rendered once with no data and loading=true, and then again with the fetched data and loading=false.  So you need to guard against that initial 'loading' render cycle which happens only with client-side routing, and show a spinner or whatever while client-side fetch happens.

**Comment by keeth** [comment]
@devboell I can see in your code that you are hitting the same problem.  you need to check that films is non-null, or check that loading==false [before calling films.map](https://zeit.co/YDVp1TbLlj84Pj2n1zJhFN8q/with-apollo/mfwujvhmbt/source?redirect=1&f=components%2FFilms.js&h=133%3B23).  I think this issue can probably be closed.

**Comment by keeth** [comment]
It's funny I normally am more careful with my Apollo connected components but Next made me lazy since the data was always already magically loaded 🎉
