### ISSUE TITLE
No console message when code is rebuilt

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#206]
When there is an issue in the code, an error page is displayed in the browser, and an error stack is shown in both the browser and server consoles. For example in the server console:
```
ERROR in ./containers/Home.js
Module build failed: Error: ENOENT: no such file or directory, open '(...)/containers/Home.js'
    at Error (native)
 @ ./pages/index.js 7:12-41
```

That is great. However, once the error is fixed, although the browser refreshes properly and displays in the console: `[HMR] Waiting for update signal from WDS...`, nothing changes in the server log.

It would be very helpful to print a simple log message "Code reloaded" in both server and browser consoles, so that I can be confident that code reload worked. Otherwise when I work in my code, all I see at the bottom of my console is the old error message, and I have the unsettling feeling that something is still broken.

I suggest to also display the same message in the browser, as it would be clearer than the `[HMR] Waiting for update signal from WDS...`.

If agreed, I can _try_ to add that in Next.js to familiarize...

**Comment by nkzawa** [comment]
Agreed! PR is much appreciated 😄

**Comment by nkzawa** [comment]
This should be solved by https://github.com/zeit/next.js/pull/264
