### ISSUE TITLE
navigator.serviceWorker.getRegistrations is not a function in some older Browsers

### ISSUE THREAD

**Issue by ruslansavenok** [zeit/next.js#2061]
This errors blocks any other client JS code from being executed.

Example devices-browsers:
Android 5.1.1 - UC Browser 10.9.0
Android 5.1 - Chrome Mobile 39.0.0
Android 5.1.1 - Chrome Mobile 43.0.2357
Android 6.0.1 - Chrome Mobile 42.0.2311
Android 4.4.2 - Chrome Mobile 40.0.2214
Chrome 43.0.2357 - Windows 7/8

**Comment by timneutkens** [comment]
What version of next.js are you using? The serviceworker registration removal was removed.

**Comment by ruslansavenok** [comment]
@timneutkens thx. I'll update to latest version.
