### ISSUE TITLE
Content not rendered from the server when dispatching a redux action

### ISSUE THREAD

**Issue by sbjovanovski** [zeit/next.js#2062]
Hi, I'm having an issue with server-side rendering. 

I have this container where in componentWillMount() I'm dispatching an action to get all items
![screen shot 2017-05-25 at 2 19 05 pm](https://cloud.githubusercontent.com/assets/10733596/26438365/248b7f88-4155-11e7-925c-3050bc5cb4a5.png)

Then I have a <Listing /> component where I'm sending the items as props
![screen shot 2017-05-25 at 2 20 23 pm](https://cloud.githubusercontent.com/assets/10733596/26438405/61be6956-4155-11e7-85bf-6c58d5c3a4c6.png)

It looks like this
![screen shot 2017-05-25 at 2 22 03 pm](https://cloud.githubusercontent.com/assets/10733596/26438428/9664b6f6-4155-11e7-9709-2f9b2a03329f.png)

So the items are rendered properly on the website but the problem is that when I go to "View page source" in the browser I can't see the HTML code
![screen shot 2017-05-25 at 2 23 20 pm](https://cloud.githubusercontent.com/assets/10733596/26438468/c266387e-4155-11e7-80f5-68c9dbd8816a.png)

Any idea how to solve this?

**Comment by spencersmb** [comment]
ComponentWillMount is not available on the server. You want to dispatch that action on the PAGE that is rendering the LISTING component in GetInitialProps. GetInitialProps is called both on the server and in the browser - so if you only want that dispatch to be called once - you need to do a check for browser. Here is an example:

```
static async getInitialProps (context) {

      // If we are in the browser do nothing because the store is already loaded
      const stores = process.browser
        ? ''
        : await context.store.dispatch(getStores())
}
```

**Comment by sbjovanovski** [comment]
So I have script that creates the  store and sends it as props to the children called "withData.js"
![withdata](https://cloud.githubusercontent.com/assets/10733596/26440701/27f7766c-4160-11e7-98f9-29aaf7bf1cd5.png)

Then I have this page "index.js"
![page indexjs](https://cloud.githubusercontent.com/assets/10733596/26440717/3673b7c8-4160-11e7-9922-9c5e9bd0b1ef.png)

And in that Index.js page I have a container Home.js where I was doing the dispatch on componentWIllMount(). So if I try like you said in the Home.js Container it doesn't work, it's not even calling my function getAllItems().

I assume I need to call static async getInitialProps (context) in index.js, but my "withData.js" script is already doing. If I remove that "withData" in index.js then I have to reconfigure the store there as well or else it's undefined.

**Comment by sbjovanovski** [comment]
I fixed it by sending the store in getInitialProps to the page and over there I'm dispatching the action

**Comment by spencersmb** [comment]
Nice job man!

**Comment by tommedema** [comment]
@sbjovanovski does that mean that the action is called on the client side? that kind of beats the purpose of server side rendering?

**Comment by sbjovanovski** [comment]
yeah, I didn't find any other way
