### ISSUE TITLE
async/await fetch is slow on now hosting?

### ISSUE THREAD

**Issue by hchoriq** [zeit/next.js#2064]
My getinitialprops is an async static, with an await fetch. I'm using the node-fetch package. The reason I do this is to cache the entire page on cloudflare; if it's not async, then the page data is blank.

However, when this is set up, the page loads very slow when deployed to now. It works fine on my local machine. The endpoint that is being fetched is running just fine elsewhere. Any ideas what might be causing this or anything with now hosting?

**Comment by kamilml** [comment]
I got the same :(

pd. I think because I was using alias in now, I don't tried without alias

**Comment by arunoda** [comment]
async means async and it takes time. Please provide ways to reproduce it both locally and with now.
Reopen, when you have it.
