### ISSUE TITLE
Is it possible to send all routes to /index?

### ISSUE THREAD

**Issue by OutThisLife** [zeit/next.js#2065]
I don't want to build a router, so I have this:

```
app.prepare().then(() => {
	createServer((req, res) => {
		const
			parsedUrl = parse(req.url, true),
			{ pathname, query } = parsedUrl,
			isFile = pathname.match(/(static)/)

		if (isFile === null) app.render(req, res, '/', query)
		else handle(req, res, parsedUrl)
	}).listen(port, err => {
		if (err) throw err
		console.log(`> Ready on localhost:${port}`)
	})
})
```

It kind of works but client side rendering breaks and I get a 404 with a Node server error like "Client pings, but there's no entry for page"

Thoughts?

**Comment by timneutkens** [comment]
Maybe this helps? https://github.com/zeit/next.js/issues/257

**Comment by arunoda** [comment]
@OutThisLife I didn't exactly get the issue.

But you don't  need to create a router on your own.
Simply use express or something you are familiar with: https://learnnextjs.com/basics/server-side-support-for-clean-urls

**Comment by OutThisLife** [comment]
Solved my 'problem' by just using https://github.com/fridays/next-routes

**Comment by timneutkens** [comment]
Awesome 👍
