### ISSUE TITLE
getInitialProps error when result is a simple string

### ISSUE THREAD

**Issue by stlbucket** [zeit/next.js#207]
i have a server with a ping endpoint, and a next client with a component as follows:
```
import React from 'react'
import 'isomorphic-fetch'
export default class extends React.Component {
	static async getInitialProps () {
		const res = await fetch('http://localhost:20831/Ping')
		const data = await res.json()
		return { pingResult: data }
	}
	
	render(){
		console.log('PING', this.props);
		
		return <div>
			<h3>PING</h3>
		</div>
	}
}
```

If my Ping endpoint returns:

`
{
  data: 'GET ALL PING
}
`

everything is fine.

However, if it returns:

`
'GET ALL PING'
`

I get the following error in the server render for next:

```
SyntaxError: Unexpected token G in JSON at position 0
    at Object.parse (native)
    at D:\git2\fbkt-next\node_modules\node-fetch\lib\body.js:48:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Can I not return a simple string to the getInitialProps call?

**Comment by nkzawa** [comment]
You can return only an object, that because React's `props` is an object.

**Comment by eezing** [comment]
Your problem appears to be this line:

const data = await res.json()

res.json assumes your response body is of json, but you have the string "GET ALL PING".

Try res.text() instead of res.json()

**Comment by siddharthkp** [comment]
@nkzawa I think you got the question wrong.

@stlbucket You are using `res.json` but your response is not valid json. Just replace that with `res.text()`

**Comment by siddharthkp** [comment]
@eezing Oops! You beat me to the answer 😄
