### ISSUE TITLE
babel-plugin-transform-decorators-legacy not working with additional babel plugins

### ISSUE THREAD

**Issue by derekr** [zeit/next.js#2071]
https://github.com/derekr/decorator-legacy-plugins-bug

Plugin order seems to affect other plugins, but not sure what the root cause is. Admittedly not too familiar w/ how babel plugins are run/work, but wondering if I'm overlooking something obvious.

If I run each plugin in isolation they work as expected.

Decorators work, but root-import doesn't.

```json
{
  "presets": [
      "next/babel"
    ],
  "plugins": [
    [
      "transform-decorators-legacy",
      "babel-root-import"
    ]
  ]
}
```

![screen shot 2017-05-25 at 11 08 21 pm](https://cloud.githubusercontent.com/assets/22249/26483052/d6148b10-419f-11e7-81d7-6d6e593095f2.png)

root-import works, but decorators throw syntax error

```json
{
  "presets": [
      "next/babel"
    ],
  "plugins": [
    [
      "babel-root-import",
      "transform-decorators-legacy"
    ]
  ]
}
```

![screen shot 2017-05-25 at 11 07 46 pm](https://cloud.githubusercontent.com/assets/22249/26483064/f9fd4c74-419f-11e7-9513-d3295481cc4d.png)

**Comment by derekr** [comment]
So this was my tired eyes not realizing I had nested arrays for the plugins -_-

**Comment by AienTech** [comment]
@derekr so, how did you fixed that? I can't see that
