### ISSUE TITLE
basepath support in nextjs ?

### ISSUE THREAD

**Issue by uidev547** [zeit/next.js#2072]
Do we have basepath support in next.js?
similar to **basename** in react router 4 (https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string).

This is essential if we deploy the next.js application in particular path of  the domain like 
www.myexistingdomain.com/mynextjsapp (**mynextjsapp** is the path for next.js application)

Any suggestions or existing configurations for this scenario?

**Comment by janbaer** [comment]
See also this issue, it's unfortunately still not solved: https://github.com/zeit/next.js/issues/257

**Comment by arunoda** [comment]
Closing this because of #257

**Comment by brian-kilpatrick** [comment]
This doesn't seem like it was solved with the Zones feature that #257 concludes with. I need a single next.js app to live at ourdomain.com/admin, so that requests to /admin => / in the app. Am I missing a solution to this?

**Comment by knoebelja** [comment]
Add `assetPrefix: "/admin"` to `next.config.js` and then when you make a `NextLink` do the following: `<NextLink href={href} as={"/admin" + href}>{children}</NextLink>`

**Comment by dinofx** [comment]
Applications can have 100s of links in them.  It's silly to have to set the "as" property over and over to the same href value plus some prefix.

**Comment by bgarrett-rt** [comment]
I believe this is the same issue I ran across. I posted a potential work around in the comments at: https://github.com/zeit/next.js/issues/257#issuecomment-445509191
