### ISSUE TITLE
dynamic import request 404 in production mode

### ISSUE THREAD

**Issue by nndung179** [zeit/next.js#2073]
Hi guys,

I made a demo to display news from API & using a new feature `dynamic` import. While in development mode it works well. But in production mode, some components were not loaded successfully. Here is a repo
[https://github.com/nndung179/next.js/tree/feature/refactor_layout_with_material_ui](https://github.com/nndung179/next.js/tree/feature/refactor_layout_with_material_ui)

**Comment by arunoda** [comment]
@nndung179 yes. This is a bug.
I can see what's happening here.

In the production mode, due to code splitting, the module is moved to the app.js. So, there's nothing to live inside the dynamic component. So, that's empty.

That's why this cause an error.
We need to fix this.

**Comment by arunoda** [comment]
As a fix for now, do not try to import a module both via dynamic import and normal import.

**Comment by nndung179** [comment]
@arunoda @timneutkens I just tested in version `3.0.0-beta11`. But it still happens

**Comment by cdock1029** [comment]
@nndung179 The fix is merged in master but not part of version `3.0.0-beta11`. I imagine it will be in beta12, which isn't pushed yet.

**Comment by nndung179** [comment]
Thank @cdock1029. Yes I hope it will be there soon.

**Comment by arunoda** [comment]
@nndung179 @cdock1029 try the latest beta: `3.0.0-beta12`

**Comment by nndung179** [comment]
@arunoda just try it. It worked like charm

**Comment by arunoda** [comment]
Nice.
