### ISSUE TITLE
CDN cache time

### ISSUE THREAD

**Issue by MikeSchroll** [zeit/next.js#2074]
Some Page Speed services are reporting negative points for the low caching of next.js on your CDN.
It reports very low cache:

Cache-Control: public, max-age=3

for https://cdn.zeit.co/next.js/1.2.3/next.min.js
even though 1.2.3 has not been updated since December 2016

Is there a reason it is set so low?
Thoughts about increasing it?

It would seem the stated purpose in https://github.com/zeit/next.js/issues/17 of: "For this reason we want to promote a situation where users can share the cache for the basic runtime across internet properties." Is not being fulfilled, as the browsers are not sufficiently caching the asset loaded from the CDN.

**Comment by sergiodxa** [comment]
Hey Next.js 1.2.3 it's really old, the current version is 2.4.0 and the v3.0.0 it's on the way. AFAIK the current versions don't use that file anymore.

**Comment by timneutkens** [comment]
> AFAIK the current versions don't use that file anymore. 
It doesn't use it anymore indeed.

As far as Next.js 1.2.3 goes. I'd highly recommend updating to 2.x+, there's been a million optimizations regarding page speed / rendering 😄
