### ISSUE TITLE
Prettify?

### ISSUE THREAD

**Issue by aesop1** [zeit/next.js#2075]
I really like Next.js but I can easily imagine use cases where I use it for prototyping plain HTML solutions or WordPress themes/templates, or just sharing code with non-Next folk.

In such cases, it would be useful to have statically-rendered HTML (I know Next 3 can do this) that has prettified (non-uglified, nested and readable HTML). I know I can turn off Uglify, but the code is still pretty unreadable.

Is there a way we can get prettified static HTML from Next? Is this already available?

**Comment by sergiodxa** [comment]
@aesop1 react server render always return a single line of HTML code, it's not configurable AFAIK

**Comment by aesop1** [comment]
Thanks, that's kind of what I thought, but thought I'd ask in case there's post-renderer or something that might be capable of this.

**Comment by arunoda** [comment]
I tried to make it pretty. We need to do additional work which doesn't give us any perf or productivity.
So, I ditch the idea.

**Comment by jescalan** [comment]
Reshape can do this for you pretty quickly and easily: https://github.com/reshape/beautify
