### ISSUE TITLE
How could I set cookie or attach token for every outgoing call?

### ISSUE THREAD

**Issue by cosivox** [zeit/next.js#2077]
I've already have access to my token from the request cookie in server side or from localStorage in client side, but I want to attach this token to every outgoing call to external api made from client o server side. How could I make this possible?

**Comment by sedubois** [comment]
Have a look at with-Apollo example. The authToken is passed to the Apollo client in the headers.

**Comment by cosivox** [comment]
@sedubois it seems that example send the authToken automatically in the request with the same-origin cookies policy but it won't work for me because api and nextjs server are separated and they have different domain names. 

However, I've found a solution for anyone who's looking for the same. I've made a class wrapping `isomorphic-unfetch` like the following:

```
export default class Api {

    static setCTX(ctx) {
        Api.ctx = ctx;
    }

    static fetch(url, props) {
        const token = process.browser ? getTokenFromLocalStorage() : getTokenFromCookie(Api.ctx.req)
        return fetch(url, {
            headers: {
                //Add the token here
            }, ...props
        })
    }
}
```

Then I've made a HOC with its own `getInitialProps`, which will be wrapping any page that will be making calls to the API, and set the static `Api.ctx` inside HOC's `getInitialProps` then I simply import Api to my main page and use its fetch method which will have attached the token extracted from `ctx.request` for SSR or from the `localStorage` for client side calls.

**Comment by sedubois** [comment]
@cosivox in `with-apollo`, Next.js frontend server and GraphQL server aren't running on same domain (Next.js is deployed with Now and GraphQL server is on Graphcool).

**Comment by glenarama** [comment]
i don't believe the cookie is getting passed from the example. On client side load - cookie gets passed to same origin, on server no cookie is passed. @sedubois have you tested this to be working and believe otherwise?

**Comment by sedubois** [comment]
@glenamara sorry I don't remember the details but you can also check my demo github.com/relatenow/relate, it has Next.js + Apollo + auth, working both client and server side.

**Comment by glenarama** [comment]
Thanks for the example @sedubois Though it does not pass cookie to the api from a server initiated call - It doesn't pass cookies at all, just a token set up previously as a prop.
So i would say the example does not show how to pass cookies on all outgoing calls - client initiated only (and to same origin). 
Maybe you used an older example - but I would recommend this ticket not closed as the question remains.

**Comment by sedubois** [comment]
Sure @glenarama the OP was about "how to set cookie or attach token to every outgoing call", which is achieved in the said example I guess. If there's a specific question about cookies I'd suggest to create new issue (I'm not very familiar with that subject so would be curious too - including explaining why it's needed and what are the benefits and risks).
