### ISSUE TITLE
Bootstrap won't work when loaded in Head visited from non-bootstrap page

### ISSUE THREAD

**Issue by bestwestern** [zeit/next.js#2079]
Go to https://bootstraperror-ijijmtupiv.now.sh/ 
Click link
Now the dropdown doesn't work. 
Press F5 and it will.

Source:
https://zeit.co/hrronnie/bootstraperror/ijijmtupiv/source

PS: If anyone has jQuery and Bootstrap working by using import, I would very much like to see how.

**Comment by fridays** [comment]
Try https://github.com/reactstrap/reactstrap

It's Bootstrap 4 for React and

> The library does not depend on jQuery or Bootstrap javascript

**Comment by timneutkens** [comment]
If you open the console you'll also see an error: `Uncaught Error: Bootstrap's JavaScript requires jQuery`

**Comment by bestwestern** [comment]
I also load jQuery in Head and it works after f5.

**Comment by bestwestern** [comment]
@timneutkens The problem is that jQuery should be loaded (and will be if you press f5) as it is in the Head as well

**Comment by arunoda** [comment]
Actually, when navigating from a other page head is loading asynchronously. In this case, try to use jQuery and Bootstrap globally on all pages. 

Otherwise use a better pure JS/React alternative.

**Comment by bestwestern** [comment]
@arunoda Thanks - I don't want to bloat the starting page with those libraries. I will try reactstrap
I think this is worth mentioning somewhere. (perhaps it is and I missed it :-/ ) because bootstrap is used by many..
