### ISSUE TITLE
Append / to pathnames when in a subdir

### ISSUE THREAD

**Issue by mikecardwell** [zeit/next.js#208]
If "pages/foo/index.js" exists, and there is also no "pages/foo.js", I would expect requests for "/foo" to be redirected to "/foo/" first before rendering "pages/foo/index.js". I think doing it the way I described is much more common than the way next is currently doing it.

**Comment by nkzawa** [comment]
Thanks for the proposal, but can you explain what is the benefit of redirecting to `/foo/` urls ?

**Comment by mikecardwell** [comment]
/foo and /foo/ are two different URLs. At the moment you're serving up the same content for both. It is bad for SEO and analytics if you have different URLs for the same content. It also breaks  content fetched using relative paths. I.e you have an IMG tag with SRC="foo.jpg" ... That points to two different places whether you are on /foo/ or /foo. It's best to force a single URL as users do silly things like typing in URLs and adding or missing slashes and get confused when they see half broken content

**Comment by nkzawa** [comment]
Make sense but I think this shouldn't be default. (`express` also doesn't work like this) 
You will be able to implement this behavior if you need by https://github.com/zeit/next.js/issues/25 .
