### ISSUE TITLE
Links not working in exported site

### ISSUE THREAD

**Issue by sheepsteak** [zeit/next.js#2082]
If I use `Link` to link to another page in an exported site I'm getting 404 errors because [`loadScript`](https://github.com/zeit/next.js/blob/dff20eae0137ee121c703733fbb87084a8cd86d3/lib/page-loader.js#L71) tries to fetch `/index.js` for the new page. However, in any exported site I make there are no `index.js` files for each page; only `index.html`.

I've made an example (https://github.com/sheepsteak/next-export-error-example) based on the `create-next-app` starter package. Just do:

* `yarn`
* `yarn build`
* `serve out`

Then try to navigate between the three pages in the boxes. You'll get a 404. However, if you manually go to `/1` or `/2` the page loads just fine.

Is there a bug or am I doing something wrong?

**Comment by arunoda** [comment]
Actually, since there's no /1 or /2 pages.
You need to use route masking with links.
See: https://learnnextjs.com/basics/clean-urls-with-route-masking

**Comment by arunoda** [comment]
Please re-open this issue, if ^^^ didn't fix your issue.

**Comment by sedubois** [comment]
@arunoda I seem to be having the same issue, even with non-dynamic links. The `<Link>` seems to just disappear. The links work with `next start` but not with `next export`.

```js
// HeaderElem.js
import Link from 'next/link'

const A = ({ href, onClick, children }) => {
  console.log(`creating A with href ${href} and onClick ${!!onClick}`)
  return (
    <a href={href} onClick={onClick}>
      {children}
      <style jsx>{`
        a {
          some: style;
        }
      `}</style>
    </a>
  )
}

export default ({ href, onClick, children }) => {
  console.log(`creating HeaderElem with href ${href} and onClick ${!!onClick}`)
  const Wrapper = href
    ? ({ href, children }) => <Link href={href}><A href={href}>{children}</A></Link>
    : ({ onClick, children }) => <A onClick={onClick}>{children}</A>

  return (
    <Wrapper href={href} onClick={onClick}>
      {children}
    </Wrapper>
  )
}
```

E.g when I use `<HeaderElem href='courses'>Courses</HeaderElem>`, I get this with `next start`:
```
creating HeaderElem with href courses and onClick false
creating A with href courses and onClick true
```
But I get this with `next export`:
```
creating HeaderElem with href courses and onClick false
creating A with href undefined/ and onClick true
```

**Comment by sedubois** [comment]
OK managed to make it work by simplifying code and flattening. Still don't know why the above didn't work (it should, AFAIK).

```js
import NextLink from 'next/link'

const Span = ({ children, ...props }) => <span {...props}>{children}</span>

export default ({ href, onClick, children }) => {
  const Link = href ? NextLink : Span
  return (
    <Link href={href}>
      <a onClick={onClick}>
        {children}
        <style jsx>{`
          a {
            some: style;
          }
        `}</style>
      </a>
    </Link>
  )
}
```

**Comment by fxh615** [comment]
after build  the link like http://xxx.xxxx.xxxx/xxxx?name=xxxxx    return 404 , OMG , 2 days spented to watch this question.

**Comment by fxh615** [comment]
@arunoda
