### ISSUE TITLE
Redux store still empty after setting it up in getInitialProps in the PAGE

### ISSUE THREAD

**Issue by sbjovanovski** [zeit/next.js#2089]
I'm having issues with getting the proper state from redux store. I'm dispatching an action in my page in getInitialProps:
`static async getInitialProps(context, store){`
`       await store.dispatch(getItemById());`
`}`

then after this is called, it goes in the reducer and I can see that the data received form the server is correct so I'm doing:
`return {`
`                ...state,`
`                item: action.payload.item`
`};`

then in my page I have:
`@connect(state => {`
`return { `
`item: state.item.item`
`}`
`})`
`export default class index extends React.Component {....`

but somehow when I type "this.props.item" in my page the "Item" is an empty object which means that cannot read from the state.

Any idea why?

**Comment by shivmann** [comment]
@sbjovanovski  what was the solution? Im having same issue..

**Comment by danieldhems** [comment]
I've ben having this same problem for the last day - didn't realise I needed an `await' on the store dispatch -> fixed.

**Comment by jabacchetta** [comment]
@danieldhems Do you have this working with thunks and ajax calls? I've got this working fine for simple UI updates that just return actions directly. But it fails when using thunks for whatever reason.

I've also confirmed what others have already mentioned... the reducer receives the data, but the store does not update. This same dispatch that fails in `getInitialProps()` works just fine in `componentDidMount()`.

**Comment by jabacchetta** [comment]
@sbjovanovski @shivmann Also, what library is everyone using for their requests? I wonder if this could be some sort of axios issue (the library I'm using).
