### ISSUE TITLE
Inconsistent way of accessing useful properties in getInitialProps

### ISSUE THREAD

**Issue by mikecardwell** [zeit/next.js#209]
Is it too late to change how stuff is accessed in getInitialProps? Everywhere else in a component I can access this.props.url.query and this.props.url.pathname etc. Why can't this be the same in getInitialProps? Why do it differently there? It's just inconsistent.

I.e, rather than:

```javascript
component.getInitialProps({ ...args, query, pathname })
```

```javascript
component.getInitialProps.call({ props: { query, pathname } }, args);
```

If you're worried about breaking existing code, you could do both, but deprecate the "old" way where pathname and query are passed as function arguments...

I think anything which gets merged into props, should also be available in the props object used as the context in getInitialProps. So for example, the "params" object which is being discussed in #147 too...

**Comment by nkzawa** [comment]
I think I might not understand what you meant, but `getInitialProps` is called to create `props` so they shouldn't be the same. Can you elaborate why you think it's inconsistent ?

**Comment by mikecardwell** [comment]
getInitialProps merges the returned props with some other useful props like "url". You are currently passing through those useful props as function arguments, and only some of them. Why not pass them all in, and why not do that by adding them to the context rather than passing as function args so you can work with them exactly the same way in getInitialProps and render? I should be able to refer to this.props.url.query in both places. I shouldn't have to remember that accessing the query in getInitialProps is different to how I do it everywhere else.

**Comment by mikecardwell** [comment]
To clarify. I would like to be able to do this:

```javascript
export default class SomePage extends React.Component {
  static async getInitialProps ({ req, res }) {
    // Here, "this.props" contains just { "url": ... }
    doStuffWith(this.props.url.query);
    return {
      stuff: 123,
    };
  }
  render () {
    // Here, "this.props" contains the same stuff it did when getInitialProps was called *and*
    // also the stuff it returned, merged in: { "stuff": 123, "url": ... }
    doStuffWith(this.props.url.query);
    return (<div>Wibble</div>);
  }
}
```

**Comment by dstreet** [comment]
@mikecardwell `getInitialProps` is a static method, and `this` does not exist within a static context.

**Comment by mikecardwell** [comment]
@dstreet - the `this` object exists in every function of any type and in any scope. What it points to, depends on the context. Open your browser console and type "this" and you will see in that context it points to the `window` object. When an instance method is called, the `this` object is set to the object it is being called on. The three core functions `Function.call`, `Function.apply` and `Function.bind` allow you to specify whatever `this` object you want to exist when a function is called. For example, the following code:

```javascript
class Test {
	static foo (arg1) {
		console.log(arg1, this.bar);
	}
}

Test.foo("wibble");
Test.foo.call({ bar: 123 }, "wibble");
```

Prints out:

```javascript
1 undefined
1 123
```

You will notice that I set the `this` object to `{bar:123}` the second time I called the `Test.foo` function.

If you are not familiar with the bind/call/apply functions in JavaScript and where the `this` object comes from, I strongly recommend you take an hour or two out of your day to learn them as it is a very quick way to greatly increase your understanding of JavaScript very quickly.

**Comment by mikecardwell** [comment]
To expand, in "router.js" you have:

```javascript
const props = await (Component.getInitialProps ? Component.getInitialProps(ctx) : {})
```

If you were to make this line:

```javascript
const props = await (Component.getInitialProps ? Component.getInitialProps.call({ props: { foo: 123 } }, ctx) : {})
```

Then it would work exactly the same as it currently does, except for inside peoples getInitialProps functions they would be able to look at "this.props.foo" and see that it contains "123".

**Comment by dstreet** [comment]
@mikecardwell Yes, I misspoke. Of course `this` exists, but it is not assigned an instance of `SomePage` at the time `getInitialProps` is called. Perhaps I misunderstood what it was you were expecting. Are you saying `this.props` should be equal to the props passed to the component?

**Comment by mikecardwell** [comment]
You are currently doing this:

```javascript
Component.getInitialProps({ query, pathname, req, res, xhr, err });
```

I am suggesting you do this instead:

```javascript
Component.getInitialProps.call({ props: { query, pathname } }, { req, res, xhr, err });
```

**Comment by dstreet** [comment]
@mikecardwell I think this would cause confusion for many people since `this.props` would be not be the props of the component.

**Comment by mikecardwell** [comment]
Well, I am saying to make it exactly the same, so where would the confusion come from? Obviously it wont include the props that `getInitialProps` returns, they are merged in afterwards, but that will be obvious. All `getInitialProps` would do is return extra props which should be merged in to the existing ones. The existing ones being "url" and anything else you decide to add.

**Comment by domachine** [comment]
Since `getInitialProps` is used to calculate the initial props (see the name) I'd find it pretty confusing to receive a `this.props` with the function context.

**Comment by nkzawa** [comment]
Agreed to @dstreet and @domachine. `this.props` for `getInitialProps` seems confusing.
