### ISSUE TITLE
Prevent remounting of layout component on every page?

### ISSUE THREAD

**Issue by scf4** [zeit/next.js#2091]
I have a top level navbar component which starts a web socket to listen for user notifications. Unfortunately the navbar is unmounted and remounted on every page load, forcing the websocket to disconnect/reconnect.

Is there no way around this with next.js?

**Comment by timneutkens** [comment]
Currently there is no way around this. Closing this as duplicate of https://github.com/zeit/next.js/issues/88 which is the same question brought differently 👍

**Comment by sedubois** [comment]
will https://github.com/zeit/next.js/pull/2010 solve this or is it about something else?

**Comment by timneutkens** [comment]
#2010 is about server side rendering, renderpage is used in _document.js so it won't help with this

**Comment by bestwestern** [comment]
@scf4 a hacky solution until Next solves it: Make the web socket global
