### ISSUE TITLE
Rename next export out directory to project-specific name

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#2092]
After running `next export` and running `cd out` and `now` [as instructed](https://zeit.co/blog/next3-preview), it creates a deployment called `https://out-XXX.now.sh`. It would be better to have the project's name there, e.g renaming the `out` directory to `myproject-static` so that the deployment would be `https://myproject-static-XXX.now.sh`.

I know it's configurable, but I think the default could be better.

**Comment by arunoda** [comment]
Nope. We'll stick with "out" it's a good default. 
It's configurable, so it's up to you.
