### ISSUE TITLE
property or method assign is not supported by this object in IE11

### ISSUE THREAD

**Issue by Filipvdb321** [zeit/next.js#2097]
When I run my application with the nextjs version 2.4.0 on Internet Explorer 11,  I get error: "Property or method assign is not supported by this object."

Is this a babel issue? 

Anyone else had the problem? Is there a fix?

**Comment by berdof** [comment]
I got it solved by including babel polyfill https://babeljs.io/docs/usage/polyfill/

**Comment by Filipvdb321** [comment]
thanks @berdof . One question: did you solve it by importing it in your javascript or by using a custom webpack configuration?

**Comment by c0b41** [comment]
#1943

**Comment by arunoda** [comment]
Closing in favor of https://github.com/zeit/next.js/issues/1943
