### ISSUE TITLE
`<Link />` doesn't handle hashes well

### ISSUE THREAD

**Issue by grabbou** [zeit/next.js#2098]
When you have a `<Link />` component that points to an arbitrary section of a different page, e.g. `<Link href="/#who-we-are" />` (in this case, I want to go to `who-we-are` section of `/`), it will only work when that link is pressed from another page.

When this link is pressed on the `/` page, Next will not scroll into that view. I believe it's because we don't have any code in `Container.js` to handle hash change. We only seem to handle `didMount` scenario.

Also, since we are using `history.pushState`, there's no `hashchange` event being fired. That means we need to integrate handling logic somehow into the router itself.

**Comment by sergiodxa** [comment]
Link it's only to do client side navigation, if you don't go to another page use a native anchor tag

**Comment by arunoda** [comment]
@grabbou this is a good. I need to check this a bit.
