### ISSUE TITLE
Identity-based idempotency support for `next/head`

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#21]
We can have a declarative way of ensuring an element appears at-most-once in the `<head>`. We de-dupe based on the `id` attribute of an element. It could also be `key` but not sure if that interferes with React internals.

``` js
<Head>
  <style id="woot">{`
    /* this element will be appended at-most-once */
    /* even if it appears in multiple components */
  `}</style>
</Head>
```

**Comment by timneutkens** [comment]
Closing this based on https://github.com/zeit/next.js/pull/668#issuecomment-290883019
