### ISSUE TITLE
That bright pink error background color is painful

### ISSUE THREAD

**Issue by phil-andrews** [zeit/next.js#2100]
Any chance we can change this to something more passive? Black, white anything? This pink completely distorts my color field when I look away.

**Comment by timneutkens** [comment]
Hmm I get what you mean. cc @arunoda @rauchg @nkzawa

**Comment by arunoda** [comment]
I agree. We need to change it.
I always hate it.
Anyone wanna propose a nice design? Or reuse something from CRA or etc.
Anyway, the change should be a simple one.

**Comment by phil-andrews** [comment]
```
// black
windowStyle = {
  background-color: #000000
}
// red
errorHeaderDivStyle = {
  color: #D0011B
}
// yellow
errorDetailsDivStyle = {
  color: #F8E81C
}
```

**Comment by krisztianpuska** [comment]
Something like this?

<img width="711" alt="screenshot 2017-06-06 09 25 59" src="https://cloud.githubusercontent.com/assets/5362652/26818312/7076ae4c-4a9a-11e7-821f-9e6429c84378.png">

```FFF, 0E0D0D, 6F6767, F05E93```

**Comment by notrab** [comment]
Those colours are beautiful @krisztianpuska 🙌

**Comment by eashish93** [comment]
I like the one which recently implemented in CRA@latest.

**Comment by arunoda** [comment]
@eashish93 CRA has a pretty solid error layout. We may wanna go for something like that later.
But @krisztianpuska's PR is a solid start and I want to take it ASAP.
