### ISSUE TITLE
endless page refresh when running in development mode in Internet explorer

### ISSUE THREAD

**Issue by Filipvdb321** [zeit/next.js#2101]
When running the application in development mode in internet explorer the pages keep refreshing somehow again and again. I tested this in different IE versions: 11, 10 and 9.

Every time this message appears and the page is rebuild and refrehsed:
restobonsweb_1  | Client pings, but there's no entry for page: /
restobonsweb_1  | > Building page: /
restobonsweb_1  |  DONE  Compiled successfully in 1946ms3:03:57 PM
restobonsweb_1  | 

The next version I am using is: 2.2.0.

**Comment by timneutkens** [comment]
@Filipvdb321 can you try the latest version?

**Comment by Filipvdb321** [comment]
@timneutkens , on the latest version it works indeed. Thanks.

**Comment by timneutkens** [comment]
👌
