### ISSUE TITLE
possibility of using Webpack loaders regardless of SSR

### ISSUE THREAD

**Issue by souporserious** [zeit/next.js#2106]
I was under the impression I would have been able to use a Webpack loader [here](https://github.com/zeit/next.js#customizing-webpack-config). I now realize this is due to the server rendering. Is there any way around this? I'm ok with not having some things server rendered. I'm trying to use [this plugin I made](https://github.com/souporserious/sketch-to-svg-json-loader) to load minimal SVG data for icons. If anything, can the documentation be updated? I can submit a PR, just let me know. I spent a couple hours fighting this thinking it was an issue on my end 😞

**Comment by arunoda** [comment]
Currently that's not possible at once. May be we can do something with tinkering with the custom webpack config.
But I haven't tried that yet. 

We are already discussing this in other issues and this is not in our short term plans.
