### ISSUE TITLE
Next export combined with dynamic Next.js

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#2112]
Next export looks like an awesome way to combine Next.js' features while getting rid of server load issues (e.g #1004) etc.

- But on the other hand, some pages can have quite dynamic data and can't be exported.
- Also, `next export` doesn't support features such as HMR.

Right now, the choice is quite binary (either `next start` or `next export`), but I guess every website/webapp actually falls onto a spectrum.

E.g I guess it could help many people to have a totally normal Next.js dynamic site, except having a landing page which is statically generated (as this is the page with the most traffic and thus server load).

So, it would be quite great if we could e.g use `next dev`, `next build` and `next start` as usual, and Next.js would just serve statically whatever is specified in `next.config.js`' `exportPathMap`, whereas other pages would be handled as usual.

What do you think?

**Comment by frol** [comment]
I think you can configure that on the public facing web-server (e.g. Nginx, Lighttpd, Apache), this way it won't need to even reach the Node.js process for the landing page as it will serve the page from its cache.

**Comment by arunoda** [comment]
Combining this from Next.js itself is kind a doable but will be complex. 
I like the idea of @frol for using some load balancer configs to serves both sites under a same domain.

If you are on ZEIT now, you could use path alias support for this: https://zeit.co/blog/path-alias
