### ISSUE TITLE
unexpected behavior with Router.replace on Firefox

### ISSUE THREAD

**Issue by Filipvdb321** [zeit/next.js#2124]
I have a logout button that does a `Router.replace('/')` to go back to the home page. This works fine on chrome, but on firefox it sometimes goes to the homepage and then back to the original page.
Sometimes it works correctly, and sometimes it doesn't navigate at all.

Anyone else experienced this issue?

Next version: 2.4.0

Firefox version : 53.0.3

Happens on Mac OS and Windows.

**Comment by arunoda** [comment]
This may be related to a some other bug in Next.js
Could you check with latest Next.js versions?

**Comment by Filipvdb321** [comment]
Hi @arunoda , I checked with the latest version and the same thing occurs.

**Comment by timneutkens** [comment]
I don't think this is still an issue.
