### ISSUE TITLE
<style jsx global> not flushed with shallow Router.replace

### ISSUE THREAD

**Issue by flagello** [zeit/next.js#2125]
Working as expected with `Router.push(url, url)`.

**Comment by flagello** [comment]
Steps —

**Page /test**
```js
Router.push("/?test")
```

**Page /**
```js
if (queryAsString(this.props.url.query) === "test") {
  Router.replace("/", "/", {shallow: true})
}
```

Outcome —

`<style jsx global>`s persist across client-side routing.

**Comment by timneutkens** [comment]
I think this has been fixed since then.
