### ISSUE TITLE
Express doesn't seem to work quite right with HMR

### ISSUE THREAD

**Issue by rivertam** [zeit/next.js#2128]
When I create an express server which is hosting the API and the frontend using next's programmatic API (like so):

```javascript
  // this is flow syntax
  app.use(`*`, (req: $Request, res: $Response) => {
    frontendHandler(req, res, parse(req.originalUrl))
  })
```

Several incompatibilities occur. First of all, I need to use `parse` because if I don't, next will do it for me [here](https://github.com/zeit/next.js/blob/v3-beta/server/index.js#L54), which doesn't work as `url` has been modified. However, even if I do this, HMR still doesn't work as both `/_next/webpack-hmr` and `/_next/on-demand-entries-ping` 404.

This becomes half-resolved if I change the following lines:

https://github.com/zeit/next.js/blob/v3-beta/server/on-demand-entry-handler.js#L107 :

From

```javascript
        if (!/^\/_next\/on-demand-entries-ping/.test(req.url)) return next()

        const { query } = parse(req.url, true)
```

to

```javascript
        if (!/^/_next\/on-demand-entries-ping/.test(req.originalUrl || req.url)) return next()

        const { query } = parse(req.originalUrl || req.url, true)
```

In which case `/_next/on-demand-entries-ping` no longer 404s (and I assume returns a proper response because no errors occur)

HMR is still broken, I assume because of `webpackHotMiddleware`, but I'm not sure I understand fully as I believe `webpackHotMiddleware` is supposed to work with express.

Of course, I think this issue is non-existent in a perfectly minimal express app because `.url` doesn't get changed from `.originalUrl`, but I believe the next programmatic API endeavors to be express compliant (based on the [Next.js 2.0 announcement](https://zeit.co/blog/next2) actually showing it with express and not a node http server).

I'm trying pretty hard to solve this issue without changing Next, and I'm still working on a solution, but I fear Next might actually need to change to support this usecase.

Thanks for your time!

**Comment by rivertam** [comment]
Alright, definitely not my favorite solution but I did get it to work without changing Next or really doing anything with major interference to anything internally... It's also a pretty fragile solution and assumes the only thing that's different from an express request and Next's expected request is `url`. So... brittle. It's also not exactly compatible with node 0.10. =)

```javascript
  app.use(`*`, (req: $Request, res: $Response) => {
    const reqProxy = new Proxy(req, {
      get(target: any /* really a $Request */, name: string) {
        if (name === `url`) {
          return target.originalUrl
        }

        return target[name]
      }
    })
    frontendHandler(reqProxy, res, parse(req.originalUrl))
  })
```

**Comment by khrome83** [comment]
@rivertam - I think its easier.

`  server.get('*', (req, res) => handle(req, res));`

After all your custom and dynamic routes, add this to call the default next handler. That will pick up the HMR requests as a fall through. You probably do not want your dynamic and custom routes to be `'*'` though. You need to let if fall through to the line above.

**Comment by arunoda** [comment]
Thansk @khrome83 for the help.

**Comment by arunoda** [comment]
@rivertam 
> It's also not exactly compatible with node 0.10. =)

This project is called **Next.js** but not **Past.js** :D
