### ISSUE TITLE
Server not rendering properly when using `dangerouslySetInnerHTML`

### ISSUE THREAD

**Issue by flybayer** [zeit/next.js#213]
## Background
I'm using [Prismic.io](https://prismic.io/) as a CMS and am fetching this data in `getInitialProps()`. The content is pre-formatted as HTML so I'm using `dangerouslySetInnerHTML`.

## Expected Behavior
The output of `render()` is identical when executed on the server and on the client.

## Actual Behavior
The output of `render()` on the server is wrong and doesn't match the client.

### Render from server:
![image](https://cloud.githubusercontent.com/assets/8813276/20034088/3907136e-a380-11e6-989a-333868a0d7f6.png)

### Render from client
![image](https://cloud.githubusercontent.com/assets/8813276/20034096/45913772-a380-11e6-88fe-1a47726843e8.png)

The difference is the content doesn't have the proper style on the server because the DOM nodes are not nested properly.

### DOM from the server:
![image](https://cloud.githubusercontent.com/assets/8813276/20034108/a35f0e74-a380-11e6-8346-7219730304ff.png)

### DOM from the client:
![image](https://cloud.githubusercontent.com/assets/8813276/20034110/a9723458-a380-11e6-8ce9-7b20d6683196.png)

## Relevant Code
```jsx
const htmlFor = (type) => ({__html: this.props[type]})
<Article heading="Devotional" html={true} >
   {htmlFor('devotional')}
</Article>
```
and
```jsx
const Article = ({heading, children, date, link, style, html}) => (
  <article
    className="mv3 mv4-m mv5-l measure"
    style={style}
  >
    <header>
      <h1 className="f3 f2-ns mt0 lh-title i garamond bb bw3 b--gold">
        {heading}
      </h1>
    </header>
    { html
      ? <p className="lh-copy" dangerouslySetInnerHTML={children} />
      : <p className="lh-copy" >{children}</p>
    }

    <footer>
      { date
        ? <p className="f6 i">{date}</p>
        : null
      }
      {link
        ? <a href="#" className='link dim mid-gray bb b--gold'>
            {link}
          </a>
        : null
      }
    </footer>
  </article>
)
```

## More Info

This deployment and `/_src` are public here: https://thefaithnet-ynikfpghwu.now.sh/

**Comment by impronunciable** [comment]
@flybayer thanks for reporting. I could be wrong but passing your sith through an HTML validator gives me  this errorhttps://validator.w3.org/nu/?doc=https%3A%2F%2Fthefaithnet-ynikfpghwu.now.sh%2F I think is because in HTML nesting `p` tags is not valid. Can you try using a div instead of the outer `p`?

**Comment by flybayer** [comment]
@impronunciable Wow, that was it! 

Good catch, and thank you so much for your help!

**Comment by impronunciable** [comment]
Glad it worked!
