### ISSUE TITLE
next export does not support custom build directory

### ISSUE THREAD

**Issue by davemcorwin** [zeit/next.js#2133]
Looks like the build directory is hardcoded in 'server/export.js'

`const nextDir = join(dir, '.next')`

at

https://github.com/zeit/next.js/blob/v3-beta/server/export.js#L14

Should this be looking at next.config.js to see if `distDir` has been set?

**Comment by timneutkens** [comment]
Yes. Feel free to send a pull request ❤️

**Comment by arunoda** [comment]
Fixed with https://github.com/zeit/next.js/pull/2135
