### ISSUE TITLE
js to external cdn

### ISSUE THREAD

**Issue by davemcorwin** [zeit/next.js#2134]
We are hosting our Next.js application on AWS and would typically deploy the javascript assets to to an external CDN while still keeping the universal rendering intact. Does this make sense with a Next.js application?

Perhaps this is a stupid question, but which js files would I actually need move to the CDN? Is it just app.js?

**Comment by arunoda** [comment]
Tracking this here: https://github.com/zeit/next.js/issues/2053
However, you could use this: https://github.com/zeit/next.js#cdn-support-with-asset-prefix
With the CDN's origin support. Basically, the CDN will fetch the file from the actual site for the very first time.

**Comment by davemcorwin** [comment]
Thanks for the quick response! I understand the asset prefix and plan on using it. The part that confuses me is WHAT to deploy to the cdn, everything in '.next'? just app.js? something else?

Thanks!

**Comment by arunoda** [comment]
@davegomez you don't need to upload anything.
Check this: https://aws.amazon.com/blogs/aws/amazon-cloudfront-support-for-custom-origins/

**Comment by davemcorwin** [comment]
Thats awesome, but it may not be an option for me, I don't have final say on all deployment details. So if I am required to push to S3, what do I need to push?

**Comment by arunoda** [comment]
For that you need to wait until #2053

**Comment by davemcorwin** [comment]
ok, thanks!
