### ISSUE TITLE
pages directory not found when using next export

### ISSUE THREAD

**Issue by valnub** [zeit/next.js#2136]
Loving Next so far, guys. Thanks a lot for building this!

But when trying to export, I get:

```
valnub$ yarn run export
yarn run v0.23.4
$ next build && next export 
> No `pages` directory found. Did you mean to run `next` in the parent (`../`) directory?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Pages directory is clearly there:

```
valnub$ ls
export		node_modules	pages		static		yarn.lock
next.config.js	package.json	src		yarn-error.log
```

And filled:

```
valnub$ ls pages
HeadInclude.js		index.js		publish.js		watch.js
VideoDataMock.js	login.js		signup.js		watchstyles.js
```

**next.config.js**

```javascript
// next.config.js
module.exports = {
  exportPathMap: function () {
    return {
      "/": { page: "/" },
      "/watch": { page: "/watch" },
      "/login": { page: "/login" },
      "/signup": { page: "/signup" },
      "/publish": { page: "/publish" },
    }
  },
}
```

Whats wrong? :-(

"Normal" dynamic server-side rendering works perfectly when running `yarn run dev`

**Comment by moroshko** [comment]
I'm hitting a similar issue when trying to deploy using `now`:

> Couldn't find a `pages` directory. Please create one under the project root

The app works locally fine, and `pages` directory is clearly there.

**Comment by arunoda** [comment]
Can someone give me a proper reproducible repo?

**Comment by valnub** [comment]
@arunoda Sure, here you go: https://github.com/valnub/ZeitExportTest

**Comment by geovanisouza92** [comment]
@valnub Your `package.json` uses `"next": "^2.3.0",`

Isn't the static export [only available](https://zeit.co/blog/next3-preview) from version 3?

**Comment by valnub** [comment]
@geovanisouza92 That's possible, but why is this already in the docs then? How am I supposed to know that parts of the documentation only works for 3.x? https://github.com/zeit/next.js#static-html-export

**Comment by valnub** [comment]
@geovanisouza92 Oooh, yes! You're right. That's it I guess.
