### ISSUE TITLE
`send` dependency missing from package.json

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#2137]
In versions `3.0.0-beta7` and `3.0.0-beta8` the package `send` is used [here](https://github.com/zeit/next.js/blob/3.0.0-beta8/server/render.js#L4), without appearing as a dependency in package.json.

Thats why since upgrading I get `Error: Cannot find module 'send'` when attempting to start the server.

**Comment by ajacksified** [comment]
👍 can confirm, broke me on beta8 as well, fixed by manually installing `send`.

**Comment by arunoda** [comment]
Sorry for this. Fixing this now.

**Comment by cho-is** [comment]
still same issue here

**Comment by MindRave** [comment]
Confirming here too, just got the error on a brand new app.
