### ISSUE TITLE
Handle runtime errors

### ISSUE THREAD

**Issue by nkzawa** [zeit/next.js#214]
- display runtime errors on console and/or browsers.
- recover with hot-code reloading

**Comment by fdidron** [comment]
Hi,

I have been using this on my webpack configs for a while, I think it's a nice way to display errors + build status 

https://github.com/geowarin/friendly-errors-webpack-plugin

It would handle this #206 as well

**Comment by rauchg** [comment]
wow that's pretty amazing @fdidron!

**Comment by fdidron** [comment]
I was able to add this fairly easily to next. I can make a PR if you want
![next-friendly-errors](https://cloud.githubusercontent.com/assets/1848786/20085453/5e07f326-a5ac-11e6-8134-3a464fbc913e.gif)

**Comment by rauchg** [comment]
My god, everything about that gif is beautiful @fdidron. Your themes, and the CLI output of course :D

**Comment by rauchg** [comment]
Please make that PR!

**Comment by fdidron** [comment]
Here you go !
