### ISSUE TITLE
Replace '/_next/' in assets url's with something else

### ISSUE THREAD

**Issue by pietrasiak** [zeit/next.js#2141]
Some url's with required js files look like: `mysite.com/_next/1cc1ce2183f06ed34996e5ea4cebd558/app.js`.

Is it possible to replace `_next` in this url with anything else like `build` so url would be `mysite.com/build/1cc1ce2183f06ed34996e5ea4cebd558/app.js`?

My reason is simply aesthetic.

**Comment by arunoda** [comment]
No that's not possible.
Basically we need to care about the performance and no one is going to look at your source code and then start buying products on your site :)

**Comment by pietrasiak** [comment]
@arunoda thats totally right, but having pretty and _branded_ source code keeps me motivated 🤓
