### ISSUE TITLE
getInitialsProps not called on client

### ISSUE THREAD

**Issue by DCKT** [zeit/next.js#2143]
Hello,

I'm using next with a custom server which use `express`. I've setup a dynamic route to be able to create any pages with my API (prismic.io). The thing is when I load the page on the server, the page with the correct url will load correctly but if I try to use a `<Link>` or `Router` it won't.

Here is my server route : 
```javascript
server.get('/', (req, res) => {
  const mergedQuery = Object.assign({}, req.query, req.params)
  return app.render(req, res, '/page', mergedQuery)
})

server.get('/:page', (req, res) => {
  const mergedQuery = Object.assign({}, req.query, req.params)
  return app.render(req, res, '/page', mergedQuery)
})
```

I've tried to use the `Link` component like this : 
```javascript
<Link href='/page' as='test' query={{ page: 'test' }}>
```

It will load the page as `index` and by-pass the `getInitialProps` method. If I go back with the navigator, the page stay on `/test` and is correctly loaded.

It looks like it's because I'm staying on the "same" URL and the server/client doesn't emit something.

Any idea about this ? 

Thanks for your help.

**Comment by bs1180** [comment]
I think your usage of Link is wrong - [the query should be a property within href](https://github.com/zeit/next.js#with-url-object). Either `<Link href={{ pathname: '/page', query: { page: test }}}>` or ```<Link href={`/page?page=${test}`}>```.

**Comment by DCKT** [comment]
@bs1180 You're totally right !
Now it works perfectly : 
```javascript
<Link
        href={`/page?page=${link.value.document.uid}`}
        as={`/${link.value.document.uid}`}
        key={i}
      >
```
