### ISSUE TITLE
beta 8: pages reload in dev mode after compilation

### ISSUE THREAD

**Issue by finneganh** [zeit/next.js#2147]
Something I just noticed after upgrading from beta 6 to beta 8. In dev mode, clicking a Link to an uncompiled page causes a reload of the current page.

Repro:

 - Click a `<Link>` wrapping an `<a>` to a page that hasn't been compiled yet

What should happen:

 - Page compiles
 - You go to that page

What does happen:

 - Page compiles
 - New page appears briefly
 - Browser reloads the previous page's URL

Seeing this in Chrome. I'm noticing that the server is showing a 200 to the previous page's URL, so it's a full page load rather than just re-rendering client side.

**Comment by gragland** [comment]
Having the same issue.

**Comment by MindRave** [comment]
Yep, seeing the same thing here.

**Comment by starburst997** [comment]
Also have this problem on 2.4.1 (was fine on 2.4.0)

**Comment by arunoda** [comment]
Fixed with https://github.com/zeit/next.js/pull/2171

**Comment by gragland** [comment]
Still seeing this problem on beta 13.

**Comment by gragland** [comment]
@MindRave @finneganh Are you also still seeing this issue with the latest beta?

**Comment by finneganh** [comment]
I have not.
