### ISSUE TITLE
onEnter checks for routes and serverside api proxy?

### ISSUE THREAD

**Issue by IljaDaderko** [zeit/next.js#215]
As routing and server files are not exposed I was wondering if it is possible and how can we achieve following tasks?

1) Add onEnter check to the routes
2) Adjust server to proxy our api calls so we can use something like `/api` on client side to mask it.

**Comment by nkzawa** [comment]
> Add onEnter check to the routes

I wonder if `componentWillMount` is enough ?

> Adjust server to proxy our api calls so we can use something like /api on client side to mask it.

It's addressed on https://github.com/zeit/next.js/issues/25
I'm not sure if we support it, but you can run Nginx or such to proxy requests of next.js server and API server from a domain.

**Comment by timneutkens** [comment]
Closing in favor of #25.
