### ISSUE TITLE
Check if react/react-dom version is incompatible with current release of next

### ISSUE THREAD

**Issue by iaincollins** [zeit/next.js#2150]
After doing an urgent upgrade to next@2.4.1 I ran into a fatal error that stopped one of my apps working in production mode (but it was fine in development mode).

The error was obtuse and preventing react from running on the client, so could I not use the react debug tools, and the error was about PropTypes (and not even code I was invoking) made it hard to track down the problem.

It turns out the problem was an incompatibility between react@15.4.2 / react-dom@15.4.2 and next@2.4.1. Upgrading to react@15.5.4 and react-dom@15.5.4 resolved the fatal error I was seeing in production.

This was a very simple fix but not an easy issue to track down due to the nature of the error. While I know what to look now I probably won't have a problem if I run into this again - but as both next.js and react are updated frequently I can imagine it will bite other people in future.

(It's not actually the first time I've run into a problem like this in the last 6 months or so due to a next+react versioning issue, but this one caught me off guard.)

I'm not sure of the best method to implement this but I'd like to suggest that next.js should check the version of react specified in package.json (or that is being included with webpack?) and raise an error and/or warning if it is earlier than a known compatible version for the the specified release of next.js.

**Comment by arunoda** [comment]
Good point.
We can do this updating peerDeps here: https://github.com/zeit/next.js/blob/v3-beta/package.json#L130

Feel free to send a PR.

**Comment by iaincollins** [comment]
Thanks @arunoda, I've submitted and referenced a PR with react and react-dom bumped in both dependencies and peerDependencies.

(Not sure it the pragma the team is using is to create a branch for chances, couldn't find any docs on it so just did it on master as it's a simple package.json change).

The test suite is 💯 BTW, I am super impressed.

**Comment by arunoda** [comment]
Closed by https://github.com/zeit/next.js/pull/2212
