### ISSUE TITLE
"Can't set headers after they are sent" when calling `res.redirect` from `getInitialProps`

### ISSUE THREAD

**Issue by bookercodes** [zeit/next.js#2152]
Hi folks, really loving Next so far, just ran into one issue:

When I redirect on the server from `getInitialProps`, like this:

```javascript
import React from 'react'

export default class extends React.Component {
  static getInitialProps ({ res }) {
    // assume we're on the server for this example, obviously this won't work on the client
    res.redirect('/')
    return {}
  }
  render () {
    return <h1>Hello</h1>
  }
}
```

I get a server-side error:

```
Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at sendHTML (/Users/booker/Code/next-minimal-oauth-authentication-demo/node_modules/next/dist/server/render.js:422:7)
    at Server._callee17$ (/Users/booker/Code/next-minimal-oauth-authentication-demo/node_modules/next/dist/server/index.js:767:73)
    at tryCatch (/Users/booker/Code/next-minimal-oauth-authentication-demo/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/booker/Code/next-minimal-oauth-authentication-demo/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/booker/Code/next-minimal-oauth-authentication-demo/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/booker/Code/next-minimal-oauth-authentication-demo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/booker/Code/next-minimal-oauth-authentication-demo/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
> Building page: /
```

Also note that this code **works** (the user **is** redirected to `/`), but I see this error in the console. Weird!

Also note that I'm using `express` and `next` (the npm lib, not the cli)

Any thoughts?

**Comment by iaincollins** [comment]
I'm not sure if you can do a redirect like this inside of Next.js on the server side, but curious to know if that is possible.

There is next/router on the client, but I'm not sure that it runs server side (it doesn't AFAIK):
````
import Router from 'next/router'
Router.push('/redirect-route')
````

I wonder if it's worth adding a route handler in express to take of server side redirection? 

````
server.get('/example-route', (req, res) => {
  return res.redirect(301, 'https://example.com/redirect-route')
})
````

**Comment by bookercodes** [comment]
Oh, it is definitely possible! And`next/router` is definitely for the client only. If you attempt to run it from the server, you'll get an error.

I too _suspect_ that the solution here is to define my routes on the server however, for context, I am working on an authentication module that looks like this:

```javascript
export default Component => {
  return class extends React.Component {
    static async getInitialProps ({ req, res }) {
      let session = {}
      if (req) {
        console.log('on the server...')
        if (req.user) {
          session = {
            user: req.user
          }
        } else {
          res.redirect('/admin/login')
        }
      } else {
        const response = await fetch('/auth/session', {
          credentials: 'same-origin'
        })
        const json = await response.json()
        console.log('json', json)
        if (json.user) {
          session = {
            user: json.user
          }
        } else {
          Router.push('/admin/login')
        }
      }

      let isAuthenticated
      if (session.user && session.user.id) {
        isAuthenticated = true
      }
      console.log('returning...', JSON.stringify({ isAuthenticated, session }))
      return { isAuthenticated, session }
    }

    render () {
      if (this.props.isAuthenticated) {
        return <Component {...this.props} />
      }
      return null
    }
  }
}
```

As you can see, there is a certain symmetry to my client and server authentication logic that I'm attached to (maybe I shouldn't be)

Like I say, it works, I just get an error in the terminal which bothers me.

**Comment by bookercodes** [comment]
hehe, this _is_ based on [starter.now.sh](). I'm endeavouring to build a simpler example, focusing on one OAuth provider only.

**Comment by bookercodes** [comment]
Just published the latest version if you want to check it out: https://github.com/bookercodes/next-minimal-oauth-authentication-demo

Remember to `yarn install` and to create `.env` if you want to run it locally:

```
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
SESSION_SECRET=123123123123123123123123123123123123123123123123
PORT=8080
```

**Comment by timneutkens** [comment]
@bookercodes @iaincollins https://github.com/timneutkens/next-universal-redirect/blob/master/index.js#L6-L30 I made this a while back 👍

**Comment by sedubois** [comment]
@timneutkens I got the same error as described in the OP and saw it disappeared when removing my `express-session` middleware. Haven't had yet time to debug more.

**Comment by iaincollins** [comment]
Thanks @timneutkens! 

@sedubois aah yes that rings a bell, thanks for the tip.

**Comment by bookercodes** [comment]
@timneutkens Will check it out, thanks

@sedubois Interesting. Can't remove `express-session` without breaking my app though!

**Comment by sedubois** [comment]
Would be great to test if tim's package combined with express-session shows the issue. If yes, then this ticket could be reopened?

**Comment by timneutkens** [comment]
@sedubois either way it's related to express And not next.js cause without that package it works right. So in theory you could reproduce it with a simple request handler that does the same thing as getInitialProps.

**Comment by bookercodes** [comment]
@timneutkens I'm not really following you. Do you mean that `server.get('/test', (req, res) => res.redirect('/admin/login')` should throw the same error? It doesn't

**Comment by bookercodes** [comment]
Yeah, I just tried

```
res.writeHead(301, {
  Location: '/admin/login'
})
res.end()
```

... Same error :(

**Comment by timneutkens** [comment]
@bookercodes Hmmm, okay, I'll re-open this then, cause we're still discussing it 😄

**Comment by timneutkens** [comment]
@bookercodes one thing I'm thinking right now is, have you tried production mode?

**Comment by bookercodes** [comment]
@timneutkens Yeah, same problem :(

**Comment by bookercodes** [comment]
I am starting to notice that this happens sporadically now, eek!

**Comment by bookercodes** [comment]
Just tested, and this happens with Hapi too.

Also tested `next@beta` as well as the latest stable release (just in case)

**Comment by mattfysh** [comment]
Also having this issue... was working 5 minutes ago.

**Comment by mattfysh** [comment]
@bookercodes @timneutkens are you setting `res.finished = true` after you've sent the response? e.g.

```javascript
if (res) {
  res.redirect(`/article/${doc.id}/${doc.slug}`)
  res.finished = true
}
return {}
``

**Comment by bookercodes** [comment]
No, I'm not. I can't remember off the top of my head, but doesn't `res.redirect` do that automatically?

**Comment by mattfysh** [comment]
@bookercodes `res.redirect` will set the 301 status code, write the location header and end the response. However `res.finished` is a next.js construct only, that tells next.js you have handled the entire request/response lifecycle in `getInitialProps`, so that it knows not to continue writing to the response.

See https://github.com/zeit/next.js/blob/87e01f681bc2d82e59ee30c026180d6984157a34/server/render.js#L67

**Comment by timneutkens** [comment]
@mattfysh does that mean doing that works? 😄

**Comment by mattfysh** [comment]
@timneutkens yea this is working for me now :)

**Comment by bookercodes** [comment]
Oh wow, good to know.

Will test this this afternoon :)

**Comment by timneutkens** [comment]
Amazing. TIL 😲

**Comment by timneutkens** [comment]
Documented here https://github.com/zeit/next.js/wiki/Redirecting-in-%60getInitialProps%60

**Comment by dajomu** [comment]
Quick comment on this issue:
When using `res.finished = true` the connection never seemed to finish and ran till timeout.
When i replaced `res.finished = true` with `res.end()` it seemed to work.
I got that idea from this example -
https://github.com/zeit/next.js/blob/dff20eae0137ee121c703733fbb87084a8cd86d3/test/integration/basic/pages/nav/redirect.js

I'm unsure if this is the correct way to do this, but it worked in a way that the code on the wiki page did not.

**Comment by mattfysh** [comment]
You need to do both.

**Comment by dajomu** [comment]
Ah, ok, thanks

**Comment by dajomu** [comment]
After adding `res.finished = true` I get the timeout issue again, so I've removed it for now.

**Comment by mattfysh** [comment]
@dajomu hmmm... this doesn't sound right, if you're getting a timeout its because you're not handling the request/response lifecycle correctly.

Setting `res.finished = true` tells next.js you've already processed the entire request lifecycle, and that it does not need to do anything further with the `req` or `res` objects. Can you upload an example repo?

**Comment by timneutkens** [comment]
This should work:

```
res.finished = true
res.end()
```

**Comment by mattfysh** [comment]
@dajomu I noticed the wiki only had `writeHead` and `res.finished = true` ... which will result in the timeout because the response was never ended. I've updated the wiki example - https://github.com/zeit/next.js/wiki/Redirecting-in-%60getInitialProps%60

**Comment by timneutkens** [comment]
Thanks @mattfysh

**Comment by bookercodes** [comment]
Just out of interest, is this something that can/will be abstracted by Next?

Having to write,

```
res.finished = true
res.end()
```

Is neither intuitive nor "clean", you know?

Not a complaint as  I am aware of the solution (and I don't feel like I'm in a position to propose a change), just advocating for future Next users who might trip over this.

I wonder if this need to write `res.finished = true`, `res.end()` stems from something internal that could be tweaked?

**Comment by mattfysh** [comment]
Perhaps next could pass in a redirect function and make the request/response management opaque to getInitialProps?

**Comment by guigrpa** [comment]
Just for the record: in my case, the same error appeared when using `compression` middleware with a custom `express` server.
