### ISSUE TITLE
Error: only absolute urls are supported

### ISSUE THREAD

**Issue by kacak9229** [zeit/next.js#2153]
My issue is whenever I refresh the page, I will get this

>  Error: only absolute urls are supported

But manually navigating using `Link` works just fine, its just when I refresh the page I will get that error

I even used this solution, to get the base URL but it does not work https://github.com/zeit/next.js/issues/1213

React
```
import Layout from '../components/MyLayout.js'
import Link from 'next/link'
import fetch from 'isomorphic-unfetch'

const Products = (props) => (
  <Layout>
    <h1>List of Products</h1>
    <ul>
      { props.products.map((product) => (
        <li key={product._id}>{ product.title }</li>
      ))}
    </ul>
  </Layout>
)

Products.getInitialProps = async function() {

  const res = await fetch('/products')
  const data = await res.json()

  console.log(data)
  console.log(`Showed data fetched. Count ${data.length}`)

  return {
    products: data
  }
}

export default Products

```

Serverside

```
app.prepare()
.then(() => {
  const server = express()

  server.get('/products', (req, res, next) => {
    Product.find({}, (err, products) => {
      res.send(products)
    })
  })

  server.get('*', (req, res) => {
    return handle(req, res)
  })

  server.listen(3000, (err) => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000')
  })
})
.catch((ex) => {
  console.error(ex.stack)
  process.exit(1)
})
```

**Comment by marek-sed** [comment]
well you are returning the result from database and not rendered page.

instead  of `res.send` you should call
`app.render(req, res, '/products')`

**Comment by timneutkens** [comment]
In short it's because of `const res = await fetch('/products')`. isomorphic-fetch uses node-fetch on the server side. Node.js is not aware of a base url so it doesn't know where to fetch from. I've seen people solve this using the host header, but that's not 100% secure. I think we talked about this a few days back on slack. Closing cause it's not an issue with next.js.

**Comment by trusktr** [comment]
I have this same problem with Nuxt.js. 😆

**Comment by tomasdev** [comment]
the solution is to hardcode or have a process.env variable containing the prefix.
