### ISSUE TITLE
async-loaded scripts in v3 throw invariant errors

### ISSUE THREAD

**Issue by ajacksified** [zeit/next.js#2154]
Example at: https://github.com/exoplay/exobot-docs (`npm run build`)

`next` server works great, and `next export` works great when loading `docs/index.html` locally. _however_, as soon as you push the static site generated by next.js to a remote server - in my case, github pages - all kinds of react errors occur, such as invariant errors relating to "not finding element id of undefined". If you remove the `async=""` property from the `script` tags that load each page's code, everything works perfectly fine.

I haven't started tracking down the error yet, but did want to make you aware that at least in v3.0.0-beta.8, async-loading scripts is broken. I don't _think_ I'm doing anything weird in my project. It's fairly simple to set up and run the example, but let me know if you have any questions about what I've written if I haven't updated this issue with more detail by the time you look at this.

**Comment by arunoda** [comment]
Interesting. 
I'd like to have a look at this first.

**Comment by arunoda** [comment]
There are some issues in this repo. I can't work properly.
Remove your node_modules directory and run it.
You'll see the errors.
Fix me and send that to me.

But I'm guessing the issue with deploying the app into a sub directory.
We haven't address that yet in whole Next.js deployments.

We need to do it separately. May be after 3.

**Comment by arunoda** [comment]
Re-open this when you update the repo.

**Comment by ajacksified** [comment]
Updated; bumped next.js and added react to the package.json.

> I'm guessing the issue with deploying the app into a sub directory.

That would cause async loading issues? The files get loaded, but the dependencies are out of order.

**Comment by arunoda** [comment]
You didn't push changes to github.
And try to do `npm run export` as well.
Also check the browser console. There are some errors as well.

> That would cause async loading issues? The files get loaded, but the dependencies are out of order.
I can't tell anything without looking at this.

**Comment by ajacksified** [comment]
Sorry, I'm an idiot. Done - `npm run build` runs the export.

You'll need to update `siteRoot` to `"."` in `pages/routes` to run locally, or leave empty for a web server running from`/`.

**Comment by timneutkens** [comment]
I'm going to close this as it's over a year old and from the sound of it can now be handled by using `assetPrefix` and the multi-zones feature
