### ISSUE TITLE
Production of repeteadly ongoing fetch requests.

### ISSUE THREAD

**Issue by ArnoBuschmann** [zeit/next.js#2156]
Hi there :)

I just installed the very basic, newest Next version:

```
yarn add next@beta react react-dom --save
```
Extended the package.json file with the scripts, populated ./pages/index.js inside my project with:
```
export default () => (
  <div>Welcome to next.js!</div>
)
```
And ran ```npm run dev``` The site rendered as expected, but I see the production of repeatedly, ongoing fetch requests in the console:
```
Fetch complete: GET "http://localhost:3000/_next/on-demand-entries-ping?page=/".
Fetch complete: GET "http://localhost:3000/_next/on-demand-entries-ping?page=/".
Fetch complete: GET "http://localhost:3000/_next/on-demand-entries-ping?page=/".
...
```
Request Headers in the network panel are looking like this:
```
GET /_next/on-demand-entries-ping?page=/ HTTP/1.1
Host: localhost:3000
Connection: keep-alive
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Accept: */*
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
```
Any idea, how I can fix this and/or why it happens?

**Comment by frol** [comment]
There is nothing to fix. It is Next.js way of checking which pages are open to automatically rebuild only the necessary pages during development. This is only dev-mode behavior, thus you won't see these requests on production/release build (`yarn run build` + `yarn start`).

**Comment by timneutkens** [comment]
100% What frol said. 👍🏻🙌🏻

**Comment by ArnoBuschmann** [comment]
Ah ok, thanks.
