### ISSUE TITLE
jsx styles not included in server rendered page in 2.4.1

### ISSUE THREAD

**Issue by Filipvdb321** [zeit/next.js#2157]
I suddenly noticed in 2.4.1 that my server rendered pages missed the jsx styles. Then when the client takes over the styles appear. 

Moving back to 2.4.0 solves the problem.

**Comment by arunoda** [comment]
Try the latest releases. And make sure not to do `npm link` Next.js or styled-jsx to your repo.

**Comment by Filipvdb321** [comment]
Hi @arunoda , with the latest version it works and I had also a separate dependency to styled-jsx in my package.json. It seems that removing this one solved the problem.
Thanks.
