### ISSUE TITLE
JSX Styles from imported package not rendered on server

### ISSUE THREAD

**Issue by bnisbett** [zeit/next.js#2158]
I have a package of reusable components that use styled-jsx that I import into my Next.js app (version 2.4.0).

The styles of the components in the package do not get rendered on the server and results in a flash of unstyled content on page load.
 
Is there an approach that's taken for cases like this? 

My only hack has been to import the styled-jsx files separately into my app and add the style to the render using `<styled-jsx>{style}</style>` but that results in duplicate styles when the component's styles get attributed by the client.

Any help would be greatly appreciated

**Comment by timneutkens** [comment]
Hmm afaik this is because you're basically running 2 versions of styled-jsx cc @giuseppeg. I feel like  we might have to move this issue to the styled-jsx repo since it wouldn't only happen with next.js, but with any 2 packages both using styled-jsx.

**Comment by giuseppeg** [comment]
@bnisbett are the components from the component library already transpiled with styled-jsx? If so we have an issue for that already #225

**Comment by arunoda** [comment]
I think the issue mentioned by @giuseppeg is the right one.

**Comment by bnisbett** [comment]
@giuseppeg that's correct the component library is already transpiled with styled-jsx. I think the mentioned issue should cover my case as well.
