### ISSUE TITLE
React attempted to reuse markup in a container but the checksum was invalid.

### ISSUE THREAD

**Issue by sbjovanovski** [zeit/next.js#2160]
Hi, I keep getting an error when I'm getting the data from the server

**React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) tic/temp_images/bike4.jpg" class="cardIm
 (server) tic/temp_images/bike.jpg" class="cardIma**

I'm calling my API in the page

`static async getInitialProps(context, store) {`
`          await store.dispatch(getProfile(context.query.profileId))`
` }`

Any idea why?

**Comment by timneutkens** [comment]
Please provide an example repository to reproduce. It's most likely an external library and not something with next.js.

**Comment by tomexa** [comment]
I have exactly the same error while trying to use Next with redux and redux saga.
We use it exactly the same way as the example 'with-redux-saga', and we dispatch an action that triggers a saga in the getInitialProps function:
```javascript
static async getInitialProps ({ query, store, isServer }) {
    store.dispatch(ProductsActions.getCategories())
}
```
When I query the page, it is rendered with the categories displayed, then they disappear and this error is printed in the console...

It all works good when I get the categories through an async await and return them in the props.

More specifically the error reads:
```
(client)  data-reactid="26"></ul><div class="row"
(server)  data-reactid="26"><li style="flex-grow:
```

So if I guess correctly the client expects an empty `ul` meaning NO categories and the server renders the list of categories
