### ISSUE TITLE
HMR "incomplete chunked encoding" network errors

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#2164]
Since some recent updates (not certain when but I think it was after `3.0.0-beta8`) myself, and a few others on Slack and in other issues have been experiencing weird HMR "incomplete chunked encoding" network errors.

Around the time these errors started appearing, the app began having other issues with routing. Clicking links would not do anything, or pages would spontaneously reload. I think most of these behaviors are related to https://github.com/zeit/next.js/issues/2147.

Possibly related: https://github.com/zeit/next.js/issues/2163.

See screenshot:

<img width="989" alt="screen shot 2017-06-05 at 2 23 03 pm" src="https://cloud.githubusercontent.com/assets/1754873/26770524/fd0c5a5a-49fa-11e7-81bc-bc3489dfe1fc.png">

**Comment by timneutkens** [comment]
Fixed in https://github.com/zeit/next.js/pull/2166
