### ISSUE TITLE
Using MobX `observer` function (not decorator) generates error

### ISSUE THREAD

**Issue by funky0leary** [zeit/next.js#2169]
When I follow the Next/MobX example to the letter, using classes for everything, I have no problems. As soon, however, as I started playing around with using functional components & MobX, I ran into issues. 

Here's an example where I copied some code I had from a hand-built React/MobX app I wrote a while ago:

```javascript
import { observer } from 'mobx-react';

export default observer((props) => {
  return (
    <list-items>
      <ul>
        {props.items}
      </ul>
    </list-items>
  );
});
```
Using the above functional component in the app generates an error:

```
_class.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```
When I remove the `observer` wrapper, the app works fine. 

Just to be safe, I created a class-based version of the component:

```javascript
import { observer } from 'mobx-react';
import React from 'react';

@observer
export default class ListItems extends React.Component {

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <list-items>
        <ul>
          {this.props.items}
        </ul>
      </list-items>
    );
  }
};
```
I encounter no issues with this implementation.

Any ideas why this would be the case?

**Comment by programbo** [comment]
I use `observer` on functional components a lot with Next.js. Can you deploy an example to `now` with the source visible? Just the `index.j` and `list-items` component should be fine.

**Comment by programbo** [comment]
Also, it looks as though you are creating a `ListItems` component, so what is `list-items`? If you haven't declared it yet then you will be returning `undefined` instead of a valid React element.

**Comment by funky0leary** [comment]
No problem. I'll deploy an example. I'll update here when it's up.

**Comment by funky0leary** [comment]
Hmmm... Made a test app. When I deploy it to `now` everything works fine (https://mobx-next-test-ncormpjzvj.now.sh/). But, it still doesn't work on my local, which is really weird.  The. Exact. Same. Code. (sigh...)

![peek 2017-06-08 06-30](https://user-images.githubusercontent.com/28619668/26912391-41580784-4c14-11e7-95ea-d5701252a4cf.gif)

**Comment by javadbat** [comment]
you need install => npm install mobx first
