### ISSUE TITLE
Trouble with Query Params

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#2170]
I am having some issues implementing params to specify the content on my page. 

Some background - I started defining my routes within a headless CMS (contentful). I use a script to build a JS file for inclusion with my `server.js` file. This allows my content authors to define new landing pages, change page names (seo) and other wonderful things. It also allows me to potentially make it so the page within next (ex `/index.js`) is just a template, and I should be able to pass different ids to my datasource.

In my server, I do something like this to define routes. 

```
  for (const { route, locale, renderer, additions, referrer, id } of routes.routes) {
    server.get(route, (req, res) => {
      if (config.APP_ENV !== 'localhost') {
        renderAndCache(req, res, renderer, { id, locale, referrer, additions });
      } else {
        app.render(req, res, renderer, { id, locale, referrer, additions });
      }
    });
  }
```

We use a configuration option to prevent SSR-cache if we are developing. 

Then on my page, I use 

```
  static async getInitialProps({ query: { id } }) {
    const initProps = await new Promise((resolve) => {
      const cms = new Connector();
      const cmsRet = cms.retrieve(id);
      resolve(cmsRet);
    });
    return initProps || {};
  }
```

`Connector()` and `cms.retrieve(id)` is a wrapper to get data specified by the `id`. It then parses it and returns it for us to pass back as part of the initial props. 

When loading into `index.js`, the page renders fine. Meaning that the ID works without any issues. When navigating to another page and them returning, I see -

<img width="978" alt="screen shot 2017-06-05 at 8 19 15 am" src="https://cloud.githubusercontent.com/assets/1844739/26785392/b77d6c46-49c7-11e7-83fc-7ebbf760ff7e.png">

This tells me that the browser history (back button) or client side routing (clicking on site logo from another page) is not preserving that ID. What is the realistic solution?

Keep in mind that every page of the site has it's own unique ID. So passing `id` as a query param using Router seems like a massive limitation.

**Comment by quentin-sommer** [comment]
How are you passing the id param if it's not by query param?

On the client side you can do something like this to implicitly pass the query param but keep pretty URLs:
``` js
<Link
  href={`/index?id=${pageId}`}
  as={`/${prettyName}`}
>
</Link>
```

What's the URL you are using when doing client side routing?

**Comment by khrome83** [comment]
@quentin-sommer - i am trying to find a solution that does not meet the ID as query params. On client side this is a lot of link rewritting. Additionally, I do not want the link to have the query params in the route. That would be less than idea to show the long has value each time.

**Comment by quentin-sommer** [comment]
Your next application use the ID query param to render (because you give it here)
`app.render(req, res, renderer, { id, locale, referrer, additions });`

You can't distinguish between pages on the client without it

**Comment by khrome83** [comment]
@quentin-sommer - i agree. I am just curious if there is a alternative. 

The issue is that the CMS defines a link to home as `/`. So if I use the incoming href, and attach the ID that I need to it. Then use the `as` param to control the appearance and restore it to the originally linked URL?

```
<Link
  href={`/?id=${pageId}`}
  as={`/`}
>
```

**Comment by quentin-sommer** [comment]
This would work, it will direct you to pages/`index.js` with `/` as browser url and populate query string `id` in your code. It's actually the same principle used in this example: 
```
<Link
 href="/route?item=subitem"
 as="/route/subitem"
>
nav : /route/subitem
code querystring : {item: "subitem"}
```

**Comment by khrome83** [comment]
@quentin-sommer - ok this makes me feel better. Thank you!
