### ISSUE TITLE
Can't navigate to dynamic page

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#2173]
So I have a number of pages on my site that 100% of the same, except for data passed from CMS (entry identified by the ID that is passed in). 

I decided to remove the `/about`, `/faq`, `/terms`, `/privacy` pages and replace them with a single `/dynamicContent`;

Using the express code below, `renderer` represent that page on the file system that I am using to present the content. The ID is what actually makes the pages different. 

```
  // All Routes we Support from Contentful
  for (const { route, locale, renderer, additions, referrer, id } of routes) {
    server.get(route, (req, res) => {
      if (config.APP_ENV !== 'localhost') {
        renderAndCache(req, res, renderer, { id, locale, referrer, additions });
      } else {
        app.render(req, res, renderer, { id, locale, referrer, additions });
      }
    });
  }
```

This is what I am using the for the actual pages content.

```
import { Component } from 'react';
import Connector from '../libs/cms/Connector';
import Layout from '../layouts/Default';
import PageContent from '../components/PageContent';

export default class DynamicContentPage extends Component {
  static async getInitialProps({ query: { id, locale, additions } }) {
    const initProps = await new Promise((resolve) => {
      const cms = new Connector();
      const cmsRet = cms.retrieve(id, locale, additions);
      resolve(cmsRet);
    });
    return initProps || {};
  }

  render() {
    const { site, header, content, footer } = this.props;
    const layout = { site, header, footer };

    return (
      <Layout {...layout} >
        <PageContent {...content} />
      </Layout>
    );
  }
}
```

**Problem** - When I enter into a URL `domaion.com/about` it works, but when I navigate to `/about` I get a error page, and the following in console.

<img width="604" alt="screen shot 2017-06-05 at 8 51 19 pm" src="https://cloud.githubusercontent.com/assets/1844739/26810355/cb8f0776-4a30-11e7-9d5a-d9105fd1ff66.png">

How do I instruct a link to use a specific `renderer` from the client side?

**Comment by khrome83** [comment]
Looks like in my route map, I have to store the render and pass that to the client. 

Then instead of a link going to `/about` i send it to `/dynamicContent` and set `as="/about"`.

Does not look like the url is separated from the file path name of the renderer in the Router.

**Comment by Goluis** [comment]
You probably encounter more problems, I've been in a similar situation, what I recommend is that you have each route within pages and do something like this in each route:

```js
import Home from '../components/home'

export default Home
```

one of the main problemas that I have was that you can't browse back when you navigate to the same page using a different `as` prop.

**Comment by khrome83** [comment]
@Goluis - not following what the issue is, can you walk me through that again?

**Comment by arunoda** [comment]
> Then instead of a link going to /about i send it to /dynamicContent and set as="/about".

Actually this is our routing system works.
Please read: https://learnnextjs.com/basics/clean-urls-with-route-masking

**Comment by khrome83** [comment]
Makes sense. The issue for me is a little strange.

The content authors in the CMS do not know what actually does the rendering under the hood, they just want the user to navigate to `/about`. 

What I did was create a custom <Link> component and generates the correct params and uses the imperative router solution. Works great. Not sure what @Goluis is suggesting above...
