### ISSUE TITLE
How to force /404 

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#2174]
Currently in express I am looping over a array of routes that I want to always 404.

These are files within the pages folder that should not resolve because they are used for dynamic content. 

I am looping over a array of route names and currently sending the status code back. But this is not triggering the error page to render.

```
  // All Forced 404s
  for (const route of notFound) {
    server.get(route, (req, res) => {
      res.sendStatus(404);
    });
  }
```

**Comment by khrome83** [comment]
Looks like switching the code to render `_error.js` solved the issue.

```
  // All Forced 404s
  for (const route of notFound) {
    server.get(route, (req, res) => {
      res.statusCode = 404;
      app.render(req, res, '/_error', {});
    });
  }
```

Does anyone know why I should not do this?

**Comment by arunoda** [comment]
@khrome83 I think what you have it good.
Nothing wrong with that.

**Comment by khrome83** [comment]
@arunoda - thank you for the validation =)
