### ISSUE TITLE
Couldn't find a `pages` directory. Please create one under the project root

### ISSUE THREAD

**Issue by moroshko** [zeit/next.js#2178]
I noticed that when I add `files: []` in `package.json`, the following error appears:

> Couldn't find a `pages` directory. Please create one under the project root

Is this a bug?

If not, it would be great to document this.

**Comment by arunoda** [comment]
This is not a bug. What's happening is your files are not included in the project.
See: https://docs.npmjs.com/files/package.json#files

So, use the `files` wisely or remove it.

**Comment by moroshko** [comment]
I put `files: []` intentionally there, as I was planning to publish some files to npm later.

Why is publishing to npm bound to publishing via `now`?

Ideally, I'd like to publish only a subset of all my app files to npm.

What if `now` checked `nextFiles` rather than `files` in `package.json`?

**Comment by arunoda** [comment]
@moroshko Actually this is not a Next.js issue. Try asking it from the now repo(or from the channel) for more info.

**Comment by to-kra** [comment]
i have same issue using next.js in docker. how to resolve it ?

**Comment by smety** [comment]
Hello, i have the same problem. I run npm as user, the owner is me, next.js do not create folder dist. 

Thx

**Comment by julianguyen** [comment]
@to-kra How did you solve it with Docker?
