### ISSUE TITLE
Custom static folder?

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#2180]
Can Next be configured to use a custom folder for static files, rather than `/static`? (e.g. `/client/static`)

**Comment by arunoda** [comment]
Currently this is not possible and we don't have short term plans to take this.

**Comment by BruceHem** [comment]
Is there are way to solve this now?

**Comment by piupiupiu** [comment]
Hey guys,

This is really a must-have feature. In my particular case,I have tons of dynamic urls which come from API and which are absolute. So, now the only possible way of solving this issue is playing with 301 redirects which is not reliable and much more time consuming. I bet I'm not the only one who needs an ability to alternate this path.

**Comment by iamolegga** [comment]
+1 for this feature

**Comment by kachkaev** [comment]
I'd also like be able to configure path to static in a project with this layout

```
.next/

src/
  lib/
  pages/
  static/                <--- current location of static
  next.config.js
  server.ts

production-server/       <--- autogenerated on build
  static/                <--- current symlink to ../src/static
  server.js

static/                  <--- where I want to keep my static files
```

In current `src/server.ts`:
```ts
const app = next({
  dir: "./src",
  dev: env.NODE_ENV !== "production"
});
```

Desired change:
```ts
const app = next({
  dir: "./src",
  staticDir: path.resolve(__dirname, "..", "static"),
  dev: env.NODE_ENV !== "production"
});
```

@arunoda could you please reopen this issue?

**Comment by kachkaev** [comment]
Alternatively, `staticDir` could go to `conf` object, i.e. become a part of `next.config.js` if this file exists. In my case it is present in development (so `conf` can be `undefined`) and is absent in `build` (so `distDir` needs to be defined).

**Comment by skywickenden** [comment]
See https://github.com/zeit/next.js/blob/canary/examples/root-static-files/server.js for an example of how to serve static files from another location. I customised this so that it serves everything in the static folder as if it is from root.

```
const { createServer } = require('http')
const { parse } = require('url')
const next = require('next')
const { join } = require('path')
const fs = require('fs');

const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

fs.readdir('./static', (err, staticFiles) => {

  app.prepare()
    .then(() => {
      createServer((req, res) => {
        const parsedUrl = parse(req.url, true);
        let file = parsedUrl.pathname.replace('/', '');
        file = file.substring(0, file.indexOf('/')); 

        // serve static files as if from root - removing the static reference.
        if (staticFiles.indexOf(file) > -1) {
          const path = join(__dirname, 'static', parsedUrl.pathname);
          app.serveStatic(req, res, path);

        // Else handle with next
        } else {
          handle(req, res, parsedUrl);
        }
      }).listen(port, (err) => {
        if (err) throw err;
        console.log(`> Ready on http://localhost:${port}`);
      });
    });

});

```

**Comment by kachkaev** [comment]
`app.serveStatic()` includes `this.isServeableUrl()` check:

https://github.com/zeit/next.js/blob/e9242705a3c75fa480250ef623b926b6140b1bf5/server/index.js#L396-L410

This means that serving any static file from outside next.js dir will result 404. In order to avoid that in some special case, this version of `serveStatic` can be used:

```js
import { serveStatic } from "next/dist/server/render";
```

e.g.:
```js
server.get("*", (req, res) => {
  const { pathname } = parse(req.url, true);

  if (env.WEB_ASSETS_DIR) {
    const fullPathname = `${req.protocol}://${req.get(
      "Host",
    )}${decodeURIComponent(pathname)}`;
    if (fullPathname.startsWith(env.WEB_ASSETS_BASE_URI)) {
      const assetPath = resolve(
        env.WEB_ASSETS_DIR,
        fullPathname.substr(env.WEB_ASSETS_BASE_URI.length),
      );
      if (fs.existsSync(assetPath)) {
        return serveStatic(req, res, assetPath);
      }
    }
  }
  handle(req, res);
});
```
