### ISSUE TITLE
NextJS with React-Intl

### ISSUE THREAD

**Issue by kimthangatm** [zeit/next.js#2181]
Hi, When running next.js with react-intl in **Safari** in example https://github.com/zeit/next.js/tree/v3-beta/examples/with-react-intl i see error:

## Development:
![dev](https://user-images.githubusercontent.com/7090588/26861816-bb72a19a-4b70-11e7-9d77-d61059db9650.png)

## Production: 
![production](https://user-images.githubusercontent.com/7090588/26861817-bb78dd30-4b70-11e7-9742-15f5749f84f4.png)

Chrome and Firefox is ok.

**Comment by lucasfeliciano** [comment]
👀 Keeping my on this because I'll introduce react-intl soon to my project.
So would be nice to see this discussion

**Comment by coluccini** [comment]
Which version of Safari are you using? I think until 10 they didn't had the Intl API, so you need to use a polyfill (I use polyfill.io)

**Comment by kimthangatm** [comment]
Thanks @coluccini . 👍 

My Safari version: Version 9.1.2 (11601.7.7) and you right :)

@lucasfeliciano You can try this solution:

I try to change https://github.com/zeit/next.js/blob/v3-beta/examples/with-react-intl/components/Layout.js follow code and It work for me: 

```javascript
export default injectIntl(({intl, title, children}) => {
  const polyfillURL = 'https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.' + intl.locale;
  return (    
  <div>
    <Head>
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <title>{title || intl.formatMessage(messages.title)}</title>
      <script src={polyfillURL}></script>
    </Head>

    <header>
      <Nav />
    </header>

    {children}

  </div>
)
})
```

**Comment by coluccini** [comment]
:+1: You can add it in /pages/_document.js as well.

**Comment by timneutkens** [comment]
If this works, could you please send a pull request for it, then everyone has the fix ❤️

**Comment by coluccini** [comment]
Of course! 👉  https://github.com/zeit/next.js/pull/2283

**Comment by skumblue** [comment]
Thank you team!

**Comment by thundermiracle** [comment]
I got the same error when trying to use outdated IE10 after applying this solution. (By IE11's debug bar on Windows10)
