### ISSUE TITLE
how can I add custom attributes to the <head> html tag

### ISSUE THREAD

**Issue by quentin-sommer** [zeit/next.js#2183]
For example : `<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# place: http://ogp.me/ns/place#">`

**Comment by HaNdTriX** [comment]
I think the docs have an answer for that https://github.com/zeit/next.js#custom-document 😃

**Comment by quentin-sommer** [comment]
Hi @HaNdTriX,

If you go through the example it doesn't show how to `<head>` tag, only its children, I'm talking about affecting the tag itself!

Moreover the next `<Head>` is a special component that collects children everywhere you use it and puts them back in the `<head>` of the document at the end, but the props aren't propagated into the `<head>` tag. See here : https://github.com/zeit/next.js/blob/v3-beta/server/document.js#L86

**Comment by HaNdTriX** [comment]
Now I get the point. Good catch!

I don't think it's possible right now: https://github.com/zeit/next.js/blob/v3-beta/lib/head.js

    import Head from ''
    ... 
    <Head foo='bar' />

**Comment by HaNdTriX** [comment]
@quentin-sommer did the PR solve your problem?

**Comment by quentin-sommer** [comment]
It did! thanks
