### ISSUE TITLE
Firefox console warnings when navigating

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#2193]
Most of the time when navigating by clicking links an empty string is being passed to `getElementById`. I think it is from [this line](https://github.com/zeit/next.js/blob/dff20eae0137ee121c703733fbb87084a8cd86d3/lib/app.js#L47) related to scrolling to hashes.

Firefox has a console warning:

<img width="453" alt="screen shot 2017-06-08 at 2 40 18 pm" src="https://user-images.githubusercontent.com/1754873/26912602-ea1fd6c8-4c58-11e7-8a2e-71c6f3c2a369.png">

**Comment by timneutkens** [comment]
I don't see any harm in adding a check for `if(hash)`. Feel free to send a PR ❤️

**Comment by arunoda** [comment]
Yeah! Feel free to send a PR :)
