### ISSUE TITLE
Production mode pushRoute issue

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#2195]
I am really stumped. When certain conditions exist, `Router.pushRoute` runs without doing anything, without any console errors appearing.

All of these are conditions must be met to see the issue:

- Running a Next.js build in `production` mode. Dev mod is fine in all browsers.
- Cache must be cleared. If you have visited the page you are trying to route to, it will work.
- Firefox or Safari. Chrome is fine.
- For Safari, an additional condition is required: It must be a deployed live site (I'm using Now), all the above conditions work locally.

I am using `pushRoute` via [fridays/next-routes](https://github.com/fridays/next-routes) inside an Apollo mutation callback. I have console logged everything ok up until the Next.js router is meant to do it's thing [here](https://github.com/fridays/next-routes/blob/master/src/index.js#L72). I am pretty confused how to debug from there.

If you manually click a link to the same route in the site nav because you are sick of waiting, it transitions fine.

Seen in `3.0.0-beta10` and `3.0.0-beta11`.

**Comment by jaydenseric** [comment]
Setup [all the available router event listeners](https://github.com/zeit/next.js#router-events), to log what happens.

`RouteChangeStart` logs fine, with the right `url` in the callback. Then nothing else happens.

If you click on any other link, immediately `onRouteChangeError` fires with a `Route Cancelled` error and the `url` is `undefined`.

Then `RouteChangeStart`, `BeforeHistoryChange`, and `RouteChangeComplete` events fire correctly for the link route transition.

**Comment by jaydenseric** [comment]
I have tried removing everything fancy on the destination page, no apollo or redux decorators. Just a hello-world `div`. Same result.

**Comment by arunoda** [comment]
Could you reproduce this in the plain Next.js routing APIs?
I'd like to have a sample repo for this in either case?

**Comment by jaydenseric** [comment]
For some reason Chrome is displaying the issue too now.

I tried to setup a test case using the plain routing APIs, using next-routes, using next@2, and using the latest 3.0.0-beta, but it all works.

I think the issue relates to Apollo and a race condition. I have added a `setTimout` of 2 seconds around the `Router.pushRoute` line, and it works. Something to do with Apollo fetching or caching is happening slower than the route is trying to change, and instead of logging an error it just hangs.

**Comment by jaydenseric** [comment]
To clarify what I'm trying to do. In the Apollo mutation callback of a login form, I am attempting to redirect to the user page. The user page is decorated `withData` and fetches additional user data from the GraphQL API.

**Comment by jaydenseric** [comment]
Further clues.

Ruled out it having anything to do with query batching.

Interestingly, when replacing `Router.pushRoute('user', { userId })` with `window.location.href = `/users/${userId}` it works. Something silently breaks within the imperative Router API.

**Comment by jaydenseric** [comment]
@arunoda HOLY MOTHER OF GOD. It seems to be related to `prefetch` on links. 3 days of debugging node_modules and minified production code.

Just before the redirect, I dispatch a redux action that stores details about the logged in user. The global header component is subscribed to the store, and when there is a logged in user it shows additional links in a user menu. The user page link has `prefetch` on it. This seems to re-render at the similar time the `Router.pushRoute` runs. The prefetching of the same page that Router is trying to transition to confuses the process. Everything is prefefetched and looks ok, but it fails to action the transition - maybe because an event temporarily silenced while prefetching.

I removed `prefetch` of the link in question and no more problem!

**Comment by gragland** [comment]
@jaydenseric I've been having a similar issue which I believe is caused by the same bug. In production if I click a link created with `<Link prefetch>` right after the page loads `RouteChangeStart` will fire and then nothing happens. The next time I click a link `onRouteChangeError` fires, just like you describe. Because this is intermittent my guess is that it's only happening if the prefetch has not completed before the link is clicked.
