### ISSUE TITLE
How to run test on a Next.js project with jest?

### ISSUE THREAD

**Issue by tw0517tw** [zeit/next.js#2197]
When I build a project with next, I want to run test on my pages. 
When I do so, it came up with some errors:
repo: https://github.com/tw0517tw/nextcov
CI: https://travis-ci.org/tw0517tw/nextcov/builds/240702824

1. Test suite failed to run
It seems not using correct babel config so I can't use `import` or `export`?

2. Failed to collect coverage from /home/travis/build/tw0517tw/nextcov/pages/about.js
Also seems to be a babel config problem?

Any ideas about how to test next projects?

**Comment by arunoda** [comment]
Check our examples: https://github.com/zeit/next.js/tree/v3-beta/examples

**Comment by neighborhood999** [comment]
Hey @tw0517tw, try to write under config in your `.babelrc`:

```json
{
  "env": {
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ]
    }
  }
}
```

**Comment by tw0517tw** [comment]
I've checked the example and solve this problem. Thanks.

**Comment by ATM-SALEH** [comment]
Update link of example project using jest
https://github.com/zeit/next.js/tree/canary/examples/with-jest
