### ISSUE TITLE
Slide In / Slide Out page transitions

### ISSUE THREAD

**Issue by paulwehner** [zeit/next.js#2198]
Is there a recommended approach for page transitions... to have current page slide out and next page slide in. So something like this: https://github.com/maisano/react-router-transition

**Comment by Ajar-Ajar** [comment]
+1 for page transitions :)
If only the initial rendering happens on the server, and all the rest of the routing happens on the client, like is the case with react-router, then it means that it must be possible right?

**Comment by timneutkens** [comment]
@Ajar-Ajar it's not that simple. We re-render the whole page on route changes. This is tracked in https://github.com/zeit/next.js/issues/88. Closing as duplicate.
