### ISSUE TITLE
next-v3 export 404.html

### ISSUE THREAD

**Issue by MikeSchroll** [zeit/next.js#2199]
netlify uses a 404.html: https://www.netlify.com/docs/redirects/

What's the best way to have next export produce this file?

**Comment by arunoda** [comment]
Simple. Create a page called `404.js` or whatever the name you like :)
And then add a export path to that page in the `next.config.js`

**Comment by MikeSchroll** [comment]
Note for myself and others... next export does not directly make a 404.html
I had to:

```
$ grep 404 next.config.js
    "/404": { page: "/404" }
$ grep 404 package.json
    "build": "next build && next export && cp out/404/index.html out/404.html && cp static/_redirects out/",
```

Also note that I'm moving the netlify _redirects from static to the correct path.
