### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by pietrasiak** [zeit/next.js#220]
Hi,

What do you guys think about making it `react-native` compatible?

Files structure could be the same as now, and `Link` component with path to proper `view` would push it to Navigation (eg `NavigationExperimental`) of `react-native`.

eg

`<Link to="app/view-1" transition="push-left"/>`

I'm not sure how this could support Navigation `topbar` making it easy to use/get started and customizable at the same time.

What do you think?

**Comment by sergiodxa** [comment]
I think in a React Native application you usually don't use server-render because it's a native application, also the server doesn't know how to render a `<View>`, `<Image />`, `<ScrolledView />` and other RN components because they aren't HTML tags but native application UI elements.

**Comment by timpler** [comment]
@sergiodxa right, but I didn't mean `server rendering` as it's not needed for mobile apps. 

What I mean is - other concepts of `next.js` would be great for react-native development.

**Comment by impronunciable** [comment]
@timpler I totally get your point. It would be great to support React Native. I think this has to do with https://github.com/zeit/next.js/issues/20

**Comment by rauchg** [comment]
@sergiodxa there are some legitimate usecases for server-rendering even in RN world

**Comment by timneutkens** [comment]
I'm not sure if we can support this, it would be a cool project similar to nuxt.js maybe 🤔
@impronunciable what do you think?

**Comment by impronunciable** [comment]
I can't see right now the best way this could be approached but definitely an interesting idea to play with

**Comment by ttraenkler** [comment]
Would it make sense to integrate it with [react-navigation](https://reactnavigation.org/) (which replaces NavigationExperimental) and targets not only React Native but also React Web)? 

> React Navigation is born from the React Native community's need for an extensible yet easy-to-use navigation solution. It replaces and improves upon several navigation libraries in the ecosystem, including Ex-Navigation and React Native's Navigator and NavigationExperimental components.
Until the community lands on one navigation solution that works well on the web and React Native, we will forever be destined to re-invent navigation. We are extremely sensitive about the burden of change that accompanies a new navigation library, so we aim to provide a solution that will work long into the future. We are excited to support React Navigation for any platform, including cutting-edge frontiers like hybrid native apps, web server rendering, and ReactVR.

**Comment by timneutkens** [comment]
This would be a long term goal of the project. I'm closing this because it won't be realised anytime soon. (Doing an open issue sweep to keep things organized 👍) Do note this is definitely on my mind, since well, how cool would it be :smirk: and I'm sure ZEIT has thought about it.

**Comment by rdewolff** [comment]
Would be an amazing addition to Next.js!

**Comment by frol** [comment]
There is Expo.io project, which doesn't implement a router, but it simplifies React Native development  greatly.

**Comment by sscaff1** [comment]
I'm working on an app right now where we use NextJS to power the API and robust admin interface. The client facing application is a React Native app though. It's a nice stack (Next, Express RN) if you need interfaces on both sides. I guess this is no different than using Express with RN though. Just thought I would share.
