### ISSUE TITLE
next export getting stuck

### ISSUE THREAD

**Issue by ritz078** [zeit/next.js#2201]
I am using v3.0.0-beta11.

My export is stuck.

```
$ next build renderer && next export -o build renderer 
> Using external babel configuration
> location: "/Users/ritz078/projects/snape/.babelrc"
> Using "webpack" config function defined in next.config.js.
  Exporting to: /Users/ritz078/projects/snape/build

  copying "static" directory
  exporing path: /download
```

Its working great using `next start`. This isn't helping me in knowing what's wrong. Maybe any error message will be great. Anything that helps in debugging.

**Comment by arunoda** [comment]
It's hard to say. But seems like something when exporting the `/download` page. Double check the getInitialProps of that page.

If that doesn't solved, reopen this and send me a sample repo.

**Comment by arunoda** [comment]
Also try to update to the latest beta.

**Comment by ritz078** [comment]
Hi @arunoda ,

Here is the repro https://github.com/ritz078/snape/tree/nex-v3

All dependencies are latest. Run `yarn build` and it will be stuck.

**Comment by arunoda** [comment]
@ritz078 I'll have a look at this.
Thanks.
