### ISSUE TITLE
How to change where Next looks for pages?

### ISSUE THREAD

**Issue by bookercodes** [zeit/next.js#2202]
So, I am wanting to build a Next app with T$.

To do that, I install `typescript` and compile my Next app into a `bin` directory:

```
+ bin/
  + server.js
  + pages/
    + index.js
+ server.js
+ pages/
+ index.tsx
+ package.json
```

In `package.json`, I have a `script`: `node bin/server.js`. When I run said script, Next will look in `./pages` instead of `./bin/pages` (i.e. from the `cwd` not `__dirname`). To work around this, I have to `cd` into `bin` before running `node ./server.js` (a one-line would be `(cd ./bin && node ./server)`, if you're reading this and you need a work-around)

It it possible to configure where Next looks for pages?

**Comment by sergiodxa** [comment]
When you create your custom server you can pass a argument `dir` to next.

```
const next = require('next')
const dev = process.env.NODE_ENV !== 'production'
const app = require({ dir: './bin', dev })
```

Next.js it's going to use `./bin` to look for pages directory.

**Comment by bookercodes** [comment]
Ah, that is exactly what I was looking for but couldn't find in the docs 😢

**Comment by jonathanrz** [comment]
I followed the idea of specifying the dir property for the next app and it worked, thanks.

But when I run `yarn next build`, it crashes with the message: 

```> Couldn't find a `pages` directory. Please create one under the project root
error
Command failed with exit code 1.```

How can I specify the pages directory when running the build task?

**Comment by timneutkens** [comment]
Posted https://github.com/zeit/next.js/issues/8451
