### ISSUE TITLE
Styled-jsx doesn't work on withTypescript example.

### ISSUE THREAD

**Issue by Rokt33r** [zeit/next.js#2209]
https://github.com/zeit/next.js/blob/v3-beta/examples/with-typescript/tsconfig.json#L5

Styled-jsx seems to be able to convert JSX element only, not the compiled one, `React.create...`. So we lose styled-jsx if we set `"jsx": "react"` to tsconfig.json.

We can not use `"jsx": "preserve"` neither because its outputs become `*.jsx`, which next.js can not resolve now.

So, the only card we have `"jsx": "react-native"`, which preserves JSX element and outputs `*.js` file.

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2015",
        "jsx": "react-native",
        "allowJs": true
    }
}
```

Does it make sense?

**Comment by jclem** [comment]
I was also confused by this issue while working my way through https://learnnextjs.com. Setting "react-native" works for now, but seems like this should also work with `React.createElement`.

**Comment by lukemorton** [comment]
`"jsx": "preserve"` works for me but means my tests now fail as I'm running ts-jest which is no longer compiling JSX as you'd expect by setting to `"preserve"`.

**Comment by mrisoli** [comment]
I ran into the same issue, I have ```"jsx": "react-native"``` on my ```tsconfig.json``` file but using it with ```ts-jest``` fails with a ```SyntaxError: Unexpected token import```
