### ISSUE TITLE
Global styles in _document.js not loading on first render 

### ISSUE THREAD

**Issue by andrewwong97** [zeit/next.js#2210]
When I first load the site using `yarn dev` or `npm run dev`, all styles **except** the global ones defined in _document.js (layout) load well. 

After refreshing the webpage, the _document.js styles load fine.

Snippet from my package.json:
"dependencies": {
    "next": "^2.4.0",
    "react": "^15.5.4",
    "styled-jsx": "^0.5.7"
  }

Has anyone else encountered this issue? Is there a way to load these global layout styles first?

**Comment by timneutkens** [comment]
@andrewwong97 Are you using `<style jsx global>` in `_document.js`? That's what causing the issue. You can just use a normal `<style>` tag in this case.

**Comment by andrewwong97** [comment]
Will try, thanks!

**Comment by arunoda** [comment]
@andrewwong97 also remove styled-jsx from your `package.json`. Next will use the one inside it.
