### ISSUE TITLE
JSON-LD

### ISSUE THREAD

**Issue by LeeTwelve** [zeit/next.js#2213]
I want add structured data to head via json-ld:
`<script type="application/ld+json">
            {
              {
                "@context": "http://schema.org",
                "@type": "LocalBusiness",
                ...
              }
            }
          </script>`
But I have error:
`Invariant Violation: Objects are not valid as a React child (found: object with keys {@context, @type, address, image, description, name, priceRange, telephone, openingHours, url, logo, email, hasMap, geo, sameAs}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.`
How can I avoid render's this object?

**Comment by impronunciable** [comment]
Using `dangerouslySetInnerHTML`

```
<script type='application/ld+json' dangerouslySetInnerHTML={ __html: `{ "@context": "http://schema.org", "@type": "LocalBusiness", ... }`} />
```

**Comment by brandonmp** [comment]
cautionary tale: i tried to render some json+ld like a normal string, eg:
```
<script type='application/ld+json'>
    {props.schema}
</script>
````
it appeared to work perfectly on my site, when google scraped it, all quotes were transformed to `&quot;` & none of the data was parsed.
