### ISSUE TITLE
Question about with-apollo example

### ISSUE THREAD

**Issue by alexpriceonline** [zeit/next.js#2214]
Can I ask why the withData.js component has [`serverState: PropTypes.object.isRequired`](https://github.com/zeit/next.js/blob/v3-beta/examples/with-apollo/lib/withData.js#L10) in the with-apollo example?

I'm wrapping a child component with `withData()` and getting

```
Warning: Failed prop type: The prop `serverState` is marked as required in `WithData(Apollo(Component))`, but its value is `undefined`
```

Thanks

**Comment by timneutkens** [comment]
@ads1018

**Comment by ads1018** [comment]
@Rowno I noticed you added that prop type validation in your last pull request. Is there a reason that field is required?

**Comment by Rowno** [comment]
Because it's required for the server-side rendering and client-side rehydration. If you're getting a warning it means you broke something. 😉 

https://github.com/zeit/next.js/blob/v3-beta/examples/with-apollo/lib/withData.js#L55-L62

**Comment by ads1018** [comment]
^ @alexpriceonline

**Comment by alexpriceonline** [comment]
@Rowno Okay thanks. It seems to work fine (`dev` mode atlas) and I have it working in other places of my app without missing prop errors. I guess I'll close the issue and have a deeper dive into whats happening.

**Comment by hmontes** [comment]
I have the same error with "with-apollo-and-redux" example. Do you fix that issue?

https://github.com/zeit/next.js/tree/master/examples/with-apollo-and-redux

**Comment by atuttle** [comment]
@alexpriceonline would be nice if you circled back and posted the solution for anyone else that might wind up here from a search...

**Comment by alexpriceonline** [comment]
@atuttle I think the app I was building still gets the error but works fine! It's been a while since I worked on it so I can't really help more than that I'm afraid! :(

**Comment by notrab** [comment]
I get this error if I’m using withData inside my pages directly. 

If I wrap a component with withData and include that inside my page, I don’t get the error. Perhaps something that needs further looking into?

**Comment by jaqua** [comment]
I just removed the `isRequired` part. Don't know why it is necessary at all...

**Comment by dntrkv** [comment]
Fyi, removing the warning does not resolve the underlying issue. The `serverState` needs to be populated at the time of server rendering. If your app is working after removing the warning, you are probably not server rendering the data that's applied with `withData`

This is most likely caused by not applying the `withData` HOC are the right point like @notrab pointed out above.

**Comment by pramendra** [comment]
Issue:
warning occurs when integrating gql to a component 

Solution:
`withData` should be passed to  page component 

```
const enhance = compose(withData);
const Index = props => (
  <div>
    <EenhancedProductCarousel />
  </div>
);

export default enhance(Index);
```

**Comment by willmeierart** [comment]
for anyone visiting this page, since it's the first google result, a very clear answer to this issue is that you need to wrap your top level page in ```withData()```, and that's it. you can then wrap your down-tree child components in whatever ```compose()``` or other ```graphql()``` HOC's you want, as long as the page they are contained within is wrapped in ```withData()```

**Comment by ads1018** [comment]
Thanks @willmeierart. I should have been more explicit in the README about that. Feel free to submit a pull request to make that more clear.
