### ISSUE TITLE
incorrect docs

### ISSUE THREAD

**Issue by paulwehner** [zeit/next.js#2215]
According to https://github.com/zeit/next.js/issues/2094 the docs are incorrect here https://github.com/zeit/styled-jsx#keeping-css-in-separate-files and you can not keep separate CSS files. Docs should be updated if this is incorrect.

**Comment by timneutkens** [comment]
It's never mentioned in the next.js docs. With the next styled-jsx release we'll update it in next.js. @giuseppeg is working on it 👌 Thanks for reminding us though 👍
