### ISSUE TITLE
Authentication token storage with Server side rendering

### ISSUE THREAD

**Issue by cyrus-za** [zeit/next.js#2216]
I am using apollo with nextjs thanks to @ads1018's blog post about it. I am getting auth0 token back from the server upon login and need to store the token in the callback and then whenever the user refreshes the page, it should still have the user authenticated. So if the page is rendered server side, there's obviously no access to HTML5 localStorage. What's the best practice for getting that token across to nextjs server to have access to it upon SSR phase?

**Comment by ron-liu** [comment]
Check [153](https://github.com/zeit/next.js/issues/153)
Basically, I think it should be put in cookie as well. 

I actually have another question, if we put token into cookie, do we bother to put in local storage.  In most examples, token was put both in cookie and local storage.

**Comment by sedubois** [comment]
@ron-liu keeping localStorage might help for when using `next export`?

**Comment by ron-liu** [comment]
@sedubois yeah, make sense. I just noticed there is an option to run only on client side. :)
Is this the only reason?

**Comment by arunoda** [comment]
@cyrus-za I think as others mentioned, cookie is the best place to do this.
