### ISSUE TITLE
Any way to force an error in getInitialProps?

### ISSUE THREAD

**Issue by rongierlach** [zeit/next.js#2218]
Say show a 404 after a bad API response in getInitialProps.
I could use Router and push to a non-existent route like `/error` or something but I'd rather not force a second route change.

**Comment by coluccini** [comment]
You can do something like this:
```javascript
class Demo extends React.Component {
  static async getInitialProps({ res }) {
    // --> API CALL
    if (!apiResults) {
      res.statusCode = 404;
    }
    return { error: apiResults ? false : true  };
  }

  render() {
    const { error } = this.props;
    if (error) {
      return <Error404 />
    }
    return (
      <div>
        Component content
      </div>
    );
  }
}

export default Demo;
```

**Comment by arunoda** [comment]
Thanks @coluccini 
That's the same as what I had in my mind.

**Comment by sandric** [comment]
I don't think that answers the question, @rongierlach asked about routing and not rendering component on the same page. I found that this works for me:

```js
  componentDidMount() {
    if(this.props.error == 'unauthorized')
      Router.push('/users/signin')
  }
```
