### ISSUE TITLE
Consider making your examples public domain (CC0)

### ISSUE THREAD

**Issue by aickin** [zeit/next.js#2221]
Thanks for all your hard work!

As I read the project right now, the entire thing is MIT licensed, which is great. However, given that a lot of the examples folders encourage folks to copy the code of the example into their own project, it means that the license for their own project has to be MIT-compatible.

This is a bit restrictive IMO, especially for proprietary software, and it could impede folks wanting to use the examples. Would it be possible to add a license to the root of the examples folder making all the examples Public Domain, as it seems they are intended to be copied out to lots of different kinds of projects?

Thanks for all your work!

ETA: I also just noticed that the default instructions for copying an example folder as scaffolding breaks the current MIT license, since the copyright notice isn't copied over.

**Comment by arunoda** [comment]
I don't think MIT is restrictive license. You can nearly do anything with a MIT project.
If you consider about licensing, please download whole Next.js source and use the examples.
