### ISSUE TITLE
query undefined: getInitialProps

### ISSUE THREAD

**Issue by eashish93** [zeit/next.js#2222]
I need to access `query` prop on client side sent from `getInitialProps` method like this:

```js
// page.js
const Page = (props) => <div>Page No: {props.page}</div>
Page.getInitialProps = async ({query}) => {
  return {page: query.page}  // here `page` is set by server side routes 
}
```
The problem is when I go from homepage to that `/page` route, `props.page` returns undefined. But refreshing on same `/page`return page no. 
I know that because of `getInitialProps` render on server when moving from one page to another via `<Link>`.

So my question is there any way to access that `query` props on client.

**Comment by impronunciable** [comment]
@eashish93 `query` should work both in the client and the server. I set up an example to show that it works: https://page-arazpkvguj.now.sh

Maybe if you provide more context we can figure out why is it not working for you.

**Comment by eashish93** [comment]
Let us suppose there are two pages with the following code:
```js
    // index.js 
    // here `slug` can be deeply nested, eg: `/c/cat`, `/c/cat/dog/lion` etc...
    export default () => <Link href="/products" as={`/c/${slug}`}><a>Go to product Page</a></Link>
```
and 
```js
// products.js
const Page = (props) => (
<div>Page No (should not return undefined): {props.slug}</div>        
);
Page.getInitialProps = async ({query}) => {
    // some async code (or not)
    return {slug: query.slug, page: query.page}
}

```

In my server side (expressjs) code, I've the following custom routes:
```js
// .... other express code.
const nextjs = require('nextjs')({dev});
/// .....

app.get('/c/:slug*', (req, res) => {
    const pathname = req.params.slug + req.params['0'];     // will combine the whole slug: `/c/cat/dog/lion`
    const queryParams = {slug: pathname, page: req.query.page || 1};
    nextjs.render(req, res, `/products`, queryParams);
})

```

Now when I move from `index.js` via `Link` tag to `products.js`. `query.slug` and `query.page` print undefined in client side.
But works fine when directly refresh on `products.js` file.

**Comment by c0b41** [comment]
@eashish93 this not query

**Comment by eashish93** [comment]
Now I find the solution. The only way to make the `query` work on both client and server is by defining the same queries in link `href` attribute:
```js
// index.js 
// slug: `/cat/dog/lion`.
export default () => <Link href={{ pathname: 'products', query: {slug: slug, page: 1} }}
                                as={`/c/${item.link}`} prefetch>
        <a>Go to product Page</a>
</Link>
```
And then we can access `props.slug` directly. Also available via `props.url.query.slug`.

But I think this is a double work and needs to resolve.

**Comment by c0b41** [comment]
@eashish93 see https://github.com/zeit/next.js/tree/v3-beta/examples/with-url-object-routing

**Comment by eashish93** [comment]
@c0b41. Mistake: `query params` sent via custom server routing.
