### ISSUE TITLE
Error: Cannot find module 'setprototypeof'

### ISSUE THREAD

**Issue by paulwehner** [zeit/next.js#2226]
When I try and extend a Next.js project that started from the learnnext-demo repo and has this as the package:

    "next": "^2.0.0",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",

I get errors like the one in the title. Specifically, I tried to "npm install react-player --save" and after doing so, if I run "npm run dev" I get:

Error: Cannot find module 'setprototypeof'

Additionally, if I try and update the next, react or react-dom versions the project stops working.

**Comment by nkzawa** [comment]
I also experienced this with npm v5. In this case, try to install next.js by using `npm v4`.

**Comment by arunoda** [comment]
Try to use latest React version `15.5.x`

**Comment by elmasse** [comment]
I got that fixed by removing node_modules and the package-lock.json then running npm install again

**Comment by arunoda** [comment]
In the beta release, we'll look for version `15.5.x` of React.
So, this won't be an issue soon.
