### ISSUE TITLE
Error: spawn EACCES while following setup instructions for 3.0.0-beta12

### ISSUE THREAD

**Issue by jedrichards** [zeit/next.js#2228]
# Note from maintainers 
The temporary fix is to run `chmod -R u+x node_modules/next/dist/bin` thank you very much @jedrichards for surfacing this.
Please see https://github.com/zeit/next.js/issues/2228#issuecomment-307593716 for more information.

# Original issue
```sh
nvm use lts/boron
Now using node v6.11.0 (npm v3.10.10)
mkdir test
cd test
npm init --yes
npm install next@beta react react-dom --save
# Added dev/build/start scripts to package.json
# Added pages/index.js with basic contents
npm run dev

> test@1.0.0 dev /Users/jed/work/test
> next

internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:378:9)
    at spawn (/Users/jed/work/test/node_modules/cross-spawn/index.js:17:18)
    at startProcess (/Users/jed/work/test/node_modules/next/dist/bin/next:69:36)
    at Object.<anonymous> (/Users/jed/work/test/node_modules/next/dist/bin/next:90:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by Leeds-eBooks** [comment]
@jedrichards Any luck with this? I've just hit the same, trying to google around but not found anything useful yet.

**Comment by Leeds-eBooks** [comment]
Rolling back to `2.5.4` doesn't fix this.

**Comment by jedrichards** [comment]
Nope, no luck either. I've tried a few different Node versions too. This is my first time trying Next.js so a bit stuck ...

**Comment by Leeds-eBooks** [comment]
Found [this](https://stackoverflow.com/questions/34562496/gulp-error-internal-child-process-js298-throw-errnoexceptionerr-spawn-err), going to give it a try when I pluck up the courage. Not 100% confident with modifying file permissions.

**Comment by jedrichards** [comment]
Ah nice one. That fixed it for me.

Pretty sure we shouldn't have to be modifying permissions though. Maybe they've published some files with incorrect permissions to npm ...

**Comment by Leeds-eBooks** [comment]
Did you do it on the root of your project? Does `-R` apply only to files in the project?

**Comment by jedrichards** [comment]
```
chmod -R u+x .
```

Yeah, I just did it in the root. It recursively sets all files to be executable by the user in the current directory. I guess you wouldn't want to do that on a whole project though ...

Maybe just do the files in the `bin` directory and see if that works?

```
chmod -R u+x node_modules/next/dist/bin
```

**Comment by Leeds-eBooks** [comment]
That worked! Thanks for your help!

**Comment by jedrichards** [comment]
Boom! Thanks for yours! Well, I've leave this issue open since I think there's something to fix ...

**Comment by timneutkens** [comment]
@jedrichards what npm version are you using? 🤔

**Comment by Leeds-eBooks** [comment]
@timneutkens FYI I was using `yarn`

**Comment by Flaque** [comment]
I had just had this problem and I tried running:
`chmod -R u+x . ` and `chmod -R u+x node_modules/next/dist/bin`

but that did not work for me. But then, I updated to newest version using yarn with:

``` yarn add next@beta ```

and then that worked for me. Previously I was using npm (although not sure if that makes all that much of a difference).

**Comment by timneutkens** [comment]
Okay I can confirm that I can reproduce and it. It's only `next@beta`. The fix, as said is `chmod -R u+x node_modules/next/dist/bin`. I have contacted @arunoda to do a new release. Stay tuned 👍. I'll add the fix on the top of the thread.

**Comment by arunoda** [comment]
Published a new version: `next@3.0.0-beta13`.

This issue arise because I shipped `next@3.0.0-beta12` on windows. 
I didn't get the issue because I am using yarn.
Anyway, I hope now everything works well.

**Comment by timneutkens** [comment]
Confirmed, it's fixed.

**Comment by gfelot** [comment]
I follow the tutorial and I had this issue... A quick search for `NextJS Error: spawn EACCES` pointed out this issue.

The `chmod` cmd fix it but there is still a problem if we follow the setup.

**Comment by jabacchetta** [comment]
Also had the same issue with version 3.2.1 and the `chmod` command resolved it.

**Comment by nexdrew** [comment]
Just to be clear, it sounds like the original problem was a packaging issue that was fixed. The current problem is a bug specific to npm@5.4.0: https://github.com/npm/npm/issues/18324
