### ISSUE TITLE
404 page for pages/_Name.js files

### ISSUE THREAD

**Issue by graphan** [zeit/next.js#2230]
Hi guys,

Thank you for Next.js, it is awesome!

What I think could make it even more awesome is the convention to display 404 page for pages/_Name.js files. Of course, we could write custom routes for this, but I think that it might quite often case.

Let's imagine that we have the following structure of the project:

- components // we keep here reusable components
- pages
-- comments
&nbsp;&nbsp;&nbsp;&nbsp; index.js
&nbsp;&nbsp;&nbsp;&nbsp; _RepoInfo.js // not reusable component - just splited part of Comments page

What do you think about that? Does it make sense for you?

**Comment by timneutkens** [comment]
Recommended way to do this is creating `components/comments/repoinfo.js`. `pages` should only contain pages (routes). A good structure to follow is github.com/rauchg/blog

**Comment by graphan** [comment]
I take part in the really huge project where there are around 100 components. Keeping reusable and non-reusable components together is definitely not clean. Keeping non-reusable components next to appropriate page files would boilerplate significantly.
The advantage of Next.js
