### ISSUE TITLE
Getting Error: commons.js from UglifyJs Unexpected character '`' in Scoped stylesheets with PostCSS example

### ISSUE THREAD

**Issue by sepiropht** [zeit/next.js#2233]
Im getting the following error when trying to run now the Scoped stylesheets with PostCSS example
 > Failed to build on /tmp/ae7c98c0-1d8b-4ecc-a12d-7408247acb54 { Error: commons.js from UglifyJs
      Unexpected character '`' [commons.js:6271,91]

**Comment by arunoda** [comment]
This is happening when some of your imported NPM package contains some ES6 code.
UglifyJS doesn't work well with ES6.

Find that NPM module and use some other alternative.
To find that, you need to do it manually by removing code and so on.

**Comment by sepiropht** [comment]
Ok thanks i will check that

**Comment by sepiropht** [comment]
It is possible to desactivate uglifyJs ?

**Comment by arunoda** [comment]
Yes. Search this issue list. You will find the answer.
