### ISSUE TITLE
Can this work without the polling element?

### ISSUE THREAD

**Issue by Industrial** [zeit/next.js#2238]
Hi.

I am getting a request to `/on-demand-entries-ping?page=<pagename>` every 2 seconds. This is spamming my network tab in the browser (eventually locking it up due to endless amounts of requests!) and also on the server side it causes a lot of unneeded logging.

Is it possible to just use a WebSocket with push instead of using a Polling method with pull when stuff changes?

**Comment by frol** [comment]
What stops you from filtering those items out in the DevTools?

What server side logging do you refer to? `/on-demand-entries-ping` is a development-only feature (https://github.com/zeit/next.js/issues/2156#issuecomment-305956157), and I haven't seen any logs on the next dev console. If you see `/on-demand-entries-ping` on production build, that is a bug.

**Comment by arunoda** [comment]
I think we talked about this somewhere else.
As @frol mentioned, this is a dev feature. We will improve this over time.
