### ISSUE TITLE
HMR error with index.js

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#224]
We should reload with the existing `props`

**Comment by rauchg** [comment]
Actually this is not always the case. Need to come up with better reproduction instructions

**Comment by rauchg** [comment]
I found the issue: it's when using `index.js` which exports `something-else.js`, `something-else.js` has `getInitialProps` (which might or might not be related)

**Comment by nkzawa** [comment]
I'm not sure when this actually happens, but https://github.com/zeit/next.js/pull/268 might solve the issue.

**Comment by nkzawa** [comment]
Closes for now.
