### ISSUE TITLE
Promise not polyfilled correctly in IE11

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#2244]
In IE11, `Promise` is not defined in app.js and causes errors every page load:

<img width="423" alt="screen shot 2017-06-13 at 3 46 09 pm" src="https://user-images.githubusercontent.com/1754873/27067763-e6be6d14-504f-11e7-9c5e-18844ec16586.png">
<img width="455" alt="screen shot 2017-06-13 at 3 46 28 pm" src="https://user-images.githubusercontent.com/1754873/27067764-e6c612b2-504f-11e7-9394-1d810ada4540.png">

I don't think the global polyfill attempt [here](https://github.com/zeit/next.js/blob/dff20eae0137ee121c703733fbb87084a8cd86d3/client/index.js#L11) is working:

<img width="235" alt="screen shot 2017-06-13 at 3 51 19 pm" src="https://user-images.githubusercontent.com/1754873/27067838-35b4e5ce-5050-11e7-8a13-057f73968a90.png">

**Comment by jaydenseric** [comment]
You can reproduce the problem using the [with-custom-babel-config example](https://github.com/zeit/next.js/tree/master/examples/with-custom-babel-config) with `next@3.0.0-beta14`. There is no issue using `next@latest`.

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/pull/1344/files

**Comment by jaydenseric** [comment]
Will be a very happy camper once this is resolved; our testing is blocked and downgrading will re-introduce other issues.

**Comment by jaydenseric** [comment]
Narrowed it down a bit; `3.0.0-beta6` works and `3.0.0-beta8` doesn't.

**Comment by arunoda** [comment]
This should not be happening. But I'll check this.

**Comment by jaydenseric** [comment]
Found [the exact issue](https://github.com/webpack/webpack/issues/4916#issuecomment-303349812). The difference that caused it was [upgrading Webpack to 2.6](https://github.com/zeit/next.js/pull/2043/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R95). Maybe upgrading Webpack would fix it?

**Comment by jaydenseric** [comment]
Just noticed that for some reason the `webpack` entry [in package.json](https://github.com/zeit/next.js/blob/3.0.0-beta14/package.json#L96) is missing the `^`. This is locking it to `2.6.0` – the patch we need is [in `2.6.1`](https://github.com/webpack/webpack/releases/tag/v2.6.1).

**Comment by ritujain1000** [comment]
Seeing the same issue with webpack v3.4.1 in IE11.

ReferencedError: 'Promise is undefined' for verdor.js
