### ISSUE TITLE
remove data-reactid ?

### ISSUE THREAD

**Issue by paOol** [zeit/next.js#2248]
it seems the latest version of next is using `  "react": "^15.5.4" `  ,  I thought data-reactid was removed after version 15?

Is there an additional step to remove them?

**Comment by sergiodxa** [comment]
It was removed from client-side render, but not for server-side render, if you do it then React doesn't know how to re-use the current HTML and avoid rendering everything again.

**Comment by arunoda** [comment]
Thanks @sergiodxa for the answer.
