### ISSUE TITLE
No router errors in exported site

### ISSUE THREAD

**Issue by code2k** [zeit/next.js#2249]
There are no router errors in an exported site using next@3.0.0-beta14.

This happens on a fresh install with a single page containing a non-existing link.

When I click the link the router fires `onRouteChangeStart`, then the server responds with a 404 error and nothing happens.

`onRouteChangeError` is never called and the error document is never shown. The same happens also when clicking a link and a network error occurs.

**Comment by q-nishimura** [comment]
I think this has been fixed with https://github.com/zeit/next.js/commit/742fa6590c47bd83f2e13d80a423f1a834e54cd9#diff-c7ddf3ad46bcb0938d6043ea0393d554

**Comment by code2k** [comment]
Just did a quick test with the current next.js version (6.0.0) and it is indeed working now.
