### ISSUE TITLE
next build w/ --harmony?

### ISSUE THREAD

**Issue by iamdevonbutler** [zeit/next.js#2254]
I'm using node 8 w/ object spreads and "next build" doesn't seem to like it. Is there a way to run build and pass the --harmony flag?

**Comment by sergiodxa** [comment]
Next it's already transforming object rest and spread with Babel when you run `next build`
https://github.com/zeit/next.js/blob/v3-beta/server/build/babel/preset.js#L24

Do you have a custom `.babelrc` file? Check if you are loading the `next/babel` preset.

**Comment by iamdevonbutler** [comment]
I'm using the .babelrc file and the transform-define plugin to load a config file that is using object spreads. When I try to build it errors: "The nodePath: PATH is not valid." The error is gone when i remove the object spread. This particular use case is not important, I can easily not use object spread in the config file. This ticket was more of a question about passing harmony to build, which as a hunch, might have fixed it. feel free to close.

**Comment by arunoda** [comment]
I think your `.babelrc` messed up with something.
Try to use `next/babel` always.
We haven't experimented yet with using harmony and using features available in the browser.
But we should do it.
