### ISSUE TITLE
When installing next in a Koa server, building crashes with can't find module .next/build-stats

### ISSUE THREAD

**Issue by serle** [zeit/next.js#2255]
I have installed next in a sub directory of coa and set the dir option of next as a relative path from the root. I am getting an error when building and starting the Koa server. Error: Cannot find module 
'Development\koa-server\.next\build-stats.json'. I presume this has something to do with the directory variable. Any suggestions?

**Comment by geovanisouza92** [comment]
Did you called `.prepare()` on the next app instance?

**Comment by serle** [comment]
No, is there any documentation on that? let me try

**Comment by geovanisouza92** [comment]
https://github.com/zeit/next.js/tree/v3-beta/examples/custom-server-koa

**Comment by serle** [comment]
@geovanisouza92 thx that has worked to an extent
