### ISSUE TITLE
Is there an easier way to define a language for the page?

### ISSUE THREAD

**Issue by oliverjam** [zeit/next.js#2256]
Just started using Next and it's been a blast so far, thank you!

I may be missing something, but there doesn't appear to be an obvious way to add a `lang` attribute to `<html>`. ~~My demo app keeps getting Google Translate pop-ups because Chrome thinks the page is in French...~~ This appears to have nothing to do with `lang`

I assume I could manually do this by extending the `<Document />`, but that seems like a lot of hassle just to get `lang="en"` in there. This attribute is also [quite important for accessibility](https://www.paciellogroup.com/blog/2016/06/using-the-html-lang-attribute/), so should probably be there by default.

**Comment by sergiodxa** [comment]
You need to create a custom `pages/_document.js` to do that. It's not a good idea for Next.js to think that every page it's in english, so you need to do it manually with your app/site language. Or if you use react-intl and similar set the loaded locale.

**Comment by oliverjam** [comment]
@sergiodxa Thanks. I don't think Next should assume every page is in English, but since every page does need a `lang` the fact that users will have to create their own `<Document />` should probably be emphasised more in the docs. Otherwise I imagine there will be lots of apps out there without a language set.

I also notice my page has no `<title>` by default either. Is the recommendation for this also to create a custom `<Document />`?

**Comment by sergiodxa** [comment]
Yeah, it's not documented that you must create a custom Document, but I saw many websites without it sadly, eg [zeit.co](https://zeit.co).

About the title, you can use `next/head` to set elements in the `<head>` tag.

```js
import Head from 'next/head'

export default () =>
  <main>
    <Head>
      <title>An awesome page</title>
    </Head>
    <h1>the title in the body</h1>
 </main>
```

You will need to do that in every page, you can also set a `<title>` in any component, that way when a specific component is rendered you can change the page title. Also can set a `<title>` in your custom document to define a default one.

**Comment by quentin-sommer** [comment]
the `<Head>` component collect its children everywhere you use it in your components and then outputs them in the `<head></head>`, so you can use it for all tags that go in `<head>`.

For tags that go on `<html>`  you have to use the `_document`.

**Comment by timneutkens** [comment]
Both are fairly well documented in the readme 👍 I don't think learnnextjs.com mentions them though :)
