### ISSUE TITLE
`next start` signals won't be handled properly

### ISSUE THREAD

**Issue by wangkechun** [zeit/next.js#2257]
![image](https://user-images.githubusercontent.com/4022174/27112246-67f4fb6c-50e8-11e7-8378-fccab2bdbfc8.png)

**Comment by wangkechun** [comment]
In the production environment using [supervisorctl](http://supervisord.org/index.html) to deploy, `supervisorctl restart` will produce a zombie processes ,
`node_modules/next/dist/bin/next-start` is ok.

**Comment by timneutkens** [comment]
Should be handled here https://github.com/zeit/next.js/blob/bf0d7f8b401b1e5b650cbbf73d3620f370ac05a7/bin/next#L60-L80 right? 🤔

**Comment by timneutkens** [comment]
@wangkechun

**Comment by wangkechun** [comment]
Maybe yes

**Comment by timneutkens** [comment]
I'm going to close this as we haven't run into this and there's not enough information to come to a solution.
