### ISSUE TITLE
Next build when run inside outer Koa project picks up Koa .babelrc and crashes

### ISSUE THREAD

**Issue by serle** [zeit/next.js#2258]
When running next build inside my Koa project, it picks up the .babelrc file for the Koa project instead of using its own internal babel configuration. It then fails to build the client files and crashes. If I rename my .bablerc file to something else it builds fine using its own internal file. I do need to keep the Koa .babelrc file to enable me to use async functions etc. in my outer koa environment.

Additionally, I'm not sure if the build option is correct to use in development. I see all the development scripts seem to assume next is a stand alone server. Is it possible to have next-dev-no-server and next-build-no-server scripts.

**Comment by sedubois** [comment]
https://github.com/zeit/next.js#customizing-babel-config

**Comment by albinekb** [comment]
You should separate your frontend (next.js) and API Backend (Koa).

**Comment by serle** [comment]
@albinekb  tried to separate them initially but I ran into problems with the working directory, so reverted (but I think the problem was elsewhere so will try again. 

@sedubois I tried to use the presets but they did not seem to work, the next build crashed, when I tried that, however do I need to download the next/babel npm, if so I could not find it.

Finally my workaround is to edit next/dist/server/build/find_config.js and either set filename=null or babelrc: false. It would be nice to expose the bablerc flag in the next.config option, or get the preset approach to work corretly

**Comment by serle** [comment]
I moved next into its own sub-directory with its own package.json and without a .babelrc file, in order to ensure that the working directory for the next build was contained. The build continued to fail until a put a  .babelrc file in the next sub-directory. From the babel documentation, babel will recursively search up the directory structure untill it finds a .babelrc file to use. So even though I was trying to isolate next in its own directory it was inadvertantly using the Koa .babelrc file. 

Please add this into the documentation to assist others.  

I also feel that next should be split into two packages one with the core and one with its own server. This would streamline it to be run in a higher-level container.

**Comment by timneutkens** [comment]
> I also feel that next should be split into two packages one with the core and one with its own server. This would streamline it to be run in a higher-level container.

In what case would this make sense? Do keep in mind that we have hundreds (maybe thousands looking at the stars) of users who all have very different use cases 😄

FYI:
When you add a `.babelrc` to the next.js directory (or above) with the following content, it'll automatically use the default babelrc:

```
{
  "babelrc": false
}
```

We had this exact usecase for the examples directory: https://github.com/zeit/next.js/blob/v3-beta/examples/.babelrc 👍

If you feel it's valuable to add that to the readme feel free to send a pull request 👌 

Thanks for the feedback! 🙏

**Comment by serle** [comment]
Happy to create a pull request, never done so before but willing to try.

My use case is the followings (chip in if you have other suggestions):
1) I need to redirect to https. (middleware required)
2) I need to split the site into a private area and public area and do an oauth process. (more middleware, with session etc)
3) I need to install a graphql server on one of the routes, I also want compression on the graphql side (more middleware)
4) I want to use next to build a more progressive web app. I have extensive experience with SPA react and want to leverage my skill and existing components to be in a position to tune the startup time of some of my components. I'm probably not as sold as you guys on extensive SSR everywhere, but I realise for some of my react component it makes absolute sense for a first render. I'm looking for an isomorphic experience in this regard, so I can experiment.
5) I will need to pass my session object into the next.render() method so the components can use the information to do graphql queries for data and also render in the right language/locale etc. which is stored in my session object. 

From a container perspective it would be nice to be able to pass the already parsed request and response objects into next.render or even the koa context itself without reverting the the low level req and res objects. 

Finally recognition of properties i.e. additional parameters to the render method, (ideally treated as react properties) flowing from the container wrapper down into the next/react page component. 

It feels as though running next in a container is more of a hack at the moment, but I think next should keep the focus on the react progressive web app side and making it easier to integrate into the three main node servers i.e. express koa, hapi. This would be similar to the approach taken by the graphQL server libraries which have variants which play nicely with the above mentioned servers

I'm sure you've heard all these cases before, so I hope this helps.

**Comment by timneutkens** [comment]
These are all issues you get from wanting to build a monolith application with Next.js. Like @albinekb  pointed out earlier (https://github.com/zeit/next.js/issues/2258#issuecomment-308439695) you'll want to separate the frontend and backend. Think of Next.js as a frontend server, it should only be responsible for rendering html based on api calls to an external api. The custom server (programmatic) api is provided to let you handle custom routing and caching.

**Comment by arunoda** [comment]
@serle using babel for server is kind a tricky. Since it might mix with next's client side (and ssr) babel config. 
We want to fix it but it's complicated. And currently you can hack with babel by using different environment and using custom config for each.

Anyway, this is how I'd deal with this problems like this:

* I use Node 8 for the server and I got all the new features except import / export
* And I use cookies for authenticating on the server and client. (See [sample app](https://github.com/arunoda/coursebook-ui/blob/master/server.js))
* Always try to use a separate server for data apis and communicate them with HTTP (or WS) 

> Anyway, here the original issue is babelrc is getting mixed up with the server. It's true and it'll hard to fix without making our babel config complex.
> We don't want to address it right now.
> So, I suggest to use Node 8 for the server.
