### ISSUE TITLE
Issue with nesting index.js into folder 

### ISSUE THREAD

**Issue by oliviertassinari** [zeit/next.js#2261]
I have noticed an issue with the HMR feature in the following configuration.
We have a **full page reload instead of a hot reload** when working on the root `/` route.

Still, It's working find for the `/signin` route or when renaming `pro/index` into `pro/homepage`.

- **folder structure**:
```
pages/
├── _document.js
├── _error.js
├── admin
│   ├── index.js
│   └── signin.js
└── pro
    ├── index.js
    └── signin.js
```

- **[next-routes](https://github.com/fridays/next-routes) config**:
```js
import nextRoutes from 'next-routes'

const routes = nextRoutes()
routes.add('pro/index', '/')
routes.add('pro/signin', '/signin')

export const Router = routes.Router
export const Link = routes.Link

export default routes
```

*P.S: regarding why nesting the pages, the answer is subdomain handing.*

**Comment by arunoda** [comment]
Could you send me a sample repo and clearly describe the error a bit more?

**Comment by oliviertassinari** [comment]
Given how simple the fix is, I'm not sure I want to spend more time on that issue. I have raised it at it may sounds something trivial to fix for someone knowing the code base. Still, I could submit a new examples PR to show how people can handle subdomains with next.

**Comment by timneutkens** [comment]
@fridays I'm not sure if it's related to next-routes. But do you have any idea? 😄

**Comment by fridays** [comment]
I can't reproduce, maybe it's related to the subdomain setup? A sample would be great.

**Comment by oliviertassinari** [comment]
Yeah, will work on a reproduction as this setup seems to no longer work with the v3-beta. I need to sort that out.
