### ISSUE TITLE
styled-jsx psuedo selectors broken

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#2264]
They are fixed in version `1.0.4` (`1.0.5` latest). Next. `2.4.3` still uses styled-jsx `1.0.3`. Can we upgrade, or is there way for me to upgrade just this piece of next early? I tried installing 1.0.4 locally and it does not seem to be used automatically over 1.0.3.

https://github.com/zeit/styled-jsx/releases/tag/1.0.4

**Comment by timneutkens** [comment]
Right now `next@beta` has 1.0.5 👍 cc @arunoda guess we should do a new release of next.js stable too, cause there's a lot of bugfixes in 1.0.5 afaik 👍

**Comment by khrome83** [comment]
I installed 1.0.5 inside the next folder within `node_modules` and confirmed this resolves the issue. I just need that on the stable branch. Should I do a PR?

**Comment by khrome83** [comment]
Opened PR to resolve this - #2275

**Comment by timneutkens** [comment]
Thanks @khrome83 ❤️
