### ISSUE TITLE
How can I get next to serve out it _next link resources when embedded in a Koa server

### ISSUE THREAD

**Issue by serle** [zeit/next.js#2273]
These resources are required: 

GET /_next/1497539794531/page/about 
GET /_next/1497539794531/page/_error. 
GET /_next/1497539794531/manifest.js 
GET /_next/1497539794531/commons.js 
GET /_next/1497539794531/main.js 

Is there another call besides the render call that I should be using when I detect a _next/ route

**Comment by serle** [comment]
This problem is actually more general and happens when serving any static resources from next on a windows 10 platform, when next is embedded in another server. Should I re-log under a different heading?

**Comment by arunoda** [comment]
@serle I'm not sure we handle these requests and it works well in express.
But you can manually handle them in `_next/` too.

Could you send me a sample repo, where I can have a look at this?
