### ISSUE TITLE
custom route not working in production

### ISSUE THREAD

**Issue by sepiropht** [zeit/next.js#2277]
I have this test-project [https://github.com/sepiropht/pinterest-next-js](url), in dev it working like expected but when i build my project, and start it,  my app start, but my customs route like /api/images /api/user don't respond ... Any idea ? 
Thanks

**Comment by sergiodxa** [comment]
You are using `next start` instead of running your custom server with `NODE_ENV=production`.

**Comment by sepiropht** [comment]
Ok thanks i missed that

**Comment by sepiropht** [comment]
i'am one half year experience in js, and start react recently. If you have time could you look at globally and briefly on my poject and give me your feelings. The view is ugly i know already that !
