### ISSUE TITLE
Issue with router and Storybook

### ISSUE THREAD

**Issue by hlandao** [zeit/next.js#2284]
When trying to use Stroybook together with NextJS, I'm running into an issue that router is missing because Storybook only renders the component.

`No router instance found. You should only use "next/router" inside the client side of your app.`

I still want to use `next/link` because I think it's better practice.
How would you suggest to bypass the issue with Storybook.

Thanks!

**Comment by arunoda** [comment]
Check this: https://github.com/zeit/next.js/issues/1827#issuecomment-306740374

It's for Jest. But the root cause is the same.
