### ISSUE TITLE
Show stacktraces with proper line numbers in src rather dist (SSR)

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#2285]
Currently when there's an error, it shows the line numbers of the `dist` version of the file.
We need to use sourcemaps or something other way to clearly show the correct file and the line number.

**Comment by ldthorne** [comment]
Hey @arunoda! Really excited about this as a feature. What kind of complexities and challenges do you see in its implementation?

**Comment by arunoda** [comment]
@ldthorne this is kind a pretty hard as v8 doesn't support this by default.
If someone could help us in anyway, that'd be great.

**Comment by kpdecker** [comment]
I have a bit of experience making this work in various node environments. Will take a crack, time permitting.

**Comment by timneutkens** [comment]
That's amazing @kpdecker ❤️
