### ISSUE TITLE
Enhancement: Provide HMR and ping handlers for next run in a container server.

### ISSUE THREAD

**Issue by serle** [zeit/next.js#2288]
Please could you expose handlers for `/_next/on-demand-entries-ping` requests and `/_next/webpack-hmr` requests so that an outer server can respond properly during development. If the container matches the pattern then it should be able to route these requests down to next for a valid response.

**Comment by arunoda** [comment]
Hmm. I am quite not sure about the question.
These urls are just like urls of you page. What went wrong?
Could you give us more info.

**Comment by serle** [comment]
I'm running next in a Koa server on windows10 (dev environment). I had a router that matches on anything with an /_next url and passes it onto to the next server to resolve by calling next.render() in the same way I call it for standard next page "components". What I am noticing (after debugging into next code) is that the underlying send call that next uses to serve static resources is not working (for my environment), so all the _next calls come back to the browser with GET 404 failures, while my index component page renders perfectly. Note these same `_next` calls work when next is running standalone i.e. not embedded in a koa server.

So I tried to use the koa-send library (a duplicate of the send library next is using) to duplicate what next is doing for the _next script url's. This did not work either, even though I have the underlying file path perfect. When I serve the same script files using fs.readFile, I get the script files across the browser correctly. Which only leaves the need for the  `on-demand-entries-ping` and `webpack-hmr` calls to be sorted out (as a work around). 

Not sure how to tackle this, but I think the underlying problem is with the send call in the underlying serverStatic next function.

**Comment by arunoda** [comment]
I'm not exactly sure what you are trying to do. But all these are dev stuff. So, I don't think you need such a complex setup for dev.

If you need that, I hope redirecting(302) those routes would do the trick.

Anyway, we don't have a plan to expose a specific API for these.

**Comment by serle** [comment]
I use Server-side OAuth which handles a minimal set of routes to set up a session object and passes all the other requests down to next to handle rendering responses. I need to be able to test the entire sign-up process and logon process in dev and obviously make changes where necessary. I am currently not able to test the whole end-to-end process because of the problems with next serving out ANY of its static resources. If this has been fixed, what version of next should I download and retest on?
