### ISSUE TITLE
very minor documentation issue

### ISSUE THREAD

**Issue by sw-yx** [zeit/next.js#2291]
bug in the docs:

https://learnnextjs.com/basics/fetching-data-for-pages/fetching-data-for-pages
![image](https://user-images.githubusercontent.com/6764957/27241930-d05e1438-52a8-11e7-8c8b-e8466478207f.png)

**Comment by impronunciable** [comment]
@sw-yx thanks for reporting but the repo for learnnextjs is https://github.com/arunoda/learnnextjs-content

**Comment by sw-yx** [comment]
ok cross reported. thanks for the link
