### ISSUE TITLE
Any way to bust client side cache?

### ISSUE THREAD

**Issue by OutThisLife** [zeit/next.js#2292]
I have a unique situation I guess. I'm fetching JSON from a service, and I've confirmed that `fetch()` and the API itself is updating whenever a certain value in the JSON changes.

However, Next is still rendering the 'old' data despite the fresh data being updated in redux. I'm assuming this is some sort of client side cache?

**Comment by sergiodxa** [comment]
Next.js doesn't have client side cache, are you sure your store it's being updated?

**Comment by OutThisLife** [comment]
Hmm. It is, but now that I know that I'll dig deeper into my codebase.

**Comment by fabe** [comment]
I have this issue as well, except when client-side caching is disabled. Seems like the props don't update. Did you find a solution?
