### ISSUE TITLE
SSR: Failed requests to load main.js, manifest.js etc

### ISSUE THREAD

**Issue by obfuscatedgeek** [zeit/next.js#2298]
I have a very basic implementation of SSR next.js with redux-saga at https://github.com/obfuscatedgeek/next.js-with-redux-saga.

The app works fine but I see multiple failed requests in my browser. Attaching the image

<img width="647" alt="screen shot 2017-06-18 at 02 05 38" src="https://user-images.githubusercontent.com/322543/27257241-fff3ff4c-53ce-11e7-9380-ee1edb09ace7.png">

I am using custom-routing for displaying pages.

How do I get rid of these ?

Thanks.

**Comment by arunoda** [comment]
This is happening because of you set the statusCode = 404 when rendering the `/_error` route. For now, just remove the statusCode and run your app.

Here's the core fix I did: https://github.com/zeit/next.js/pull/2299

**Comment by obfuscatedgeek** [comment]
@arunoda thanks for the quick response. Works like a charm!
