### ISSUE TITLE
console keeps refreshing; errors disappear

### ISSUE THREAD

**Issue by hchoriq** [zeit/next.js#2305]
It is very hard to debug a lot of app errors because the console keeps refreshing. Is there any way to disable that?!

**Comment by albinekb** [comment]
In chrome you can use the "Preserve log" option: ![image](https://user-images.githubusercontent.com/5027156/27263900-c3bb4f08-5473-11e7-92f1-a7b75194c76f.png)

**Comment by arunoda** [comment]
Yes. We need to stop reloading.

**Comment by radum** [comment]
The same happens in the console once you run dev. If you use the express server alternative, any server error will be cleared once a route compiles ok.

**Comment by hchoriq** [comment]
I'm using express server alternative, yeah.

**Comment by arunoda** [comment]
Here's the fix for this: https://github.com/zeit/next.js/pull/2437
