### ISSUE TITLE
Close old milestones

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#2308]
This is a petty housekeeping issue, but there are a few outdated milestones still open that can be closed.

This will reduce confusion for people exploring the current state of Next.js.

<img width="990" alt="screen shot 2017-06-19 at 11 31 00 am" src="https://user-images.githubusercontent.com/1754873/27266465-e4378244-54e4-11e7-8ea9-e69c95e8d93c.png">

**Comment by arunoda** [comment]
Good point thanks.
