### ISSUE TITLE
Repo with examples

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#231]
There's a Redux example in the wiki but that's not really a proper place for code as we can't do code reviews, suggest improvements etc. Would it make sense to have a "next-examples" repo similar to the [now-examples](https://github.com/now-examples)? Or having an examples folder within this repo? [Nextgram](https://github.com/zeit/nextgram) could move there too.

**Comment by impronunciable** [comment]
We acknowledge that. @rauchg is prepping a repo with examples like nextgram or the auth one

**Comment by Florian-R** [comment]
Any reason to prefer a repo over [this directory](https://github.com/zeit/next.js/tree/7f0f3ae940f85d274b5d1a9307cf7c24a3df9950/examples)?

**Comment by pborreli** [comment]
@Florian-R maybe for being able to fix things on those examples repos without the need of updating next.js lib

**Comment by sedubois** [comment]
As mentioned all examples are being added to the [examples](https://github.com/zeit/next.js/tree/master/examples) folder which I think is nice.

I just still wonder then why Nextgram is in a separate repo, shouldn't it move to the examples folder too?

**Comment by timneutkens** [comment]
@sedubois Nextgram is an example of a more complex app. Same with next-news. Closing this one ❤️.
