### ISSUE TITLE
AMP does not allow the attribute 'as' appeared in tag 'link rel='

### ISSUE THREAD

**Issue by garfieldduck** [zeit/next.js#2310]
When running the `with-amp` example, the AMP validator shows errors `The attribute 'as' may not appear in tag 'link rel='`.

The errors are related to the following lines generated by the <Head> component automatically:
```
<link rel="preload" href="/_next/1497861989817/page/" as="script"/>
<link rel="preload" href="/_next/1497861989817/page/_error/index.js" as="script"/>
<link rel="preload" href="/_next/1497861989817/manifest.js" as="script"/>
<link rel="preload" href="/_next/1497861989817/commons.js" as="script"/>
<link rel="preload" href="/_next/1497861989817/main.js" as="script"/>
```

**Comment by impronunciable** [comment]
@garfieldduck The validator is passing for me. Just to confirm I deployed the example as it is on https://with-amp-hiwywerbxd.now.sh (and it's validating) 
![screen shot 2017-06-23 at 3 24 35 pm](https://user-images.githubusercontent.com/165799/27495396-18e08680-5828-11e7-9867-faf8cdfd2589.png)

Have you modified the example?

**Comment by garfieldduck** [comment]
@impronunciable Could you let me know which version of nextjs are you using?
Because I used `next@3.0.1-beta.1` and `next@2.4.4`, and both of them produced AMP errors as follow:
<img width="690" alt="screenshot 2017-06-26 18 03 53" src="https://user-images.githubusercontent.com/1139698/27534528-e28b6cc0-5a99-11e7-9ac1-f9a3d589a7c7.png">

The errors seem to be generated by the following code (in [/sever/document.js](https://github.com/zeit/next.js/blob/v3-beta/server/document.js)):
```
 <link rel='preload' href={`${assetPrefix}/_next/${buildId}/page${pagePathname}`} as='script' />
 <link rel='preload' href={`${assetPrefix}/_next/${buildId}/page/_error/index.js`} as='script' />
```

**Comment by korneel** [comment]
@garfieldduck I'm having the same issue.

**Comment by timneutkens** [comment]
@impronunciable could you have a look?

**Comment by impronunciable** [comment]
@korneel this is the code https://with-amp-hiwywerbxd.now.sh/_src
and the next version is `2.1.1`. I'll take a look using next 3

**Comment by impronunciable** [comment]
I see the issue. Besides the `charSet` that I'll update there is a bigger issue with the `Head`. If we change `Head` for `head` then the components are not capable of setting important tags like the page title. This is because of the preloaded scripts automatically injected

**Comment by AdamBroos** [comment]
In _document.js
I changed <Head> to <head>, <meta charset='utf8' /> to <meta charSet='utf8' />.
And the page passed AMP validation.

**Comment by heylookalive** [comment]
Just gave this a go - the head tag is rendered properly as lower-case, though the page produced isn't valid due to the "as" attribute on the link tags as originally reported. On Next `3.2.2`.

**Comment by timneutkens** [comment]
Going to close this as it's almost a year old. We're going to improve AMP support soon.
