### ISSUE TITLE
Enhancement Request: add session parameter onto the end of the next.render() method

### ISSUE THREAD

**Issue by serle** [zeit/next.js#2321]
Could we add a session object to the next.render() method, so that an outer server can pass session information through to page components rendered with next. That way we can keep session/cache management outside the next environment and have it exposed as either an additional property or a set of additional destructured properties for usage within the page component

**Comment by dnakov** [comment]
You can already do that by just attaching it to `ctx.req.whatever` like you'd normally do with express/connect/etc

**Comment by serle** [comment]
That's what I have done as a work around, but I think it much clearer to pass it down on its own parameter. In Koa the session is on the ctx and not on the request, as the session object is something that is not sent by the user, but is materialized on in the server.

**Comment by arunoda** [comment]
I think you need to stick with what @dnakov mentioned.
