### ISSUE TITLE
I get 404 error in my browser when trying to load assets

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#2327]
I don't know why my browser cannot find these path. I'm facing this issue since yesterday. I can't find a solution.

`Error GET http://localhost:5002/_next/a020c586-9e9e-4a64-9cfb-1a6dd8232b1e/page`

`Error GET http://localhost:5002/_next/77863f38-3739-407b-9739-959562b6cd27/page/_error `

`Error GET http://localhost:5002/_next/95f1845c1ef003b80b360d9b9c2498a7/app.js `

Thanks for helping

**Comment by royrijkers** [comment]
i also have an app.js error :(

**Comment by arunoda** [comment]
If you using a custom server, this could be the issue: https://github.com/zeit/next.js/issues/2298
It has been fixed and I'll to do a new beta release today.

**Comment by jackmatrix** [comment]
In fact , my issue is explained deeper [here](https://medium.com/google-cloud/server-side-rendered-react-on-google-cloud-functions-8b51b2b0878c)

However, in my case (localhosted app) i can't use fastly . my functions aren't yet been deployed but only available locallly.

Any idea ?

**Comment by royrijkers** [comment]
@jackmatrix , did you find a way to solve this?

**Comment by royrijkers** [comment]
@arunoda I tried beta16 also without success.

I checked if i set the 404 status when rendering the _error page but i could not find that.

my repo is here: https://github.com/royrijkers/next-test

when i run this locally it runs fine, but when i deploy on Digitalocean using a Nginx reverse proxy it does not. nginx is setup as instructed here: https://github.com/zeit/next.js/wiki/Deployment-on-Nginx's-reverse-proxy

this is the error:

![image](https://user-images.githubusercontent.com/4340039/27440078-89eeee60-5761-11e7-8ef7-12e2148aa722.png)

Can you please help me?

**Comment by arunoda** [comment]
This is seems working to me very well locally with production build. So, I think something with the nginx config.
Unfortunately, I don't know much about this.
