### ISSUE TITLE
Win 10 Reload Support

### ISSUE THREAD

**Issue by IanMitchell** [zeit/next.js#2328]
Just curious how many previous versions of Windows 10 you want to support? I [added this a while ago](https://github.com/zeit/next.js/blob/v3-beta/server/hot-reloader.js#L175) and I don't believe it's needed anymore - if you're fine supporting Creators Update on, I can run some tests and see if it can be removed.

**Comment by arunoda** [comment]
@IanMitchell That would be great. May be we could detect windows 10 specifically and disable this on it.

**Comment by IanMitchell** [comment]
Ok, I'll poke around Saturday and see what I can do!

**Comment by arunoda** [comment]
Superb.

**Comment by IanMitchell** [comment]
Merged in, closing
