### ISSUE TITLE
Is there a way to exclude specific pages from production build

### ISSUE THREAD

**Issue by jpbourgeon** [zeit/next.js#2332]
I find it useful to have a sandbox to test spike solutions and features before integration in my codebase.

Can you think of a way to exclude specific pages at build time ?

Would it be an interesting added feature to the framework ?

This could be defined in next.config.js

**Comment by timneutkens** [comment]
You can't really exclude them. But you could render a 404 page in getInitialProps. We don't have short term plans to add this feature cause you can lock down the pages using the programmatic (custom server) api.

**Comment by sergiodxa** [comment]
You can also [create a HOC](https://github.com/zeit/next.js/tree/v3-beta/examples/with-higher-order-component) `onlyDevelopment` and conditionally render your page if `NODE_ENV === 'development'` and render a 404 if it's production.

**Comment by jpbourgeon** [comment]
There are solutions in issue #746 too

**Comment by jpbourgeon** [comment]
My solution :

__Server side (expressjs)__
```js
Router.route('/sandbox').get((req, res, next) => {
  try {
    if (process.env.NODE_ENV === 'development') {
      handle(req, res);
    } else {
      NextApp.render(req, res, '/_error');
    }
  } catch (err) {
    next(err);
  }
});
```

__Client side__
```js
  static async getInitialProps() {
    const showSandbox = (process.env.NODE_ENV === 'development');
    return { showSandbox };
  }

  componentWillMount() {
    if (!this.props.showSandbox) {
      Router.replace('/_error', '/sandbox');
    }
  }
```
