### ISSUE TITLE
Add config support to export project with custom path prefix

### ISSUE THREAD

**Issue by moarwick** [zeit/next.js#2335]
Currently, `next export` generates files assuming absolute paths. This is problematic when the static site is pushed to a sub-folder, e.g. Github Pages. 

For example, if I push my `my-project/out` folder to a `gh-pages` branch, then access it at `https://user.github.io/my-project/`, the page is looking for assets at `/_next/...`, for example `href="/_next/a3c4359f-2b55-4680-b981-dfddcf84cea4/page/index.js"`

To solve the problem, I think we want to be able to specify a custom path e.g. `/my-project`, so then  it would look for assets in `/my-project/_next/...`

**Comment by sergiodxa** [comment]
You already can do that using [assetPrefix](https://github.com/zeit/next.js#cdn-support-with-asset-prefix) configuration. Just add that key to your `next.config.js` and set `/my-project` if you are running on production, that way when running `next build` you will have `/my-project/_next/...` and in development you will use `/_next/...`.

**Comment by arunoda** [comment]
@moarwick deploying any Next.js app into a sub directory is kind a tricky. We'll address this after 3.0
