### ISSUE TITLE
compression js with nodejs

### ISSUE THREAD

**Issue by ckken** [zeit/next.js#234]
1 i want to compression the js with node and cache it；
2 how cant i use server node in next

**Comment by mikecardwell** [comment]
1. Compression is the job of the web server
2. It is not clear what you're asking

**Comment by nkzawa** [comment]
You mean enabling gzip compression for the js file ? 
It sounds related to https://github.com/zeit/next.js/issues/243

**Comment by ckken** [comment]
@nkzawa yes

**Comment by impronunciable** [comment]
This is addressed on #555 and #622 thanks for reporting!
