### ISSUE TITLE
Option to disable hot code reloading and use full reload

### ISSUE THREAD

**Issue by fabien-h** [zeit/next.js#2341]
Hot code reload is awesome.

But I’m working on a app that uses the canvas a lot for the next month. I have to reload manually all the time. Is there a way to full reload the page each time we save ?

**Comment by arunoda** [comment]
Currently we don't provide that.
But you can play with the webpack config and do something: https://github.com/zeit/next.js#customizing-webpack-config

**Comment by IhostVlad** [comment]
Is there any way for disable HMR at all? Maybe building bundles at first run and then don't touch it anyway. Unfortunately, preliminary build and run in production mode is not applicable.
Any solution, except implicit next.js library code patching, is appropriate. Thanks in advance.
