### ISSUE TITLE
Undesired character encoding in style / head

### ISSUE THREAD

**Issue by fabien-h** [zeit/next.js#2342]
When using `next/head`, I add :

    font-family: "Arial";

In a `<style>` tag. And I get

    font-family: &quot;Arial&quot;;

In my end source.

**Comment by timneutkens** [comment]
This is due to React escaping, you can use https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml to insert unescaped html, or in this case it's probably better to use styled-jsx like this:
```
<style jsx global>{`
   body {
     font-family: "arial";
   }
`}</style>
```

Note that this has to be **outside** of the `<Head>` (next/head) tag
