### ISSUE TITLE
Should I avoid styled-jsx if I want a universal/isometric web app?

### ISSUE THREAD

**Issue by tomsoderlund** [zeit/next.js#2343]
From [next.js readme](https://github.com/zeit/next.js/blob/v3-beta/readme.md):

> We bundle styled-jsx to provide support for isolated scoped CSS. The aim is to support "shadow CSS" resembling of Web Components, which **unfortunately do not support server-rendering and are JS-only**.

Does this mean I should not use `styled-jsx` if I want a universal/isometric web app?

**Comment by hawkins** [comment]
Maybe I misunderstand your question, but the readme is discussing an issue with Web Components, not styled-jsx. In other words, it's basically saying "Web Components shadow CSS doesn't support universal rendering, so we bundle styled-jsx to fill that role."

You're totally fine to use styled-jsx for server-rendering or universal apps

**Comment by nndung179** [comment]
You can use it in server-rendering. But there are several things you should consider:
+ If your style is too large => your page size is going to be increased. That means the time to ship your page to client will be increased too.
+ When you use `view page source` feature, you will see your css is in document. Imagine you have base64 `background-image` => Your site size is kind of heavy.

I met this issue. My approach is use css file. You can checkout my article to know detail and also demo was provided too.

[https://medium.com/@nndung179/next-js-at-chotot-ca9c1520f436](https://medium.com/@nndung179/next-js-at-chotot-ca9c1520f436)

**Comment by tomsoderlund** [comment]
Thanks for clarifying, @hawkins and @nndung179!
