### ISSUE TITLE
Confused on how to use apollo SSR and redux

### ISSUE THREAD

**Issue by johhansantana** [zeit/next.js#2347]
I'm trying to follow the example here

[With Data](https://github.com/zeit/next.js/blob/v3-beta/examples/with-apollo-and-redux/lib/withData.js)

I've already done the `initRedux` and `initApollo` exactly as they are and they are working correctly.

My `Page` looks like this

```javascript
import React from 'react';
import { ApolloProvider } from 'react-apollo';
import apolloClient from '!/lib/initApollo';
import initRedux from '!/lib/initRedux';
import Home from '!/containers/home';
/**
 * Component to show the home container.
 */
class App extends React.Component {
  static getInitialProps({ req }) {
    const isServer = !!req;
    return { isServer };
  }

  constructor(props) {
    super(props);
    this.apollo = apolloClient();
    this.store = initRedux(this.apollo);
  }

  render() {
    return (
      <ApolloProvider client={this.apollo} store={this.store}>
        <Home />
      </ApolloProvider>
    );
  }
}

export default App;
```

While this works, I'm concern on how I can do queries via SSR.

Before I had apollo I used to have my `Page` similar to this:

```javascript
import React from 'react';
import { Provider } from 'react-redux';
import withRedux from 'next-redux-wrapper';
import { initStore } from '!/store';
import About from '!/containers/about';
import * as kittensActions from '!/actions/kittensActions';
/**
 * Component to show the about component.
 */
class App extends React.Component {
  static async getInitialProps({ store, req }) {
    const isServer = !!req;
    await store.dispatch(kittensActions.getAsyncKittens());
    return { initialState: store.getState(), isServer };
  }

  constructor(props) {
    super(props);
    this.store = initStore(props.initialState, props.isServer);
  }

  render() {
    return (
      <Provider store={this.store}>
        <About />
      </Provider>
    );
  }
}

export default withRedux(initStore)(App);
```

Notice that I have `withRedux` library. I tried using it with the example of apollo but couldn't get it to work.

Now I'm back to old redux implementation and I'm not sure how to run redux actions in the `getInitialProps` anymore.

**Comment by cncolder** [comment]
In the fully [with-apollo-and-redux](https://github.com/zeit/next.js/blob/b2bda416b64b476667ba3b3dec0e2c4841baef2b/examples/with-apollo-and-redux/lib/withData.js#L27) example. `redux` is set in `getInitialProps`

**Comment by johhansantana** [comment]
@cncolder oh good point, thank you!

Btw, Do I have to import the container that has the graphql query in order to use them with SSR?

What I've done now is:
```javascript
import React from 'react';
import { ApolloProvider, getDataFromTree } from 'react-apollo';
import apolloClient from '!/lib/initApollo';
import initRedux from '!/lib/initRedux';
import Home from '!/containers/home';
/**
 * Component to show the home container.
 */
class App extends React.Component {
  static async getInitialProps(ctx) {
    let serverState = {};
    // Evaluate the composed component's getInitialProps()
    let composedInitialProps = {};
    if (App.getInitialProps) {
      composedInitialProps = await App.getInitialProps(ctx);
    }
    if (!process.browser) {
      const apollo = apolloClient();
      const redux = initRedux(apollo);
      // Run all graphql queries
      const app = (
        <ApolloProvider client={apollo} store={redux}>
          <Home {...composedInitialProps} />
        </ApolloProvider>
      );
      await getDataFromTree(app);
      const state = redux.getState();
      serverState = {
        apollo: { // Make sure to only include Apollo's data state
          data: state.apollo.data
        }
      };
    }
    return {
      serverState,
      ...composedInitialProps
    };
  }

  constructor(props) {
    super(props);
    this.apollo = apolloClient();
    this.store = initRedux(this.apollo, props.serverState);
  }

  render() {
    return (
      <ApolloProvider client={this.apollo} store={this.store}>
        <Home {...this.props} />
      </ApolloProvider>
    );
  }
}

export default App;
```

But gives me an error:
`RangeError: Maximum call stack size exceeded`

**Comment by cncolder** [comment]
Because you call `App.getInitialProps(ctx)` in `App.getInitialProps`. This is infinite loop.

In [with-apollo-and-redux](https://github.com/zeit/next.js/blob/b2bda416b64b476667ba3b3dec0e2c4841baef2b/examples/with-apollo-and-redux/lib/withData.js) example. `withData` is [HOC](https://facebook.github.io/react/docs/higher-order-components.html). It do all work about how to feed data on server side, and how to wrap children in `ApolloProvider`.

You need remove HOC logic code from `App`. Then export App like this `export default withData(App)`.

If there is only one page in your project. You do not need call `App.getInitialProps(ctx)` manual. Next.js will call this method.

**Comment by cncolder** [comment]
In that example. Your component props come from three sources:

1. `withData.getInitialProps` generate data
2. `wrappedComponent.getInitialProps` return value.
3. Apollo fetched data.

So you can understand why `withData.getInitialProps` write like that. Next.js only call top level compoent `getInitialProps` method. `withData` merge those three data into one props object.

**Comment by johhansantana** [comment]
@cncolder Thank you so much I think I got it working now like this

```javascript
import React from 'react';
import { ApolloProvider, getDataFromTree } from 'react-apollo';
import apolloClient from '!/lib/initApollo';
import initRedux from '!/lib/initRedux';
import Home from '!/containers/home';
/**
 * Component to show the home container.
 */
class App extends React.Component {
  static async getInitialProps(ctx) {
    let serverState = {};
    if (!process.browser) {
      const apollo = apolloClient();
      const redux = initRedux(apollo);
      // Run all graphql queries
      const app = (
        <ApolloProvider client={apollo} store={redux}>
          <Home />
        </ApolloProvider>
      );
      await getDataFromTree(app);
      const state = redux.getState();
      serverState = {
        apollo: { // Make sure to only include Apollo's data state
          data: state.apollo.data
        }
      };
    }
    return {
      serverState,
    };
  }

  constructor(props) {
    super(props);
    this.apollo = apolloClient();
    this.store = initRedux(this.apollo, props.serverState);
  }

  render() {
    return (
      <ApolloProvider client={this.apollo} store={this.store}>
        <Home {...this.props} />
      </ApolloProvider>
    );
  }
}

export default App;
```

Any final tips you think this can be improved? if not you can close this as resolved.

**Comment by cncolder** [comment]
It's ok if your app is only one entry.

**Comment by johhansantana** [comment]
@cncolder I see, could you take a look https://github.com/johhansantana/nerg ?

The plan is to create the pages with the code above when you need SSR. I think everything is working a ok.

**Comment by timneutkens** [comment]
I'm going to close this.
