### ISSUE TITLE
loadGetInitialProps throw error after reboot server

### ISSUE THREAD

**Issue by cncolder** [zeit/next.js#2355]
After reboot server. Browser fetch in `on-demand-entries-ping`. At this time `Component` maybe undefined.

[/lib/utils.js#L50](https://github.com/zeit/next.js/blob/7b8a4ea234d67fd4e8fddba9ee53df36cd70adb7/lib/utils.js#L50)

**Comment by timneutkens** [comment]
Can you provide a way to reproduce this? Then I'll re-open.
