### ISSUE TITLE
Raspberry Pi stuck on Using external babel configuration

### ISSUE THREAD

**Issue by safinn** [zeit/next.js#2357]
Im trying to run my project on a Raspberry Pi but it just gets stuck on `Using external babel configuration`. I have a custom `.babelrc` file that looks like this:
```
{
  "presets": [ "next/babel" ],
  "plugins": [ "inline-react-svg" ]
}
```
Works fine on OSX. The Raspberry Pi has version node `v8.1.2` and npm version `5.0.3`. 

Anyone else faced this issue?

**Comment by safinn** [comment]
Updated to 3.0.1 beta 1 and it is now working. Not sure if it was just really slow!

**Comment by mhkabir123** [comment]
Hi safinn, 
I am trying to install and configure babeld on my Raspberry Pi3(Raspbian), I have installed babeld(sudo apt-get install babeld), but I couldn't configure it, can you please give me idea? Thanks in advance!

**Comment by safinn** [comment]
I think [babeld](https://www.irif.fr/~jch//software/babel/) is different to what I was trying to get working [babel](https://babeljs.io/).
