### ISSUE TITLE
Override websocket location

### ISSUE THREAD

**Issue by mikecardwell** [zeit/next.js#236]
I have an nginx server. It has a https vhost. We'll pretend it is https://www.example.com for now. I have told it to proxy to a next.js application running at localhost:3000. The trouble is, my browser is trying to open a websocket to "https://localhost:3030". I don't see a way of overriding where the websocket connection should go to... Ideally, I'd just tell it to go to https://www.example.com and then configure nginx to forward requests for /sockjs-node/ to localhost:3030.

So, is there a way of overriding the websocket location? If not, can I add this as a feature request please.

**Comment by nkzawa** [comment]
Unfortunately, you can't customize it. It should be supported.

**Comment by coffenbacher** [comment]
Similarly, I develop on a remote machine so localhost doesn't work for me. If anyone else has that challenge, for now, I was successfully able to use Fiddler HOSTS feature to remap localhost -> remote IP. I'm sure there's a similar debugging proxy for OS X / Linux (Charles?) that could do the same.

**Comment by mingfang** [comment]
This is a show stopper for me.

**Comment by mikecardwell** [comment]
FWIW, as a temporary workaround I am running the following command to modify the hard coded websocket to my own domain. In the below example I'm changing it to the SSL secured "example.com":

```shell
grep -r http://localhost:3030 .next node_modules/next|awk -F ':' {'print $1'}|sort -u|xargs perl -pi -e 's,http://localhost:3030,https://www.example.com,g'
```
