### ISSUE TITLE
getInitialProps gets called in exported static site in Safari 10.1

### ISSUE THREAD

**Issue by elmasse** [zeit/next.js#2360]
I'm trying to get more data for this issue. What I have found so far is that Safari 10.1 triggers popstate when back button is pressed. Somehow the Router handler (onPopState) causes the getInitialProps to be called.

Check this example https://out-ewgbaypiah.now.sh - click on a Post link and then press back button on Safari. You'll notice a 404 call that is made by the getInitialProps.

Tested on Chrome and Firefox and this works properly.

I have commented out the `window.addEventListener('popstate',this.onPopState)` on the generated `app.js` and that seems to fix the issue.

Tested with 3.0.0-beta16 and 3.0.1-beta1

Any help on how to debug this properly will be greatly appreciated.

**Comment by arunoda** [comment]
Something is not good. Could you send me the source code of this or a sample repo.
I'd like to investigate more.

**Comment by elmasse** [comment]
@arunoda 

source is https://github.com/elmasse/nextein-example
and that is basically using a few HOCs defined in
https://github.com/elmasse/nextein/blob/master/src/components/posts.js and
https://github.com/elmasse/nextein/blob/master/src/components/post.js

There is not much magic in there. I'll try to get a simple test case to avoid those indirections.

Thanks!

**Comment by elmasse** [comment]
@arunoda I created this gist with some simple files that are able to reproduce the issue.

gist:https://gist.github.com/elmasse/d98ab6d9cc447459dcfbe6329dc0c810
deploy: https://out-hnjokhqdns.now.sh

steps: 

1.  open https://out-hnjokhqdns.now.sh in safari
2. open the dev tools
3. click on 'About' link
4. press back button
  a. notice a 404 call to `./no-found` that is performed by Index getInitialProps in the dev tools

**Comment by arunoda** [comment]
@elmasse this is correct. What's happening is even though this is a static site when you `next/link` it'll do the client side routing and all the other stuff Next.js do.
That includes running `getInitialProps`.

If that's not the behavior you wanted, simply use normal `a` tag instead of `next/link`. Or you can do some conditional stuff in getInitialProps.

**Comment by timneutkens** [comment]
😲 Nice!

**Comment by elmasse** [comment]
@arunoda 
I understand your point of view. However, the example that originated this issue was not using `next/link` at all it was a plain `<a>` tag.
On the other hand, if Link causes getInitialProps to be called, then the behavior is not consistent across browsers (Chrome and FF do NOT call getInitialProps on back button in those examples)

As I mentioned before, I believe this is related to onPopState event being fired differently in Safari.

Please consider reopening this issue.


Thanks!

**Comment by arunoda** [comment]
What you mention [here](https://github.com/zeit/next.js/issues/2360#issuecomment-311501752) is not an issue. That's how it should work.

Anyway, I saw an something weird in the original app.
Could you please show me the reproduction details for that issue?

**Comment by elmasse** [comment]
Ok, 2 things here then:

if that is the intended behavior, is there any way to disable the Router? I'm not using the `next/link` in my app so I don't see a real need for it in an static export.

And again, if it is the intended behavior why it is not consistent across browsers?


The reproduction details for the code that originated this issue are basically the same:

open https://out-ewgbaypiah.now.sh/ in safari
open the dev tools
click on any  'Post' link
press back button
 a. notice a 404 call to ./load-entries that is performed by Index getInitialProps in the dev tools

The page shows an error since the fetch is not wrapped in a try/catch

**Comment by timneutkens** [comment]
This can now be fixed using https://github.com/zeit/next.js#intercepting-popstate
