### ISSUE TITLE
Add UTF-8 charset by default to head

### ISSUE THREAD

**Issue by jimthedev** [zeit/next.js#237]
Currently there is no charset added by default in the head. The problem is that if you don't have are charset and use a UTF-8 font like any of those in Google Fonts then you can easily run into [this problem](http://chromakode.com/post/react-utf8).

**Comment by nkzawa** [comment]
SGTM

**Comment by nkzawa** [comment]
Related: https://github.com/zeit/next.js/issues/248

**Comment by rauchg** [comment]
+1 as well

**Comment by rauchg** [comment]
I'd still like to retain its customizability. We can basically have `Head` render a default utf-8 charset if none have been set. If `<meta charSet>` is passed, it overrides the default

**Comment by rauchg** [comment]
Also, isn't this fixed by sending the right encoding with the HTTP response?

**Comment by mikecardwell** [comment]
@rauchg - HTTP response headers are OK until the user goes and saves the HTML page to disk. When they open the document later in the same or a different browser, it will not know the charset unless it is embedded in the document.

**Comment by simakwm** [comment]
Why doesn't  <meta charSet="utf-8"> have any effect after "next build" ?
