### ISSUE TITLE
Including raw javascript in <script> tag in <head>

### ISSUE THREAD

**Issue by paulwehner** [zeit/next.js#2374]
If I use Head from 'next/head', how could I include a <script> tag that has inline javascript in it? Is that possible?

```
<Head>
  <script>
    //inline javascript
    console.log('im doing something')
  </script>
</Head>
```

**Comment by arunoda** [comment]
Frankly, I am not sure about it.
May be react will strip out if you do it like this.

Use this: https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml
