### ISSUE TITLE
Generate component info using react-docgen and babel-plugin-react-docgen

### ISSUE THREAD

**Issue by PetrSnobelt** [zeit/next.js#2379]
Hi,

I try use `babel-plugin-react-docgen`, I just install babel-plugin-react-docgen and react-docgen and then add "react-docgen" into plugins in ".babelrc" 

But when I run `npm run dev` it looks like nothing is generated.

When I try `react-docgen ./components/button.js` it return fine json, but I can't find similar json into .next folder.

Is there any trick which can help generate doc for my components?

Thanks

**Comment by timneutkens** [comment]
@arunoda any ideas?

**Comment by arunoda** [comment]
Hey, https://github.com/storybooks/babel-plugin-react-docgen doesn't generate anything.
It adds the docgen output into the React class.

Please read the docs on that repo.

**Comment by PetrSnobelt** [comment]
Exactly, it should add docgen output into the React class. 
But docgen output is missing in .next folder
