### ISSUE TITLE
You can add classname to <Main /> components

### ISSUE THREAD

**Issue by enternode** [zeit/next.js#2380]
It will be possible to create custom classname in document.js components like <Main />

**Comment by sergiodxa** [comment]
Right now you can add a `className` to your body, check -> https://github.com/zeit/next.js#custom-document.

It's not possible at the moment to add a className to some of the divs rendered by `<Main />` ([it render 3 divs](https://github.com/zeit/next.js/blob/v3-beta/server/document.js#L106-L109)) but you can create a PR.

**Comment by timneutkens** [comment]
What's the use case for adding classes to those? 🤔 Both divs have an id property.

**Comment by PetrSnobelt** [comment]
@timneutkens What about reuse existing css?
