### ISSUE TITLE
'npm run build' fails

### ISSUE THREAD

**Issue by PDXIII** [zeit/next.js#2383]
I followed the [learn next.js](https://learnnextjs.com) tutorial which worked out pretty fine but a few days later I wanted to try our the build process without ```now``` so I tried ```npm run build``` aka ```next build``` and it ended with this error:

### Error:

    Error: ./pages/batman-shows.js?entry
    Module build failed: SyntaxError: unknown: Unexpected token (5:25)
      3 | import fetch from 'isomorphic-fetch';
      4 |
    > 5 | export default (props => <BasicLayout>
        |                          ^
      6 |     <h1>Batman Shows</h1>
      7 |     <ul>
      8 |       {props.shows.map(({ show }) => <li key={show.id}>

Which is kind of strange because the original code looks like this:

### Original Source Code: 

    import BasicLayout from '../layouts/BasicLayout'
    import Link from 'next/link'
    import fetch from 'isomorphic-fetch'

    export default (props) => (
      <BasicLayout>
        <h1>Batman Shows</h1>
        <ul>
          { props.shows.map(({ show }) => (
            <li key={ show.id }>
              <Link
                as={`/s/${ show.id }`}
                href={`/show?id=${ show.id }`}>
                  <a>{ show.name }</a>
                </Link>
            </li>
          ))}
        </ul>
      </BasicLayout>
    )
    .getInitialProps = async () => {
      const res = await fetch('http://api.tvmaze.com/search/shows?q=batman')
      const data = await res.json()

      console.log(`Show data fetched. Count: ${data.length}`)

      return {
        shows:data
      }
    }

The app works fine when started with ```npm start```. Any ideas?

### Update

Even when I try to run it with ```npm run dev``` it shows the same error.

**Comment by coluccini** [comment]
Your are missing the closing parenthesis here `(props`

**Comment by PDXIII** [comment]
Thanks for your reply, @coluccini!

That’s what the error says. 
But when you take a look at the source code the closing parenthesis isn’t missing.

**Comment by coluccini** [comment]
Can you put the whole problematic code? I think you are mistaken the parenthesis that should wraps `props` with another one

**Comment by PDXIII** [comment]
But this is the problematic code. 
For me, it seems that the build process somehow strips away the parenthesis. 
Or am I missing something in my source code?

It is basically (my source code): 

    export default (props) => (
      <div>
        MARKUP
      </div>
    )

And it complies to (error output):

    export default (props => 
      <div>
        MARKUP
      </div>
    )

I would love to know what I am doing wrong here. I have no clue.

**Comment by timneutkens** [comment]
@PDXIII looks like you have a `.babelrc` in the next directory or in an upwards directory.
