### ISSUE TITLE
Make sure react and react-dom always moves to the commons

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#2388]
It will fix issues like #2121 
Also, we need to test how these works with chunks and how it affects how algorithm for deciding a commons module.

**Comment by quentin-sommer** [comment]
Example showcasing the bug: https://github.com/quentin-sommer/quentin-sommer.com

- `git clone`
- `yarn && npm run build && npm run bundle:view` 

And you'll see `main.js` bundle contains `react-dom` whereas `react` is in `common.js`. can I help fix this? If so could you point me where to look in the codebase? @arunoda

**Comment by arunoda** [comment]
Thanks @quentin-sommer 
Fixed with https://github.com/zeit/next.js/pull/2572
