### ISSUE TITLE
Next & SailsJS

### ISSUE THREAD

**Issue by juliandavidmr** [zeit/next.js#2394]
Is there any way to integrate Next with [SailsJS](http://sailsjs.com)?

**Comment by sergiodxa** [comment]
Use Sails.js as an API and consume it from Next.js

**Comment by RasCarlito** [comment]
Hi!

If anyone is interested, I have a [work in progress](https://github.com/RasCarlito/sails-hook-next) integrating Next.js into Sails using a hook. This way you can run Next.js and Sails on the same port/domain and keep the sources in a single project. Quite useful for small projects.

Cheers :beers:
