### ISSUE TITLE
Router as an independent module 

### ISSUE THREAD

**Issue by bubuzzz** [zeit/next.js#2396]
I started to use next.js for several projects and extremely like it. What I like the most is the simple way to navigate through the page, thank to the router of nextjs. Is there any chance that the module can be separated and then i could use in other old react projects as well ? 

Currently in the React world, there is only react-router, which brings the complexity to the level of insanity (checkout https://stackoverflow.com/questions/31079081/programmatically-navigate-using-react-router with dozen of answers in order to just to move from one page to the other)

**Comment by timneutkens** [comment]
We're not planning to release it separately in the short term since it's pretty connected to Next.js at the moment. It's a cool idea though 😄
