### ISSUE TITLE
Next.js & Flow setup.

### ISSUE THREAD

**Issue by grundmanise** [zeit/next.js#2402]
Should I install `babel-preset-flow` when using `next/babel` preset? Or `next/babel` already handles `flow` types transformation?

**Comment by AugustinLF** [comment]
It already handles it.

**Comment by timneutkens** [comment]
Please see the with-flow example: https://github.com/zeit/next.js/tree/v3-beta/examples/with-flow

**Comment by mikemclin** [comment]
Updated link as of today: https://github.com/zeit/next.js/tree/canary/examples/with-flow

**Comment by MacKentoch** [comment]
Client side is ok. 

But server side flow types won't be stripped despite having a custom babelrc (in my case `@babel/preset-flow`).

Does someone uses flow on a custom server with NextJS?

**Comment by ericclemmons** [comment]
I still had issues with using `graphiql`, but was able to fix it with this:
https://github.com/ericclemmons/customized-graphiql/blob/master/next.config.js

**Comment by zomars** [comment]
Is there a reason for `_app.js` not being typed in the linked example?
