### ISSUE TITLE
Server side routing gets broken in production (dev works ok) when using `pages/foo/index.js` rather than `pages/foo.js`

### ISSUE THREAD

**Issue by kunokdev** [zeit/next.js#2408]
I am using custom server Express with Next.js 2.
After changing `pages` folder structure to:

```
pages
|_ about
|__ index.js
|__ style.js
|_ other
|__ index.js
|__ style.js
...
```
it worked by default very nicely, at least in dev mode. After pushing to production, I noticed on hard refresh, error would be displayed. (Unexpected error kind of message appeared instead of page). Then I noticed it also would happen when user would visit some page directly via link. Meanwhile, page transitions via `<Link />` component worked just fine. So I realized it's related to server side router. 

I returned my pages folder to old structure such as:

```
pages
|_ about.js
|_ other.js
...
```
and bug was gone. 

Key points:

- Happens only in production, dev mode can't reproduce this bug
- Happens when using `pages/foo/index.js` instead of `pages/foo.js`
- Related to server side routing

**Comment by sergiodxa** [comment]
Can you provide a repo to replicate this? Also are you using `/about` or `/about/`? if you use `pages/about/index.js` you need to use `/about/` URL

**Comment by kunokdev** [comment]
@sergiodxa Is there a way to use both by default?

**Comment by sergiodxa** [comment]
@kunokdev no, you need to create a custom server and redirect from urls without `/` to urls with `/` at the end

**Comment by kunokdev** [comment]
Should routes with `/` and without it be merged was already discussed in different topic, so I am closing this issue, gonna edit this comment with code when I update it.
