### ISSUE TITLE
Production deployment: HMR Issue

### ISSUE THREAD

**Issue by obfuscatedgeek** [zeit/next.js#2409]
I have a basic nextjs app deployed to production. It is basically the next-routes example with SSR using koa server.

For some reason when I navigate to the site, I can see in the browser's console messages as `[HMR] connected`.

Need help to understand how to stop these messages.

Next version: `"next": "^3.0.1-beta.1"`

Deployment is  basic as well.
```
"build": "next build",
"start": "NODE_ENV=production node server.js"
```

And everytime I navigate to various routes I get mesages like `[HMR] bundle rebuilding
`

**Comment by jaydenseric** [comment]
Are you sure `NODE_ENV` is being used to toggle dev mode correctly in your server code, like [here](https://github.com/zeit/next.js/blob/v3-beta/examples/custom-server-koa/server.js#L6)?

**Comment by obfuscatedgeek** [comment]
@jaydenseric that was precisely the problem. I had hard coded it to `{dev: true}` and had forgotten all about it. Thanks a ton!
