### ISSUE TITLE
Server side routing API w/o requiring custom server

### ISSUE THREAD

**Issue by PandaWhisperer** [zeit/next.js#2410]
Hey guys,

just stumbled on this project and went through the tutorial on [learnnextjs.com](http://learnnextjs.com). Pretty neat! I like the idea of bringing configuration over convention to the React world (which seems to favor explicitness over everything).

All in all, once I got over my initial hurdle of accepting writing all my HTML in JS, I went along with most of the sections with a smile on my face, and always thinking "that's neat". 

One thing that kinda bugged me though was when it came to server side routing. Suddenly you have to create a custom server app with copypasta code and deployment ramifications (BTW that chapter about deploying with custom server was a little dense). 

That could be a little simpler, don't you think? 

I'm thinking if all you want is custom server-side routing, it would be nice if there was just a single file to create (e.g. `routes.js`) that exported a single function that's automatically chained into the `createServer` callback, like so:

```js
export default function(app, req, res) {
    if (pathname === '/a') {
      app.render(req, res, '/b', query)
    } else if (pathname === '/b') {
      app.render(req, res, '/a', query)
    } else {
      app.getRequestHandler()(req, res, parsedUrl)
    }
}
```

This function could do all the routing (or whatever else one wants or needs) and simply delegate to the default request handler for anything that doesn't need special handling. 

Any thoughts on that?

**Comment by obfuscatedgeek** [comment]
Had the same thoughts initially untill I stumbled on their examples folder, do check it out. They have a solution for many common stuff. https://zeit.co/blog/next2
You need to really scroll to the bottom to see the various stuff.

I believe this is what you are looking for: https://github.com/zeit/next.js/tree/master/examples/with-pretty-url-routing 

There are many examples for routing

**Comment by PandaWhisperer** [comment]
Thanks for pointing that out. Would be cool if the README section on server side routing linked to that example. Also, that example *still* requires a custom `server.js`, although I definitely like that the routes are living in their own file.

**Comment by PandaWhisperer** [comment]
Gotta say thought, props on the examples. I'm used to getting like 3. This thing has more like 30.

**Comment by arunoda** [comment]
I think we have talked about this many times. The current solution is the best we can have.
You can search the issue list for more ideas and reasons why we did this.

**Comment by fridays** [comment]
Also checkout [next-routes](https://github.com/fridays/next-routes) 👍
