### ISSUE TITLE
Need update in example code about external stylesheet

### ISSUE THREAD

**Issue by mocheng** [zeit/next.js#2413]
In example code about external stylesheet https://github.com/zeit/next.js/tree/master/examples/with-global-stylesheet , it still has `dangerouslySetInnerHTML`. According to this `styled-jsx` improvement` https://github.com/zeit/styled-jsx/pull/148, we can reference  imported stylesheet now.

I tried to change code and it works.

```diff
 export default () =>
   <div>
-    <style dangerouslySetInnerHTML={{ __html: stylesheet }} />
+    <style jsx global>{stylesheet}</style>
     <p>ciao</p>
   </div>
```

The `dangerouslySetInnerHTML` does not look right and might trigger eslint error. If my understanding is right, I'll submit a PR for this.

**Comment by timneutkens** [comment]
@giuseppeg this won't work right? Since it's not a JS export

**Comment by eliot-akira** [comment]
In my case, using `<style jsx global>` for the stylesheet results in this:

> Module build failed: SyntaxError: The Identifier `stylesheet` is either `undefined` or it is not an external StyleSheet reference i.e. it doesn't come from an `import` or `require` statement

**Comment by giuseppeg** [comment]
@timneutkens correct, styled-jsx transpiles only exported js strings/template literals. 
Maybe with something like webpack raw-loader you can make it work but afaik only client side code gets bundled via webpack so it won't work for SSR.

@eliot-akira in your case the error could be due to the fact that you don't import the `stylesheet`.

**Comment by timneutkens** [comment]
@giuseppeg thanks for the confirmation 👌

**Comment by mocheng** [comment]
@giuseppeg @timneutkens  Sorry to bother you, but it does work in SSR.

With this commit https://github.com/mocheng/next.js/commit/7ac857aac79b360b95becd92a3cb3a416ddb76ac , the server-side-rendered HTML has `.foo{color:green}` in its `<style id="__jsx-style-14162456061">` tag of `<head>`. 

I understand that @giuseppeg 's point is that webpack config only affects browser side bundling. But, this change proves that it work in SSR by injecting style into inline style.

**Comment by giuseppeg** [comment]
> afaik only client side code gets bundled via webpack so it won't work for SSR
@mocheng this was more like "I think that...", I was looking for someone to confirm :) 

It seems that in the example webpack is doing the magic, but if it would be very cool if that works for ssr too. Have you also tried without the `global` property on the `style` tag?

**Comment by mocheng** [comment]
@giuseppeg without `global`, the inline style tag would have something like `.foo[data-jsx-ext~="24162456061"]{color:green}` which is scoped style.

With `global`, the inline style tag would have `.foo{color:green}`.

**Comment by timneutkens** [comment]
This is *really* cool 😲

**Comment by giuseppeg** [comment]
I will give it a try, if this works it is amazing because it means that people can write regular CSS in separate .css files and benefit from tooling etc.

**Comment by giuseppeg** [comment]
Alright @mocheng it works indeed! Apparently a combo of `babel-plugin-wrap-in-js` and webpack's `raw-loader` does the trick. But I wouldn't use it in production yet because the babel plugin doesn't have tests and when doing server side rendering styled-jsx writes the css in a `style` tag in the page which means that it is never cached therefore if you have a lot of css and big external files your page size can grow considerably. 

Since there is a solution though we might explore ways to allow this in a performant way – maybe we should write external compiled files for SSR in actual `.css` files and the load them using a regular `link` tag rather than an inline `style`.

**Comment by mocheng** [comment]
@giuseppeg I once tried to utilize `ExtractTextPugin` to extract CSS/SCSS into bundle CSS files to be referenced in `style` tag in `head`, but it is hard (if not impossible) to do it by customizing webpack config. I bet it would be easier if next.js itself provides such feature.

**Comment by giuseppeg** [comment]
I think that we could do that in styled-jsx I'll think about it and write a proposal. The api could be `<style jsx as="link">`

**Comment by ilionic** [comment]
Noticed `styles/index.scss` is bundled in commons.js
Basically same css duplicated - inlined into the page and part of `app.js`
Any tips how to exclude it from app.js?
![image](https://user-images.githubusercontent.com/1027871/28250850-3394df68-6a6a-11e7-84f1-0bea630c665b.png)

**Comment by giuseppeg** [comment]
for regular global styles files I would just serve them from `/static` and include them in the page with a `link` tag

**Comment by ilionic** [comment]
So is it normal behaviour with bundling? 
In my case I have external component-based `.styl` files that are imported and injected to `<style jsx>` so it's not really regular global styles.

```
import ComponentStyles from 'components/my-component.styl';
...
<style jsx>{ComponentStyles}</style>`
```

**Comment by giuseppeg** [comment]
@ilionic it'll be inlined in the page when you do server side rendering and in your bundle in case you load that page on the client (via router/ajax)

**Comment by giuseppeg** [comment]
see also the conversation above https://github.com/zeit/next.js/issues/2413#issuecomment-314212017

**Comment by ilionic** [comment]
Ok I see, it's about finding compromise between performance, page size and dev experience.
Currently using combination of both methods - global css file with some theme dependencies ( like bootstrap ) above the fold loaded using `link` tag in non-render blocking way.
Critical css above-the fold is inlined ( using `style jsx` ) also it's nicer dev experience having component based styles with hot reload.
It works but as you pointed @giuseppeg page size started growing considerably ( including js bundle )
So until we can migrate from global css to css-in-js solutions looking for possible optimisations.
