### ISSUE TITLE
next build causes Error: commons.js from UglifyJs Unexpected token: operator (>)

### ISSUE THREAD

**Issue by nwshane** [zeit/next.js#2414]
Running `next build` causes this error:

```
Error: commons.js from UglifyJs
Unexpected token: operator (>) [commons.js:15841,37]
```

Running next in development mode works fine.

Next JS version: 2.4.6

Just in case it matters, here are my config files.
```
// .babelrc
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    ["react-intl", {
        "messagesDir": "./lang/.messages"
    }],
    "transform-flow-strip-types",
    "babel-plugin-root-import"
  ],
  "env": {
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ]
    }
  }
}

// next.config.js
module.exports = {
  webpack: function (c) {
    // Fixes bug: https://github.com/zeit/next.js/issues/1877
    if (c.resolve.alias) {
      delete c.resolve.alias['react']
      delete c.resolve.alias['react-dom']
    }
    return c
  }
}
```

**Comment by arunoda** [comment]
This is when one of your NPM modules have ES6 code in it. Without transpiling. 
Frankly, you've to manually find out which module causing this issue.

Try deleting all pages and adding one by one and build and see which module causes the issue.
There are some other issues in the issue list we talked about this topic.
Please search for them.

**Comment by nwshane** [comment]
@arunoda Ah, my bad. I did a search for this error and next but couldn't find anything. Thanks for your help!

**Comment by arunoda** [comment]
Here we go: https://github.com/zeit/next.js/issues?q=is%3Aissue+UglifyJs+is%3Aclosed
