### ISSUE TITLE
example with-dynamic-import doesn't work 

### ISSUE THREAD

**Issue by supra28** [zeit/next.js#2416]
TypeError: promise.then is not a function

**Comment by ndelangen** [comment]
I had problems with dynamic imports not working, and solved it by adding: ` "next/babel"` to my `.babelrc`. Hope this helps you too.

```js
{
  "presets": [
    "next/babel",
    "stage-0"
  ],
}
```

**Comment by timneutkens** [comment]
Please Provide an example repository.

**Comment by supra28** [comment]
@ndelangen Didn't work :(
@timneutkens The code is in the examples directory with-dynamic-imports. I just cloned it.

**Comment by timneutkens** [comment]
@supra28 thanks! it's actually installing an old beta version. Fixing the example now. You can just `yarn remove next` `yarn add next@beta` and it'll install the right version 👌

**Comment by timneutkens** [comment]
Created PR #2423 to fix this 👌
