### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by Orecic** [zeit/next.js#2431]
ReferenceError: document is not defined ,What should I do to solve the problem, thanks.

**Comment by timneutkens** [comment]
@Orecic please provide a way to reproduce this error. Then I'll re-open the issue.

**Comment by arunoda** [comment]
Usually this means, you are using a module which can't use in the server.
If so, run only that in the client.

**Comment by Orecic** [comment]
![wechatimg20](https://user-images.githubusercontent.com/11868645/27768787-4e3f0af4-5f4e-11e7-8fbb-57eb3cb5e4d2.jpeg)

I want to write a HTTP interceptor to handle system errors with antd，it works in  client slide rendering,but has an error "ReferenceError: document is not defined" in server slide rendering, how can I write a HTTP interceptor,thanks very much

**Comment by Orecic** [comment]
I want to write a HTTP interceptor to handle system errors with antd，it works in client slide rendering,but has an error "ReferenceError: document is not defined" in server slide rendering, how can I write a HTTP interceptor that works in server slide rendering ,thanks very much.
![wechatimg21](https://user-images.githubusercontent.com/11868645/27768843-9213d20e-5f4f-11e7-956d-07c337c7dca5.jpeg)

**Comment by arunoda** [comment]
I assume you can't render antd Model in the server. Try looking at their support channels on how to do that. Or use something else.
