### ISSUE TITLE
Open graph meta tags duplication in <head />

### ISSUE THREAD

**Issue by gbiryukov** [zeit/next.js#2438]
Right now [facebook Open Graph meta tags](https://developers.facebook.com/docs/sharing/webmasters#markup) gets duplicated in head if several next `<Head />` components used in one page.
```html
<head>
  <meta property="og:title" content="Default Page Title" />
  <meta property="og:title" content="Current Page Title" />
</head>
```
This happens because `property` prop doesn't considered in head [`METATYPE`s](https://github.com/zeit/next.js/blob/v3-beta/lib/head.js#L45).
It should be super easy to fix.

**Comment by timneutkens** [comment]
@gbiryukov interesting. Let me have a look 👌

**Comment by timneutkens** [comment]
@gbiryukov #2439

**Comment by gbiryukov** [comment]
good job, thanks!

**Comment by ilionic** [comment]
Can you please revert it or make exception for `og:image` ? It's common practise to use multiple `og:image`

**Comment by schoenwaldnils** [comment]
@timneutkens still have this issue on next@4.0.5
see: 
- https://github.com/schoenwaldnils/blog
- http://schoenwald.media/hello-world/
