### ISSUE TITLE
add test coverage

### ISSUE THREAD

**Issue by bcoe** [zeit/next.js#244]
I would love to help add test coverage to this repo, using `nyc` and potentially `babel-plugin-istanbul`. Would you accept a pull request for this?

**Comment by rauchg** [comment]
Sounds great. And a badge!

**Comment by arunoda** [comment]
And I'd like to see some test cases as well.
@rauchg do you have any plans on how to do testing?
Currently, it's just a few integration test cases.

**Comment by bcoe** [comment]
@rauchg would you be open to using `babel-register` for tests, rather than a compile step; or would you prefer to wire up source-maps?

I have a slight preference for `babel-register`, but can take on either approach (source-maps being slightly more of a hassle).

**Comment by rauchg** [comment]
@bcoe I tend to use `babel-register` for tests as well

**Comment by nkzawa** [comment]
@bcoe @rauchg we don't use `babel-register` for now since need to compile the source at the same time in some cases anyway.

**Comment by bcoe** [comment]
two options for you here:

<img width="877" alt="screen shot 2016-11-14 at 4 07 25 pm" src="https://cloud.githubusercontent.com/assets/194609/20287945/96c6e87a-aa84-11e6-88e7-69f1e9f19e16.png">

☝️ implement just the files currently touched by tests -- a less terrifying view of the world.

<img width="505" alt="screen shot 2016-11-14 at 4 09 07 pm" src="https://cloud.githubusercontent.com/assets/194609/20287959/b0f86372-aa84-11e6-9cad-253cca72d8a0.png">

Instrument everything, a more honest view of the world.

Next question, are there any folders you see there that should be excluded from coverage? CC: @nkzawa, @rauchg

**Comment by rauchg** [comment]
omg this is so beautiful I want to cry 😭

**Comment by bcoe** [comment]
@rauchg @nkzawa see #259, I did my best to stay in the spirit of the project's current structure.

**Comment by sedubois** [comment]
What do you think about using Jest? It's very fast‚ provides built-in test coverage and has things like snapshot testing. React-boilerplate just [switched](https://github.com/mxstbr/react-boilerplate/issues/970) to Jest.

**Comment by bcoe** [comment]
@sedubois Jest uses `istanbul-lib-coverage` and `babel-plugin-istanbul` behind the scenes to facilitate its coverage, both libraries that I maintain. and are part of #259 . I personally like having `nyc` in the tool-chain:

* it provides a simple CLI interface for outputting tests in various formats:
  * HTML which helps you dig into where your coverage is lacking.
  * lcov which allows you to pipe it to coveralls, which @rauchg had requested for badges.
* nyc also supports sub-processes, which is useful for instrumenting everything in the `next.js/bin`.

any ways, I would happily help write some more tests, but my personal preference would be to stick with AVA right now and to get some more tests written; rather than swapping technologies.

@sindresorhus can you speak the the advantages/disadvantages of using AVA vs. Jest for testing a react application, I was reading this document on the technical considerations:

https://github.com/avajs/ava/blob/master/docs/recipes/react.md

**Comment by nkzawa** [comment]
This tweet makes sense https://twitter.com/sindresorhus/status/774244618057555970
We are trying to introduce `babel-core/register` but it will gradually make our tests slow.
I think `Jest` can be a better choice for next.js.

**Comment by arunoda** [comment]
I also like to move into Jest. Since we don't have many tests, it's better to decide this soon and work on actually writing tests.
