### ISSUE TITLE
Tests not run on with-jest example

### ISSUE THREAD

**Issue by langpavel** [zeit/next.js#2441]
Hi

I followed instruction in README at https://github.com/zeit/next.js/tree/v3-beta/examples/with-jest,
but it looks like `babel-jest` is not in use and test will fail like this:
```
$ jest
 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    /home/langpavel/Projects/work/next-with-jest/__tests__/index.test.js:3
    import { shallow } from 'enzyme';
    ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.814s
Ran all test suites.
```
```
$ jest --version
v20.0.4
$ node --version
v8.1.3
```
I installed packages with both, `yarn` and `npm`

**Comment by timneutkens** [comment]
<img width="532" alt="screen shot 2017-07-02 at 20 08 38" src="https://user-images.githubusercontent.com/6324199/27772419-490d6d64-5f62-11e7-8eaf-6e3f1b1a5bb6.png">

I can't reproduce this.

**Comment by langpavel** [comment]
@timneutkens Weird. I tried it again and it didn't work. :disappointed:

**Comment by timneutkens** [comment]
That's super weird.

**Comment by timneutkens** [comment]
Without a reproduction we can't really fix it :/

**Comment by pex** [comment]
@langpavel you might try to add the `--no-cache` option to jest. More on this [in their docs](http://facebook.github.io/jest/docs/en/cli.html#cache).

**Comment by timneutkens** [comment]
@pex interesting, thanks!

**Comment by langpavel** [comment]
Wow! Thanks @pex

**Comment by jcollum** [comment]
`--no-cache` fixed it for me
