### ISSUE TITLE
Add example of how to use next.js with other root directory.

### ISSUE THREAD

**Issue by Industrial** [zeit/next.js#2444]
Hi.

I'm having trouble settting up next.js to work with my gulp setup. I have a `src` and `build` directory and I would like next.js to take the build directory as it's root (so also where to find the next.config.js etc).

I have set my npm task to `next dev ./build` but that doesn't seem to work.

It would be nice to have a runnable example that shows this feature.

**Comment by timneutkens** [comment]
`next dev <dir>` in this case `<dir>` is actually the `.next` directory name where it compiles to. You can see the explanation for the full command by running `next dev --help`. It's the same as setting `distDir` https://github.com/zeit/next.js#custom-configuration.

What you want to do is possible using the custom server api:
https://github.com/zeit/next.js/blob/v3-beta/examples/custom-server-express/server.js#L5

If you change that line to `const app = next({ dev, dir: './build' })` it'll work 👌

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/blob/v3-beta/server/index.js#L28 shows all available options

**Comment by timneutkens** [comment]
It's also documented here: https://github.com/zeit/next.js#custom-server-and-routing
