### ISSUE TITLE
[Discussion] Pass initial props to "app.render()" method on server

### ISSUE THREAD

**Issue by delgermurun** [zeit/next.js#2447]
> Maybe it is too naive or crazy idea. If so just ignore and close it.

When we are doing SSR, how about passing initial props to `app.render()` method on server?

```js
  server.get('/checkout/:token', (req, res) => {
    const queryParams = { token: req.params.token }
    const initialProps = { checkout: getCheckoutDetail(req.params.token) }
    app.render(req, res, '/checkout', queryParams, initialProps)
  })
```

Something like that. In this example, `getCheckoutDetail` will work synchronously, so process will be blocked. But I'm pretty sure we can find some async way to do it.

Running code only on server (or client) is pretty complicated issue. I read @arunoda's article (https://arunoda.me/blog/ssr-and-server-only-modules), but unfortunately there is no nice clean way to do it.

If there is something like this, we can pass initial props on server without any hassle. On `getInitialProps` will `fetch` only on client.

What do you think? Thanks in advance.

_PS: You are doing great job. Thank you very much._

**Comment by arunoda** [comment]
I don't like passing initial props from the client side. But you can do the same with query params. Use `getInitialProps` to convert them as props.

With that, we don't need to introduce a new API.
