### ISSUE TITLE
Example app: fb-like chat tabs

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#245]
This is would be a really cool example of how to merge the worlds of simple page navigation (through `<Link>`) and global state (for chat tabs that persist across pages)

**Comment by jangerhofer** [comment]
Hey, @impronunciable:  is this something you have started?  Considered at all?

I'm in the midst of evaluating Next as an alternative to my beloved Meteor (Apollo was the impetus!) and am more than happy to build this example as a way to get a grasp on Next.  I am thinking something along the lines of a contact list that links to a profile page (for a total of two "routes" or pages).  Chat boxes for each contact can be opened and endure through page-changes.

Make sense?  Would it be helpful if I whip this up?

**Comment by impronunciable** [comment]
@jangerhofer I haven't started this but definitely want to do it and would help of course.

**Comment by blwsk** [comment]
Has anyone started working on this? I'd be interested in contributing

**Comment by timneutkens** [comment]
@blwsk no, go for it :smile: 👌 Thank you very much!

**Comment by chandrajob365** [comment]
@blwsk I'm Working on it . Happy to get any help

**Comment by blwsk** [comment]
@chandrajob365 feel free to mention me in the eventual PR, if interested

**Comment by chandrajob365** [comment]
@blwsk Sure 👍

**Comment by chandrajob365** [comment]
@blwsk : Didn't got option to mention anyone as reviewer

**Comment by chandrajob365** [comment]
@arunoda  @timneutkens @impronunciable  @rauchg  "CoverageAll"is failing but in `package.json` I just changed `"license": "ISC" -> "license": "MIT"` ?
https://github.com/zeit/next.js/pull/2591

**Comment by chandrajob365** [comment]
@timneutkens : Is there something that I need to change in this PR or its good to go ?

**Comment by frol** [comment]
@chandrajob365 There is a typo in the CSS: https://github.com/chandrajob365/next.js/blob/f2fe4ce8eb8410da119216ad6e5963c456854eb9/examples/fb-like-chat-tab/components/chatPannel.js#L18 (unnecessary `'` before `1px`).

Also, due to the #88, all the "chats" will get re-rendered on every navigation and the scrolling position will be lost.

**Comment by timneutkens** [comment]
I'm going to close this issue as it's been open for 2 years.
