### ISSUE TITLE
npm run build throws multiple errors field browser doesn't contain valid alias configuration

### ISSUE THREAD

**Issue by Kielan** [zeit/next.js#2450]
npm run build throws multiple errors including:

nModule not found for all top level file paths 
the output is very ugly with whitespace slashes in the console output.

Field \'browser\' doesn\'t contain a valid alias configuration.

on the nextjs examples next is able to build, err occurs only in new and currently up to date projects of the app project directory. 

so I guess my question is, why is the path for building broken?

* Next.js version:
* Environment:
node -v v7.8.0
npm -v 4.2.0
next -v 3.0.1-beta.7^
* Operating System : macOS

**Comment by timneutkens** [comment]
I just saw this happen to someone else too. It seemed like he installed `react` and `react-dom` version 16 alpha/beta. Could you check that? 😄

**Comment by Larry850806** [comment]
I also have this problem. I am not using react 16.
