### ISSUE TITLE
componentDidMount is not triggered on inner components

### ISSUE THREAD

**Issue by mike3run** [zeit/next.js#2453]
```js
export default class Example extends Component {
  constructor (props) {
    super(props)
    this.state = {
      loaded: false
    }
  }

  componentDidMount () {
    this.setState({
      loaded: true
    })
  }

  render () {
    let { loaded } = this.state
    return loaded
      ? <p>💕</p>
      : <p>Loading...</p>
  }
}
```

Everything stays in loaded false state probably because componentDidMount never gets triggered, my folder structure is

- pages -> index.js
- components -> example.js

Running on latest version of next.js

Is this behavior intended?

**Comment by sergiodxa** [comment]
It's not intended, and in fact Next.js should not be affecting that, can you provide a repo to reproduce it? I think something else it's wrong 🤔

**Comment by timneutkens** [comment]
I'll re-open when there's an example to reproduce.

**Comment by mike3run** [comment]
Thanks, I'm trying to make the example as minimal code as possible 😢 

But basically im using dotenv and also next-routes with some getInitialProps maybe its too much stuff in the mix??
