### ISSUE TITLE
Faied to fetch when changing route via <Link /> component

### ISSUE THREAD

**Issue by nathanqueija** [zeit/next.js#2454]
Hello, I get the error: failed to fetch when I change the route via component <Link />
If I go straight on the route where I use the getInitialProps function to make an http call I do not get the error, however if I navigate in the route via Link I get this error.

**Comment by nathanqueija** [comment]
This is happening because of CORS:
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

But if I navigate directly to the route without the Link component I don't get this error.

**Comment by mattfysh** [comment]
@nathanqueija I'd say this is because when you navigate directly to the URL, the page is rendered on the server where the CORS restrictions do not apply.

**Comment by nathanqueija** [comment]
Thanks for your response man.
I am a newbie in this server side thing, do you know a workaround for this?
Because I want to execute getInitialProps when the user navigate directly to the URL.

**Comment by mattfysh** [comment]
@nathanqueija if you own the endpoint, add the required CORS headers to it. Otherwise you need to route the request via an endpoint on the server. Take a look at the "Custom server and routing" section of the docs. Cheers  :)

**Comment by nathanqueija** [comment]
Ok, man. I'll do it. Thanks for your attention.
