### ISSUE TITLE
Window reload after navigate to new page on dev: Hard reloading due to no default component in page: /../../manifest

### ISSUE THREAD

**Issue by nantaphop** [zeit/next.js#2458]
This problem only occurred in `next` dev only. `next build` then `next start` will not have this issue

Let say I start `next dev` then I go to Page A.
Next, I click on link to  Page B. This time next.js log say Building Page B
Then, log said Build Finish and Window Reload but I still on Page A.
Lastly, click on link to Page B. this time I can go to Page B.

Following client log might help.
```
App is changing to:  /b  // log router change by Router.onRouteChangeStart
VM61585 commons.js:47812 [HMR] bundle rebuilding
VM61585 commons.js:8949 Hard reloading due to no default component in page: /../../manifest // What is this page???
VM61585 commons.js:47820 [HMR] bundle rebuilt in 514ms // Building Page B Finish
VM61585 commons.js:47901 [HMR] Checking for updates on the server...
VM61585 commons.js:47972 [HMR] Nothing hot updated.
VM61585 commons.js:47981 [HMR] App is up to date.
Navigated to http://localhost:3001/a // Why it navigate back to Page A
```

The log that said `Hard reloading due to no default component in page` come form [webpack-hot-middleware-client.js](https://github.com/zeit/next.js/blob/f4345e79c254cff935fa5c4a7949ee4b0834cd78/client/webpack-hot-middleware-client.js)

which have a comment and call window.reload()
```
        // This only happens when we create a new page without a default export.
        // If you removed a default export from a exising viewing page, this has no effect.
        console.log(`Hard reloading due to no default component in page: ${route}`)
        window.location.reload()
```

next@3.0.0-beta9
Chrome Version 59.0.3071.115

**Comment by arunoda** [comment]
@nantaphop you are using a pretty old version of Next.js beta.
Use the latest beta.

**Comment by nantaphop** [comment]
@arunoda oh, updated and solved
