### ISSUE TITLE
Scroll position gets reset after setting on Safari

### ISSUE THREAD

**Issue by jedrichards** [zeit/next.js#2459]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behaviour

When navigated using `<Link scroll={false}>` the component below should restore the saved scroll position when the component mounts.

```
let scrollY = 0

export default class Thing extends Component {
  constructor(props) {
    super(props)
    this.onScroll = this.onScroll.bind(this)
  }

  onScroll(e) {
    scrollY = window.scrollY
  }
  
  componentDidMount() {
    window.addEventListener('scroll', this.onScroll)
    window.scroll(0, scrollY)
  }

  componentWillUnmount() {
    window.removeEventListener('scroll', this.onScroll)
  }

  ...
}
```

## Current Behaviour

The code works on latest Chrome (macOS) and Edge (Windows 10), but fails on Safari 10 (macOS). 

The behaviour I'm observing in Safari is that the scroll position is first briefly set to my correct saved position, but then another scroll event is fired and the scroll position reset somewhere nearer the top of the page (always the same pixel value). I think it might have something to do with component load order, or a race condition, since I'm observing the problem on a fairly image heavy page.

## Steps to Reproduce (for bugs)

There's a live example here http://www.gillythomas.co.uk

1. Using Safari 10 visit the site and scroll down the page to near the bottom
2. Click an image to view a larger version
3. Click the "back to gallery" button
4. Observe that the scroll position wasn't properly restored
5. Try on different browsers, should work well on Chrome for example

## Context

This is using the Next.js v3 beta and new static site output feature. I'm just trying to persist the scroll position on a page, but its not working on Safari.

## Your Environment

* Next.js version: `3.0.1-beta.8` static export
* Environment name and version (e.g. Chrome 39, Node.js 5.4): Safari 10
* Operating System (Linux, maxOS, Windows): macOS

**Comment by arunoda** [comment]
I'm quite not exactly sure why that's happening. It seems like images are loading (or rendering again) and that's completing after the `componentDidMount`.

I'm quite not sure who's responsible for this issue.
But you can do something like this:

```js
function tryScrolling(amount, after) {
   setTimeout(() => window.scroll(0, amount), after)
}

componentDidMount() {
  window.addEventListener('scroll', this.onScroll)
  tryScrolling(scrollY, 0)
  tryScrolling(scrollY, 100)
  tryScrolling(scrollY, 500)
  tryScrolling(scrollY, 1000)
}
```

I don't think there's something we (Next.js) can do about this.

**Comment by arunoda** [comment]
BTW: Thanks a lot for using the issue template. That's the best help you can do about this.

**Comment by jedrichards** [comment]
Hmm, I was assuming since Next.js is playing with the scoll position a bit in the `<Link />` component it might be framework related. I'll try your approach ...
