### ISSUE TITLE
No router found 

### ISSUE THREAD

**Issue by timlind** [zeit/next.js#2460]
On Safari the page loads and subsequent transition gives fails giving an error in dev console "No router instance found. You should only use "next/router" inside the client side of your app."

![screen shot 2017-07-04 at 1 34 49 pm](https://user-images.githubusercontent.com/237741/27828723-feed00e8-60bd-11e7-9d1c-3ac815b16bd5.png)

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Page transition

## Current Behavior

Failure to transition page

## Steps to Reproduce (for bugs)

1. Load page
2. Click link

## Your Environment

* Next.js version: next.js v2.4.6
* Environment name and version (e.g. Chrome 39, Node.js 5.4): Safari / Node 7.2
* Operating System (Linux, maxOS, Windows): OSX

**Comment by timneutkens** [comment]
@timlind I can't reproduce this.

**Comment by arunoda** [comment]
I think this has to do with something used in your app. Could you send us a reproduce the bug into a smaller repo. We can't see this in our apps.

This could only happens, if you've two versions of Next.js in your app.
That's possible, if you are using a module which depends on `next` inside it.
If so, ask that module owner to use a peerDependency for `next`.

**Comment by arunoda** [comment]
Please reopen, when you've the minimal sample repo.
