### ISSUE TITLE
with-apollo fails to build 

### ISSUE THREAD

**Issue by timlind** [zeit/next.js#2461]
Following instructions on with-apollo example on master (v2.4.6) fails to build.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Should build and run.

## Current Behavior

> Failed to build on /var/folders/g0/40w25pdx4r166gr3dr2dszr80000gn/T/73a90ccb-e790-431e-bab9-5ffba7560413
{ Error: ./components/App.js
Module not found: Error: Can't resolve 'next/node_modules/styled-jsx/style.js' in '/Lair/with-apollo/components'
resolve 'next/node_modules/styled-jsx/style.js' in '/Lair/with-apollo/components'
  Parsed request is a module
  using description file: /Lair/with-apollo/package.json (relative path: ./components)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Lair/with-apollo/package.json (relative path: ./components)
    resolve as module

## Steps to Reproduce (for bugs)

1. Follow instructions to download with-apollo example
2. next build
3. observe build error
4.

## Your Environment

* Next.js version: v2.6.4
* Environment name and version (e.g. Chrome 39, Node.js 5.4): node 7.2
* Operating System (Linux, maxOS, Windows): osx

**Comment by timneutkens** [comment]
@timlind I can't reproduce this 🤔

**Comment by timlind** [comment]
@timneutkens are you building with next v2.4.6 or latest, I see on the master branch the dependency is still set to "latest" which is 3 correct?

**Comment by timneutkens** [comment]
latest is 2.x, and I tried it with that :)

**Comment by timlind** [comment]
looks like this was just an issue with npm silently skipping some dependencies, used yarn and it worked.

**Comment by timneutkens** [comment]
:/ Damn
