### ISSUE TITLE
webpack.DefinePlugin is not working on next.config.js

### ISSUE THREAD

**Issue by hank7444** [zeit/next.js#2465]
# next.config.js
![image](https://user-images.githubusercontent.com/4727090/27853502-7e0434b4-6195-11e7-82c3-fa045822bd6e.png)

# pages/index.js
![image](https://user-images.githubusercontent.com/4727090/27853513-87341234-6195-11e7-941a-62fabbb49316.png)

# result
![image](https://user-images.githubusercontent.com/4727090/27853537-9d020c9c-6195-11e7-8c78-30b35e233159.png)

Does it mean I lost something @@?

**Comment by timneutkens** [comment]
Please see https://github.com/zeit/next.js/tree/v3-beta/examples/with-universal-configuration

**Comment by mrsteele** [comment]
I wanna submit that this issue gets reopened.

While you have solved the underlining issue for @hank7444 there may be other use-cases and workflows that still depend on DefinePlugin.

All to say I believe the issue still stands that the variables defined in `webpack.DefinePlugin` do not exist in the bundled files.

**Comment by tgdn** [comment]
Completely agree, this is still not possible. `ReferenceError` is always thrown. @timneutkens your solution has caveats as says the readme

**Comment by Deval520** [comment]
why did you close this issue,what's the solution? i also met this problem too recently!

**Comment by Deval520** [comment]
what's the solution? i also met this problem too recently! @timneutkens

**Comment by makstr** [comment]
it works for me 
``` 
const webpack = require('webpack'); // eslint-disable-line
const FRONTEND_ENV_KEYS = [
	'NODE_ENV',
	'IS_STATIC',
	'API_URL',
	'CONTENTFUL_SPACE',
	'CONTENTFUL_ACCESS_TOKEN'
];

const envPlugin = FRONTEND_ENV_KEYS.reduce(
	(result, key) =>
		Object.assign({}, result, {
			[`process.env.${key}`]: JSON.stringify(process.env[key])
		}),
	{}
);

module.exports = {
	webpack(cfg) {
		// make selected env vars avail on client
		cfg.plugins.push(new webpack.DefinePlugin(envPlugin));
		return cfg;
	}
	// exportPathMap: require('./next.exportPathMap').exportPathMap
};
```

**Comment by matthewmueller** [comment]
^ not sure why everyone downvoted this. it works fine and it's something I've been using for at least a year now.
