### ISSUE TITLE
Exmple how to render breadcrumb serverside?

### ISSUE THREAD

**Issue by ndelangen** [zeit/next.js#2466]
I'm interested in printing or gaining access the current path for rendering a breadcrumb serverside.

I've tried gaining access to the current route via `'next/router'` but it's a client-only package?

How would you suggest to do this?

**Comment by timneutkens** [comment]
@ndelangen the url is provided in getInitialProps. After v3 we're going to add a HOC which allows you to get the route on server/client side https://github.com/zeit/next.js/pull/2352

**Comment by notrab** [comment]
You could use `props.url.pathname` to do this. There is a PR open #2352 for a withRoute HOC which may help you when that merges 😎

**Comment by mrdulin** [comment]
same issue.

**Comment by shubham-2710** [comment]
Same Issue

**Comment by timneutkens** [comment]
How can you possibly have the same issue as a 12 months old resolved issue 🤔
