### ISSUE TITLE
Using Head and Link components with TypeScript

### ISSUE THREAD

**Issue by corydeppen** [zeit/next.js#2472]
The with-typescript example [mentions](https://github.com/zeit/next.js/blob/v3-beta/examples/with-typescript/README.md) the following about using the `Head` and `Link` components with TypeScript:

```
In tsconfig.json the options jsx="react" compiles JSX syntax into nested React.createElement calls.
This solution doesn't work well with some Next.js features like next/head or next/link.
The workaround is to create JS files that just return the mentioned module and require them from TSX files.
```

While I have sporadically seen an error using these components, I was wondering if there is/will be an effort to prevent having to write these workarounds in the future. As someone who's evaluating Next.JS at the moment, the TypeScript support seems to be hit or miss and I'm trying to get a sense for whether the plan is to treat it as a first-class citizen within Next.JS going forward.

**Comment by timneutkens** [comment]
Tracked here: https://github.com/zeit/next.js/issues/2391
