### ISSUE TITLE
No source maps for server side execution

### ISSUE THREAD

**Issue by emattias** [zeit/next.js#2474]
When outputting `debugger` keywords in my code and connecting my IDE to the node debugger it is breaking in the compiled code, not the uncompiled code. Sourcemaps are stripped from custom codes/pages/etc.

The commons.js and main.js files follow the sourcemaps settings (`devtool: cheap-module-eval-source-map` in webpack settings by default)

Could this be related with the custom babel setting that are used for node?
 -> https://github.com/zeit/next.js/blob/v3-beta/server/build/webpack.js#L205 🤔 

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
The compiled custom code in the .next/dist folder should have sourcemaps generated according to settings in webpack/babel.

## Current Behavior
No sourcemaps are generated for custom code accessible for server side debugging. The sourcemaps are however accessible on client side.

## Steps to Reproduce (for bugs)
1. Create a next.js project with a index.js page and sourcemaps enabled (at time of writing the default setting)
2. Run `next`to start dev server
3. Open `.next/dist/pages/index.js` and scroll down to the bottom of the file. It will have no `//# sourceMappingURL` comment
3. Open `.next/dist/main.js` and scroll down to the bottom of the file. It will have a `//# sourceMappingURL` comment!

**Comment by timneutkens** [comment]
I believe fixing https://github.com/zeit/next.js/issues/2285 will fix this too. Lets track it there 👌
