### ISSUE TITLE
Symbol entities like &rarr; do not render properly

### ISSUE THREAD

**Issue by jdan** [zeit/next.js#248]
I first noticed then while trying to add `&raquo;` to my markup, which was rendering as `Â»`.

![image](https://cloud.githubusercontent.com/assets/287268/20247819/57645824-a98b-11e6-8bf0-b4aaf3323d66.png)

Curiously, HMR seems to handle this just fine! I can change my markup to include `&raquo;` and save, and `»` shows up as expected. A hard refresh, however, results in `Â»`.

As a quick repro you can save the following as `pages/symbol.js`:

```
import React from "react"
import Head from "next/head"

export default () => <div>
    <Head>
        <meta charset="utf-8" />
    </Head>
    &rarr;
</div>
```

Note that `create-react-app` does not seem to suffer from this problem.

**Comment by jdan** [comment]
Looks like this is a problem with glamor's `renderStatic` method. I filed it here: https://github.com/threepointone/glamor/issues/110

**Comment by nkzawa** [comment]
I can't reproduce the problem. It seems these symbols are correctly rendered to me.

```js
test(async t => {
  const html = await render('/symbol')
  t.true(html.includes('&rarr;'))
})
```

This test fails, but if I change it to the actual value (`→`), it succeeds.

**Comment by nkzawa** [comment]
These html special chars are converted to the actual character when transpiling JSX. And it seems you'd have to set `<meta charset="utf8" />` using `<Head />` component 

https://github.com/facebook/react/issues/1177

**Comment by jdan** [comment]
@nkzawa Yes, my apologies, my original repro doesn't seem to point out the issue. I went ahead and modified it.

I am still unable to get the character to display correctly, even with `<meta charset="utf-8">` (or "utf8") as pointed out above). Curiously, I see the following in "View source," suggesting that `<meta charset>` doesn't appear until mount?

```
<!DOCTYPE html><html><head><title class="next-head">Hello, world! | jordan scales | jordan scales</title><meta class="next-head"/><style>
```

In DevTools, that `<meta>` has a `charset` after the page rehydrates.

**Comment by jdan** [comment]
A-ha, `charSet` not `charset`! No issue here, thanks for your help.
