### ISSUE TITLE
Enhancement: Types on DefinitelyTyped

### ISSUE THREAD

**Issue by Dru89** [zeit/next.js#2484]
Hey guys!

I noticed that, while you had a typescript example, none of the modules that you provided had types written for TypeScript.  I took some time to read through most of the code at a high level and gleaned what I thought the expected "public-facing API" was from it.

If you have some time to review, I'd love for someone to look at DefinitelyTyped/DefinitelyTyped#17781 and make sure that I wasn't either over-exposing something you meant to keep private or not exposing something you expected to be public.

Thanks!

**Comment by timneutkens** [comment]
just checked it out, looks good!
