### ISSUE TITLE
Hard refresh needed when HMR expected

### ISSUE THREAD

**Issue by Sotorin** [zeit/next.js#2486]
This is very simple react component run from 'pages/index.js' (sorry, but I don't know why the code is not formatted properly in this example).

If I change input value to, say, 'click Me' then the page is HMR'ed and changes are immediately reflected in the browser. However, if I change `console.log` in the `handler()` to, say, 'some other message' then changes are not reflected in the browser and I have to do a hard refresh to pick up the changes. I would think that this change should be picked up but I could be wrong and it's normal.

```
export default class Test extends React.Component {
    handler = () => { console.log('some message')}
    render () {
      return ( <input type="button" value="click" onClick={this.handler} />) 
   }
}
```

- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

If I change `console.log('message')` to `console.log('some message')` and save the file and click the button then I would expect this changes to be picked up by HMR and see 'some message' in the browser's console output

## Current Behavior

I don't see these changes and I have to do a hard refresh in order to see them in the browser.

## Steps to Reproduce (for bugs)

1. Just run the sample code provided and change variables as described.
2.
3.
4.

## Context

It's not affecting me in any meaningful way. I can do a hard refresh if that's by design.

## Your Environment

* Next.js version: 3.0.1-beta.8
* Environment name and version (e.g. Chrome 39, Node.js 5.4): Node 8.x, NPM 5
* Operating System (Linux, maxOS, Windows): OSX Sierra

**Comment by arunoda** [comment]
Use a normal class method like this for the `handler`

```js
import React from 'react'

export default class Test extends React.Component {
    handler ()  {
      console.log('some message 44')
    }

    render () {
      return ( <input type="button" value="click" onClick={() => this.handler()} />)
   }
}
```

react-hot-loader doesn't work well with function defined as class variables.
