### ISSUE TITLE
Is it possible to define routes as in react-router

### ISSUE THREAD

**Issue by japesh** [zeit/next.js#2488]
Hello everyone,
I have just started to use nextJS. 
I am trying to move forward and backward between pages using animation.
But since whole page renders every time i loose track of whole DOM.
Is their any way to implement shallow routing as in react router, that is rather reloading whole page we can define routes to load or reload only specific part of page.

**Comment by arunoda** [comment]
Sorry. That's not possible.

**Comment by japesh** [comment]
Ohk, can you suggest me  any solution for it.

**Comment by arunoda** [comment]
Please search the issue list

https://github.com/zeit/next.js/search?q=animations&type=Issues&utf8=%E2%9C%93
