### ISSUE TITLE
Next + Jest does not support common .babelrc

### ISSUE THREAD

**Issue by pex** [zeit/next.js#2499]
I recently tried to define special presets in `.babelrc` only for test environment in [with-jest example](https://github.com/zeit/next.js/tree/v3-beta/examples/with-jest).
When importing a file for testing that uses React and/or StyledJSX and that does not manually `import` React and/or StyledJSX, the test will fail with following error message:
```
SyntaxError: Unexpected token import
```
This is because the automatically added imports of React/StyledJSX are always es2015 style module imports. 

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

A simple `.babelrc` that only defines a special `test` env should be possible.
In my opinion it should be possible to use the following `.babelrc`:
```json
{
  "presets": "next/babel",
  "env": {
    "test": {
      "presets": [
        "env",
        "next/babel"
      ]
    }
  }
}

```

I played with this issue [on a separate branch](https://github.com/pex/next.js/tree/jest-babel-next-issue). Currently you could work around this issue by importing React & StyledJSX manually:

  ```javascript
  import React from 'react'
  import _JSXStyle from 'styled-jsx/style'
```

## Current Behavior

Either you define `development`, `production` and `test` envs in `.babelrc` whereas `development` and `production` or you manually import React / StyledJSX. Otherwise tests with JEST will fail.

## Steps to Reproduce (for bugs)

1. Goto `examples/with-jest`
2. Simplify your `.babelrc` as proposed
3. Run `$ npm run test`

**Comment by sergiodxa** [comment]
That looks more like a problem with how Babel it's handling the multi-environment presets when you define a default one 🤔

**Comment by arunoda** [comment]
@pex  for the test you need to use this babel-preset I guess:

```js
{
  "env": {
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ]
    }
  }
}
```

And do not use `next/babel` on the top.

**Comment by arunoda** [comment]
@sergiodxa I think the issue is, `["env", { "modules": "commonjs" }]` should run before `next/babel` in test.

If you set a default one. It'll run always at first.

**Comment by pex** [comment]
Thank you for your quick response @arunoda . Unfortunately those suggestions won't fix the issue. I added your suggestions to `.babelrc` to https://github.com/pex/next.js/commit/220d7a8e30cb244524f942434197725a0a5aa75d and tests fail with the same message they did before.

Another note on this:
- I am not sure about what the impact of switching order of `next/babel` and `env` is;
- Writing `["env", { "modules": "commonjs" }]` is obsolete, though. Since this is default in `env`: https://babeljs.io/docs/plugins/preset-env/#optionsmodules

**Comment by willmeierart** [comment]
@pex / anyone having this trouble in the future: 
can confirm that @arunoda 's advice worked for me, with the following .babelrc:
`
{
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["."],
        "alias": {
          "styles": "./styles"
        },
        "cwd": "babelrc"
      }
    ],
    [
      "wrap-in-js",
      {
        "extensions": ["css$", "scss$"]
      }
    ]
  ],
  // "presets": ["next/babel"],
  "ignore": [],
  "env": {
    "test": {
      "presets": [["env", { "modules": "commonjs" } ], "next/babel"]
    },
    "dev": { "presets": ["next/babel"] },
    "production": { "presets": ["next/babel"] }    
  }
}
`
the commented-out 'presets' line worked in every env except test. once I added the separate dev/production env presets individually, everything works.
