### ISSUE TITLE
next-dev CLI should take hostname argument

### ISSUE THREAD

**Issue by sco** [zeit/next.js#2500]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

`next dev` should accept the -H/--hostname argument, like `next start` (see #1017).

## Current Behavior

`next dev` ignores the hostname argument, defaulting to `localhost`.

## Context
Cloud9 wants servers to start on 0.0.0.0

I am happy to provide a PR for this if you agree.

**Comment by timneutkens** [comment]
Sure we can take this in.
