### ISSUE TITLE
I can't run (v3-beta)with-static-export example

### ISSUE THREAD

**Issue by Nyuno** [zeit/next.js#2504]
https://github.com/zeit/next.js/tree/v3-beta/examples/with-static-export
I have tried to use with static export example, and I got an error when I run ```npm run dev```.
the error looks like this on ```next.config.js``` file
```
SyntaxError: Unexpected identifier
async exportPathMap
           ^^^^^^^^^^^^^^
```
I think I follow the instruction to run this.
Is there anything I am missing?

Thanks for the help in advance.

**Comment by arunoda** [comment]
Make sure you've Node8.
