### ISSUE TITLE
Custom babel config with webpack

### ISSUE THREAD

**Issue by rohmanhm** [zeit/next.js#2517]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

My app run smoothly.

## Current Behavior

Throw error

## Steps to Reproduce (for bugs)

I have typescript project, which I cannot use `.babelrc` to my project. So I decided to make custom babel config via webpack (`next.config.js`).
This is my custom config in my `next.config.ts`
```tyepscript
module.exports = {
  webpack: (config: Webpack.Configuration) => {
    (config.module as Webpack.NewModule).rules.push({
      test: /\.js$/,
      exclude: /(node_modules|bower_components)/,
      use: {
        loader: 'babel-loader',
        options: {
          plugins: [
            [require('babel-plugin-module-resolver'), {
              root: './',
              alias: {
                '@': './app'
              }
            }]
          ]
        }
      }
    })

    return config
  }
}
```
That will throw an error 
>  error  in ./dist/pages?entry
Module build failed: Error: Plugin 0 specified in "base" provided an invalid property of "defaultExtensions"

Any solution to write babel config via webpack config without `.babelrc` file?

## Your Environment

* Next.js version: next
* Environment name and version (e.g. Chrome 39, Node.js 5.4): node 8
* Operating System (Linux, maxOS, Windows): macOS

**Comment by rohmanhm** [comment]
For now, I fixed by using `.babelrc`.
I don't need to have `.babelrc` file inside my project

**Comment by arunoda** [comment]
Since you can use use `.babelrc` I'm gonna close this.
