### ISSUE TITLE
Can't find a solution to get sass frameworks to be working

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#2519]
I read the issues and [docs](https://github.com/zeit/next.js/tree/v3-beta/examples/with-global-stylesheet) but i have to admit that i can't find a solution to my problem. 

I am trying to use some sass frameworks like compass and susy. But i can't. 

I understand that i can't only use webpack loader but maybe i've missed something but i don't know how to implement them in my project.

I am struggling with this error since many days : 

```
Module build failed: 
  @include container(600px);
          ^
      No mixin named container
```

I changed so many times my webpack configuration 

```javascript
//Current next.config.js setup
{ test: /\.s(a|c)ss$/,
        use: [
          'babel-loader', 'raw-loader', 'postcss-loader',
          { loader: 'sass-loader',
            options: {
              includePaths: ['node_modules', 'node_modules/compass-mixins/*']
                .map((d) => path.join(__dirname, d))
                .map((g) => glob.sync(g))
                .reduce((a, c) => a.concat(c), [])
            }
          }
        ]
      }
```

Nevertheless, i'm still in the wrong way. 
I know i can't just use webpack but I just need some advices to help me to understand in which way i can use these framworks and fix this issue. I am so desperate now. 

Thanks.

**Comment by dvakatsiienko** [comment]
+1 on this. Actually I'm watching next.js repository for about of couple of weeks about this topic ( a good way to connect css preprocessors ). But still there is no a really convenient and beautiful (sigh) solution. I've managed to connect `scss` to our project but in really clunky and fragile way. 
As far as I saw, a significant chunk of people suffers cuz of limited support of `css preprocessors` by next. Including me and my team. Just saying.

**Comment by jackmatrix** [comment]
Update. I fact, compass is okay and working without any problem. I just need to keep  into my `includePaths` the following line : 

`node_modules/compass-mixins/*`

when i remove it, compass is no longer working.

So i've tried to include directly the susy path but it doesn't made the deal neither. 

It's drive me crazy i really can't understand why the compass mixins are working and it's not the same for the susy ones.

**Comment by jackmatrix** [comment]
Ok got it seems the new version of susy just removed all the mixins. So that explain my issue. Anyway my postcss/webpack config is good and i just have to fix it on the susy side.
