### ISSUE TITLE
next can get the nuxt good function about middleware 

### ISSUE THREAD

**Issue by fxh615** [zeit/next.js#2522]
nuxt is a great framework , and next have more to learn about. eg : middleware about router for client-side and server-silde . come on next.

**Comment by supra28** [comment]
@fxh615 Have you tried next-routes?

**Comment by arunoda** [comment]
Thanks @fxh615 
We want to make things simple as possible.
And the top priority is not features but the stability and performance.

And we want to do most of the things in the user space. Like next-routes.
Anyway, we'd like to pick good stuff from anyway we like.

**Comment by supra28** [comment]
@arunoda Can we expect next-routes to become a first class citizen in next.js in the future?
for the reasons like the one's mentioned  [here](https://github.com/zeit/next.js/issues/2487#issuecomment-314050061)
