### ISSUE TITLE
Improve with-ant-design example

### ISSUE THREAD

**Issue by plxel** [zeit/next.js#2524]
It will be great to have customzing default theme sample in [ant-design example](https://github.com/zeit/next.js/tree/master/examples/with-ant-design)

## Expected Behavior
The way how to do it is described in [offical docs](https://ant.design/docs/react/customize-theme)
And there is link to more informative article on [medium](https://medium.com/@GeoffMiller/how-to-customize-ant-design-with-react-webpack-the-missing-guide-c6430f2db10f)

## Current Behavior
Now we have ant-design example with default theme

## Steps to Reproduce (for bugs)
I followed the article, but in the end my app is not compiled:
`SyntaxError: Invalid or unexpected token`

I have created [repository](https://github.com/plxel/nextjs-ant-design-custom-theme) based on with-ant-design example with config similar to medium article

 ##

Need some help with understanding this error and how can I solve it

**Comment by aoc** [comment]
I've been using antd with custom themes taking some config from [with-global-stylesheet](https://github.com/zeit/next.js/tree/v3-beta/examples/with-global-stylesheet) example.

I set up a repo so you can check my current config: https://github.com/aoc/with-ant-design-custom-theme

hope it helps

**Comment by plxel** [comment]
@aoc 
Hi. great, it works. thank you
I have fixed my [example](https://github.com/plxel/nextjs-ant-design-custom-theme), also I added ExtractTextPlugin, if anybody want to extract resulting css into seperate file.

**Comment by Mantak** [comment]
how about importing components on demand ?

https://ant.design/docs/react/use-with-create-react-app#Use-babel-plugin-import

**Comment by notsu** [comment]
@Mantak Does it really work on server-side? I have  `SyntaxError: Invalid or unexpected token` issue that can't be compiled CSS or LESS.
