### ISSUE TITLE
_document HMR is lagging

### ISSUE THREAD

**Issue by felixrabe** [zeit/next.js#2525]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

This `pages/_document.js` does change color only after 2 triggered HMRs:

```jsx
import Document, {Head, Main, NextScript} from 'next/document';

export default class MyDocument extends Document {
  static getInitialProps(ctx) {
    return super.getInitialProps(ctx);
  }

  render() {
    return (
      <html>
        <Head>
          <style jsx global>{`
            body {
              color: green;
            }
          `}</style>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
};
```

This is in a fresh project (`yarn add next@^3.0.1-beta react react-dom`, hello world `pages/index.js`  and the above in `pages/_document.js`), running server with `yarn next`.

## Expected Behavior

When I edit `color: green` to another color (e.g. red) and save, page updates to show the new color.

## Current Behavior

When I edit `color: green` to another color (e.g. red) and save, _page stays green_. Then I edit the color again (e.g. black) and save, _page becomes red_.

## Context

Trying to get a new project with some global styling going.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     2.4.7 and 3.0.1-beta.13 (using styled-jsx 1.0.8)    |
| node    |     8.1.3    |
| OS      |    OS X 10.9.5     |
| browser |     Chrome 59    |
| editor     |  Sublime Text 3 (build 3141)       |

**Comment by felixrabe** [comment]
`pages/index.js` reloads just fine (content and style). Also, if I change something other than the style in `pages/_document.js`, it also reloads fine. E.g. if I add some text to the body, and I change both text and CSS in one save, I see the text updating fine, but the CSS lagging behind as described.

So, this might be an issue with styled-jsx.

**Comment by timneutkens** [comment]
Since `_document.js` is not loaded the same way other React components are and it's also only rendered server side, it works a bit different from a normal component. Please use a normal `<style>` tag. This has been explained in previous issues too 👌 Thanks!

**Comment by felixrabe** [comment]
Thanks for the solution and short explanation - changing to plain `<style>` works.

**Comment by timneutkens** [comment]
Great! 👍 👍
