### ISSUE TITLE
Can we have environment NODE_ENV=development

### ISSUE THREAD

**Issue by titellergetlinks** [zeit/next.js#2529]
package.json
```
"scripts": {
  "dev": "node server.js",
  "build": "next build",
  "start": "NODE_ENV=production node server.js",
  "start-dev": "NODE_ENV=development node server.js"
}
```

server.js
```
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
```
**I have 2 server (development and production) but i want development work like a production but database different.**

If dev is true the server will build every time when tester come to the website but i want to push process.env.NODE_ENV=development like a process.env.NODE_ENV=production.

**Comment by frol** [comment]
You can just use another environment variable for that, don't you? Leave `NODE_ENV` for Node and build purposes and use `CONFIG` to select the config presets.

**Comment by titellergetlinks** [comment]
@frol  Thank for reply my issue.

I have used another environment variable get undefined from browser (client-side) but on server side, I can get that environment variable.

I have used [with-universal-configuration](https://github.com/zeit/next.js/tree/v3-beta/examples/with-universal-configuration) but result is the same.

**Comment by frol** [comment]
@titellergetlinks `with-universal-configuration` is the right approach for your problem, and it works for me, so experiment more with it and get back with a specific question and/or code snippet which doesn't work for you. In any case, given this is not a bug, I suggest we move the further discussion to stackoverflow: https://stackoverflow.com/questions/tagged/next.js
