### ISSUE TITLE
NextJS doesn't support parsing nested objects in query parameters

### ISSUE THREAD

**Issue by pencilcheck** [zeit/next.js#2530]
- [X] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Expected at least nested objects be supported and parsed correctly from query

## Current Behavior

It takes the whole thing as a key, instead of creating an nested object
Doesn't matter the format, none of them works
`/?nested[key]=value`
or
`/?nested.key=value`

## Steps to Reproduce (for bugs)

1. Open the page with the pattern above
2. Print the this.props.url.query in top level page component
3. Does not work
4.

## Context

I can't pass nested object over arbitrarily if I am not using `<Link />` component, actually I'm not sure if `<Link />` would work with nested object since it is using npm 'url' which does not supported nested object parsing...

Btw, I'm currently using https://github.com/ljharb/qs for parsing atm, I hope this saves you all time if you are looking for alternatives.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    2.4.6     |
| node    |    8.1.3     |
| OS      |     macOS Sierra    |
| browser |    chrome     |
| etc     |         |

**Comment by arunoda** [comment]
Yes. This is something we should work on.
Will do this after 3.0.

Feel free to send us a PR.

**Comment by pencilcheck** [comment]
I think @chrismatheson has a PR, what do you all think?

**Comment by timneutkens** [comment]
See https://github.com/zeit/next.js/pull/2605#issuecomment-343774156

**Comment by chrismatheson** [comment]
im a little confused, @arunoda 's comments seem to imply that the feature is something that is desirable, but the issue has been closed? 

Would an implementation that uses something more lightweight than the `qs` lib be and adequate solution?

**Comment by arunoda** [comment]
@chrismatheson as @timneutkens mentioned size of the `qs` is the problem here.
We are open to use a smaller well maintained alternative (if exists)
