### ISSUE TITLE
Next.js SSR and side effects

### ISSUE THREAD

**Issue by masylum** [zeit/next.js#2532]
First of all, thanks for this amazing framework. We love the simplicity of it!

I have a question related to caching SSR pages.
We have a page that has a side effect (accessing the DB) but we always receive the same response with a very aggressive caching strategy. I've checked the source and discovered that all SSR pages contain [a cache control header ](https://github.com/zeit/next.js/blob/1c7b2603d4730dd4e6329d8dbd61447d07a7a2bb/server/index.js#L377).

While I understand the performance gains from it, how do you deal with pages that have side effects? Am I missing something?

Thanks in advance!

**Comment by masylum** [comment]
I got very confused! That was the build. I see the html actually gets an Etag, so everything is fine. We had a different bug that was not related to next. Sorry.

**Comment by timneutkens** [comment]
No worries 😄
