### ISSUE TITLE
Nextjs with react-redux-firebase?

### ISSUE THREAD

**Issue by smoliji** [zeit/next.js#2535]
I have custom server, successfully set up redux using with-redux demo, now I am trying to use react-redux-firebase for reading firebase's rt database.

I created store like this http://react-redux-firebase.com/docs/getting_started.html#compose-function.

Then I was getting the error: 'The XMLHttpRequest compatibility library was not found.'

I tried to follow this guide http://react-redux-firebase.com/docs/recipes/ssr.html to install XMLHttpRequest library, but then nextjs compilation failes on 
These modules were not found:

* child_process in ./~/xmlhttprequest/lib/XMLHttpRequest.js
* fs in ./~/xmlhttprequest/lib/XMLHttpRequest.js

And I cant get past that. Any idea what might be the problem and solution?

**Comment by esbb48** [comment]
Hi @smoliji , this comment help me to resolve the problem.
https://github.com/webpack/webpack-dev-server/issues/66#issuecomment-61577531

**Comment by smoliji** [comment]
@esbb48 I've set the `next.config.js` contents to this:
```
module.exports = {
    webpack: function (config) {
        config.externals = [
            {
                xmlhttprequest: '{XMLHttpRequest:XMLHttpRequest}'
            }
        ];
        return config
    }
}
```
- should be it, isnt it? But I still get the same error.

**Comment by smoliji** [comment]
Ok, this resolved it: https://github.com/prescottprue/react-redux-firebase/issues/72#issuecomment-292403834

Now I get this error, but thats not an issue to solve in this thread
`Error: This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled.
`

**Comment by maitham1** [comment]
@smoliji  did you get this working in the end with v2? Is there any chance of sharing your setup?
