### ISSUE TITLE
Can login facebook with javascripts SDK ?

### ISSUE THREAD

**Issue by kenshero** [zeit/next.js#2536]
```
import React, { Component } from 'react'

export class LoginPage extends React.Component {
  constructor (props) {
    super(props)
  }

  componentDidMount() {
    window.fbAsyncInit = function() {
      FB.init({
        appId      : 'xxxxxxxxxxxxxxx',
        xfbml      : true,
        version    : 'v2.9'
      });
      FB.AppEvents.logPageView();
    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));

    console.log(FB);
  }

  render() {
    return (
      <div>
      </div>
    )
  }
}

```
When i refresh(F5) page . "Uncaught ReferenceError: FB is not defined"

but work if not Reload page.

How i fix it ?

Thank you.

**Comment by radeno** [comment]
FB is loaded asynchronously only on client side. So you get FB only in window.fbAsyncInit. Better alternative is use Facebook library eg: https://github.com/CherryProjects/react-facebook

**Comment by kenshero** [comment]
@radeno thank you. but i dont know if i want get profile in every page for check authen. how i do.

**Comment by radeno** [comment]
You should save profile into state and then you need to check just login status:
https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus

**Comment by kenshero** [comment]
@radeno yes but when i change page make state refresh.so i think get profile every page reload right ?

**Comment by radeno** [comment]
If your page will be server-side-rendered then yes. You dont need to request profile every page if it not neccessary (if you don't need fresh token to request something from facebook). What you only need is check if is still connected with Facebook and that is what getLoginStatus do.

**Comment by hmontes** [comment]
What about google login?
