### ISSUE TITLE
Error in NPM 5.2.0 with styled-jsx

### ISSUE THREAD

**Issue by enternode** [zeit/next.js#2538]
import Document, { Head, Main, NextScript } from 'next/document'
import flush from 'styled-jsx/server' 
##ALERT###
import flush from 'styled-jsx/server' With the new npm 5.2.0 something changed because the module gives an error of not found and I started to look and npm change something to review please
#########
export default class MyDocument extends Document {
  static getInitialProps ({ renderPage }) {
    const {html, head, errorHtml, chunks} = renderPage()
    const styles = flush()
    return { html, head, errorHtml, chunks, styles }
  }

**Comment by enternode** [comment]
NPM 5.2.0 It may be because of this:
06c154fd6 #17678 Stop flattening modules that have peer dependencies. We're making this change to support scenarios where the module requiring a peer dependency is flattened but the peer dependency itself is not, due to conflicts. In those cases the module requiring the peer dep can't be flattened past the location its peer dep was placed in. This initial fix is naive, never flattening peer deps, and we can look into doing something more sophisticated later on. (@iarna)
88aafee8b #17677 There was an issue where updating a flattened dependency would sometimes unflatten it. This only happened when the dependency had dependencies that in turn required the original dependency. (@iarna)

**Comment by Goluis** [comment]
I found the same error, the solution was to add style-jsx to my dependencies.

**Comment by Goluis** [comment]
well, I can't use StandardJS in my project anymore with the new version of NPM for the same reason why styled-jsx is not found, https://github.com/npm/npm/issues/17717 - it should be fixed soon
