### ISSUE TITLE
Dynamic routing with next export to static

### ISSUE THREAD

**Issue by i8ramin** [zeit/next.js#2542]
Hi, according to the v3-beta docs, next.js support exporting to static html, and apparently also support "dynamic routes". Was wondering if there was some documentation on how to create dynamic routes when exporting static html.

> This is a way to run your Next.js app as a standalone static app without any Node.js server. The export app supports almost every feature of Next.js **including dynamic urls**, prefetching, preloading and dynamic imports.

I've added this to my `next.config.js` but it doesn't seem to work.

```
exportPathMap: () => {
    return {
      "/": { page: "/" },
      "/account/:id": { page: "/account" }
    }
  }
```

I also tried `"/account/*"`, but no luck. Any help would be greatly appreciated.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by i8ramin** [comment]
Actually, never mind. I found this example tutorial:
https://github.com/zeit/next.js/blob/v3-beta/examples/with-static-export/next.config.js

It may be worth adding that to the README

**Comment by i8ramin** [comment]
Sorry, opening again. That example shows how to generate dynamic paths based on existing data that is fetched. But what if the dynamic `:id` in the path is actually needed to generate the page. I essentially want a single page `/account` to handle all requests to `/account/:id` and then the app will fetch the data based off of `:id` and render the results. Is this possible with next.js as exported static html?

**Comment by i8ramin** [comment]
FYI, I am currently trying to handle this situation using Netlify:
https://www.netlify.com/docs/redirects/

**Comment by berzniz** [comment]
Since the exported site is completely static, it can never support this. The browser just goes to the URL you tell it to (for example: `/account/23`) and has no idea you want it to actually go to `/account`.

The only way to do this is with a backend (usually `nginx`/`haproxy`) that routes requests to correct pages. Some providers (like AWS's `s3` buckets) will allow you to make these maps. You can also switch to a query parameter which works (`/account?id=23`) but doesn't look nice.

**Comment by arunoda** [comment]
I think @berzniz provides the perfect answer. If you want such a feature, use Next.js with a Node.js custom server.

If you know all those ids in the buildtime, you can create a `getInitialProps` fetch data and build pages for all those ids. (via the config in `next.config.js`)

**Comment by supra28** [comment]
@berzniz @arunoda  Static sites generated using create-react-app with react-router does it. 
`<Route path='profile/:Id' component={Profile}  />`

Here the Profile component is passed the id which uses it to fetch the profile.

**Comment by sergiodxa** [comment]
That's because create React app and React router will create a Single Page app with a single html file, next static export is not intended for the same, is to create many HTML files with the content and it's not a SPA, just a bunch of HTML files.

**Comment by supra28** [comment]
@sergiodxa Thank you.

**Comment by arunoda** [comment]
Seems like we are good here. Thanks all.

**Comment by hbwoodrose** [comment]
aaaawww i wish this worked with nextjs static sites :(

**Comment by jaketrent** [comment]
static-site-generator-webpack-plugin has a cool `crawl` option.  https://github.com/markdalgleish/static-site-generator-webpack-plugin#crawl-mode

Perhaps something like that would at least support those dynamic routes that the app uses in the ui.

This, at least, could be statically generated.

**Comment by shurvirmori** [comment]
I think this demo will work fine for Export as static HTML of dynamic urls. :+1:  :ok_hand: 

https://github.com/zeit/next.js/tree/canary/examples/with-static-export
