### ISSUE TITLE
SSR optimizations

### ISSUE THREAD

**Issue by idibidiart** [zeit/next.js#2547]
Hi,

Looking to use Next.js for several major clients, and the concern is scalability of SSR.

Watching this video by Sasha Aickin (ex CTO of Redfin), I learned that we can apply some optimizations:

https://www.youtube.com/watch?v=PnpfGy7q96U

Does Next.js employ the optimizations mentioned in Sasha's demo?

Regarding streaming of HTML. I understand that Fiber is async and preemptive, so it lends itself well to the streaming model. But what is wrong with just copying what Sasha had done with react-dom-stream ? At least it will give us a half decent solution till you figure out Fiber streaming.

Starred & thank you for sharing :)

**Comment by arunoda** [comment]
Yes. This is a good question.
We are working on this after 3.0 release (which is happening this week or next)

We want to support SSR streaming as well as static component caching.
Actually, there are a lot of community tools out there.
What we are doing is make it easy to use them.
