### ISSUE TITLE
JS is all High Priority, blocking DOMContentLoaded. Can it be made Low priority?

### ISSUE THREAD

**Issue by unregistered** [zeit/next.js#2553]
I just wanted to see if there was a reason why the nextjs scripts like page/ and app.js load in as High priority assets. It seems to me that as high priority, they block DOMContentLoaded, and we could get quicker page rendering if we made them low priority assets.

It also seems like there was [some intention to have them as low priority assets in #1436](https://github.com/zeit/next.js/issues/1436): the scripts all have `async=""` on them in production, which should make them low priority, but the presence of [these preload links](https://github.com/zeit/next.js/blob/master/server/document.js#L43
) makes them high priority. For instance this is next-news.now.sh:

![screen shot 2017-07-13 at 12 34 45 pm](https://user-images.githubusercontent.com/300439/28184328-d82883c2-67c7-11e7-817b-f9d2f04be364.png)

More on priorities in chrome: https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf

------

I did an experiment with throttling on my project, with throttling to simulate a 3G connection (Regular 3G preset in Chrome).

```
      var rendered = await nextApp.renderToHTML(req, res, '/', '');
      rendered = rendered.replace(/<link rel="preload" href="\/_next\/[a-zA-Z0-9\-]+\/.+?" as="script"\/>/g, '');
      res.send(rendered);
```

* Standard next.js (high priority): DOMContentLoaded in 10.26 seconds
* Removing rel=preload links (this makes them medium priority): DOMContentLoaded in 7.87 seconds

This seems to make a big difference for mobile users.

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by khrome83** [comment]
What version of Next are you using? This is not he behavior we are seeing with next 2.x. As a master of fact, the dom loads so fast, we had toninline some critical Js so things like our menu drop down works without the extra request. On slow connections our app.js would download many seconds after the dom was ready.

I feel like something else is going on....

**Comment by unregistered** [comment]
@khrome83 We're on 2.4.X

The network priority issue happens in 3.0.0-beta5 as well, which you can verify by looking at the chrome network panel on https://next-news.now.sh/

You'll have to check "Disable Cache" and right click the column headers to enable "Priority"

<img width="1384" alt="screen shot 2017-07-19 at 11 07 36 am" src="https://user-images.githubusercontent.com/300439/28382290-8113d988-6c72-11e7-9aa3-5fa7e7a856a8.png">

Do you see the same on your site?

**Comment by khrome83** [comment]
Something is different between us. When I use chrome, version 59, I see this (with cache enabled) - 

<img width="939" alt="screen shot 2017-07-19 at 1 34 28 pm" src="https://user-images.githubusercontent.com/1844739/28383519-089fb5ca-6c87-11e7-9e5b-41f27c49324c.png">

With cache disabled, the JS was after the HTML. It seems chrome using the checkbox of "disable cache" to prioritize JS over other media assets. 

This is what it looks like for my site (www.insiderx.com - with cache disabled)- 

<img width="921" alt="screen shot 2017-07-19 at 1 36 16 pm" src="https://user-images.githubusercontent.com/1844739/28383590-4a4db0bc-6c87-11e7-9cc5-8914bd48a559.png">

We have a lot of assets, and as you can see it get prioritized right after the HTML with "cache disabled" checked. It looks like this is working as intended without the cache disabled. With the cache disabled, i think it may still be working as intended, as JS is probably the 2nd most priority item when developing websites, which is what that checkbox is used for.

**Comment by arunoda** [comment]
@unregistered I get your point on this.
But check this GIF:

![lqv0dbkyge](https://user-images.githubusercontent.com/50838/28385520-feddad76-6ce5-11e7-81e4-08de1389056b.gif)

We render the HTML just after browser see them.
We preload (High priority) some JS assets because, they are need to make the app work.

This is intentional and I don't see any issues with this approach.

**Comment by unregistered** [comment]
@arunoda You're right that the browser doesn't block first paint on the completion of those scripts, even if Lighthouse says they're part of the critical path. (That might be a bug in Lighthouse). It also looks like even without preload tags, Chrome still likes to fetch scripts relatively early anyways. I'll close this issue, and I'll continue to keep an eye on perf since that's especially important to us.

![screen shot 2017-07-19 at 2 06 09 pm](https://user-images.githubusercontent.com/300439/28389554-745ede04-6c8b-11e7-84e8-8a8887072f66.png)
^ Green line is first paint

@khrome83 I don't think there's anything different between our browsers, with cache enabled that's what I see too. However it's useful to disable cache since that reflects what new users will experience.

In general I'd like to point out that with progressive enhancement, the sites we build can work even before the JS loads.

**Comment by arunoda** [comment]
@unregistered yep. Thanks for detailed issue.

**Comment by khrome83** [comment]
@unregistered -  

> However it's useful to disable cache since that reflects what new users will experience.

I don't know this is completely a true statement based on what we saw. I am sure it is very close though. But I think clearing the cache will be more accurate than using the dev tools method of disabling the cache. Maybe I will play with this when I have more down time.

Either way you are right about performance. Remember perceived performance is also important.
