### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, open 'E:\react\react-server-render\.next'

### ISSUE THREAD

**Issue by chenghaohao** [zeit/next.js#2556]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.  windows 10 platform npm run build
2.  Error: EISDIR: illegal operation on a directory, open 'E:\react\react-server-render\.next'

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |      2.4.7   |
| node    |     v6.10.3    |
| windows |     10   |

**Comment by arunoda** [comment]
I'm using windows10 but didn't see this.
Could you send me more steps to reproduce.
May be a sample app?

**Comment by arunoda** [comment]
Anyway, try using the beta version.
