### ISSUE TITLE
HOC with getInitialProps on pages without it

### ISSUE THREAD

**Issue by jedlikowski** [zeit/next.js#2557]
I've been experimenting with authentication in my app.
These experiments have led me to create a HOC, called withAuth, in which I wrap all my pages components. Not all pages have getInitialProps defined, some are just pure functions.

withAuth has getInitialProps in which I perform the authentication and dispatch some actions to the redux store.

Now the tricky part: 
*dev mode*: getInitialProps in withAuth is called for all pages (this is the expected behaviour since the component wrapping the page has getInitialProps)
*prod mode* getInitialProps is called only if pages have their own getInitialProps as well. Why is that? Is it some misconfiguration or my end or a bug?

**Comment by supra28** [comment]
This is strange :S 
Can you make a repository with minimal working code that has this bug?

**Comment by supra28** [comment]
I couldn't reproduce it.

**Comment by timneutkens** [comment]
Please provide a consistent way to reproduce this issue. I'm pretty sure this has nothing to do with Next.js though. Cause when you wrap a page in a HOC, it'll just execute `getInitialProps` of the HOC. So you have to manually call `Component.getInitialProps` of the child.

**Comment by jedlikowski** [comment]
Thanks guys, I thought there were cases in which getInitialProps wouldn't be called on a top-level component but turns out I forgot to dispatch the action to the redux store in one case. I was expecting the store to have an initial state but it didn't due to no action being dispatched to set it.

Anyway, sorry for trouble and keep up the good work!

**Comment by timneutkens** [comment]
No worries :smile: ❤️
