### ISSUE TITLE
Js assets are 404 not found when i'm using ExpressJS

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#2575]
Strange behavior when i'm using express JS.

When i am doing

```javascript
server.get("/",(req,res) => {
//...
})
```

I get this error in my client 

`Failed to load resource: the server responded with a status of 404 (Not Found)`

for all my js assets (`manifest.js` , `common.js`, `main.js` etc.)

However, if i'm doing 
```javascript
server.get("*",(req,res) => {
//...
})
```

Everything works fine.

Looks good but in this case i lose all the benefit that offer express js . 

Has someone know how to manage this ?

Thanks.

**Comment by timneutkens** [comment]
Please see the example in the examples directory.
