### ISSUE TITLE
Handling moment internationalization

### ISSUE THREAD

**Issue by adrianha** [zeit/next.js#2576]
Hi, I'm developing web using Next and Express. Currently i'm facing issue when applying moment locale on the web. It shows that mark up that generated on server and client is different (Screenshot attached).
<img width="1394" alt="Different markup on server and client" src="https://user-images.githubusercontent.com/5382429/28250611-268901fa-6a97-11e7-8187-588e3b260cb9.png">
I'm applying moment's locale on **custom _document.js**. How to fix this issue?

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

It should generate same markup on server and client

## Current Behavior

It generate different markup on server and client

## Steps to Reproduce (for bugs)

[Repository](https://github.com/adrianha/next-routes-demo)

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | ^3.0.1-beta.8 |
| express | ^4.15.3 |
| moment | ^2.18.1 |
| react | ^15.6.1 |
| node    | v6.11.0 |
| OS      | macOS Sierra 10.12.1 |
| browser | Chrome Version 59.0.3071.115 |

**Comment by kolpav** [comment]
You need to use https://github.com/kadirahq/react-no-ssr for parts of components using `moment` at least that is how I do it. Maybe there is better solution.

**Comment by jedlikowski** [comment]
You could use a custom HOC together with a Redux store to achieve this. Basically you would have a custom HOC with getInitialProps, which will read the locale on the server side and dispatch it to the redux store. This HOC would return any component passed to it, wrapped in withRedux. You would wrap all your pages in this HOC, which would pass the locale down to these pages.

Sounds like a bit of an overkill but if locale is not the only thing you need to fetch on the server side and pass to the pages (like some authentication data?), maybe it a path worth exploring.

**Comment by adrianha** [comment]
Hi @kolpav @jedlikowski 
Thank you for the response. I already use custom HOC to dispatch current locale to update on the server and client. But the issue is from moment object itself, i was using object that created using moment() and store it in reducer and turns out the object is store default locale. I ended up store the date using string format and it solved the issue :)
