### ISSUE TITLE
shouldn't the URL be changed before getInitialPros?

### ISSUE THREAD

**Issue by jedlikowski** [zeit/next.js#2577]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

If a user clicks a Link in your app and navigates to a page with getInitialProps which takes some time to fetch data, your app may seem broken or hung. Even if you show some kind of preloader to tell them something is loading, if they take a look at the address bar, they will see the old url until getInitialProps finishes it's job and the new url is pushed to the browser history. Shouldn't the url change come first?

I'm curious what do you guys think about it and what was the motivation behind implementing it this way.

**Comment by arunoda** [comment]
No. We can't do that. At that time, we don't have data to pass into the page. Once we fetch/get data only we can render the page component.

See this [example](https://github.com/zeit/next.js/tree/v3-beta/examples/with-loading) on how to add a loading indicator.

You can also do nothing in the client side of getInitialProps and fetch data inside the component. With that, you can render the page immediately and show anything you want.

**Comment by jedlikowski** [comment]
@arunoda Thank you, I already have a loading indicator :) 

My question is if we should change the url before rendering the page. So user clicks the link -> url changes (but old page is still active) -> getInitialProps fetches data -> new page is rendered. Would that be possible?
