### ISSUE TITLE
styled-jsx does not render server side with custom _document.js

### ISSUE THREAD

**Issue by mattfca** [zeit/next.js#2593]
I am using styled-jsx throughout my app and I am getting a flicker when the server loads the initial page.
This only happens when I use a custom _document.js, so it must be something with that page.  

This is the code:

```
import Document, { Head, Main, NextScript } from 'next/document'
import GoogleTagManager from '../utils/GTM'
import flush from 'styled-jsx/server'

export default class MyDocument extends Document {
    static async getInitialProps ({ renderPage }) {
        const { html, head } = renderPage()
        const styles = flush()
        return { html, head, styles }
    }
    render () {
        console.log('styles: ', this.props.styles)
        return (
            <html>
                <head>
                    <script src={`https://maps.googleapis.com/maps/api/js?key=${GOOGLE_KEY}`} />
                    <meta charSet="utf-8" />
                    {this.props.styles}
                </head>
                <body className="body">
                    <GoogleTagManager gtmId='GTM-xxx' />
                    <div id="fb-root" />
                    <Main />
                    <NextScript />
                </body>
            </html>
        )
    }
}
```

Output:
```
styles: []
styles: []
```

The console output for props.style is always empty arrays.  Should this be done in a different way? I'm unsure what to do as the docs seem to say this is all that is needed.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     2.4.6    |
| node    |     7.7.4    |
| OS      |    w10/macos/centos     |
| browser |    all     |
| etc     |         |

**Comment by mattfca** [comment]
I moved everything from _document.js into my Layout components and everything is working as expected.

I did some logging inside style.js from styled-jsx and it doesn't look like it was finding any components to add to stylesMap.

**Comment by arunoda** [comment]
Try to use this as getInitialProps:

````js
    static async getInitialProps (ctx) {
      return Document.getInitialProps (ctx)
    }
```

**Comment by timneutkens** [comment]
```
  static getInitialProps ({ renderPage }) {
    const {html, head, errorHtml, chunks} = renderPage()
    const styles = flush()
    return { html, head, errorHtml, chunks, styles }
  }
```

The document.js signature has changed. Looks like the above now. That's why Arunoda is suggesting calling the parent 👍

**Comment by mattfca** [comment]
Okay so using

```
static async getInitialProps (ctx) {
      return Document.getInitialProps (ctx)
    }
```

does work, I have access to a styles prop.

**Comment by aviramga** [comment]
Hi @mattfca, @timneutkens, @arunoda  
I got the same issue
This is my getInitialProps:
  static async getInitialProps(ctx) {
 const { html, head, errorHtml, chunks } = renderPage();
 return { html, head, errorHtml, chunks };
  }

And changing it to 
static async getInitialProps (ctx) {
    return Document.getInitialProps (ctx)
}

solves it. But can you please explain why?
Im using latest NextJS.

Also where can I find documentation about document.js and all its capabilities and features?

Thanks!

**Comment by zation** [comment]
This is really weird... When I rewrite getInitialProps with exact same code as original Document, I can not get styles:
```js
  static getInitialProps ({ renderPage }) {
    const { html, head, errorHtml, chunks } = renderPage();
    const styles = flush();
    return { html, head, errorHtml, chunks, styles };
  }
```
When I use original `Document.getInitialProps` or not to rewrite it, I can get styles. Can anyone let me know why? Thanks!

**Comment by pruhstal** [comment]
Out of curiosity, is it necessary to call `const styles = flush();` for styled jsx? @arunoda @timneutkens

**Comment by timneutkens** [comment]
@pruhstal it's the way to flush all the styles into a string and make sure they're rendered server side, so yes, if you're using styled-jsx. If you're not using styled-jsx at all you don't need it.

**Comment by roma98** [comment]
Hi guys!
I hope you don't mind me 'uping' this thread.
I'm actually in the same situation as the original description.
I'm in the process of migrating a decent size create-react-app to next.js, and the legacy code includes material-ui and aphrodite.
So to start, I have merged [with-react-with-styles](https://github.com/zeit/next.js/tree/canary/examples/with-react-with-styles) and [with-material-ui-next](https://github.com/mui-org/material-ui/tree/v1-beta/examples/nextjs).
Now I can see that the css is not rendered server side, showing a 'flicker' when switching between server rendering and client rendering.

I have seen this snippet of code in this thread, but don't understand where/how to use it
```
static async getInitialProps (ctx) {  
      return Document.getInitialProps (ctx)  
    }  
```
here is my _document.js code

```
import Document, { Head, Main, NextScript } from "next/document";
import { StyleSheetServer } from "aphrodite";
import JssProvider from "react-jss/lib/JssProvider";
import flush from "styled-jsx/server";
import getPageContext from "../src/getPageContext";

export default class MyDocument extends Document {
  static async getInitialProps({ renderPage }) {
    const pageContext = getPageContext();

    const { html, css } = StyleSheetServer.renderStatic(() =>
      renderPage(Component => props => (
        <JssProvider
          registry={pageContext.sheetsRegistry}
          generateClassName={pageContext.generateClassName}
        >
          <Component pageContext={pageContext} {...props} />
        </JssProvider>
      ))
    );

    const ids = css.renderedClassNames;

    return {
      ...html,
      css,
      pageContext,
      ids,
      style: (
        <React.Fragment>
          <style
            id="jss-server-side"
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{
              __html: pageContext.sheetsRegistry.toString()
            }}
          />
          {flush() || null}
        </React.Fragment>
      )
    };
  }

  constructor(props) {
    super(props);
    /* Take the renderedClassNames from aphrodite (as generated
     in getInitialProps) and assign them to __NEXT_DATA__ so that they
     are accessible to the client for rehydration. */
    const { __NEXT_DATA__, ids } = props;
    if (ids) {
      __NEXT_DATA__.ids = this.props.ids;
    }
  }

  render() {
    /* Make sure to use data-aphrodite attribute in the style tag here
     so that aphrodite knows which style tag it's in control of when
     the client goes to render styles. If you don't you'll get a second
     <style> tag */
    const { pageContext } = this.props;
    return (
      <html>
        <Head>
          <style
            data-aphrodite
            dangerouslySetInnerHTML={{ __html: this.props.css.content }}
          />
          <meta charSet="utf-8" />
          {/* Use minimum-scale=1 to enable GPU rasterization */}
          <meta
            name="viewport"
            content={
              "user-scalable=0, initial-scale=1, " +
              "minimum-scale=1, width=device-width, height=device-height"
            }
          />
          {/* PWA primary color */}
          <meta
            name="theme-color"
            content={pageContext.theme.palette.primary[500]}
          />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```
