### ISSUE TITLE
Call of undefined while first time load after next build

### ISSUE THREAD

**Issue by malikimprowised** [zeit/next.js#2595]
I am still getting `call of undefined` error. I think its because i require npm package in componentWillMount. I also tried in componentDidMount. I got the error for the first time i load the after build. How to solve this.

**Comment by arunoda** [comment]
Please provide a way to reproduce the issue.

**Comment by malikimprowised** [comment]
For example if i add package like this way only for client side
```
 componentWillMount() {
    d3 = require("d3");
  }
```
Now if i do client side navigation to the component that acquire this code. At that time during first navigation i get the error.

**Comment by malikimprowised** [comment]
Any help would be appreciated.

**Comment by malikimprowised** [comment]
problem solved with the latest version.

**Comment by stevebluck** [comment]
What was the resolution to this? I am having the same issue.

**Comment by malikimprowised** [comment]
I have upgraded to latest version of next.js.

**Comment by stevebluck** [comment]
Same here, but when running `next build` to get ready for production, these scripts are not included for me.

**Comment by malikimprowised** [comment]
try `npm run dev`

**Comment by stevebluck** [comment]
Running in dev is fine, it works ok - it's when I `yarn build && yarn start` so that it runs in production (to benefit from prefetching etc..) is the issue.

**Comment by malikimprowised** [comment]
It works for me. I use `npm` and my script in package.json is 
```
"scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
```
and when i do `npm run build` it gets build.
