### ISSUE TITLE
add example with Reflux

### ISSUE THREAD

**Issue by iamsoorena** [zeit/next.js#2596]
reflux is way more handy than redux.

**Comment by ian-cawood** [comment]
I'd like to do this can I go ahead?

**Comment by timneutkens** [comment]
@ian-cawood sure go ahead 👍

**Comment by iamsoorena** [comment]
@ian-cawood  how's it going?

**Comment by ian-cawood** [comment]
Hey I'll finish it this week.

**Comment by rickyplouis** [comment]
I wrote up something pretty simple because I was interested in reflux myself. If anything they would like to see added/changed about the example then let me know.
