### ISSUE TITLE
Next.js and redux. Populating store on server side does not take effect

### ISSUE THREAD

**Issue by Tomekmularczyk** [zeit/next.js#2597]
Hey, I'm having trouble with redux and nextjs. If that's okay I will post a link to SO question where I described in details what I'm trying to do.

https://stackoverflow.com/questions/45191080/next-js-and-redux-populating-store-on-server-side-does-not-tak-effect

**Comment by jedlikowski** [comment]
try changing `withRedux(initStore()` to `withRedux(initStore`

the initStore function should be passed to withRedux, not executed by you

**Comment by Tomekmularczyk** [comment]
@jedlikowski my initStore() is a function that returns function

export default function initStore(logActions) {
  return function init() {
    const middleware = [tokenMiddleware, axiosMw];
    if (logActions) middleware.push(logger);
    return createStore(getReducer(), applyMiddleware(...middleware));
  };
}
