### ISSUE TITLE
getInitialProps req is undefined when using Link vs going directly to page

### ISSUE THREAD

**Issue by paulwehner** [zeit/next.js#2600]
## Context
I'm using the 'with-firebase' example (https://github.com/zeit/next.js/tree/v3-beta/examples/with-firebase), and running into an issue when I have multiple Pages and navigate between the pages using a Link component. Specifically, when I navigate between pages using a Link, the getInitialProps req is undefined, so I'm unable to get the 'req.session.decodedToken' which is added onto the request session in server.js.

My getInitialProps looks like:

```
static async getInitialProps ({req, query}) {
  const user = req && req.session ? req.session.decodedToken : null
  if(user && user.user_id){
    const snap = await req.firebaseServer.database().ref('user/'+user.user_id).once('value')
    return { user, data: snap.val() }
  }
  else{
    return { user, data: null}
  }
}
```

And in server.js, similar to 'with-firebase' example, it looks like:

```
const session = require('express-session')
const FileStore = require('session-file-store')(session)
...
  server.use(session({
    secret: 'test',
    saveUninitialized: true,
    store: new FileStore({path: '/tmp/sessions', secret: 'test'}),
    resave: false,
    rolling: true,
    httpOnly: true,
    cookie: { maxAge: 604800000 } // week
  }))

  server.use((req, res, next) => {
    req.firebaseServer = firebase
    next()
  })

  server.post('/api/login', (req, res) => {
    if (!req.body) return res.sendStatus(400)

    const token = req.body.token
    firebase.auth().verifyIdToken(token)
      .then((decodedToken) => {
        req.session.decodedToken = decodedToken
        return decodedToken;
      })
      .then((decodedToken) => {
          res.json({ status: true, decodedToken })
      })
      .catch((error) => res.json({ error }))
  })

  server.post('/api/logout', (req, res) => {
    req.session.decodedToken = null
    res.json({ status: true })
  })
```
So the issue I have is, if I go to 'localhost:3000' directly and load index.js, the req will be defined, and I can grab the decodedToken and use it to query firebase for some initial data.

If instead I'm on another page, that has a Next Link component, that links to the homepage, then the req will be 'undefined' when clicking the Link to the homepage and I will be unable to query firebase from within getInitialProps, and so can't seed the components on the homepage with the correct starting data.

How can I make it work so when I use the Link component the getInitialProps is able to grab the decodedToken and use it to query firebase, similar to how it can be done if I load the homepage directly from the browser bar?

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |        latest |
| node    |       v8.1.2  |
| OS      |        mac osx |
| browser |       chrome  |

**Comment by JustasPolis** [comment]
req is available only on initial load of page, then client takes over, so when you're transitioning through Link, there is no request object, only window object. For your problem, maybe use some global state to store that token ?

**Comment by arunoda** [comment]
Thanks @JustasPolis 
@paulwehner his answer is correct.

**Comment by paulwehner** [comment]
@JustasPolis Is there an example of storing Global state you could point me to? Not sure if I want to go full Redux yet, as it seems like a simpler solution would work for now.

**Comment by JustasPolis** [comment]
Well redux is best known global state management library, you could try mobx, not sure if there is simpler solution. You could create HOC that queries your server( (via fetch/axios) on initialProps for user data (token) when there is no req object and then wrap every page with that HOC. I hope that helps you somehow.
