### ISSUE TITLE
How to get separate multiple query data?

### ISSUE THREAD

**Issue by HadiAkmal** [zeit/next.js#2601]
- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Context
I'm tying to get multiple query data. I came up with this before redirect:

`Router.push('/acceptance/procurement/RejectedInfo?procurementUUID=0ae56414-0699-4866-898d-be41ab146523?acceptanceUUID=24ecb437-8e52-48f1-82f8-d5d7fb1d22b7');`

which mean there is 2 query param:
`procurementUUID=0ae56414-0699-4866-898d-be41ab146523` and 
`acceptanceUUID=24ecb437-8e52-48f1-82f8-d5d7fb1d22b7'`

but in my props, both query is merged with `procurementUUID`
![image](https://user-images.githubusercontent.com/14165645/28398611-94a6546c-6d3a-11e7-864e-643af5799759.png)

How can I separate `procurementUUID` and  `acceptanceUUID` value? 

Thanks in advance.

**Comment by HadiAkmal** [comment]
This is how you do it:

`Router.push({ pathname: '/acceptance/procurement/RejectedInfo', query: { procurementUUID: '0ae56414-0699-4866-898d-be41ab146523', acceptanceUUID: '24ecb437-8e52-48f1-82f8-d5d7fb1d22b7' } });`

![image](https://user-images.githubusercontent.com/14165645/28400893-b8f81cca-6d48-11e7-89b2-f18e5530b665.png)

It's clearly written in the docs. :p

**Comment by khrome83** [comment]
This is basic HTML query resource manipulation. You learned how to do it by passing a object to Router, but it is worth pointing out that you were close with the string solution also.

'/acceptance/procurement/RejectedInfo?procurementUUID=0ae56414-0699-4866-898d-be41ab146523`&`acceptanceUUID=24ecb437-8e52-48f1-82f8-d5d7fb1d22b7'

You only have 1 question mark in query params, and that denotes the start of the query. Every property then follows `key=value` with a `&` joining multiple into the same query. 

`domain.com?key1=valueA&key2=valueB&key3=valueC`

The object you found in the docs is the preferred way when using the Router for sure. But it's good to know what it is actually building behind the scenes.

**Comment by HadiAkmal** [comment]
Thank you. It's really helpful. :)

**Comment by jeanmaried** [comment]
I am also making a multiple query url push. I did the same as @HadiAkmal:

    Router.push({
      pathname: '/singlePost',
      query: { name: post_type, postId: post_id }
    });

I was expecting to get an object. Instead it is a string. Did something change since this was answered or am I missing something?
![screen shot 2018-01-24 at 9 17 37 am](https://user-images.githubusercontent.com/28982554/35336881-bc01a0b6-00e7-11e8-8c09-93df3d6a83b5.png)
