### ISSUE TITLE
Page with ant-design component is reloaded after disposing the previous inactive page

### ISSUE THREAD

**Issue by yongching** [zeit/next.js#2614]
When im going from "/" page to "/other" page in dev mode, after "Disposing inactive page(s): /"
"/other" page will get reloaded. Only happens when there is ant-design component used in "/other" page. 

Shouldn't it be a hot reload?

## Steps to Reproduce (for bugs)
The example [repo](https://github.com/yongching/with-ant-design) with this issue. 
1. Open up index page
2. Click "Ok" to navigate to "/other" page
3. Wait "disposing inactive page(s): /" to trigger
4. "/other" page will be reloaded

## Environment

| Tech    | Version |
|---------|---------|
| next | 3.0.1-beta.18 |
| node-v | v8.1.2 |
| browser | Google Chrome |

**Comment by arunoda** [comment]
Let me check this.

**Comment by arunoda** [comment]
I'm getting this on the browser console.
<img width="1257" alt="screen shot 2017-07-24 at 8 40 32 pm" src="https://user-images.githubusercontent.com/50838/28530148-6773c244-70b0-11e7-986e-7ed0108650e6.png">

I guess, that's something related to the HMR algorithm.
Frankly in this case, I'm not sure what I can do with Next.js to fix this issue.
