### ISSUE TITLE
react-fa font loading issue

### ISSUE THREAD

**Issue by umairfarooq44** [zeit/next.js#2615]
**Font loading issue**

I am using react-fa to load the font but I am getting this error on initial load :

``/home/umair/Projects/next-projs/next/node_modules/font-awesome/css/font-awesome.css:7
@font-face {
^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/umair/Projects/next-projs/next/node_modules/react-fa/lib/index.js:13:1)```

As I have written the loaders in next.config.js , 
if hmr executes (by changing/editing file) error disappears and page reloads fine but in chrome console ,
 I get this error:
`Warning: React attempted to reuse markup in a container but the checksum was invalid. 
This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting.
 React injected new markup to compensate which works but you have lost many of the benefits of server rendering. 
Instead, figure out why the markup being generated is different on the client or server:
 (client) ta-reactid="1"><div data-reactid="2"><st
 (server) ta-reactid="1"><div style="color:#000;ba`
Is there any way to load font without error on first load.

**Comment by HaNdTriX** [comment]
> Warning: Adding loaders to support new file types (css, less, svg, etc.) is not recommended because only the client code gets bundled via webpack and thus it won't work on the initial server rendering. Babel plugins are a good alternative because they're applied consistently between server/client rendering (e.g. babel-plugin-inline-react-svg).

https://github.com/zeit/next.js#customizing-webpack-config

**Comment by timneutkens** [comment]
@HaNdTriX I talked with @umairfarooq44 on slack. Issue was fixed, I believe he moved away from this lib 👍
