### ISSUE TITLE
Node freezes when I accidentaly use "static/" in img src attribute

### ISSUE THREAD

**Issue by vanniewelt** [zeit/next.js#2617]
This code anywhere in next page
```js
<img src="/static/" />
```

will cause node to freeze after rebuild. Page cannot be reloaded and node CPU and memory usage continue to rise until I terminate the task.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

It should probably throw error and crash.

## Current Behavior

There's a memory leak that causes node to freeze.

## Steps to Reproduce (for bugs)

1. Create minimal next app
2. Add this code to index.js page
```js
export default () => (
    <div>
        Hello
        <img src="/static/" />
    </div>
)
```
3. `npm run dev`
4. Load the page

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 3.0.1-beta.8 |
| node    | v8.1.1 |
| OS      | Windows 10 |
| browser | Chrome |

**Comment by timneutkens** [comment]
Thanks @vanniewelt, #2629 fixes this 🙌

**Comment by arunoda** [comment]
Thanks @vanniewelt for the report and @timneutkens for making this a priority.
Here's the fix: https://github.com/zeit/next.js/pull/2631
