### ISSUE TITLE
Optimizing for Google PageSpeed Insights

### ISSUE THREAD

**Issue by amitsch666** [zeit/next.js#2618]
The prototype I built following the tutorial on learnnextjs.com needs a lot of optimization on its final build. When run past [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights), it gets scored down on the following parameters:

- Enable compression

- Reduce server response time

According to Google, the following scripts are uncompressed:

- /_next/7edb944ce4757e3fa4d6f778f42d60f1/app.js

- /_next/97e680aa-2946-4f9e-ad5b-8f938979a15c/page/_error

- /_next/97e680aa-2946-4f9e-ad5b-8f938979a15c/page/(index)

- /(index)

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
All bundled files served to the client should be minified and compressed.

## Current Behavior
Bundled files being served to the client are not being minified or compressed.

**Comment by arunoda** [comment]
We don't compress assets by ourselves. It's upto the server to do that.
You can put a static server like nGinx or use a CDN.

**Comment by LordotU** [comment]
Sorry for necroposting, but is there any way to serve next.js bundle via nGinx? How should I map routes with BUILD_ID and app.js hash to nGinx settings?
