### ISSUE TITLE
Get rid of peerDependencies for react & react-dom when using preact & preact-compat

### ISSUE THREAD

**Issue by amio** [zeit/next.js#2619]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Shall we remove react & react-dom from peerDependencies? Since using preact (without react) is already an option.

## Current Behavior
will warning about:
```
npm WARN next@3.0.1-beta.18 requires a peer of react@^15.5.4 but none was installed.
npm WARN next@3.0.1-beta.18 requires a peer of react-dom@^15.5.4 but none was installed.
```

## Steps to Reproduce

`npm install next@beta preact preact-compat`

**Comment by arunoda** [comment]
We'd love to do that. But there's no such way to do that AFAIK.

**Comment by reel** [comment]
Also, for development, you need to use react/react-dom for hot-reloading (as stated in the `with-preact` example)?

**Comment by amio** [comment]
@reel @arunoda Thanks for clarifying!
