### ISSUE TITLE
Router methods throw exception for objects with relative pathnames

### ISSUE THREAD

**Issue by tmeasday** [zeit/next.js#2620]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Calling `Router.push({pathname: 'about'})` should work just as `<Link href={{pathname: 'about'}}/>` does, and as described [here](https://github.com/zeit/next.js#with-url-object-1).

## Current Behavior
Client side, it throws an error `Route name should start with a "/", got "page"` (thrown from https://github.com/zeit/next.js/blob/v3-beta/lib/page-loader.js#L22)

It then immediately falls back to the server side route, which then loads the page as usual.

Depending on how long the server page takes to load, you may or may not see the error above.

Note that absolute pathnames (`/about`) work as normal.

## Steps to Reproduce (for bugs)

1. https://github.com/tmeasday/next-routing-bug - `git clone https://github.com/tmeasday/next-routing-bug; cd next-routing bug; npm install; npm run dev`
2. Click the "Link" or "Leading Slash" tags, notice normal behaviour.
3. Click the "No Leading Slash" tag, notice the error for 2 seconds (how long the "page" takes to load).
4. Inspect the server console and note that the "page" page loaded from the server.

## Context

I think the issue here is that the `Link` calls `url.resolve` [here](https://github.com/zeit/next.js/blob/v3-beta/lib/link.js#L58), where as `Router.push` does not.

I suspect the `resolve` call should come somewhere deeper in the stack.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    2 + 3 betas     |
| node    |    8.1.0     |
| OS      |     macOS 10.12.5    |
| browser |    Chrome     |

**Comment by tmeasday** [comment]
I'm not sure I have all the context but happy to submit a PR if the suggestion (moving the `url.resolve` call deeper into the stack) makes sense to someone in the know.

**Comment by arunoda** [comment]
Actually, we don't support relative paths. In this case I think we need to block using `<Link href={{pathname: 'about'}}/>` and throw the client side error.

**Comment by tmeasday** [comment]
Oh? All the examples in the readme use relative paths and they work fine for Links

**Comment by arunoda** [comment]
Oh! Then we should change them.
Relative URLs might work. But they cause issues (specially user space).
So, that's why don't support it.

**Comment by arunoda** [comment]
Changed the README with this: https://github.com/zeit/next.js/commit/f8950e9b4c4c25f22047f5b019a66bf77bc1457d

I think the example as absolute URLs.
