### ISSUE TITLE
Need an example about bunyan

### ISSUE THREAD

**Issue by cncolder** [zeit/next.js#2625]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Add `with-bunyan` example.

I understand the main challenge is bunyan not work friendly with webpack.

I have try one day full. Open this issus for some help.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 3        |
| node    | 8        |
| OS      | OSX        |
| browser | Chrome        |
| etc     |         |

**Comment by timneutkens** [comment]
https://github.com/trentm/node-bunyan this?

**Comment by cncolder** [comment]
yes @timneutkens . I have no idea how integrate into next.js app.

**Comment by cncolder** [comment]
I give up and use pino instead.

**Comment by timneutkens** [comment]
Okay 👍 it looked like a server only module.

**Comment by jorge-autogravity** [comment]
how do you use pino to make nextjs server to output as json?

**Comment by sergiodxa** [comment]
@jorge-autogravity you mean the pages response to be JSON? Next.js is not intended for API, but you could use a custom server to add API code to do that (or whatever you want) and let the Next.js pages only for HTML.

**Comment by jorge-autogravity** [comment]
@sergiodxa  I currently the errors log to console in plain text. I would like to have them being logged as json so I can pipe the STDOUT to elasticsearch and visualize in Kibana.
I see in https://github.com/zeit/next.js/blob/4d0147385ca0dd55c69a7448d39e8ee6c77d8a1f/server/index.js#L51 that there is a catch that will always print to console. So I guess at the moment it's not possible
