### ISSUE TITLE
Accessing next render inside a controller file

### ISSUE THREAD

**Issue by dillonraphael** [zeit/next.js#2626]
I'm trying to have next render my js files using a controller in express.

Based on the custom example directory, routes are placed inside the single app.js file.

And example would be:

```
const Product = require('../models/Product.js')

exports.listProducts = (req, res) => {
	nextRender.render(req,res, '/products')
}
```

In the app.js file where I include next and start the server, I try setting nextRender. Example:

```
const next = require('next')
const dev = process.env.NODE_ENV !== 'production'
const nextLoader = next({dev})
const handle = nextLoader.getRequestHandler()

nextLoader.prepare().then(() => {
	const app = express();

	app.use(cors());
	app.set('nextRender', nextLoader)
```

**Comment by arunoda** [comment]
It's not clear what's this nextRenderer is. Please provide a sample repo with the issue.

**Comment by arunoda** [comment]
Reopen once you have it.
