### ISSUE TITLE
with-amp example Error: Can't resolve 'react-dom/lib/ReactInjection'

### ISSUE THREAD

**Issue by Wolke** [zeit/next.js#2627]
as title
npm run build
will show this error

**Comment by Goluis** [comment]
npm -v 5.3.0
node -v 8.0.0
![58eca2d4527dfa1dcc893e0be3c53016](https://user-images.githubusercontent.com/4278345/28532235-d95442aa-705e-11e7-823d-953281846957.png)

**Comment by timneutkens** [comment]
Try installing next@beta. Should be fixed there.
