### ISSUE TITLE
https on local machine using node https.createServer in server.js

### ISSUE THREAD

**Issue by Kielan** [zeit/next.js#2633]
[x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

It appears that https cannot work with nextjs in development but there is no documentation or direct answer to this question in the issues history.

I want to use https through the node https module on my local machine and communicate in dev environment over https to secure api's. 
 
As far as I can tell the https server does not work properly. While I can create the https server the connection is not considered secure by chrome. I do see in the server specific http server handling, is this not accessible through the api to configure?

in the server I am using 

`const handle = app.getRequestHandler(); 
`
to handle the requests, as far as I can tell this should be all that I need to do to server the pages securely.
 

`return handle(req, res, parsedUrl)
`

next  v 3.0.1-beta.8
node v 7.8.0
OS  osx

**Comment by arunoda** [comment]
We don't do anything to prevent working with HTTPs.
I think it should work properly with out custom server.

Anyway, I don't think it makes sense to use HTTPs for the dev server.
And pro production, use a proxy like nGinx in front of Node.

**Comment by arunoda** [comment]
More comments: https://github.com/zeit/next.js/issues/2281#issuecomment-317602443

To make it clear.

* We won't have SSL support in the core.
* But anyone can have it via our custom server API. (So, we welcome an example)
