### ISSUE TITLE
"Extracting" HTML on route load?

### ISSUE THREAD

**Issue by albertovilva** [zeit/next.js#2635]
I have a question, and I can't manage to find the answer in the docs.

I would like to get the HTML the server is going to render on a route so I can connect it to a service that turns that HTML into a PDF, in order to server side render pages as PDF.

Can someone shed any light on where I could plug in this? Im playing around in server.js but I cant manage to get the HTML..

The idea is as follows:

1.- You enter in /document/:id/pdf/ route
2.- The HTML string is processed by a HTML to PDF script on the server (or possibly is sent to an external service)
3.- The server renders the page and serves the PDF document file to the user.

Any info is greatly appreciated. Thanks.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by albertovilva** [comment]
I saw I can get the HTML at context.renderPage() on _document.js but I can't access renderPage() on the rest of pages.

```javascript
static async getInitialProps(context) {
    const page = context.renderPage();
    const props = await super.getInitialProps(context);
    return props
  }
```

**Comment by sergiodxa** [comment]
I think you will need a [custom server](https://github.com/zeit/next.js/tree/v3-beta/examples/custom-server) to do that.

**Comment by arunoda** [comment]
@albertovilva You can check the [SSR caching](https://github.com/zeit/next.js/blob/v3-beta/examples/ssr-caching/server.js#L58) example on how exactly you can do that.

It also includes whole HTML output with scripts. May be you can get rid of that by using some regexp or using a library like [cheerio](https://github.com/cheeriojs/cheerio).

**Comment by albertovilva** [comment]
Thank you very much guys, did it!

**Comment by timneutkens** [comment]
@albertovilva I'm pretty interested in what you made 😄 maybe provide it as an example for Next? 😄 💯

**Comment by albertovilva** [comment]
@timneutkens Sure! What I did was, in certain routes (those followed by /pdf) it triggers renderToHTML and processes the stringified HTML vía https://www.npmjs.com/package/html-pdf to generate a PDF. Working with styled components.

Not sure if too much moving parts for an example, let me know if I shall simplify it or follow any guidelines to PR as an example.

**Comment by timneutkens** [comment]
That's nice. Will give it a try and create an example 😄

**Comment by albertovilva** [comment]
Great! Let me know if you need any help.

**Comment by Rhjulskov** [comment]
Hi @timneutkens  & @albertovilva,
Did any of you have an example of this, you'r willing to share? :)

**Comment by albertovilva** [comment]
Hi @Rhjulskov I ended up not going that route. What I did is:

Create a High order component with my print logic:

1. Get HTML from body document.querySelector("body")
2. on ComponentDidMount send a POST to my backend sending and object with the HTML string.
3. Show a loader to the user while the file is being generated
4. On the response of the POST my backend sends back an URL with the PDF on it. Change the browser location to that and bam! the user gets a nice PDF

Cool thing about this is that you can wrap any page in this HOC(High Order Component) and you get PDF print with the same components.

I have this working in production, let me know if you need any more help.
