### ISSUE TITLE
how get cookie in getInitialProps with hapi.js

### ISSUE THREAD

**Issue by andy1028** [zeit/next.js#2636]
this is server.js

```js

const defaultHandlerWrapper = (app) => {
  const handler = app.getRequestHandler();
  return ({ raw, url }, hapiReply) => {
    return handler(raw.req, raw.res, url) // at this point filter raq,
      .then(() => {
        hapiReply.close(false);
      });
  };
};

```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by simenbrekken** [comment]
@andy1028 try `req.headers.cookie`

**Comment by timneutkens** [comment]
Thanks @simenbrekken 🙌
