### ISSUE TITLE
not work with hapi.js plugin yar, canot access req.yar in getInitialProps

### ISSUE THREAD

**Issue by andy1028** [zeit/next.js#2637]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
Please Provide a way to reproduce this :)
