### ISSUE TITLE
Way to mount multiple apps from single source tree?

### ISSUE THREAD

**Issue by pke** [zeit/next.js#2641]
I could not find that in the docs anywhere. Everything seems to be happening magically I wonder how I could run nextjs with multiple server instances with different ports from a common root folder structure?

``` 
apps
  app1
  app2
  shared
```

I'd like to mount `app1` and `app2` as own nextjs apps

**Comment by sergiodxa** [comment]
You can run `next -p <port>` to change the server port or create a custom server and listen to any port you want.

**Comment by pke** [comment]
Thanks for the swift response. I know that, but nextjs uses `/pages` from the root by default. I need it to use it from within each `app` folder.

**Comment by sergiodxa** [comment]
Using a custom server you can pass a base `dir` and Next.js will use that dir to search for the `/pages` folder. Check the supported options here https://github.com/zeit/next.js#custom-server-and-routing.

That way you can run them from `/apps` but you'll need to have a custom server for each Next.js app.

**Comment by pke** [comment]
ah cool! Thanks, I'll try that.

**Comment by cultofmetatron** [comment]
@pke @sergiodxa I'm trying to do the same thing you're doing, managed to get it working server side but the frontend does not recognize it and loads in the root folder .

here's my server.js

```js
const express = require('express');
const next = require('next');
const { parse } = require('url')
const dev = process.env.NODE_ENV !== 'production';''
const mainApp = next({ dev });
const helloApp = next({ dev, dir: './apps/hello'});
const handle = mainApp.getRequestHandler();
const helloHandle = helloApp.getRequestHandler();
mainApp.prepare()
.then(() => helloApp.prepare())
.then(() => {
  const server = express();

  server.get('/p/:id', (req, res) => {
    const actualPage = '/posts'
    const queryParams = { title: req.params.id }
    console.log('what is oibg on')
    mainApp.render(req, res, actualPage, queryParams)
  });

  server.get('/auth/*', (req, res) => {
    //console.log('grrr', req)
    const parsedUrl = parse(req.url, true);
    const { pathname, query } = parsedUrl;
    console.log('url: ',  parsedUrl)
    return helloApp.render(req, res, '/');
  })

  server.get('*', (req, res) => {
    return handle(req, res)
  })

  server.listen(3000, (err) => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000')
  })
})
.catch((ex) => {
  console.error(ex.stack)
  process.exit(1)
})

```

basicly ssr works but the loaded js does not load

**Comment by pke** [comment]
We have long given up using nextjs and rolled our own multi-product solution based only on react.
