### ISSUE TITLE
2.4.8 not available via npm / yarn

### ISSUE THREAD

**Issue by davecarlson** [zeit/next.js#2646]
## Expected Behavior

It should install 2.4.8

## Current Behavior
It provides 2.4.7 as the latest stable

## Steps to Reproduce (for bugs)
1. yarn add next@2.4.8
2. yarn
<img width="493" alt="screen shot 2017-07-25 at 21 01 12" src="https://user-images.githubusercontent.com/299702/28591169-9ef9af9a-717c-11e7-910b-749c6c836cf7.png">

**Comment by davecarlson** [comment]
It might be because appveyor failed with an out of memory exception :)

https://ci.appveyor.com/project/arunoda/next-js/branch/master

**Comment by timneutkens** [comment]
@davecarlson most likely Arunoda forgot it in this case ❤️ Thanks for creating this issue!

**Comment by arunoda** [comment]
Oh my.

**Comment by arunoda** [comment]
Done.
