### ISSUE TITLE
Custom actions on build?

### ISSUE THREAD

**Issue by dbkaplun** [zeit/next.js#2651]
Hey all,

Is there documention regarding how to perform some action on build? I am trying to open a browser to the current host:port on build. Is something like this possible?

**Comment by arunoda** [comment]
Actually, you do if after you run the `next build` command.

Like:

```
"build": "next build && node open-browser.js"
```

Also, you could use some webpack plugins: https://github.com/zeit/next.js#customizing-webpack-config

**Comment by dbkaplun** [comment]
I'm a little confused. How do I perform some action on new builds (i.e. whenever code changes or next is run)?
