### ISSUE TITLE
How to access `req` and `res` in page component lifecycle methods?

### ISSUE THREAD

**Issue by mocheng** [zeit/next.js#2653]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
In page component lifecycle method, it could access `req` and `res` in server side.

## Current Behavior
In static method `getInitialProps`, the argument `context` has fields `req` and `res` which is express request & response. However, there is no way to access `req` and `res` in page component lifecycle methods, because life cycle methods are instance methods.

## Context
In some cases, it is preferred to have access to `req` and `res` in component lifecycle methods in server side. I tried to have `getInitialProps` to return `req` & `res` as props, but `next.js` throw warnings about that these objects are not OK to be dehydrated.

For the time being, I used [request-local-storage](https://www.npmjs.com/package/request-local-storage) to transfer access from `getIntialProps` method. I hope `next.js` could have some native support for this scenario.

**Comment by arunoda** [comment]
You can access them in the client side. They are only available inside the server.x
I think, it's up to the user to maintain the state.

**Comment by alidavut** [comment]
I need this feature too. I want to pass the store via request object into the component in server side.
