### ISSUE TITLE
Prepare for Babel 7.x

### ISSUE THREAD

**Issue by stevefan1999** [zeit/next.js#2654]
- .babelrc.js
- Fixed stage-x/proposal versioning
- Deprecation of old node environment

The alpha versions of Babel 7 is publicly available in npm. Feel free to test it but I'm not sure that's the intent.

[The milestone page for Babel 7](https://github.com/babel/babel/milestone/9)

**Comment by arunoda** [comment]
Thanks. I'd like to test it.
Anyway, I think updating this is pretty straight forward.

**Comment by gilbert** [comment]
TypeScript support [just landed](https://github.com/babel/babylon/issues/320#issuecomment-321041737) in Babel 7 alpha. I'm interested in testing it. What are the steps involved in updating next.js to use Babel 7?

**Comment by xtuc** [comment]
That good news. Note you can find more informations about breaking changes in the future blog posts: [Upgrade to Babel 7](https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7) and [Upgrade to Babel 7 for Tool Authors](https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7-for-tool-authors).

Don't hesitate to ping me for questions about Babel 7.

**Comment by MAPESO** [comment]
@xtuc  What **features** does babel 7?

**Comment by xtuc** [comment]
An extensive list of new features will be published in the release blog post (coming soon).

**Comment by schoenwaldnils** [comment]
It seems that babel-loader@7.1.2 is in the dependencies of next@4.0.3
But I still can't use `.babelrc.js` any updates on this?

**Comment by lednhatkhanh** [comment]
Also, babel 7 allows us to use typescript with `@babel/preset-typescript`, any news on applying this to next directly?

**Comment by lifeiscontent** [comment]
any updates on this guys? Would love to use babel+typescript together.

**Comment by timneutkens** [comment]
@lifeiscontent you can already do that using `@zeit/next-typescript`, but babel 7 is on our list for v6 👍

**Comment by lifeiscontent** [comment]
@timneutkens I tried using the typescript example with dotenv example babelrc and it didn't work.
