### ISSUE TITLE
Browser forward, back, page will not be refreshed, bug

### ISSUE THREAD

**Issue by sowdf** [zeit/next.js#2657]
Browser forward, back, page will not be refreshed, bug

**Comment by timneutkens** [comment]
Please provide a way to reproduce.

**Comment by sowdf** [comment]
Browser forward, back, page will not be refreshed for <Link/>

**Comment by timneutkens** [comment]
I can't reproduce this in any of my apps and on https://zeit.co/

**Comment by sowdf** [comment]
if use Link Tag  browser  no  reload  , but use a tag , no problem

**Comment by sowdf** [comment]
i from china english is no good

**Comment by sowdf** [comment]
如果是用《Link》 标签 浏览器 点击浏览器 前进后退按钮 ，页面不会 按照 历史记录来返回，但是用 《a》标签不会出现这样的问题

**Comment by The-End-Hero** [comment]
@sowdf 感觉我目前是好的

**Comment by arunoda** [comment]
> i from china english is no good
This is good enough english. 

Could you send us a sample repo where we can reproduce the issue?

**Comment by maticzav** [comment]
If you mean that `getInitialProps` doesn't trigger, it's because you have to return Promise to fetch data.

```js
class Index extends React.Component {
  static async getInitialProps() {
    return Promise.all([
      //fetch data
    ])
  }

  render() {
    return (
      <div>page</div>
    )
  }
}

```

**Comment by arunoda** [comment]
Try await here:

```
static async getInitialProps() {
    return await Promise.all([
      //fetch data
    ])
  }
```

**Comment by sowdf** [comment]
`<Link href="/page"></Link>`

**Comment by sowdf** [comment]
skip after  , Browser forward, back, page will not be refreshed

**Comment by sowdf** [comment]
forward tips :
Failed to fetch
TypeError: Failed to fetch

**Comment by tungv** [comment]
I think he's talking about imperative navigation. Browser back/forward button doesn't work after imperative `Router.push` invocations.
