### ISSUE TITLE
Production Build Route with different parameter works only first time.

### ISSUE THREAD

**Issue by Rupeshn73** [zeit/next.js#2661]
`<Link prefetch href={'/store/?name=' + merchantDetail._id} as={'/store/' + merchantDetail._id}></Link>`

ie. http://domainname.com/store/storename1  works when I navigate from menu bar .

not work 

http://domainname.com/store/storename2 doesn't works after first route navigation with parameter stroename1 .

but when I navigate to different route ,that route also work for one time .

i.e http://domainname.com/category/category1

but not for i.e http://domainname.com/category/category2

This functionality is working fine for dev build .But when I run npm run build and then `    "start": "NODE_ENV=production node server.js"`  it is giving me inconsistent behavior of routing .Any suggestion on this.

**Comment by arunoda** [comment]
Hmm. I can't see anything without looking at the code.
May be you can isolate the issue. So, we can try this locally.

**Comment by arunoda** [comment]
Please re-open when you have it.

**Comment by Rupeshn73** [comment]
Please reopen it I am facing this issue. @arunoda

**Comment by arunoda** [comment]
I'll do it for sure.
But I can't reproduce this our apps.
I need a sample repo for this error.
And clear steps to re-produce it.

**Comment by Rupeshn73** [comment]
ok I will create a repo of it ,so that you can have a look.

**Comment by arunoda** [comment]
Nice.
