### ISSUE TITLE
"start": "NODE_ENV=production node server.js"

### ISSUE THREAD

**Issue by sowdf** [zeit/next.js#2662]
"start": "NODE_ENV=production node server.js"

npm run start ., output file a large , my output file 3.6M commons.js  , look my blog  http://www.sowdf.com/

open chrome look network commons.js have 3.6M ， how to solve ?

**Comment by timneutkens** [comment]
Please check your bundle using https://github.com/zeit/next.js/tree/v3-beta/examples/with-webpack-bundle-analyzer. Also make sure your server.js is reading NODE_ENV to decide if you're in dev/production
