### ISSUE TITLE
Firebase Authentication - SSR localStorage

### ISSUE THREAD

**Issue by maticzav** [zeit/next.js#2667]
Hi! 

I am trying to achieve SSR with Firebase and Firebase authentication. As far as I know Firebase authentication saves its session in localStorage item. Furthermore as I have read other issues (#153 especially), sharing localStorage items between server and client isn't possible and I will have to use cookies or some other hacks. (Correct me if I'm wrong!)

I had some other ideas, such as establishing admin instance on the server-side and then calling it instead of Firebase directly when SSR (just a thought).

Is there any other, better solution, any idea how to tackle this problem?

**Comment by ilionic** [comment]
Have you checked Firebase Auth example? https://github.com/zeit/next.js/tree/master/examples/with-firebase-authentication

**Comment by timneutkens** [comment]
#153 has most of the best practices. You could also create an api on top of firebase and call that api instead of firebase directly 👌
