### ISSUE TITLE
Server scripts aren't adapting to native Node ES environment (but full ES5 and CommonJS)

### ISSUE THREAD

**Issue by stevefan1999** [zeit/next.js#2671]
My classes and lambdas are transformed to ES5 constructs for server scripts(all files in .next/dist/**/*.js after `next build`), which is totally not acceptable despite it runs fine. 

I'm using babel-register with env preset to still getting the latest ES features that doesn't come with native V8 support. I'm using Node v8.2.x, and most of the modern ES constructs are implemented, so I'm pretty confused why are my server scripts are being boiled down to primitive ES5.

[And here's maybe the reason why.](https://github.com/zeit/next.js/blob/v3-beta/server/build/webpack.js#L257-L268)

_I'm sorry if my wordings are kinda ambiguous, but English is not my mother tongue, heh_

**Comment by arunoda** [comment]
@stevefan1999 These code needs to run on the client. That's why we transpile them back to ES5.
In the future, we may accept a set of browsers and server version you need to support.
Based on that, we can transpile effectively.

**Comment by stevefan1999** [comment]
I removed `next/babel` in presets in my `.babelrc` and instead installed `react` and `env` with specific versions of browsers back to presets. 

Now it kinda works, I can finally have modern ES semantics, but both client and server packages are using it... 

I wish I could still have ES5 for client bundle but ESnext in server.
