### ISSUE TITLE
PSA: Next version of UglifyJS and ecosystem

### ISSUE THREAD

**Issue by stevefan1999** [zeit/next.js#2672]
### Summary: 
- `uglifyjs-webpack-plugin` or `webpack.optimize.UglifyJsPlugin` will be upgraded to `1.0.x` in a week and uses `uglify-js@3/uglify-es`

- `uglify-js@3` is not backward compatible to `uglify-js@2`, to which the latter is used in current upstream version (0.4.6) of `uglifyjs-webpack-plugin`
---

### New features: 

- (Uglify-Es) ES6+ minification
- (uglifyjs-webpack-plugin) UglifyJS parallelization (!) 
- (uglifyjs-webpack-plugin) Selective minification (you can include/exclude files to minify)

---
https://github.com/mishoo/UglifyJS2/tree/harmony
https://github.com/webpack-contrib/uglifyjs-webpack-plugin

Currently in beta or prerelease stage, will be upstreamed sooner or later.

Code impacted: [#1](https://github.com/zeit/next.js/blob/v3-beta/server/build/webpack.js#L152-L155)

Related:

1. https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/95#issuecomment-318125994

**Comment by arunoda** [comment]
Could you tell us how this impact us?

Webpack already comes with this plugin. So, we just need to bump webpack when it's out. 
(And we are doing it everytime)

**Comment by stevefan1999** [comment]
@arunoda Pretty hard for me to explain...
uglifyjs-webpack-plugin seems to have moved UglifierJs options into an independent uglifyOptions, originally you could put UglifierJs config into top-level argument, now only sourceMap option is left in top-level

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/tree/master#uglifyoptions

Now the plugin config would have to rewrite like this
```
// Before 1.0.0
new webpack.optimize.UglifyJsPlugin({
  compress: { warnings: false },
  sourceMap: false
})

// After 1.0.0
new webpack.optimize.UglifyJsPlugin({
  parallel: true,
  uglifyOptions: {
    compress: { 
      warnings: false 
    }
  },
  sourceMap: false
})
```
Diff:
```
2c2,7
<   compress: { warnings: false },
---
>   parallel: true,
>   uglifyOptions: {
>     compress: {
>       warnings: false
>     }
>   },
```


But the maintainer(s) also pointed out that they are trying to make the update as seamless as possible, so maybe the legacy options can remain for a while.

I couldn't inspect anything else breaking.

We shall wait and see if there's anymore changes.

**Comment by arunoda** [comment]
Ah okay. It's the config.
I'll try to update to newest.

**Comment by nelix** [comment]
I'm curious about the order of things now, I use es6 and I am super keen to avoid commonjs, exported functions with the wrong displayName and symbols that ugly can't mangle...
Is this going to improve those issues?

**Comment by jonkwheeler** [comment]
Any update on this? This became a major issue for me.

**Comment by cheshirecode** [comment]
Yesterday my build with `"next": "^3.0.4"` broke and I had to disable UglifyJS to make it work again. Today I reinstalled everything from scratch, re-enabled UglifyJS and it worked without issues. Not sure why. All I did was cleaning up everything with `git clean -xfd; npm cache clear -f; rimraf node_modules/; ` prior to installation.

**Comment by chemzqm** [comment]
You should never use `git clean -fdx`, it would force remove any file not in git repo.

**Comment by cheshirecode** [comment]
@chemzqm precisely. On deployment, we need a fresh repository without any redundant artifacts.

**Comment by pencilcheck** [comment]
Getting the infamous `commons.js from UglifyJs\nUnexpected token: punc ()) [commons.js:46536,18]` after upgrading from next v3 to v4.

This seems to happen on every next upgrade since v2.

**Comment by stevefan1999** [comment]
@pencilcheck Purge .next/ folder and node_modules then try building the project again.

**Comment by pencilcheck** [comment]
Turns out the way to fix this is to use the comment suggestion by @rwieruch
https://github.com/zeit/next.js/issues/1195#issuecomment-326901737

A newer Uglify fixed it.
