### ISSUE TITLE
SyntaxError: unexpected token }

### ISSUE THREAD

**Issue by The-End-Hero** [zeit/next.js#2673]
First of all, this framework is great.

and i has an error:
in the package.json:
 `"dev": "concurrently \"npm run mock\" \" npm run development\"",`

when i run 'npm run dev',it take an error:
![c3a9c064-f94c-473e-b389-213c091cc166](https://user-images.githubusercontent.com/19590233/28708656-9d3f1bc4-73af-11e7-846c-3cc98f515d75.png)

the server.js code:
```
const express = require('express')
const compression = require('compression')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare()
.then(() => {
  const server = express()
    server.use(compression())

  server.get('/p/:id', (req, res) => {
    const actualPage = '/post'
    const queryParams = { id: req.params.id }
    app.render(req, res, actualPage, queryParams)
  })
    server.get('/T/:id', (req, res) => {
        const actualPage = '/h5article'
        const queryParams = { id: req.params.id }
        app.render(req, res, actualPage, queryParams)
    })
  server.get('*', (req, res) => {
    return handle(req, res)
  })

  server.listen(3000, (err) => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000')
  })
})
.catch((ex) => {
  console.error(ex.stack)
  process.exit(1)
})
```

i search this error on google,but not find.
What should I do to solve the problem?

**Comment by stevefan1999** [comment]
Use `next({ dev: dev })` as Node does not support [shorthand properties](https://babeljs.io/docs/plugins/transform-es2015-shorthand-properties/) natively yet

**Comment by arunoda** [comment]
We don't use babel and transpile code for the custom server code.
So as @stevefan1999  said, use the latest Node.js :D
