### ISSUE TITLE
run npm start and npm run dev at the same time

### ISSUE THREAD

**Issue by mhemrg** [zeit/next.js#2685]
Hi,
As I said I want to use `npm start` and `npm run dev` at the same time in my computer. I run `npm start` first and after that I change Express's port in my `server.js` to another port. Then I run `npm run dev` to have my app running in both development and production modes. But when I do that, the first app throws errors and doesn't work as expected.

**Comment by arunoda** [comment]
Unfortunately, that's not supported.
