### ISSUE TITLE
with-apollo-and-redux - not providing store

### ISSUE THREAD

**Issue by MarkLyck** [zeit/next.js#2688]
Working off the with-appollo-and-redux I'm having issues using react-redux connect to bindActionCreators.

I'm getting the error: 
`
Could not find "store" in either the context or props of "Connect(WithData(FileUploader))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(WithData(FileUploader))".
`

here's the code:

```js
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import FileUploader from './FileUploader'
import { updatePlan } from './actions'
import withData from 'lib/withData'

function mapDispatchToProps(dispatch) {
    const actions = { updatePlan }
    return { actions: bindActionCreators(actions, dispatch) }
}

export default connect(null, mapDispatchToProps)(withData(FileUploader))
```

FileUploader being a React Component that needs to dispatch an action.

This is the "top" level page file that's loaded. So I don't know where else I could possibly put withData...

the withData, initRedux, initApollo & reducers files are exactly as they are in the example.

I have tried editing the last bit to pass store directly to the ComposedComponent but that didn't work either:

```js
render() {
            return (
                // No need to use the Redux Provider
                // because Apollo sets up the store for us
                <ApolloProvider client={this.apollo} store={this.redux}>
                    <ComposedComponent {...this.props} store={this.redux}  />
                </ApolloProvider>
            )
        }
```

I'm using next v.3.0.1-beta.19

Any ideas why store isn't getting properly passed with the ApolloProvider?

**Comment by nickdandakis** [comment]
I think you need to be doing `withData` before `connect`. `compose` will help with this too.
Try:
```
import { compose } from 'redux';
...
...
export default compose(
  withData,
  connect(null, mapDispatchToProps),
)(FileUploader);
```

**Comment by MarkLyck** [comment]
@nickdandakis attempting this causes the following error to occur: 

```
Cannot call a class as a function
```

The FileUploader is a `class FileUploader extends React.Component`
