### ISSUE TITLE
npm run build success but got an error when I run next start

### ISSUE THREAD

**Issue by zigxas** [zeit/next.js#2691]
I execute npm run build success but got an error message  

**> Could not find a valid build in the '.next' directory! Try building your app with 'next build' before starting the server.**

I try removing node_module and reinstall them but still got an error.

**Comment by Goluis** [comment]
is your script `build` in `package.json` actually doing `next build` ?

**Comment by zigxas** [comment]
yes 
 "scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "next start -p 80 server.js",
    "start2": "next start server.js"
  },

**Comment by Goluis** [comment]
remove the `.next` folder and try again

**Comment by zigxas** [comment]
not work.

**Comment by zigxas** [comment]
I found this https://github.com/arunoda/next.js/blob/6d0511b96ab4d32b09879ecff53fa46e18f93fb1/bin/next-start

if (!existsSync(resolve(dir, '.next', 'build-stats.json'))) {
  console.error(`> Could not find a valid build in the '.next' directory! Try building your app with 'next build' before starting the server.`)
  process.exit(1)
}

**Comment by Goluis** [comment]
Mmmm, try not to use `next start` in the script `start` and use `NODE_ENV=production server.js` instead

**Comment by zigxas** [comment]
Wow thanks it works !

**Comment by dbkaplun** [comment]
I have the same issue, `next build` works fine but `next start` fails. No custom server. `next build` doesn't seem to create a `build-stats.json` when I run it.

**Comment by Goluis** [comment]
@dbkaplun can you share a repo ?

**Comment by dbkaplun** [comment]
Here's the repo: https://github.com/dbkaplun/dbkaplun

**Comment by Goluis** [comment]
your project worked very well with me
![working](https://user-images.githubusercontent.com/4278345/31185888-c1ad4e2c-a8f2-11e7-96e7-d4e96e33a3a3.png)

with `next 3.0.1-beta.17`  - `node 8.0.0` - `npm 5.4.2`
Maybe you have a lower version of node ?

btw nice canvas :D

**Comment by boriswexler** [comment]
@dbkaplun I am having the same issue - how did you resolve yours? I checked your repo and can't find the glitch.

**Comment by khrome83** [comment]
I can confirm i am seeing this, when I run `next` in development mode

**Comment by khrome83** [comment]
Deleting `.next` folder and restarting dev server fixed the problem. 
I am using `nodemon` to run `next` in dev mode after using `babel-register`. So I am guessing something go out of wack.

**Comment by khrome83** [comment]
Another updated, it fixed the issue briefly. Now it started doing it all over again.

**Comment by MiguelCedric** [comment]
Try running `npm run build` then run `npm start` again it should work

**Comment by faeghe-hajiabadi** [comment]
thanks @MiguelCedric  . worked for me

**Comment by PiyankaYadav** [comment]
@lfades could you please tell me that what these are doing: 
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
I just started with next.js and I want to know wy thses are used.
