### ISSUE TITLE
[example] react-i18next example does not work

### ISSUE THREAD

**Issue by gloorx** [zeit/next.js#2693]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
no error

## Current Behavior
"'common' of undefined" error

## Steps to Reproduce (for bugs)

1. yarn
2. yarn run dev
3. hit it on browser localhost:3000

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    v3 |
| node    |   8.1.2   |
| OS      |   sierra   |
| browser |   chrome latest  |
| etc     |         |

**Comment by yhjor1212** [comment]
It works on my side but it doesn't work on the production server.

I am examining why the changes in `serever.js` doesn't apply. See the lines around: `server.use('/locales', express.static(path.join(__dirname, '/locales')))`.
