### ISSUE TITLE
__webpack_public_path__ is not defined

### ISSUE THREAD

**Issue by klaygomes** [zeit/next.js#2697]
## Write a Component
```
import imageFile from "./happy-image.svg";
export default ()=> <img src={imageFile} alt="happy image" />;
```
obs.: Image does exist and it is on the same directory

## next.config.js

```
module.exports = {
  webpack: (config, { dev }) => {

    config.resolve = config.resolve || {};
    config.resolve.symlinks = false;

    config.module.rules.push( 
      {
        test: /\.(gif|svg)(\?.*)?$/i,
        use: [
          {
            loader: "emit-file-loader",
            options: {
              name: "dist/[path][name].[ext]",
            },
          },
          {
            loader: "file-loader",
            options: {
              limit: 1000,
            },
          },
        ],
      });
  }
}

```

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Component get rendered with correct image url 

## Current Behavior

Error: ReferenceError: \_\_webpack_public_path__ is not defined

- SVG file was emited to .next/[hash].svg
- There is a module in .next/build/components_folder/happy-image.svg with contents:
- `module.exports = __webpack_public_path__ + "[hash].svg";`

*.note \_\_webpack_public_path__  was not defined anywhere 

## Steps to Reproduce (for bugs)

1. write code described above

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     v2.4.9    |
| node    |    v8.2.0    |
| OS      |   OSX SIERRA      |

**Comment by arunoda** [comment]
Currently we don't support custom webpack loaders. But we may need to do it in the future.

**Comment by klaygomes** [comment]
What a shame.

**Comment by BjornMelgaard** [comment]
[For anyone who is interested how to use images in components directory](https://github.com/zeit/next.js/issues/2645#issuecomment-323437479)
