### ISSUE TITLE
forcing client side rendering for specific components

### ISSUE THREAD

**Issue by ramigg** [zeit/next.js#2701]
Hi,
I have a chart library which doesn't work with server side rendering.
how can I force the components which use this library to render on the client side?

thanks

**Comment by renancouto** [comment]
Like [this](https://github.com/zeit/next.js/blob/v3-beta/examples/progressive-render/pages/index.js#L13) maybe?

**Comment by timneutkens** [comment]
@renancouto thanks for answering 👌

**Comment by ramigg** [comment]
works great!
Thanks

**Comment by renancouto** [comment]
Always a pleasure @ramigg @timneutkens 🍻

**Comment by tejasmanohar** [comment]
Here's a [new link](https://github.com/zeit/next.js/blob/e451218900b16e721db10413734ca7a964c53677/examples/progressive-render/pages/index.js#L13).

Protip: `y` to link to file at specific revision so links don't break :-)

**Comment by jcollum** [comment]
Is that NoSSR library valid for React 16?

**Comment by planadecu** [comment]
What about this?

```
const Map = dynamic(() => import('../components/Map.js'), {
  ssr: false,
  loading: () => <p>Loading map</p>
})
```
