### ISSUE TITLE
Class with render as arrow function won't hot reload

### ISSUE THREAD

**Issue by rafaelsales** [zeit/next.js#2706]
❌  This won't hot reload when changes are made on render function:
```jsx
import React from 'react'

export default class Opa extends React.Component {
  render = () => (
    <div>Welcome to next.js!</div>
  )
}
```

✅  But this will hot reload when changes are made on render function:

```jsx
import React from 'react'

export default class Opa extends React.Component {
  render() {
    return (
      <div>Welcome to next.js!</div>
    )
  }
}
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
The arrow function version should hot reload. The create-react-app for instance can hot reload with arrow function.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | ^3.0.1-beta.20        |
| node    | v6.11.1        |
| OS      | macOS        |
| browser | Chrome 59        |

**Comment by arunoda** [comment]
What you've is a class variable. React Hot Loader doesn't work well with that.
And it's not good in the performance wise as well.
So, avoid using it. (At least for now)

**Comment by rafaelsales** [comment]
I'm curious why the create-react-app hot reloader handles that.

Aside from that, is this recommendation only for render method or any class function?

**Comment by hmontes** [comment]
what about add stage-0 to custom .babelrc ?

**Comment by Flaque** [comment]
Hey, is this still an issue? It looks like `react-hot-loader` fixed this: https://github.com/gaearon/react-hot-loader/issues/221 in this pull request: https://github.com/gaearon/react-hot-loader/pull/322

And we seem to be using the newest version of `react-hot-loader`. But, at least for me, I'm still getting something like this:

```
Module parse failed: /Users/Flaque/Projects/aurora/packages/aurora-demo/node_modules/react-hot-loader/webpack.js!/Users/Flaque/Projects/aurora/packages/aurora-feed/index.js Unex
pected token (26:16)
You may need an appropriate loader to handle this file type.
|   }
|
|   addSavedNotes = notes => {
|     notes.forEach(note => {
|       this.addCard(note);

 @ ./feed.js 11:18-43
 @ ./pages?entry
 @ multi ./pages?entry
```

My `.babelrc` looks like this:
```
{
  "presets": ["next/babel", "stage-2"]
}
```

And I'm using the newest version of Next:
```
"dependencies": {
    "next": "^3.2.2",
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
 },
```
