### ISSUE TITLE
Render static markup with custom Document page

### ISSUE THREAD

**Issue by nickdima** [zeit/next.js#2707]
Is there a way to render static markup (via `renderToStaticMarkup`) in a custom Document page?

**Comment by sergiodxa** [comment]
Not sure if I understood well but if you create a custom document it will render as static markup, you can also import ReactDOMServer yourself and render the static markup inside the render method of your custom document.

**Comment by nickdima** [comment]
A custom document renders to string (via `renderToString`) but in my case I was looking to render just markup without react checksum and ids.
But anyway, I just found out that using a custom server I can pass `staticMarkup` as `true` and it works perfect.
https://github.com/zeit/next.js/blob/v3-beta/server/index.js#L31
Not sure if it's documented somewhere.
