### ISSUE TITLE
How to sanitize HTML for passing it to 'dangerouslySetInnerHTML'

### ISSUE THREAD

**Issue by hugzug** [zeit/next.js#2711]
I tried to sanitize HTML in the following JSX code:
```
<div dangerouslySetInnerHTML={{ __html: cleanHTML }}></div>
```
with [DOMPurify](https://github.com/cure53/DOMPurify) module but it's not isomorphic so it didn't work for both client and server-side rendering. Any solution?

**Comment by timneutkens** [comment]
Something like https://www.npmjs.com/package/html-escape might work. This is not a Next.js issue 😄
