### ISSUE TITLE
how about importing components on demand ?

### ISSUE THREAD

**Issue by Mantak** [zeit/next.js#2713]
like this
https://ant.design/docs/react/use-with-create-react-app#Use-babel-plugin-import

**Comment by sergiodxa** [comment]
Are you talking about dynamic imports? That's supported in v3 (still beta)

Check:
https://github.com/zeit/next.js#dynamic-import

An example:
https://github.com/zeit/next.js/tree/v3-beta/examples/with-dynamic-import
