### ISSUE TITLE
Passing props or how to validate server side when js is disabled

### ISSUE THREAD

**Issue by dagda1** [zeit/next.js#2715]
I am doing a spike with nextjs for an application that has to run server side.

The app is a multistep wizard with each step a form that will not allow you to pass to the next step until the form is valid.  I did a quick prototype with redux, redux-form and all the good client side goodness but one requirement is that the app has to run with js disabled which has led me to nextjs.  This is a UK government site and this requirement will definitely not drop.

I'm very impressed with nextjs but I don't know how to do server side validation or how I could pass props to a server rendered component.

Say I have a form with an action like this:

```
    <form method="post" action="/some-url">
      <div>
```

And I have a handler like this in a custom server:

```
app.prepare().then(() => {
  const server = new Koa();
  const router = new Router();

  router.post('/some-url', async ctx => {
 
   // some validation checks
    if(formIsInvalid()) {
     // how do I pass props to /pages/the-original-url
      app.render(ctx.req, ctx.res, '/the-original-url', ctx.query);
      ctx.respond = false;
      return;
    }
     // if all is good then we render this view
    app.render(ctx.req, ctx.res, '/application/mothers-maiden-name', ctx.query);
    ctx.respond = false;
  });

  router.get('*', async ctx => {
    await handle(ctx.req, ctx.res);
    ctx.respond = false;
  });
```

In the above pseudo code, if the `formIsInvalid` function returns false, I want to render the original view that posted the form but I want to somehow pass props that I can use to determine whether to display validation messages or not.

**Comment by sergiodxa** [comment]
You can pass any object instead of `ctx.query`. That allow you to send custom data to `getInitialProps`
