### ISSUE TITLE
How to use nodemon with a custom Express server?

### ISSUE THREAD

**Issue by tomsoderlund** [zeit/next.js#2718]
How to use `nodemon` with a custom Express server?

I looked at [examples/custom-server-express](https://github.com/zeit/next.js/tree/master/examples/custom-server-express) and added:

	"scripts": {
		"dev": "nodemon server.js",
	},

...but it generates an infinite loop when I run it. Any tips?

**Comment by timneutkens** [comment]
Taken from one of the OSS Next.js projects I knew uses nodemon: https://github.com/relatenow/relate/blob/master/package.json#L12 it seems like you have to provide specifically that only the server has to be watched 👍

**Comment by malixsys** [comment]
Put your custom server in `server` and then:
```
    "scripts": {
      "dev": "nodemon --watch server server/index.js",
    }
```

**Comment by tomsoderlund** [comment]
Thanks @timneutkens, so the `-w` parameter is instrumental. But how do I make Next.js rebuild the `.next` folder every time `nodemon` detects a change?

**Comment by sergiodxa** [comment]
@tomsoderlund if you're running Next.js in dev mode you don't need that since Next.js will build everything every time the server is started automatically.

**Comment by tomsoderlund** [comment]
@sergiodxa Thanks, but Next doesn't do that for me. I based my code on [this tutorial](http://thecodebarbarian.com/building-a-nextjs-app-with-mongodb.html), so the relevant code in my `server.js` looks like:

	const next = require('next')
	const isDevelopment = process.env.NODE_ENV !== 'production'
	console.log('isDevelopment?', isDevelopment);
	const app = next({ isDevelopment })
	const handle = app.getRequestHandler()

	//...

	server.get('*', (req, res) => {
	  return handle(req, res)
	})

**Comment by sergiodxa** [comment]
Is `next({ dev })` no `next({ isDevelopment })`. Also you're not running `app.prepare()` which is used to build the files.

**Comment by tomsoderlund** [comment]
@sergiodxa Thanks, `dev` of course. Now works fine!
