### ISSUE TITLE
Link and browser history

### ISSUE THREAD

**Issue by kamish24six** [zeit/next.js#2720]
Hi.
i build a express app with next.js. the data fetching executed by route, for example: 
```
` server.get('/post/:id',  (req, res) => {
    Post.find({_id: req.params.id}).exec(function(err, post) {
      return app.render(req, res, '/post', post);
    });
  });

  server.get('/posts',  (req, res) => {
    Post.find({}).exec(function(err, posts) {
      return app.render(req, res, '/posts', posts);
    });
  });`
```

and then, in the page component i get the data from the props: 
```
`  static getInitialProps (props) {
    const { query } = props;
    return {post: query };
  }`
```

Then i make a map function on the data, and on each row i set a Link component with the post.id.

The problem is when i navigate to a single post and get back to the index posts with the browser: i get an error "this.props.post.map is not a function".

**Comment by timneutkens** [comment]
You'll have to fetch the data in getInitialProps if you're using `<Link>`, you can use a normal `<a>` tag to do what you want, but you'll lose the benefit of prefetching.
