### ISSUE TITLE
Only Index page loads while trying to use nextjs with express as an express router

### ISSUE THREAD

**Issue by walleXD** [zeit/next.js#2725]
I am trying to use nextjs with express by loading the nextjs app as an express router. I am mostly following the express example in the example folder but when the server starts up, I can only access the index page. All the other pages aren't loaded into the build folder. Not sure why that's happening as everything works perfectly if I load the next app directly rather than loading it as an express router.
   

- [X] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected & Current Behavior
I expected all the pages to load normally but that's not happening as only the index page loads

## Steps to Reproduce (for bugs)
The project can be access [here](https://github.com/walleXD/nextpack-simple/tree/refactor/next_express-router). It's very similar to the express example in the nextjs repo other than splitting out the rendering into an express router file, which is what I am trying to accomplish 

*index.js*(main project entry)
``` es6
import express from 'express'
import next from 'next'

import { apiRouter, nextRouter, app } from './server/router'

const start = async () => {
  const server = express()
  await app.prepare()

  server.use('/api', apiRouter)

  server.use('*', nextRouter)

  server.listen(3000, (err) => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000')
  })
}

start()
```

*nextRouter.js*
``` es6
import express from 'express'
import next from 'next'

import conf from '../../client/next.config'

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev, dir: './client', conf})
const handle = app.getRequestHandler()
const nextRouter = express.Router()

nextRouter.get('*', (req, res) => {
  return handle(req, res)
})

export {
  app,
  nextRouter
}
```

## Context
I am trying to use nextjs with backpackjs and I have been mostly successful. I am trying to separate out the nextjs app rendering into a separate express router file as that would allow me to better define route rendering on the server side

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     latest    |
| node    |    8.2.1     |
| OS      |       macOS 10.12.5  |
| browser |      chrome   |

**Comment by timneutkens** [comment]
Based on your code I don't see any issues. But it might be caused by app.prepare being imported from the router module.
