### ISSUE TITLE
Include example with traditional state container (Sans Redux/Mobx?)

### ISSUE THREAD

**Issue by relhtml** [zeit/next.js#2726]
I have been working through the tutorials of Next JS via learnnextjs.com, and I have a better understanding of the framework now thanks to that, in addition to the documentation provided on the official repo right here - much appreciated! 

I'm somewhat still fairly new to using React, and I have a grasp on container/presentation components. The apps I have written typically do not need the complexity that Redux and Mobx bring to the table. I want to keep the architecture fairly lean and intuitive for my team to jump into - and introducing an alternative state container later on if I need it. 

The way I set up my apps is as follows: 

AppContainer - initializes a state object. Pretty much all of my application's state resides here with the exception of local state for smaller components (form validation etc). State changes are also set here via functions, and then tunneled to different routes via React Router. I'm happy with this architectural pattern, and was just wondering how Next JS handles this pattern? The current examples show how to manage state via Mobx, but a more "pure" example would be beneficial to me, and hopefully some others too!

Thanks

**Comment by timneutkens** [comment]
@fdidron might be able to answer this. Feel free to join https://zeit.chat
