### ISSUE TITLE
Next ^3.0.0 is not available on npm

### ISSUE THREAD

**Issue by thangngoc89** [zeit/next.js#2730]
As for right now, I can not install next@3.0.0 from npm. Latest 3.0 version is beta 21

**Comment by samjbmason** [comment]
Yeah Im seeing the same thing

**Comment by pukapukan** [comment]
next@beta is 3.0.1-beta

https://github.com/zeit/next.js/releases/tag/3.0.1

**Comment by mike3run** [comment]
it is love now ❤️

**Comment by arunoda** [comment]
Guys, here's the correct Next.js 3 version: https://github.com/zeit/next.js/releases/tag/3.0.2
