### ISSUE TITLE
What happened to the with-redux-saga example directory?

### ISSUE THREAD

**Issue by michaelfriedman** [zeit/next.js#2733]
Is there a specific reason this was removed from the examples?

**Comment by sergiodxa** [comment]
It looks like the examples in [v3-beta](https://github.com/zeit/next.js/tree/v3-beta/examples) are still in that branch instead of master 🤔 
cc @timneutkens @arunoda

**Comment by michaelfriedman** [comment]
Oh, thanks!

**Comment by sbking** [comment]
It seems like no files were committed and just the `package.json` version was bumped? It seems like no v3.0.1 features are actually available. @rauchg

**Comment by sergiodxa** [comment]
It's fixed now, v3-beta examples are now in master.
