### ISSUE TITLE
Can't export my next app to static HTML

### ISSUE THREAD

**Issue by vanniewelt** [zeit/next.js#2738]
When I run script `next export` after `next build`, it throws this error:

```
> No such directory exists as the project root: C:\path\to\project\export
```

I'm executing those through npm scripts

```
"build": "next build",
"export": "next export"
```

My `next.config.js` is as simple as this:

```js
module.exports = {
    exportPathMap: () => ({
        '/': { page: '/' }
    })
}
```

However, removing this does not have any effect to the error.

I have no clue what could cause this error. It used to work, but at some point of development history it stopped working. Any thoughts? Is it bug?

| Tech    | Version |
|---------|---------|
| next    | 3.0.3 |
| node    | v8.2.1 |
| OS      | Windows 10 |

**Comment by timneutkens** [comment]
This has been fixed. Please update to the latest version.

**Comment by sheerun** [comment]
@timneutkens This still happens if one provides custom dir to "next export". For example "next export" automatically creates out directory, but "next export .build" complains there's not .build directory: "No such directory exists as the project root"
