### ISSUE TITLE
typescript error Cannot write file ... because it would overwrite input file

### ISSUE THREAD

**Issue by johhansantana** [zeit/next.js#2740]
![1](https://user-images.githubusercontent.com/9933887/29129417-b18844cc-7cf4-11e7-80ac-eada0677f038.png)

my tsconfig file

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2015",
    "jsx": "react",
    "allowJs": true
  }
}
```

I'm new to typescript but I don't think this should happen.

this is the script I'm running
`"dev": "concurrently \"tsc --watch\" next",`

**Comment by timneutkens** [comment]
You'll have to rename all your `.js` files to `.jsx`
