### ISSUE TITLE
fetch is not working

### ISSUE THREAD

**Issue by flexwie** [zeit/next.js#2745]
I am following the tutorial on fetching [here](https://learnnextjs.com/basics/fetching-data-for-pages/fetching-batman-shows).

I am trying to fetch data from my API (API is working fine) and display it like in the tutorial, but I get an error saying "Cannot read property '_id' of undefined" every time i try.

The returned array from the API looks like this:
`[
{_id: "1", name: "one"},
{_id: "2", name: "two"}
]`

The array get correctly logged in the servers console...
Any ideas on what I'm doing wrong?

**Comment by dogui** [comment]
Hard to tell what you're doing wrong without looking at the code but if your component is extending `React.Component` then make sure to do `this.props.myData`. The tutorial page uses a stateless functional component so that might slip past people.

**Comment by flexwie** [comment]
This is the code:
`import Link from 'next/link'
import Header from '../components/header'
import fetch from 'isomorphic-unfetch'

const Entry = (props) => (
  <Link prefetch as={`/e/${props.id}`} href={`/entry_view?id=${props.id}`}>
    <div style={{width: '100%', height: 80,}}>
      <div style={{height: '100%', width: '80%', display: 'inline-block'}}>{props.name}</div>
      <div style={{height: '100%', width: '20%', display: 'inline-block'}}>{props.value}</div>
    </div>
  </Link>
)

const Index = (props) => (
  <div>
    <Header />
    {props.entry.map(({e}) => (
      <Entry id={e._id} name={e.name} value={e.money} />
    ))}
  </div>
)

Index.getInitialProps = async function() {
  const res = await fetch('http://api.adress.com')
  const data = await res.json()

  console.log(data)

  return {
    entry: data
  }
}

export default Index`

This is the error:
![Error](https://user-images.githubusercontent.com/1215778/29188970-2ca023d4-7e15-11e7-8761-497979b313f6.PNG)

**Comment by sergiodxa** [comment]
You're decomposing your data in the map.

```js
{props.entry.map(({e}) =>
```

That should be

```js
{props.entry.map(e =>
```

**Comment by flexwie** [comment]
Thank you @sergiodxa ! Is this wrong in the tutorial as well?
