### ISSUE TITLE
How to access custom response values from a page?

### ISSUE THREAD

**Issue by amitsch666** [zeit/next.js#2746]
This might sound like a silly question but I have really tried everything I could to figure it out. I am creating a variable and adding it to my response object in `server.js` like so:

```
server.get('*', (req, res) => {
   res.locals.test = 'some string';
   handle(req, res);
});
```

Now I want to access this `res.locals.test` from all of my pages, i.e. index.js, about.js, etc., in order to keep a tab on the active session's user credentials. Is that possible?

**Comment by amitsch666** [comment]
A similar question was asked [here](https://github.com/reactjs/express-react-views/issues/96) and was closed by @zpao saying, "`res.locals` is passed to the top-level component you render as `props`." But that doesn't seem to be working in my case as no matter what value `res.locals.test` is assigned, `this.props.test` always returns `null`. In the same thread, @sumbad's solution was:

```
let scripts = [];
    scripts.push(<script dangerouslySetInnerHTML={{
      __html: `
      var data = ${JSON.stringify(this.props.data).replace(/script/g, 'scr"+"ipt')};
      `}} />);
```
Even that fails to do anything in my case, as `this.props.data` always returns `null`, thus breaking the script at `replace()`. Can anyone please suggest a solution? This is super urgent!

**Comment by zpao** [comment]
That was an entirely different project and I would not expect it to work here.

**Comment by Tsitsimelody** [comment]
I have a similar question, i have managed to access `res.locals`, through the getInitialProps function. 
```
export default class extends Component {
  static getInitialProps({ res }) {
    if (res) {
      console.log(res.locals.myData);
      return res.locals;
    }
```

It seems that this only works on refresh but if the component is accessed through a client route, it doesnt work. Im guesing you would need something like session storage/ local storage to save on the client?

**Comment by amitsch666** [comment]
Wow, your solution has at least given me some direction, @Tsitsimelody. Thanks! But like you said, no res.locals upon a client-side reroute. I would take the local-storage route but not sure how that would affect the refresh-reload since there's no local-storage on the server. Would still wait to see if anyone has a less-hacky NextJS-friendly workaround.

**Comment by timneutkens** [comment]
You can set a cookie and read it on both client/server side requests.
