### ISSUE TITLE
How to debug nextjs apps?

### ISSUE THREAD

**Issue by resting** [zeit/next.js#2748]
I think there should be a section on how to debug nextjs apps?
Am exploring the possibility of moving to JS rendered apps, but am having difficulty trying to inspect results from `fetch`. 

For instance:

    const res = await fetch('https://myapi/something').then((res)=>{
      console.log(res.json());
    })

Returns `Promise { <pending> }` which doesn't really tell much.

What are the common debugging practice and tools for nextjs, or server side JS apps in general?

**Comment by sergiodxa** [comment]
That's not related to Next.js, the `response.json()` of Fetch API returns a promise, you need to do:

```js
const response = await fetch(url)
const data = await response.json()
console.log(data) // here you have your data
```

Debug a Next.js is the same as debugging any React.js or Node.js app.
