### ISSUE TITLE
Image don't appear on csr..

### ISSUE THREAD

**Issue by BijayRai** [zeit/next.js#2754]
I've put image inside static file and call in my pages like below
`<image src="../static/logo_uxcam.png" alt="prof-image" width="160px"/>`

But while CSR it doesn't load images on screen. but while SSR it loads.
How to solve this behaviour?

**Comment by Blistok** [comment]
@BijayRai 
assuming that `<image/>` is actually `img` tag, try:
`<img src="/static/logo_uxcam.png" alt="prof-image" width="160px"/>`
as shown [here](https://github.com/zeit/next.js#static-file-serving-eg-images).
