### ISSUE TITLE
Why are vendor files built on every run?

### ISSUE THREAD

**Issue by piotryordanov** [zeit/next.js#2755]
Everytime I run `npm run dev` and load a new page, I have to wait a while for the page to build. I suppose this is basically `next` fetching all the dependencies in the `import` of the page and it's sub-component, then building them. But, if my understanding is correct, all of these dependencies are vendor files that rarely change, if ever.

Why then do I need to wait for a build  every time i do `npm run dev`?
It gets quite annoying when I am forced to reset the build during development, and then end up waiting minutes for the pages to build :(

Am I doing something wrong? Or is this how next works? If so, is there a way to build the vendor files once then only load a cache version while in `development` ?

Thank you in advance.

**Comment by timneutkens** [comment]
We're going to work on adding webpack dll soon. Which solves this.
