### ISSUE TITLE
I need all "_next" URLs to go under a prefix

### ISSUE THREAD

**Issue by callumlocke** [zeit/next.js#2758]
I'm using `assetPrefix` to prefix `/_next/` URLs with `/foo`. This is necessary because my entire app is behind a CDN and routing system which only routes paths beginning with `/foo` to my app. Therefore my app **cannot** receive URLs like `/_next/...` in production – I need all URLs to be `/foo/_next/...` instead.

But the problem is, the `assetPrefix` only seems to affect things like app.js or page bundles, and not **chunks** (things I load with a dynamic `import(...)`).

Is this a bug? Or is there some other way to specify a prefix for the entire app?

**Comment by timneutkens** [comment]
Please see #257, it has some solutions 👍

**Comment by callumlocke** [comment]
I can't find any solution there that would address this.

Can you confirm if this is a bug, or if it's intended behaviour that `assetPrefix` does not affect chunks?

**Comment by adibas03** [comment]
Just putting this here:
This comment gives a way to prefix chunks using webpack:
https://github.com/zeit/next.js/issues/257#issuecomment-321797741
