### ISSUE TITLE
Exception when return array as custom webpack config

### ISSUE THREAD

**Issue by trungdq88** [zeit/next.js#2762]
Regrading webpack allow array of config as input, this `next.config.js` crashes `yarn dev`

```
module.exports = {
  webpack: (config, { dev }) => {
    return [config];
  },
};
```

Console output:
```
 DONE  Compiled successfully in 3232ms                            12:18:49

(node:4702) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'chunks' of undefined
(node:4702) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4702) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'chunks' of undefined
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Should work as normal

## Current Behavior

Throw an UnhandledPromiseRejectionWarning, the app doesn't work.

## Steps to Reproduce (for bugs)

1. Create a new next app.
2. Add `next.config.js` with following content:
```
module.exports = {
  webpack: (config, { dev }) => {
    return [config];
  },
};
```
3. Run `yarn dev`

## Context

I was trying to transpile custom server code using next's webpack config.
## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         3.0.3|
| node    |        v8.1.0 |
| OS      |         macOS Sierra 10.12.6 (16G29)|

**Comment by sergiodxa** [comment]
That webpack method in `next.config.js` is an API implemented by Next.js to customize his internal weback configuration, and Next.js only require a single configuration.

If you want to use webpack in your custom server just create a `webpack.config.js` as usual and implement your own configuration. The Next.js webpack config is too customized for Next.js usage.

**Comment by timneutkens** [comment]
This is tracked in https://github.com/zeit/next.js/issues/1306
