### ISSUE TITLE
Styles don't apply correctly on dangerouslySetInnerHTML div's

### ISSUE THREAD

**Issue by Jonarod** [zeit/next.js#2764]
Hi,

I need to render `markdown-it` to `HTML`. The only way I found was to use the `dangerouslySetInnerHTML` prop from a `div`. (yeah, I know what `Dangerously` means...)
Anyway, after some setup and testing, I found that all the generated markup is out of the scope of any css put in `<style jsx>` block. Also, when using the `global` parameter, css is applied only at first page load, but not after transitioning to the page... 

:/

Here is some code.

Snippet 1:
```js
const MyComponent = () => (
   <div>
      <Head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"/>
      </Head>
      <style jsx>
          {`
                 a {color: red;}
          `}
      </style>
      <a href='#'>Link 1</a>
      <div dangerouslySetInnerHTML={ {__html: '<a href=\'#\'>Link 2</a>'} }></div>
   </div>
)
```
# Expected result (snippet 1):
All links `Link 1` and `Link2` should render as red color, including the one set by `dangerouslySetInnerHTML`.

# Actual Behavior (snippet 1):
`Link 1` is red, but `Link 2` seems to be outside the scope of the styles in `<style jsx>` and renders blue inherited from the `bootstrap` css in `Head`.

Snippet 2 (same code but using `global` jsx styles):
```js
// ... code
          <style jsx global>
              {`
                     a {color: red;}
              `}
          </style>
// ... code
)
```
# Expected result (snippet 2):
All links `Link 1` and `Link2` should render as red color, including the one set by `dangerouslySetInnerHTML`.

# Actual Behavior (snippet 2):
All links are rendered as red color ONLY AT FIRST PAGE LOAD (when it is server rendered ??). When navigating around (when rendered from the browser??), `Link 2` becomes blue again.

**Comment by coluccini** [comment]
The style is going to be localize, so will end up being `.a[data-jsx="'..."]{}` and be only applied to the links that next can add the data-jsx attribute (something not possible inside `dangerouslySetInnerHTML`).
You should declare the style as global style: `:global(a) {color: red;}`
