### ISSUE TITLE
Any way to run my own clientside script before Next's scripts?

### ISSUE THREAD

**Issue by callumlocke** [zeit/next.js#2766]
I want to detect browser features and give some browsers a static HTML/CSS experience if certain conditions aren't met. So I don't want the Next scripts to run automatically on page load – instead, I want to first run my own JavaScript that would then decide whether to run Next's scripts. (If not, the browser would entirely rely on SSR.)

I've thought of one hacky way to do it: intercept my server's `res.end()` function to modify the final HTML, stripping out all the Next script tags, and replacing them with my own custom script which will re-insert the Next script tags dynamically if conditions are met.

Before I try that, is there any better (less hacky) way to do it?

**Comment by sergiodxa** [comment]
You can create a [custom document](https://github.com/zeit/next.js#custom-document) to run your script before `<NextScript />`.

**Comment by callumlocke** [comment]
Awesome, thanks
