### ISSUE TITLE
webpack devtool

### ISSUE THREAD

**Issue by The-End-Hero** [zeit/next.js#2770]
Hi，guys. This project is awesome.
But in the development env，if I do something is wrong.(in the Console )cannot show the real code error.
like: the real code error in the index.js line15. but in the Console, it showed like es5,and the error is not in line15.
it look like the webpack devtool. 
i see in the guide. 
What can I do to make it what I want?

**Comment by jpsc** [comment]
This show's up on the browser as a pretty error message that's better no?

**Comment by timneutkens** [comment]
We're working on improving the sourcemaps etc to give more useful errors. This is tracked in another ticket.

**Comment by riddla** [comment]
@timneutkens: can you point me (and others) to the other ticket?

**Comment by timneutkens** [comment]
The ones in red:
https://github.com/zeit/next.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20sourcemap
