### ISSUE TITLE
Next build doesn't exit

### ISSUE THREAD

**Issue by terimyaki** [zeit/next.js#2775]
Hi, 

I am trying to run my next app in production, programmatically. However I notice it never exits the `next build` step and instead starts the server on port 3000, without hitting the start script.

Package.json
```
"scripts": {
    "start:prod": "npm run build && cross-env NODE_ENV=production node server",
    "build": "next client/ && next build"
}
```

```
Directory Structure
+ client/
+ - build/
+ - components/
+ - pages/
+ - static/
+ - next.config.js
+ server/
+ - index.js
```

Screenshot
<img width="249" alt="screen shot 2017-08-14 at 10 27 08 am" src="https://user-images.githubusercontent.com/6937112/29278904-165cfe04-80e4-11e7-9be8-a524321df0cd.png">

**Comment by sergiodxa** [comment]
In your build script you're running `next client/` before `next build`, that's running Next for development which build files and run a server.

**Comment by terimyaki** [comment]
Thanks. Found out it was `next build client/` to build the correct next app directory.
