### ISSUE TITLE
Cannot read property 'getBoundingClientRect'

### ISSUE THREAD

**Issue by safeimuslim** [zeit/next.js#2777]
Hi
I am new in Next JS, some times when i go to some page , I got error like this ?
```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
```

Thx for helping.

BGD
Safei Muslim

**Comment by timneutkens** [comment]
Most likely it's some dependency in your project. We don't use it in Next.js.

**Comment by safeimuslim** [comment]
OK
