### ISSUE TITLE
Miss class name placement in prod env when navigating to current route self.

### ISSUE THREAD

**Issue by tenosiswono** [zeit/next.js#2778]
I build some simple dashboard layout with nextjs and material ui next, but I face with strange problem that only happened in production.
The problem is regarding miss class name placement to the component wherever I click some link that navigate to the current route. I'm not quite sure if it nextjs problem or material ui problem.
live example: https://vanilla-nextjs-dashboard.herokuapp.com/

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
All style and class name placed at the right component

## Current Behavior
Normal scenario the component will get this classname
`<div class="c280 c281" aria-hidden="true" style="opacity: 1; transition: opacity 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;"></div>`
After I click navigation to the current route (current route dashboard, I click dashboard). The class name will change to the wrong one.
`<div class="c1 c2" aria-hidden="true" style="opacity: 1; transition: opacity 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;"></div>`

## Steps to Reproduce (for bugs)

1. Clone https://github.com/tenosiswono/vanilla-nextjs-dashboard
2. Run production
3. Login, Navigate to current route
4. Click on the notification button

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     latest  |
| node    |    6.11.2     |
| OS      |     heroku    |
| browser |     chorme    |
| etc     |      -   |

**Comment by timneutkens** [comment]
@oliviertassinari can you check this?

**Comment by oliviertassinari** [comment]
@tenosiswono Do you want to move the issue to Material-UI with a reproduction repository? It could be a classNameGenerator issue. Do you see any warning in the console in dev?
