### ISSUE TITLE
How to defer the page's first render? 

### ISSUE THREAD

**Issue by 0xsven** [zeit/next.js#2779]
I want to load a json file of page specific data. The first render of the app should be deferred until after this file is loaded. 

While the following code works just fine when navigating client side, it doesn't work on page load since `getInitialProps` runs on the server only. 

```
...
Index.getInitialProps = async ({ isServer }) => {
  if (!isServer) {
	  const data = await fetch('http://localhost:3000/static/index-data.json')
	  return {data}
  }
};
```

The following code doesn't defer the first render and there is a flicker:

```
class Index extends React.Component {
  async componentWillMount() {
    this.data = await fetch('http://localhost:3000/static/index-data.json')
  }
  render() {
    <div>{this.data}</div>
  }
}
```

How would I defer the page's first render until the fetch has completed?

**Comment by timneutkens** [comment]
You basically want this: https://github.com/zeit/next.js#3-with-no-ssr to fetch the component async 😄

**Comment by 0xsven** [comment]
@timneutkens thank you for that tip! 

How would I set this up with a json file?

```
import dynamic from 'next/dynamic'
const common = dynamic(import('../static/index-data.json'))

const Index = () => (
  <div>
    {data.someValue}
  </div>
)

export default Index
```

This seems to do nothing...
