### ISSUE TITLE
Switch to Jest

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#278]
What do you think about using Jest instead of AVA? It is made with React in mind, is supposed to be very fast‚ provides built-in test coverage and has things like snapshot testing, mocking, etc.

[NPM download trends](http://www.npmtrends.com/jest-vs-ava) are favoring Jest since [v15 came out in September](https://facebook.github.io/jest/blog/2016/09/01/jest-15.html). React-boilerplate just [switched](https://github.com/mxstbr/react-boilerplate/issues/970) to Jest and not very scientific but this [tweet](https://twitter.com/moox/status/774226671469727744) shows 4x speed improvement and this [tweet](https://twitter.com/mikenikles/status/772234132436885504) shows 10x improvement. 

"Automatic" [migration instructions](https://facebook.github.io/jest/docs/migration-guide.html#jest-codemods).

**Comment by pyros2097** [comment]
Yeah I would also suggest jest as its more suited for testing frontend and also find it better to use.

**Comment by rauchg** [comment]
Sounds great since we also have a jest example in the `examples` directory
