### ISSUE TITLE
Data doesn't render on first click from MongoDB.

### ISSUE THREAD

**Issue by Maklik123** [zeit/next.js#2780]
Iam concatenating the id as a query in the url. 
<Link href={{pathname :'/generatechallan', query :{id:element._id}}}><a>Generate Challan</a></Link>
And Rediecting the Generatechallan Page by Link Tag of Next.js.
Then I am fetching the Query id in this Mini API 
server.get('/generateChallan?:_id',(req,res)=>{
    if(req.user){
      Student.findById(req.query.id,function(err,student,done){
        
      if(err){console.log(err)}
      else{
        console.log(student);
      res.json(student);
      }
    })
    }
    else{
      res.redirect('/')
    }
  })
And calling this route to the generateChallan Page 
constructor(props){
    super(props);
    this.state ={data :[]}

    this.getChallanData = this.getChallanData.bind(this);
  }

  getChallanData(){
    axios.get('/generateChallan?:id').then((response) =>{
      console.log(response);
      this.setState({data: response.data})
    })
  }
In this getChallanData I cann't take the response on first click

**Comment by timneutkens** [comment]
You shouldn't use mongodb in Next. Rather create an api endpoint and fetch that. Using mongo directly won't work cause of server side rendering.

**Comment by Maklik123** [comment]
but endpoint api take too much time in getting and rendering the response.
