### ISSUE TITLE
Koa Example - 404 Flash

### ISSUE THREAD

**Issue by moaxaca** [zeit/next.js#2781]
Hello, 
When using the Koa router example I am seeing some strange behavior. When loading pages between routes the app it flashes a 404. I've isolated it down to:

```
  router.get('*', async ctx => {
    await handle(ctx.req, ctx.res);
    ctx.respond = false;
  });
```

When this block is removed we lose the next handled 404 page. Any guidance the app.getRequestHandler()(req, res) would be much appreciated. 

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate

**Comment by mashaal** [comment]
I was having this same issue -- what solved it for me was using the `Link` component like this...

```
<Link href="/wine-info?id=cloth-label" as="/wines/cloth-label">
```

My rookie mistake was that I had `/wine-info/?id=cloth-label` for the longest time, which is a 404 on server side, but the url in browser is correct. Which is where this 404 nonsense was stemming from.

**Comment by timneutkens** [comment]
thanks @mashaal 👌
