### ISSUE TITLE
redux-saga with axios catch causes converting to circular JSON error

### ISSUE THREAD

**Issue by JustasPolis** [zeit/next.js#2784]
# Introduction and buggy(?) behaviour

I'm using **with-redux-saga example** with  **axios** library. **response.status > 200** gives this error **below**

![image](https://user-images.githubusercontent.com/20723848/29340118-21ba53a8-8226-11e7-93a9-aeffa2e7144e.png)

**code causing this** 

```javascript
function* loadDataSaga() {
  try {
    const res = yield axios(
      "https://api.github.com/users/zxccxqweqewqeqwwrqrewqeqw"
    );
    yield put(loadDataSuccess(res.data));
  } catch (err) {
    console.log(err);
    yield put(failure(err.response));
  }
}
```

# What causes this ? 
Axios, unlike fetch, assumes that response codes above 200 and below 500 are errors, so when you request some API and get response.status above 200, you're getting an error and you can .catch it. How is that related to  converting circular structure to JSON, I have no idea.

# Workaround
I could use fetch and check if res.ok and continue. But axios is less-boilerplate library imo.

```javascript
function* loadDataSaga() {
  try {
    const res = yield fetch(
      "https://api.github.com/users/zxccxqweqewqeqwwrqrewqeqw"
    );
    const data = yield res.json();
    if (res.ok) {
      yield put(loadDataSuccess(data));
    } else {
      yield put(failure(data));
    }
  } catch (err) {
    yield put(failure(err));
  }
}
```
# How to reproduce ?
I took public github api to show this, this particular route gives us 404 response code, because that user does not exist.

* git clone https://github.com/JustasPolis/with-redux-reproduce
OR
* clone with-redux-saga example in next.js examples
* install axios
* Change **given lines below** in saga.js

```javascript
import axios from 'axios';
import { delay } from "redux-saga";
import { all, call, put, take, takeLatest } from "redux-saga/effects";
import es6promise from "es6-promise";

import { actionTypes, failure, loadDataSuccess, tickClock } from "./actions";

es6promise.polyfill();

function* runClockSaga() {
  yield take(actionTypes.START_CLOCK);
  while (true) {
    yield put(tickClock(false));
    yield call(delay, 800);
  }
}

function* loadDataSaga() {
  try {
    const res = yield axios(
      "https://api.github.com/users/zxccxqweqewqeqwwrqrewqeqw"
    );
    yield put(loadDataSuccess(res.data));
  } catch (err) {
    console.log(err);
    yield put(failure(err.response));
  }
}

function* rootSaga() {
  yield all([
    call(runClockSaga),
    takeLatest(actionTypes.LOAD_DATA, loadDataSaga)
  ]);
}

export default rootSaga;
```

Thank you

**Comment by JustasPolis** [comment]
It's axios issue, closing.

**Comment by KetrinJohnson01110101** [comment]
use this syntaxis
axios.get,
"https://api.github.com/users/zxccxqweqewqeqwwrqrewqeqw"
