### ISSUE TITLE
Files outside compiled directory

### ISSUE THREAD

**Issue by radeno** [zeit/next.js#2786]
I'm using ExpressJS and NextJS and currently i'm on the edge between simple app and something like medium sized app.
So i have server side and client side code, multi-language support and so on. (eg: `client` and `server` directories)
I need to extract configuration files outside of source code. Third directory `config` next to client and server.
Config is something changing/setuping application code (eg available languages, title pattern generator, grid size and so on), so could not be with source code together.

Issue with extracting config file (or another files) outside compiled directory (`next({ dir: './client', dev: isDev });`) is that NextJS include only one defined directory.

Is there any way how to include another directories to compiled build?
Next compiled directory (default `.next`) contains `dist` folder, so there is option to include another directories with preserver path looking.

**Comment by timneutkens** [comment]
There is no way to work around this cause it uses webpack roots and some other restrictions to the directory. So you'll have to move the directory into the next.js application directory.
