### ISSUE TITLE
Feature proposal: <NextScript postpone />

### ISSUE THREAD

**Issue by callumlocke** [zeit/next.js#2787]
It would be great if you could do this:

```jsx
// pages/_document.js

import Document, { Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  render () {
    return (
     <html>
       <body className="custom_class">
         <Main />

         <NextScript postpone /> {/*   <------- NEW FEATURE PROPOSAL    */}

       </body>
     </html>
    )
  }
}
```

With the `postpone` prop, it would **not output any of Next's external script tags**. Instead, it would create a global function called `__NEXT_START`, which, when called, would inject the script tags into the DOM.

It would be up to the app developer to call `__NEXT_START()` when they are ready – or even not at all, in some cases.

## Context
Many sites have a two-tier browser support strategy, opting to deliver a no-JS experience to older browsers. For example, the BBC and the FT both do a [quick feature-detect](http://responsivenews.co.uk/post/18948466399/cutting-the-mustard) in an inline script in the `<head>`, and then load other scripts dynamically **if** the browser meets a minimum baseline of features. Older browsers are still supported, but they get static, server-rendered HTML. This simplifies the rules for developers and QA testers, who don't have to worry (so much) about varying browser capabilities.

AFAICT, this approach is currently not possible with Next.js.

**Comment by timneutkens** [comment]
Tracking here: #4901
