### ISSUE TITLE
Upgrade with-flow example to Flow version 0.53.0

### ISSUE THREAD

**Issue by nwshane** [zeit/next.js#2797]
Flow now has [better support for React](https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627). We should upgrade the `with-flow` example to use the new version of flow.

Also, I don't know much about adding flow type support to libraries, but it doesn't seem like Next JS has flow types built in... would this be something worth adding?

- [ x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

In `examples/with-flow/components/layout.js`, we can change the children prop to be a required property, and change the value to React.Node. There are likely other changes that could be made - we can run flow-upgrade as described [here](https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627) to see what changes need to be made.

## Current Behavior

`with-flow` example uses old flow version.

**Comment by timneutkens** [comment]
> Also, I don't know much about adding flow type support to libraries, but it doesn't seem like Next JS has flow types built in... would this be something worth adding?

The flow types are held in flow-typed. We're not planning to add them to next in the short term.

**Comment by matiasfh** [comment]
I want to take this issue.

**Comment by timneutkens** [comment]
Feel free to @matiasfh 🙏
