### ISSUE TITLE
Does Next.JS expose everything to the client per Auth0's article ( below )?

### ISSUE THREAD

**Issue by bresson** [zeit/next.js#2799]
I'm trying to get to the bottom of authenticating / authorizing users and ran across the following snippet from Auth0: 

https://auth0.com/blog/build-better-universal-apps-with-nextjs2/

_"Note: Nextjs exposes virtually everything to the client. Secrets and environment variables are leaked to the frontend. So if you want to perform an API call and you need to validate a token based on a secret, then you will have to run a custom express server so that your secret can be available only on the server. This also applies to other forms of operations that require loading some secret environment variables that the user of your app shouldn't have access to."_

Are there any further details / documentation on what is exposed? If indeed the Auth0 article is accurate, server authentication/authorization will be the only option in many cases. However, server auth requires a full browser refresh, erasing any state maintained on the client ( unless preserved in cookie, LS, etc ) ... is this right? Thank you.

**Comment by timneutkens** [comment]
Please see https://github.com/zeit/next.js/issues/153 for ideas :)
