### ISSUE TITLE
Deployment Errors with SSR Next & Now

### ISSUE THREAD

**Issue by jay-manday** [zeit/next.js#2801]
Hi, 

I've been seeing deployment errors with my Next.js project using Now. My project runs as expected on my own device and when I try to deploy I get several build errors, I suspect it has something to do with my build scripts. The project with previous deployments had worked just fine before, I recently added dynamic importing of some components. Maybe this has something to do with how the Now servers are building the deployment. Thanks for taking a look!

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Just trying to deploy to now.

## Current Behavior

`
> sh: next: not found
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! jm-site-react@1.0.0 build: `next build`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the jm-site-react@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2017-08-17T19_26_59_314Z-debug.log
`

## Steps to Reproduce (for bugs)

1. download this repo: https://github.com/jay-manday/jm-site-react/tree/responsive-p5
2. `git checkout responsive-p5`
3. yarn
4. now deploy

## Your Environment

| Tech      | Version |
|---------|---------|
| next    | latest        |
| node    | 8.0.0        |
| OS      |  Mac OSX 10.12.5       |
| browser | Chrome        |
| etc     |         |

**Comment by MAPESO** [comment]
I entered the link but I get a 404 error. **Please check your link**

**Comment by arunoda** [comment]
It seems like there's no `next` in the repo. Check your `package.json`
