### ISSUE TITLE
why not use a webpack loader to deal with css/less/sass file importing?

### ISSUE THREAD

**Issue by bytesnail** [zeit/next.js#2807]
## Expected Behavior
* in FE entry, the loader works as style-loader
* in BE entry, it will cache every css-module's content by their module id
* when async page/component is rendered, css-modules that it depends will be cached by ids in an array, and these relationships between components & css-module-id arrays also could be stored as a map for re-rendering
* we could get styles from these cached css-module ids & contents by current component id in server rendering
* we can also load sync module with this loader, but it would be not necessary

## Current Behavior
style-jsx

## Context
anyway, the currently usage of style is not attractive to me

**Comment by albinekb** [comment]
There are already examples of using external styles, have you looked at them? `styled-jsx` is just the recommendation as it's currently the only solution that works correct with server-side rendering.
