### ISSUE TITLE
Production Build breaks when updating to 3.0.x from 2.4.9

### ISSUE THREAD

**Issue by supra28** [zeit/next.js#2810]
Production Build fails when updating my project to use next 3.0.x versions from 2.4.9
The development build runs fine.

This is the error I get in the browser console :
`Invariant Violation: Minified React error #130`

[Details Here](https://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]=%20Check%20the%20render%20method%20of%20%60t%60)
![err](https://user-images.githubusercontent.com/19588893/29486582-41f0cb64-8507-11e7-877f-0cae2fe627c7.PNG)

I see the initial render without the stuff that's loaded on the client-side after the API calls. 
When I scroll there is a page with `An unexpected error has occurred.` written on it.  :/

I don't know where to start to debug hence I downgraded to 2.4.9.
Are there any caveats to keep in mind before upgrading?

| Tech    | Version |
|---------|---------|
| next    |  3.0.2       |
| node    |  7.10.0       |
| OS      |   Windows      |
| browser | Chrome        |
| etc     |         |

**Comment by linatoquica93** [comment]
Hi, did you solve this problem?

**Comment by supra28** [comment]
@linatoquica93  no :(

**Comment by afc163** [comment]
I can't reproduce it by using https://github.com/zeit/next.js/tree/v3-beta/examples/with-ant-design . And import Pagination in `pages/index.js`.

- antd@2.13.1
- next@3.2.2

```bash
npm run build
npm start
```

<img width="569" alt="image" src="https://user-images.githubusercontent.com/507615/30478177-8eeeda8c-9a42-11e7-88e1-12cbb2d80fc2.png">

It works fine, is anyone can make a reproduible, minimal demo?

**Comment by fxh615** [comment]
hardly
