### ISSUE TITLE
how can I use next in pm2 cluster mode?

### ISSUE THREAD

**Issue by Qeneke** [zeit/next.js#2814]

**Comment by timneutkens** [comment]
You can combine the provided answer here https://github.com/zeit/next.js/issues/109 and then configure cluster mode :)

**Comment by zl810881283** [comment]
use next in pm2 cluster mode
not use next in pm2
I think it is another question

**Comment by pruhstal** [comment]
@zl810881283 it's all in the cli option:

https://keymetrics.io/2015/03/26/pm2-clustering-made-easy/

`pm2 start app.js -i <NUM_CORES_AVAILABLE>`
