### ISSUE TITLE
Issue with redirect example from wiki

### ISSUE THREAD

**Issue by gwintrob** [zeit/next.js#2815]
I found this [wiki page](https://github.com/zeit/next.js/wiki/Redirecting-in-%60getInitialProps%60) and have the following code to redirect in `getInitialProps`:

```
  static async getInitialProps({res}) {
    res.writeHead(301, {
      Location: 'http://example.com'
    })
    res.end()
    res.finished = true
    return {}
}
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

The page should redirect to `http://example.com` before rendering.

## Current Behavior

When I browse to the URL (the page is at `http://localhost:3000/dashboard`), the request just hangs. Here's what it looks like in the Chrome dev tools:
[screenshot](https://www.dropbox.com/s/2v0c6x6ubi5v417/Screenshot%202017-08-19%2014.39.35.png?dl=0).

## Context

I swear this was working before and I have no clue what changed. I'm going to try playing with different versions of Express. Thanks for your help! 

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     3.0.6    |
| node    |    8.1.1     |
| OS      |     Mac Sierra (10.12.5)    |
| browser |     Chrome    |
| express     |     4.15.3    |

**Comment by gwintrob** [comment]
It's fixed if I remove `res.finished`. This looks correct based on https://github.com/zeit/next.js/blob/42e21288a91b2f58d90c3cc782766611de30630f/server/render.js#L66-L67. I'm now seeing this warning https://github.com/zeit/next.js/issues/2152 and will keep digging into it.

**Comment by manovotny** [comment]
I was experiencing the same issues as described above, ie. *"the request just hangs"*. 

Removing `res.finished = true` fixed the issue for me and I didn't get any warnings like #2152 mentions, but I am also not using `express-session`.

Should the [Redirecting in `getInitialProps` wiki page](https://github.com/zeit/next.js/wiki/Redirecting-in-%60getInitialProps%60) be updated to remove `res.finished = true` so others don't face the same problem?

**Comment by gcpantazis** [comment]
I'm wondering if this is just incomplete in covering use-cases. I had to include `res.finished = true` to prevent `render()` from running in my project. I'm running Next 3.0.3 at the moment, with the following in my pages:

```
      if (res) {
        res.redirect(302, successPage);
        res.finished = true;
      }
```

**Comment by oliviertassinari** [comment]
I was facing this very same issue. I have found the following workaround:
```diff
function redirect(options) {
  const { Router, ctx, location } = options

  if (ctx.res) {
    // Temporary redirection
-   ctx.res.writeHead(302, {
-     Location: location,
-   })
-   ctx.res.end()
+   ctx.res.redirect(302, location)
    ctx.res.finished = true
    return
  }

  Router.replace(location)
}

export default redirect
```

[Here is the implementation](https://github.com/expressjs/express/blob/b7817ab1b0bbadabe79fc88819c8338838ead707/lib/response.js#L905) of the `redirect` function by express

**Comment by timneutkens** [comment]
This has been fixed in Next.js 5.

**Comment by raywat** [comment]
i use example code in custom-server-express and edit code something like this

```javascript
// server.js

app.prepare()
  .then(() => {
    const server = express()

    server.get('/a', (req, res) => {
      return app.render(req, res, '/b', req.query)
    })

    server.get('/b', (req, res) => {
      return app.render(req, res, '/a', req.query)
    })

    server.get('/c', (req, res) => {
      return app.render(req, res, '/c', req.query)
    })

    server.post('/c', (req, res) => {
      return app.render(req, res, '/c', req.query)
    })

    server.get('/posts/:id', (req, res) => {
      console.log('/posts/', req.params.id)
      return app.render(req, res, '/posts', { id: req.params.id })
    })

    server.get('*', (req, res) => {
      return handle(req, res)
    })

    server.listen(port, (err) => {
      if (err) throw err
      console.log(`> Ready on http://localhost:${port}`)
    })
  })

// pages/c.js
import React, { Component } from 'react'
import Router from 'next/router'

export default class extends Component {
  static getInitialProps ({ req, res }) {
    if (res) {
      if (req.method === 'POST') {
        res.writeHead(301, {
          Location: '/a'
        })
        res.end()
        res.finished = true
        return {}
      } else {
        return {}
      }
    } else {
      Router.push('/')
    }
  }

  render () {
    return <div>redirect to /a
      <button onClick={e => {
        fetch('/c', {method: 'POST'})
      }}>redirect
      </button>
    </div>
  }
}
```
It not redirect to /a 
what i do something wrong?
