### ISSUE TITLE
Trying to replicate the with-apollo example for local development [help]

### ISSUE THREAD

**Issue by strongui** [zeit/next.js#2817]
I want to recreate this example, to use my localhost database (running with WAMP) to try out next js for my project, but I'm stuck on how to exactly configure my server.js file.

**inside initApollo.js I have this:** 

```
function create () {
  return new ApolloClient({
    ssrMode: !process.browser, // Disables forceFetch on the server (so queries are only run once)
    networkInterface: createNetworkInterface({      
      uri: 'http://localhost:3000/graphql/',
      opts: { // Additional fetch() options like `credentials` or `headers`
        credentials: 'same-origin'
      }
    })
  });
}
```

**And my server.js looks like this:** 

```
import express from 'express';
import Schema from './schema';
import next from 'next';
import bodyParser from 'body-parser';
import { graphqlExpress } from 'apollo-server-express';

const port = parseInt(process.env.PORT, 10) || 3000;
const isDev = process.env.NODE_ENV !== 'production';
const app = next({ isDev });
const handle = app.getRequestHandler();

app.prepare()
.then(() => {
  const server = express();

  app.use('/graphql',
    bodyParser.json(),
    graphqlExpress({
      schema: Schema,
      pretty: true,
      graphiql: false
    })
  );

  server.get('/p/:id', (req, res) => {
    const actualPage = '/post';
    const queryParams = { title: req.params.id };
    app.render(req, res, actualPage, queryParams);
  });

  server.get('*', (req, res) => {
    return handle(req, res);
  });

  server.listen(port, (err) => {
    if (err) {
      console.log('error???');
      throw err;
    }
    console.log('> Ready on http://localhost:3000');
  });
})
.catch((ex) => {
  console.error(ex.stack);
  process.exit(1);
});
```

I have created the exact same table/fields inside my mysql database, so that I can respond with the same data, but I never get to that actual step. When I load localhost/3000 I get error:

**http://localhost:3000/graphql/ 501 (Not Implemented)**

What am I missing here?

**Comment by bs1180** [comment]
The line `app.use('/graphql'` should be `server.use('/graphql'` - otherwise you're trying to add the express graphql middleware to the next instance, rather than your express server instance.

**Comment by strongui** [comment]
I have tried that, I noticed that typo yesterday, but it doesn't seem to make a difference. Even with server.use(.... I just get **Not Implemented** as the post response.

**Comment by strongui** [comment]
Ok...after a lot of digging around I found that the problem is you cannot use hot-reloading if you use a custom server. It would be really nice if this was better documented.

Using a custom server you **HAVE TO run _npm next build_ and then _npm node server.js_**, after every and any change you make to any client or server files.

This basically makes a custom server option unusable.

**Comment by timneutkens** [comment]
@strongui that's not true at all. This line is incorrect:

```js
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
```

should be:

```js
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
```

https://github.com/zeit/next.js#custom-server-and-routing

**Comment by alfiepoleon** [comment]
@timneutkens it's true, once you change the server code you have to restart. Got me before
