### ISSUE TITLE
<Link/>: prefetch priority [feature request]

### ISSUE THREAD

**Issue by AvraamMavridis** [zeit/next.js#2821]
This is a feature suggestion/request. I am not sure how easy is to be implemented.

### Scenario

Imagine you have a long list with links to articles, sorted by date, and you are using `<Link prefetch />`. Users are more likely to click on links that are recent, it would be nice if `<Link />` can provide some mechanism of prioritisation. 

The platform try to achieve it (kind of) using `preload`

<img  src="https://cdn-images-1.medium.com/max/2000/0*KKong0kz69LOteD3." width="600" />

But I am talking about a finer control of it. Something like

```
<Link priority="1" href="/blog/article-1" prefetch>Article 1</Link>
<Link priority="2" href="/blog/article-1" prefetch>Article 2</Link>
<Link priority="3" href="/blog/article-1" prefetch>Article 3</Link>
<Link href="/blog/article-1" prefetch>Article 4</Link>
<Link href="/blog/article-1" prefetch>Article 5</Link>
<Link href="/blog/article-1" prefetch>Article 6</Link>
```

**Comment by timneutkens** [comment]
Cool idea, I'm pretty sure you could implement this using the imperative api https://github.com/zeit/next.js#imperatively-1. It hasn't been done before though. I'm willing to take an example in if you figure it out, cause it'd be pretty cool 😄 👌
