### ISSUE TITLE
Needs better warning when exportPathMap[n].page does not start with `/`

### ISSUE THREAD

**Issue by tannerlinsley** [zeit/next.js#2826]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Do not allow exporting an entry in `exportPathMap` that does not start with a backslash
-or-
Ensure that the page template defined in an `exportPathMap` entry either starts with *or is preprended with* a backslash to ensure operability.

## Current Behavior
Using a `page` value in a path exported from `exportPathMap` that does not start with a backslash `/` results in an error on the client when it attempts to retrieve `/_next/:buildID/pagemytemplate` instead of `/_next/:buildID/page/mytemplate`. Because of this functionality, a brief 404 will displayed, then replaced with the actual page request.

## Steps to Reproduce (for bugs)
1. Export a path in `exportPathMap` with a `page` value that does not start with a backslash.

## Context
This resulted in unexpected 404's, and was a very silent error.

**Comment by tannerlinsley** [comment]
I believe the culprit code is located here: https://github.com/zeit/next.js/blob/master/server/document.js#L84-L87

**Comment by Sekhmet** [comment]
I think it should be fixed in #3456.
