### ISSUE TITLE
Next.js + Redux + Apollo. Put withData OUTSIDE of pages folder

### ISSUE THREAD

**Issue by hmontes** [zeit/next.js#2827]
I'm follow this example: https://github.com/zeit/next.js/tree/master/examples/with-apollo-and-redux

Works okey if i put withData in pages folder. But i have a layout and in the layout i have a header.

So. If i put getData in the layout folder (Outside of pages) i get:

```
Warning: Failed prop type: The prop `serverState` is marked as required in `WithData(Unknown)`, but its value is `undefined`.
```

So. The question is. How can i put withData in the /layout folder and call only ONE time? (Because i have a header and i need to call withData in ALL pages)

Thank you

**Comment by ads1018** [comment]
You must explicitly wrap every page with the higher order component. This constraint is by design. See [here](https://github.com/zeit/next.js/issues/659#issuecomment-270925152).
