### ISSUE TITLE
Set More than Two custom environment variables for our application based on NODE_ENV in NEXT_JS

### ISSUE THREAD

**Issue by BijayRai** [zeit/next.js#2829]
following https://github.com/zeit/next.js/tree/v3-beta/examples/with-universal-configuration
i can do something like this only

```
const prod = 'production' === process.env.NODE_ENV

module.exports = {
    'process.env.API_URL': prod ? 'http://api.server.com' : 'http://api.local.com/web',
}
```
This solve only cases for production and development .
What if i want more custom production mode env!?
just eg(QATEST) . custom development mode
For this how to write config for this?

I followed this : https://gist.github.com/ledfusion/7854fdc440300d162f7759a5a5c1e04a
(Example of a dev/production/env config system for NodeJS)

and run : `npm run dev`
then i got same error like :
**property of MemberExpression expected node to be of a type ["Identifier"] but instead got "StringLiteral"**

My main concern is how to handle more than two(dev n production) custom environment variables for our application based on NODE_ENV in **NEXTJS**...

**Comment by eezing** [comment]
If I'm following you correctly, it sounds like you want to set process.env.NODE_ENV to something other than "development" or "production"?

**Comment by BijayRai** [comment]
@eezing  yes i want to setup different env for testing purpose before productions.

**Comment by timneutkens** [comment]
You can just read different env vars you set yourself. the `prod` check is just an example.
