### ISSUE TITLE
Is it possible to have multiple custom documents?

### ISSUE THREAD

**Issue by callumlocke** [zeit/next.js#2832]
The docs say you can define a custom document at `pages/_document.js`.

But is there any way to make two pages that use different custom documents?

**Comment by sergiodxa** [comment]
You need to have a single `pages/_document.js` and you can then check the URL before rendering to change the HTML you're going to render.

**Comment by callumlocke** [comment]
That makes of a lot more sense than what I was imagining

**Comment by greggootz** [comment]
@sergiodxa this sounds like an excellent approach!

Can you give a simple example of this?

I can get  `_document.js` to identify URL (query, pathname) on first load, but struggling with `_document.js` identify when the Routes are changed.

Thanks!

**Comment by timneutkens** [comment]
_document.js is only rendered once on the server, all navigation using <Link> is client side.
