### ISSUE TITLE
can nextjs use width dva?

### ISSUE THREAD

**Issue by zzh3319** [zeit/next.js#2838]
can nextjs use width dva?

**Comment by witwave** [comment]
@zzh3319   I have try it, but not success.

**Comment by eezing** [comment]
I haven't used Dva myself, but based on the docs I'd say probably not. As with Next.js, Dva is an opinionated framework, not a library... it would be like trying to stuff a car into the engine compartment of another car.

**Comment by timneutkens** [comment]
Yeah as far as I can see your description is correct @eezing

> it would be like trying to stuff a car into the engine compartment of another car.
:joy: :joy: :joy: :joy: :joy: :joy: :joy:

**Comment by zzh3319** [comment]
so? @timneutkens  can you make a demo for us to study?

**Comment by timneutkens** [comment]
Like @eezing said it's not possible at the moment
