### ISSUE TITLE
rebase component did mount

### ISSUE THREAD

**Issue by ayepRahman** [zeit/next.js#2839]
- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
Please provide a clear description of your issue / feature request 👌
