### ISSUE TITLE
Disable stacktrace on error

### ISSUE THREAD

**Issue by rprinsen** [zeit/next.js#2841]
Is there a way to disable stacktraces in nextJS?
Currently, even when i'm running nextjs in production mode, on an error nextjs shows a stacktrace in the http response body, containing full filesystem paths which I really would like to disable.

For instance, calling a url like this:
http://localhost:3000/_next/dummy/page

returns the following response:
```
 window.__NEXT_REGISTER_PAGE('/', function() {
      var error = {"name":"Error","message":"INVALID_BUILD_ID","stack":"Error: INVALID_BUILD_ID\n    at Server._callee9$ (/home/user/development/project/node_modules/next/dist/server/index.js:451:29)\n    at tryCatch (/home/user/development/project/node_modules/regenerator-runtime/runtime.js:65:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/user/development/project/node_modules/regenerator-runtime/runtime.js:303:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/user/development/project/node_modules/regenerator-runtime/runtime.js:117:21)\n    at step (/home/user/development/project/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)\n    at /home/user/development/project/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14\n    at Promise.F (/home/user/development/project/node_modules/core-js/library/modules/_export.js:35:28)\n    at Object.<anonymous> (/home/user/development/project/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)\n    at Object._nextBuildIdPagePath [as fn] (/home/user/development/project/node_modules/next/dist/server/index.js:514:27)\n    at Router._callee$ (/home/user/development/project/node_modules/next/dist/server/router.js:81:60)","buildIdMismatched":true}
      return { error: error }
    })
```

Is there a way to disable this behaviour?

**Comment by sergiodxa** [comment]
How are you running it in production? Next only has the stack trace enabled in development 🤔

**Comment by timneutkens** [comment]
@rprinsen this is a really good catch. It should do that. I've submitted a PR to fix it: #2843.

**Comment by rprinsen** [comment]
Great Tim! thanks for the quick response!
Would it be possible to merge this in the 2.x branch too?

We're running 2.4.9 now and are really close to a production release.
So not really keen on going to 3.x just yet :)

**Comment by timneutkens** [comment]
@rprinsen I'd highly recommend updating to v3, since it doesn't have real breaking changes, only a tiny bit of the getInitialProps of `_document` changed. The rest is the same + extra features / bugfixes / dev improvements etc 😄
