### ISSUE TITLE
Nodevember Discussion

### ISSUE THREAD

**Issue by ericclemmons** [zeit/next.js#285]
Howdy @rauchg! 

Tonight you mentioned some future plans for `Next.js` that are directly in line with preferences I have for my own projects.

I wanted to list out the ones I can remember & my _current take_ on potential solutions.

- - -

### Prefer `<div class="...">` over `<div className="...">`.
  - <https://github.com/insin/babel-plugin-react-html-attrs>

  _Everyone_ on my team prefers this because _no one's had to touch `element.className`_ manually since using React.  Having less context switching between React & HTML is 💯 .

### Less Babel.
  - <https://github.com/babel/babel-preset-env>

  We're _just now_ experimenting with this, but I was able to **avoid Babel entirely** in a recent project because _Chrome + Node support is that good_.  (Check out my [`webpack.config.js`](https://gist.github.com/ericclemmons/cf7c2a2139b7193d0d91cf958d3b2257))

  But, the gist is that we'll develop with only the latest Chrome + Node and, when `NODE_ENV=production`, build to the lowest-common-denominator.

  In the future, we're going to attempt individual targeted builds (e.g. Top 5 browsers and ES5 build) that are served depending on User Agent.

### Remove `import React from "react"`.
  - ([`webpack.ProvidePlugin` example](https://gist.github.com/ericclemmons/cf7c2a2139b7193d0d91cf958d3b2257))

  When writing functional components, _React is an implementation detail_.  In this case:

    1. Implicitly provide the `react` module when the `React` variable is referenced.
    2. Alias `react` package to `preact-compat` for smaller production bundles.

### Fragments.
  - <http://isfiberreadyyet.com/>

  We're both waiting for it :)

### Better `<style>` interface.
  - Glamor just released this, which I find much simpler to copy/paste old code into _CSS-in-JS_:

    https://github.com/threepointone/glamor/blob/master/docs/css.md

  I've also done `<Style>{`body { ... }`}</Style>` which _works_, but I'm not completely sold that this is _better_. It's an ugly, lateral solution to using existing CSS within React.  Having used some Glamor & `styled-components`, I'm increasingly confident that we're at a place that custom styles can build upon globals, as well as leveraging resets/normalizers to effectively sandbox styles for components (until Shadow DOM/CSS is viable).

### `<Head>`.
  Personally, I'm not a fan of side-effect components like `react-helmet` & similar.  In a Redux/MobX environment, I'm a fan of the centralized state tree being able to `APPEND_TITLE`, `SET_TITLE`, etc. for the layout to transform accordingly.

  For something like `Next.js`, `getDocumentMeta({ title })` could allow for `title.set(...)`, `title.append(...)`, etc. after the `getInitialProps` lifecycle.

- - -

Anyway, I wanted to jot this stuff down for a couple of reasons:

- I think `Next.js` is fantastic & deserving of wider adoption.
- These solutions, excluding maybe one or two, have existed in some form for a bit, so I assume they're on your radar and *I would like to know why they're not viable solutions*.  That way I can make better decisions for _my_ projects as well :)

**Comment by jonaswindey** [comment]
+1 on the removal of `import React from "react"`

Not sure about the class vs className since `standard` enforces single quotes in strings, so also for html attributes, which would mean they will not be 100% compatible with html anyway.

**Comment by cusxio** [comment]
I don't really understand the removal of `import React from 'react'`, what implications does it have? Where can I read more about it ?

**Comment by jonaswindey** [comment]
It's the fact that each component, even the smallest one, that uses jsx will need the import statement at the top

right now an index.js with this won't work:
```
export default () => <div>hi there, what's up</div>
```

You'll need
```
import React from 'react'
export default () => <div>hi there, what's up</div>
```

Which is basically overhead since almost all files that render something will need this import.

**Comment by arunoda** [comment]
@ericclemmons I think we could most of these stuff, when Next.js allows you to customize your babel and webpack config.

**Comment by rauchg** [comment]
> Personally, I'm not a fan of side-effect components like react-helmet & similar. In a Redux/MobX environment, I'm a fan of the centralized state tree being able to APPEND_TITLE, SET_TITLE, etc. for the layout to transform accordingly.

You don't really have to use `<Head>`, which is great. But it basically covers 99% of the use-cases with a very simple API that works with SSR, which is a really big deal.

**Comment by rauchg** [comment]
These are some really great thoughts. Thank you

**Comment by rauchg** [comment]
@cusxio I'm convinced JSX should be built into the language, like Reason (https://github.com/facebook/reason/pull/775). Right now it's a weird transformation for a specific framework. Plus, you need to `import` even if you don't explicitly use `React` in the file which is weird.

**Comment by rauchg** [comment]
Also, something worth noting is that I initially considering making the page a "full page". Since this is not possible with React and because it has lots of other complications, I discarded it.

```
export default () => (
  <html>
     <head>
       <title>woot</title>
     </head>
  </html>  
)
```

`<Head/>` is somewhat of an answer to those limitations. The fact that it's _composable_ is definitely questionable, but it _seems_ right for this use-case and it's been confirmed with our experience so far.

**Comment by ericclemmons** [comment]
Per your last comment, with any 3rd party lib, modal, or analytics, React barfs when rendering the full body. 

Glad you guys saw it. Closing so individual issues can be raised as needed...
