### ISSUE TITLE
rendering Mustache js templates

### ISSUE THREAD

**Issue by iamsoorena** [zeit/next.js#2857]
is it possible to use mustache js template inside next js app?(for amp-mustache)
when I try to render something like **{{template}}** with mustache js , next js will take over because of **braces**.

**Comment by eezing** [comment]
@iamsoorena I think this is outside the scope of Next.js. The question you probably need answered: **Is it possible to use amp-mustache in react?**

**Comment by timneutkens** [comment]
I agree with eezing.
