### ISSUE TITLE
Uploading images/files

### ISSUE THREAD

**Issue by nialloc9** [zeit/next.js#2861]
When I upload an image to static using fs to move it the image is not available untill I restart next. I'm assuming this is because it needs to be bundled. However, I was wondering is there an example of how to do this correctly when using nextjs framework?

**Comment by eezing** [comment]
@nialloc9 How often are uploading files?

**Comment by nialloc9** [comment]
Hey @eezing. This would be very regularly  as every user would have the ability to do this when posting messages. As it is a spa these need to be available straight away. I was researching this and I see that it should be in it's own folder with just read write permissions and not within the code base. I think this is the most logical and best solution so I am going to close this issue.

**Comment by nialloc9** [comment]
Hey @eezing. This would be very regularly  as every user would have the ability to do this when posting messages. As it is a spa these need to be available straight away. I was researching this and I see that it should be in it's own folder with just read write permissions and not within the code base. I think this is the most logical and best solution so I am going to close this issue.
