### ISSUE TITLE
Static HTML export adds a trailing slash to URLs

### ISSUE THREAD

**Issue by anothertaxi** [zeit/next.js#2862]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
I love the new static HTML export functionality in next 3.x, but it is behaving somewhat differently than I would expect. If you have a next.config.js that looks like this:

```javascript
// next.config.js
module.exports = {
  exportPathMap: function() {
    return {
      "/": {page: "/"},
      "/page2": {page: "/page2"},
    };
  },
};
```
then I would expect `next export` to create an `out` directory like this:

```
index.html
page2.html
```
and I would expect `Link` components that link to `/page2` to result in URLs that link to `/page2`.

## Current Behavior
Instead, the config above produces an `out` directory like this:

```
index.html
page2/index.html
```
and `Link` components that link to `/page2` result in URLs that link to `/page2/`.

## Context
I'm trying to make a next site that can be easily hosted on a static server, but this feature means that all of the URLs in the site have an unnecessary trailing slash. This is not only a bit unsightly, but it's also not the same behavior as `next start`.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  3.0.6       |
| node    |  8.2.1       |
| OS      |   macOS Sierra      |
| browser |   N/A      |
| etc     |         |

**Comment by sergiodxa** [comment]
That's because with simple HTML files (without a custom server router) the only way to avoid the `.html` is creating a directory with the file name and put a `index.html` inside, so if you have the file `page2.html` then you need to go to `/page2.html` instead of `/page2`, but if you create the folder you can do `/page2/` and avoid the `.html`

**Comment by anothertaxi** [comment]
@sergiodxa Thanks for the response! In my experience, though, that's that's not how a lot of static servers work these days. `http-server`, for example, will map `/page2` to `/page2.html` automatically, as will Netlify. Which servers are you thinking of that don't automatically map `/page2` to `/page2.html`?

**Comment by anothertaxi** [comment]
Let me ask this: if I were to make a PR that allowed `next export` to output `/page2.html` rather than `/page2/index.html`, is there a chance it could get accepted?

**Comment by arunoda** [comment]
I want this to be the default behavior as this is gonna work without any configurations. And it doesn't hurt.

But I'd like to have an option to remove that and save as `.html`.

**Comment by arunoda** [comment]
Closing this in favor of a PR.
