### ISSUE TITLE
Antd form validation doesn't work in production with next@3.0.6

### ISSUE THREAD

**Issue by XavierLeTohic** [zeit/next.js#2865]
Antd form validation doesn't work when using next 3.0.6.
I have to stay on 2.4.9.

This is the error that I get everytime I type on the input or I try to submit the form : 

<img width="404" alt="capture d ecran 2017-08-29 a 13 52 37" src="https://user-images.githubusercontent.com/6340490/29819695-0d06d962-8cc2-11e7-9075-fcba604b0a5d.png">

```js

import React, { Component } from 'react'
import { Form, Input, Button } from 'antd';

const FormItem = Form.Item;

class MyForm extends Component {

    handleEmailSubmit = (e) => {
        e.preventDefault();
       // The error happen when this.props.form.validateFields is called and on every change in the input
        this.props.form.validateFields((err, values) => {
            console.log(err, values)
        });
    }

    render() {

        const { getFieldDecorator } = this.props.form;

        return (
            <Form onSubmit={this.handleEmailSubmit}>
                <FormItem>
                    {getFieldDecorator('email', {
                        rules: [{
                            required: true, message: 'Email required',
                        }],
                    })(
                        <Input size="large" type="email" />
                    )}
                </FormItem>
                <Button
                    type="primary"
                    htmlType="submit"
                    size="large"
                >
                    Valider
                </Button>
            </Form>
        )
    }
}

export default Form.create()(MyForm);

```

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     3.0.6    |
| node    |    8.1.3     |
| OS      |     OSX    |
| browser |    Chrome     |

**Comment by eezing** [comment]
@XavierLeTohic 
- What react version?
- What antd version?
- Are you able to reproduce this error in a clean/new project?

**Comment by XavierLeTohic** [comment]
@eezing 

- What react version? 
=> React 15.6.1

- What antd version?
=> Antd 2.12.8

- Are you able to reproduce this error in a clean/new project?
=> I will try on a blank project tomorrow, I tried on a new page without anything else with the code provided above.

**Comment by pruhstal** [comment]
Your code is incorrect:

```
        this.props.form.validateFields().then((err, values) => {
            console.log(err, values)
        });
```

Should be:

```
this.props.form.validateFields((err, values) => {
   console.log(err, values);
});
```

**Comment by XavierLeTohic** [comment]
@pruhstal my apologies I copied the wrong code, but it doesn't work with the good version too.
I will make a little example soon.
