### ISSUE TITLE
Cannot (or should not) use `Router.prefetch()` in `render()`

### ISSUE THREAD

**Issue by amio** [zeit/next.js#2868]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
[document](https://github.com/zeit/next.js#imperatively-1) says:
```
import Router from 'next/router'
export default ({ url }) => (
  <div>
    <a onClick={ () => setTimeout(() => url.pushTo('/dynamic'), 100) }>
      A route transition will happen after 100ms
    </a>
    {
      // but we can prefetch it!
      Router.prefetch('/dynamic')
    }
  </div>
)
```

## Current Behavior

While use `Router.prefetch('/foo')` in `render()` would got an error:
```
No router instance found. You should only use "next/router" inside the client side of your app.
```

## Alternative Usage
Use it in `componentDidMount` works as expected:
```
  componentDidMount () {
    Router.prefetch('/foo')
  }
```

Is it a bug or the document needs update?

**Comment by arunoda** [comment]
That's something intended. You can't use `next/router` inside the server. What you are doing is correct. May be guard this to run only inside the client.
