### ISSUE TITLE
Can support egg.js?

### ISSUE THREAD

**Issue by MinJieLiu** [zeit/next.js#2874]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

egg.js: [https://github.com/eggjs/egg](https://github.com/eggjs/egg)

In this example: [https://github.com/zeit/next.js/blob/master/examples/custom-server-koa/server.js](https://github.com/zeit/next.js/blob/master/examples/custom-server-koa/server.js). **`ctx.respond = false`** causes a large number of koa middleware to be invalid. `egg.js` is based on`koa` implementation.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    v3     |
| node    |    8.4     |
| OS      |     mac    |
| browser |    *     |
| etc     |         |

**Comment by arunoda** [comment]
May be there will be ways to use with koa as it should have done. 

Basically to render page we return a promise. So, you need to wait until that. 

Not an expert on koa, but I guess it's doable. 

Closing this but feel free to discuss. Reopen or ping me if there is something needs from the core.

**Comment by MinJieLiu** [comment]
[https://github.com/eggjs/egg/issues/328](https://github.com/eggjs/egg/issues/328)

**Comment by yangchongduo** [comment]
@MinJieLiu Are you sure that the middleware is not working? Give a demo
