### ISSUE TITLE
Mixpanel maximum call stack error.

### ISSUE THREAD

**Issue by deejayxd07** [zeit/next.js#2877]
Sorry for the noob question.
When I add mixpanel just as the the normal procedure that was stated here:
https://mixpanel.com/help/reference/javascript

Seems like when I do the normal procedure and I navigate to different pages with mixpanel on it,
it keeps throwing maximum call stack error.

Help!

**Comment by AlexKlim** [comment]
@deejayxd07 did you find the answer? I have the same problem. thanks.
