### ISSUE TITLE
Better integrating CSS by default

### ISSUE THREAD

**Issue by HelloEdit** [zeit/next.js#2878]
I write this issue for a problem that seems recurring, the "CSS". Indeed, I have seen many people unable to include CSS files in their projects (myself, using [typeface-roboto](https://www.npmjs.com/package/typeface-roboto) and not wanting to change all the default configurations, I had to resolve to use a CDN). Next is really great, but I think a lot more documentation about CSS and ways to better integrated it would be appreciated by everyone.
Create-react-app creates a solid, durable webpack configuration for projects, why next would not do the same by default ? I think you could take example on their webpack cofigurations. 😄

In any case, good work, and incredible project! 👍 🎉 

PS: I find your system very poorly designed, **what are the differences between styles-jsx and CSS modules**, which I find really better?

**Comment by sergiodxa** [comment]
If you want to know more why CSS in JS (like styled-jsx) instead of CSS Modules and other alternatives check this awesome (and large) article by the creator of CSS Modules:
- [A Unified Styling Language](https://medium.com/seek-blog/a-unified-styling-language-d0c208de2660)

**Comment by coluccini** [comment]
Using styled-jsx is not mandatory. You can add a stylesheet from the /static/ folder and don't use any kind of css in your components. Or have one stylesheet with global styles and the use styled-jsx just for the deep styles.

**Comment by HelloEdit** [comment]
Hmm ... considering the benefits I see, I think change architecture for my styles and start working with the Next.js style system

Thank you !
