### ISSUE TITLE
Publish 'emit-file-loader' to npm?

### ISSUE THREAD

**Issue by davidchase** [zeit/next.js#288]
Hi guys,

really digging what next.js provides and i found [emit-file-loader](https://github.com/zeit/next.js/blob/master/server/build/loaders/emit-file-loader.js) really useful in my server prebuild setup and was wondering if there were any thoughts on publishing it to npm. 

I think others could benefit since i dont know if its currently possible to output a directory structure related to the input directories specified in entry.

either way thanks for the great work on next.js

**Comment by rauchg** [comment]
Makes a lot of sense.

**Comment by timneutkens** [comment]
@davidchase feel free to draft it up, the code is MIT licensed 👌
