### ISSUE TITLE
'next/link' can't work when build

### ISSUE THREAD

**Issue by hansinhu** [zeit/next.js#2884]
```
<Link href={{ pathname: '/products', query: { type: 'top' `}}}>
<a className="nav-font"> TOP SELLING </a>
</Link>
<Link href={{ pathname: '/products', query: { type: 'new' }}}>
<a className="nav-font"> NEW ARRIVALS </a>
</Link>
```
build : http://localhost:3000/products?type=top
page tips: An unexpected error has occurred.

**Comment by timneutkens** [comment]
You'll most likely see an error either in your terminal or in the browser console. With only this information I cannot reproduce the issue.
