### ISSUE TITLE
Wrong behaviour when a page dose not exists 

### ISSUE THREAD

**Issue by ioganegambaputifonguser** [zeit/next.js#2889]
I scanned my website with a security scanner and there are a lot warnings when it try to get the pages from the _next/HASH/page/* url

## Expected Behavior
GET /_next/2025e8cd-80d3-454a-bf9f-ddd04aedcd3d/page/admin.aspx

should return the 404 error code with my 404 error page

## Current Behavior

GET /_next/2025e8cd-80d3-454a-bf9f-ddd04aedcd3d/page/admin.aspx

I get the 200 status code and this text in the browser

```
window.__NEXT_REGISTER_PAGE('/admin.aspx', function() {
        var error = new Error('Page does not exist: /admin.aspx')
        error.statusCode = 404

        return { error: error }
      })
```

**Comment by niccai** [comment]
FWIW, this is quite problematic when using a cloud platform like Fastly.  During a purge, you could get a stale html doc returned that references the js from a previous immutable build.  If this didn't return a 200, fastly would be able to more accurately deal with the transition to the new deploy.

**Comment by timneutkens** [comment]
Fixed in next@canary.
