### ISSUE TITLE
metatags are not being populated when I use custom _document

### ISSUE THREAD

**Issue by AvraamMavridis** [zeit/next.js#2890]
I created a very simple `_document` element just to add the `lang='en'` to the `html` tag

```
import Document, { Main, NextScript } from 'next/document';
import React from 'react';
import flush from 'styled-jsx/server';

export default class MyDocument extends Document {

  static getInitialProps ({ renderPage }) {
    const {html, head, errorHtml, chunks} = renderPage()
    const styles = flush()
    return { html, head, errorHtml, chunks, styles }
  }

  render () {
    return (
     <html lang="en">
        <Main />
        <NextScript />
     </html>
    )
  }
}
```

The problem that I am facing is that the `<Head />` is not rendered on the server (if I disable the javascript I see an empty head tag), but it is correctly populated dynamically on the client. Am I missing something or this is a bug?

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js#custom-document

You're missing this bit:
`import Document, { Head, Main, NextScript } from 'next/document'`

`<Head />`

**Comment by AvraamMavridis** [comment]
@timneutkens I was using the `<Head /> in my `<Layout />` component (same as the layout example in the repo) so I wasn't missing it. The head was populated on the client, but not on the server. If I had't include it at all I wouldn't see any head I guess (?)

**Comment by timneutkens** [comment]
You literally need to add `<Head />` above `<Main />` then it'll work, this is the sole reason it's not showing up on the server 😄 this head component is something different than `next/head`.

**Comment by AvraamMavridis** [comment]
@timneutkens I see, thx a lot.
