### ISSUE TITLE
404 page for static HTML export?

### ISSUE THREAD

**Issue by pcmaffey** [zeit/next.js#2892]
From the docs on static HTML export:
> So, you could only use pathname, query and asPath fields of the context object passed to getInitialProps. You can't use req or res fields.

Does static export entirely negate the ability to use the _error.js component for error handling, which is dependent on `res`? How would I go about creating a 404 page?

The current behavior is that any unknown routes redirect to `/index.js`.

One possible solution I can think of is to maintain a list of all routes and check against it to see if pathname is found. However this seems especially onerous to run on every page load for a site/blog that generates 100s of routes.

Is there a way to do this? 
Or is it possible to define a custom error route and redirect to that instead? 
Or even better, catch all routes within subfolders? eg
```
 {
    ...routes,
     '/*': { page: '/_error.js' },
    '/blog/*': { page: '/blog/_error.js' },
  }
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by thinnakrit** [comment]
add ``_error.js``  for custom error page


```
root
  |---pages
  |        |---  _error.js
```
