### ISSUE TITLE
Open Collective

### ISSUE THREAD

**Issue by jabacchetta** [zeit/next.js#2897]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

I just started using Next.js and so far I've been blown away by the combination of features and simplicity.

I'd like to donate in some way. How should I go about doing that? An [Open Collective](https://opencollective.com/), maybe?

**Comment by timneutkens** [comment]
It's fun to see how people are in the: take my money! mode 😄 @rauchg can weight in on this 👌 

Thanks for the kind words ❤️

**Comment by rauchg** [comment]
@jabacchetta first of all thanks a lot!

Here are some of the highest priority contribution areas:
- "Good first bug" labeled issues on GitHub
- Examples and documentation. 
- Triaging issues and questions from the community on https://zeit.chat
