### ISSUE TITLE
500 (Internal Server Error), while following Getting started in Readme

### ISSUE THREAD

**Issue by driglou** [zeit/next.js#2899]
I have just heard about next.js so I wanted to give it a try, however as I ran `npm run dev` I get Internal Server Error on localhost:3000 and in console `GET http://localhost:3000/ 500 (Internal Server Error)`

**Same results using zeit/nextgram**

- [x] I have checked Next.js Issues and while my issue seems like a duplicate, there was no solution.
- [x] Followed everything as in Readme, used Powershell, Git bash, results are always the same.

Error text
`{ Error: Cannot find module D:\path\.next\dist\pages\_error
    at _callee$ (D\path\node_modules\next\dist\server\resolve.j
s:220:19)
    at tryCatch (D:\path\node_modules\regenerator-runtime\runtim
e.js:65:40)
    at Generator.invoke [as _invoke] (D:\path\node_modules\regen
erator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (D:\DEV\
up\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (D:\path\node_modules\babel-runtime\helpers\asyncToG
enerator.js:17:30)
    at D:\\path\node_modules\babel-runtime\helpers\asyncToGenerat
or.js:28:13 code: 'ENOENT' }`

| Tech    | Version |
|---------|---------|
| next    | 3.2.1 |
| node  | 7.5.0 |
| npm  | 4.1.2 |
| OS      | Windows 10 |

**Comment by timneutkens** [comment]
Interesting, I can't debug it though cause it's windows. @arunoda could you check it?

**Comment by phc5** [comment]
I was getting Internal Server Error after following the setup steps in the README.

I had my project in ~/c/Users/<username>/Desktop/<project-name> but after moving it down to ~/c/Users/<project-name> I was able to run npm run dev without any issues on Windows 10 (npm v5.3.0 and node v8.5.0).

**Comment by DanielRSnell** [comment]
Just attempted this with the same error without success

**Comment by liweinan0423** [comment]
maybe the file path is too long. try move the project directory to the top level of the partition, like `d:\<project-name>`
