### ISSUE TITLE
Redux saga with proper hot reload

### ISSUE THREAD

**Issue by smoliji** [zeit/next.js#2902]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

I've been following the https://github.com/zeit/next.js/tree/master/examples/with-redux-saga example and noticed when I change the code in the saga files, the app is hot-reloaded, although not the saga files. The new saga code starts working after F5 reload.

## Expected Behavior
When saga files changed, the changes are propagated with the rest of the app and replaced the existing saga code.

## Current Behavior
```
client.js?3cc2700:199 [HMR] bundle rebuilding
client.js?3cc2700:207 [HMR] bundle rebuilt in 439ms
process-update.js?3cc2700:27 [HMR] Checking for updates on the server...
process-update.js?3cc2700:100 [HMR] Updated modules:
process-update.js?3cc2700:102 [HMR]  - ./saga.js
process-update.js?3cc2700:102 [HMR]  - ./store.js
process-update.js?3cc2700:102 [HMR]  - ./pages?entry
process-update.js?3cc2700:107 [HMR] App is up to date.
```
But saga code is still the former one, until next server render.

## Steps to Reproduce (for bugs)
1. clone the with-redux-saga example
2. Run with `next`
4. Add some changes, e.g. console.log at the saga beginning https://github.com/zeit/next.js/blob/master/examples/with-redux-saga/saga.js#L31
5. save, watch the code replace, but not the saga.

Is this even possible? The saga file is executed after change, but the saga code in the generators does not.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    v3.2.1     |
| node    |   v5.12.0    |
| OS      |   Windows 10 x64  |
| browser |    Google Chrome, Version 60.0.3112.113 (Official Build) (64-bit)    |

**Comment by timneutkens** [comment]
It probably has to module hot accept, same as redux requires.
