### ISSUE TITLE
Dynamic Import load .json?

### ISSUE THREAD

**Issue by jacobpdq** [zeit/next.js#2903]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
I expected to have my .json file returned. 

## Current Behavior
Instead, I was asked for 'module' or 'render' objects.

## Steps to Reproduce (for bugs)
1. Create a JSON file to import
2. use dynamic(require) to import the file
3. voila

## Context
I'd like to use the dynamic import in a page-loading situation whereby my .md/json is loaded in on the prop-injection. Better than working with fetch as the export function is respected by next and the require baked-in.

**Comment by sergiodxa** [comment]
You are able to do `await import('path/to/file.json`)`, the `next/dynamic` module is for rendering dynamic React component but you don't need it to use async imports.

```js
const data = await import('../data.json')
console.log(data);
```

👆 that works.

**Comment by timneutkens** [comment]
Nice!
