### ISSUE TITLE
NextJS suddenly stopped working in my machine

### ISSUE THREAD

**Issue by johhansantana** [zeit/next.js#2907]
I'm not sure what's happening if it's on my end but I nextjs suddenly stopped working for me.

I've even started from scratch and did:

`npm init`
`npm install --save next react react-dom`

Added script for `"dev": "next"`

and ran it

I keep getting this error:
![image](https://user-images.githubusercontent.com/9933887/30039365-b697913a-919d-11e7-9422-37d660d8b280.png)

I've tried v2 of nextjs but still the same thing.

**Comment by eveetsc** [comment]
npm 5.4.0 for some reason does not allow to run to react properly.
Install npm 5.3.0 with -> sudo npm install npm@5.3.0

**Comment by johhansantana** [comment]
@eveetsc omg, this has caused us so many issues.... we were opening issues everywhere like crazy. thanks! I had to remove the `node_modules` folder and reinstall everything using npm v5.3.0

**Comment by timneutkens** [comment]
@eveetsc that's pretty crucial 😓 💩
