### ISSUE TITLE
Make the router only load pages from the top level of the url path?

### ISSUE THREAD

**Issue by jcheroske** [zeit/next.js#2912]
I'm experimenting with using React Router 4 in conjunction with Next.js. Our application uses the Next.js `/pages` directory to split up our app into separate, medium-sized modules. Within each of those pages/modules, we would like to use react-router to handle URLs. Right now, Next.js treats the following URLs as different pages:
  * `/portal`
  * `/portal/login`
  * `/portal/products`

What we would like is for Next to only care about the first part of that path (`/portal`), We want it to load the same `portal.js` page for all three of those paths. If it did that, I think that react-router could then be used to handle the more fine-grained routing from there on down.

Is there a place in the configuration where I could change the page matching logic, such that only the top-level of the path is consulted when trying to determine the file to load from the `/pages` dir?

**Comment by sergiodxa** [comment]
That's not configurable and is intended to works how it's working right now to allow any possible path. Why are you using React Router? Next.js came with a builtin router, yo don't need RR and if you want custom urls (eg. with params) you can create a custom server (as showed in many examples).

If you still want to use React Router just don't use `/pages`, only create a index.js file there where all your routes should go and then import your pages code from any other directory.
