### ISSUE TITLE
How use moduleDirectories in next.js?

### ISSUE THREAD

**Issue by tronghiep92** [zeit/next.js#2913]
Hi all,

I had a look at https://github.com/tleunen/babel-plugin-module-resolver but it was not enough for me.
I want to use moduleDirectories(webpack) but it does not work on next.js.

It looks like https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346#shared-module-resolution

Thanks advance.

**Comment by timneutkens** [comment]
It's currently not possible to use that webpack config. We have an example for plugin-module-resolver. https://github.com/zeit/next.js/tree/master/examples/with-absolute-imports.
