### ISSUE TITLE
Configuring public path for hot middleware reload

### ISSUE THREAD

**Issue by beku8** [zeit/next.js#2914]
We are trying to use nextjs for certain parts of our app. So I have a proxy app running on ```http://localhost:8080```, which will dispatch certain requests to nextjs app running on ```http://localhost:3000```. For production environment, hopefully, it will work fine with ```assetPrefix: 'http://{production_url}'```, but for development the following requests are being made for hot module replacement:

- ```/_next/webpack-hmr```
-``` /_next/on-demand-entries-ping?page=/```

which are apparently configured as a relative path, so when I access thru my proxy, it will try to access at ```http://localhost:8080/_next/on-demand-entries-ping?page=/``` from the browser.

Is there any possible way to override the path to explicitly define to fetch from ```http://localhost:3000```?

**Comment by sergiodxa** [comment]
I tried to replicate it and my `/_next/on-demand-entries-ping?page=/` and `/_next/webpack-hmr` both goes to the correct port. Could you provide a repository to replicate it?

**Comment by timneutkens** [comment]
Will be fixed when https://github.com/zeit/next.js/pull/2901 lands 👍
