### ISSUE TITLE
Source map broken with 3.1.0 -> 3.2.0

### ISSUE THREAD

**Issue by oliviertassinari** [zeit/next.js#2915]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I would expect to see the source map in the dev tools of Chrome.

## Current Behavior

<img width="234" alt="capture d ecran 2017-09-06 a 13 08 18" src="https://user-images.githubusercontent.com/3165635/30108907-87174b90-9304-11e7-9bf4-1355d87fdc95.png">

## Steps to Reproduce (for bugs)

With Material-UI:

1. `git clone git@github.com:callemall/material-ui.git`
2. `cd material-ui`
3. `git checkout v1-beta`
4. `yarn`
5. `yarn docs:dev`

Or with a simpler project: https://github.com/callemall/material-ui/tree/v1-beta/examples/nextjs.

## Context

1. I have first noticed this issue on a project at work.
2. Hopefully, I was able to nail down the npm release that introduced the issue [by a bisection between](https://github.com/callemall/material-ui/compare/v1.0.0-beta.6...v1.0.0-beta.7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L74) the `v1.0.0-beta.6` release and `v1.0.0-beta.7` release of Material-UI.
3. I'm also able to reproduce the issue on a simpler example, the [nextjs example](https://github.com/callemall/material-ui/tree/v1-beta/examples/nextjs) of Material-UI.

So, it's 3 independent projects impacted by the issue. I do think that it's a strong [SNR](https://en.wikipedia.org/wiki/Signal-to-noise_ratio) ratio.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | v3.2.1         |
| node    | v8.1.4        |
| OS      | MacOs        |
| browser | Chrome        |

**Comment by timneutkens** [comment]
Hey, this was fixed and will be in the next released 👌

**Comment by timneutkens** [comment]
@arunoda

**Comment by oliviertassinari** [comment]
:)

**Comment by csevier** [comment]
I am on 3.2.1 and this is happening to me. Perhaps I am not doing this right. Can some one point me to a proper webpack config? I has see multiple mentions that its enabled in "dev" by default. Some guidance would be appreciated. I am new to webpack and nextjs. I would be happy to share my teams webpack function in out next.config.js

**Comment by csevier** [comment]
Scratch that. Title is misleading. 3.2.2 solves.
