### ISSUE TITLE
Quotes being escaped in <Head> CSS

### ISSUE THREAD

**Issue by yunyu** [zeit/next.js#2917]
- [X] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Bug: the single quotes are escaped when they shouldn't be in this code:

    <Head>
      <style>{`
      body {
        display: flex;
        align-items: center;
        justify-content: center;
        background: url('/static/img/bg.jpg');
      }
      `}</style>
    </Head>

## Current Behavior

This is rendered as:

      <style class="next-head">
      body {
        display: flex;
        align-items: center;
        justify-content: center;
        background: url(&#x27;/static/img/bg.jpg&#x27;);
      }
      </style>

Which is incorrect.

## Steps to Reproduce (for bugs)

1. See above code

## Context

This makes using URL resources or fonts with spaces in <Head> CSS close to impossible.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 3.2.1        |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
This is basic react functionality which we won't be able to change. You can use dangerouslySetInnerHtml to inject without escaping. If you're doing global styling you can also use `<style jsx global>{`html { background: red; }`}</style>`. In that case please don't use `<Head>` around it 👍

**Comment by yunyu** [comment]
Yep, read the docs a bit more and realized that style global works outside of Head. Thanks!

**Comment by timneutkens** [comment]
Great 🙌
