### ISSUE TITLE
How to use interceptors in next js?

### ISSUE THREAD

**Issue by BijayRai** [zeit/next.js#2919]
How to use interceptors in next Js..
for example i've to check on every request response that token is expired or not .
i've used fetch as per doc in getInitialProps to get response .. 
so, i am confused or say blank to set global interceptors so on each request it automatically check its expired or not. How to achieve this?

**Comment by sergiodxa** [comment]
You can use a high order component with that shared logic and wrap every page with that HOC.
Example: https://github.com/zeit/next.js/tree/master/examples/with-higher-order-component

BTW, there's no way to create a global HOC that is automatically applied to every page, you need to apply it manually to every page.

**Comment by BijayRai** [comment]
@sergiodxa  I am confused how HOC helps me to create interceptors? 
 
I want something like this to be done in next js. So, that on each fetch request if some response said expired or something i want to do something on each those request or response. which i want to set global. 

```
You can intercept requests or responses before they are handled by then or catch.

// Add a request interceptor
axios.interceptors.request.use(function (config) {
    // Do something before request is sent
    return config;
  }, function (error) {
    // Do something with request error
    return Promise.reject(error);
  });

// Add a response interceptor
axios.interceptors.response.use(function (response) {
    // Do something with response data
    return response;
  }, function (error) {
    // Do something with response error
    return Promise.reject(error);
  });
```
