### ISSUE TITLE
Stylization jumps when loading page. Most noticeable with Safari.

### ISSUE THREAD

**Issue by paulwehner** [zeit/next.js#2923]
When I click between pages of my Next.js app, there is a big stylization jump that occurs where buttons will start out stretched out and then jump to their appropriate size, along with every other component on the page.

Is there a suggestion on how to remedy this issue? Can the page be pre-loaded or not rendered until the stylization has been applied to all components. Not sure if this a React issue or something to do with how page loading occurs with Next.js using the Link component and server vs browser rendering.

Once again, the issue appears most prominently with the latest Mac Safari browser.

**Comment by timneutkens** [comment]
How are you doing styling?
