### ISSUE TITLE
can package to a file use webpack?

### ISSUE THREAD

**Issue by wjszxli** [zeit/next.js#2924]
## Context
We use next.js as the react server rendering, next.js is good, but there is a problem, we packed to the server, because we did not find the method packaged into a file, so posted to the server when the speed is very slow, the need to node_modules folder to the server, so once released need more than 3 minutes

## My Environment

| Tech    | Version |
|---------|---------|
| next    |     3.2.1    |
| node    |     8.0    |
| OS      |      macOs 10.12   |
| browser |  chrome   60.0     |
| etc     |         |

**Comment by timneutkens** [comment]
Hi,
I don't understand the issues you're trying to explain. Is the page load slow? The build time?
