### ISSUE TITLE
Is my server crashing due to favicon issue ?

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#2926]
My server is crashing everytime (even in production) .

I am tired and i'm wondering what can cause these crashes

```javascript
info: User function triggered, starting execution
info: Execution took 60006 ms, finished with status: 'timeout'
info: Execution took 18329 ms, finished with status: 'crash'
info: Execution took 60005 ms, finished with status: 'timeout'
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
```

In the other hand, in my next webpack server, i've noticed something weird.

I'm making a`GET` request in my `getInitialProps`.

```javascript
const res = await axios.get('http://localhost/fetchserverdata',{params: { ID : req}})...
```

It's seems the param `GET` request is fire several times and the value of param `ID` is replaced by `favicon.ico` as i can see in my log :

```javascript
...
_headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/fetchserverdata?ID=favicon.ico',
        _ended: true,
        _redirectable: [Object],
        parser: null,
        res: [Object] },
     data: { error: [Object] } } }
```

Of course my server doesn't expect `favicon.ico` and can't process the request. So it's probably what  causing the `timeout` then `crash`

Why `favicon` is sent as parameter ?

How can i prevent this and prevent my app to crash ?

Thanks for helping

**Comment by timneutkens** [comment]
First of I'd say passing the whole `req` object to an external request is a bad practice. When you open a web page it'll do a request for the page and `/favicon.ico` I'm expecting your server is not handling the routes correctly which is causing it to try to render a page when requesting `/favicon.ico`
