### ISSUE TITLE
Now-style update warnings

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#293]
We should warn that your Next version is not up to date.

- For `next` (ie: dev mode only).
- We should only do this if a new semver patch or feature is available, but not major?
- Now-style: https://github.com/zeit/now/blob/master/lib/check-update.js (very slim)
- Not sure what this looks like with #264?

**Comment by timneutkens** [comment]
@rauchg new implementation for now-cli is using the [update-notifier](https://www.npmjs.com/package/update-notifier) package

**Comment by timneutkens** [comment]
Implemented here https://github.com/zeit/now-cli/blob/0c2ef197adc3d5b2f9cddd6f359b326a3b132ce3/bin/now.js#L27
