### ISSUE TITLE
shouldComponentUpdate is skipped on change route, every component re-rendered

### ISSUE THREAD

**Issue by marbemac** [zeit/next.js#2935]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

This is related to #88, but not quite the same. In this case, we are routing between the same page (/user.js), not different pages. Something weird is happening with the normal react lifecycle hooks for ALL page child components (all the way down the tree) that makes it impossible to prevent something from re-rendering.

Essentially, this means that on every route change (even if you are routing between the same page) every single component on the page is forced to re-render, and there is no way to stop it.

## Expected Behavior

shouldComponentUpdate should be triggered as normal on the page component, and its child components.

## Current Behavior

shouldComponentUpdate is skipped on the page component, and its child components.

## Steps to Reproduce

I have created an example that reproduces the issue in an isolated environment. It includes instructions for running, and seeing what's going on. It also includes a link to an animated gif for you lazy folks out there :).

https://github.com/stoplightio/nextjs-router-bug

## Context

We have complicated inner components and not being able to prevent them from re-rendering is a problem.

**Comment by coluccini** [comment]
Hi @marbemac, sounds like this is the same bug I've reported a few months ago:

https://github.com/zeit/next.js/issues/2114

**Comment by marbemac** [comment]
Ah didn't see that one, thanks @coluccini - closing this and commenting over there.
