### ISSUE TITLE
with-global-stylesheet example: maybe it better to extract css with extract-text-webpack-plugin?

### ISSUE THREAD

**Issue by BjornMelgaard** [zeit/next.js#2936]
Really concerned about load speed in[ this with-global-stylesheet](https://github.com/zeit/next.js/blob/master/examples/with-global-stylesheet) example 

I'm using the same approach in [my boilerplate](https://github.com/BjornMelgaard/my-nextjs-typescript-boilerplate) and got this image with analyzer, as you see about half of size falls on grommet css
![2017-09-10-22 08 22-screenshot](https://user-images.githubusercontent.com/7573215/30252066-9f87f922-9674-11e7-86bf-f701be3f029a.png)

As I saw author of [universal-webpack](https://github.com/catamphetamine/universal-webpack) proposes to extract css and add it to[ page through `<link ...>` ](https://github.com/catamphetamine/universal-webpack#chunks), since css loaded by browser asynchronously

**Comment by 2rajpx** [comment]
+1
