### ISSUE TITLE
Hot reloading sub-components

### ISSUE THREAD

**Issue by jonaswindey** [zeit/next.js#294]
When you have a page `test.js` in /pages, only changes to that file will be hot-reloaded.

If you have a file `child.js` and load this from `test.js`, any changes to `child.js` will not be hot reloaded.

`test.js`
```javascript
import React from 'react'
import Child from './child'

export default () => <div>hello <Child /></div>
```
`child.js`
```javascript
import React from 'react'

export default () => <div>world</div>
```

**Comment by lipp** [comment]
You should keep you (reusable) sub-components in your own "components" dir, parallel to the "pages" dir.
Just as this [example](https://github.com/zeit/next.js/tree/master/examples/nested-components) does.
If you stick to this, the hot-reloading works just fine.

**Comment by jonaswindey** [comment]
Yep, I know. But this is not documented and I don't see the reason to have this limitation to only support the /components directory

**Comment by rauchg** [comment]
There shouldn't be such a limitation, and this issue is legitimate. Thanks @jonaswindey
