### ISSUE TITLE
Using a debugger on client side code does not show source code in chrome 

### ISSUE THREAD

**Issue by jackdeng** [zeit/next.js#2941]
I put a debugger in client side page (in the /pages dir specifically) and the chrome developer tool will pause but in the screen that usually shows source code to step through I see a blank window.

p.s. great job btw, nextjs is sweet.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1. put DEBUGGER in any component render function
2. chrome browser will pause
3. open developer tools, go to Source tab
4. in the javascript asset, there is no source code, instead I see:

```
null

// WEBPACK FOOTER //
// ./pages/broker_of_record.js
```

```
## Context

I cannot step through source code and debug 😞 

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    3.2.1     |
| node    |    v8.4.0     |
| OS      |   macOS Sierra 10.12.6      |
| browser |  Version 61.0.3163.79 (Official Build) (64-bit)       |
| etc     |         |

**Comment by jackdeng** [comment]
I'll provide the environment information when I get home

**Comment by steida** [comment]
I can confirm.

**Comment by jackdeng** [comment]
I've updated the ticket with the version information, thank you for looking into this!

**Comment by timneutkens** [comment]
Please update to 3.2.2, it has been fixed there 👍

**Comment by jackdeng** [comment]
SWEET!!!
