### ISSUE TITLE
Question: isServer vs checking req/res?

### ISSUE THREAD

**Issue by kjs3** [zeit/next.js#2946]
I have `isServer` in `getInitialProps` which looks like it's coming from [`lib/dynamic.js`](https://github.com/zeit/next.js/blob/master/lib/dynamic.js#L36).

I'm checking this on a bunch of pages but just realized it's not one of the [documented](https://github.com/zeit/next.js#fetching-data-and-component-lifecycle) params.

Is this param going to disappear and am I living on the edge? :)
Should I add `isServer` to the readme?

**Comment by timneutkens** [comment]
@kjs3 fun fact, we never intended nor included `isServer` it's something that magically works when using webpack in a universal environment. Which is pretty cool 😄. Personally I stick with req/res checks, and I don't think we should document it 👍

**Comment by kjs3** [comment]
Thanks @timneutkens, good to know.

**Comment by timneutkens** [comment]
Happy to explain 😄
