### ISSUE TITLE
Why can't I .gitignore .next/ files?

### ISSUE THREAD

**Issue by thetoxicavenger** [zeit/next.js#2948]
This is probably just me being novice at .gitignore, but after doing a lot of googling I'm unable to understand what I am doing wrong. Here is the link to my repo (next.js-boilerplate branch): https://github.com/thetoxicavenger/google-sheets-api-test. Thank you.

**Comment by enmai1988** [comment]
I don't see .next in the .gitignore file?

**Comment by MAPESO** [comment]
Could you explain your problem better. I just checked your package.json but you do not have **next.js** installed.

**Comment by kylealwyn** [comment]
@thetoxicavenger You have the line commented out: https://github.com/thetoxicavenger/google-sheets-api-test/blob/next.js-boilerplate/.gitignore#L60

Change that line to just contain `.next` and then run `git rm -r --cached .next` to remove the folder from your git repo

**Comment by timneutkens** [comment]
Like @kylealwyn said 😄

**Comment by thetoxicavenger** [comment]
@kylealwyn  @timneutkens yep, props Kyle. Didn't know about that git command; that's exactly what I was looking for! Kudos.
