### ISSUE TITLE
Warning: Unknown prop `jsx` on <style> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by BijayRai** [zeit/next.js#2950]
I'am getting this error `Warning: Unknown prop `jsx` on <style> tag. Remove this prop from the element.`on my project . 

So, i thought there must be some issue in my code but recently i tested out [Next Basic CSS example ](https://github.com/zeit/next.js/tree/master/examples/basic-css) . There too am getting this error.

Even i changed next Js version as `2.0.0` in `package.json` but still I am getting this issue. So , how can i fix this issue?

**Comment by pruhstal** [comment]
Did you nest it within a `<div></div>`? Please post a code example!
