### ISSUE TITLE
Use available babel-runtime, don't resolve it relatively

### ISSUE THREAD

**Issue by ianwensink** [zeit/next.js#2951]
In the `next/babel.js` the babel-runtime module is aliased to use a local version. This is bad practise, since the build script should use any available version of `babel-runtime`, which allows me to use my own.

- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

In `dist/server/build/babel/preset.js` on line `:24` there is an alias for `babel-runtime` to relatively resolve it inside of next.js. This should be removed, so any version of `babel-runtime` inside the `node_modules` folder is used, not just the one in `next/node_modules`

## Current Behavior

The build script throws an error, since all `babel-runtime` modules are `undefined`.
Currently generated when building:
`var _regenerator = require('next/node_modules/babel-runtime/regenerator');`
Expected/wanted behaviour when building:
`var _regenerator = require('babel-runtime/regenerator');`

## Steps to Reproduce (for bugs)

1. Have a module (let's call it `module-a`) with `next` as `devDependecy`
1. In `modula-a`, use `next/babel` as babelrc preset
1. Build `module-a` to a lib folder
1. In the generated lib files, `var _regenerator = require('next/node_modules/babel-runtime/regenerator');` is now inserted at the top
1. Use `module-a` in another project (`module-b`) that doesn't have `next` as `dependency`.
1. Build `module-b`
1. The build script throws an error, since all `babel-runtime` modules are `undefined` (`next` is not installed in `module-b`).

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 3.0.6 |

**Comment by unregistered** [comment]
What's the latest on this issue? It looks like the PR was reverted.

Because yarn pushes packages up to avoid duplicating them, if another package uses the same version of babel-runtime, it seems like yarn will install it in the root node_modules folder, which means next won't be able to find it.

The dirty fix is to run `ln -s ../../babel-runtime node_modules/next/node_modules/`

Not sure if there's a better way
