### ISSUE TITLE
next/dynamic load antd error react #130

### ISSUE THREAD

**Issue by fxh615** [zeit/next.js#2953]
when use next/dynamic loding a component include antd , something wrong with react 130# error .
if i remove dynamic load it work well . 

## Context

| Tech    | Version |
|---------|---------|
| next    |     3.2.2    |
| node    |     7.10.1    |
| OS      |     windows    |
| browser |     chrome    |
| etc     |         |

**Comment by fxh615** [comment]
app.js:39 Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]=%20Check%20the%20render%20method%20of%20%60t%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by pruhstal** [comment]
Please provide an example of your code.

**Comment by vipnetvnn** [comment]
Hi, 
Need change import antd in .babelrc
`[
        "transform-runtime",
        [
          "import", {
            "libraryName": "antd",
            "style": true
          }
        ]
      ]
`

**Comment by fxh615** [comment]
@vipnetvnn  not work because my project also have antd-mobile lib and antd lib

**Comment by fxh615** [comment]
may be is the antd bug i change the pagnation ui cm  to render on client it works

**Comment by MickaelBZH** [comment]
I also have the same issue with antd. 
The interesting part of it is that it does work on dev but not on prod ...

**Comment by designspin** [comment]
I am experiencing this #130 error also, although works in dev:

Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (http://localhost:3000/_next/2f87a5c61d5514001a913d24d63f2535/app.js:15:64864)
    at te (http://localhost:3000/_next/2f87a5c61d5514001a913d24d63f2535/app.js:15:74495)
    at createFiberFromElement (http://localhost:3000/_next/2f87a5c61d5514001a913d24d63f2535/app.js:15:141590)
    at c (http://localhost:3000/_next/2f87a5c61d5514001a913d24d63f2535/app.js:15:76122)
    at v (http://localhost:3000/_next/2f87a5c61d5514001a913d24d63f2535/app.js:15:77619)
    at b (http://localhost:3000/_next/2f87a5c61d5514001a913d24d63f2535/app.js:15:78405)
    at http://localhost:3000/_next/2f87a5c61d5514001a913d24d63f2535/app.js:15:80831
    at u (http://localhost:3000/_next/2f87a5c61d5514001a913d24d63f2535/app.js:15:83392)
    at a (http://localhost:3000/_next/2f87a5c61d5514001a913d24d63f2535/app.js:15:83288)
    at beginWork (http://localhost:3000/_next/2f87a5c61d5514001a913d24d63f2535/app.js:15:85653)

I started getting the problem when trying to load a Module with XMLHttpRequest via a web worker, the way I am doing it feels pretty wrong!

`const work = new Worker('/static/worker.js');
    
    work.addEventListener('message', (e) => {
    
    const script = document.createElement('script');
    let base64 = 'data:application/javascript;base64,';

    try {
      base64 += btoa(unescape(encodeURIComponent(e.data)));
    } catch(err) {
      let symbols = e.data.split(' ');
      for(let i = 0, l = symbols.length; i < l; i++) {
        let symbol = symbols[i];
        try {
          btoa(symbol);
        } catch(err) {
          let code = symbol.charAt(0).toString(16);
          while(code.length < 4) {
            code = '0' + code;
          }
          symbols[i] = '\\u' + code;
        }
      }
      base64 += btoa(symbols.join(''));
    } finally {
      script.src = base64;
      document.body.appendChild(script);
    }
    
    setTimeout(() => {
      CanvasAnim = window.module.exports.default;

      this.setState({
        canvas: true
      });
    }, 1);
    

    }, false);

    work.postMessage('getCanvasAnim');`

If I omit the CanvasAnim = window.module.exports.default, it will work again.

I was trying to expose the module as a library via webpack config, but was not getting any success.

**Comment by designspin** [comment]
That all occurs in component did mount of my index page, in case anybody is interested.
