### ISSUE TITLE
Make `next build/export` programmatically accessible

### ISSUE THREAD

**Issue by craig-mulligan** [zeit/next.js#2954]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

I'm building a wrapper module around next.js and was looking for an easy way to call `build` and `export` where I can pass the config in much the same was as the server api can be initiated. 

Judging by nexteins implementation this is the [currently the way to interact with these apis](https://github.com/elmasse/nextein/blob/master/bin/nextein).

it'd be great if we had either of the following: 
```
const nextApp = next({ dev, conf })

// server
await nextApp.prepare()

// build / export
await nextApp.build()
await nextApp.export()
```

Alternatively 
```
const build = require('next/server/build')
const export = require('next/server/export')

await build({ dev, conf })
...
```

Thoughts?

**Comment by bin4ryio** [comment]
Hi. Is this gonna open up possibility to render Next programmatically? I have the followings code in an Isomorphic Nuxt (Vue) + Express as a middleware:

Will this patch allow me to do the same in Nextjs?

```
const { Nuxt, Builder } = require('nuxt')
const logger = require('winston')
const config = require('../../nuxt.config')

const nuxt = new Nuxt(config)

if (config.dev) {
  new Builder(nuxt).build()
    .then(() => process.emit('nuxt:build:done'))
    .catch((error) => {
      logger.error(error)
      process.exit(1)
    })
} else {
  process.nextTick(() => process.emit('nuxt:build:done'))
}

module.exports = nuxt
```

**Comment by craig-mulligan** [comment]
@bin4ryio, yes you can. See the [custom server docs](https://github.com/zeit/next.js#custom-server-and-routing), what I was specifically referring to was that the `export` function only reads config from disk rather than reading from an argument. (this is fixed now so you can do)

```
const nextBuild = require('next/dist/server/build')
const nextExport = require('next/dist/server/export')

nextBuild(<dir>, <config>)
.then(() => {
     return nextExport(<dir>, <exportOpts>, <config>)
})
```

I've been building a little wrapper around next.js and nuxt.js for graphql powered static sites, the [code](https://github.com/craig-mulligan/nextatic/blob/master/lib/adapters/next/index.js) maybe helpful to look at.

**Comment by craig-mulligan** [comment]
#2962 fixes this issue.
