### ISSUE TITLE
When I use draft.js, editorState false  [Help]

### ISSUE THREAD

**Issue by wanlerong** [zeit/next.js#2963]
### error
Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.
editorState.getCurrentContent is not a function
React DOM tree root should always have a node reference.

## my code is

```js
import { Component } from 'react';
import ReactDom from 'react-dom';
import { Editor, EditorState } from 'draft-js';
export default class TestEditor extends Component {
  constructor(props) {
    super(props);
  }
  static async getInitialProps ({ query, req }) {
    return { editorState: EditorState.createEmpty()}
  }
  render() {
    console.log('init',this.props.editorState);
    return (
      <div>
        <h1>Test Editor</h1>
        <Editor
          editorState={ this.props.editorState }
        />
      </div>
    );
  }
}
```

my package.json
```json

{
  "name": "nextnote",
  "version": "1.0.0",
  "license": "ISC",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "antd": "^2.12.2",
    "babel-plugin-import": "^1.2.1",
    "babel-plugin-module-resolver": "^2.7.1",
    "babel-plugin-wrap-in-js": "^1.1.1",
    "draft-js": "^0.10.1",
    "draftjs-to-html": "^0.7.5",
    "es6-promise": "^4.1.1",
    "isomorphic-fetch": "^2.2.1",
    "less": "^2.7.2",
    "less-loader": "^4.0.5",
    "next": "latest",
    "next-redux-wrapper": "^1.0.0",
    "raw-loader": "^0.5.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-draft-wysiwyg": "^1.10.8",
    "react-error-overlay": "^1.0.10",
    "react-icons": "^2.2.5",
    "react-infinite-scroller": "^1.0.15",
    "react-redux": "^5.0.6",
    "react-router": "2",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  }
}
```
I have no Idea about this,and would be very appreciative

**Comment by pruhstal** [comment]
What if you do this:

```
import { Component } from 'react';
import { Editor, EditorState } from 'draft-js';

export default class TestEditor extends Component {
  constructor(props) {
    super(props);
    this.state = {editorState: EditorState.createEmpty()};
  }
  render() {
    console.log('init',this.state.editorState);
    return (
      <div>
        <h1>Test Editor</h1>
        <Editor  editorState={this.state.editorState}  />
      </div>
    );
  }
}
```

It makes much more sense to make state since you're technically not even passing props to this component (although you're setting them in an unnecessary `getInitialProps` call.

Also, you don't need `ReactDOM`.

**Comment by omerdn1** [comment]
I am also getting this issue when trying to pass entityMap.
Doesn't occur with: `contentState={{
                    entityMap: {},
                    blocks: htmlToDraft(this.props.test)
                      .contentBlocks,
                  }}`

occurs with: `contentState={{
                    entityMap: htmlToDraft(this.props.test)
                      .entityMap,
                    blocks: htmlToDraft(this.props.test)
                      .contentBlocks,
                  }}`

Breakpoint: `editorState = EditorState.createWithContent(convertFromRaw(props.contentState));`

**Comment by pruhstal** [comment]
@wanlerong @omerdn1 did you guys ever figure this out?

**Comment by timneutkens** [comment]
I don't think this is a Next.js issue but rather something related to draft.js and server side rendering React. Feel free to post on spectrum.chat/next-js if you still run into this.
