### ISSUE TITLE
Crashing in Tor on "High" security level.

### ISSUE THREAD

**Issue by blecher** [zeit/next.js#2967]
Hi Next.js team, and thank you for your amazing framework,

We are testing out a .onion version of our site (single onion service). When opening my Next.js app in Tor browser on "Medium" [security level ](https://en.wikipedia.org/wiki/Tor_(anonymity_network)#Levels_of_security)all works fine, however "High" (with JS enabled) security level redirects to `_error.js`. `this.props.statusCode` from `_error.js` returns `null`, no 500's in Network, and console has the following: 

`a is undefined`
`f.setValueForStyles@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:379620
m.Mixin._updateDOMProperties@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:377777
m.Mixin.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:374095
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
g.performInitialMount@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:392312
g.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:391195
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
h<.Mixin.mountChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:387051
m.Mixin._createInitialChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:375928
m.Mixin.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:374142
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
h<.Mixin.mountChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:387051
m.Mixin._createInitialChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:375928
m.Mixin.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:374142
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
g.performInitialMount@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:392312
g.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:391195
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
g.performInitialMount@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:392312
g.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:391195
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
g.performInitialMount@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:392312
g.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:391195
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
g.performInitialMount@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:392312
g.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:391195
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
h<.Mixin.mountChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:387051
m.Mixin._createInitialChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:375928
m.Mixin.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:374142
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
h<.Mixin.mountChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:387051
m.Mixin._createInitialChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:375928
m.Mixin.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:374142
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
g.performInitialMount@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:392312
g.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:391195
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
g.performInitialMount@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:392312
g.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:391195
o<.mountComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80389
g._updateRenderedComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:395896
g._performComponentUpdate@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:395413
g.updateComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:394691
g.receiveComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:393808
o<.receiveComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80783
u.updateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:388901
h<.Mixin._reconcilerUpdateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:386814
h<.Mixin._updateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:387560
h<.Mixin.updateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:387458
m.Mixin._updateDOMChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:378320
m.Mixin.updateComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:376526
m.Mixin.receiveComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:376079
o<.receiveComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80783
u.updateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:388901
h<.Mixin._reconcilerUpdateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:386814
h<.Mixin._updateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:387560
h<.Mixin.updateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:387458
m.Mixin._updateDOMChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:378320
m.Mixin.updateComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:376526
m.Mixin.receiveComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:376079
o<.receiveComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80783
u.updateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:388901
h<.Mixin._reconcilerUpdateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:386814
h<.Mixin._updateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:387560
h<.Mixin.updateChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:387458
m.Mixin._updateDOMChildren@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:378320
m.Mixin.updateComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:376526
m.Mixin.receiveComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:376079
o<.receiveComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80783
g._updateRenderedComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:395659
g._performComponentUpdate@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:395413
g.updateComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:394691
g.performUpdateIfNecessary@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:394024
o<.performUpdateIfNecessary@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:80965
s@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:67275
o.perform@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:15:2042
o.perform@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:15:2042
.perform@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:68332
k@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:68509
o.closeAll@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:15:2624
o.perform@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:15:2122
f.batchedUpdates@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:402481
o@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:12:66862
W._renderNewRootComponent@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:120213
W._renderSubtreeIntoContainer@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:121198
W.render@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:121325
e/<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:55:6139
r@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:326092
l/<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:327214
s/</e[t]@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:326268
r@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:7:80819
t.default/</<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:7:80971
w@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:335642
t.default/<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:7:80765
module.exports<[637]/d</<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:55:6331
e/<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:55:4696
r@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:326092
l/<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:327214
s/</e[t]@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:326268
r@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:7:80819
t.default/</<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:7:80971
w@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:335642
t.default/<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:7:80765
module.exports<[637]/t.render</<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:55:4928
e/<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:55:8243
r@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:326092
l/<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:327214
s/</e[t]@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:326268
r@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:7:80819
r/<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:7:80919
D/</<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:334520
D/<@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:334390
e.exports/l@http://myTorSingleOnionHiddenServiceSite.onion/_next/4b84e8ff32fe0cbdee5584c6f8890db7/app.js:29:337519`

I am not loading any fonts, but I do have some SVG files. However, not being able to load SVG shouldn't crash an app, should it?
Could this be a problem with the framework?

| Tech    | Version |
|---------|---------|
| next    |    3.0.2   |
| node    |  6.11.2     |
| OS      |    Ubuntu 16.04     |
| browser |  Tor     |
| material-ui |  1.0.0-beta.4     |

**Comment by MAPESO** [comment]
@arunoda  Take a look at this problem is very interesting 🤔

**Comment by timneutkens** [comment]
@blecher is there an issue way to reproduce this / test this locally? @MAPESO I'll take a look once we can reproduce 👍
