### ISSUE TITLE
Autorefreshing on 404 page (again?)

### ISSUE THREAD

**Issue by kachkaev** [zeit/next.js#2968]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

I'm playing with next 3.2.2 and am quite enjoying its simplicity and the plentifulness of examples. Awesome experience, even compared with other boilerplates I've used before!

After building a simple demo website based on the [`with-apollo`](https://github.com/zeit/next.js/tree/master/examples/with-apollo) example, I noticed a behaviour previously mentioned in #1888/#2305 and fixed in https://github.com/zeit/next.js/pull/2437.

## Expected vs Current Behavior

My sandbox project has got three pages: `index`, `about` and `_error`, all wrapped into `withData` HOC that helps init and reuse the apollo client. There is also a custom `_document` page that enables [i18n](https://github.com/zeit/next.js/tree/master/examples/with-react-intl) and [styled-components](https://github.com/zeit/next.js/tree/master/examples/with-styled-components). When I navigate between `index` and `about`, GraphQL cache persists and so there is no `loading...` message showing up after the data has been loaded for the first time (no matter if on the server or on the client). However, when visit a 404 page and then return to an existing page, the redux cache appears to be reset and so apollo does the data fetching again. Also when I click on a link that leads to a 404 error, Chrome's history of network requests wipes out, thus suggesting that the 404 page shows up after a full reload.

<s>I deployed a built version of my experiment to https://example.com/, but this URI is likely to be deleted or replaced in a few days. Quite an ugly demo, but should be enough to reproduce what I mean.</s> The sources are in a private gitlab repo, but I can upload them to github if necessary.

How could I avoid this refresh behaviour and thus provide future users with a smoother UX?

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  3.2.2       |
| node    |  8.5.0       |
| OS      |  macos / alpine linux (docker)       |
| browser | latest chrome        |

**Comment by kachkaev** [comment]
@arunoda do you think your your PR #2437 could be somehow cancelled out? @pie6k @hchoriq do you experience the same problems in the latest next.js as you reported in #1888 and #2305?

**Comment by timneutkens** [comment]
I think this was fixed.
