### ISSUE TITLE
setTimeout / setInterval in event handler doesn't work correctly

### ISSUE THREAD

**Issue by hiromitz** [zeit/next.js#2975]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

In my project using next.js, I was trying to make carousel for mobile.

But for some reason, setTimeout / setInterval in event handler doesn't work correctly.
Timer takes few seconds even if set 100ms.
This is affect ONLY for **Android Chrome**. iOS Safari and Chrome work fine.

Here is my sample component code.
```handler``` is called right after ```touchend```, but the code inside ```setTimeout``` run after few seconds.

This component works fine in the project by using create-react-app .

```
import React from 'react';

class Scroller extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      scrolled: [],
    };
    this.handler = this.handler.bind(this);
  }
  handler(e) {
    setTimeout(() => {
      this.setState({
        scrolled: [...this.state.scrolled, 'yes'],
      });
    }, 100);
  }
  render() {
    return (<div>
      <style jsx>{`
        .scroller {
          width: 300px;
          overflow-x: auto;
          white-space: nowrap;
        }
        .box {
          display: inline-block;
          margin: 0 15px;
          width: 100px;
          height: 100px;
          line-height: 100px;
          text-align: center;
          border: 1px solid #ccc;
        }
      `}</style>
      <div
        className="scroller"
        onTouchEnd={this.handler}
      >
        {[1,2,3,4,5,6,7,8,9,10].map(key => (
          <div className="box" key={key}>{key}</div>
        ))}
      </div>
      <ul>
        {this.state.scrolled.map((str, i) => (
          <li key={i}>{str}</li>
        ))}
      </ul>
    </div>)
  }
}
export default Scroller;
```

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  3.2.2    |
| node    |   8.4.0  |
| OS      |   MacOS 10.12.6  |
| browser | Android Chrome    |

**Comment by timneutkens** [comment]
I guess this is related to React and not Next 🤔

**Comment by pruhstal** [comment]
https://stackoverflow.com/a/11613327

**Comment by timneutkens** [comment]
Thanks @pruhstal! ❤️

**Comment by hiromitz** [comment]
@timneutkens I thought so, but like I wrote, pure react project works fine.

@pruhstal thanks. but its not woking even i added preventDefault. and its about Android <4, really old post.

Could someone try my code?

**Comment by pruhstal** [comment]
@hiromitz yes, it's old, but if you expand the comments, someone said it's still broken in 4.4.4 (~2015). Which could mean that it's still not fixed today.

**Comment by hiromitz** [comment]
@pruhstal Oh, I see. Thanks.
