### ISSUE TITLE
Use redux-observable in getInitialProps

### ISSUE THREAD

**Issue by Tomekmularczyk** [zeit/next.js#2979]
I'm wondering If I can use redux-observable epics that handle **ajax** calls inside `getInitialProps`?
Tried it and failed, because epics just react to actions that were already dispatched.

[StackOverflow question](https://stackoverflow.com/questions/46380861/next-js-and-redux-observable-handle-requests-in-getinitialprops)

**Comment by kkak10** [comment]
@Tomekmularczyk me too. i set redux-observable ajax call but getInitialProps action is failed....
