### ISSUE TITLE
how to export  custom JSON api ? 

### ISSUE THREAD

**Issue by mydearxym** [zeit/next.js#2982]
Hey guys!

i add a custom JSON api , [source](https://github.com/mydearxym/mastani/blob/boilerplate/server.js#L56)
and it works fine in local dev ( /locale/en is accessable in browser)

```js
app.prepare().then(() => {
  createServer((req, res) => {
  .....
    if (localeMatch) {
      res.setHeader('Content-Type', 'application/json;charset=utf-8')
      return res.end(JSON.stringify(getMessages(localeMatch.lang)))
    }
  .....
  }).listen(3000, err => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000')
  })
})
```
my next.config.js [source](https://github.com/mydearxym/mastani/blob/boilerplate/next.config.js): 

i know i should add locale config to let `next` know how serve `xx/locale/en` request

```js
exports.exportPathMap = () => ({
  '/': { page: '/' },
  '/home/i': { page: '/', query: { name: 'index' } },
  '/home/feature': { page: '/', query: { name: 'feature' } },
  '/home/theme': { page: '/', query: { name: 'theme' } },
  '/home/i18n': { page: '/', query: { name: 'i18n' } },
  '/home/example': { page: '/', query: { name: 'example' } },
  '/shop': { page: '/shop' },
})
```
but how ?  i don't have a actual page called 'locale' , how can i config this ?

Or i should use the solution in #2939  ?

**Comment by timneutkens** [comment]
In this case you need to use `'/locale/en': {page: '/'}`
The object keys are url paths and the value defines the `page` inside of your `pages` directory and the `query` object for getInitialProps 👍
