### ISSUE TITLE
expand quiet flag to hide all error messages

### ISSUE THREAD

**Issue by rprinsen** [zeit/next.js#2984]
This is followup on issue #2841 

http://localhost:3000/_next/dummy/page now returns the following response (HTTP 200):
    window.__NEXT_REGISTER_PAGE('/', function() {
      var error = {"message":"500 - Internal Server Error.","buildIdMismatched":true}
      return { error: error }
    })
  
Currently i have the 'quiet' server option set to true. 
Would it be possible to disable all error messages when the quiet option is set to true and just respond with the corresponding http status code?

So: expected behaviour on any error with quiet flag on true:
- HTTP statuscode 500 (or whichever status code is relevant)
- empty response body

(although technically i would expect http://localhost:3000/_next/dummy/page to return a http 404)

**Comment by niccai** [comment]
Related to #2889
