### ISSUE TITLE
Placeholder loading app while fetching data

### ISSUE THREAD

**Issue by dcatanzaro** [zeit/next.js#2985]
Hi.

Im using NextJS for a big project and I want to add a placeholder loading while fetching data.

Example:
![image](https://user-images.githubusercontent.com/3155693/30816001-24f28934-a1eb-11e7-88fd-5076836a7c63.png)

Currently NextJS use fetch in getInitialProps and wait to fetch all data to show de render.

Is there a way to show the basic render with placeholder loading and in the background do the fetch?

Thanks!

**Comment by ragingwind** [comment]
How about https://github.com/zeit/next.js#router-events

**Comment by MAPESO** [comment]
@dcatanzaro If the doubt was resolved, I suggest closing the subject 😸

**Comment by azza85** [comment]
@dcatanzaro I have it working in this issue, https://github.com/zeit/next.js/issues/2981 I am having a few issues on a dynamic level page but may work for what you are looking for.

**Comment by dcatanzaro** [comment]
Thanks! I will see both.

**Comment by JustasPolis** [comment]
If you want to show some loading/placeholders just dont fetch on SSR, use componentDidMount and fetch when client kicks in and while fetching show your placeholder :)

**Comment by dcatanzaro** [comment]
I'm trying to continue using SSR, and when it comes from de client-side use componentDidMount!

Thanks!.

**Comment by timneutkens** [comment]
Like @JustasPolis said when you use componentDidMount to fetch you can render the placeholder server side 👍

**Comment by nyl-auster** [comment]
Hello ! Can someone provide an example of this ? I want my page to display "loading ..." until getInitialProps() Promise is resolved; so it is basically the same need than the one described in this issue.

Should I use router events ? is there an example somewhere on how this has to be done ? Should i use a store to update a "pageLoading" variable ?

Should I use componentDidMount ? I dont understand this suggestion, as i guess i will loose SSR if i use this method... 

Any help appreciated :)

**Comment by timneutkens** [comment]
@nyl-auster https://github.com/zeit/next.js/tree/master/examples/with-loading might help

**Comment by nyl-auster** [comment]
@timneutkens definitely does, thanks !
So the answer is : use Router events. The above example is using nprogress to display a progress bar at the top of the page and that works great, but we can do anything we want this way...

```JavaScript
Router.onRouteChangeStart = (url) => NProgress.start()
Router.onRouteChangeComplete = () => NProgress.done()
Router.onRouteChangeError = () => NProgress.done()
```

**Comment by timneutkens** [comment]
👌 Happy it helped 😄

> There's an example for that! - Tim Neutkens
