### ISSUE TITLE
"asPath" is missing in url objects

### ISSUE THREAD

**Issue by gwn** [zeit/next.js#2987]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

"asPath" information should be present in url objects that are passed as
properties to components, as documented in:
https://github.com/zeit/next.js/blob/master/readme.md#with-link

> Each top-level component receives a url property with the following API:
> 
> ...
> asPath - String of the actual path (including the query) shows in the browser
> ...

## Current Behavior

"asPath" is not present in url objects

## Steps to Reproduce (for bugs)

1. Check out the "url" properties of page components to see that "asPath" is missing

## Notes
I'm aware that I can get "asPath" from the router object, but it looks like I should be able to get it from the url object as well.

**Comment by azza85** [comment]
@gwn do you have a code sample?

I can access it in `getInitialProps` as shown below.

```
<Link prefetch as={'/news/title-1'} href={'/news?title=title-1'}><a>{'Title 1'}</a></Link>
```


```
class News extends Component {
  static async getInitialProps({query,pathname,asPath}) {
```

returns 
```
query =>  {title: "title-1"}
pathname =>  /news
asPath =>  /news/title-1
```

**Comment by timneutkens** [comment]
@azza85 I know what he means 😄 Every top level page automatically gets `this.props.url` even if you don't use getInitialProps
