### ISSUE TITLE
Ability to configure babel-preset-env missing

### ISSUE THREAD

**Issue by tmcw** [zeit/next.js#2989]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I'd expect a way to configure `babel-preset-env` to support a narrower range of browsers, and thus use more native ES6 features. I'd like to rely on native browser implementations of classes, generators, and other commonly-supported-in-edge features. The babel-preset-env project allows for this configurability, but its encapsulation within `next/babel` prevents users from configuring.

## Current Behavior

There is no route to adjusting the amount of transpilation, so ES6 code is compiled down to the lowest-common-denominator always.

## Context

My product uses generators - as part of the product - so that's one guarantee that I can rely on, and accordingly use generators in the code. Right now the over-aggressive transpilation means, among other things, that [performance is decreased on features like for of](http://incaseofstairs.com/six-speed/), and sourcemap debugging is less effective.

I see that there [was already a PR suggesting this behavior](https://github.com/zeit/next.js/pull/1808), but it was closed by its author. There was also [a feature request](https://github.com/zeit/next.js/issues/2021), also closed. I'm more than happy to reimplement / update that PR and push this to completion, because it's important for my usecase.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   3.2.2      |
| node    |    8.4.0     |
| OS      |      macOS   |
| browser |      Google Chrome   |

**Comment by jrolfs** [comment]
I'm able to accomplish this with a custom Babel configuration (`.babelrc` in the root of the project), which I believe has been mentioned elsewhere in the issues here:

```json
{
  "presets": [
    ["env", {
      "modules": false,
      "debug": true,
      "useBuiltIns": "usage",
      "targets": {
        "browsers": [
          "last 2 Chrome versions",
          "last 2 ChromeAndroid versions",
          "last 2 Edge versions",
          "last 2 Firefox versions",
          "last 2 FirefoxAndroid versions",
          "last 2 iOS versions",
          "last 2 Opera versions",
          "last 2 Safari versions"
        ]
      }
    }],
    "next/babel"
  ]
}
```

However, it would be really nice to have support for a separate, common [browserslist configuration](https://github.com/ai/browserslist#queries) that other tools can share.

It seems [babel-preset-env](https://github.com/babel/babel-preset-env) is quite [out of date](https://github.com/zeit/next.js/blob/master/package.json#L63) and therefore lacks support for external configuration (package.json, `.browserslistrc`, `browerslist`, etc.).

Hopefully the above will help some people configure `babel-preset-env` in the meantime, should I open a separate issue for upgrading the dependency?

**Comment by jrolfs** [comment]
Sorry, I was looking at the unreleased version of `babel-preset-env` ... I could have sworn the current version support external **browserslist** configuration...

**Comment by acanimal** [comment]
Hi,
I applied the configuration similar than the suggested by @jrolfs but know my tests (using jest) related to react components doesn't work anymore raising an error similar to `SyntaxError: Unexpected token import`.

My babel config is as follow. For the `test` environment I tried different values for the `modules` options but no one seems to work. Any help?

```
  "presets": [
    ["env", {
      "modules": false,
      "debug": true,
      "useBuiltIns": false,
      "targets": {
        "browsers": [
          "last 2 Chrome versions",
          "last 2 ChromeAndroid versions",
          "last 2 Edge versions",
          "last 2 Firefox versions",
          "last 2 FirefoxAndroid versions",
          "last 2 iOS versions",
          "last 2 Opera versions",
          "last 2 Safari versions"
        ]
      }
    }],
    "next/babel"
  ],
  "env": {
    "test": {
      "presets": [
        ["env", {
          "modules": "commonjs",
          "debug": true,
          "useBuiltIns": false,
          "targets": {
            "node": "6"
          }
        }]
      ]
    }
  },
```

**Comment by timhuff** [comment]
I was able to resolve this by merging my person babel configs with the configs specified in [the next.js .babelrc](https://github.com/zeit/next.js/blob/canary/.babelrc). It's a bit off book so buyer beware but it seems to do the trick. @goldensunliu, is this a bad idea? It's the only way I can get my server-side libraries to play well with next.
