### ISSUE TITLE
Sourcemaps broken in simplest example

### ISSUE THREAD

**Issue by tmcw** [zeit/next.js#2990]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I'd expect sourcemaps of a basic module to enable breakpoint selection on all lines, except those clearly represented differently through transpilation.

## Current Behavior

A basic component is not debuggable with sourcemaps: clicking on a line to set a breakpoint does not set a breakpoint at that line.

## Steps to Reproduce (for bugs)

1. Example: https://github.com/tmcw/next-sourcemap-breakage-example

Single page with the source:

```js
import {Component} from "react";
export default class Button extends Component {
  render() {
    function foo() {
      console.log(1);
    }
    return <button onClick={foo}>hi</button>
  }
};
```

Setting a breakpoint on the line

```js
      console.log(1);
```

Is not possible:

![next-bug](https://user-images.githubusercontent.com/32314/30833972-fc1c7784-a205-11e7-91ec-ec99624c5852.gif)

## Context

This makes debugging applications quite difficult.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    3.2.2     |
| node    |      8.4.0   |
| OS      |    macOS 10.12.6     |
| browser |      Google Chrome 61.0.3163.100   |

**Comment by timneutkens** [comment]
cc @kpdecker since you updated the sourcemaps 👌

**Comment by ckeeney** [comment]
I have this problem too and I'm surprised more developers are not complaining about this issue.  Is there a workaround for this?

**Comment by tmcw** [comment]
I've updated the testcase repository to React v0.16.x and Next.js ^4.0.3, and can confirm the issue persists in the updated versions.

**Comment by scsper** [comment]
I've also seen this issue in our app

**Comment by kpdecker** [comment]
#3121 fixes both the immediate issue here and another where breakpoints were lost in Chrome on every page refresh.
