### ISSUE TITLE
Can not change status code when using custom render method

### ISSUE THREAD

**Issue by chemzqm** [zeit/next.js#2992]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Current Behavior

I have custom route something like:
```
    router.get('/feed/:id/subs', async (ctx, next) => {
      ....
      await n.render(ctx.req, ctx.res, '/feed/subs', query)
    })
```
And in the `getInitialProps` of page `/feed/subs` I throw error like:

```
let error = new Error('没有权限')
error.statusCode = 401
throw error
```

I can have error message shown correctly, but the status code would always 500, I think I should have the ability to change the status code.

## Context

I've tried to change status code after `render`, but no hope, response is finished after `render`

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   3.2.2     |
| node    |   8.5  |
| OS      |    MacOS     |
| browser |  any       |
| etc     |         |

**Comment by ragingwind** [comment]
Using return with status code not throwing https://github.com/zeit/next.js#custom-error-handling

**Comment by chemzqm** [comment]
@ragingwind Looks like I have to handler the error myself.
