### ISSUE TITLE
learnnextjs.com installs react 16 and fails to compile

### ISSUE THREAD

**Issue by JasonRitchie** [zeit/next.js#2997]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Steps at https://learnnextjs.com/basics/getting-started/setup should succeed compilation and show 404 in the browser.

## Current Behavior

>  ERROR  Failed to compile with 1 errors                                                                                                                      

> 15:19:19
> 
> This module was not found:
> 
> * react-dom/lib/ReactReconciler in ./node_modules/next/dist/client/next-dev.js
> 
> To install it, you can run: npm install --save react-dom/lib/ReactReconciler
> (node:78867) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead

> Ready on http://localhost:3000

## Steps to Reproduce
Steps are at https://learnnextjs.com/basics/getting-started/setup

## Context
This is my initial discovery of nextjs and my first exploration of the learning resources.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |        3.2.2 |
| node    |    8.1.2     |
| OS      |    macOS 10.12.6     |
| browser |     Chrome 61    |
| nvm     |      0.32.1   |

**Comment by glennreyes** [comment]
Related: https://github.com/zeit/next.js/issues/1098

**Comment by JasonRitchie** [comment]
For any beginners trying to get past this, simply replace the npm install command with the following:

`npm install --save react@15 react-dom@15 next`

**Comment by timneutkens** [comment]
@JasonRitchie I've updated the readme, next.js v4 beta will be released soon by @rauchg. 👍

**Comment by gringogidget** [comment]
Same issue for me :)

**Comment by sscaff1** [comment]
`npm i --save next@4.0.0-beta.2` worked for me.

**Comment by yantakus** [comment]
This should be closed I suppose as next v4 is out of beta for a long time.

**Comment by timneutkens** [comment]
👍
