### ISSUE TITLE
[Question] Tree Shaking howto?

### ISSUE THREAD

**Issue by brikou** [zeit/next.js#2999]
Because code is run on browser and server, we cannot take full advantage of webpack tree shaking. The code is transformed to commonjs before anything.

How is it possible to take full advantage of tree shaking? (I've tried webpack-common-shake without success)

ESM is landing in node 8.5 with --experimental-module and also available with @std/esm package. Do you have any plan about this?

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not x duplicate.

**Comment by Goluis** [comment]
Tree Shaking si enabled by default in next as long as you're not using a babel preset that transforms imports in commonjs, also next is using `babel-preset-env` but without transforming the modules.

**Comment by brikou** [comment]
Are you sure?, because in webpack.js there is a plugin to get it back to commonjs https://github.com/arunoda/next.js/blob/68738d1c904476e9c99989ae5ee12a90c184fbc1/server/build/webpack.js#L228

**Comment by Goluis** [comment]
Yes, I already asked something similar some days ago
![d909c7ac5ca479266459da4447077cb8](https://user-images.githubusercontent.com/4278345/30888307-75130268-a2e5-11e7-8f97-ee82ccfa96e2.png)

**Comment by goldensunliu** [comment]
We can either close this issue. Or submit a simple PR to verify the tree shaking output for the people to believe I
