### ISSUE TITLE
npm install next@beta got old version

### ISSUE THREAD

**Issue by Larry850806** [zeit/next.js#3007]
I'm trying to use `npm install next@beta` to install `4.0.0-beta.1` and use react 16，but I got `next@3.0.1-beta.21`

**Comment by JeromeFitz** [comment]
Right now it is waiting to be published per @timneutkens on the `#next` Slack channel.

> tim [21:17 GMT] 
> Working on it :slightly_smiling_face:
> rauchg has to publish it :slightly_smiling_face:

**Comment by naquiuddin** [comment]
Would be great if this is done as soon as possible. Want to use react 16.

**Comment by timneutkens** [comment]
Just released the new version 👌

**Comment by naquiuddin** [comment]
Awesome! Thanks.
