### ISSUE TITLE
Documentation request: Recommended solutions for static cache invalidation

### ISSUE THREAD

**Issue by ericelliott** [zeit/next.js#3023]
It's a good idea to create immutable static assets, such as images, and set the cache to never expire. It appears that Next.js does a good job of this for the JavaScript files, but it would be great to document a solution for CDN static assets.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Next.js build assets get served from `_next/<some uuid>/<asset path>`. Perhaps a similar solution could work for static assets as well? We could supply instructions for setting up common reverse proxies to serve the static assets properly (nginx, haproxy).

## Current Behavior

Static assets always get served from the same URL, which forces users to roll their own cache-invalidation solution for static content, even though perfectly usable cache-invalidation is already built-in to Next.js.

## Context

We recently rolled a new version of one of our apps into production. Everything worked great, but it served up the old image assets, which may cause a lot of confusion.

Presumably, a solution to this problem is needed for every application ever made. We should make sure it's covered in the Next.js documentation.

## Your Environment

No bug. Just requesting documentation.

**Comment by yakovkhalinsky** [comment]
I wonder if you could use a custom webpack config with the `file-loader` and add a hash to do this?

https://webpack.js.org/loaders/file-loader/

Haven't tried this. Might give this a quick go on Monday morning.

**Comment by timneutkens** [comment]
@sergiodxa made an example: https://github.com/zeit/next.js/tree/canary/examples/with-hashed-statics
