### ISSUE TITLE
Prettier config for the examples folder?

### ISSUE THREAD

**Issue by jthegedus** [zeit/next.js#3028]
Now that Prettier supports config files it would be much simpler to support a style for the `examples/` directory. I know you use Standard as per https://github.com/zeit/next.js/issues/1527, I'm only suggesting this for the `examples/` directory. A lot of the React, JS and TS community are moving to Prettier and are also the people to create the examples in this repo. By having a `.prettierrc` in the `examples/` directory everyone who uses Prettier would not need to turn off or alter their settings each time they want to contribute (I've been struggling with this all day on various repos).

Again, this is not a suggestion to run Prettier over the Next.js source, just a config in the `examples/` directory.

I don't intend to start a long discussion on this, I just thought the friction might be much lower now Prettier has configs. Feel free to close this without discussion if it is not of interest to any maintainers.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

This config seems to apply a style almost identical to the current styling of some of the examples from Next.js Maintainers.
```json
{
  "tabWidth": 2,
  "trailingComma": "none",
  "printWidth": 100,
  "singleQuote": true,
  "semi": false
}

```

PS: thanks for your work!

**Comment by timneutkens** [comment]
I guess we could support this. I'd still like to do it for the whole project though 👍 I'll work on this 😄

**Comment by radeno** [comment]
Why not use Prettier with ESlint? It is very nice combination.
Then you need use just .eslintrc and then Prettier plugin for editor use this config

**Comment by timneutkens** [comment]
Going to close this. We'll add it sometime in the future. Not in the short term.
