### ISSUE TITLE
Basic example of custom CSS

### ISSUE THREAD

**Issue by thebetterjort** [zeit/next.js#3033]
I'm looking for understanding of how to load a css framework, or custom css file with the use of styled components and next.js?

**Comment by timneutkens** [comment]
There's a lot of css examples :smile: https://github.com/zeit/next.js/tree/master/examples
https://github.com/zeit/next.js/tree/master/examples/with-styled-components
https://github.com/zeit/next.js/tree/master/examples/basic-css
https://github.com/zeit/next.js/tree/master/examples/with-global-stylesheet

**Comment by thebetterjort** [comment]
Module not found: Error: Can't resolve 'grommet/components/App' in '/usr/src/app/pages'
resolve 'grommet/components/App' in '/usr/src/app/pages'
  Parsed request is a module
  using description file: /usr/src/app/package.json (relative path: ./pages)
    Field 'browser' doesn't contain a valid alias configuration
