### ISSUE TITLE
Environment variable is undefined when deploying the Dotenv Example with Docker

### ISSUE THREAD

**Issue by syncspot-dockercloud** [zeit/next.js#3035]
I followed the [with-dotenv](https://github.com/zeit/next.js/tree/master/examples/with-dotenv) example to structure my environment variables. When I do development (aka `npm run dev`), everything works as expected. The app is pulling the environmental variable from the `.env` file.

But when I write a docker file, build the image, upload it to Docker Hub, and then host my cluster on Docker Cloud, for some reason the environment variable isn't being included in the app.js that is served to the browser.

For reference, here is my Dockerfile:

```dockerfile
FROM node:alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

RUN npm run build
EXPOSE 3014

CMD [ "npm", "start" ]
```

The `build` and `start` scripts correspond to `next build` and `next start` respectively.

From my understanding, the environment variables should be included at runtime (from `next start`). So I even logged in to the specific container and wrote `echo $MY_ENV_VAR` and confirmed that it was the same variable that I set on the Docker Cloud GUI. The problem is, it is undefined when served to the client.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
The app served by `next start` to the client should include the environment variables that I set on Docker Cloud for that particular container.

## Current Behavior
The value of that variable in the browser seems to be `undefined`. Everything works in development, and I have also proved that the environment variable exists inside the container by typing `echo $MY_ENV_VAR` inside the specific container.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |      3.2.2   |
| node    |   8.4.0    |

**Comment by syncspot-dockercloud** [comment]
After doing some digging, it seems that Babel plugin [transform-inline-environment-variables](https://github.com/zeit/next.js/blob/master/examples/with-dotenv/.babelrc#L10) is not run at `next start`, but rather at `next build`.

The problem with this, is that my environment variables are not available until after the Dockerfile has already finished building. What is the proper way to deal with this?

**Comment by radeno** [comment]
All docker env are available through `process.env`
So if you set for example REDIS_URL=some_redis_url it is available in `process.env.REDIS_URL`

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/tree/canary/examples/with-universal-configuration Please see this example. We'll add another example showing how to do runtime configuration soon.
