### ISSUE TITLE
Typescript loader?

### ISSUE THREAD

**Issue by pyros2097** [zeit/next.js#304]
Any help on having typescript support. Right now I'm starting a new project and would like to start with it directly. I know custom webpack config is right now in the works but I'm thinking of forking the project for now and add the typescript loader to the webpack config and use the fork for now until it is officially supported. Is this the best approach or should I await for the async custom webpack config (shameless pun)?

**Comment by sebastianmacias** [comment]
+1

**Comment by nkzawa** [comment]
As you mentioned, you have to fork the repo for now. The custom webpack config support would be released in the near future.

**Comment by pyros2097** [comment]
Any pointers on the I forked it and added awesome-type-script loader. Then I got stuck.

I have a component in ts and its not getting resolved.
```
Module not found: Error: Cannot resolve 'file' or 'directory' ../components/header in /home/pyros2097/Code/cron/src/pages
 @ ./pages/index.js 11:14-45
> Ready on http://localhost:3000

```

Where should I add this to load .ts files?
and also when my index.js is index.ts it doesn't render that also? So again which code should I change?
