### ISSUE TITLE
Export performance 

### ISSUE THREAD

**Issue by aviramga** [zeit/next.js#3040]
Hi,

I know about the new export in nextjs to generate static pages.
How long does the build takes? Assuming I have hundreds of pages.
Is there some kind of benchmark?

Thanks!

**Comment by ldthorne** [comment]
@aviramga Nothing empirical, but our site (common.com), which has 51 pages at the moment, takes (on average) about 130 seconds to build/export static pages.

**Comment by timneutkens** [comment]
Cool site and concept @ldthorne 😲 👌

**Comment by aviramga** [comment]
Thanks!!

**Comment by ldthorne** [comment]
Thanks @timneutkens 😊! And no problem @aviramga
