### ISSUE TITLE
dynamic import still imposes a huge security risk

### ISSUE THREAD

**Issue by stevefan1999** [zeit/next.js#3042]
So I want to achieve client-server separation by using TC-39 import, it goes pretty well I guess yeah...Until I found a problem. 

Once the attacker can find the address to the webpack chunk, he can probably grab the dynamic chunk content by finding all possible __webpackChunkName in the page file, or worse, he could just switch pages and get all loaded dynamic chunk URL.

Since I'm not a proficient user in English, hopefully by inspecting all those screenshots carefully you could get a grip of what I really means.

(`./pages/dynamic.js`)
```js
import dynamic from 'next/dynamic'
let DynamicIndexComponent = dynamic(import('./index'))
export default () => <DynamicIndexComponent />
```

(`./pages/random_name.js`)
```js
export default let RandomName = ({ name }) => <div>{name}</div>

RandomName.getInitialProps = async ({ req }) => {
  if (req != null) {
    const { SecretClass } = await import('../server.secret');
    return { name: SecretClass.getName() };
  }
}
```

(`./server.secret.js`)
```js
import faker from 'faker'

export class SecretClass {
  static getName() {
    return faker.name.findName()
  }
}
```

![](https://i.imgur.com/lOAkOUj.png)
![](https://i.imgur.com/KiuY3vx.png)
![](https://i.imgur.com/mItAAqW.png)
![](https://i.imgur.com/lC5mZwy.png)

I don't know what to do to preventing malicious user viewing my internal business logic. Besides using the Node `global` hack, all of my codes can be scrapped. No, I don't want to use isomorphic-fetch or any other means because the extra HTTP overhead is really unbearable.

**Comment by stevefan1999** [comment]
Strange. I can delete all files in `./.next/chunks/` and get no problems. Maybe this issue is solved I don't know? I guess I have to clean up my browser cache to see what happens...

**Comment by stevefan1999** [comment]
I guess the reason for the leak is here:
https://github.com/zeit/next.js/blob/master/server/build/babel/plugins/handle-import.js#L17

and maybe here:
https://github.com/zeit/next.js/blob/master/server/build/babel/plugins/handle-import.js#L58

We need to remove the hash and stop appending chunk if the import function call is not wrapped with `next/dynamic`
```
import dynamic from 'next/dynamic'
```

**Comment by arunoda** [comment]
First thing first.

You should not do any business logic(or secret stuff) inside a Next.js app. Use a separate server for that. Or use REST routes.

This is designed in this way. So, this is not an issue.
