### ISSUE TITLE
Access previous props in getInitialProps

### ISSUE THREAD

**Issue by DavidSvetlik** [zeit/next.js#3043]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
It would be great if you could access "previousProps" when rendering page client-side. 

## Current Behavior
Currently getInitialProps passes "req" to function when the page is rendered server-side. In the req I'm receiving some site-specific data. Then, when navigation occurs (via router), getInitialProps is runned on client-side without req object and application has to make special ajax request just to download those site data again.

## Context
Obviously it feels very redundant to make this kind of request for some site data (I need to pass to graphql queries for instance) every-single-time when user navigates from one page to another. That's why it would be very useful to recall them when rendering page in browser. Or to store them someplace when rendering page first time on server (but I guess that's technologically not possible).

If there's already way to achieve that, I would appreciate link, but I wasn't been able to find a solution or related issues at all.

Thank you,
David

**Comment by timneutkens** [comment]
There is no way to have `req` available on the client side, but you could store `window. __NEXT_DATA__` in another variable on `componentDidMount` of your component.

**Comment by DavidSvetlik** [comment]
@timneutkens Okay, will check it out. Thanks.

**Comment by tomsoderlund** [comment]
@DavidSvetlik @timneutkens This works for me but I wonder if there’s another, better solution to retain access to properties on `req`?

	static async getInitialProps ({isServer, req}) {
		if (isServer) {
			const loggedInUser = _.get(req, 'session.passport.user.username');
			return { loggedInUser };
		}
		else {
			return window.__NEXT_DATA__.props.initialProps;
		}
	}

**Comment by tomsoderlund** [comment]
Since `query` on `getInitialProps` is available for both server and client rendering, I reckon this is a better approach than using `window.__NEXT_DATA__`. However this requires the developer to pass all required query parameters with `href`, e.g:

	<Link href={'/profile?userId' + this.props.userId} as='/myprofile'><a>My Profile</a></Link>
