### ISSUE TITLE
Using different babel version?

### ISSUE THREAD

**Issue by jjant** [zeit/next.js#3046]
I would like to use a different babel version than the currently supported by Next (in particular, Babel 7.0.0 beta).

Is this possible? I couldn't find it in the docs.

**Comment by pruhstal** [comment]
why not try and find out?

```
{
  "presets": [
    "stage-1",
    "stage-2",
    "stage-3",
    "react",
  ]
}
```

run with `yarn` as:

```
  "dev": "babel-node index.js --presets es2015,stage-1,stage-2,stage-3",
```

**Comment by jjant** [comment]
That's not what I want, Next uses Babel 6, and I want to use Babel 7, which supports `babel-plugin-syntax-optional-chaining` for example (and Babel 6 does not).

**Comment by pruhstal** [comment]
Add it to your package and your `.babelrc` file:

https://github.com/zeit/next.js/tree/master/examples/with-custom-babel-config

**Comment by jjant** [comment]
@pruhstal Again, you're not getting my point, this requires Babel 7, a different package than the one used by next..

**Comment by timneutkens** [comment]
@jjant Hey :wave: It's currently not possible since we require the babel version inside of Next's package.json

**Comment by timneutkens** [comment]
I'm going to close this for now

**Comment by Smolations** [comment]
> It's currently not possible

I feel like a bit more could have been said here. I have the same issue (wanting to use babel 7) and was disappointed to see the lack of information here. Does this mean that the version of babel to be used with next will _always_ be tied to next's `package.json`? Are there any plans for changing this behavior? Is the next.js team planning on upgrading to babel7 as soon as it leaves beta?

My team has a desire to use the new `React.Fragment` element in its shorthand (e.g `<></>`) and this is only possible with babel7 at the moment. There are other features of babel7 that will come in handy for us of course, that's just the most pressing example.

**Comment by timneutkens** [comment]
Yes the babel version is tied to next, just like the webpack version. Babel 7 is on the roadmap for next 6. There’s a few babel plug-ins we use that are not het compatible with babel 7. It’s also not released as stable.
