### ISSUE TITLE
CSS animation keyframes missing in production

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#3047]
When using `styled-jsx` in the latest beta, CSS animation keyframes are missing in production. I only noticed this happening today.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

A production build should include CSS animation keyframes.

## Current Behavior

CSS animation keyframes do not appear in the production build, causing a loss of all animations on the front end.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4.0.0-beta.3 |
| node    | v8.6.0 |

**Comment by timneutkens** [comment]
We Fixed this last night, Will do a new release soon 👍🏻

**Comment by jaydenseric** [comment]
@timneutkens thanks, super keen.

**Comment by timneutkens** [comment]
Release is out 👌
