### ISSUE TITLE
Top level component for cron and notifications

### ISSUE THREAD

**Issue by digitalmio** [zeit/next.js#3051]
What's the best place / way to run a cron job for heartbeat? I need to check if user session is still valid. I tried to keep it in Layout component, but I get many instances of cron.
Secondly, I would like to have growl type of notifications / messages, but when I change page they disappear.

Many thanks for all help.

**Comment by timneutkens** [comment]
Set a timeout in `componentDidMount` and clear it on `componentWillUnmount` then you won't have multiple instances 👍 

> Secondly, I would like to have growl type of notifications / messages, but when I change page they disappear.

I guess you can use React portals for this 👍
