### ISSUE TITLE
Question: Scss hot reload support V4

### ISSUE THREAD

**Issue by aviramga** [zeit/next.js#3057]
Hi Everyone,

I know this issue has been discussed a lot in this forum but I get understand what is the bottom line in any of the other posts.
I'm just trying to know what is the plan with this issue in the near future.

We are planning to migrate our systems (hopefully to nextjs) and we heavily relay on scoped scss.
Do you think the hot reload issue will be solved in V4?

If not what is the best alternative for scoped non inline css (we want a clear .js .css separation) that is supported with hot reload?

Thanks!

**Comment by mike3run** [comment]
create-react-app eject and tweak?

**Comment by mike3run** [comment]
there's also this:
https://github.com/zeit/next.js/tree/master/examples/with-external-scoped-css

**Comment by aviramga** [comment]
@mike3run thanks! I already played with with-external-scoped-css example. You can get SCSS support there but no hot reload on dev env which is a big issue for the dev experience.
Other SCSS solutions only allow global scoped styling which is also an issue.

create-react-app is an option but I was hoping to save the configuration overhead of webpack and bable that nextjs offers

**Comment by adisak1618** [comment]
Try to fix this problem also

**Comment by sheerun** [comment]
I've implemented external scss with hot-reloading here: https://github.com/zeit/next.js/pull/3451

**Comment by timneutkens** [comment]
Fixed with next-sass
