### ISSUE TITLE
Styled JSX shouldn't be built in NextJS

### ISSUE THREAD

**Issue by jjant** [zeit/next.js#3058]
Many of us don't use `styled-jsx` while we use Next, and given that it isn't really necessary to do any SS-rendered app, I think this goes against the "minimalist" mindset of Next's API.

Why not leave this as an opt-in for folks who use it? Just like PropTypes were extracted away from React's main package.

**Comment by timneutkens** [comment]
@jjant This has been brought up before, please see #2384.
