### ISSUE TITLE
Best way to add properties to window when developing?

### ISSUE THREAD

**Issue by jjant** [zeit/next.js#3064]
I like to keep things like my redux store, perf tools, apollo instance, etc. as properties of the `window` object when developing, to easily debug stuff.

I usually just did stuff like
```js
if (process.env.NODE_ENV === 'development') {
  window.store = store;
}
```

But with SSR, I'm finding this harder, as just checking for `process.browser` is not enough, because you have to put this piece of code somewhere you know will be executed by the browser (I can't just throw this somewhere in `_document.js`).

What's the best practice for this?

**Comment by sergiodxa** [comment]
You could check `typeof window !== 'undefined'`, that's `true` only in browsers. Then just create a file with your code and import it in every page you need it.

**Comment by jjant** [comment]
@sergiodxa I tried to explain why that isn't enough, but I think I was unclear: If I just do that, and I browse to that page (simply by typing the url in chrome), that code won't execute, I'll have to browse back and forth to that page so that this browser-only code executes, and even in this case, I'm finding only ugly ways to do it (like putting all those `window.x = x` in a `componentWillMount`).

**Comment by pruhstal** [comment]
You could use a HOC where you extend React.Component and not use the _document.js pattern.

**Comment by jjant** [comment]
One way to solve this could be having a special place to put code that will execute on both environments the first time the app loads, so inside that file we could just check for `process.browser` and be sure that our code will execute.

**Comment by timneutkens** [comment]
We already have a way to execute code both on server and in the browser, using `getInitialProps` and `componentDidMount`. `getInitialProps` will be called server side, and `componentDidMount` client side (when refreshing the page).
