### ISSUE TITLE
styled-jsx-postcss example broken after in next 4

### ISSUE THREAD

**Issue by tenosiswono** [zeit/next.js#3066]
example of styled-jsx-postcss broken after commit 559c25253ea4a50fbc04ef37f466d9e9b616512a

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
The custom babel-present.js in example can modify the `next/babel`

## Current Behavior
after commit, `next/babel` became a function and cannot be modified

## Steps to Reproduce (for bugs)
1. Use example in here next.js/examples/with-styled-jsx-postcss/
2. run dev

## Context
We use styled-jsx-postcss, but since we want to update to the latest of next, it got broken

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |    4.0.1     |
| node    |     v6.11.3    |

**Comment by pukapukan** [comment]
FYI. There is an styled-jsx update coming this week to address postcss issue for styled-jsx.

https://github.com/giuseppeg/styled-jsx-postcss/issues/24

**Comment by MFCo** [comment]
Hi, I left a PR with my solution to this issue.Although I'm waiting the styled-jsx update, this code can help you meanwhile.

```javascript
const nextBabelPreset = require('next/babel');

/*
  This code will load the 'styled-jsx-postcss/babel' package instead 
  of built-in 'styled-jsx/babel'
*/

let presetArray = nextBabelPreset();

presetArray.plugins = presetArray.plugins.map(plugin => {
  if (!Array.isArray(plugin) && plugin.indexOf('styled-jsx/babel') !== -1) {
    return require.resolve('styled-jsx-postcss/babel');
  }
  return plugin;
});

module.exports = presetArray;
```

When you switch to NextJS v4, './dist/server/build/babel/preset' now returns a function which result is the plugins + presets array. So you can use an auxiliar to call that function and then do the plugin replacement :)

Hope it can help you.

https://github.com/zeit/next.js/pull/3083

**Comment by younes200** [comment]
Also the example using postcss as plugin is not working :https://github.com/zeit/next.js/tree/master/examples/with-styled-jsx-plugins
@MFCo according to the example, it should work without replace 'styled-jsx/babel' I suppose.

**Comment by MFCo** [comment]
@younes200 yeah, that code that I left was working before 4.1.0, now you don't have to replace 'styled-jsx/babel'. I haven't tested 4.1.0 myself yet

**Comment by timneutkens** [comment]
Exactly, `styled-jsx-postcss` as npm module is deprecated now, since you can just use `styled-jsx-plugin-postcss` 👍
