### ISSUE TITLE
FaviconsWebpackPlugin won't generate icons, inject them into head

### ISSUE THREAD

**Issue by schoenwaldnils** [zeit/next.js#3068]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

### my config (tidied)
```js
// next.config.js
import HtmlWebpackPlugin from 'html-webpack-plugin';
import FaviconsWebpackPlugin from 'favicons-webpack-plugin';

module.exports = {
  webpack: (config, { dev }) => {
    config.plugins.push(
      new FaviconsWebpackPlugin({
        logo: './static/assets/images/favicon.png',
        inject: true,
      }),
      new HtmlWebpackPlugin(),
    );

    return config;
  },
};
```
```js
// pages/_document.js
import React from 'react';
import Document, { Head, Main, NextScript } from 'next/document';

export default class SmediaDocument extends Document {
  render() {
    return (
      <html lang="en">
        <Head>
          <meta charSet="utf-8" />
          <meta content="IE=edge" httpEquiv="X-UA-Compatible" />
          <meta content="width=device-width,initial-scale=1" name="viewport" />
          <title>Schoenwald.media</title>
          <meta name="description" content="Thoughts on CSS, JS, and overall clean code." />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

I'd expect that the favicons-webpack-plugin generates the icons, and the html-webpack-plugin inject it in the `<head/>` of the page. Which it doesn't.

## Steps to Reproduce
1. Checkout https://github.com/schoenwaldnils/blog
2. Set up `.env`file with 
```
HOST=localhost
PORT=3000
```
3. `docker-compose up`

## Environment
| Tech      | Version |
|---------|---------|
| next      | ~4.0.0-beta.4 |
| html-webpack-plugin | ~2.30.1 |
| favicons-webpack-plugin | 0.0.7 |
| node    | 8.4.0 |
| OS        | mhart/alpine-node:8.4.0 |

**Comment by MacKentoch** [comment]
Does it run `production`?
In dev (*npm run dev*) webpack won't run your plugins (see .next directory content).

My issue is to found out a way to make `sw-precache-webpack-plugin` working even in dev (only works in production).

**Comment by mtford90** [comment]
Hmmm I'm facing similar issues with next 5 despite universal webpack. Similar setup to above:

```js
	return Object.assign({}, nextConfig, {
		webpack(config, options) {
			config.plugins.push(
				new FaviconsWebpackPlugin({
					logo: './static/img/favicon.png',
					inject: true
				})
			)

			config.plugins.push(
				new HtmlWebpackPlugin()
			)
                }
        }
```
I see nothing injected when running in both prod & dev

Am I perhaps missing something important? @timneutkens :P

**Comment by timneutkens** [comment]
`new HtmlWebpackPlugin()` this does nothing in Next. Next uses React, not html, as a renderer.

The favicons will probably end up somewhere in the `.next` folder.
