### ISSUE TITLE
warning "styled-jsx@2.0.2" has incorrect peer dependency "react@15.x.x".

### ISSUE THREAD

**Issue by vinodronold** [zeit/next.js#3073]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
next@latest should add without incorrect peer dependency

## Current Behavior
````
>yarn add react@latest react-dom@latest next@latest
yarn add v1.2.0
info No lockfile found.
[1/4] Resolving packages...
warning next > glob-promise > semantic-release > npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
warning next > glob-promise > semantic-release > @semantic-release/condition-travis > travis-deploy-once > travis-ci > request > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "styled-jsx@2.0.2" has incorrect peer dependency "react@15.x.x".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 618 new dependencies.
````
````
>yarn check
yarn check v1.2.0
error "next#styled-jsx#react@15.x.x" doesn't satisfy found match of "react@16.0.0"
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
````
## Steps to Reproduce (for bugs)

1. yarn add react@latest react-dom@latest next@latest on Windows 7 laptop

2. Also try 
````
>yarn check
````
After adding.

## Context
I am currently developing an app with Next@3 and using React@15/Styled-JSX. I am now trying to install Next@4 and thought of using React@16/Styled-JSX@2. Not sure if this is an error with Yarn.
Apologize if this is a duplicate issue or a silly one.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |4.0.3|
| node    |8.1.2|
| OS      | Windows 7 |
| browser | N/A |
| etc     |N/A|

**Comment by jaydenseric** [comment]
See https://github.com/zeit/styled-jsx/issues/265 and https://github.com/zeit/styled-jsx/pull/284.

**Comment by vinodronold** [comment]
@jaydenseric thank.!
