### ISSUE TITLE
How do you know whether a page moves forward or backward?

### ISSUE THREAD

**Issue by czy0729** [zeit/next.js#3077]
How do you know whether a page moves forward or backward?
With React-router 3.X,  I can used location.action === 'PUSH'  or  'POP', but it does't seem in next.js :-D

**Comment by stevefan1999** [comment]
I believe a simple URL history will do.
Or you could opt-in for hash URL, so the detection is left for you to implement

https://github.com/Raynos/hash-router

**Comment by czy0729** [comment]
@stevefan1999  thank you for your answer, but I decide to calculate by myself, it not a hard work :-D
