### ISSUE TITLE
Mailto links without recipients fails

### ISSUE THREAD

**Issue by jonasknutsen** [zeit/next.js#3081]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

A mailto link should open the email client of the user, regardless if the recipient is present or not.

## Current Behavior

When the recipient is missing, isLocal in <Link> returns true. Leading to 'Cannot read property replace of null' further down the road.

## Steps to Reproduce (for bugs)

1. mailto:jonas@example.com?subject=Next.js%20rocks works as intended
2. mailto:?subject=Next.js%20rocks does not work
3.
4.

## Context

One of the ways our users can recommend an article to a friend, is to email a link. This is handled by providing a mailto link without recipient, but with information in the subject and body field. Then the users only need to fill in a recipient, and the mail will be sent from his own email client. 

This issue is of course avoidable by using a form, but the project owner is currently insisting on keeping this how it is today. So we were hoping this could be fixed.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.0.3     |
| node    |    6.11.3     |
| OS      |    macOS 10.13     |
| browser |    Safari, Chrome     |
| etc     |         |

**Comment by timneutkens** [comment]
I don't see how this relates to Next 🤔 If you're using `<Link href="mailto:test@email.com"><a>email</a></Link>` you should simply change it to `<a href="mailto:test@email.com">email</a>` since it's not a link to an internal page.
