### ISSUE TITLE
TypeScript + Custom Server + HMR = Unusable

### ISSUE THREAD

**Issue by sarriaroman** [zeit/next.js#3086]
If you try to develop a next.js app in an environment with TS + Custom Server + HMR the development is almost impossible. HMR must be able to be disabled because TS will recreate the entire code every time you save, HMR will try to load it but will just reload the entire page and is pretty heavy having it bundled. If you have a medium - large app will become a development hell.

Tested Version: Next.JS 4.0.3
TypeScript: 2.5.3
NodeJS: 8.7.0

**Comment by timneutkens** [comment]
The only real solution for this is https://github.com/zeit/next.js/issues/1245.
