### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by sincu** [zeit/next.js#309]
I was following your instructions (which are kinda not clear), but app doesn't start after `npm run dev` 

`jd@jd-XPS:~/next/next.js$ npm run dev

> next@1.1.2 dev /home/jd/next/next.js
> next

sh: 1: next: not found

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! next@1.1.2 dev: `next`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the next@1.1.2 dev script 'next'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the next package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     next
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs next
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls next
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jd/next/next.js/npm-debug.log
`

My actions:
1. Cloned the repo && cd
2. Run `npm install next --save`
3. Add in package.json "dev": "next"
4. Created file `./pages/index.js` with mentioned in manual content
5. Then I run `npm run dev`

**Comment by jonaswindey** [comment]
Do you have `next`in your folder `node-modules`?

Which version of node and npm are you running?

**Comment by nkzawa** [comment]
> Cloned the repo && cd

Do you mean you cloned the `zeit/next.js` repo ? If so, follow the instruction with an empty dir.

**Comment by sincu** [comment]
Ok, now it work, thank you (still, I don't know why I couldn't did it first time, it was saying "Can't install dependency as itself" or kind of)

**Comment by parkerproject** [comment]
I'm having the same issue with Node v7.8.0 and npm v4
