### ISSUE TITLE
`next export` won't generate index.js for dynamic routes

### ISSUE THREAD

**Issue by schoenwaldnils** [zeit/next.js#3091]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

As stated in the title, for dynamic pages defined in the `exportPathMap` there are no generated `index.js` files. This brakes the next-router.
For example `http://blog.schoenwald.media/_next/a7725bcd-89fa-4f04-950c-54d296a9e9d9/page/tag/css/index.js`

As you can see here: 
- https://issue-3091.schoenwald-media.de
- https://github.com/schoenwaldnils/blog/tree/issue-3091
- [next.config.js](https://github.com/schoenwaldnils/blog/blob/issue-3091/next.config.js)
- [Travis build (see line 4069 and following)](https://travis-ci.org/schoenwaldnils/blog/builds/287982634)
- the generated files on gh-pages: https://github.com/schoenwaldnils/blog/tree/gh-pages

the generated pathMap:
```json
{
  "/": {
    "page": "/",
    "query": {
      "posts": [{
        "id": "6uzkBYXsME0CiSwMI8isSY",
        "url": "/sticky-footer-with-flexbox"
      }, {
        "id": "4iJ3AOLOmIqykMw4qAKw4Y",
        "url": "/hello-world"
      }]
    }
  },
  "/imprint": {
    "page": "/page",
    "query": {
      "id": "5Wa2mgh3zOuku4GqOQEuAG"
    }
  },
  "/about": {
    "page": "/page",
    "query": {
      "id": "yBv8udv1XqwkEMmew0Wwi"
    }
  },
  "/sticky-footer-with-flexbox": {
    "page": "/page",
    "query": {
      "id": "6uzkBYXsME0CiSwMI8isSY"
    }
  },
  "/hello-world": {
    "page": "/page",
    "query": {
      "id": "4iJ3AOLOmIqykMw4qAKw4Y"
    }
  },
  "/tag/css": {
    "page": "/tag",
    "query": {
      "tag": "css",
      "tags": ["css", "flexbox", "footer", "Hello", "world"],
      "posts": [{
        "id": "6uzkBYXsME0CiSwMI8isSY",
        "url": "/sticky-footer-with-flexbox"
      }]
    }
  },
  "/tag/Hello": {
    "page": "/tag",
    "query": {
      "tag": "Hello",
      "tags": ["css", "flexbox", "footer", "Hello", "world"],
      "posts": [{
        "id": "4iJ3AOLOmIqykMw4qAKw4Y",
        "url": "/hello-world"
      }]
    }
  },
  "/tag/world": {
    "page": "/tag",
    "query": {
      "tag": "world",
      "tags": ["css", "flexbox", "footer", "Hello", "world"],
      "posts": [{
        "id": "4iJ3AOLOmIqykMw4qAKw4Y",
        "url": "/hello-world"
      }]
    }
  },
  "/tag/footer": {
    "page": "/tag",
    "query": {
      "tag": "footer",
      "tags": ["css", "flexbox", "footer", "Hello", "world"],
      "posts": [{
        "id": "6uzkBYXsME0CiSwMI8isSY",
        "url": "/sticky-footer-with-flexbox"
      }]
    }
  },
  "/tag/flexbox": {
    "page": "/tag",
    "query": {
      "tag": "flexbox",
      "tags": ["css", "flexbox", "footer", "Hello", "world"],
      "posts": [{
        "id": "6uzkBYXsME0CiSwMI8isSY",
        "url": "/sticky-footer-with-flexbox"
      }]
    }
  }
}
```

| Tech    | Version |
|---------|---------|
| next    |  ~4.0.3 |
| node    | 8.4.0 |

**Comment by jacobpdq** [comment]
Bump – I'll need this in the next 10 days or I'm toast :(

**Comment by jacobpdq** [comment]
Any help on this one?

**Comment by jacobpdq** [comment]
Hey @schoenwaldnils, I've gotten around this issue by mapping links to a dictionary – if there's a corresponding page, it looks it up in the index (via url).

Although, maybe this is a different issue (your 404 is showing [..._next...]/page/tag/**footer**/index.js

**Comment by timneutkens** [comment]
I think this has been fixed since then 🤔

**Comment by schoenwaldnils** [comment]
This issue has kind of changed but is still there.

| Tech    | Version |
|---------|---------|
| next    |  7.0.2 |
| node    | 10.9.0 |

The tags are still generated like seen above.
But I think I didn't described the issue well last time.

The problem is that the routing using next/link is missing files when working with pages generated using the `exportPathMap`

For example I have this on my tag overview page:
```
import Link from 'next/link';
...
<Link href={`/tag/${tag}`}>
  <a>{tag}</a>
</Link>
```

The page: https://bug-3091-missing-index-js.schoenwald.media/tag/

When clicking on the tags the routing doesn't work. (for example `css`)
Instead I get a 404 like this:
```
GET https://bug-3091-missing-index-js.schoenwald.media/_next/static/kptFDJZh3nwjex~F9qD2R/pages/tag/css.js net::ERR_ABORTED 404
```
And then the page loads with the default click on `a` behaviour.

My files:
- [next.config.js](https://github.com/schoenwaldnils/blog/blob/bug/3091-missing-index-js/next.config.js)
- [the Filter.js using Link](https://github.com/schoenwaldnils/blog/blob/bug/3091-missing-index-js/source/components/Filter/Filter.js)

**Comment by timneutkens** [comment]
@schoenwaldnils sounds like a misunderstanding in how routing works, this comment should help clarify: https://github.com/zeit/next.js/issues/2833#issuecomment-414919347
