### ISSUE TITLE
Bind ONLY to 127.0.0.1

### ISSUE THREAD

**Issue by mtrabelsi** [zeit/next.js#3094]
Security should be addressed here, we should provide a way to provide binding arguments:

In my case I want to bind only to 127.0.0.1 and not exposing my app to public ( only nginx is exposed ).
Ofcourse we can use the firewall to prevent direct access to my app - but Nex.js should provide a basic mechanism to bind to a specific address.

**Comment by timneutkens** [comment]
@mtrabelsi `now dev --help` `now start --help`. We provide a `--host` option to set the binding host. I believe that's what you're looking for?

**Comment by mtrabelsi** [comment]
I think you're talking about **now** which is not my case :- ) I'm putting a issue on **next.js** repo

**Comment by mtrabelsi** [comment]
Well, that's sad : https://learnnextjs.com/basics/deploying-a-nextjs-app

Looks like it's not yet decided how we deploy next apps.

**Comment by timneutkens** [comment]
@mtrabelsi whoops it was still early, I'm talking about `next`.

**Comment by timneutkens** [comment]
```
next dev --help

    Description
      Starts the application in development mode (hot-code reloading, error
      reporting, etc)

    Usage
      $ next dev <dir> -p <port number>

    <dir> represents where the compiled folder should go.
    If no directory is provided, the folder will be created in the current directory.
    You can set a custom folder in config https://github.com/zeit/next.js#custom-configuration.

    Options
      --port, -p      A port number on which to start the application
      --hostname, -H  Hostname on which to start the application
      --help, -h      Displays this message```
