### ISSUE TITLE
Feature request. Service-worker option in Static Export

### ISSUE THREAD

**Issue by bestwestern** [zeit/next.js#3096]
I love the static export, but would love an 'include service worker option here:
![image](https://user-images.githubusercontent.com/3617433/31583346-37f32fac-b19a-11e7-9017-a296bb5b604b.png)
that is
`{page:'..',sw:true }` 
which would add a service worker to that route, which would make that route offline available (with sw-precache) 
The same as Preact-Cli and create-react-app

**Comment by sergiodxa** [comment]
You could do that yourself. I did it for [my personal site](https://github.com/sergiodxa/personal-site) which is a Next.js exported site.

## Steps
1. Create a SW as described in the example [with-sw-precache](https://github.com/zeit/next.js/tree/master/examples/with-sw-precache)
2. Add a `postexport` script in your `package.json` to copy the SW from `.next` to your exported dir (eg. `cp .next/service-worker.js out`).
3. Load the SW and register it as described in the example above.
4. Deploy your app (eg. `now out`).
4. That's all, the SW will precache all your pages based on the current build and you can configure it in the `next.config.js`

**Comment by timneutkens** [comment]
Thanks Sergio 🙌

**Comment by bestwestern** [comment]
@timneutkens  , @sergiodxa Thank you very much - I will try it.
I just think it should be part of next.js set of features - perhaps even enabled by default (as preact-cli and create-react-app has)

Doing it the way you described will not minify - from the service-worker.js created:
`// This file should be overwritten as part of your build process.`

Doing it the way you described will cache the entire site - I think a better option would be to just cache each route (or give the user the option)
