### ISSUE TITLE
Examples not working. latest next requires react 16

### ISSUE THREAD

**Issue by bestwestern** [zeit/next.js#3107]
Many (all?) examples has this 
![image](https://user-images.githubusercontent.com/3617433/31601659-e22b7a04-b25a-11e7-9961-34ba6ea7ef82.png)

But the latest next requires React 16 so at build time this is shown:
![image](https://user-images.githubusercontent.com/3617433/31601718-17089982-b25b-11e7-8c38-ba1af1ca6e1e.png)

**Comment by timneutkens** [comment]
Yeah we need to update them, will do that tonight 👍
