### ISSUE TITLE
FOUC: Warning: Text content did not match. Server: "...css..."

### ISSUE THREAD

**Issue by lancejpollard** [zeit/next.js#3108]
Getting large error (printing all of CSS used in `<style jsx global>`) in web console.

```
Warning: Text content did not match. Server: "
...(css)...
```

I _think_ this is causing FOUC, so there is a flash of unstyled content followed by a second later the actual styles.

This is coming from a library being used in a next project (from https://github.com/zeit/next.js/issues/3088).

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

- Styles should be applied from server directly.
- There should be no FOUC
- There should be no error in web console

## Current Behavior

To elaborate a little more, when rendering a next app in the library itself (so some page in that repo), the styles render fine. View-source shows source maps and minified CSS in the HTML markup.

However, when using that same code as a compiled project loaded into a separate next app, the markup in view-source shows unminified CSS and no source maps (and we get the web console error and fouc).

## Steps to Reproduce (for bugs)

1. See https://github.com/zeit/next.js/issues/3088 for setup.
2. I am manually compiling some files in repo-b using `babel <folder> --out-dir ... etc.`, and then importing that and also importing `babel-polyfill` if that matters.

## Context

This is just unexpected behavior making the app not look right (ux).

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4beta2  |
| node    | 8.4 |

**Comment by lancejpollard** [comment]
Hmm what could be happening as a rough guess is because it's being precompiled with babel and babel-polyfill is being used, its not getting passed through the styled-jsx when its being rendered on the server for some reason. Not sure.

**Comment by e10jc** [comment]
I'm getting this as well. I believe it has to do with the CSS being encoded when rendered. Here's the full warning message I receive:

```
warning.js?dce5fb5:33 Warning: Text content did not match. Server: "
      html, body, body &gt; div, #__next, #__next &gt; div { height: 100% }
      main {
        margin-bottom: -100px;
        min-height: 100%;
      }
      main:after {
        content: &quot;&quot;;
        display: block;
        height: 100px;
      }
      footer {
        height: 100px;
      }
    " Client: "
      html, body, body > div, #__next, #__next > div { height: 100% }
      main {
        margin-bottom: -100px;
        min-height: 100%;
      }
      main:after {
        content: "";
        display: block;
        height: 100px;
      }
      footer {
        height: 100px;
      }
    "
```

**Comment by lancejpollard** [comment]
Also getting stuff like this, which seems related:

```
Warning: Received `true` for non-boolean attribute `jsx`. If this is expected, cast the value to a string.
    in style
    in div
    in Layout (at index.js?entry:13)
    in HomePage
    in AppContainer
    in Container
    in div
    in App
```

If it has `<style jsx>`, not sure why this message would be occurring.

**Comment by lancejpollard** [comment]
I tried reproducing it but in the simple case it seems fine.

**Comment by lancejpollard** [comment]
@e10jc nice I see what you mean. It looks like its the encoding of those quotes and probably other stuff. Simple case:

```
Text content did not match. Server: "
body {
  background: red
}

body:before {
  content: &#x27;&#x27;;
}
  " Client: "
body {
  background: red
}

body:before {
  content: '';
}
```

**Comment by lancejpollard** [comment]
Looking at the HTML elements debugger in Chrome, there is a ~1s delay to add the title tags (_and anything following that in the head perhaps?_):

```
<head><link rel="preload" href="/_next/1508208268137/page/" as="script"><link rel="preload" href="/_next/1508208268137/page/_error/index.js" as="script"><link rel="preload" href="/_next/1508208268137/manifest.js" as="script"><link rel="preload" href="/_next/1508208268137/commons.js" as="script"><link rel="preload" href="/_next/1508208268137/main.js" as="script"><meta charset="utf-8" class="next-head"><title>Home page</title></head>
```

The title appears a few frames afterward. Maybe its associated with that.

**Comment by lancejpollard** [comment]
YAY It is the encoding! Here is an example to see it:

```
body {
  font-family: "Helvetica Neue";
}
```

The quotes get mangled and so it will be Times New Roman or whatever before the client-side styles are applied.

**Comment by lancejpollard** [comment]
But, it looks like it only happens with an external repo? Not sure.

**Comment by lancejpollard** [comment]
This repo demonstrates the bug: https://github.com/lancejpollard/next-2-repos

**Comment by giuseppeg** [comment]
@lancejpollard first thing I noticed is that `transform-react-jsx` is transforming JSX to `React.createElement` calls and therefore styled-jsx is not capable of transpiling your library and app code (since it only understands JSX). Try to pass that after styled-jsx is done doing its work. Also beware that Babel merges visitors and often this optimization results in nasty bugs that are hard to debug/figure out - typically some plugins visitors end up never executing because swallowed or overridden by other plugins' ones.

Also make sure that you always use the latest version of styled-jsx - in 2 beta there was a bug which caused fouc indeed. Though it seems that in your app it resolves to 2.1.1 nonetheless.

That said, in case you still see FOUC let me know and I will try to take a look - any help is appreciated ofc, you are all pretty smart folks so I believe that you can debug as I would do too :) 

Check with the Next.js folks and see whether Next (OR your custom server) encodes SSR code also.

**Comment by giuseppeg** [comment]
By the way you might need to export `styled-jsx/server`'s `flushToHTML` in your library so that the consumer app can render your styles on the server

**Comment by lancejpollard** [comment]
Thanks for the help. One thing is I can't seem to leave the raw JSX in a separate module, get this error: https://github.com/zeit/next.js/issues/3088. So catch 22 sort of.

**Comment by giuseppeg** [comment]
@lancejpollard I guess because Next doesn't transpile `node_modules`. I believe that if your invert the plugins order in your example repo it might work: `--plugins=styled-jsx/babel,transform-react-jsx`

**Comment by lancejpollard** [comment]
Yeah, maybe some way could be added to handle that. Changing the order didn't work.

**Comment by lancejpollard** [comment]
@arunoda maybe we can have this be configurable somehow (excluding node_modules):

https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L196-L288

**Comment by giuseppeg** [comment]
> without transpiling

oh yea I meant, if you run `yarn build` in repo-b and use the built version.

**Comment by lancejpollard** [comment]
I tried tinkering with the webpack.js file but to no avail. Maybe someone could point me to where this sort of feature (loading external modules as jsx) could be implemented (what changes would need to be made).

**Comment by giuseppeg** [comment]
@lancejpollard yeah I am afraid that Next won't transpile `node_modules`. Maybe you can hack something together using `babel-require` but these are all ideas/assumptions. Probably #3088 or the slack channel is the best place to discuss about this with someone like @arunoda, @rauchg or @nkzawa who definitely have more knowledge of the internals of Next.js

**Comment by edmondnyaigoti** [comment]
had the same issue, for **my case** the error originated from  trying to load image -> 
<style>{`
                  .subject{
                        background-image: url('../static/images/file-1.svg');
                    }
`}</style>

**Comment by timneutkens** [comment]
We're going to implement transpiling node_modules in a future release. Till then you can use something like this example: https://github.com/zeit/next.js/pull/3732

**Comment by tanguyandreani** [comment]
Still happening.

With the basic template provided by the tutorial and the following controller:
```
import React from 'react'
export default () => (
  <div>
    <script>{`

var Input = React.createClass({
  getInitialState: function() {
    return {typed: ''};
  },
  onBlur: function(event) {
    this.setState({typed: event.target.value});
  },
  render: function() {
    return <div>
        <input type="text" onBlur={this.onBlur.bind(this)}/>
        You typed: <code>{this.state.typed}</code>
      </div>
  }
});
React.render(<Input/>, document.querySelector('div'));

    `}</script>
  </div>
)
```

**Comment by Weipengzhou** [comment]
I want to know what method you used to solve last.

**Comment by tanguyandreani** [comment]
@Weipengzhou if by last you mean mine then I didn’t workout a solution yet. If I do I will post updates here.

**Comment by mtrelis** [comment]
```
.side-pannel > * {
        padding:0.3em 0;
    }
```
becomes
```
.side-pannel &gt; *{
        padding:0.3em 0;
    }
```
gives a warning but still applies the padding ( next 7.0.2 )

**Comment by mattdamon108** [comment]
I have the same issue still. I import the css style in string from external *.js file. It give me a warning.

```
Server: "#layout {
  display: grid;
  grid-template-columns: minmax(200px, 1fr) 2fr;
  grid-template-areas: &quot;header header&quot; &quot;category content&quot; &quot;footer footer&quot;;
}"

Client: "#layout {
  display: grid;
  grid-template-columns: minmax(200px, 1fr) 2fr;
  grid-template-areas: "header header" "category content" "footer footer";
}"
```

I'm using next 7.0.2 now. But I didn't encounter this issue when I using next 6

**Comment by jeanlescure** [comment]
I have the same issue

```css
body > div {
  /* ... */
}
```

becomes

```css
body &gt; div {
  /* ... */
}
```

Even though the style was being applied properly, the warning was disruptive enough (I use the console extensively in my day-to-day development) for me to try the following:

```jsx
// Originally I was applying my theme like this from a HOC that wraps "themeable" components
<style
  jsx="true"
  global="true"
>
  {`${theme.shades[shade][componentName]}`}
</style>

// Replaced with this awful thing
<style
  jsx="true"
  global="true"
  dangerouslySetInnerHTML={{__html: theme.shades[shade][componentName]}}
/>
```

This got rid of the warning but now the "de-dupe" functionality is broken and I get as many style definitions for each component as the number of said component's instances, which just kills performance at the scale of apps I'm working with.

![](https://media.giphy.com/media/zPOErRpLtHWbm/giphy.gif)
