### ISSUE TITLE
React Hot Loader: this component is not accepted by Hot Loader. 

### ISSUE THREAD

**Issue by hnq90** [zeit/next.js#3109]
After upgrading to 4.1.0 from 4.0.2, I got this warning in my browser's console. It didn't occur on 4.0.2.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
- No warning message.

## Current Behavior
```
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top-level class, a function or a variable. 
Click below to reveal the source location: 
 ƒ (props, context, updater) {
      // This constructor gets overridden by mocks. The argument is used
      // by mocks to assert on what gets mounted.

      if (true) {
        warning(
          th…
```

## Steps to Reproduce (for bugs)
1. Install Next 4.1.0
2. Run dev server.
3. Warning messages in the browser's console.

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |   4.1.0      |
| node    |     8.6.0    |
| OS      |     Ubuntu    |
| browser |    Chrome 60     |

**Comment by oliviertassinari** [comment]
It can easily fixed with this new option: https://github.com/gaearon/react-hot-loader/issues/667

**Comment by hnq90** [comment]
I think we should revert `react-hot-loader` to 3.0.0 beta7.
