### ISSUE TITLE
Dynamic imported component's ref becomes a DynamicComponent instance, how do I retrieve the refs from that?

### ISSUE THREAD

**Issue by pencilcheck** [zeit/next.js#3115]
- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by kelleg1** [comment]
@pencilcheck Did you resolve this?

**Comment by pencilcheck** [comment]
I am not using in any of my projects, so technically no.
