### ISSUE TITLE
Doing next export just for the changed files

### ISSUE THREAD

**Issue by aviramga** [zeit/next.js#3116]
Hi,

Is it possible to build on the changed files? 
We are building a new project with nextjs that has both static and ssr pages. The static part will include hundreds of pages with assets and we are afraid that every build and deploy will take a very long time (we have this issue in our existing project with middleman)

Thanks for your help!

**Comment by timneutkens** [comment]
Currently, there is no way to determine if a page has changed or not. It's also very hard to determine if a page changed since we just ask for a static route mapping of all URLs.
