### ISSUE TITLE
adding couple of pages to service worker and not all of them

### ISSUE THREAD

**Issue by iamsoorena** [zeit/next.js#3117]
I learned how [sw-precache](https://github.com/goldhand/sw-precache-webpack-plugin) works and also I found [with-sw-precache ](https://github.com/zeit/next.js/tree/master/examples/with-sw-precache) example by @chrisdwheatley which adds almost anything to service worker.
like this:
```javascript
webpack: (config) => {
    config.plugins.push(
      new SWPrecacheWebpackPlugin({
        verbose: true,
        staticFileGlobsIgnorePatterns: [/\.next\//],
        runtimeCaching: [
          {
            handler: 'networkFirst',
            urlPattern: /^https?.*/
          }
        ]
      })
    )
````
but I need to be able to have control over service worker to add some of js files and not all of them which currently I don't know how.
I will be grateful If someone tells me how's that possible.
_______________________________________________________________________
take a look at what I think might work:
```javascript
    config.plugins.push(
      new SWPrecacheWebpackPlugin(
        {
          minify: true,
          navigateFallback: '/',
          staticFileGlobs: [
            ".next/bundles/pages/page1.js",
            ".next/bundles/pages/page2.js",
            ".next/app.js",
          ],
        }
      )
    )
```

**Comment by timneutkens** [comment]
I'm going to close this issue as it's over 6 months old. Feel free to post it on https://spectrum.chat/next-js if you still have this question.
