### ISSUE TITLE
Unicode characters not rendering correctly on server?

### ISSUE THREAD

**Issue by coffenbacher** [zeit/next.js#312]
If I paste something like "●" in a component, it renders properly in the client when it's HMR'd in, but if I reload the server pushes it out as (â—).

I hesitate to post here because this smells like it could just be some problem in my environment, but if anyone could just paste a character in and see if you repro that would help. 

```
"next": "^1.1.1",
```
```
node --version
v7.2.0
```

**Comment by nkzawa** [comment]
Hmm, I can't reproduce it.

**Comment by sorahn** [comment]
Also can't reproduce.

I just have a single index.js file.

```
import React from 'react'
export default () => <div>•¢£™¡</div>
```

**Comment by coffenbacher** [comment]
Thx, I will try to figure out what's wrong with my environment.

**Comment by dbkaplun** [comment]
Adding `<Head>` to `pages/_document.js` fixed this issue for me
