### ISSUE TITLE
use typescript and styled-jsx-plugin-postcss error.

### ISSUE THREAD

**Issue by tungh** [zeit/next.js#3124]
Using styled-jsx-plugin-postcss error in typescript

```
warning.js?f60f4f0:33 Warning: Received `true` for non-boolean attribute `jsx`. If this is expected, cast the value to a string.
    in style (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by Container)
    in AppContainer (created by Container)
    in Container (created by App)
    in div (created by App)
    in App

```
## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   latest      |
| node    |    8.4     |
| OS      |     mac    |
| browser |    chome     |
| etc     |         |

**Comment by lukemorton** [comment]
Related to https://github.com/zeit/next.js/issues/2209

**Comment by jeffscottward** [comment]
How is this actually solved without depending on Universal Webpack ^^
Have this issue on our own build setup.
