### ISSUE TITLE
How can I use redux-form with next.js

### ISSUE THREAD

**Issue by hazelnutce** [zeit/next.js#3125]
I'm a beginner react developer. I need some suggestion or example to use redux-form with next.js. because I didn't understand withRedux example
-you can also give some link that make me understand about React - Redux more. pls help meeee

**Comment by rockchalkwushock** [comment]
@hazelnutce 

Join the [Slack community](https://zeit.co/chat) if you have not and ping me (same screen name as here on Github). I will be more than happy to help you out. 😄

**Comment by rockchalkwushock** [comment]
@hazelnutce 

[Live very ugly demo](https://mashaeltsovaphotography.com/one) if you change your default locale to Russian you will see the language change.

[Pertinent Files](https://gist.github.com/rockchalkwushock/ad9219314fb18ab736fc9b7e3c694c7a), sorry repo is private at the moment. FYI `/one` route will be gone by end of the day.

**Comment by hazelnutce** [comment]
Nice example. I've already solved my problem 👍
