### ISSUE TITLE
Issue with Fetch as Google? Robots?

### ISSUE THREAD

**Issue by mattjstar** [zeit/next.js#3126]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Current Behavior

I'm struggling to figure out how to duplicate this locally, but I was using `3.0.0-beta9` and upgraded to `4.1` (including upgrading to react 16) and now I get this when I use fetch as google or google's page speed test. I narrowed it down to happening sometime between the 3.0 beta and upgrading to next `3.2.1`
![screen shot 2017-10-18 at 3 01 43 pm](https://user-images.githubusercontent.com/4423173/31737414-6a55bb36-b415-11e7-902e-6e48994f485c.png)

I'm worried that it's causing SEO issues. Has anyone else run into this issue?

## Steps to Reproduce (for bugs)

1. Deploy a next site to Netlify at > `3.2.1` 
2. Test that site on Google Page Speed [insights tool](https://developers.google.com/speed/pagespeed/insights/)

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 3.2.1 || 4.1     |
| node    |    8.4.0   |
| OS      |     10.12.6    |
| browser |    chrome     |
| etc     |         |

**Comment by mattjstar** [comment]
FYI, I was able to confirm it's still an issue in `3.0.2`

**Comment by mattjstar** [comment]
Hmm, this could be related https://github.com/styled-components/styled-components/issues/1033

**Comment by mattjstar** [comment]
Ignore! There was an issue with how we were loading postcss in our specific app. Apologies for making it an issue. Carry on with the good work!

**Comment by timneutkens** [comment]
❤️ No worries!

**Comment by mattjstar** [comment]
hmm, this actually might still be an issue. 

When I use custom `_document.js` and remove `<NextScript/>` it loads properly in fetch as google. Unfortunately, that defeats the purpose of using Next as none of the JS loads. I'm gonna keep digging into the [NextScript]([url](https://github.com/zeit/next.js/blob/f1f83507dbf655ceb67a07b41a2765e00499add3/server/document.js#L119)) component to see if I can find anything.

**Comment by iamsoorena** [comment]
I think the problem relies on using strip-ansi package in next js. since strip-ansi uses arrow functions and google uses chrome 41 for crawling websites which doesn't support arrow functions and results in errors.
check [this](https://github.com/zeit/next.js/issues/2747).

**Comment by mattjstar** [comment]
Ah thanks for connecting me to that issue @iamsoorena I'll close this in favor of https://github.com/zeit/next.js/issues/2747

**Comment by i8ramin** [comment]
What I had to do to finally make it all work:
https://github.com/zeit/next.js/issues/3205#issuecomment-350612939
