### ISSUE TITLE
Custom dir on custom server doesn't load .babelrc presets or plugins

### ISSUE THREAD

**Issue by zapaiaavantrip** [zeit/next.js#3127]
```
const app = next({
  dev,
  dir:'./src'
})
```

- [ x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
It should load all the plugins in my .babelrc. It seems like it doesn't load my .babelrc and doesn't load the presets/

## Current Behavior
`
You may need an appropriate loader to handle this file type.
|   layout
| }) => (
|   <div>
|     <Container>
|       <TextContainer>
`

## Steps to Reproduce (for bugs)

1. Create a custom server and a custom .babelrc
2. Config a custom dir like:

```
const app = next({
  dev,
  dir:'./src'
})
```

3. run server

**Comment by liweinan0423** [comment]
where did you put your `.babelrc`? 

I read through the source code and it seems you have to put your `.babelrc` under `src` folder

Please refer to https://github.com/zeit/next.js/blob/master/server/build/babel/find-config.js
