### ISSUE TITLE
Difference between next start and next export

### ISSUE THREAD

**Issue by divyenduz** [zeit/next.js#3132]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Next.js export and Next.js should result in an eventually consistent state when dealing with network request (with requests originating from server, client or both).

If it is an `next export` deployment then I need to refresh the content on top of the snapshot content but with `now` deployment, if SSR works, client refresh is not required. 

## Current Behavior

A deployment with now works flawlessly with SSR - https://self.now.sh

A deployment with `next export` shows the snapshot of when the export happened but does not refresh the data on client site - https://self.netlify.com

Both the above are deployments of same commit id but backend has an extra entry (resume) after the deployments. Now deployment shows it but Netlify depoyment does not. 

## Steps to Reproduce (for bugs)

1. Links provided above

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.1.0     |
| node    |    8.4.0     |
| OS      |     macOS Sierra - 10.12.6    |
| browser |       Version 61.0.3163.100 (Official Build) (64-bit) |

**Comment by divyenduz** [comment]
Related example - https://github.com/zeit/next.js/tree/master/examples/data-fetch

**Comment by timneutkens** [comment]
> A deployment with next export shows the snapshot of when the export happened but does not refresh the data on client site

This is expected, one way you could handle this is in `componentDidMount` you fetch the new content.
