### ISSUE TITLE
Production build not minified

### ISSUE THREAD

**Issue by tweeres04** [zeit/next.js#3134]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
When I'm deploying a production build, I should have minified javascript code in order to minimize file size and maximize performance.

## Current Behavior
My app.js is 529KB and not minified

## Steps to Reproduce (for bugs)

1. `next build`
2. `next start`

OR

1. `next build`
2. `next export`

## Context
I wanted to use next.js in order to have a lightning fast site as advertised but no minification kills that. I'm sure I'm missing something simple.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  4.1.1       |
| node    |   8.4.0      |
| OS      |   MacOS Sierra 10.12.6       |
| browser |   Chrome      |
| etc     |    React and react-dom 16     |

**Comment by liweinan0423** [comment]
Can you confirm your NODE_ENV is set to `production`? I guess you may have a global environment variable NODE_ENV set and `next` scripts would honor the user defined ENV if there is one

**Comment by mcansh** [comment]
i thinks he's referring to 
```
VM40:21 Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build
```

**Comment by tweeres04** [comment]
@liweinan0423 Yes, confirmed that NODE_ENV is `production`.

@mcansh Yes, I'm getting that!

**Comment by mcansh** [comment]
Looks like a 4.1.1 issue as it’s not happening in 4.1.0

**Comment by timneutkens** [comment]
Did a new release (2.4.2) can you try updating?

**Comment by mcansh** [comment]
seems good 👍

**Comment by timneutkens** [comment]
Thanks for verifying @mcansh 👌

**Comment by tweeres04** [comment]
Looks good! Thanks for your quick response @timneutkens!

**Comment by zhaihaoran** [comment]
it`s still a issue for me  next@4.2.1,the same question happened on the Production enviroment, need help

**Comment by ilionic** [comment]
Confirm, getting the same on `4.2.1`

**Comment by rgbkrk** [comment]
Yep, this is worth reopening. I believe [React changed their strategy with 16.2.0](https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html).

**Comment by timneutkens** [comment]
@rgbkrk @ilionic will be fixed when a new version of canary is released. Also will be fixed once and for all when universal webpack lands (currently working on this).

**Comment by devmetal** [comment]
Getting same on 4.2.3

The error is:
```
React is running in production mode, but dead code elimination has not been applied.
```

**Comment by ilionic** [comment]
@devmetal should be gone in latest canary version. Although I am app.js size is twice as large compared to next.js 3 Investigating..

**Comment by devmetal** [comment]
@ilionic Thank you for quick answer :) Its working! You made my day! :1st_place_medal:

**Comment by dazjavier** [comment]
I'm getting this in 4.2.3 using a custom server and routing. Trying to update to the canary version now to test.

**Comment by devmetal** [comment]
@dazjavier I use it for production with custom server and routing, everything is working fine. No bad experience. Maybe a little bit slower in development mode, but its not big issue, and my stack also a little bit heavy, firebase, apollo, etc so maybe that cause this. Anyway, in production is working as expected :)

**Comment by dazjavier** [comment]
@devmetal Thanks  for the information. I've using it for 3 days now, and everything works great. No big performance issues for now.
Thank you.

**Comment by cernadasjuan** [comment]
I am using the 5.0.0 version, and I am getting this error again

**Comment by davecarlson** [comment]
@timneutkens can this be reopened ?

**Comment by timneutkens** [comment]
It's extremely hard to get this message with v5. The only way I'm aware of is removing the react aliases in your next.config.js.
Earlier today someone on slack said he saw the warning.
Turned out he had this in his next.config.js:

```
if (config.resolve.alias) {
      delete config.resolve.alias.react
      delete config.resolve.alias['react-dom']
    }
```

To be clear. React doesn't require minification anymore. If you're using React 16+ the React is already minified when published on npm, the message is purely to point out that there *might* be something wrong with the transpilation. In our case we made the choice to not minify minified code and alias to the right bundle in dev/prod automatically. This saves ~20seconds with builds for us in production. And we avoid doing unneeded work.

If you removed the aliases because you have code using react-dom/server on the client side you can upgrade to `next@canary` which will be released as master soon 🙏

**Comment by arunoda** [comment]
And here's the version: https://github.com/zeit/next.js/releases/tag/5.0.1-canary.2

**Comment by davecarlson** [comment]
@timneutkens - you are correct. I'd actually done some next.config optimisations between me posted and you posting, removing the alias lines ) - and that does fix it :)
