### ISSUE TITLE
Cannot run with-amp example 

### ISSUE THREAD

**Issue by phongtattuan** [zeit/next.js#3152]
I'm using nextjs 4.1.3

When I run `with-amp` example with `npm run dev`, it show an error:
```
ERROR  Failed to compile with 2 errors                                                                                        

These dependencies were not found:

* react-dom/lib/DOMProperty in ./pages/_document.js?entry
* react-dom/lib/ReactInjection in ./pages/_document.js?entry
```

I cannot build this example also.

How can I resolve this ?

Thank you so much.

**Comment by ismamz** [comment]
This is because [React v16 admits unknown DOM attributes](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html). You can remove `react-dom/lib/DOMProperty` and `react-dom/lib/ReactInjection` imports as well as the first conditional on `pages/_document.js` file.

**Comment by phongtattuan** [comment]
thanks so much
I work, I can run the example now

but I found another issue here #3155
