### ISSUE TITLE
Deployment Question Regarding config.js

### ISSUE THREAD

**Issue by awworrell** [zeit/next.js#3160]
I am deploying in an environment with multiple servers behind a load balancer. We current build on one server then move those files everywhere. How do I deal with instances where there are environmental specific variables in the package that will be deployed?

- [ x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I would envision a process where I can build the application on a build server and deploy that built application to all servers in my environment and between environments where the environment specific information like the api url to use could be parameter without the need to run yarn build on each environment at deploy time.

## Current Behavior

Today in the environment I deploy in, I have multiple environments. There is development, qa, staging, and production. Each environment have different variables like the URL of the server it's connecting to, which api it should use, or various keys to use for analytics. Today when we deploy, we run yarn install and build on each server that it's being deployed to except when deploying behind a load balancer. We build on the first server then SCP it over to the other servers. This keeps the build number in check and allows me to update config files with the appropriate values prior to building. If i were to build the file, then update the config, the updated configs would not reflected in the built package until I build again.
 
I am curious if I did this how would i deal with the variables that are different between environments? Does a hard coded build number care of that even though I have modified the config.js file after having built it on a build server and overridden that build file?

## Context

My deploy process is messy and not very sustainable. 

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by pruhstal** [comment]
You can manage your .env variables with something like https://www.npmjs.com/package/dotenv and then set your environment like:

`NODE_ENV={development/qa/staging/production}`

**Comment by timneutkens** [comment]
This can now be handled using https://github.com/zeit/next.js#exposing-configuration-to-the-server--client-side
