### ISSUE TITLE
Some peer deps are missing

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#3166]
When you install `next` with a package manager like `pnpm` that uses `npm@2`-style non-flat `node_modules`, and then try to run it, there are the following packages missing that are required at the top-level:

- babel-loader
- react-hot-leader
- webpack
- babel-core

Because of the flattening of npm@3+ and yarn, these dependencies are available automatically, and things work.

But this is not safe, and is not guaranteed to always work.

These should be listed as peer dependencies in `next`. There should also be a note in the readme that they need to be added to your `package.json`.

**Comment by pruhstal** [comment]
Pull requests are gladly accepted ;)

**Comment by timneutkens** [comment]
> These should be listed as peer dependencies in next. There should also be a note in the readme that they need to be added to your package.json.

This is definitely not something I want to do. 
I'm thinking the webpack config has to be updated to also check for modules / loaders etc in `node_modules/next`

**Comment by vzaidman** [comment]
with npm 5.6 and yarn its the same.

when you install anything that has peer deps on core packages you also get peer deps warnings.

it's important to me to not have any warnings. for example:

`@babel/preset-stage-0@7.0.0-beta.42` warns about not meeting `@babel/core@7.0.0-beta.42`
`eslint-import-resolver-webpack@0.9.0` warns about not meeting `webpack@>=1.11.0`

**Comment by timneutkens** [comment]
This was solved with the release of Next 6 or so. Again all mentioned packages are not peerdeps.
