### ISSUE TITLE
multiple <link /> tags get duplicated in <head />

### ISSUE THREAD

**Issue by liweinan0423** [zeit/next.js#3169]
Relates to #2438 .

If we add the same `<link />` tag multiples in different `<Head />`, they are duplicated in the rendered the DOM

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
multiple `<link />` tags with exactly the same attributes should be du-duped when rendering HTML `<head>` elements

e.g.
component1.js
```jsx
import Head from 'next/head'

<Head>
  <link rel="stylesheet" href="/static/style.css" />
</Head>
```

component2.js
```jsx
import Head from 'next/head'
<Head>
  <link rel="stylesheet" href="/static/style.css" />
</Head>
```

Then the rendered HTML should be, where duplicated <link /> tags are unique'd
```html
<html>
  <head>
    <link rel="stylesheet" href="/static/style.css" class="next-head" />
  </head>
</html>
```
## Current Behavior
There will be duplicated <link /> tags rendered
```html
<html>
  <head>
    <link rel="stylesheet" href="/static/style.css" class="next-head" />
    <link rel="stylesheet" href="/static/style.css" class="next-head" />
  </head>
</html>
```

## Context

I am currently working on a solution with `react-apollo` which allows the data be pre-fetched before a new page is rendered at client side, the example [with-apollo-redux](https://github.com/zeit/next.js/tree/canary/examples/with-apollo-and-redux) only supports prefetching data at server side, therefore, at client side I have to walk through the whole component tree again and do data fetching if one node from the component tree has been wrapped by the `graphql` HOC. 

Since the component tree contains `<Head />` tags that produces side effects while going through the tree, so duplicated `<link />` tags get inserted in the DOM. I was supposed to call `Head.rewind()` but it is not allowed at client side.

As I know [react-helmet](https://github.com/nfl/react-helmet) will not generate duplicated `<link />` tags

I know we should leave user the liberty of inserting duplicated `<link />` tags if it is desired. But I believe in most cases user doesn't want it. So I am wondering if it would be OK by adding a `unique` flag on the tags so the [head.js](https://github.com/zeit/next.js/blob/2ec397b3564d5dbca933e8def9cd0801ebd3a2b5/lib/head.js#L50) would de-dupe tags with `unique` specified. 

```jsx
import Head from 'next/head'

<Head>
  <link rel="stylesheet" href="/static/style.css" unique />
</Head>
```

**Comment by timneutkens** [comment]
@liweinan0423 I had a PR adding the React `key` property for next/head so you can dedupe tags, but we closed it as ZEIT didn't have a need for it anymore. Something like `unique` wouldn't work cause we'd have to dedupe all the tags manually while the user can just provide a `key` to make sure it's deduped, just like React does 👌 I'm not opposed to adding it 👍  What do you think about this proposal? We've talked about this quite extensive internally.

**Comment by liweinan0423** [comment]
@timneutkens Thanks for your suggestion. I like the `key` property more than `unique` 😄 . I will try to send a PR.

**Comment by timneutkens** [comment]
@liweinan0423 you don't have to, I already did it a while ago. Will pull the fix back in and fix it 👌

**Comment by liweinan0423** [comment]
@timneutkens When I finished my PR I saw your last comment. But could you review and feel free to close it and get your old in :)

**Comment by SBoudrias** [comment]
Did this got removed again somehow?

I'm using `next@^4.1.4` and I'm still seeing duplicated style tags:

![screen shot 2017-11-27 at 4 43 40 pm](https://user-images.githubusercontent.com/923865/33258390-5a140dc4-d394-11e7-9ff9-e07702b7b218.png)
<img width="646" alt="screen shot 2017-11-27 at 4 43 29 pm" src="https://user-images.githubusercontent.com/923865/33258391-5a70adae-d394-11e7-8a3a-d7812eabad42.png">

```js
() => (
    <div>
            <Head>
                <style
                    key="aa-react-select-css"
                    data-source="aa-react-select-css"
                    type="text/css"
                    dangerouslySetInnerHTML={{ __html: cssStyle.toString() }}
                />
            </Head>
            <Etc />
    </div>
);
```

**Comment by liweinan0423** [comment]
this change is in the `canary` branch now. please use `next@canary` for now
