### ISSUE TITLE
Cannot test components in pages that use `withRedux`

### ISSUE THREAD

**Issue by lillyanka** [zeit/next.js#3177]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Developer should be able to shallow test components in pages using `withRedux`

## Current Behavior

Cannot access methods or state within components in pages using `withRedux`

## Steps to Reproduce (for bugs)

1. Create a page
2. import `withRedux`
3. Manipulate state within the page
4. Shallow test the page
5. `console log` the shallow test.

State or methods will not be shown in `console.log`.

## Context

We haven't been able to write tests for pages using `withRedux`

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    3.2.1    |
| node    |    6.3.1     |
| OS      |    OSX Sierra     |
| browser |    Chrome 61.0.3163.100     |

**Comment by lillyanka** [comment]
We're building an app using Next.js, but so far we've been unable to test methods or state contained in a page that uses `withRedux`. We've tried to fix that for about 2 or 3 weeks, but have been unable to and haven't had any luck finding a fix, or at least something that shed some light over this issue, online.

**Comment by coluccini** [comment]
Usually the issue is that you are exporting the wrapped component, not the component itself, so when you shallow render it you are just rendering the wrapper and that's why you can't access the component's methods.
What you can do, is to export the unwrapped component like this:
```javascript
class Component extends React.Component {
  // ...
}

export default withRedux(initStore, null, mapDispatchToProps)(Component)

export const PureComponent = Component;
```

And the import the pure component in your tests:

```javascript
import { PureComponent as Component } from './Component';
```
