### ISSUE TITLE
The build assumes that all js files under /pages is a page

### ISSUE THREAD

**Issue by emattias** [zeit/next.js#3183]
We have structured our files so that page specific code is in the pages folder. Here is an example:

- pages
  - manage-users
    - \_\_tests\_\_
      - manage-users.test.js
    - index.js
    - components
      - ManageUsersPage.js
      - \<other page specific components here\>

The index.js file has the ManageUsersPage.js components as its default export. That is a regular next.js page component

This structure has worked fine for us except when we build. This hardcoded glob assumes that all js files under pages is a page: https://github.com/zeit/next.js/blob/canary/server/build/webpack.js#L50

Does it make sense to make this glob overridable or do we have to not use file based routing?

**Comment by liweinan0423** [comment]
I thin you can move non-page components to another top-level folder and only keep page file under `pages` folder.

**Comment by emattias** [comment]
Yes, but I think our structure is good because it makes it clear that the components under a `/pages/<page name>` folder are specifically for that page

**Comment by liweinan0423** [comment]
what about the following structure?
```
- pages
   - page1.js
   - page2.js
- components
   - page1
      - page-1-component-1.js
      - page-1-component-2.js
   - page2
      - page2-component.js
```

**Comment by zenflow** [comment]
#1914 is related. It's marked closed but it's still active.

**Comment by zenflow** [comment]
Yup, this issue prevents us from using a [folders-by-feature](https://softwareengineering.stackexchange.com/questions/338597/folder-by-type-or-folder-by-feature) organization, which would be more scalable than the folders-by-type organization that is being imposed on us

**Comment by sergiodxa** [comment]
@zenflow I think a page is not always a feature, I mean a single page could have more than one feature of your app at the same time.

> e.g. pages/index.js could be showing the feature Chat and the feature Timeline (like FB) in the same page.

So **pages aren't features**.

**Comment by emattias** [comment]
@sergiodxa I agree they aren't always but when you have components that are only used in that page it made it clearer with the structure I described initially.

**Comment by zenflow** [comment]
@emattias Configurable `pagesGlobPattern` would resolve this issue (thanks for submitting the PR) but here's another proposal, which might be better considering Next's convention-over-configuration philosophy: 

Make all `lib/` and `__test__/` folders ignored. No configuration necessary, and it fits all use cases we've come across.

The idea of `lib/` folders is that they contain supporting code for their parent folder, so your components (along with helper functions and whatever else) would go somewhere in there.

@arunoda Could we get your thoughts?

**Comment by zenflow** [comment]
For clarification

This is the folder structure we want to **avoid**, especially if it is to scale to have more than 3 pages in a hierarchy more than 1 deep:

```
/components
  /chat
  /index
  /timeline
/helpers
  /chat
  /index
  /timeline
/pages
  /chat.js
  /index.js
  /timeline.js
/tests
  /chat
  /index
  /timeline
```

This would be more maintainable at scale, since we don't duplicate the (chat, index, timeline) structure for each file type:

```
/pages
  /index.js
  /__tests__
  /lib
    /components
    /helpers
  /chat
    /index.js
    /__tests__
    /lib
      /components
      /helpers
  /timeline
    /index.js
    /__tests__
    /lib
      /components
      /helpers
```

**Comment by zenflow** [comment]
@emattias Would my proposal fit your use case?

**Comment by emattias** [comment]
@zenflow I dont want to have to structure pages folders differently than other domains in our project. There there is no need for a lib/ sub folder for example

What if instead of excluding everything that is not a page, we have a convention where all pages have a filename suffix of .page.js 
Then you could structure things however you want/need.

**Comment by zenflow** [comment]
@emattias 

Files inside of `pages/` intuitively seem to have already opted into being a page, by virtue of being under `pages/`. I think it makes more sense to opt back out via a `lib/` sub folder, rather than opt in a second time via a `.page.js` suffix. 

Also consider that `.page.js` would be a breaking change affecting **every** project using Next.js. Many/most users have no problem with the current folders-by-type layout, and IMO it works fine for small projects. We should try to avoid imposing any changes on those users and projects, especially if it makes things less ergonomic for them, just to make things more ergonomic for us.

What is the harm in structuring the pages folders differently than other domains? Perhaps you could bring this convention to those other domains? E.g. if you have a `models/` folder and some of the files under it are not models, explicitly indicate this by putting them under a `lib/` sub folder. 

Do you think my proposal *could* satisfy your use case?

**Comment by mattbrunetti** [comment]
@liweinan0423 Would love to hear your thoughts on this!

**Comment by zenflow** [comment]
@liweinan0423 Would love to hear your thoughts on this!
