### ISSUE TITLE
UglifyJs: “Invalid assignment” – support for uglify-es?

### ISSUE THREAD

**Issue by tomsoderlund** [zeit/next.js#3184]
I'm getting “Invalid assignment” from UglifyJs in `next build`, so I've been forced to disable UglifyJs for now.

Anyone been able to migrate to [`uglify-es`](https://github.com/mishoo/UglifyJS2/tree/harmony)
 (with support for ES2015+/ES6+)?

**Comment by radeno** [comment]
What about Babel Minify and do more changes? #3056

**Comment by IanWang** [comment]
try to use `uglifyjs-webpack-plugin@1.0.1` and modify your `next.config.js`
 
```js
config.plugins = config.plugins.filter(p =>
  p.constructor.name !== 'UglifyJsPlugin'
)

if(!dev) {
  const Uglify = require('uglifyjs-webpack-plugin')
  config.plugins.push(
    new Uglify({
      parallel: true,
      sourceMap: true
    })
  )
}
```

**Comment by tomsoderlund** [comment]
Thank you @IanWang! It worked great.

**Comment by psycura** [comment]
i`ve added config, and now my next.config.js look like this:
`module.exports = {
    webpack: function ( config ) {
        if ( config.resolve.alias ) {
            delete config.resolve.alias['react'];
            delete config.resolve.alias['react-dom']
        }
        config.plugins = config.plugins.filter ( p =>
            p.constructor.name !== 'UglifyJsPlugin'
        );
        const dev  = process.env.NODE_ENV !== 'production';
    
        if ( !dev ) {
            const Uglify = require ( 'uglifyjs-webpack-plugin' );
            config.plugins.push (
                new Uglify ( {
                    parallel:  true,
                    sourceMap: true
                } )
            )
        }
        return config
    }
};
`

But now after successfull build, deploy , by useing now stuck at

>  Using "webpack" config function defined in next.config.js.
Whats wrong with this?
