### ISSUE TITLE
Throw undefined not handled correctly

### ISSUE THREAD

**Issue by oliviertassinari** [zeit/next.js#3186]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Throwing undefined in the `renderToHTML` shouldn't halt the request.

## Current Behavior

Throwing undefined halt the request.

## Steps to Reproduce (for bugs)

1. Throw `undefined` in a `.getInitialProps()` method.

## Context

To be more specific an error is raised from this line:
https://github.com/zeit/next.js/blob/2ec397b3564d5dbca933e8def9cd0801ebd3a2b5/server/index.js#L321

> unhandledRejection reason TypeError: Cannot read property 'code' of undefined
     at Server._callee18$ (/app/node_modules/next/dist/server/index.js:943:37)

Yes, throwing undefined is [supported by JavaScript](https://stackoverflow.com/questions/30049093/javascript-is-it-safe-to-throw-undefined). It was a mistake on my end. I don't throw undefined on purpose 😁 .

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  v4.0.2       |
| node    | v8.5.0        |
| OS      | Linux        |
| browser | Chrome        |

**Comment by oliviertassinari** [comment]
Actually, undefined error origins are very hard to track down. After all, having Next.js failing fast can be a hint on where the source can be. So, the current behavior helps on the DX side but is really wrong on the UX side.

**Comment by timneutkens** [comment]
I'm assuming we could do something with this in development mode, but I don't think we should increase the production bundle size to facilitate an uncommon pattern 👍
