### ISSUE TITLE
[Package] is not defined for browser-only lib in code that won't run in the server

### ISSUE THREAD

**Issue by jjant** [zeit/next.js#3189]
I have a component which looks roughly like this

```js
class ImagePreview extends React.Component {
  onChange = () => {
    const fileReader = new FileReader();
    // ...
  }

  render() {
    return (
      <div>
        {...}
        <input onChange={this.onChange} />
        {...}
      </div>
    )
  }
}
```

When I try to run this, I get `FileReader is not defined`, and I understand this, `FileReader` doesn't exist in the server, but the thing is that that shouldn't matter, since the corresponding piece of code containing that API won't run in the server.
I get that I could fix this using some isomorphic library/polyfill, but there shouldn't really be a need to do that in cases like this.

**Comment by liweinan0423** [comment]
Could you share your repo?  the `onChange` method is not supposed to run at server side

**Comment by goldensunliu** [comment]
Ditto.

**Comment by timneutkens** [comment]
@jjant can you try `new window.FileReader()`

**Comment by jjant** [comment]
You guys are completely right, I was doing this in a lifecycle hook (`componentWillReceiveProps`) which was called during server rendering. I'm sorry!

**Comment by timneutkens** [comment]
❤️
