### ISSUE TITLE
Make `CSS-in-JS` opt-in

### ISSUE THREAD

**Issue by lukeed** [zeit/next.js#319]
Although I see the use case for this, I personally will never use this feature.

I lose too much flexibility & reusability (and/or gain awkwardness) by not using SASS/Stylus/whatever. And with a cached, single (or not) stylesheet, I won't suffer any performance loss by not taking the small, as-needed css module approach.

> Plus, imo, the CSS module / Shadow-dom styles approach isn't fully solved yet. As [mentioned](https://github.com/zeit/next.js/issues/22#issuecomment-256417971), when each component prints  its own styles, excessive duplicates add up quickly. Of course, this is not a `next.js` or `glamor` issue specifically, but part of the reason why I find it makes more sense to compile styles ahead of time.

So, with as easy as it is to attach static assets in the `<Head />`, I think `glamor` should be opt-in or opt-out. 

As it is, I have to require & load all of `glamor` regardless of my choice of architecture. 😿

**Comment by nkzawa** [comment]
I think https://github.com/zeit/next.js/issues/251 will solve your problem.
You can make `glamor` opt-in and load global `.css` with it.

**Comment by lukeed** [comment]
It's close! But even with a custom doc, there's usage of glamor scattered throughout Next. So even if "turning off" or replacing glamor, it'll still be used and running.

**Comment by cameronroe** [comment]
+1 I have 10k lines of Sass that I'd like to import instead of port entirely to js. I'll migrate slowly, but this is a blocker.

**Comment by arunoda** [comment]
@cameronroe Currently you could import them via Next's static directory and writing a style tag in the head.

**Comment by cameronroe** [comment]
@arunoda Thanks. Does that use webpack's `sass-loader` from the `/static/`?

**Comment by sergiodxa** [comment]
@cameronroe next.js doesn't use `sass-loader`, in the future you would be able to use a custom webpack configuration (#40 #222), meanwhile you need to use your own task to run sass (either trough webpack or plain sass)

**Comment by rauchg** [comment]
@lukeed it's not true that we will have any usage of glamor scattered through the codebase if you use the `<Document>` approach (#251)

Performance and codebase size wise we'll make sure it always has near-zero impact. In fact @threepointone is working on making it even smaller now.

The alternative is that every single user of next has to set up a server-rendering pipeline for CSS, which is tedious, clunky and prone to memory leaks if not executed perfectly. But, it will be an option, since there are so many interesting alternatives in the React world (not least of which is `styled-components`).

The reason we picked glamor in fact is that it's the simplest possible abstraction, without trading off  CSS features. `css(obj) → className` is as simple as it gets.

One of my biggest priorities is to once #251 and #333 land is to explain in the Wiki different approaches to managing CSS, and point to those from the README.

**Comment by lukeed** [comment]
@rauchg These are all the direct & implicit uses of `glamor` that I traced:

* [`pages/_error-debug`](https://github.com/zeit/next.js/blob/c7ba914f527ebcfe084cb0e36946b9dee00d25fa/pages/_error-debug.js)
* [`pages/_error-debug`](https://github.com/zeit/next.js/blob/c7ba914f527ebcfe084cb0e36946b9dee00d25fa/pages/_error.js)
* [`lib/eval-script`](https://github.com/zeit/next.js/blob/master/lib/eval-script.js)
* [`client/next`](https://github.com/zeit/next.js/blob/65c4e1e5bd99c44befa94ab1d66fbada3e8986a1/client/next.js)
* [`client/next-dev`](https://github.com/zeit/next.js/blob/fcd59adea1a5fe34f5a663d7d2cdb8807f0315d4/client/next-dev.js)
* [`server/render`](https://github.com/zeit/next.js/blob/c7ba914f527ebcfe084cb0e36946b9dee00d25fa/server/render.js)
* [`lib/router`](https://github.com/zeit/next.js/blob/c7ba914f527ebcfe084cb0e36946b9dee00d25fa/lib/router.js)

While some of those (pages) are easy fixes, the rest are more deeply integrated. 

I understand that Glamor is part of the core system and that, truthfully, loading it at runtime isn't the end of the world. I also see how & why Next is one of the better offerings because of how Glamor is implemented. 

But, perhaps with #222, we can expose a `useCSS` option that defaults to `true` and, at runtime, conditionally imports the `glamor`-based methods and scaffolding in these files.

**Comment by rauchg** [comment]
Very good point. Let's open an issue with that option to discuss it when we
merge Document

**Comment by lukeed** [comment]
@rauchg 😺 I'll go ahead & open it now, just to have it ready.

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/create-next-app/index.test.js** 
- create next app > valid example
- create next app > should allow example with GitHub URL
- create next app > should allow example with GitHub URL and example-path
- create next app > should use --example-path over the file path in the GitHub URL

<details>
<summary>Expand output</summary>

  ● create next app › valid example

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js valid-example --example basic-css

      64 |   it('valid example', async () => {
      65 |     const projectName = 'valid-example'
    > 66 |     const res = await run(projectName, '--example', 'basic-css')
         |                 ^
      67 |     expect(res.exitCode).toBe(0)
      68 | 
      69 |     expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:66:17)

  ● create next app › should allow example with GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-app --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages

      81 |   it('should allow example with GitHub URL', async () => {
      82 |     const projectName = 'github-app'
    > 83 |     const res = await run(
         |                 ^
      84 |       projectName,
      85 |       '--example',
      86 |       'https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages'

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:83:17)

  ● create next app › should allow example with GitHub URL and example-path

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path --example https://github.com/zeit/next-learn-demo/tree/master --example-path 1-navigate-between-pages

      104 |   it('should allow example with GitHub URL and example-path', async () => {
      105 |     const projectName = 'github-example-path'
    > 106 |     const res = await run(
          |                 ^
      107 |       projectName,
      108 |       '--example',
      109 |       'https://github.com/zeit/next-learn-demo/tree/master',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:106:17)

  ● create next app › should use --example-path over the file path in the GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path-2 --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages --example-path 1-navigate-between-pages

      129 |   it('should use --example-path over the file path in the GitHub URL', async () => {
      130 |     const projectName = 'github-example-path-2'
    > 131 |     const res = await run(
          |                 ^
      132 |       projectName,
      133 |       '--example',
      134 |       'https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:131:17)

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/create-next-app/index.test.js** 
- create next app > valid example
- create next app > should allow example with GitHub URL
- create next app > should allow example with GitHub URL and example-path
- create next app > should use --example-path over the file path in the GitHub URL

<details>
<summary>Expand output</summary>

  ● create next app › valid example

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js valid-example --example basic-css

      64 |   it('valid example', async () => {
      65 |     const projectName = 'valid-example'
    > 66 |     const res = await run(projectName, '--example', 'basic-css')
         |                 ^
      67 |     expect(res.exitCode).toBe(0)
      68 | 
      69 |     expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:66:17)

  ● create next app › should allow example with GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-app --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages

      81 |   it('should allow example with GitHub URL', async () => {
      82 |     const projectName = 'github-app'
    > 83 |     const res = await run(
         |                 ^
      84 |       projectName,
      85 |       '--example',
      86 |       'https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages'

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:83:17)

  ● create next app › should allow example with GitHub URL and example-path

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path --example https://github.com/zeit/next-learn-demo/tree/master --example-path 1-navigate-between-pages

      104 |   it('should allow example with GitHub URL and example-path', async () => {
      105 |     const projectName = 'github-example-path'
    > 106 |     const res = await run(
          |                 ^
      107 |       projectName,
      108 |       '--example',
      109 |       'https://github.com/zeit/next-learn-demo/tree/master',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:106:17)

  ● create next app › should use --example-path over the file path in the GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path-2 --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages --example-path 1-navigate-between-pages

      129 |   it('should use --example-path over the file path in the GitHub URL', async () => {
      130 |     const projectName = 'github-example-path-2'
    > 131 |     const res = await run(
          |                 ^
      132 |       projectName,
      133 |       '--example',
      134 |       'https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:131:17)

</details>
