### ISSUE TITLE
How to use jquery library in nextjs component

### ISSUE THREAD

**Issue by s875515** [zeit/next.js#3190]
Hi, sorry about that easy issues, but I can't fix it......

there is my sample:
[https://github.com/s875515/nextjs-jquery-test](https://github.com/s875515/nextjs-jquery-test)

To click target link will be 「 $ is not defined 」 when first enter page not target.
I had already try npm install jquery but had another problem.

Did I miss something?  thanks all

**Comment by sergiodxa** [comment]
Use /static instead of ../static in the script src attribute.

**Comment by s875515** [comment]
@sergiodxa 
It still have problem...
(0 , _jquery2.default)(...).counter is not a function

**Comment by adamelliotfields** [comment]
Hi Leon,

I looked at your code and it appears you're not including the script tags anywhere in your index.html.

`pages/_document.js`

```
import Document, {Head, Main, NextScript } from 'next/document';
import flush from 'styled-jsx/server';

export default class CustomDocument extends Document {
  static getInitialProps({ renderPage }) {
    const { html, head, errorHtml, chunks } = renderPage();
    const styles = flush();
    
    return { html, head, errorHtml, chunks, styles };
  }

  render() {
    return (
      <html>
        <Head>
          <script src="/static/jquery.js"></script>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

Do that for all your scripts.

If you're looking to use React as a server-side templating language, and using jQuery on the client side, I'd recommend the `express-react-views` package instead.
