### ISSUE TITLE
Static Exports Should Resolve Symlinks

### ISSUE THREAD

**Issue by mikecentiq** [zeit/next.js#3191]
In my static folder I have the following symlink:

```
semantic.min.css -> ../node_modules/semantic-ui-css/semantic.min.css
```

When I do a `next export` it copies the symlink into the `out/static` folder. It would make more sense for it to read the contents of the file that is symlinked to and place that into the `out/static` folder.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Read the contents of the file pointed to by the symlink and place that into the `out/static` folder.

## Current Behavior
Symlink is copied.

## Context
I'm symlinking a file in my node_modules directory into my static directory so whatever version is installed by npm is immediately accessible and so that I don't have to commit that 3rd party modules file into git. Now I'm having to manually replace the symlink in the out folder after each export.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4.1.3        |

**Comment by jeffvandyke** [comment]
I'm having this same issue, and am working around it now by just copying the file in node_modules into /static, but just like `cp` has a `-L` option to always follow symlinks, a build that copies all from static should resolve symlinks, or at least provide a config option to do so.
