### ISSUE TITLE
Append bundle to `doc.body`

### ISSUE THREAD

**Issue by lukeed** [zeit/next.js#320]
Following PWA & PageSpeed recommendations, the `next.min.js` bundle should not be placed in the `document.head` as it delays the first paint.

Using Lighthouse on Nextgram (and zeit.co) shows that the bundle is (significantly) render-blocking, despite the pre-compiled server output.

<img width="803" alt="screen shot 2016-12-01 at 6 02 53 pm" src="https://cloud.githubusercontent.com/assets/5855893/20820517/9fd29184-b7f0-11e6-838b-637b2d6dd100.png">

Code Responsible:

```js
function load (src, fn) {
  fn = fn || function () {}
  var script = document.createElement('script')
  script.src = src
  script.onload = function () { fn(null) }
  script.onerror = fn
  script.crossorigin = 'anonymous'
  document.head.appendChild(script)
}
```

Ofc, the last little bit can be changed to wherever, or simply appended to the `body` altogether.

```js
document.body.insertBefore(script, document.body.lastChild);
//=> div#__next
//=> <script> __NEXT_DATA__ = ...
//=> <script src='next.min.js'>
//=> <script> function load(){}

document.body.appendChild(script);
//=> div#__next
//=> <script> __NEXT_DATA__ = ...
//=> <script> function load(){}
//=> <script src='next.min.js'>
```

And since the first load is always via SSR, visual content does not rely on the bundle being loaded. Because of this, we can set `script.async = true` within the `load` function.

---

Opening issue before starting PR 👌

**Comment by arunoda** [comment]
Okay. This is something interesting.
We can't make this async since there's another JS module called `commons.js` is getting loaded and it depends on the `next.min.js`.
But appending this to the body is a good idea.

**Comment by lukeed** [comment]
@arunoda I don't have anything substantial running, but I don't see a `commons.js` anywhere. Can see [nextgram](https://nextgram.now.sh/) as an example

**Comment by arunoda** [comment]
@lukeed it's something new and just came with `1.2.x` of Next.

**Comment by lukeed** [comment]
I can open a PR for this. I just wanted to get feedback before doing so.

**Comment by arunoda** [comment]
@lukeed go ahead and do it :) We'd love to take this in.
