### ISSUE TITLE
creating a component that is not affected by changes

### ISSUE THREAD

**Issue by sdfjfsdj** [zeit/next.js#3200]
ex. facebook desktop website messages component
it is the rationale behind doing this with nextjs
or for the navbar
or the ad that is not affected by page transitions

**Comment by Goluis** [comment]
Use the lifecycle from react: https://reactjs.org/docs/react-component.html

Also try to ask this kind of questions in [Slack](https://zeit-community.slack.com/) instead of here.

**Comment by sdfjfsdj** [comment]
the entire page refreshes in page transitions I want to be impressed by page transitions as an external component

**Comment by rileybracken** [comment]
Take a look at #88 and by extension #2440
