### ISSUE TITLE
Document can be pure component

### ISSUE THREAD

**Issue by bitsofpancake** [zeit/next.js#3204]
If the component specified in `pages/_document.js` is a pure component, this line throws.

https://github.com/zeit/next.js/blob/72827d25cb5990156436d5fffc4bd3ab7a4bdd38/server/render.js#L107

Everything seems to work fine if I remove this check.

**Comment by sergiodxa** [comment]
`pages/_documents.js` must always extends from `next/document` so you can't use neither use a `PureComponent` or a function stateless component.

If you're extending PureComponent or using a function then you need to change it to extend `next/document` as in https://github.com/zeit/next.js#custom-document

**Comment by frol** [comment]
@sergiodxa If that is the case, the error message is misleading, isn't it?

**Comment by frol** [comment]
@bitsofpancake I don't see how this check may fail if you pass a PureComponent as it should have both `prototype` and `isReactComponent` should be true. May it be that you forgot to export it as default?

**Comment by bitsofpancake** [comment]
Sorry, when I said pure component, I meant a stateless functional component like:

     const PlainDocument = ({ head, html, errorHtml }) =>
        <html>
            <head>{ head }</head>
            <body dangerouslySetInnerHTML={{ __html: errorHtml || html }} />
    </html>;

    PlainDocument.getInitialProps = ({ renderPage }) => renderPage();

Admittedly an edge case, as I can always inherit from Document as mentioned, but this is a bit nicer since it matches the style of the rest of my pages. I use this component when I know my pages are completely static and don't need React once rendered.

**Comment by sergiodxa** [comment]
@bitsofpancake you can't do that since you need some methods next/document has. So to work it *must* extends that class.

@frol yeah you're right we may need to improve the error message to say you need to extend next/document
