### ISSUE TITLE
Revision of with-mobx example

### ISSUE THREAD

**Issue by michaelsbradleyjr** [zeit/next.js#3206]
I found the with-mobx example useful, but wanted to have `<Provider>` wrapping be a bit less manual for Next.js page-components.  I looked to the `withRedux` helper function from the [next-redux-wrapper](https://github.com/kirill-konshin/next-redux-wrapper) project and got something working.

[canary...michaelsbradleyjr:with-mobx-revised](https://github.com/zeit/next.js/compare/canary...michaelsbradleyjr:with-mobx-revised)

Rather than make a pull request right away, I wanted to invite comments and suggestions as to whether this is a good idea or not, how it could be further improved, etc.

I haven't yet updated the README for the example since, based on your feedback, the way it works may continue to evolve.

**Comment by stevefan1999** [comment]
+1 For MobX. Screw Redux.

**Comment by zenflow** [comment]
@michaelsbradleyjr I'd recommend you open a PR with this since it will get more attention there and it's a better place to review and discuss exact code changes. PRs don't have to be ready to merge to be opened.

**Comment by michaelsbradleyjr** [comment]
Closing in favor of #3260.
