### ISSUE TITLE
Multiple Custom <Document> - Multiple definition of the surrounding document's markup

### ISSUE THREAD

**Issue by lanceschi** [zeit/next.js#3207]
Hi,

is it possible to define and use multiple custom Documents in next.js? Should I operate with subfolders?

- [ x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
I would like to define and import more than one custom document (https://github.com/zeit/next.js/#custom-document).

Should I operate with subfolders?

## Current Behavior
I can't define more than one custom document definition.

## Steps to Reproduce (for bugs)
I just run the code you can find here https://github.com/zeit/next.js/#custom-document

## Context
I'd like to set the lang attribute in HTML tag in a multi-language website.

## Your Environment
| Tech    | Version |
| next    |    4.1.3     |
| node    |    8.8.1     |
| OS      |    Ubuntu 16.04.2 LTS    |
| browser |    Google Chrome 64 bit v58.0.3029.110     |

Thanks,
Luca

**Comment by frol** [comment]
You can implement the single `_document.js` the way that it will choose different components based on whatever logic you want (e.g. URL).

**Comment by timneutkens** [comment]
Yep you can check the url in `getInitialProps`

**Comment by pruhstal** [comment]
@timneutkens what's the danger in not using `_document.js` within `/pages` and instead using your own custom document elsewhere? (like in `/components`) for a base layout?

**Comment by frol** [comment]
@pruhstal There is no danger in that. `_document.js` allows you to manipulate with the whole HTTP body while page component gets rendered inside the specific place in the layout defined in the `document`.
