### ISSUE TITLE
how to support random assetPrefix

### ISSUE THREAD

**Issue by huyansheng3** [zeit/next.js#3209]
the example is  assetPrefix: isProd ? 'https://cdn.mydomain.com' : '',
but i need set servals cdn name ,for example ,
assetPrefix: _.random(['https://cdn01.mydomain.com', 'https://cdn02.mydomain.com'])

- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by sergiodxa** [comment]
That should work, just load lodash inside the next.config.js and run that code, but that will just pick one of the CDN when building the app.

If you want to pick one dynamically you need to do it yourself in the code of your app. Maybe get the CDN url in the getInitialProps and cache it client side (maybe with sessionStorage) so it's going to be the same always for that user session.

**Comment by timneutkens** [comment]
👍
