### ISSUE TITLE
<link rel='preload' ..> before <meta charset="utf-8"> 

### ISSUE THREAD

**Issue by schoenwaldnils** [zeit/next.js#3210]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
`<meta charset="utf-8">` should be the first element in the `<head>`

## Current Behavior
`<NextScript />` prepends the preloadDynamicChunks in the head.
https://github.com/zeit/next.js/blob/canary/server/document.js#L87

## Context
https://sonarwhal.com/docs/user-guide/rules/meta-charset-utf-8/

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |    4.1.3    |
| node    |   8.4.0   |

**Comment by schoenwaldnils** [comment]
@timneutkens this PR doesn't solve this issue. sadly.

**Comment by timneutkens** [comment]
@schoenwaldnils it's not released yet. Have you tried the branch?

**Comment by schoenwaldnils** [comment]
Seems to work with ~4.2.1
