### ISSUE TITLE
Question: Should we PR into canary or master?

### ISSUE THREAD

**Issue by callumlocke** [zeit/next.js#3211]
I just noticed the default branch is `canary`, not `master`.

If we want to PR a change, should we be branching off (and PR'ing back into) `canary`?

Also, if possible can you explain the general purpose of the `canary` branch? Is it only temporary, or will there always be a `canary` branch, and will it always be the default branch?

**Comment by notrab** [comment]
I'm also interested in the response to this question. I've noticed NextJS ships new version releases quite often, even for things like typo changes in the README or examples update.

With the approach of using NPM and tagged releases, I was always under the impression `master` was the bleeding edge. Having a `canary` branch feels confusing.

*subscribed for updates*

**Comment by timneutkens** [comment]
@callumlocke @notrab there's a blogpost coming very soon about all this 👍 But you can read about Canary releases in general here: https://leo.im/2017/canary

**Comment by callumlocke** [comment]
Any update on that blog post?

As far as I can tell, the answer seems to be: PR into canary.

**Comment by timneutkens** [comment]
@callumlocke oh, yes! PRs go to canary. Sorry for not answering your question immediately 😄

**Comment by callumlocke** [comment]
@timneutkens no worries! Let me know when there's a blogpost, I'm curious to hear more context.

One other thing I'm confused about: master appears to be slightly ahead of canary at the moment.

**Comment by timneutkens** [comment]
@callumlocke @notrab https://zeit.co/blog/next-canary
