### ISSUE TITLE
Problems trying to Render a nextjs page blob (from a HTTP POST) into an iframe src

### ISSUE THREAD

**Issue by jorge-autogravity** [zeit/next.js#3216]
I’m trying to render a nextjs page blob (from a HTTP POST) into an iframe src. 

I do a HTTP POST to an url in my next server. Then convert that html document into a blob using `const urlBlob = URL.createObjectURL(blob)` and passing that into an iframe `<iframe src={urlBlob}/>`

I had to use **assetPrefix** in **next.config.js** to point to the host, in this case `http://localhost:3000`

In npm run dev the hmr is unavailable.
After running `npm build` and `npm start` it renders the page on an iframe and the JS loads.

The problem is that the router is breaking my JS.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Javascript should be functional. I expect the router to be disabled.

## Current Behavior

Javascript crashes with the following error:

`app.js:15 Failed to execute 'replaceState' on 'History': A history state object with URL 'tp://localhost:3000/2ada9931-0621-4f74-81ed-dc8255a340e6' cannot be created in a document with origin 'http://localhost:3000' and URL 'blob:http://localhost:3000/2ada9931-0621-4f74-81ed-dc8255a340e6'.`

## Steps to Reproduce (for bugs)

1. HTTP Post to a NextJS page
2. Render the html blob into an iframe using Url.createObjectURL
3. Open browser's console and see the router errors.

## Context

I am unable to use JS on iframes which are populated by blobs.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.1.0     |
| node    |   8.8.1      |
| OS      |    OSX High Sierra     |
| browser |     Chrome 62    |
| etc     |    ...     |

**Comment by timneutkens** [comment]
That has been fixed in Next 5/5.1.
