### ISSUE TITLE
Error in deploy

### ISSUE THREAD

**Issue by psycura** [zeit/next.js#3218]
Hello, guys.

Im trying to deploy nextjs project with now command, and have an issue with next.config.js file: if i use :
```
module.exports = {
webpack: function ( c ) {
if ( c.resolve.alias ) {
delete c.resolve.alias['react'];
delete c.resolve.alias['react-dom']
}
c.plugins = c.plugins.filter ( plugin => {
if ( plugin.constructor.name === 'UglifyJsPlugin' ) {
return false;
} else {
return true;
}
} );
return c
}
};`
```

everything work fine, and project deployed with no issues, but if i change this file to
`module.exports = {
webpack: function ( config ) {
if ( config.resolve.alias ) {
delete config.resolve.alias['react'];
delete config.resolve.alias['react-dom']
}
config.plugins = config.plugins.filter ( p =>
p.constructor.name !== 'UglifyJsPlugin'
);
const dev = process.env.NODE_ENV !== 'production';

    if ( !dev ) {
        const Uglify = require ( 'uglifyjs-webpack-plugin' );
        config.plugins.push (
            new Uglify ( {
                parallel:  true,
                sourceMap: true
            } )
        );
    }
    return config
}
};`

the deploy stuck at

Using "webpack" config function defined in next.config.js.
and throw me an message that deploy cannot be completed.

Why is this happen?

**Comment by psycura** [comment]
Any feedback?

**Comment by timneutkens** [comment]
Probably fixed in 5.x
