### ISSUE TITLE
ErrorComponent not receiving server-side props

### ISSUE THREAD

**Issue by finneganh** [zeit/next.js#3219]
- [X] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
If a component defined at `pages/_error.js` returns props from its `getInitialProps` on the server side, those props should be passed in when rendering the error component.

## Current Behavior
The server-generated props get thrown out when `client/index.js`’s `render` method checks for an `err` and calls `renderError` passing just `props.err` and not `props.props`.

## Steps to Reproduce (for bugs)

0. Use `NODE_ENV=production` to avoid the dev-only error behavior
1. Make an `_error` component that returns values from `getInitialProps` that depend upon values known on the server.
2. Throw an exception from another page’s `getInitialProps` method
3. When you visit that page, your `_error` component will be rendered, but its props will be from the client-side `getInitialProps` call from the client’s `renderError` function.

## Contributing
I’m happy to open a PR; I think that the fix would be to pass an optional set of props to `renderError` when `render` calls it in `client/index.js`. Only if those props are not provided would `renderError` call `loadGetInitialProps`.

If that’s a proper solution I can code it up.

## Context
I initialize a bit of my app’s state (API keys and the like) by passing values on the `req` object that’s given on the server to `getInitialProps`. If the first page a visitor sees is an error page, then these values from the server are thrown away, leaving my app partially un-initialized.

## Your Environment
Using Next 4.1.3 in my app, but looking through the code indicates that this is broken on HEAD as well.

**Comment by Mikhail-Fiadosenka** [comment]
Using next@5.1.0 - it's broken too.
I would like to add a note that default error handling from nextjs suffers from this bug too - if unhandled exception occurs during SSR phase, then SSR'ed error page has a message for 500 status code. But on the client-side it gets re-rendered with default error message since the props are lost (error message depends on `props.statusCode`).

Also, it seems for me incorrect that `getInitialProps` are invoked for SSR'ed page. This doesn't happen for regular, non-error pages.

**Comment by timneutkens** [comment]
> Using next@5.1.0 - it's broken too.

Sounds like a case of time to upgrade 😄 

This issue has been fixed in the latest version of Next.js.
