### ISSUE TITLE
Getting this error => "Warning: Did not expect server HTML to contain a <style> in <div>."

### ISSUE THREAD

**Issue by danielrvoigt** [zeit/next.js#3220]
- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

I am getting the following error in my React / Next.js app:
*Warning: Did not expect server HTML to contain a style in div.*

This affects the way the page is rendered, with a lot of content either not rendered or without styles. I have not been able to pinpoint the origin of this error and have tried different things, i.e. configuring the _document.js page.

**Comment by liweinan0423** [comment]
@danielrvoigt Could you share the repo you are working on so that we can help you?

**Comment by danielrvoigt** [comment]
Unfortunately I can't share the repo publicly.
