### ISSUE TITLE
Question: Blocking mixed resources https and http

### ISSUE THREAD

**Issue by danielstaleiny** [zeit/next.js#3225]
I tried to push my app into production but once deployed my images were not loaded with http and were blocked. I think that cause of this is some internal setting for production which dissable http on https comunication. I am running everything else on https and I get mix resources warning but I guess there has to be some setting blocking it in production cause on any other app I didn't run into this problem. 

Is there some setting which could cause this blocking of external resources ? I am planning to serve my pictures later on https but until then, I would like to disable blocking.

**Comment by timneutkens** [comment]
>  I would like to disable blocking.
Browsers do this automatically when you try to load http content on https. We don't do anything related to http/https and all urls are relative to the domain root. If you're using the `<img>` tag you've most likely done something similar to `<img src="http://<yoururl>/static/image.png" />`.

**Comment by danielstaleiny** [comment]
Okey, I am glad to hear that you don't do anything by it was just strange for me that it worked with create-react-app solution but not with nextjs so I felt like asking. 

I am not serving images from static but I am indeed serving them with `<img src="http://exterternal.source/name.jpeg" />`. 

I will try to serve them with https but that require some work. 
thank you anyway.
