### ISSUE TITLE
Next.js 4: Node-uuid deprecated - use uuid module instead

### ISSUE THREAD

**Issue by volaka** [zeit/next.js#3233]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Should not get deprecated warning when fresh install.

## Current Behavior

I am receiving deprecated warn:
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

## Steps to Reproduce (for bugs)

1.  Go to this blog: https://zeit.co/blog/next4
2.  Copy how to start: npm i next@latest react@latest react-dom@latest
3.  Install and receive warning

## Context

This warning didn't effect me but deprecated modules should be replaced.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4.1.4 |
| node    | 8.9.0 |
| OS      | Linux Mint |
| browser | - |
| npm     | 5.5.1 |

**Comment by rapzo** [comment]
That should be a dependency issue rather than a next issue.
From the `package-lock.json` i believe it's a `request` dependency from a dev-only dependency. I'd point it to coveralls or chromedriver or any kind of old stable stuff for dev purposes.

**Comment by volaka** [comment]
@rapzo I think it is also included in *next.js*
this is from my package-lock.json file. I am not sure how this file works but I see uuid in *request* and also in *next.js*
```json
"next": {
      "version": "4.1.4",
      "resolved": "https://registry.npmjs.org/next/-/next-4.1.4.tgz",
      "integrity": "sha512-8NP3bkRSguRmvr9NPHBvw9FxAbSSG4miYajcmvwY1Lr5/9ESs8IM6gHLkztP2vvMn5d++ag+TN9n+JlSNEazkQ==",
      "requires": {
        "ansi-html": "0.0.7",
        "babel-core": "6.26.0",
        "babel-generator": "6.26.0",
        "babel-loader": "7.1.2",
        "babel-plugin-module-resolver": "2.7.1",
        "babel-plugin-react-require": "3.0.0",
        "babel-plugin-syntax-dynamic-import": "6.18.0",
        "babel-plugin-transform-class-properties": "6.24.1",
        "babel-plugin-transform-es2015-modules-commonjs": "6.26.0",
        "babel-plugin-transform-object-rest-spread": "6.26.0",
        "babel-plugin-transform-react-jsx-source": "6.22.0",
        "babel-plugin-transform-react-remove-prop-types": "0.4.8",
        "babel-plugin-transform-runtime": "6.23.0",
        "babel-preset-env": "1.6.0",
        "babel-preset-react": "6.24.1",
        "babel-runtime": "6.26.0",
        "babel-template": "6.26.0",
        "case-sensitive-paths-webpack-plugin": "2.1.1",
        "cross-spawn": "5.1.0",
        "del": "3.0.0",
        "etag": "1.8.1",
        "fresh": "0.5.2",
        "friendly-errors-webpack-plugin": "1.6.1",
        "glob": "7.1.2",
        "glob-promise": "3.2.0",
        "hoist-non-react-statics": "2.3.1",
        "htmlescape": "1.1.1",
        "http-status": "1.0.1",
        "json-loader": "0.5.7",
        "loader-utils": "1.1.0",
        "md5-file": "3.2.3",
        "minimist": "1.2.0",
        "mkdirp-then": "1.2.0",
        "mv": "2.1.1",
        "mz": "2.7.0",
        "path-match": "1.2.4",
        "pkg-up": "2.0.0",
        "prop-types": "15.6.0",
        "prop-types-exact": "1.1.1",
        "react-hot-loader": "3.1.1",
        "recursive-copy": "2.0.6",
        "send": "0.16.1",
        "source-map-support": "0.4.18",
        "strip-ansi": "4.0.0",
        "styled-jsx": "2.1.1",
        "touch": "3.1.0",
        "unfetch": "3.0.0",
        "url": "0.11.0",
        "uuid": "3.1.0",
        "walk": "2.3.9",
        "webpack": "3.6.0",
        "webpack-dev-middleware": "1.12.0",
        "webpack-hot-middleware": "2.19.1",
        "write-file-webpack-plugin": "4.2.0",
        "xss-filters": "1.2.7"
      }
    },
```

**Comment by volaka** [comment]
@rapzo Sorry that i forgot to check which the false module was. I checked again and see that next.js is using uuid. Thanks for your interest. I will make a request to *request* library to check that module. :hand:
