### ISSUE TITLE
Added Entry does not go through build process?

### ISSUE THREAD

**Issue by designspin** [zeit/next.js#3235]
Thanks for next.js , I think it's awesome and has enabled me to progress a universal website much quicker than I could of done trying to build it out from scratch!

I have added an entry point in my config for a component that ends up in the /static folder, this is a script that I am loading onto a script tag on componentDidMount and accessed via a Web Worker:

```
const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer')
const { ANALYZE } = process.env
const path = require('path');

module.exports = {
  webpack: function (config) {
    console.log(config);
    if (ANALYZE) {
      config.plugins.push(new BundleAnalyzerPlugin({
        analyzerMode: 'server',
        analyzerPort: 8888,
        openAnalyzer: true
      }))
    }

    return Object.assign({}, config, { entry: function() {
      return config.entry().then((entry) => {
        return Object.assign({}, entry, { '../static/components/canvasAnim.js': './components/CanvasAnim'})
      })
    }})

    return config;

  }
}
```
My script is working in dev, but when I build it does not seem to get touched. I was expecting this to end up all minified. So when I run the code in prod, React complains with: Error: Minified React error #130;
 

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I don't think I am describing a bug here, probably something I am missing around the way next.js config works!

## Current Behavior

During build the entry does not seem to be touched.

## Steps to Reproduce (for bugs)

1. Add an entry point that maps to static and then build

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    latest     |
| node    |   8.6.0     |
| OS      |    macOs 10.12.6     |
| browser |    chrome 61     |
| etc     |         |

**Comment by designspin** [comment]
Does anybody know how I can modify the config to make this happen?

**Comment by timneutkens** [comment]
This is most likely related to the fact we don't let webpack handle everything. So this will most likely only work when we land https://github.com/zeit/next.js/issues/1245. I'm going to close this as duplicate and refer to it in the other issue 👍
