### ISSUE TITLE
Feature request: Triple serve

### ISSUE THREAD

**Issue by binary64** [zeit/next.js#3240]
Hi. Would anyone be so kind as to help me construct a npm command that will launch 3 servers:
1. dev on port 3000. This will be the usual npm run dev server with full debugging enabled
2. build->start on port 3001. This will be the nodejs next server (SSR)
3. build->export on port 3002. This will be serving purely static files (.html/.js/.css)

**Comment by sergiodxa** [comment]
Use [zeit/serve](https://github.com/zeit/serve) to serve the exported HTML.

**Comment by binary64** [comment]
Thanks for the start. How would I go about make it re-export on change to the sourcecode?

**Comment by binary64** [comment]
.

**Comment by binary64** [comment]
.

**Comment by sergiodxa** [comment]
You need to run `next build && next export` to re-export your changes. Export is not intended to be used in development, you develop withe `next` and when ready run `next build && next export` to create the static HTML and JS files.
