### ISSUE TITLE
eslint-loader doesn't appear to be respected

### ISSUE THREAD

**Issue by ryami333** [zeit/next.js#3241]
Have attempted to extend the webpack config in `next.config.js` to use the `eslint-loader` (to give warnings and/or errors during `dev` or `build`, much the same as Create React App does. 

### What I've tried: 
```js
/* next.config.js */
module.exports = {
    webpack: config => {
        config.module.rules.push(
            {
                test: /\.js$/,
                enforce: 'pre',
                exclude: /node_modules/,
                loader: 'eslint-loader',
            },
        );
        return config;
    },
};
```
```js
/* pages/index.js */
import React from 'react';

// This line should produce an eslint error, 'foo' is assigned a variable but never used
const foo = 'bar';

function Page() {
	return <h1>Welcome to next.js!</h1>
};

export default Page;
```

### What happens:
`dev` and `build` both run without incident.

### What I expect to happen:
`dev` and `build` to either fail entirely, or to produce an error in the browser, the browser console, or the CLI.

### What I've already found:
I found [this](https://github.com/zeit/next.js/issues/2184) issue already, which I believe might have been prematurely closed - a user referenced a way to configure the loader, which the OP had presumably already done.

---

Has anybody got any idea how I can configure nextjs to either fail-on-error or to emit some kind of error/warning message, in a similar way to CRA?

**Comment by vladmelnikov** [comment]
i have the same issue too

**Comment by davscro** [comment]
hi @ryami333,

I have working setup like:
```javascript
if (!dev)
            config.plugins.push(
                new BundleAnalyzerPlugin({
                    analyzerMode: 'disabled',
                    // For all options see https://github.com/th0r/webpack-bundle-analyzer#as-plugin
                    generateStatsFile: true,
                    // Will be available at `.next/stats.json`
                    statsFilename: 'stats.json'
                })
            );
        else {
            config.module.rules.push(
                {
                    test: /\.js$/,
                    enforce: 'pre',

                    include: [
                        path.resolve('components'),
                        path.resolve('pages'),
                        path.resolve('utils')
                    ],
                    options: {
                        configFile: path.resolve('.eslintrc.js'),
                        eslint: {
                            configFile: path.resolve(__dirname, '.eslintrc.js')
                        }
                    },
                    loader: 'eslint-loader'
                }
            );
            config.devtool = 'cheap-module-eval-source-map';
        }
```
**Please note else statement** Let me know does it work for you as well.

**Comment by vladmelnikov** [comment]
@davscro  it doesnt work for me

**Comment by ryami333** [comment]
Sorry @davscro, I abandoned Next for that project because of this issue, so I can't verify whether you setup works, but I'm fairly certain I had something almost identical.

**Comment by dsantic** [comment]
@ryami333 sorry about that. 
@vladmelnikov Could you please share simple example of your setup?

**Comment by vladmelnikov** [comment]
@dsantic i  tried this, but always  got error 

> Module build failed: TypeError: eslint.CLIEngine is not a constructor    at Object.module.exports (C:\react-components\node_modules\eslint-loader\index.js:176:27)
    at Object.module.exports (C:\react-components\node_modules\eslint-loader\index.js:176:27)

my config [https://gist.github.com/vladmelnikov/4f59ce9bdf1e67845111d251f3b33ebd](url)

**Comment by felquis** [comment]
I'm trying to use custom image loaders at next.config.js with no success, I think it is kind of related to this issue.

**Comment by timneutkens** [comment]
This will be fixed in Next.js v5.
