### ISSUE TITLE
the bundle for npm run dev is too big

### ISSUE THREAD

**Issue by accforgit** [zeit/next.js#3248]
I run the  `npm run dev` as the [SetUp](https://github.com/zeit/next.js#setup) said,no other package,but the bundle of the result is so big that even reach by 4MB, anything wrong?

**Comment by timneutkens** [comment]
This is expected for dev builds, they contain sourcemaps and devtools you don't have in production. The dev build is also not ran through uglify. If you want to see the production bundle run `npm run build` `npm run start`
