### ISSUE TITLE
Better to scope firebase-admin to auth user permissions?

### ISSUE THREAD

**Issue by jakelowen** [zeit/next.js#3250]
In the "with-firebase-authentication" example the server attaches a unrestricted firebase-admin instance to the request for later use in getInitialProps. This is ok, but wouldn't it be better to scope the firebase-admin down to just the permission level of the authed user? That way any query you run server-side has the same permissions as the user. I believe this is easily accomplished by omitting:

```
server.use((req, res, next) => {
    req.firebaseServer = firebase
    next()
  })
```

and instead adding in an additional express middleware (after the 'api/login' route):

```
server.use((req, res, next) => {
      try {
        admin.app('userScopedServer').delete()
      } catch (error) {
        console.log("creating new user scoped firebase-admin instance")
      }

      if (req.session && req.session.decodedToken && req.session.decodedToken.uid) {
        const userScopedFirebaseServer = admin.initializeApp({
          credential: admin.credential.cert(require('./credentials/server')),
          databaseAuthVariableOverride: {
            uid: req.session.decodedToken.uid
          }
        }, 'userScopedServer')

        req.userScopedFirebaseServer = userScopedFirebaseServer
      }
      next()
    })
```

Or am I thinking about this incorrectly?

**Comment by efosao** [comment]
@jakelowen It is certainly a very good idea to limit the`scope` of the server-side permissions to the user. The only issue I see is that it doesn't seem like you can make `anonymous` firebase requests in your example since the firebase-server is only set for `authenticated` users.

**Comment by efosao** [comment]
@jakelowen, this the solution I came up with to ensure matching scopes on the client and server...

```js
    // Server.js --->
    // verify auth token and extract the user's uid
    const uid = await admin
      .app()
      .auth()
      .verifyIdToken(token)
      .then(({ uid }) => uid)

    // create a `customToken` with the user's uid
    const customToken = uid ? await admin
      .auth()
      .createCustomToken(uid) : null
```

```js
    // Page.js --->
    // sign-in using the `customAuthToken` created above
    await firebase
      .auth()
      .signInWithCustomToken(customAuthToken)
      ...
```
