### ISSUE TITLE
Adjacent JSX elements must be wrapped in an enclosing tag

### ISSUE THREAD

**Issue by accforgit** [zeit/next.js#3251]
Next.js 4 supports React 16,and now React 16 supports  return an array of elements from a component’s render method，but why it throw an error of `Adjacent JSX elements must be wrapped in an enclosing tag` when I attempt to use it in Next.js 4 ?

package,json:   react: ^16.0.0 react-dom ^16.0.0 next ^4.1.4

thank you

**Comment by liweinan0423** [comment]
could you confirm you have `react: ^16.0.0` in the `dependencies` of package.json of your project?

**Comment by timneutkens** [comment]
Just checked and can't reproduce. Please provide a way to reproduce.

**Comment by julen** [comment]
I'm able to reproduce it this way:
```bash
mkdir tmp && cd tmp
npm init -y
npm install --save next react react-dom
mkdir pages
echo "export default () => (<div>hello</div><div>world</div>);" > pages/index.js
./node_modules/.bin/next
```
Visit http://localhost:3000/:
```
Module build failed: SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag (1:38)

> 1 | export default () => (<div>hello</div><div>world</div>);
```

Note at the moment `react` and `react-dom` are at version 16.1.0. With 16.0.0 the result is the same.

**Comment by sergiodxa** [comment]
@julen to render more than one element you need to return an array.
```
return [
  <div key={1}>hello</div>,
  <div key={2}>world</div>
]
```

Doing:

```
return (
  <div>hello</div>
  <div>world</div>
)
```

Is invalid JS code.

**Comment by julen** [comment]
Sorry I missed that, thanks for pointing it out 👍
