### ISSUE TITLE
Saga code splitting

### ISSUE THREAD

**Issue by trungpham** [zeit/next.js#3259]
Is code splitting possible with redux sagas? Does it hurt to load every single saga and reducer?

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by sergiodxa** [comment]
> Is code splitting possible with redux sagas?

You can use `await import('./your/saga.js)` to use code splitting everywhere, then it depends on how you handle that in your saga code, but that's not related to Next.js.

> Does it hurt to load every single saga and reducer?
It depends on how much code are you loading, also if all your pages are going to load the same sagas and reducers then it's going to be added to a common bundle and loaded only one time.

**Comment by zalabinc** [comment]
see https://github.com/zalabinc/nextjs-boilerpate/blob/master/app/utils/injectSaga.js
and https://raw.githubusercontent.com/zalabinc/nextjs-boilerpate/master/app/utils/sagaInjectors.js

simple HOC to inject sagas as wrapped component
