### ISSUE TITLE
next build minimizing doesnot work effieciently

### ISSUE THREAD

**Issue by BijayRai** [zeit/next.js#3263]
after doing next build my current project is creating a file around **8 mb - 10 mb** which taking so many time for routing... How to minimize our all code in like **kb** file so our site performance increases. 

Whenever i changed my routes to settings it takings so much time. and its showing Size of 8.4 Mb. Whats the cause for this?

![screen shot 2017-11-10 at 3 13 26 pm](https://user-images.githubusercontent.com/4888819/32651719-00654f6c-c62a-11e7-91ec-3cff168e9662.png)

**Comment by frol** [comment]
@BijayRai Without more information about your project and dependencies, there is nothing we can help with. In general, use tools for bundle size analysis; here are examples of how to use them with Next.js:

* https://github.com/zeit/next.js/tree/canary/examples/with-webpack-bundle-analyzer
* https://github.com/zeit/next.js/tree/canary/examples/with-webpack-bundle-size-analyzer
