### ISSUE TITLE
[using-inferno] Next.js 4 requires React 16

### ISSUE THREAD

**Issue by lyquocnam** [zeit/next.js#3264]
can not swich react 16 to inferno, i try to clone https://github.com/zeit/next.js/tree/canary/examples/using-inferno but not work

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
```Next.js 4 requires React 16```

## Steps to Reproduce (for bugs)

1. next build
2. next start
3. ```Next.js 4 requires React 16```
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     4    |
| node    |    9     |
| OS      |     osx    |
| browser |    chrome     |
| etc     |         |

**Comment by vladejs** [comment]
Is this already solved?

**Comment by acao** [comment]
I had issues with preact as well, before this message appeared. Next 5 uses ReactDom.hydrate() and some other react 16 featurea not available yet in preact-compat or inferno-compat

**Comment by acao** [comment]
see: https://github.com/developit/preact-compat/issues/432

**Comment by acao** [comment]
`ReactDom.hydrate()` will be tricky - `ReactDom` got quite the overhaul in React 16.

just dug through the call stack and it's deeply enmeshed with fiber and `react-reconciler`. not sure how to re-create this in preact or inferno without just being cheap and calling the compatibility layer's `render()` instead.
