### ISSUE TITLE
hese relative modules were not found

### ISSUE THREAD

**Issue by sandywk** [zeit/next.js#3266]
`These relative modules were not found:

* ../../../../.4.1.4@next/dist/lib/error.js in ./node_modules/.4.1.4@next/dist/pages/_error.js?entry
* ../../../../.4.1.4@next/dist/server/document.js in ./node_modules/.4.1.4@next/dist/pages/_document.js?entry
(node:93235) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead`

| Tech    | Version |
|---------|---------|
| next    |     4.1.4    |
| node    |    8.0.0     |
| OS      |     macOS 10.12.6    |
| browser |     Chrome    |
| etc     |         |

In fact, there are files.

**Comment by timneutkens** [comment]
Please provide a repository to reproduce the issue. Thanks!

**Comment by wz2cool** [comment]
I have same issue , follow "Getting Started": https://learnnextjs.com/basics/getting-started/setup
