### ISSUE TITLE
Problems encountered by NPM run dev

### ISSUE THREAD

**Issue by sandywk** [zeit/next.js#3267]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
I just started to use next.js, but after the completion of the installation is encountered, only in macOS, win 10 is normal.

## Current Behavior
`These relative modules were not found:

* ../../../../.4.1.4@next/dist/lib/error.js in ./node_modules/.4.1.4@next/dist/pages/_error.js?entry
* ../../../../.4.1.4@next/dist/server/document.js in ./node_modules/.4.1.4@next/dist/pages/_document.js?entry
(node:6711) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead`

## Steps to Reproduce (for bugs)
My operation process :
`mkdir gw`
`cd gw`
`npm install --save next react react-dom`
`mkdir pages`
`cd pages`
`vim index.js`
index.js content
`export default () => <div>Welcome to next.js!</div>`
package.json
`{
  "scripts": {
    "a": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^4.1.4",
    "react": "^16.1.0",
    "react-dom": "^16.1.0"
  }
}`
`npm run dev`

## Context
I'm just going to do my project with next.js, but I've got this problem at the beginning.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     4.1.4    |
| node    |    8.0.0     |
| OS      |    macOS 10.12.6     |
| browser |    Chrome     |
| etc     |         |

I hope to get help. Thank you very much!

**Comment by sandywk** [comment]
solved!
`sudo npm install -g npm`

**Comment by tennessine** [comment]
小心cnpm版本，用npm最新版本安装依赖
