### ISSUE TITLE
Safari will always scroll to top when local/redux state is change but works fine in chrome and firefox.

### ISSUE THREAD

**Issue by lsping8** [zeit/next.js#3274]
- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

![screen shot 2017-11-14 at 4 00 18 pm](https://user-images.githubusercontent.com/22074518/32769028-3858d564-c955-11e7-9b06-8318d5e51da3.png)
Scrollview and left sidebar is in different container and when changing component's state should not affect others.

## Current Behavior

Scrollview will always get affected when any component changing state.

## Steps to Reproduce (for bugs)

1. go to https://wander.chat/ with safari.
2. scroll to the bottom.
3. click on the left top corner logo and scroll view will suddenly jump to the top

## Context

I just want to make how it is working in google chrome and i had try to log which container/component is re-render but nothing is being re-render while scrollview keep on scrolling to the top.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    3.2.2     |
| node    |   8.2.1      |
| OS      |    macOs High Sierra v 10.13.1    |
| browser |    Safari v 11.0.1     |

**Comment by timneutkens** [comment]
This is most likely related to Safari rendering. There's not much we can do to prevent this on our side.
