### ISSUE TITLE
How to access webpack.config.js from js?

### ISSUE THREAD

**Issue by lifeiscontent** [zeit/next.js#3279]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

Hi there,

I want to setup this node_module https://react-styleguidist.js.org/docs/webpack#create-react-app-typescript

and in order for it to work, it needs to access the webpack.config, how do I go about exposing that to this node_module?

**Comment by timneutkens** [comment]
It's available in `next.config.js` from there you can write it to a file and then require it in the module.

**Comment by lifeiscontent** [comment]
@timneutkens how do you write the config to a file? It has a dynamic entry function. so util.inspect doesn't work. and JSON.stringify doesn't do it either.
