### ISSUE TITLE
with-i18next example doesn't work

### ISSUE THREAD

**Issue by julianguyen** [zeit/next.js#3282]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

https://github.com/zeit/next.js/tree/canary/examples/with-i18next should run when I run `yarn && yarn dev`

## Current Behavior

I get the following error:
```
TypeError: Cannot read property 'node' of undefined
    at Object.<anonymous> (/Users/julia/with-i18next/node_modules/react-i18next/dist/commonjs/interpolate.js:100:29)
    at Module._compile (module.js:570:32)
    at Module._compile (/Users/julia/with-i18next/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/julia/with-i18next/node_modules/react-i18next/dist/commonjs/index.js:12:20)
```

## Steps to Reproduce (for bugs)

1. yarn && yarn dev
2. Open localhost:3000

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     latest    |
| node    |    6.10.0     |
| OS      |    10.12.5    |
| browser |     62.0.3202.94      |
| etc     |         |

**Comment by oliviertassinari** [comment]
It took me one week to integrate next.js with i18next. It's doable, but be ready to dodge issues.

**Comment by julianguyen** [comment]
Oh thanks @oliviertassinari lol... Did you encounter the issue I posted above by any chance or have your working example anywhere to look at?

**Comment by oliviertassinari** [comment]
@julianguyen The demos on next.js and react-i18next weren't matching our requirements. We wanted:
- isolated requests
- negotiation of the locale by the server, and only the server
- namespaces by pages
- asynchronous and dynamic namespaces load
- Intl support

**Comment by julianguyen** [comment]
Ah thanks @oliviertassinari! Do you recommend using react-intl over i18next with next.js?

**Comment by oliviertassinari** [comment]
react-intl is better written than i18next but solve fewer problems, your call.
If I have had the time, I would have been writing my own solution.

**Comment by Neophy7e** [comment]
@julianguyen @oliviertassinari [js-lingui](https://github.com/lingui/js-lingui) seems to be a good alternative to both react-intl and i18next

**Comment by oliviertassinari** [comment]
@Neophy7e As far as I have seen at js-lingui the problems solved scope is close to react-intl. For instance, it doesn't solve the ressources loading as one would expect with next.js https://lingui.github.io/js-lingui/guides/dynamic-loading-catalogs.html
