### ISSUE TITLE
Prebuild JS Bundles for CDN

### ISSUE THREAD

**Issue by chrisui** [zeit/next.js#3284]
Would it be possible for `next build` to prebuild all js bundles from pages and spit them out so they can be uploaded to the cdn? I can see `next export` however I still want the server for the initial render but also want to leverage a CDN for my js assets.

**Comment by sergiodxa** [comment]
That's exactly what `next build` does, you can see all the JS files inside `.next` directory and there you can find the client side code required.

That's also why Next.js custom config [support `assetPrefix`](https://github.com/zeit/next.js#cdn-support-with-asset-prefix).

**Comment by chrisui** [comment]
Ah gotcha. I've got some other bad config emitting a build and dist folder which confused me.

Thanks for clarification!

**Comment by pcardune** [comment]
Not sure what I'm doing wrong, but this doesn't seem to be working for me. The browser is requesting files from urls like

```
/_next/9cb53b14-3000-42e4-8b61-7e87ee82ea4a/page/podcast-episode
```

But these paths do not show up in the output of `next build`. Here is what I get in my `.next` directory (which I've renamed to `build`):

```
build
build/dist
build/dist/ui
build/dist/ui/BlogPostCard.js
build/dist/ui/Section.js
build/dist/ui/ProfileCard.js
build/dist/ui/PageLayout.js
build/dist/ui/GlobalNav.js
build/dist/ui/Colors.js
build/dist/ui/Hero.js
build/dist/ui/ProfileGrid.js
build/dist/ui/PodcastEpisodeCard.js
build/dist/ui/TrustedHTML.js
build/dist/ui/PodcastPlayer.js
build/dist/ui/Footer.js
build/dist/CMS.js
build/dist/styles
build/dist/styles/getContext.js
build/dist/components
build/dist/components/withRoot.js
build/dist/propTypes.js
build/dist/pages
build/dist/pages/blog-index.js
build/dist/pages/_error.js
build/dist/pages/login.js
build/dist/pages/home-page.js
build/dist/pages/podcast-index.js
build/dist/pages/blog-post.js
build/dist/pages/_document.js
build/dist/pages/podcast-episode.js
build/manifest.js
build/BUILD_ID
build/main.js
build/build-stats.json
build/commons.js
build/app.js
build/bundles
build/bundles/pages
build/bundles/pages/blog-index.js
build/bundles/pages/_error.js
build/bundles/pages/login.js
build/bundles/pages/home-page.js
build/bundles/pages/podcast-index.js
build/bundles/pages/blog-post.js
build/bundles/pages/_document.js
build/bundles/pages/podcast-episode.js
```

So what am I supposed to be uploading to the CDN?

**Comment by arunoda** [comment]
@pcardune You don't need to upload anything.
Most of the CDN server offers [custom origin](https://www.maxcdn.com/one/tutorial/origin-url-and-label-field/) support

* Basically, you set a custom origin to `yourapp.com` and get a CDN url like `abc.mycdn.com`
* Then you default a new version of your app and set it to yourapp.com with the `abc.mycdn.com` as the `assetPrefix`

So,

* When the browser asks `abc.mycdn.com/_next/***` for the first time, CDN will fetch it from the `yourapp.com` and cache it inside it.

This is the same thing we do for https://zeit.co.

In our case, `assetPrefix` is https://assets.zeit.co/raw/upload/front-assets

**Comment by pcardune** [comment]
Yes, I'm familiar with using a CDN as a proxy to your application servers.

But I think it is still useful to be able to get all the assets in static file form for the following reasons:

1. Warming CDN caches before deploying new versions (https://www.cdnplanet.com/guides/prefetch/)

2. Using many of the "turn-key" CDN solutions that are backed by cloud file storage (S3, Google Cloud Storage, etc) where the simplest configuration is to just point the CDN to a storage bucket.

**Comment by unregistered** [comment]
We're currently looking into uploading assets to a bucket as well, it seems like we'll need to generate the mappings ourselves. 

It doesn't seem like using the application servers as the origin would work though because of the versioning requirements, especially if the application servers are behind a load balancer, and rolling deploys means that multiple versions can coexist.

**Comment by gcpantazis** [comment]
> It doesn't seem like using the application servers as the origin would work though because of the versioning requirements, especially if the application servers are behind a load balancer, and rolling deploys means that multiple versions can coexist.

@arunoda this is exactly our problem as well; AWS ECS deployments for example expect you to handle the case where two versions can temporarily coexist while traffic is being drained on the last build.

Is there an updated solution for that case?

**Comment by dav-is** [comment]
Plus one. Can we get this issue reopened?

**Comment by sergiodxa** [comment]
Next.js detects a BUILD_ID change and reload the page to use the new built files.

So if an user access to a Next.js app and start navigating the page, then the developer build a new version, the internal BUILD_ID will change, if the user try to navigate to another page client side Next.js will detect the mismatch of the BUILD_ID and do a page reload, then it will download the new built files, so you don't need to have two versiones coexisting, user of the old version will be forced to load the new bundles.

**Comment by dav-is** [comment]
Google cloud cdn doesn’t support remote origin and uses google storage. Is it too much to ask that next outputs truly static bundles. Seems a bit needless that static file requests run through nodejs to begin with.

**Comment by jsnick** [comment]
@sergiodxa 
Suppose there are over two instances behind a load balancer, which are next.js app.
and CDN origin is web server. (Endpoint is LB)

If I deploy a new version, rolling update is started.
Then the old and new versions could be coexisting.

At that time, a user requested my app, and the LB send the request to a new version.
It'll receive the new version which endpoint of the new assets is included.
Then it'll send the request of new assets to CDN. 
CDN has no cache about it, so cdn request it to origin. (LB)

But this time, If the LB send the reqeust of CDN to the old version instance, CDN will receive a response 404. because the old one doesn't have new assets.
CDN could cache the endpoint of new assets to 404.


So, I will build my next.js app, make BUILD_ID directory in my origin (like S3) and upload files in dist to BUILD_ID directory.

**Comment by dav-is** [comment]
Exactly and would be the case for some forms of AB testing where you deploy two versions to different groups of users

**Comment by unregistered** [comment]
@jsnick good summary. We’ve already implemented exactly that at my workplace. It works well so far. Not sure if there’s interest for an open source contribution

**Comment by vaibhavi3t** [comment]
@sergiodxa 

I set `assetPrefix` in next.config.js like below:
```
module.exports = {
  assetPrefix: isProd ? 'https://dw745fgl22f1q.cloudfront.net/pwa-ssr/' : ''
};
```
       
It's added following script
```
<script async="" id="__NEXT_PAGE__/home" src="https://dw745fgl22f1q.cloudfront.net/pwa-ssr/_next/4c667dfa-d920-4973-9214-dec4485990b1/page/home.js"></script>
<script async="" id="__NEXT_PAGE__/_app" src="https://dw745fgl22f1q.cloudfront.net/pwa-ssr/_next/4c667dfa-d920-4973-9214-dec4485990b1/page/_app.js"></script>
<script async="" id="__NEXT_PAGE__/_error" src="https://dw745fgl22f1q.cloudfront.net/pwa-ssr/_next/4c667dfa-d920-4973-9214-dec4485990b1/page/_error.js"></script>
<script src="https://dw745fgl22f1q.cloudfront.net/pwa-ssr/_next/static/commons/main-b982386b18bef2694dbd.js" async=""></script>
```
I uploaded `.next` folder to my CDN

I'm able to get main.js bundle with 200 OK but getting 400 Error for other pages. You can see there is build number in the path but there is not such path in the `.next` folder. so it's not able to resolve.
How can I fix it?

**Comment by Janpot** [comment]
The `.next` folder seems to contain server code as well. Is it safe to upload that to a CDN?
