### ISSUE TITLE
Module parse failed, You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by tharakabimal** [zeit/next.js#3287]
I'm trying to use [react-datepicker](https://github.com/Hacker0x01/react-datepicker) in one of my react components. When I import the `CSS` file like mentioned below, I get an error.

`import 'react-datepicker/dist/react-datepicker.css'`

The error I get is,

```
Error in react-datepicker/dist/react-datepicker.css

Module parse failed: /path/to/my/project/folder/node_modules/react-datepicker/dist/react-datepicker.css 
Unexpected token (1:0) You may need an appropriate loader to handle this file type. | .react-datepicker-popper[data-placement^="bottom"] .react-datepicker__triangle, .react-datepicker-popper[data-placement^="top"] .react-datepicker__triangle, .react-datepicker__year-read-view--down-arrow, | .react-datepicker__month-read-view--down-arrow { | margin-left: -8px;

```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   latest      |
| node    |    8.4.0     |
| OS      |   macOS High Sierra      |
| browser |    Google Chrome Version 61.0.3163.100     |

**Comment by timneutkens** [comment]
Please search for `css` in the issue tracker. There are multiple issues asking the exact same thing. There are multiple solutions.
