### ISSUE TITLE
Hot reload with styled-components doesn't work.

### ISSUE THREAD

**Issue by tangbc** [zeit/next.js#3290]
When I running the offical example [with-styled-components](https://github.com/zeit/next.js/tree/canary/examples/with-styled-components) hot-reload is all ok if `styled-component` is write in `pages/index.js`.

I just import a `styled-component` which is defined in `styles/index.js`. It works fine at first building, then I change `styles/index.js` CSS rule and save file, my terminal shows nextjs compiled successfully but the changes not effect in browser (force refresh F5 can be effect), it seems hot-reload not change the styles build like this way. Can this problem be sloved ?

**Structrue:**
```
├── package.json
├── pages
│   ├── _document.js
│   └── index.js
└── styles
    └── index.js
```

**styles/index.js:**
```javascript
import styled from 'styled-components'
export const Title = styled.h1`
    color: green;
`
```

**Comment by Flaque** [comment]
Hmm, I'm working on a project right now with Next and Styled-components where hot code works just fine. 

Can you clone [this project](https://github.com/gu-app-club/save-the-net), run `yarn dev` to launch next and then edit the background of the component at `components/ui/Card` to see if it changes anything?

**Comment by timneutkens** [comment]
External styles are not watched, but there's multiple issues around this. Not only for styled-components. So I'm going to close this one.
