### ISSUE TITLE
Basic state in a next.js page

### ISSUE THREAD

**Issue by gusaiani** [zeit/next.js#3291]
Hi all,

thanks for Next.js.

I've been building from the [data fetch](https://github.com/zeit/next.js/tree/canary/examples/data-fetch) example, so no Redux here, just the basics.

I'd like to know how to handle state.

Example: I have a `popup` that should be hidden on page load.
When the user clicks a button, I'd like to toggle something, be it a prop or state, to show the popup.

Simple as it is, I haven't been able to find a good practice and will be very grateful for your help.

Thank you.

**Comment by brandonmp** [comment]
I'm still learning NextJS, but I don't think working with state requires any special consideration. I think you'd just build state into your component as usual, setting the initial state to `{ isPopupOpen: false }`

**Comment by gusaiani** [comment]
Thanks @brandonmp.
I think you're right. 
I was able to set stuff with `Router.push` but it seemed overkill.

So far I'm setting `initialState` in the constructor and changing with `this.setState(...)`, and so far so good.

Closing the issue but I'm always open to any other suggestions.

**Comment by OKNoah** [comment]
@gusaiani Have an example?

**Comment by sergiodxa** [comment]
@OKNoah -> https://reactjs.org/docs/state-and-lifecycle.html#adding-local-state-to-a-class
Handling state in Next.js is the same as any React component.
