### ISSUE TITLE
Q: Can this save the fetched data for offline reading?

### ISSUE THREAD

**Issue by AndersGerner** [zeit/next.js#3298]
Just a quick question:

I would like to create a React app that shows some JSON data in a nice way from my server.
This needs to work for a maximum of 30 days offline. 

Is it possible to store a React app build with NextJS to both save my JSON and alert when 30 days are up? 

Thanks in advance :)

**Comment by jacobpdq** [comment]
https://developers.google.com/web/ilt/pwa/caching-files-with-service-worker

**Comment by AndersGerner** [comment]
@jacobpdq Thank you very much!
