### ISSUE TITLE
@types/next/router has no exported member 'withRouter'

### ISSUE THREAD

**Issue by shabith** [zeit/next.js#3300]
Hello everyone,

It seems @ types/next/router is missing an exported member called 'withRouter'. Is it a knowing issue?
Any workaround for this?

Thanks

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     4.1.4    |
| node    |   8.5.0      |
| OS      |   Windows 10      |
| @ types/next     |   2.4.5      |

**Comment by brikou** [comment]
I think you can close because type has been updated, check it by yourself

**Comment by ndreckshage** [comment]
shouldnt this (https://github.com/zeit/next.js/blob/canary/examples/with-flow/types/next.js.flow) be
```
declare module 'next/router' {
  declare export default {
    route: string,
    pathname: string,
    query: Object,
    onRouteChangeStart: ?(url: string) => void,
    onRouteChangeComplete: ?(url: string) => void,
    onRouteChangeError: ?(
      err: Error & {cancelled: boolean},
      url: string
    ) => void,
    push(url: string, as: ?string): Promise<boolean>,
    replace(url: string, as: ?string): Promise<boolean>
  };

  declare export function withRouter(
    Component: React$ComponentType<*>
  ): React$ComponentType<*>;
}
```
