### ISSUE TITLE
Import all .jpg images in /static as an Array

### ISSUE THREAD

**Issue by xih** [zeit/next.js#3301]
Hi I want to use React Masonry to display a bunch of pictures. I have all the pictures in a folder titled Europe inside /static. I need to get the src's of the images into an array, so I can do this:

` 

             var childElements = this.props.photos.map(function(element) {
                   return (    
                     <li className="image-element-class">
                          <img src={element.src} />
                     </li>
                );
            });
`

I'm trying this: 
import Images from "/static/Europe/*.jpg"

but it is not working. 

How would I import all *.jpgs into an array ?

**Comment by sergiodxa** [comment]
We have an example in the repo to import static files to get the URL using a Babel plugin but I think it only works while importing each file individually.

With Next.js we don't support importing images the way you want.

**Comment by timneutkens** [comment]
You could add a build step outside of Next that turns the directory into a json file and import that in your app 👍
