### ISSUE TITLE
How to redirect to subdomain url?

### ISSUE THREAD

**Issue by jaqua** [zeit/next.js#3307]
Is it possible to do a redirect to a subdomain url?

This is how my redirect function looks like to handle server/client redirect:

    const redirect = (context, target) => {
      if (context.res) {
        // server
        context.res.writeHead(303, { Location: target })
        context.res.end()
      } else {
        // client
        Router.replace(target)
      }
    }

With that on `anything.domain.com` I can do somethin like

    redirect({}, '/login')

to get redirected to `anything.domain.com/login`

But I need to redirect to `login.domain.com` instead.

This does not work: `redirect({}, 'http://login.domain.com')`

**Comment by DevSpeak** [comment]
@jaqua 
If you're using the redirect on the client, you could use `window.location.replace('http://login.domain.com')` instead of `redirect({}, 'http://login.domain.com')` until someone post a better fix.

_Tested in with-apollo-auth, but im far from good at JS_

**Comment by brandonmp** [comment]
if you're using `now` for hosting, this might help: https://zeit.co/blog/path-alias

**Comment by timneutkens** [comment]
What @DevSpeak said is correct. You're not routing inside of the next.js app so you need to use `window.location.href`
