### ISSUE TITLE
Private Routes and Redirect

### ISSUE THREAD

**Issue by vladmelnikov** [zeit/next.js#3309]
is it possible to make Private Route like in react-router 4 ? 
https://reacttraining.com/react-router/web/example/auth-workflow
or there is another way to make redirect at the browser ?

**Comment by sergiodxa** [comment]
Yes, totally possible to create routes behind authentication, but that depends on how you implemented your auth.

**Comment by vladmelnikov** [comment]
for example, i have secret page and if in redux  isLogined = false, i want to redirect to '/auth' page. here is that i do now http://prntscr.com/hcl79m, but got error, what should i do ?
