### ISSUE TITLE
Fetch data always from client

### ISSUE THREAD

**Issue by lipp** [zeit/next.js#331]
Is it possible to prevent server side rendering at all (yes, I know this is not isomorphic).

Running locally debug and production execute the constructor and componentDidMount in the client. When deploying with now, this only happens "sometimes".

this [app](https://todos.now.sh/) loads the data (websocket) sometimes, sometimes not.
running locally, everything works fine.

this is the source https://github.com/lipp/next-todos

cheers!

**Comment by nkzawa** [comment]
It can be related to https://github.com/zeit/next.js/pull/326 .
Can you try to deploy with now again and see if it succeeds?

**Comment by lipp** [comment]
Just stumbled upon #326 too :) I'm afk right now. Will give it a try in some hours

**Comment by lipp** [comment]
Yes, re-deploying solved it. THX
