### ISSUE TITLE
router.push({path, query})  exist some bug 

### ISSUE THREAD

**Issue by huyansheng3** [zeit/next.js#3310]
![image](https://user-images.githubusercontent.com/11534583/33005711-04397e58-ce02-11e7-8c22-3532a91f2318.png)

when i surf the http://localhost:80 ，the query is undefined, then i push or replace the query, it will shallowEqual with the old query, but it is undefined ,so something go wrong.

- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
Please provide steps to reproduce the issue.
