### ISSUE TITLE
`filter: drop-shadow` property gets mangled in compiled CSS when using external scoped CSS

### ISSUE THREAD

**Issue by agurtovoy** [zeit/next.js#3312]
In this case, picture is worth 1000 words:
<img width="989" alt="nextjs-css-bug" src="https://user-images.githubusercontent.com/3394202/33049327-275cc750-ce25-11e7-8936-153e4a5acc1b.png">

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
 - Data urls should be left unmodified

## Current Behavior
- `filter: url('data:image/svg+xml;...` gets mangled into `filter: url("http://localhost:3000//'data:image/svg+xml;...`

## Steps to Reproduce (for bugs)
1. Clone https://github.com/agurtovoy/nextjs-css-substitution-bug
2. `npm install`
3. `npm dev`
4. Open http://localhost:3000/ in Firefox, go to dev console's Style Editor tab, select "Show original sources" option to see the compiled CSS:
<img width="886" alt="screen shot 2017-11-20 at 7 06 37 pm" src="https://user-images.githubusercontent.com/3394202/33049500-0ba9afea-ce26-11e7-83eb-3e27bb3f3fc7.png">

## Context
Note that **the issue has more severe impact in production**: a side-effect of this bug is that the browser ignores the rest of the CSS line in question due to unmatched `"`; because in production the CSS is likely to be minimized into a single line of text, that means that all styles following the `filter: drop-shadow` property will be silently ignored. 

You can see that effect in the repo with the reproduce: if you do `npm build && npm start`, you'll see that the "Hello" text loses its red styling.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  4.1.4    |
| node    |   v6.11.1  |
| OS      |    macOS     |
| browser |   any    |

**Comment by timneutkens** [comment]
@giuseppeg could you check this?
