### ISSUE TITLE
apollo / getInitialProps firing w/ Next static export 

### ISSUE THREAD

**Issue by brandonmp** [zeit/next.js#3313]
I'm trying `next export` in an app that uses apollo client to load content from our CMS. When navigating from page to page via <Link> or imperative Router actions w/ prefetching, `getInitialProps` fires on page load & emits a call to my graphql API.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
I'd hoped that the static export process would 'pre-hydrate' the apollo cache such that the data for a route is packed into the HTML/JS of the route payload. When loading a route, then, no calls should be fired to the content API at all (we don't have any dynamic content).

This works fine when fetching the response w/ `curl` or something, and when navigating directly to a route, no calls are fired to our API endpoint (per the Network tab). 

My expectation is that no API calls would be fired when loading subsequent routes accessed via `<Link prefetch>`

## Current Behavior
When clicking a prefetch link (or using the imperative `Router.prefetch`), `getInitialProps` is fired on route transition & I get a 'loading' state.

If I use vanilla `<a>`, the transition happens as expected and no API call is fired. But, there's no prefetching w/ this option, so not really ideal. 

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |  4.14       |
| node    |     8.6     |
| OS      |     win10 w/ WSL    bash |
| browser |     chrome 62    |
| etc     |         |

**Comment by mlecoq** [comment]
Hi, 
I have a similar issue.

I have created a small repo to reproduce it : [https://github.com/mlecoq/nextjs-initialprops-issue](url)

After static export : 
There is two pages : index & details

In details I want to display query param

````
import React from 'react';
import Link from 'next/link';

const Details = ({ name }) => <div>Here is my .... name ! {name}</div>;

Details.getInitialProps = async ({ query: { name } }) => {
  return { name };
};

export default Details;
````

When I click on a link from index (http://localhost) page to details (http://localhost/details/?name=testname), initial props is fired 

but when I reload the page, my param is missing, initial props is not called

**Comment by mfellner** [comment]
I worked around this issue by creating a custom `Link` component that renders a regular `a` tag when the `NEXT_STATIC` environment variable is set:

```js
import { default as NextLink, LinkState } from 'next/link';
import * as React from 'react';

export default class Link extends React.PureComponent<LinkState> {
  private isStatic = () => typeof process !== 'undefined' && process.env.NEXT_STATIC;

  private getHref = () => `${this.props.as || this.props.href}`;

  public render() {
    if (this.isStatic()) {
      return <a href={this.getHref()}>{this.props.children}</a>;
    } else {
      return <NextLink {...this.props} />;
    }
  }
}
```

**next.config.js**
```js
module.exports = {
  webpack: (config, { buildId, dev }) => {
    if (process.env.NEXT_STATIC) {
      config.plugins.push(
        new webpack.DefinePlugin({
          'process.env.NEXT_STATIC': JSON.stringify(true)
        })
      );
    }
    return config;
  }
};
```

**package.json**
```js
{
  "scripts": {
    "export": "NEXT_STATIC=true next build && next export"
  }
}
```

**Comment by brandonmp** [comment]
@mfellner  does this workaround mean the client's sending a request to `next` with every page transition? and/or does this workaround undo any route pre-fetching?

**Comment by mfellner** [comment]
Well it‘s a plain old link so clicking it simply fetches the linked HTML from the server... Since we‘re talking about a static export here I don’t think that’s a big deal but it probably negates some advantages of using Next.js.

I didn’t dig deep into the underlying issue yet so I’m not sure how properly fix it.

**Comment by timneutkens** [comment]
You could use `preval` to inline the cache into the bundles: https://github.com/zeit/next.js/tree/canary/examples/with-babel-macros

**Comment by dimitrinicolas** [comment]
I encountered the same problem, `preval` is a great solution. I would like to inform those who would like to use it to call an API, that it is possible by using [sync-request](https://github.com/ForbesLindesay/sync-request).

```js
const body = preval`
  const syncRequest = require('sync-request');
  const res = syncRequest('GET', 'https://example.com')
  module.exports = res.getBody();
`;
```

**Comment by valerio-battaglia** [comment]
Is there a way to prevent the next link with `prefetch` to fire off once the `getInitialProps` on page transitions in a static build?
