### ISSUE TITLE
Updating custom-server-hapi dependency to Hapi v17.x

### ISSUE THREAD

**Issue by fdidron** [zeit/next.js#3323]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Following the `custom-server-hapi` example with hapi's latest release should work.

## Current Behavior
I came across two issues when trying to implement a custom hapi 17 server.
1. The `server.connection` method was removed in favor of passing the connection props to the server's constructor I fixed it like this:
```es6

//BEFORE

app.prepare()
.then(() => {
  server.connection({ port })
  server.register(pluginOptions)
  .then(() => {
    server.route({
      method: 'GET',
      path: '/{p*}', /* catch all route */
      handler: defaultHandlerWrapper(app)
    })

    server.start().catch(error => {
      console.log('Error starting server')
      console.log(error)
    }).then(() => {
      console.log(`> Ready on http://localhost:${port}`)
    })
  })
})

//AFTER

app.prepare().then(() => {
  const server = new Hapi.Server({ host, port }); 
  server.route({
    method: 'GET',
    path: '/{p*}' /* catch all route */,
    handler: defaultHandlerWrapper(app)
  }); 
  server.start(err => {
    if (err) throw err;
    console.log(`> Ready on http://${host}:${port}`);
  }); 
});
```
2. The defaultHandlerWrapper  was throwing this error `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: x): Cannot set headers after they are sent to the client`. I fixed it like this:

```es6

//BEFORE

const defaultHandlerWrapper = app => {
  const handler = app.getRequestHandler()
  return ({ raw, url }, hapiReply) =>
    handler(raw.req, raw.res, url)
      .then(() => {
        hapiReply.close(false)
      })
}

//AFTER

const { parse } = require('url');
const defaultHandlerWrapper = app => (
  { raw: { req, res }, url },
  hapiReply
) => {
  const parsedUrl = parse(url, true);
  const { pathname, query } = parsedUrl;
  return app.renderToHTML(req, res, pathname, query).then(hapiReply);
};
```

## Context

While following the `custom-server-hapi` example using the latest release of Hapi, I came across the issues described above. I managed to have it working by applying the fixes I attached to this issue. If this all makes sense I'm hapi (pun intended) to send a PR.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.1.4     |
| node    |     9.2.0    |
| OS      |     Linux hal9000 4.13.12-1-ARCH 1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux    |
| hapi |    17.0.2     |

**Comment by zazapeta** [comment]
@fdidron totally agree
