### ISSUE TITLE
How to automatically add hash tag to static assets

### ISSUE THREAD

**Issue by luanwulin** [zeit/next.js#3324]
version : 4.1.4

I've tried webpack config to next.config.js:
`config.module.rules.push(
        {test: /\.(png|jpeg)$/, loader: 'url-loader?limit=8192'}
    )`

but as #1935

it comes error 
`This module was not found:

* /static/enen.png in ./pages?entry

To install it, you can run: npm install --save /static/enen.png
{ Error: Cannot find module '/static/enen.png'
...`

 i want to get the resolvable path of the img, with hash tags,

i know using`/static/` route, i can hadle image easily, but each time i update the image, i have to clear the browser cache

is there any workarounds?
hope your help.

**Comment by sergiodxa** [comment]
We have an example [with-hashed-statics](https://github.com/zeit/next.js/tree/canary/examples/with-hashed-statics) for that.

**Comment by gijo-varghese** [comment]
@sergiodxa that example only works in `npm run start`. Not working after `npm run build && npm run export`
