### ISSUE TITLE
Document's `renderPage` does not return html on error

### ISSUE THREAD

**Issue by martinhorsky** [zeit/next.js#3326]
Before [4.1.3](https://github.com/zeit/next.js/releases/tag/4.1.3) release the `renderPage` from context of Document's `getInitialProps` always returned `html` no matter what. It also happened in the case of error. 

After commit #3142 `html` can be `undefined` which causes issue when you depend on it. Before it was error page (with 500) overlayed with error code - that was ok.

Now, when you use for example `glamorous` or `glamor` with it's server side rendering it will not work. See code: https://github.com/zeit/next.js/blob/20af8cdabece57de21d9cbcdba7361a09bf66fbb/examples/with-glamor/pages/_document.js#L7

Currently when you make syntactic error it will propagate as `glamor` [error](https://github.com/threepointone/glamor/blob/667b480d31b3721a905021b26e1290ce92ca2879/src/server.js#L23) and you need to always reload the page after this happens (hot reloading stops working).

**Comment by janedbal** [comment]
I find this issue very annoying since it **breaks hot reloading**...

**Comment by timneutkens** [comment]
Feel free to add it to the docs.
