### ISSUE TITLE
why dev my commons.js is 404?

### ISSUE THREAD

**Issue by webxzy** [zeit/next.js#3328]
started `npm run dev`, my browser‘s  Console tell me `"GET http://localhost:3001/_next/1511457233403/commons.js" net::ERR_ABORTED` and Network error `404 Not Found`

**Comment by timneutkens** [comment]
Please provide a way to reproduce.

**Comment by accforgit** [comment]
Have you solved it?

**Comment by iTonyYo** [comment]
try this https://github.com/zeit/next.js/issues/2833#issuecomment-324202757
@webxzy @accforgit

**Comment by gingerbenw** [comment]
I experienced a similar situation with my repo today, and found if my git repo had a space in it (which then became replaced with %20 when I cloned it to my machine), all of the static assets get a 404 with `net::ERR_ABORTED`
