### ISSUE TITLE
Consider `next.config.js`

### ISSUE THREAD

**Issue by cameronroe** [zeit/next.js#333]
next is fantastic! However, I'd like to be able to override some configuration, such as the path to  pages (`/pages/index.js -> /src/pages/index.js`). 

Considering, some other people are asking for webpack overrides, would it make sense to have a high-level config that allows for minimal settings. This could also potentially go in `package.json` as a `"next"` option.

```json
"next": {
  "pages_directory": "./src/pages",
  "webpack": {
    "dev": "./webpack.config.js",
    "prod": "./webpack.prod.config.js"
  },
  ...
}
```

Another (related) idea to consider:
- Wrap webpack and make loaders an easy `npm install | yarn add` https://github.com/HenrikJoreteg/hjs-webpack

**Comment by nkzawa** [comment]
We have no plan to support overriding `pages` path fow now, but https://github.com/zeit/next.js/pull/222 is what you want.

**Comment by archae0pteryx** [comment]
In my package.json I simply add my src/ folder to the scripts - such that - ```"dev": "next src/"```
