### ISSUE TITLE
Proposal: Use webpack-chain to allow users mutate the webpack configuration

### ISSUE THREAD

**Issue by d-asensio** [zeit/next.js#3331]
Hi,

Would be nice to be able to modify the webpack configuration using the interface that [webpack-chain](https://github.com/mozilla-neutrino/webpack-chain) provides.

My proposal is to do something like [poi](https://poi.js.org/) does, as is described in [poi>docs>webpack](https://poi.js.org/#/home?id=webpack). Doing it that way the user have the choice of using [webpack-chain](https://github.com/mozilla-neutrino/webpack-chain) or mutate the configuration object directly (which is not the safest way).

@sergiodxa, @liweinan0423, @emattias What do you think about it? Should I submit a PR?

---
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by arunoda** [comment]
@d-asensio I think we are not supposed to go that way.
We allow to customize webpack a bit via our config file, but not 100%.
We may do it at somepoint, but not right now.

So, I'd suggest you to stop doing this right now. (You can do it as project, but we won't support it officially).

**Comment by d-asensio** [comment]
Got it! Thanks for the answer!
