### ISSUE TITLE
Clarify documentation regarding the static folder

### ISSUE THREAD

**Issue by granmoe** [zeit/next.js#3334]
- [ x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Clarify the section in the docs explaining the static folder convention and how it is handled by next. The docs should emphasize that static assets *must* be put in the static dir.

## Current Behavior

I only discovered that static assets *had* to come from the static dir after running into problems and then poring over many GH issues.

**Comment by tvthatsme** [comment]
I'd be happy to add this documentation. Looks like nothing has been done on this issue to date.
