### ISSUE TITLE
Transpile babel from src directory

### ISSUE THREAD

**Issue by cameronroe** [zeit/next.js#334]
Currently babel doesn't transpile directories outside of the ones mentioned in the docs. (at least from what I can see after adding a `styles/` folder)

Also, the structure isn't clear on what folders work. Wouldn't it make sense to have standard `src` and `test` directories and transpile everything in the src according to `next` conventions.

**Comment by rauchg** [comment]
The only convention we want to impose is `pages/`. Transpilation happens through the `import` system. Whatever you `import` from pages is subject to the build pipeline.

`static` is a special directory in that it's _only_ for serving stuff. We won't be doing any special stuff there. You could set up another pipeline for outputting stuff to `static/` for example.

When #222 lands, you'll also be able to extend the babel and webpack config with your custom requirements.
