### ISSUE TITLE
Any way to get list of available pages / routes?

### ISSUE THREAD

**Issue by negamaxi** [zeit/next.js#3351]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

```
pages/
  components/
    component.js
  index.js
  catalog.js
  about.js
```

```javascript
const listOfPages = await getListOfPages()
console.log(listOfPages)
// [ 'index', 'catalog', 'about' ]
```
Is it possible to implement such a thing?

**Comment by brandonmp** [comment]
afaik there's no out-of-the-box way with next. if your structure is that simple, you could just list the directory with `fs`

we have a ton of dynamically generated pages, so we generate a sitemap.xml w/ `next-routes`, [express-sitemap](https://www.npmjs.com/package/express-sitemap), and some code that fetches slugs from our db. 

we then use [sitemapper](https://www.npmjs.com/package/sitemapper)  to turn the xml into a list of urls for tests (though i guess we could just do this while we built the sitemap). 

if you don't have a sitemap (which i'm guessing you don't), there's a tool popular among SEOs called [screaming frog](https://www.screamingfrog.co.uk/xml-sitemap-generator/) that'll crawl your site & build an XML sitemap. free up to 500 pages & fairly reliable / credible

**Comment by timneutkens** [comment]
@negamaxi you can use https://github.com/zeit/next.js/blob/canary/server/build/webpack.js#L53

```js
const pages = await glob('pages/**/*.js', { cwd: __dirname })
```

**Comment by timneutkens** [comment]
@brandonmp feel free to contribute an example for this. I'm pretty sure there's other people wanting that feature 👌
