### ISSUE TITLE
Setting global styles with a _styles.css file 

### ISSUE THREAD

**Issue by malimichael** [zeit/next.js#3353]
Just like we can use `_document.js` to customise the document and `_error.js` to customise the error page is would be great to be able to have `_styles.css` to set global css.

Reading the page on [global styles and layouts](https://github.com/zeit/next.js/wiki/Global-styles-and-layouts) left me feeling that there must be a better solution.

>The easiest way to accomplish it is by using the <style jsx global> tag on a component, specifically with `<Head>`.

Now this is a pretty straight forward process, but you quickly find yourself writing custom components (`<Meta>` in the example) to make sure your styles are applied project wide. It all seems quite unnecessary when all you really wanted to do was set a nice background color.

**Comment by pddigital** [comment]
The idea with styled JSX is to add a <style jsx global> block to your layout component that's used on every page (along with the Head component). You only have to add it in one place.

**Comment by malimichael** [comment]
@pddigital I agree that css-in-js is the best choice for most cases. My issue with this approach is when it comes to global styles and tying them to a specific component. I would like a way to be able to set a style in one place and be done. As soon as I add them to a `<Layout>` component I'm making big assumptions about the future structure of my app

**Comment by pddigital** [comment]
That's sort of the antithesis of CSS-in-JS: to have the styles all in one place... so if you're not into it, don't use Styled JSX then. Just use a link tag and a stylesheet. That's what you want to do, there's nothing stopping you from doing that now!! Or using one of the numerous CSS preprocessors (lots of examples) that are supported.

**Comment by malimichael** [comment]
Found a solution similar to what I was wanting solution https://github.com/zeit/next.js/tree/canary/examples/with-global-stylesheet
