### ISSUE TITLE
main.js IE11 syntax error

### ISSUE THREAD

**Issue by Jinnified** [zeit/next.js#3354]
Hi all

I am using next as dependency to build a react universal rendering site. Just found out a very weird behaviour. In fact, if you check out any examples in this repo, say with-ga or with-redux, run dev locally, and add a simple page with a click button in it.
```
export default class Test extends from React.Component {
  handleClick = () => {
    alert('hellloo');
  }
  render() {
    return <button onClick={this.handleClick}>CLICK ME</button>;
  }
}
```
Then you try to visit this page in any android device's stock browser, the click event won't get fired, anyone had come acrosse this issue before? Is it function in the main.js that captures document event that did something fancy? Please help, I kinda run out of ideas.

**Comment by Jinnified** [comment]
strangely, the boilerplate ran is using nextjs, which does not have the problem: https://github.com/Sly777/ran

but the offical example of next does

**Comment by Jinnified** [comment]
Plus i have tried onTouchStart, onTouchEnd, onTap event instead of onClick evnet, none of these works.

**Comment by Jinnified** [comment]
OK, i think i kinda know where the error comes from now, it looks the main.js has an syntax error, main.js (17547,25)

**Comment by Jinnified** [comment]
related: https://github.com/zeit/next.js/issues/2747
but didn't find a clean solution

**Comment by landvibe** [comment]
same issue here

**Comment by alexdevero** [comment]
The same issue here.

OS: Win 10.
Browser: IE 11.
Next.js: 4.1.4.

**Comment by timneutkens** [comment]
Please try latest next@canary. not sure if it's still an issue.
