### ISSUE TITLE
Expose `useCss` option within config

### ISSUE THREAD

**Issue by lukeed** [zeit/next.js#336]
After #251 and along with #222, we may want to expose an `useCSS` option that defaults to `true` and, at runtime, conditionally imports the `glamor`-based methods and scaffolding in these files.

Doing so will allow for full omission (or as close as possible) of Glamor, should the developer choose the static assets & custom `Head` approach.

These are the files that contain traces of Glamor & will be affected:

* [`pages/_error-debug`](https://github.com/zeit/next.js/blob/c7ba914f527ebcfe084cb0e36946b9dee00d25fa/pages/_error-debug.js)
* [`pages/_error-debug`](https://github.com/zeit/next.js/blob/c7ba914f527ebcfe084cb0e36946b9dee00d25fa/pages/_error.js)
* [`lib/eval-script`](https://github.com/zeit/next.js/blob/master/lib/eval-script.js)
* [`client/next`](https://github.com/zeit/next.js/blob/65c4e1e5bd99c44befa94ab1d66fbada3e8986a1/client/next.js)
* [`client/next-dev`](https://github.com/zeit/next.js/blob/fcd59adea1a5fe34f5a663d7d2cdb8807f0315d4/client/next-dev.js)
* [`server/render`](https://github.com/zeit/next.js/blob/c7ba914f527ebcfe084cb0e36946b9dee00d25fa/server/render.js)
* [`lib/router`](https://github.com/zeit/next.js/blob/c7ba914f527ebcfe084cb0e36946b9dee00d25fa/lib/router.js)

This is a slight piggyback of #319, continued at the bottom.

**Comment by impronunciable** [comment]
Since we moved to `styled-jsx` I think this is not relevant anymore @rauchg ?

**Comment by rauchg** [comment]
Basically, if you don't use `<style jsx>`, the import will never be added, and the client side stuff package should never make it to the bundle. This is also because we moved away from using one global bundle.

**Comment by lukeed** [comment]
Forgot this was open. Was happy to see the `styled-jsx` implementation. Thanks~! 😄
