### ISSUE TITLE
Incorrect first render with multiple `Head` elements in `_document.js`

### ISSUE THREAD

**Issue by agurtovoy** [zeit/next.js#3360]
When (implicitly) using multiple `Head` elements in `_document.js`, e.g.

```jsx
    return (
      <html>
        <Head>
          <title>Test</title>
        </Head>
        <HeadStyle />
      ...
```

where `HeadStyle` is defined as

```jsx
const HeadStyle => <Head><style>{`body { margin: 0; color: red; }`}</style></Head>;
```

... the second `Head`'s content never gets injected into the document **on the first page load of a fresh `now` deployment**. The consequent reloads (including in a clean browser) are fine.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
 - Multiple `Head` elements (implicit and explicit) work reliably (even in `_document.js`)

## Current Behavior
 - Broken page on the first page load of a fresh `now` deployment

## Steps to Reproduce (for bugs)

1. Clone https://github.com/agurtovoy/nextjs-head-bug
2. `now`
3. Open the deployed site, see this (note the black text and the absence of the custom `<style>` element in `<head>`): 
<img width="792" alt="screen shot 2017-11-30 at 4 11 58 pm" src="https://user-images.githubusercontent.com/3394202/33458660-b586c7a0-d5ec-11e7-80f9-bde8b26b30d0.png">

4. Refresh the page, get the expected result (text is red, `<style>` element is there): 
<img width="769" alt="screen shot 2017-11-30 at 4 12 17 pm" src="https://user-images.githubusercontent.com/3394202/33458793-32e1f9e0-d5ed-11e7-8ecb-9d118f340b06.png">

## Context
This reproduces consistently, i.e. every time you push a new deployment, the very first page load will surface the issue. It also reproduces in dev env from time to time, but not consistently.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   4.1.4   |
| node    |   `now`   |
| OS      |  `now`, macOS  |
| browser |   any  |

**Comment by liweinan0423** [comment]
👍 , I think it should relate to the side effect, will do some investigation.

**Comment by agurtovoy** [comment]
I suspected that this could be a built-in limitation of the framework; I worked around the issue along the lines above, but I'd still add a cautionary note to the `_document.js` portion of the docs, since it's non-obvious that components that work inside of pages don't work the same way in the `_document.js`.

**Comment by agurtovoy** [comment]
Also, perhaps we could issue a warning to the console when the "extra" head elements get detected/dropped by the document?

**Comment by liweinan0423** [comment]
To check if there is a `next/head` document in document, it requires walking through the virtual DOM tree of the `Document` component. Not sure if it would degrade the performance. 

We can also modify the rendering logic that allowing using 'next/head` in `Document`.

Anyway, a PR is welcome.

**Comment by timneutkens** [comment]
It's expected that you only use one `<Head>`. Since _document reflects the HTML markup.
