### ISSUE TITLE
Serving static files from .next/static as fallback

### ISSUE THREAD

**Issue by sheerun** [zeit/next.js#3366]
Here's the idea: allow loaders to generate custom static content (e.g. compressed images with hashed filenames or preprocessed css files), and put them inside `.next/static` directory. next.js would serve this directory as a fallback of usual `static` directory in development, and for production build would merge these directories into `out/static`.

What do you think?

**Comment by timneutkens** [comment]
Haha this is exactly what I implemented with `.next/static` => `/_next/static` for Next v5. Without having seen this issue 😄
