### ISSUE TITLE
Pass variable to _document.js from server.js

### ISSUE THREAD

**Issue by blackbing** [zeit/next.js#3367]
Can I pass some variable from create `next`? for example 
```
const app = next({ dev: isDev, customProps: { GA_ID: 'UA_XXXXXX' });
```
then I can get this `GA_ID` variable in _document.js and render it.

I know universal-config provide another way to handle it, but it will be replaced in the build time. If I have several different environment. I have to build by different config. So I hope I can pass variable to render _document.js

related issue is https://github.com/zeit/next.js/issues/159 but as I mentioned above, universal-config will replace variable in the build time instead of run time. so I hope there is a better way to do that.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by pddigital** [comment]
if that's the google analytics ID, you can initialize Google Analytics in the custom document using dangerouslySet html in a script tag and then use router events from the layout component to handle page events... you don't need to pass the GA ID to the client from the document.... if properly initialized there you should be able to use it's functions it within ComponentDidMount or a function on the client...

**Comment by blackbing** [comment]
@timneutkens thanks for your example. I understand you export env config to `windows.__ENV__`. 
I use https://github.com/mozilla/node-convict to configure my env variable. Consider this example code. 
```
var convict = require('convict');

// Define a schema
var config = convict({
  API_URL: {
    doc: "API_URL.",
    format: String,
    default: "127.0.0.1",
    env: "API_URL",
  },
});
// Load environment dependent configuration
var env = config.get('env');
config.loadFile('./config/' + env + '.json');

// Perform validation
config.validate({allowed: 'strict'});
```
It loads the file and do some validate. however it cannot be executed on client side. The env config should be decided on server side, and I can decided what I should export to client side. So I am curious about if I make this variable from create next.
```
const app = next({ dev: isDev, customProps: { GA_ID: 'UA_XXXXXX' });
```

Is it possible?

**Comment by timneutkens** [comment]
@blackbing `_document.js` is executed only on the server. Only the API_URL environment variable is exposed https://github.com/zeit/next.js/pull/3371/files#diff-bc9a93f185c52580e4adb7607bc35ddaR5. You can put the convict code in _document.js and it'll work just fine 👍

**Comment by misuzu** [comment]
@timneutkens 
When running like this it does not work properly:
```bash
npm run build
API_URL='https://example.com' npm run start
```
This is needed when building on CI server and running resulting build on many environments with different configuration.

**Comment by timneutkens** [comment]
Use this: https://github.com/zeit/next.js#exposing-configuration-to-the-server--client-side
