### ISSUE TITLE
 Webpack config does not get loaded when specifying a custom dir in CLI commands

### ISSUE THREAD

**Issue by Inkdpixels** [zeit/next.js#3379]
If you execute e.g. `next build src` and hold a `next.config.js` file in the root of the package, the config does not get properly/consistency loaded. 

I traced this bug into the `server/config.js` and added logs to the `getConfig` function, it seems that once the config get's loaded properly from the root (`path === "usr/src/app/"`), and once the config does not get loaded since it gets called with (`path === "usr/src/app/src/"`). The current implementation only looks for the file in the given directory, I would propose to traverse the tree up until it find's the `next.config.js` using sindresorhus [find-up package](https://github.com/sindresorhus/find-up)

## Expected Behavior
Next.js should load the `next.config.js` config consistently, no matter if a custom dir was specified via the CLI or not.

## Current Behavior
Next.js does not find/resolve the config inconsistently.

## Steps to Reproduce (for bugs)
1. Move your `pages` folder into `src/` 
2. Create a `next.config.js` in the root containing a webpack option which just logs `webpack config loaded`
3. Execute `next build src`
4. Log will not be printed / webpack config will not be loaded/merged.

## Context
I just tried out to integrate next.js into a scaffold, in which the pages folder is located within `src/`, so I execute e.g. `next build src` to build the application. Since I use newer NodeJS language features, and the current internally used UglifyJS webpack plugin conflicts with this as specified in #1195, I created a `next.config.js` containing a webpack option in the root of the repository and tried to filter out the internal uglify plugin.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | latest |
| node    | LTS (8.9.1) |
| OS      | Linux |
| browser | - |
| etc     | - |

**Comment by nexdrew** [comment]
Maybe this is a silly question, but why not put `next.config.js` into the `src` dir as well?

**Comment by Inkdpixels** [comment]
@nexdrew For sure would be a quick solution! For me this issue it is about consistency and it is something that is pretty easy to fix (I also created a PR to solve this issue). I don't like to put framework/library configuration into my `src` folder, but keep them consistently at one level where the `.babelrc`, `package.json`, `webpack-config.js` and so on are placed.
