### ISSUE TITLE
Re-generate .next folder

### ISSUE THREAD

**Issue by pthphap** [zeit/next.js#3382]
Hello, everyone. I was running "npm run build" command" 

Then I hit to this error:

>  Error: ENOENT: no such file or directory, open '/opt/www/0d1f7f3c-746b-401e-9bef-411086e6c452/.next/app.js'
>     at Error (native)
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/opt/www/0d1f7f3c-746b-401e-9bef-411086e6c452/.next/app.js' }
The folder is created automatically, but there is not files in it.

So I thought I just had to delete .next folder and run it again so I did, but after I did that.

I still get that error and more I lost .next as well.

How can I fix that error and have my .next folder back? 

This bugs has reported in https://github.com/zeit/next.js/issues/2293
but it seems like no solution.

I have a custom webpack file:
```
const UglifyJSPlugin = require('uglifyjs-webpack-plugin')
module.exports = {
    webpack: (config) => {
        config.node = {
            fs: 'empty'
        }
        config.loader = {
            test: /\.es6$/,
            exclude: /node_modules/,
            loader: 'babel',
            query: {
                presets: ['es2015']
            }
        }
        config.plugins = [
            new UglifyJSPlugin()
        ]
        return config
    }
}
```
Thank you
## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  3.2.2       |
| webpack  | 3.8.1         |

**Comment by Soundvessel** [comment]
I was having the same issue on Windows 10 working on the Learn NextJS course (https://learnnextjs.com/basics/deploying-a-nextjs-app/run-two-instances) and using `npm run build`.

I got past it by opening Windows Task Manager and closing 2 instances of node.js. Ran `npm install` after then `npm run build` worked without issue.
