### ISSUE TITLE
examples/with-react-intl TypeError: Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by soulmachine** [zeit/next.js#3386]
## Expected Behavior

For the example [examples/with-react-intl/](https://github.com/zeit/next.js/tree/canary/examples/with-react-intl/), the first time the page loads successfully, then if you click links on the page, it should work normally without throwing out error.

## Current Behavior

Actually if you click links it will crash with the following error:

```
Cannot read property 'locale' of undefined
TypeError: Cannot read property 'locale' of undefined
    at Function._callee$ (http://localhost:3000/_next/1512390186142/page/:15950:90)
    at tryCatch (http://localhost:3000/_next/1512390186142/main.js:5512:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/_next/1512390186142/main.js:5746:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/_next/1512390186142/main.js:5564:21)
    at step (http://localhost:3000/_next/1512390186142/main.js:1598:30)
    at http://localhost:3000/_next/1512390186142/main.js:1609:13
    at <anonymous>
```

## Steps to Reproduce (for bugs)

1. Run `npm run dev` and go to <http://localhost:3000/>
2. Click either the `home` link or `about` link

## Context

In line 26 of `PageWithIntl.js`:

    const {locale, messages} = req || window.__NEXT_DATA__.props.initialProps

When a page is loaded from links, there is no SSR happening, somehow both `req` and `window.__NEXT_DATA__.props.initialProps` are `undefined`, this is why the page will crash.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   4.1.4  |
| node    |   v8.9.1      |
| OS      |   macOS High Sierra      |
| browser |    Chrome Version 62.0.3202.94 (Official Build) (64-bit)    |

**Comment by soulmachine** [comment]
Fixed this issue with this PR <https://github.com/zeit/next.js/pull/3392>

**Comment by julmot** [comment]
I have a similar error, just cloned installed and ran npm run dev, then clicked on "About":

![topic](https://user-images.githubusercontent.com/8310677/35725525-eea2dc1c-0801-11e8-8e71-6b9646359f1f.png)

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/pull/3392
