### ISSUE TITLE
How to debug with customized koa backend?

### ISSUE THREAD

**Issue by jchbh-duplicate** [zeit/next.js#3388]
I don't found anything about debug backend with dev mode. 

Now I can only run `npm run build`, and `npm run start` to debug the app.
It is very slowly and inefficiency. 

Is there any way to run `npm run dev` with customized backend enabled? 
I test and find `npm run dev` not start customized backend as expect.

**Comment by pukapukan** [comment]
https://nodejs.org/en/docs/inspector/

Run your app with --inspect flag and use chrome://inspect to connect Chrome to your app to debug backend logic

**Comment by benatkin** [comment]
In the `custom-koa-server` example, [package.json](https://github.com/zeit/next.js/blob/canary/examples/custom-server-koa/package.json#L5) is modified to start it by calling `node server.js`. You should be able to add `--inspect` to that.
