### ISSUE TITLE
Property 'getInitialProps' does not exist on type 'typeof default'.

### ISSUE THREAD

**Issue by soulmachine** [zeit/next.js#3396]
I'm trying to convert the example [examples/with-react-intl/](https://github.com/zeit/next.js/tree/canary/examples/with-react-intl) to TypeScript, but I bump into the error at line 7 of `pages/_document.js`:

    Property 'getInitialProps' does not exist on type 'typeof default'.

In the last line of `node_modules/@types/next/document.d.ts`, the class `Document` is exported as default, thus it is impossible to use module argumentation to add a new method `getInitialProps()` to the `Document` class.

How to work around this? Any ideas? Thanks.

**Comment by thanmathieu** [comment]
I have the same issue.

**Comment by timneutkens** [comment]
Sounds like the typescript types require getInitialProps instead of making it optional. We don't keep they're community made and contributed to https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by soulmachine** [comment]
@timneutkens Yes, it's related to typescript typings, seems I have to wait for somebody to fix it since I'm not familiar with typings definitions.

**Comment by soulmachine** [comment]
Posted a question on Stackoverflow <https://stackoverflow.com/questions/48037609/rewrite-the-next-js-example-with-react-intl-in-typescript/>
