### ISSUE TITLE
Fragments not supported in <Head />

### ISSUE THREAD

**Issue by tusbar** [zeit/next.js#3399]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Considering the following snippet:

```jsx
<Head>
  {title ? (
    <React.Fragment>
      <title>{title} | Cool site</title>
      <meta property='og:title' content={title} />
    </React.Fragment>
  ) : (
    <title>Cool site</title>
  )}

  {/* … */}
</Head>
```

When `title` is defined, I would expect `<title>foo | Cool site</tite>` to be rendered.

## Current Behavior

An empty `<title />` is rendered.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.1.4     |
| node    |   8.9.1      |

**Comment by loris** [comment]
Confirm same behavior, it seems to be only emptying the `title` tag. Other type of head tags (`meta`, `link`, etc.) are correctly rendered.

**Comment by arunoda** [comment]
Actually what's happening inside `<Head/>` is quite different than other elements. We read elements(direct children) inside in the `Head` add it to the actual head.

In this case, we only see the `React.Fragment` but not the content inside it.

So, with conditional logic, you can as have as many as `<Head>` tags rather implementing logic inside it.

But if someone willing to add `React.Fragment` support, we are super glad to take it.

**Comment by Sekhmet** [comment]
Hey,
I was super excited to start contributing and decided to try to solve this issue. I have come up with following change:
```diff
diff --git a/lib/head.js b/lib/head.js
index 3473332..0457f3a 100644
--- a/lib/head.js
+++ b/lib/head.js
@@ -21,6 +21,12 @@ function reduceComponents (components) {
   .map((c) => c.props.children)
   .map((children) => React.Children.toArray(children))
   .reduce((a, b) => a.concat(b), [])
+  .reduce((a, b) => {
+    if (React.Fragment && b.type === React.Fragment) {
+      return a.concat(React.Children.toArray(b.props.children));
+    }
+    return a.concat(b);
+  }, [])
   .reverse()
   .concat(...defaultHead())
   .filter((c) => !!c)
```

This makes code posted by tusbar work without problems. This doesn't change current logic much - it's still reading direct children (so no nested Fragments).

Is it kind of solution you are looking for? If it is I'm happy to take this issue and create PR.
cc @arunoda

**Comment by tusbar** [comment]
@Sekhmet that looks good. :) Open that PR, it’ll get more visibility.
