### ISSUE TITLE
Create example using custom charset

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#3401]
Continuation of https://github.com/zeit/next.js/pull/3333

Here's an example component with a different charset.

```js
// pages/index.js
import React from 'react'
import Head from 'next/head'
export default class extends React.Component {
  static async getInitialProps ({res}) {
    if (res) {
      res.setHeader('Content-Type', 'text/html; charset=iso-8859-2')
    }
    return {}
  }

  render () {
    return <div>
        <Head>
            <meta charSet="iso-8859-2" class="next-head"/>
        </Head> 
    </div>
  }
}
```

You can also avoid doing it in getInitialProps using a custom server.

**Comment by ppatel221** [comment]
Hey if no one is working on this, Id like to get started!

**Comment by timneutkens** [comment]
@ppatel221 feel free to!

**Comment by arunoda** [comment]
Closing with this: https://github.com/zeit/next.js/pull/3697#issuecomment-363330644
