### ISSUE TITLE
Dynamic imports & next export

### ISSUE THREAD

**Issue by OutThisLife** [zeit/next.js#3415]
I'm aware this may be edge-case or useless to most people, but I'm using an API to figure out which template to use in index.js sort of like -

```js
const Templates = {
  Home: dynamic(import('pages/home')),
  Sample: dynamic(import('pages/sample'))
}

const slug = props.url.asPath || props.template || props.url.query.slug
const Dummy = Templates[ucfirst(slug.replace(/\//g, '') || 'home')]

return <Dummy {...props } />
```

In order to get this to work with `next export`, it's just as simple as:

```js
exportPathMap () {
  return {
    '/': { page: '/' },
    '/sample': { page: '/' }
  }
}
```

This works perfectly fine. However, I would expect `next export` to _not_ load the chunk with the HTML..?

Of course the dynamic imports render on SSR just fine, therefor there's no need to asynchronously load this chunk right? If the export is supposed to be 100% static html/css.

`<link rel="preload" href="/_next/<BUILDID>/webpack/chunks/app_pages_sample_<CHUNKID>.js" as="script"/>` shouldn't even exist AFAIK.

What am I missing?

**Comment by OutThisLife** [comment]
I suppose it could be trying to ensure that client-side JS comes with it, but I guess I would expect it to be bundled elsewhere.

**Comment by arunoda** [comment]
The idea of Next.js export is to keep it's SPA nature even exported. For an example, supporting client side navigations.

That's why you get this behaviour.
If you don't need JS support, try using our [custom document ](https://github.com/zeit/next.js#custom-document)support to get rid of them.

**Comment by OutThisLife** [comment]
Gotcha, that makes sense. Thanks!
