### ISSUE TITLE
Next's build resolves packages to nextNodeModulesDir before 'node_modules'

### ISSUE THREAD

**Issue by masad-frost** [zeit/next.js#3418]
Requiring a package in bundle e.g. `import camelcase from 'camelcase'` resolves to `<root_dir>/node_modules/next/node_modules/camelcase` before `<root_dir>/node_modules`.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Requiring a package that's a direct dependency resolves project's `node_modules`

## Current Behavior
Webpack looks in next's nested node_modules

## Steps to Reproduce (for bugs)

1. `yarn add camelcase@3.0.0` 
2.  add import to a `pages/index.js` `import camelcase from 'camelcase'`
3. `next build`
4. Build bundles package/chunk using next's `camelcase` which is version 4
   1. Which leads to an uglifyJS error because camelcase v4 is published as es2015.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     4.2    |
| node    |     8    |

Note: I know `camelcase` is not a browser module, but it's just an example.

**Comment by arunoda** [comment]
Hmm. This seems like an issue.
But I'm not sure how to fix it.

Try using https://webpack.js.org/configuration/resolve/
That might help.

**Comment by masad-frost** [comment]
Is it too bad if I swap [these two lines](https://github.com/zeit/next.js/blob/e2bcb039cf1a4d9bb605655b0282026a5ab7ca41/server/build/webpack.js#L344-L345)?

Maybe users should be warned at build with the list of modules that exist in both `node_modules` and have a version discrepancy.

**Comment by arunoda** [comment]
@masad-frost Yes. That's a good point.
But if we do that, it might fail Next.js due to a incompatible version installed inside user's `node_modules.`
(You can always override that with our custom config)

But I got your point.

And I have no idea for a proper way to warn users. (With efficiency in mind)
