### ISSUE TITLE
Babel doesn't compile node_modules

### ISSUE THREAD

**Issue by kanjielu** [zeit/next.js#3421]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

I notice that next.js ignores the node_modules directory from being compiled by babel. It will cause some errors in old version browsers.

For example, after `npm run dev` in example of [data-fetch](https://github.com/zeit/next.js/tree/canary/examples/data-fetch), it would generate the following code in .next/main.js

```javascript
/* 347 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

const ansiRegex = __webpack_require__(348);

module.exports = input => typeof input === 'string' ? input.replace(ansiRegex(), '') : input;


/***/ }),
/* 348 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


module.exports = () => {
	const pattern = [
		'[\\u001B\\u009B][[\\]()#;?]*(?:(?:(?:[a-zA-Z\\d]*(?:;[a-zA-Z\\d]*)*)?\\u0007)',
		'(?:(?:\\d{1,4}(?:;\\d{0,4})*)?[\\dA-PRZcf-ntqry=><~]))'
	].join('|');

	return new RegExp(pattern, 'g');
};
```

These code is generated from `strip-ansi`, which is one of the dependencies of next.js.
However, Chrome browsers whose version < 41 would throw error of "SyntaxError: Use of const in strict mode" according to [caniuse](https://caniuse.com/#search=const). In addition, a few old browsers don't recogize `arrow functions`. 

How can I make babel compile node_modules so that my project can run on these old version browsers?

**Comment by PrudviGali** [comment]
Babel does not compile node_modules. You should raise this issue with (strip-ansi)[https://github.com/chalk/strip-ansi] . They should provide a provide a compiled version.

**Comment by arunoda** [comment]
I think this is intentional.
And for this specific issue we are dealing it here: https://github.com/zeit/next.js/pull/3403
