### ISSUE TITLE
It is posible to customize the generated chunks?

### ISSUE THREAD

**Issue by batusai513** [zeit/next.js#3429]
We are building an app with several dependencies being used in several pages, the thing is when building the application for production, some dependencies are being used in several of the chunks generated, here you can see how it looks:
<img width="1280" alt="screen shot 2017-12-08 at 3 49 34 pm" src="https://user-images.githubusercontent.com/996671/33784872-873b1dc0-dc30-11e7-94c9-b0e1ffeda64d.png">

In this case draft-js, redux-form among others are repeated in many pages across the app.

I wanted to know if it is possible to configure webpack to extract the repeated dependencies into a separated normal chunk to decrease the size of the pages.

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     4.1.4    |

**Comment by arunoda** [comment]
The easiest solution is to use [dynamic import](https://github.com/zeit/next.js#dynamic-import) to import `redux-form`. 
So, It'll move into a it's own chunk.

**Comment by timneutkens** [comment]
@batusai513 could you make a sample repository, we're very curious to investigate this.

**Comment by batusai513** [comment]
@timneutkens Sure, I'll work on that.

**Comment by sheerun** [comment]
@arunoda Are dynamic imports prefetched with script tags? If not they are useless in this use case as they'd force 2 roundtrips for each page, one for main js, and then one for draft.js..

Ideally I'd be able to configure next.js so it splits draft.js and other dependencies into separate chunk, and serves them in script tags on each page that uses it, like so:

```
<script src="./page-1.js"></script>
<script src="./draft-and-heavy-plugins.js"></script>
```


```
<script src="./page-2.js"></script>
<script src="./draft-and-heavy-plugins.js"></script>
```

```
<script src="./page-3.js"></script>
<script src="./draft-and-heavy-plugins.js"></script>
```

**Comment by batusai513** [comment]
@arunoda @timneutkens I was wishing to do something like the first example of this [article](https://medium.com/webpack/webpack-bits-getting-the-most-out-of-the-commonschunkplugin-ab389e5f318), something that i've done before using just webpack.

As soon as i have a working example I'll post it in here

**Comment by batusai513** [comment]
This was mostly because a misunderstanding of how next pages worked, we've solved it, thanks for your responses.

**Comment by illogikal** [comment]
How did you solve this?
