### ISSUE TITLE
Configuring on demand entries and ssr-caching caching example

### ISSUE THREAD

**Issue by sheerun** [zeit/next.js#3430]
Isn't SSR-caching example superfluous given that next has this feature built in?

https://github.com/zeit/next.js/#configuring-the-ondemandentries

What is the difference between configuring onDemandEntries and custom ssr caching as in the  SSR-caching example? https://github.com/zeit/next.js/tree/canary/examples/ssr-caching

Is it good idea to change ssr-caching example so it uses ondemandentries instead?

**Comment by sergiodxa** [comment]
They are different thing, on demand entries is a dev only features which let you only build the page your working on (based on what page to you have open in the browser), this make the hot reload remains fast even if the project is too large.

The cache example is to avoid SSR if the HTML is already in cache.

**Comment by sheerun** [comment]
I've sent PR that clarifies it. But I think this should be built-in feature.
