### ISSUE TITLE
When using styled-jsx on a page this error is thrown: "Cannot read property 'start' of undefined"

### ISSUE THREAD

**Issue by valnub** [zeit/next.js#3431]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

I've been using styled-jsx in some components and it worked well. Now I tried using it directly in a page like this:

**product.js**

```jsx
import React from 'react';
import Page from './page';
import HeadInclude from './headinc';

class ProductPage extends Page {
  render() {
    return (
      <div>
        <HeadInclude />
        <h2>bleh</h2>
        <style jsx>{`
          h2 {
            color: blue;
          }
        `}
        </style>
      </div>
    );
  }
}

export default ProductPage;
```

**page.js**

```jsx
import { Component } from 'react';
import Local from '../src/local';

class Page extends Component {
  static getInitialProps() {
    return {
      local: Local.de_DE,
    };
  }
}

export default Page;
```

If I open `localhost:3000/product` I suddenly get this error:

```console
Error in /pages/product.js?entry
Module build failed: TypeError: /pages/product.js?entry: Cannot read property 'start' of undefined
    at processCss (/node_modules/next/node_modules/styled-jsx/dist/_utils.js:447:49)
    at PluginPass.exit (/node_modules/next/node_modules/styled-jsx/dist/babel.js:232:51)
    at newFn (/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/node_modules/babel-traverse/lib/index.js:114:17)
```

What's wrong? Everything else was working perfectly fine until I added `<style jsx>`. Also, I noticed that if I remove "jsx" so it only reads `<style>` it works as well but styles aren't scoped then. From what I understand there is an issue with babel but I don't quite understand what?

I'm using:

- npm 5.3.0
- node 8.2.1
- next 4.1.4
- react 16.1

**Comment by valnub** [comment]
Dang. I noticed that the style has to be inside the h2:

        <h2>bleh
          <style jsx>{`
            h2 {
              color: blue;
            }
          `}
          </style>
        </h2>

Now it works :D

**Comment by Leland-Kwong** [comment]
Actually, I've been getting those errors as well. For example, this will trigger an error:

```javascript
export default () => {
  return (
    <div className='Spinner'>
      <style jsx>{/* @css */`
        .Spinner {
          display: inline-block;
        }
      `}</style>
      <div className='Inner'>
        <style jsx>{/* @css */`
          .Inner {
            position: 'absolute';
          }
        `}</style>          
      </div>
    </div>
  );
};
```

**Comment by valnub** [comment]
@Leland-Kwong I tried [Radium](https://github.com/FormidableLabs/radium) now instead of styled-jsx. Works quite well so far.

**Comment by valnub** [comment]
@Leland-Kwong In your case the problem is that nested styles are currently not supported by styled-jsx, see: https://github.com/zeit/styled-jsx/issues/365 :-(
