### ISSUE TITLE
Dynamic Imports don't respect custom BUILD_ID, the uuid used at build time is hardcoded

### ISSUE THREAD

**Issue by unregistered** [zeit/next.js#3446]
Based on the [guide in the wiki](https://github.com/zeit/next.js/wiki/Deployment#hot-fix) I assumed it would be safe to override the build id by changing that file. However, any use of dynamic imports `import('.../....')` will still use the old build id, which is hardcoded in the generated webpack bundle. 

This results in a 404.

One solution might be to allow overriding the buildId at build time instead of afterwards: 

https://github.com/zeit/next.js/blob/52ccc14059673508803f96ef1c74eecdf27fe096/server/build/index.js#L10-L31

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    3.0.6    |
| node    |     7.10    |
| OS      |      Mac OS X   |
| browser |     All    |

**Comment by jayaram171992** [comment]
Closing https://github.com/zeit/next.js/issues/3402 because this issue is more up-to-date

**Comment by timneutkens** [comment]
Dynamic imports now use file hashing
