### ISSUE TITLE
[docs] Document config.clientBootstrap

### ISSUE THREAD

**Issue by harriha** [zeit/next.js#3449]
The [recently added config option](https://github.com/zeit/next.js/commit/6e44cdef5f877a85d9015002d3f77640c0e1ba21#diff-0f2f34c098f5954f99483c9bd61e439dR46) for adding a custom bootstrap file to the main bundle is mentioned only in comments here and there so far, so thought to turn this into an actual task for clarity.

References:

- https://github.com/zeit/next.js/issues/2969#issuecomment-348158039
- https://github.com/zeit/next.js/issues/1556#issuecomment-346933034

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I'd expect to

- find `config.clientBootstrap` documented in main README
- find an example showing how to use this (suggestion: use something common like babel-polyfill in the example to help issues such as #2468) 

As a side note, it seems that there are no tests exercising this config option, but perhaps that can be seen as a different task than these docs.

## Notes

Something to be aware of with this config (and the docs): sadly this option does not help with everything. I tried to add EventSource polyfill for webpack-hot-middleware to make the dev mode work in IE11, but this custom bootstrap is injected too late and thus it does not help with this kind of polyfilling.

**Comment by timneutkens** [comment]
@arunoda made an example internally, he can commit it to the repository 👍

**Comment by designspin** [comment]
I'm trying to run a polyfill for intersection-observer using the clientBootstrap:

```
async function loadPolyfills() {
	const polyfills = [];
	console.log("Running polyfills!");
	if(!supportsIntersectionObserver()) {
		polyfills.push(import('intersection-observer'))
	}

	let all = await Promise.all(polyfills);
	return all;
}

function supportsIntersectionObserver() {
	return (
		'IntersectionObserver' in global &&
		'IntersectionObserverEntry' in global &&
		'intersectionRatio' in IntersectionObserverEntry.prototype
	)
}

loadPolyfills().then((polyfills) => {
	console.log(polyfills);
});

```
Unfortunately my react code is starting before the polyfill loads. What am I missing here?

**Comment by catuskeeper** [comment]
@timneutkens 
React requires `Set`, `Map` and `Object.assign` to fit for IE 9 and IE 10, but in a Next.js project I can't find a proper place to import these polyfills from core-js. Adding them in the `clientBootstrap` config does not solve this problem because the Set, Map is used before these injected `clientBootstrap`.
If there is any solution to inject some local modules BEFORE React is executed in Next.js plz tell me.

**Comment by arunoda** [comment]
We might remove `clientBootstrap` feature from Next.js in the future.
So instead use this: https://github.com/zeit/next.js/pull/3568

It's the same as `clientBootstrap`, but just using webpack config.

**Comment by arunoda** [comment]
@designspin your issue is because of the promise usage.
Try to load polyfills using NPM as shown in the ^^ mentioned example.
If not, start a new issue.
