### ISSUE TITLE
Dev server breaks on broken module dependencies, requires restart

### ISSUE THREAD

**Issue by dbo** [zeit/next.js#345]
The dev server does not recover from broken module dependencies, a restart of the server is required.

This might be related to issue #294, similar scenario:
```js
import React from 'react'
import Child from './child'
export default () => <div>hello <Child /></div>
```
child.js (outside of pages directory)
```js
import Child from './child2'
export default Child
```
child2.js (outside of pages directory)
```js
import React from 'react'
export default () => <div>world</div>
```
In case you once break the dependencies, e.g.
- changing the import statement in `child.js` to e.g. `import Child from './child2typo'`
- or temporarily renaming `child2.js`
there's no way to recover the dev server other than restarting it.

**Comment by timneutkens** [comment]
Looks like this issue was fixed 👍
