### ISSUE TITLE
Errors when navigating an exported site

### ISSUE THREAD

**Issue by maciej-ka** [zeit/next.js#3454]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

No errors

## Current Behavior

Clicking on `Dynamic1` or `Dynamic2` blinks an error before a correct page is displayed
Clicking on `Level1 home page` or `Level1 about` page displays "Not Found"
Clicking on `WithHash` displays An unexpected error has occured

## Steps to Reproduce (for bugs)

Run an project from test/integration/static, for example by:
1. `cp -r test/integration/static /tmp/next-client`
2. `cd /tmp/next-client`
3.  `yarn init -y`
4.  `yarn add next react react-dom`
5. `next build && next export && serve out`
6. visit `localhost:5000` and click links described in Current Behaviour

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  4.3.0-canary.1  |
| node    | v8.2.1        |
| OS      | 10.11.2 El Capitan        |
| browser |  Chrome 62.0.3202.94       |
| etc     |         |

**Comment by techandmedia** [comment]
Hi guys, I am still having this problem when exporting my app to html; switching between pages/link doesn't work properly on both the development and production server.
Have a look at my website: demo-ssr.subarnanto.com

Can you advise please?

**Comment by techandmedia** [comment]
I just add a 'padding' inside a body tag just to prevent to error:
`    <style jsx global>{``body {
      padding: 1px;`
    }`}</style>`

Please update the repository so other people can avoid the error. Sorry for my English.
