### ISSUE TITLE
Single page routing with express-history-api-fallback

### ISSUE THREAD

**Issue by corysimmons** [zeit/next.js#3464]
```js
var fallback = require(`express-history-api-fallback`)
var express = require(`express`)
var app = express()
var root = `${__dirname}/out`
app.use(express.static(root))
app.use(fallback(`index.html`, { root: root }))
app.listen(1337, console.log(`http://localhost:1337`))
```

```
$ node_modules/.bin/next build
$ node_modules/.bin/next export
$ node ./server.js
```

- Index works fine.
- When I click links they take me to the correct pages.
- When I try to travel directly to a link, it just takes me to index.html and doesn't route me to the correct page.

How can I fix this?

**Comment by corysimmons** [comment]
Seems to work fine with `$ now` but I'm trying to use Netlify for frontend stuff and zeit/now for Node APIs.

**Comment by corysimmons** [comment]
Never mind, sorry, figured it out. I had forgotten about configuring routes in `next.config.js`.

I'll close this, but anyone care to explain why `next export` doesn't automatically assume:

```js
module.exports = {
  exportPathMap: function () {
    return {
      '/': { page: `/` },                              // Routes
      '/about': { page: `/about` },           // match
      '/portfolio': { page: `/portfolio` },  // by
      '/contact': { page: `/contact` },     // default?
    }
  },
}
```

**Comment by sergiodxa** [comment]
@corysimmons you need to be explicitly about what do you want to export and exactly what pages and query use for them.

**Comment by corysimmons** [comment]
@sergiodxa I know now, but as a feature request I think `next export` should detect if `./pages/x.js` exists and map it to `'x': { page: '/x' }` automatically—by default, with a way to override it.

There is rarely a time when I need params, or don't want the filename to match my path. 🤷‍♂️
