### ISSUE TITLE
How to minimize css when import to comoponent?

### ISSUE THREAD

**Issue by tanobi92** [zeit/next.js#3465]
I write a file css like:
```
body{
     color: red;
}
```

and I import to component,  use [example-with-global-stylesheet](https://github.com/zeit/next.js/tree/canary/examples/with-global-stylesheett), or [example-with-global-stylesheet-simple](https://github.com/zeit/next.js/tree/canary/examples/with-global-stylesheet-simple), but it not minimize the css that I write.
How to minimize css?
Thanks!

**Comment by arefaslani** [comment]
IMO best way to use global stylesheets is to put them in the `static` directory and link them in the `_document.js` as you link normal css files. Then you can install `postcss-cli` as a dependency and add a script to watch and process your css files. Postcss has a large set of plugins such as `cssnano`.
