### ISSUE TITLE
Need advice, Immutable toJS() performa with Redux + Reselect + Saga

### ISSUE THREAD

**Issue by zalabinc** [zeit/next.js#3474]
what I do is create a custom intregation nextjs with immutable, redux, saga, and reselect.
all I need is advice how to use immutableJS properly.
because after I find out, maybe **immutable toJS requires 'enormous energy' to render.**
but anyway, toJS I really need on selector files, because this is very easy for me in splitting data
I'm also looking into how to make toJS work inside the HOC groove

https://github.com/zalabinc/nextjs-boilerpate/blob/master/app/containers/HomePage/selectors.js
https://github.com/zalabinc/nextjs-boilerpate/blob/master/app/utils/configureStore.js
https://redux.js.org/docs/recipes/UsingImmutableJS.html

**Comment by JustasPolis** [comment]
That is redux/immutableJs issue/question, it's not related to next.js anyhow. Not trying to be a dick, just want to help maintain issues related to next.js ;). gl
