### ISSUE TITLE
Improve error template

### ISSUE THREAD

**Issue by leo** [zeit/next.js#3475]
We've internally workout a slight improvement to the error template:

**BEFORE:**

![screen shot 2017-12-19 at 02 35 54](https://user-images.githubusercontent.com/6170607/34136248-5c21a6f8-e465-11e7-9a40-5fe3b6bcef8b.png)

**AFTER:**

![screen shot 2017-12-19 at 02 35 47](https://user-images.githubusercontent.com/6170607/34136253-622c2000-e465-11e7-94de-436faae6fff7.png)

It's now slightly better looking, responsive and has no `.` anymore.

Please take the styling AND markup from [here](https://gist.github.com/leo/e2a9b710eae877330dd424797b14300b). The code should be as similar as possible to what you can find in this file, so that it's in sync with all of the other parts/errors of the ZEIT ecosystem.

Ignore the CSS selectors that aren't used in the markup, please!

VERY IMPORTANT: Don't adjust the existing error page style trying to match the style of the new one. Copy the style over from the new gist instead!

**Comment by jaydenseric** [comment]
IMO these error messages are sentences (not sentence "fragments" or titles) and should have sentence-correct end punctuation. Almost all UI guidelines recommend end punctuation for alert messages:

- https://ux.stackexchange.com/questions/18671/periods-at-the-end-of-a-sentence-in-alert-message
- https://developer.apple.com/tvos/human-interface-guidelines/interface-elements/alerts#alert-titles-and-messages
- https://msdn.microsoft.com/en-us/library/windows/desktop/dn742471.aspx
- https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#use-grammatically-correct-error-messages

One practical benefit is that it allows you to build out a particular message with commas, semicolons, multiple sentences etc. without breaking consistency.

See Safari and Chrome HTTP error messages:

<img width="375" alt="screen shot 2017-12-27 at 2 10 04 pm" src="https://user-images.githubusercontent.com/1754873/34369446-dfca8a14-eb0f-11e7-8d8e-b6117542b8d4.png">
<img width="292" alt="screen shot 2017-12-27 at 2 10 19 pm" src="https://user-images.githubusercontent.com/1754873/34369447-dff4b474-eb0f-11e7-9f08-4c8a64a93219.png">

**Comment by dav-is** [comment]
I'd like to hear the rational of why this issue is "Priority: OMG Maximum". Completely ridiculous...
