### ISSUE TITLE
DynamicHOC equivalent to DynamicComponent

### ISSUE THREAD

**Issue by jsvde** [zeit/next.js#3479]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Let users dynamically import higher order components in the same manner as regular components to increase composability. 

## Current Behavior
Using `dynamic(import('./file.js'))` returns a DynamicComponent and can't be used to load HoCs, which makes sense because HoCs are functions and not components.

## Context
When using next to render the same modular frontend for different clients, we use `getInitialProps` to fetch the client data and then wanted to apply HoCs (derived from the client settings) for customization.

Example: 
hoc_1.js
```
export default Content => {
  return props => (
    <section className="Module" alt={props.alt}>
      <h2>{props.title}</h2>
      <Content {...props} />
    </section>
  );
};
```

hoc_2.js
```
export default Content => {
  return class Module extends React.Component{
    componentDidMount(){
      //do some module specific stuff
    }
    render(){
      return (
        <section className="Module" alt={props.alt}>
          <div className="SubModule">
              <Content {...props} />
          </div>
          <div>Some other Stuff</div>
        </section>
      )
    }
  }
};
```

index.js
```
import Modules from "../components/Modules.js"; // all modules dynamically imported and exported as Object
import HOCs from "../components/HOCs.js"; // all HOCs dynamically imported and exported as Object

export default class Index extends Component {
  static async getInitialProps({ req }) {
    const res = await fetch(`/client_settings_api/`);
    const json = await res.json();
    return { modules: json.modules, contentHoC: json.contentHoC };
  }

  render() {
    return (
      <div>
        {this.props.modules.map(module => {
          const Module = Modules[module.type];
          const contentHoC = HOCs[this.props.contentHoC];
          const EnhancedComponent = contentHoC(Module);
          return <EnhancedComponent />;
        })}
      </div>
    );
  }
}
```

In this particular case you could simply render `this.props.children`in the HoC, use it as a dynamic component and render `<Hoc {...props} /><Module {...props} /></Hoc>` but this raises the question how to use HoCs dynamically in general? Instead of exporting components already wrapped in HoCs maybe it's possible to use HoCs dynamically to compose them where and how you like?

## Your Environment
| Tech    | Version |
|---------|---------|
| next    | 4.2.1 |
| node    | 8.4.0 |

**Comment by timneutkens** [comment]
This can be implemented without core support right 🤔
