### ISSUE TITLE
`next export` cannot run properly

### ISSUE THREAD

**Issue by jferrettiboke** [zeit/next.js#348]
I am getting an error when I try to execute `next export`. Although it says "DONE Compiled successfully in...", it is not compiling everything.

I get an error that says this.

```
DONE Compiled successfully in 4711ms

> Ready on http://localhost:3000
> No `pages` directory found. Did you mean to run `next` in the parent (`../`) directory?
```

Any idea?

**Comment by ejulen** [comment]
See my comment in #70. I don't think there is such a command.

**Comment by jferrettiboke** [comment]
Close according to [this comment](https://github.com/zeit/next.js/issues/70#issuecomment-265024136). I had a misunderstood. Sorry for the inconvenience.
