### ISSUE TITLE
Custom Head component not finding <title>

### ISSUE THREAD

**Issue by hobbs** [zeit/next.js#3483]
## Expected Behavior
I created a custom <Head> element, with a standard <title> template. I expect the <title> element to set the title for the page this component is used on.

## Current Behavior
Using this component in a page results in 2 <title> elements

## Context
Here is the example component, MyHead.js
```

const MyHead = (props) => (
  <Head>
    <title>{(props.pageTitle)? props.pageTitle + ' · ' : ''}site.com · Tagline here</title>
    {props.children}
  </Head>
)

export default MyHead
```
Then in a page.js, I would simply use it in the render, for example:
```
<Layout>
  <MyHead pageTitle='Section 1' />
   {content}
</Layout>
```

**Comment by arunoda** [comment]
If there's an exiting title or any other head elements, `<Head>` won't touch them.
(That's a design decision)

So, it's better to manage title via only using `<Head>` if you want to have different titles for different pages.

**Comment by timneutkens** [comment]
In canary there’s a new feature that allows you to define a key prop to dedupe tags in the head. Works exactly like react’s on key property
