### ISSUE TITLE
Using JQuery plugins in Next.js

### ISSUE THREAD

**Issue by khakestani** [zeit/next.js#3492]
I want to use a jQuery plugin named `Justified` into my next.js project .

This plugin in addition to his lib files need another jQuery plugin for managing loading files named `imagesLoaded` 

At first I import jQuery like this :
``` javascript
import $ from 'jquery';
```
And add another libs by `require` inside `componentDidMount` method like this:
``` javascript
let imagesLoaded = require('static/scripts/justified-gallery/imagesloaded.pkgd.min.js');
let justifiedGrid = require('static/scripts/justified-gallery/justified.min.js');

let parameters = {
    gridContainer: '#grid-container',
    gridItems: '.grid-item',
    enableImagesLoaded: true
};
let grid = new justifiedGrid(parameters);
$('body').imagesLoaded( function() {
    grid.initGrid();
});
```
but I received following error: 
`Uncaught TypeError: (0 , _jquery2.default)(...).imagesLoaded is not a function`

The content of files for more information:
[https://www.jqueryscript.net/demo/jQuery-Plugin-For-Responsive-Justified-Image-Gallery-Justified/imagesloaded.pkgd.min.js](url)

[https://www.jqueryscript.net/demo/jQuery-Plugin-For-Responsive-Justified-Image-Gallery-Justified/dist/js/justified.min.js](url)

**Comment by jaydenseric** [comment]
I strongly advise not polluting your project with jQuery. That effect with the images can be achieved with css flexbox in just a few lines; you can avoid adding upwards of 40kb of JS to your bundle.

If the design can not be achieved with pure CSS, it's best to change the design. If you really want/need a JS solution, use search npm for a module that can be installed as a versioned dependency and can be imported properly without depending on a jQuery environment.

**Comment by timneutkens** [comment]
Agreed with @jaydenseric.
But, the reason for this is that the javascript you try to load from /static expects a global jQuery object. So you need to do something like this:

```
import $ from 'jquery';
window.jQuery = $
```

**Comment by julmot** [comment]
@timneutkens Can't confirm that this approach works.
