### ISSUE TITLE
React portal support for server side rendering

### ISSUE THREAD

**Issue by antonybritto** [zeit/next.js#3493]
Currently i am working on a AMP project where i need to render some AMP components directing into BODY. Though there are some external modules like 'react-portal' , 'react-portal-universal' does the same, but would like to see the native support in nextjs itself, as it can avoid extra webpack config change and react render tweaks.

**Comment by sergiodxa** [comment]
Portals are a client only feature because you need to provide a DOM element where to render them and there no API inside `react-dom/server`.

**Comment by antonybritto** [comment]
I have a requirement to do this in SSR as well. Trying to figure out the best way to do this.

**Comment by sergiodxa** [comment]
@antonybritto I think you'll need to create your own implementations of portals.

**Comment by PaulTondeur** [comment]
I think this answer is a bit too simplistic to say that one need to create their own implementation. I understand that it works differently serverside, but actually this is nothing I should be worrying about. Portals should just be supported by zeit.js out of the box.

**Comment by timneutkens** [comment]
I'm not sure what you're referring to, React.createPortal is supported just fine, here's an example:
https://github.com/zeit/next.js/tree/canary/examples/with-portals

**Comment by timneutkens** [comment]
The original issue is about "Currently i am working on a AMP project" AMP has very different semantics and doesn't run client-side React.

**Comment by PaulTondeur** [comment]
Thanks @timneutkens. I ran into an issue (using PortalWithState) and arrived here in this topic and concluded incorrectly that it wasn't supported. It turns out that it works indeed when a pure portal is used. I understand that AMP is a total different case.

Excuses for the confusion and thanks for your time.

**Comment by alinchican** [comment]
@PaulTondeur Because you didn't search for an answer. Last reply was posted 1 year ago, a lot of things have changed meanwhile. Also, this framework is named next.js and not zeit.js. I didn't think it was necessary to motivate my reaction. I'm glad the issue was resolved.

**Comment by dextermb** [comment]
> I'm not sure what you're referring to, React.createPortal is supported just fine, here's an example:
> https://github.com/zeit/next.js/tree/canary/examples/with-portals

@timneutkens, when I attempt todo something similar to this I get an error:
```
Invariant Violation: Target container is not a DOM element.
```

```jsx
class Component extends React.Component {
    componentDidMount() {
        this.portal = document.body;
        // this.portal = document.querySelector('body');
    }

    // ...

    render() {
        render (
            ReactDOM.createPortal(
                this.renderDropdown(),
                this.portal
            )
        )
    }
}
```
