### ISSUE TITLE
with-refnux example critical dependency error 

### ISSUE THREAD

**Issue by idkjs** [zeit/next.js#3497]
```
WARNING  Compiled with 1 warnings                                      20:40:39

 warning  in ./node_modules/try-prop-types/index.js

4:11-24 Critical dependency: the request of a dependency is an expression
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Current Behavior

error is referencing this line in the [refnux package](https://github.com/algesten/refnux/blob/8f992e77674ff346dab3a9779322e7d4a53ee2a1/src/refnux.coffee#L2)
## Steps to Reproduce (for bugs)

1. npm install
2. npm run dev
3. open http://localhost:3000/page1

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |       "next": "latest",      |
| node    |   v8.9.1      |
| OS      |    macOS, sierra     |
| browser |      firefox   |
| etc     |         |

**Comment by timneutkens** [comment]
Sounds like an upstream issue.
