### ISSUE TITLE
If it is possible to perform a client-side routing `pushState` BEFORE `getInitialProps`

### ISSUE THREAD

**Issue by catuskeeper** [zeit/next.js#3501]
I think a client-side `pushState` should be performed BEFORE `getInitialProps`.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I think the correct way is to perform `pushState` first, leaving the unfetched data as default value, so that we can render the static part of the page, and dynamic part of the page will be blank or filled with loading spinners, just like what we do in writing a totally client-side-rendered project. After this, data fetching will be performed and dynamic data will be fed to the page asynchronously.

## Current Behavior

Currently, in a client-side routing, `pushState` will be performed after the execution of `getInitialProps` of the destination page. So if the async data fetching in `getInitialProps` takes 5 seconds, the client-side will do nothing during the 5 seconds, leading to a bad user experience. 

## Context

This issue leads to a delay when I click any `<Link>` in client-side.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   4.2.1  |
| node    |  8.9.1  |

**Comment by sergiodxa** [comment]
You can do that right now manually. Check if `getInitialProps` is running client side and return an empty object, then fetch the data inside `componentDidMount`, if you extract the data fetching to a function you can just execute it in both methods without duplicating code.

The idea of `getInitialProps` is not fill the state after the page is loaded, but instead, as the name implies, get the initial props required for the page, we've an example on how to display a loading on route change which you can implement using `next/router` events, that way you can show something to the user while awaiting the data.

**Comment by catuskeeper** [comment]
@sergiodxa Thank you for the reply.
So there are two solutions:
1. manually extract client-side data fetching into `componentDidMount` - good user experience but it requires additional codes in every page of the project.
2. display a loading after clicking `<Link>` and before `pushState` - less work but the final user experience is a bit strange, actually I think I never saw a webpage like that, click an anchor, then display a loading for some while, then jump to the destination page.
For now I think I will choose the first solution.
