### ISSUE TITLE
SSR only for selected pages (disable client side scripts) for amphtml

### ISSUE THREAD

**Issue by maszynka** [zeit/next.js#3504]
I'm considering using amphtml with nextjs.

I have found that currently all custom scripts are disallowed (apart of special version of iframe, useless in this case) on amphtml.

The soloution could be turning off React on client side:

1. Prevent from adding react.js to page
2. Make sure all used components are SSR-only compatible

I have seen my next.js page working with js disabled in browser. But maybe I am missing something important to consider? What kind of difficulties may I approach?

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by sergiodxa** [comment]
We've an example [with-amp](https://github.com/zeit/next.js/tree/canary/examples/with-amp).
