### ISSUE TITLE
Support to Add Google Custom Search to NextJS site?

### ISSUE THREAD

**Issue by JohnWooS** [zeit/next.js#3513]
- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and I believe this is not a duplicate

## Expected Behavior
Adding Script tags got the Google Custom Search in HTML section with JSX should be supported or provide alternative ways

## Current Behavior
Throws the following error
app/pages/index.js?entry: name.charAt is not a function

## Steps to Reproduce (for bugs)
Add the following code in HTML section of JSX page inside a DIV.

`<script>
  (function() {
    var cx = '0089289843748653:ikyblft4';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>:search></gcse:search>`

I also tried with following but didn't work

`App.componentDidMount = () => {
var embedcode = `<script>
      (function() {
        var cx = '013626029654558379071:ze3tw4csia4';
        var gcse = document.createElement('script');
        gcse.type = 'text/javascript';
        gcse.async = true;
        gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(gcse, s);
      })();
    </script>
    <gcse:search></gcse:search>`

  $('#gsearch').html(embedcode)
}`

## Context
Trying to add Google Custom Search to my site created in NextJS

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.2.1     |
| react    |    16.2.0     |
| OS      |     Mac    |
| browser |   Chrome      |
| node     |   latest      |

**Comment by JohnWooS** [comment]
With following code I made the script and tag get added, but nothing shows up in the UI. Am I missing something? 

`var embedcode = `<script>
        (function() {
          var cx = '013626029654558379071:ze3tw4csia4';
          var gcse = document.createElement('script');
          gcse.type = 'text/javascript';
          gcse.async = true;
          gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(gcse, s);
        })();
      </script>
      <gcse:search></gcse:search>`
    document.getElementById('gsearch').innerHTML = embedcode;`

**Comment by timneutkens** [comment]
You need to use `dangerouslySetInnerHTML`, React has a built in XSS filter.
https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml
