### ISSUE TITLE
<style> in _document.js renders > as &gt;

### ISSUE THREAD

**Issue by city41** [zeit/next.js#3520]
When using _document.js, a style tag will render `>` as `&gt;`. This prevents selectors like `.foo > .bar { ... }` from working.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
when defining a style tag in _document such as 
```
<style>{' body > div { background-color: red }'}</style>
```
it should preserve the `>`

## Current Behavior

The `>` gets encoded as `&gt;`

## Steps to Reproduce (for bugs)
Using the hello-world example in examples/ as a basis

1. add a _document.js in pages that looks like
```javascript
import Document, { Head, Main, NextScript } from 'next/document'
import flush from 'styled-jsx/server'

export default class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    const { html, head, errorHtml, chunks } = renderPage()
    const styles = flush()
    return { html, head, errorHtml, chunks, styles }
  }

  render() {
    return (
      <html>
        <Head>
          <style>{`body > div { background-color: red }`}</style>
        </Head>
        <body className="custom_class">
          {this.props.customValue}
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

2. `next build && npm start`
3. view the page source in the browser, `<style>body &gt; div { background-color: red }</style>` is rendered.

## workaround
Using `dangerouslySetInnerHTML` fixes the issue

```
<script dangerouslySetInnerHTML={{__html: 'body > div { background-color: red }' }} />
```

## Context
I am attempting to change the css of divs that are outside of what a normal nextjs page can access.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4.2.1        |
| node    | 6.9.4        |
| OS      | Ubuntu 16.04        |
| browser | Chrome 63.0.3239.108  and Firefox 57.0.3        |

## Note

When using styled-jsx inside a nextjs page, `>` works as expected

**Comment by lededje** [comment]
I came across this too. A workaround I found was referencing an external css file. Not ideal though if you are trying to reduce the number of requests being bad though.

**Comment by timneutkens** [comment]
Yeah it's an upstream issue. Not much we can do here.
