### ISSUE TITLE
Router.push promise resolves before page finished transitioning.

### ISSUE THREAD

**Issue by adailey14** [zeit/next.js#3523]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I expected the promise returned from Router.push('/myurl') would only resolve after the new page had been navigated to. This is useful for triggering UI events after the transition like: Router.push('/myurl').then(() => showModal('Hello'));

## Current Behavior

Currently, the promise often resolves before that page transition is completed. This is especially easy to see in development mode, since the transition often takes considerable time while the next page is building.

## Steps to Reproduce (for bugs)

1. Put some code like Router.push('/myurl').then(() => window.alert('Premature Alert?')) to be triggered by a button click.
2. Add something that will take some time to getInitialProps for myurl.js
2. Click the button, and, see if the alert arrives before the new page is rendered.

## Context

In particular, I'm trying to put together a login flow where the app shows a "loading..." message while the page is being navigated to the next destination, and then disappears after the new page is loaded.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  4.1.4  |
| node    | 8.8.1  |
| OS      |   OSX  |
| browser |   Chrome  |
| etc     |         |

**Comment by timneutkens** [comment]
It is triggered the same moment as `routeChangeComplete`, we won't be changing this behavior in the short term as it will increase client side bundle size and is breaking from the current behavior.
