### ISSUE TITLE
Can get http port in getInitialProps?

### ISSUE THREAD

**Issue by yanyu0517** [zeit/next.js#3526]
There are code:
![image](https://user-images.githubusercontent.com/5326851/34477831-ffd20a18-efd7-11e7-8346-a7a94a416c7f.png)

When to get port from`req` use `req.port`, it is undefined. How can I get port?

**Comment by timneutkens** [comment]
https://stackoverflow.com/questions/23319033/how-to-get-the-port-number-in-node-js-when-a-request-is-processed

**Comment by yanyu0517** [comment]
Thank you for your replay. 
My problem is:

I put next.js in a express server run on the 3002 port, and have a ngnix that run on 3003 in the front of express. 

My site address is http://www.xxx.com:3003, and ngnix will upstream requests to express(port 3002). My point is I want to get the 3003 in getInitialProps, like get headers or cookie from request.

**Comment by yanyu0517** [comment]
I think I make a mistake, forget it
