### ISSUE TITLE
Error on imperative router.prefetch()

### ISSUE THREAD

**Issue by jmike** [zeit/next.js#3532]
I get an unhandled promise rejection when using `withRouter(MyComponent)` and `props.router.prefetch('/foo')` within MyComponent.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I expected `props.router.prefetch('/foo')` to just work as illustrated [here](https://github.com/zeit/next.js/#imperatively).

## Current Behavior

I get the following error:

```
TypeError: Cannot read property 'loadPage' of undefined
at Router._callee8$ (/Users/jmike/Workspace/project/node_modules/next/dist/lib/router/router.js:726:40)
```

## Steps to Reproduce (for bugs)

1. Create dummy react component
2. Wrap component with `withRouter` HOC
3. Run `props.router.fetch('/foo')`

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4.2.1 |
| node    | 9.2.0 |
| OS      | MacOS 10.12.6 |
| browser | Google Chrome 63.0.3239.84 |

**Comment by timneutkens** [comment]
Try upgrading to latest 👍
