### ISSUE TITLE
`next build` on canary using full path in transpiled require statements

### ISSUE THREAD

**Issue by kylealwyn** [zeit/next.js#3533]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

`next build` does not include absolute path to node module

## Current Behavior

`next build` includes absolute path in transpiled require path

### Correct
```sh
yarn add next@4.2.0
next build

# Transpiled output
var _extends2 = require('babel-runtime/helpers/extends');
```

### Incorrect
```sh
yarn add next@canary
next build

# Transpiled output
var _extends2 = require('/Users/kyle/projects/test/node_modules/babel-runtime/helpers/extends');
```

## Context

Unable to deploy to lambda using [up](https://github.com/apex/up) due to `up` building locally and uploading zip file to s3 rendering absolute paths invalid

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   canary      |
| node    |    8.9.0     |
| OS      |     macos 10.13.2    |

**Comment by mrtnzlml** [comment]
Same problem - see ^^ postmortem. Also serverless environment deployed from Travis-CI.

**Comment by juancampa** [comment]
FWIW the problem seems to be: https://github.com/zeit/next.js/blob/85f341c9d834114be1127cf73a04bc3517cc2f67/server/build/webpack/utils.js#L4

**Comment by timneutkens** [comment]
Created a pull request 🙏
