### ISSUE TITLE
with-react-helmet bug in production mode

### ISSUE THREAD

**Issue by damianfrizzi** [zeit/next.js#3534]
I tried to implement React Helmet for our project and noticed a bug when running in production mode. 
React Helmet doesn't initialize on the very first request after starting the application. But it initializes correctly on each subsequent request (SSR & CSR).
I cloned the minimal [with-react-helmet](https://github.com/zeit/next.js/tree/canary/examples/with-react-helmet) example and I can confirm that the issue appears there, too.

![image](https://user-images.githubusercontent.com/5004390/34601739-91db88f4-f1fd-11e7-99d5-4a2c6d6ee5a5.png)

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
React Helmet should initialize correctly on the first request that was made.

## Current Behavior
As described above, React Helmet doesn't initialize correctly on the very first request.

## Steps to Reproduce (for bugs)
1. Clone [with-react-helmet](https://github.com/zeit/next.js/tree/canary/examples/with-react-helmet)
2. npm install
3. npm run build
4. npm start
5. Check the DOM/page source

**Comment by JeromeFitz** [comment]
I do not believe this is limited to `with-react-helmet`. The initial server render seems to set the tone and subsequent requests are good to go. (Tried looking for issues to reference, will continue to see if I can link any here.)

I can absolutely reproduce this following your steps (and have).

Accessing the same URL from a separate machine and even network does not reproduce the behavior though (SSR source), which I believe limits it to the *very first* render of a newly built deployment (and the client-side JS compensates for it, in that exact case).

**Comment by damianfrizzi** [comment]
@JeromeFitz do you maybe have any workaround for this? Right now we're extracting the desired information to render the correct meta information from `this.props.__NEXT_DATA__` which is quite hacky...

**Comment by JeromeFitz** [comment]
@damianfrizzi On my end, I am okay with its current behavior (wherein, I can only verify this happen on the _first render_ from the server itself). So at this time, I have no workaround or way to suggest addressing this.

**Comment by Ephem** [comment]
I dug into this and found out what caused the behaviour.

The default metadata was declared inside of `<Head>` in `_document.js`. This document gets rendered by `renderToStaticMarkup` _after_ `getInitialProps`. So when `Helmet.renderStatic` was called, the default metadata had not yet been rendered. This got flushed on the next request.

Solution is to move the declaration of any default metadata into `_app.js` instead. This gets rendered before `Helmet.renderStatic` is called and so works correctly.
