### ISSUE TITLE
[Question] Can isomorphic routing happen with custom sever?

### ISSUE THREAD

**Issue by aviramga** [zeit/next.js#3537]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

I'm struggling to make the isomorphic routing work with an express server.
The routing works just fine on the server, but when I try to do client side routing via the Link tag I get the flashing 404 and then the page.

I've read all about the 404 flashing issue in other tickets (like this https://github.com/zeit/next.js/issues/2833), nothing have worked for me.

I'm wondering if isomorphic routing is possible with express router or I need to use NextJs default router for that?

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |  4.1.4       |
| node    |    8.6.0     |
| OS      |     HighSierra    |
| browser |     Chrome 62    |
| Express    |  4.15.3       |

Thanks!!!

**Comment by timneutkens** [comment]
Please read my full explanation here: https://github.com/zeit/next.js/issues/2208#issuecomment-341107868
We should definitely update the docs 👍

**Comment by aviramga** [comment]
Thanks @timneutkens! feels hacky though.... any chance this will be fixed anytime in the future? or this is something I'll have to live with when using custom server?

**Comment by sergiodxa** [comment]
@aviramga check this example https://github.com/zeit/next.js/tree/canary/examples/parameterized-routing

**Comment by aviramga** [comment]
Thanks for the example guys! Im having a hard time understanding how to embed this solution with an express server.
Is there an example for that as well?

**Comment by sergiodxa** [comment]
The express example has a parametized route.

**Comment by aviramga** [comment]
Hi @sergiodxa I know how to use express with paramterized routes, but I still can make it work with your suggested workaround, the endpoint that is called is always route/:id and not route?id=xxxx
Below you can see how I configured my routes - 

`  router.get("/jobs/route1", (req, res) => {
    return app.render(req, res, "/homepage/jobs/route1");
  });

  router.get("/jobs/:id", (req, res) => {
    return app.render(req, res, "/homepage/jobs-position", {
      id: req.params.id
    });
  });

  router.get("/jobs*", (req, res) => {
    if (req.query && req.query.id) {
      return app.render(req, res, "/homepage/jobs-position", Object.assign(req.params, req.query));
    }
    return app.render(req, res, "/homepage/jobs");
  });
  return router;
};
`

My link is configured liked this:
`    
render() {
    const { uid } = this.props;
    const href = `/jobs/?id=${uid}`;
    const as = `/jobs/${uid}`;
    return (
      <div>
        <div className="single-position-component-wrapper">
          <Link href={href} as={as}>
            <a className="main-container"> Link  </a>
          </Link>
        </div>
      </div>
    );
  }
`

What am I doing wrong?
Thanks!
