### ISSUE TITLE
How can I display different page for the same url when different client visit?

### ISSUE THREAD

**Issue by supwjm** [zeit/next.js#3538]
There is some case that I want to display different page to the visitor form different client ( web or app webview , and so on ) .  And the pages is not only different in style but also in logic 。How can I make it work in Next.js. When I use react , I make it happen by create different servers , and each server has its router. So  I  reuse the other common components and so on。However , since Next.js create routers itself.
I don't know how to implement it.

**Comment by timneutkens** [comment]
You can check the user agent inside getInitialProps and use that to render differently 👍

**Comment by supwjm** [comment]
Though that maybe work , but I thought it will make the page more complex . I saw can render different child like below : 
<Route path='/page' children={(props) => (
  props.match
    ? <Page {...props}/>
    : <EmptyPage {...props}/>
)}/>

If Next.js can offer some similar feature like that , It will be awesome .

**Comment by timneutkens** [comment]
We're planning to implement react router at some point.
