### ISSUE TITLE
`next init`

### ISSUE THREAD

**Issue by leo** [zeit/next.js#354]
We should introduce a command that automatically generates a boilerplate (example site) within the current directory.

Also allows you to specify a path:

```bash
next init ../bla/bla
```

[This](https://ember-cli.com/user-guide/#create-a-new-project) is how Ember's CLI handles it.

**Comment by nkzawa** [comment]
It already exists. We have to write a doc.

**Comment by arunoda** [comment]
So, we need to install next globally too. How about move it into another utility like `next-init`. I mean there's another NPM package for that.

**Comment by leo** [comment]
@arunoda I wouldn't recommend that. Ember also has it built into the main CLI.

**Comment by arunoda** [comment]
@leo If you are looking for an example, CRA does the way I suggested.
They have `create-react-app` and `react-scripts`.

`react-scripts` updated very often and `create-react-app` rarely.

Anyway, document something better than nothing.

**Comment by leo** [comment]
Already documented in `next init`.
