### ISSUE TITLE
`npm install` fails on leannextjs-demo, no valid versions available for duplexer3, npm -v: 5.6.0

### ISSUE THREAD

**Issue by jeffvandyke** [zeit/next.js#3542]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

npm install should work on branch `getting-started`

## Current Behavior
npm install fails with this output:
```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated @semantic-release/last-release-npm@2.0.2: Use @semantic-release/npm instead
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for duplexer3

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeff/.npm/_logs/2018-01-06T19_19_13_553Z-debug.log
```

## Steps to Reproduce (for bugs)

1. git clone <this repo>
2. git checkout getting-started
3. npm install

## Environment

| Tech    | Version |
|---------|---------|
| next    |    ^4.2.0     |
| node    |    8.9.3     |
| OS      |     Manjaro GNOME 3 x64 (relatively) fresh install    |
| browser |    Firefox 57.0.3     |
| etc     |    npm version 5.6.0     |

**Comment by Fallion** [comment]
Seems to be a global issue.

**Comment by benatkin** [comment]
It seems to be like the infamous left-pad issue, only the maintainer of duplexer3 cleaned out old versions instead of deleting it entirely (and more likely to be unintentional/accidental breakage).

**Comment by benatkin** [comment]
[duplexer 1.3 is back](https://www.npmjs.com/package/duplexer3) so this issue should be fixed!

**Comment by benatkin** [comment]
apparently the maintainer of duplexer3, @deoxxa, simply published a new version, and that caused it disappear due to an npm bug

**Comment by benatkin** [comment]
It looks like the maintainer of duplexer3 is actually @floatdrop – @deoxxa released duplexer2 and that part the README wasn't changed for duplexer3.

**Comment by rauchg** [comment]
Thanks for reporting. Thanks @benatkin for diagnosing the issue correctly. We'll keep this open until npm resolves their issue

**Comment by shanedroid32** [comment]
I have similar issues:

`warning next > glob-promise > semantic-release > npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
warning next > glob-promise > semantic-release > @semantic-release/last-release-npm@2.0.2: Use @semantic-release/npm instead
error Received malformed response from registry for "timed-out". The registry may be down.`

**Comment by benatkin** [comment]
Getting `No valid versions available for timed-out` now

**Comment by shanedroid32** [comment]
I was getting the same and now I am getting an error for `'pinkie-promise'`

**Comment by shanedroid32** [comment]
From status.npmjs.org — "Update - Most of the deleted packages have been restored and installation of those packages should succeed. Nine packages are still in the process of restoration. "

**Comment by benatkin** [comment]
It went from being broken to working to being broken again, so I'm guessing it's not fixed.

**Comment by jeffvandyke** [comment]
Seems to be working for me now. As of now, NPM packages seem to be restored, and they're working on a final tidying up, so I think this can be closed.
