### ISSUE TITLE
[Question] Can next.js use faster alternatives to expressjs (like micro/connect/fastify)?

### ISSUE THREAD

**Issue by trivikr** [zeit/next.js#3544]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

When it comes to node servers, [expressjs](https://github.com/express/expressjs) has now got tough competition when it comes to performance.
Here is a [benchmark](https://github.com/fastify/fastify#benchmarks) which shows some alternatives like [micro](https://github.com/zeit/micro), [connect](https://github.com/senchalabs/connect) and [fastify](https://github.com/fastify/fastify) are much faster/efficient than expressjs.

Are there any plans of next.js moving to one of these faster alternatives to expressjs?

**Comment by lucleray** [comment]
Hi,

You can use next.js with the server of your choice :
https://github.com/zeit/next.js#custom-server-and-routing

Here is an example of next.js with fastify (look at file `server.js`) :
https://github.com/zeit/next.js/tree/canary/examples/custom-server-fastify

Another example with micro :
https://github.com/zeit/next.js/tree/canary/examples/custom-server-micro

The list of all examples (look at the custom-server ones) :
https://github.com/zeit/next.js/tree/canary/examples

**Comment by timneutkens** [comment]
To be clear, we don't use express in the core. We're just using the http server node provides.
