### ISSUE TITLE
I want to know how to pass the hapi handler value to next.js page?

### ISSUE THREAD

**Issue by sivabalan02** [zeit/next.js#3548]
This is not a bug. 

I have started the nextjs for a week ago for my admin panel. I want to integrate the nextjs with hapijs. I don't know how to pass the values from the hapi handler to the nextjs page

**Comment by CallumDenby** [comment]
You typically pass values through in the query params and then access it in the props of your page.

https://github.com/zeit/next.js/blob/canary/examples/custom-server-hapi/next-wrapper.js#L16

**Comment by sivabalan02** [comment]
@CallumDenby  Thanks for the reply. But what i do is getting the mongodb data from the hapi handler and want to pass it. Can't pass it through the query param

**Comment by CallumDenby** [comment]
You can pass any object data through the query parameter. However it's probably better for you to create an endpoint to retrieve the mongodb data and call it in getInitialProps on your page.

**Comment by sivabalan02** [comment]
@CallumDenby  I doubt that query parameter is the right way pass the values to the nextjs?

**Comment by CallumDenby** [comment]
From what I've seen it's used for passing data only accessible from the server into the application, however the better approach would be as described to create and endpoint and retrieve the data in getInitialProps

**Comment by sivabalan02** [comment]
@CallumDenby You mean create api endpoint on the hapi server and access it on the nextjs?

**Comment by CallumDenby** [comment]
Yes, create an API on the hapi server and have it fetched from the getInitialProps in your next.js pages.

**Comment by sivabalan02** [comment]
I have one more doubt. As i am using nextjs as SSR why i have to call one more api for the getting db data. For that kind of scenarios, i can go to the CSR. Am i right?
