### ISSUE TITLE
`renderPage` equivalent for page level components

### ISSUE THREAD

**Issue by attapurposevc** [zeit/next.js#3550]
Hi,
Currently, we can pass the through the `renderPage` through the `_document.js` for decorating our components. This seems a bit restrictive, since I want to decorate one of my pages on the server side. 

I've looked into it, there seems no straightforward way of accomplishing this. Correct me if I'm wrong. If there isn't, then I'll start making a pull request.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by tz5514** [comment]
I think you can check this out https://github.com/zeit/next.js/pull/3552.

**Comment by timneutkens** [comment]
There's a few PRs and other issues about this. closing this one.
