### ISSUE TITLE
Options to map or regexp file system routes

### ISSUE THREAD

**Issue by chingyawhao** [zeit/next.js#3554]
## Problem
My team is maintaining a large front end application with the same file hierarchy as:-
- component
- pages

but we don't like it. We usually have multiple component that is only used by a single page resulting whenever we found bugs or wanted to modify a page, we have to navigate though component to find the components related to the page. Its a pain in developing. So, we prefer the approach of:-
- pages
   - page
      index.js
      - component
and we are looking for a new framework to use

## Ideal case
We would name our pages and components differently
- pages
   - page
      index.page.js
      - component
         component.component.js

We would use pagesGlobPattern to only render files ending with .page.js ignoring .component.js
But then we would need another option to ask next to treat index.page.js as index.js

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by moaxaca** [comment]
I face the same issue, this functionality would be awesome. 👍

**Comment by timneutkens** [comment]
I'm going to close this issue since `pagesGlobPattern` will be removed in v5. In a later version we might implement something like a `pagesResolver` function that'll allow you to implement functionality like this. But for now you're bound to `pages` being only for pages 👍

**Comment by gihrig** [comment]
> I'm going to close this issue since pagesGlobPattern will be removed in v5.

At first this made me sad. 😢 

But not wishing to "fight City Hall", I came up with an idea that I haven't seen discussed in this or the many related issues. That is, `pages` is a Next.JS route specific feature. I might prefer it were called `routes`. But as such, it really should have nothing in it that is not route related.

Here's a solution that I think satisfies the requirements of the OP, without modifying Next.

I created a more or less "react standard" `containers` folder that serves the function the OP is requesting of `pages`. It fetches data and/or uses components to build a page view. This folder may contain other files, including tests, styles, other components, etc., that relate to a specific page or tree of pages.

This structure eliminates issues that come up when too much material is placed in `pages` like multiple routes to the same content, tests included in production bundles, etc.

The content of `pages` then is just 'boilerplate' redirects that shape the routes the app responds to.

Here's an example where served routes include `/about`, `about/us` and `about/work`:

![image](https://user-images.githubusercontent.com/1481063/35129872-8f2976b4-fc72-11e7-86a1-1d7b1f14edaa.png)

Files under `pages/about` are 'link files', they serve to establish routes only.
```javascript
import About from 'containers/About'

export default About
```

**Comment by moaxaca** [comment]
I have a similar structure and think of pages as bundle entry points. I then have modules containing containers, components, reducers, etc that are feature specific. This strategy works, but it could be cleaner if we could supply custom route mapping or resolver.

I would actually like to see that idea taken farther by having a resolver that maps to a named route structure that could be referenced by custom servers.
