### ISSUE TITLE
How to do hot deploy in a production environment

### ISSUE THREAD

**Issue by Cuihongsen** [zeit/next.js#3555]
like nginx reload

**Comment by oliviertassinari** [comment]
…

**Comment by lededje** [comment]
If by hot deployment you mean using something like hot module replacement in a production environment, I don't believe it's supported. You can do things like [rolling restarts](https://aws.amazon.com/premiumsupport/knowledge-center/auto-scaling-group-rolling-updates/) with your instance provider which will achieve something similar.

I believe the hot module replacement that next.js use is Webpack's, and they only reference it's use within [development environments](https://webpack.js.org/concepts/hot-module-replacement/#get-started).

**Comment by timneutkens** [comment]
You can use https://github.com/zeit/next.js/wiki/Handle-BUILD_ID-Mismatch-Error to trigger a reload. Hot updates are not supported. We might support it in the future. But not in the short term.
