### ISSUE TITLE
Set cache-control header in getInitialProps() in NextJs

### ISSUE THREAD

**Issue by cyrilpanicker** [zeit/next.js#3556]
I need to set `Cache-Control` header with a dynamic value in `getInitialProps` method. I tried the below.

    if(context.res){
        context.res.setHeader('Cache-Control','My-Cache-Control');
        context.res.setHeader('My-Header','My-Value');
    }

But it looks looks like NextJs is overriding the header value before sending the response. Below is the `cache-control` header value in response header in browser.

    Cache-Control: no-store, must-revalidate
    My-Header: My-Value

Let me know if anything is missing.

**Comment by pddigital** [comment]
I would set this value in the custom server not in getInitialProps, like in the middleware before the route is rendered.

**Comment by timneutkens** [comment]
`no-store, must-revalidate` sounds like you're testing in development mode. In That case we *always* want that value to prevent caching of the page (and development headaches) 👍
