### ISSUE TITLE
mobx example doesn't run with jest example .babelrc config

### ISSUE THREAD

**Issue by saibs** [zeit/next.js#3557]
The mobx example does not work with jest configured(I use the .babelrc config as in jest example).
I believe there is problem with .babelrc configuration with env

So, if .babelrc config is same as jest then, tests run but mobx doesn't and vice-versa.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

mobx store should run

## Current Behavior

mobx store does not work, the observable properties/ action setters and getters does not work. 

## Steps to Reproduce (for bugs)

1. Use mobx example and change the babelrc config to the one with jest example

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.2.2     |
| node    |    8.4     |
| OS      |     macos    |
| browser |       |
| etc     |         |

**Comment by gihrig** [comment]
@saibs `.babelrc` is unique to the needs of each project. In this case you will need to merge `.babelrc` from both projects to have Jest and Mobx working together.

Something like this:

```javascript
{
  "env": {
    "development": {
      "presets": "next/babel",
      "plugins": [
        "transform-decorators-legacy"
      ]
    },
    "production": {
      "presets": "next/babel",
      "plugins": [
        "transform-decorators-legacy"
      ]
    },
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ],
      "plugins": [
        "transform-decorators-legacy"
      ]
    }
  }
}
```

**Comment by saibs** [comment]
aah my mistake, I merged incorrectly and didn't include plugins for each env.
Thanks a lot.
