### ISSUE TITLE
Exported sites don't trigger onAppUpdated event

### ISSUE THREAD

**Issue by denisw** [zeit/next.js#3558]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Context

We export a Next.js site using `next export` and deploy it to Netlify. We noticed that after deploying a new version of the site, all users who have the previous version open in the browser cannot follow links anymore.

## Expected Behavior

The router's `onAppUpdated` event is triggered and causes a reload of the page by default, as documented in the README.

## Current Behavior

`onRouteChangeStart` is triggered, but `onAppUpdated` (or even `onRouteChangeError`) is never called. Instead, nothing user-visible happens. The browser developer tools reveal a failed `<script>` request (because the build ID - and thus the JS chunk's path - changed) which is apparently not being acted upon.

## Steps to Reproduce (for bugs)

1. Create a Next.js page with at least one (non-prefetch) link and create a listener for `onAppUpdated`.
2. Build it with `next export`, serve it (e.g. `npx server _build`) and visit it.
3. With the page open, rebuild the page (another `next export`).
4. Try clicking on the link you created. Nothing happens, and the `onAppUpdated` listener is not called.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   4.2.1      |
| node    |  9.3.0       |
| OS      |    macOS 10.13.1     |
| browser |    Any     |

**Comment by timneutkens** [comment]
Most likely fixed with the new error handling. Try upgrading to next@canary 👍
