### ISSUE TITLE
Would it be realistic to expect to use blueprint with next?

### ISSUE THREAD

**Issue by spherop** [zeit/next.js#356]
Still learning about the react ecosystem, nextjs, and how all this works... So am confused by something basic. 

Was hoping I'd be able to easily add npm components to my new next app - such as [blueprint](https://github.com/palantir/blueprint)

```
import React from 'react'
import * as Blueprint from "@blueprintjs/core" // this line creates error below
export default () => (
  .... 
)
```
I get this in the browser...
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/danielnewman/Documents/next/camillo_client/node_modules/dom4/build/dom4.max.js:760:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/src/components/index.ts:8:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Am I expecting to be able to do something that is not really feasible?

Thanks for any insight...

**Comment by arunoda** [comment]
I hope you getting this on the server. That means blueprint is not ready for SSR.

**Comment by MoOx** [comment]
I am getting similar issues with Phenomic (a project that create a static website from React components - I am thinking about rewriting it using next) where people don't stop complaining about "window is not defined", "document is not defined" etc.
I was thinking about doing an experimental thing: injecting a jsdom instance in the global node scope so window, document are always defined. I guess most stuff will works (maybe sometimes without the proper values that they would expect from a real browser).

For now I am using this snippet for testing components with jest https://github.com/MoOx/phenomic/blob/bab74b8647ccfc20491f381303fdc340ae27ee24/src/_utils/jsdom/index.js but I was thinking it could be a good idea to inject it during SSR and see how it works. Probably via an explicit/documented experimental helper, or being a flag - as I expect "some" failures with "some" components in "some" cases :)

**Comment by spherop** [comment]
@arunoda - Yea the error is on server - you're correct.

Has anyone been able to use any similar UI component library like Blueprint with Next? Or is this a likely problem for any framework that has been in SSR?

**Comment by spherop** [comment]
@MoOx - thanks for sharing your investigations and thinking on this... Next has such a low barrier entry, yet seems to hit all the right notes, but I am definitely looking for scenario where I can focus on building an app and not having to do a lot of workaround-ing. Nothing against Next as a project - just my own needs at this stage (looking for the best, fastest way to build React app and leverage open source components and libs).

**Comment by rauchg** [comment]
@MoOx thanks for sharing your experience. It'd be cool to provide a better developer experience by capturing the errors that are typically associated with lack of SSR (`document`, `window`, etc), and then pointing people to the wiki!

**Comment by frol** [comment]
> Has anyone been able to use any similar UI component library like Blueprint with Next?

I am using [React-MD](https://react-md.mlaursen.com/) (Material UI) with no problems at all and I love it.
