### ISSUE TITLE
Static files in folder other than 'static'

### ISSUE THREAD

**Issue by eugeneross** [zeit/next.js#3562]
As what the title states, do we have the ability to place files in the root file of the build `out` folder? A lot of PaaS's such as Netlify need some files there to override some configurations for things such as domain redirects and forwarding. I'm sure there are some other good use cases for this feature as well.

Any guidance on this is appreciated! 🤠

**Comment by sergiodxa** [comment]
After the export you can move or copy (better) static files to `out` folder and let your HTTP server serve them. I do that here https://github.com/sergiodxa/personal-site/blob/master/package.json#L10 with a single line:
```
"postexport": "cp .next/service-worker.js portfolio && npm run build:rss",
```
Just run the `cp` command after the export script.

**Comment by MFCo** [comment]
I don't know if you want something like this. But this code just serve anything inside `/out` as `/filename.ext`. I'm ussing express.

```javascript
    server.use(
      express.static(__dirname + '/out', {
        maxage: dev ? '0' : '365d'
      })
    );
```

**Comment by eugeneross** [comment]
@sergiodxa Exactly what I was looking for static export. Thanks!

@MFCo Thanks for this too. I'll keep it in mind for my custom server projects.

**Comment by morgs32** [comment]
Anyone guess how I could do `express.static` with `micro`?
