### ISSUE TITLE
Get previous page url

### ISSUE THREAD

**Issue by junshengpierre** [zeit/next.js#3565]
Hi, is there a way to get the url of the previous page for page tracking purposes? `window.document.referrer` always points to the url in which the first page load occurred for subsequent client side page navigation.

**Comment by MFCo** [comment]
Do you mean something like this?

https://github.com/zeit/next.js/blob/master/lib/router/router.js#L108

You can use Router.back() or you can even call window.history.back() like Router.back() does

**Comment by junshengpierre** [comment]
Hey, @MFCo I would like to retrieve the url or pathname without navigating to the page. Do you know if that's possible?

**Comment by sergiodxa** [comment]
@junshengpierre you need to implement it yourself, you can save each URL after the page changed in-memory, if you're using Redux you can dispatch an action and save the URL.
