### ISSUE TITLE
Export: Postpone JS loading

### ISSUE THREAD

**Issue by mrienstra** [zeit/next.js#3566]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
HTML pages generated by `next export` command should render initial view as quickly as possible.

## Current Behavior

JS is loaded before everything else:

```
<!DOCTYPE html>
<html>
<head>
<meta charSet="utf-8" class="next-head"/>
<meta name="viewport" content="width=device-width, initial-scale=1" class="next-head"/>
<link rel="preload" href="/_next/[hash]/page/index.js" as="script"/>
<link rel="preload" href="/_next/[hash]/page/_error.js" as="script"/>
<link rel="preload" href="/_next/[hash]/app.js" as="script"/>
</head>
```

If those `<link rel="preload"/>` tags are removed, the JS still loads a bit sooner than I would prefer.

One solution is to replace these lines:

```
<script async="" id="__NEXT_PAGE__/" type="text/javascript" src="/_next/[hash]/page/index.js"></script>
<script async="" id="__NEXT_PAGE__/_error" type="text/javascript" src="/_next/[hash]/page/_error.js"></script>
<script type="text/javascript" src="/_next/[hash]/app.js" async=""></script>
</body>
</html>
```

With something like:

```
<script>
setTimeout(function(){
var insertScript = function (src, id) {
  var scriptEl = document.createElement('script');
  id && (scriptEl.id = id);
  scriptEl.src = src;
  document.body.appendChild(scriptEl);
}
  insertScript('/_next/[hash]/page/index.js', '__NEXT_PAGE__/');
  insertScript('/_next/[hash]/page/_error.js', '__NEXT_PAGE__/_error');
  insertScript('/_next/[hash]/app.js');
}, 0);
</script>
</body>
</html>
```

I've cobbled together a crude / brittle approach to making both of these modifications:

1. `npm install --save-dev replace-in-file`

2. Add the file in [this gist](https://gist.github.com/mrienstra/218c0836208af352951a663652a6d7c7) to your project root.

2. Add something like the following to `package.json`:

```
  "scripts": {
    "export": "next export && node export_postprocess.js",
  },
```

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4.3.0-canary.1 |
| node    | 8.9.4 |
| OS      | OS X 10.13.2 |

## Notes

The HTML snippet shown above after "One solution is to replace these lines" is as seen in `next.js 4.3.0-canary.1`. In `4.2.1` these lines are slightly different (line 3 empty div, line 5 closing div):

```
<script async="" id="__NEXT_PAGE__/" type="text/javascript" src="/_next/[hash]/page/index.js"></script>
<script async="" id="__NEXT_PAGE__/_error" type="text/javascript" src="/_next/[hash]/page/_error.js"></script>
<div></div>
<script type="text/javascript" src="/_next/[hash]/app.js" async=""></script>
</div>
</body>
</html>
```

The `export_postprocess.js` node script (see gist link above) takes this difference into account.

## Next Steps

Should these changes be applied (in a cleaner way) to the `export` tool? As options or as defaults?

Would be interested in hearing how these changes affect the loading sequence for others.

**Comment by ewagstaff** [comment]
Dropping in to say I would also like this.

**Comment by timneutkens** [comment]
> HTML pages generated by next export command should render initial view as quickly as possible.

As per this description that's exactly what `preload` achieves, it marks the scripts as needing to be fetched (it starts download sooner), they're not executed until the `<script>` tag is invoked. Basically this means that the page becomes interactive faster as the script is already download.
