### ISSUE TITLE
Putting in component Header and 'next/head' makes browser tab unresponsive and my CPU fan gets loud.

### ISSUE THREAD

**Issue by mastrauckas** [zeit/next.js#3567]
When I use the below code it makes the browser tab unresponsive and my CPU fan gets loud.

Here is the code:

`layout.js`
``` js
import { Component } from 'react';
import Head from 'next/head';
import Header from '../components/header';

export default class Index extends Component {
  render() {
    const { title, description, children } = this.props;

    return (
      <div>
        <head />
        <Header />
        {children}

        <footer>{'I`m here to stay'}</footer>
      </div>
    );
  }
}
```

`header.js`
``` header.js
import { Component } from 'react';

export default class Header extends Component {
  render() {
    return <Header />;
  }
}
```

`index.js`
```js
import Layout from '../components/layout';

export default () => (
  <Layout>
    <p>Hello Next.js</p>
  </Layout>
);
```

If I remove either `<head /> ` or `<Header />` in `layout.js` everything works fine.  If I have them both in makes browser tab unresponsive.

## Expected Behavior
With the above code, I expect it not to make the browser tab unresponsive.

## Current Behavior
Makes browser tab unresponsive.  

## Steps to Reproduce (for bugs)
Use the above code.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.2.3     |
| node    |   v9.3.0      |
| OS      |   macOS High Sierra      |
| browser |    I've tested it with Chrome 63 and the current Firefox Developer Edition     |

**Comment by liweinan0423** [comment]
Header is rendering itself that causes a infinite loop. Change `<Header />` to `<header />` in `header.js`

**Comment by mastrauckas** [comment]
@liweinan0423 Thanks, can't believe I didn't notice that.  Thanks!
