### ISSUE TITLE
Unable to use the "request" package

### ISSUE THREAD

**Issue by rafaelalmeidatk** [zeit/next.js#3569]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
I should be able to use the package [request](https://github.com/request/request) without crashes.

## Current Behavior
The server crashes when I import the package.
![image](https://user-images.githubusercontent.com/11896398/34912646-ea691122-f8cd-11e7-9d90-d770a3240f84.png)

    These dependencies were not found:

    * fs in ./node_modules/needle/lib/needle.js, ./node_modules/needle/lib/multipart.js and 1 other
    * net in ./node_modules/forever-agent/index.js, ./node_modules/tough-cookie/lib/cookie.js and 1 other
    * tls in ./node_modules/forever-agent/index.js, ./node_modules/tunnel-agent/index.js

    To install them, you can run: npm install --save fs net tls

## Steps to Reproduce (for bugs)
1. Get a next.js project running (I've utilized the [Basic CSS Exaple](https://github.com/zeit/next.js/tree/canary/examples/basic-css))
2. Add the package with `npm install request`
3. Import the package anywhere with `import request from 'request'`
4. Try to run, the server crashes as soon as it reaches the import.

## Context
I am just trying to create a POST request to an API.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | v4.2.3 |
| node    | v8.1.3 |
| OS      | Ubuntu 16.04.3 LTS |
| browser | Chrome 62.0.3202.89 |

**Comment by rafaelalmeidatk** [comment]
Solved it using the following `next.config.js`:

    module.exports = {
      webpack: function (config) {
        config.node = {
          console: false,
          fs: 'empty',
          net: 'empty',
          tls: 'empty'
        }
        return config
      }
    }

**Comment by timneutkens** [comment]
It's best to use `isomorphic-fetch` instead of a server only http client.

**Comment by rafaelalmeidatk** [comment]
Thank you for the heads-up, I searched more and now I am using `isomorphic-fetch`.
