### ISSUE TITLE
custom page dir

### ISSUE THREAD

**Issue by krasevych** [zeit/next.js#3570]
- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
run without any error

## Current Behavior
work good with `node server.js`
but with: `next export` got error  `Couldn't find a `pages` directory. Please create one under the project root`

## Steps to Reproduce (for bugs)

1. move pages to `./src`
2. create `server.js`
3. add the code: `const app = next({ dev, dir: './src' });`
4. run: `"export": "next export"`

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |    4.2.1     |
| node    |    v7.6.0     |
| OS      |    window 8.1     |
| browser |    chrome     |

**Comment by gihrig** [comment]
@krasevych I got this to work as follows:

Add to `src/next.config.js`:
```javascript
module.exports = {
  exportPathMap() {
    return {
      '/': { page: '/' },
      '/about': { page: '/about' },
    }
  },
```

Add 'src' directory to `package.json` scripts:
```
  "scripts": {
    "dev": "next src",
    "build": "next build src",
    "start": "next start src",
    "export": "next build src && next export src",
```

`yarn export` produces a static build in `src/out`

**Comment by timneutkens** [comment]
`dir` is a next.js app root. So you need to have pages in `src/pages`.

**Comment by krasevych** [comment]
@timneutkens but I wrote `move pages to ./src`, that means I have page in `./src/pages`

**Comment by timneutkens** [comment]
Ah, sorry @krasevych I understood it as: `moved pages to src` as in `mv -r pages/* src`, which wouldn't work 😉 i'll check your issue out after v5 is released 👍

**Comment by timneutkens** [comment]
Actually you're confusing 2 things. `next export` doesn't use the custom server. @gihrig's explanation is correct. You need to provide the `dir` to `next build` and `next export`. Then it'll work 👍
