### ISSUE TITLE
react-komposer example

### ISSUE THREAD

**Issue by jonasblumer** [zeit/next.js#3574]
I've created an example that uses react-komposer, if anyone is interested. Might be interesting for the examples section, since I've seen a few questions concerning where to load data in components/containers. This might help them out.
You can find it here: https://github.com/jonasblumer/nextjs-komposer

I'm open to suggestions and CRs.

Cheers, hope this helps

**Comment by sergiodxa** [comment]
@jonasblumer you are welcomed to PR the code as an example in the repo 👍
