### ISSUE TITLE
Client and Server routing works differently

### ISSUE THREAD

**Issue by ahalimkara** [zeit/next.js#3577]
Issue repository: https://github.com/ahalimkara/next-routing-issue
Example: https://next-routing-issue-etmpnbuodz.now.sh

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

When navigating on Client side and also when directly enter path on browser address bar, it should show `Page B` content for path `/a` and `Page A` for `/b` path.

## Current Behavior

On client side: when navigating by clicking links it shows `Page A` content for path `/a` and when I refresh page it shows `Page B` content for path `/a`, same for path `/b`.

## Steps to Reproduce (for bugs)

1. Clone issue repository
2. `yarn dev`

## Context

Trying to use custom server routing.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.2.3     |
| node    |    8.5.0     |
| OS      |     macOS    |
| browser |     Chrome    |

## Question
When using custom server routing, [this](https://github.com/zeit/next.js/blob/e451218900b16e721db10413734ca7a964c53677/server/index.js#L197) `path-pattern` shouldn't be customized in some how? So when serving pages when navigating on client side (`http://localhost:3000/_next/[id]/page/a.js`) it will use same patterns. [Example](https://github.com/zeit/next.js/blob/e451218900b16e721db10413734ca7a964c53677/server/index.js#L202):
```js
if (page === '/a') {
  page = '/b';
} else if (page === '/b') {
  page = '/a';
}
```

**Comment by sergiodxa** [comment]
Check the example https://github.com/zeit/next.js/blob/canary/examples/custom-server-express/pages/index.js

You need to provide an `as` prop with the URL the be displayed in the browser and an `href` with the oath r and file name of the page.
