### ISSUE TITLE
Unable to get HMR working with Docker + server

### ISSUE THREAD

**Issue by damianesteban** [zeit/next.js#3579]
When running next.js on top of Docker with express my app is not hot reloading. It hot reloads without Docker as expected.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

The app should hot reload.

## Current Behavior

The app is not hot reloading, nor does the page reflect changes after I manually refresh the page.

## Steps to Reproduce (for bugs)

Command:

```
$ docker run -p 3000:3000 betterpt/patientapp-dev-nextjs:latest
```

Contents of my `Dockerfile`:

```
FROM node:alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY . /usr/src/app
RUN npm install

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
```

Contents of my `server.js` file:

```
const express = require('express');
const next = require('next');
const webpack = require('webpack');
// const remotedev = require('remotedev-server');
const routes = require('./dist/routes');
const { parse } = require('url');
const minifyJsPlugin = require('babel-minify-webpack-plugin');

const env = process.env.NODE_ENV || 'development';

const app = next({
  dev: env === 'development',
  dir: `${__dirname}/dist`,
  conf: {
    webpack: function(config) {
      return {
        ...config,
        externals: {
          'mapbox-gl': 'mapboxgl',
        },
      };
    },
    webpackDevMiddleware: (config) => {
      config.watchOptions = {
        poll: 1000,
        aggregateTimeout: 300,
      };
      return config
    }
  },
});

const handler = routes.getRequestHandler(app);

const PORT = 3000;
console.log(PORT);

app
  .prepare()
  .then(() => {
    express()
      .get('*', (req, res, next) => {
        if (req.url === '/robots.txt') {
          return res.sendFile(`${__dirname}/dist/static/robots.txt`);
        }
        if (req.url === '/video-sitemap.xml') {
          return res.sendFile(`${__dirname}/dist/static/video-sitemap.xml`);
        }
        if (req.url === '/sitemap.xml') {
          return res.sendFile(`${__dirname}/dist/static/sitemap.xml`);
        }
        next();
      })
      .use(handler)
      .listen(PORT);
  })
  .catch(ex => {
    console.error(ex.stack);
    process.exit(1);
  });
```

## Context

I am unable to run a development environment with Docker.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  4.0       |
| node    |  8.40       |
| OS      |   macOS High Sierra      |
| browser |    Chrome     |
| etc     |         |

**Comment by Fallion** [comment]
Docker needs to have your local files mounted as a volume. When you run the docker it copies the files into itself and runs that. It does not sync with your filesystem. 

https://docs.docker.com/engine/admin/volumes/volumes/

Reason for this is so that the image is self-contained and ready to be shipped.

**Comment by Fallion** [comment]
http://www.summa.com/blog/docker-for-developers-hot-module-reloading-live-editing-in-containers

**Comment by damianesteban** [comment]
Thanks. I am mounting the volume but now it is hot reloading very slowly, and I periodically get errors like this:

```
http://localhost:3000/_next/30360fad-5525-4f39-82da-a24e10f4dfc4/webpack/f88614b8efb1fd5899ce.hot-update.json 404 (Not Found)
```

Any idea on why this is happening?

**Comment by Fallion** [comment]
Well apps running in Docker are generally going to be substantially slower. 

How many things are you mounting as a volume? It's best to limit it to just like the src and pages folder and leave the compiled files in Docker. It may be that it's trying to sync and the IO isn't fast enough.

**Comment by damianesteban** [comment]
@Fallion I forgot to add `node_modules` to the volumes to be mounted. Now that I did it is very fast.

Thanks.
