### ISSUE TITLE
Automatically select port when starting

### ISSUE THREAD

**Issue by franzheidl** [zeit/next.js#358]
When starting next outputs this:

> Ready on http://localhost:3000

Even if something else is already running on 3000. It would be great if next could detect that and then automatically use the next sensible free port (e.g. 3001).

**Comment by MoOx** [comment]
> It would be great if next could detect that and then automatically use the next sensible free port (e.g. 3001).

I am currently using this technique on a project (Phenomic) and I can tell the UX is not the best. Especially if you are already using your own project, just in another terminal/tab and you forget it.

create-react-app is doing something different and tells you that something (and [who](https://github.com/facebookincubator/create-react-app/blob/05c3b55c62e5b5159382a024c21aa3527c95f1af/packages/react-dev-utils/getProcessForPort.js)) is using the port and offer you a way to adjust it.
This UX seems a better choice (source: https://github.com/facebookincubator/create-react-app/blob/dc6edce99bc999252757114cb54721928abc28f1/packages/react-scripts/scripts/start.js#L294-L318)

**Comment by franzheidl** [comment]
Totally agree! The UX you proposedis in fact better than automatically selecting selecting another port. The thing that was actually bugging me was the fact next.js does not reflect the fact 3000 is already in use, and thus creating output that was simply wrong.

**Comment by arunoda** [comment]
Related discussion: https://github.com/zeit/next.js/pull/68

**Comment by MoOx** [comment]
Oh that's exactly this. I guess this issue can be closed then?

**Comment by arunoda** [comment]
I hope so. Let's talk more on that PR.
