### ISSUE TITLE
Accessing query param from client-side undefined after redirect from link ?

### ISSUE THREAD

**Issue by frendyguo** [zeit/next.js#3581]
I've checked other issues, but just couldn't make it work. Please tell me where I went wrong

This is my custom route
```
// The path looks like '_4dCv' / '_dCbd'.
    server.get('/_:hash', (req, res) => {
        const mergedQuery = Object.assign({}, req.query, req.params)
        return app.render(req, res, '/my-page', mergedQuery);
    });
```

This is the <Link/> implementation
```
<Link href={'/my-page'} as={`/_${'ABCD'}`}>
    ....
</Link>
```

And finally, the 'page' implementation
```
static async getInitialProps({ req }) {
        if (req) {
            try {
               // Do some request with incoming params
            } catch(err) {
                ...
            }
        }

        return {}
    }

componentDidMount() {
  // How do I access the 'hash' param from here?
}
```

**Comment by pddigital** [comment]
You could pass the query param to the return statement in as a props var in GetIniitalProps. Or parse the URL. Either would get you the param to use client side.

**Comment by frendyguo** [comment]
@pddigital I tried, but query just returned empty object `{}`

**Comment by pddigital** [comment]
why do you have the try and catch block?

**Comment by frendyguo** [comment]
Sorry, forgot to remove it, I used it for async/await network call. But still, it doesn't matter right ?

**Comment by pddigital** [comment]
I'd try to use the example from the repo and see if that works. https://github.com/zeit/next.js/blob/canary/examples/parameterized-routing/server.js

**Comment by frendyguo** [comment]
Ahh, found it, the problem wasn't the server after all, turns out, I have to put the query for the 'href' in my <Link /> implementation

```
<Link href={'/my-page?hash=ABCD'} as={`/_${'ABCD'}`}>
    ....
</Link>
```

@pddigital Thanks mate, I really appreciate it.

Closing
