### ISSUE TITLE
How to navigate to a dynamic url ?

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#3583]
I have an issue while trying to create links to navigate in my app.

I have this setup in my server.js 

```javascript
server.get('/:post', (req, res) => {

     if(req.params.post.length > 0){
      return app.render(req, res, '/post', req.query)
    }
    return app.render(req, res, '/', req.query) 

  })
```

However when i click a link from a different path, the app render the index page instead of my post page

```javascript
const href = {pathname:'/', query:{post:'randomPost'}}
  const as = '/randomPost'
title = <Link href={href,as}>My Link</Link>
```

also when i try this, 

```javascript
  const href = '/randomPost'
title = <Link href={href}>My Link</Link>
```

my app has a strange behavior, first it lead me to a 404 not found page and then redirect me to the expected page.

Any suggestions ?

**Comment by arefaslani** [comment]
@jackmatrix You can use [next-routes](https://github.com/fridays/next-routes) to create dynamic routes. We've created a [Next Boilerplate](https://arefaslani.github.io/next-boilerplate) that is configured with next-routes and many more features. Check it out :)

**Comment by tuanhuu** [comment]
> @jackmatrix You can use [next-routes](https://github.com/fridays/next-routes) to create dynamic routes. We've created a [Next Boilerplate](https://arefaslani.github.io/next-boilerplate) that is configured with next-routes and many more features. Check it out :)

Hi, how to pass title to url, like "/this-is-reable-link" but can get it from it to query data. I think it should be "/this-is-realbe-link.123" then get 123 is id

**Comment by arefaslani** [comment]
@tuanhuu If I understand you correctly, you want to pass your page title as a query parameter or path variable.

1. Send title as path variable:
    - define routes
      ```javascript
      const routes = module.exports = require('next-routes')()
      routes
        .add('blog', '/blog/:title')
      ```
    - go to the route (e.g. /blog/this-is-blog-title)
    - Access the title variable in pages
      ```javascript
      import React, { Component } from "react";

      export default class extends Component {
        static getInitialProps(ctx) {
          return { url: ctx.url };
        }

        render() {
          const { url: { query: { title } } } = this.props
          return (
            <div>This is page title: {title}</div>
          )
        }
      }
      ```
      It will show `This is page title: this-is-blog-title` in the browser
2. send title as query parameter:
go to /blog?title=this-is-blog-title
```javascript
import React, { Component } from "react";

export default class extends Component {
  static getInitialProps(ctx) {
    return { url: ctx.url };
  }

  render() {
    const { url: { query: { title } } } = this.props
    return (
      <div>This is page title: {title}</div>
    )
  }
}
```
It will show `This is page title: this-is-blog-title` in the browser

In this example I used node `http` module for creating http server. You can use express if you like. But then you should change `getInitialProps` function so that it returns `req` object instead of `url`.
