### ISSUE TITLE
Side effects of using config.pagesGlobPattern (Possible Bug?)

### ISSUE THREAD

**Issue by moaxaca** [zeit/next.js#3587]
I've dug through the code and found that the pagesGlobPattern may not be fully be supported. When building my next server in develop it doesn't recognize my pagesGlobPattern. 

I've traced that down to this webpack configuration: 
https://github.com/zeit/next.js/blob/e179c98aa8469a2978137dc09a23184cafe5ce9d/server/build/webpack.js#L35-L39

Was it intentional to omit the pageGlobPattern while building in develop?

I have a custom server that is constructed using an isDevelop flag and it doesn't play well with this setting.

Here's an example: 
```
const next = require('next');
const nextConfig = require('./next.config');

/**
 * @param isDevelop {boolean}
 * @return {next.Server}
 */
module.exports = isDevelop => next({
  dev: isDevelop,
  quiet: true,
  conf: nextConfig,
});
```

Also, I found when building using the production build command:
```
NODE_ENV=production next build .
```
 I get a nasty error `Couldn't find a `pages` directory. Please create one under the project root`.

This problem is caused by a static check for pages directory:
https://github.com/zeit/next.js/blob/72827d25cb5990156436d5fffc4bd3ab7a4bdd38/bin/next-build#L37-L43

Again, I find myself wondering if this was intentional or a symptom of still being in development. 

I completely understand that this feature may be in development, and I am happy to help with its implementation. I am more worried about the intent around its design, and if it will fulfill my use case.

**Comment by timneutkens** [comment]
Please see https://github.com/zeit/next.js/issues/3570
