### ISSUE TITLE
Is there a way to know if we're coming back through browser history?

### ISSUE THREAD

**Issue by steeeeee** [zeit/next.js#3591]
Hi there, I'm trying to find a way to know if i'm coming through browser history.
The page gets its initial data through custom routing, eventually fetching it on its own if the
variable is empty. 

```javascript

class Index extends Component {
  static async getInitialProps ({ query, store }) {
    const loc = store.getState().localization
        
    let pageData = query.initialData
    
    if (!pageData) {
      const Fetch = new ApiGetHome(`${loc.region}/${loc.language}`)
      const res = await Fetch.getData()
      pageData = res.response[0]
    }

    // destructuring response data
    const { title, slider, main, footer } = pageData

    [...]
```
Navigating to an Internal URL, and then coming back from browser history, I think that getting a variable like `isFromHistory` or something similiar could be useful to prevent a new data fetch.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by timneutkens** [comment]
`onBeforePopState` was recently added to the router events which is only triggered when going back
