### ISSUE TITLE
with-apollo-and-redux is out of date

### ISSUE THREAD

**Issue by goldensunliu** [zeit/next.js#3593]
Now that react-apollo is in 2.0 query reducers are removed since redux is no longer used in react-apollo. The code here won't do much help with the latest react-apollo lib

code reference
https://github.com/zeit/next.js/blob/93990ab3fcae1a7e9cabc16e4153738c54e230b2/examples/with-apollo-and-redux/lib/initRedux.js#L16

related to reducers removal https://www.apollographql.com/docs/react/2.0-migration.html#reducers

**Comment by malimichael** [comment]
This example has been recently updated to use 2.x.x https://github.com/zeit/next.js/blob/canary/examples/with-apollo-and-redux/lib/initRedux.js - See #3463 as I believe there is still an issue accessing redux store

**Comment by vjpr** [comment]
There is still a bug: https://github.com/zeit/next.js/commit/46b57a6effa5f9c4f5ab043e682970bd5b5ae311#commitcomment-27133465
