### ISSUE TITLE
Can not load JSX files via custom .babelrc configuartion

### ISSUE THREAD

**Issue by S-Cardenas** [zeit/next.js#3598]
I am trying to use the .jsx file type and have created a custom .babelrc file as per the documentation (see below).

```
{
  "plugins": [
    ["transform-react-jsx", {
      "extensions": [".jsx"]
    }]
  ],
  "presets": [
    "next/babel"
  ]
}
```

However with the above .babelrc file I receive the following error:

<img width="1608" alt="screen shot 2018-01-20 at 2 11 24 pm" src="https://user-images.githubusercontent.com/14102289/35187079-2a20c8c8-fdec-11e7-8bb6-00e568ec1178.png">

Can someone point me in the direction as to what I am doing wrong to get .jsx files to load properly?

Cheers,
Stefan

**Comment by sergiodxa** [comment]
JSX files support is [already built-int](https://github.com/zeit/next.js/pull/3376). You don't need to add anything to Babel.

**Comment by S-Cardenas** [comment]
Hey. I have the latest version of next.js and I assure you that I am seeing that error even when I don't include a custom .babelrc file. Here is my package.json:

```
{
  "name": "web_app",
  "version": "1.0.0",
  "description": "Web App (Next.js &amp; React.js)",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "next"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/grafiti-io/web_app.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/grafiti-io/web_app/issues"
  },
  "homepage": "https://github.com/grafiti-io/web_app#readme",
  "dependencies": {
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "express": "^4.16.2",
    "isomorphic-unfetch": "^2.0.0",
    "next": "^4.2.3",
    "next-redux-wrapper": "^1.3.5",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-devtools-extension": "^2.13.2",
    "redux-thunk": "^2.2.0"
  }
}

```
