### ISSUE TITLE
Development workflow breaks when using .jsx extension for pages

### ISSUE THREAD

**Issue by voydz** [zeit/next.js#3599]
When using the .jsx extension for pages the development workflow (`node server.js`) breaks. 

* The browser prints an error in the console.
* Components on this page will not work.
* React DevTools won't work.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

There should be no difference in behavior, as when I am using the .js extension for pages.

## Current Behavior

1. Browser prints the following error in the console:

```
index:1 GET http://localhost:3000/_next/-/page/index.js net::ERR_ABORTED
index:14 GET http://localhost:3000/_next/-/page/index.js net::ERR_ABORTED
```

**NOTE:** If I try to open these files in a new tab I am getting a regular 404.

2. React Components on this page won't execute a bit of code. 
3. React DevTools can not connect to react.

## Steps to Reproduce (for bugs)

1. Fire up a new nextjs project
2. Create a `index.jsx` with some dummy components
3. Start your dev env with `next`
4. Open the page in the browser

## Context

I like having my files that actually contain jsx to be also named with the corresponding extension.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  4.4.0-canary3 |
| node    |  9.4.0 |
| OS      | windows 10 1709 (build 16299.192), osx 10.13.2  |
| browser |  chrome 63.0  |
| etc     |  linux subsystem for windows, same issue happens with cmd, tho  |

**EDIT:** Verified the same behavior on a mac.

**Comment by dmurawsky** [comment]
Hey @voydz , did you follow this example for your setup: https://github.com/zeit/next.js/tree/canary/examples/with-typescript

**Comment by voydz** [comment]
Hi @dmurawsky, I am not using typescript. 

These are plain javascript files containing jsx. This feature was introduced with PR https://github.com/zeit/next.js/pull/3376 and is actually a part of typescript support (#2391) but has nothing to do with it in the first place.

**Comment by mgamperl** [comment]
same issue here and I have the exact same problems and errors as described by @voydz 

next | 4.4.0-canary.3
-- | --
node | 8.8.0
OS | windows 10 1709 (build 16299.192)
browser | chrome 63.0
etc | cmder in windows

**Comment by timneutkens** [comment]
Will probably be fixed when https://github.com/zeit/next.js/pull/3578 is released.
