### ISSUE TITLE
Webpack outputs absolute module paths

### ISSUE THREAD

**Issue by benhjames** [zeit/next.js#360]
So this is a problem deploying to Heroku as mentioned in #198, where babel-loader transforms paths to be absolute, causing issues when running `next` from a different directory to which it is built.

```
import css from 'next/css'
```

Goes through babel-loader and gets turned into the absolute:

```
import css from '/builddir.../dist/lib/css'
```

Which won't resolve once the app is launched onto the dyno since either:

a) `/builddir.../` doesn't exist anymore if it's built on Heroku
b) `/builddir.../` doesn't exist at all if it's built locally and pushed up to Heroku

I'm kind of wondering why aliasing is needed when `next/css` can just resolve immediately to `node_modules/next/css`. I would have suggested removing the aliasing but that seems to cause problems with local tests and the error pages not resolving since (obviously) there's no `next` in `node_modules` inside itself.

Thoughts? :)

**Comment by nkzawa** [comment]
A simple solution would be to set `NODE_PATH` to `next/node_modules`, though it causes to allow `require` unintended modules.

**Comment by arunoda** [comment]
I think we are talking about the same topic in https://github.com/zeit/next.js/issues/198
So, I'm gonna close this.
