### ISSUE TITLE
suicrux example

### ISSUE THREAD

**Issue by cyrus-za** [zeit/next.js#3601]
Check the below issue on their repo. If we can get a example going with this it would be amazing. They using quite a few good packages that does some nice groundwork. I reckon the combination with nextjs could be a perfect fit

https://github.com/Metnew/suicrux/issues/165

**Comment by cyrus-za** [comment]
I understand that it is boilerplate. I just figured the nextjs community could help with a fork of that or some example as I am not sure how to map the webpack config over to next.config and so forth.

**Comment by timneutkens** [comment]
When https://github.com/zeit/next.js/pull/3578 lands you'll be able to use webpack loaders with Next. The title on their repository says: `[RAZZLE INTEGRATION SOON]` so i guess they've decided to use razzle instead of next.js.
