### ISSUE TITLE
How to stop the auto reload _error.js file in next js

### ISSUE THREAD

**Issue by ranjeetk3** [zeit/next.js#3602]
How to stop the auto reload page _error.js file in next js

**Comment by timneutkens** [comment]
Please provide a full explanation based on the issue template.

**Comment by ranjeetk3** [comment]
Hi, Sorry I was not able to brief at top. My Query is ..
How Can **I Integrate 404 page in the next.js Framework, if routing for any specific URL is not defined**. Currently we are getting response _Internal server error,_ this we want to replace to 404 page and the same if URL routing not defined.
Please review and Let us know your suggestion regarding same.
