### ISSUE TITLE
Cannot back if handle pages of 2 routes are the same 

### ISSUE THREAD

**Issue by phongtattuan** [zeit/next.js#3606]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1. I have 2 pages on pages folder: `category.js`, `detail.js`
2. Open browser 
3. I go to `/category`
4. Then go to `/detail?id=1`
5. Then go to `/detail?id=2`
6. Press back button on browser -> **nothing happen**
7. Press back button again -> it go to `/category`

Note: I'm using `<Link>` component to handle the route change

## Current Behavior

Cannot back to page `/detail?id=1`

## Expected Behavior

Can back to page `/detail?id=1`
 

Thanks.

**Comment by pddigital** [comment]
Post your GetInitialProps, could be there.

**Comment by phongtattuan** [comment]
@pddigital it's not call `getInitialProps` when back button is pressed

**Comment by pddigital** [comment]
We need a little more information to be able to help you here... on how your routes are setup, how your Link component is setup, and how you're fetching data to populate your page template, if the expected behavior is that the page data is different based on the query params...

**Comment by timneutkens** [comment]
Thanks for your report,
Please provide a minimal reproducible repository so that we can debug 🙏
