### ISSUE TITLE
What is the Release Cycle for Nextjs

### ISSUE THREAD

**Issue by timurista** [zeit/next.js#3609]
I want to use universal webpack in this PR: https://github.com/zeit/next.js/pull/3578 but I don't know when the release cycle is for nextjs version 5.0. Anyone have any idea when universal webpack can be loaded?

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Context
I want to use universal webpack loader to load in babel and use es6 on ssr.

**Comment by timneutkens** [comment]
> I want to use universal webpack loader to load in babel and use es6 on ssr.

ES6 is supported by default in Next.js

Regarding the PR. You can expect the pull request to be merged once all tests are fixed. I can't share a definitive timeline.

**Comment by alexindigo** [comment]
@timneutkens Does it mean other PRs are hold until all that resolved? Or there is a chance for other PRs in good standing to go through? Thank you.

**Comment by timneutkens** [comment]
Yes @alexindigo, since universal webpack involves a *lot* of changes. I'll be reviewing your PR after shipping universal webpack 👍

**Comment by alexindigo** [comment]
Perfect. Thanks @timneutkens 

Btw, we've been playing with some 5-alpha version and seems like `dynamic` functionality is broken as well us `next-routes` support. Is it a final state for those parts of the system and we should start fixing it or there are still some changes in the pipeline to make them to work again?

**Comment by timneutkens** [comment]
@alexindigo as stated in the pull request it's a `WIP` => work in progress. The alpha releases were to test functionality related to npm modules and loaders. Arunoda fixed the dynamic imports yesterday, there's 8 tests left to fix which both Arunoda and me are working on 👍

**Comment by alexindigo** [comment]
Perfect, that what I was thinking, just wanted to double check it’s not new state of things. Thank you.
Can’t wait for the new cool :)
