### ISSUE TITLE
Integrate 404 page in the next.js Framework,

### ISSUE THREAD

**Issue by ranjeetk3** [zeit/next.js#3610]
How Can I Integrate 404 page in the next.js Framework, if routing for any specific URL is not defined. Currently we are getting response Internal server error, this we want to replace to 404 page and the same if URL routing not defined.

Please review and Let us know your suggestion regarding same.

**Comment by sergiodxa** [comment]
You can customize the error page -> https://github.com/zeit/next.js#custom-error-handling
