### ISSUE TITLE
Is routing without the URL possible?

### ISSUE THREAD

**Issue by sean256** [zeit/next.js#3614]
I'm looking to manage some of my routes based on non-url states. I'm building a sort of interactive mobile game and each players game page will be a consistent URL like `/game/some-uuid`

Based on some internal 'game state' I would like to route the app to a couple of different pages without changing the URL. I would like to do this to take advantage of NextJS's awesome code splitting.

Is this possible?

**Comment by sergiodxa** [comment]
You can keep the state of what to show inside a component state and then based on that decide what to render and get the code split usind dynamic imports.

Basically don't use pages for that, they rely on the URL, but create a single page with the state and the dynamic imports.

**Comment by sean256** [comment]
Perfect! And it looks like you guys have great example code for that as well. Thank you!
