### ISSUE TITLE
Error while creating npm run build in next,js

### ISSUE THREAD

**Issue by ankitachetu** [zeit/next.js#3615]
I am getting following error below while creating a Next,js build, as follows:-

> Using external babel configuration
> location: "D:\xampp\htdocs\gitNextTeo\theelegantoffice\.babelrc"
> Using "webpack" config function defined in next.config.js.
Total precache size is about 800 kB for 40 resources.
> Failed to build on C:\Users\RANJEE~1\AppData\Local\Temp\b158b02b-ff86-4331-9411-185b8c5d8679
{ Error: commons.js from UglifyJs
Name expected [commons.js:67915,4]
    at D:\xampp\htdocs\gitNextTeo\theelegantoffice\node_modules\next\dist\server\build\index.js:181
    at D:\xampp\htdocs\gitNextTeo\theelegantoffice\node_modules\webpack\lib\Compiler.js:272:15
    at Compiler.emitRecords (D:\xampp\htdocs\gitNextTeo\theelegantoffice\node_modules\webpack\lib\C
    at D:\xampp\htdocs\gitNextTeo\theelegantoffice\node_modules\webpack\lib\Compiler.js:265:12
    at D:\xampp\htdocs\gitNextTeo\theelegantoffice\node_modules\webpack\lib\Compiler.js:360:11
    at next (D:\xampp\htdocs\gitNextTeo\theelegantoffice\node_modules\tapable\lib\Tapable.js:218:11
    at Compiler.compiler.plugin (D:\xampp\htdocs\gitNextTeo\theelegantoffice\node_modules\webpack\l
    at next (D:\xampp\htdocs\gitNextTeo\theelegantoffice\node_modules\tapable\lib\Tapable.js:220:14
    at D:\xampp\htdocs\gitNextTeo\theelegantoffice\node_modules\sw-precache-webpack-plugin\lib\inde
    at <anonymous>
  errors: [ 'commons.js from UglifyJs\nName expected [commons.js:67915,4]' ],
  warnings: [] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextteo@0.0.1 build: `cross-env NODE_ENV=production next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nextteo@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ranjeetk3\AppData\Roaming\npm-cache\_logs\2018-01-24T09_46_12_903Z-debug.log

So please help us what we can do for the following, we have also installed uglifyJs package, but nothing has been impacted for the same. 

Your Quick Response will be highly appreciable, Thanks..!

**Comment by timneutkens** [comment]
Please provide a minimal reproduceable example, it's impossible to judge what's going wrong based on the logs 👍
