### ISSUE TITLE
Custom Error Handling page Keeps on loading after 3 seconds, hence unable to render on another link via click

### ISSUE THREAD

**Issue by ankitachetu** [zeit/next.js#3616]
Hi, I have defined my custom error handling page as per in your description related to Next.js as below:-

> 404 or 500 errors are handled both client and server side by a default component error.js. If you wish to override it, define a _error.js in the pages folder:
> 
> import React from 'react'
> 
> export default class Error extends React.Component {
>   static getInitialProps({ res, err }) {
>     const statusCode = res ? res.statusCode : err ? err.statusCode : null;
>     return { statusCode }
>   }
> 
>   render() {
>     return (
>       <p>
>         {this.props.statusCode
>           ? `An error ${this.props.statusCode} occurred on server`
>           : 'An error occurred on client'}
>       </p>
>     )
>   }
> }

But the **error page keeps on autoloading after 3 seconds**, I don't want this error page to autoload which causes hindrance in the application for smooth operation.
Please review and Let us know your suggestion regarding same, Your Quick Response will be highly appreciable.. Thanks!

**Comment by timneutkens** [comment]
Please provide a minimal reproduceable example 👍
