### ISSUE TITLE
[Noob Developer] Integrating things like ParcelJS web app bundler with NextJS 

### ISSUE THREAD

**Issue by lightswarm124** [zeit/next.js#3619]
I've seen guides on how do the integration with the standard "create-react-app" framework. I'm hoping to do the same with a NextJS project I'm working on right now. Could anyone point me in the right direction?

**Comment by sergiodxa** [comment]
Next.js comes with webpack, you don't need (and can't change) the module bundler, just customize the webpack configuration.

**Comment by lightswarm124** [comment]
The features I'm looking for is more so the Rust integration. I'm working on an Ethereum Blockchain-based application using NextJS, and I'm exploring Rust to handle much of the critical backend calculations. Parcel recently posted a [blog](https://medium.com/@devongovett/parcel-v1-5-0-released-source-maps-webassembly-rust-and-more-3a6385e43b95) on combining Rust/JavaScript/WebAssembly.  That integration is basically what I'm trying to seek

**Comment by malimichael** [comment]
@sergiodxa chances of moving over to parcel in the future?

**Comment by sergiodxa** [comment]
@lightswarm124 use Rust to create an API and fetch it from Next.js in `getInitialProps`. That's the best thing if you're doing expensive calculations.

@malimichael I don't think so, we use a lot of custom configurations in Next.js to be able to use Parcel, but it depends if they allow custom configs in the future.

**Comment by timneutkens** [comment]
We're not planning to integrate parcel in the short term. Maybe in the long term 👍
