### ISSUE TITLE
3.2.3 is listed as the latest release in https://github.com/zeit/next.js/releases

### ISSUE THREAD

**Issue by benatkin** [zeit/next.js#3622]
The latest stable release of Next is 4.2.3, but 3.2.3 is listed as the latest release in https://github.com/zeit/next.js/releases

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

The latest release on the releases page should be 4.2.3

## Current Behavior

[The latest release on the releases page is 3.2.3](https://github.com/zeit/next.js/releases)

It looks like maybe the security release was backported which was why the new version was released.

## Steps to Reproduce (for bugs)

N/A

## Context

I was upgrading next.js in my package.json and needed to know what number to upgrade it to.

## Your Environment

N/A

**Comment by timneutkens** [comment]
This is because 3.2.3 was backported after the patch was released. Unfortunately there's no way to update the latest release on github without doing a new release. I've added a comment to the release notes of 3.2.3

**Comment by dav-is** [comment]
This is why you don’t use “latest” in the package.json. This issue broke all the examples...

**Comment by timneutkens** [comment]
@dav-is I'm not following. this is unrelated to npm, where the correct version is `latest` 🤔 http://npmjs.com/next

**Comment by dav-is** [comment]
https://github.com/zeit/next.js/blob/canary/examples/custom-server-express/package.json#L11

Several (if not all) of the examples use this. Running npm downloaded version 3.2.3 and React 16 which are not compatible with each other. If it was set to “next”: “^4.0.0”, this wouldn’t have been an issue.
