### ISSUE TITLE
Rename `with-redux` to `with-redux-wrapper`

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#3624]
I loved the old examples because they were explicit and you could look at the `react-redux` documentation and then look at the `with-redux` example and see how it fits together.

Using `next-redux-wrapper` obfuscates that and the [source](https://github.com/kirill-konshin/next-redux-wrapper/blob/master/src/index.js) is not as easy to follow as the old examples.

So I propose going back to https://github.com/zeit/next.js/blame/00590d71811eadc32c5d2d334bda09d7b682067c/examples/with-redux/pages/index.js for `with-redux`. Providing a HOC wrapper in the example source code would be a better approach. It means that it has to be simple, and avoids the verbosity that comes from the configurability of a published library.

When you start wanting to combine other things into redux like Apollo, Saga, etc. it starts getting complicated having these magical wrappers involved, and it starts feeling like a framework.

**Comment by sergiodxa** [comment]
> it starts feeling like a framework
Next.js is technically a framework.

But yeah I agree with your point. We should have both the wrapper and the manual version and link them.

Do you want to send a pull request with this?

**Comment by omaksi** [comment]
I agree with OP, especially with `next-redux-wrapper` source being not easy to follow and extend. 

I could create a PR changing the `with-redux` to a basic manual HOC, and change the current example to `with-redux-wrapper`

**Comment by timneutkens** [comment]
Go ahead 👍
