### ISSUE TITLE
introducing env-hoc lib / feature request

### ISSUE THREAD

**Issue by supukarmin** [zeit/next.js#3625]
Made a library for easier working with cookies / supported languages / userAgent / ipAddress in Next.js (works also with After.js). Check it out: [env-hoc](https://github.com/supukarmin/env-hoc).

While I was writing the library I thought about the idea of having a specification for getInitialProps, would make it easier to write libraries and ensure that in the near future there won't be a dozen of frameworks with there own getInitialProps implementation. The most important thing would be to ensure the arguments passed to getInitialProps are the same and that they support Promises / async. What's your opinion? And what do you think about implementing an additional prop to the getInitialProps object named serverProps, which gives access to the result of server-rendered getInitialProps instead of accessing the props somewhat hacky through `window.__NEXT_DATA__.props`. For libraries, there isn't really any other solution and the props are so-or-so available.

**Comment by sergiodxa** [comment]
Well in the initial client-side render getInitialProps is not called so there's is no reason to pass serverProps there as far as I remember.

You can check returning `{ isServer: typeof window === "undefined" }` and it will keep as true after the page loads completely.

**Comment by supukarmin** [comment]
@sergiodxa I meant something else, I'll give you an example:
```js
static async getInitialProps(args) {
  if (typeof window === 'undefined') {
    return { ipAddress: args.req.connection.remoteAddress }; //assuming the property is always available
  } else {
    const ipAddress = window.__NEXT_DATA__.props.ipAddress;
    return { ipAddress };
  }
}
```
The problem is, that on client-side it is very hard to get the IP address without a server (I had seen once an example with mocking a request, but it's expensive and doesn't work in old browsers). Of course, that's just an example, there are other properties from the request object which share the same problem. When someone now switches to a page, which did not perform a server-side rendering and wants to have access to the IP address, he can't get it on that page without saving it before somewhere globally. So, currently, someone must save such properties after server-rendering (probably using `componentDidMount`) somewhere outside and access it then from there, let's say within a redux store or just directly somewhere into the windows object, but for a library, this isn't really an option and using `window.__NEXT_DATA__.props` isn't an official API.
So, introducing serverProps will make it easy to use properties from server-side rendering, without having to introduce for every library a *store* in the `windows` object or relay on existing stores. I think the benefits for libraries are clear and it will be very easy to integrate into Next.js, just map `window.__NEXT_DATA__.props` to `serverProps`. It's just about having an official & stable API. This feature becomes much more interesting when we consider the fact, that there will be in the future more frameworks like Next.js using getInitialProps. Currently, my code looks like this: [/supukarmin/env-hoc/blob/master/src/utils/getInitialServerProp.js](https://github.com/supukarmin/env-hoc/blob/master/src/utils/getInitialServerProp.js). This could become worse in the future. If every such framework integrates serverProps it would be much easier.

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js#exposing-configuration-to-the-server--client-side
