### ISSUE TITLE
next.js when load /static/ files like images got 404 return in production

### ISSUE THREAD

**Issue by Deval520** [zeit/next.js#3628]
how to resolve it ?

**Comment by timneutkens** [comment]
Please Provide a minimal example of how to reproduce.

**Comment by robdmoore** [comment]
I'm seeing this same problem. Been trying to debug why it's happening. Will keep trying and see if I can get a minimum reproduction. Funnily enough I have the same code running with it working and a fresh checkout causes this to happen - very confusing.

**Comment by mikemclin** [comment]
Same thing is happening to me.  `next build` is not copying the `static` directory from my project root into the dist folder.  I added a build step where I manually copy the `static` directory to remedy the issue in the meantime.

**Comment by bryan** [comment]
How did you guys resolve this? I'm getting the same 404 when in development for **image files only**, but displaying the static image is working in development.

I've tried adding the following code to my server to no avail:
`server.use('/static', express.static(path.join(__dirname, '/../static')));`

I'm on the latest canary.16.
