### ISSUE TITLE
Add crossorigin attribute to NextScript

### ISSUE THREAD

**Issue by undirectlookable** [zeit/next.js#3630]
I'm using `assetPrefix` to serve my javascripts from a different domain. I need to add `crossorigin="anonymous"` attribute to these script tags in [NextScript](https://github.com/zeit/next.js/blob/4.2.3/server/document.js#L119) for error tracking. Otherwise, error details will not provided because of security reason.

I read the source code, seems no way to do that with `next.config.js`.

**Comment by dav-is** [comment]
Along with this, [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) support would be nice.
