### ISSUE TITLE
Update the api document, not just demos

### ISSUE THREAD

**Issue by mrdulin** [zeit/next.js#3631]
Is there an api document? I do not see.

1. ` app.render(req, res, '/b', query)`, yeah, the demo is used like this, so 90% people copy this.
I need an api document like `express.js`
`app.render(view, [locals], callback)`, each argument has been explained clearly.

2. `NextScript`, I search `NextScript` in readme,  It just write there. There is no explain.
So, maybe 95% people copy the demo to their project and don't know why.

and so on...

**Comment by timneutkens** [comment]
We're planning to add more documentation.
