### ISSUE TITLE
How to minify a next js app

### ISSUE THREAD

**Issue by bouzoumita** [zeit/next.js#3632]
Hi,  After creating our website with nextjs we ended with a large size about 5M sended to the user without minifaction. I flow the discution here #1195 in order to enable minifaction in nextjs but it does not solve the problem.
Please how enable minifaction on nextjs.

Thanks

**Comment by timneutkens** [comment]
Next.js apps are automatically minified in production (`next build` and then `next start`) it sounds like you're checking the bundles while in development mode. These have webpack related code and are not minified.

If you were running in production try using this blogpost to find outliers in the external modules you import: https://arunoda.me/blog/ssr-and-server-only-modules

**Comment by bouzoumita** [comment]
@timneutkens i used the webpack analyze to know the size of the app and webpack analyzer make a call to next build

**Comment by bouzoumita** [comment]
@timneutkens in a production build  when i inspect the source code the code is not minified (plenty of comments)
