### ISSUE TITLE
Production build is not minified

### ISSUE THREAD

**Issue by bouzoumita** [zeit/next.js#3636]
In #3632 I was told that next js minify every thing, but this is not the case for me, next js don't minify files, i created a repo (https://github.com/bouzoumita/minify-next-js) contain a project  with a large file about 300kb filled  with comments, when building it, next does not erase those comment and the size of the output still enormous ~800kb due to comments(without comment it is about ~300kb). Can someone please help me with this code and tell me how to make it shrink.

Thanks.

**Comment by ilionic** [comment]
I was actually looking into bundle sizes it and noticed same thing:
on `"next": "3.2.2",` 

![image](https://user-images.githubusercontent.com/1027871/35600069-479c715c-062c-11e8-93b6-c4864f001b2f.png)

on `"next": "4.4.0-canary.3",`

![image](https://user-images.githubusercontent.com/1027871/35600089-5fde0884-062c-11e8-99ab-2b3279410c71.png)

As you can see Parsed size is huge. 
I am using this trick for newer version of UglifyJSPlugin ( that supports ES6 ) otherwise build fails:

```
    if (!dev) {
      config.plugins.push(
        new UglifyJSPlugin({
          sourceMap: false,
          parallel: true,
        }),
      );
    }
```

**Comment by ticky** [comment]
I’ve been having similar troubles, and our bundle size has ballooned about 20% when upgrading to 5.0.0. Tree shaking (#2999) doesn’t seem to be occurring for us.

**Comment by arunoda** [comment]
We did some optimizations for uglifyjs focused on the build speed. (We simply do white space removing).
We may need to change some of those settings.

**Comment by sfrieson-tm** [comment]
I'm not even seeing white space removal right now.  From looking at the bundle, it looks like Webpack is being run in dev mode.

Do we have the ability to turn some of those optimizations back on?  Our gzipped bundle ballooned 67%.

**Comment by ticky** [comment]
@arunoda @timneutkens is there any update on this? I’m holding off on deploying 5.0 as this is a big jump

**Comment by timneutkens** [comment]
Try next@canary.

**Comment by ticky** [comment]
Ok, tested with canary:
**next 4.2.3**: 589.16 KB
**next 5.0.1-canary.15**: 695.54 KB (18% increase)

**Comment by tashburn** [comment]
I'm on `5.0.1-canary.17`, and my production build is not minified either.

**Comment by ufhy** [comment]
any progress??

**Comment by jimbojetlag** [comment]
Ok, this is not acceptable.

The whole point of using next is performance, and yet its 'optimized' production built is bigger than a diy webpack setup for a client side rendered react app.

This issues has been open for 5 months. Any comments from the authors?

**Comment by timneutkens** [comment]
Fixed in #4536

**Comment by r0b-** [comment]
I'm using latest canary version (6.1.1-canary.0) but build is not minified (js & css).
Do I have to add sth to one of the configs?

next.config:
```
const withTypescript = require('@zeit/next-typescript');
const withOptimizedImages = require('next-optimized-images');
const withCss = require('@zeit/next-css');
module.exports = withTypescript(withOptimizedImages(withCss()));
```

.babelrc:
```
{
  "presets": [
    "next/babel",
    "@zeit/next-typescript/babel"
  ],
  "plugins": [
    [
      "styled-components",
      {
        "ssr": true,
        "displayName": true
      }
    ]
  ]
}

```
Thanks!

**Comment by and3rsonsousa** [comment]
Using `cssnano` fixed this.
Here I am using TailwindCSS.

`module.exports = {
  plugins: [tailwind("./tailwind.config.js"), autoprefixer, nano]
};
`
