### ISSUE TITLE
Add support to work with yarn workspaces

### ISSUE THREAD

**Issue by matiasfh** [zeit/next.js#3638]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.
But I think that this issue https://github.com/zeit/next.js/pull/3319 can be related and maybe solve the problem.

## Current Behavior
Based on what I have:
I have a folder estructure working with `yarn workspaces` with multiple workspaces like:

|-- packages
|-- .babelrc
..
..
..
|----- shared
|-------- components // named @org/components
|-------- utils               // named @org/utils
|----- web
|------- app                  // named @org/mainApp
|--------- src
|------------ next.config.js
|------------ .babelrc
|----------- pages
....
...
|------- otherPackage // named @org/otherPackage

Where `app` folder is a next.js app that **import** code from the other components.

The dev mode of next is run from root folder using `npm run web` that call `next packages/web/app/src` to allow next to found the pages folder (and `next.config.js` and `.babelrc` )

After run and start compiling, and get the "success" mensaje, some errors arise in the console on web loaded.
Errors referring to the use of `type` and `import` keywords in the files that comes from the imported modules (modules named as `@org/` that lives inside the same repo but (maybe) in other workspaces).

This means that next webpack configuration is not transpiling the imported files. (the `babel-plugin-transform-flow-strip-types` is installed in packages/web/app and also in the root folder)

## Expected Behavior

Should not have any error with the imported files and works as expected (no problem with es6 and flow).

## Steps to Reproduce (for bugs)

1. Create a project with yarn workspaces activated
2. Create at least two workspaces
3. Create a package inside a workspace that run with next
4. Import file from other workspaces

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |       4.2.3  |
| node    |     9.3.0    |
| OS      |       macosx  |
| browser |       safari/chrome  |
| yarn     |     1.3.2    |

**Comment by bogdansoare** [comment]
Any news on this?

**Comment by HaNdTriX** [comment]
Next.js is working fine from my point of view.
I am about to add a working yarn workspace example. ⬆#5034

**Comment by beku8** [comment]
webpackDivMiddleware watch options are not working properly. This example is not picking up the changes from ```bar/``` directory. Should we open a new issue?
