### ISSUE TITLE
Nested Routes Missing In _next folder of static build

### ISSUE THREAD

**Issue by jakegibson** [zeit/next.js#3639]
## Expected Behavior
<Link href="/nested/page" > Should work for navigating to nested pages in static build. 

## Current Behavior
The Link component seems to depend on the _next folder.  This is generated correctly for a flat structure but nested pages are not created in the correct structure.  This can be manually fixed by created folders to match the nested structure and coping the files into it.  For example for the route:
'/account/refer': { page: '/refer' },
_next/currenthash/page/  will have refer.js in it but should have
_next/currenthash/page/account/refer.js

## Steps to Reproduce (for bugs)
1.  Currently using https://github.com/zeit/next.js/wiki/Centralizing-Routing but had the same issue with the standard static build routing
2.  create a page that in the pages folder
3. create a route that gives it a nested path '/account/refer': { page: '/refer' },
4. npm run build which runs "next build && next export"

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   4.2.3      |
| node    |  9.3.0       |
| OS      |    mac sierra     |
| browser |  firefox and chrome       |
| etc     |         |

**Comment by pencilcheck** [comment]
Looks like the issue is gone in next@5.0.1-canary.2, but is back on next@5.0.1-canary.5

**Comment by timneutkens** [comment]
Can you please provide a reproducible repository 🙏 Also try next@canary.
