### ISSUE TITLE
Some links in readme are broken.

### ISSUE THREAD

**Issue by Rokt33r** [zeit/next.js#3643]
https://github.com/zeit/next.js#importing-css--sass--less-files

It seems https://github.com/zeit/next-plugins doesn't exist anymore.

**Comment by timneutkens** [comment]
It does exist, it'll be public soon with the upcoming v5 release 👍

**Comment by Rokt33r** [comment]
How can I grab some news about v5?

**Comment by timneutkens** [comment]
Keep an eye out for https://github.com/zeit/next.js/releases 😄

**Comment by timneutkens** [comment]
And join https://zeit.co/chat 👍
