### ISSUE TITLE
Upgrade Apollo example to Apollo Client 2.0

### ISSUE THREAD

**Issue by billnbell** [zeit/next.js#3647]
https://github.com/zeit/next.js/tree/master/examples/with-apollo-and-redux

Please upgrade to Apollo 2.0 and probably add redux to it.

This will not work: <ApolloProvider client={client} store={store}>

Switch to:

<ApolloProvider client={client}>
  <Provider store={store}>
    ...
  </Provider>
</ApolloProvider>

**Comment by jonespen** [comment]
The example in the canary branch is Apollo 2.0: https://github.com/zeit/next.js/tree/canary/examples/with-apollo-and-redux
