### ISSUE TITLE
babel-transform-runtime adds `import` in modules that don't use es6

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#3650]
It's a known issue for webpack/babel-transform-runtime because webpack breaks when combining 2 types of modules and babel transpiles those fine. 

To reproduce:

```
// pages/index.js
import data from '../data'
export default () => <div>Hello world</div>
```

```
// data.js
module.exports = ''
Object.keys({}) // gets polyfilled by transform-runtime
```

Now when transpiled by babel this becomes (illustrational)

```
// data.js
import ObjecyKeysPolyfill from 'core-js/object/keys;
module.exports = ''
ObjecyKeysPolyfill({})
```

To solve this we can't enable transpilation of modules in babel, because that'd negate code splitting in webpack. which is one of the key features of Next.

It seems like the only way to solve this is to extend transform-runtime to detect commonjs vs es6 exports and then apply the right import type (`import` or `require`) to it.
https://github.com/webpack/webpack/issues/4039

create-react-app has disabled the polyfill/helpers transform which inlines all the polyfills and helpers.
https://github.com/facebook/create-react-app/blob/master/packages/babel-preset-react-app/index.js#L33-L40

**Comment by timneutkens** [comment]
When providing the following option to `@babel/preset-env` the same happens:
```
"useBuiltIns": "usage"
```

As pointed out by @mtoso

**Comment by KristerV** [comment]
Spent half a day on this, finally fixed with **`.babelrc`**
```
{
    "presets": [
        [
            "next/babel",
            {
                "preset-env": {
                    "modules": "commonjs"
                }
            }
        ]
    ],
    "plugins": []
}
```

Tried changing sourceType and didn't work.

Since finding this issue was a challenge on it's own, I'm going to leave the error I got for Googlers to find:

```
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

**Comment by timneutkens** [comment]
@KristerV I've hidden your comment as setting `modules` to `commonjs` is an anti-pattern, you disable webpack tree shaking by doing this.

**Comment by lydell** [comment]
I got this problem in _one single file_ – routes.js, using [nextjs-dynamic-routes](https://github.com/gvergnaud/nextjs-dynamic-routes).

I worked around the issue by switching to commonjs for _that file only:_

```
  "overrides": [
    {
      "test": "./routes.js",
      "presets": [
        [
          "next/babel",
          {
            "preset-env": {
              "useBuiltIns": "usage",
              // `useBuiltIns` adds `import` statements for polyfills,
              // but webpack does not allow assigning `module.exports` if a file
              // contains `import`, so transpile those added `import`s to
              // `require`.
              "modules": "commonjs",
            }
          }
        ]
      ]
    }
  ]
```
