### ISSUE TITLE
Link to next-css/sass/less in docs are broken

### ISSUE THREAD

**Issue by isaachinman** [zeit/next.js#3651]
## Expected Behavior

Docs are accurate.

## Current Behavior

Docs are inaccurate.

## Steps to Reproduce (for bugs)

1. Go here: https://github.com/zeit/next.js#importing-css--sass--less-files
2. Click any of the three css/sass/less links

Happy to put together a quick PR if someone can tell me where the relevant branch is located.

**Comment by Albert-Gao** [comment]
Duplicate #3643

**Comment by isaachinman** [comment]
@Albert-Gao Apologies. When is the release?

**Comment by Albert-Gao** [comment]
Quote from the owner one day ago:

> it'll be public soon with the upcoming v5 release
