### ISSUE TITLE
Hero image not rendered properly from next.js with style-jsx

### ISSUE THREAD

**Issue by Albert-Gao** [zeit/next.js#3653]
## Expected Behavior

The hero image should be shown on the page, and the text should be in the center of the image

## Current Behavior

The image is not there, and the texts are disappear.

## Steps to Reproduce (for bugs)

1. Create a component `components/Page.js`
```javascript
import Head from 'next/head';

const Page = ({title, children}) =>
  <div>
    <Head>
      <title>{title}</title>
      <meta name='viewport' content='width=device-width, initial-scale=1'/>
      <meta charSet='utf-8'/>
      <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css'/>
    </Head>
    {children}
  </div>;

export default Page;
```

2. Create `pages/index.js`
```javascript
import React from 'react';
import Page from '../components/Page';

const HeroImage = ({children}) =>
  <div className="hero-image">
    {children}

    {/*language=CSS*/}
    <style jsx>{`
      .hero-image {
        height: 50%;
        background: url("https://www.w3schools.com/howto/photographer.jpg") no-repeat center;
        background-size: cover;
        position: relative;
      }
    `}</style>
  </div>;

const HeroTitles = () =>
  <div className="hero-text">
    <h1>I am John Doe</h1>
    <p>And I am a Photographer</p>
    <button>
      Get Started
    </button>

    {/*language=CSS*/}
    <style jsx="">{`
        .hero-text {
        text-align: center;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        color: white;
      }
    `}</style>
  </div>;

const Index = () =>
  <Page title="project Help">
      <HeroImage>
        <HeroTitles/>
      </HeroImage>
  </Page>;

export default Index;
```

3. Run the app via `npm run dev`, no image there. Same for `build` then `start`.

4. Create a `index.html`, and everything is fine, the hero image is there at top and text are all right in the center.
```html
<html>
  <head>
    <title>project Help</title>

    <style>    
        .hero-image {
          height: 50%;
          background: url("https://www.w3schools.com/howto/photographer.jpg") no-repeat center;
          background-size: cover;
          position: relative;
        }

        .hero-text {
          text-align: center;
          position: absolute;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
          color: white;
        }
    </style>
    <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css'/>
  </head>
  <body>
    <main>
      <div class="hero-image">
        <div class="hero-text">
          <h1>I am John Doe</h1>
          <p>And I am a Photographer</p>
          <button>Get started</button>
        </div>
      </div>
    </main>
  </body>
</html>
```

## Context

Strange enough, after `next` has rendered the index page, if you find that `hero-image` class in developer panel, and try to disable and re-enable the one of the css properties. The image with all the text will be shown. But still not right, because the texts are not centered.

I already tried to `Empty cache and hard reload`, no luck.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    latest     |
| node    |   8.9.4      |
| OS      |     OS X  10.13.3   |
| browser |    Chrome 63    |
| etc     |         |

**Comment by lfades** [comment]
Hi Albert, I checked your code to see what's wrong and you're right, the same code in index.html and in Next doesn't behave in the same way, although my css knowledge is very basic I was able to notice that the `body` and `divs` inside had a height of 0 (like if they didn't have any content).

Changing `height: 50%` to `height: 50hv;` in `.hero-image` solved the issue (https://stackoverflow.com/questions/40490852/height-0-on-body)

btw the href to `semantic.min.js` is missing `https:`

**Comment by Albert-Gao** [comment]
@lfades Thanks for the help!

Yes, by giving that `.hero-image` a static height indeed solves the problem, a huge progress, but why? That 2 code seems identical, at least to me...

**Comment by lfades** [comment]
They are identical in code, but when you inspect them Next is adding new elements that change the final html

**Comment by Albert-Gao** [comment]
@lfades Thanks. So, as the problem solved practically.

I re-create the whole thing in `create-react-app`, seems the same result.... OK, so `next.js` is fine?

Should I close this issue?
Or it worths some digging to verify if it's a bug or not?

**Comment by timneutkens** [comment]
I guess we can close it. Pretty sure it's not an issue with Next 🙏
