### ISSUE TITLE
Styled Components: Global Styles (injectGlobal) In Wrong Order

### ISSUE THREAD

**Issue by julmot** [zeit/next.js#3654]
When I use `injectGlobal` to inject global styles using styled-components in e.g. the `_documents.js` the resulting `<style>` tag for global styles will be generated _below_ the component's `<style>` tag. Therefore global styles will override component styles. This should be turned around since global styles like e.g. normalize.css shouldn't override component styles.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

The `<style>` tag for global styles should be generated before the `<style>` tag of component styles

## Current Behavior

It's generated in the wrong order.

## Steps to Reproduce (for bugs)
Download this zip: [example.zip](https://github.com/zeit/next.js/files/1685672/example.zip)
This example is based on the example with styled-components.
Run `$ npm install` and open `localhost:3000`, then view the HTML source code.

This proofes that non-local CSS isn't generated at the top:

![topic](https://user-images.githubusercontent.com/8310677/35680830-ba11c6a8-075b-11e8-8649-1e8532c28d11.png)

## Context

I'm trying to add normalize.css at the very top of the HTML file. 

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4.2.3  |
| node    | 6.11.3 |
| OS      | Win 10 |
| browser | FF 58 |
| etc     |         |

**Comment by lucleray** [comment]
This issue is related to this : https://github.com/styled-components/styled-components/issues/1109

**Comment by timneutkens** [comment]
Thanks @lucleray sounds like an upstream issue.

**Comment by bartdominiak** [comment]
Hey, I'm facing with this issue. Tried to add `global.js` to a top of `_app.js` or `_document.js` and still getting wrong order.

**Comment by alanhr** [comment]
I have the same problem in my project, @bartdominiak  Did you find any solution ?

**Comment by bartdominiak** [comment]
@alanhr Yes. Just add `global.js` on top of your `index.js`

**Comment by alanhr** [comment]
@bartdominiak  add  the global.js in all of pages ?

**Comment by bartdominiak** [comment]
nope, I added it only to `index.js`, and its visible in other pages.

**Comment by alanhr** [comment]
Thanks @bartdominiak , I add in my Layout component  and now everything is ok

**Comment by clayhan** [comment]
@bartdominiak Just stumbled on this and I was wondering if you could clarify what exactly your global.js looks like/what it is? I'm also trying to have styled-components bring in normalize.css. Thanks a ton.

**Comment by VasilyMur** [comment]
@clayhan did you manage to figure it out? I'm having the same issue...

**Comment by VasilyMur** [comment]
@bartdominiak - could you share your global styles component?
