### ISSUE TITLE
Replace uglify?

### ISSUE THREAD

**Issue by lkostrowski** [zeit/next.js#3659]
I have faced the issue with production build. I don't know why, but Next's babel config didn't properly compile my source code, so I ended up with "unexpected token punc()" which is most likely not compiled source to ES5 (which is needed for UglifyJS).

I have been searching for issues and also tried to extend babel config with babel-preset-env (targets.uglifyjs = true), but actually it didn't work, nor es-2015 presets.

I have fixed this issue by extending webpack config with `BabiliPlugin` and removing UglifyJS. This is first issue I wanted to report... Moreover I think uglify should be removed if it doesn't support new JS syntax. I want to be able to specify what browsers I support.

I have also a problem to detect where and what caused the problem in my source.

Sorry if this issue has been already discussed.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by sergiodxa** [comment]
Next.js doesn't tranpile node_modules, you should be using a node_modules which is not transpiling properly it's own code.

About how to use Babili instead of Uglify add this to your `next.config.js`.

```js
const BabiliPlugin = require("babili-webpack-plugin");

module.exports = {
  webpack(config, { dev }) {
    // remove Uglify plugin
    config.plugins = config.plugins.filter(plugin => {
      return plugin.constructor.name !== "UglifyJsPlugin";
    });

    if (!dev) {
      // add Babili plugin
      config.plugins.push(
        new BabiliPlugin()
      );
    }

    return config;
  },
};

**Comment by lkostrowski** [comment]
```
Next.js doesn't tranpile node_modules, you should be using a node_modules which is not transpiling properly it's own code.```

But for with Babili it works, so why not use it by default? It's lottery when some package isn't compatible

**Comment by sergiodxa** [comment]
Check #1195
