### ISSUE TITLE
with-dynamic-import example won't compile

### ISSUE THREAD

**Issue by Terrycoco** [zeit/next.js#3662]
Following directions to clone and run with-dynamic import and run dev yields following error:

Module not found: Error: Can't resolve 'react-dom/lib/ReactReconciler' in '/home/terry/myProjects/next/with-dynamic-import/node_modules/next/dist/client'
 @ ./node_modules/next/dist/client/next-dev.js 5:23-63
 @ multi ./node_modules/next/dist/client/webpack-hot-middleware-client ./node_modules/next/dist/client/on-demand-entries-client ./node_modules/next/dist/client/next-dev.js

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

It should run without errors.

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     downloaded from examples repository   |
| node    |     8.0.0    |
| OS      |   ubuntu 16.04      |
| browser |   chrome      |
| etc     |         |

**Comment by timneutkens** [comment]
Just tried and I can't reproduce this. Looks like you're on an older version of next. Try upgrading next to `4.2.3`
