### ISSUE TITLE
SSR caching with embedded client side component

### ISSUE THREAD

**Issue by shauravg** [zeit/next.js#3666]
I read through the SSR caching example. I have a website where pages mostly static content (some pages serve content served from a headless CMS) but there is a header bar where the user can signup/login and when they do, the header bar changes to showing them their current favorites. I have this header bar in its own component which is imported using the dynamic() import so that its rendered client side. The authentication is handled via Auth0 and the component checks for the access token in local storage to figure out if there is an authenticated user and then renders appropriately. 

So my question is the best way to adapt the SSR caching example where the page has a client rendered component? It doesn't seem like I could use the app.renderToHTML() function.

**Comment by ivan-aksamentov** [comment]
You could selectively exclude components from server side rendering. That is, your can make the header bar to be rendered on client only, while everything else is be SSRed and cached. Check [examples/progressive-render](https://github.com/zeit/next.js/tree/master/examples/progressive-render).

**Comment by timneutkens** [comment]
The SSR caching example will still work fine for you, because you're not changing the server output based on the state, based on your description.
