### ISSUE TITLE
Is it possible to make a check (if else) in every page without coding it in each file?

### ISSUE THREAD

**Issue by farebord** [zeit/next.js#3671]
I'm having a little trouble and no answering on google. 

When I use CRA to built my frontend sites I used react router to handle routes and redux to push locations, so in that way in index.js I could check if user is authenticated in this way:

```
// Check if user is authenticated function
const userIsAuthenticated = (nextState, replace) => {
    if(!store.getState().user.isAuthenticated){
        replace('/ingresar?next='+nextState.location.pathname);
    }
};
ReactDOM.render(
<Router>
...
    <Route path="/search" component={Search} />
    <Route path="/edit/:pubId" component={EditPublication} onEnter={userIsAuthenticated} />
    <Route path="/:pubId/:url_title" component={Details} />
<Router>
)
```

Is it possible to make this on nextjs using nextjs/router?

Thanks.

**Comment by lfades** [comment]
By using next router: No, it's just a router

It's possible if you're using a custom server (Express, Koa, whatever) and then you just add a middleware before any of your routes (you can check the examples with custom servers and custom routing in `/examples`)

Also, if you don't want to use a custom server or don't know how to do authentication there then you can do your auth in `getInitialProps` or the `React Lifecycle`

**Comment by timneutkens** [comment]
The recommended way is to use a HOC https://github.com/zeit/next.js/tree/canary/examples/with-higher-order-component
