### ISSUE TITLE
NextJS aggressively tries to load unnecessary dependencies

### ISSUE THREAD

**Issue by lacymorrow** [zeit/next.js#3672]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Using the [`npm-name` module](https://github.com/sindresorhus/npm-name) outputs `true` or `false` in a next project.

## Current Behavior

Attempts to use `npm-name` result in the error:
```bash
This dependency was not found:  
* electron in ./node_modules/npm-name/node_modules/got/index.js  
To install it, you can run: npm install --save electron
```

## Steps to Reproduce (for bugs)
In a Next.JS project:
```js
import npmName from 'npm-name'
npmName('npm-name') // throws the error
```

## Context
Trying to use the `npm-name` module results in Next throwing an error because electron is not installed. I don't want to introduce electron to the project obviously, and looking through the [source of `got`](https://github.com/sindresorhus/got/blob/master/index.js#L90), I'm not sure why it's being required.

## Your Environment

| Tech    | Version |
|--------|---------|
| next     | 4.2.3                   |
| node    | 9.2.0                   |
| OS       | macOS 10.12.6   |
| browser | chrome63        |

Corresponding ticket with `npm-name`: https://github.com/sindresorhus/npm-name/issues/16
I believe this is a NextJS issue.

**Comment by lucleray** [comment]
Nextjs uses webpack that will analyze the code and bundle all the necessary packages.

So, in this case, I guess webpack will try to bundle electron since it's required in the [the source of got](https://github.com/sindresorhus/got/blob/master/index.js#L90).

Maybe you can fix that by adding some config to webpack to ignore electron package.

**Comment by lacymorrow** [comment]
@lucleray Thanks for shedding some light on this!

I believe you're correct in what's happening, it's an unfortunate side-effect.

I chose to use a different library that `got` for the HTTP request, rather than modifying my webpack config

**Comment by timneutkens** [comment]
`got` is for server side only. You need to use a universal fetching solution like `isomorphic-fetch` or `isomorphic-unfetch`
