### ISSUE TITLE
Uncaught DOMException: Failed to execute 'open' on 'Window': Unable to open a window with invalid URL

### ISSUE THREAD

**Issue by safeimuslim** [zeit/next.js#3673]
Hi, anyone help me?
I got error when implemented firebase google login, how to fix?

Uncaught DOMException: Failed to execute 'open' on 'Window': Unable to open a window with invalid URL

**Comment by timneutkens** [comment]
Please provide a full repository to reproduce, this is most likely unrelated to next though.
