### ISSUE TITLE
@zeit/next-sass plugin doesn't work.

### ISSUE THREAD

**Issue by kondricz** [zeit/next.js#3674]
Hi,

The plugin in the title unfortunatelly doesn't work. Seems like an issue with the plugin itself.

## Expected Behavior

https://www.npmjs.com/package/@zeit/next-sass

Followed the official documentation here, to import properly SASS files to my project. (Because before it is loading only partly).

## Current Behavior
Can't run my project because in my next.config.js file I get the following error message.

`> Using external babel configuration
> Location: "/home/kondricz/Desktop/-----/.babelrc"
> Using "webpack" config function defined in next.config.js.
(node:17481) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot set property 'sass' of undefined
(node:17481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Thank You your reply and effort in advance.
Regards,
Koppany

**Comment by timneutkens** [comment]
It'll be released 🔜 The latest version of next-sass should throw an error when you're on an unsupported version of next.js. Which is every version below v5, which will be released soon 🙏

**Comment by kondricz** [comment]
okay. Thanks for the update!
