### ISSUE TITLE
react-i18next vs i18next

### ISSUE THREAD

**Issue by kelleg1** [zeit/next.js#3686]
Which example should I use, [the with-18next one](https://github.com/zeit/next.js/tree/canary/examples/with-i18next), or [the with-react-i18next one](https://github.com/zeit/next.js/tree/canary/examples/with-react-i18next)? What are the pros and cons of one over the other?

**Comment by arunoda** [comment]
@kelleg1 the first one is a very simple usage of the library where you keep locale files under our static directory.  But the second is more advance it it uses express to serve files and give you more options.
