### ISSUE TITLE
example polyfill fails under next@5

### ISSUE THREAD

**Issue by Kikobeats** [zeit/next.js#3687]
[This](https://github.com/zeit/next.js/tree/canary/examples/with-polyfills) is the example:

```bash
~/Downloads/with-polyfills
❯ npm run dev

> with-polyfills@1.0.0 dev /~/Downloads/with-polyfills
> next

(node:54219) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'unshift' of undefined
    at DynamicEntryPlugin.cfg.entry (/Users/josefranciscoverdugambin/Downloads/with-polyfills/next.config.js:6:26)
    at <anonymous>
(node:54219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:54219) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by arunoda** [comment]
Let's have a look.

**Comment by OverVlad** [comment]
This one work for me 
` if (entries['main.js']) {
          entries['main.js'].unshift('core-js/fn/string/includes');
          entries['main.js'].unshift('core-js/fn/string/trim');
          entries['main.js'].unshift('core-js/fn/array/find');
          entries['main.js'].unshift('core-js/es6/object');
          entries['main.js'].unshift('core-js/fn/array/includes');
          entries['main.js'].unshift('core-js//fn/string/virtual/starts-with');
        }`

**Comment by timteeling** [comment]
Thanks, @OverVlad! Just verified that worked for me with my polyfills for IE11.
(need to run `next build && next start`)

Demo code can be rewritten as follows:

```JS
module.exports = {
  webpack: function (cfg) {
    const originalEntry = cfg.entry
    cfg.entry = async () => {
      const entries = await originalEntry()

      if (entries['main.js']) {
        entries['main.js'].unshift('./client/polyfills.js')
      }

      return entries
    }

    return cfg
  }
}
```

**Comment by arunoda** [comment]
@timteeling could you send us a PR with that change?

**Comment by afages** [comment]
All of your codes linked with "module.exports" are great and all but they don't pass the "no-reassign parameter" ESLINT quality gate.
