### ISSUE TITLE
update homepageUrl to next 5 🎉

### ISSUE THREAD

**Issue by benatkin** [zeit/next.js#3689]
[since next 5 is out](https://www.npmjs.com/package/next)

Currently the homepageUrl is https://zeit.co/blog/next4

``` graphql
query { 
  repository(owner: "zeit", name: "next.js") {
    homepageUrl
  }
}
```

``` json
{
  "data": {
    "repository": {
      "homepageUrl": "https://zeit.co/blog/next4"
    }
  }
}
```

My preference would be changing it to https://zeit.co/blog/next5 because keeping developers up to date is super important :)

**Comment by sergiodxa** [comment]
@timneutkens maybe we can setup next.now.sh or something like that with a redirect to the latest blog post

**Comment by arunoda** [comment]
@sergiodxa that'd be fancy. But I think it's fine to change it manually for now.
Since we might be working on a website for Next.js soon.

**Comment by arunoda** [comment]
BTW: 

Thanks @benatkin 
I changed the link.
