### ISSUE TITLE
Update with-typescript example to use next-typescript

### ISSUE THREAD

**Issue by sergiodxa** [zeit/next.js#3694]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Use new Next.js plugin for TypeScript

## Current Behavior
Use a hack to transpile TypeScript to JSX and then let Next.js handle it.

## Context
With the release of Next.js v5 the current example with TypeScript is outdated and can be simplified with the new [next-typescript](https://github.com/zeit/next-plugins/tree/master/packages/next-typescript) plugin.

**Comment by isBatak** [comment]
I would like to write my custom server setup in typescript. Could we get that example also?

**Comment by sergiodxa** [comment]
@isBatak that could be another example for a `custom-server-typescript`, it should require to run `tsc` for your server code and then run it as any Node.js server.

**Comment by sergiodxa** [comment]
Fixed on #3698
