### ISSUE TITLE
How to use Material-UI buttons as `next/Link` links?

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#3696]
I'd like to have Material-UI buttons be links instead of using `onTouchTap`. This allows you to tab-click the button to open the target in a new tab, and on hover the button shows a link in the browser status bar. Lots of nice benefits to this.

It seems that Material-UI's `FlatButton` and `RaisedButton` both have a `containerElement` attribute made for this use case. But I've tried several variations using `next/Link` and am getting errors.

```
<RaisedButton label='hello' containerElement={<Link href="http://www.google.com"/>} />

<RaisedButton label='hello' containerElement={<Link href="http://www.google.com"><a>There</a></Link>} />
```

In both these cases, I get `error: Invariant Violation: React.Children.only expected to receive a single React element child.`

Any suggestions on how to fix this?

The following work, but they use `<a href="...">` instead of `next/Link`. I need to use `next/Link`.

```
<RaisedButton label='hello' containerElement={<a href="http://www.google.com"></a>} />

<RaisedButton label='hello' containerElement={<a href="http://www.google.com"/>} />
```

**Comment by tashburn** [comment]
I found a solution to this.

```
class MyLink extends React.Component {
  render() {
    const { style, href, hrefAs, children, prefetch } = this.props
    return (
      <div style={style}>
        <Link href={href} as={hrefAs} prefetch>
          <a>
            {children}
          </a>
        </Link>
      </div>
    )
  }
}

...

<RaisedButton
  label='hello'
  containerElement={<MyLink href='http://www.google.com'/>}
/>

```

Is there a more elegant solution?

**Comment by tgdn** [comment]
Same with SemanticUI

**Comment by blainegarrett** [comment]
The Button component has a `component` attribute that you can pass in your `<Link href={href} as={hrefAs} prefetch>`

e.g. <Button component={<Link href={href} as={hrefAs} prefetch>}>Click Me</Button>

I have not tried it with next, but I have had to do the same for React Router Links.

**Comment by timneutkens** [comment]
That's the solution I would recommend. It's up to the framework you're using to support stuff like this. `<Link>` supports any child that implements `onClick` btw.

**Comment by tgdn** [comment]
Yes that solves the issue, however, no actual link (a valid HTML link with the href prop) is actually created. An onClick handler is set but really the href prop should persist.
