### ISSUE TITLE
Add next-css plugin usage example

### ISSUE THREAD

**Issue by sergiodxa** [zeit/next.js#3699]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
We should have documented as an example how to use the new [next-css](https://github.com/zeit/next-plugins/tree/master/packages/next-css) plugin

## Current Behavior
We have a few examples to import `.css` files which are mostly hacks to make it work.

## Context
With the release of Next.js v5 the current examples of importing CSS are outdated and can be simplified with the new next-css plugin.

**Comment by AriLFrankel** [comment]
I can start on this

**Comment by sergiodxa** [comment]
@AriLFrankel awesome, feel free to do it and mention the issue with a `Fix #3699` in the description so it's linked here and this will automatically close after the PR is merged 👍

**Comment by AriLFrankel** [comment]
Awesome, will do! 👍

**Comment by revolunet** [comment]
Thanks for the example.

Looks like `next export` doesnt produce the CSS though. any idea ?

**Comment by timneutkens** [comment]
Upgrade to next@canary 😄

**Comment by revolunet** [comment]
works, thanks @timneutkens
