### ISSUE TITLE
`next-build` should warn about existing `.next`

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#37]
This way, people can avoid accidents and side-effects. Typically if you're starting a `next build` you want to start from a clean slate.

Displaying a simple warning in stdout is probably a good idea.

**Comment by timneutkens** [comment]
@rauchg @nkzawa Think this can be closed 🤔

**Comment by nkzawa** [comment]
@timneutkens 👍 

Let's reopen if we need.
