### ISSUE TITLE
Add next-sass plugin usage example

### ISSUE THREAD

**Issue by sergiodxa** [zeit/next.js#3700]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
We should have documented as an example how to use the new [next-sass](https://github.com/zeit/next-plugins/tree/master/packages/next-sass) plugin

## Current Behavior
We have a few examples to import `.sass` files which are mostly hacks to make it work.

## Context
With the release of Next.js v5 the current examples of importing SASS/SCSS are outdated and can be simplified with the new next-css plugin.

**Comment by Albert-Gao** [comment]
Hi, wanna contribute, when checked the next-sass repo, I found several cases there, with-cssmodules, without-cssmodules, production-use, with-postcss.

Do we need all of them?

**under separate folders like this:**
- with-next-sass-css-modules
- with-next-sass-no-css-modules
- ....

**Or in one folder as subfolders**
-next-sass
---- with-css-modules
---- without-css-modules
---- ....

**Or just provide the first example and link to the doc in the readme.md**

What do you think? :)

**Comment by sergiodxa** [comment]
All the examples should be production ready, or at least describe how to do it if it's too complicated, in this case should be production ready.

You can make it works with CSS Modules and explain how to disable it if required. The PostCSS plugin is another example.

**Comment by Albert-Gao** [comment]
Added :) Let me know if I did something wrong.

**Comment by tills13** [comment]
Hi! An example using a custom server would be awesome.
