### ISSUE TITLE
isomorphic-unfetch in safari issue

### ISSUE THREAD

**Issue by posrix** [zeit/next.js#3707]
isomorphic-unfetch in safari cause 'An unexpected error has occurred' while use go back button from any other website. This error is tested only occur in safari, ios.

## My Environment

| Tech    | Version |
|---------|---------|
| next    |    5.0.0    |
| node    |   8.9.1     |
| OS      |     ios 11.2.5   |
| browser |   safari 11.0    |

**Comment by posrix** [comment]
I fixed it by performance.navigation.type, but didn't fix the origin issue

**Comment by timneutkens** [comment]
Unrelated to Next.js.

**Comment by posrix** [comment]
Turns out safari in IOS will cache the static page file while go back using history operation, and the api using isomorphic-unfetch  won't execute in backend as before, once it execute in frontend, request any remote server will throw CORS error, and next capture this error simply just print 'An unexpected error has occurred', quite confusing in this situation. The solution is add http proxy in backend.

**Comment by tilomitra** [comment]
@posrix  can you elaborate on this a bit more? Even if I add a http proxy in backend, loading the site in https mode causes this error. Have you been able to get around that? Thanks.

**Comment by posrix** [comment]
There are many reasons that cause 'An unexpected error has occurred', you need to locate the issue use safari developer tool. In my case, its the CORS issue.
