### ISSUE TITLE
Roadmap somewhere ?

### ISSUE THREAD

**Issue by romainquellec** [zeit/next.js#3713]
More of a question than an issue : 
Is there a clear roadmap somewhere about where you want to go with next.js ?
Next5 is 1 day old but I didn't found any info about what you are going to do for v6 ?

**Comment by lfades** [comment]
The post about Next5 is here: https://zeit.co/blog/next5
There isn't a public roadmap about Next6 but you can follow the branch `canary` for updates.

**Comment by timneutkens** [comment]
We don't have a public roadmap at the moment. When it's made public you'll see it on our blog zeit.co/blog 👍
