### ISSUE TITLE
Can't import global stylesheet in _document.js using next-css

### ISSUE THREAD

**Issue by saimeunt** [zeit/next.js#3714]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Using the new next-css module in dev mode, I'd like to globally import a css stylesheet and figured out the correct place could be `_document.js`.

`import '../css/style.css';`

## Current Behavior
It looks like importing css works only in components or in pages.
Production is unaffected by this problem as we're using a different strategy: https://github.com/zeit/next-plugins/tree/master/packages/next-css#production-usage

## Your Environment
| Tech    | Version |
|---------|---------|
| next    | 5.0        |
| node    | 9.5        |
| OS      | MacOS        |
| browser | Chrome        |

**Comment by davecarlson** [comment]
Confirmed same issue with `next-sass`, I've had to place it into `pages/**.js`

**Comment by timneutkens** [comment]
_document is not client rendered. So it won't be included with style-loader. Would work with server rendered styles like in https://github.com/zeit/next-plugins/pull/9 though. But I'm guessing you don't want this 😄

**Comment by timneutkens** [comment]
Regarding the original issue, check https://github.com/zeit/next-plugins/tree/master/packages/next-css#without-css-modules

> Note: CSS files can not be imported into your _document.js. You can use the _app.js instead or any other page.

Since then we have added `_app.js` which wraps all pages and renders on both sides.

Regarding your issue, this is a completely different issue and has been fixed in `next@canary` + `@zeit/next-css@canary` (or -sass -less -stylus if you're using that) so it will be part of Next 7.

**Comment by mtrabelsi** [comment]
thanks.. so its another bug.

**Comment by mtrabelsi** [comment]
@timneutkens its funny because i upgraded to Canary: 
- it works on Firefox
- crashes on chrome : Unhandled Rejection (TypeError): Cannot read property 'call' of undefined

the page loading is very slow.

Any idea ?
