### ISSUE TITLE
POST to a route

### ISSUE THREAD

**Issue by jesselee34** [zeit/next.js#372]
Looking through the documentation, I don't see a way to POST to a route. Is this possible?

**Comment by jonaswindey** [comment]
What are you trying to achieve? Next is a client-side framework that renders html (with server-side html rendering). For any API calls (GET/POST) you will need a server environment that handles this.

Unless you configure custom routes, which is under development (https://github.com/zeit/next.js/issues/291) I would still advise a separate Node server for your backend (in Express or Hapi)

**Comment by krstffr** [comment]
This would be great to clarify in the readme as I spent a little too much time thinking of the best way to solve this using only next.js before realizing that an external API app makes so much more sense :)

**Comment by rauchg** [comment]
I think a great place to put this is the FAQ!
