### ISSUE TITLE
ERROR in *.css . Module build failed: ValidationError: Style Loader Invalid Options 

### ISSUE THREAD

**Issue by geryit** [zeit/next.js#3720]
Can not import css after upgrading to v5

```js
//next.config.js
const withCSS = require('@zeit/next-css')
module.exports = withCSS()
```

```js
//pages/test.js
import React from 'react';
import './test.css';

export default () => <div className="test">Hello World!</div>;
```

```css
/*pages/test.css*/
.test{background-color: red;}
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Have a box with red background

## Current Behavior
Seeing this error:
```js
ERROR in ./pages/test.css
Module build failed: ValidationError: Style Loader Invalid Options

options['importLoaders'] should NOT have additional properties

 @ ./pages/test.js 10:0-20
 @ multi ./pages/test.js
```

## Context
I don't have `.babelrc` and `postcss.config.js` in my local and trying to import css

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 5 |
| node    |9.5 |
| OS      | macOS 10.12.6 |
| browser |chrome Version 64.0.3282.140 |

<img width="1218" alt="screen shot 2018-02-07 at 5 00 50 am" src="https://user-images.githubusercontent.com/514149/35896216-e7195c80-0bc3-11e8-9a9d-3458ab4051fe.png">

**Comment by windyGex** [comment]
The same problem that using next-sass plugin.

```
ERROR in ./src/styled-components/index.scss
Module build failed: ValidationError: Style Loader Invalid Options

options['importLoaders'] should NOT have additional properties
```

**Comment by timneutkens** [comment]
Already made a pr on next-plugins to solve this 🙏🏻

**Comment by haikyuu** [comment]
@timneutkens thanks ❤️ . Was it merged? how can i use it?

**Comment by timneutkens** [comment]
@haikyuu Will do a new release soon with a lot of improvements to next-css / less / sass

**Comment by OmarZeidan** [comment]
Any updates on this? I still get the same error.

- "next": "^7.0.2",
- "@zeit/next-css": "^1.0.1",

**Comment by vladimirlukyanov** [comment]
Same here

**Comment by zivanovicb1** [comment]
+1

**Comment by njiyto** [comment]
+1

**Comment by letsspeak** [comment]
+1

**Comment by mockee** [comment]
+1

- `next` v7.0.2
- `@zeit/next-css` v1.0.1
- `next-compose-plugins` v2.1.1

**Comment by schabluk** [comment]
`yarn add @zeit/next-css@next`

**Comment by katspaugh** [comment]
Neither removing `css-loader`, nor installing the canary version of the next-css plugin is helping.

**Comment by imakan** [comment]
> 我遇到了同样的问题。
> 
> ```
> % yarn build
> $ next build
> [1:02:12] Compiling server
> [1:02:12] Compiling client
> [1:02:14] Compiled server in 2s
> [1:02:17] Compiled client in 5s
> > Failed to build
> { Error: (client) ./components/font.scss
> Module build failed (from ./node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js):
> ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
> ValidationError: CSS Loader Invalid Options
> 
> options should NOT have additional properties
> ```
> 
> ## 它用以下命令解决了
> `yarn remove style-loader css-loader sass-loader`

thx，resolve my problem
