### ISSUE TITLE
NextJS 5 causes breakage in serverside implementations 

### ISSUE THREAD

**Issue by majelbstoat** [zeit/next.js#3721]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

Next5 causes some subtle breakage when developing in code that worked correctly in Next4, for a site that uses express. In particular, two things are observed in dev mode:

1. There is a flash of unstyled site before all `<styled jsx>` CSS loads on first load. (Client side navs are still fine.)
2. 401s on HMR, when using express-basic-auth.

## Steps to Reproduce (for bugs)

I created a minimal folder structure to demo the second behaviour: https://www.dropbox.com/s/ulazf3kutnsve2v/simple.tgz?dl=0 

1. Unzip, run yarn install, yarn dev (this uses Next 4.2.3.)
2. Visit localhost:3000, enter "something", "secure"
3. Open console.
4. Edit index.js
5. In the Network tab, observe that `on-demand-entries-ping?page=/` returns a 200.
6. Stop the server
7. yarn add next@latest, yarn dev.
8. Visit localhost:3000, enter "something", "secure" (new incognito window if you like)
9. Edit index.js 
10. In the Network tab, observe that `on-demand-entries-ping?page=/` returns a 401.

**Comment by majelbstoat** [comment]
Pretty sure flash of unstyled site was fixed by this: https://github.com/zeit/next.js/pull/3722/files. No longer happening in 5.0.1-canary.1. 401s still happening though.

**Comment by AndreasZeiser** [comment]
Just make sure that NextJS can handle the ping request before basic-auth middleware is used. Here's an example:

```js
// let next js handle requests to dev server before basic authentication is enforced
server.get('/_next/on-demand-entries-ping', (req, res) => handle(req, res));

// basic authentication
server.use(/* basic-auth middleware */);

// next js middleware
server.get('*', (req, res) => handle(req, res));
```

**Comment by majelbstoat** [comment]
Thanks for the workaround, @AndreasZeiser. Kind of curious what changed to cause the requirement of this additional step, but I can live with not knowing 😄.
