### ISSUE TITLE
How to load external assets only once accross isomorphic navigation?

### ISSUE THREAD

**Issue by rickysahu** [zeit/next.js#373]
What's the best way to load an external JS file only once across different pages and components between navigation events?  For example i need the google maps js file in one specific component used across many pages. Currently im using <Head><script..></Head> but each time the component loads, it reloads the external js file. 
Obviously multiple loads adds additional bandwidth, but more importantly when the js file reloads, it breaks gmaps

**Comment by mikecardwell** [comment]
Can you provide some example code?

**Comment by mr47** [comment]
@rickysahu it's require a dynamic modules, you can use `require.ensure` or wait #310.

**Comment by babakness** [comment]
@mr47 Looks like #310 has merged, are you saying `require.ensure` is need with #310 merged or before?

**Comment by mr47** [comment]
@babakness currently you need to setup a custom middleware to serve additional static file chunks that webpack generates (also need a tweak for webpack config), using #310 yes we can use `require.ensure`

PS: I am working to make some demo, so everybody can use this.

**Comment by impronunciable** [comment]
Dynamic imports will be ready for next `2.1` https://github.com/zeit/next.js/pull/742

**Comment by sedubois** [comment]
Does this also relate to https://github.com/zeit/next.js/issues/738?
