### ISSUE TITLE
HTTPS redirect in Next SSR

### ISSUE THREAD

**Issue by Utkarshbhimte** [zeit/next.js#3734]
I am working on a project based from the [SSR Caching Example](https://github.com/zeit/next.js/tree/canary/examples/ssr-caching). I am hosting this on a GCP VM.

I want all the HTTP routes to redirect to HTTPS. Can anyone help me with that?
```
app.prepare().then(() => {
  const httpApp = express();
  var server = express();

  // Use the `renderAndCache` utility defined below to serve pages
  server.get("/", (req, res) =>
    res.sendFile("./legacy_html/desktop.html", { root: __dirname })
  );

  server.get("*", (req, res) => handle(req, res));

  httpApp.get("*", (req, res) => {
    console.log(`user came to http 😨`);
    res.writeHead(302, {
      Location: "https://" + req.headers.host + req.url
    });
  });

  https.createServer(credentials, server).listen(config.ports.https, err => {
    if (err) throw err;
    console.log(`> HTTPS Ready on http://localhost:${config.ports.https}`);
  });

  http.createServer(server).listen(port, err => {
    if (err) throw err;
    console.log(`> HTTP Ready on http://localhost:${port}`);
  });
});
```

**Comment by mikestoltz** [comment]
@Utkarshbhimte This is more of an express issue, but you're well on your way there. Just make sure to pass `httpApp` to the http server and call `res.end` after you're done writing.
``` javascript
app.prepare().then(() => {
  const httpApp = express();
  const server = express();

  server.get("/", (req, res) =>
    res.sendFile("./legacy_html/desktop.html", { root: __dirname })
    res.end();
  );

  server.get("*", (req, res) => handle(req, res));

  httpApp.get("*", (req, res) => {
    console.log(`user came to http 😨`);
    res.writeHead(302, {
      Location: "https://" + req.headers.host + req.url
    });
    res.end();
  });

  https.createServer(credentials, server).listen(config.ports.https, err => {
    if (err) throw err;
    console.log(`> HTTPS Ready on https://localhost:${config.ports.https}`);
  });

  http.createServer(httpApp).listen(port, err => {
    if (err) throw err;
    console.log(`> HTTP Ready on http://localhost:${port}`);
  });
});
```
For what its worth, in my experience I have found that it is much easier to do the https termination with a reverse proxy loadbalancer than to run two separate express servers within the app, but this should work.

I did notice that none of your defined routes are using the `renderAndCache` utility defined in the example, if caching the SSR is your intention you may want to revisit that piece.

**Comment by timneutkens** [comment]
> For what its worth, in my experience I have found that it is much easier to do the https termination with a reverse proxy loadbalancer than to run two separate express servers within the app, but this should work.

Our recommendation also 👍

**Comment by Utkarshbhimte** [comment]
Thanks @mikestoltz @timneutkens
