### ISSUE TITLE
Livereload 404s

### ISSUE THREAD

**Issue by asbjornenge** [zeit/next.js#374]
Hi! I'm having some weird issue where I get `404`s when modifying files.

I have a basic site:

```sh
npm init -y
yarn add next
mkdir pages
cat >pages/index.js <<EOL
import React from 'react'
export default () => <div>Hello world!</div>
EOL
jq '.scripts.dev="next"' package.json | sponge package.json
npm run dev
```

Next starts and initial pageload looks fine. However, when I modify `index.js` in any way, I get a `404`. Looking at devtools I see; 

`next-dev.bundle.js:32334 GET http://localhost:3000/index.json 404 (Not Found)`

Any idea what could be causing this? Could it be a global npm package or something?

OS: Ubuntu 16.04
Node: v6.9.2
Next: v1.2.3

**Comment by andrew--grant** [comment]
I have this exact same problem. It seems to be a pattern. I make an edit, get this 404, make another and it comes good, make another and I get the 404, make another and it comes good, so on and so forth.


GET http://localhost:3000/index.json 404 (Not Found)
loadJSON	@	next-dev.bundle.js:32334
loadComponent	@	next-dev.bundle.js:32234
(anonymous)	@	next-dev.bundle.js:31965
F	@	next-dev.bundle.js:21805
_callee5$	@	next-dev.bundle.js:31941
tryCatch	@	next-dev.bundle.js:32452
invoke	@	next-dev.bundle.js:32726
prototype.(anonymous function)	@	next-dev.bundle.js:32485
tryCatch	@	next-dev.bundle.js:32452
invoke	@	next-dev.bundle.js:32668
prototype.(anonymous function)	@	next-dev.bundle.js:32485
step	@	next-dev.bundle.js:33182
(anonymous)	@	next-dev.bundle.js:33200
F	@	next-dev.bundle.js:21805
(anonymous)	@	next-dev.bundle.js:33179
fetchComponent	@	next-dev.bundle.js:32041
_callee3$	@	next-dev.bundle.js:31578
tryCatch	@	next-dev.bundle.js:32452
invoke	@	next-dev.bundle.js:32726
prototype.(anonymous function)	@	next-dev.bundle.js:32485
step	@	next-dev.bundle.js:33182
(anonymous)	@	next-dev.bundle.js:33200
F	@	next-dev.bundle.js:21805
(anonymous)	@	next-dev.bundle.js:33179
reload	@	next-dev.bundle.js:31671
reload	@	webpack-hot-middleware-client.js?dd47b12:57
(anonymous)	@	webpack-hot-middleware-client.js?dd47b12:75
processMessage	@	client.js?dd47b12:151
handleMessage	@	client.js?dd47b12:68

**Comment by frol** [comment]
I am facing the same issue even with the latest master (and 2.0.0-beta.0). Every second save results in 404. I am working on Linux (Arch Linux x64), and I have noticed that if I save and exit VIM (`:wq`), everything is fine (!), but if I just save (`:w`), I am getting this weird 404.

**Comment by asbjornenge** [comment]
What?? :see_no_evil: I can confirm I'm seeing the same behaviour as @frol regarding totally closing vim (`:wq`) - if I do that it works as expected. Could it be related to `*.swp` files then? Is there a `.nextignore` file we can add? :stuck_out_tongue_closed_eyes:

**Comment by timneutkens** [comment]
@asbjornenge could you try using the latest beta build? `npm install next@beta`. I've just tried using vim with hot reloading, but for me everything is updating correctly. Even after totally closing, opening again and using `:w` and `:wq` combinations.

**Comment by frol** [comment]
It seems to be working fine now (tested on `next@2.0.0-beta.18`)! Thank you!

**Comment by arunoda** [comment]
I'm gonna close now.
@asbjornenge is this is still there please re-open.
(Make sure to test with the latest beta)

**Comment by asbjornenge** [comment]
Can confirm that it now works with the latest `@beta` :grin: :rocket: :tada:
