### ISSUE TITLE
React-hot-loader: Please require react-hot-loader before React.

### ISSUE THREAD

**Issue by u3u** [zeit/next.js#3742]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Console no error

## Current Behavior

React-hot-loader: fatal error caused by  ƒ BasicLayout()
no instrumentation found.  Please require react-hot-loader before React. More in troubleshooting.

## Steps to Reproduce (for bugs)

1. Open the page
2. Use `next/link` to jump to other pages

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | v5.0.0 |
| node    | v8.9.0 |
| OS      | macOS High Sierra version 10.13.3 |
| browser | Chrome/64.0.3282.140 |

**Comment by timneutkens** [comment]
Please provide a repository to reproduce this.

**Comment by u3u** [comment]
@timneutkens 
Sorry, I found the reason.
It's caused by the `<Layout />` component in [antd](https://github.com/ant-design/ant-design), but I do not know why.

As long as the use of this component, there will be this problem.

```jsx
import * as React from 'react'
import { Layout } from 'antd'

const { Header, Content, Footer } = Layout

export default class BasicLayout extends React.Component {
  render() {
    return (
      <Layout>
        <Header />
        <Content />
        <Footer />
      </Layout>
    )
  }
}
```

**Comment by u3u** [comment]
[antd](https://github.com/ant-design/ant-design) version of this issue is v3.2.0.
I switch it to v2.13.11 there is no problem.
But I use next/@4.2.3 and antd/@3.2.0 is no problem.

**Comment by jadengore** [comment]
@u3u Does this resolve it for you? https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#react-hot-loader-fatal-error-caused-by-xxx---no-instrumentation-found

I have this issue too in my app with a HOC layout component.

**Comment by u3u** [comment]
@jadengore Thank you very much!
I import the `react-hot-loader` module and fix it with the hot decorator! 😄
But all pages need this, a bit of trouble. 😕

```jsx
import { hot } from 'react-hot-loader'
import * as React from 'react'
import styled from 'react-emotion'
import BasicLayout from 'layouts/basic-layout'

const H1 = styled.h1`
  margin: 0.5em;
  text-align: center;
`

@hot(module)
export default class IndexPage extends React.Component {
  public render() {
    return (
      <BasicLayout>
        <H1>Index Page</H1>
      </BasicLayout>
    )
  }
}
```

**Comment by OrangeXC** [comment]
@u3u use next/5.0.1-canary.10 and antd/@3.2.3  is no problem.

**Comment by u3u** [comment]
@OrangeXC 
I tried this, but after using next/@5.0.1-canary.10, the problem was even more, I don't know why

**Comment by u3u** [comment]
This problem seems to be fixed in version 5.0.1-canary.11.
But there is a smaller chance of recurrence, no major impact.

**Comment by arnaud-zad** [comment]
I still have this problem with 5.0.1-canary.15

**Comment by blainegarrett** [comment]
I am experiencing this as well in canary.15. In my case the error involves MuiThemeProvider and triggering hot reloading (save, etc). I assume I have something incorrectly setup however.

**Comment by mcdyzg** [comment]
I am experiencing this without next.  
Finally i resovle it with this:
```
webpack.config.js:

entry: [
        'react-hot-loader/patch',
        './src/app/index.js'
]
```

**Comment by ckeeney** [comment]
This is what solved this problem for me: 
https://github.com/gaearon/react-hot-loader/issues/894#issuecomment-393005041
