### ISSUE TITLE
Question: What exactly is cached in onDemandEntries?

### ISSUE THREAD

**Issue by julmot** [zeit/next.js#3743]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

According to [the docs](https://github.com/zeit/next.js#configuring-the-ondemandentries) a page is cached for 25sec in development by default. However, when you change something on the API-side or even in the JSX of a page, the page will update (both by HMR and when calling manually using F5).

So I'm curious, what exactly is cached here, what exactly do you specify with `maxInactiveAge`?

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 5.0.0 |
| node    | 9.5.0 |
| OS      | Win10 |

**Comment by timneutkens** [comment]
When you don't access the page for x time it will be removed from webpack compilation till you ask for it again through accessing it.

The x time is `maxInactiveAge`
