### ISSUE TITLE
next.config.js with multiple plugins

### ISSUE THREAD

**Issue by r0b-** [zeit/next.js#3752]
Hi,

I'm trying to use typescript & css plugin like this:
```
const withTypescript = require('@zeit/next-typescript');
const withCss = require('@zeit/next-css');
module.exports = withTypescript();
module.exports = withCss();
```
but it's not working (I guess module.exports assignments are wrong/overwriting).

Thanks in advance

**Comment by khuezy** [comment]
Line 3 is replaced by line 4.

Look at the source code for these plugins to see what they return for a better understanding.

`module.exports = withTypescript(withCss(/*optional parameters*/));

**Comment by r0b-** [comment]
Thanks!

(Now I'm facing the `options['importLoaders'] should NOT have additional properties` error, but that's not related here I think...)

**Comment by khuezy** [comment]
Np! I think https://github.com/zeit/next-plugins/issues would be a better place to report any issues.
