### ISSUE TITLE
Fela.js integration is broken after 5.0 (with-fela example)

### ISSUE THREAD

**Issue by devilcoders** [zeit/next.js#3757]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Expected to render css on the server first, using specific code in `_document.js`. So, expected behavior would be to see no FOUC.

## Current Behavior
CSS is not rendered on the server, only on the client. It's interesting that class names are applied correctly on the server, only actual CSS is not rendered. As the result, we see FOUC before client side catch up.

This happened right after updated to 5.0. Latest `canary` releases also broken.

## Steps to Reproduce (for bugs)
1. `curl https://codeload.github.com/zeit/next.js/tar.gz/canary | tar -xz --strip=2 next.js-canary/examples/with-fela`
2. `cd with-fela`
3. `yarn`
4. `yarn dev`

## Your Environment
| Tech    | Version |
|---------|---------|
| next    | 5.0.0 / 5.0.1-canary.4 / 5.0.1-canary.5 / 5.0.1-canary.9        |
| node    | 9.5.0        |
| OS      |  OSX 10.13.3       |

**Comment by danielantelo** [comment]
same issue here , any luck with this?


Tech | Version
-- | --
next | 5.0.0
node | 8.9.1
OS | OSX 10.13.2

**Comment by devilcoders** [comment]
@danielantelo Not much so far. Had to downgrade next to 4.4 for now :(

**Comment by rofrischmann** [comment]
I also struggle with that and am using Next 4.4 for now. Seems to be the same for Styletron, Aphrodite and all the other solutions that use the getInitialProps method to cluster CSS.

**Comment by TxHawks** [comment]
Any update on this? Weuse Fela and are building an app that needs the `zones` feature in 5

**Comment by ilionic** [comment]
This issue needs more attention, any ETA?

**Comment by devilcoders** [comment]
@ilionic I agree, this one is really critical.

**Comment by rofrischmann** [comment]
ETA: today.

As I need this to work for myself, I hacked around till I got it working.
Will update the example asap.
