### ISSUE TITLE
With Firebase Authentication example needs more explicit instructions

### ISSUE THREAD

**Issue by abelta** [zeit/next.js#3765]
I have my project set up in Firebase and created locally too.

Instructions literally say this:
> get your service account credentials and client credentials and set both in firebaseCredentials.js
but there's no explanation as to what it means or how to get it.

How do I get these credentials: command line or section in the console?
Will the content of these credentials go into a new file called `firebaseCredentials.js` (I'm guessing no)  or into the existing `credentials/client.js` and `credentials/server.js`?

**Comment by abhinayar** [comment]
The Client credentials are found under the "Authentication" tab in the Firebase console, by clicking on the "Web Setup" button. The Server credentials can be found by clicking on the gear icon next to "Project Overview", entering the "Project Settings", navigating to "Service Accounts" and clicking on "Generate New Private Key" for Node (if you're using NextJS).

Know this is pretty late after you asked but hope it helps! Cheers.
Abhi

**Comment by bastienrobert** [comment]
I totally agree, I huge issues using rematch/redux and firebase auth with Next. SSR is doing weird things and the content reload is ugly. I opened a new question on Spectrum yesterday, still no answers :( : https://spectrum.chat/?t=5c6a32d6-190b-4670-bbc1-b658da6d2fb7

**Comment by timneutkens** [comment]
Feel free to send a pull-request to the example.
