### ISSUE TITLE
HMR broken for tsx pages in Next5

### ISSUE THREAD

**Issue by majelbstoat** [zeit/next.js#3766]
Hot module reloading does not work for `.tsx` pages in Next5.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Editing, for example, `pages/index.tsx`, should cause HMR to reload part of index.tsx.

## Current Behavior

A browser warning is issued and the full page is reloaded:

`Ignored an update to unaccepted module ./pages/index.tsx -> 2`

<img width="1322" alt="screenshot 2018-02-11 13 53 34" src="https://user-images.githubusercontent.com/425787/36079000-fedcaa9e-0f32-11e8-9b67-28915764ac2f.png">

## Steps to Reproduce (for bugs)
1. Copy the with-typescript example into a clean directory
2. Edit package.json to next@5.0.1-canary.4
3. yarn install && yarn dev
4. Visit localhost:3000, open console.
5. Edit pages/index.tsx and save
6. Observe warning in the console and full reload.

I've observed this in next 5.0.0, 5.0.1-canary.2, and 5.0.1-canary.4 (canary3 not tested)
Chrome Version 64.0.3282.140
OSX High Sierra 10.13.3

**Comment by majelbstoat** [comment]
There's a couple of suspicious places like https://github.com/zeit/next.js/blob/canary/server/hot-reloader.js#L290 and https://github.com/zeit/next.js/blob/canary/server/build/loaders/hot-self-accept-loader.js#L39 which seem to be only looking for `.js` files, but I don't know enough to know if that's the problem.

**Comment by timneutkens** [comment]
Fixed. See https://github.com/zeit/next-plugins/pull/43

**Comment by timneutkens** [comment]
Fix released as @zeit/next-typescript@0.0.9
