### ISSUE TITLE
Slow page load in production

### ISSUE THREAD

**Issue by Dzale** [zeit/next.js#3767]
Hey guys,

I have a simple app built with next.js and react. Average initial time of loading pages in production is between 4-6s, which is like crazy, since loading data from external API takes about 200ms. 

Below is example of page load that doesn't even make request to external API:

DONE  Compiled successfully in 6043ms12:51:07 AM      

I have basic droplet on VPN (5$ / month) and i used PM2 to serve this app. 

Any ideas how to improve this ? Will using "now" speed it up ? Or buying better/faster droplet ?

As i said it is very basic app (i don't have hundreds of packages, no additional webpack config, nothing), so no really space for improvement there. But having this high loading time is unacceptable!

**Comment by khuezy** [comment]
There shouldn't be any compiling in production mode.
It looks like you're running: `npm run dev`

To run production:
`npm run build`
`npm start`

**Comment by Dzale** [comment]
No, `npm start` doesn't support SSR (Server Side Rendering).

I am running following commands:
`npm run build`
`pm2 start server.js`

**Comment by khuezy** [comment]
? `npm start` renders SS for me.

**Comment by Dzale** [comment]
For me it throws 404 for each page that has to prefetch some data from API.

![image](https://user-images.githubusercontent.com/9077950/36081381-6dc96e36-0f9e-11e8-984f-898c3dccc876.png)

![image](https://user-images.githubusercontent.com/9077950/36081390-8217b280-0f9e-11e8-834e-c17dea6f8b67.png)

**Comment by khuezy** [comment]
Can you post the `script` object in your `package.json`?

My `npm start` => `node index`

There's an open issue w/ slow compile time in dev mode: #3735
But I'm not seeing any slow downs running the `build`

**Comment by Dzale** [comment]
My `npm start` => `next start` :D

**Comment by Dzale** [comment]
I tried, the loading time is the same, about 6s. It's basically the same thing that `pm2 start server.js` does, pm2 just makes that command permanent. 

Not sure what can be the problem. Maybe i should get better droplet...

However, thanks for the help.

**Comment by timneutkens** [comment]
You are starting the app in development mode. Which is not optimized  for production usage. In case you're using a custom server you need to set `dev` to false. In the examples we do it using `process.env.NODE_ENV === 'production'` So when starting your app you need to set `NODE_ENV=production node server.js`

**Comment by Dzale** [comment]
works perfectly, thanks!
