### ISSUE TITLE
About the Redux example in the wiki

### ISSUE THREAD

**Issue by iamjacks** [zeit/next.js#377]
Isn't it best to have the store as part of a root wrapper or layout component? I'm someone who's learning Redux at the moment and almost every example I see is following that approach. With Next, are we encouraged to setup the store inside every page component? If not, does anyone have another Redux example?

**Comment by sedubois** [comment]
I tend to agree, that's what I did in [Relate](https://github.com/RelateMind/relate/): https://github.com/RelateMind/relate/blob/master/hocs/page.js. Note that server-side you still render each component in an isolated manner and collect all the data with `getDataFromTree`: https://github.com/RelateMind/relate/blob/master/hocs/apollo.js.

**Comment by impronunciable** [comment]
@sedubois @iamjacks We moved the examples into an examples folder and are more than willing to review the redux example
