### ISSUE TITLE
Can't use materialize css with next js

### ISSUE THREAD

**Issue by davidteejay** [zeit/next.js#3773]
I can't seem to be able to use materialize css with nextjs, I imported the source file into the app using next-sass, but whenever I try to import the javascript file, it either tells me that jQuery is not defined (even after I imported the jQuery node module), or window is not defined or cash is not defined or some other error

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    5.0.0     |
| node    |    9.1.0     |
| OS      |     Windows 10    |
| browser |    Chrome     |

**Comment by timneutkens** [comment]
Most likely you have to do something like tihs:

```
import $ from 'jquery'
window.$ = $
window.jQuery = $
```
