### ISSUE TITLE
next-preact example fails in development mode

### ISSUE THREAD

**Issue by programbo** [zeit/next.js#3774]
Production mode works as expected. Running the example in development mode does not build the `common.js` file.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Both `main.js` and I expect `common.js` to exist in the `/.next` directory in development mode.

## Current Behavior

In the browser console:
```
GET http://localhost:3000/_next/-/commons.js net::ERR_ABORTED
[HMR] connected
GET http://localhost:3000/_next/-/commons.js 404 (Not Found)
```

I have checked in the `.next` directory and it's definitely not there.

## Steps to Reproduce (for bugs)
1. `curl https://codeload.github.com/zeit/next.js/tar.gz/canary | tar -xz --strip=2 next.js-canary/examples/using-preact`
2. `cd using-preact`
3. `npm i`
4. `npm run dev`

## Context
I am unable to run [next-preact](https://github.com/zeit/next-plugins/tree/master/packages/next-preact) or the current [with-preact example](https://github.com/zeit/next.js/tree/canary/examples/using-preact) in development mode.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 5.0.0 |
| node    | 8.9.4 |
| OS      | MacOS 10.13.3 |
| browser | Chrome 63.0.3239.132 |

**Comment by simonhaenisch** [comment]
I used `create-next-app --example using-preact next-app` (node 9.5.0), but when running in dev mode, the content flickers and then disappears.

```json
"dependencies": {
    "@zeit/next-preact": "0.0.4",
    "next": "5.0.0",
    "preact": "8.2.7",
    "preact-compat": "3.18.0",
    "react": "16.2.0",
    "react-dom": "16.2.0"
}
```

**Comment by timneutkens** [comment]
Related https://github.com/zeit/next-plugins/issues/24
