### ISSUE TITLE
Error combining with-apollo and with-i18next

### ISSUE THREAD

**Issue by craigcartmell** [zeit/next.js#3779]
- [X] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

I should be able to use `withData` from the [with-apollo example](https://github.com/zeit/next.js/tree/5.0.0/examples/with-apollo) and `translate` from react-i18next  HoCs together.

## Current Behavior

I've been using Apollo as per the [with-apollo example](https://github.com/zeit/next.js/tree/5.0.0/examples/with-apollo) quite happily for some time and I'm now trying to integrate [with-i18n](https://github.com/zeit/next.js/tree/5.0.0/examples/with-i18next). Unfortunately I think there may be issues with combining the two approaches. I'm receiving the following error:

```
Cannot read property 'options' of undefined
TypeError: Cannot read property 'options' of undefined
...
at new I18n node_modules/react-i18next/dist/commonjs/I18n.js:56:20
```

It seems i18n isn't being initialised correctly (hence options of undefined (the i18n instance)), or is being overridden, perhaps because of the usage of `getInitialProps` in `withData.js`?

Has anyone managed to get Next.JS, Apollo and i18n working together? Any working examples?

## Steps to Reproduce (for bugs)

1. Follow the steps to setup [with-apollo example](https://github.com/zeit/next.js/tree/5.0.0/examples/with-apollo) and [with-i18n](https://github.com/zeit/next.js/tree/5.0.0/examples/with-i18next)
2. Create a page which is wrapped in `translate` from react-i18next and `withData` from the with-apollo example.
3. See error.

## Context

I'm trying to integrate react-i18next into my current next/apollo setup.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 5.0.0        |
| node    | 8.9.4        |
| OS      | macOS High Sierra        |
| browser | Chrome        |
| etc     |         |

**Comment by thomhos** [comment]
Do you have a repo of the implementation, or can you post a bit more info on how you're trying to achieve this?

**Comment by craigcartmell** [comment]
@thomhos Sorry for the delay in getting back to you. I haven't been able to get back onto this.

I'm going have another go at it to make sure I'm not doing something stupid. I'll close the issue or post the repo up soon.

**Comment by craigcartmell** [comment]
It was the latter (I was doing something stupid).

**Comment by ckeeney** [comment]
@craigcartmell can you give details about you did?  I'm getting an identical error but haven't yet learned what stupid thing I'm doing.

**Comment by ckeeney** [comment]
Nevermind.  I for temporarily removed the `translate` HOC from my `Page`.

**Comment by mikepuglisi** [comment]
Does anyone in this thread have a working example of combining with-apollo and with-i18next?

I have a demo repo which attempts to combine both, but SSR does not work when using the <Query> component.

https://github.com/mikepuglisi/next-js-with-apollo-and-i18next

Some devs on react-i18next advised me that I must "merge getInitialProps", but I'm having a hard time merging the getInitialProps from 

https://github.com/mikepuglisi/next-js-with-apollo-and-i18next/blob/master/lib/with-apollo-client.js

with 

https://github.com/mikepuglisi/next-js-with-apollo-and-i18next/blob/master/lib/withI18next.js

---------------

Addition Discussion on Topic:

https://github.com/i18next/react-i18next/issues/593

**Comment by ericyip** [comment]
I am also facing the same issue here. Hope someone can help
