### ISSUE TITLE
css reference to static files

### ISSUE THREAD

**Issue by DarkAdmiral** [zeit/next.js#378]
Hi, I'm looking for a solution to set my background image in glamor css:

``const mainStyle = style({
    background: 'url(/static/bg.png) no-repeat center center scroll'
})
``

Unfortunately that link yields a 404.

**Comment by SpencerCDixon** [comment]
+1, curious how to go about this properly

**Comment by arunoda** [comment]
Now sure how you did this but this works pretty well for me:

```js
import React from 'react'
import style from 'next/css'

const mainStyle = style({ background: 'url(/static/bg.png) no-repeat center center scroll' })

export default () => (
  <div className={mainStyle}>
    <p>Hello World</p>
  </div>
)
```

You need to create a directory called `static` in the root of your app and put your image `bg.png`.

**Comment by SpencerCDixon** [comment]
yeah I ended up with the same solution.  [There is a section of readme that goes over this if anyone else is curious](https://github.com/zeit/next.js#static-file-serving-eg-images)

**Comment by arunoda** [comment]
I hope we could close this issue.
