### ISSUE TITLE
How to call api in server render and save in redux ?

### ISSUE THREAD

**Issue by safeimuslim** [zeit/next.js#3780]
How to call api in server render and save in redux ?

**Comment by TheRobBrennan** [comment]
@safeimuslim You can have the server dispatch actions that trigger API calls...then when they complete, the client will have the store populated as desired.

**Comment by safeimuslim** [comment]
ok, thx  @TheRobBrennan

**Comment by TheRobBrennan** [comment]
Have you done that before in Next? I've got an example of that in my demo project at https://github.com/TheRobBrennan/demo-nextjs-v5
