### ISSUE TITLE
Question: how to identify the API call is from SSR/CSR

### ISSUE THREAD

**Issue by shibukawa** [zeit/next.js#3797]
I'm creating API on server.js that uses user authentication via passport.

I already add code to use passport and it works fine. If the user is not authorized, then redirect to login page for page, or return 403 Forbedden for APIs.

```js
const isAuthenticatedAPI = (req, res, next) => {
    if (req.isAuthenticated()) {
        return next();
    } else {
        res.sendStatus(403);
    }
};

server.get("/api/item/:id", isAuthenticatedAPI, (req, res) => {
    // API implementation
});
```

But it is too strong. The code reject API calls during SSR. I hope to omit authentication check during SSR. I thought two solutions, but they were fragile:

* Checking user-agent is ``node-fetch/1.0 (+https://github.com/bitinn/node-fetch)`` or not.
* Checking req.ip is local or not (via [is-local-ip](https://www.npmjs.com/package/is-local-ip))

Is there any cool solution to identify the API client is for SSR or CSR?

thanks,

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

We will get any good solution to decide authentication check should be omitted or not.

## Current Behavior

I couldn't identify API call is for SSR/CSR in Express.js's handler.

## Steps to Reproduce (for bugs)

1. Add passport to next's server.js
2. Call the API during SSR (it's ok on CSR)
3.
4.

## Context

I am creating the website that has uses user authentication via passport.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    5.0     |
| node    |   8.9.4      |
| OS      |     macOS 10.12.6    |
| browser |    Chrome M63     |
| etc     |         |

**Comment by timneutkens** [comment]
You should check in getInitialProps, and then you can check for `!!req`, if true it's ssr, if false it's the browser.

**Comment by shibukawa** [comment]
Yes. Checking in React layer is easy. But it is difficult on Express (or any API server). I could detect on getInitialProps(), but inside http handlers, I couldn't check. The handlers are accessed via isomorphic-unfetch. 

```
getInitialProps() : OK
          ↓
isomorphic-unfetch
          ↓
http handlers on Express : No idea
```

**Comment by timneutkens** [comment]
That's unrelated to how next handles things, if you need to know if it comes from the server/client you should add that to the body of a request sent to your api. Another idea, is adding cors configuration to pass cookies to your api. But that only works for apis on the same domain. And makes your api stateful. So it's not really a recommendation.
