### ISSUE TITLE
Implement options to provide Zoho url

### ISSUE THREAD

**Issue by pahan35** [zeit/next.js#3805]
Now it's hardcoded to **crm.zoho.com**. But in Zoho isset another domains like **crm.zoho.eu**.

It will be nice to have possibility to setup Zoho domain on instance creation.

**Comment by timneutkens** [comment]
I'm extremely confused. Please elaborate. 👍

**Comment by pahan35** [comment]
Sorry. It's wrong project. I add it to wrong repository.

My fault.
