### ISSUE TITLE
next export: Error at chunk.map in document.js:152 and document.js:284

### ISSUE THREAD

**Issue by milmaj** [zeit/next.js#3813]
after `next export`

We get this error: 

`
TypeError: chunks.map is not a function at NextScript.getDynamicChunks (/Users/Me/Desktop/project_code/node_modules/next/dist/server/document.js:284:16)
`

If I do `console.log(chunks)`:

`
{names:[],files:[]} 
`

## Environment
| Tech    | Version |
|---------|---------|
| next    |  5.0.0       |
| node    | 9.5.0        |

**Comment by timneutkens** [comment]
I can't find the specific `chunks.map` Please provide a repository to reproduce 👍

**Comment by w01fgang** [comment]
I experience the same error in development. If I build the project, everything is ok.
I tried to do a trick, and it works. In my `_document.js` I pass `chunks` like this:
```javascript
const page = renderPage(App => props => sheet.collectStyles(<App {...props} />));
const styleTags = sheet.getStyleElement();
const chunks = Array.isArray(page.chunks) ? page.chunks : [page.chunks]; // this do the trick
return {
  ...page,
  chunks,
  styleTags,
  locale,
  localeDataScript,
};
```
