### ISSUE TITLE
Bundles are not created correctly when pages export an imported component

### ISSUE THREAD

**Issue by stevebluck** [zeit/next.js#3818]
The build process does not recognise shared files when your pages export an imported or wrapped component.

A common way of batching multiple `getInitialProps` is to wrap your pages in multiple HOC's - however doing this causes these issues described here.

I'll try to explain using `moment` as an example dependency.

These three files are identical.
```
pages/one/index.js
pages/two/index.js
pages/three/index.js
``` 

#### Broken Page Structure
Doesn't bundle correctly, `one.js`, `two.js` and `three.js` include the `moment` code.
```
import View from './View';
import moment from 'moment';

export default View;
```
#### Working Page Structure

Bundles correctly, `app.js` includes the `moment` code
```
import moment from 'moment';

export default () => "page one"
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

The app.js file to include all shared files between pages regardless of how the page is exported.

## Current Behavior

Each page is bundled with the same files causing duplicate code to be downloaded across pages.

## Steps to Reproduce (for bugs)

1. Clone https://github.com/stevebluck/next-test
2. `yarn install`
3. `yarn build`
4. `yarn start-broken`
5. Open a new terminal tab and run `yarn start-working`
6. Open 2 browser tabs at `http://localhost:3000/one` and `http://localhost:4000/one`
7. Compare the bundles, port 4000 is the working version

## Context

Bundles are too large

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     canary    |
| node    |    8.9.0     |
| OS      |     MacOS high Sierra 10.13.3    |
| browser |    Chrome/any     |

**Comment by timneutkens** [comment]
Currently the commons calculation is `amount of pages * 0.5`, if a dependency is used in 50% of all pages it's considered commons. The `amount of pages` is the total amount of glob'ing the `pages` directory.
