### ISSUE TITLE
Possible to use local semantic UI css file?

### ISSUE THREAD

**Issue by jaqua** [zeit/next.js#3825]
Now as nextJS v5 is released, I hoped to be able to use local (!) semantic ui css file instead of using CDN like shown in the examples.

So this is how I tried to do it:

**next.config.js**

    const withCSS = require('@zeit/next-css')
    module.exports = withCSS()

**Header.js**

    import Head from 'next/head'
    import 'semantic-ui-css/semantic.min.css'

    export const Header = props => {
      return (
        <Head>
          <meta http-equiv='content-type' content='text/html;charset=UTF-8' />
          <meta charset='utf-8' />
          <title>{props.title}</title>
          <link rel='icon' href='/static/favicon.ico' />
        </Head>
      )
    }

But with this I do get some errors, which look like this:

    error  in ./node_modules/semantic-ui-css/themes/default/assets/fonts/icons.ttf

    Module parse failed: Unexpected character '' (1:0)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)

    @ ./node_modules/semantic-ui-css/semantic.min.css 7:127119-127169
    @ ./components/Header.js
    @ ./pages/index.js
    @ multi ./pages/index.js

I'm not quite sure if it is still impossible to use a local semantic ui css file or if I need to extend some configuration...

**Comment by timneutkens** [comment]
You need to add a loader for the fonts. Something like: https://github.com/arefaslani/next-images/blob/master/index.js#L10-L24 but using the image extensions.

@arefaslani might be interesting to do another plugin 🕵️

**Comment by jaqua** [comment]
I tried this one, but the error keeps the same:

```
const withCSS = require('@zeit/next-css')
module.exports = withCSS({
  webpack (config, options) {
    config.module.rules.push({
      test: /\.(png|svg|ttf|woff?2|eot)$/,
      use: [
        {
          loader: 'url-loader',
          options: {
            limit: 8192,
            fallback: 'file-loader',
            publicPath: '/_next/',
            outputPath: 'static/images/',
            name: '[name]-[hash].[ext]'
          }
        }
      ]
    })

    return config
  }
})
```

**Comment by torinagrippa** [comment]
I have Semantic UI working in Next. It’s less obvious than it should be to have the templating system work. @timneutkens how would you like me to add this to the community?

**Comment by jaqua** [comment]
@torinagrippa You could add it in the example as right now there is just the CDN implementation used.

But I would be very thankful if you can post your solution also in this thread here. My solution is not working properly in production. :-(

**Comment by ruhusobeje** [comment]
@torinagrippa 
Struggling with semantic ui less and next integration
Would it be possible for you to add your working solution ?

Thanks!

**Comment by kytwb** [comment]
@torinagrippa Could you give any details on your solution? I'm also looking to implement templating with Next.js/Semantic UI.

**Comment by kaym0** [comment]
@torinagrippa why did you say you have it working and not post solution, please post the solution

**Comment by eddneal** [comment]
@torinagrippa Have you shared the solution for this anywhere?

**Comment by vidann1** [comment]
@jaqua 's solution works, just need to install @zeit/next-css first then add this to next.config.js

const withCSS = require('@zeit/next-css')
module.exports = withCSS({
  webpack (config, options) {
    config.module.rules.push({
      test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000
        }
      }
    })
    return config
  }
})
