### ISSUE TITLE
5.0.1-canary.2 Router.replace works, 5.0.1-canary.5 not

### ISSUE THREAD

**Issue by steida** [zeit/next.js#3828]
I don't know why, but my auth component redirecting `Router.replace(redirectUrl);` will update URL, but not UI, which still shows `/signin` content. What has been changed? 5.0.1-canary.2 is the last working version.

**Comment by JerryCauser** [comment]
yeah, in dev mode not working page changing.

**Comment by JeromeFitz** [comment]
This could be related to PR #3808.

Where the `react-hot-loader` on `dev` doesn't "see" the change. Let's see if `5.0.1-canary.6` alters the behavior on your end.

**Comment by steida** [comment]
Can we optionally have react-hot-loader disabled? It will never work correctly because JS is stateful a lot.

**Comment by timneutkens** [comment]
@steida released the new react-hot-loader version.

**Comment by timneutkens** [comment]
@steida could you confirm it's solved/not?

**Comment by steida** [comment]
@timneutkens  Yeah Canary 7 works.

**Comment by timneutkens** [comment]
Great 😄
