### ISSUE TITLE
using-preact example not working on development mode

### ISSUE THREAD

**Issue by johhansantana** [zeit/next.js#3832]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

When running `yarn dev` it should work.

## Current Behavior

When running `yarn dev` it gives me `GET http://localhost:3000/_next/-/commons.js net::ERR_ABORTED`

## Steps to Reproduce (for bugs)

1. npm i -g create-next-app
2. create-next-app --example using-preact using-preact-app
3. cd using-preact-app
4. yarn dev
5. open browser http://localhost:3000
6. ?? doesn't work

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    next.js v5.0.0     |
| node    |     v8.9.3    |
| OS      |    macOS     |
| browser |    chrome     |
| etc     |         |

**Comment by timneutkens** [comment]
There's already an issue for this in the next-plugins repository. It's unrelated to Next.js itself.

**Comment by johhansantana** [comment]
https://github.com/zeit/next-plugins/issues/24
