### ISSUE TITLE
Using <style jsx> from within <Context.Consumer />

### ISSUE THREAD

**Issue by maximilianschmitt** [zeit/next.js#3834]
Hi, I'm trying to use `styled-components` with React's new context API but I'm getting `Warning: Received true for a non-boolean attribute jsx.` in the browser console and when I inspect the DOM, I can see that there is an actual `<style>` element in there.

Here is how I'm trying to use `styled-components` with the new context API (polyfilled from [jamiebuilds/create-react-context](https://github.com/jamiebuilds/create-react-context)).

```js
import createReactContext from "create-react-context";

const StyleContext = createReactContext({ colors: { base: 'black' } });

// ...
class SomeComponent extends React.Component {
  render() {
    return (
      <div>
        <p>Hello world</p>
        
        <StyleContext.Consumer>
          {style =>
            <style jsx>{`
              p {
                color: ${style.colors.base};
              }
            `}</style>
          }
        </StyleContext.Consumer>
      </div>
    )
  }
}
```

This is my setup:

```json
{
    "@zeit/next-typescript": "^0.0.10",
    "create-react-context": "^0.1.6",
    "next": "^5.0.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "typescript": "^2.7.2"
}
```

I found a related issue #3432 but the error there seems to be of a different origin (defining the style in a separate file). Am I doing something wrong or is `styled-jsx` not (yet) compatible with the new context API? Is there any way I can work around the issue I'm having?

Thanks for your help!

**Comment by timneutkens** [comment]
You can't use styled-jsx like this. Please file an issue here: github.com/zeit/styled-jsx
