### ISSUE TITLE
Cannot npm install next

### ISSUE THREAD

**Issue by jpke** [zeit/next.js#3842]
`npm install next` fails with error:
`npm ERR! 404 Not Found: @zeit/check-updates@1.1.0`

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1. Following instructions here: https://learnnextjs.com/basics/getting-started/setup
2. `npm install next` should succeed
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 5.6.0        |
| node    |  9.5.0       |
| OS      | OSX 10.12.6        |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
The package is available on github: https://www.npmjs.com/package/@zeit/check-updates

Maybe there was an error at npm's side 🤔

**Comment by gcdurastanti** [comment]
What was the resolution to this? I've been seeing this same behavior even though the package is definitely available.

**Comment by jpke** [comment]
I finally got it to work by removing my auth info from my npmrc file.

**Comment by Grant05** [comment]
I'm getting the same issue trying to install next. 
npm ERR! code E404
npm ERR! 404 Not Found: @zeit/check-updates@1.1.0
