### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by billnbell** [zeit/next.js#3845]
`<html lang="en-US"><head><meta charSet="utf-8" class="next-head"/><link rel="preload" href="/_next/1519032583163/page/my-community/.js" as="script"/><link rel="preload" href="/_next/1519032583163/page/_error.js" as="script"/>`

then...

`<script async="" id="__NEXT_PAGE__/my-community/" type="text/javascript" src="/_next/1519032583163/page/my-community/.js"></script>`

Getting error:
GET http://localhost:3000/_next/1519032583163/page/my-community/.js net::ERR_ABORTED

When upgrading to 4.2.3

Note:
    "react": "^16.2.0",
    "react-apollo": "^2.0.4",
    "react-dom": "^16.2.0",

**Comment by timneutkens** [comment]
Try upgrading to v5 canary. It's fixed there. (`next@canary`)

**Comment by timneutkens** [comment]
`npm i next@canary`

**Comment by timneutkens** [comment]
That will install `5.0.1-canary.6`

**Comment by billnbell** [comment]
OK it comes up, but when I refresh http://localhost:3000/my-community/ is gives me a 404.

**Comment by billnbell** [comment]
I am making sure I did an npm install. And will report back
