### ISSUE TITLE
Canary Command-R refresh shows 404

### ISSUE THREAD

**Issue by billnbell** [zeit/next.js#3847]
When clicking around it works fine. But when I press Command-R I get a 404. Why?

Is there something I need to setup with routes for SSR?

**Comment by billnbell** [comment]
OK It has to do with

http://localhost:3000/my-community/

vs

http://localhost:3000/my-community

The http://localhost:3000/my-community works fine. How do I use that to make both work?

**Comment by billnbell** [comment]
I did the following and it works:

`    server.get('*', (req, res) => {
      // https://github.com/zeit/next.js/issues/1189
      const parsedUrl = parse(req.url, true)
      const { pathname, query } = parsedUrl

      if (pathname.length > 1 && pathname.slice(-1) === '/') {
        app.render(req, res, pathname.slice(0, -1), query)
      } else {
        handle(req, res, parsedUrl)
      }
    })
`

**Comment by timneutkens** [comment]
It's something that has to be handled in userland, we basically enforce without `/` at the end.
