### ISSUE TITLE
Css is loading after DOM is ready and glitches seen.

### ISSUE THREAD

**Issue by rafinkarki** [zeit/next.js#3848]
I am actually using **@zeit/next-sass** and all of my scss files are withing styles directory within root folder.
Then within components like **import '../../styles/header.scss';** .

This process is working fine but css and styling appears only when all elements are loaded and glitches seen.

**Comment by rafinkarki** [comment]
```
module.exports = withSass({
  webpack: (config, { dev }) => {
    config.plugins.push(
      // If you want to export an environent variable from the server to the
      // client (so that you can write isomorphoic code), this is how you can 
      // do that with webpack. Note we use dotenv module to import environment 
      // variables configured in .env. This can be useful for setting options
      // for things like API URL hostnames.
      new webpack.DefinePlugin({
        'process.env.MY_ENV_VAR': JSON.stringify(process.env.MY_ENV_VAR)
      })
    );
    return config;
  }
```

This is my next.config.js file

**Comment by timneutkens** [comment]
Please try upgrading next-sass, should be fixed. Otherwise file it under next-plugins, with a *reproducible example*. Otherwise it's really hard for us to check it out and help 👍
