### ISSUE TITLE
Long term caching (vendor code splitting)

### ISSUE THREAD

**Issue by rashidul0405** [zeit/next.js#3850]
## Feature Request
I'm not quite sure does this play well with next.js concepts. [create-react-app repo](https://github.com/facebook/create-react-app) contains lots of [discussion](https://github.com/facebook/create-react-app/issues/3878) on this [topic](https://github.com/facebook/create-react-app/pull/3145).

[[facebook/create-react-app#2206](https://github.com/facebook/create-react-app/issues/2206)] It would be beneficial for splitting the js bundle into app and vendor files.
My app code keeps changing but vendor dependencies rarely change. splitting into two files will be a lot beneficial for long term caching.

If I decorate it as below will it plays well with next's automatic code splitting?

```js
module.exports = {
  webpack(config, { prod }) {
    // pseudo code - modify CommonschunkPlugin behavior and return config.
    new webpack.optimize.CommonsChunkPlugin({
	    name: "vendor",
	    // filename: "vendor.js"
	    // (Give the chunk a different name)

	    minChunks: Infinity,
	    // (with more entries, this ensures that no other module
	    //  goes into the vendor chunk)
    })
    
  // return config
  }
}
```

**Comment by timneutkens** [comment]
It might work, but we're going to address this for next v6

**Comment by ex3ndr** [comment]
So, what's new in v6 about this?
