### ISSUE TITLE
Explicit returned value is missing 

### ISSUE THREAD

**Issue by chinesedfan** [zeit/next.js#3853]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

When I was reading source codes of next.js, I found an interesting place, https://github.com/zeit/next.js/blob/canary/lib/router/router.js#L138.

We'd better to return `true` there? Those codes were introduced by #1250.

## Current Behavior

Return without explicit boolean value.

**Comment by arunoda** [comment]
@chinesedfan Thanks for the issue.
We just fixed it.
