### ISSUE TITLE
Next@5 errors on external routes when used with static CDN

### ISSUE THREAD

**Issue by alexindigo** [zeit/next.js#3855]
When using next.js app in production mode with assets hosted on static (or not next.js powered) CDN  it breaks when user navigates to non-existing page.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Expected behavior to do full page "refresh" to allow integration between next.js powered pages other web pages on internet.

## Current Behavior

It renders unexpected error page:
![unexpected error](http://ia.gs/2X240E311g0E/Image%202018-02-20%20at%2011.59.45%20AM.png)

## Steps to Reproduce (for bugs)
I created example repo: https://github.com/alexindigo/next-ab

## Context
It doesn't allow us to integrate new next.js powered pages with the existing website.

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |  5.0.0   |
| node    |  8.9.3  |
| OS      |  macOS 10.13.3  |
| browser |  Chrome 64  |

Thank you.

**Comment by arunoda** [comment]
@alexindigo Thanks for the issue.
PR https://github.com/zeit/next.js/pull/3849 has the fix for this issue.

**Comment by arunoda** [comment]
I just also published a new canary release with this fix: https://github.com/zeit/next.js/releases/tag/5.0.1-canary.7
