### ISSUE TITLE
Ability to load different next.config.js files based on lifecycle hook

### ISSUE THREAD

**Issue by alexindigo** [zeit/next.js#3857]
With introduction of next-plugins we've got more functionality and dependencies exposed in `next.config.js`, using plugins like `next-sass` and others adds extra development dependencies to the runtime, even in production mode, since `next.config.js` is execute at server start time.
Requiring us to carry along node modules that we'd never use with production baked artifacts.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

As we discussed last week, possible solution would be to allow next.js to read lifecycle specific configs, like `next.config.dev.js` and `next.config.build.js` with fallback to `next.config.js`.

## Current Behavior
Loads `next.config.js` irrespectively of the lifecycle stage. 

Thank you.

**Comment by vorillaz** [comment]
You may easily tweak/compose `next.config.js` as:

```javascript
import webpackProdConf from './prod';

module.exports = (nextConfig = {}) => {
  const isProd = process.env.NODE_ENV === 'production'
  
  return Object.assign({}, nextConfig, {
    webpack(config, options) {
      if (isDev) {
        Object.assign(config, webpackProdConf);
      }
      // ...
      return config
    }
  })
}``

**Comment by alexindigo** [comment]
Thanks for the suggestion @vorillaz – looks like in your example it keeps prod config separate, and in my use case we have that `module.exports = withCss(withSass(config))` that bring all sorts of dependencies.
There is a workaround to move `require` call inside webpack config function, but it would be a hack rather than stable solution. And during prior conversation with @rauchg this is what we agreed on – better "API" for the community as a whole. Added this issue, so it won't get lost in the woods.

**Comment by vorillaz** [comment]
I see @alexindigo . I still think that splitting the logic within separate files causes lots of problems. IMHO it looks more natural sharing dependencies across development and production with composed config files.
