### ISSUE TITLE
Above the fold CSS

### ISSUE THREAD

**Issue by virzak** [zeit/next.js#3858]
Hello,

What's the best way of combining inline css (examples/with-global-stylesheet) and an external one (examples/with-next-sass).

I have a one pager with a lot of small images below the fold and CSS below the fold.

The scss needed above the fold is stored in aboveTheFold.scss and imports anything global like bootstrap.
The rest of scss is stored in index.scss which imports aboveTheFold.scss.

Attempting to wrap the code with `withSass` failed for me.

Please advise and thanks in advance.

**Comment by timneutkens** [comment]
You can probably get some inspiration from https://github.com/zeit/next.js/pull/3451
