### ISSUE TITLE
Maintainer for Zeit/Hyperlinks

### ISSUE THREAD

**Issue by lacymorrow** [zeit/next.js#3859]
Some of the Hyper plugins seem to be dead, mainly hyperlinks. There are year-old PRs with needed fixes, the URL listed for Hyper (hyperterm.org) redirects to a 20 year-old website, and the first issue (from 2016) reads _"Doesn't work at all"_.

We either need a core maintainer, an authorized community maintainer given access, or a new community plugin entirely added to the Hyper plugins database.

Can someone comment?

**Comment by chabou** [comment]
Hi @lacymorrow, `hyperlinks` will be deprecated with Hyper v2 release.
Links are now handled directly by `xtermjs` in our canary release and you don't need any plugin to handle them.

Do not hesitate to open an issue in https://github.com/zeit/hyper if you encounter some problems with this canary functionality.

**Comment by timneutkens** [comment]
Thanks to xterm the canary channel is also way faster and better at handling large output. So it's highly recommended to upgrade. Here's how to upgrade: https://zeit.co/blog/canary#hyper

The Hyperlinks repository will be deprecated and archived when v2 comes out officially (very soon).

**Comment by lacymorrow** [comment]
It would be beneficial to note this on the Zeit/Hyperlinks page if anything to prevent any more confusion to the folks creating issues there. I saw that the URL has updated 👍
