### ISSUE TITLE
[feature request] Migrate to Closure compiler

### ISSUE THREAD

**Issue by corysimmons** [zeit/next.js#386]
Closure compiler seems objectively better: https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016#raw-data

https://github.com/cramforce/splittable

**Comment by nkzawa** [comment]
It seems `splittable` doesn't support some feature we need (HMR, multiple layers of bundle).
I think ClosureComiler (JS version) can be a good replacement of UglifyJS.

**Comment by corysimmons** [comment]
Good points. I think that's a good idea.

**Comment by arunoda** [comment]
I think it's uglify does a good job in general. (Both the size and execution)
Since we are using babel, https://github.com/babel/babili is also another option.

I think current setup is reasonable.

**Comment by corysimmons** [comment]
reasonable !== best
