### ISSUE TITLE
npm run build stuck

### ISSUE THREAD

**Issue by zakst** [zeit/next.js#3862]
I am trying to build the app but it just gets stuck, does not throw and error at all

## Expected Behavior
Build the app

## Current Behavior
after running the command `npm run build` the following shows up and nothing happens

```
> Using external babel configuration
> Location: "path\to\\.babelrc"
> Using "webpack" config function defined in next.config.js.
```

my babel is as follows

```
{
  "presets": ["next/babel", "latest", "stage-2"],
  "plugins": [
    [
      "inline-react-svg",
      "styled-components",
      "styled-jsx/babel",
      { "ssr": true, "displayName": true, "preprocess": false }
    ]
  ]
}

```

And the `next.config.js` is

```
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  exportPathMap: () => ({
    '/': { page: '/' },
    '/pre': { page: '/pre' }
  }),
  webpack: (config, { dev }) => {
    const newConfig = config;
    const oldEntry = newConfig.entry;

    newConfig.entry = () => {
      return oldEntry().then(entries => {
        entries['main.js'].unshift('babel-polyfill');
        return entries;
      });
    };

    newConfig.module.rules.push(
      {
        test: /\.((sa|sc|c)ss|jpg|png)$/,
        use: [
          {
            loader: 'emit-file-loader',
            options: {
              name: 'dist/[path][name].[ext]'
            }
          }
        ]
      },
      {
        test: /\.(sa|sc|c)ss$/,
        use: ['extracted-loader'].concat(
          ExtractTextPlugin.extract({
            use: [
              'babel-loader',
              {
                loader: 'css-loader',
                options: {
                  url: true,
                  minimize: !dev,
                  sourceMap: dev,
                  importLoaders: 2
                }
              },
              {
                loader: 'postcss-loader',
                options: {
                  plugins: [require('autoprefixer')({})]
                }
              }
            ]
          })
        )
      }
    );

    newConfig.plugins.push(
      new ExtractTextPlugin({
        filename: path.join(
          __dirname,
          'access-content/static/assets/vendor.css'
        ),
        allChunks: true
      })
    );

    return newConfig;
  }
};

```

Also here goes the `scripts` object in `package.json`

```
 "scripts": {
    "dev": "node server.js",
    "build": "next build && next export",
    "start": "next start"
  },
```

I tried `next build` only does not work.
Any ideas anyone?

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |   latest      |
| node    |   9.3.0      |
| OS      |   windows 10 64bit      |
| browser |    chrome     |
| npm     |  5.5.1       |

**Comment by timneutkens** [comment]
I'm guessing because you're running *double compilation* of sass. Try using / taking inspiration from the next-sass plugin here: github.com/zeit/next-plugins

**Comment by zakst** [comment]
@timneutkens That should not be the case, as i did get the whole application built. You think there can be any other reason? Thanks for `next-sass` though will use in the next project.

**Comment by benhjames** [comment]
I had this the other day - clearing the `node_modules/.cache` folder fixed it from hanging. I have no idea how it got into a corrupted state in the first place!

**Comment by frizadiga** [comment]
@timneutkens why this issue closed, before we have solution for the issue?

**Comment by timneutkens** [comment]
No clear minimal reproducible reproduction, making it impossible to debug this from our side. Please provide a minimal github repository.

**Comment by StefanoChiodino** [comment]
I can reproduce this on https://github.com/rauchg/blog on Win10,

Just changed the scripts in `package.json` to
```
  "scripts": {
    "dev": "next",
    "build": "next build",
    "export": "next export",
    "start": "NODE_ENV=production node server"
  }
```

then ran `npm i && npm run build && npm run export`

Terminal hangs here forever
![image](https://user-images.githubusercontent.com/1428893/50966565-2ef26700-14cd-11e9-842b-cd71618d2e9d.png)
