### ISSUE TITLE
Next 5: Pages broken with custom .babelrc

### ISSUE THREAD

**Issue by DaveStein** [zeit/next.js#3863]
- [X] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Page should render

## Current Behavior
Page is not rendering. Instead giving error that ` The default export is not a React Component in page: "/"`

## Steps to Reproduce (for bugs)
1. Update to Next 5 using command from blog: `npm i next@latest react@latest react-dom@latest`

I reduced my page to this, and still got error:

```
export class MyComp extends React.Component {
  render() {
    return (
        <div>
          Hello World
        </div>
    )
  }
}

export default MyComp;
```

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     5.0.0    |
| node    |     9.4.0    |
| OS      |     Mac    |
| browser |     All    |
| react | 16.2.0 |
| react-dom | 16.2.0 |

**Comment by DaveStein** [comment]
Changed next back to `"^4.2.0"` then ran `npm rm -rf node_modules/next && npm install`. Then restarted server and module rendered as expected. Just writing this as sanity check it was Next upgrade vs anything else.

**Comment by DaveStein** [comment]
Sorry for editing title often... I had nuked customer server & babelrc and got it working.. then narrow it down. Anywho, here is my `.babelrc` file which works fine for Next 4:

```
{
  "env": {
    "dev": {
      "presets": ["next/babel", "env"]
    },
    "build": {
      "presets": ["next/babel", "env"]
    },
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ]
    }
  }
}
```

**Comment by timneutkens** [comment]
`dev` => `development`:
```
{
  "env": {
    "development": {
      "presets": ["next/babel", "env"]
    },
    "build": {
      "presets": ["next/babel", "env"]
    },
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ]
    }
  }
}
```

Or you can just provide it at the top level:

```
{
  "presets": ["next/babel"],
  "env": {
    "development": {
      "presets": ["next/babel", "env"]
    },
    "build": {
      "presets": ["next/babel", "env"]
    },
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ]
    }
  }
}
```

Also, it makes no sense to add `"env"` since that's already included in `"next/babel"`, meaning it's ran twice over all your code 😅

**Comment by DaveStein** [comment]
@timneutkens How come `dev` worked before and now it doesn't? I tried the below snippet and then I got a syntax error as if no babel ran. You know, `unexpected token` on the first `<` for my `render` function. Everything worked with what you pasted - but what about having the top level preset vs the env-specific preset made it work/not work? I did remove `env` from your example in the additional presets, and it worked as you said. 
```
{
  "env": {
    "development": {
      "presets": ["next/babel", "env"]
    },
    "build": {
      "presets": ["next/babel", "env"]
    },
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ]
    }
  }
}
```

**Comment by DaveStein** [comment]
I also trimmed my file down to:
```
{
  "presets": ["next/babel"],
  "env": {
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ]
    }
  }
}
```

Jest is now blowing up when running tests. `Unexpected token import`
