### ISSUE TITLE
500 errors flash due to markup mismatch

### ISSUE THREAD

**Issue by migueloller** [zeit/next.js#3865]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

When encountering an internal server error, it's expected that the server rendered markup matches the clients, thus avoiding flashing content.

## Current Behavior

Currently internal server errors will cause a flash. More explicitly, the `statusCode` prop isn't present when rendering `_error.js` in the client, causing the markup to differ.

## Steps to Reproduce (for bugs)

1. Setup a simple Next.js project.
2. Add a page `pages/500.js` with the following content:
```js
export default () => { throw new Error('Boom!') }
```
3. `next build && next start`
4. Point a browser to `http://localhost:3000/500`.

## Context

When deploying an application to production, internal server errors cause an unwanted flash of content.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |v5.0.1-canary.7|
| node    |v9.4.0|
| OS      |macOS v10.13.3|
| browser |Chrome v64|

**Comment by timneutkens** [comment]
Please try `next@canary`

**Comment by mgiraldo** [comment]
i can reproduce in `5.0.1-canary.13`

**Comment by timneutkens** [comment]
Should be fixed now.
