### ISSUE TITLE
How Reload getInitialProps on Back Button?

### ISSUE THREAD

**Issue by vapstor** [zeit/next.js#3872]
Can someone help me, how to refresh the page and _call_ getInitialProps _again_ when i click on back button of the browser? i got no answer on StackOverflow and Gitter so..

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    latest    |
| node    |    9.4.0     |
| OS      |    Mac     |
| browser |    Chrome     |
| etc     |         |

**Comment by ptomasroos** [comment]
This is still not an issue. Its a question.
