### ISSUE TITLE
Clean urls can not support refresh page?

### ISSUE THREAD

**Issue by InvincibleJun** [zeit/next.js#3881]
At the official level，nextjs can clean urls and create Dynamic Pages.
[The address: https://learnnextjs.com/basics/server-side-support-for-clean-urls/create-a-custom-server](https://learnnextjs.com/basics/server-side-support-for-clean-urls/create-a-custom-server).
But,It will be as 404's page when Refresh page.
How to do ?

**Comment by sergiodxa** [comment]
They do, check you have added them to be handled in your custom server. Also check the [custom server Express example](https://github.com/zeit/next.js/tree/canary/examples/custom-server-express).
