### ISSUE TITLE
Next@5 server bundle has absolute file paths for require()

### ISSUE THREAD

**Issue by robdmoore** [zeit/next.js#3887]
With server-side bundles in next@5 the require statements that are built via `next build` now have an absolute file path.

E.g. at the bottom of `<projroot>/.next/dist/bundles/pages/_error.js` it has `module.exports = require("C:\\path\\to\\<projroot>\\node_modules\\next\\dist\\pages\\_error.js");` rather than `require("next\\dist\\pages\\_error.js");`.

This means that if I build my site on a continuous integration server and then shift the result onto a deployment server it fails because the file path is wrong.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
After running `next build` none of the built files should not have absolute file paths.

## Current Behavior
After running `next build` the built files have absolute file paths.

## Steps to Reproduce (for bugs)
1. Run `next build`
2. Inspect the `.next/dist` folder

## Context
I'd like to follow continuous delivery practices and build my site once on a continuous integration server then use that build across multiple environments (e.g. dev, test, prod) via a deployment pipeline.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  5.0.0  |
| node    |  6.8.1 |
| OS      | Windows 10  |

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/issues?q=is%3Aissue+sort%3Aupdated-desc+absolute+file+paths+is%3Aclosed

https://github.com/zeit/next.js/issues/3533

Upgrade to `next@canary`. Will be released as stable soon.

**Comment by robdmoore** [comment]
Doh! Sorry @timneutkens :( I didn't see those when I looked.

Can confirm this is fixed with canary - thanks so much!

**Comment by timneutkens** [comment]
No worries 👍🏻🙏🏻
