### ISSUE TITLE
Allow getInitialProps to return an rx.js observable

### ISSUE THREAD

**Issue by nmaro** [zeit/next.js#389]
This is just an idea.

Every time the observable emits a new value, the component should be reloaded.

I see at least 2 cases in which this could be useful:

For partially loaded data: for example when fetching multiple apollo graphql queries. Already render the component before all data is loaded, display loading components where necesary.

For subscriptions: for example apollo data subscriptions. Every time the data updates, update the component. Here the server should just pick the first version and render.

In the first case the server should render upon receiving the first value, and in the second it should render when the observable closes, so maybe this should be configurable.

But I can see how this might be considered out of scope :) If you have any idea about how to recreate something equivalent without changing the next.js api, please chime in.

**Comment by rauchg** [comment]
This is definitely something I've thought quite a bit about. But instead, I think the best solution to this will be functional composition:

```
export default observable(obv, ({ title }) => (
  <div>{title}</div>
))
```

Imagine an observable that emits the props object. Makes generating a component with `getInitialProps` very easy (you wait for one `data` event and ditch the subscription, or convert it to a `Promise`), and then upon mount hooks you listen indefinitely, ditching the subscription upon unmount.

I'd like to revisit this once either of these happen:
- I see evidence of experimentation along these lines in userland.
- `Observable` lands in ES

**Comment by rauchg** [comment]
This is definitely something I've thought quite a bit about. But instead, I think the best solution to this will be functional composition:

```js
export default observable(obv, ({ title }) => (
  <div>{title}</div>
))
```

Imagine an observable that emits the props object. Makes generating a component with `getInitialProps` very easy (you wait for one `data` event and ditch the subscription, or convert it to a `Promise`), and then upon mount hooks you listen indefinitely, ditching the subscription upon unmount.

I'd like to revisit this once either of these happen:
- I see evidence of experimentation along these lines in userland.
- `Observable` lands in ES

**Comment by arunoda** [comment]
On the other hand, we could write a HOC which does this properly. It use getInitialProps behind the for the initial data and do other stuff in `componentDidMount` and etc.

Not sure specific details, but I assume this can be done in the user-land.
