### ISSUE TITLE
document is not defined when you refresh the page 

### ISSUE THREAD

**Issue by Ai01** [zeit/next.js#3893]
![image](https://user-images.githubusercontent.com/18245929/36663927-1ab903ba-1b1e-11e8-96be-53992a649ac4.png)

l have already create the `_document.js` file. but this error will still happen when the page who has the `getInitialProps` method be  refreshed.

```js
class AllMovies extends Component {

  static getInitialProps = async () => {
    const moviesData = await getMoviesData();
    return moviesData || {};
  };
}

```

**Comment by timneutkens** [comment]
The error is `document` is not defined. This has nothing to do with `_document.js` but with the browser side `document` variable https://developer.mozilla.org/en-US/docs/Web/API/Document.

The module you're importing is using it as you can see here: https://github.com/react-component/notification/blob/8af073bda33ae255c3232a4b00a1e291b4c6b98d/src/Notification.jsx#L92

You'll have to conditionally load the component only on the client side.

**Comment by Ai01** [comment]
```js
      if(typeof window !== "undefined") {
       // message use document
        const message = require('../components/message');
        message.error(errorMessage);
      }
```
