### ISSUE TITLE
babel-loader doesn't run on symlinked files

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#3898]
https://github.com/zeit/next.js/blob/1bcd2e0575c40b577380b0bc5ad5104111cbf510/server/build/webpack.js#L181-L186

The `include: [dir]` means that only files in the current tree can be transpiled.

Say you have a dir like:

```
/app
  - next.config.js
  - packages
    - foo
    - symlinked-package -> /src/symlinked-package
```

The symlinked package is resolved to its "realpath" (`/src/symlinked-package` instead of `/app/packages/symlinked-package`) by webpack. The `include: [dir]` prevents symlinked dirs from being transpiled.

I am wondering what is the reason for having the `include` option?

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    5     |
| node    |   8      |
| OS      |     macOS    |
| browser |      Chrome   |
| etc     |         |

---

**Workaround**

```js
function supportSymlinkedFilesInNextBabelLoader(config) {
  const nextBabelLoader = config.module.rules.find(({use, include, test}) => {
    if (!use) return
    return use.loader === 'babel-loader' && test.toString() === '/\\.+(js|jsx)$/'
  })
  if (!nextBabelLoader) return
  nextBabelLoader.include = undefined
}
```

**Comment by jthegedus** [comment]
@vjpr The discussions here https://github.com/zeit/next.js/issues/3018 and here https://github.com/zeit/next.js/pull/3732 seem related and might be useful to you.

**Comment by majelbstoat** [comment]
Unfortunately, this no longer seems to work for Next 6 and next-plugin-typescript 1.0.0, which moved to using babel-loader as well.

The files are found, and executed, but if the file is outside the main tree, typescript compilation does not happen:

```
 error  in ./lib/editor/constants/BlockType.ts

 Syntax Error: enum is a reserved word (1:0)

 > 1 | enum BlockType {
     | ^
   2 |   Image = 'image',
   3 |   Text = 'text',
```

where most of the code resides under `./app` and is compiled correctly.

Have tried lots of different approaches to get this to work, but no luck. Will be stuck on Next 5.1 until there's a workaround.

**Comment by majelbstoat** [comment]
For others struggling with this, in Next 6 the loader is now `next-babel-loader` not `babel-loader`. And, you'll need to make sure your `.babelrc` file is in the root folder so that it is used for both the app-specific code, and the common code (or have one `.babelrc` in each location.)

**Comment by mstn** [comment]
@majelbstoat thanks for digging out. I wonder if you can share your config files. I am using Next 6 with Typescript. I am facing the same problem with symlinks (lerna).

My settings for the Next app

```
// next.config.js
const withTypescript = require('@zeit/next-typescript'); // v 1.0.1

module.exports = withTypescript();
```

```
// .babelrc
{
    "presets": [
        "next/babel",
        "@zeit/next-typescript/babel"
    ]
}
```

I copied `.babelrc` inside symlinked packages without success.

**Comment by majelbstoat** [comment]
My babelrc is the same as yours. However, I have a single babelrc file sitting in my root directory. You may need to run with `NODE_PRESERVE_SYMLINKS=1`. My nodemon looks like this:

```json
  "execMap": {
    "ts": "NODE_PRESERVE_SYMLINKS=1 ts-node --project tsconfig.server.json"
  }
```

(I'm using a custom server for routing.)

**Comment by mstn** [comment]
@majelbstoat thanks. However, as far as I can tell, `ts-node` should not use babel loader.

**Comment by majelbstoat** [comment]
ts-node runs the custom server. webpack/nextjs use babel loader. But symlinks don't work without that environment variable for me 🤷‍♂️ .

**Comment by timneutkens** [comment]
Tracking this here: #706
