### ISSUE TITLE
.next packaged folder contains absolute path, failing on AWS + time out no logs

### ISSUE THREAD

**Issue by Vadorequest** [zeit/next.js#3903]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
I am trying to host Next.js on AWS Lambda/CloudFormation. (using [Serverless](https://github.com/serverless/serverless))

I am running into two issues:

1. When I host the packaged version of next (.next folder), it fails on AWS with 
    ```
    { Error: Cannot find module '/Users/vadorequest/dev/serverless-with-next/node_modules/next/dist/pages/_document.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.7 (/var/task/.next/dist/bundles/pages/_document.js:86:18)
    at __webpack_require__ (/var/task/.next/dist/bundles/pages/_document.js:23:31)
    at Object.6 (/var/task/.next/dist/bundles/pages/_document.js:78:18)
    at __webpack_require__ (/var/task/.next/dist/bundles/pages/_document.js:23:31)
    at /var/task/.next/dist/bundles/pages/_document.js:70:18
    at Object.<anonymous> (/var/task/.next/dist/bundles/pages/_document.js:73:10) code: 'MODULE_NOT_FOUND' }
     ```
    I don't understand why there are absolute paths used in the generated code. I looked at the content of `.next` folder and there are tons of them, how are we supposed to use this package if it cannot be moved to another system? I cannot compile on AWS lambda. Is there a way of replacing those path programmatically using webpack for instance?

2. I manually replaced those paths to match AWS, basically replaced `/Users/vadorequest/dev/serverless-with-next` to `/var/task` in the `.next` folder. Once uploaded to AWS and hitting my endpoint `https://bcwl62lv2e.execute-api.us-east-1.amazonaws.com/dev` it loads for 30 seconds and then time out. Logs are empty, I don't know what's happening, at first I assumed the first Next.js load was slow (default timeout 6s) but 30s is way too much and something must be wrong. How can I debug this? Is there a way to configure Next.js to log what it does?

## Steps to Reproduce (for bugs)

1. Go to https://github.com/Vadorequest/serverless-with-next
1. `git clone git@github.com:Vadorequest/serverless-with-next.git`
1. `nvm use` or use node 6.10.3
1. `npm i`
1. `npm run build:staging` => Generates a .next folder, you can check files have absolute path here
1. `serverless deploy -v --package .serverless` => Deploy to AWS, requires serverless cli, and an AWS account

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    5     |
| node    |     6.10.3    |
| OS      |    MacOS X     |

**Comment by huangbong** [comment]
Not an answer to your question, but I would recommend getting rid of `serverless` and using `up` instead. We are running on Lambda with 2048mb mem functions. <200ms response times on all of our endpoints (including DB fetch). No infrastructure to manage and nearly the same perf as EC2.
https://github.com/apex/up
https://github.com/apex/up-examples/tree/master/oss/node-next

**Comment by timneutkens** [comment]
Upgrade to next@canary. It’s been fixed already.

**Comment by Vadorequest** [comment]
@timneutkens Thanks!

I use `npm i next@5.0.1-canary.9 -S` now, and indeed it fixes the paths. Now, I only have absolute paths in the `*.js.map` files, but that's not a real issue. (I should probably ignore the `.next` folder for sourcemaps support?)

But I still have the 2nd issue, where my script times out (30s) with no logs and I have no idea what's happening. Any trick to debug this?
