### ISSUE TITLE
Using Trello client api

### ISSUE THREAD

**Issue by sinapcs** [zeit/next.js#3914]
Hi. first of all thanks for this great library.
I have a problem using client.js from Trello.

refrence: https://developers.trello.com/docs/clientjs

I added it's script to head using <Head> component of 'next/head'

but when I try to use window.Trello.authorize(opts) or Trello.authorize(opts) in my component it says Trello is not defined. can someone help me handle this?

**Comment by haohcraft** [comment]
how did you add the script to the `next/head`?
For the third party script, it's better to use `onload` callback to trigger the following function. Something like:

```
const ThirdParty = () => {
  const onload = () => {
    if (window && window.Trello) {
      window.Trello.authorize(opts);
    }
  };
  return (<script onload={onload} src="https://trello.com/1/client.js?key=[key]"></script>);
}

```

**Comment by timneutkens** [comment]
I'd recommend using their api without the client so that you can server render too. But including in the head should work fine. If it doesn't it's related for the script.

**Comment by sinapcs** [comment]
I did fix it. it doesn't work when I add it to head of my component. but If I add it to _document.js it works.
thank you for your advise
