### ISSUE TITLE
Make HMR heartbeat configurable

### ISSUE THREAD

**Issue by majelbstoat** [zeit/next.js#3917]
When running NextJS inside a docker container that mounts a local volume, the server is typically slower to respond than on bare metal. In combination with Node 8, this often leads to INCOMPLETE_CHUNKED_ENCODING errors when hot module reloading.

This was fixed for bare metal setups in https://github.com/zeit/next.js/pull/2166, but the chosen heartbeat is often too short for a containerised instance.

Can we make heartbeat in `server/hot-reloader.js` configurable through next.config.js? 

https://github.com/zeit/next.js/blob/canary/server/hot-reloader.js#L224

**Comment by timneutkens** [comment]
As no one else has brought up or upvoted this issue I don't think we should change the default.
