### ISSUE TITLE
Google API client | help wanted

### ISSUE THREAD

**Issue by sahlouls** [zeit/next.js#3918]
Hi,
I wish to use Gapi for authentication in a future nextjs app. Any idea if this is possible ? or have been done already ?

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.
Thanks

**Comment by timneutkens** [comment]
@iaincollins made this https://github.com/iaincollins/next-auth

**Comment by sahlouls** [comment]
Thanks for the link :smile:
