### ISSUE TITLE
Seek help, Serverless + Next.js

### ISSUE THREAD

**Issue by Vadorequest** [zeit/next.js#3919]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

I'm struggling to put Next.js and Serverless together. I could use some help with my latest issue. I don't really know if the bug is on Next.js side, or serverless side (none, I guess, it's just hard to put them together) so any help would be greatly appreciated.

One of the errors I'm running into is `Error: INVALID_BUILD_ID`, which is on Next.js side, and I don't really know why.

Explained in depth there:
https://github.com/serverless/serverless/issues/4772#issuecomment-369385253

Thanks!

**Comment by yakovkhalinsky** [comment]
Have you got `Use Lambda Proxy integration` checked on the API gateway endpoint?

**Comment by TomiTakussaari** [comment]
I have mostly working example app using Serverless & Next.js here: https://github.com/TomiTakussaari/serverless-nextjs

**Comment by TomiTakussaari** [comment]
I think I got INVALID_BUILD_ID errors when i did not have next.js build directory (.next) properly included in serverless bundle.

Also, I believe you need to add wildcard http handler to SSR other pages besides /.

**Comment by Vadorequest** [comment]
@TomiTakussaari I tried to use your way but it's failing too. The browser displays a string instead of the actual app.

```
PCFET0NUWVBFIGh0bWw+PGh0bWw+PGhlYWQ+PG1ldGEgY2hhclNldD0idXRmLTgiIGNsYXNzPSJuZXh0LWhlYWQiLz48bGluayByZWw9InByZWxvYWQiIGhyZWY9Ii9fbmV4dC83YTI0ZWU3MC0wYWJjLTQ1YjEtYmU5MC1lNDJjODZlMWI4NGUvcGFnZS9pbmRleC5qcyIgYXM9InNjcmlwdCIvPjxsaW5rIHJlbD0icHJlbG9hZCIgaHJlZj0iL19uZXh0LzdhMjRlZTcwLTBhYmMtNDViMS1iZTkwLWU0MmM4NmUxYjg0ZS9wYWdlL19lcnJvci5qcyIgYXM9InNjcmlwdCIvPjxsaW5rIHJlbD0icHJlbG9hZCIgaHJlZj0iL19uZXh0LzM5OTM2MDM5MTZiODYxZmZmYjE3OGQ3YzBkMjVhZTI5L2FwcC5qcyIgYXM9InNjcmlwdCIvPjwvaGVhZD48Ym9keT48ZGl2IGlkPSJfX25leHQiPjxkaXYgZGF0YS1yZWFjdHJvb3Q9IiI+SGVsbG8gd29ybGQhPGJyLz48aW1nIHNyYz0iL3N0YXRpYy9zZXJ2ZXJsZXNzLnN2ZyIgYWx0PSJTZXJ2ZXJsZXNzIGxvZ28iIGhlaWdodD0iNTAiIHdpZHRoPSI1MCIvPsKgU2VydmVybGVzczxici8+PGltZyBzcmM9Ii9zdGF0aWMvbmV4dGpzLnBuZyIgYWx0PSJOZXh0LmpzIGxvZ28iLz48L2Rpdj48L2Rpdj48ZGl2IGlkPSJfX25leHQtZXJyb3IiPjwvZGl2PjxzY3JpcHQ+CiAgICAgICAgICBfX05FWFRfREFUQV9fID0geyJwcm9wcyI6e30sInBhZ2UiOiIvIiwicGF0aG5hbWUiOiIvIiwicXVlcnkiOnt9LCJidWlsZElkIjoiN2EyNGVlNzAtMGFiYy00NWIxLWJlOTAtZTQyYzg2ZTFiODRlIiwiYnVpbGRTdGF0cyI6eyJhcHAuanMiOnsiaGFzaCI6IjM5OTM2MDM5MTZiODYxZmZmYjE3OGQ3YzBkMjVhZTI5In19LCJhc3NldFByZWZpeCI6IiIsIm5leHRFeHBvcnQiOmZhbHNlLCJlcnIiOm51bGwsImNodW5rcyI6W119CiAgICAgICAgICBtb2R1bGU9e30KICAgICAgICAgIF9fTkVYVF9MT0FERURfUEFHRVNfXyA9IFtdCiAgICAgICAgICBfX05FWFRfTE9BREVEX0NIVU5LU19fID0gW10KCiAgICAgICAgICBfX05FWFRfUkVHSVNURVJfUEFHRSA9IGZ1bmN0aW9uIChyb3V0ZSwgZm4pIHsKICAgICAgICAgICAgX19ORVhUX0xPQURFRF9QQUdFU19fLnB1c2goeyByb3V0ZTogcm91dGUsIGZuOiBmbiB9KQogICAgICAgICAgfQoKICAgICAgICAgIF9fTkVYVF9SRUdJU1RFUl9DSFVOSyA9IGZ1bmN0aW9uIChjaHVua05hbWUsIGZuKSB7CiAgICAgICAgICAgIF9fTkVYVF9MT0FERURfQ0hVTktTX18ucHVzaCh7IGNodW5rTmFtZTogY2h1bmtOYW1lLCBmbjogZm4gfSkKICAgICAgICAgIH0KCiAgICAgICAgICBmYWxzZQogICAgICAgIDwvc2NyaXB0PjxzY3JpcHQgYXN5bmM9IiIgaWQ9Il9fTkVYVF9QQUdFX18vIiBzcmM9Ii9fbmV4dC83YTI0ZWU3MC0wYWJjLTQ1YjEtYmU5MC1lNDJjODZlMWI4NGUvcGFnZS9pbmRleC5qcyI+PC9zY3JpcHQ+PHNjcmlwdCBhc3luYz0iIiBpZD0iX19ORVhUX1BBR0VfXy9fZXJyb3IiIHNyYz0iL19uZXh0LzdhMjRlZTcwLTBhYmMtNDViMS1iZTkwLWU0MmM4NmUxYjg0ZS9wYWdlL19lcnJvci5qcyI+PC9zY3JpcHQ+PHNjcmlwdCBzcmM9Ii9fbmV4dC8zOTkzNjAzOTE2Yjg2MWZmZmIxNzhkN2MwZDI1YWUyOS9hcHAuanMiIGFzeW5jPSIiPjwvc2NyaXB0PjwvYm9keT48L2h0bWw+
```

I did this in a separate branch: https://github.com/Vadorequest/serverless-with-next/tree/serverless-http

**Comment by Vadorequest** [comment]
@TomiTakussaari Indeed... What was missing was the `any+`

```
      - http:
          method: GET
          path: /{any+}
```

This way I catch other routes and redirect everything towards the main handler.

**Comment by TomiTakussaari** [comment]
> @TomiTakussaari I tried to use your way but it's failing too. The browser displays a string instead of the > actual app.
> ...
> I did this in a separate branch: https://github.com/Vadorequest/serverless-with-next/tree/serverless-http

Thats because serverless-http is configured to use apigw-binary mode, while your serverless.yml does not add necessary serverless-apigw-binary plugin which would actually enable that binary mode in Apigw.

I use binary mode so it's possible to also serve binary files. (images, fonts, compressed content, etc). For big files, its probably better to use some other way.
