### ISSUE TITLE
Custom Server - showing 404 in production

### ISSUE THREAD

**Issue by sureshdurairaj** [zeit/next.js#3920]
Here's the URL looks like,

www.mydomain.com/suresh/450

Here **suresh** is parsed as "**username**" and **450** is parsed as "**amount**". Here's the **server.js** code
`const express = require("express");
const { parse } = require("url");
const next = require("next");

const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

app
  .prepare()
  .then(() => {
    const server = express();

    server.get("/", (req, res) => {
      return handle(req, res);
    });
    server.get("/get-link", (req, res) => {
      return handle(req, res);
    });
    server.get("/:username/", (req, res) => {
      const actualPage = "/processor";
      const mergedQuery = Object.assign(
        {},
        { reqQuery: req.query },
        { reqParams: req.params }
      );
      console.log('req', req);
      console.log('cProps', cProps);
      return app.render(req, res, actualPage, { cProps: mergedQuery });
    });

    server.get("/:username/:amount", (req, res) => {
      const actualPage = "/processor";
      const mergedQuery = Object.assign(
        {},
        { reqQuery: req.query },
        { reqParams: req.params }
      );
      return app.render(req, res, actualPage, { cProps: mergedQuery });
    });

    server.get("*", (req, res) => {
      return handle(req, res);
    });

    server.listen(3005, err => {
      if (err) throw err;
      console.log("> Ready on http://localhost:3005");
    });
  })
  .catch(ex => {
    console.error(ex.stack);
    process.exit(1);
  });
`
In Dev mode, this URL **www.mydomain.com/suresh** and **www.mydomain.com/suresh/450**is working as expected, But after build and running in production its showing 404.

Here's my package.json
`{
  "name": "stellar-me",
  "version": "1.0.0",
  "scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production next start"
  },
  "dependencies": {
    "next": "5.0.0",
    "express": "4.16.2",
    "next-redux-wrapper": "^1.0.0",
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-redux": "^5.0.1",
    "redux": "^3.6.0",
    "redux-devtools-extension": "^2.13.2",
    "redux-thunk": "^2.1.0",
    "stellar-sdk": "^0.8.0"
  },
  "license": "ISC"
}
`

Please let me know whats happening.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   5.0.0      |
| node    |     6.10.3    |
| OS      |    Ubuntu 16.04     |
| browser |     Chrome    |
| etc     |         |

**Comment by timneutkens** [comment]
Please provide a repository that we can check, either way this is most likely not a Next.js issue. But a *question* which should be posted on https://spectrum.chat/next-js as per the issue template.

**Comment by sureshdurairaj** [comment]
Thanks Tim. Here's the repo https://github.com/sureshdurairaj/stellarme

**Comment by DaveStein** [comment]
I am seeing similar behavior on next 5.0. When running `npm start` I am 404ing on anything I have tried using express for with `.server.get()`.  If I run `npm run dev`, everything runs fine. Basically the page loads, and then makes an XHR request that fails.

The scripts in package.json:
```
"start": "npm run build && next start -p 3001",
"build": "NODE_ENV=build next build",
"dev": "NODE_ENV=dev nodemon server.js"
```
