### ISSUE TITLE
Custom directory for "pages"

### ISSUE THREAD

**Issue by Vadorequest** [zeit/next.js#3921]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

I'd like to use a custom sub directory to store my "pages". I looked in the next.config.js but couldn't find any way of customizing it. Also, I found https://github.com/zeit/next.js/blob/07af67bfea3eb366c3b3457db9534d532d2e902b/server/build/webpack/utils.js#L4 which makes me thing it's not possible yet.

Is this something you intend to support?

**Comment by timneutkens** [comment]
It's not possible. And it's been discussed in other issues.

We're currently not planning to change it to be configurable.

**Comment by billnbell** [comment]
We really should consider re-opening this.

Adding a variable to allow.

public/pages/
admin/pages/

So that we can have 2 directories of pages.

**Comment by lxblvs** [comment]
How is this not a thing?

**Comment by timneutkens** [comment]
Posted https://github.com/zeit/next.js/issues/8451
