### ISSUE TITLE
Hijacking forms to use custom routes

### ISSUE THREAD

**Issue by mrozbarry** [zeit/next.js#3922]
I have been contracted to work on an SPA, and some of it is using forms. The problem is the forms action goes to a custom route. My current solution is:

```javascript
<form
  action="/page"
  method="get"
  onSubmit={e => {
    e.preventDefault()
    Router.push(`/search/${this.state.hashedSearch}`);
  }}
>
```

The problem is this forces the page to do a full reload. I'm a little jealous that with links, we can easily do `<Link href="/search" as={`/search?id=${this.state.someValueFromForm}`} />` but there isn't a nice `<form>` equivalent. We're trying to keep a certain A11y standard, so using real forms and form validation is very important.

On the server-side, I have:

```javascript
const routes = [
  { to: '/search', matcher: route('/search/:hash') },
  // ...
];

// ...
app.prepare().then(() => {
  createServer((req, res) => {
    const parsedUrl = parse(req.url, true);
    const { pathname, query } = parsedUrl;
    for (let r of routes) {
      const params = r.matcher(pathname);
      if (params !== false) {
        return app.render(req, res, r.to, Object.assign({}, params, query));
      }
    }
    handle(req, res, parsedUrl);
  });
});
```

To me, it seems like this shouldn't be doing a full page reload when I submit my form, since I'm using `import Router from 'next/router';` and the `Router.push` method.

I should mention that the page with the form is `/search`, and the form should take you to `/search/magicHashFromForm`.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

Page shouldn't do a full page reload.

## Current Behavior

Page unmounts all components, and reloads the page.

## Context

I'm aiming for restful routes, so it's not uncomm

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   5.0.0      |
| node    |  8.9.4       |
| OS      |   OSX 10.12.6      |
| browser |  Chrome 64.0.3282.186       |

**Comment by timneutkens** [comment]
Issue template:
> ⚠️ IMPORTANT ⚠️
> If you have a question about Next.js please ask it on Spectrum https://spectrum.chat/next-js
> or join our Slack community at https://zeit.chat and ask it in the `#next` channel

This is not a bug, but a question about how to use Next.

Nontheless, you're using `Router.push` The first parameter is `href` the second parameter is `as` usage is the same as `<Link href="" as="" />`
