### ISSUE TITLE
I want to have requests between our middleware using koa & http-proxy-middleware to be proxied to another debugging proxy

### ISSUE THREAD

**Issue by zhangfaliang** [zeit/next.js#3925]
- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
Please provide a full description of an issue when you create them.

Based on the title, we're not going to add this to next since you can use the custom server api with https://www.npmjs.com/package/http-proxy

**Comment by didilinkin** [comment]
问题的描述都不写吗?  囧...
