### ISSUE TITLE
Unable to query a React component's functions on client after upgrading to v5

### ISSUE THREAD

**Issue by dargue3** [zeit/next.js#3933]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

Looking at this repo — https://github.com/dargue3/nextjs-v5-object-context — this line of code (in `pages/index.js` used to return the names of all the functions belonging to a React component class before upgrading to `next v5`.

`Object.getOwnPropertyNames(Object.getPrototypeOf(context))`

## Expected Behavior
It should print out `["constructor", "onClick", "otherFunction", "render", "componentDidMount", "componentWillUnmount"]`

## Current Behavior
It prints out `["constructor", "render", "componentWillReceiveProps", "componentWillUpdate"]`

## Steps to reproduce
Fire up the repo I pasted above and load `localhost:3000`. While rendering on the server, this works as expected. You can see the custom functions belonging to the class printing to the terminal. On the client however, any custom functions that you add to the React component will not show up. If you'd like to verify that this is related to `v5`, downgrade to `v4.2.2` and you should see the print statement showing up correct on both server and client.

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |     v5.0.0    |
| node    |   v8.6.0      |

I can't really speak to whether or not this is a bug (or how the version of Next is even related to this change in expected behavior). Could someone shed some light on what changes to `v5` could have caused this?

**Comment by ex3ndr** [comment]
I have hit same issues because of new react-hot-loader

**Comment by timneutkens** [comment]
Try upgrading to `next@canary`

**Comment by dargue3** [comment]
@timneutkens Yep that seemed to do the trick!

**Comment by timneutkens** [comment]
Newer version of react-hot-loader 😄 Will be released on master soon 👍
