### ISSUE TITLE
Production Sourcemaps on v5.0.0

### ISSUE THREAD

**Issue by bodhi** [zeit/next.js#3934]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

In production, enabling `devtool` and tweaking the `UglifyJSPlugin` configuration should build a full source map that can e.g. be used by the browser or external services to map stack traces back to original source files.

## Current Behavior

In Next.js v5.0.0, source maps are generated for `common.js`, `manifest.js` and `react.js` in the Next.js build directory,  but not for `app.js` (see *context* below for the gory details).

I haven't checked `canary` yet to see if the problem has been fixed, but from a casual inspection of the changes since `5.0.0`, I would expect to still have the same problem.

## Context

(I've copied the following from an internal discussion about this, apologies if any of it is unclear)

Next 5.0.0 by default will not correctly build source maps for
production. The client-code build process is:

1. List app pages and `main.js` as Webpack *entry points*. `main.js`
   points to `node_modules/next/dist/client/next.js` (and pages point
   to the indivdual file in `pages/` [1]

2. Use `CommonsChunkPlugin` to: a) extract common code from pages into
`common.js`, b) provide a single implementation of React, and c)
extract the webpack setup code. [2]

3. Use UglifyJS to minify code.

4. Use custom `CombineAssetsPlugin` [3] to hand-merge the common
chunks from step 2, with `main.js`, into `app.js`. [4]

Then when pages are generated in production, only `app.js` is linked
[5].

---

By:

* adjusting the UglifyJS plugin configuration [6],

* setting `devtool` in the Webpack configuration, and

* using `source-map-loader` for all JS code,

it's possible to get Next to build source maps for the files generated
in step 1 and step 2.

But when the chunks are merged in step 4, it causes the source map
offsets to become incorrect (because only the file content is merged,
the maps are not adjusted).

We can't build `app.js` directly with Webpack, because it needs to
contain the Next.js framework entry code (`main.js`) but *not* have it
linked in as a module (it needs to execute on load).

We can't easily modify Next to link in *both* `app.js` and `main.js`
when generating production HTML, without hacking further into the
build process, as we need to a) build the two files, b) include
`main.js` in the generated `.next/build-stats.json` file and c) modify
`Head` and `NextScript` to include `main.js` (see [5] again).

We can modify the CommonsChunkPlugin setup from step 2, and the
`CombineAssetsPlugin` from step 4:

1. Create a *single* `common.js` chunk that will have a correct source
   map.

2. Merge `common.js` and `main.js` using `CombineAssetsPlugin`,
ensuring that `common.js` is *first* in the file.

Then we can reuse the generated source map file for
`common.js` (`common.js.map`), by copying it somewhere that Next can
serve directly (eg. `static/`, and linking it from `app.js` by
appending a source map comment like this:

    //# sourceMappingURL=/static/common.js.map

Then we have:

1. Server generating HTML that links to `app.js`

2. `app.js` links to `static/common.js.map`

3. the *first* part of `app.js` is identical to `common.js` so the map
   file is correct for most of the code in `app.js`.

4. `static/common.js.map` is a source map for app *and* library code.

---

There is a hole where client-side errors in `getInitialProps` do not
use a source map when being displayed in Chrome.

---

[1]:
https://github.com/zeit/next.js/blob/9cfea69ab148b21300b7294fb14aea824b314873/server/build/webpack.js#L117-L132

[2]:
https://github.com/zeit/next.js/blob/9cfea69ab148b21300b7294fb14aea824b314873/server/build/webpack.js#L259-L312

[3]: https://github.com/zeit/next.js/blob/9cfea69ab148b21300b7294fb14aea824b314873/server/build/plugins/combine-assets-plugin.js

[4]: https://github.com/zeit/next.js/blob/9cfea69ab148b21300b7294fb14aea824b314873/server/build/webpack.js#L251-L254

[5]: https://github.com/zeit/next.js/blob/832425e67e1e4e04c601dfc7bcbcd03cff0c564d/server/document.js#L143-L153

[6]: https://github.com/zeit/next.js/blob/9cfea69ab148b21300b7294fb14aea824b314873/server/build/webpack.js#L215

**Comment by bodhi** [comment]
For reference, the relevant part of `next.config.js`:

```
  webpack(config, options) {
    ////////////////////////////////////////
    // Find UglifyJSPlugin instance, and turn sourceMap *on* to
    // generate production maps. UglifyJSPlugin is only used in
    // !options.dev.
    const uglify = config.plugins.find(p => {
      return p instanceof UglifyJSPlugin;
    });
    if (uglify) {
      console.log("Setting UglifyJSPlugin.options.sourceMap to true");
      uglify.options.sourceMap = true;
    }
    ////////////////////////////////////////

    ////////////////////////////////////////
    // If we are generating production client-side bundle, then
    //
    // 1. tweak the CombineAssetPlugin to only combine common.js and
    //    main.js (*ensuring* that `common.js` is first!).
    //
    // 2. tweak the CommonsChunkPlugin to only generate `common.js`,
    // and include all the chunks that would have gone into
    // `common.js`, `react.js` and `manifest.js`.
    let plugins = config.plugins;
    if (!options.isServer && !options.dev) {
      plugins = [];
      const chunkFns = [];
      config.plugins.forEach(p => {
        // Strip out existing CommonsChunkPlugins
        if (p instanceof CommonsChunkPlugin) {
          p.minChunks && chunkFns.push(p.minChunks);
          return;
        }

        // tweak CombineAssetsPlugin
        if (p instanceof CombineAssetsPlugin) {
          console.log("Adjusting config of CombineAssetsPlugin");
          p.input = ["common.js", "main.js"];
        }
        plugins.push(p);
      });

      // Add new CommonsChunkPlugin
      plugins.push(
        new CommonsChunkPlugin({
          name: "common",
          filename: "common.js",
          minChunks(module, count) {
            return chunkFns.some(fn => fn(module, count));
          }
        })
      );
    }
    ////////////////////////////////////////

    return {
      ...config,

      // In production, don't include code in source map, only include
      // lookup data.
      devtool: options.dev ? "inline-source-map" : "nosources-source-map",

      // Include source maps from library code that has maps (eg
      // ecjs).
      module: {
        rules: [
          ...config.module.rules,
          {
            test: /\.[jt]sx?$/,
            loader: "source-map-loader"
          }
        ]
      },

      // Use our custom plugin setup.
      plugins
    };
  }
```

and the simple post-build script:

```
# Build the Next app
yarn next build

# Add newline to end of built `app.js`
echo >> .next/app.js

# Add sourcemap comment to `app.js`
echo "//# sourceMappingURL=/static/common.js.map" >> .next/app.js

# Make sourcemap available to download
mkdir -p static
cp .next/common.js.map static/
```

**Comment by bodhi** [comment]
(hmm, my footnotes got turned into barely-visible inline links...)

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/pull/3793

**Comment by bodhi** [comment]
👏 👏 👏  Sorry, I didn't manage to find that PR when searching!
