### ISSUE TITLE
a.subscribe is not a function

### ISSUE THREAD

**Issue by ryanbas21** [zeit/next.js#3935]
The route `/posts/` renders on the server but then the store on the client subscribe is undefined. In the chrome dev tools, it shows an error on the import for `isPlainObject` from lodash. I've done this before and I have no idea whats wrong. I'm sure its something I am doing, but I can't put my finger on it.

Basically I create in my `hoc` folder in `src/` a `pageWrapper` that just partially applies the store and is waiting for the component. I then have my `Posts` component in `features/` `connect`ed. I can't seem to figure out whats wrong with the store and why its broken on the client.

Initially I see the basic text appear before the error pops up which leads me to believe the store is working on the server but not the client.

Code here, https://github.com/ryanbas21/blog .

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
The error comes from rxjs, don't see how this is related to Next.js, so I'm going to close the issue.

Just as a side note:
https://github.com/ryanbas21/blog/blob/master/package.json#L16
You don't have to run `tsc` when using next-typescript.
