### ISSUE TITLE
How to set click menu reload the page with next/router

### ISSUE THREAD

**Issue by jyjin** [zeit/next.js#3937]
Code:
```
import Router from 'next/router'
import { Scrollbars } from 'react-custom-scrollbars'

export default class ChildrenMenus extends React.Component {
    render() {
        return (
            <div style={{flex:1}}>
                <Scrollbars>
                <List>
                    { this.props.menus.map((item,_index)=>{
                        let _st={}
                        if(_index==this.props.selected){
                            _st.style={
                                backgroundColor: "rgba(0, 0, 0, 0.2)"
                            }
                        }
                        _st.onTouchTap=()=>{
                            Router.push(item.href)
                        }
                        return <ListItem key={_index} primaryText={item.text[this.props.local]} {..._st}/>
                    }) }
                </List>
                </Scrollbars>
            </div>
        )
    }
}
```
when I visit /system/home, it get the home page correctly. But I have many content in the home page, including table with page and charts and so on. I want to click home page menu to reload this page, and I tried add timestamp query like ?t=timestamp to the url , but not worked. So what shall I do?

**Comment by timneutkens** [comment]
Based on your description I can't follow what you want to do. If you want to force page reloads just use `window.location.href = url`.

Please follow the issue template 🙏

**Comment by jyjin** [comment]
Location.href will reload all page resource. I has two leval menu, and each menu has one page. But some pages I have the 'inner page', this 'inner page' just by state coding, they not really a page. No matter it is outer page or inner page, they are from the same route, just by different state. When I was in inner page, and want to back outer page, I just want to click the menu for that. But they are same route, I still in inner page.
