### ISSUE TITLE
duplicate react in bundle ?

### ISSUE THREAD

**Issue by revolunet** [zeit/next.js#394]
Hi,

Looks like a basic next.js project gets react duplicated in the `next-dev.bundle.js`.
when launching my fresh project, and going to http://127.0.0.1:3000/_next/next-dev.bundle.js i can see two `SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED` in the source, and i guess this is not good ?

it doesnt hurt for simple cases, but as soon as you use `ReactCSSTransitionGroup` or something using React `refs` then you get that error : 

> next-dev.bundle.js:945 Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).(…)

PS: using next.js@1.2.3

**Comment by revolunet** [comment]
trying to debug that from the source :)

```sh
cat ./dist/client/next-dev.bundle.js  | grep _FIRED
var ReactPropTypesSecret = 'SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED';
var ReactPropTypesSecret = 'SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED';
```

**Comment by revolunet** [comment]
Not really sure this is related but i still have a weird bug with `ReactCSSTransitionGroup`

> next-dev.bundle.js:945 Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).(…)

Here's a repro : https://github.com/revolunet/next-issue-394

**Comment by arunoda** [comment]
Okay. It seems like you are using a React addon.
I think we had an issue with that. See: https://github.com/zeit/next.js/issues/204

**Comment by revolunet** [comment]
how did i missed that...thanks.

**Comment by arunoda** [comment]
Hey @revolunet could you try this PR: https://github.com/zeit/next.js/pull/401

**Comment by arunoda** [comment]
I hope #401 fixes this. If not reopen and tell me what went wrong.

**Comment by revolunet** [comment]
#401 fixed it, great job thanks 👍
