### ISSUE TITLE
Can't insert comment in head _document (styled_componet, jss)

### ISSUE THREAD

**Issue by Popugune** [zeit/next.js#3943]
Hello. I try to insert a html comment in the _document, but when rendering a page, the comment falls into the text in body. Is there a solution to the problem?

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   5.0.0      |
| node    |  9.5.0       |
| OS      |   win 10      |
| browser |   chrome 64      |
| etc     |         |

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/issues/3904

**Comment by Popugune** [comment]
this method not working. @timneutkens
