### ISSUE TITLE
Link to the same page on server render

### ISSUE THREAD

**Issue by sobocinski** [zeit/next.js#3952]
- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

Hello,
I have this problem, if I rendered page _XX_ through the server (Express), which uses the alias (as) _YY_, click on `<Link>` doesn't work.

### Current Behavior
We display the XX page, there is a link to the same page, but with extra param - defined in this way `<Link href="/XX?id=1" as="/YY/ 1">` then clicking on it do nothing, no errors in the console.
I noticed that the link works if I change `href="/XX?id=1"` to `href="_random_string_"`.

Also when I change the subpage to _ZZ_ dynamically and return dynamically to _XX_, Link <Link href="/XX?id=1" as="/YY/ 1"> works correctly (**expected**).

### Expected Behavior
Clicking on `<Link>` changes the parameter in the url without changing the page.

### Context
Let's say I have a list of recipes in strore and I display them on the page _/recipes_, when I click on the Link, I do not want to change the page, just add the parameter /recipies/1 and load the selected recipe details.

## Environment

| Tech    | Version |
|---------|---------|
| next    |    5.0     |
| node    |    9.4.0     |

**Comment by timneutkens** [comment]
Search for `shallow` in the readme 👍 https://github.com/zeit/next.js#shallow-routing
