### ISSUE TITLE
Cannot import bootstrap CSS

### ISSUE THREAD

**Issue by fabioespinosa** [zeit/next.js#3953]
I just upgraded to Next.js 5.0 especially to make use of the new CSS import.

I'm trying to use `import 'bootstrap/dist/css/bootstrap.min.css';` from layout page, and using the next.config.js:

`const withCss = require('@zeit/next-css');
module.exports = withCss({});
`

However it throws an error that says: Module parse failed: "Unexpected character ''
You may need an appropriate loader to handle this file type." (Maybe its because bootstrap.min.css requires some .ttf, .woff, .eot files?)

In previous next.js releases I included bootstrap css by manually including the stylesheet like this in a layout component: 
`<link rel="stylesheet" href="/static/css/bootstrap.min.css" />`

Right now, with next.js 5 it loads the stylesheet after the dom shows on screen and gives certainly not the desired feeling. 

I don't know now how to include the bootstrap css and external css correctly. 

Thanks Zeit team 👍, huge fan here.

**Comment by timneutkens** [comment]
Upgrade next to `next@canary` and upgrade `@zeit/next-css`. 

> Right now, with next.js 5 it loads the stylesheet after the dom shows on screen and gives certainly not the desired feeling.

This is definitely related to being on a really old version of next-css.

**Comment by fabioespinosa** [comment]
Thanks @timneutkens ! upgrading to `next@canary` and `@zeit/next-css` fixed the issue of loading the stylesheet after the dom 👍 

Just curious, if you were to import bootstrap's css only (and maybe other external CSS), which way would you do it?

Are there any advantages of using:

`import 'bootstrap/dist/css/bootstrap.min.css';`

or is `<link rel="stylesheet" href="/static/css/bootstrap.min.css" />` fine?

**Comment by timneutkens** [comment]
The link tag would save compilation time, probably a lot because bootstrap is pretty big if you import all of it.

**Comment by fabioespinosa** [comment]
Thanks for the quick reply and all the energy you’re putting into Zeit projects @timneutkens. Will use the link tag then 👍
