### ISSUE TITLE
SyntaxError: Invalid or unexpected token @

### ISSUE THREAD

**Issue by kushalsiddesh** [zeit/next.js#3958]
>  solution expected to work
>
```
//next.config.js
const withCSS = require("@zeit/next-css");
module.exports = withCSS();

```

Facing below issue

>/Users/crushy/dev/relive/node_modules/antd/lib/style/index.css:6
>
> @font-face {
> ^
> 
>  SyntaxError: Invalid or unexpected token
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:607:28)
>     at Object.Module._extensions..js (module.js:654:10)
>     at Module.load (module.js:556:32)
>     at tryModuleLoad (module.js:499:12)
>     at Function.Module._load (module.js:491:3)
>     at Module.require (module.js:587:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/Users/crushy/dev/relive/node_modules/antd/lib/button/style/css.js:3:1)
>     at Module._compile (module.js:643:30)
>     at Object.Module._extensions..js (module.js:654:10)
>     at Module.load (module.js:556:32)
>     at tryModuleLoad (module.js:499:12)
>     at Function.Module._load (module.js:491:3)
>     at Module.require (module.js:587:17)
>     at require (internal/module.js:11:18)
>     at Object.antd/lib/button/style/css (/Users/crushy/dev/relive/.next/dist/bundles/pages/external "antd/lib/button/style/css":1:1)
>     at __webpack_require__ (/Users/crushy/dev/relive/.next/dist/bundles/pages/webpack/bootstrap 399d3c85f3fa45b2531f:21:1)
>     at Object../components/Lane.js (/Users/crushy/dev/relive/.next/dist/bundles/pages/index.js:380:84)
>     at __webpack_require__ (/Users/crushy/dev/relive/.next/dist/bundles/pages/webpack/bootstrap 399d3c85f3fa45b2531f:21:1)
>     at Object../components/Vertical.js (/Users/crushy/dev/relive/.next/dist/bundles/pages/index.js:804:64)

**Comment by timneutkens** [comment]
Should be filed in github.com/zeit/next-plugins
