### ISSUE TITLE
Is the entire core-js from the babel-polyfill being included on the client-side? 

### ISSUE THREAD

**Issue by matthewmueller** [zeit/next.js#396]
Taking a look at the bundle size, it seems like all of core-js is being included from the babel-polyfill. I wonder if it could just require a few things like Set + Promise. Doesn't seem like the client library implements features like Symbol, for-of, etc. Also seems like babel should figure this stuff out for us.

<img width="821" alt="screenshot 2016-12-15 13 45 10" src="https://cloud.githubusercontent.com/assets/170299/21239573/025813a6-c2cd-11e6-802e-daf275a71535.png">

**Comment by arunoda** [comment]
Sure. I'll a have a look at what's going on here.

**Comment by arunoda** [comment]
I wonder how you've got the webpack visulalizer working. It totally doable with a fork of Next.js where I can change the webpack config.

If you did it with some other way, I really like to know about that.

**Comment by matthewmueller** [comment]
Oh sure thing, it's a big hack, but I just am writing out the stats of the webpack build in the `gulpfile`:

```js
gulp.task('build-client', ['compile-lib', 'compile-client'], () => {
  return gulp
  .src('dist/client/next.js')
  .pipe(webpack({
    quiet: true,
    output: { filename: 'next.bundle.js', libraryTarget: 'var', library: 'require' },
    plugins: [
      new webpack.webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify('production')
        }
      }),
      new webpack.webpack.optimize.UglifyJsPlugin()
    ],
    module: {
      loaders: [
        {
          test: /eval-script\.js$/,
          exclude: /node_modules/,
          loader: 'babel',
          query: {
            plugins: [
              'babel-plugin-transform-remove-strict-mode'
            ]
          }
        }
      ]
    }
  }, null, function (err, stats) {
    fs.writeFileSync('next.json', JSON.stringify(stats.toJson(), true, 2))
  }))
  .pipe(gulp.dest('dist/client'))
  .pipe(notify('Built release client'))
})
```

**Comment by arunoda** [comment]
Actually this the next-bundle, but not the app's bundle.
I'll see what we can do about this.

**Comment by arunoda** [comment]
I just checked the size of the core-js bundle get increased with the use of ES6 features. I can't find a way to reduce it. I could stop using ES6 features, but that's not something we wanna do.

We are going to do some changes to how we actually load different bundles. And one such thing is we may need to add support for [babel-preset-env](https://github.com/babel/babel-preset-env)

So, I am gonna close this issue in favor of future optimizations on this topic.

**Comment by arunoda** [comment]
FYI:

For the production next-bundle core-js takes around 7.7% in the current master.
<img width="760" alt="screen shot 2016-12-16 at 2 52 27 pm" src="https://cloud.githubusercontent.com/assets/50838/21257687/74b22400-c39f-11e6-9d7b-4ccf89755dbc.png">

Here's [stats.json](https://gist.github.com/arunoda/45c92d7caa20126d15b231d9eaf9f6f0) file.
