### ISSUE TITLE
assetPrefix ignored by stylesheet in export

### ISSUE THREAD

**Issue by quickhand** [zeit/next.js#3967]
When doing a static export with assetPrefix defined in next.config.js, stylesheet does not link properly. 

Script files are included as `<assetPrefix>/_next/<...>/index.js`, while the css file is included as `/_next/static/style.css` with no prefix.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Current Behavior
Stylesheet is linked as `/_next/static/style.css` with no prefix when assetPrefix is defined

## Expected Behavior
Stylesheet should be linked as `<assetPrefix>/_next/static/style.css` when assetPrefix is defined

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | canary (07-03-2018)        |
| node    |  v8.4.0       |
| OS      |  macOS Sierra       |
| browser | Chrome Version 63.0.3239.132   |

**Comment by revolunet** [comment]
How do you declare your css ? 
mine is declared in `_document.js` with a hardcoded path so of course the assetPrefix needs to be set manually.

**Comment by timneutkens** [comment]
You can use the following in `_document.js`:

```
this.props.__NEXT_DATA__.assetPrefix
```
