### ISSUE TITLE
Components lose refs when exporting

### ISSUE THREAD

**Issue by bitkomponist** [zeit/next.js#3970]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Current Behavior

Components lose all references when staticly exporting the app

## Context
In my project i have multiple components which use refs to determine dom-specific stuff (e.g. height of elements), they work as expected when building for production and running next. I intend to use the static export of the app. When i run the exported build on my server (apache), all refs that should be populated, are set to null. i also tried to wrap these components with `react-no-ssr` to no avail.

__One of my Components which produce this behaviour__

```javascript
import React,{Component} from 'react'
import ReactDOM from 'react-dom'

function isElementInViewport (el) {

	const rect = el.getBoundingClientRect();

	return (
		rect.top >= 0 &&
		rect.left >= 0 &&
		rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
		rect.right <= (window.innerWidth || document.documentElement.clientWidth)
	);
}

export default class Runningback extends Component {
	state = {visible:false}

	componentDidMount(){
		window.addEventListener('scroll',this.handleScroll,false);
		this.handleScroll();
	}
	componentWillUnmount(){
		window.removeEventListener('scroll',this.handleScroll);
	}

	handleScroll = ()=>{
		const el = ReactDOM.findDOMNode(this.refs[0]);
		if(!el) return;
		const visible = isElementInViewport(el);
		const {both=false} = this.props;
		if(this.state.visible !== visible && (visible || both)){
			// console.log(`el switched ${visible?'visible':'invisible'}`);
			this.setState({visible});
		}
	}
	render(){
		const {children} = this.props;
		const {visible} = this.state;
		if(typeof(children) !== 'function') throw new Error('expects a function as children-prop');
			
		return React.Children.map(children(visible),(child,index)=>{
			//debugger;
			return <child.type {...child.props} ref={index} />;
		});
	}
}
```
## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    v5.0.1-canary.11     |
| node    |    v9.1.0     |
| OS      |    macOS High Sierra      |
| browser |    Google Chrome     |
| etc     |         |

**Comment by bitkomponist** [comment]
Ok so if anyone encounters this behaviour as well, _refs are also lost when running in production mode_. I worked around the issue, by getting a reference to the Component itself (e.g.`ReactDOM.findDOMNode(this)`) which works fine. from there i can get the desired child node.

**Comment by timneutkens** [comment]
Looks like you're using an old ref api. There's a new one: https://reactjs.org/docs/refs-and-the-dom.html
