### ISSUE TITLE
next build does not do any typechecking in typescript examples

### ISSUE THREAD

**Issue by terencechow** [zeit/next.js#3974]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
Bug
typechecking should occur in the typescript examples

## Current Behavior
typechecking does not occur

## Steps to Reproduce (for bugs)
1. Clone the with-typescript or custom-server-typescript repos
2. in pages/index.jsx write the below function

```
function typeCheckingNotCalled(): boolean {
      return 'abc';
}

// call function to prevent typescript error about function unused
typeCheckingNotCalled() 
```

3. Run `npm run build`

In step 3 you should expect an error that says `'abc' is not assignable to boolean`.
However it builds fine.

## Context
I'm trying to use next js with typescript

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |    5     |
| node    |     8.10    |
| OS      |     mac osx 10.13   |
| browser |    chrome 64     |
| etc     |         |

**Comment by terencechow** [comment]
just had a look at next-typescript and I see that it has set `transpileOnly to true` for the ts-loader.

For anyone coming here in the future you can get typechecking in development with the plugin `fork-ts-checker-webpack-plugin`.

I'm gonna consider that good enough since we don't really need `next build` to typecheck if the development is already typechecking... will leave this open so that a moderator can review and see if they want to add input. Otherwise i'm good to close.

```
//next.config.js
const withTypescript = require("@zeit/next-typescript");
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

const env = process.env.NODE_ENV || 'development'

module.exports = withTypescript({
  webpack(config, options) {

    // only add plugin in development to client webpack config .
    if (env === 'development' && !options.isServer){
      config.plugins.push(new ForkTsCheckerWebpackPlugin())
    }

    return config;
  },
});
```

**Comment by timneutkens** [comment]
Yeah using `transpileOnly` was a conscious choice, it's recommended in the ts-loader docs, and you can do type checking with vscode, or a babel plugin as you mentioned 👍
