### ISSUE TITLE
Code is not transpiled outside of src folder (not just for node_modules).

### ISSUE THREAD

**Issue by glemiere** [zeit/next.js#3979]
- [X] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
I have (and want to keep) the following file structure : 

- config
  - index.js
- node_modules
  - ...
- server
  - index.js
- src
  - .next
  - components
  - pages
- static
  - serviceWorker.js

The **import statement** should work in **server/index.js**, as well as the **export statement** in **config/index.js**.

## Current Behavior
The **import statement** fails in **server/index.js**, as well as the **export statement** in **config/index.js**.
It would really feel weird to use ES5 in a part of the project and ES6 in another part.

## Steps to Reproduce (for bugs)
https://github.com/glemiere/nextjs-starter/tree/Transpiling-Issue

## Context
Just building a complete starter for NextJS apps.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 5        |
| node    | 9.6.0        |
| OS      | OSX High Sierra        |
| browser | X        |
| etc     | X        |

**Comment by langpavel** [comment]
I believe that this is expected and desired behavior

**Comment by timneutkens** [comment]
The server initiates webpack, so you can't compile it with webpack. next.config.js is also loaded before the server starts. With regards to doing import outside of the main directory, there is an open issue for that.

**Comment by glemiere** [comment]
@timneutkens any link or other helpful resources would be greatly appreciated :D

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+transpile

https://github.com/zeit/next.js/issues/3898
