### ISSUE TITLE
How can I embed script into my next.js page?

### ISSUE THREAD

**Issue by sergiofilhowz** [zeit/next.js#3980]
I want to embed Sendpulse into my next.js page, how can I do this?

Their code: 
```
<script charset="UTF-8" src="//cdn.sendpulse.com/9dae6d62c816560a842268bde2cd317d/js/push/998014b3613c5ffdd01ac8c8a6390391_1.js" async></script>
```

- [X] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

**Comment by timneutkens** [comment]
Use next/head.

**Comment by sergiofilhowz** [comment]
Hi Tim, thanks for your quick answer!

Can you provide an example or a link to the docs please?

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js#populating-head
