### ISSUE TITLE
Unhandled promise rejection (rejection id: 8): Error: Cannot find module '/home/pnhduc/Project/javascript/startup-5p/v2/site-web-client/node_modules/next/dist/pages/_error.js'

### ISSUE THREAD

**Issue by hong-duc** [zeit/next.js#3981]
Sometime that error show in log, I don't know when or how that error show up, it just show up random
It seem like I do something wrong but I don't know what

- [ x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

Not show error on random time
## Current Behavior

Show error on random time
## Steps to Reproduce (for bugs)

Just run and watch the log
## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     5    |
| node    |     9.1.0    |
| OS      |     manjaro linux    |
| browser |         |
| etc     |         |

**Comment by jthegedus** [comment]
Can you reproduce this with `next@canary`?

Do you have a minimal example repo on which this occurs?

**Comment by timneutkens** [comment]
Please upgrade to canary, Will be solved there.
