### ISSUE TITLE
[Issue ] Using Material UI (next) + Styled compoenet with NextJS  

### ISSUE THREAD

**Issue by nmpatzios** [zeit/next.js#3983]
I'm facing an issue when trying to reload a page after I have changed a material ui next component using a styled component. Based on the solution above (#8032) after reloading/refreshing the browser the material ui next component goes back to it's original css.

p.s.
**This issue only occurs in dev not in production**

**The browser console error message after refresh/reload the page**
``` 
Warning: Prop `className` did not match. Server: "MuiButtonBase-root-47 MuiButton-root-86 sc-VigVT iwjLMD" Client: "MuiButtonBase-root-47 MuiButton-root-86 sc-bwzfXH cHkGGL"

```

more details:

step 1:
clone the repo from the examples (examples/nextjs)

step:2
import styled components as shown 
https://material-ui-next.com/guides/interoperability/#styled-components
e.x.:
 ```import Button from 'material-ui/Button';
const StyledButton = styled(Button)`
    && {
    background: red;
    border: 1px solid red;
    font-size: 2rem;
    font-weight: bold;
    }
`; 
```
<StyledButton >Title</StyledButton>

When I build the project everything works fine the css applied correctly.
![style-component](https://user-images.githubusercontent.com/11279939/37212121-0f90889c-23a6-11e8-9d38-bccf24698dd5.png)

But when i try to reload/refresh or clean cache from browser the button goes back to it's original state  (the style css) 
![lost-css](https://user-images.githubusercontent.com/11279939/37212253-70f00cfc-23a6-11e8-969b-26fd9647f4a2.png)

Any suggestions?

**Comment by timneutkens** [comment]
Try upgrading to next@canary.

**Comment by nmpatzios** [comment]
Thnaks guys for all your help!!!

I found a solution by added .babelrc to project.
installing ``` 
"babel-plugin-styled-components": "^1.5.1",

and adding the following code to babel file 
```
```
{
    "presets": [
        "next/babel"
      ],
    "plugins": [
        ["styled-components", { "ssr": true, "displayName": true, "preprocess": false } ]
    ]
}
```

**Comment by RobbinHabermehl** [comment]
Unfortunately, apparently this isn't working in all cases; the issue persists when using `material-ui` v1.0.0-beta.43 and `next` v5.1.0 and so far I haven't found a solution. Could you please re-open this issue @timneutkens?

**Comment by kutsyk** [comment]
Hello guys the same errors with `"material-ui": "^1.0.0-beta.44"` and `"next": "^6.0.0"` tried a lot of configuration with `.babelrc`. Unfortunatelly nothing helps. Could you, please, reopen this task to fix the problem?

**Comment by timneutkens** [comment]
Can you please create a new issue that follows the issue template 👍

**Comment by roland-reed** [comment]
Any updates? I came across the same issue with `next@6.0.3` and `@material-ui/core@1.1.0`.  Add `.babelrc` didn't solve the issue.

**Comment by williamluke4** [comment]
Any updates on this or does anyone have an example that I can look at? All the ones I have found are not working

**Comment by Neo478** [comment]
Same here, we can't continue with NextJs because of this issue.

**Comment by williamluke4** [comment]
@Neo478 Try this out [nextjs-materialui-styledcomponents](https://github.com/williamluke4/nextjs-materialui-styledcomponents)

**Comment by Neo478** [comment]
@williamluke4 Thanks! It solved half the issue. My elements still inherits from MuiCircularProgress after reloading the page, but they aren't spinning all around anymore!

**Comment by williamluke4** [comment]
@Neo478 Try this

```javascript
const StyledButton = styled.div`
  && {
    width:  150px;
    padding: 10px;
    margin: 10px auto;
    text-align: center;
    color: white;
    background-color: blue;
  }
`;
```

**Comment by Neo478** [comment]
I tried to put 
`
&& {

}
`

Around the elements's styles that are failing to render correctly, but it doesn't change anything.

**Comment by scottdevito** [comment]
Thanks @williamluke4 . I implemented what you have in that repo almost exactly (not using TS) but I'm getting a styling flicker on refresh (unstyled buttons are visible and then re-render as Material UI styling) and can't seem to pin down why.

**Comment by msreekm** [comment]
same here, flashing styles

**Comment by simonsmadsen** [comment]
Any fix to avoid the flashing styles?

**Comment by sunlee-newyork** [comment]
I followed @williamluke4 's thread and landed on https://github.com/mui-org/material-ui/tree/master/examples/nextjs - I followed this example to the T and it worked

**Comment by caprica-Six** [comment]
Thanks @sunlee-newyork  - worked like a charm after restarting the server. 
I did forget to add the `import flash ... ` & the .babel import...
