### ISSUE TITLE
Error: Page does not exist: /static/logo.png

### ISSUE THREAD

**Issue by glemiere** [zeit/next.js#3987]
- [X] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
Automatically render the static folder to get access to some assets for the manifest.json file.

## Current Behavior
The routing seems confused thinking that static is a page instead of an asset folder. Doesn't work in both cases : static folder at the root, and static folder in src.

## Steps to Reproduce (for bugs)
https://github.com/glemiere/nextjs-starter/tree/Static-Folder-Routing-Bug

## Context
Impossible to set icon in the manifest.json

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 5        |
| node    | 9        |
| OS      | OSX        |
| browser | X        |
| etc     | X        |

**Comment by timneutkens** [comment]
https://github.com/glemiere/nextjs-starter/tree/Static-Folder-Routing-Bug/src/static

They're supposed to be here.

**Comment by glemiere** [comment]
Wow weird! I just tried again, I was getting a 404 yesterday and now it works without changing anything. I have no idea what's going on, good news though. Thank you!
