### ISSUE TITLE
Error: _document.js is not exporting a React element when wrapping Document inside withRedux() HOC

### ISSUE THREAD

**Issue by Vadorequest** [zeit/next.js#3990]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

I'm trying to see if I can wrap the Document inside Redux, using withRedux HOC.

But when I do, I get `Error: _document.js is not exporting a React element`

```jsx
import React from 'react';
import classnames from 'classnames';
import _Document, { Head, Main, NextScript } from 'next/document'
import withRedux from 'next-redux-wrapper';
import configureStore from '../store/configureStore';

class Document extends _Document {

  render() {
    console.log('----------- document props', this.props);

    return (
      <html>
        <body className={classnames('loan-advisor')}>
          <Main/>
          <NextScript/>
        </body>
      </html>
    )
  }
}

// export default Document;
const EnhancedDocument = withRedux(
  configureStore
)(Document);
console.log(EnhancedDocument)

export default EnhancedDocument; // I tried rendering a <EnhancedDocument /> too but doesn't work either
```

I get the following server output:
```
{ [Function: WrappedCmp] getInitialProps: [Function] }
next Error: _document.js is not exporting a React element
next     at _callee3$ (/Users/vadorequest/dev/student-loan-simulator-serverless/aws/loan-advisor/node_modules/next/dist/server/render.js:209:19)
next     at tryCatch (/Users/vadorequest/dev/student-loan-simulator-serverless/aws/loan-advisor/node_modules/regenerator-runtime/runtime.js:62:40)

```

Is what I try to do possible? And is it a good idea?

My goal is to do the following:

- Load redux automatically for all pages (which fetch some data in `getInitialProps`
- Load react-jss automatically for all pages (depends on redux)
- Make react-jss work with SSR (I currently have a blank effect because server doesn't inject styles)

I've achieved this behaviour already, but with boilerplate in every page that I don't like much, hence the fact I'm trying to simplify all this stuff using the _document.js

**Comment by timneutkens** [comment]
_document is only server rendered. So you can't wrap it in redux. Our recommendation is to write a HOC and wrap pages in it. In theory you can now also do this with a webpack loader automatically.

**Comment by Vadorequest** [comment]
HOC works very well, thanks @timneutkens
