### ISSUE TITLE
How to access the style assets of next@css / next@sass after I change my folder structure?

### ISSUE THREAD

**Issue by wellyshen** [zeit/next.js#3991]
Thank you for this great framework. I'm using next@sass and I wanna know how to access the styles after I change my folder structure.

Here's my folder strcuture:
root
|---- src
           |---- .next
           |---- pages
           |---- next.config.js

When I run `yarn dev` my `css` path is missed:
```javascript
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  render() {
    return (
      <html>
        <Head>
          <link rel="stylesheet" href="/_next/static/style.css" /> // <== How to adjust the path?
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

**Comment by jbsmith731** [comment]
I'm having the same issue. I have my app inside of `./app` directory. I've made the adjustments to the express server & the build command however my css file still 404s.

**Comment by jbsmith731** [comment]
@wellyshen see https://github.com/zeit/next.js/issues/4004

I updated to canary as suggested and this issue was resolved.

**Comment by wellyshen** [comment]
@jbsmith731 Thanks I'll try it.
