### ISSUE TITLE
How about if I use Router

### ISSUE THREAD

**Issue by minooo** [zeit/next.js#3992]
https://github.com/zeit/next.js/blob/b02e5849e9472c80839704b0003448f30482a818/examples/using-with-router/components/ActiveLink.js#L1

```
import Router from "next/router"
```
if I do this like above，I can also solve the same problem，then `withRouter` is unnecessary???

**Comment by arunoda** [comment]
@minooo `withRouter` and `Router` provides the same functionality with different kinds of API.

* Router is an object containing a set of function.
* `withRouter` is a function which creates a higher order component with the router API

If you can live with `Router` you don't need to use `withRouter`.

**Comment by minooo** [comment]
Thank you, I just think `Router` can replace `withRouter` completely.
