### ISSUE TITLE
CSS not being compiled in non-pages directory

### ISSUE THREAD

**Issue by fandy** [zeit/next.js#3993]
I currently have my project setup with Emotion but have tried Sass modules as well. It compiles styles in the [`pages`](https://github.com/fandy/community/blob/master/pages/index.tsx#L19) dir, but not [elsewhere](https://github.com/fandy/community/blob/master/components/Header/Header.tsx#L7). Is this a Next.js issue, or is there something wrong with the way I set it up? When I tried with Sass modules I encountered the same problem, where the styles would exist if the component was in `pages` but not in another root dir.

### Styles exist in [`pages`](https://github.com/fandy/community/blob/master/pages/index.tsx#L19)
![image](https://user-images.githubusercontent.com/19108762/37267795-dcc15000-2598-11e8-99b2-1c01d4c81f18.png)

### Styles do not exist in [`components`](https://github.com/fandy/community/blob/master/components/Header/Header.tsx#L7)
![image](https://user-images.githubusercontent.com/19108762/37267803-e48f1c86-2598-11e8-853e-05817297ab76.png)

The weird thing is, the className is there but just not the styles for it.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
Has styles in the Header className

## Current Behavior
Header className is being referenced but contains no styles. However, the styles in pages does.

**Comment by pklada** [comment]
Your screenshots appear to be the same.

But, I'm getting a similar behavior when using css modules. 

config: 
![image](https://user-images.githubusercontent.com/1474231/37475246-763c0534-282f-11e8-97d2-f07a98635510.png)

test style (in `styles.scss`)
![image](https://user-images.githubusercontent.com/1474231/37475276-86f19e70-282f-11e8-9c38-8ad4b715f428.png)

markup
![image](https://user-images.githubusercontent.com/1474231/37475301-9ce0d9d0-282f-11e8-8996-1a32e5aabef1.png)

result
![image](https://user-images.githubusercontent.com/1474231/37475323-aae2ff9a-282f-11e8-80b6-4d45de9930fe.png)

You can see the class is generated, but no styles are actually being applied (color, background-color)

Is this a known issue?

**Comment by timneutkens** [comment]
@pklada try upgrading to next@canary and installing the latest next-css. Should be fixed.

**Comment by pklada** [comment]
@timneutkens will do. thanks for the quick reply!

**Comment by fandy** [comment]
Upgrading to `next@canary` fixed it for me. 🙌
