### ISSUE TITLE
Very Slow build Next 5

### ISSUE THREAD

**Issue by mbj36** [zeit/next.js#3995]
Thanks you making NextJS, We are using it at our company

Problem is it takes around 7-8 seconds to route to different page which is very slow

Example - I am in `/` route, if i go to `/admin`  it takes  `DONE  Compiled successfully in 6946ms`

**Comment by timneutkens** [comment]
Please provide a reproducible case, with code, it’s impossible to act on an issue saying: it doesn’t work for me

Also try upgrading to next@canary.
