### ISSUE TITLE
Make the Programmatic API aware of prefetching

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#400]
Since #375 is merged, we need to make sure #310 works nicely with that.

**Comment by rauchg** [comment]
Basically to the backend it should be no different?

**Comment by arunoda** [comment]
Yes. I don't think we need to change at all.
Since now we are serving JSON pages from `/next/pages` basepath, we might could do few extra steps to make other HTTP requests pass through the service worker.

**Comment by arunoda** [comment]
This is now implemented. #422
