### ISSUE TITLE
Changing next's dir option won't load compiled css file

### ISSUE THREAD

**Issue by DWboutin** [zeit/next.js#4004]
I changed the Next.js config to handle the structure like I wanted but, the generated css file won't load the same way.
```javascript
const app = next({ dir: './src/', dev })
```
I load my css file like this
```html
<link rel="stylesheet" href="/_next/static/style.css" />
```
When I put everything outside the src folder, like suggered, it works.

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

My CSS file must load the same way if I specify a dir path or not.
```javascript
const app = next({ dir: './src/', dev })
```

## Current Behavior

When I specify a dir path, Next won't load my CSS file compiled with @zeit/next-sass
## Steps to Reproduce (for bugs)

1. Change de dir option of Next.js server side
2. Use @zeit/next-sass and import a css file into a page
3. Add the file to an Head
4. The file won't load

## Context

I'm trying to have a cleaner structure. I'm not a fan of all the things at the root level.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    5     |
| node    |    8.10     |
| OS      |     OSX El Capitain V10.11.6    |
| browser |    Chrome 64.0.3282.186     |

**Comment by haha54carol** [comment]
Try to put your pages folder under the root not in src
--project
--pages
--src
   --index.js

**Comment by DWboutin** [comment]
The pages works well, it's just the CSS file who won't load.

**Comment by timneutkens** [comment]
Try upgrading to next@canary.

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/pull/3722

**Comment by haha54carol** [comment]
This is my folder structure
├── ...
├── pages
├── src                         
│   ├── static
│   ├──── sass 
│   └──── images 
 | ── next.config.js           
└── ...

@DWboutin ,
 Pages still can work but css not.
 I had same issue before.
 Fixed that by moving pages folder to root from src.
And you also need a next.config file
Hope it can help you!

``` javascript
// next.config.js
const withSass = require('@zeit/next-sass')
module.exports = withSass({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: "[local]___[hash:base64:5]",
  }
})
```

**Comment by DWboutin** [comment]
@timneutkens Works perfectly! You rock! Thanks
