### ISSUE TITLE
next@latest is pointing at a canary release

### ISSUE THREAD

**Issue by Rowno** [zeit/next.js#4021]
## Expected Behavior
`next@latest` points at the latest stable release.
i.e: `npm install next` installs `next@5.0.0`

## Current Behavior
`next@latest` points at the latest canary release.
i.e: `npm install next` installs `next@5.0.1-canary.16`

## Context
Maybe I'm misunderstanding what the canary releases are, but shouldn't `next@latest` point at the latest stable build not the latest experimental build?

The [Next canary blog post](https://zeit.co/blog/next-canary) says that `next@canary` should be used to install the latest canary release. It seems kinda pointless if `next@latest` points at canary too.

**Comment by timneutkens** [comment]
@Rowno Thanks! I've updated the dist tag 🙏
