### ISSUE TITLE
Build doesn't respect NODE_ENV

### ISSUE THREAD

**Issue by Vadorequest** [zeit/next.js#4022]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
When running `NODE_ENV=staging next build` I expect the `.next` folder to be generated with "staging" as `process.env.NODE_ENV` but I get "production" instead.

## Steps to Reproduce (for bugs)

1. Run `NODE_ENV=staging next build`

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     5.0.1-canary.14    |
| node    |    6.10     |

**Comment by timneutkens** [comment]
Searching for `NODE_ENV`: https://github.com/zeit/next.js/issues/3605#issuecomment-370255754

**Comment by Vadorequest** [comment]
Indeed, I did search for "build process.env.NODE_ENV" and found nothing tho. Thanks.
