### ISSUE TITLE
Webpack function in config ran twice

### ISSUE THREAD

**Issue by andrewreedy** [zeit/next.js#4023]
After configuring next with a webpack function it seems that the function gets called twice during all builds which results in ForkTsCheckerWebpackPlugin running lint/ts checks twice (in my setup).

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)
1. Create a next config with a webpack function which console.logs something
2. Run the app and see the message log twice.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    canary |
| node    |   6.11.5  |
| OS      |   macosx |

**Comment by timneutkens** [comment]
Once for the server, once for the client. Nothing weird there. You can check for `isServer` to distinguish them.

```
webpack: (config, {isServer}) => {return config}
```

**Comment by timneutkens** [comment]
And it's in the documentation https://github.com/zeit/next.js#customizing-webpack-config

**Comment by andrewreedy** [comment]
@timneutkens oops thank you for the info 👍
