### ISSUE TITLE
How to use a local IP address instead of localhost ?

### ISSUE THREAD

**Issue by glemiere** [zeit/next.js#4025]
- [X] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

Sorry in advance if I didn't find any informations. If this behavior is actually possible, please specify it in the README.

## Expected Behavior
Being able to use an IP (10.x.x.x) instead of localhost while using next dev.

## Current Behavior
Dev server launch on localhost.

**Comment by timneutkens** [comment]
@glemiere https://github.com/zeit/next.js/blob/canary/bin/next-dev#L34

Lets document this in the readme 👍

**Comment by glemiere** [comment]
Thank you!

**Comment by glemiere** [comment]
@timneutkens I made a PR that you might appreciate. ;-)
https://github.com/zeit/next.js/pull/4027

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/blob/canary/bin/next-dev#L56

https://github.com/zeit/next.js/blob/canary/server/index.js#L290

As you can see the value is directly passed into Node.js's http.listen, so any value that doesn't work is related to Node.js not supporting it I guess.
