### ISSUE TITLE
Styles rendering different between SSR/CSR

### ISSUE THREAD

**Issue by FrancosLab** [zeit/next.js#403]
Noticed a css bug/difference between SSR and CSR, when toggling javascript on and off.
CSS is being rendered backwords or incorrectly. Also using `import 'glamor/reset'` seems to cause double reset stylesheets.

Here is the component and styles.
https://gist.github.com/FrancosLab/6627597a0df0a9467a5c5f8b4e6e2cd7

Edit, there's a work around for the gist above

```
  const baseStyles = styles;
  const secondaryStyles = layout === 'rtl' ? rtlStyles : {}
  const css = merge(baseStyles, secondaryStyles);
```

Only SSR with javascript off. (incorrect)
<img width="1438" alt="ssr" src="https://cloud.githubusercontent.com/assets/20787123/21251301/a03981fc-c301-11e6-85ae-d3b4a7276acd.png">

With Javascript. (correct)
<img width="1439" alt="js" src="https://cloud.githubusercontent.com/assets/20787123/21251312/b0d67916-c301-11e6-813c-9f9d080ac718.png">

**Comment by rauchg** [comment]
We don't recommend using of glamor `reset` as you would have to do it per-page anyways. Please look at the global styles wiki page: https://github.com/zeit/next.js/wiki/Global-styles-and-layouts
