### ISSUE TITLE
Custom server routes can't found static files

### ISSUE THREAD

**Issue by gcfabri** [zeit/next.js#4032]
I've followed the custom-express-example to set custom server routes. Next/Link is working properly in client-side, but when the page is refreshed, the error message with 'not found' appears in console, regarding the files (css/images) from '/static' folder.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
The files in static folder should be found when matches the custom routes on server.

## Current Behavior
client:
```
 <Link as={`/lead/${id}`} href={`/lead?id=${id}`}>
```
server:
```
server.get('/lead/:id', async (req, res) => {
  return app.render(req, res, '/lead', { id: req.params.id });
});
```
error when page is refreshed:
![image](https://user-images.githubusercontent.com/10598662/37627192-10b917ca-2bb2-11e8-916f-c18900358873.png)

![image](https://user-images.githubusercontent.com/10598662/37627115-b3c79992-2bb1-11e8-83ec-7411072e8032.png)

## Steps to Reproduce (for bugs)
1. Define a custom route with express

## Context
I'm trying to set routes on an Express server and pass parameters by URL. Style and image files in the static folder are not found when accessed directly by the URL or refreshing the page.

## Your Environment
| Tech    | Version |
|---------|---------|
| next    | 5.0.1-canary.15 |
| node    | v9.5.0 |
| OS      | elementary OS 0.4.1 Loki |
| inferno     | ^4.0.8 |
| inferno-compat     | ^4.0.8 |
| inferno-server     | ^4.0.8 |
| react     | ^16.2.0 |
| react-dom     | ^16.2.0 |

**Comment by timneutkens** [comment]
You probably forgot to prepend a `/` when adding the assets 🤔

**Comment by gcfabri** [comment]
Probably...hehe. Sorry for the useless question. Thank you.

**Comment by timneutkens** [comment]
🙏
