### ISSUE TITLE
Build and Export for Cordova

### ISSUE THREAD

**Issue by ostrichegret** [zeit/next.js#4035]
Hi, would you please give me steps to build and export next.js for cordova ( localfile without server )?
Currently I use Create React App + Redux + Styled Components + React Router v4 ( HashRouter ),
after go to https://learnnextjs.com/, next.js looks promising with it's Server Side Rendering.

I hope I can build a web app with SSR and mobile app with one code base in next.js.
Please explain the steps required to build and export to Cordova, a demo will be very appreciated.

I already try to build and export, then edit the index.html to redirect the js to correct location, but still got error when navigating.

I have commented on https://github.com/zeit/next.js/issues/263 and go to slacks, it seems the participants are busy so I open a new issue

Thank you

**Comment by timneutkens** [comment]
We're currently focused on making Next.js an amazing experience for creating web applications / static applications, you might have a look at the react-native-web example: https://github.com/zeit/next.js/tree/canary/examples/with-react-native-web
