### ISSUE TITLE
How to write Server Side Code?

### ISSUE THREAD

**Issue by Ajar-Ajar** [zeit/next.js#404]
Hi,
Coming from express, where can I write server side code to handle tasks like authentication, sending emails, fetching data from DB?
I feel as if Next.js is providing an amazing infrastructure but it is a bit hard to get first orientation beyond the basic features. I think as a Universal framework, it will be great to have a real-world universal example made with Next.js!!

**Comment by sergiodxa** [comment]
The recommendation here is to have an API server for that kind of things and let Next.js only care about the data fetching (inside `getInitialProps`) and rendering your application (either server and client side).

Your API can be in Express.js, Django, RoR, Sails.js, Laravel, whatever you want :)

**Comment by arunoda** [comment]
@Ajar-Ajar even though it's said to be Universal. That's not exactly what it's means.
By default, Next.js will only render your pages on the server. 

As @sergiodxa mentioned, then it's the developers responsibility to connect to a data server and load the data. As @sergiodxa mentioned you could do that in the [`getInitialProps`](https://github.com/zeit/next.js#faq)

Other than that, you also will be able to do more on the server side once we land #310

**Comment by Ajar-Ajar** [comment]
Thank you both for the quick response!
