### ISSUE TITLE
Allow disabling Next's handling of 404

### ISSUE THREAD

**Issue by ghengeveld** [zeit/next.js#4042]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

I'm using a custom Express server around my Next.js application and I would like to be able to deal with unhandled routes myself. 

## Current Behavior

Currently Next.js handles all routes and [renders a 404 page](https://github.com/zeit/next.js/blob/eff27bdcfb7208e9cdadbfbeada4467384ffd379/server/index.js#L337) when a matching route isn't found. I haven't found a way to circumvent this behavior other than by avoiding the `nextApp.render()` altogether, but that requires me to deal with `/_next/` routes and hot reloading myself. I consider `defineRoutes()` to not be part of Next's public API so I don't want to use it.

## Context

I'm implementing a new frontend for a legacy application. I want to migrate away from the old application page-by-page. I do this by having Express proxy any unhandled requests (as the final catch-all route) to the legacy environment. At the moment this is impossible due to Next.js handling 404s, so I have to resort to using a whitelist of "already implemented routes".

## Proposal
I propose adding a `finalizeRequests` (default `true`) option to `next({...options})` which allows us to disable the handling of unknown routes. Specifically this concerns [these lines of code](https://github.com/zeit/next.js/blob/eff27bdcfb7208e9cdadbfbeada4467384ffd379/server/index.js#L336-L341).

**Comment by timneutkens** [comment]
This makes sense to me, but would we `throw` an error there when the flag is enabled? @arunoda what do you think?

**Comment by ghengeveld** [comment]
My current workaround is to essentially reimplement the `run` method:

```js
server.get("*", (req, res, next) => {
  const fn = nextApp.router.match(req, res, parse(req.url, true))
  const run = () => (nextApp.hotReloader ? nextApp.hotReloader.run(req, res).then(fn) : fn())
  fn ? run() : next()
})
```

Which is workable, but fragile (you guys may change this logic in the futute, breaking my app).

**Comment by ghengeveld** [comment]
I'm happy to setup a PR for this, but I would like to get some feedback before I dive into it.

**Comment by arunoda** [comment]
@ghengeveld Our idea os Next.js is to provide a simple API with some great control.
So, what you've is a really valid problem. And I can imagine some other related use cases.

But we don't like to add options to address each of these cases. This is the reason why we've two major features.

* Custom Routes - You can decide on which routes you need to process
* Custom Error Pages - You can change the look and feel of the default errors

I think you find a solution with ^^ features and If you've some time try to isolate it into a NPM module where other can use. (Not as a direct PR)

**Comment by vjpr** [comment]
Ran into this too. I think there should at least be an option.

A common case is someone using a custom server with a route for an Apollo server.

Say with a Koa server, if you have the next app handler anywhere in your routes, it will always 404 for things other than next.
