### ISSUE TITLE
Can I add functions in the pages/document.js to handle click events?my code Like this,

### ISSUE THREAD

**Issue by Hack-Jay** [zeit/next.js#4046]
_`

    static async getInitialProps({ renderPage }) {
      const { html, head, errorHtml, chunks } = renderPage()
      let config = {
        method: 'post',
        data: {
          query: `
                query {
                 ...
                    }
                }`
        }
      }
      const res = await fetch(config)
      const department = await Array.from(res.data.data.department)
      const data = await resetDepartment(department, null, 0)
      return { html, head, errorHtml, chunks , data  }
    }
`_

` 

   render() {

      const data = this.props.data
      if (data) {
        return (
          <html>
            <Head>
              <link rel="stylesheet" href="/_next/static/style.css" />
              <link rel="stylesheet" href="/static/header.css" />
            </Head>
            <body>
            {data.map( v =>{
                 <li key={v.id} ><button onClick={ ??? }>{v.name}</button></li>
            })}
              <Main />
              <NextScript />
            </body>
          </html>
        )
      }
`

How do I add a click to button event, I tried to add but didn't work?

**Comment by timneutkens** [comment]
You can't the _document is only server rendered. So you can't place interactions like onClick in it. You can use https://github.com/zeit/next.js/tree/canary/examples/layout-component for layout.
