### ISSUE TITLE
Dynamic import cache / HMR

### ISSUE THREAD

**Issue by OutThisLife** [zeit/next.js#4059]
Currently using dynamic imports like so:

```index.js
const Templates = {
  Type1: dynamic(import('./type1')),
  Type2: dynamic(import('./type2'))
}

export default ({ type, ...props }) => {
  const Component = Templates[type]
  return <Component {...props} />
}
```

All's been fine for awhile. However, after upgrading to 5.0 it seems like HMR no longer re-fetches the dynamic chunk. It seems hard cached on the server. Reverting to next@^4 fixes the issue.

Is there a way to disable the cache or..?

**Comment by OutThisLife** [comment]
Very easy to replicate w/ a fresh install: 

```
$ git clone git@github.com:OutThisLife/nextjs-cache-issue.git
$ yarn && yarn dev
```

Edit `test/index.js` and see HMR "reload" but not really.

**Comment by lolcoolkat** [comment]
I believe this is also similar to this bug here https://github.com/zeit/next.js/issues/3775

Hope this can be solved soon :(

**Comment by brad-decker** [comment]
Definitely related to #3775

**Comment by OutThisLife** [comment]
Still happening.
