### ISSUE TITLE
Let all the modules to bundle on the app

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#406]
Currently, we use a pre-bundled set of modules to load core modules like React, React DOM etc.
With this (specially with built in CDN support) we thought to increase the page load speed.

But it seems like if cause few issues:

* Some modules shared between the pre-packages bundle and the app's bundle (specially, babel and core-js related modules)
* If the user use React like frameworks, this has no use.
* Eventually, everyone will starting to use [`babel-preset-env`](https://github.com/babel/babel-preset-env). So, we never will be able to use the pre-packaged bundle.

So, we are getting rid of that and going back to the normal way how we bundle.

**Comment by matthewmueller** [comment]
Oh interesting, so the client bundle is going away?

 I think those points make a lot of sense, but one thing I liked about the client bundle was that you could vendor it so it wasn't rebuilt with the page each time, maybe there's a way to still do that with the new implementation for libraries that don't change much?

**Comment by rauchg** [comment]
Absolutely. We'll never move away from ahead of time compilation of bundles, otherwise everything will become slow

**Comment by arunoda** [comment]
@matthewmueller no it's not happening like that. 
But just how other apps works. It will send new modules over HMR. 
Anyway, if you still need a common bundle you could do it. 
Because you can do anything with the custom webpack setup.
