### ISSUE TITLE
how to config next.config.js withSass() with exportPathMap?

### ISSUE THREAD

**Issue by iamglenbacs** [zeit/next.js#4069]
I am trying to config next.config.js with exportPathMap like this, but it don't work,

`const withSass = require('@zeit/next-sass');
module.exports = withSass();
module.exports = {
  exportPathMap: () => ({
    '/': { page: '/' },
  }),
};
`
How do i config this together?

**Comment by timneutkens** [comment]
The parameter of withSass / any next plugin is the next config.
```
const withSass = require('@zeit/next-sass'); module.exports = withSass({ exportPathMap: () => ({ '/': { page: '/' }, }),
});
```
