### ISSUE TITLE
Should the httpOnly cookie set by external RestAPI be visible to NextJS?

### ISSUE THREAD

**Issue by jdolinski1** [zeit/next.js#4080]
Hello. I am currently facing this issue during implementing httpOnly cookie based authentication.
Scope:
1) Client accesses `/login` page and makes client-side login request to external RestApi server. If successful - recieves httpOnly cookie with JWT token as value. Cookie is set and readable by RestApi in future client-side (!) requests.

2) Client requests `/dashboard` page, in `getInitialProps` NextJS wants to make server-side data fetch from secured RestAPI route. This route requires the httpOnly cookie to be present in request headers.

3) Now what i thought would work is to obtain the cookie from client's requests `ctx.req.headers`, and manually append it to server-side api request headers. Problem is that the wanted cookie is not present in the `ctx.req.headers` - which somehow makes sense, because the initial cookie setup happened between browser and rest api - no NextJS involved here.

Any ideas how to make server-side fetching work here?
Thanks,
Jiří

**Comment by supra28** [comment]
can you check the cookie in `ctx.req.cookies` it should be there.

**Comment by timneutkens** [comment]
Basically the cookie is set on the API's domain, not your Next app, so you can't access it.
What I'd do (and what we do at ZEIT) is having a stateless API and doing verification to the API with a token (bearer).
