### ISSUE TITLE
What is ExportPatnMap for dynamic import ?

### ISSUE THREAD

**Issue by Popugune** [zeit/next.js#4099]
where i can find documentation for how to use exportPathMap

`module.exports = {
  exportPathMap: function() {
    return {
      // routes
    };
  }
};
`

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |    5.1     |
| node    |  9.9.0       |
| OS      |    win10     |

**Comment by timneutkens** [comment]
... https://github.com/zeit/next.js
