### ISSUE TITLE
Explanation of Custom Server and `popstate` Usage - Safari Back Button and Objects

### ISSUE THREAD

**Issue by jhoffmcd** [zeit/next.js#4103]
Noticied that in Safari (11.1), using the back/forward buttons with a custom express server fails to pass plain type objects via `getInitialProps`. This is causing errors due to running methods on `undefined` objects when users on Safari navigate using the back/forward buttons.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

Objects passed from server routes through `gitInitialProps` should persist even when using back/forward buttons in the browser.

## Current Behavior

Objects passed from server routes through `gitInitialProps` are not persisting when using back/forward buttons in the browser.

## Steps to Reproduce (for bugs)

See this repo I created, it includes steps: https://github.com/jhoffmcd/next-test-custom-server#test-2

## Context

I have a client site where a data object being passed by the server is not available on back/forward action, thus creating an error page for users. (Other types seem fine, arrays, strings, etc)
Could be related to: https://github.com/zeit/next.js/issues/2360
If custom `popstate` handling is a must to ensure persistant SSR, can this be added to the `custom-server-express` example or documented more clearly somewhere?

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  5.0.1  |
| node    | 8.9.4  |
| OS      |  osx 10.13.4  |
| browser | safari 11.1  |
| express     | 4.14.0 |
| react     | 16.3.0 |

**Comment by jhoffmcd** [comment]
Might be worth retesting this with v6 now thats its out. I'll try and do that and see if this is still valid.

**Comment by Aziz-JH** [comment]
I found for v5 a dirty workaorund. If you use the back button in Safari is the req undefined, but only on rerender. 

````js
class Index extends React.Component {
  static async getInitialProps({asPath, res, req, query}) {
    if (typeof req === 'undefined') {
      return __NEXT_DATA__.props;
    }
  }
}
````

**Comment by josephmaxim** [comment]
Same problem here. but only in Safari browsers. works fine in Chrome

**Comment by v1v3k** [comment]
Any other alternative to __NEXT_DATA__

**Comment by ijjk** [comment]
Might be related to #5648 putting this for reference

**Comment by ijjk** [comment]
Closing this as it does appear to be related to #5648 feel free to comment if you find it is not related.
