### ISSUE TITLE
Server render seems to time out during extended async call in getInitialProps

### ISSUE THREAD

**Issue by eli0shin** [zeit/next.js#4106]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

When dispatching an additional action (the middleware is `await`ing the second action before forwarding the first action to `next()`) from a redux middleware invoked by an action call in `getInitialProps`, the function should await both of the action promises resolving before rendering.

## Current Behavior

Server render does not include state from store dispatched by either action creator. If I don't `await` the second action call, state from the first action creator is present. As soon as the page is hydrated on the client side the actions dispatch normally in `componentDidMount()`.

It seems as if for some reason, the server render is timing out and not waiting for `getInitialProps` to resolve.

`getInitalProps`:
```js
static async getInitialProps({
    store: { dispatch },
    query: { slug },
    res,
  }) {
    await dispatch(getActiveOrg(slug)).catch(
      ({ response: { status } }) => {
        if (status === 404) {
          res.statusCode = 404;
        }
      },
    );
    return {
      slug,
    };
  }
```

middleware:
```js
export default ({ dispatch }) => next => async action => {
  if (action.type === ORGANIZATION_INFO_RECEIVED) {
    const { payload } = action;
    if (payload.donor_landing_page === 'cause') {
      await dispatch(
        fetchCauses(
          payload.subdomain,
          payload.donor_landing_page_id,
        ),
      );
    }
  }
  next(action);
};
```

## Context
The goal of this redux middleware is to allow for conditionally fetching additional data before the server response dependent on the response of an initial API call.

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |       5.0.0  |

**Comment by timneutkens** [comment]
As far as I know `dispatch` doesn't return a promise, so the `await` would do nothing. You'll probably have to check out one of the redux examples.

**Comment by eli0shin** [comment]
@timneutkens removing `await` results in the initial action completing before the second and the page being rendered with its state on the server.

With `await` it does wait for the promise to resolve. (hence why the initial action is never dispatched because the render times out while waiting for the second action to resolve before calling `next`) This code works perfectly once the page rehydrates on the client side however it seems to time out on the server.

`await`ing `dispatch` in `getInitialProps` works because dispatch does return a promise when it is called with a promise based action creator

```js
typeof dispatch === function;

typeof dispatch(
  promiseBasedAction()
) === object;

console.log(
  dispatch(
    promiseBasedAction()
  )
); > Promise { <pending> }
```

Additionally, looking at the redux dev tools. I can see that when `await`ing the second action before `dispatch`ing the first, the second action shows up in the dev tools before the first. When not `await`ing the second action, they show up in the original order.

**Comment by eli0shin** [comment]
Interestingly, the following code works as expected:

```js
static async getInitialProps({
    store: { dispatch, getState },
    query: { slug },
    res,
  }) {
    await dispatch(getActiveOrg(slug)).catch(
      ({ response: { status } }) => {
        if (status === 404) {
          res.statusCode = 404;
        }
      },
    );

    const org = getState().activeOrganization;

    if (org.donor_landing_page === 'cause') {
      await dispatch(
        fetchCauses(slug, org.donor_landing_page_id),
      );
    }

    return {
      slug,
    };
  }
```
