### ISSUE TITLE
Page path is incorrect in SSR when route is dynamic

### ISSUE THREAD

**Issue by lhguerra** [zeit/next.js#4109]
- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
Be able to access current route path inside page component.

## Current Behavior
When I console.log the current path inside a page and look at it in the server side, it is correct in the first moment but it logs a second time with an `&` instead of the dynamic part of the path.

## Steps to Reproduce
1. Create a dynamic route in `server.js`
```
server.get('/test/:id', (req, res) => {
    app.render(req, res, '/test')
  })
```
2. Create a page component for this route and log the route path
```
// pages/test.js
const Test = ({ url: { asPath } }) => (
  <div>
    Some content
    { console.log(asPath) }
  </div>
)

export default Test
```
3. Look at it in the terminal while running `node server.js` and accessing a page that matches the route (`/test/mytest`, for example)
```
/test/mytest
/test/&
```

## Context
I use this route because it matches my backend route that I am using as a context to load content, and with the incorrect route I do not get my data.

FYI: the same behavior is being noticed using `withRouter` from `next/router`.

**Comment by hugotox** [comment]
Can you describe what's your console.log? I can't find references to `currentPath`

**Comment by lhguerra** [comment]
@hugotox my console statement is simply logging a property from the url object that every Next page component has as a prop. I do not understand why you are looking for `currentPath`.

**Comment by hugotox** [comment]
You need to pass the query params to your render call: `app.render(req, res, '/test', { id: req.params.id })` like desbribed here https://github.com/zeit/next.js#custom-server-and-routing

**Comment by lhguerra** [comment]
I passed the params, but it changed nothing in my case.

**Comment by xfumihiro** [comment]
@lhguerra I had the same issue.
Check if there's any asset with invalid url (which is the suspect for firing second request to server).

**Comment by timneutkens** [comment]
1. `yarn create next-app --example custom-server-express custom-server-express-app`
2. `cd custom-server-express-app`
3. change `pages/posts.js` to:

```
import React, { Component } from 'react'

export default class extends Component {
  static getInitialProps ({ asPath, query: { id } }) {
    console.log('ASPATH', asPath)
    return { postId: id }
  }

  render () {
    console.log('URL', this.props.url)
    return <div>
      <h1>My blog post #{this.props.postId}</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
      </p>
    </div>
  }
}
```

4. `yarn dev`
5. go to `http://localhost:3000`
6. Go back to the console and see:

```
ASPATH /posts/id
URL { query: [Getter],
  pathname: [Getter],
  asPath: [Getter],
  back: [Function: back],
  push: [Function: push],
  pushTo: [Function: pushTo],
  replace: [Function: replace],
  replaceTo: [Function: replaceTo] }
```
