### ISSUE TITLE
cannot import components from outside the project

### ISSUE THREAD

**Issue by cyrilpanicker** [zeit/next.js#4114]
I have a project structure as below
```
- components
       - SharedComponent.js
- desktop
    - pages
        - page1.js
    - .next
- mobile
    - pages
        - page1.js
    - .next
```
There are 2 NextJs Projects. I am trying to share components between the two projects.
But I am getting an error when I try to use SharedComponents in one of the projects. SharedComponents is a React component written in JSX.

Below is the error
```
 error  in ./components/SharedComponent.js
[1] Module parse failed: Unexpected token (98:12)
[1] You may need an appropriate loader to handle this file type.
```

**Comment by mitrey** [comment]
does anybody know how to fix this?

**Comment by kuongknight** [comment]
@mitrey did you found solution?

**Comment by timneutkens** [comment]
Tracking this under #706
