### ISSUE TITLE
next/head allow duplicates if it has uniq keys

### ISSUE THREAD

**Issue by iserdmi** [zeit/next.js#4115]
I am trying add http://ogp.me/#array of `article:tag` property:
```
import NextHead from 'next/head'
<NextHead>
  <meta property="article:tag" content="tag1" key="tag1key"  />
  <meta property="article:tag" content="tag2" key="tag2key" />
</NextHead>
```

## Expected Behavior
I have set key for each line, so I expect that next.js understand that it is not duplicates:
```
<head>
  <meta property="article:tag" content="tag1"  />
  <meta property="article:tag" content="tag2" />
</head>
```

## Current Behavior
But next.js think tah it is a duplicates and remove tags except last tag:
```
<head>
  <meta property="article:tag" content="tag2" />
</head>
```

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    5.1.0     |
| node    |    9.2.0     |
| OS      |    OSX     |

**Comment by davscro** [comment]
Hi @iserdmi, 

you're right. Only two of them by [specifications](https://www.w3.org/TR/2014/REC-html5-20141028/document-metadata.html#standard-metadata-names) should not be duplicated:
You may not have multiple …

`meta-description elements:
`

> There must not be more than one meta element with its name attribute set to the value description per document.

`meta-application-name elements (per language):
`

> There must not be more than one meta element with a given language and with its name attribute set to the value application-name per document.

So I believe we should fix this to allow duplication in some cases.
