### ISSUE TITLE
Is it possible to use webpack DllPlugin to speed up the build?

### ISSUE THREAD

**Issue by tonypee** [zeit/next.js#4123]
Has anyone looked at how this could work with next - to make dev builds faster?

**Comment by timneutkens** [comment]
Yeah we did, but it will become obsolete with webpack 4.

**Comment by AndrewRayCode** [comment]
I'm exploring porting a project with a LOT of assets to next.js. Previously I was using the dllplugin to build a separate dll bundle once, and include that in my head tag. I'm not sure if something like this is possible with next? does next abstract away the entire webpack config?

**Comment by Gigacore** [comment]
Same here. Has anyone been able to use DllPlugin with NextJS?
