### ISSUE TITLE
Populate HEAD asynchronousy using Firebase

### ISSUE THREAD

**Issue by krokhale** [zeit/next.js#4128]
I use something like this to load firebase in my app, works great:

    export default async () => {
    const firebase = await import('firebase');
    try {

      firebase.initializeApp({
          apiKey: config["process.env.API_KEY"],
          authDomain: config["process.env.AUTH_DOMAIN"],
          databaseURL: config["process.env.DATABASE_URL"],
          projectId: config["process.env.PROJECT_ID"],
          storageBucket: config["process.env.STORAGE_BUCKET"],
          messagingSenderId: config["process.env.MESSAGE_SENDER_ID"]
      });

    } catch (err) {
      // we skip the "already exists" message which is
      // not an actual error when we're hot-reloading
      if (!/already exists/.test(err.message)) {
        console.error('Firebase initialization error', err.stack)
      }
    }

    var db = firebase.database();
    return {fb: firebase, db: db)}
     }

In my react component i use something like this to populate the head:

    <Head>
            <title>A Page - {this.state.pageName}</title>
    </Head>

this.state.pageName is fetched from firebase on component load.

The problem is that the title does not show up on the page. How do i make sure that firebase fetches things before page load. As in it is truly server side rendered, at least the initial page load.

ideas?

**Comment by timneutkens** [comment]
You'd have to fetch in `getInitialProps`

**Comment by krokhale** [comment]
Thanks, can't believe i missed that!
