### ISSUE TITLE
test: can't run testcases rightly in local environment

### ISSUE THREAD

**Issue by xtx1130** [zeit/next.js#4133]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=test) of this repository and believe that this is not a duplicate.

## Expected Behavior
```shell
$ npm run test
```
Should run testcases without mistakes

## Current Behavior
![image](https://user-images.githubusercontent.com/5475069/38540314-25c3de5c-3cce-11e8-96f2-ac37c0ac4945.png)

## Steps to Reproduce (for bugs)
1. download next.js canary
2. `npm install`
3. `npm run test`

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |    canary     |
| node    |    6.7.0     |
| OS      |   Mac OS 10.12.6       |
| tty |     zsh    |

**Comment by timneutkens** [comment]
These are the tests for the next.js repository. (just to be clear).
It sometimes happens that webdriver is not installed correctly by npm/yarn. The solution is usually to `rm -rf node_modules` and reinstall.
