### ISSUE TITLE
Static Export - Missing Query params when opening link in new tab

### ISSUE THREAD

**Issue by mlecoq** [zeit/next.js#4135]
I have several nextjs application that are statically exported. Navigation through pages works fine except when I use _right click_ > _Open Link in new tab_ : query params are missing in the url of the opened tab

When I run the application with a server, everything works fine. This issue is related to static export.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
When I open a link in a new tab, I expect to have the url of the link in the new tab (like a regular click) 

## Current Behavior
When I open a link in a new tab, query params are missing in the url

## Steps to Reproduce (for bugs)

1. Create two pages /a /b
2. In page a add a `<link href="/b?param=value"><a href="/b?param=value">link</a></link>`
3. Static export
4. On page a, right click > open link in new tab => the url is /b/ instead of /b/?param=value

## Context
My application is a marketplace, from a list users open several tabs to compare details of opened items

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    5.1.0   |
| node    |   8.10      |
| OS      |     Reproduced on MacOS and Linux    |
| browser |   Reproduced on Firefox and Chrome     |

**Comment by arunoda** [comment]
I just tested your case. I cannot reproduce.
It should work without any issues.

Could you send us a sample repo with the issue?

**Comment by mlecoq** [comment]
Sure, I will build a small example

**Comment by mlecoq** [comment]
I was not able to reproduce on a small example. 

In fact this issue is related to using static export on Amazon S3. 

I did not notice it while opening new tabs : amazon make a redirection from /a?param=value to /a/ whereas /a/?param=value works fine. 

I close this issue, 
thanks for your time

**Comment by balazs4** [comment]
I'm facing a very similar issue, and I was able to reproduce it.
I'm not sure that this is a AWS S3 issue.

@arunoda could you please take a look? :pray: 
https://github.com/balazs4/next-export-issue
