### ISSUE TITLE
when i use custom server, why webpack-dev-server also work?

### ISSUE THREAD

**Issue by Deval520** [zeit/next.js#4142]
- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
Not sure what you're trying to ask.
