### ISSUE TITLE
Update custom `<App>` examples in README

### ISSUE THREAD

**Issue by julianrubisch** [zeit/next.js#4145]
Apologies, I'd like to use a custom `<App>`, but the examples referenced in the README either don't include a custom `pages/_app.js` file (https://github.com/zeit/next.js/tree/canary/examples/layout-component) or don't exist anymore (https://github.com/zeit/next.js/blob/canary/examples/componentdidcatch)

**Comment by timneutkens** [comment]
They're not released yet, same with the custom `<App>` component.

**Comment by mattiasewers** [comment]
When can we expect a release? week? month?

**Comment by timneutkens** [comment]
Canary will be out this week. The stable release schedule is not public at this point 👍

**Comment by growak** [comment]
Does the _app.js still working on the current version ?

**Comment by chanlito** [comment]
Hi, @timneutkens I'm new to next.js, I'm wondering how is the workaround before custom _app.js?

**Comment by Bamieh** [comment]
@timneutkens will _app be used to initialize the store for redux and wrap providers? (instead of HOCs at the page level?)

**Comment by timneutkens** [comment]
Just released https://github.com/zeit/next.js/releases/tag/6.0.0-canary.4

Will add the new examples soon (as per the initial ticket request).

**Comment by callumlocke** [comment]
It would be good to flesh out the readme section on custom apps too. Currently it doesn't explain what `Component` and `Container` do, and what props they take, if any.

**Comment by timneutkens** [comment]
The examples have been updated. Created a new issue for #4347

**Comment by sauravazad** [comment]
Please add details about container , I could not find one even in the codebase.

**Comment by timneutkens** [comment]
It's in `lib/app.js`, anyway there's an issue for it, #4347 as I said in the comment.
