### ISSUE TITLE
Extend `assetPrefix` for global prefixing

### ISSUE THREAD

**Issue by zvictor** [zeit/next.js#4146]
It has been great to have `assetPrefix` in our app. With few modifications we are able to serve nextjs next to a meteor app, served in the same domain but with a specific prefix:

```
mydomain.com/next/* --> nextjs
mydomain.com/* --> old meteor
```

**The problem**

In the scenario described above, we make use of `assetPrefix` not only for assets but for the whole application. As consequence:

1) It feels hacky to call it `assetPrefix` when we are actually prefixing everything.
2) As it was intended, the helpers from `next/asset` are only useful for proper assets. Anything outside of `/static` that needs to be prefixed can't be done this way.
3) The `assetPrefix` is not accessible from `next/config`. If you want to reuse `assetPrefix` e.g. when [prefixing your routes](https://github.com/fridays/next-routes/issues/30#issuecomment-380832653), you can't.

**Desired behaviour**

↳  Option 1 (quick and dirty):

give access to `assetPrefix`, allowing devs to keep misusing it as a global prefix.
```js
import { getAssetPrefix } from 'next/asset'

myRouter.setPrefix(getAssetPrefix())
```

↳  Option 2:

create a new prefix to cover the use case I described.

```js
import { globalPrefix } from 'next/config'

myRouter.setPrefix(globalPrefix)

...

express().use(globalPrefix, myRouter)
```

`assetPrefix` would still exist, but `globalPrefix` would be its default value.

**Comment by tlenex** [comment]
Struggling with this too, seems like we have to make a custom server with all routes just for prefix support.

**Comment by timneutkens** [comment]
Tracking this here: #4998
