### ISSUE TITLE
--- Error: Cannot find module 'next' --- on custome-server-express example project

### ISSUE THREAD

**Issue by Ajar-Ajar** [zeit/next.js#415]
trying to install and run the custome-server-express example project
getting  -- Error: Cannot find module 'next' -- on server.js line 2 
`const next = require('next')`

any ideas?

**Comment by arunoda** [comment]
I hope you are running from the local next repo.
(Since we've not shipped this yet)

Follow these steps:

Go to the next.js local clone

```
npm i
npm link
cd examples/custome-server-express
npm i
npm link next
npm start
```

**Comment by Ajar-Ajar** [comment]
Thank you, that solved it!

**Comment by arunoda** [comment]
Okay. Let's close this issue.

**Comment by Stas-Buzunko** [comment]
What do u mean by saying "(Since we've not shipped this yet)" ?
next module is installed why can't I import it?

**Comment by Stas-Buzunko** [comment]
when is it going to be shipped?

**Comment by livoras** [comment]
Yeah, same issue here. I am still wondering why I cannot import the 'next' module even it's in my local node_modules/ .
