### ISSUE TITLE
Font loading on custom server

### ISSUE THREAD

**Issue by awesome-rio** [zeit/next.js#4157]
I am trying to use parameterized routing using custom server for clean routes.but the problem is that my static folder that contains the images and fonts does'nt load from server.js. is there any way to do that?
![screenshot from 2018-04-16 10-52-36](https://user-images.githubusercontent.com/32071070/38792351-350f270e-416a-11e8-93b7-cc5922c57aac.png)

**Comment by albinekb** [comment]
Yes, you need to have the last fallback handler to get the default static serving to work:

```
  server.get('*', (req, res) => handle(req, res))

```

It's all in the express example 👍

**Comment by timneutkens** [comment]
If what @albinekb is saying is not the case please provide a way to reproduce 🙏 It's impossible for us to help if we don't get any code samples.
