### ISSUE TITLE
Allow better organisation of pages (like subfolders)

### ISSUE THREAD

**Issue by baba43** [zeit/next.js#4158]
Hello,

as my project grows, I see problems with having all the pages within a single folder. Usually every website has some kind of hierarchy, but currently it seems like we are unable to create any kind of hierarchy on file-level.

For instance, it would be perfect for us if we would have the possibility to use subdirectories. I have tried that and found out that my page gets inaccessible after moving it into a subfolder.  Neither `/mypage` nor `/subfolder/mypage` seems to work. 

I can see two very simple solutions:

1. Ignore subdirectories and make the page accessible by its name (`/mypage`)
2. Include subdirectories as parts of the route, so we can use dynamic routing to access them

Last but not least, I would like to say thank you for this awesome project.

**Comment by baba43** [comment]
You are absolutely right, sorry.

The routing did not work in my case, because of the existing dynamic routing. 

Everything is fine. Keep up the great work 👍

**Comment by timneutkens** [comment]
Great! 🙏

**Comment by spikebrehm** [comment]
I'm having this issue too, with Express custom routing.  I have an Express server that sets up a few custom end points, and then I pass Next's middleware to a wildcard route:

```js
const handle = app.getRequestHandler();
app.prepare().then(() => {
  // add custom routes to `server`
  server.get('foo', customMiddleware);

  server.get('*', handle);
});
```

This works fine for pages like `/blog`, but filesystem routing doesn't work for subdirectories like `/blog/hello-world`.

Can you help me understand why this doesn't work out of the box, and if there's a simple way to fix it that doesn't entail explicitly spelling out all my routes in Express?

Thanks @timneutkens

**Comment by spikebrehm** [comment]
Nevermind — I had a previous route glob that was overriding the route in question 🤦🏻‍♂️.
