### ISSUE TITLE
Add config.pagesGlobPatternOptions for Glob

### ISSUE THREAD

**Issue by billnbell** [zeit/next.js#4164]
const pages = await glob(config.pagesGlobPattern, { cwd: dir })

Would like you to add:

config.pagesGlobPatternOptions
const pages = await glob(config.pagesGlobPattern, { ...config.pagesGlobPatternOptions, cwd: dir })

**Comment by timneutkens** [comment]
Please follow the issue template, especially for feature requests. 
We’re Not planning to change anything related to how we resolve pages at this moment.
