### ISSUE TITLE
404 page not working with <Link prefetch />

### ISSUE THREAD

**Issue by boblauer** [zeit/next.js#4172]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

A link using `prefetch` and pointing to a non-existent url should show the standard 404 page.:

```html
<Link prefetch href="/bad-url" />
```

## Current Behavior

The browser does not navigate anywhere, and so it looks like the link is unresponsive.

## Steps to Reproduce (for bugs)

1. Add 

```html
<Link prefetch href="/bad-url" />
```

to a page

2. Click on it, notice the browser does nothing.

## Context

Because this has to do with `prefetch`, this is production-only. Not sure if it matters, but this is a client-side only app hosted on Netlify.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  4.2.3  |
| node    |N/A, client-side only|
| OS      |OS X 10.13.4|
| browser | Chrome  |
| etc     |         |

**Comment by timneutkens** [comment]
If this wasn't fixed already in next 5/6/7 it's fixed by https://github.com/zeit/next.js/pull/5737 for sure.
