### ISSUE TITLE
Can't get SASS modules working with global stylesheets and vice versa

### ISSUE THREAD

**Issue by eugeneross** [zeit/next.js#4178]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

I want to expect styles from my modules to be compiled into the same stylesheet as my global styles. Please see demo setup below to understand where styles are being pulled from.
```
├── pages
│   ├── index.js
├── components
│   ├── Button
│   │   ├── index.js
│   │   ├── index.sass
├── styles
│   ├── index.sass (Global stylesheet with @imports)
```

## Current Behavior

Can't get both modules and global styles to work together in parallel. Only one of them can be used while the other cannot. Please see my comments in [this demo repo](https://github.com/numieco/tortuga/tree/demo) in the files, `_document.js`  and `styles/index.sass`

## Steps to Reproduce

1. Clone [this repo](https://github.com/numieco/tortuga/tree/demo)
2. `yarn && yarn dev`
3. View comments in `_document.js` and `styles/index.sass` to turn on and off behaviors.
4. If you inspect the styles you'll see that the global styles are only being applied.
5. Comment out line 5 in `_document.js`, save, and you'll notice that module styles will be applied but not the global styles.

## Context

As stated in the above, I want the ability to use SASS modules within my `components` folder AND global styles in my `styles` folder together. As of right now I can either have styles from modules and NOT from my global stylesheet OR have styles from global stylesheet and not my modules. 

The only work around I've found is including the path of a component's style inside my `styles/index.sass` file, like so:

`@import '../components/Button/index'`

The only issue with this is that the global stylesheet is imported into the `_document.js` and therefore reloads the page on save for those styles intstead of injecting those changes. That's not the biggest deal in the world, but not ideal.

I'm not sure if the issue is due to the way modules and `_document.js` work together, or if there needs to be a specific way to allow this within the `next.config.js` setup.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     6.0.0-canary.4    |

Issue is persistant for stable releases too.

**Comment by timneutkens** [comment]
Please file this under next-plugins.
