### ISSUE TITLE
Error: INVALID_BUILD_ID Error Handling or Redirect to Current Build

### ISSUE THREAD

**Issue by ottoinfo** [zeit/next.js#4179]
ISSUE:  Bots will scrape your pages, they may come back at a later time to index your page. During this time we may have released a new BUILD. The bot is scraping with a specific BUILD_ID ( OLD/INVALID ) and I cant find a way to catch ERRORS ( via Middleware ), now we just have get '500 - Internal Error'.

![screen shot 2018-04-19 at 11 36 45 am](https://user-images.githubusercontent.com/643526/39013833-751446e4-43cd-11e8-803b-71223cf0c207.jpg)
 
POSSIBLE FIX: Check Current Build and Redirect 301 to new Build

server.js ( minimal server.js file )
``` 
const dev = process.env.NODE_ENV !== 'production'
const nextApp = nextJS({ dev })
const server = express()
nextApp.prepare().then(() => {
  server.get('/_next/*', (req, res) => {
    if (!dev) { 
      redirectOnInvalidNextdBuildHash(req, res)
    }
    nextApp.getRequestHandler()(req, res)
  })
  server.listen(3000, (err) => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000') // eslint-disable-line
  })
})

```

redirectOnInvalidNextdBuildHash.js 
```
const fs = require('fs')
const path = require('path')

const BUILD_ID = fs.readFileSync(path.join(__dirname, '../../.next/BUILD_ID'), 'utf8').trim()

const redirectOnInvalidNextdBuildHash = (req, res) => {
  const file = req.params[0]
  console.log('/_next/*', { file })
  // Check Build Hash
  if (file.search(`${BUILD_ID}/`) === -1) {
    const url = `/_next/${BUILD_ID}${file.slice(file.indexOf('/'))}`
    console.log(`must redirect to ${BUILD_ID} at ${url}`)
    res.redirect(301, url)
  }
  return 'valid'
}

module.exports = redirectOnInvalidNextdBuildHash
```

![screen shot 2018-04-19 at 12 17 32 pm](https://user-images.githubusercontent.com/643526/39013843-7c5d8a6e-43cd-11e8-8e96-00e7881799c4.jpg)

**Comment by tima101** [comment]
@ottoinfo I tested - this error also happens when user has current app open in the tab while you deploy new app. I think this or related error is described here: https://github.com/zeit/next.js/wiki/Handle-BUILD_ID-Mismatch-Error

**Comment by alexanderatallah** [comment]
Having this same problem on Next v5.1 - we're getting 500 errors from the googlebot every 2 minutes...

**Comment by jschumme** [comment]
this is a problem I struggle with over and over again. When making use of caching and Service Workers you will definitely run into that problem from time to time. 

After deploying a new version of your app, it might happen that a user keeps getting this 500 error (or 404 in next 6.0.0). The only thing you can do is to clear the cache. On mobile devices this is not a common thing to do. I have to admit that I know too less about the cause for that error and I wonder if there's anything we could do server-side to solve the problem for the user.

**Comment by timteeling** [comment]
Had this same issue between Googlebot and New Relic reporting the 500 errors.

The 500 errors have changed to 404 errors in v6 with this PR: https://github.com/zeit/next.js/pull/3941 and it makes Goooglebot & New Relic happy. The cached page has old asset reference, but since its server rendered, the page content gets indexed still without Google throwing errors since it doesn't care about 400 series errors.

**Comment by timneutkens** [comment]
The invalid build id issue was solved in v6.
