### ISSUE TITLE
Dynamic imports (without next/dynamic) error in builds

### ISSUE THREAD

**Issue by morgs32** [zeit/next.js#4180]
When using the conventional [webpack 2+ dynamic imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports), everything works great in dev but breaks in production (with builds).

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Current Behavior
A bug: dynamic imports should work in production as well as they do in development.

## Steps to Reproduce (for bugs)

1. Pull down this [example nextjs](https://github.com/morgs32/with-dynamic-imports) app to reproduce
2. `yarn dev` to see it working in dev
3. `yarn build` then `yarn start` to spin up the production build

## Context
I am trying to code-split my app and some of my dynamic imports are NOT components. So using `next/dynamic` is not appropriate...

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   5.1.0 (latest)     |
| node    |   9.7.1    |
| OS      |    mac     |
| browser |   chrome    |

**Comment by morgs32** [comment]
This doesn't seem to be an issue in next@6.0.0-canary.4

**Comment by mapledna** [comment]
> 
> 
> This doesn't seem to be an issue in next@6.0.0-canary.4

I have the same problem. So why ?
