### ISSUE TITLE
Importing CSS/Less in dynamically imported modules not working.

### ISSUE THREAD

**Issue by krokhale** [zeit/next.js#4184]
const FormCreator = dynamic(import('../components/forms/creator'));

And inside FormCreator:

    import '../../node_modules/button/style/index.less';

If i were to import FormCreator the usual way:

    import FormCreator from '../components/forms/creator';

Works great and the less file is included. But when dynamically invoked, the less file does not take effect.

What am i missing?

**Comment by krokhale** [comment]
Looked a bit into this, the module is fetched dynamically as expected with the styles in it, but the styles aren't getting added to the page, the page does not refresh with the new styles imported dynamically.

**Comment by timneutkens** [comment]
There is an issue for this on the next-plugins repository
