### ISSUE TITLE
Custom _error.js with scss breaks the stylesheets from other pages in next@6.0.0-canary.x

### ISSUE THREAD

**Issue by PaulRBerg** [zeit/next.js#4185]
This happens only in `6.0.0-canary.x` releases. If you go back to `5.10.0` it works fine.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

Should load scss in pages even if there are styles set in `_error.js`.

## Current Behavior

It doesn't load scss in pages if therea are styles set in `_error.js`,

## Steps to Reproduce (for bugs)

1. git clone https://github.com/PaulRBerg/next.js-broken-scss
2. cd next.js-broken-scss
3. npm install
4. npm run dev

## Context
If you try to load other scss in any file from pages, it doesn't load and it defaults to the scss used in the custom `_error.js` file. If you comment that out, you lose the styles for the error page, but it works on the normal ones.

I spent one full day on this, and I think it's an important bug. It's really confusing, hard to track and reproduce, as you'd normally question the configuration of babel, next-sass, next-compose-plugins & so on.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 6.0.0-canary.4 |
| node    | 9.4.0 |
| OS      | OSX Sierra 10.13.3 |
| browser | Chrome 65.0.3325.181 |

**Comment by timneutkens** [comment]
Please file this under the next-plugins repository. We're not doing anything in Next itself to provide scss/sass support.

**Comment by PaulRBerg** [comment]
Okay, thank you for your reply.
