### ISSUE TITLE
_app.js problem in 6.0.0-canary.4

### ISSUE THREAD

**Issue by landerton** [zeit/next.js#4186]
I can't get my app to work after switching to 6.0.0-canary.4.  It is complaining that it can't import App or Container in my _app.js file.

The error I get says: 
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
    in Container (at _app.js:18)
    in App
{ TypeError: Cannot read property 'toLowerCase' of undefined
```

- [ x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

I'm trying to override _app.js to create a persisting layout. Although, even without a _app.js file in my pages directory, I still get a similar error.

## Current Behavior

I get the error mentioned above follow by a sequence of `TypeError: Cannot read property 'toLowerCase' of undefined` errors, which I believe is a result of the first error related to importing something wrong.

## Steps to Reproduce (for bugs)

1. Upgrade from next 5.1.0
2. Run the app - `yarn dev` or `yarn build` and `yarn start`
3. Get the error
4. I get the same error even if I don't try to override _app.js, but my _app.js file is currently just boilerplate from the example

```
import React from 'react'
import App, {Container} from 'next/app'

class MyApp extends App {
  static async getInitialProps ({ Component, router, ctx }) {
    let pageProps = {}

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }

    return {pageProps}
  }

  render () {
    const {Component, pageProps} = this.props
    return (
      <Container>
        <Component {...pageProps} />
      </Container>
    );
  }
}

export default MyApp
```

## Context

I'm excited about the new features released in 6.0.0-canary.4. Especially the idea of persisting layout. 

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    6.0.0-canary.4     |
| node    |    v8.1.3     |
| OS      |    macOS 10.13.4     |
| browser |    chrome 65     |
| etc     |         |

**Comment by timneutkens** [comment]
Works fine for me. Can you provide a full reproduction. With the simplest app I can't reproduce.

**Comment by liumin1128** [comment]
I had the same problem, have you solved it ?

**Comment by landerton** [comment]
@liumin1128 Finally figured it out. It was just a matter of updating react and react-dom to the their latest versions. Went from v16.0.0 to v16.3.2.
