### ISSUE TITLE
How to remove the slash / from the src that imports the javascripts?

### ISSUE THREAD

**Issue by victorsferreira** [zeit/next.js#4189]
I exported my application and i'm serving it from an Apache server from a context `/some/context`.

Next is generating this Link tag in the HTML

`<link rel="preload" href="/_next/2c31e04a-25d0-4955-b025-633ff48e3fbd/main.js" as="script">`

The problem is that the page is looking for the javascripts from the root of the server. But it should look for it from `/some/context`.

How can I make Next remove this slash from the `href` so it will look for javascripts in the `_next` from this specific context?

**Comment by timneutkens** [comment]
Add https://github.com/zeit/next.js#cdn-support-with-asset-prefix set to `/some/context`.
