### ISSUE TITLE
How to define multiple routes on a custom server?

### ISSUE THREAD

**Issue by Ajar-Ajar** [zeit/next.js#419]
Hi, I need to implement multiple parametized routes like:
`/profile/:id` , `/profile/:id/edit` ,  `/item/:id` , `/item/:id/edit`  etc...

the 'parameterized-routing' example is using a custom server which uses 'path-match' npm package.
Both the 'parameterized-routing' example and the 'path-match' readme file demonstrate a single route example and I wasn't able to hack my way into implementing multiple routes...

Your help would be very much appreciated
Thank you
Ajar

**Comment by arunoda** [comment]
@Ajar-Ajar you could simply use express for that. Use express's routing APIs.
See: https://github.com/zeit/next.js/blob/master/examples/custom-server-express/server.js#L11

**Comment by rauchg** [comment]
For everyone visiting this issue: please note that the custom server API has not been released to npm yet :D

**Comment by Ajar-Ajar** [comment]
Thank you @arunoda !
