### ISSUE TITLE
Fix release description for v6.0.0-canary.5

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#4196]
As `react-hot-loader` was not actually updated in the version published to npm the line should be removed from the [v6.0.0-canary.5 release](https://github.com/zeit/next.js/releases/tag/6.0.0-canary.5) description.

See https://github.com/zeit/next.js/pull/4171#issuecomment-383429602.

**Comment by timneutkens** [comment]
Released canary 6
