### ISSUE TITLE
Using _app.js in v6.0.0-canary.5 Release Breaks Static Export

### ISSUE THREAD

**Issue by adamsoffer** [zeit/next.js#4200]
Using `_app.js` and then running `next export` throws an error.

`TypeError: Cannot read property 'getInitialProps' of undefined`.

**Comment by timneutkens** [comment]
Only happens when you `next export` without `exportPathMap` right, Fixed that in #4201, thanks for the report 😌

**Comment by timneutkens** [comment]
Released as canary 6

**Comment by adamsoffer** [comment]
Nice! Yup this is fixed now. Thank you!
