### ISSUE TITLE
SyntaxError: Expected the "svgName" prop to be a string, What should I do?

### ISSUE THREAD

**Issue by skyweaver213** [zeit/next.js#4203]
I assign a string to svgName, is ok.

```js
return (         
            { BENIF.map((v, k) => {
                return (<li key={k}>
                    <svg svgName="webapp/src/assets/svg/local"  width='9' height='17' className="svg-arr-l"/>
                    </li>)
            } )}
```                

But I assign a variable to svgName, is bad.

``` js
  const BENIF = [
            'webapp/src/assets/svg/crown',
            'webapp/src/assets/svg/discount',
            'webapp/src/assets/svg/earth'
           ];
 return (         
            { BENIF.map((v, k) => {
                // svgName={v} "webapp/src/assets/svg/local"  svgName={str}
                let str = v.toString() || ''
                return (<li key={k}>
                    <svg svgName={str}  width='9' height='17' className="svg-arr-l"/>
                    </li>)
            } )}
```
<img width="365" alt="string1" src="https://user-images.githubusercontent.com/5363176/39165279-429ba120-47b6-11e8-8d8b-3b104483e2f5.png">

**Comment by timneutkens** [comment]
It's probably something specific to React expecting it to be a string. Please file an issue on the React repository.

**Comment by gaearon** [comment]
React can’t make your build fail. No, it’s not specific to React.

**Comment by skyweaver213** [comment]
Hello Tim Neutkens, Could you help to confirm it? Thanks! @timneutkens

**Comment by timneutkens** [comment]
@gaearon thanks for confirming, then I don't know what it is, it's also not related to Next.js, since we don't use any linter. So it's either related to Babel or Webpack 🤔 can you provide a minimal reproduction as repository, so that I can check it out real quick.
