### ISSUE TITLE
Replacing dynamic import component loading text

### ISSUE THREAD

**Issue by paschaldev** [zeit/next.js#4219]
I use next.js with a custom server, my dynamically imported component always shows a 'loading...' text. 

I would like to override that behaviour because it doesn't fit well on my layout, I'll rather show blank instead of a text. I've tried replacing it with an empty string `''`, `' '` and also `null`, all to no avail. 

When I navigate via a click, component renders well but when I refresh the page, I see this directly above the already loaded and rendered dynamic component.

```
<p>loading...</p>
```

## My Environment

| Tech    | Version |
|---------|---------|
| next    | 5.1.0        |
| node    |  v8.6.0       |
| OS      | Mac OS El Capitan        |
| browser | All Browsers        |

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js#2-with-custom-loading-component

**Comment by paschaldev** [comment]
@timneutkens I know about that, I would've loved to render nothing instead if the component hasn't loading yet. Works best for my layout. I've tried something like this.

```js
const UserConnectionList = dynamic( import('../src/components/UserConnectionList'), { loading: () => null })
```

and also with an empty string 


```js
const UserConnectionList = dynamic( import('../src/components/UserConnectionList'), { loading: () => '' })
```

Unfortunately, I still see the `<p>loading...</p>`

**Comment by timneutkens** [comment]
Should be fine 🤔 Can you provide a reproduction repository?

**Comment by paschaldev** [comment]
To my surprise, it works perfectly now. I realized the cause was the empty string, I replaced all with `null` and it did work fine, I don't see it anymore. 

All good. Closing this.
