### ISSUE TITLE
WebCrypto API disappears in production

### ISSUE THREAD

**Issue by KristerV** [zeit/next.js#4220]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

The WebCrypto library makes available a variable "crypto" in browser side. This variable has useful keys like `subtle`. And in the development environment this works just fine.

## Current Behavior

In production however the variable `crypto` is an empty object. As in `{}`. This is true in Chromium: Version 65.0.3325.181 (Official Build) Arch Linux (64-bit)

Firefox 50.0.2 works just fine.

## Steps to Reproduce (for bugs)

The production site is here: http://159.65.115.61/

Later I'll try produce a minimal code example too.

## Context

I need to do ArrayBuffer -> SHA256 hashing on client side.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | ^5.0.0 |
| node | v8.2.1 |
| OS      | docker + ubuntu |
| browser | Chrome 65.0.3325.181 |

## Other

While this may be a Chrome issue it's unclear how do I debug the situation since it's working in dev env.

**Comment by antimatter15** [comment]
I think the WebCrypto API is only available on HTTPS sites, it should come back if you host your website with LetsEncrypt or otherwise get an SSL certificate.

**Comment by timneutkens** [comment]
We don't do anything to block this. The https/localhost vs http makes sense.
