### ISSUE TITLE
Warning: Prop `xx` did not match. Server: "A", Client: "A, B", But Client not rendered

### ISSUE THREAD

**Issue by skyweaver213** [zeit/next.js#4228]
I found that as long as the server side is different from the client, it is often not rendered, but in fact, some properties are added when the client is needed, such as the information recorded in localStorage. Should this problem be solved?

<img width="862" alt="wx20180430-174349 2x" src="https://user-images.githubusercontent.com/5363176/39422196-e88fdfe6-4c9e-11e8-878f-dc3964dfde38.png">

| Tech    | Version |
|---------|---------|
| next    |     5.1.0    |
| node    |    V8.9.3     |
| OS      |     10.12.6    |
| browser |     chrome 66.0.3359.117    |

**Comment by timneutkens** [comment]
Please provide a full reproduction. This is unrelated to Next.js, and related to rendering classNames directly based on some environment, instead of using state with componentDidMount.
