### ISSUE TITLE
server side dependencies in _doucment throw not found error in v6

### ISSUE THREAD

**Issue by chentsulin** [zeit/next.js#4230]
It looks like webpack try to bundle all of server side dependencies, so it can't find module `fs`.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

`dotenv` in `_document` works with Next.js v6.

## Current Behavior

After upgrading from v5 to v6, it throws error:

```
This dependency was not found:

* fs in ./node_modules/dotenv/lib/main.js

To install it, you can run: npm install --save fs
(node:6389) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
Client on: http://localhost:3000/projects
```

## Steps to Reproduce (for bugs)

1. use `dotenv` in `_doucment`
2. upgrade to Next.js v6

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  v6.6.0       |
| node    | v9.11.1        |
| OS      |  macos 10.13.4       |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
There was a regression in Next 5 where _document didn't get hot reloaded. This was fixed (same behaviour as next 4), but now you need to add fs etc to externals when `!isServer` in next.config.js.

**Comment by kachkaev** [comment]
@timneutkens I just upgraded to Next 6 and am facing the same issues. Could you please explain what you mean in your comment? In particular, I'm trying to make this trick work: https://github.com/zeit/next-plugins/issues/11#issuecomment-376125174

**Comment by kachkaev** [comment]
Looks like I solved this by adding this to my `next.config.js`:

```js
module.exports = {
    webpack: function(config) {
      config.externals.push('fs');
      return config;
    },
}
```

🤷‍♂️
