### ISSUE TITLE
Next@6.0.0 development profile error (ECONNREFUSED 443 port with local NPM registry) (needs `update-check` bump to `1.4.0`)

### ISSUE THREAD

**Issue by alexandre-marchina** [zeit/next.js#4237]
Hello,

Trying to run `Next@6.0.0` with dev profile and a local NPM registry that doesn't serve https (443)

We've got an error `ECONNREFUSED` when calling: 

```javascript
const dev = true;
const nextApp = next({ dev });
nextApp.prepare().then(...)
```
We got this `Error: connect ECONNREFUSED %IP_ADDRESS%:443`

Our .npmrc has a setting like this, using a local registry: `registry=http://mycompany.intranet` (notice the *http://*)

Actually our local registry doesn't run in https (only http) thus causing the :443 port not to be exposed.

Investigating further, we've find out that a dependency (`update-check`) tries to connect directly with our registry ignoring that protocol setting, connecting with https and getting this "connection refused"
https://github.com/zeit/next.js/blob/canary/server/index.js#L118

(`update-check` explicitly using `https` ignoring the protocol setting coming from the .npmrc: https://github.com/zeit/update-check/blob/master/index.js#L2)

**Comment by alexandre-marchina** [comment]
@ghengeveld Yes, this is kinda a "solution" that solves the problem but I believe that `update-check` should respect these settings on .npmrc (it does this to the other parts of the registry URL like "hostname" and "pathname")

While this is an issue in `update-check` module, it's a direct dependency (with a fixed version) and it prevents Next.js from running with these settings. 

Another suggestion, independent from what's being done inside `checkForUpdate`, it's to maybe add an option to skip this "check for updates".

**Comment by ghengeveld** [comment]
Ah I see, Next.js should bump its version of `update-check` 👍 
Maybe rename this issue to capture that notion.
PS Sorry if I came across too blunt.

**Comment by saschajullmann** [comment]
Btw this problem still exists. When I try to run next@6.0.3 I still get this error (only with regards to port 80 instead of the here mentioned 443).

The update-check module that got installed is "1.4.0".
