### ISSUE TITLE
Nextjs.org tutorial broken when moving away from a page with a quiz item.

### ISSUE THREAD

**Issue by vpicone** [zeit/next.js#4238]
- [X] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

Navigate to the next page without errors.

## Current Behavior

Taking a 'quiz' after reading through a lesson. I've already completed the quizes, but when I click "next" to leave the page I get an "An unexpected error has occurred." message and an error in the console.

"Error: StyleSheetRegistry: styleId: `jsx-1586328328` not found.
Stack trace"

## Steps to Reproduce (for bugs)

1. Having already completed the lessons (possibly a factor) go through the quizes
2. After hitting next on a page with a quiz, observe the error message in the browser and console.

## Context

Trying to review content, errors on every other page is a rough ux.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |    firefox developer     |
| etc     |         |

**Comment by vpicone** [comment]
`
Error: StyleSheetRegistry: styleId: `jsx-1586328328` not found.
Stack trace:
y@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:414098
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:412132
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:397915
a@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:212528
s@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:212668
c@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:213229
commitDeletion@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:215228
w@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:227275
_@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:226299
m@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:225821
g@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:225658
p@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:225032
c@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:224486
t@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:229997
updateContainer@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:230586
module.exports</Fi.prototype.render@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:245585
Zi@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:251330
render@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:251950
ee@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:352484
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:352097
h@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:354904
i@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:356874
E/</e[t]@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:355417
s@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82833
u@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82925
i/</<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82964
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:364113
i/<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82768
X@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:351412
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:350620
h@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:354904
i@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:356874
E/</e[t]@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:355417
s@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82833
u@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82925
i/</<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82964
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:364113
i/<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82768
Z@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:350353
e/<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:350090
e/<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:379954
module.exports</e.exports/</<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:383019
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:379908
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:377045
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:375144
h@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:354904
i@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:356874
E/</e[t]@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:355417
s@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82833
u@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82925
a@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:362949
R/<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:363106
c@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:366052
main-be6424f743e3dc90bf3c.js:1:212132
StyleSheetRegistry: styleId: `jsx-1586328328` not found.
y@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:414098
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:412132
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:397915
a@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:212528
s@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:212668
c@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:213229
commitDeletion@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:215228
w@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:227275
_@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:226299
m@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:225821
g@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:225658
p@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:225032
c@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:224486
t@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:229997
updateContainer@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:230586
module.exports</Fi.prototype.render@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:245585
Zi@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:251330
render@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:251950
ee@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:352484
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:352097
h@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:354904
i@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:356874
E/</e[t]@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:355417
s@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82833
u@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82925
i/</<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82964
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:364113
i/<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82768
X@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:351412
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:350620
h@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:354904
i@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:356874
E/</e[t]@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:355417
s@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82833
u@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82925
i/</<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82964
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:364113
i/<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82768
Z@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:350353
e/<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:350090
e/<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:379954
module.exports</e.exports/</<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:383019
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:379908
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:377045
e@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:375144
h@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:354904
i@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:356874
E/</e[t]@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:355417
s@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82833
u@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:82925
a@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:362949
R/<@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:363106
c@https://learnnextjs-zone.now.sh/_next/static/commons/main-be6424f743e3dc90bf3c.js:1:366052



    in t
    in div
    in e
    in t
    in WithData(t)
    in div
    in t
    in WithData(t)
    in div
    in div
    in div
    in t
    in e
    in WithData(e)
    in t
    in App
main-be6424f743e3dc90bf3c.js:1:351207
`

**Comment by timneutkens** [comment]
I just deployed a fix, can you try again?

**Comment by vpicone** [comment]
@timneutkens working perfectly. Thanks!

**Comment by vpicone** [comment]
@timneutkens working perfectly. Thanks!
