### ISSUE TITLE
StyleSheetRegistry: styleId: `jsx-739358267` not found

### ISSUE THREAD

**Issue by Richtervn** [zeit/next.js#4246]
That error happen everytime I changed style jsx. The styleId is not consistent . My pages are just simple withRedux

**Comment by timneutkens** [comment]
You probably have an empty `<style jsx>{``}</style>` somewhere, there is a known issue related to that.

**Comment by giuseppeg** [comment]
probably same issue as https://github.com/zeit/styled-jsx/issues/425

**Comment by timneutkens** [comment]
Yep, closing it here.

**Comment by williamli** [comment]
I got this error without an empty `<style jsx>{``}</style>`

**Comment by jacobhixon47** [comment]
I also get this error when changing any style attributes within the `<style jsx>` module.

I am using React with Webpack/Babel/HMR.

**Comment by williamli** [comment]
UPDATE: After upgrading to 6.0.1.canary.2 and 6.0.2, this error went away for me
