### ISSUE TITLE
Production size: requiring next.config.js forces to bundle dev dependencies

### ISSUE THREAD

**Issue by SBoudrias** [zeit/next.js#4248]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

This is an issue for v5, I didn't test v6 yet, but I believe from some other ticket that it is still happening (e.g. requiring call to `app.prepare()`)

## Expected Behavior

When shipping an app bundled for production, we shouldn't require development/build dependencies with the whole app.

## Current Behavior

Right now this is required because the server always tries to load `next.config.js` in production mode and the config decorator approach (`withSourceMaps = require('@zeit/next-source-maps')`) makes it inconvenient to exclude webpack plugins from production bundle.

## Context

Having small bundles helps save server and storage space - and is a requirement to run on serverless environment.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   5      |
| node    |     8    |
| OS      |     docker (ubuntu), serverless    |

**Comment by Vadorequest** [comment]
For the record, AWS Lambda allows only 50Mo of disk space, if the generated bundled zip is bigger than that, we can't deploy the function.

I've reached 30Mo on my last Next.js app and I'm particularly careful about this.

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js#custom-configuration

Specifically the part about `phase`: 

```
const {PHASE_DEVELOPMENT_SERVER, PHASE_PRODUCTION_BUILD} = require('next/constants')
module.exports = (phase, {defaultConfig}) => {
  if(phase === PHASE_DEVELOPMENT_SERVER || phase === PHASE_PRODUCTION_BUILD) {
	const withCSS = require('@zeit/next-css')
    return withCSS({
      /* development only config options here */
    })
  }

  return {
    /* config options for all phases except development here */
  }
}
```

**Comment by Enalmada** [comment]
@timneutkens Would it be appropriate for me to change the examples to use phases like this?  Is there any reason a new user would NOT want next-css not done like this?
