### ISSUE TITLE
Main JS commons chunk is not being cached

### ISSUE THREAD

**Issue by eweilow** [zeit/next.js#4250]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

I'm not entirely sure on the intended behaviour, but I expect all loaded JS to be cached. On my own site, as well as on at least https://nextjs.org/learn, the `/_next/static/commons/main-{hash}.js` file gets a `public, max-age=0` header.

## Current Behavior

I'd expect all JS to get some sort of cache header that does not set the max-age to 0, as this seem to require my browser to download the file on every page load.

## Steps to Reproduce (for bugs)

1. Open https://nextjs.org/learn with devtools
2. Look at the cache header on the `/_next/static/commons/main-{hash}.js` request

## Context

The result of not caching the `/_next/static/commons/main-{hash}.js` request results in waterfall requests. Even though etags can be applied, it seems that another round trip has to happen before code can be initialised.

After looking through the code, it seems that no static assets are being sent with cache headers by default - is this intended? I've checked a version of my own project running Next 5.1 and the main bundle (which is handled differently in that version) appear to be cached properly.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 6.0.0 |
| node    | 10 |
| OS      | N/A |
| browser | Chrome |
| etc     |         |

**Comment by roytan883** [comment]
check this may help you
https://github.com/zeit/next.js/issues/4321

**Comment by eweilow** [comment]
Closing as #4322 was merged
