### ISSUE TITLE
Can't use [chunkhash] for files

### ISSUE THREAD

**Issue by barrysteyn** [zeit/next.js#4255]
With next v6.0.0, there is a manifest plugin written by @timneutkens. It should allow one to alter the webpack filenames like this in `next.config.js`:

```
const withHashedOutput = (nextConfig = {}) => {
  return Object.assign({}, nextConfig, {
    webpack(config, options) {
      if (!options.defaultLoaders) {
        throw new Error(
          'This plugin is not compatible with Next.js versions below 5.0.0 https://err.sh/next-plugins/upgrade'
        );
      }

      console.log(config);
      config.output.filename = isProduction ? '[name][chunkhash]' : '[name]';

      if (typeof nextConfig.webpack === 'function') {
        return nextConfig.webpack(config, options);
      }

      return config;
    }
  });
};
const config = withHashedOutput({});
module.exports = config;
```

**NOTE**: I have overridden `_document.js`

## Expected Behavior
I would expect all file names to be hashed, and for next to have a proper mapping from the original file name to the hashed filename.

## Current Behavior
`_document.js` is excluded from this mapping, so things fail.

## Steps to Reproduce (for bugs)

 1. Alter `next.config.js` by using the code pasted at the start of this bug
 2. Note that files have hashes in them after this alteration (look in the .next folder)
 3. Next will crash since it can't find `_document`

I have a suspicion (although unconfirmed) that `_error` and `_app` will also suffer from this (if overridden).

**Comment by timneutkens** [comment]
Doing:

```
config.output.filename = isProduction ? '[name][chunkhash]' : '[name]';
```

Is currently not supported, since you're changing the output of *all* files, instead of specific ones you're generating. 

Adding hashes to page files is going to be up to us the future.

The pages-manifest.json wasn't added as a way to support , instead it was added as a way to speed up page resolving.

We don't ship this manifest to the client side, that's why pages can't be hashed like this.

**Comment by barrysteyn** [comment]
Hi Tim

Do you think this would be a nice feature? What is your estimated level of effort to get this going? If not incredibly high, I am thinking of implementing it myself?
