### ISSUE TITLE
with-jest example doesnt work

### ISSUE THREAD

**Issue by Popugune** [zeit/next.js#4263]
when i run test from npm scripts i have error

```
  C:\with-jest-app\jest.setup.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { configure } from 'enzyme';
                                                                                                    ^
    
    SyntaxError: Unexpected token {
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
```

| Tech    | Version |
|---------|---------|
| next    |   5.1.0      |
| node    |    10.0.0     |

**Comment by ikandars** [comment]
Same with me. But I can fixed that by doing these steps:

1. Install babel-plugin-transform-es2015-modules-commonjs

```
npm install --save-dev babel-plugin-transform-es2015-modules-commonjs
```

2. Added it to your `.babelrc` file

```
{
  "env":{
    "development": {},
    "production": {},
    "test": {
      "plugins": [
        ["transform-es2015-modules-commonjs"]
      ],
      "presets": [["next/babel", { "preset-env": { "modules": "commonjs" } }]]
    }
  }
}
```

Don't forget to adjust with your own `.babelrc` config, then run it again.

**Comment by Popugune** [comment]
@ikandars 
I replaced es6 imports to es5. And it all worked.
```
const enzyme = require('enzyme')
const Adapter = require('enzyme-adapter-react-16')

enzyme.configure({ adapter: new Adapter() })
```

**Comment by binarykitchen** [comment]
Well, I think it is still borken. `babel-preset-env` is missing. Complains with this infamous error:

"Couldn't find preset "env" relative to directory ..."

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js#customizing-babel-config read this.

**Comment by binarykitchen** [comment]
thanks but when it already works fine with `next build`, can't you make it work when using the `yarn test` command as well?

**Comment by binarykitchen** [comment]
and now seeing this error

```
    Plugin 0 specified in "/Users/mick/code/urban-signs/node_modules/next/babel.js" provided an invalid property of "default" (While processing preset: "/Users/mick/code/urban-signs/node_modules/next/babel.js")

      at Plugin.init (node_modules/babel-core/lib/transformation/plugin.js:131:13)
      at Function.normalisePlugin (node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
          at Array.map (<anonymous>)
      at Function.normalisePlugins (node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
```

**Comment by lydell** [comment]
@binarykitchen I also got that error and fixed it by adding `"babel-core": "7.0.0-bridge.0"` to package.json as shown here: https://github.com/zeit/next.js/blob/905da6f92bd36b48c5067f1f1525004777213e17/examples/with-jest/package.json#L5

**Comment by binarykitchen** [comment]
ugh, can't this be integrated in next/babel? i am pretty sure many others will have the same problem

**Comment by timneutkens** [comment]
Well not in next/babel, since next/babel is just a babel preset. but it's already part of the Next.js dependencies 🤔 https://github.com/zeit/next.js/blob/canary/package.json#L68

**Comment by binarykitchen** [comment]
@timneutkens ah good to know and then is that coming out?

**Comment by timneutkens** [comment]
I mean, that was part of 6.0.0 already.

**Comment by timneutkens** [comment]
It's also extremely hard to help anyone posting "it doesn't work in my app" or a random babel error without the actual `.babelrc` / next.config.js.

**Comment by binarykitchen** [comment]
fair enuff. here's more. 

.babelrc

```
{
  "presets": ["next/babel"],
  "plugins": []
}
```

test command

`NODE_ENV=test && jest`

dependencies in package.json

```
  "dependencies": {
    "compression": "^1.7.2",
    "express": "^4.16.3",
    "helmet": "^3.12.1",
    "material-ui": "^1.0.0-beta.47",
    "next": "^6.0.3",
    "pino": "^4.17.3",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-redux": "5.0.7",
    "redux": "4.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.3",
    "enzyme": "^3.3.0",
    "jest": "^23.0.0",
    "nodemon": "^1.17.5",
    "react-test-renderer": "^16.4.0",
    "redux-devtools-extension": "2.13.2"
  }
```

test code

```js
import { shallow } from 'enzyme'
import React from 'react'
import renderer from 'react-test-renderer'

import App from '../src/pages/index.js'

describe('With Enzyme', () => {
  it('App shows "Hello world!"', () => {
    const app = shallow(<App />)

    expect(app.find('p').text()).toEqual('Hello World!')
  })
})
```

the output again

```
└─❱❱❱ yarn test                                                                                                                                                                                    1 ⏎  +8799 17:17 ❰─┘
yarn run v1.7.0
$ NODE_ENV=test && jest
 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    Plugin 0 specified in "/Users/michael-heuberger/code/urban-signs/node_modules/next/babel.js" provided an invalid property of "default" (While processing preset: "/Users/michael-heuberger/code/urban-signs/node_modules/next/babel.js")

      at Plugin.init (node_modules/babel-core/lib/transformation/plugin.js:131:13)
      at Function.normalisePlugin (node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
          at Array.map (<anonymous>)
      at Function.normalisePlugins (node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.323s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tommypater** [comment]
I had the same problem when I wanted to upgrade with-jest, and with-jest-typescript. But with with-next-typescript I was able to solve that by putting

"jest": {
  "globals": {
   "ts-jest": {
    "useBabelrc": true
   }
  }
}

in package.json instead of jest.config.js
Example here: https://github.com/zeit/next.js/pull/4483/files

**Comment by timneutkens** [comment]
@binarykitchen you're not using the example 🤔 https://github.com/zeit/next.js/blob/canary/examples/with-jest/.babelrc
https://github.com/zeit/next.js/blob/canary/examples/with-jest/package.json#L5-L6

**Comment by tommypater** [comment]
Just upgrade the last exemple with-jest in fact :

Jest@latest, babel-jest@latest and enzyme@latest

package.json :

```
{
  "name": "with-jest",
  "version": "1.0.0",
  "dependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.0.1",
    "next": "6.0.3",
    "react": "16.2.0",
    "react-dom": "16.2.0"
  },
  "devDependencies": {
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "1.1.1",
    "jest": "^23.1.0",
    "react-addons-test-utils": "15.6.2",
    "react-test-renderer": "16.2.0"
  },
  "scripts": {
    "test": "NODE_ENV=test jest",
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
}
```

.babelrc :

```
{
  "env": {
    "development": {
      "presets": ["next/babel"]
    },
    "production": {
      "presets": ["next/babel"]
    },
    "test": {
      "presets": [["next/babel", { "preset-env": { "modules": "commonjs" } }]]
    }
  }
}
```

Error : 

```
> with-jest@1.0.0 test /mnt/c/Users/tommy/Work/git/lab/tests/nextjs/with-jest-app
> NODE_ENV=test jest

 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    Plugin 0 specified in "/mnt/c/Users/tommy/Work/git/lab/tests/nextjs/with-jest-app/node_modules/next/babel.js" provided an invalid
property of "default" (While processing preset: "/mnt/c/Users/tommy/Work/git/lab/tests/nextjs/with-jest-app/node_modules/next/babel.js")

      at Plugin.init (node_modules/jest-config/node_modules/babel-core/lib/transformation/plugin.js:131:13)
          at Array.map (<anonymous>)
          at Array.map (<anonymous>)
```

**Comment by tommypater** [comment]
397/5000
I do not know much about babel, but would it be because of a babel-jest update? With ts-jest it works.
A change like https://github.com/facebook/jest/commit/5d1babab7a5695026d3e9c31ba6ac1dd8fff2d73#diff-4d50022735c04444c3ed5901ee4b2208
You can read in the changelog "` [babel-jest] `[** BREAKING **] Always return object from transformer," next uses babel internally, so maybe ...

**Comment by binarykitchen** [comment]
@timneutkens nope, using the examples
https://github.com/zeit/next.js/blob/canary/examples/with-jest/.babelrc
https://github.com/zeit/next.js/blob/canary/examples/with-jest/package.json#L5-L6

still doesn't work for me. same error. and doesn't make sense why it's a dependency when babel-jest should be a dev dependency by the way.

yes, when i bump `babel-jest` then that error is gone but am seeing other new errors. maybe we should update the jest example to their latest packages and fix any wrong configs to make it work? cc @tommypater

**Comment by tommypater** [comment]
wtf...

@binarykitchen try to delete package-lock.json and node_module and "npm i".

I think it comes from bad management of the npm installations.

**Comment by binarykitchen** [comment]
ah now the tests pass.

but why did you put babel-core and babel-jest as a dependency when they should be under dev dependencies instead @tommypater ?

**Comment by binarykitchen** [comment]
and why wont the test work with the latest jest version 23?

**Comment by tommypater** [comment]
@binarykitchen i just retake the exemple of next.js quicky (i don't use jest without typescript). 23.1.0 is the lastest version, it was just to be more explicit. It's works now, no ? :)

**Comment by binarykitchen** [comment]
no, it doesn't work with jest v23 - possible to update the jest example to make it work with latest?

**Comment by Popugune** [comment]
@binarykitchen 

jest.setup

```
/* eslint-disable import/no-extraneous-dependencies */
const enzyme = require('enzyme');
const Adapter = require('enzyme-adapter-react-16');

enzyme.configure({ adapter: new Adapter() });
```
and babel-jest, jest ^23

it working in my project

**Comment by aganglada** [comment]
Not working for me with `"jest": "^23.1.0"`. Any news on this?

Thanks in advance!

**Comment by paulomfr** [comment]
Hello there! I added this following `.babelrc`
```json
{
  "env": {
    "development": {
      "presets": ["next/babel"]
    },
    "production": {
      "presets": ["next/babel"]
    },
    "test": {
      "presets": ["env", "react"]
    }
  }
}
```

and installed `yarn add --dev babel-jest babel-preset-env babel-preset-react`

Worked for me.

**Comment by MHwishes** [comment]
I use `yarn add --dev babel-jest babel-preset-env babel-preset-react` ,and fixed this issues

**Comment by webberwang** [comment]
how would we enable babel to use es6 instead of es5?

**Comment by Bijayini** [comment]
.babelrc


`{
  "presets": [
    ["next/babel"],
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "include": ["es6.map", "es6.set", "es6.object.assign"],
        "forceAllTransforms": true
      }
    ]
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"],
  "env": {
    "test": {
      "presets": ["@babel/env", "@babel/react"],
      "plugins": ["styled-jsx/babel-test", "dynamic-import-node"]
    }
  }
}`

Using Jest with enzyme. Getting the below error. Please help me.

  import React from "react";
           ^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript




Facing this issue after trying to fix IE11.  Please help me.
