### ISSUE TITLE
feature request: renderPage can pass props to App component directly

### ISSUE THREAD

**Issue by comus** [zeit/next.js#4269]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Current Behavior

currently `material-ui` use `renderPage` to pass `pageContext` to page Component
```js
// _documents.js
const page = ctx.renderPage(Page => props => (
      <Page pageContext={pageContext} {...props} />
  ));
```

so, **every page** components need to handle `pageContext`
```js
// pages/index.js
export default withRoot(Home) // <-- withRoot HOC handle pageContext
```

## Expected Behavior

but i really want '_app.js' handle withRoot or other HOC,
so **every page** components can be more simplier.

currently `_document.js` can use `renderPage` to  pass props to `Page Component` such as  'pageContext' above.
its for style ssr.

but `_document.js` can't send props to `App Component``_app.js`.
u only can modify `App` props by custom it `/page/_app.js`, and then generate App props by getInitialProps function.
https://github.com/zeit/next.js/blob/canary/server/render.js#L79-L88

but, again, `_document.js` can't send props to `_app.js` directly if i want to handle something about style ssr in _app.js, so that i don't need write those same code in every pages

may be Next.js would modify the renderPage function, may be add `appProps` below
```js
const renderPage = (enhancer = Page => Page, appProps) => {
    const app = createElement(App, {
      Component: enhancer(Component),
      router,
      ...props,
      ...appProps
    })
```

**Comment by joeporpeglia** [comment]
This is also making it impossible to use styled components ssr when you're using styled components in `_app.js`. I _think_ one solution that avoids breaking changes could involve some sort of `renderApp` hook that behaves the same as `renderPage`, but enhances the `_app.js` component instead.

**Comment by timneutkens** [comment]
There’s an open PR about where the enhancer in renderPage is used, it should wrap App now, but we’re still working out potential issues.

**Comment by scottdj92** [comment]
☝️ Is there a link to that PR? I'd like to take a look at it 😄

**Comment by comus** [comment]
https://github.com/zeit/next.js/pull/4762
