### ISSUE TITLE
Response size of HTML file is too large

### ISSUE THREAD

**Issue by narikei** [zeit/next.js#427]
I think next.js is a very good concept.
but, I tried running the `todo application` using next.js.

The size of this application is greater than 500KB.
Even though gzip is considered, it is difficult to use it for Production.
`__NEXT_DATA__` seems to be bloated.

example:
https://zeit.co/ 1.6 MB

**Comment by arunoda** [comment]
First of all `https://zeit.co` uses an older unpublished version of Next.js.

We have few things takes the size of the:

* commons.js - All of the common modules used in all your pages
* main.js - Runtime of Next.js
* __NEXT_DATA__ 
  - source code of the current viewing page
  - data you sent via `getInitialProps`

So one thing to look at the data you passed in the `getInitialProps`. That's something you can configure easily.

We've done a lot of optimization to the current master. (It's not available in NPM yet). So, the size you get is pretty decent. (I am not saying it's the smallest).

Here's a screenshot of current master and it's file sizes. (not gzipped)
(Make sure to run it in the production mode)

![screen shot 2016-12-19 at 9 18 44 am](https://cloud.githubusercontent.com/assets/50838/21300690/3a424834-c5cc-11e6-8e89-511e200ae3d0.png)

**Comment by narikei** [comment]
Thank you @arunoda. I'm looking forward!

**Comment by bbnnt** [comment]
same thoughts… a large html page will result in a large NEXT_DATA obviously. in the examples we see 2.0.0-beta, is that the one you referring to ?

**Comment by rauchg** [comment]
It's tradeoffs. If you want the React programming model, we have to ship the source of the component alongside the HTML. Otherwise, you can print out some HTML and ship code that doesn't know how to re-render completely, but only knows how to modify it (e.g.: the jQuery way). It's up to you to decide what model you prefer.

**Comment by rauchg** [comment]
That said, we're always looking for ways to ship lightweight stuff. The focus after 2.0 stable is not to add more features but to make everything faster and speedier 😉

**Comment by bbnnt** [comment]
ouch sorry just deleted it, overreacted over it did not expect such a quick rep.

treadeoffs yep, everyone can agree react's approach is what you want to adopt. quite struggled to get a decent ssr, then landed on next… *amazing*. but right now questioning myself about this specific part. it might bring soon the best of both world i guess

**Comment by rauchg** [comment]
The really cool thing is that for many applications where the user is interesting in consuming some data first (then acting on it), the server-rendered HTML+CSS does a great job _while_ the JS loads.

**Comment by pesho** [comment]
> It's tradeoffs. If you want the React programming model, we have to ship the source of the component alongside the HTML.

You don't have to ship it **inline** in the HTML. This is quite off-putting honestly. Include it as a static bundled .js file, yes. Don't serve it as part of `__NEXT_DATA__` which is generated dynamically on the server on each page load.

**Comment by jhurliman** [comment]
Should a separate issue be opened regarding shipping JS as a separate bundled.js file?

**Comment by plxel** [comment]
have same issue too
I got big js script in  html source when using [custom express server ](https://github.com/zeit/next.js/tree/v3-beta/examples/custom-server-express)
Without custom server, looks like there is no "component" property in `__NEXT_DATA__`

I think @pesho is right, there is no need to inline it in the HMTL

**Comment by mrdulin** [comment]
same issue.

The `html` from server contain `__NEXT_DATA__`, it's not good for performance and seo!!
