### ISSUE TITLE
development mode

### ISSUE THREAD

**Issue by bamaarintoko** [zeit/next.js#4272]
when i build next js on production, why react developer tool still detect my react in development build for react?
![deve](https://user-images.githubusercontent.com/28489752/39639327-203c300a-4ff3-11e8-91aa-941c181797bf.PNG)

| Tech    | Version |
|---------|---------|
| next    |     ^5.1.0    |
| node    |    v8.9.0     |
| OS      |     windows    |
| browser |   chrome      |
| etc     |         |

**Comment by bamaarintoko** [comment]
@lfades yes, i already set to production

**Comment by bamaarintoko** [comment]
@lfades 
![f](https://user-images.githubusercontent.com/28489752/39659592-e1714d16-5055-11e8-9fff-638f8b02885a.PNG)

**Comment by lfades** [comment]
@bamaarintoko React is not included in your execution of `server.js` but in `next build`, set the env in the same way for `next build` (I think it should be done by default but this way we make sure `NODE_ENV` is 
`production` for the build)

**Comment by bamaarintoko** [comment]
ok i will try

**Comment by timneutkens** [comment]
Please provide a minimal reproduction based on the issue template 👍🏻

**Comment by bamaarintoko** [comment]
ok its work now, but my custom route now dont work, always routing to home :(
