### ISSUE TITLE
StyleSheetRegistry: styleId not found. Next 6.0

### ISSUE THREAD

**Issue by Richtervn** [zeit/next.js#4273]
I'm using next 6.0. I'm having this problem with style jsx. It say styleId not found everytime I changed style.

I have folder called 'themes' under src folder which is same level with pages folder.
I use a custom .babelrc to have it resolved as absolute path.

**Here is my .babelrc**
`
{
  "presets": ["next/babel"],
  "plugins": [
    ["module-resolver", {
      "root": ["./src"], 
      alias: {
        "data": "./src/data",
        "modules": "./src/modules",
        "store": "./src/store",
        "themes": "./src/themes",
        "utils": "./src//utils",
        "svgs": "./svgs"
      }
    }],
    ["inline-react-svg"]
  ]
}
`

**When I write new component I did something like:**

`
import {color, fontSize} from 'themes';
export default () => (<div><style jsx> div { color: ${color.green}  } </style></div>)
`
And I'm using withRedux to wrap my page.
I'm using classnames too.

It happen on next 6.0 not 5.x.

**Comment by timneutkens** [comment]
I've opened a pull request with a fix + test so that it doesn't happen again.
