### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by bamaarintoko** [zeit/next.js#4274]
how to fix this issue in production mode?

![zxc](https://user-images.githubusercontent.com/28489752/39661056-c3b79422-5075-11e8-8334-da7ed9b43dc4.PNG)

| Tech    | Version |
|---------|---------|
| next    |    ^5.1.0     |
| node    |     v8.9.0    |
| OS      |    windows     |
| browser |     chrome    |
| etc     |         |

**Comment by timneutkens** [comment]
Please follow the issue template and provide a reproduction.

**Comment by pozylon** [comment]
This seems like related to those tickets:
- https://github.com/zeit/next.js/issues/4306
- https://github.com/Semantic-Org/Semantic-UI-React/issues/2721

I also get this problem with Upgrading to React Semantic UI 0.8 together with Next 6.0.2.
