### ISSUE TITLE
Use `babel.config.js` instead of `.babelrc`

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#4275]
`babel@7.0.0-beta.46` uses `babel.config.js` for global config. See https://github.com/babel/babel/pull/7358.

`next@6.0.0` uses `.babelrc`.

```
> Using external babel configuration
> Location: "/app/.babelrc"
```

I assume this is because `next@6.0.0` uses `babel@7.0.0-beta.42` and not the latest yet.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

**Comment by vjpr** [comment]
Forgot that I am working in a lerna monorepo and that `babel.config.js` is mostly relevant to monorepos, so `.babelrc` still makes sense for a basic Next project.

**Comment by skyrpex** [comment]
I just pass by to say that I struggled for this some hours xD Is babel7 documented somewhere?

**Comment by steelbrain** [comment]
@skyrpex and for future visitors from Google search See https://babeljs.io/docs/en/next/babelconfigjs

**Comment by wildeyes** [comment]
> Forgot that I am working in a lerna monorepo and that `babel.config.js` is mostly relevant to monorepos, so `.babelrc` still makes sense for a basic Next project.

what difference does it make between a basic project and a lerna one?
