### ISSUE TITLE
update-check throws error when using node 6.14.0

### ISSUE THREAD

**Issue by MartinReiche** [zeit/next.js#4279]
I am developing a nextjs app that runs on google cloud functions. Cloud functions requires node v.6.14.0 and the local function emulator needs v.6.14.0 as well. Since I upgraded to next 6, I am getting the following error when running the next dev server:

```
/project/node_modules/update-check/index.js:18
const getFile = async (details, distTag) => {
                      ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Server._callee$ (/project/node_modules/next/dist/server/index.js:194:34)
 ...

```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

This is related to #4258, but this has been closed because they could resolve the issue by updating the node version. However, I would like to keep the node version at v6.14 because I would like to keep my dev environment as close as possible to google cloud functions.

## Expected Behavior
Should work as expected, like in next v5.

## Current Behavior
Throws the error described above and does not start up the dev server.

## Steps to Reproduce (for bugs)

1. Use Node v.6.14.0
2. Install Dependencies
3. run next

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  6.0.0       |
| node    | 6.14.0        |
| OS      |   Arch Linux      |
| browser |  Chrome       |

**Comment by pan100** [comment]
Hi. I searched some more and addressed the syntax error. I found some information that might be valuable if the solution is to use babel and transform the code. I have not tried this myself but I do believe the code can be transpiled. https://stackoverflow.com/questions/42299393/using-async-await-in-node-6-with-babel

**Comment by uuau99999** [comment]
I occurred the same problem in node 6.12.2
