### ISSUE TITLE
Question: Recommended approach for importing npm modules to client?

### ISSUE THREAD

**Issue by danielbh** [zeit/next.js#428]
Hello, what is the recommended approach for importing npm modules to client?

Thanks for any guidance you could offer.

**Comment by bhurlow** [comment]
The js files you put in the `pages` directory are executed on both the server and the client. Thus, code written in vanilla js which doesn't rely on either browser or node.js specific APIs can run in both contexts.

You should be able to use many browser specific npm modules out of the box directly:

```
import React from 'react'
import ReactDOM from 'react-dom'
import GoogleLogin from 'react-google-login'

let handler = (e) => {
  // do something
}

export default () => (
  <GoogleLogin
    clientId="xxx"
    buttonText="Login"
    onSuccess={handler}
  />
)
```

**Comment by danielbh** [comment]
The library in question does rely on browser context. Window object.

Sent from my iPhone

On 19 Dec 2016, at 09:35, Brian Hurlow <notifications@github.com<mailto:notifications@github.com>> wrote:


The js files you put in the pages directory are executed on both the server and the client. Thus, code written in vanilla js which doesn't rely on either browser or node.js specific APIs can run in both contexts.

You should be able to use many browser specific npm modules out of the box directly:

import React from 'react'
import ReactDOM from 'react-dom'
import GoogleLogin from 'react-google-login'

let handler = (e) => {
  // do something
}

export default () => (
  <GoogleLogin
    clientId="xxx"
    buttonText="Login"
    onSuccess={handler}
  />
)


-

**Comment by bhurlow** [comment]
@danielbh it appears you're already using next.js the recommended way: https://github.com/danielbh/danielhollcraft.com/blob/master/components/background/index.js#L6-L14. Is that causing issues? `componentDidMount` should only be invoked in the browser

**Comment by bhurlow** [comment]
when in doubt you can always use `getInitialProps` to detect if a page is being rendered server-side or client side. `getInitialProps` is passed the https `req` object only when on server

**Comment by danielbh** [comment]
This works. But I prefer to have my dependencies centralized in npm. I consider the current way not so nice.

**Comment by bhurlow** [comment]
You can also, though not the most elegant way, detect for the `window` global directly

**Comment by danielbh** [comment]
Someone suggested this is an issue with Particles JS (the library), not next.js would you agree?

**Comment by bhurlow** [comment]
@danielbh let's move this convo over to your repo instead of `next.js`
