### ISSUE TITLE
css file will not update even when rebuild

### ISSUE THREAD

**Issue by sydneywu** [zeit/next.js#4282]
This is a very perplexing issue for me. For some reason, I am trying to change my css style but next will keep building my previous style. Even after I deleted .next folder and rebuild by "npm run build". The previous css style will still be loaded. 

Briefly my code is like this.

**Component**
`
import articlePostStyle from '../css/articlePost.css'

class ArticlePost extends React.Component {

    render() {
        return (
            <div>
                <style jsx global>{articlePostStyle}</style>
                {this.props.article.articlePost.content && (
                    <div className="article-content" dangerouslySetInnerHTML={{__html:this.props.article.articlePost.content}} />
                )}
            </div>

        )
    }
`
**css**
`
.article-content{
    background-color: blue;
}
`

This works fine and show my div as blue. But now when i change it to background-color: white; it is still rendered as blue. I tried to stop the server and rebuild "npm run build" (next build), it will still be blue. This is not internet cache, what i mean is that the .next folder it will have this.

**/.next/bundles/bundles/pages/post.js**
`
/* babel-plugin-inline-import '../css/articlePost.css' */var articlePostStyle = '.article-content{\r\n    background-color: blue;\r\n}
`
**/.next/dist/components/ArticlePost**
`
/* babel-plugin-inline-import '../css/articlePost.css' */var articlePostStyle = '.article-content{\r\n    background-color: blue;\r\n}
`

What is perplexing is that even when i deleted .next folder and search my entire project to see that there is no reference of "background-color: blue", after I build it, the blue color will still come back. It's like there is some cache in the system that remembers the code in the css. 

The only time where i can successfully update "background-color: white" is to delete the css file and intentionally let next throw a red error screen. Thereafter, the .next folder will update "background-color: white"

My Env
| Tech    | Version |
|---------|---------|
| next    |  2.1.1       |
| node    |     8.9.4    |
| OS      | Windows        |
| browser |  Chrome       |
| etc     |         |

**Comment by maxdyy** [comment]
Experiencing same issue here. Did you manage to solve it?

**Comment by maxdyy** [comment]
Solved moving all the custom css to static folder

**Comment by jjperezaguinaga** [comment]
I've faced this issue before with `svg` files btw. Ended up changing the name of the files, if it's any help to pin point the real issue or as a temporal workaround.

**Comment by timneutkens** [comment]
Assuming this issue was already fixed in Next 7.x, as it's not following the issue template / doesn't have a clear reproduction I'm going to close it.
