### ISSUE TITLE
 'url' property is deprecated - question

### ISSUE THREAD

**Issue by mandriv** [zeit/next.js#4284]
I am using `withRouter` HoC as described in this [snippet](https://github.com/zeit/next.js/blob/master/errors/url-deprecated.md), however, I am still getting the error:
```
 utils.js:26 Warning: the 'url' property is deprecated. https://err.sh/next.js/url-deprecated
```

- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

Code executes without the deprecation warning.

## Current Behavior

The error mentioned above appears.

## Steps to Reproduce (for bugs)

1. Import `withRouter` to your component
2. Refer any field from `this.props.router`
3. Export your component wrapped in `withRouter` HoC
4. When component is rendered, the deprecation error appears in console

## Context

I am implementing Navigation component that is aware of the current route (to highlight the NavItem).

## Your Environment

| Tech    | Version |
|-------|-------|
| next    | 6.0.0  |
| node   | 9.11.1 |
| OS      | OSX 10.13.4 |
| browser | Chrome Version 66.0.3359.139 |

**Comment by kv9991** [comment]
If you check the source of basic App component (https://github.com/zeit/next.js/blob/30b0e36c7134ea4eb711c95f61cc773354348f09/lib/app.js), you'll see how it works. So the answer is to create your own App component like it described in README of next.js

**Comment by hugotox** [comment]
I do not have a custom App component and I still get the warning. I do have a custom _document with the contents described here https://github.com/zeit/next.js#custom-document
Any ideas how to get rid of that warning?

**Comment by mandriv** [comment]
@hugotox you simoly need to create a custom _app.js(x)

**Comment by roopemerikukka** [comment]
I think this should be told in the readme because now it just states that "[Each top-level component receives a url property](https://github.com/zeit/next.js/blame/canary/readme.md#L370)..."

Maybe there should be a note of the special case when using custom App component?

**Comment by hopperhuang** [comment]
continously focus on this issue

**Comment by ryanfitzer** [comment]
While some of my page components rely on `this.props.url`, this isn't what is triggering the warning. One of my child components triggers the warning with `JSON.stringify( this.props )`.

**Comment by scaasic** [comment]
I'm using a pretty standard configuration (no custom App, no attempt to ever reference `url`) and I get this warning. I don't think we should be forced into using a custom `_app.js` just to get rid of this.

**Comment by timneutkens** [comment]
@remy mentioned it's possible that React devtools triggers the url property read that causes the warning to show

**Comment by scaasic** [comment]
@timneutkens Yep, that appears to be the issue in my setup. Should we update the error docs to reflect this?

**Comment by timneutkens** [comment]
I've removed the suggestions in this thread saying you should create a custom `_app.js` that passes in the url property globally, as the reason we removed it is to be more explicit and not pass in `url` as a property, but instead you can inject the `router` using `withRouter()` as per the deprecation. We will provide a codemod soon to update `url` in pages to the `withRouter()` implementation automatically.

**Comment by timneutkens** [comment]
I just open sourced the codemod we used to upgrade 35K+ lines of code from `url` to `withRouter`:

https://github.com/zeit/next-codemod#url-to-withrouter

@scaasic regarding documenting the React devtools property read, sure feel free to send a pull request. We always welcome documentation improvements 😌

**Comment by timneutkens** [comment]
After re-visiting this issue it seems like there's nothing wrong. Only React Devtools making it log out the warning, unfortunately, we can't get around that. @scaasic has created a pull request that adds a message saying react devtools can cause the warning to show up.

**Comment by SergioJrDev** [comment]
I was getting this warning message when I accessed the property `query` in `this.props.url`, in some page with query param url, like `post?id=22`, even by console when I printed `this.props`.

I got fix it using `withRouter` from `next/router` and accessing `query` from `this.props.router`.

```js
import { withRouter } from "next/router";

class Single extends Component {
  componentDidMount = () => {
    const { router: { query: { id } }} = this.props;
    console.log(id);
  };
}

export default withRouter(Single);

```
