### ISSUE TITLE
Module build failed after upgraded to v6 with "_document.js"

### ISSUE THREAD

**Issue by wellyshen** [zeit/next.js#4291]
I'm trying to upgrade from v5 to v6. And I encountered a build error which caused from the `_document.js` as the following screenshot. Once I remove the `_document.js` the error was gone. In additional even that I used the [example](https://github.com/zeit/next.js#custom-document) the error still occurs.

<img width="997" alt="2018-05-07 5 37 10" src="https://user-images.githubusercontent.com/21308003/39695649-ec3203e8-521d-11e8-8383-1700a387a2ec.png">

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
- Upgraded to v6 and build success with `_document.js`.

## Current Behavior
- Upgraded to v6 but build failed with `_document.js`.

## Steps to Reproduce (for bugs)
1. Upgraded to v6 via [this](https://github.com/zeit/next.js/issues/4239#issuecomment-385691474) instruction. 
2. Run `yarn dev` and build success.
3. But build failed due to `Module build failed: ReferenceError: Unknown helper getPrototypeOf` which caused from `_document.js`.

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |   v6   |
| node    |  v9.11.1   |
| OS      |    MacOS   |
| browser |  Google Chrome  |

**Comment by timneutkens** [comment]
It's impossible to reproduce without any code samples. Please provide a full reproduction repository 👍

**Comment by srascar** [comment]
@wellyshen , you might be missing some of the babel plugins.
can you try to add ?

```
"plugins": [
      "@babel/plugin-transform-runtime"
    ]
```

Hope it will help

**Comment by zspencer** [comment]
Thanks @srascar, adding that resolved the build failure.
