### ISSUE TITLE
Server side _app.js

### ISSUE THREAD

**Issue by elrumordelaluz** [zeit/next.js#4292]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

Get initial `props` using a HOC in `_app.js` same as when using directly in all _pages_

## Current Behavior

Using custom `_app.js` works only client-side

## Steps to Reproduce (for bugs)

1. Fork/install [with-apollo example](https://github.com/zeit/next.js/tree/canary/examples/with-apollo)
2. Create a _custom_ `_app.js` like [here](https://github.com/zeit/next.js#custom-app)
3. Import and Wrap the default exported _Component_ of `_app.js` with [withData](https://github.com/zeit/next.js/blob/canary/examples/with-apollo/lib/withData.js) :: [see below](#code-snippet-_app)
4. Unwrap the default exported Component from [Index page](https://github.com/zeit/next.js/blob/canary/examples/with-apollo/pages/index.js#L7) :: [see below](#code-snippet-index)

## Context

When the `withData` _HOC_ wraps each _Page_, the _GraphQL_ data fetched is available _server-side_ like: 

![withData wrapping each page](https://user-images.githubusercontent.com/784056/39698251-67931736-51f4-11e8-871f-986c884360d0.png)

instead wrapping the _custom_ `_app.js` is only available _client-side_, like: 

![withData wrapping custom _app](https://user-images.githubusercontent.com/784056/39698280-8f6f1566-51f4-11e8-933b-f1bd78bebec8.png)

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  6.0.0|
| node    | v8.11.0 |
| OS      | OSX 10.11.6 |
| browser | |
| etc     |         |

### Code Snippet _app
```js
import App, { Container } from 'next/app'
import React from 'react'
import withData from '../lib/withData'

class MyApp extends App {
  static async getInitialProps({ Component, router, ctx }) {
    let pageProps = {}

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }

    return { pageProps }
  }

  render() {
    const { Component, pageProps } = this.props
    return (
      <Container>
        <Component {...pageProps} />
      </Container>
    )
  }
}

export default withData(MyApp)
```

### Code Snippet Index
```js
import App from '../components/App'
import Header from '../components/Header'
import Submit from '../components/Submit'
import PostList from '../components/PostList'

export default () => (
  <App>
    <Header />
    <Submit />
    <PostList />
  </App>
)

```

**Comment by elrumordelaluz** [comment]
repo https://github.com/elrumordelaluz/next-with-apollo-custom-app

**Comment by timneutkens** [comment]
See https://github.com/zeit/next.js/pull/4286

**Comment by elrumordelaluz** [comment]
cool, thank you @timneutkens !
