### ISSUE TITLE
with-firebase-hosting example is not working with Next 6

### ISSUE THREAD

**Issue by bennygenel** [zeit/next.js#4293]
[with-firebase-hosting](https://github.com/zeit/next.js/tree/master/examples/with-firebase-hosting) example is giving error when upgrading Next to version 6. I tried it with `v6.0.0` and` 6.0.1-canary.1`. Problem occurs when running `deploy` command.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
Project should deploy succesfully

## Current Behavior
It gives the error below

```
C:\projects\with-firebase-hosting>yarn deploy
yarn run v1.6.0
warning package.json: No license field
$ firebase deploy

=== Deploying to '****-app'...

i  deploying functions, hosting
Running command: npm run build-funcs && npm run build-app && npm run copy-deps && npm run install-deps

> with-firebase-hosting@3.0.0 build-funcs C:\projects\with-firebase-hosting
> babel "src/functions" --out-dir "dist/functions"

Error: Error: Cannot find module 'babel-preset-env' from 'C:\projects\with-firebase-hosting\src\functions'
- Did you mean "@babel/env"?
    at C:\projects\with-firebase-hosting\node_modules\@babel\cli\lib\babel\dir.js:185:22
    at C:\projects\with-firebase-hosting\node_modules\@babel\cli\lib\babel\dir.js:148:23
    at C:\projects\with-firebase-hosting\node_modules\@babel\cli\lib\babel\dir.js:120:23
    at C:\projects\with-firebase-hosting\node_modules\@babel\cli\lib\babel\dir.js:82:23
    at C:\projects\with-firebase-hosting\node_modules\@babel\cli\lib\babel\util.js:126:16
    at C:\projects\with-firebase-hosting\node_modules\@babel\core\lib\transform-file.js:49:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
```

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  6.0.0   & 6.0.1-canary.1    |
| node    |  8.11.1       |
| OS      |  Windows 10     |

**Comment by Grimones** [comment]
The is related to `.babelrc` wrong configuration.

At the moment `.babelrc` wants an `env` preset, a `"babel-preset-env"`
In `package,json` is installed `"@babel/preset-env": "^7.0.0-beta.40"` which means, that in `.babelrc` should be listed `@babel/env` preset. 

However, it works because `nextjs 5.1.0` has 
https://github.com/zeit/next.js/blob/e3a9c9502332371b9dbf2483297964b55f110087/package.json#L67
and babel takes that preset

But `nextjs 6.0.0` has
https://github.com/zeit/next.js/blob/7e3d46491285dabf62714f933720043251493e17/package.json#L62

that is why it fails.

To fix this `.babelrc` should have listed `"@babel/env"` in presets
I'll open a PR

**Comment by bennygenel** [comment]
@jthegedus I'm having problem with [with-firebase-hosting](https://github.com/zeit/next.js/tree/canary/examples/with-firebase-hosting) example again.

I copied the example directory, installed dependencies and set the project id. Then when I deploy I get the following error.

```
PS C:\stacktest\netoptik\with-firebase-hosting> npm run deploy

> with-firebase-hosting@4.0.1 predeploy C:\stacktest\netoptik\with-firebase-hosting
> npm run build-public && npm run build-funcs && npm run build-app && npm run copy-deps


> with-firebase-hosting@4.0.1 build-public C:\stacktest\netoptik\with-firebase-hosting
> cpx "src/public/**/*.*" "dist/public" -C


> with-firebase-hosting@4.0.1 build-funcs C:\stacktest\netoptik\with-firebase-hosting
> babel "src/functions" --out-dir "dist/functions"

ReferenceError: Unknown option: .configFile. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    at buildUnknownError (C:\stacktest\netoptik\with-firebase-hosting\node_modules\@babel\core\lib\config\validation\options.js:98:11)
    at C:\stacktest\netoptik\with-firebase-hosting\node_modules\@babel\core\lib\config\validation\options.js:84:57
    at Array.forEach (<anonymous>)
    at validate (C:\stacktest\netoptik\with-firebase-hosting\node_modules\@babel\core\lib\config\validation\options.js:62:21)
    at loadPrivatePartialConfig (C:\stacktest\netoptik\with-firebase-hosting\node_modules\@babel\core\lib\config\partial.js:28:48)
    at loadFullConfig (C:\stacktest\netoptik\with-firebase-hosting\node_modules\@babel\core\lib\config\full.js:33:37)
    at C:\stacktest\netoptik\with-firebase-hosting\node_modules\@babel\core\lib\transform-file.js:36:33
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
```

I tried to update all the dependencies to the latest versions and got the same error. I'm not sure what is the cause of the problem since I didn't change anything with the project.

I'll appreciate if you help me again.


|   	|   	|
|---	|---	|
| Node  	|   v8.11.3	|
| Npm  	|  v5.6.0  	|
| Next 	|   v6.1.1	|
| OS 	|  Windows 10 	|
