### ISSUE TITLE
What is the equivalent of browserHistory.push(path) for client redirect without next/link?

### ISSUE THREAD

**Issue by Ajar-Ajar** [zeit/next.js#430]
Sometimes you want to redirect grammatically after user interaction / redux action fired.
What is the equivalent of ` browserHistory.push(path) `  to allow client-side redirects without using the naxt/link component?

**Comment by arunoda** [comment]
We've a new PR for this: https://github.com/zeit/next.js/pull/429 :) 

For now check this: https://github.com/zeit/next.js#routing
(At the end, you'll see how to get access to the router and use it)

**Comment by Ajar-Ajar** [comment]
@arunoda The PR is exactly what I mean, I hope it will be merged promptly.
As for getting access to the router currently - I have checked the routing part of the readme and wasn't able to locate the way to access it. Would you be so kind and be more specific?
Thank you!
Ajar
