### ISSUE TITLE
`externalBabelConfig` can never be loaded because of `babelrc` check in `babel@7.0.0-beta.46`

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#4301]
https://github.com/zeit/next.js/blob/737f6cfce0cd89c2ee487b9b2e48f03624dc630b/server/build/webpack.js#L43-L62

If I add `babelrc: true` to my Babel config I get this error: 

```
Error: .babelrc is only allowed in root programmatic options
```

NOTE: This is with `@babel/core@7.0.0-beta.46`. Prob related to changes in 46 for config handling.

Maybe its related to the fact that I am using `babel.config.js`...

**Comment by loganfsmyth** [comment]
`next` support for Babel 7 landed before the PR for `babel.config.js` so Next just needs to be updated to support it.
