### ISSUE TITLE
fs in _document.js

### ISSUE THREAD

**Issue by SiwakornS** [zeit/next.js#4305]
[x] I have searched the issues of this repository and believe that this is not a duplicate.

I try to use fs in _document.js, developement & build process is success, but when I tried to run in production mode.  I got the message. 

```Error: EBADF: bad file descriptor, fstat```

My understand. _document.js can use on _document.js because it only runs on server-side only right?

What else, I need to config 

## My Environment

| Tech    | Version |
|---------|---------|
| next    |    5.1     |
| node    |   8.9.3      |
| OS      |    OSX    |
| browser |    Chrome     |

**Comment by Iliyass** [comment]
first this read is important https://arunoda.me/blog/ssr-and-server-only-modules.
I think you have to import using (any method in the above article) in `getInitialProps` because it's the only function that runs on the server.

**Comment by timneutkens** [comment]
_document is actually only rendered on the server. 

It sounds like something specific to your filesystem. https://stackoverflow.com/questions/16604176/error-ebadf-bad-file-descriptor-when-running-node-using-nohup-of-forever

**Comment by SiwakornS** [comment]
Many thanks. I solve the problem

**Comment by comus** [comment]
@timneutkens 

    _document is actually only rendered on the server.

but i really tried it, just import fs, below both not work, i remember it works before next@6
```js
import fs from 'fs' // <--- here
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps }
  }

  render() {
    return (
      <html>
        <Head>
          <style>{`body { margin: 0 } /* custom! */`}</style>
        </Head>
        <body className="custom_class">
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

```js
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    if (!process.browser) { // <-- here
      const fs = require('fs')
      console.log(fs)
    }
    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps }
  }

  render() {
    return (
      <html>
        <Head>
          <style>{`body { margin: 0 } /* custom! */`}</style>
        </Head>
        <body className="custom_class">
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

both show error message in terminal
```
This dependency was not found:

* fs in ./pages/_document.js

To install it, you can run: npm install --save fs
```

**Comment by comus** [comment]
oh, sorry, seems like next.config.js must add fs: empty for import fs, not sure how it works
```
module.exports = {
  webpack: function (config, { isServer }) {
    config.node = {
      fs: 'empty'
    }
    return config
  }
}

```

**Comment by timneutkens** [comment]
@comus in development we do bundle it for the client side, the reason for this is hot reloading on _document.js
