### ISSUE TITLE
Cannot read property 'call' of undefined using react-popper

### ISSUE THREAD

**Issue by Iliyass** [zeit/next.js#4306]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

First let me thank you guys for this wonderful library, I know the effort you are putting here. thanks

## Expected Behavior

I'm using [`react-popper`](https://github.com/FezVrasta/react-popper) library for tooltips positioning.
it works in dev env, and it should work in prod env using `next build` command.

## Current Behavior

it breaks in build mode when importing the above library

## Steps to Reproduce (for bugs)

1. `yarn add react-popper`
2. integrate the sample code from the readme 
3. `yarn run build` alias for `next build`

## Context

I want to use `react-popper` for tooltip positioning 
## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 5.1.0 |
| node    | v8.5.0  |
| OS      | macOS High Sierra v10.13.4 (17E199)  |
| browser |   Chrome Version 66    |

**Comment by timneutkens** [comment]
It's probably something related to how webpack bundles this module.

**Comment by Iliyass** [comment]
@timneutkens can you elaborate more, how can I debug more on the webpack bundling side ?
