### ISSUE TITLE
Is it possible to use postcss with Next.js?

### ISSUE THREAD

**Issue by Ajar-Ajar** [zeit/next.js#431]
I know Next.js is opinionated using Glamor, and I can use it for most things but many PostCSS plugins like rucksack for responsive font-size and px-to-rem among others are indispensable...
Is there a way to create a workflow that will allow to use postcss on top? Is there a way to add postcss configuration to the underlying webpack config? and what will it mean? that we'll need to give up using Glamor alltogether?

**Comment by rauchg** [comment]
We'll make all CSS engines completely optional. Stay tuned for the 2.0 announcement.

**Comment by Ajar-Ajar** [comment]
That is GREAT news!!! any assumption on the announcement date more or less?
Even if it is vague it would help to know if it is a matter of weeks or months...
We have a production project and we're evaluating... I'm sure you can understand...

**Comment by rauchg** [comment]
Days!

**Comment by Ajar-Ajar** [comment]
YES!!!
:)

**Comment by bkniffler** [comment]
Any news on this?

**Comment by arunoda** [comment]
@bkniffler unfortunately we can't support it 100% with 2.x 
See: https://github.com/zeit/next.js/issues/627#issuecomment-270039476
