### ISSUE TITLE
next-sass: Custom Server routing doesn't automatically compile styles for css modules

### ISSUE THREAD

**Issue by Kyle-Mendes** [zeit/next.js#4313]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

When using a custom server, routing to a page should automatically bundle the styles of all included components.

## Current Behavior

That is not the case.  You will need to hard refresh the page to get the styles to be built.

## Steps to Reproduce (for bugs)

1. Clone https://github.com/Kyle-Mendes/next-sass-modules/tree/custom-server (make sure you're on the `custom-server` branch
2. Run `yarn dev`
3. visit `localhost:3000`
4. Click "Test Page"
5. **Observe**:  The `Headline` component is not styled.
6. Refresh the page
7. **Observe**: The `Headline` component is styled.

### NOTE:
Sometimes, even doing a hard reload results in `Headline` not being styled.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  6.0       |
| node    |      9.11.1   |
| OS      |   Mac OS      |
| browser |    Chrome     |

**Comment by vanshady** [comment]
My project sometimes has the same behavior

**Comment by timneutkens** [comment]
This is unrelated to next and should be filed under next-plugins
