### ISSUE TITLE
Link tag with prefetch attempts fetch at the wrong address if the project's index is not the domain root 

### ISSUE THREAD

**Issue by ewagstaff** [zeit/next.js#4330]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

My index.html file is at this URL: `mydomain.com/test-proj/test-slug/`

When I put a prefetch attribute on my Link tag, like this:
```
<Link prefetch href={`${publicRuntimeConfig.ASSET_PATH}/about`}>
	<a>About this project</a>
</Link>
```

It should prefetch the code at this address: `mydomain.com/test-proj/test-slug/_next/8a75d7ea-0f56-4f5e-880e-5ca422462521/page/about.js`

## Current Behavior

Instead, prefetch attempts to fetch the code at this address: `mydomain.com/test-proj/test-slug/_next/8a75d7ea-0f56-4f5e-880e-5ca422462521/page/test-proj/test-slug/about.js`

If the link looks like this instead, the prefetch works properly, but the actual link goes to `mydomain.com/about` which 404s on refresh.

```
<Link prefetch href={`/about`}>
	<a>About this project</a>
</Link>
```

## Steps to Reproduce (for bugs)

1. Create a project hosted on a non-root domain path.
2. Create a link to a page with a prefetch attribute.
3. See that the prefetch fails when the link has its asset path provided.

## Context

I would like to prefetch content, but can't until this is resolved.

## Your Environment

This bug was observed using Chrome on Mac OS Sierra.

**Comment by ewagstaff** [comment]
It looks like I could potentially use this imperative API to route to one place and prefetch from another. Please let me know if that's my only option in this circumstance.

```
import Router from 'next/router'

export default ({ url }) =>
  <div>
    <a onClick={() => setTimeout(() => url.pushTo({`${publicRuntimeConfig.ASSET_PATH}/dynamic`}), 100)}>
      A route transition will happen after 100ms
    </a>
    {// but we can prefetch it!
    Router.prefetch('/dynamic')}
  </div>
```

**Comment by fiveanddone** [comment]
Just ran into this same problem today.  @ewagstaff Did you ever find a different solution?

**Comment by ewagstaff** [comment]
Nope, custom implementation is the only fix I’m aware of. Please update if there’s a new work around!

**Comment by timneutkens** [comment]
The current behavior is actually expected, as Next.js doesn't have a basePath your directory structure / href has to match the url including any prefixes. There's an issue tracking changing that here: #4998
