### ISSUE TITLE
Npm install next fails

### ISSUE THREAD

**Issue by geekyme** [zeit/next.js#4336]
`npm install next` fails with the following error:

```
➜ npm install --save next
npm ERR! code E404
npm ERR! 404 Not Found: @babel/helper-module-imports@7.0.0-beta.42
```

I tried to show the versions of the above module
```
➜ npm show @babel/helper-module-imports versions

[ '7.0.0-beta.4',
  '7.0.0-beta.5',
  '7.0.0-beta.31',
  '7.0.0-beta.32',
  '7.0.0-beta.33',
  '7.0.0-beta.34',
  '7.0.0-beta.35',
  '7.0.0-beta.36',
  '7.0.0-beta.37',
  '7.0.0-beta.38',
  '7.0.0-beta.39',
  '7.0.0-beta.40',
  '7.0.0-beta.41',
  '7.0.0-beta.42',
  '7.0.0-beta.43',
  '7.0.0-beta.44',
  '7.0.0-beta.45',
  '7.0.0-beta.46' ]
```

Installing other packages like `react` works. 

## Environment

| Tech    | Version |
|---------|---------|
| next    |  latest using `npm install next --save` |
| node    |        v10.0.0 |
| OS      |   OSX El Capitan, version 10.11.6  |

**Comment by timneutkens** [comment]
I can't reproduce this. It's probably something with the npm registry. Unrelated to Next.js.

**Comment by geekyme** [comment]
It's fixed today. Strange.
