### ISSUE TITLE
 More webpack configuration

### ISSUE THREAD

**Issue by hopperhuang** [zeit/next.js#4338]
next.js need more webpack configuration

- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

webpack config can use hashcode to generate file name, add the hascode can be used in pages
## Current Behavior

i genereate my css file use extractCssPlugin, and named it by hashcode. but i couldn't get the webpack content hashcode in my pages, cod i couldn't use this css file.

and i wanna know, how can i cache my css file and js file, without hashcode, should i write the version code by hands? it is ridiculous. why you guys don't provide the static resouce cache examples? it's hard for newer to found out how to cache static resouse in next.js.

i think we aslo need a example about cache js file and css file!!!

## Context

i just wanna know how to cache static resource like main.js and css generate by withcss plugin,
where to get the unique version code and how to quote them in my _doucment.js file
## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    6.0.0     |
| node    |      8.9.7   |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
You can use something like https://github.com/zeit/next.js/pull/4119#issuecomment-379299209
