### ISSUE TITLE
new with-apollo example initializes twice on ssr

### ISSUE THREAD

**Issue by glenarama** [zeit/next.js#4355]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
with-apollo-client should be called once only per ssr

## Current Behavior
The with-apollo example that uses _app.js initializes twice on the server, this seems to be due to Error being called with _app.js as well as the page.

## Steps to Reproduce (for bugs)
Add a console.log(Component) within the getInitialProps of with-apollo-client and see console log two entries. One for your component another for error.

## Context
Performance and possible other side effects.

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |    6.0.1     |

**Comment by glenarama** [comment]
Just worked out this is due to Chrome calling favicon - and it causing a 404 render. Will close.

**Comment by PeteJodo** [comment]
doesn't the example still initialize apollo client twice for ssr though? One in `getInitialProps` and second in the constructor. The second call at least gets the initial state from the work of the previous store but it still seems not very kosher
