### ISSUE TITLE
google-site-verification tag

### ISSUE THREAD

**Issue by shmulikkaminker** [zeit/next.js#4357]
Hello friends, I'm trying to add the "google-site-verification" tag to validate my site on the google search console, and the authentication fails.

I use the head element of next.js.It appears in html but I think because it has a class of class = "next-head" Google does not recognize the tag, can you remove the class, or do you have another idea?

**Comment by timneutkens** [comment]
You can use https://github.com/zeit/next.js#custom-document

Or use dns verification. 

Please follow the issue template next time.
