### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by matthewmueller** [zeit/next.js#436]
Would be nice to see what the browser support is for next.js.

Also if `next/prefetch` breaks on IE, or just falls back to `next/link`.

**Comment by rauchg** [comment]
Great question, we should add it to the README. When `ServiceWorker` is not supported, it doesn't do anything. We've thought about adding fallbacks (like a regular `Worker`), but I tend to prefer to "keep it lean, give best performance to modern browsers". It also seems that `ServiceWorker` is gaining momentum.

**Comment by rauchg** [comment]
Other than that, I think it's fair to say that it works everywhere where React works

**Comment by matthewmueller** [comment]
Yah cool that's what I figured. There's just some high-order components specific to next that it'd be good to make sure work cross-browser, so we know what we're getting ourselves into by integrating. I did a quick test and it seems like zeit works on IE though. 

I think if it's easy for prefetch to fallback to link that would be ideal. If I'm understanding it correctly, next app's using prefetch would be broken on latest IE since they can't switch pages.

**Comment by rauchg** [comment]
Pre-fetching is a side-effect. It definitely falls back to regular `<Link>`

**Comment by rauchg** [comment]
To re-state it more clearly: the side-effect of pre-fetching is disabled in browsers without `ServiceWorker`.

**Comment by arunoda** [comment]
Yes that's right Service Workers.  It has no effect on unsupported browsers.

**Comment by arunoda** [comment]
@matthewmueller I only have access to a IE9 browser. Next.js works properly even for an app utilizing prefetching. It's works exactly as it should be. (But no prefetching)

I assume, this will work with IE7 as well.

**Comment by basvdheijden** [comment]
@arunoda @rauchg I'm developing a platform for 3rd world countries (where the connection capabilities are really poor), and the reason for me that Next.js is so interesting is because of the low footprint & bandwidth that is required when fetching new pages (a whole page refresh is not necessary). However, I still see IE6 popping up quite oftenly (and other obscure browsers) in the analytics. Is it completely hopeless to get this working in IE6 with something like https://www.npmjs.com/package/react-ie ? Or even just get it working so that IE6 uses full page refreshes (disable the client side part alltogether) but keep the low footprint for modern browsers? Would love to hear your POV on this. Thanks a lot in advance and happy 2017 :+1:

**Comment by rauchg** [comment]
Definitely should be doable to make that package work via a `react -> react-ie` association in webpack, in the same manner we support preact (check the examples)

**Comment by arunoda** [comment]
@basvdheijden @rauchg 
Currently we can only support IE9+ only.
That's due to our usage of history API.
See: https://github.com/zeit/next.js/issues/473#issuecomment-269320177

I hope we could do something about it.

**Comment by basvdheijden** [comment]
And its not possible to replace that part with # based urls?

**Comment by rauchg** [comment]
The situation that I'd like to have is that people who want to support older browsers can just add _polyfills_, and nothing else is required.

**Comment by arunoda** [comment]
@rauchg That's possible if that's a simple library/API thing.
But here we totally depend on the history API for routing.

And we only support page based routing. So, we expect to have client side to do history API based routes. (Not `#` based routes)

**Comment by rauchg** [comment]
Isn't that just a matter of polyfilling `history` ?

**Comment by arunoda** [comment]
@rauchg I tried that.
Polyfill to history work on the API level.
But not in the route wise.

For example, if we do a pushState to `/about`. It'll work properly on modern browsers.
With history polyfill, it'll be like this: `http://myapp.com/#/about`

So, that's the problem is.

**Comment by rauchg** [comment]
Oh, I understand now. To support pre-pushState will be difficult. Not impossible though, but we certainly won't be prioritizing this.
