### ISSUE TITLE
@zeit/next-css link displaying 404

### ISSUE THREAD

**Issue by mritgupta** [zeit/next.js#4364]
# 404 page not found
<a href="https://github.com/zeit/next-plugins/tree/canary/packages/next-css" target="_blank" rel="noopener noreferrer" class="jsx-3433991402">@zeit/next-css</a>

can anyone help me

Thanks

**Comment by timneutkens** [comment]
@mritgupta took me quite a while to figure out you meant on nextjs.org/docs. It's fixed now. Next time please follow the issue template.

**Comment by mritgupta** [comment]
Yes, it fixed. Thanks, @timneutkens
