### ISSUE TITLE
Absolute distDir fails

### ISSUE THREAD

**Issue by fatfisz** [zeit/next.js#4367]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate. There is a related issue #2769, but it's slightly different and what was described there seems to be working now.

## Expected Behavior

When I provide an absolute `distDir`, it works.

## Current Behavior

Because `path.join(dir, config.distDir)` is used everywhere, the path doesn't make sense and mkdirp fails (I guess other parts of Next.js would fail too if not for mkdirp failing first).

## Steps to Reproduce (for bugs)

1. Create a custom server with the following configuration:
```js
const app = next({
  dev,
  dir: __dirname,
  conf: {
    distDir: path.resolve('.foobar'),
  },
});
```
2. Launch this server.

## Context

I'm creating a tool that uses Next.js internally. As such, I'd like to keep stuff like `pages/` inside my package while putting the dist dir inside the project.

Issue #2769 describes a situation where paths like `'../.foobar'` not working, but it doesn't seem to be the case now. That's why I can use the workaround of `path.relative(dir, path.resolve('.foobar'))`. But if `path.resolve(dir, config.distDir)` was used instead of `path.join(dir, config.distDir)`, other people could avoid this pitfall in the future.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   6.0.2 |
| node    |   8.9.3 |
| OS      |  Win 10 |

**Comment by illuminist** [comment]
I keep pages in src directory and point base directory there. I had migrated from other build system which used absolute path for distDir. I didn't realize at first but found dist folder is missing from project root directory, and found out later that it built in to src folder with full path from `project_root/src/home/me/project_root/dist/...`.

My current work around is to explicitly define distDir as `../dist` so it would build into destination correctly.

**Comment by timneutkens** [comment]
Feel free to send a PR if this is still a requirement. There's very few cases where I would recommend setting `distDir`. I'm going to close this as no one else has brought up the same issue 👍
