### ISSUE TITLE
How add [hash] for .js .css and other files in build? 

### ISSUE THREAD

**Issue by Popugune** [zeit/next.js#4368]
I want add [name]__[hash]__.[ext] for `.js .css` and other files in build

For example in webpack i have `file-loader` and i have 
```
options: {
              name: '[name]__[hash]__.[ext]',
              publicPath: '...',
              outputPath: '...',
            },
```

How do same in next.config.js? Or nextjs do hashing files when build? 

| Tech    | Version |
|---------|---------|
| next    |     5.1.0    |
| node    |  10.0.0       |

**Comment by Popugune** [comment]
it working but look like as shi~
```
const nextConfiguration = {
  webpack: (config, { dev, buildId }) => {
    if (!dev) {
      const nextExtractTextPlugin = config.plugins.find(
        element => element.__proto__.constructor.name === 'ExtractTextPlugin'
      );
      nextExtractTextPlugin.filename = `static/style.${buildId}.css`;
      config.plugins.push(nextDefinePlugin(buildId), nextCleanWebpackPlugin);
      return config;
    }
    config.plugins.push(nextDefinePlugin);
    return config;
  }
};
```

**Comment by timneutkens** [comment]
Doesn't seem like a Next.js issue. Maybe you're using one of the next-plugins, in that case file it there. Also, when creating issues, please follow the issue template.

**Comment by Popugune** [comment]
@timneutkens what about extractCSSPlugin in context `webpack: (config, context) => {`
how i can manipulate it

**Comment by Popugune** [comment]
@timneutkens nextjs do hashing files when build?

**Comment by Popugune** [comment]
@timneutkens do u answer me?

**Comment by ghengeveld** [comment]
@Popugune The issue tracker is for filing bugs in Next.js, not to ask for support. You can try asking your question on [Spectrum](https://spectrum.chat/next-js). 

It looks like you're on the right track with your `nextConfiguration` above.
