### ISSUE TITLE
next.js example fail, can't import 'next' module.

### ISSUE THREAD

**Issue by askldjd** [zeit/next.js#437]
When I try to run the custom server example, it fails at the line [`require('next')`](https://github.com/zeit/next.js/blob/master/examples/custom-server-express/server.js#L2).

Looking into the module, it doesn't seem to have a main index.js file. Am I missing something?

**Comment by rauchg** [comment]
It's not released yet. The most up to date documentation is on the README for https://github.com/zeit/next.js/releases/tag/1.2.2. `master` targets our upcoming `2.0` release

**Comment by askldjd** [comment]
Ah, gotcha. Looking forward to the next release. Keep up the good work.
