### ISSUE TITLE
Update with-apollo-auth example to use _app.js?

### ISSUE THREAD

**Issue by lolcoolkat** [zeit/next.js#4372]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
The ```with-apollo-auth``` example (https://github.com/zeit/next.js/tree/canary/examples/with-apollo-auth) should be updated to use the new ```_app.js``` functionality https://github.com/zeit/next.js/pull/4286. Each pages ```getInitialProps``` to check if a user is logged in should be moved to _app.js to reduce duplication of code.

## Current Behavior
The ```with-apollo-auth``` example (https://github.com/zeit/next.js/tree/canary/examples/with-apollo-auth) has not yet been updated.

## Steps to Reproduce (for bugs)
N/A

## Context
Doing something similar to the following would be ideal, rather than having to put ```getInitialProps``` on each page that you want to authorize/redirect a user on via the ```checkLoggedIn``` function.

**Note**: I had an issue doing the following code however; seemed to be getting an infinite loop.. so hoping someone else can take a look and figure out a solution :D

```
import App, { Container } from 'next/app'
import React from 'react'

import redirect from '../lib/redirect'
import withData from '../lib/Apollo/withData'
import checkLoggedIn from '../lib/Apollo/checkLoggedIn'

class MyApp extends App {
  static async getInitialProps({ Component, router, ctx }, apolloClient) {
    let pageProps = {}

    const { loggedInUser } = await checkLoggedIn(ctx, apolloClient)

    if (!loggedInUser.me) {
      // If not signed in, send them to the login page
      redirect(ctx, '/login')
    }

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }

    return { pageProps, loggedInUser }
  }

  componentDidCatch(error, errorInfo) {
    console.log('Error: ', error)
    super.componentDidCatch(error, errorInfo)
  }

  render() {
    const { Component, pageProps } = this.props
    return (
      <Container>
        <Component {...pageProps} />
      </Container>
    )
  }
}

export default withData(MyApp)
```

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |   6.0.2      |
| node    |   9.11.1      |
| OS      |    Windows 10     |
| browser |    Google Chrome     |
| etc     |         |

**Comment by timneutkens** [comment]
Please follow the issue template next time. Added the good first issue label.

**Comment by timneutkens** [comment]
New example was merged.

**Comment by uri3000** [comment]
If you put this in the App will it still handle client side routing?
