### ISSUE TITLE
"Home.getInitialProps()" should resolve to an object. But found "undefined" instead.

### ISSUE THREAD

**Issue by Nishchit14** [zeit/next.js#4373]
- [ x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

It should not fire the error

## Current Behavior

I'm using custom express server and I'm getting this error page load
```
"Home.getInitialProps()" should resolve to an object. But found "undefined" instead.
```

## Steps to Reproduce (for bugs)

1. Use custom  express server
```
server.get('/home/:slug', (req, res) => {
		const { pathname, query }  = parse(req.url, true)
		return app.render(req, res, '/Faq', {
	 		slug: req.params.slug
		})
	})
```
2. Home component is like this
```
export default class Faq extends Component {

	static async getInitialProps ({ req, query }) {
		console.log(query)
	}
      render() {
         <div> This is home </div>
      }
```
3. I'm gettting above error

## Context

I want to render page dynamically as per the slug, without it I'm not able proceed further

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   6.0.2      |
| node    |     9.2.0    |
| OS      |      Mac   |
| browser |    Chrome     |
| etc     |         |

**Comment by timneutkens** [comment]
`"Home.getInitialProps()" should resolve to an object.` seems pretty clear to me 🤔 

```
static async getInitialProps ({ req, query }) {
		console.log(query)
	}
```

You're returning nothing from getInitialProps, it should always return an object. Like `return {}`
