### ISSUE TITLE
Tutorial: dynamic page quiz answer incorrect on FF

### ISSUE THREAD

**Issue by dlcoffee** [zeit/next.js#4375]
**Describe the bug**
the quiz asks for the url when clicking on the link. when selecting the option seen in firefox, it's marked as incorrect (it is correct on chrome).

**To Reproduce**
1. follow tutorial steps normally
2. answer quiz on https://nextjs.org/learn/basics/create-dynamic-pages/adding-a-list-of-posts
3. get wrong answer when using what's seen on firefox

**Expected behavior**
i'm not sure... i think both are valid (`/post?title=Hello%20Next.js` and `/post?title=Hello Next.js`). i understand that the end result is the same, but it might be confusing for beginners when running through the tutorial.

**Screenshots**
![screen shot 2018-05-14 at 12 46 39 pm](https://user-images.githubusercontent.com/2092822/40019713-e050dff2-5774-11e8-8d3b-465d4453eb4b.png)
![screen shot 2018-05-14 at 12 43 43 pm](https://user-images.githubusercontent.com/2092822/40019734-edf0e508-5774-11e8-9b48-e644c142b88b.png)

**System information**
 - OS: macOS
 - Browser: firefox dev edition, 61.0b4
 - Version of Next.js: 6.0.2

**Comment by gatezh** [comment]
Just faced the same issue

**Comment by timneutkens** [comment]
Please file under github.com/zeit/next-site. Thanks 🙏

**Comment by gatezh** [comment]
Done [#35](https://github.com/zeit/next-site/issues/35)
