### ISSUE TITLE
How to add additional folder with es6 code for server (Next.js + GraphQL)

### ISSUE THREAD

**Issue by Kizbo** [zeit/next.js#4391]
Hi, i found a little problem with building my app and i really can't solve this by myself:
I have my app, located inside /pages directory. Everything in here is fine, problem is when i try
to add additional folder for my graphql server in my app, lets say that will be graphql inside my root directory.

How can i achieve that, keeping in mind i have my resolvers and connectors written in es6 etc. I want to transpile that folder, then just include my schema.js from this folder inside my custom server.js

> - graphql_server
>   -- schema.js
>   -- connector.js
>   -- resolver.js
> - pages
>   -- myapp...
> - server.js

and here is my server.js:
```
const express = require('express');
const next = require('next');
const { graphqlExpress, graphiqlExpress } = require('apollo-server-express');
const bodyParser = require('body-parser');
const schema = require('./pages/graphql_server/data/schema');

//app server vars
const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();
//graphql server vars
const GRAPHQL_PORT = 3003;
const graphQLServer = express();

//graphql server

graphQLServer.use('/graphql', bodyParser.json(), graphqlExpress({ schema }));
graphQLServer.use('/graphiql', graphiqlExpress({ endpointURL: '/graphql' }));

graphQLServer.listen(GRAPHQL_PORT, () =>
    console.log(
        `GraphiQL is now running on http://localhost:${GRAPHQL_PORT}/graphiql`
    )
);

//app server
app.prepare()
    .then(() => {
        const server = express();

        server.get('*', (req, res) => {
            return handle(req, res)
        });


        server.listen(port, (err) => {
            if (err) throw err;
            console.log(`> Ready on http://localhost:${port}`)
        })

    });
```

I might doing this all wrong, sorry if this is just stupid idea, i'm kinda fresh.

**Comment by timneutkens** [comment]
Generally you'll want to split out your next.js app and api server for performance reasons.
