### ISSUE TITLE
blocking behavior and routes

### ISSUE THREAD

**Issue by andrew--grant** [zeit/next.js#440]
Not sure this is an issue as such, possibly ignorance.

I understand that the `getInitialProps `will block while I await data from a remote server, but I’m not sure how NextJS recommends I handle the side effect of this when clicking on route links. So, when I click on the route link for ‘/about’ there is a noticeable delay while the data is fetched, so it appears to the end user like clicking on the aforementioned link was ineffective/non-responsive for some period.

I understand why this is happening, but this (among a couple of other things) is making me wonder what value NextJS is adding over, say, a create-react-app and redux solution? Or if I’m missing something here w/r to appropriate use cases for NextJS?

**Comment by FrancosLab** [comment]
In `master` we now have prefetch so browsers with service workers can download the next pages in the background and that delay will be gone.

We also have https://github.com/zeit/next.js/pull/250 so eventually we'll have a indicator of progress :)

**Comment by arunoda** [comment]
@FrancosLab is right.
We have some stuff in the pipeline and will come with 2.0 release.

**Comment by andrew--grant** [comment]
Thank you, appreciate the speedy response!
