### ISSUE TITLE
Exported site client routing breaks

### ISSUE THREAD

**Issue by iammerrick** [zeit/next.js#4403]
**Describe the bug**

Using a client route (query parameter) fails *after* exporting the site. Clicking the link works but going directly to the URL does not. I'm guessing client sites need some sort of hydration step that inits fro the current route.

**To Reproduce**

I made a reproduction repo: https://github.com/iammerrick/next-6-client-routing-bug-repro
The built version of that code and being able to see the issue can be found here: https://out-qipaehstsc.now.sh/?id=1 

Notice, it isn't until you click the buttons that you see the page update. Refreshing the page resets the route and doesn't respect the query parameter.

**Expected behavior**

I expect the page to be rendered with the proper query parameters on page load. The router should be instantiated with the correct URL.

**System information**
 - OS: macOS
 - Version of Next.js: 6.0.3

**Comment by sergiodxa** [comment]
This is expected, since you exported your app the HTML files are static so there is no way to render an initial HTML respecting the query parameter.

You should instead get the query param in componentDidMount and update your page state as you need with the query param value.

**Comment by iammerrick** [comment]
@sergiodxa Thank you for the quick response! I am surprised the router doesn't pick it up on the client side when initializing and cause an additional render (or hydrate router state before re-hydrating the app). That part is intentional?

**Comment by iammerrick** [comment]
I didn't expect it to be the initial render but I did expect after JS had run the router would pick up initial state from the url like other client side routing solutions. Is this simply a trade-off for the universal js router?

**Comment by ijjk** [comment]
Closing in favor of #4804
