### ISSUE TITLE
Allow duplicate meta tag some attribute

### ISSUE THREAD

**Issue by suntunz** [zeit/next.js#4407]
I can't add same meta tag because **"next/head"** override same meta tag.

`<meta name="cXenseParse:trt-keywords" content="keyword1" />`
`<meta name="cXenseParse:trt-keywords" content="keyword2" />`

Please setting allow some meta tag attribute without override.

I hope you can help me.  :D

**Comment by timneutkens** [comment]
This was solved in https://github.com/zeit/next.js/pull/5800
