### ISSUE TITLE
404 on loading next scripts when migrated to NextJS 6

### ISSUE THREAD

**Issue by felixnoriel** [zeit/next.js#4408]
Hi, I have a problem when I migrated to NextJS 6. I'm getting 404 when importing all NextJs scripts eg: `www.url.com/_next/BUILD_ID/page/index.js`

- **problem only occurs during production build**, dev build is fine
- the page itself loads, but Next javascripts aren't loaded, see image below
- tried and installed all 6.0 canary pre-release
- 6.0.0-canary.1 to 6.0.0-canary.3 are working fine and problem occurs on 6.0.0-canary.4 onwards
- I didn't really change any code, just upgraded NextJS from 6.0.0-canary.3 to 6.0.0-canary.4
- why suddenly _next scripts aren't available/working? do I need to add or change something?
- when I access the script file via url it's not found, is the script missing or ? 
- there are no errors in the logs
- sorry I don't know how to reproduce the error, everything was working fine until I upgraded to 6.0.0-canary.4 version

next.config.js
```
const withSass = require('@zeit/next-sass')
 module.exports = withSass({
  useFileSystemPublicRoutes: false,
  webpack: function (c) {
    if (c.resolve.alias) {
      delete c.resolve.alias['react']
      delete c.resolve.alias['react-dom']
    }
    return c
  },
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: "[local]___[hash:base64:5]",
  },
  publicRuntimeConfig: {
      node_env: process.env.NODE_ENV || 'development'
  }
})
```

server.js 
```
const next = require('next')
const routes = require('./routes')
const app = next({dev: (process.env.NODE_ENV !== 'production_net' && process.env.NODE_ENV !== 'production_com' ) })
const handler = routes.getRequestHandler(app)
const mobxReact = require('mobx-react')
const path = require('path');
mobxReact.useStaticRendering(true)
const server = express();

if (process.env.NODE_ENV === 'production_net' || process.env.NODE_ENV === 'production_com') {
  const handler = routes.getRequestHandler(app, ({req, res, route, query}) => {
    app.render(req, res, route.page, query)
  })
  const bodyParser = require('body-parser')
  const cors = require('cors')
  const compression = require('compression')

  server.use(handler)
        .use(compression)
        .use(cors)
        .use(bodyParser.json())
        .listen(3000);
} else {
  app.prepare()
    .then(() => {
      const handler = routes.getRequestHandler(app, ({req, res, route, query}) => {
        app.render(req, res, route.page, query)
      })
      server
      .use(handler)
      .listen(3000);
    })
  .catch((ex) => {
    console.error(ex.stack)
    process.exit(1)
  })
}
```

routes.js

```
const nextRoutes = require('next-routes')
const routes = module.exports = nextRoutes()
routes
.add('/', '/', 'index')
.add('posttype', '/:posttype', 'post')
.add('posttype/:category', '/:posttype/:category', 'post')
.add('posttype/:category/:slug', '/:posttype/:category/:slug', 'post')
.add('posttype/:category/:slug/:twoslug', '/:posttype/:category/:slug/:twoslug', 'post')
.add('posttype/:category/:slug/:twoslug/:threeslug', '/:posttype/:category/:slug/:twoslug/:threeslug', 'post')
```

<img width="816" alt="screen shot 2018-05-17 at 2 59 53 pm" src="https://user-images.githubusercontent.com/3009324/40157544-fef52768-59e2-11e8-9983-b05b70a8da03.png">

anyone has the same problem as mine? any help is much appreciated! thanks

**Comment by timneutkens** [comment]
Please provide the full server.js, you are referencing a variable routes that doesn’t exist

**Comment by felixnoriel** [comment]
@timneutkens Sorry about that. I think I found the issue now. I just realised that for production, I didn't put the code inside app.prepare(). I've put it inside that and it's now working. Rookie mistake. 
Thanks though.
