### ISSUE TITLE
Doc for static site export disagrees with blog post about next.js v6

### ISSUE THREAD

**Issue by avaragado** [zeit/next.js#4410]
The blog post announcing next.js v6 at https://zeit.co/blog/next6#static-react-applications says:

> With Next.js 6, we automatically generate the route map for you based on the content of your pages/ directory

But both sources of documentation for static export, https://github.com/zeit/next.js#static-html-export and https://nextjs.org/docs#static-html-export, both say:

> Simply develop your app as you normally do with Next.js. Then create a custom Next.js config as shown below:

I presume the blog post is correct. But I shouldn't have to read the blog post to learn about this feature.

Apologies if this is not the right place to report a bug with nextjs.org. I can't find a better place. And the doc looks like a prettified copy of the main repo's `readme.md` anyway.

**Comment by timneutkens** [comment]
Updated the docs in the readme: https://github.com/zeit/next.js#static-html-export

nextjs.org/docs will be updated later.
