### ISSUE TITLE
Router.push  add unnecessary "/" suffix on end of url in export code

### ISSUE THREAD

**Issue by mydearxym** [zeit/next.js#4411]
hey there ~

when i call Router.push in dev mode, every thing works fine, and browser url looks as  expected

```js
Router.push('/', `/racket/posts`)
```
```bash
http://192.168.31.162:8000/racket/posts
```
but when i compile the site in static files use `next export`, the `Router.push ` automatic add a "/" suffix in the end of the url :

```bash
http://192.168.31.162:8000/racket/posts/
```
page/index.js 

```js
export default class Index extends React.Component {
  static async getInitialProps({ req, pathname, asPath }) {
    console.log('getInitialProps asPath ---> ', asPath)  // ==> /racket/posts/
   }
   .....
}
```
get 303 in  browser

![image](https://user-images.githubusercontent.com/6184465/40211867-9928a372-5a7f-11e8-9244-4ca316ddbefb.png)

related: #1189 #619 #3876

**System information**
 - OS:  macOS 
 - Browser: chrome 
 - Version of Next.js:  6.0.3

**Additional context**
 i am using custom server route

**Comment by NathanielHill** [comment]
This isn't the router. When the site is exported a page like `pages/about.js` gets converted to `about/index.html` to avoid having the `.html` suffix in the location bar. There are several issues about this, including a PR #3283. Hopefully this is implemented, it's my only problem with using static exports.

**Comment by NathanielHill** [comment]
This is fixed :tada:
https://zeit.co/blog/new-static-deployments

**Comment by mydearxym** [comment]
@NathanielHill  awesome !
