### ISSUE TITLE
Scroll to div id is not working (<Link href='/page#id'/> )

### ISSUE THREAD

**Issue by lenaten** [zeit/next.js#442]

**Comment by suhaotian** [comment]
This caused: https://github.com/zeit/next.js/blob/master/lib/link.js#L33

**Comment by lenaten** [comment]
Thanks @suhaotian, it's works, but it's not very intuitive and not documented.

**Comment by nkzawa** [comment]
Maybe we should automatically make `scroll={false}` when url includes `#`.

**Comment by lenaten** [comment]
What the original purpose of this line `if (scroll !== false) window.scrollTo(0, 0)`?

**Comment by nkzawa** [comment]
We have to adjust the scroll position when you redraw pages with `history.pushState` since browser doesn't reset the position.

**Comment by lenaten** [comment]
> Maybe we should automatically make scroll={false} when url includes #.

`#<value>` can represent something else then element id.

**Comment by arunoda** [comment]
> #<value> may represent something else than element id.

Yep. But in this case, it seems like something we don't need to look at.
I agree with @nkzawa's proposal.

> Maybe we should automatically make scroll={false} when url includes #.
