### ISSUE TITLE
Example material-ui-next is broken and empty

### ISSUE THREAD

**Issue by afridley** [zeit/next.js#4431]
**Describe the bug**
Material-ui-next example loads an empty project only containing the readme
yarn start does nothing because well its empty.

follow instructions

**To Reproduce**
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to material-ui-next example Go to Material-ui-next example https://github.com/zeit/next.js/tree/canary/examples/with-material-ui-next 
2. follow instructions yarn create next-app --example with-material-ui-next with-material-ui-next-app

**Expected behavior**
The example project is created and working with Material-ui-next rc1.0.0 latest version

**System information**
The latest version of Next.js

**Comment by oliviertassinari** [comment]
Should be fixed by #4444

**Comment by timneutkens** [comment]
Exactly, thanks @oliviertassinari
