### ISSUE TITLE
Shallow routing, when updating URL parameters, still get old params when the page re-renders

### ISSUE THREAD

**Issue by vonwao** [zeit/next.js#4432]
**To Reproduce**
Create a page.  
Create an event that calls Router.push(newUrl, newUrl, { shallow: true });
The new newUrl is the same page with updated query params. 
When the event is called, page re-renders, but props.url.query still has old query params.

**Expected behavior**
props.url.query should have new query params

**System information**
 - Version of Next.js: 6.0.2

**Comment by timneutkens** [comment]
Maybe query is still mutable https://github.com/zeit/next.js/pull/4352/files#diff-c39f41208533f29db9e4150b6efd2b68R101

**Comment by vonwao** [comment]
@timneutkens can you think of any way (aside from the test) that I can check if that's the case?

**Comment by vonwao** [comment]
By the way, the workaround I found is to avoid using Next router, and instead update the URL with window.history.  I wonder how many are using this approach this since the router doesn't seem to work correctly.

**Comment by mattclough1** [comment]
@vonwao Do you remember if you had a custom app.js? I have hunch.

**Comment by kachkaev** [comment]
I guess I'm also expiriencing this issue in `next@6.1.1-canary.5`. Here's my scenario:

1. Navigate to `/my-page?x=1&y2`.
2. Inject these values into the page component inside `getInitialProps()`:
  ```jsx
    public static getInitialProps({ query }) {
    return {
      x: query.x,
      y: query.y,
    };
  }
  ``` 

3. Interact with the page and modify `x` or `y` using `Router.replace(newHref, newHref, { shallow: true });`. The new values of `x` and `y` are kept in the state of the page component to avoid full re-render of the whole layout every time.

4. Navigate to some other page by clicking on a `<Link />`. Let's assume that we see `/my-page?x=42&y=43` at the moment of the click and the page is reflecting this data correctly.

5. Press _back_ in the browser and return to `/my-page?x=42&y=43`. At this moment, I am expecting a client-side call of `getInitialProps` with `query` equal to `{x: 42, y: 43}`. However, I observe `{x: 1, y: 2}` as in the first render. This happens despite that `window.location.href` contains `?x=42&y=43`, which means that it gets unsynchronised with the value of Next's `{ query }`.


Here's my workaround for the time being:

  ```jsx
  import { parse } from "url";

  // ...

  public static getInitialProps({ query }) {
    // https://github.com/zeit/next.js/issues/4432
    const fixedQuery =
      typeof window === "undefined"
        ? query
        : parse(window.location.href, true).query;
    return {
      x: fixedQuery.x,
      y fixedQuery.y,
    };
  }
  ```

The trick is to rely on `{ query }` only during SSR and fall back to a more robust `window.location.href` on the client.

**Comment by timneutkens** [comment]
Can someone create a minimal repository reproducing this?

**Comment by kachkaev** [comment]
I tried creating an MWE, but could not reproduce the bug in my previous comment. Moreover, `getInitialProps` in the original app started working correctly without introducing `fixedQuery` 😅 

I'll show up again if I notice the problem again and realise what's happening. Sorry if it's a false alarm!

**Comment by 7c78** [comment]
Hi @timneutkens 
I am facing this issue. I have created a repo to reproduce it.
Here it is: https://github.com/7c78/next-4432

Step to reproduce:
1. access to http://localhost:3000
2. press `Navigate` link and check the F12 console

**System information**
```
"next": "^6.1.1",
"next-routes": "^1.4.2",
"mobx": "^5.1.0",
```

**Comment by timneutkens** [comment]
The original issue was fixed already.

@7c78 the issue in your app is that you're doing:

`console.log(appContext.router.query)` whereas you should be doing:

`console.log(appContext.ctx.query)`, `ctx` is the page context. `router` is the router at that point in time, before it's updated.

**Comment by 7c78** [comment]
@timneutkens oh thanks!
