### ISSUE TITLE
There's no way to control the default scripts that are added to <head>

### ISSUE THREAD

**Issue by stenehall** [zeit/next.js#4434]
**Is your feature request related to a problem? Please describe.**
There's currently no way to control what scripts/preloads should be added to your document. As it is `app.js` and a few others will always be loaded.

This means that there's no way to create a simple static html page, with no connection to next.js.

**Describe the solution you'd like**
A way to control what/if any next.js provided tags should be adde. A proposed simple solution to this is https://github.com/zeit/next.js/pull/4387

**Describe alternatives you've considered**
A better way to solve this would be to rewrite the way scripts are added to head and let have a hook to filter/replace/add scripts to this.

**Additional context**
With this functionality we'd be able to use next.js as a simple static page generator and not have to also get all what is next.js.

**Comment by timneutkens** [comment]
Closing this in favor of #5054
