### ISSUE TITLE
Some details about build

### ISSUE THREAD

**Issue by liumin1128** [zeit/next.js#4437]
Now, my project can be compiled under Mac OS, no problem, but there will be errors on the server, and there is no feedback information.

Local environment: Mac OS 10.13.4, node 10.0.0

Server environment: Ubuntu 16.04, node 10.0.0
![image](https://user-images.githubusercontent.com/12379461/40281340-30ffbce8-5c93-11e8-8ae1-912e51970fe5.png)

**Comment by liumin1128** [comment]
I want to know how to deal with this situation. Thank you very much.

**Comment by timneutkens** [comment]
Exit code 137 usually means out of memory. So your server doesn't have enough memory to process the build step.

**Comment by liumin1128** [comment]
Thank you so much
