### ISSUE TITLE
Bundling should take only pages directory children

### ISSUE THREAD

**Issue by steida** [zeit/next.js#4440]
**Describe the bug**
Next.js generates bundles even for __generated__ files.
![screen shot 2018-05-20 at 21 02 09](https://user-images.githubusercontent.com/66249/40282545-51cc2bc2-5c71-11e8-9f77-a9d16f3c5737.png)

**Expected behavior**
I would expect, because of URL mapping, only direct children files will be processed.

**Comment by TheRobBrennan** [comment]
Why are generated pages being stored underneath pages? NextJS will assume you have subfolders as routes you intend to have in your application.

For example, my demo has a sign-in URL at `pages/auth/sign-in`:
<img width="196" alt="00" src="https://user-images.githubusercontent.com/4030490/40282570-39cf6322-5c26-11e8-96dd-183e3b115695.png">

**Comment by timneutkens** [comment]
Like @TheRobBrennan said, nesting has always worked this way, if you create `pages/abc/def/g.js` you'll have a route on `/abc/def/g`. The pages directory should only hold pages 👍

**Comment by steida** [comment]
Oh, I see! Thank you. One question, can we add ignore for that logic? __generated__ is by Relay and it's imho not possible to change that logic.
