### ISSUE TITLE
Koa Isomorphic App 404's after npm run build

### ISSUE THREAD

**Issue by NewETown** [zeit/next.js#4441]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Copy the Koa custom server app
2. Create a route that returns some JSON object
3. Use fetch to retrieve the endpoint and show the JSON in your app
4. `npm run dev`
5. Verify the JSON shows on your screen as expected
6. `npm run build`
7. `npm run start` and try to load that same piece of data again

**Expected behavior**
The behavior from npm run dev and npm run start are identical.

**System information**
 - OS: macOS and Ubuntu
 - Version of Next.js: Latest as of this post

**Additional context**
Seems very odd, I've tried reworking the routes on my server with no luck. Currently blocking my production deploy. 99% sure it's something to do with the build process but I'm not familiar with the NextJS build process (or any build processes, not my jam) so anyone with intricate knowledge would be very helpful.

**Comment by gastonfartek** [comment]
@NewETown I've tried to follow your steps but was unable to reproduce the issue, it works for me. Can you provide a code example?

Here is what I've tried

1. cloned the [koa-example](https://github.com/zeit/next.js/tree/canary/examples/custom-server-koa) from this repo

2. `yarn add isomorphic-fetch`

3. modified the following files

**server.js**

```javascript
const Koa = require('koa');
const next = require('next');
const Router = require('koa-router');

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  const server = new Koa();
  const router = new Router();

  router.get('/a', async (ctx) => {
    await app.render(ctx.req, ctx.res, '/b', ctx.query);
    ctx.respond = false;
  });

  router.get('/b', async (ctx) => {
    await app.render(ctx.req, ctx.res, '/a', ctx.query);
    ctx.respond = false;
  });

  router.get('/test', async (ctx) => {
    ctx.body = { some: 'json' };
  });

  router.get('*', async (ctx) => {
    await handle(ctx.req, ctx.res);
    ctx.respond = false;
  });

  server.use(async (ctx, next) => {
    ctx.res.statusCode = 200;
    await next();
  });

  server.use(router.routes());
  server.listen(port, () => {
    console.log(`> Ready on http://localhost:${port}`);
  });
});
```

**a.js**
```javascript
import React, { Component } from 'react';
import fetch from 'isomorphic-fetch';

export default class ComponentA extends Component {
  state = {};

  setStateAsync(state) {
    return new Promise((resolve) => {
      this.setState(state, resolve);
    });
  }

  async componentWillMount() {
    const response = await fetch('http://localhost:3000/test');
    const data = await response.json();
    await this.setStateAsync({ data });
  }

  render() {
    return <div>{JSON.stringify(this.state)}</div>;
  }
}
```

**Comment by HaNdTriX** [comment]
@gastonfartek Thanks you! I could not reproduce this either.
