### ISSUE TITLE
with-apollo-auth fails with no cookie

### ISSUE THREAD

**Issue by glenarama** [zeit/next.js#4442]
**Describe the bug**
The current solution checks for a req cookie and falls back to document if the cookie is not in the request. When no cookie exists, this causes an error.

**To Reproduce**

Clear cookies - then load the example - the offending code is: 

withApollo.js:
`function parseCookies(req, options = {}) {
  return cookie.parse(
    req && req.headers.cookie
      ? req.headers.cookie
      : document.cookie,
    options
  )
}`

A fix would look something like:
` 
  cookie.parse(
    req ? (req.headers.cookie ? req.headers.cookie : "") : document.cookie,
    options
  )
`

**Comment by timneutkens** [comment]
@lfades
