### ISSUE TITLE
getting 404 on js.map after upgrade to 6.0.3

### ISSUE THREAD

**Issue by DeathDealerr** [zeit/next.js#4448]
Hi All , I am still pretty new to Next JS and i have been  exploring Next JS for quite some time now and today after upgrading next-redux-wrapper to 2.0 and next to 6.0.3 i have started seeing a strange issue with js.maps  i am not sure if this is a bug but my search in here didnt give me any matching results

**Describe the bug**
My app wont load due to 404 with js.map.

**To Reproduce**
Index Route from Express Server
```
server.get('/', (req, res) => {
    req.db = {
      quiz: Quiz,
    };
//Quiz is a const from mongoose models
    const mergedQuery = Object.assign({}, req.query, req.params, req.db);
    return renderAndCache(req, res, '/index', mergedQuery);
  });
```
\pages\index.js ->getinitalprops
```
 static async getInitialProps({ req, query }) {
    const page = Number(query.p);
    
    if (query.quiz) {
      if (!query.p) {
        const res = await query.quiz.find({}, ' type imgsrc views caption description scope').sort('-created_at').skip(0).limit(21);
        console.log(res);
        return { quizData: res };
      }
      const res = await query.quiz.find({}, ' type imgsrc views caption description scope').sort('-created_at').skip(21 * page).limit(21);
      return { quizData: res };
    }else{
    if (!query.p) {
      const res = await fetch('/14/25/28/15/quizzes/?select=type%20imgsrc%20views%20caption%20description%20scope&sort=-created_at&limit=21&skip=0', gibberish);
      const data = await res.json();
      return { quizData: data };
    }
    const res = await fetch(`/14/25/28/15/quizzes/?select=type%20imgsrc%20views%20caption%20description%20scope&sort=-created_at&limit=21&skip=${21 * page}`, gibberish);
    const data = await res.json();
    return { quizData: data };
  }
  }
```

**Expected behavior**
I expect the page to load fine

**Screenshots**
![image](https://user-images.githubusercontent.com/32959814/40360732-b102d5d6-5de4-11e8-9b33-c444ac89b64d.png)

**System information**
 - OS: Windows
 - Browser (if applies) Chrome/Opera
 - Version of Next.js: 6.0.3

**Changes Done**
1. Updated Nextjs from 6.0.1 to 6.0.3
2. Updated Next Redux Wrapper to version 2.
3. Added _app.js as described in Next Redux Wrapper. (https://github.com/kirill-konshin/next-redux-wrapper)

**Comment by timneutkens** [comment]
> My app wont load due to 404 with js.map.

This is incorrect, what happens is that an error is rendered, and in development, we try to enrich that error to include the real source path using source maps. These requests are not harming anything.

I'm guessing you're using `this.props.url` inside your page, which is not provided when you create a custom _app.js since magically injecting `url` is deprecated since 6.0.

**Comment by DeathDealerr** [comment]
Thanks @timneutkens . Issue is resolved now 👍
