### ISSUE TITLE
setInterval hangs if browser tab is in background

### ISSUE THREAD

**Issue by DuChrisNix** [zeit/next.js#4453]
Hey!

I work on a research project at the moment and need a live watch with seconds. I use setInterval for that in componentDidMount and set the state every time.

In an active browser tab, no problem. But if you change the tab, the time freezes and only continues if you go back - with a delay of 2 seconds or so. Console.log is still triggered though.

It works in plain JS and in plain React, so it must be an issue with next.js or it's SSR.
Any idea how I can get over it?

**Comment by timneutkens** [comment]
Maybe this is related to react-hot-loader 🤔

**Comment by DuChrisNix** [comment]
Then it should work after exporting the app, right? Tried that, doesn't help.

**Comment by timneutkens** [comment]
Either way, it's not like we can pause a browser 🤔

**Comment by timneutkens** [comment]
Can you provide a full reproduction?

**Comment by DuChrisNix** [comment]
Sure. Go [here](https://stupefied-bohr-7f13d7.netlify.com/), switch to a diffrent browser tab, wait a few seconds and switch back.

And [here](https://gist.github.com/DuChrisNix/190055c62bfd9662be0fae38189ef0bc) is a Gist of the mentioned component.

**Comment by DuChrisNix** [comment]
Oooh.. Nevermind.. I found the problem.
My Background Image was too big. Now that it's just black, it works just fine 😄

**Comment by timneutkens** [comment]
Interesting! I’m going to close this issue then 👍👌
