### ISSUE TITLE
Nextjs not updating new code with PM2 reload

### ISSUE THREAD

**Issue by aviramga** [zeit/next.js#4455]
**Describe the bug**

I would like to utilise the 0 downtime deploy with the pm2 reload function.
For that I switched from running
```pm2 stop hpssr; pm2 delete hpssr; pm2 start ecosystem.config.js```
to run
```pm2 reload ecosystem.config.js```

The output I get is
```
[PM2] Applying action reloadProcessId on app [hpssr](ids: 0,1)
[PM2] [hpssr](0) ✓
[PM2] [hpssr](1) ✓
```

But I dont see the new code changes.
While there is a new build and BUILD_ID the page is still loaded with the old BUILD_ID (while with the other command it would update to the new BUILD_ID)

**To Reproduce**
Try to update an existing running app and restart it with ```pm2 reload all```
This also happens with 
```
pm2 stop all; pm2 start all;
pm2 restart;
```
The only way I manage to get the new BUILD_ID is by deleting the current running processes with 
```pm2 delete all```

**Expected behavior**
The app should reload with the new BUILD_ID

**System information**
 - Ubunutu 14 aws server
 - Version of Next.js: 5.0.1

**Additional context**
I also opened a ticket in the pm2 project but I believe it to be an issue that relates to next&pm2 
https://github.com/Unitech/pm2/issues/3677

Thanks for your help!!!

**Comment by timneutkens** [comment]
Next.js is just a Node.js application. When Next.js is started the BUILD_ID is read. It's up to the user to make sure the app is restarted correctly after building.

**Comment by aviramga** [comment]
@timneutkens but other apps works just fine with pm2 so its probably not an issue on their end as well... I can see it restart the servers but I for some reason it will not grab the new build_id
