### ISSUE TITLE
404 in sourcemaps with custom server

### ISSUE THREAD

**Issue by jonaswindey** [zeit/next.js#4458]
**Describe the bug**
When there is an error in a component, the application loads the sourcemap. For instance: `/components/banner.js.map`

This returns a 404 when using a custom server (like in the example: https://github.com/zeit/next.js/tree/canary/examples/custom-server-hapi)

It also seems that all those requests are passing _app.js, where my Redux connection is located.

**To Reproduce**
Clone the custom server project and try loading a sourcemap

**Expected behavior**
Requests to sources in dev mode should return the code.

**System information**
 - Next.js: 6.0.3

**Comment by timneutkens** [comment]
> Clone the custom server project and try loading a sourcemap

I'm expecting the step "make an error in a Next.js page" is missing here. It's the only time I can imagine we try to fetch the sourcemaps, which right now is expected, but we can make it smarter.

**Comment by jonaswindey** [comment]
Yes sorry, it was in the bug description.

How are the source files supposed to be loaded with a custom server? For instance at when loading http://localhost:4000/components/banner.js ?

**Comment by timneutkens** [comment]
This isn't related to having a custom server. We just shouldn't try to load source maps that we know won't be returned, like `components/banner.js`, because that's compiled into the page bundle.

**Comment by timneutkens** [comment]
Solved in Next 7
