### ISSUE TITLE
Dimensions - with-react-native-web - example

### ISSUE THREAD

**Issue by gHashTag** [zeit/next.js#4459]
The tag is not working properly `Dimensions`

```javascript
import { Dimensions } from 'react-native'

const win = Dimensions.get('window')
const w = win.width
```

For example, the width of an iPhone is 980, but it's not like that

![2018-05-23 22 57 04](https://user-images.githubusercontent.com/6774813/40447896-a4dd1b9c-5edc-11e8-8f57-0a27143fecee.png)

**System information**
 - OS: [macOS]
 - Browser (if applies) [All]
 - Version of Next.js: [6.0.3]

**Comment by timneutkens** [comment]
You probably need to set the viewport meta tag.

**Comment by gHashTag** [comment]
@timneutkens 

Is the meta tag added to _document.js?
Why do you hurry to close tasks, if it is not solved?
Are you sure that this attitude leads to the prosperity of the project?

**Comment by timneutkens** [comment]
I've updated the example https://github.com/zeit/next.js/commit/c461d46efd16d99db73a0841b2ab4651d8371f0f

**Comment by gHashTag** [comment]
@timneutkens  thanks, and I made a pull request :)

**Comment by timneutkens** [comment]
Already merged it! Thank you very much 🙌
