### ISSUE TITLE
App.js bundle size too large even for Production Build

### ISSUE THREAD

**Issue by VansonLeung** [zeit/next.js#4463]
app.js is costing my browser 3MB size to load. 

I have asked a question here:
https://stackoverflow.com/questions/50501059/next-js-bundle-size-too-large-3mb

But as no answer yet, would like to ask if I am hitting a bug or else, and any solution for it.

**Comment by VansonLeung** [comment]
Note: I am using Next.js 4.2.1
I don't know how to upgrade the version either

**Comment by timneutkens** [comment]
I'm not sure what you're asking. If you import a big library the bundle becomes bigger. Next.js by itself is relatively small. It's definitely not a bug.

**Comment by VansonLeung** [comment]
Never mind, I have just found a full official tutorial of Code-Splitting function for Node.JS, which is automatic. Well done!
