### ISSUE TITLE
Next.js IE10 Object.setPrototypeOf() Not Working

### ISSUE THREAD

**Issue by yongbeam** [zeit/next.js#4471]
React 16 / Next.js 6.0.3 Object.setPrototypeOf() Not Support Error.
Is there a way to fix this error?

**Comment by timneutkens** [comment]
Please follow the issue template.

I'm going to close this and leave some links:

https://reactjs.org/docs/javascript-environment-requirements.html
https://github.com/zeit/next.js/tree/canary/examples/with-polyfills

**Comment by reesexu** [comment]
@yongbeam  Hi, has your problem been solve?Now i am facing the same problem
