### ISSUE TITLE
custom-server-express - the 'url' property is deprecated.

### ISSUE THREAD

**Issue by roma98** [zeit/next.js#4490]
# custom-server-express bug report

## Example name
custom-server-express

## Describe the bug
the warning message 'utils.js:26 Warning: the 'url' property is deprecated.' is being reported whenever you are using an express server.
I've started noticing it in my project, and verified it in this example to be sure.

## To Reproduce
Just download and start this example

## Expected behavior
We shouldn't get any warning message when executing this example.

**Comment by teleginzhenya** [comment]
I didn't see any warning messages
Which version of node are you using?

**Comment by timneutkens** [comment]
nextjs.org/learn has been updated.
