### ISSUE TITLE
Remove `react-hot-loader`

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#4494]
It causes way more issues than it fixes.

It's a matter of removing it from babel options

```js
    plugins: [dev && !isServer && hotLoaderItem, dev && reactJsxSourceItem].filter(Boolean)
```

becomes

```js
    plugins: [dev && reactJsxSourceItem].filter(Boolean)
```

**Comment by timneutkens** [comment]
It’s a little more involved than just removing the babel plugin. Also requires to rewrite the provider component they have to handle errors with componentDidCatch. I’m planning to fix this after a bug fix when using _app.js

**Comment by ArmorDarks** [comment]
I wonder, which exactly issues does it cause?

**Comment by Everettss** [comment]
@ArmorDarks Some changes made in RHL 4.1.0 course this problem: https://github.com/zeit/next.js/issues/4232

**Comment by ex3ndr** [comment]
What's alternatives? How we should auto-refresh page on changes?

**Comment by timneutkens** [comment]
Note that `react-hot-loader` !== hot reloading. Hot reloading still works.

**Comment by oliviertassinari** [comment]
I confirm, it works like a charm with `@material-ui/styles`. I have also the feeling that the end-to-end time for hot releading has greatly improved.

**Comment by timneutkens** [comment]
Good to hear @oliviertassinari 😌

**Comment by msand** [comment]
This seems to have decreased hot reloading from a worst case of minutes to seconds for a handful of views, now it seems to perform as good as next.js v4, or even better. And some strange edge cases in development have disappeared. Great work.

**Comment by timneutkens** [comment]
Great 👍
