### ISSUE TITLE
req.headers.cookie undefined when build & export

### ISSUE THREAD

**Issue by namcoder** [zeit/next.js#4499]
I used next-redux-wrapper with /page/_app.js.
I want to check the jwt token in cookies when user refresh their browser.
Everything is fine when run in dev but got error when build and export. Please take a look at screenshot.
By the way, could you let me know my logic is good or bad ? Could you let me know how you do that ?

Thank you very much !

![screen shot 2018-05-30 at 9 35 23 am](https://user-images.githubusercontent.com/8687083/40695802-0e435d48-63ed-11e8-8cb0-72e1e8cac0f4.png)
![screen shot 2018-05-30 at 9 35 37 am](https://user-images.githubusercontent.com/8687083/40695812-198c1bd6-63ed-11e8-9329-b84a1fae0379.png)

**Comment by rashidul0405** [comment]
not completely sure, I think when there are no cookies, `req.headers` is undefined. you can try this:
`const cookies = cookie.parse(ctx.req.headers.cookie || "")`

**Comment by namcoder** [comment]
@rashidul0405 Thank you for your response.
I found https://nextjs.org/docs/#limitation : 

> So, you could only use pathname, query and asPath fields of the context object passed to getInitialProps. You can't use req or res fields.

I think that is a reason. Do you have any idea for check jwt token every browser refresh ?

**Comment by rashidul0405** [comment]
you are doing this onServer. req params available there. Just noticed one thing - `ctx.isServer` - is this working? We were supposed to check isServer like this:
`const isServer = !!req`

**Comment by namcoder** [comment]
@rashidul0405 I have checked and `ctx.isServer ` works . I used your way but still got error.
when I run `yarn build` => success
when I run `yarn export` => error

I think the document https://nextjs.org/docs/#limitation is correct and I should research another way

**Comment by rashidul0405** [comment]
Right, when you use static export, it's a different story.

**Comment by namcoder** [comment]
@rashidul0405 Thank you for your support. Could you please let me know how do you do for this case ? I mean how could we keep user session via jwt token in cookie and dispatch in server side. 
Thank you

**Comment by timneutkens** [comment]
When exporting static html is exported, meaning there’s no req/res available on every request, so you have to check it in componentDidMount.
