### ISSUE TITLE
Accessing named exports from page components (MDX)

### ISSUE THREAD

**Issue by craigsssmith** [zeit/next.js#4502]
We're using MDX with mext.js to put together a simple documentation site and it's working great, they fit together nicely. We're using Markdown files as our top-level pages (e.g. `/pages/about-us.md`) but can't see any way of accessing metadata, which is handled via named exports by the MDX loader (see https://github.com/mdx-js/mdx#exports).

Is this possible at present, or would it require code changes to the next.js renderer?

**Comment by timneutkens** [comment]
It's currently not possible to access named exports of a top-level page. The current workaround is https://github.com/zeit/next-site/blob/master/pages/docs/index.js. Feel free to create an issue following the issue template for a feature request. Given that you have a solution to the issue you'd like to propose.

**Comment by kate-hall** [comment]
@timneutkens, can you relink the current workaround mentioned in this comment: https://github.com/zeit/next.js/issues/4502#issuecomment-393274989 ?

**Comment by nayaabkhan** [comment]
@kate-hall I guess that file is now moved to https://github.com/zeit/next-site/blob/master/www/pages/docs/index.amp.js#L8.
