### ISSUE TITLE
Next Router integration with Redux?

### ISSUE THREAD

**Issue by AiusDa** [zeit/next.js#4503]
There is an integration between Next Router and Redux like react-router-redux?

**Comment by timneutkens** [comment]
There's no need to put the routing information into a redux store. You can just access the route information using `withRouter`. Also please follow the issue template, which shows questions should be posted on https://spectrum.chat/next-js

**Comment by danielr18** [comment]
@AiusDa https://github.com/danielr18/connected-next-router

**Comment by AiusDa** [comment]
Great! Let me try it! Thanks @danielr18

**Comment by danielr18** [comment]
FYI: `getInitialProps` is called before history changes, so you should not read the location state directly from the Redux store there (or elsewhere), as you have `withRouter` HOC.

**Comment by ckeeney** [comment]
Thanks @danielr18 this looks like exactly what I needed.
