### ISSUE TITLE
Wrong imports in with-redux/lib/with-redux-store.js

### ISSUE THREAD

**Issue by julmot** [zeit/next.js#4507]
The 1 and 3 error is important:

![topic](https://user-images.githubusercontent.com/8310677/40796535-b1c6d314-6505-11e8-8de0-3d6e0f586040.png)

https://github.com/zeit/next.js/blob/master/examples/with-redux/lib/with-redux-store.js#L1

Also `import React from 'react';` is missing.

**Comment by timneutkens** [comment]
Feel free to send a pull request.
