### ISSUE TITLE
next-page-transitions example broken

### ISSUE THREAD

**Issue by julmot** [zeit/next.js#4514]
Just run the documented installation steps. What you'll get:

> Error: Cannot find module './dist/server/build/babel/preset'

![topic](https://user-images.githubusercontent.com/8310677/40839504-2ff0ea0c-65a3-11e8-8459-d2d984786552.png)

**Comment by timneutkens** [comment]
You have to manually build Next.js if you clone the repository using `yarn release` or `yarn build`.
