### ISSUE TITLE
with-react-intl example is showing fallback messages on client side render

### ISSUE THREAD

**Issue by tobitos** [zeit/next.js#4516]
# Examples bug report

## Example name
with-react-intl

## Describe the bug
In a production build of the with-react-intl example the client side rendering doesn't seem to respect the browser locale and falls back to the default messages. The server side rendering is correctly rendering all the messages in the browser's locale.

## To Reproduce
1. Create a with-react-intl example project (`npx create-next-app --example with-react-intl with-react-intl-app`)
2. `npm run build`
3. `npm run start`
4. Set your browser language settings to French
5. Access the index page at localhost:3000
6. Notice that all messages are correctly displayed in French
7. Click on "Accueil" link in Navigation
8. Observe all messages switch to their English counterparts

## Expected behavior
The messages stay in French.

## Screenshots
SSR: 
![image](https://user-images.githubusercontent.com/509421/40849274-c6d5726c-65c1-11e8-9cdf-06b1413f5496.png)

CSR: 
![image](https://user-images.githubusercontent.com/509421/40849286-d1177c34-65c1-11e8-94e2-27d37fad5382.png)

## System information
 - OS: macOS 10.13.2
 - Browser: Firefox 60.0.1
 - Version of Next.js: 6.0.3

## Additional context

The issue seems to be in line 26 of `PageWithIntl.js`: 

`const {locale, messages} = req || window.__NEXT_DATA__.props`

The `locale` and `messages` props are actually one level deeper on `props.pageProps`, so the line should be changed to:

`const { locale, messages } = req || window.__NEXT_DATA__.props.pageProps`

This fixes the issue. I've created a PR for this: #4517

**Comment by leyius** [comment]
const {locale, messages} = req || window.__NEXT_DATA__.props.initialProps.pageProps;
