### ISSUE TITLE
Build for production with custom routing server

### ISSUE THREAD

**Issue by deanmcpherson** [zeit/next.js#452]
Hey there,

Following the example in https://github.com/zeit/next.js/blob/master/examples/custom-server/server.js I managed to get custom routing working with wildcards, parameters etc. 

How would you then go about building the app for production? Simply flagging false for dev does not minify the codebase or link out to the CDN for the base library, and running next build before running the custom server doesn't seem to function either.

**Comment by nkzawa** [comment]
As far as I tested, `dev: false` and `next build` work fine.
Let me know how did you actually setup it.

**Comment by rauchg** [comment]
@deanmcpherson keep in mind CDN has been removed from `master` to create base builds

**Comment by deanmcpherson** [comment]
Wow, thanks for the fast reply. I might have a version issue or something, as I originally installed via npm, but then installed via master, what's the recommended way of installing this at the moment?

**Comment by deanmcpherson** [comment]
Ok, I created a custom pages/_document and it now correctly builds and loads the server rendered page. The only strange part now is http://localhost:3000/_next/main.js never resolves (though the common.js does). No errors are thrown, it just hangs for two minutes and then fails.

**Comment by deanmcpherson** [comment]
Never mind! It was a version clash, the global cli was still running the npm version for build, which wasn't generating all the files needed by the local master version. All working now!
