### ISSUE TITLE
Index files for sub pages don't get rendered

### ISSUE THREAD

**Issue by ooade** [zeit/next.js#4521]
# Bug report
Index files for sub pages don't get rendered

## Describe the bug
I created a directory, for instance, named "book" in `pages`, and an index.js file in that directory. When I tried navigating to /book, nothing get rendered, says page don't exist. Creating a book.js will work perfectly, I just felt its nice to have an index file since i'll be having more pages in that sub directory

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to '/pages'
2. Create 'book' folder
3. Create an index.js file

## System information
 - OS: Debian 9
 - Browser (if applies): Chrome 67
 - Version of Next.js: 6.0.3

**Comment by timneutkens** [comment]
This is already supported + we have tests for it. I've also followed your steps to reproduce but it worked fine 🤔 

```
tree pages
pages
├── book
│   └── index.js
└── index.js
```
