### ISSUE TITLE
some expectation about router

### ISSUE THREAD

**Issue by liumin1128** [zeit/next.js#4523]
With regard to next/router, the current router will cause the entire page redraw when the page is switched, including the common part of two pages, which makes it very difficult to achieve the animation when the page is switched.

In addition, when the page is switched, it is necessary to wait for the downloaded resources. There is no feedback in the process, and the page will pause in this place until the new page is loaded. I hope I can jump to the new page, even if it only shows a loaded animation.

**Comment by timneutkens** [comment]
You can use https://github.com/zeit/next.js#custom-app to solve both. Also please follow one of the issue templates. This is not a bug/feature request. So it should be posted on https://spectrum.chat/next-js
