### ISSUE TITLE
react-icons big portion from common.js

### ISSUE THREAD

**Issue by khakestani** [zeit/next.js#4527]
In Analyze view, react-icons in my project is a big part of common.js file while the just limited number of icons used in all of my project pages.

How can I get rid of this problem?
![image](https://user-images.githubusercontent.com/33417289/40885987-726777c2-6745-11e8-909c-cedaed5bfc1e.png)

**Comment by timneutkens** [comment]
react-icons is not part of Next.js. I guess the solution is using a smaller library.

Also, this is not a bug/feature with Next.js, so following the issue template this question should be posted on https://spectrum.chat/next-js
