### ISSUE TITLE
CSS modules are not included in main CSS bundle while using dynamic import

### ISSUE THREAD

**Issue by ba1uev** [zeit/next.js#4537]
I created simple next app which detects type of user devise (in each file in 'pages' directory) and returns a specific component depending on it. This app uses CSS-mudules provided by `@zeit/next-sass` plugin. It also uses dynamic import to implement javascript bundle splitting for desktop and mobile versions of app.

But styles of these two component trees (Desktop & Mobile) are not included in the main css bundle when I use dynamic import instead of normal

How can I fix it? May be it's not the best way to split desktop and mobile bundles of next-based app?

```javascript
// next.config.js

const withSass = require('@zeit/next-sass');

module.exports = withSass({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: "[path]__[local]",
  }
});
```

```javascript
// pages/index.js

import dynamic from 'next/dynamic';
const Mobile = dynamic(import('components/Mobile'));
const Desktop = dynamic(import('components/Desktop'));

class Index extends Component {

  static async getInitialProps({ req }) {
    return { userAgent: req ? req.headers['user-agent'] : navigator.userAgent };
  }

  render() {
    return (
      <div>
        <Head>
          <link rel="stylesheet" href="/_next/static/style.css" />
        </Head>
        {isMobile(this.props.userAgent) ? (
          <Mobile/>
        ) : (
          <Desktop/>
        )}
      </div>
    );
  }
};
```

**Comment by timneutkens** [comment]
This is not an issue with Next.js. But with next-plugins. There's an issue there already.
