### ISSUE TITLE
with-prefetching example not working on Windows. 

### ISSUE THREAD

**Issue by bestwestern** [zeit/next.js#454]
I cloned the project, npm install in 'examples\with-prefetching', npm run dev and I get:

Module build failed: ReferenceError: Unknown plugin "transform-async-to-generator"

**Comment by FrancosLab** [comment]
You'll need to `link` the local repo as well into the example.

Inside master local repo
`npm install` 
`npm link`

`cd examples\with-prefetching`
`npm i`
`npm link next`

and you should be good!

**Comment by arunoda** [comment]
Thanks @FrancosLab.
I think when we do npm install, it might not installing the beta versions.
I'll check what we can do about it.

And having a hacking guide it pretty useful.

**Comment by bestwestern** [comment]
Thanks - it helped - but now I get 
'This dependency was not found in node_modules:
* next/prefetch
Did you forget to run npm install --save for it

**Comment by arunoda** [comment]
I hope now everything will work fine.
See: https://github.com/zeit/next.js/tree/master/examples/with-prefetching

**Comment by bestwestern** [comment]
It's still a problem.
I tried creating VirtualBox with Ubuntu, installed Node, and then
curl https://codeload.github.com/zeit/next.js/tar.gz/master | tar -xz --strip=2 next.js-master/examples/with-prefetching

cd with-prefetching
Then
npm install
npm run dev

But I still got this error:
next/prefetch
Did you forget to run npm install --save for it

**Comment by rauchg** [comment]
@bestwestern re-opening it. Thanks for the repro instructions, sorry for the issue!

**Comment by thebetterjort** [comment]
Still having this issue. After running yarn add next/prefetch

**Comment by arunoda** [comment]
@thebetterjort You need to add `^2.0.0-beta` to the next field in package.json dependency.
Then you need to do `yarn upgrade`

**Comment by thebetterjort** [comment]
Thanks resolved.
