### ISSUE TITLE
Typescript private/public constructor shorthand is not possible

### ISSUE THREAD

**Issue by Bennit** [zeit/next.js#4542]
# Question about Next.js - with-typescript example

The problem is about using the shorthand notation to assign private/public object properties through private/public/protected constructor argument modifiers, which is perfectly valid typescript since a long time.

I've provided an example page using private/public constructor argument modifiers that do not seem to work in whatever typescript setup is included in @zeit/next-typescript.

You can find the example in my fork here:

https://github.com/Bennit/next.js/blob/canary/examples/with-typescript/pages/test.tsx

Is there a way to get this specific feature of typescript working? I'm thinking babel config or tsconfig extension.

It makes me wonder if there are other hidden things I shouldn't do in typescript to work in next.js's framework

Kind regards
Ben

**Comment by timneutkens** [comment]
next-typescript just implements @babel/typescript, so you can file an issue on the babel repository. If you want to use the older `ts-loader` downgrade next-typescript to a version below 1.0.0.
