### ISSUE TITLE
Route masking using pushRoute()

### ISSUE THREAD

**Issue by ukvaddi** [zeit/next.js#4544]
# Feature request
How can we handle route masking using pushRoute?

## Is your feature request related to a problem? Please describe.
link href and as, now become route(), the same will goes to pushRoute(url) api method. But if I want to do Route masking, say I want to create route with both href and as, how can I achieve this with pushRoute() api call. Currently pushRoute() is only accepting urlorname means only href is going down the next/link , but not url masking value. How can I pass "as" down to the nextjs/link?

**Comment by timneutkens** [comment]
`pushRoute` is not part of Next.js, but of next-routes. Which is a community made plugin.
