### ISSUE TITLE
What's the meaning of export static ?

### ISSUE THREAD

**Issue by mydearxym** [zeit/next.js#4549]
hi guys, i know there are some issue talk about static export, but i am still very confused. 

from my understanding , the exported static file should excute `getInitialProps` every time when req comes, but currently the `getInitialProps` method in exported files is __only triggered  in build time__? 

the official example [with-static-export](https://github.com/zeit/next.js/blob/canary/examples/with-static-export/next.config.js), next.config.js export one page of posts to it's own urls, like `http://xyz.com/posts/10`, which is good for SSR. 

but when "posts/10" 's content updated, the exported static "posts/10" is still the old version, we had to export it again ... __it does't make sence__ 

is `export static` only means export "static content" __literally__?
or if there method that i can trigger `getInitialProps` on export static files?

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js#static-html-export

> The way next export works is by pre-rendering all pages possible to HTML. It does so based on a mapping of pathname key to page object. This mapping is called the exportPathMap.

What you're talking about is the default in Next.js, which is not exporting to static HTML and just rendering when a request comes in.
