### ISSUE TITLE
webpack depenancy uglifyjs-webpack-plugin causing build errors - AWS

### ISSUE THREAD

**Issue by dunika** [zeit/next.js#4556]
# Bug report

I am deploying my app to AWS using `docker` and it has started failing on `npm install` due to the following error. 

`aws_beanstalk/staging-app: s/webpack/node_modules/uglifyjs-webpack-plugin > node lib/post_install.js [91m [0mThe command '/bin/sh -c npm install' returned a non-zero code: 1.`

Upon further investigation it looks like it is being caused by `webpack 3.1.0`'s dependency on `uglifyjs-webpack-plugin 0.4.6`. It seems to be a [known issue](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/129)

`webpack` removed its dependency on `uglifyjs-webpack-plugin` in `webpack 3.4.0`. Updating `webpack` seems like a possible fix but I'm not sure what the repercussions would be in relation to `next` 

## System information
Docker image:  `64bit Amazon Linux/2.10`
`node 8.11.2`
`npm 6.1.0`
`next 6.0.3`

**Comment by timneutkens** [comment]
I don't think this is an issue with Next.js: https://github.com/zeit/next.js/blob/canary/package.json#L105

We're already on 3.10.0, and uglifyjs-webpack-plugin is a dependency.

**Comment by dunika** [comment]
Yes I'm not sure if I was clear but the issue is being caused by the fact that next is using webpack 3.1.0

**Comment by dunika** [comment]
Oh I had written originally 3.1.0 instead of 3.10.0 sorry for the confusion
