### ISSUE TITLE
getInitialProps not executing after Router.push

### ISSUE THREAD

**Issue by boriswexler** [zeit/next.js#4557]
I am using Router.push to trigger a page transition from a front end rendered component (when the user clicks a button). My code is:
` Router.push('/', '/')`
Yet when the homepage loads, getInitialProps doesn't get called (inserting debug output in it yields no output on the backend console). Any suggestions as to what might be causing this, or could it be a bug. I need to trigger a hard SSR reload so I can access the cookies after a user has logged in.

Thanks.

**Comment by timneutkens** [comment]
Please provide a reproduction. And follow the issue template.
