### ISSUE TITLE
Error handling 404

### ISSUE THREAD

**Issue by masiya255** [zeit/next.js#4561]
Hello, friends ! How to correctly handle 404 errors when entering the page address incorrectl ? I attach a screenshot of the page instead of which I need to make my own.

![image](https://user-images.githubusercontent.com/11834317/41148250-339016c4-6b11-11e8-8631-0470f7894863.png)

**Comment by cherniavskii** [comment]
@masiya255 
Follow [Next.js docs](https://github.com/zeit/next.js#custom-error-handling)

**Comment by timneutkens** [comment]
Thanks for the reply @cherniavskii 👍 you're right, use `_error.js`

**Comment by masiya255** [comment]
@cherniavskii Thanks, bro !
