### ISSUE TITLE
Page is loading slowly or 500 on fetching page

### ISSUE THREAD

**Issue by gitsad** [zeit/next.js#4567]
# Bug report
Page is loading slowly or 500 on fetching page
Development is almost impossible

## Describe the bug
Page is loading slowly or sometimes at initial loading has permission errors to `ROOT`/.next/bundles/pages/index.js
Hot reload also works slowly. I have to wait 10-20 sec to see changes.

## To Reproduce
It happened when rebooted my computer. I do not know why I'm facing this issue. I had this before one time but after one day and some updates which includes my computer software issue seemed to be solved from my point of view.

## Expected behavior
Working hot reloading.
Fast loading page.

## Screenshots
![screen shot 2018-06-08 at 13 21 26](https://user-images.githubusercontent.com/13887724/41155573-e2d88492-6b1e-11e8-962a-22e6cd94384a.png)

## System information
- OS: MacOS High Sierra 10.13.5
- I've only checked on Chrome and Firefox but I think the browser is not a case in this issue. 
- Version of Next.js: 5.1.0

**Comment by gitsad** [comment]
I have tried solutions mentioned in #3735. None of these works for me.

**Comment by timneutkens** [comment]
We can't really help without a full reproduction. Restarting my laptop won't make this issue show up for me 😅

**Comment by gitsad** [comment]
😿
