### ISSUE TITLE
Polyfill documentation

### ISSUE THREAD

**Issue by andrewmclagan** [zeit/next.js#4572]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently there is no clear guidelines on implementing polyfils for browsers. There exists examples to polyfill with `core-js` although there also exists examples to use `.babelrc` with the `env` preset to support older browsers.

There is allot of confusion and issues around this topic.

## Describe the solution you'd like

A clear section in the documentation that describes using `.babelrc` and the `env` preset to polyfill older browsers.

## Additional context

We ([ethical-jobs](https://github.com/ethical-jobs)) would be happy to write up a PR / example to address this issue if people think its needed.

**Comment by timneutkens** [comment]
So to explain:
Next.js supports ie11 and all modern browsers out of the box without polyfills.

The only time you'd need a polyfill is when you are pulling in an external dependency which is using methods that should be polyfilled in ie11/etc, this is what the `with-polyfill` example shows. So basically we'd have to document that specific part. I'd be super happy to take in a PR with documentation around this if you're willing to write it up 🙏

**Comment by andrewmclagan** [comment]
Sure I will try and get one fo the team to do this some time next week.

**Comment by andrewmclagan** [comment]
PR is up at https://github.com/zeit/next.js/pull/4601

**Comment by sheerun** [comment]
btw. this is false claim this is fixed: https://github.com/zeit/next.js/issues/5783

Polyfills on native objects like `[].includes()` are not handled by current setup

**Comment by timneutkens** [comment]
I'm not sure what's false here, [my comment](https://github.com/zeit/next.js/issues/4572#issuecomment-395960145) says exactly what your issue describes.

> The only time you'd need a polyfill is when you are pulling in an external dependency which is using methods that should be polyfilled in ie11/etc

**Comment by timneutkens** [comment]
Next.js by default with no external dependencies works fine in ie11.

**Comment by sheerun** [comment]
@timneutkens My fault, sorry!

**Comment by chirag04** [comment]
@timneutkens - our app is crashing in IE because of this line in nextjs router: https://github.com/zeit/next.js/commit/b88addfcd5d3d305664ff95a709b4a4df7e0cbcf#diff-49f9285928f23ee1231af5aa2534c70aL66

looks like includes is not polyfilled by default
