### ISSUE TITLE
add google place library for a page 

### ISSUE THREAD

**Issue by saurabhSiddhu** [zeit/next.js#4576]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js
I wanted to add google place autocomplete in my project. But not  able to figure out where to add <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places"></script>

**Comment by timneutkens** [comment]
As per the issue template.

> Questions should be posted on spectrum.chat/next-js
