### ISSUE TITLE
tutorial is broken

### ISSUE THREAD

**Issue by dcsan** [zeit/next.js#4577]
this page in the tutorial:

https://nextjs.org/learn/basics/create-dynamic-pages/passing-data

![image](https://user-images.githubusercontent.com/514002/41203491-50e51d5a-6d0a-11e8-9db4-e242b6842f08.png)

uses

       <h1>{props.url.query.title}</h1>

but that throws an error:

utils.js:26 Warning: the 'url' property is deprecated. https://err.sh/next.js/url-deprecated

https://github.com/zeit/next.js/blob/master/errors/url-deprecated.md

the deprecation page suggests some options that I can't seem to get to work

```js
const Story = (props) => {
  console.log("props", props)
  // console.log("router", router)
  const {router} = props
  console.log("router", router)
```

![image](https://user-images.githubusercontent.com/514002/41203520-d0ed3c94-6d0a-11e8-91d3-4810c2d8d9d8.png)

result: tutorial = broken, throws errors.

**Comment by dcsan** [comment]
FWIW props (in the tutorial flow) does seem to have a URL property and nothing else.
so basically its going to be deprecated in favor of sweet FA? this is a really harsh example of JS churn.

![image](https://user-images.githubusercontent.com/514002/41203542-296ac9c2-6d0b-11e8-98bc-056d3cc65633.png)

**Comment by timneutkens** [comment]
Please keep in mind that while the warning is produced, the functionality remains working perfectly, and it's not going to be removed anytime soon.

The reason it's going away is that we want to make things very predictable and explicit. Having a magical `url` property coming out of nowhere doesn't aid that goal.

That said, the alternative is very trivial:

```
import {withRouter} from 'next/router'
import Layout from '../components/MyLayout.js'

const Page = withRouter((props) => (
    <Layout>
       <h1>{props.router.query.title}</h1>
       <p>This is the blog post content.</p>
    </Layout>
))

export default Page
```

I've updated the specific pages mentioning the magic "url" property to now show the "withRouter" use case:

https://nextjs.org/learn/basics/create-dynamic-pages/passing-data

**Comment by dcsan** [comment]
OK thanks! easy if you know the incantation 🗡 

FWIW i'm on  `next.js v6.0.3` and it says this will be removed in v7
