### ISSUE TITLE
I cannot setup next.js

### ISSUE THREAD

**Issue by Hitoshi5858** [zeit/next.js#4578]
#I did following tutorial. Then command 'npm run dev', error is occurred.
https://github.com/zeit/next.js

## Describe the bug
ERROR  Failed to compile with 1 errors                                                                                                                                             

 error  in ./pages?entry

Syntax Error: Unexpected token (6:21)

  4 | // };
  5 | 
> 6 | export default () => <div>Welcome to next.js!</div>
    |                      ^
  7 | 
 @ multi ./pages?entry

## Screenshots
<img width="639" alt="2018-06-11 2 02 46" src="https://user-images.githubusercontent.com/24564510/41204133-94d14f6e-6d1b-11e8-89a7-4ebc0d54d952.png">
<img width="895" alt="2018-06-11 2 03 22" src="https://user-images.githubusercontent.com/24564510/41204138-a4b93748-6d1b-11e8-8f20-bcc750ab918b.png">
<img width="922" alt="2018-06-11 2 03 41" src="https://user-images.githubusercontent.com/24564510/41204143-b16cd580-6d1b-11e8-9c58-cf30e8a37f30.png">

## System information
 - OS: macOS
 - Browser (if applies) chrome
 - Version of Next.js: 4.2.3

### ------index.js-----------
export default () => <div>Welcome to next.js!</div>
-------------------------

------package.json------
{
  "name": "kickstart",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "mocha",
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fs-extra": "^6.0.1",
    "ganache-cli": "^6.1.0",
    "mocha": "^5.2.0",
    "next": "^4.2.3",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "solc": "^0.4.24",
    "truffle-hdwallet-provider": "0.0.3",
    "web3": "^1.0.0-beta.26"
  }
}
------------------------------

**Comment by timneutkens** [comment]
Looks like you're on a very old version of Next.js, 4.2.3, we're currently at Next.js 6. Let's start by upgrading. But I'm pretty sure that's not the issue.

What I suspect is that you have a `.babelrc` somewhere in the upwards directory tree. Like in your home directory for example. Next will show a message similar to `"using custom .babelrc: <path>"`.

**Comment by Hitoshi5858** [comment]
@timneutkens Thank you very much for your quick response.
I upgrade Next.js and delete my .babelrc file, it works!!
Really appreciate it.

**Comment by timneutkens** [comment]
Great 🙌 The only time I saw this happen is with a `.babelrc` file somewhere 👍
