### ISSUE TITLE
Typescript custom server example is broken

### ISSUE THREAD

**Issue by AleksandarAleksandrov** [zeit/next.js#4580]
# Typescript custom server example is broken

## Example name
custom-server-typescript

## Describe the bug
When launching the demo with `yarn run dev` the following error is displayed:
```js
D:\temp\custom-server-typescript> npm run dev
> @ dev D:\temp\custom-server-typescript
> nodemon server/index.ts

[nodemon] 1.17.5[nodemon] to restart at any time, enter `rs`
[nodemon] watching: server/**/*.ts
[nodemon] starting `ts-node --compilerOptions '{"module":"commonjs"}' server/index.ts`
undefined:1
'{module:commonjs}'
^

SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parse (D:\temp\custom-server-typescript\node_modules\ts-node\dist\index.js:53:25)
    at Object.<anonymous> (D:\temp\custom-server-typescript\node_modules\ts-node\dist\_bin.js:92:30)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
[nodemon] app crashed - waiting for file changes before starting...

```

## To Reproduce
Clone the example repository, install the dependencies and type `yarn run dev`

## Expected behavior
The example shoud work.

## System information
 - OS: [Windows 10]
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [latest]

**Comment by billnbell** [comment]
+1

**Comment by AleksandarAleksandrov** [comment]
Tried the answer here - https://github.com/zeit/next.js/pull/4543

Namely: `npx babel-upgrade --write` which added `babel-core@^7.0.0-bridge.0`
but this didn't have any effect either 😞

**Comment by AleksandarAleksandrov** [comment]
It seems the problem was from the fact that windows power shell escapes the `"` character.
For windows the `nodemon.json` file should be :

```json
{
    "watch": [
        "server/**/*.ts"
    ],
    "execMap": {
        "ts": "ts-node --compilerOptions {\"\"\"module\"\"\":\"\"\"commonjs\"\"\"}"
    }
}
```

PS: Please close the issue.

**Comment by rohmanhm** [comment]
Is this issue resolved?
If yes, now you can close the issue then.
