### ISSUE TITLE
When the network is slow, then you run `npm run dev`...

### ISSUE THREAD

**Issue by minooo** [zeit/next.js#4581]
As we know, everytime you run `npm run dev` in next.js project.
The default first work is to "checking updates",
But when your network is very slow,  the work of "checking updates" can take an hour! 
You can do nothing except wait!

**Comment by timneutkens** [comment]
I actually already implemented a timeout in update-check, just had to upgrade it in Next.js 👍

**Comment by minooo** [comment]
nice
