### ISSUE TITLE
I hope next.js supports hash router in client render。

### ISSUE THREAD

**Issue by minooo** [zeit/next.js#4586]
# Feature request
As you know, next.js can server render and client render。
I had to make a next.js project  to be a client render with hash router for some reasons。
I dot't find the way to make it.
Any ideas?

**Comment by timneutkens** [comment]
We currently don't support hash routing as it doesn't work with pre-rendering pages. In theory, you could build something on top of the router to handle hash routing, as the router does support pushing to hashes and shallow rendering.

**Comment by trusktr** [comment]
> as it doesn't work with pre-rendering pages

So support it and put a note in the docs that it disabled pre-rendering pages. 👍
