### ISSUE TITLE
Client-side Dynamic Routing bug in combination with Static Export

### ISSUE THREAD

**Issue by wkentdag** [zeit/next.js#4590]
# Bug report

## Describe the bug

I have a single page, `pages/index.js`, that hides/shows 4 modals in response to the `activeSection` query param, with routes aliased like this:

```javascript
// next.config.js.exportPathMap
      '/': { page: '/' },
      '/about': {
        page: '/',
        query: { activeSection: 'about' },
      },
      // ...
```

```javascript
// server.js
server.get('/about', (req, res) => {
    const actualPage = '/';
    const queryParams = { activeSection: 'about' };
    app.render(req, res, actualPage, queryParams);
  });

```

```javascript
// pages/index.js
<Link href="/?activeSection=about" as="/about">
      <a href="/about">About</a>
</Link>
```
In development (the context in which this bug occurs), I'm using an Express server, but for production, I have the project configured to statically export a page for each active section (`/about/index.html`, `/store/index.html`, etc) so I can serve it on S3 and have SEO for each page. 

When I click on a `Link` to a dynamic route, the page doesn't re-render and my UI doesn't update.  If I remove the `exportPathMap` key from my `next.config.js`, dynamic routes *do* work.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Check out my [sample project](https://github.com/wkentdag/next-bug)
2. `git clone https://github.com/wkentdag/next-bug`
3.`cd next-bug && npm i && npm start`
4. Navigate to [localhost:3000](localhost:3000), click on nav links, observe that nothing happens
5. Quit server, comment out `exportPathMap` key from `next.config.js`, restart server
6. Note that routes update as expected when clicked
7. uncomment `exportPathMap` and run `npm run export && npm run serve`, note that dynamic routing works in this context

## Expected behavior
I expect the route to update and UI to re-render when links are clicked in any context (server-side, static, or client-side)

## System information
 - OS: macOS
 - Browser: chrome
 - Version of Next.js: `6.0.3`

## Additional context

* Once I export the project as static, dynamic links *do* work as expected
* If you directly link to a dynamic route, e.g. `localhost:3000/about`, the page will display correctly, and it will *also* update whenever you click on a link on the page 🤔 
* I thought I had the same problem described in https://github.com/zeit/next.js/issues/3257 but as you can see I already am using `getInitialProps` and have isolated my issue to the static export thing.

**Comment by ijjk** [comment]
This appears to be working fine in the latest version of Next.js so I am going to close this issue. If you are still having trouble with this feel free to comment.
