### ISSUE TITLE
 [BABEL] Unknown option: .preset-env

### ISSUE THREAD

**Issue by Popugune** [zeit/next.js#4595]
https://github.com/zeit/next.js#customizing-babel-config

in babelrc i wrote like in doc, but i get error about  [BABEL] Unknown option: .preset-env

```
"production": {
      "presets": ["next/babel", {
        "preset-env": {
          "targets": {
            "browsers": ["last 2 versions", "safari >= 7"]
          }
        }
      }]
    },
```

**Comment by chilijung** [comment]
@Popugune do you have the answer to this question? I also got this error thanks!

**Comment by timneutkens** [comment]
Providing options is done through having a nested array in babelrc.

So it should be:

```
"presets": [
  ["next/babel", { "preset-env": { "targets": { "browsers": ["last 2 versions", "safari >= 7"] } } }]
]
```
