### ISSUE TITLE
svg-components example fails with latest babel-plugin-inline-react-svg

### ISSUE THREAD

**Issue by Zertz** [zeit/next.js#4599]
# Examples bug report

## Example name
svg-components

## Describe the bug
Example does not work with `^0.2.0` which currently resolves to `0.5.2`

```
Module parse failed: Unexpected token (39:6)
You may need an appropriate loader to handle this file type.
```

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Run the example with the latest version of `babel-plugin-inline-react-svg`

## Expected behavior
It should work

## System information
 - OS: macOS 10.13.4
 - Browser: Chrome 67
 - Version of Next.js: 6.0.3

## Workaround
Downgrade to `"babel-plugin-inline-react-svg": "~0.4.0"`

**Comment by PR1YANKPAT3L** [comment]
I just tested the example with babel-plugin-inline-react-svg@0.5.2 and am having no issue with it at all.

**System Information**
- OS: Ubuntu 17.10
- Browser: 66.0.3359.139
- Version of Next.js: 6.0.4-canary.6

**Comment by stramel** [comment]
Just checked `^0.5.2` and `~0.4.0` both failed.

My attempted code looks like `dynamic(import('static/icons/chrome.svg'))`. This did not work.

I tested just doing `import Chrome from 'static/icons/chrome.svg'` and that worked with both `~0.4.0` and `^0.5.2`! However, it is important to me to not import all the SVGs in this component.

**Comment by Zertz** [comment]
This issue is fixed in `6.0.4-canary.*`

**Comment by stramel** [comment]
@zertz Still broken with dynamic imports

**Comment by AikoRamalho** [comment]
What is 6.0.4-canary? A version of next?

**Comment by stramel** [comment]
@aikoramalho yes it is basically the nightly

**Comment by AikoRamalho** [comment]
So everything I have to do is to ""next": "^6.0.4-canary"" in my package.json for this svg_example works?

**Comment by Zertz** [comment]
@AikoRamalho Not quite, `"next": "6.0.4-canary.9",` :)

**Comment by stramel** [comment]
Actually @Zertz, `^6.0.4-canary` will work as well but will resolve to the latest canary build

**Comment by Zertz** [comment]
Oh, awesome! I wasn't aware, thanks 👍
