### ISSUE TITLE
Silently catched error in _app.js getInitialProps

### ISSUE THREAD

**Issue by znarf** [zeit/next.js#4605]
# Bug report

## Describe the bug

When an error is thrown in `_app.js` `getInitialProps` on the client side, the error is silently catched and navigation is broken without any error output.

Why it's a problem? As a developer, if you unfortunately generate an error in `_app.js` `getInitialProps`, you suddenly have a broken navigation and have no idea what's happening and where to look at.

## To Reproduce

1. Go to https://app-getinitialprops-silent-error-gbvspsorhf.now.sh/
2. Click on 'Say Hello?'
4. Not navigating to `/hello`, no error output.

## Expected behavior

Navigating to `/hello` OR error output.

## Source

https://github.com/opencollective/next-issues/tree/master/app-getInitialProps-silent-error

**Comment by timneutkens** [comment]
The reason this happens is that when an error is throw in a normal page, we try to render the error page, but the error page also depends on `getInitialProps` being executed, as you can see here: https://github.com/zeit/next.js/blob/canary/lib/router/router.js#L260-L265

So when an error happens as part of `getIntialProps` in `_app.js` we have to catch it again and render the error page.

**Comment by znarf** [comment]
Thank you @timneutkens. That was fast!

**Comment by timneutkens** [comment]
Thank you very much for the detailed description and reproduction. Makes it way faster to solve issues like this 🙌
