### ISSUE TITLE
ctx.query undefined during dev and using exportPathMap

### ISSUE THREAD

**Issue by remy** [zeit/next.js#4615]
# Bug report

## Description of the bug

The `query` object `undefined`  missing from the `ctx` in `getInitialProps` during development. This causes exceptions to be thrown when expecting an object (rather than undefined).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://next6-queries-kvyvgbrmae.now.sh/?a=b
2. See that the `query` is missing from props.

Note: if the URL shows a 5xx error, it's because Next is running in dev mode on Now, which it doesn't really like! Here's the source for local testing: https://gist.github.com/remy/391923f938629436d671456d3e1234b7

[Source](https://zeit.co/rem/next6-queries/kvyvgbrmae/source) of `pages/index.js`:

```js
const Page = props => <pre>{JSON.stringify(props, '', 2)}</pre>;
export default Page;
```

## Expected behavior

I'd expect to see the page render:

```json
{
  "query": {
    "a": "b"
  },
  "url": {
    "pathname": "/",
    "asPath": "/?a=b"
  }
}
```

## System information
 - OS: macOS
 - Version of Next.js: 6.0.3

## Additional context

I've debugged through the compiled code and I _think_ it's due to the `exportPathMap` being used during development: https://github.com/zeit/next.js/blob/canary/server/index.js#L252-L258

I'm not quite sure how to work out which should win, but if I were to suggest, I'd expect the exportMap.query to merge with the URL query, giving priority to the URL query.

At the very least, it shouldn't be undefined, and I can see in the original server/index.js it tries to default to an empty object, but that isn't getting passed through - see screenshot of generated code:

<img width="966" alt="screen shot 2018-06-16 at 10 43 56" src="https://user-images.githubusercontent.com/13700/41497695-3db85e80-7152-11e8-8f70-f1c2e4e5dfbc.png">

**Comment by timneutkens** [comment]
Can you try `next@canary`? I don't believe that fix has been released yet (top of my mind)

**Comment by timneutkens** [comment]
> I'm not quite sure how to work out which should win, but if I were to suggest, I'd expect the exportMap.query to merge with the URL query, giving priority to the URL query.

This would actually be unexpected, because when we pre-render using `next export` we only use `exportPathMap` (since we render static HTML).
One thing we might consider is merging and showing a warning for keys not defined in `exportPathMap`

**Comment by remy** [comment]
next@canary also missing `query` object.

**Comment by remy** [comment]
I think what was odd that I hadn't rendered out to static HTML during development, so I didn't expect the config to take priority (WRT query object). It's also definitely missing / `undefined` instead of defaulted to emtpy.

**Comment by timneutkens** [comment]
It should definitely default to `{}`

**Comment by remy** [comment]
Correcting my earlier comment: it *does* default in canary.

**Comment by timneutkens** [comment]
> One thing we might consider is merging and showing a warning for keys not defined in exportPathMap

I'm willing to take in a pull request for this 👍

**Comment by teleginzhenya** [comment]
I would like to take this one :)
