### ISSUE TITLE
request handler effect on component's event handlers?

### ISSUE THREAD

**Issue by escKeyStroke** [zeit/next.js#4632]
Hi,
I made a [working repo](https://github.com/escKeyStroke/whatsnexthandler) just to illustrate this issue.
I don't know if to call it an "issue", as it's just a behavior I was not expecting (I'm not a web development specialist) and I couldn't find anything in the [docs](https://nextjs.org/docs/) that refers to it.
It's about
```javascript
const app = next({ dev:true })
const handle = app.getRequestHandler()
```
In the repo I linked above, see that the event handler `onSubmit` of the component in `/pages/index.js` doesn't work when the line `handle(req, res, parsedUrl);` is commented out in `./server.js`.

node.js version 10.4.0

Files copied here for convenience:
`./pages/index.js`
```javascript
export default () => 
  <form onSubmit={e => {
    e.preventDefault();
    alert('submit');
  }}>
    <button type="submit">submit</button>
  </form>
```

`./server.js`
```javascript
const { createServer } = require('http');
const { parse } = require('url');
const next = require('next');
const app = next({ dev:true });
const handle = app.getRequestHandler();



app.prepare().then(() => {
  createServer((req, res) => {
    const parsedUrl = parse(req.url, true);
    const { pathname, query } = parsedUrl;

    if (pathname === '/') {
      app.render(req, res, '/', query);
    }      
    // If you comment out this else clause
    // the submit hanlder will no longer work.
    else {
      handle(req, res, parsedUrl);
    }
    
  }).listen(3000, (err) => {
    if (err) throw err;
    console.log('> Ready on http://localhost:3000');
  });
});
```

**Comment by timneutkens** [comment]
`handle` handles all internal routes. This includes the client side javascript routes (the reason your onSubmit doesn't work), internal routing of the pages directory, handling /static and a few other things like on-demand-entries and hot module replacement / webpack hot middleware in development

**Comment by timneutkens** [comment]
Also noticed your custom server has a bug:

```
if (pathname === '/') {
      app.render(req, res, '/', query);
    } 
```

Should be:

```
if (pathname === '/') {
      app.render(req, res, '/', query);
return
    } 
```

**Comment by escKeyStroke** [comment]
OK I was just copying the code in the [docs](https://nextjs.org/docs/#custom-server-and-routing) (honestly I don't know what's that `return` is for).  But never mind.  Thanks for reply and the info.
