### ISSUE TITLE
Set up https://next.js.org/

### ISSUE THREAD

**Issue by aequasi** [zeit/next.js#4641]
You can reserve the domain at: https://js.org/

All for free :)

**Comment by timneutkens** [comment]
We don't use GitHub pages for hosting the website, we use our own hosting platform: https://now.sh

**Comment by aequasi** [comment]
As long as your site supports CNAME redirects, js.org will most likely support it. Doesn't require GitHub pages:

https://github.com/js-org/js.org/issues/1032
