### ISSUE TITLE
Slow TTFB (Time to First Byte) for a very simple production deployment.

### ISSUE THREAD

**Issue by driglou** [zeit/next.js#4646]
I've created a basic "Hello world example, however when deploying in production mode I am getting slow loading speed, which is mostly accumulated by slow TTFB.
I'm deploying to zeit.co Premium plan.

![network-test](https://user-images.githubusercontent.com/5339578/41750684-e1e9a51e-75c5-11e8-9288-979f00164378.jpg)

Repository for reproduction - https://github.com/driglou/satv

**Comment by timneutkens** [comment]
As you can see here: the TTFB is considerably lower:
https://dfhjdsjfhjdshjfhjhjksdf-ilsvtjqpfn.zeit.sh/

The only changes I made:

- `rm yarn.lock`
- `rm yarn-error.log` (doesn't make a difference, just clean up)
- `rm -rf .next`
- added a `.gitignore` with `.next` as contents

Then I ran

`now`

I made no changes to the code.

**Comment by driglou** [comment]
I've cleaned up, however I am still seeing the same results, while your deployment has indeed a smaller TTFB

**Comment by driglou** [comment]
Additionally I have tried Nextgram example app - https://github.com/now-examples/nextgram
I just downloaded the project and deployed with:
`now --regions bru`

I think it's quite important if there is a possiblity to cut 400ms from TTFB

![ggg](https://user-images.githubusercontent.com/5339578/41842324-237eafce-7873-11e8-9363-cdda4315e2a0.jpg)

**Comment by timneutkens** [comment]
Could you check the latency on http://sfo.now.sh/ and http://bru.now.sh/? Also what location are you testing from?

**Comment by driglou** [comment]
SFO avg. 200-250ms
BRU avg, 50-80ms

I am testing from Romania with 290mb/s internet speed.

**Comment by timneutkens** [comment]
So I've scaled https://satv-tgrbmyzrec.now.sh/ to bru and the TTFB is ~200ms. It seems like the majority is latency 🤔

**Comment by driglou** [comment]
I do not necessary disagree with what you say, however interestingly your example - https://dfhjdsjfhjdshjfhjhjksdf-ilsvtjqpfn.zeit.sh/
gives me around 230ms TTFB with the rest of the loading time being similarly just TTFB being smaller. Makes me wonder....

**Comment by driglou** [comment]
https://ietv-tszrtadfvd.now.sh/ on this one I have region BRU with scale rules min:3 max:3

It's interesting that your examples come out with 200ms and mine with 700ms TTFB time, do you have any suggestions as I am not sure I could get on your examples 200ms if I am getting 700ms on mine due to latency.

Do you have any ideas or suggestions?

**Comment by danbeck** [comment]
I observed the same behavior. For the the static frontpage of my app (Link: https://wwwtest.urteile-gesetze.de/, Premium plan), I got 270ms TTFB. 

I have the impression that there is simply too much load on the zeit.co servers. This makes page-rendering on the server very slow. I will benchmark the rendering-speed this weekend.

**Comment by jhalvorson** [comment]
I'm seeing similar behaviour on SF01, however, my TTFB is consistently 1.5-1.6 seconds

**Comment by robertoaikode** [comment]
Hello! I'm from Chile, I have a spa test in the firebase housing and this load is very fast.

Now, develop another test spa with Next.js that you implement in Zeit hosting (sfo.now.sh) and the first load is always slow :( very slow

**Comment by timneutkens** [comment]
@danbeck your app has a 110ms ttfb for me.

@jhalvorson based on your profile you're from Edinburgh, try scaling to BRU1, it'll avoid a roundtrip halfway around the world.

@robertoaikode what's your deployment url?

@driglou based on `x-now-trace` the deployment you're mentioning (https://ietv-tszrtadfvd.now.sh/) is in SFO1: `x-now-trace: bru1,sfo1`

You can check this using `curl -I https://ietv-tszrtadfvd.now.sh/`

**Comment by jhalvorson** [comment]
Hey, sorry meant to say BRU1, not SFO1. The TTFB is ~350 this morning which is way better than last night (scaled to 2 auto). I'll keep an eye on it and reach out if it gets back to the slower speeds. I presume a Next.js GitHub issue isn't the best place to reach out for Now issues, should that be the Slack channel?

**Comment by timneutkens** [comment]
> I presume a Next.js GitHub issue isn't the best place to reach out for Now issues, should that be the Slack channel?

Yeah, definitely 👍 https://zeit.chat (for anyone coming to this issue)

**Comment by robertoaikode** [comment]
@timneutkens the url is https://propiedadesmussa-ujaidvjqfe.now.sh/

When entering, the first charge always takes up to 1 minute.
When updating, the load is fast.

I re-enter after being inactive for a few hours and the aforementioned is repeated.

**Comment by timneutkens** [comment]
@robertoaikode that's because by default instances freeze. You can read about scaling your app here: https://zeit.co/docs/other/faq#why-does-my-deployment-occasionally-have-long-response-times

**Comment by lluisnieto** [comment]
I'm also experimenting very high latency in Firebase Storage files:

https://i.ibb.co/HrY4CXL/Captura-de-pantalla-2018-11-28-a-les-1-11-55.png

**Comment by timneutkens** [comment]
That's unrelated to Next.js.

I'm going to close this issue since we introduced https://zeit.co/blog/now-2
