### ISSUE TITLE
Question of Server Side Caching

### ISSUE THREAD

**Issue by sarukuku** [zeit/next.js#465]
Does next support any kind of server side caching?
 - a) If it does how can I configure it?
 - b) If it doesn't could something like f.ex. [apicache](https://github.com/kwhitley/apicache) be used with relative ease?

In my use case I'm making quite a few requests to different API endpoints and the server waits for them to return to be able to set the initial state of the application. In minimum I'd like to cache the API responses for some time so that the server wouldn't need to call the API on every request. If caching the whole request result is possible that would be even better.

**Comment by arunoda** [comment]
With Next.js you probably wanna use a your own version of API server.
So, in this case it's up to you to do any caching.

If you are using Next.js [custom server feature](https://github.com/zeit/next.js#custom-server-and-routing), you can do anything you want.
You can even cache SSR pages.

**Comment by sarukuku** [comment]
My API is on a different server and caching there has been taken care of. I'm more interested in implementing caching for SSR pages.

I've read about the custom server feature and understand that it allows me to do pretty much what I want but I'm looking for suggestions. What would work best with next or does it matter from next perspective how I tackle this?

**Comment by arunoda** [comment]
Okay. I think we need an example on SSR caching. I'll work on it.

**Comment by arunoda** [comment]
Check this: https://github.com/zeit/next.js/pull/497

**Comment by sarukuku** [comment]
Excellent!
