### ISSUE TITLE
Environment variables when deploying to production / Fetching Contentful data from client or server

### ISSUE THREAD

**Issue by krothenbaum** [zeit/next.js#4651]
I asked a version of this question on spectrum but didn't get a response.

I've been using Next to port a react project that requires SSR it's been going smoothly until I attempted to deploy the app to Google App Engine (GAE). I need to fetch data from Contentful which requires an API key which can't be exposed. Currently I'm using a custom express server but all Contentful API calls are made client side. I'm using the example webpack config to load my environment variables from a .env file during development which works just fine. For deploying a production build I added my environment variable to the app.yaml as instructed by GAEs docs. The app deploys successful and it starts to load when I open it but then I get an error in reference to my Contentful API key. 

I'm using the env to setup my Contentful client used fetch my Contentful data via `getInitialProps` in my next.js pages as shown in the learn Next docs:

Contentful Client
```
import { createClient } from 'contentful';

const API_SPACE_ID = process.env.CONTENTFUL_SPACE_ID;
const API_TOKEN = process.env.NODE_ENV !== 'production' ? process.env.CONTENTFUL_API_PREVIEW_TOKEN : process.env.CONTENTFUL_API_TOKEN;
const HOST = process.env.NODE_ENV !== 'production' ? process.env.CONTENTFUL_API_PREVIEW_URL : process.env.CONTENTFUL_API_BASE_URL;

const contentfulClient = createClient({
  space: API_SPACE_ID,
  accessToken: API_TOKEN,
  host: HOST,
});

export default contentfulClient;
```

Contentful API Call:
```
import contentfulClient from './contentfulClient';

const getContentByType = async contentType => {
  return contentfulClient
    .getEntries({
      content_type: contentType,
    })
    .then(response => {
      return response.items;
    });
};
```

Questions:
1. Should I fetch data from Contentful using `getInitialProps` on the client or should I setup an API on the server and call that from the client?
2. If fetching the data on the client side is ok, how do I set the environment variables and do so without exposing them?

Thanks so much for the awesome framework.

**Comment by jonespen** [comment]
Afaik the contenful access token does not need to be kept secret if the content is public. You should keep it out of the source code tho, I suggest using nextjs’ config feature. 

If you have private content, you’ll need to create an api endpoint/server, where you keep your key secret, and communicate with that endpoint instead of contentful.

Source: https://www.contentfulcommunity.com/t/should-i-keep-access-tokens-secret/457

**Comment by timneutkens** [comment]
> I've been using Next to port a react project that requires SSR
>  need to fetch data from Contentful which requires an API key which can't be exposed.

Doesn't this mean that you already ran into the same issue with the React project you initially built before moving to Next 🤔

Anyway, @jonespen's suggestions are great, just to throw in a few extra links:
This is the runtime configuration feature he's talking about: https://github.com/zeit/next.js#exposing-configuration-to-the-server--client-side

The suggestion to set up a custom endpoint/microservice is probably a good idea if you don't want to do requests to contentful directly for security reasons. It also could be interesting to do that if you're considering to combine multiple data sources or move to another CMS provider in the future.

**Comment by timneutkens** [comment]
As this answers both questions I'll close this issue.

**Comment by timneutkens** [comment]
Linked to this issue here: https://spectrum.chat/?t=e0cfdcc6-d394-4f73-97bd-35ab71bfa9d3
