### ISSUE TITLE
npm run build hangs forever at 91% percent

### ISSUE THREAD

**Issue by longbkit** [zeit/next.js#4657]
# Bug report

## Describe the bug
I am experiencing a bug with next build that I had been struggling for several days now.

npm run build just hangs around 91% and never finish. 

## To Reproduce

I have remove the code to the minimized version that cause the bug.

Just download the zip file and run the following:
```
npm install
npm run build
```
The build command will hang as could be seen in the below image:
![image](https://user-images.githubusercontent.com/562164/41817942-eced5e6e-77ce-11e8-862d-9a419ed996bb.png)

[next build error.zip](https://github.com/zeit/next.js/files/2130655/next.build.error.zip)
#4647 
## System information
 - OS: [e.g. macOS, Windows]
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [e.g. 6.0.2]

## Additional context
#4647

**Comment by timneutkens** [comment]
I've commented in #4647 it works fine for me based on your reproduction.
