### ISSUE TITLE
`buildId` is set to `undefined` in the custom webpack hook during development builds 

### ISSUE THREAD

**Issue by 3rd-Eden** [zeit/next.js#4664]
# Bug report

## Describe the bug

Issue https://github.com/zeit/next.js/pull/3001 exposed the `buildId` to the custom `webpack` handler that is specified in the `next.config.js` configuration file. The `buildId` will, unfortunately, be
set to `undefined` during development, making it impossible to rely on this value. 

## To Reproduce

1. Create a new next.js app
2. Add `next.config.js` with a `webpack` function:

```js
module.exports = {
  webpack: function (config, data) {
     console.log('buildId', data.buildId);
     return config;
  }
}
```

3. Run the server `dev` script: `npm run dev` and you will see `buildId: undefined`
4. Run the server `build` script: `npm run build` and you will see `buildId: <id here>`

## Expected behavior

The `buildId` should not be set as `undefined`, during development the id `-` is used, and should be provided instead of `undefined`.

## System information

 - OS: [e.g. macOS, Windows] OSX
 - Version of Next.js: [e.g. 6.0.2] latest canary.

**Comment by timneutkens** [comment]
@3rd-Eden good catch, created a pull request to fix it here: #4665
