### ISSUE TITLE
In 

### ISSUE THREAD

**Issue by pkellner** [zeit/next.js#4666]
In the with-redux-sage example, I'm unable to debug into the saga itself.

https://github.com/zeit/next.js/tree/canary/examples/with-redux-saga

I reported the issue to JetBrains (WebStorm) and there response was as follows:

> as far as I can see, this method is indeed executed on server side, but Next.js starts node_modules/next/dist/bin/next-dev  child proceess without debug args (parent process args are not inherited), as a result the process can't be debugged

Is this something that can be fixed on the NextJS side?

**Comment by timneutkens** [comment]
I'm going to close this issue as it's stale.
