### ISSUE TITLE
app.js not found

### ISSUE THREAD

**Issue by diggymon** [zeit/next.js#4668]
# Bug report
<img width="567" alt="screen shot 2018-06-26 at 12 28 38 am" src="https://user-images.githubusercontent.com/40578401/41869924-2a71f7cc-78d8-11e8-83b3-6ced4eaa7c51.png">

## Describe the bug

app.js not found on production, works just fine on locally machine. Very weird.

## To Reproduce

1. Go to TOP-5.IN

## System information
 - Version of Next.js: 2.4.0

**Comment by timneutkens** [comment]
> Version of Next.js: 2.4.0

The latest version of Next.js is 6.0.3. Any issues you're having on 2.4.0 will be fixed in the latest version of Next.js.
