### ISSUE TITLE
Problem with MobX observable array

### ISSUE THREAD

**Issue by delgermurun** [zeit/next.js#4671]
Hello,

This bug occurs with Next.js project. Code works fine with `create-react-app`. So maybe it is specific to Next.js. 

Created [issue](https://github.com/mobxjs/mobx/issues/1596) on MobX's repo, but no response from maintainer. So I basically created copy of above issue.

## Bug description

Observable array member's observable property becomes `undefined` on initialization.

Reproduction repo: https://github.com/delgermurun/mobx-next-issue
Similar code ([sandbox](https://codesandbox.io/s/0y13k12750)) with `create-react-app` works fine.

When you run project and go to http://localhost:3000, you don't see team's name on initial render. But it appears after 2 seconds. If you see `console`, team's name is `undefined`.

But team's name has been initialized before adding to observable array. It should be `tt-name` on initial render.

If you comment out [pages/index.js#L25-L26](https://github.com/delgermurun/mobx-next-issue/blob/master/pages/index.js#L25-L26) these lines it works fine.

Code is based on base [sandbox](https://codesandbox.io/s/v3v0my2370). `TimerView` doesn't observe `AppState`'s `timer`. If you comment out [pages/index.js#L6](https://github.com/delgermurun/mobx-next-issue/blob/master/pages/index.js#L6) and add `this.timer = 0;` this to `constructor`, it fixes this problem too.

BTW our project was working fine (with decorators). Problem occurred when I removed decorators.

Thanks.

**Comment by timneutkens** [comment]
It's configurable, I don't think we should edit defaults.
