### ISSUE TITLE
Error of withRouter 

### ISSUE THREAD

**Issue by xyyjk** [zeit/next.js#4687]
# Bug report

## Describe the bug

Error when using `_app.js` with the `using-with-router` example under ie9 (`router` is undefined), but ie11 is ok

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

https://github.com/xyyjk/next.js/tree/canary/examples/using-with-router

1. npm run build

2. npm run start

3. open http://localhost:3000

## Expected behavior
ie9 without error

### ie9&ie10
![ie9](https://user-images.githubusercontent.com/2508421/42037983-5099ffda-7b1c-11e8-93a8-040de3e86520.jpg)

### ie11
![ie11](https://user-images.githubusercontent.com/2508421/42038031-7b98de4a-7b1c-11e8-8820-604de32139ea.jpg)

## System information
 - OS: Windows
 - Browser IE9、IE11
 - Version of Next.js: latest

## Additional context

If you delete the `_app.js` file then it is OK

**Comment by cherniavskii** [comment]
@xyyjk 
I don't think Next.js supports <IE11 - see https://github.com/zeit/next.js#browser-support.

Maybe it'll work in IE9 with some extra polyfills, but I'm not sure about that.

**Comment by xyyjk** [comment]
@cherniavskii  

I have added polyfill to [index.js](https://github.com/xyyjk/next.js/blob/canary/examples/using-with-router/pages/index.js).

I am currently using a temporary solution, Add the following code to [_app.js](https://github.com/xyyjk/next.js/blob/canary/examples/using-with-router/pages/_app.js#L6-L13) to work properly in IE9:

```js
static childContextTypes = {
  router: PropTypes.object,
};

getChildContext() {
  const { router } = this.props;
  return { router };
}
```

**Comment by hkongm** [comment]
@cherniavskii 
We indeed use `withRouter`, see
https://github.com/xyyjk/next.js/blob/474e451d0440d994ef3b0cc7079a55d0abd32165/examples/using-with-router/components/ActiveLink.js#L25

But, there is `router is undefined` error blew this line, in IE9
https://github.com/xyyjk/next.js/blob/474e451d0440d994ef3b0cc7079a55d0abd32165/examples/using-with-router/components/ActiveLink.js#L10

can we fix this like above reply of xyyjk? and Is there any potential problems with this solution in your experience. 

thanks

**Comment by timneutkens** [comment]
@xyyjk you shouldn’t override the default contextTypes, it’s guaranteed to break

**Comment by xyyjk** [comment]
@cherniavskii  Yes, the Map and Set are already included in the [babel-polyfill](https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.26.0/polyfill.min.js)

**Comment by stevokk** [comment]
@timneutkens We're seeing this issue on IE11 with IE10 compatibility mode activated, I've included all the polyfills required, but now I just keep getting the router passed as undefined using withRouter from next/router. This seems like an upstream issue that can be fixed? Adding the fix from @hkongm worked but I don't really understand the fix itself which is risky.

Can we get some closure on the recommended approach for this?

**Comment by xyyjk** [comment]
Next.js 7

```
  static childContextTypes = {
    headManager: PropTypes.object,
    router: PropTypes.object
  }
```
