### ISSUE TITLE
Next 6 with Babel 7 beta

### ISSUE THREAD

**Issue by genox** [zeit/next.js#4691]
Hi,

This is more a general question than an issue, apologies.

I run next with typescript (I honestly don’t think that this is far fetched or even an exotic combination) and since the dependency bump to Babel 7 beta, some of the typescript features my project depends on don’t work anymore. Some of the Babel language plugins just aren’t there yet and it is confusing. 

Don’t take this the wrong way, but why do you guys depend on a beta version (outdated at that) for one of the key components?

I love how you keep the pace up with canary releases et al, but I don’t think Babel 7 is ready yet for prime time, especially in regards to certain TS language features. 

The “with-typescript” example works fine, but it’s also super trivial. This shouldn’t be a measurement to determine the level of stability.

By hey, just my five cents. :-)

Oliver

**Comment by jaydenseric** [comment]
Babel v7 is a must, but it certainly should be up to date, which it is not. Babel is pinned at `7.0.0-beta.42`, when latest is `7.0.0-beta.51`! There have been [lots of important bugfixes, etc](https://github.com/babel/babel/releases).

**Comment by genox** [comment]
See https://github.com/zeit/next.js/issues/4707

**Comment by genox** [comment]
Well, here's the answer: #4733
And here's the progress: https://github.com/babel/babel/milestone/15

**Comment by genox** [comment]
PSA: Babel 7 entered RC stage, so we should soon be able to see a new canary version with bumped Babe dependencies. Looking forward :D

https://github.com/babel/babel/releases
