### ISSUE TITLE
Router. This page could not be found.

### ISSUE THREAD

**Issue by markolofsen** [zeit/next.js#4692]
# Question about Next.js
I'm using next-router.
Strange, when I click by the <Link> page working perfect, but if I trying open Link directly got an error `This page could not be found.`

**routes.js**
```
const nextRoutes = require('next-routes')
const routes = module.exports = nextRoutes()
routes.add('offer', '/offer/:slug')
```

**pages/index.js**
```
import {Link} from '../routes'
<Link route='offer' params={{ slug: item.slug }}><a>{item.title}</a></Link>
```

**pages/offer.js**
Render....

**Comment by timneutkens** [comment]
Looks like you didn't add a custom server. `next-routes` is a community plugin so I'm going to close this issue.
