### ISSUE TITLE
i18next — Replace lng=en to /en/

### ISSUE THREAD

**Issue by markolofsen** [zeit/next.js#4696]
**Next.js**
Example source: [https://github.com/zeit/next.js/tree/canary/examples/with-react-i18next](https://github.com/zeit/next.js/tree/canary/examples/with-react-i18next)
What's best way for replacing lang-param in url from `?lng=en` to `/en/`
Necessary for ssr till load the page
**Default:** http://localhost:3000/catalog?lng=en
**Need:** http://localhost:3000/en/catalog

**Comment by timneutkens** [comment]
As per the issue template questions should be posted on spectrum.chat/next-js

**Comment by stramel** [comment]
https://spectrum.chat/next-js?thread=31adf3bd-8711-4bd1-91b7-04b598fae291
