### ISSUE TITLE
Have non-route file inside pages?

### ISSUE THREAD

**Issue by AlexanderIgnacz** [zeit/next.js#4699]
I know all files inside `pages` folder create route(path)s automatically. I'm going to add `style.js` file to all pages so that main code and styles are separated each other. This is what I'm going to do:

```
app/pages/page1/index.js
app/pages/page1/style.js
app/pages/page2/index.js
app/pages/page2/style.js
...
```

This should create unnecessary routes - `/page1/style`, and `/page2/style`.

How can I ignore these style files to create route?

**Comment by timneutkens** [comment]
You shouldn't put component files inside the pages directory. Every file inside `pages` is considered a publicly accessible route.
