### ISSUE TITLE
Using <Link> or <a> to link to index.html or index.php of local projects

### ISSUE THREAD

**Issue by AmnonSkladman** [zeit/next.js#4701]
# I am trying to link to a project on my server that uses plain HTML and CSS.
# I am also trying to link to another project, which is written in PHP.

It doesn't have index.js as it's not build in NextJS, but I still want to link to it to it. However, I keep getting ```404: Page Not Found```. The console says: ```Client pings, but there's no entry for page: [path here]/index.html```.

```
<div className="projLink">
    <Link href="../projects/clients/woolifox/index.html">
        <a>See More</a>
    </Link>
 </div>
```

```
<div className="projLink">
    <a href="../projects/clients/woolifox/index.html">See More</a>
 </div>
```

```
 <div className="projLink">
    <a href="../projects/databases/cats/index.php">See More</a>
</div>
```

I know for a fact that the file is there, and I've run ```npm run build``` too.

**Comment by timneutkens** [comment]
Taken directly from the issue template:

```
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js
```
