### ISSUE TITLE
Zones with Custom Server

### ISSUE THREAD

**Issue by TheGesticulator** [zeit/next.js#4702]
I am using zones for an application I am working on and it works great until I attempt to use a custom server so I can do custom routing. You can easily reproduce this problem by cloning the with-zones example project and using a custom server in either of the applications. 

You will get a 404 error for any page/route you setup under the custom server zone. I've encountered this issue in nginx and micro. 

It looks like a problem with next bundling? The .next folder is being ejected under the project root instead of the zone application root. Has anyone else encountered this? Possible workarounds? Thanks.

**Comment by timneutkens** [comment]
>  The .next folder is being ejected under the project root instead of the zone application root.

I'm not sure what you mean by this, can you give an example? 

> You will get a 404 error for any page/route you setup under the custom server zone. I've encountered this issue in nginx and micro.

At ZEIT we run multiple custom servers in zones, which works fine when correctly configured (`assetPrefix`)

Also, this should actually be posted on spectrum.chat/next-js, as it's a question, please follow the issue template next time.

**Comment by Enalmada** [comment]
For anyone else having trouble with zones and custom server, keep this in mind: 
* "npm install" is technically required for each zone.  node will look up the file tree for missing dependencies and the with-zones-app example seems to work without doing npm install on each zone without custom server but you will start to have errors with custom server.
* Each "zone" is just a normal next.js project that knows nothing about other zones.  Zone really isn't a next.js feature at all...NOW provides a convenient way of aggregating multiple next.js projects under same domain name, but there is no next.js magic for "zone" feature.  The micro-proxy is really the secret sauce of "zone" feature.  I don't mean to diminish how amazing the NOW zones feature is, just as a new user it is important to clarify that I think the docs imply there is more next.js side logic when it comes to zones than there actually is.
* Don't try to run custom server from the parent directory like this "blog/server.js".  This will give you 404 for reasons beyond my current understanding.  Instead, if you want to start a zone from parent directory, run this "npm run --prefix blog start" where start in blog/package.json is something like "PORT=5000 node server.js".

I am very new to next/node so I am sure this could be improved but in my ignorance here are some convenience methods I put together to install/start zones in parallel from the parent example directory:

> {
>   "name": "with-zones",
>   "version": "1.0.0",
>   "scripts": {
>     "installTask": "npm install",
>     "installHome": "npm run --prefix home installTask",
>     "installBlog": "npm run --prefix blog installTask",
>     "installParallel": "npm-run-all --parallel installTask installHome installBlog",
>     "home-start": "npm run --prefix home start",
>     "blog-start": "npm run --prefix blog start",
>     "buildParallel": "npm-run-all --parallel home-build blog-build",
>     "proxy-dev": "npm run micro-proxy -p 9000 -r rules-dev.json",
>     "start-dev": "npm-run-all --parallel blog-start home-start proxy-dev",
>   },
>   "dependencies": {
>     "npm-run-all": "^4.1.3",
>      ...
>   }
> }
