### ISSUE TITLE
getInitialProps

### ISSUE THREAD

**Issue by chepelevdi** [zeit/next.js#4709]
Hi all. I'm newly to next.js and cant get some parts about getInitialProps

1) How proxy this request?  I did it with a help of baseURL: process.env.BACKEND_URL in axios? And why this https://github.com/zeit/next.js/tree/canary/examples/with-custom-reverse-proxy doesn't work?

2) Why  passport.deserializeUser  doesn't called on this request.
I have my pet project http://i.prntscr.com/UdKjw1BZTk2GTSMNgE46Zw.png
And getInitialProps -doesnt work, cdm - work perfect.
https://github.com/chepelevdi/course-search

3) what is a main purpose of this life-cycle?

**Comment by timneutkens** [comment]
as per the issue template you posted it here: https://spectrum.chat/thread/b462bfa2-cc70-4a1e-8a0c-1aaa7a2586f5
