### ISSUE TITLE
Update &/or unpin styled-jsx version

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#4713]
# Bug report

## Describe the bug

The version of styled-jsx that has been pinned (v2.2.6) [has bugs that have been fixed in the latest version](https://github.com/zeit/styled-jsx/issues/432#issuecomment-401267274) (v2.2.7).

Pinned dependency versions in public packages is an anti-pattern, please consider unpinning the styled-jsx version and use normal semver (with `^`). It is another Zeit project, so it should be "safe".

## To Reproduce

N/A.

## Expected behavior

styled-jsx should be up to date to avoid bugs.

## Screenshots

N/A.

## System information

 - Version of Next.js: v6.1.1

**Comment by timneutkens** [comment]
Feel free to send a pull request to upgrade styled-jsx. 

We've talked about the pinned dependencies multiple times before in other issues. We're not going to change this as it has broken Next.js multiple times in the past. 

With pinning, we always know we're releasing the most stable software on which users can depend. As all Next.js's tests will have run against the new dependency version before releasing.
