### ISSUE TITLE
Google Cloud Platform SQL

### ISSUE THREAD

**Issue by Gmulti** [zeit/next.js#4720]
# Question about Next.js

I want to use my Google Cloud Platform SQL instance + the Sequelize module.
In development: everything is good
In production : 
```
 "errorno": "ETIMEDOUT",
"code": "ETIMEDOUT",
"syscall": "connect",
fatal": true
```

I added the IP of the server on which my instance is hosted.
Is there anything specific to do?

**Comment by timneutkens** [comment]
This is unrelated to Next.js. Next.js only renders the frontend of an application.
