### ISSUE TITLE
next export getting stuck

### ISSUE THREAD

**Issue by sarkistlt** [zeit/next.js#4721]
ref: [next export getting stuck, #2201]

when running `next export`, it does export, it works, but then process never dies, so I'm forced to use something like  `next export& sleep 300 ; kill $!` in my deployment which is not really reliable.
I'm not using `getInitialProps` anywhere besides `_document.js`.

Current version of nextjs is `next@6.0.4-canary.3`.
I was trying to upgrade nextjs, hopping maybe this issue will be resolved, but If I will upgrade to `next@6.0.4-canary.4` and up, getting following error when running `next build`:
```shell
{ Error: (client) [component full path].js from UglifyJs undefined
  errors: 
   [ '(client) [component full path].js from UglifyJs\nundefined',
   ...],
  warnings: [] }
npm ERR! code ELIFECYCLE
```

**Comment by timneutkens** [comment]
Please follow the issue template. It's there to prevent non-actionable issues.
