### ISSUE TITLE
Static HTML export: dynamic routing, with queries

### ISSUE THREAD

**Issue by sarkistlt** [zeit/next.js#4722]
I use to use `next-routes` library and it works quit well when running on custom server. 
Because I'm able to use middleware to resolve predefined dynamic path like `'/inventory/products/:id', [path to the page]`, where `id` is a query parameter. So in the browser I can access product by typing `/inventory/products/1`, but because of how static export works and it's not possible to use any middleware, if I want to access product by url, I have to use like this `/inventory/products?id=1`.

My question is it possible to still have that prettify url pattern like `/inventory/products/1`, with static export?

`exportPathMap` is not a solution, because I can't define any default value for `id`.

**Comment by timneutkens** [comment]
> My question is

Please follow the issue template. Which says you should post questions on https://spectrum.chat/next-js
