### ISSUE TITLE
with-apollo : withApolloClient.js:37 Error while running `getDataFromTree` Error: GraphQL error: Variable "$slug" of required type "String!" was not provided.

### ISSUE THREAD

**Issue by nyl-auster** [zeit/next.js#4725]
## example
with-apollo 

## descrition of the bug
Client error when navigating with the client from my homepage ( listing blog posts) to the page of a specific post
> withApolloClient.js:37 Error while running `getDataFromTree` Error: GraphQL error: Variable "$slug" of required type "String!" was not provided.

because router is not filled with the right values here : https://github.com/nyl-auster/reactpress-graphql/blob/494526e40bfe223ec303402a689027926da62b4e/pages/post.js#L32

<img width="1258" alt="capture d ecran 2018-07-03 a 23 09 40" src="https://user-images.githubusercontent.com/335495/42244715-5c801b60-7f16-11e8-9f76-276f65adc168.png">

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://reactpress-ubrjmidjjw.now.sh/
2. Click on 'readmore'

This does **not** happen when loading directly https://reactpress-nblhwppnbr.now.sh/post/lecture-des-propositions-xii-a-xx-du-de-affectibus

**Comment by lmatheus** [comment]
In production, this is due to `(blocked:mixed-content)`. To avoid this just modify `wordpressGraphqlEndpoint` in your `reactpress.config.js` file from `http://dev-reactpress.pantheonsite.io/graphql` to `https://dev-reactpress.pantheonsite.io/graphql`

**Comment by nyl-auster** [comment]
@lmatheus good catch ! still got this error though 

> withApolloClient.js:37 Error while running `getDataFromTree` Error: GraphQL error: Variable "$slug" of required type "String!" was not provided.

**Comment by nyl-auster** [comment]
@lmatheus You can reproduce this issue with this new deployment (I fixed httpS issue) : https://reactpress-ubrjmidjjw.now.sh/
- open developper console
- go to https://reactpress-ubrjmidjjw.now.sh/
- click on "Read more"
- console displays "Error while running `getDataFromTree` Error: GraphQL error: Variable "$slug" of required type "String!" was not provided."
- refresh the page
- page served by the server is correctly displayed

**Comment by nyl-auster** [comment]
I managed to get this done by using https://www.npmjs.com/package/next-apollo
Here is an example code : https://github.com/nyl-auster/reactpress-graphql/blob/a5d70ee81760688a3af3c27b854307e28bf2b0a2/pages/post.js
