### ISSUE TITLE
Using newrelic with next.js

### ISSUE THREAD

**Issue by djskinner** [zeit/next.js#4728]
# Bug report

## Describe the bug

`next run build` fails with `Module not found: Error: Can't resolve 'aws-sdk'` when `require('newrelic')` is present in a page.

## To Reproduce

See minimally reproducible example: https://github.com/zeit/next.js/compare/canary...djskinner:newrelic

## Expected behavior

A next.js app can easily be instrumented with newrelic both on the server and on the browser.

## Additional context

`require('newrelic')` in server.js is fine and server-side instrumentation works without issue. The problem is only with browser instrumentation.

newrelic package details and usage instructions: https://www.npmjs.com/package/newrelic

**Comment by timneutkens** [comment]
It looks like this is a server-only module, so you can't use it inside `pages/index.js`, instead, I guess you can use `_document.js` as it's only rendered on the server side.
