### ISSUE TITLE
Keeping server data when navigating pages

### ISSUE THREAD

**Issue by MickaelBZH** [zeit/next.js#4729]
Hello,

I am using a custom server and passing some server data through the query params:

```
server.get('/', (req, res) => {
            const mergedQuery = Object.assign({'data': somedata}, req.query, req.params);
            return app.render(req, res, '/', mergedQuery);
     })
```

I don't know if it's the best way to do so, but it works somehow.
The issue is with client routing, the query is overwritten and the data is lost.
How do you keep server data sent on the first request (without using Redux or localstorage ...)?
 

# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

**Comment by timneutkens** [comment]
As you can see in the issue you posted:

> Questions should be posted on spectrum.chat/next-js
