### ISSUE TITLE
Module build failed: Error: .sourceMap is an alias for .sourceMaps, cannot use both - after 6.1.1 upgrade

### ISSUE THREAD

**Issue by vagh27** [zeit/next.js#4730]
After upgrading to next 6.1.1 and next-typescript 1.1.0, running `next build` yields the following error:

```
Module build failed: Error: .sourceMap is an alias for .sourceMaps, cannot use both
```
![screen shot 2018-07-04 at 10 57 19 am](https://user-images.githubusercontent.com/2664316/42284001-2809e72c-7f79-11e8-81a0-c778e7b48b62.png)

Running locally works - it's just the build that fails.

.babelrc file:
```
{
  "sourceMaps": false,
  "presets": [
    "next/babel",
    "@zeit/next-typescript/babel"
  ],
  "plugins": [
    [
      "styled-components",
      {
        "ssr": true,
        "displayName": true,
        "preprocess": false
      }
    ]
  ]
}
```

**Comment by timneutkens** [comment]
Sourcemaps are automatically enabled in dev and disabled in production. There's no need to provide this option.
