### ISSUE TITLE
Styles dont work when use next-routing in dev mode

### ISSUE THREAD

**Issue by Popugune** [zeit/next.js#4732]
# Bug report
Styles dont work when use next-routing in dev mode
## Describe the bug
In the development mode, no styles are going to the components when navigating through links for components.

The style file in .next / statics / style.css does not update, when changing to another url

## To Reproduce
use next-routing
use sass with css-modules
Start the server, move to a different page
The creation of the chunk for the page begins, but the styles will not be created for the page

## Expected behavior
That when navigating through the URL in the development mode, css will be updated

## Screenshots
[pic](https://pp.userapi.com/c830708/v830708948/13aa3a/E0wTYCbR5YA.jpg)

## System information
 - Version of Next.js: [6.1.1]

**Comment by kv9991** [comment]
+1. This bug is real
I'm using next-less plugin

**Comment by timneutkens** [comment]
github.com/zeit/next-plugins. This is unrelated to next.js core.

**Comment by Popugune** [comment]
@timneutkens its core! Webpack config in core work not correctly
