### ISSUE TITLE
I found a bug in babel: 7.0.0-beta.42

### ISSUE THREAD

**Issue by longge-0516** [zeit/next.js#4733]
Module build failed: Error: [BABEL] D:\projectCode\code\workspace\ssr\Nfes-boilerplate\pages\demo.js: You gave us a visitor for the node type PrivateName but it's not a valid type

     Updated babel version to 7.0.0-beta.51 can solve the problem.

**Comment by timneutkens** [comment]
We'll upgrade Babel to latest once the 7 RC comes out.

**Comment by atainter** [comment]
I'm seeing the same issue. @timneutkens Looks like 7.0.0 was released. Do you have an upgrade planned? 

https://www.npmjs.com/package/@babel/core

**Comment by timneutkens** [comment]
We were the first package to upgrade when 7.0.0 came out, it'll be released with Next 7 though, as it has quite a few breaking changes. No breaking changes on the Next.js side though, if you don't have a custom `.babelrc` nothing will break 🙏 It's out on `next@canary` (beta) right now.

**Comment by Ethaan** [comment]
@timneutkens i'm facing this issue with `next 7.0`, while doing this.

```
require('@babel/register', {
  babelrc: false,
  presets: ['env'],
  plugins: [
    'transform-class-properties',
    'babel-plugin-graphql-import',
    'transform-object-rest-spread',
  ],
});
```

does ` if you don't have a custom .babelrc nothing will break` should be fixed with `babelrc: false,`

(i'm doing this `babel/register` becuase i'm running a custom server)
