### ISSUE TITLE
Fetch from api fails when page is accessed from Link, otherwise works

### ISSUE THREAD

**Issue by adueck** [zeit/next.js#4742]
# Bug report

## Describe the bug

This is very strange, it seems like a bug or perhaps something I am missing.

I have a very basic app started, based on the [tutorial here](https://nextjs.org/learn/), except that on one page I fetch data from api server set up in express (which grabs data from a mongodb locally).

This works great when I run it on my development rig (WSL Ubuntu 16.04), but when I run it on my cloud server (Ubuntu 16.04), something very strange happens.

When I click the link to the page that fetches the data from my local api, I get this error:

`TypeError: Failed to fetch`
`"Resources.getInitialProps()" should resolve to an object. But found "undefined" instead.`

- At the black error screen, if I just click on the address bar and `Enter` (w/o changing the url), *it works*
- If I manually type in the address of the link to that same page, *it works*
- If I manually type in the address to the api call, *it works*
- If I do the exact api call used by the `fetch` on my server, *it works*
- When I log the output of the db....find() to the console as it appears in the code, *it works*

It's only when I click on the Link to the page that the `fetch` fails, and this only happens when the code is on my cloud server.  (I saw it fail the same way once or twice on my development machine (Ubuntu 16.04 Bash on Windows 10), but I am not able to reproduce it.)

## To Reproduce

**server.js** 

```
const express = require('express')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

console.log("Connecting to mongodb");
require('monk')('localhost/myMongoDb').then((db) => {
  console.log("Connected to db");
  app.prepare().then(() => {

    const server = express()

    server.get('/api/resources', (req, res) => {
      db.get('resources').find().then((results) => res.json(results));
    });

    server.all('*', (req, res) => {
      return handle(req, res)
    });

    server.listen(3000, (err) => {
      if (err) throw err
      console.log('> Ready on http://localhost:3000')
    })
  })
  .catch((ex) => {
    console.error(ex.stack)
    process.exit(1)
  })
});
```

**components/Header.js**

```
import Link from 'next/link'

const linkStyle = {
    marginRight: 15
}

const Header = () => (
    <div>
        <Link prefetch href="/">
            <a style={linkStyle}>Home</a>
        </Link>
        <Link prefetch href="/lessons">
            <a style={linkStyle}>Lessons</a>
        </Link>
        {/* WHEN I CLICK THIS LINK THE FETCH FAILS */}
        <Link prefetch href="/resources">
            <a style={linkStyle}>Resources</a>
        </Link>
    </div>
)

export default Header
```

**pages/resources.js**

```
import Layout from '../components/Layout'
import Link from 'next/link'
import fetch from 'isomorphic-unfetch'

const listStyle = {
    lineHeight: 2
}
 
const Resources = (props) => (
	<Layout>
		<h3>Resources</h3>
        <ul style={listStyle}>
            {props.resources.map((mpd) =>
                <li key={mpd._id}>
                    <Link href={mpd.link}>
                        <a>{mpd.title}</a>
                    </Link>
            </li>)} 
        </ul>
    </Layout>
);

Resources.getInitialProps = async function() {  
    try {
        // THIS FETCH ONLY FAILS WHEN I ENTER THE PAGE FROM THE LINK IN THE HEADER
        // IT WORKS JUST FINE WHEN I TYPE https://******.com/resources IN THE ADDRESS BAR
        const list = await fetch('http://localhost:3000/api/resources');
        const data = await list.json();
        return {
            resources: data
        }
    } catch(e) {
        console.log(e);    
    }    
}

export default Resources;
```

## Expected behavior
The `resources/` page should behave the same, whether I access it from a link within the app, or whether I access it directly from the address bar. 

## System information
 - OS: Ubuntu 16.04 Server (Digital Ocean)
 - Browser - Same error with Chrome/Firefox/Edge
 - Version of Next.js: 6.1.1

## Additional context

I am sorry if this is just an obvious mistake that I am making. I am new to next.js and this is very puzzling to me.

**Comment by timneutkens** [comment]
Sounds like a case of `CORS` stopping the request, but I can't say for certain without a live example. 

The reason Next will render the error screen is that you do a try/catch and the catch returns nothing. The error that is logged should say exactly what's wrong though 🤔

Either way, I'm sure this is not a bug in Next.js but something in your implementation as we have tests for `getInitialProps`.

Feel free to post this with a live example on https://spectrum.chat/next-js so that other community members can see the solution once you find one.

**Comment by adueck** [comment]
Could this have something to do with the fact that my app is being served with a nginx reverse proxy in front of the express server? 🤔 

It's just so strange that the request works perfectly when I open the page through the url in the address bar, but it's not going through when I open the page from the `<Link>` in the app.

**Comment by adueck** [comment]
And excuse my ignorance, but how would I post a live example??

**Comment by adueck** [comment]
It would be really nice if there could be a little tutorial on getting next.js hooked up to a local database for us less experienced folks. It seems like a bunch of people would appreciate that as seen in [this issue](https://github.com/zeit/next.js/issues/370#issuecomment-276189774).

**Comment by adueck** [comment]
Sorry for the lots of comments here, but it also doesn't seem to be `CORS` because I tried enabling cors with [https://github.com/expressjs/cors](https://github.com/expressjs/cors), and still no luck. 😞

**Comment by timneutkens** [comment]
Could you provide a live website?

**Comment by adueck** [comment]
Sure,   http://45.77.7.9:3000/  
I posted that and the [source code](https://github.com/adueck/nextjs-with-db) on a chat question like you suggested. 👍 Thanks for your help. Sorry I'm really at a loss in getting this db connected.

**Comment by benatkin** [comment]
Found this on Spectrum – it seems that `getInitialProps()` is working on the SSR but not on the page transitions. This [references localhost](https://github.com/adueck/nextjs-with-db/blob/master/pages/resources.js#L25). If you have it deployed to http://45.77.7.9:3000/ you want it to change to http://45.77.7.9:3000/ for client requests but stay as http://localhost:3000/ for SSR requests for it to work. I used environment variables for this.

**Comment by adueck** [comment]
Thank you very much, could you explain how I would use environment variables in this case?

**Comment by benatkin** [comment]
@adueck I did this:

First, in [next.config.js](https://github.com/benatkin/freeyoga/blob/2bd61a62c99cb3cb9bad07b41f80dde242bc7ec8/next.config.js) I have:

``` js
module.exports = {
  webpack: (config) => {
    // Fixes npm packages that depend on `fs` module
    config.node = {
      fs: 'empty'
    }

    return config
  },
  serverRuntimeConfig: {
    apiBaseUrl: `http://localhost:${process.env.PORT || 3000}/api`
  },
  publicRuntimeConfig: {
    apiBaseUrl: '/api'
  }
}
```

[Then where I make the fetch call, I have](https://github.com/benatkin/freeyoga/blob/2bd61a62c99cb3cb9bad07b41f80dde242bc7ec8/pages/index.js):

``` js
const {serverRuntimeConfig, publicRuntimeConfig} = getConfig()
```

``` js
const apiBaseUrl = serverRuntimeConfig.apiBaseUrl
      ? `${serverBaseUrl}/api`
      : publicRuntimeConfig.apiBaseUrl
```

Finally in the fetch call:

``` js
const res = await fetch(`${apiBaseUrl}/chapters`)
```

**Comment by adueck** [comment]
@benatkin  Thanks for your help, but unfortunately this doesn't work for me. 😞 Now it doesn't work from the link or from the url directly.

You can see my [code here](https://github.com/adueck/nextjs-with-db/)  and a live example at http://45.77.7.9:3000/

**Comment by adueck** [comment]
I've decided that the simplest thing is just to make a separate api server, and use that for all the db operations. This was also what was [recommended earlier here](https://github.com/zeit/next.js/issues/370#issuecomment-265914216), and it works great for me.

It would be nice though, to include something in the docs/tutorial about this, encouraging people to use a separate api for this kind of thing because of this issue of client/server side calls on getInitialPropsEtc. It seems [a bunch of people](https://github.com/zeit/next.js/issues/370#issuecomment-276189774) would appreciate that.

Thanks for all your work on this fantastic product!
