### ISSUE TITLE
How to hide SSR render on initial request?

### ISSUE THREAD

**Issue by omgcyrilic** [zeit/next.js#4743]
I just finished building my app with next.js and I'm loving it so far.

When I see the initial request for my website, I see the SSR paint and then the client side paints (with some wowjs stuff). Is there any way to show a loading notification when the server side is loading?

Thanks!

**Comment by sergiodxa** [comment]
You can use [progressive render](https://github.com/zeit/next.js/tree/canary/examples/progressive-render) to only render client side and render a loading in the server.
