### ISSUE TITLE
String templating is not working

### ISSUE THREAD

**Issue by teddybee** [zeit/next.js#4744]
# Bug report

## Describe the bug

I would like to use variables in strings especially in url-s. As far as I know it should be working with ES6. But with nextjs it isn't working in jsx nor in code.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Run this little function:
```
export const testStringTemplate = () => {
    const str = "some long string";
    console.log('This should be ${str}');
};
```

2. Watch the console logs in the browser, that is currently gives back this: 
This should be ${str}

## Expected behavior
The log should contains the str variable.

## System information
 - OS: Win10 pro
 - Browser: Chrome
 - Version of Next.js: 6.1.1
 - React: 16.4.1

## Additional context
My next.config.js:
```
const withCSS = require('@zeit/next-css');
module.exports = withCSS({
    webpack: (config, options) => {
      // Fixes npm packages that depend on `fs` module
      config.node = {
        fs: 'empty'
      }    
      return config
    }
  });

```

**Comment by timneutkens** [comment]
`console.log('This should be ${str}');` should use backticks (`)

```
console.log(`This should be ${str}`);
```

**Comment by teddybee** [comment]
Ahhhh.... thank you.
