### ISSUE TITLE
Duplication className for meta charSet

### ISSUE THREAD

**Issue by udanpe** [zeit/next.js#4745]
```jsx
<meta charSet="utf-8" class="next-head next-head"/>
```

**Comment by geoffRGWilliams** [comment]
Confirming this occurs client-side in 6.1.1 and both client and server-side in canary.
![image](https://user-images.githubusercontent.com/21004338/42915485-47dddd42-8b54-11e8-895b-a75220e6c9e2.png)

Steps to reproduce:
- `npm init`
- `npm i react react-dom next -s`
- create `index.jsx` with the following contents:
```
import Head from "next/head";

export default () => <>
    <Head />
  </>
```

Additional "next-head"s pile up if further components (e.g. _document, _app, page, child component) add elements to <Head />.
