### ISSUE TITLE
Static export hangs infinite - handle errors

### ISSUE THREAD

**Issue by lkostrowski** [zeit/next.js#4747]
# Bug report

## Describe the bug

When I do `next build` && `next export`, the process hangs infinitely. No eerrors are thrown, according to source code, there are [missing error handlings ](https://github.com/zeit/next.js/blob/canary/server/export.js#L156)

My exportPathMap:

```
async exportPathMap () {
        await initDb();

        const posts = await getPosts();

        const tags = await getTags();

        const postsPages = {};

        posts.forEach(post => {
            postsPages[`/post/${post.slug}`] = {
                page: '/post',
                query: {
                    post
                },
            };
        });

        const config = {
            ...postsPages,
            '/': {
                page: '/',
                query: {
                    posts,
                    tags,
                },
            },
        };

        console.log(config);

        return config;
    },
```

Console logs:
```
> using build directory: /my-project/.next
  copying "static" directory
  copying "static build" directory
{ '/post/example-post': { page: '/post', query: { post: [Object] } },
  '/': { page: '/', query: { posts: [Array], tags: [Array] } } }
> exporting path: /example-post
> exporting path: /

```

`/out` has properly exported files, but process doesn't end, so I can't run pipelines.

It's possible there is somewhere bug on my site, but I can't reproduce since no errors are thrown

## Expected behavior
The process should end or fail with errors logged

**Comment by timneutkens** [comment]
The specific part you're linking to happens way before the `exporting path` console.log.

The one thing I can think of is that your `getInitialProps` doesn't resolve.

Please provide a full reproduction. As we can't resolve issues without a reproduction.

**Comment by lkostrowski** [comment]
Thanks for the reply. 

Unfortunately it will take me quite a long time to strip code so I can make it public.
Maybe I can debug it myself? 

I logged whole flow of this function 
https://github.com/zeit/next.js/blob/canary/server/export.js

And it resolves till the end, including last `log("")` statement. Also `getInitialProps` are resolved.

Can you tell me if any other piece of code is run after this?

**Comment by lkostrowski** [comment]
Update: 

https://github.com/zeit/next.js/blob/canary/bin/next-export#L60

This line also resolves. Looks like adding `.then(()=> printAndExit('Exported', 0))` helps.
