### ISSUE TITLE
with-dotenv example when changing .env changes doesn't get applied

### ISSUE THREAD

**Issue by FadiAboMsalam** [zeit/next.js#4748]
## Example name
with-dotenv

## Describe the bug
i have followed this with-dotenv example and it works as expected  fist time then i did a change on the .env file but it seems the first values of .env is still loaded
 
## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1.  define some variable inside .env lets say we want to change  REACT_APP_EMAIL = 'x@gmail.com' to REACT_APP_EMAIL = 'x2@gmail.com'
2.  yarn build
3. i start my application using pm2 start ecosystem.config.js
4. is still see my old values (x@gmail.com) for variables when running the app

## Expected behavior
to see the new values of variable which is x2@gmail.com

**Comment by timneutkens** [comment]
Try `rm -rf node_modules/.cache`

**Comment by maxbeatty** [comment]
is pm2 restarting the process entirely when you make changes to your .env file? dotenv will not overwrite existing values in `process.env` so it needs a fresh process for you to see your changes

**Comment by timneutkens** [comment]
>  i don't think this is the solution to go but at least it is a work around

That's why I added the labels instead of closing immediately 😄

**Comment by HaNdTriX** [comment]
Related Issue: https://github.com/brysgo/babel-plugin-inline-dotenv/issues/13
