### ISSUE TITLE
Style changes are not hot reloading

### ISSUE THREAD

**Issue by iamjacks** [zeit/next.js#475]
Trying out the 2.x beta using the same example styled-jsx code in the readme. Changing `background: red` to `background: green` results in all elements losing their styles. Refreshing restores them and displays the changes.

Edit: impronunciable mentioned below that styles are not being flushed. I'm noticing that as well. At first I thought it was related to using global, but it's not.

**Comment by impronunciable** [comment]
A bigger issue that I spotted from here is that styles are not being flushed. If I change the background some times and then refresh I still get 4 style tags with previous styles even if those are not used anymore

![screen shot 2016-12-22 at 8 29 03 am](https://cloud.githubusercontent.com/assets/165799/21427185/f5d53d30-c820-11e6-9a93-c3e3b2fd105a.png)

**Comment by katopz** [comment]
Same here (with some more issue) https://github.com/zeit/styled-jsx/issues/50

**Comment by iamjacks** [comment]
@rauchg npm is still listing 0.2.2 as the latest for styled-jsx

**Comment by rauchg** [comment]
`0.2.3` has been published
