### ISSUE TITLE
examples require root Next.js project installation

### ISSUE THREAD

**Issue by mherodev** [zeit/next.js#4751]
# Examples bug report

## Example name
All examples

## Describe the bug
Tim's description, via Slack:

> Basically the problem is that next Will look for a babelrc
> Which it finds in examples
> But that has to reference the built file
> As it can’t Find the next/babel of the dir it’s running from
> Previously we had a custom property in .babelrc to disable the tree lookup, but babel 7 is strict
> It validates the file
> It’ll also be fixed once we move to a different directory structure

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://github.com/zeit/next.js/tree/canary/examples/with-next-routes
2. Follow installation instructions by cloning Next.js, `cd with-next-routes`, etc.
3. Encounter error:
```
Module build failed: Error: Cannot find module './dist/build/babel/preset'
```

## Expected behavior
It should run successfully without installing the root project.

**Comment by timneutkens** [comment]
Lets start with documenting this step in contributing.md.

**Comment by mherodev** [comment]
Is it related to contributing? I feel like this would be documented in each example, or maybe at the root readme (although there it would be overlooked)

**Comment by timneutkens** [comment]
Posted a comment here #4758

**Comment by timneutkens** [comment]
This has been solved.
