### ISSUE TITLE
Dynamic Rendering with Next Js

### ISSUE THREAD

**Issue by gdi-user02** [zeit/next.js#4752]
# Question about Next.js
 I watched [Google's conference on SEO](https://www.youtube.com/watch?v=PFwUbgvpdaQ&t=137) and they suggested to use Dynamic Rendering for JS built applications (React, Vue, etc). How can I do Dynamic Rendering with Next JS? 

Questions should be posted on https://spectrum.chat/next-js

**Comment by timneutkens** [comment]
> Questions should be posted on spectrum.chat/next-js

As you've posted yourself 😅
