### ISSUE TITLE
/_next/static/**.(js/css)  failed

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [zeit/next.js#4753]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

IN chrome console:
/_next/static/commons/main.js  200 (OK)
/_next/static/style.css   200 (OK)

but, IN chrome network:
their status is failed.

why?

**Comment by timneutkens** [comment]
You've posted the issue template which clearly says questions shouldn't be posted here. Also, Next.js doesn't generate any .css, that's what @zeit/next-css (the plugin) does. Note that you haven't provided a way to reproduce this issue, so it's impossible to give you an answer as to "why".
