### ISSUE TITLE
now alias shows old version on Chrome 67

### ISSUE THREAD

**Issue by lonelydatum** [zeit/next.js#4761]
When I deploy using "now alias _____ prequilt.com", then going to prequilt.com still shows an old version I deployed weeks ago. 

The error happens on Chrome Version 67.0.3396.99. 
Its fine when I view it in Chrome Incognito.
Now 4.0.0-canary

**Comment by timneutkens** [comment]
This is the Next.js repository. 
This question should be posted on github.com/zeit/now-cli / zeit.chat or by emailing to support@zeit.co.

I just had a look and it seems like the domain is aliased to a deployment done earlier today. So that all seems correct.

**Comment by lonelydatum** [comment]
Sorry. I'll post this question on now-cli for further discussion. Thanks!
