### ISSUE TITLE
Mocha.js testing example

### ISSUE THREAD

**Issue by jeffscottward** [zeit/next.js#4767]
# Feature request
Mocha testing example with babel config (v7)

## Is your feature request related to a problem? Please describe.
https://github.com/zeit/next.js/issues/4300#issuecomment-396382717

## Describe the solution you'd like
A folder in /examples with a proper babel config for making it work (in package.json so it inherits?)

**Comment by stephensauceda** [comment]
Mocha example [here](https://github.com/zeit/next.js/tree/canary/examples/with-mocha)
