### ISSUE TITLE
with-material-ui seems to not be

### ISSUE THREAD

**Issue by pkellner** [zeit/next.js#4769]
The example in the repo for with-material-ui does not seem to have any code in that is about material-ui.  I could somehow be totally missing the point, but I was expecting to see code that looked similar to what is in this post:  

https://medium.com/codingthesmartway-com-blog/getting-started-with-material-ui-for-react-material-design-for-react-364b2688b555

Instead, I don't see any imports of the material-ui library

Sorry for the bother if I'm missing the point here somehow.

**Comment by dextermb** [comment]
The code is not hosted by Zeit as mentioned in the README. If you're looking for the source code on GitHub then go to Material UI's NextJS example.

> // ...
> :warning: The source code [is hosted](https://github.com/mui-org/material-ui/tree/master/examples/nextjs) on the Material-UI repository.
