### ISSUE TITLE
import from installed packages doesn't work properly

### ISSUE THREAD

**Issue by wslx520** [zeit/next.js#4770]
I prepared the way to import external css( spent a whole day, finally, I choose `extracted-loader`), and then I found this bug

I have set a `babel-plugin-import` in `.babelrc`:
```json
{
  "presets": ["next/babel"],
  "plugins": [
    ["import",{"libraryName":"antd", "libraryDirectory": "es", "style": "css"}]
  ]
}
```
my purpose is import the css of a component, the `antd` supply a js file for every component, which contains the all css of the component. the content of this file isn't special, just require two css:
```javascript
require('../../style/index.css');
require('./index.css');
```
So I import it:
```javascript
import 'antd/lib/carousel/style/css';
```
but I got crashed:

![image](https://user-images.githubusercontent.com/1026909/42617174-5ea43092-85e3-11e8-8e7b-48c6a6ef897a.png)

it seems can't recognize the `css`  file type...

## one more 

if I changed the content of the js file to:
```javascript
import ('../../style/index.css');
import ('./index.css');
```
Another error occured:
![image](https://user-images.githubusercontent.com/1026909/42617333-e8d95c38-85e3-11e8-8249-af88c15830eb.png)

it seems can't recognize `import`

## but
If I built a file in the project directory, such as `css/css.js`, and the content is:
```javascript
import 'antd/lib/style/index.css';
import 'antd/lib/carousel/style/index.css';
```
then imort this js file in my `pages/index.js`:
```javascript
import '../css/css';
```
Everything works. it has no problem with either `import` or css filetype

so, is there any diffrence between import from installed packages (like `import 'antd/xxx/xxx'`) and import from path (like `import '../css/css'`)？How can I solve this?

**Comment by timneutkens** [comment]
`import()` is something different than `import`. This is not a bug in Next.js, please file an issue on the right repository, github.com/zeit/next-plugins, with a reproducible example, preferable a GitHub repository, otherwise, it's impossible to help.

**Comment by wslx520** [comment]
@timneutkens sorry but I have a whitespace between `import` and `(` in the above code, maybe it's too neglected. and actually the following code got the same error:
![image](https://user-images.githubusercontent.com/1026909/42668992-f90470dc-8685-11e8-808c-a884df9bb6d5.png)

I agreed with you that it's a bug of next-plugins, I'll try to go there and report. Thank you
