### ISSUE TITLE
[Question/Proposal] Serve assets directly from nginx

### ISSUE THREAD

**Issue by rashidul0405** [zeit/next.js#4777]
## Backgroud
We use custom express server to serve all js, css, and static assets (images, svgs etc.). We use `compression` module from express and use Nginx as reverse proxy. As we are using Nginx then why not use that to compress and serve assets, while doing compression using node is not a good idea. Node(single threaded) can then offload some of its responsibilities.

## Issue/Question
Assets build for specific pages are being served as like `/_next/BUILD_ID/page/[_app|index].js`. How  can we serve this directly through nginx and utilize long term caching?

## Proposal
When we build the assets, should we use `BUILD_ID` as directory name and put assets into that directory so that we can directly map those files from nginx without going through node/express server?

**Comment by timneutkens** [comment]
Same as https://spectrum.chat/thread/5fc437ab-6d7c-4253-b1d9-821b04f1820c
