### ISSUE TITLE
Uncaught SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by markolofsen** [zeit/next.js#4779]
I builded project (yarn build & yarn start)
At localhost everything ok, but in web got an error... The same bundles.
```
main-5bb8a1bd1fb5e7e7ce5c.js:1
Uncaught SyntaxError: Unexpected token }
```

Demo [TenerifeBook.com](https://tenerifebook.com)
r=this.props,a=r.className,i=r.style,s=this.props.useDangerouslySetInnerHTML|| 
!1,u=this.props.dangerouslySetInnerHTMLPartElement|| 
"span",l=x({},this.props.options,{interpolation:{prefix:"#$?",suffix:"?$#"}}),c=this.t(this.props.i18nKey,l);
if(!c||"string"!=typeof c)return o.a.createElement("noscript",null); 
var d=[];c.split(n)
.reduce(function(t,n,r){
var a=void 0;if(t&&(Object.setPrototypeOf?Object.setPrototypeOf(e,t):e.__proto__=t) **}**(t,r["Component"]),.........

**Comment by timneutkens** [comment]
There is nothing actionable to help here.
