### ISSUE TITLE
Styled-components FOUC with nextjs and typescript

### ISSUE THREAD

**Issue by scottdj92** [zeit/next.js#4782]
# Bug report

## Describe the bug

Hi, there seems to be FOUC when attempting to render styled components server-side.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://github.com/scottdj92/next-styled-components-fouc
2. Clone, install, run `npm run dev` with the dev tools open
3. See that the index route doesn't render styles server side
4. Further inspection (console logging) of _document.tsx's `styleTags` prop returns undefined

## Expected behavior
I expected style tags to be rendered server side with TS. I ran the same repo without TS, and it behaved as expected.

## System information
 - OS: OS X
 - Browser (if applies) FF Quantum & Chrome 67
 - Version of Next.js: ^6.1.1

## Screenshot
<img width="1439" alt="screen shot 2018-07-14 at 9 13 56 am" src="https://user-images.githubusercontent.com/4582261/42724774-47d54b8a-8746-11e8-9eca-a2dfc8ca058c.png">

## Additional Questions
Would this be solved by moving this to _app.js? I don't see anything in the docs that say so. If the examples need to be updated, I'd be willing to do that :)

**Comment by brainkim** [comment]
Ran into this myself. `getInitialProps` in your example should be static or it won’t run. Maybe next.js could emit a warning when getInitialProps is defined non-statically?

**Comment by scottdj92** [comment]
Ooo that's a nice catch, I didn't see that.
