### ISSUE TITLE
Functional Components vs ES6 Classes in NextJS

### ISSUE THREAD

**Issue by behnamazimi** [zeit/next.js#4785]
All of the examples and tutorials of **NextJs** pages which presented in its docs and other references are with functional components. 

So, What about classes? What happens to `getInitialProps` (or other features that mentioned in docs) when a functional component replaces with an ES6 class. Is that page still a NextJS page after replacing?

**Comment by timneutkens** [comment]
The contract is that you export a React component, which can be a function or a class, for example:

```
import React from 'react'
export default class SomePage extends React.Component {
  static async getInitialProps() {
    return {}
  }
  render() {
    return <div>test</div>
  }
}
```
