### ISSUE TITLE
Stuck at "Downloading files for with-redux example"

### ISSUE THREAD

**Issue by sydneywu** [zeit/next.js#4786]
# Examples bug report

## Example name
with-redux

## Describe the bug
Using windows, When I try to yarn install or npx install, 

`npx create-next-app --example with-redux with-redux-app`
`yarn create next-app --example with-redux with-redux-app`

it will be stuck at "Downloading files for with-with example. Waited 2 hours and still stuck. Doesn't make a difference if i have create-next-app installed globally.

## To Reproduce
`npx create-next-app --example with-redux with-redux-app`

## Expected behavior
It should create the example in with-redux-app.

**Comment by timneutkens** [comment]
Not sure how to reproduce, works fine when I just tried, try downloading the source manually (steps below the create-next-app example.

**Comment by sydneywu** [comment]
@nullablebool Yes. This is a windows only issue. I tried on mac and it works.

To run the example on window, I just cloned the whole repo and copy the specific example folder to another clean directory. (Note: if you try to run just the specific example while it is somewhere inside the next project directory, it won't work. Must be something to do with the parent's babelrc file.)
