### ISSUE TITLE
`prop-types-exact` prevents user from using `data-testid` prop for locating components during testing

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#4788]
# Bug report

## Describe the bug

When using the common `data-testid` practice for components (https://blog.kentcdodds.com/making-your-ui-tests-resilient-to-change-d37a6ee37269), `prop-types-exact` prints errors that are not able to be disabled.

Was added here: https://github.com/zeit/next.js/pull/2516

https://github.com/suprraz/babel-plugin-react-element-info/issues/2

## Solutions

a. Remove `prop-types-exact`
b. Add another prop to `Link` that allows disabling it (escape hatch).

## Workaround

Wrap `Link` component, and don't add `data-testid` to `next/link`, only to the wrapper.

**Comment by timneutkens** [comment]
Adding `data-testid` to `<Link>` won't add anything to the resulting HTML document, adding it to `<a>` or the element under `<Link>` will, so the exact proptypes check is correct here, and this is not a bug.

**Comment by vjpr** [comment]
Ah wait, I see what you mean. I was using a `babel-plugin` to generate the data tags. Placing one on the `Link` tag would never make it to the dom anyway as you said
