### ISSUE TITLE
How to change where Next looks for pages?

### ISSUE THREAD

**Issue by bing1021** [zeit/next.js#4789]
Every .js file in **pages** becomes a route, can i change it? 

I want use src/pages

**Comment by twltwl** [comment]
To use src/pages you can add a dir option in your server.js
``` const next = require('next')({ dev, dir: './src/pages' })```

**Comment by egorovli** [comment]
According to docs, `dir` specifies the location of the project, so the correct way would be to set it to `./src`:

```js
const next = require('next')({
  dev,
  dir: './src'
})
```

But it's only used in a programmatic API (with a custom server) and will affect the presumed location of other files as well (like `next.config.js` and `static` directory, I believe).

**Comment by brainkim** [comment]
No idea what these other comments are saying but you can configure which directory next.js looks for pages from the command-line:
```
$ next ./src
$ next dev ./src
$ next build ./src
$ next start ./src -p 8080
```

**Comment by timneutkens** [comment]
You can't change the directory, and we're not planning to change this, please search for an issue on the issue tracker (including closed issues) in the future before posting an issue, as this question has come up quite a few times.

**Comment by Carduelis** [comment]
@timneutkens don't be like maintainer of moment.js, who rejected optimization for client-side apps, what is led to custom configs in a lot of projects, even in CRA. 
A lot of project boilerplates has an `src` folder, where files lay.

**Comment by aequasi** [comment]
As this is currently the first result on google when searching for this, maybe it would be beneficial to explain the reasoning behind that decision @timneutkens ?

**Comment by ivan-kleshnin** [comment]
@msegers I'm trying to follow this setup and getting tons of errors like this:

> `Cannot find module 'next/document'`
> `Cannot find module 'next/error'`

Any idea how to fix that?

**Comment by helderburato** [comment]
Try this config, its works for me:

```bash
const nextConfiguration = {
  webpack: config => {
    config.module.rules.push({
      test: /\.worker\.js$/,
      loader: 'worker-loader',
      options: webpackExtra.workerLoaderOptions || {
        name: 'static/[hash].worker.js',
        publicPath: '/_next/',
      },
    })

    // Overcome webpack referencing `window` in chunks
    config.output.globalObject = `(typeof self !== 'undefined' ? self : this)`

    return Object.assign({}, config, webpackExtra)
  },
  poweredByHeader: false,
  rootPaths: ['./src'],
}
```

**Comment by folofse** [comment]
@msegers  Suggestion worked for me. 

If you use next-i18next make sure you set the correct localePath in the NextI18 config:`localePath: 'src/static/locales/',` 

**Like this :**
```NextI18NextInstance = new NextI18Next({
	defaultLanguage: 'en',
	otherLanguages: ['en'],
	debug: true,
	localePath: 'src/static/locales/',
});
```

**Comment by slaterbbx** [comment]
The only thing I don't like about next. Pages location. Based on the 70+ thumbs down on the "never gonna change it!" comment, I see I am not alone. :-P

**Comment by slaterbbx** [comment]
So if someone put in a PR to add this as a feature? The answer would be no? Because to me, ( and many others ) the only problem I see with Next, is that horrid folder location of pages. It was the first thing that stuck out to me like a sore thumb. When you build something that has a server and an app, the folder structure looks like ( server / pages / app ), Cant stand it. 😂

**Comment by malimccalla** [comment]
There seems to be quite an appetite for this - would love to be able to configure where my top level pages are looked for.

**Comment by slaterbbx** [comment]
@malimccalla You can, check out here: https://github.com/slaterbbx/fullstackinator

Look in the client folder, notice there are a few key things needed to make this happen. 
If you have any questions, feel free to shoot me an email or here is fine too.

**Comment by malimccalla** [comment]
Thanks for this @slaterbbx 

My issue is that I am trying to co-locate conceptually related code. I have the following structure

```
├── components
|   ├──  GridItem.tsx
|   ├──  Avatar.tsx
|   └──  Button.tsx
├── pages
|   └── profile
|       └── components
|       |   ├── CoverPhoto.tsx
|       |   └── UserInterests.tsx
|       ├── data.ts
|       ├── styles.ts
|       └── index.tsx
```

The issue with this approach (as pointed out by @timneutkens) is that all the files within `pages` are treated as webpack entry points so in turn considered for the commonchunks config. As it currently stands Next only supports top level page components within `pages`. If I could configure where pages are looked for I could keep this (reasonable?) structure. I imagine something like this in the config

```ts
pages: ["./src/pages/*/index.tsx"]
```

It could also be used for projects that store pages in multiple locations

```ts
pages: ["./pages/*", "./admin-pages/*"]
```

or projects that want to store their top level components in a folder named something differently 

```ts
pages: ["./views/*"]
```

or projects that just want to customise the path

```ts
pages: ["./src/custom/path/pages/*"]
```

**Comment by slaterbbx** [comment]
@malimccalla ah, yea, totally understand your grief, I also desire a fully flexible solution. Possibly something worth contributing an effort too, but I have read that they are not interested in offering a solution ( somewhere, but don't quote me on that ) so I fear that investing such time into such a feature could be a lost cause. Unless of course they confirm that they would be interested in such a contribution, then again, might be a project to consider undertaking 🙋‍♂️

**Comment by joncursi** [comment]
@malimccalla were you able to get next to play nicely with your desired project structure, or did you end up flattening out your `pages` directory and storing the page sub-components elsewhere?

**Comment by malimccalla** [comment]
@joncursi I managed to work around by renaming `pages` to `views` and then creating a new `pages` directory thats sole purpose is exporting the top level page components.

```ts
export { default } from `../views/profile`
```

it's by no means ideal but allows me to keep my desired project structure

**Comment by AmazingTurtle** [comment]
@folofse changing the i18n localePath works when it comes to scanning the directory. But when resolving language files it is removing src again. What to do?

**Comment by armenr** [comment]
Question:

We have a custom server file in `/projectRoot/next-web/server.js`

It mounts `/projectRoop/next-renderer-universal/client` like so:

```const nextApp = next({
  dev: NODE_ENV !== 'production',
  dir: APP_DIR,
  quiet: false,
});```

How the heck do we actually build and ship this :)?

**Comment by kachkaev** [comment]
@armenr This small app of mine might help. It uses a custom entry point (`src/server.ts`) and here is how it calls `next()`:
https://gitlab.com/kachkaev/website-frontend/blob/e1c7106cf63811f6341c4bd47dd2354eb2546914/src/server.ts#L11-18

Keeping all source files under `PROJECT_ROOT/src` (or another subdirectory) is quite challenging in Next.js. Because of the added automatic TS integration in Next 9, things become a bit more messy even 😔 I wish https://github.com/zeit/next.js/issues/4315 was reopened.

**Comment by afsanefda** [comment]
I have a server.js file and my scripts are like this:
 ```
 "scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "next start",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

I have to define in my **server.j**s file that looks for src directory but I don't know how?

**Comment by armenr** [comment]
:) I set up a monorepo, so the question I was asking was compounded by other complexities

We've since figured out exactly what to do, but I appreciate the sample code. Still useful! Thank you :)

**Comment by anoop-gupt** [comment]
@armenr  What is your workaround with regards to monorepo? I set up my project with lerna and still constrained with it.

**Comment by armenr** [comment]
@anoop-gupt 

Lerna, monorepo, yarn workspaces, and separate `packages.`

I put all the front-end code into a folder I call `renderer-universal`. I then have a package called `next-web` where I keep my custom next server. I also have another package where I keep `nextron` (next + electron...excellent project, look them up on GitHub).

In the server.js file for nextron and next-web, I use:
```
const nextApp = next({
  dev: NODE_ENV !== 'production',
  dir: APP_DIR,
  quiet: false,
});
```
And I pass in the directory location of the renderer-universal package via ENV variables those server files. 

I also have a bunch of microservices we wrote residing in other lerna packages in the monorepo as well.

No custom webpack/babel configs or symlink resolution required.

**Comment by revskill10** [comment]
Normally, i prefer this project structure:

```
src
  - api
  - pages
  - utils
```
Top level `src` folder is normal and many projects use it. Why not ?

**Comment by anoop-gupt** [comment]
@revskill10  Yesh, even I preferred that structure.

**Comment by armenr** [comment]
We're distributing our app & services + NextJS into both desktop/cloud hybrids as well as web builds.

Package management - node_modules duplication, the need for custom serverJS files w/ Next, and shared modules and libs between the different microservices made it hard to break everything apart or follow the conventional/simpler directory structure.

To provide an easily manageable setup for my team, I had to come up with a pattern that let us work on desktop and web versions simultaneously, and to decouple all microservices and deduplicate all shared libs & modules between them. The only real "right" way to do that was via the setup I've described.

For the average project getting started, this is overkill. In our case, we had a reasonably clear understanding of our initial requirements and what we needed to build, so I was just answering the question. 

For what it's worth, we're thinking of getting rid of the custom server.js file and instead moving to the /api layout that's been implemented into Next9. Unclear, as of yet, whether this will still make it easily possible for us to develop on/build web + nextron simultaneously in a simple way.

**Comment by anoop-gupt** [comment]
@armenr  Can I have your repository location, please? It seems a good solution.

**Comment by scf4** [comment]
The `distDir: '../dist',` method no longer works in Next 9 with typescript and customer server. The problem is it creates a `tsconfig.json` in the `src` dir.

**Comment by scf4** [comment]
Spent a couple of hours trying to solve this but had to move everything into the root dir... such a mess.

<img width="351" alt="image" src="https://user-images.githubusercontent.com/768234/62582431-4e574400-b8a4-11e9-81f8-70d9548c3da6.png">

**Comment by armenr** [comment]
> Spent a couple of hours trying to solve this but had to move everything into the root dir... such a mess 😞
> 
> <img alt="image" width="351" src="https://user-images.githubusercontent.com/768234/62582431-4e574400-b8a4-11e9-81f8-70d9548c3da6.png">

Nothing changes if you try messing with path resolutions, *or modifying the entrypoint file in your tsconfig.json?*

**Comment by chengsokdara** [comment]
For the love of god, please follow the best possible structure in the history of humankind and put pages in src directory.

**Comment by janhesters** [comment]
This has been requested since 2017. How can we help to get this feature shipped?

**Comment by scf4** [comment]
@timneutkens please reopen this issue and reconsider

**Comment by scf4** [comment]
@janhesters  https://github.com/zeit/next.js/issues/8415

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/issues/4315#issuecomment-522263598
