### ISSUE TITLE
Redirect, Router.push() problem

### ISSUE THREAD

**Issue by khorolets** [zeit/next.js#479]
Hi, guys! Can you help me?

I'm using the latest `2.0.0-beta.1` version. And I'm trying to use [this section of README](https://github.com/zeit/next.js#imperatively) to implement a redirect.

My code is:

```javascript
import Router from 'next/router'

export default () => (
    Router.push('/auth/signin')
)
```

And I'm getting error:
```
TypeError: _router2.default.push is not a function
```

Also, I've tried to use `.replace` with the same result.

Can you help me to understand is this a bug or I'm using it wrong?

Thank you!

**Comment by manishbalyan** [comment]
i am workin with latest release of next.js but my router is not working, showing error`TypeError: _router2.default.push is not a function()`. help me how to fix it , not getting how to fix with #480 issue

**Comment by timneutkens** [comment]
@manishbalyan can you make sure you're using `next@beta` instead of `next` in your project dependencies? You can check this in `./node_modules/next/package.json`.

**Comment by manishbalyan** [comment]
my version is `next@latest`

**Comment by timneutkens** [comment]
@manishbalyan try `npm install next@beta`, I believe the router api was added in v2.0.0 which is currently in beta.

**Comment by manishbalyan** [comment]
thanks @timneutkens but i got new problem after update to beta `Cannot read property 'Component' of undefined`. any solution

**Comment by timneutkens** [comment]
Can you create a new issue for that with an example to reproduce? ❤️
