### ISSUE TITLE
[Question] _error.jsx not rendered on server-side render error

### ISSUE THREAD

**Issue by egorovli** [zeit/next.js#4790]
Hi. Please, consider the following example. The `index.js` page will throw a test error on server-side render. I tried using `componentDidCatch` method on a custom `_app.jsx`, but it obviously works only client-side. So, I figured that a custom `_error.jsx` should be rendered in case of server-side render error. But it's still giving me the page with a stack trace (see below).

### ./pages/_error.jsx

```jsx
import React, { Component } from 'react'

export default class CustomError extends Component {
  static getInitialProps = async () => {
    // this gets logged
    console.log('getting initial props of custom _error.jsx')
    return {}
  }

  render = () => {
    // this however is not rendered
    return (
      <h1>OMG, error!</h1>
    )
  }
}
```

### ./pages/index.jsx

```jsx
import React, { Component } from 'react'

export default class Landing extends Component {
  static getInitialProps = async () => {
    return {}
  }

  render = () => {
    // simulate a server-side render error
    if (typeof window !== 'object') {
      throw new Error('Test server render error')
    }

    return (
      <p>Landing page</p>
    )
  }
}
```

The server is a basic `express` server:

### ./server/index.js

```js
const next = require('next')
const express = require('express')

const app = next({ dev: true })
const handle = app.getRequestHandler()
const server = express()
const router = express.Router()

server.locals.handle = handle

router.get('*', (req, res, next) => {
  // also tried appending `.catch(next)` with no luck
  return req.app.locals.handle(req, res)
})

const errorHandler = (err, req, res, next) => {
  // this is never reached even with `.catch(next)` above,
  // so I cannot solve this issue in server
  res.json({ err })
}

app.prepare()
  .then(() => {
    const port = 8080

    server
      .use(router)
      .use(errorHandler)
      .listen(port, () => {
        console.log(`> http server started on port ${port}`)
      })
  })
  .catch(err => {
    console.error(err)
    process.exit(1)
  })
```

When a server-side render occurs, the stack trace is rendered:

![screen shot 2018-07-17 at 10 45 28](https://user-images.githubusercontent.com/5165202/42803479-bf9db1d8-89ae-11e8-9525-073e89b9a104.png)

The interesting fact that it thinks that the proper `_error.jsx` should be rendered, expecting a `h1` tag in the HTML:

<img width="708" alt="screen shot 2018-07-17 at 10 46 14" src="https://user-images.githubusercontent.com/5165202/42803523-d928fc5c-89ae-11e8-926d-5574b00a2b9e.png">

## System information
 - Version of Next.js: 6.1.1

**Comment by egorovli** [comment]
Besides, [the docs state](https://github.com/zeit/next.js#fetching-data-and-component-lifecycle) that the static method `getInitialProps` of the page should receive `err` — "Error object if any error is encountered during the rendering", however the `err` property is always falsy (`null` or `undefined`) in both `index.jsx` page and `_app.jsx` in case of a server-render error.

**Comment by timneutkens** [comment]
In development, _error is not rendered. Only in production.
