### ISSUE TITLE
Mysterious 404 on reload

### ISSUE THREAD

**Issue by ryanfields** [zeit/next.js#4791]
# Bug report

## Describe the bug

After starting my server and loading an initial URL, everything appears to work fine until I either navigate to any other URL and then hit the reload button, or just paste a different URL from the app into the address bar and go.  At that point, I get a 404 and no other error information anywhere.  I can reload that initial URL just fine, and I can navigate via Links to any other URL in my app without seeing an issues.  However, reloading or manually visiting any page that *was not* the first page the server loaded after being started results in a 404.

This bug appears to have come into existence between 6.0.2 and 6.0.3-canary.0 and is still present in 6.1.1.  If I revert back to 6.0.2, this issue disappears.

When running in 6.0.2, I am not seeing any component errors.  Looking through the commits between 6.0.2 and 6.0.3-canary.0, I don't see much that could have changed to cause this behavior.  It's baffling.  It *might* be related to #4458, but none of the commits leading up to 6.0.3-canary.0 look like they'd be doing something that would cause an error in any of my components.  Further, I'm not getting any error information logged anywhere.

The worst part is, I can't reproduce this in a small app.  It's only happening in a big, complex app that I can't share in any useful manner.  It's entirely possible that I'm doing something I shouldn't be doing, and that it's my own code to blame.  I was really hoping to spot something in the commits between 6.0.2 and 6.0.3-canary.0 that might point me in the right direction but I've come up empty after a good 8 hours of poking at this.  The fact that I'm not getting any errors anywhere, just a 404, is a big problem in trying to track down what's going on.  If that 404 *is* caused by #4458, is there a known workaround for that issue?  That might help me uncover some underlying component error that's currently being buried.

## To Reproduce

Unable to reproduce outside of the primary app I'm working on right now.

## System information
 - OS: macOS
 - Version of Next.js: 6.0.3-canary.0 - 6.1.1

## Additional context

 - I use a custom server.
 - I have a custom _app and _document.
 - I wrap _app with several higher order components (but removing them doesn't resolve the problem)
 - The getInitialProps of all the HOCs wrapped around my _app are running without error and their expected output props are present in the render method of _app.
 - Logging the custom route handling from my server, I can see the requests coming in, and I can see the correct routing happening.  This is definitely not a case of a missing `as` on a Link, and not caused by a failure to route a pretty URL to a Next URL.
 - Sometimes, the 404 page will attempt to reload on its own after a minute or so and I'll get an error in one of my components that looks like the component is being called with no properties being passed.  This error is definitely outside of my code, and probably just a side effect of whatever is going wrong further up the rendering path.
 - It doesn't seem like the change in hot-loader made for 6.0.3-canary.0 has anything to do with this, but I can't entirely rule it out as a possibility.  Are there a bunch of commits somewhere that I'm missing between 6.0.2 and 6.0.3-canary.0?
 - My entire app works fine, no errors and no reload issues, on 6.0.2.

It's so bizarre for this to pop up between two releases that have only one tiny and seemingly unrelated code difference between them, but maybe I'm overlooking something.

**Comment by timneutkens** [comment]
I'm not sure what to do with this without a reproduction.

**Comment by ryanfields** [comment]
@timneutkens I realize not having a repro makes this challenging, but let me reiterate that the entire app works completely fine in 6.0.2, and then exhibits this problem from 6.0.3-canary.0 onward.  I'm trying to find any hint at what happened between those two versions that would take down a previously working app.

If my routes were not configured, then my app wouldn't work in 6.0.2 and prior versions.

**Comment by ryanfields** [comment]
**Solved**

I unknowingly caused the same issue raised in #2584.  I needed Webpack's ModuleConcatenationPlugin and, short of having gone into github's search, had no way of knowing the plugin was known to cause issues in dev.  It also appears to cause much more severe issues if included twice in the plugins list (which occurs in a production build if it has been manually added in next.config.js)

As a very low-priority feature request, it would be helpful to have next scan the webpack config for known issues specific to next and provide warnings.
