### ISSUE TITLE
SSR asPath behavior when mounting app under a path

### ISSUE THREAD

**Issue by Janpot** [zeit/next.js#4792]
# Bug report

## Describe the bug

When [mounting the next.js handler under a path](https://github.com/Janpot/next-mount-subpath/blob/24aa5902a740e9cf51e1f0ada011e5514852d4c7/index.js#L19) `asPath` shows different values on server and browser.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone https://github.com/Janpot/next-mount-subpath
2. `npm i`
3. `npm run dev`
4. Go to `http://localhost:3000/test`
5. check the console

## Expected behavior

No warnings

## Screenshots

![screen shot 2018-07-17 at 16 25 51](https://user-images.githubusercontent.com/2109932/42823544-1abb0a82-89de-11e8-9d2b-e6a0dbf83372.png)

## System information
 - OS: macOS
 - Browser: chrome
 - Version of Next.js: 6.1.1

**Comment by timneutkens** [comment]
Unrelated to this issue, but you're missing:

```
    server.get('*', (req, res) => {
      return handle(req, res)
    })
```

**Comment by Janpot** [comment]
Actually, I don't want to serve anything under the root. I plan to compose several of these together with `micro-proxy`.
The app is working without your piece of code. What is it supposed to add?

**Comment by timneutkens** [comment]
Oh wait nvm you want to only server un /test 👍

**Comment by Janpot** [comment]
For context, I'm just in the experimentation phase of a new i18n workflow I'd like to try.
basically
1. I'd like to run a next.js app for each locale
2. all of them get composed together with proxying
3. the next.js app webpack configuration will be augmented so it inlines i18n messages as react components (similar to [this](https://github.com/Janpot/i18n-test) experiment)

**Comment by timneutkens** [comment]
It's actually a problem with express, they override `req.url` when using `app.use`

https://expressjs.com/en/api.html#req.originalUrl

```
This property is much like req.url; however, it retains the original request URL, allowing you to rewrite req.url freely for internal routing purposes. For example, the “mounting” feature of app.use() will rewrite req.url to strip the mount point.
```

**Comment by Janpot** [comment]
Yes, they have `req.originalUrl` that we need to get back in the mix somehow

**Comment by timneutkens** [comment]
So what you have to do is `req.url = req.originalUrl` in the handler

**Comment by timneutkens** [comment]
This will also make sure Next looks for the right directory, as we don't have a client-side basepath option. Meaning your `next/link` wouldn't work correctly

**Comment by Janpot** [comment]
I tried `req.url = req.originalUrl` but it doesn't work for me. `next` doesn't seem to recognize the internal urls anymore.

also, I have a solution for the `next/link`, I just need to prefix the `asPath` with `/test`. Witha  little context magic this becomes relatively clean

```js
// components/link.js
import Link from 'next/link';
import React from 'react';
import PropTypes from 'prop-types';

export default class PrefixedLink extends React.Component {
  render () {
    const { href, as = href, ...props } = this.props;
    const { prefix = '' } = this.context;
    return <Link href={href} as={`${prefix}${as}`} {...props} />;
  }
}

PrefixedLink.contextTypes = {
  prefix: PropTypes.string
};

export class PathPrefix extends React.Component {
  getChildContext () {
    return { prefix: this.props.prefix || '' };
  }

  render () {
    return this.props.children;
  }
}

PathPrefix.childContextTypes = {
  prefix: PropTypes.string
};
```
Just make sure to set the context in `_app.js` and `Link`s work everywhere
```
// pages/_app.js
import App, { Container } from 'next/app';
import React from 'react';
import { PathPrefix } from '../components/link';

export default class MyApp extends App {
  static async getInitialProps ({ Component, router, ctx }) {
    let pageProps = Component.getInitialProps
      ? await Component.getInitialProps(ctx)
      : {};

    return { pageProps };
  }

  render () {
    const { Component, pageProps } = this.props;
    return <Container>
      <PathPrefix prefix='/test'}>
        <Component {...pageProps} />
      </PathPrefix>
    </Container>;
  }
}
```

**Comment by timneutkens** [comment]
All your pages should be put into `pages/test` with this setup, that's the reason it doesn't work.

**Comment by Janpot** [comment]
hmmm, that seems to generate some errors
```
GET http://localhost:3000/test/_next/-/page/test.js 404 (Not Found)
```

**Comment by Janpot** [comment]
@timneutkens Actually, the following seems to do it:
```js
    server.use('/test', (req, res) => {
      if (!/^\/(?:static|_next)\//.test(req.url)) {
        req.url = req.originalUrl;
      }
      handle(req, res);
    });
```
as well as
```js
    server.get('/test*', (req, res) => {
      const nextUrl = req.url.replace(/^\/test/, '');
      if (/^\/(?:static|_next)\//.test(nextUrl)) {
        req.url = nextUrl;
      }
      handle(req, res);
    });
```
but tbh, it feels a bit hacky. I mean, whether using express or anything else, some url rewriting like this is always going to need to happen. Since it relies on internal API design (`static|_next`), it feels quite brittle.

**Comment by Janpot** [comment]
In my ideal world I'd like to be able to do
```js
const app = next({
  dev,
  conf: {
    appPrefix: `/test`, // tell next where the app root is
    assetPrefix: `/test`
  }
});
```
And
```js
server.get('/test*', app.getRequestHandler());
```
And the pages would reside under `/pages` (no subfolder equal to the path)
This would make the resulting app quite portable across paths, only need to update `appPrefix`.
Is that something that next.js could be interested in in working towards?

**Comment by lucasnorman** [comment]
@Janpot Tried your method above and I got a 404 for all my _next files. 

    server.use("/auth", (req, res) => {
        if (!/^\/(?:static|_next)\//.test(req.url)) {
          req.url = req.originalUrl;
        }
        handle(req, res);
      });

    server.get("/auth*", (req, res) => {
    const nextUrl = req.url.replace(/^\/auth/, "");
    if (/^\/(?:static|_next)\//.test(nextUrl)) {
        req.url = nextUrl;
    }
    handle(req, res);
    });


<img width="391" alt="screen shot 2018-07-17 at 11 14 35 am" src="https://user-images.githubusercontent.com/26310749/42833872-a71128f8-89b2-11e8-80d8-d09d88ea809e.png">

**Comment by Janpot** [comment]
And you've put your pages under `./pages/auth/`?

**Comment by lucasnorman** [comment]
I did not. I think that is the issue... will report back once my build process finishes. Thanks!

**Comment by lucasnorman** [comment]
So for localhost:3000/auth/PATH I get:
`GET http://localhost:3000/_next/49d131b1-34ac-4d68-a8b2-a39a51266781/page/_app.js 404 (Not Found)`

My pages are now inside the auth subfolder. Anything else I am missing?

**Comment by Janpot** [comment]
@lucasnorman Check out this branch: https://github.com/Janpot/next-mount-subpath/tree/with-subfolder

@timneutkens Do you mean that with this solution, `<Link>`s are supposed to work with the right basepath?

**Comment by timneutkens** [comment]
Closing this in favor of #4998
