### ISSUE TITLE
next.js Link target

### ISSUE THREAD

**Issue by mylesan** [zeit/next.js#4795]
# Feature request

Please add the ability to pass target as props to Link

## Is your feature request related to a problem? Please describe.

I need to force a new tab for a .pdf located on the FS.

## Describe the solution you'd like

I'd like "target" to be added as a propType to Link with excepted types including but not limited to "blank", "new" etc.

## Describe alternatives you've considered

I could do this myself, but it seems like a useful feature which will add value to Next.

Here's an example of how I'd like to use it:

```
<Link href={this.props.url} target="_blank">click me</Link>
```

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/releases/tag/6.1.1-canary.1

https://github.com/zeit/next.js/pull/4763

```
<Link href={this.props.url}>
 <a target="_blank">
   click me
 </a>
</Link>
```

Currently only available on `next@canary`

**Comment by tzehe** [comment]
@timneutkens I have the same use case. Is this feature already released? I am on version 6.1.2. Or is there another way of achieving the same result. Thank you!

**Comment by timneutkens** [comment]
It's out on canary, will be part of Next 7.

**Comment by Khachatour** [comment]
Hey folks, I'm on Next 8.1.0, and I am experiencing the same issue. Any news?

**Comment by Khachatour** [comment]
@timneutkens Sorry it was my fault of not seeing the results, there is no issue, sorry for disturbing.
