### ISSUE TITLE
Can't resolve image loaded from node_modules

### ISSUE THREAD

**Issue by NirBenya** [zeit/next.js#4796]
# Bug report

## Describe the bug
When I load a component from node_modules that imports an image, I get SyntaxError: Invalid or unexpected token. I'm using url-loader and file-loader and when I import an image inside of my "normal" components its working fine. any ideas on why this is happening?

## To Reproduce
1.have a node_modules component that imports an PNG or JPG image inside it.
2. Import the component to the app.

## Expected behavior
The file will import as if it was a module loaded from inside the app.

## Screenshots
![screen shot 2018-07-18 at 4 10 27 pm](https://user-images.githubusercontent.com/15313208/42883747-25e8f870-8aa5-11e8-8756-2bd83c6fbaf0.png)

**Comment by timneutkens** [comment]
Please provide a full reproduction in a GitHub repository.

**Comment by codinronan** [comment]
@NirBenya the problem is that most webpack and babel plugins ignore node_modules by default. In almost all cases, that project's repo will direct you to copy the asset into your own project structure and import it from there, and this is exactly why.

Alternatively, there is a babel plugin called `transpile-modules` that should do this for you. Use it sparingly, it has a high build cost.

**Comment by wslx520** [comment]
@NirBenya I think we met the same problem: https://github.com/zeit/next.js/issues/4770 

and util now I haven't found the solution... maybe I should try @codinronan 's way

**Comment by NirBenya** [comment]
This is the solution that I found, that helps us "ignore" import modules from node_modules.

next.config.js:         

        const withSass = require('@zeit/next-sass')
         const withImages = require('next-images')
         const path = require('path');
        
        
        const internalNodeModulesRegExp = /NODE_MODULES_PACKAGE_NAME(?!.*node_modules)/;
        const externalNodeModulesRegExp = /node_modules(?!\/NODE_MODULES_PACKAGE_NAME(?!.*node_modules))/;
        
        
        const config = {
        
            webpack: (config, { buildId, dev, isServer, defaultLoaders }) => {
        
        
                config.externals = config.externals.map(external => {
        
                    if (typeof external !== "function") return external
                    return (ctx, req, cb) => (internalNodeModulesRegExp.test(req) ? cb() : external(ctx, req, cb))
                });
        
                config.module.rules.push({
                    test: /\.(png|jpe?g|gif|webp)$/i,
                    use: [
                        {
                            loader: 'url-loader',
                            options: {
                                outputPath: 'images/',
                                publicPath: '/_next/',
                                name: dev ? '[name]-[hash].[ext]' : '[hash].[ext]',
                                limit: 4000,
                            },
                        },
                    ],
                });
        
                // Important: return the modified config
                return config
            },
        
            webpackDevMiddleware: config => {
                const ignored = [ config.watchOptions.ignored[ 0 ], externalNodeModulesRegExp ]
                config.watchOptions.ignored = ignored
                return config
            }
        
        }
        
        module.exports = withImages(withSass(config));`
