### ISSUE TITLE
Error console "Warning: Unknown prop `jsx` on <style> tag. Remove this prop from the element."

### ISSUE THREAD

**Issue by babakness** [zeit/next.js#481]
Using Next@1.2.3

When I call a component that uses `<style jsx>` I get this written to the console (server & client)

```
Warning: Unknown prop `jsx` on <style> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in style (created by Unknown)
    in nav (created by Unknown)
    in Unknown (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by App)
    in App
```

The strange thing is that the problem wasn't happened on a previous run. What I did was try out `next@beta` then noticed that `<style jsx>` wasn't working there at all. I then downgrade to `stable` and this problem started.

**Comment by rauchg** [comment]
Re-opening this as https://github.com/zeit/styled-jsx/issues/51

**Comment by rauchg** [comment]
This shouldn't be happening actually, that means the transformation is not being run at all

**Comment by babakness** [comment]
Well the styles on `next@1.2.3` do get applied (i.e., `background-color: red` works) and I do get this error (not sure if this is something different than transformation). On `next@beta` I don't recall seeing the error and the style didn't apply at all (i.e., `background-color: red` doesn't work) .

**Comment by impronunciable** [comment]
@rauchg @babakness maybe I'm wrong but I think `next@1.2.3` ships with glamor and not `styled-jsx`. The styles are being applied because react is rendering the style tag into the html, that inject the styles (global) into the document.

**Comment by babakness** [comment]
@impronunciable Oh, so why doesn't it work when using `next@beta`?

**Comment by impronunciable** [comment]
@babakness it's working for me https://pea-qsjykozetl.now.sh/ (the code is at https://pea-qsjykozetl.now.sh/_src).

Try removing the `node_modules` folder and installing again to see if the issue is an outdated dependency.

**Comment by rauchg** [comment]
That's a beautiful example @impronunciable. Thank you <3

**Comment by rcolepeterson** [comment]
I still get this error. 
Using master branch and the example code.

**Comment by devdua** [comment]
Even I am seeing this error, I have installed next (v1.2.3) from npm though.

**Comment by skidding** [comment]
This seems to occur when I have two components in the same file (each with `<style jsx>`). Only the 1st style block gets transformed. Known limitation?

**Comment by rauchg** [comment]
No, can you provide an example please?

**Comment by skidding** [comment]
Dug a bit and it seems the problem happens when you have a tree of 3 components where only the root and leaf components have a `<style jsx>` tag, but not the middle one.

E.g. This works fine:
```jsx
function C() {
  return (
    <div className="c">
      C
      <style jsx>{`
        .c {
          color: blue;
        }
      `}</style>
    </div>
  );
}

function B() {
  return (
    <div className="b">
      B
      <C/>
      <style jsx>{`
        .b {
          color: green;
        }
      `}</style>
    </div>
  );
}

export default function A() {
  return (
    <div className="a">
      A
      <B/>
      <style jsx>{`
        .a {
          color: red;
        }
      `}</style>
    </div>
  );
}
```
But the `<style>` tag from component A no longer gets transformed (along with "Unknown prop `jsx` on <style> tag." error) when the `<style jsx>` tag is removed from component B:
```diff
function C() {
  return (
    <div className="c">
      C
      <style jsx>{`
        .c {
          color: blue;
        }
      `}</style>
    </div>
  );
}

function B() {
  return (
    <div className="b">
      B
      <C/>
-      <style jsx>{`
-        .b {
-          color: green;
-        }
-      `}</style>
    </div>
  );
}

export default function A() {
  return (
    <div className="a">
      A
      <B/>
      <style jsx>{`
        .a {
          color: red;
        }
      `}</style>
    </div>
  );
}
```
Notes:
- Is there any jsbin-like playground for Babel transforms? (aside from the standard ones at babeljs.io)
- This should probably be in the [styled-jsx](https://github.com/zeit/styled-jsx) repo

**Comment by rauchg** [comment]
Can you file it there? Thanks a lot for digging this up. @giuseppeg

**Comment by giuseppeg** [comment]
@skidding good catch, it stops working when there is a component without styles in between. I've got a fix :)

> Is there any jsbin-like playground for Babel transforms?

Yep http://astexplorer.net

**Comment by PatrickWilding** [comment]
Hey, we are seeing this issue also.

```
import React from 'react';
import Link from 'next/link';
import Head from 'next/head'

export default () => (
  <div>
    <Head>
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    </Head>
    <ul>
      <li className="mentorship">
        <a href="#">1:1 Mentorship</a>
      </li>
      <li className="support">
        <Link href="/support">Support</Link>
      </li>
      <li className="chat">
        <a href="#">Chat</a>
      </li>
      <li className="shop">
        <Link href="/shop">Shop</Link>
      </li>
    </ul>

    <style jsx>{`
       ul {
        display: flex;
       }

       li {
        list-style: none;
       }
      `}</style>
  </div>
);

```

next v1.2.3

**Comment by rauchg** [comment]
`style jsx` is 2.0.0 beta only ;)

**Comment by jimthedev** [comment]
Sorry I am a bit confused by the chain of comments. Should this be fixed in 2.0.1? I am still seeing it. Happy to post a snippet if it'd be useful.

**Comment by andrewmclagan** [comment]
Also seeing this on 2.0.1

**Comment by thebillkidy** [comment]
Still present on 2.1.1

**Comment by andrewmclagan** [comment]
Also on 2.1.1 and seeing this. The component logged against the warning changed if removed to another component

**Comment by drejohnson** [comment]
Also getting this error on latest (v2.3.0-alpha1)

**Comment by bukinoshita** [comment]
Getting on `v2.3.0-alpha1`.

It seems the styles are not scoped anymore. Getting styles from other components

<img width="325" alt="screenshot 2017-05-02 11 25 39" src="https://cloud.githubusercontent.com/assets/6929565/25625266/19ce7fa6-2f2a-11e7-8cc4-51a801658a5a.png">

#### Example

``` javascript
// badge.js
const Badge = ({children, type = 'primary'}) => (
  <div className={type}>
    {children}

    <style jsx>{`
      div {
        border-radius: 3px;
        padding: 4px 6px;
        font-size: .8rem;
        display: inline-block;
        vertical-align: middle;
        margin-left: 5px;
        color: ${colors.white};
      }
    `}</style>
  </div>
)
```

```javascript
// text-input.js
const TextInput = ({
  type = 'text',
  label = null,
  placeholder = null
}) => (
  <div>
    <label>{label}</label>
    <input type={type} placeholder={placeholder}/>

    <style jsx>{`
      div {
        margin-bottom: 30px;
      }
    `}</style>
  </div>
)

```

**Comment by pak11273** [comment]
everything magically started working once i added this to my .babelrc

`"plugins": [
    "styled-jsx/babel"
  ]`

**Comment by sbking** [comment]
Anyone getting this error when using TypeScript - add the following to your `tsconfig.json`:

    "jsx": "react-native"

This will prevent TypeScript from transforming JSX into `React.createElement` calls, but it will output files with the `.js` extension rather than `.jsx` (which next ignores).

**Comment by kunokdev** [comment]
When I use  `<style>{ templatestring }</style>` my CSS works and while I use it with `jsx` prop it stops working.

This is my `.babelrc` file

```
{
  "plugins": [
    "styled-jsx/babel",
    ["module-alias", [
      { "src": "./components", "expose": "Components" },
      { "src": "./containers", "expose": "Containers" },
      { "src": "./templates", "expose": "Templates" },
      { "src": "./redux", "expose": "Redux" },
      { "src": "./helpers", "expose": "Helpers"},
    ]]
  ],
  "presets": [
    "es2015",
    "next/babel"
  ]
}
```
package versions:
"styled-jsx": "^1.0.8",
"next": "^2.4.7",

**Comment by kallada1978** [comment]
while using styled-jsx in our application we are also getting the same error.
Warning: Unknown prop `jsx` on <style> tag. Remove this prop from the element. For details, see ```https://fb.me/react-unknown-prop
    in style (created by FirstPage)
    in div (created by FirstPage)
    in FirstPage (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Root)
    in Root
    in Provider```


## Sample code:
```
    return (
           <div>
                         <p>Styled With styled-jsx/babel - RED</p>
                         <style jsx>{` p {color: red;}`}</style>
           </div>
                  );
    
package versions:
"styled-jsx": "^1.0.10",

**Comment by mattyfresh** [comment]
Was having the same issue trying to get some Next.js boilerplate set up, what fixed it for me was installing `styled-jsx` (`npm i styled-jsx`) and adding `"styled-jsx/babel"` to my babel plugins.

https://www.npmjs.com/package/styled-jsx

**Comment by ssamakar** [comment]
Adding `"styled-jsx/babel"` to the babel plugins worked for me, but only when it was listed first, like so:

`
"plugins": [
      "styled-jsx/babel",
      "transform-object-rest-spread",
      "transform-react-jsx"
    ]
`

**Comment by ssamakar** [comment]
Order matters when using in tandem with `transform-react-jsx`. Declare `styled-jsx/babel` first:

`"plugins": [
      "styled-jsx/babel",
      "transform-object-rest-spread",
      "transform-react-jsx"
    ]`
