### ISSUE TITLE
Custom syntax error / HMR error page

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#4813]
# Feature request

I would like to modify the error page for syntax errors.

`lib/error-debug` I believe.

My idea is to linkify the stack trace so I can open it in my IDE.

I do not see a way of doing it at preset.

**Comment by vjpr** [comment]
Looks like it would be a simple addition:

_client/index.js_

```
  ErrorDebugComponent = passedDebugComponent
  ErrorComponent = await pageLoader.loadPage('/_error')
```

```
  ErrorDebugComponent = await pageLoader.loadPage('/_error-debug')
  ErrorComponent = await pageLoader.loadPage('/_error')
```

**Comment by timneutkens** [comment]
Linking to source code will be trivial to add after https://github.com/zeit/next.js/pull/4639 lands, as errors get rendered by react-error-overlay which has this feature built in.
