### ISSUE TITLE
Allow passing of of object to <Head /> to specify contents

### ISSUE THREAD

**Issue by aequasi** [zeit/next.js#4820]
# Feature request

It would be nice if we could pass a spread object to `<Head />` (`<Head {...meta} />`), like [react-helmet](https://github.com/nfl/react-helmet/blob/master/test/HelmetTest.js#L1878) allows for

**Comment by aequasi** [comment]
For me, it provides a cleaner interface to using and updating Head. Helps reduce boilerplate too

For comparison, react-helmet allows for this (as i mentioned above), as does vue-head

**Comment by aulneau** [comment]
You could create a wrapper on top of it, eg:

```jsx
// <HeadWrapper {...meta} />

import Head from 'next/head'

const HeadWrapper = ({title, description, ...rest}) => <Head>
{title && <title>{title}</title>}
...
</Head>

```

**Comment by aequasi** [comment]
Yes, I'm aware that i can write a component/wrapper that can do that

**Comment by timneutkens** [comment]
Creating a wrapper component seems like the way to go. Like I said it's not worth making the next/head runtime bigger for this when it won't be used by all users.

**Comment by aequasi** [comment]
Its a quality of life feature for people coming from these other solutions that do use it this way. Doesn't seem like you guys will budge on this though. Re-open if you change your mind.

**Comment by timneutkens** [comment]
Feel free to create a wrapper for it and release it on npm though.
