### ISSUE TITLE
use with-typescript

### ISSUE THREAD

**Issue by zhangking** [zeit/next.js#4821]
# Examples bug report

## Example name
with-typescript

## Describe the bug
I use with-typescript width babel-plugin-import 
my .babelrc file like this

```
{
  "presets": [
    "next/babel",
    "@zeit/next-typescript/babel"
  ],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": true
      }
    ]
  ],
  "comments": false,
  "compact": "auto"
}
```
but it does't work

**Comment by briefguo** [comment]
https://www.google.com/search?source=hp&ei=sT9VW6mDDcPdvASl3Lr4DA&q=next+js+antd&oq=nextjs+ant&gs_l=psy-ab.3.0.0i10i203k1l2j0i10i30k1.3279.6869.0.8328.9.8.0.0.0.0.223.851.0j5j1.6.0....0...1.1.64.psy-ab..3.6.849.0..0j35i39k1j0i203k1.0.WgoP0pXIbg0

**Comment by briefguo** [comment]
https://github.com/zeit/next.js/issues/544

**Comment by zhangking** [comment]
thanks~   but these examples import all of antd.css , I just want the part of single component. So I set ` "style": true` , but show errors

**Comment by goodwinfame** [comment]
@zhangking 
add it in your next.config.js
```
// fix: prevents error when .less files are required by node
if (typeof require !== 'undefined') {
    require.extensions['.less'] = (file) => {}
}
```
