### ISSUE TITLE
Slow build time in 6.1 (introduced by 6.0.4-canary.4)

### ISSUE THREAD

**Issue by kenips** [zeit/next.js#4824]
# Bug report

## Describe the bug

My build time is doubled from ~75s to ~170s after going from 6.0.3 to 6.1.1. Pinpointing the release turns out that the increased was introduced in 6.0.4-canary.4. I'm taking a closer look but couldn't see anything in that release to stand out as the culprit. Any help on debugging would be appreciated.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Upgrade from 6.0.3 to 6.1.1

## Expected behavior
Build time not to double

## System information
 - OS: macOS 10.13.6
 - Version of Next.js: 6.0.4-canary.4

**Comment by timneutkens** [comment]
Probably related to the uglifyjs optimization we had that I removed because some users were complaining about slightly bigger build sizes, and without the optimization is the default in webpack 4.

**Comment by timneutkens** [comment]
This PR: https://github.com/zeit/next.js/pull/4536

**Comment by kenips** [comment]
Absolutely. Re-adding all options fixes the issue. Thanks!

**Comment by kenips** [comment]
@timneutkens I assume adding the options is the right thing to do now? What's the long term solution? Have minification done outside of build?

**Comment by timneutkens** [comment]
It's a rather interesting issue as uglifyjs is just plain slow with all optimizations, but it results in smaller builds. One thing we could do is create a plugin for faster builds with worse minification after webpack 4 lands 🤔

**Comment by kenips** [comment]
hmmm yeah... I think I need to leave the options in for now. Will check again after Webpack 4. Thanks!
