### ISSUE TITLE
Error checking updates TypeError: promisify is not a function in latest Next (6.1.1)

### ISSUE THREAD

**Issue by trevordmiller** [zeit/next.js#4831]
# Bug report

## Describe the bug

When running `next` to develop locally, outputs `Error checking updates TypeError: promisify is not a function`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. In a Next project with a `.babelrc` [like this](https://github.com/trevordmiller/trevordmiller-website/blob/master/.babelrc), run `next`
2. See error.

## Expected behavior

No errors when running `next` :)

## Screenshots

![image](https://user-images.githubusercontent.com/5497885/43154023-29e5bb36-8f30-11e8-89b5-44162e54e552.png)

## System information
 - OS: macOS
 - Version of Next.js: `6.1.1`

**Comment by timneutkens** [comment]
update-check is going to be removed in the upcoming canary release. I'm pretty sure this error happened because you're on a Node.js version update-check doesn't support.

**Comment by timneutkens** [comment]
Fixed by #4639

**Comment by trevordmiller** [comment]
Yep you were right, forgot I was testing an older version of node. Switched back to latest node and all is well. Thanks!
