### ISSUE TITLE
"next build" works locally but fails in "now" in latest Next (6.1.1)

### ISSUE THREAD

**Issue by trevordmiller** [zeit/next.js#4832]
# Bug report

## Describe the bug

I'm not sure where to put this - if it's related to `next`, `now`, or `mdx`. But when I run `next build` locally, it works just fine. When I run `now` and now runs `next build` it errors out. I've confirmed I'm using the same Node version locally that is used by `now` (8.11.3). I've got a `package-lock.json` - so in theory the build in `now` should be the same as local...

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. See [package.json](https://github.com/trevordmiller/trevordmiller-website/blob/546aef694ed838573437d8b92d1a1e5925e69efb/package.json)
2. Not sure why `next build` (npm run build) locally would be different than the `next build` in now

## Expected behavior

`next build` works the same locally as it does in `now`.

## Screenshots

**Local:**

<img width="748" alt="next-build-local" src="https://user-images.githubusercontent.com/5497885/43159936-027c9e50-8f41-11e8-8a9a-f030e3155029.png">

**In Now**

<img width="1425" alt="next-build-now" src="https://user-images.githubusercontent.com/5497885/43159941-05e4a3f8-8f41-11e8-95aa-8f5c5f445668.png">

Errors with `Cannot find module 'remark-highlight.js'`.

## System information
 - OS: macOS
 - Version of Next.js: 6.1.1
- Version of Node: 8.11.3 both local and in `now`
- Version of npm: 6.2.0 local, not sure about in `now` as it doesn't show it

**Comment by timneutkens** [comment]
Looks like the module wasn't installed, so I'm pretty sure it's not related to Next.js. I've asked @TooTallNate to check this issue.

**Comment by trevordmiller** [comment]
It’s in my package.json and works locally

**Comment by trevordmiller** [comment]
I also tried moving `remark-highlight.js` from a `devDependencies` to a `dependencies` and then get a different error:

![image](https://user-images.githubusercontent.com/5497885/43419071-2ecd0a9c-93fd-11e8-8cc5-40930be83d97.png)

Something weird is definitely going on when `next build` is run inside `now` because everything works locally for me (I've tried on multiple machines, fresh `node_modules` + `npm install`s etc.) and these dependencies are all in my `package.json` and `package-lock.json`: https://github.com/trevordmiller/trevordmiller-website

@timneutkens, do you get the same errors when you run `now` on this ^ project? These errors seem to have all started with the latest next + now releases.

**Comment by trevordmiller** [comment]
I could downgrade back to next.js 5, but I was hoping to use the new `_app.js`.

**Comment by trevordmiller** [comment]
Downgraded to working versions + Next 5: https://github.com/trevordmiller/trevordmiller-website/commit/c32f83263418084e60d13a16c39314270443f3c8

I'm going to wait until Babel 7 is stable before trying to upgrade to Next 6 again.

**Comment by trevordmiller** [comment]
Did some more digging and figured out the errors I was seeing were because Next.js now requires `devDependencies` it uses in a custom .babelrc to be `dependencies`. So I had to move the dependencies in `next.config.js` and `.baberc` to be production dependencies. It seems some of the Zeit docs are inconsistent with this; a few examples:

- `next-typescript` shows `--save`: https://github.com/zeit/next-plugins/tree/master/packages/next-typescript
- `next-mdx` shows `--save`: https://github.com/zeit/next-plugins/tree/master/packages/next-mdx
- `mdx` Next.js section shows `--save-dev`: https://github.com/mdx-js/mdx#nextjs (which is where my problem was, needs to be `--save` in latest Next

**Comment by timneutkens** [comment]
https://github.com/zeit/next-plugins/tree/master/packages/next-mdx#installation

Seems like the plugin docs are consistent, I guess we have to change the MDX docs to say to use the next-mdx plugin instead.

> now require devDependencies used by next to be dependencies

This seems highly unlikely. Which devdeps?

**Comment by trevordmiller** [comment]
Per https://github.com/mdx-js/mdx/issues/128 and the related https://github.com/mdx-js/mdx/pull/131, I had `@mdx-js/mdx`, `@mdx-js/loader`, and `remark-highlight.js` as `devDependencies` (`--save-dev`). Converting them to dependencies (`--save`) fixed the errors mentioned in this issue. Feel free to try it yourself. Seems to only apply when you have a custom `.babelrc`.
