### ISSUE TITLE
Hope can custom the root #__next div

### ISSUE THREAD

**Issue by wslx520** [zeit/next.js#4834]
# Bug report

## Describe the bug
For some special layout, it would be easier if we can custom the root div:  `#__next `
![image](https://user-images.githubusercontent.com/1026909/43184250-8dd67762-901a-11e8-8736-c85594d977a1.png)

Now when trying custom document by `_document.js`, we can do nothing about the `<Main />` component. all the props will be ignored:
![image](https://user-images.githubusercontent.com/1026909/43184319-c97067f6-901a-11e8-9471-198420db048e.png)

## Expected behavior
I hope the `Main` can accept several props, at least className.

**Comment by prichodko** [comment]
What about as simply as: 

```html
<head>
 <style>
  #__next {
     /* styles */
  }
 </style>
</head>
```

?

**Comment by wslx520** [comment]
@prichodko  😄 of course we can. but I prefer assign a className to it, if it's possible...

**Comment by Rukeith** [comment]
@prichodko where should I add this css to change __next's style?
I add to __document, but it didn't change.

**Comment by woniesong92** [comment]
+1, how can we add styles to `#__next`?

**Comment by woniesong92** [comment]
Ended up doing this:

```
import Document, { Head, Main, NextScript } from 'next/document'
import { ServerStyleSheet } from 'styled-components'

export default class MyDocument extends Document {
  static getInitialProps ({ renderPage }) {
    const sheet = new ServerStyleSheet()
    const page = renderPage(App => props => sheet.collectStyles(<App {...props} />))
    const styleTags = sheet.getStyleElement()
    return { ...page, styleTags }
  }

  render () {
    return (
      <html style={{ height: '100%'}}>
        <Head>
          <title>My page</title>
          <style>{`
            #__next { height: 100% }
          `}
          </style>
          {this.props.styleTags}
        </Head>
        <body style={{ height: '100%', margin: 0}}>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

**Comment by timneutkens** [comment]
We're not planning to change `#__next` anytime soon, as React always needs a root, so you can select this safely. There's no need to add an extra className as that makes the initial HTML document larger.
