### ISSUE TITLE
Test suite for canary branch fails

### ISSUE THREAD

**Issue by DullReferenceException** [zeit/next.js#4837]
# Bug report

## Describe the bug

The `canary` branch fails the test suite due to linting issues when running `yarn test`:

> .../next.js/examples/with-ioc/components/endbutton.js:8:1: Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead

## To Reproduce

1. Check out the latest `canary` branch
2. Run `yarn install`
3. Run `yarn test`

## Expected behavior
`yarn test` should pass.

## System information
 - OS: macOS
 - Version of Next.js: `canary`

**Comment by timneutkens** [comment]
I wonder why it passes on CI, but you can use `yarn testonly` to only run tests 👍
