### ISSUE TITLE
Prebuild next.js pages on server start

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#4841]
As discussed on Slack with @timneutkens

# Feature request

## Problem

During dev, `next/link` navigation is slow (~2s) the first time you visit a link.

## Solution

Prebuild multiple page entries on app start, so that visiting links is instant.

Initial start time will be a little slower though.

### Current situation

Currently, when running `await nextApp.hotLoader.ensurePage('/page')`, it will add an entry to the webpack config, and build it, then return a promise when its done. 

Then, when you visit `/page` from a `next/link`, webpack will not have to recompile, so it will be instant. The built page bundle will simply be served (no ssr, no webpack build).

### New feature

Adding a method called `ensurePages` that accepts multiple paths and builds them all at once.

### Further optimizations

**Commons chunk bundle**

Because Next knows what to build upfront now, we can server a commons chunk bundle (which is normally disabled in dev), which will split out shared libs between the pages.

Although, the autodll plugin might be better in this case because it can be used as a commons chunk bundle but is persisted to disk between server restarts.

## API/DX

Perhaps there could be a config option called `pageGroups`, passed as config to next.

Whenever a page from the page group is visited, all the pages are built ahead of time so they are instant. There would also be a way to specify an initial page group which would load during fresh server start.

E.g. Maybe you want all your pages under the `/admin*` path to be built together. Or if you are working on a CRUD form with edit/create/list, you want all these pages always loaded.

```
pageGroups: {
  initial: 'admin',
  groups: {
    admin: ['/admin*']
  }
}
```

**Comment by timneutkens** [comment]
Let's also track this in #4844
