### ISSUE TITLE
`next build` doesn't build CSS into output directory.

### ISSUE THREAD

**Issue by chilijung** [zeit/next.js#4845]
# Bug report

## Describe the bug

When using `@zeit/next-css` in `next.config.js`, in dev mode the CSS successfully built into `.next/static/style.css` but when using `next build` to build static version of the app will not generate `.next/static/style.css` in the directory.

## To Reproduce

You could reproduce this error in this demo https://github.com/Canner/canner-demo/tree/master/nextjs-ecom-with-firebase

`next.config.js` is located: https://github.com/Canner/canner-demo/blob/master/nextjs-ecom-with-firebase/functions/next.config.js

Steps to reproduce the behavior, please provide code snippets or a repository:
1. run `npm run dev` in dev mode css is generated.

<img width="193" alt="screen shot 2018-07-26 at 1 02 29 pm" src="https://user-images.githubusercontent.com/1216029/43242546-3e8db886-90d4-11e8-9aa3-db89f547f8fa.png">

2, run `./node_modules/.bin/next build` css is NOT generated in output directory.

<img width="195" alt="screen shot 2018-07-26 at 1 06 33 pm" src="https://user-images.githubusercontent.com/1216029/43242627-c0bf59c2-90d4-11e8-8a34-d596142869bc.png">

## Expected behavior
When entering `next build` in output folder it should also generate CSS files.

## System information
 - OS: [e.g. macOS, Windows]: mac
 - Browser (if applies) [e.g. chrome, safari]: chrome
 - Version of Next.js: [e.g. 6.0.2]: 6.1.1

**Comment by timneutkens** [comment]
This is unrelated to Next.js. Please file on next-plugins.
