### ISSUE TITLE
Rename `static/commons`

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#4847]
As discussed with @timneutkens on Slack, this name is confusing.

"commons" makes me think of `CommonsChunkPlugin`, but it is unrelated, the folder just contains shared libs. When I see `static/commons/main.js` I think its a commons bundle from the split chunks plugin.

`main.js` is the Next.js core libs.
`runtime.js` is the webpack runtime.

Alternatives:

- `static/commons/runtime.js` -> `static/runtime/webpack-runtime.js`
- `static/commons/main.js` -> `static/runtime/next-runtime.js`

Or maybe `static/shared`.

**Comment by jaydenseric** [comment]
Fixed by https://github.com/zeit/next.js/pull/4853?

**Comment by timneutkens** [comment]
Yep 👍
