### ISSUE TITLE
Next.js doesn't work properly in Safari

### ISSUE THREAD

**Issue by paschaldev** [zeit/next.js#4852]
When I try to run my next app on Safari, I get this error in the console and it makes the app not function properly.

```
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
```

## System information
 - OS: macOS
 - Browser: Safari Version 9.1.2 (11601.7.7)
 - Version of Next.js: 6.1.0

## Additional context

I've searched online and found the same issue with no solution, the only reasonable solution was to use `babel.js - browser targets`, however that breaks the app badly and it doesn't even build.

**Comment by timneutkens** [comment]
Most important part of the issue template is the `reproduction` which is missing here. How can I reproduce this? Do you have more info besides the error, like a stack trace?

**Comment by paschaldev** [comment]
@timneutkens I'm sorry. Apologies. However I don't know how to replicate the same bug because I have been working with chrome and I've never witnessed it. I only got the error when I tried testing with safari. The app is live, you can see it on heroku here https://zyombo-app.herokuapp.com

**Comment by timneutkens** [comment]
@paschaldev where should I see it? Works fine in safari for me 🤔

**Comment by paschaldev** [comment]
@timneutkens In the console.

**Comment by timneutkens** [comment]
Doesn't happen for me.

**Comment by paschaldev** [comment]
@timneutkens  Check the screenshot here? https://snag.gy/ug8SdQ.jpg

The verrsion of Safari is Safari 9

**Comment by paschaldev** [comment]
@timneutkens I noticed something... I have two apps built with next.js, same version. The admin part of the app works flawlessly on Safari and I don't get this error, however only this one shows the error. I'm trying to dig deeper so I can identify the source of the error.

**Comment by sergiodxa** [comment]
@paschaldev that error looks like you imported a module from npm which is using const and not transpiling it, since Next.js doesn't transpile node_modules with Babel it will go to the browser using const and throw in Safari.

That could explain why you only got it in that part (the module is only there).

**Comment by timneutkens** [comment]
Looks like it's coming from https://github.com/reactivestack/cookies/tree/master/packages/universal-cookie

I simply opened all .js files and searched for `const ` (with spacebar) and found specific vars related to that module.

**Comment by paschaldev** [comment]
Thanks for helping @timneutkens @saginadir I'll look for a way to transpile that with webpack config.

**Comment by timneutkens** [comment]
Or use next-cookies npmjs.com/next-cookies

**Comment by paschaldev** [comment]
Just leaving this here for anybody who stumbles upon this same issue. I added this to my `next.config.js` file and everything works fine on Safari, it no longer includes the `const` keyword. 

```js
webpack(config, options) {
	...
	config.module.rules.push(
		{
			test: /\.js$/,
			include: [
				/node_modules/
			],
			loader: 'babel-loader'
		}
	)
}
```

What this does is transpile every js file imported in our app with our babel configuration. Looks like a very lazy fix but solves the problem for me.
