### ISSUE TITLE
SPA Mode

### ISSUE THREAD

**Issue by adithep** [zeit/next.js#4860]
# Feature request

## Is your feature request related to a problem? Please describe.
Correctly me if I am wrong, but I think currently there is no way to generate SPA from next.js.

## Describe the solution you'd like
An SPA option in `export`. Perhaps something like: https://nuxtjs.org/guide#single-page-applications-spa-

**Comment by darrylsepeda** [comment]
I think this is what you are looking for: https://github.com/zeit/next.js#static-html-export?

**Comment by RafalFilipek** [comment]
Hi :)

What is wrong with current `next export`? [Static HTML export](https://nextjs.org/docs/#static-html-export) is in fact "SPA mode".

**Comment by HaNdTriX** [comment]
@RafalFilipek Thank you!

I am closing this in favor of: https://github.com/zeit/next.js/issues/4381
