### ISSUE TITLE
With-sw-precache example cache nothing from the existing files

### ISSUE THREAD

**Issue by darrylsepeda** [zeit/next.js#4862]
# With-sw-precache example cache nothing from the existing files

## Describe the bug
I tried to `run npm build` with-sw-precache example and found `Total precache size is about 0 B for 0 resources.`
It means that generated service-worker.js file cache nothing inside.
Why would you have service-worker if it doesn't cache anything inside?
I also have tried to remove `staticFileGlobsIgnorePatterns: [/\.next\//],`, but still can't make it works.
```
Error: Request for http://localhost:3000/build-manifest.json?_sw-precache=a46e3af2425249c25bd18dce0685f0e9 returned a response with status 404
```

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone [with-sw-precache](https://github.com/zeit/next.js/tree/5b3578e58f610828c0112f5c38f7d3089fd4942f/examples/with-sw-precache)
2. Run `npm i`
3. Run `npm run build`
4. See from the terminal, `Total precache size is about 0 B for 0 resources.`

## Expected behavior
Service-worker.js should cache all files and serves them when there is no internet connection.
![image](https://user-images.githubusercontent.com/5493333/43389012-3bd25c4a-941d-11e8-916d-128018ccc9c1.png)

## Screenshots
![image](https://user-images.githubusercontent.com/5493333/43389429-4cbf91ac-941e-11e8-8974-60edec5c0c8b.png)
First command with `staticFileGlobsIgnorePatterns: [/\.next\//],`
Second command without `staticFileGlobsIgnorePatterns: [/\.next\//],`, yet NextJs still can't get the cached files (already tried to serves static file from app.js, yet still failed), I need an example of how to do this in NextJS.

## System information
 - OS: macOS
 - Browser: chrome
 - Version of Next.js: 5.1.0 (current project) & latest (with-sw-precache)

**Comment by timneutkens** [comment]
@hanford might know more as he built http://npmjs.com/next-offline

**Comment by darrylsepeda** [comment]
This is weird, but after take a look from [this closed issue](https://github.com/zeit/next.js/issues/3551), the code works fine [here](https://with-sw-precache-seirryascz.now.sh/).

So I tried to ignore my build folder and run it in production env, it works as what it should be.
