### ISSUE TITLE
Remove onRouteChangeStart, onRouteChangeComplete and onRouteChangeError from examples

### ISSUE THREAD

**Issue by kachkaev** [zeit/next.js#4863]
# Examples bug report

## Example name
* [with-google-analytics](https://github.com/zeit/next.js/tree/canary/examples/with-google-analytics)
* [with-loading](https://github.com/zeit/next.js/tree/canary/examples/with-loading)
* [with-flow](https://github.com/zeit/next.js/tree/canary/examples/with-flow)

## Describe the bug

Despite that the docs are suggesting to use `Router.events.on('event' ...)` instead of `Router.onEvent = ...` since https://github.com/zeit/next.js/pull/4726, there still exist three Next.js examples that use old signatures:

  🔎 [onRouteChangeStart](https://github.com/zeit/next.js/search?q=onRouteChangeStart)  
  🔎 [onRouteChangeComplete](https://github.com/zeit/next.js/search?q=onRouteChangeComplete)  
  🔎 [onRouteChangeError](https://github.com/zeit/next.js/search?q=onRouteChangeError)

Despite that old calls still work, they cause TypeScript exceptions after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27143.

I tried switching from `Router.onRouteChangeStart` to `Router.events.on(...)` for the `nprogress` bar in my project, but got this pretty strange error:

```
next-dev.js:57 No router instance found.
You should only use "next/router" inside the client side of your app.
```

And that's despite wrapping the calls into an if:

```js
// lib/pageEvents.ts
import Router from "next/router";
import NProgress from "nprogress";

if (typeof window !== "undefined") {
  NProgress.configure({ showSpinner: false });

  Router.events.on("routeChangeStart", () => {
    NProgress.start();
  });

  Router.events.on("routeChangeComplete", () => {
    NProgress.done();
  });

  Router.events.on("routeChangeError", () => {
    NProgress.done();
  });
}
```

<details>
<summary>temporary workaround</summary>

```ts
import Router from "next/router";
import NProgress from "nprogress";

if (typeof window !== "undefined") {
  NProgress.configure({ showSpinner: false });

  (Router as any).onRouteChangeStart = () => {
    NProgress.start();
  };

  (Router as any).onRouteChangeComplete = () => {
    NProgress.done();
  };

  (Router as any).onRouteChangeError = () => {
    NProgress.done();
  };
}
```

</details>

## To Reproduce
N/A

## Expected behavior
Given that `Router.events.on` is what's currently documented in README.md, I'd expect `Router.events.on` work on the client for the `nprogress` example (i.e. when routing events are not inside `withRouter` hoc etc).

## Screenshots
N/A

## System information
 - OS: macOS
 - Version of Next.js: `6.1.1-canary.2`

## Additional context

N/A

**Comment by timneutkens** [comment]
It's currently on canary https://github.com/zeit/next.js/releases/tag/6.1.1-canary.0 that's why the examples haven't been updated.

**Comment by kachkaev** [comment]
Hey @timneutkens 👋

Do you know why `Router.events.on(...)` does not work on the client and throws an exception as if I called this on the server?

**Comment by timneutkens** [comment]
cc @DullReferenceException

**Comment by DullReferenceException** [comment]
Looks like there's still a use case for the static properties after all. Attaching to the router events wouldn't work until this code runs, so maybe that client code has to be moved so it's called after mounting?

https://github.com/zeit/next.js/blob/75476a91362d6dc4e9fe7bda103adeab1e81f2d8/client/index.js#L96

Should we just add back in the static methods and have both techniques documented so there's no breaking change?

**Comment by DullReferenceException** [comment]
I guess the alternative is to put the code in a `SingletonRouter.ready` callback, like this:

https://github.com/zeit/next.js/blob/canary/lib/router/index.js#L43

**Comment by DullReferenceException** [comment]
If we want to just update the samples to not use the static event handlers, this seems to work:

https://github.com/zeit/next.js/pull/4864

**Comment by benhjames** [comment]
Looks fixed - can't find any instances of these in the repo anymore. 🙂

**Comment by timneutkens** [comment]
Thanks @benhjames!
