### ISSUE TITLE
MDX import results in "Module parse failed: Unexpected character..."

### ISSUE THREAD

**Issue by harrysolovay** [zeit/next.js#4867]
# Bug report
<img width="694" alt="screen shot 2018-07-30 at 6 12 58 pm" src="https://user-images.githubusercontent.com/4893548/43426604-3d46963e-9424-11e8-8623-62ff6b8f7fca.png">

## Describe the bug
I'm trying to use the @zeit/next-mdx package to import .mdx files (and their metadata) into one of my pages. I'm pretty sure I'm using the plugin correctly. I'm also using TypeScript (potential source of error), but have defined an mdx.d.ts:

`

    declare module '*.mdx' {
        let MDXComponent: (props) => JSX.Element
        export default MDXComponent
    }

`

I believe that I've properly configured the plugin in my next.config.js. To see the project more in depth, check out [the repository](https://github.com/harrysolovay/NextJS-TypeScript-MDX).

## To Reproduce
1. clone [the repository](https://github.com/harrysolovay/NextJS-TypeScript-MDX)
2. yarn && yarn start
3. open the locally-served site in Chrome and make sure it displays without errors
4. open the project in your code editor and navigate to pages/Landing/index.tsx
5. uncomment lines 6 & 7
6. save & refresh
7. BUG BUG BUG

## Expected behavior
The console log (line 7 in pages/Landing/index.tsx) is supposed to print out the imported MD as a JSX/TSX-compatible component and the metadata as an object literal.

## System information
 - Version of macOS: High Sierra 10.13.5
 - Version of Chrome: 68.0.3440.75
 - Version of Next.js: 6.1.1

## Additional context
Thank you so so so much for taking the time to look this over. Please let me know if you have any questions. I searched pretty hard and don't see this issue elsewhere. Apologies in advance if the answer is obvious. Hopefully this is helpful to others as well.

**Comment by timneutkens** [comment]
Pretty sure it's related to Typescript, could you post this issue in github.com/zeit/next-plugins. It's not directly related to Next.js itself.

**Comment by harrysolovay** [comment]
For sure. Thank you!
