### ISSUE TITLE
styles are not working correctly when navigating between pages using routers VueJs

### ISSUE THREAD

**Issue by MedDahTn** [zeit/next.js#4872]
i am using $router.push() to navigate between pages

**Comment by timneutkens** [comment]
Not sure what you're asking/saying. I'll close this as it's not following the issue template at all.

**Comment by MedDahTn** [comment]
i am using vuejs  and inside the page there is a  style i have 2 pages i navigate from page to the other using router .
Any one using vuejs could understand  this :) ;3
