### ISSUE TITLE
styles are not working correctly when navigating between pages using routers

### ISSUE THREAD

**Issue by MedDahTn** [zeit/next.js#4873]
i am using Vuejs: 
i have this page that has tow router-link and each page have <style> the problem is when i start the app everything is good until i use the router-link or any button that change the page with routers the style is changing .why ??
am using <router-link> and $router.push()
any help

**Comment by timneutkens** [comment]
Next.js is a framework on top of React. Maybe you're using http://github.com/nuxt/nuxt.js. Again you're not following the issue template.

**Comment by MedDahTn** [comment]
sry i am new to all of this :/ :)
