### ISSUE TITLE
some question with router

### ISSUE THREAD

**Issue by Weipengzhou** [zeit/next.js#4879]
I use next's link as matching 127.0.0.1/:id,
i o[en the real route 127.0.0.1/demo still still 127.0.0.1/:id. I then configured the route of 127.0.0.1/demo on the server side to access the current page. Is there a better solution
![image](https://user-images.githubusercontent.com/13349980/43505459-9784bd4e-9599-11e8-9388-694a5a640369.png)
![image](https://user-images.githubusercontent.com/13349980/43505465-9ac42a6c-9599-11e8-9355-c9a87d774af3.png)

**Comment by timneutkens** [comment]
Seems alright. Please follow the issue template in the future.
