### ISSUE TITLE
[v2] Back/Forward buttons break parameterized routes that use `async getInitialProps()`

### ISSUE THREAD

**Issue by jaredpalmer** [zeit/next.js#488]
I put together a demo repo [here.](https://github.com/jaredpalmer/next-back-button-error)

`async getInitialProps()` is not getting the correct `ctx` during `back()` with parameterized routes.

**Comment by nkzawa** [comment]
@jaredpalmer thanks for preparing the demo repo. It was so helpful for detecting the cause 😄

**Comment by jaredpalmer** [comment]
No problem.
