### ISSUE TITLE
Canary: SSR not reflecting updates

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#4880]
# Bug report

Discussed with @timneutkens on Slack.

## Describe the bug

After a change I am not seeing server SSR reflect the change.

The server bundle is being rebuilt properly, but its serving stale pages.

**Comment by vjpr** [comment]
The issue seems to be related to requiring an outside package from a page in `/pages`.

In my `pages/foo` I have:

```export default from '@org/my-monorepo-pkg'```

which becomes:

```/***/ "@org/my-monorepo-pkg":
/*!****************************************************************!*\
  !*** external "@org/my-monorepo-pkg" ***!
  \****************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@org/my-monorepo-pkg");

/***/ })

/******/ });```

**Comment by vjpr** [comment]
So the issue is that next.js has a default [webpack external](https://webpack.js.org/configuration/externals/) config that ignores everything in `node_modules` because bundling this server-side would be slower (and node_modules would be duplicated across all page bundles).

https://github.com/zeit/next.js/blob/183866a96db9a6bcf23c653ecc42de017d1cb519/build/webpack.js#L25

> The externals configuration option provides a way of excluding dependencies from the output bundles. Instead, the created bundle relies on that dependency to be present in the consumer's environment. This feature is typically most useful to library developers, however there are a variety of applications for it.

**Comment by clayhan** [comment]
@vjpr Going to try this out immediately!

**Comment by clayhan** [comment]
@vjpr Do you possibly have an example repo that demonstrates this? I am unable to get this to work on my end and I think I'm not doing quite a few steps beforehand. Thanks!

**Comment by timneutkens** [comment]
Going to close this as there's other issues discussing npm linked monorepo setups etc. Trying to reduce the amount of duplicate discussions.
