### ISSUE TITLE
getInitialProps called twice when you set backgroundImage to url() via styled-component style prop

### ISSUE THREAD

**Issue by janjarfalk** [zeit/next.js#4881]
# Bug report

## Describe the bug
The lifecycle method `getInitialProps` is called twice when you set `backgroundImage` to `url()` via styled-component `style` prop.

```js
// getInitialProps will be called twice.
<Title style={{backgroundImage: `url()`}}>My page</Title>
```

---

The lifecycle method `getInitialProps` WILL NOT be called twice when you set `backgroundImage` to `url(http://via.placeholder.com/350x150)` via styled-component `style` prop.

```js
// getInitialProps will NOT be called twice.
<Title style={{backgroundImage: `url(http://via.placeholder.com/350x150))`}}>My page</Title>
```

## To Reproduce
- Clone n' run.
```bash
git clone https://github.com/janjarfalk/with-styled-components-app
cd with-styled-components-app
yarn
yarn run dev
open http://localhost:3000
```
- Reload page
- Check terminal for two `getInitialProps`.

## Expected behavior
I expected the lifecycle method `getInitialProps` to be called once.

## System information
 - OS: macOS
 - Version of Next.js: 6.1.1

## Additional context
A one line change significantly reduced the load on our API. :)

**Comment by timneutkens** [comment]
<img width="518" alt="screen shot 2018-08-01 at 12 45 57" src="https://user-images.githubusercontent.com/6324199/43517416-e0ee811a-9588-11e8-9621-689a989a8b40.png">

This is not a bug or even related to Next.js, it's default browser behavior that when you include `url()` the browser tries to load the `/` route. So essentially on every page load, you had an extra page load. As you can see in the above screenshot.
