### ISSUE TITLE
Hydrate callback

### ISSUE THREAD

**Issue by kirkstrobeck** [zeit/next.js#4884]
# Feature request

## Is your feature request related to a problem? Please describe.

A third-party library needs to adjust the DOM, but it must happen after hydration is complete.

## Describe the solution you'd like

ReactDOM allows for a [`hydrate` callback](https://reactjs.org/docs/react-dom.html#hydrate), but it is not added [here](https://github.com/zeit/next.js/blob/75476a91362d6dc4e9fe7bda103adeab1e81f2d8/client/index.js#L201)

I would like to be able to pass a function in some way that would fire on hydrate-complete.

**Comment by Janpot** [comment]
If it isn't what you're talking about, would be useful for JSS too: https://github.com/cssinjs/examples/blob/gh-pages/react-ssr/src/client.js#L5

**Comment by HaNdTriX** [comment]
Looks like you only need this feature on the client. Maybe React s [`componentDidMount`](https://reactjs.org/docs/react-component.html#componentdidmount) will solve your problem in a more elegant way.

**Comment by timneutkens** [comment]
Yeah, componentDidMount would suffice for this.
