### ISSUE TITLE
Feature request: add ability to query pages structure

### ISSUE THREAD

**Issue by Janpot** [zeit/next.js#4885]
# Feature request

## Is your feature request related to a problem? Please describe.

Given a `/pages` folder. I'd like to be able to be able to
- build an overview page that lists and links to the other pages without having to define them statically
- build navigation components, like a sidebar, that is dynamically populated with whatever is in my project
- build sitemaps automatically based on the pages I have in my project
- build rss feed based on the pages I have in my project

## Describe the solution you'd like
a way to query the project structure at runtime. And a way to add metadata to the result from within the individual pages. For instance: there could be an endpoint like
```js
// GET /_next/structure?filter=/posts/*&fields=path,meta.title
{
  "pages": [
    { "path": "/posts/some-post", "meta": { "title": "This is some post" } },
    { "path": "/posts/some-other-post", "meta": { "title": "This is some other post" } }
  ]
}
```
for the project
```jsx
// /posts/some-post.mdx
export const meta = {
  title: This is some post
}

# This is some post
```
```jsx
// /posts/some-other-post.jsx
export const meta = {
  title: This is some other post
}

export default function Page () {
  return <h1>This is some other post</h1>
}
```

Or it could be a graphql endpoint that allows for querying a bunch of project and structure related data at runtime.
`getInitialProps` can then fetch this endpoint so the page can use it to build its UI, like:
```jsx
export default class extends React.Component {
  static async getInitialProps ({ req }) {
    return (await fetch(basePath(req) + '/_next/structure')).json();
  }

  render () {
    return (
      <div>
        {this.props.pages.map(({ path, meta }) => (
          <Link href={path}>{meta.title}</Link>
        ))}
      </div>
    );
  }
}
```
 It could also be used to fetch serverside to generate a sitemap on the fly.
Having it like this allows me to add/remove/change any page while the navigation of my site gets updated automatically.

## Describe alternatives you've considered

I started by trying to generate a json file in the `/static` folder with this information at build time. But there's a few challenges with this:
- in order to retrieve the `meta` object, the components need to be compiled and imported with the next configuration of the project. So in order to dothis, one will need to recreate the webpack configuration already in next
- one would also need to recreate the way next discovers and defines what are pages and their path. (index.js resolution etc...)

The problems lie mainly in generating the data. a static file would be less powerful than a graphql, but still useful.

## Additional context
I think it's also related to point 3. of this ticket https://github.com/mdx-js/mdx/issues/126

**Comment by HaNdTriX** [comment]
I am not sure if this helps but you could use babel-macros to gather the information you‘ll need at build time.

Here is an example of babel-macros and next.js: https://github.com/zeit/next.js/tree/canary/examples/with-babel-macros

Just use node-glob and babel-register to detect pages and extract the infos you need.
