### ISSUE TITLE
CSS selectors inside styled-jsx are escaped and not scoped when using the  Fragment shorthand (<>) syntax

### ISSUE THREAD

**Issue by rainice** [zeit/next.js#4886]
# Bug report

## Describe the bug
CSS selectors inside styled-jsx are escaped when server rendered resulting to incorrect CSS on initial load of the webpage. FOUC is experienced that gets corrected when the whole js file has been downloaded.

Primarily caused by unsupported shorthand syntax for react fragment.

## To Reproduce

1. Setup typescript with next.
2. create a page called index.tsx
3. add the following to index.tsx: 
```javascript
export default () => (
	<>
		<div className="m">
			<div>menu 1</div>
			<div>menu 2</div>
			<div>menu 3</div>
		</div>
		<style jsx>{`
			.m>div {
				color: red;
			}
		`}</style>
	</>
)
```
4. Errors will appear on the dev console.
```
warning.js:33 Warning: Received `true` for a non-boolean attribute `jsx`.

If you want to write it to the DOM, pass a string instead: jsx="true" or jsx={value.toString()}.
    in style (at minTest.tsx:8)
    in Err (at index.tsx:25)
    in Unknown (created by App)
    in Container (created by App)
    in App
    in ErrorBoundary
```
```
warning.js:33 Warning: Text content did not match. Server: "
			.m&gt;div {
				color: red;
			}
		" Client: "
			.m>div {
				color: red;
			}
		"
```

## Expected behavior
CSS should be scoped (with .m.jsx-3411211481>div.jsx-3411211481) and > should not be replaced by `&gt;`

```.m>div```
appeared as 
```.m&gt;div```

## System information
 - OS: Windows
 - chrome
 - next 6.1.1, react 16.4.2

## Additional context

Replacing the shorthand syntax <> to <React.Fragment> solves the issue.

**Comment by Conrad2134** [comment]
Not sure if it was alluded to in the description, but it looks like this is caused upstream in styled-jsx itself due to an incompatibility with Babel 7. Here's the related issue: https://github.com/zeit/styled-jsx/issues/458

**Comment by timneutkens** [comment]
@Conrad2134 is correct, this is an upstream issue and tracked on styled-jsx.
