### ISSUE TITLE
Link href should be resolved against base URI rather than window location

### ISSUE THREAD

**Issue by dinofx** [zeit/next.js#4888]
# Bug report

## Describe the bug

It seems like LInk's href property should be resolved against the document's baseURI (instead of window.location), which is how `<a>` tags would generally work.

## To Reproduce

In a page which sets the <base> compare the behavior of a plain anchor tag to that of the Link with only href set.

## Expected behavior
same resolution semantics as <a>, without requiring the user of "as".

**Comment by timneutkens** [comment]
Tracking this in #4998
