### ISSUE TITLE
`global` not set in browser from webpack for `2.x-beta`

### ISSUE THREAD

**Issue by philcockfield** [zeit/next.js#489]
Example repo showing a reference to MobX which assumes `global` is `window` in the browser.
https://github.com/philcockfield/nextjs-mobx

To start run:

    npm run dev

Error is thrown when MobX attempts to initialize itself by looking at `global`:

![image](https://cloud.githubusercontent.com/assets/185555/21445356/d486c1ce-c91c-11e6-8d31-b3c06f9c39c0.png)

The failing line of code: https://github.com/mobxjs/mobx/blob/6e3df706de1f1fc2408ba919559297cd0d07573e/src/core/globalstate.ts#L91

**Comment by philcockfield** [comment]
cc @arunoda

**Comment by arunoda** [comment]
Did this work with next `1.x`?

**Comment by philcockfield** [comment]
yes, it works on `1.2.3`.

**Comment by aesopwolf** [comment]
Getting the same error with uuid.
![image](https://cloud.githubusercontent.com/assets/6847633/21448299/e6504d62-c895-11e6-8668-1d8cb140905b.png)

If I remove all my uuid references then it throws the same thing with React

![image](https://cloud.githubusercontent.com/assets/6847633/21448345/80e78ae8-c896-11e6-9c99-bf9df4c2d0f0.png)

**Comment by aesopwolf** [comment]
Found this thread https://github.com/webpack/webpack/issues/1963

Looks like this problem will get automatically get fixed when webpack 2 support is added via https://github.com/zeit/next.js/pull/449

**Comment by arunoda** [comment]
@nkzawa is that because we removed the use of `babel-plugin-transform-remove-strict-mode`?

**Comment by arunoda** [comment]
@philcockfield frankly I don't know how this was not an issue in next 1.x and but in 2.x.
I just tried with #449 and seems like it's fixed in that.

**Comment by nkzawa** [comment]
> is this because we removed the use of babel-plugin-transform-remove-strict-mode?

@arunoda probably

**Comment by philcockfield** [comment]
@arunoda, @nkzawa - awesome re #449 - and getting Webpack 2 rolling.  That blocking issue seems like it's progressing, but ominous!  Any chance a webpack 2 enabled beta of Nextjs will be released soon?

**Comment by sedubois** [comment]
I get the same issue when using `uuid` dependency, worked in next@1.2.3 but with next@2.0.0-beta.1 I get `Cannot read property 'crypto' of undefined`, apparently thrown [here](https://github.com/kelektiv/node-uuid/blob/681bddd6f4cf3abb8c1af93c30d035b695cbe756/lib/rng-browser.js#L7) (looking for `global.crypto`). /cc @luisrudge

**Comment by rauchg** [comment]
Seems like we need to fix `global` :D

**Comment by arunoda** [comment]
Guys, I did a fix for this and it's now available on the master.
Could you try it out?

**Comment by hoangzinh** [comment]
@arunoda I still get the error after tried on branch master

<img width="595" alt="screen shot 2016-12-26 at 9 04 11 pm" src="https://cloud.githubusercontent.com/assets/9639873/21483053/f376cf86-cbae-11e6-9087-93e4227ec5c0.png">

**Comment by arunoda** [comment]
I checked with @philcockfield's example repo and it works pretty well.
@hoangzinh could you send us a sample app as well?

**Comment by hoangzinh** [comment]
@arunoda I tested on 2.0.0-beta.5, it works property on my repo right now. Thanks @arunoda
