### ISSUE TITLE
Dynamic Routes

### ISSUE THREAD

**Issue by maxmeng93** [zeit/next.js#4890]
# Feature request
Dynamic Routes

## Is your feature request related to a problem? Please describe.
I need Dynamic Routes. Implementation like 'nuxt.js'.

## Describe the solution you'd like
https://nuxtjs.org/guide/routing
![123456](https://user-images.githubusercontent.com/16930628/43634366-7b193ab2-973e-11e8-8dea-cfc05fa980de.png)

**Comment by sergiodxa** [comment]
You can do that using a custom server. We have many examples in the repo:
- https://github.com/zeit/next.js/tree/canary/examples
