### ISSUE TITLE
Fetching data and component lifecycle doc Issue

### ISSUE THREAD

**Issue by abnersajr** [zeit/next.js#4892]
## Fetching data and component lifecycle
Fetching data and component lifecycle section has a doc issue

## Describe the bug
Looking at the documentation of this section: https://github.com/zeit/next.js#fetching-data-and-component-lifecycle the example shows that you can get `{ req }`, but you don't have direct access to that.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to link  'https://github.com/zeit/next.js#fetching-data-and-component-lifecycle'
2. Look at the example

## Expected behavior
The right way to access is: `{ ctx: { req } }`.

**Comment by abnersajr** [comment]
Sorry, but it was a little different in my  `_app.jsx` that was causing this issue. It was a little bit different that I didn't figure out.

**Comment by HaNdTriX** [comment]
No problem happy to help 😉
