### ISSUE TITLE
styled-component styles being rendered in duplicate

### ISSUE THREAD

**Issue by ronnyhaase** [zeit/next.js#4897]
Hi issue #501 is happening to me, still or again.

(@nkzawa)

**Comment by spencersmb** [comment]
That happens to me too when developing. However as soon as I restart the server and reload the page everything looks good. Should it behave differently?

**Comment by timneutkens** [comment]
Not sure what to do with this issue as it doesn't follow the issue template and there no reproduction. So I'm going to close it.

**Comment by ronnyhaase** [comment]
Sorry!
It's also not related to NextJS anyways, it's caused by styled-components >= 3.4.0.

**Comment by josephluck** [comment]
@ronnyhaase - we're seeing a similar issue here, would you mind sharing what the behaviour was and how you solved it?

**Comment by ronnyhaase** [comment]
I think we're on the same discussion already 😉 
https://github.com/styled-components/styled-components/issues/1890

I created the issue.

**Comment by ronnyhaase** [comment]
A temporary solution is to downgrade to styled-components 3.3.3.
