### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by bluezip** [zeit/next.js#4898]
```
import React from 'react'
import Router from 'next/router'

export default class About extends React.Component {
  render() {
    console.log(Router.router.query)
    return (
      <div>sss</div>
    )
  }
}
```

not work on server render

https://ibb.co/dEaViz
![screencapture-localhost-3000-about-xxxxxxx-2018-08-05-18_47_30](https://user-images.githubusercontent.com/3119129/43687612-3eb02bf6-9902-11e8-886b-40fb38ec4104.png)

**Comment by bluezip** [comment]
close

_app.js not pass router

`import App, { Container } from 'next/app'
import Layout from '../components/shared/Layount'

export default class MyApp extends App {
  render() {
    const { Component} = this.props
    return (
      <Container>
        <Layout>
          <Component {...this.props} />
        </Layout>
      </Container>
    )
  }
}`

**Comment by timneutkens** [comment]
You should use `withRouter` instead.
