### ISSUE TITLE
Canary: with-global-stylesheet does not work with the latest canary version

### ISSUE THREAD

**Issue by mohammad-naji7** [zeit/next.js#4902]
# Examples bug report
[with-global-stylesheet](https://github.com/zeit/next.js/tree/canary/examples/with-global-stylesheet)

## Example name
with-global-stylesheet

## Describe the bug
When you try to open the page you will get this
```
./styles/index.scss
Module build failed (from ./node_modules/next/dist/build/webpack/loaders/emit-file-loader.js):
TypeError: Cannot read property 'context' of undefined
```
## To Reproduce
Just try to run the project after installing the latest Canary version.

## Screenshots
<img width="1064" alt="screen shot 2018-08-06 at 1 58 35 pm" src="https://user-images.githubusercontent.com/13167378/43713349-fac48ce0-9981-11e8-8a98-4d1972506313.png">

## System information
 - OS: macOS
 - Version of Next.js: [6.1.1-canary.4]

**Comment by abusada** [comment]
I played around with the example, and noticed that inside [build/webpack/loaders/emit-file-loader.js#L21](https://github.com/zeit/next.js/blob/canary/build/webpack/loaders/emit-file-loader.js#L21)

it uses `const context = query.context || this.options.context` 

while in [webpack4 migration guide](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202) it states the following 


> webpack 3 already deprecated this.options in the loader context. webpack 4 removes it now, A lot of people are missing the this.options.context value now. It has been added as this.rootContext.

changing it to `const context = query.context || this.rootContext` fixed the issue.

i can make a pull request if the maintainers approve of the fix.

**Comment by abusada** [comment]
Another fix would be changing the example's [next.config.js](https://github.com/zeit/next.js/blob/canary/examples/with-global-stylesheet/next.config.js#L10) to the following 

```
{
  test: /\.(css|scss)/,
  loader: 'emit-file-loader',
  options: {
    context: path.resolve(), // <----
    name: 'dist/[path][name].[ext]'
  }
}
```

**Comment by timneutkens** [comment]
This example should really be removed. It's outdated and the recommended way would be to use @zeit/next-css instead.
