### ISSUE TITLE
Add the "Mentioned in Awesome" Badge

### ISSUE THREAD

**Issue by juandc** [zeit/next.js#4904]
The next.js framework is included in the [Web Frameworks](https://github.com/sindresorhus/awesome-nodejs#web-frameworks) section in the `awesome-nodejs` repository :tada:, so you can add the `awesome badge` in the README.

![](https://camo.githubusercontent.com/974d19bae442ae2c1657753f39651ade6bef3411/68747470733a2f2f617765736f6d652e72652f6d656e74696f6e65642d62616467652e737667)

**Comment by timneutkens** [comment]
Cool! I actually don't think we need an extra button in the readme though.
