### ISSUE TITLE
LESS in _document.js renders perfectly in DEV but is missing in PRODUCTION

### ISSUE THREAD

**Issue by aofolts** [zeit/next.js#4905]
# Bug report

## Describe the bug

When I import a LESS file in _document.js, it renders using run dev, but when I build and use run start, the style from global.less is not rendered.

LESS files seem to render properly everywhere BUT _document.js.

## To Reproduce

npm run dev
global.less in _document.js is rendered properly.

npm run start
global.less in _document.js is not rendered.

```
import '../src/less/global.less'

export default class Template extends Document {

  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps }
  }

  render() {
    return (
      <html lang='en_US'>
        <Head>
          <link rel="stylesheet" href="/_next/static/style.css" />
          <Typekit kitId='dxm1wgv'/>
        </Head>
        <body className="custom_class">
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

## Expected behavior
LESS files used in _document.js should render in DEV and PRODUCTION.

## System information
 - OS: macOS
 - Browser: Chrome 68
 - Version of Next.js: 6.1.1

**Comment by aofolts** [comment]
I moved my global LESS to a Layout component, and it rendered just, so I don't know why _document.js wouldn't work, but I guess it doesn't matter!

**Comment by timneutkens** [comment]
_document should't be used for anything other than html structure / css-in-js. Instead use _app.js for your business logic (css etc)
