### ISSUE TITLE
Investigate replacing lib/EventEmitter.js with mitt

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#4908]
https://github.com/developit/mitt

Mitt is 277 Bytes

EventEmitter.js is around 1.07KB

They have the same functionality from what I've seen.

**Comment by timneutkens** [comment]
@DullReferenceException could you check this out maybe?

**Comment by HaNdTriX** [comment]
Mitt is awesome but in my opinion "not very node like".

| Feature                              | node                    | mitt |
|--------------------------------------|-------------------------|------|
| chaining (register func return self) | yes                     | no   |
| supports class inheritance           | yes                     | yes  |
| wildcards                            | no                      | yes  |
| emit returns boolean                 | yes                     | no   |
| on/off                               | (after node version 10) | yes  |
| addEventListener/removeEventListener | yes                     | no   |

**Comment by timneutkens** [comment]
@HaNdTriX it doesn't really matter when all we do is provide the `.on` / `.off` externally through `router.events`.

**Comment by HaNdTriX** [comment]
No not at all. I am actually fine with using mitt. I just wanted to point out the differences.

The issue that was fixed by @DullReferenceException here https://github.com/zeit/next.js/commit/b492e6703de62e1b4a63957350108ce8db6eeb68 will be reintroduced though.

**Comment by DullReferenceException** [comment]
Probably an ok compromise. If the `EventEmitter` changes don't make it out of `canary`, nobody will know what they're missing out on. Maybe the `mitt` maintainers would be ok with some minor contributions (I just really like chaining but acknowledge it's just a convenience).

**Comment by lucleray** [comment]
With the current version, `event-emitter.js` is now ~400 bytes gzipped vs `mitt` is 200 bytes gzipped. Is it still worth it to use `mitt` ?
