### ISSUE TITLE
target attribute with <Link /> not working

### ISSUE THREAD

**Issue by mddanishyusuf** [zeit/next.js#4914]
# Bug report
target attribute not working with <Link />

## Describe the bug
I trying to set target property _blank/new into <Link /> but this is not working. Here is my code snippets.

`<Link href={`/abc/?id=${topic.id}`} as={`/abc/${topic.id}`} target="_blank"><a><div className="topic-content">{topic.title}</div></a></Link>`

I also try to add into <a> tag like this

`<Link href={`/abc/?id=${topic.id}`} as={`/abc/${topic.id}`}><a target="_blank"><div className="topic-content">{topic.title}</div></a></Link>` 

then the attribute showing into DOM.

![image](https://user-images.githubusercontent.com/9165019/43783591-bba22820-9a7f-11e8-833d-d89f871db21a.png)

If anyone face this issues and resolved. then let me know your solution.

Thanks

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information
 - OS: [e.g. macOS, Windows]
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [e.g. 6.0.2]

**Comment by codinronan** [comment]
You might want to check this again - I use this in about a zillion places and it works fine:

```js
<Link href={'/rentals'}>
  <a target="_blank" rel="noopener noreferrer">Rentals</a>
</Link>
```

**Comment by timneutkens** [comment]
It's only out on canary.

**Comment by mddanishyusuf** [comment]
@timneutkens  not working in my case.

**Comment by mddanishyusuf** [comment]
@timneutkens you have any idea how this will work in my case?
