### ISSUE TITLE
Lazy Loading Components get an "Cannot read property 'querySelectorAll' of null" error

### ISSUE THREAD

**Issue by nicu-chiciuc** [zeit/next.js#4915]
# Examples bug report

## Example name
Lazy Loading Components

## Describe the bug
After following all the steps and running the app, visiting `http://localhost:3000/p/hello-nextjs` will output the error `Cannot read property 'querySelectorAll' of null` with a stack trace.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://nextjs.org/learn/excel/lazy-loading-components/setup
2. Follow the steps
3. Visit http://localhost:3000/p/hello-nextjs

## Expected behavior
It is expected to not have an error.

## Screenshots
![capture](https://user-images.githubusercontent.com/4076804/43784792-9d5578de-9a6d-11e8-9bb4-652bc463c4ea.PNG)

## System information
 - OS: Windows 10 Pro
 - Version of Next.js: 6.1.1
 - Node: v10.8.0
 - npm: 6.1.0

**Comment by timneutkens** [comment]
Please move the issue to https://github.com/zeit/next-site/issues
