### ISSUE TITLE
Paths when build on Windows and deploying on Linux

### ISSUE THREAD

**Issue by dbuchet-bandc** [zeit/next.js#4920]
# Bug report

## Describe the bug
Hello there.
I started the exemple to deploy a NextJS app on Firebase Hosting.
It work well on local, but when I deploy and try online, I have an "Internal Servor Error" with this line in logs
`Error: Cannot find module '/user_code/next/server/bundles\pages\index.js`

I assume this is because I built the app on a Windows env, and deploying to a Linux.

Is there an option somewhere to force slashes during build?

Thanks!

**Comment by andrewmurray** [comment]
I have just hit this very same issue.

I have run the next build on a windows machine then used the Windows Subsystem for Linux (with an Ubuntu distro) to deploy to a linux box and the build-manifest.json, pages-manifest.json and main-6cc0b499433f56b326b8.js files all needed the double backslashes exchanged for forward slashes for it to work.

**Comment by Enalmada** [comment]
I tried to build on windows and deploy that result to AWS beanstalk and got the slashes issue.  It probably would be nice to be able to pass in some path character variable override.  I used Windows Subsystem for Linux to get around this:  

```
# optional symbolic link for convenience: https://superuser.com/questions/1083962/windows-linux-subsystem-accessing-files-outside-of-ubuntu
ln -s  /mnt/<repo_path> ./<repo>

# install node: https://gist.github.com/ryanttb/9c66880b367930e402c2323c024cd202
# if you forget pwd: https://askubuntu.com/questions/772050/reset-the-password-in-linux-bash-in-windows/808425#808425
sudo su
curl -sL https://deb.nodesource.com/setup_8.x > install_node.sh
chmod a+x install_node.sh
./install_node.sh
apt-get install nodejs
npm install npm@latest -g
```

**Comment by sonjh02** [comment]
It worked to me with command 

replace-in-file /\\\\\\\\/g / dist/functions/next/** --isRegex

[replace-in-file](https://www.npmjs.com/package/replace-in-file)

**Comment by Redfern** [comment]
Is there any update on this? We are having the same issue

**Comment by marshmellow1328** [comment]
Is there a reason to not always use forward slashes? From my experiences, Windows handles them fine.
