### ISSUE TITLE
After modifying the style, no page is automatically updated

### ISSUE THREAD

**Issue by maxmeng93** [zeit/next.js#4921]
# Bug report

## Describe the bug
After modifying the style, no page is automatically updated。

console output
```
[HMR] Updated modules:
[HMR]  - ./assets/scss/main.scss
[HMR] App is up to date.
```
But the page is not the latest. Need to refresh manually。

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information
 - OS: Windows 7
 - Browser chrome
 - Version of Next.js: 6.1.1

**Comment by HaNdTriX** [comment]
@maxmeng93 Please add some more information. E.g. code example

**Comment by timneutkens** [comment]
Going to close this as there is no reproduction. Also, this is unrelated to Next.js. So it should be filed in https://github.com/zeit/next-plugins.
