### ISSUE TITLE
Shallow Routing doesn't work as expected (can't get new query)

### ISSUE THREAD

**Issue by bgold0** [zeit/next.js#4925]
# Bug report
I'm having trouble getting the new query params during a shallow route once the URL is changed using `componentWillReceiveProps(nextProps) {}`

## Describe the bug
It says in the [documentation](https://github.com/zeit/next.js/#shallow-routing) that by doing:

`Router.push( '/create/step?part=2, '/create/step/2, { shallow: true })`

It should give you a `url` attribute in `nextProps`. 

`const { pathname, query } = nextProps.url`

However, in `componentWillReceiveProps` I only receive the past URL component that only has the old `pathname` and `query`. Not that the URL in the browser DOES change.

## Expected behavior
My goal is to be able to get the new query parameters so I can change the state.

## System information
 - OS: macOS
 - Browse:r safari
 - Version of Next.js: 16.4.1

**Comment by rajendraarora16** [comment]
How did you resolve this? In case, if I am using next routes then it redirects me to 404 page.
