### ISSUE TITLE
Dynamic import `Uncaught (in promise) Error: Cannot read property 'default' of undefined`

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#4927]
# Bug report

## Describe the bug

Similar to: https://github.com/zeit/next.js/issues/3775

In canary (webpack@4), navigating to a page with a non-SSR dynamic import causes an error.

```
main.js:303 Uncaught (in promise) Error: Cannot read property 'default' of undefined
    at map.js:176662
    at register (main.js:1956)
    at PageLoader.registerPage (main.js:1994)
    at map.js:2
```

`default` refers to `comp.default`. `comp` is undefined. See `build/static/development/pages/x.js`:

```
/***/ 5:
/*!****************************!*\
  !*** multi ./pages/map.js ***!
  \****************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! ./pages/map.js */"./pages/map.js");


/***/ })

},[[5,"static/runtime/webpack.js","styles"]]])
            return { page: comp.default }
          })
        ;
```

Visiting the page directly via url works fine.

## To Reproduce

TODO: Make a repro.

## System information
 - Version of Next.js: canary

---

I noticed `dynamicImports = []` for every render here:
https://github.com/zeit/next.js/blob/a41e3c102e509db93f62be34eb782f73e43f95a7/server/render.js#L147

**Comment by timneutkens** [comment]
I guess the issue is `[5,"static/runtime/webpack.js","styles"]` "styles" seems like a runtime which webpack didn't include when I was testing next-css

**Comment by timneutkens** [comment]
This issue is very similar to https://github.com/zeit/next-plugins/issues/282
