### ISSUE TITLE
duplicate component 

### ISSUE THREAD

**Issue by ciumexan** [zeit/next.js#4928]
# Bug report
duplicate component, weird render. 
packages: 
`
    "babel-polyfill": "^6.26.0",
    "metamask-logo": "^2.1.4",
    "next": "^6.0.3",
    "react": "^16.4.1",
    "react-countdown-now": "^1.3.0",
    "react-dom": "^16.4.1",
    "semantic-ui-css": "^2.3.2",
    "semantic-ui-react": "^0.81.2",
    "solc": "^0.4.24",
    "truffle-contract": "^3.0.6",
    "truffle-hdwallet-provider": "^0.0.5",
    "web3": "^1.0.0-beta.34"
`
## Describe the bug
Duplicate component, weird render. 
While i add the components in the index.js page, i see duplicated renders of the components

My index.js looks like: 
`
export default () => {
return (
              <span>
                <HeadPage />
                <HomeFirstSection />
                <HomeWhatIsThis />
              </span>
         );
};
`
HomeWhatIsThis component renders twice: 
`
import React, { Component } from 'react';
import { Grid, Segment, Image } from 'semantic-ui-react';
class HomeWhatIsThis extends Component {
render() {
          return(
html );
}
}
export default HomeWhatIsThis;
`

## System information
 - OS: macOS
 - Browser (if applies): chrome, safari, brave - the same pb, indicating is a server side render issue.
 - Version of Next.js: 6.0.3

**Comment by timneutkens** [comment]
> Duplicate component, weird render.

This is not actionable. So I'm going close this issue.
