### ISSUE TITLE
How to dynamically import external client-side only React components?

### ISSUE THREAD

**Issue by w31ha0** [zeit/next.js#4930]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

I know this question has been asked multiple times before but none of the solution seems to work.

I'm trying to use the library 'react-chat-popup' which only renders on client side in a SSR app.(built using next.js framework) The normal way to use this library is to call import {Chat} from 'react-chat-popup' and then render it directly as <Chat/>.

The solution I have found for SSR apps is to check if `typedef of window !=== 'undefined' ` in the componentDidMount method before dynamically importing the library as importing the library normally alone would already cause the window is not defined error. So I found the link https://github.com/zeit/next.js/issues/2940 which suggested the following:

```
Chat = dynamic(import('react-chat-popup').then(m => {
  const {Foo} = m;
  Foo.__webpackChunkName = m.__webpackChunkName;
  return Foo;
}));
```

However, my foo object becomes null when I do this. When I print out the m object in the callback, i get `{"__webpackChunkName":"react_chat_popup_6445a148970fe64a2d707d15c41abb03"}` How do I properly import the library and start using the <Chat/> element in this case?

**Comment by HaNdTriX** [comment]
Please check out the documentation about [With No SSR](https://github.com/zeit/next.js#3-with-no-ssr).

**Comment by w31ha0** [comment]
Hi I've actually tried to do something like this before:

```
const DynamicComponentWithNoSSR = dynamic(import('react-chat-popup'), {
    ssr: false
})
...
render(){
...
<DynamicComponentWithNoSSR/>](url)
```

but I got the following error `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `DynamicComponent for Unknown`.`

**Comment by HaNdTriX** [comment]
This is because of the way react-chat-popup exports its components. They don't use default exports. So you'll need some kind Proxy component.

They use:

```js
import { Chat } from 'react-chat-popup'
```

instead of 

```js
import Chat from 'react-chat-popup'
```

Since questions should be posted on https://spectrum.chat/next-js. I am closing this issue.

**Comment by samdawit** [comment]
I been trying to convert static html template to nextjs, i converted the html body and also linked the css but i am still getting erro
![error while importing css and bootstrap](https://user-images.githubusercontent.com/38301322/54555046-f7210780-49c6-11e9-974c-e118a75832a4.jpg)

**Comment by samdawit** [comment]
<img width="1280" alt="nextconfigjs" src="https://user-images.githubusercontent.com/38301322/54555098-15870300-49c7-11e9-83b3-34ea4545bd2b.png">

**Comment by samdawit** [comment]
I been at this for about a week now and i tried everything i can think of, can some please help me.
i can even upload the folder whole folder with out the node_module, and the static html template included inside the static folder

**Comment by HaNdTriX** [comment]
The problem with your code above, is that you are overwriting first `module.export` by the second one.

This is how it should look like

```js
const withCSS = require('@zeit/next-css')
module.exports = withCSS({
  webpack (config, options) {
    config.node = {
      ...config.node,
      fs: 'empty'
    }
    return config
  }
})
```

**Comment by samdawit** [comment]
Thank you very much Mr. Wenz, its working now but some of the owl-carousel, and sticking menu...
