### ISSUE TITLE
How to redirect?

### ISSUE THREAD

**Issue by Popugune** [zeit/next.js#4931]
I try in _app 

render(){
if(!auth) Router.push('login')
}

and got error

Error: No router instance found.
You should only use "next/router" inside the client side of your app.

how do redirect do right?

**Comment by klujanrosas** [comment]
The wiki has an [entry](https://github.com/zeit/next.js/wiki/Redirecting-in-%60getInitialProps%60) about this subject.

From what I've seen you should post any future questions not related to actual _issues_ to [Next's Spectrum Chat](https://spectrum.chat/next-js). 

Cheers :tada:

**Comment by Popugune** [comment]
@klujanrosas Your example doesnt work in my case

**Comment by sergiodxa** [comment]
Check the code of this module https://github.com/matthewmueller/next-redirect/ it's actually quite simple, you should redirect in getInitialProps to avoid rendering and fetching unnecessary data.

**Comment by jgillich** [comment]
Maybe some details would be great, instead of just downvoting. Because the example works completely fine for me.

**Comment by omonk** [comment]
I believe this is a difference in getInitialProps signature for `_app.js` and normal pages

**Comment by goldenshun** [comment]
@sergiodxa @jgillich I am doing something very similar to the implementation in `next-redirect` but after initiating a redirect on the client (via `window.location.href=""` where the string is the redirect url), `getInitialProps` still returns and the page still tries to render briefly before the browser redirects. Do you see the same behavior? Any tips on preventing that behavior?

**Comment by lifeiscontent** [comment]
@klujanrosas how do you redirect with a dynamic route e.g. `/blog/:postId`?

**Comment by ccemeraldeyes** [comment]
I am not sure why this got closed when it clearly does not answer the question for so many people.

 There HAS to be a way to do redirects outside `getInitialProps`. I am using `relay` and don't have the data I need to be able to determine the redirect until the component is partially loaded. At that point, I no longer have access to the router OR the `window` property, it seems.

**Comment by Timer** [comment]
Hey, all!

Issuing a side effect during rendering is not a standard React practice.
This can easily become problematic in many scenarios, especially if Next.js ever starts optimistically rendering `hidden` trees for navigation.

You should avoid [redirecting client-side within `getInitialProps`](https://github.com/zeit/next.js/wiki/Redirecting-in-%60getInitialProps%60) for the same reason. While this pattern works in practice, the patterns listed below are more encouraged.

Redirects are a side effect, and should occur as so within your component's events:
```jsx
componentDidMount() { // or componentDidUpdate, depending on what you're trying to do
  if (!auth) {
    Router.push('...')
  }
}

render() {
  if (!auth) {
    return null;
  }
  // ...
}
```

For a functional component:
```jsx
function MyPage() {
  useEffect(() => {
    if (!auth) {
      Router.push('...')
    }
  })

  // ...
}
```
