### ISSUE TITLE
Next Server

### ISSUE THREAD

**Issue by sebasgarcep** [zeit/next.js#494]
Why is Next its own server? Why can't it work as a middleware for Express, Koa or plugin for Hapi?

**Comment by FrancosLab** [comment]
You can definitely use Next programmatically.

It's already in Master if you want to clone the repo and officially planned for the 2.0 release.

https://github.com/zeit/next.js#custom-server-and-routing

https://github.com/zeit/next.js/wiki/Roadmap

**Comment by arunoda** [comment]
Thanks @FrancosLab for answer.
@sebasgarcep I hope now we could close this.

**Comment by sebasgarcep** [comment]
Thanks for the prompt response.
