### ISSUE TITLE
Full Stack HMR Best Practices

### ISSUE THREAD

**Issue by Vandivier** [zeit/next.js#4946]
# Question about Next.js

package.json for a basic next.js app doesn't specify webpack, which indicates to me that directly manipulating webpack is an antipattern. I have a custom express server and I'd like hot module replacement for server-side changes. I try to look up next.js HMR but it seems to be all UI concerns. Is there a best practice for this?

Questions should be posted on https://spectrum.chat/next-js
related Spectrum convo: https://spectrum.chat/next-js?thread=8d413431-c133-43c2-aaf6-bab53db02fee

**Comment by Vandivier** [comment]
fwiw, current server.js code:

const bodyParser = require('body-parser');
const { createServer } = require('http');
const express = require('express');

const { parse } = require('url');
const next = require('next');
const { join } = require('path');

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare().then(() => {
    const server = express();
    server.use(bodyParser.urlencoded({ extended: false }));

    server.get('/a', (req, res) => {
        return app.render(req, res, '/b', req.query);
    });

    server.get('/b', (req, res) => {
        return app.render(req, res, '/a', req.query);
    });

    server.get('/posts/:id', (req, res) => {
        return app.render(req, res, '/posts', { id: req.params.id });
    });

    server.post('/reports', (req, res) => {
        debugger;

        return res.json({ title: 'sample title' });
    });

    server.get('*', (req, res) => {
        const parsedUrl = parse(req.url, true);
        const rootStaticFiles = ['/robots.txt', '/sitemap.xml', '/favicon.ico'];

        //if (rootStaticFiles.indexOf(parsedUrl.pathname) > -1) {
        //    const path = join(__dirname, 'static', parsedUrl.pathname);
        //app.serveStatic(req, res, path);
        //} else {
        //    handle(req, res, parsedUrl);
        //}
        return handle(req, res);
    });

    server.listen(port, err => {
        if (err) throw err;
        console.log(`> Ready on http://localhost:${port}`);
    });
});

**Comment by codinronan** [comment]
@Vandivier replied in Spectrum.

**Comment by te-online** [comment]
@codinronan Could you provide us with a link to that conversation? I'd be very interested in that as well 😉

**Comment by timneutkens** [comment]
Going to close this as it's posted on spectrum.
