### ISSUE TITLE
Support for babel.config.js

### ISSUE THREAD

**Issue by cangoektas** [zeit/next.js#4947]
Looking at the new Babel docs it seems like [since Babel 7 `babel.config.js` is the recommended way to configure Babel](https://babeljs.io/docs/en/next/configuration.html). It has the advantage that configuration can be created dynamically and it's especially useful for monorepos since it takes precedence over all other configs in the project.

There was an issue for this already in #4275 but as far as I can see Next.js doesn't support a `babel.config.js`. If it does, then this would be a bug report. If it doesn't, this is a feature request. 🙂

My current use case is to use Next on the root level of a monorepo, where I use a dynamically computed `babel.config.js`. Next doesn't pick it up as an external Babel config.

**Comment by timneutkens** [comment]
The version of babel 7 that's currently shipped with Next.js doesn't support babel.config.js, #4937 will fix it.
