### ISSUE TITLE
Incorrect semver for recent canary releases

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#4955]
# Bug report

## Describe the bug

The last 6 releases, `6.1.1-canary.0` -> `6.1.1-canary.5` have incorrect semver. You shouldn't publish semver prerelease versions of a version (`6.1.1`) **_after_** it has been released:

<img width="388" alt="screen shot 2018-08-15 at 12 44 29 pm" src="https://user-images.githubusercontent.com/1754873/44128946-123ac9d0-a089-11e8-92be-1c0639a9e511.png">

People who see, and want, the latest release are likely to set a `^6.1.1-canary.5` dependency, not expecting `6.1.1` to be installed.

The current release should instead be `6.1.2-canary.5` or `6.2.0-canary.5`, depending if there are new features.

**Comment by jaydenseric** [comment]
https://semver.npmjs.com

<img width="471" alt="screen shot 2018-08-15 at 12 56 45 pm" src="https://user-images.githubusercontent.com/1754873/44129306-f07a8860-a08a-11e8-858a-5272b4b72840.png">

<img width="335" alt="screen shot 2018-08-15 at 12 56 51 pm" src="https://user-images.githubusercontent.com/1754873/44129312-f4073258-a08a-11e8-843f-0cbb057950bf.png">

**Comment by jaydenseric** [comment]
I spent the entire day yesterday trying to workout why `.mjs` packages were bundling incorrectly when yet the latest canary releases are meant to be Webpack v4. Only to discover this morning I'm not even getting the latest canary 😩

**Comment by timneutkens** [comment]
Fixed in https://github.com/zeit/next.js/commit/b9533c318d25225a9a66a766d83efde8ac2a176d
