### ISSUE TITLE
Styled-Components not working as expected while client-side navigating

### ISSUE THREAD

**Issue by MFCo** [zeit/next.js#4958]
# Bug report

## Describe the bug

The only styles that are loaded are the ones in the page you load, if you client-side navigate to another page there is no styles there.

We are migrating from LESS to Styled-Components, just the LESS styles are loaded when you client-side navigate the page.

The button itself is a next/link

## To Reproduce

1. Go to https://www.medbelle.com/
2. Click on `Advices & Prices` button
3. The new page is loaded without some styles
4. Refresh the new page
5. The page is loaded with all the styles

## Expected behavior
No diference between client-side navigating or hitting the server to load the page

## Screenshots
Client-side navigating:
![image](https://user-images.githubusercontent.com/7811417/44145338-842e4128-a08b-11e8-9d44-13c7147ad2de.png)

Hitting server:
![image](https://user-images.githubusercontent.com/7811417/44145354-92bde4a0-a08b-11e8-8262-2f0d9e65399f.png)

## System information
 - OS: Manjaro
 - Version of Next.js: 6.1.1
 - Version of Styled-Components: 3.4.2

## Additional context

In development it works as expected and here is how I'm getting the styles in getInitialProps in `_document.js`, ctx is 

```javascript
  static getInitialProps(ctx) {
    const pageContext = getPageContext();
    const sheet = new ServerStyleSheet();
    const page = ctx.renderPage(Component => props => sheet.collectStyles(
      <JssProvider
        registry={pageContext.sheetsRegistry}
        generateClassName={pageContext.generateClassName}
      >
        <Component pageContext={pageContext} {...props} />
      </JssProvider>,
    ));
    const StyleTags = sheet.getStyleElement();
/* code continues */
```

**Comment by timneutkens** [comment]
Not sure what to do with this issue. There's not enough context to reproduce. Can you provide a minimal reproduction? I'm pretty sure it's not related to Next.js itself though.

**Comment by MFCo** [comment]
@timneutkens I just updated to last canary and seems to be fixed by upgrading Webpack stuff :smile: Thanks anyways! Now I'm just fighting with memory while building, it grows up considerably :fearful:
