### ISSUE TITLE
Hot loading breaks after error

### ISSUE THREAD

**Issue by denniscollective** [zeit/next.js#496]
This could be the same root cause as #495 but I wanted to submit them separately in case it's helpful.

**Comment by nkzawa** [comment]
Can you check if `2.0.0-beta.2` fixes the issue.

**Comment by nkzawa** [comment]
It can be the same issue with https://github.com/zeit/next.js/issues/345

**Comment by denniscollective** [comment]
Thanks for the work on this! I've figured some stuff out, as of 2.0.0-beta.2:

I'm new to the react work flow, so I still instinctively refresh the page when I want to see changes. After I do that I see it go the page go red and the stack trace appear. If I fix the error,  and hard refresh, the page renders again, but this time over the red background.  Hot loading will work again, but only after a reset to clear the stack trace and error page, after every hot load, the background is still red.

**Comment by rauchg** [comment]
@denniscollective thanks for the description!

**Comment by denniscollective** [comment]
Thanks for being welcoming! I hope to understand what's going on well enough to submit pull requests soon <3
