### ISSUE TITLE
Error 404 on URL direct loads! 

### ISSUE THREAD

**Issue by behnamazimi** [zeit/next.js#4961]
I know that there are many many questions about this issue in this community even others but, I could not find any solution for my case and really need help!

Here is my link:
```
<Link prefetch as={"/p/" + provider.username} href={"/provider?username=" + provider.username + "&type=" + provider.type}>
	My Link
</Link>
```

And here is my url handling in server.js:
```
server.get('/p/:username', (req, res) => {
            const actualPage = '/provider';
            let queryParams = {
                username: req.query.username,
            };
            if (res.query && res.query.type)
                queryParams.type = res.query.type;
            app.render(req, res, actualPage, queryParams)
        });
```

Everything is fine in dev mode but when I build my app and start it, the errors shown one by one!!! 

I really confused and need help!

**Comment by timneutkens** [comment]
Can you post your package.json? maybe you're bootup up using `next start` instead of `NODE_ENV=production node server.js` 🤔 Also please follow the issue template.

**Comment by behnamazimi** [comment]
My `packaje.json` scripts:

```
  ...
"scripts": {
    "dev": "node server.js NODE_ENV=production",
    "build": "next build",
    "start": "next start"
  },
...
```
Also I'm sorry that I have not followed your issue templates! But I had to.

**Comment by timneutkens** [comment]
> maybe you're bootup up using next start instead of NODE_ENV=production node server.js

It's exactly what I mentioned 😄 

```
"scripts": {
    "dev": "NODE_ENV=development node server.js",
    "build": "next build",
    "start": " NODE_ENV=production node server.js"
  },
```

**Comment by behnamazimi** [comment]
Oops!
