### ISSUE TITLE
Internet Explorer dont open the webpage when opened directly

### ISSUE THREAD

**Issue by abhishekj** [zeit/next.js#4962]
# Bug report
Whenever i browse the website via clicking on links, it works fine, but whenever i open the same link directly via pasting on the address bar, i am not able to open the page.

## Describe the bug
I am using nextjs and it call an API , i believe the external API is not being called
This occurs only on Internet Explorer 11, and lower, however it works fine on other browsers including Edge

## Expected behavior
The webpage should open while visiting directly or via anchor links,

thanks

**Comment by timneutkens** [comment]
I'm going to close this issue as there's nothing actionable (no reproduction).
