### ISSUE TITLE
`Set` is undefined on IE 10

### ISSUE THREAD

**Issue by YUFENGWANG** [zeit/next.js#4965]
# Bug report

`Set` is undefined on IE 10

## Describe the bug

I'm just running the with-react-intl example , but on ie10 developer tools console, there is an error 
`Set` is undefined 

## To Reproduce

1. npm install 
2. npm run dev
3. open ie, go to localhost:3000
4. open browser devtools, see  `Set` is undefined 

## Expected behavior
As described on the docs, nextjs supports ie10+, there should be `Set` bundled in the files

## System information
 - OS:  macOS
 - Browser:  ie10
 - Version of Next.js: latest

## Additional context

btw, windows is in parallels desktop virtual machine on my mac

![image](https://user-images.githubusercontent.com/12859005/44199881-dd40ed00-a177-11e8-9f3c-2c3dddf6fa6b.png)

**Comment by Fallion** [comment]
Does this happen without react-intl?

**Comment by YUFENGWANG** [comment]
@Fallion  you can try every nextjs example in the examples folder in ie10, maybe they all have this issue

**Comment by timneutkens** [comment]
I'm pretty sure Next.js transpiles Set etc, just not for node_modules, so that must be the issue.

**Comment by YUFENGWANG** [comment]
@timneutkens  For testing, I randomly choose an example in the examples folder named `with-redux`, clone it and run, then open ie, set the dev tools with ie10 mode, and I got the below errors
![image](https://user-images.githubusercontent.com/12859005/44308419-21d2bf80-a3e8-11e8-8868-a31ab7a4e7aa.png) .
that says: `Set` is undefined, `assign` not exists in  `Object`
to reproduce, just run the `with-redux` example and open your ie browser
that just not mean you have to try every official example, just randomly choose one and you will find the issue. for now, `with-react-intl` and `with-redux` have this issue that I've found.

**Comment by radeno** [comment]
React 16 does't support IE 10 anymore. https://reactjs.org/docs/javascript-environment-requirements.html
This is not NextJS issue. If you wanna support IE 10, load polyfill.
From core-js (like in example from link), which increases bundle or from polyfill.io.

**Comment by timneutkens** [comment]
@radeno great catch, I forgot about that one 🕵️
