### ISSUE TITLE
HMR fails causing a full reload of the current page

### ISSUE THREAD

**Issue by sampeka** [zeit/next.js#4968]
# Bug report

## Describe the bug

We've recently upgraded from `5.0.0` to `6.1.0` and now navigation between pages seems to be broken due to a HMR related issue. What happens is:

1. We navigate to a new page using a `Link` component 
2. The page is built
3. The url changes to the target
4. We see a HMR related warning in the console  (see below)
5. The page reloads
6. The original url is restored (it redirects back)

To clarify as well, the components are correctly mapped to.

```
VM12030 main.js:42500 [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See https://webpack.js.org/concepts/hot-module-replacement/ for more details.

VM12030 main.js:42508 [HMR]  - undefined
(anonymous) @ VM12030 main.js:42508
logUpdates @ VM12030 main.js:42507
applyCallback @ VM12030 main.js:42468
(anonymous) @ VM12030 main.js:42476
Promise.then (async)
cb @ VM12030 main.js:42475
(anonymous) @ VM12030 main.js:42487
Promise.then (async)
check @ VM12030 main.js:42486
module.exports.webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ VM12030 main.js:42447
processMessage @ VM12030 main.js:42384
handleMessage @ VM12030 main.js:42267
handleMessage @ VM12030 main.js:42230
```

It sounds like the same issue as the one here: https://github.com/zeit/next.js/issues/4643

Unfortunately the module in the warning above is not specified, it's just undefined and happens intermittently. After one failure, we can retry clicking the link and it tends to work. Navigating to pages directly via urls also works as expected.

## To Reproduce

Will try and create an example repo, but this could be tricky given that HMR is just kind of magically handled in the background at the moment. So any guidance would be much appreciated!

**Comment by timneutkens** [comment]
It's probably fixed in latest canary with webpack 4

**Comment by sampeka** [comment]
@timneutkens thanks, will test and get back to you asap

**Comment by sampeka** [comment]
That sorted it, thanks a lot @timneutkens

**Comment by timneutkens** [comment]
👌 I thought so 😄
