### ISSUE TITLE
Serving app from /subpath

### ISSUE THREAD

**Issue by mitrey** [zeit/next.js#4969]
I'd like to serve my builded app with nginx by path like www.site.com/app
How could I do this? Do we have some config for something like basePath ?

**Comment by timneutkens** [comment]
Zones allows you to do this:
https://github.com/zeit/next.js#multi-zones

Please post questions on https://spectrum.chat/next-js

**Comment by timneutkens** [comment]
This is exactly what zones allows you to do. For example we do this for zeit.co/docs, you can see the code here: github.com/zeit/docs.
