### ISSUE TITLE
Error: Cannot find module on GCF

### ISSUE THREAD

**Issue by iaarab** [zeit/next.js#4975]
# Bug report

## Describe the bug

Running Next.js on google cloud function returns a error

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Deploy to google cloud function
2. Surf to the htttp trigger

## Expected behavior
The index page rendered

## Screenshots
![Image of Yaktocat](https://preview.ibb.co/e7e27e/Screenshot_20.png)

## System information
 - Windows
 - Chrome
 - Next.js v6.1.1

**Comment by timneutkens** [comment]
Maybe windows supports forward slashes for `require` 🤔

**Comment by timneutkens** [comment]
This was solved on canary.
