### ISSUE TITLE
Optionally disable deletion of .next directory

### ISSUE THREAD

**Issue by Martaver** [zeit/next.js#4976]
# Feature request

## Is your feature request related to a problem? Please describe.
Our team uses a `docker-compose` dev setup that mounts `$PWD` to a developer image and links all necessary resources. This allows for hot module reloading in docker containers by changing files from the local host file system. Good practice here is to create docker volumes for things like `node_modules` and `dist` to leave the host system's dependencies and outputs intact.

We are trying to achieve the same with `.next`, however NextJS's insistence on deleting this directory is preventing this setup from working, since you can't `rm` a mounted volume.

## Describe the solution you'd like

An option that prevents NextJS from removing the NextJS directory. If the directory exists, it is re-used and instead, all the content is removed and replaced. Hoping this might be a fairly unobtrusive fix, since as I understand it, removing the `.next` directory itself is an optimization.

## Describe alternatives you've considered

When we try this setup without mounting a separate `.next` docker volume, and letting NextJS write to the host system, NextJS doesn't function correctly, producing state errors when navigating between pages and forcing Webpack to reload completely.

I'm guessing, that this is probably because of potential differences between the host system's file system and docker and read/write semantics. This is what led us to try mounting a `.next` docker volume. For reference, the containers are running `NODE_ENV=production` and `next build && next start`.

## Additional context
The `$PWD` docker compose setup is a really convenient and powerful way to work on a large code base with multiple resources and projects. E.g. if a monorepo contains two NextJS projects, docker-compose can route each to different ports without altering the underlying configuration. This 'delete `.next`' feature seems to be a blocker for effectively developing NextJS with the $PWD method.

**Comment by Janpot** [comment]
@Martaver Maybe you can use the `distDir` option to write the `.next` folder in a subfolder and create a volume for that subfolder instead?

**Comment by timneutkens** [comment]
When providing `distDir` behavior doesn't really change though, but maybe it works.

**Comment by Janpot** [comment]
@timneutkens Yes, but since it will be in a subfolder of the volume instead of being the volume itself, it shouldn't be blocked from being removed.

**Comment by timneutkens** [comment]
Next 7 doesn't remove the `.next` directory.

**Comment by Martaver** [comment]
Do I need to disable it explicitly?

I still get:
```
{ Error: EBUSY: resource busy or locked, rmdir '/stack/packages/www/.next'
errno: -16,
code: 'EBUSY',
syscall: 'rmdir',
path: '/stack/packages/www/.next' }
```

**Comment by achton** [comment]
@Martaver What did you end up doing here? I get this with Next 8 as well.
