### ISSUE TITLE
Way to serve static assets outside of next.js

### ISSUE THREAD

**Issue by rovansteen** [zeit/next.js#4981]
# Feature request

## Is your feature request related to a problem? Please describe.
I am working on a heavy traffic website where we are using external cache (Cloudflare) and internal cache (nginx) to handle peak traffic. Right now we have a problem that during the deployment (on multiple servers) you get a 404 on some assets because you get the new website served and it's requesting a new asset but the load balancer tries to fetch that asset from a server still running the old application. We want to tackle that by warming up the cache and placing the assets of a new website before putting a new version of the website live.

Right now this is not possible because the urls that next.js generate do not correspond with the build output.
For example:
* `/_next/ab63eff6da833959cead077be6b876fd1a29fad4/page/index.js` maps to `.next/bundles/pages/index.js`
* `/_next/webpack/chunks/modules_home_7c50adfce0bf056b9ab503a49320d018-d26bd0ee190393374c1e.js` maps to `.next/chunks/modules_home_7c50adfce0bf056b9ab503a49320d018-d26bd0ee190393374c1e.js`

Prefixing it with the `BUILD_ID` is not a problem but the rest of the path does not match, which makes it a lot more difficult and error prone to set this up right.

## Describe the solution you'd like
It would be nice if there was a direct mapping between the URL and the directory structure. At least for the last part (`pages/index.js` & `/chunks/module_name.js`)

## Describe alternatives you've considered
I have considered modifying the directory structure before serving it with nginx but I'm afraid this is error prone and will be subject to change in future versions of next.js.

## Additional context
There are several other issues about this, like: https://github.com/zeit/next.js/issues/4777 and while you said you are working on a way to make it compatible with CDN & other ways of statically serving the assets it would be nice if there is an issue or PR that can track the progress rather then closing it straight away.

**Comment by timneutkens** [comment]
Did you check latest canary? It's fixed there 😄

**Comment by timneutkens** [comment]
Replied in the spectrum thread too.

**Comment by rovansteen** [comment]
@timneutkens nice! Never saw this PR mentioned anywhere, but great job, thanks!
