### ISSUE TITLE
Incorrect url request to load chunk in production when used with minifier

### ISSUE THREAD

**Issue by imbhargav5** [zeit/next.js#4993]
# Bug report

## Describe the bug

Incorrect url request to load chunk in production when used with minifier

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Build next.js in production mode with a minifier `https://github.com/webpack-contrib/babel-minify-webpack-plugin` or `https://github.com/webpack-contrib/uglifyjs-webpack-plugin`
So the config will look something like this
```javascript

    if (!dev) {
      config.optimization = {
        minimizer: [
          new UglifyJsPlugin({
            uglifyOptions: {
              comments: false,
            },
            sourceMap: true
          })
        ]
      }
    }
```
2. Use one component which is dynamically imported in your home page. Make sure it is rendered to the DOM. 
3. Run the project in production `next start`
4. You will see that the url is to load a lot of the chunks is wrong. This issue only happens with chunks. runtimes load perfectly fine with the right url. Also this error seems to occur **occationally** after a few refreshes in the console. 

Note *Not all chunks have this issue*. As can be seen in the screenshots.

## Expected behavior

The url should instead have `_next/static/chunks/*`

## Screenshots

[![Image from Gyazo](https://i.gyazo.com/6b5143bfa02cb356f4193ecac56ab2fd.png)](https://gyazo.com/6b5143bfa02cb356f4193ecac56ab2fd)

[![Image from Gyazo](https://i.gyazo.com/b529cd88cd1bddf3ba63e43b9ec9e2d8.png)](https://gyazo.com/b529cd88cd1bddf3ba63e43b9ec9e2d8)

[![Image from Gyazo](https://i.gyazo.com/fda2f5f6991b19678b2e11726410826a.png)](https://gyazo.com/fda2f5f6991b19678b2e11726410826a)

## System information
 - MacOS
 - Chrome
 - 7.0.0-canary

## Additional context

This issue does not occur if I don't use a minifier. 

## Github repository

https://github.com/imbhargav5/next-dynamic-bug
I made two branches. `master` and `without-bug`. I deployed them both to now.sh. 

`With bug` https://next-canary-dynamic-bug-efeynywjqu.now.sh/
`Without bug` https://next-canary-dynamic-no-bug-gjkyepzkdj.now.sh/

**Comment by timneutkens** [comment]
This is not really a reproduction. Your steps to reproduce don't mention setting up dynamic imports. Can you provide a minimal github repository.

**Comment by imbhargav5** [comment]
@timneutkens True. I updated the issue.

**Comment by timneutkens** [comment]
I don't see anything different from before 🤔 Can you provide a minimal GitHub repository?

**Comment by timneutkens** [comment]
Hmm weird this morning it wasn't showing up for me 😭Thanks! I'll have a look.

**Comment by imbhargav5** [comment]
Can you direct me how to fix this? I can send a PR.

**Comment by xyyjk** [comment]
@imbhargav5  You can try adding plugins instead of rewriting

```JavaScript
const { minimizer = [] } = config.optimization;

minimizer.push(new UglifyJsPlugin({
  uglifyOptions: {
    comments: false,
  },
  sourceMap: true,
}));
```

**Comment by timneutkens** [comment]
Just tried your reproduction and installing `yarn add next@latest` fixes the issue.
