### ISSUE TITLE
Error in router when navigating "back"

### ISSUE THREAD

**Issue by mfix22** [zeit/next.js#4994]
# Bug report

## Describe the bug
When navigating to a Next.js page, and then clicking the Browser's 'back button', I get:
```
router.js:533 Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at Router.onlyAHashChange (router.js:533)
    at Router._callee2$ (router.js:269)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://carbon.now.sh
2. Click on '/about' at the bottom of the page
3. Click the browser's 'back button'
4. See error in console

## Expected behavior
`/` page to be displayed

## Screenshots
<img width="1280" alt="screenshot 2018-08-20 13 04 38" src="https://user-images.githubusercontent.com/8397708/44363747-eda7df00-a479-11e8-8e5b-071cab30dabe.png">
(as you can see here ^ I have navigated back to the homepage, but the 'about' page is still rendered due to the `undefined` error within the router)

## System information
 - OS: macOS
 - Browser: Chrome
 - Version of Next.js: `v6.1.1`

## Additional information
This might be related to https://github.com/zeit/next.js/issues/2315

**Comment by vaibhavi3t** [comment]
@mfix22 

I'm using next version 6.1.1. I'm am facing same issue.
In which version it is fixed?

**Comment by timneutkens** [comment]
It was not a Next.js issue. See https://github.com/dawnlabs/carbon/pull/485
