### ISSUE TITLE
next.js / apollo-client / typescript

### ISSUE THREAD

**Issue by dfee** [zeit/next.js#4995]
I've decided to try and typescript my (small) application and I've run into a bit of a problem trying to figure out how to typescript this: https://github.com/zeit/next.js/blob/b9533c318d25225a9a66a766d83efde8ac2a176d/examples/with-apollo/lib/init-apollo.js#L8-L11

My solution for getting the `browser` bit typescript'ed was this bit:
```ts
// https://github.com/zeit/next.js/issues/2177#issuecomment-357438567
declare namespace NodeJS {
  interface Process {
    browser: boolean;
  }
}
```

But I can't figure out how to get the `global.fetch` bit to stop complaining:
`[ts] Property 'fetch' does not exist on type 'Global'.`

Any ideas?

**Comment by timneutkens** [comment]
Please follow the issue templates, they're there for a reason. Questions should be posted on https://spectrum.chat/next-js as most of the community is there to answer questions.
