### ISSUE TITLE
Crash on 7.0.0-canary.0, production build

### ISSUE THREAD

**Issue by dmitweb** [zeit/next.js#4997]
# Bug report

## Describe the bug

Production build. Sometimes when reload page, app crashes.
"var r" undefined on 1 screenshot

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Reload page, or go to some page
2. See error

## Expected behavior
Page without errors

## Screenshots
![1](https://user-images.githubusercontent.com/5724174/44387869-5e5d0300-a52f-11e8-810c-cde91747165c.png)
![2](https://user-images.githubusercontent.com/5724174/44387864-5ac97c00-a52f-11e8-85dc-a2dd366c97d1.png)

## System information
 - OS: Linux
 - Version of Next.js: 7.0.0-canary.0

## Additional context

Error does not always occur, sometimes everything works as usual.

**Comment by timneutkens** [comment]
> Reload page, or go to some page

This is not a good reproduction. A good reproduction is a minimal example, with code, preferable a GitHub repository. Based on the steps you're providing there is no way to reproduce the issue you're having.

**Comment by dmitweb** [comment]
@timneutkens yes, sorry for bad reproduction, i will try make example with error as fast as i can
i will attach 2 additional screenshots, in dev
![1](https://user-images.githubusercontent.com/5724174/44442896-7d19d300-a5dd-11e8-8a18-9aba1b0ee7b5.png)
![2](https://user-images.githubusercontent.com/5724174/44442899-8014c380-a5dd-11e8-9a0f-0a4cac60186b.png)

**Comment by timneutkens** [comment]
I can't really do anything with the screenshots. I need a full reproduction.

**Comment by dmitweb** [comment]
When I looked more closely, similar to: #4927. For me really hard reproduce this issue on example "with-next-css". I needed to do a lot of browser page updates. However, perhaps I found useful information.
`
/***/ "dll-reference dll_a77a75e478981c1e0d25":
/*!*******************************************!*\
  !*** external "dll_a77a75e478981c1e0d25" ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports) {

console.log(dll_a77a75e478981c1e0d25);

module.exports = dll_a77a75e478981c1e0d25;

/***/ })

},[[1,"static/runtime/webpack.js","styles"]]])
  console.log(comp); return { page: comp.default }
})
        ;
`
As u can see i add 2 console.log.
"comp" object here is always exists, error is not here.
But, dll not always exists. When I catch an error, "dll_a77a75e478981c1e0d25" is always undefined.
Also i add 2 screenshots, with error, and without.
On 1 screenshot we don't have error and console.log show us 2 Module.
On 2 screenshot we have error and console.log show us 1 undefined, and 1 Module.
@timneutkens Pay attention to the order of page loading.
With error we have _app, then page.
Without error we have page, then _app.

**Comment by dmitweb** [comment]
When i disabled AutoDllPlugin:
`Error was not caught TypeError: Cannot read property 'default' of undefined
    at _app.tsx:218`

_app.tsx:218
`
export default MyApp;
`

Error throwed in _app, don't know why, but seems sometimes export default _app is undefined.

**Comment by timneutkens** [comment]
Once again, I need a full reproduction. I'm sorry but I really can't help otherwise as it's impossible to debug comments.

**Comment by kachkaev** [comment]
@dmitweb are you using `next-css` plugin? If so, you might be facing https://github.com/zeit/next-plugins/issues/244

**Comment by dmitweb** [comment]
@kachkaev yes, u are right. I checked prod build and found chunk with content:
`(window.webpackJsonp=window.webpackJsonp||[]).push([[22],{772:function(n,o,c){},774:function(n,o,c){},776:function(n,o,c){},778:function(n,o,c){},780:function(n,o,c){}}]);`
Thanks @kachkaev. I make repo @timneutkens with issue reproduction: https://github.com/dmitweb/next-css-crash-app
P.S. Maybe u need reload page 1-10 times

**Comment by timneutkens** [comment]
PR open to fix this: #5115
