### ISSUE TITLE
readme.md bugfix

### ISSUE THREAD

**Issue by raoenhui** [zeit/next.js#5007]
# Bug report

## Describe the bug

Here has a issue in readme.md:
If your application has dynamic routes you can add a dynamic exportPathMap in next.config.js. This function is asynchronous and gets the default " exportPathMap" as a parameter.

I think "exportPathMap " should change to defaultPathMap.

**Comment by HaNdTriX** [comment]
Thank you for taking the time to report an issue! 🙏
In this case the documentation is correct. `exportPathMap` is a function that gets as a first parameter a `defaultPathMap`.
