### ISSUE TITLE
Invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by bgold0** [zeit/next.js#5010]
# Bug report

## Describe the bug
This happens for no rhyme or reason, randomly, when I travel to different pages within my application. I haven't figured out a way to replicate this as it shows up extremely randomly. (1 in 15 requests or could be 1 in 50).

This could be because of [my custom _app.js](https://github.com/bgold0/nextjs-auth-skeleton/blob/master/pages/_app.js) but I can't be sure. I haven't seen this happen in `6.1.1` but when I upgraded to `7.0.0-canary.0` it started popping up.

I'd be happy to throw some sort of logging in if it would help pinpoint the problem but I don't know where to start with this and some guidance would be appreciated.

![](https://i.imgur.com/HknUgVd.png)

## System information
 - OS: macOS
 - Browser (if applies): chromoe/safari
 - Version of Next.js: 7.0.0-canary.0

**Comment by timneutkens** [comment]
I believe it might be related to https://github.com/zeit/next.js/commit/a9a3fc1fcad0d05e508caa1e38fd6e3e33cbb238

**Comment by timneutkens** [comment]
This will be out on canary soon. When it is we'll know for sure.

**Comment by bgold0** [comment]
@timneutkens okay, great. will keep a look out and let you know if I still see it on the new release. as always, thank you for such a timely response.

**Comment by alexfromapex** [comment]
I stumbled on this today, so I'll add some details.  This is a result of Babel 7, as you can see from your stack trace.  Here's the input, I gave Babel:

input: 

```
let [x,y] = [1,2];
let z = [...x,...y];
```

and it outputs:

```
"use strict";

function _toConsumableArray(arr) { return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _nonIterableSpread(); }

function _nonIterableSpread() { throw new TypeError("Invalid attempt to spread non-iterable instance"); }

function _iterableToArray(iter) { if (Symbol.iterator in Object(iter) || Object.prototype.toString.call(iter) === "[object Arguments]") return Array.from(iter); }

function _arrayWithoutHoles(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = new Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } }

var x = 1,
    y = 2;

var z = _toConsumableArray(x).concat(_toConsumableArray(y));
```

where the relevant code is the thrown exception that looks like it's a fallback if `_arrayWithoutHoles()` and `_iterableToArray()` both fail.

**Comment by timneutkens** [comment]
The original issue was fixed and is out on Next 7.

**Comment by gondar00** [comment]
@timneutkens  can you please explain what was the fix.

I saw this re-appear on version `7.0.2` but its random and in no order

**Comment by onggunhao** [comment]
@gondar00 - I'm experiencing the same on 7.0.2

I read through the related link https://github.com/zeit/next.js/commit/a9a3fc1fcad0d05e508caa1e38fd6e3e33cbb238 - not sure how it applies though!
