### ISSUE TITLE
Setup API

### ISSUE THREAD

**Issue by cr05s19xx** [zeit/next.js#5011]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

Is it possible to implement a NextJS application which will also have an ApI.
Basically all routes stay, but the `/api` route becomes an API

**Comment by HaNdTriX** [comment]
yes! (e.g.: https://github.com/zeit/next.js/tree/canary/examples/custom-server-express)

Questions should be posted on https://spectrum.chat/next-js 😉
