### ISSUE TITLE
Unexpected Character ' ' when building

### ISSUE THREAD

**Issue by JTRiddick** [zeit/next.js#5012]
# Bug report

## Describe the bug

Rebuilding the module from the tutorial throws an error. Every character in index has a space before and after.

## To Reproduce

Get to the last step in the getting started section of the tutorial

## Screenshots

![nextjserror](https://user-images.githubusercontent.com/13581651/44493685-8da66980-a62e-11e8-9341-222878e95f45.png)

## System information
Windows 10 / Powershell

**Comment by HaNdTriX** [comment]
Looks like you have an `Unexpected character` in your code. Probably this is an invisible character. 
You might want to delete it.
