### ISSUE TITLE
Can you create multiple _app.js files in  with-redux-wrapper  examples, with a separate store for each page

### ISSUE THREAD

**Issue by newyoung21** [zeit/next.js#5015]
## Can you create multiple _app.js files in  with-redux-wrapper  examples, with a separate store for each page

**Comment by timneutkens** [comment]
You can't create multiple _app.js files.

Questions should be posted on https://spectrum.chat/next-js.

You could have multiple stores. But the example is not tailored to that currently as it's an edge case when using Redux.
