### ISSUE TITLE
getting babel related issue when I run test. I am trying out with-jest example

### ISSUE THREAD

**Issue by pnaika** [zeit/next.js#5025]
I am trying to setup unit testing framework in my project but I get below error when I run the test. I am using with-jest example

**error**

> FAIL components/GraphComponent/GraphComponent.spec.js
> ● Test suite failed to run
> 
> Plugin 0 specified in "/Users/prashanthnaika/Documents/Projects/tweettraders-ui/node_modules/next/babel.js" provided an invalid property of "default" (While processing preset: "/Users/prashanthnaika/Documents/Projects/tweettraders-ui/node_modules/next/babel.js")
> 
>   at Plugin.init (node_modules/jest-config/node_modules/babel-core/lib/transformation/plugin.js:131:13)
>       at Array.map (<anonymous>)
>       at Array.map (<anonymous>)

**babelrc**
```
{
  "presets": [
    "env",
    "next/babel",
    "stage-2",
    "es2015"],
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./"]
      }
    ]
  ],
  "env": {
    "development": {
      "presets": ["next/babel"]
    },
    "production": {
      "presets": ["next/babel"]
    },
    "test": {
      "presets": [["next/babel", { "preset-env": { "modules": "commonjs" } }]]
    }
  }
}
```
**dependencies** (from package.json)

```
"@material-ui/core": "^1.5.1",
    "@zeit/next-css": "^0.2.0",
    "@zeit/next-sass": "^0.2.0",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "enzyme": "^3.4.4",
    "enzyme-adapter-react-16": "^1.2.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "22.4.3",
    "babel-plugin-module-resolver": "^3.1.1",
    "jest": "^23.5.0",
    "react-test-renderer": "^16.4.2",
    "react-addons-test-utils": "^15.6.2",
    "file-loader": "^2.0.0",
    "isomorphic-unfetch": "^2.1.1",
    "next": "^6.1.1",
    "node-sass": "^4.9.3",
    "postcss-css-variables": "^0.9.0",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^0.5.1",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-devtools-extension": "^2.13.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "semantic-ui-css": "^2.3.3",
    "semantic-ui-react": "^0.82.3",
    "url-loader": "^1.1.1"
```

**Comment by timneutkens** [comment]
```
"presets": [
    "env",
    "next/babel",
    "stage-2",
    "es2015"]
```

It's probably caused by this. You should *never* add preset-env yourself, as it will disable webpack tree shaking. `stage-2` is deprecated and removed in latest babel. So is es2015, and es2015 is not needed when using preset-env, which is part of `next/babel`. So all you really need is `next/babel`.

**Comment by pnaika** [comment]
Thanks for your reply @timneutkens, really appreciate it. I tried with next/babel alone, but no luck. still getting same error
