### ISSUE TITLE
About Link：How could I get Link's href value at server route

### ISSUE THREAD

**Issue by Rukeith** [zeit/next.js#5030]
# Question about Next.js

I have a Link DOM such as `<Link href="/blog/0", as="/blog/ss" />`
My server router is like this.

    router.get('/blog/:articleId', async (ctx) => {
      await app.render(ctx.req, ctx.res, '/articles', { articleId: ctx.params.articleId });
      ctx.respond = false;
    });

How could I get the Link's href value? The `ctx.params.articleId` which I get is `ss`.

**Comment by timneutkens** [comment]
As you could read in the issue template, questions should be posted on https://spectrum.chat/next-js.

Nonetheless here's an explanation: 
https://github.com/zeit/next.js/issues/2833#issuecomment-414919347

In your case `href` should be `/articles?articleId=0`
