### ISSUE TITLE
failed to deploy custom-server-express to Azure Web App

### ISSUE THREAD

**Issue by 13127755587** [zeit/next.js#5043]
# Bug report

## Describe the bug

when deploying the project to Azure, in the CMD of Kudu, run "npm start" can see the success message "Ready on http://localhost:3000"
However the website still shows 500.
I already run "npm run build" and generated the .next folder, but how can I set the web.config so that the IIS can find the access for the project??
https://jery-nextjs.azurewebsites.net/

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Download and build "custom-server-express" locally
2. Use FTP to deploy the code to Azure or directly drag the files to Azure Kudu
3. Add web.config file and set the entrance to "server.js"
4. See error 500

## Expected behavior
the website should be running OK like local environment
![image](https://user-images.githubusercontent.com/25541463/44729248-f8fda900-ab10-11e8-80b5-4db2a38f9df4.png)

## Screenshots

**error page**

![image](https://user-images.githubusercontent.com/25541463/44728921-2dbd3080-ab10-11e8-8309-3ebaa7a38e91.png)

**file directory**

![image](https://user-images.githubusercontent.com/25541463/44728947-3e6da680-ab10-11e8-8b04-ff8441f85736.png)

**web.config**

![image](https://user-images.githubusercontent.com/25541463/44728956-462d4b00-ab10-11e8-8600-65e380cf3996.png)

so where is the entrance for the next JS in IIS? in the .next folder? 

## System information
 - OS: Windows
 - Browser (if applies) chrome
 - Version of Next.js: latest

**Comment by timneutkens** [comment]
I'm not sure what to do with this.

**Comment by timneutkens** [comment]
Feel free to contribute an example back when you figure this out.

**Comment by 13127755587** [comment]
@timneutkens thanks for the reply, may I know how does the "**.next**"work?

**Comment by 13127755587** [comment]
@timneutkens thanks! but when run "next build" and "next start", will the server.js read the client code from the ".next" folder?

**Comment by timneutkens** [comment]
`next start` doesn't use your custom server. `NODE_ENV=production node server.js` will. `.next` holds the build output that is needed to boot up the production application.

**Comment by 13127755587** [comment]
@timneutkens still doesn't work, seems no good solution yet.....I'll have to implement these features for React myself...

**Comment by timneutkens** [comment]
If it doesn't work with Next.js I doubt it'd be any different when you implement your own custom server.

**Comment by 13127755587** [comment]
@timneutkens  it works perfectly in local, also works good in Linux, but failed with Azure PaaS

**Comment by chcepe** [comment]
Were you able to deploy next with custom server on Azure App Service?
