### ISSUE TITLE
Build Failure when Running "next build" and unable to fetch instantly

### ISSUE THREAD

**Issue by JeisonPham** [zeit/next.js#5044]
# Question about Next.js
Why am I getting a build error when I run it on my digitalocean droplet? I suspect it has something to do with the default settings because when I run "next build" and "next start" on vs code, I get 
`> Ready on http://localhost:3000`
when I am hosting it on :8080 in the server.js and nginx.

I am also getting an error when I run "sudo npm run dev"

> Failed to fetch
TypeError: Failed to fetch

I am using express and react to communicate with each other to get data from blog post,
but the data takes a while to load and the page needs to be refreshed. Is it because of my sync calls?

[this is my repo incase anyone wants to look at my code
](https://github.com/JeisonPham/CommunityCodingBlog)
Questions should be posted on https://spectrum.chat/next-js

**Comment by timneutkens** [comment]
Please follow the issue template.

`next build` doesn't fetch anything, it just runs a webpack build.

It seems like you're using the wrong `"start"` command:

https://github.com/JeisonPham/CommunityCodingBlog/blob/master/package.json#L21

It should be `NODE_ENV=production node server.js`
