### ISSUE TITLE
next.js/examples/with-custom-reverse-proxy  has installed, `npm run dev` then report errors

### ISSUE THREAD

**Issue by suanmei** [zeit/next.js#5052]
# Bug report

## Describe the bug

`with-custom-reverse-proxy` can't work as the folder title describes

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. cd `with-custom-reverse-proxy`
2. run `npm i`
3. run `npm run dev`
4. See error `Plugin 0 specified in "/Users/shiyi/myfile/next.js/examples/with-custom-reverse-proxy/node_modules/next/babel.js" provided an invalid property of "default" (While processing preset: "/Users/shiyi/myfile/next.js/examples/with-custom-reverse-proxy/node_modules/next/babel.js")`

## Expected behavior
custom-reverse-proxy can work as promised.

## System information
 - macOS
 - Version of Next.js: 6.1.1

**Comment by mohit2872** [comment]
Can you assign me this issue?

**Comment by timneutkens** [comment]
There is no way to assign issues on GitHub outside of the organization/collaborators. Posting a comment here is enough for other people seeing you're on it 🙏

**Comment by mohit2872** [comment]
Kindly bear with me. I am new to this. Can you tell me the procedure in case I want to work on this?
