### ISSUE TITLE
Server rendering on child processes

### ISSUE THREAD

**Issue by devcorpio** [zeit/next.js#5056]
Hi :),

My workmates and me have a concurrency problem with the server side rendering.

Reading another issues... for example:

https://github.com/zeit/next.js/issues/1004

@epiqueras says that is possible to improve the time of server side rendering using child processes.

Someone could help us?

We use nextjs 6.1 using custom server with express.

In one of our middlewares we execute:

const handler = routes.getRequestHandler(app)

handler(req, res, next)

**Comment by timneutkens** [comment]
Please follow the issue template.
