### ISSUE TITLE
[Bug next 7] React bundled in development mode

### ISSUE THREAD

**Issue by SBoudrias** [zeit/next.js#5057]
# Bug report

## Describe the bug

Since moving [react and react-dom to AutoDLLPlugin](https://github.com/zeit/next.js/pull/4951), there's no more [React user timings](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab) showing up in the devtool performance panel.

This seems to be be lost because react is then always bundled in production mode. I've check that the `process.env.NODE_ENV = development` during the build process and runtime; but somehow it must be overriden when the AutoDLL initial build occur.

## To Reproduce

1. Profile a Next.js app with the chrome devtool performance panel
2. After stopping the profiling, there won't be any user timings showing up.

## Expected behavior

React should be bundled in development mode so we get access to the deprecation warnings and performance tracking tools.

## System information
 - Version of Next.js: 7-canary.1

**Comment by timneutkens** [comment]
I noticed this yesterday and fixed it already, but was working on another bugfix so couldn't PR it yet. Just opened the PR 👍
