### ISSUE TITLE
react-loadable change to loadable-components 

### ISSUE THREAD

**Issue by popugune** [zeit/next.js#5065]
react-loadable change to loadable-components 

What do you think about using this library for next/ dynamic

https://github.com/smooth-code/loadable-components

**Comment by timneutkens** [comment]
I don't see a reason for changing. It implements the exact same pattern in a larger package:

https://bundlephobia.com/result?p=react-loadable@5.5.0
https://bundlephobia.com/result?p=loadable-components@2.2.3

Note that react-loadable is even smaller in Next.js because we've forked it.
