### ISSUE TITLE
Keyframe animation no longer working in production

### ISSUE THREAD

**Issue by hsavit1** [zeit/next.js#5073]
# Bug report

## Describe the bug

A keyframe animation that I set up with <style jsx> no longer works in production

## To Reproduce

When you hover a pointer over an Image, I should expect the keyframe animation to fire. Instead, nothing happens

this is the code

```Javascript
const Image = ({ width, src }) => (
	<div>
		<img width={width} src={`/static/${src}`} />
		<style jsx>{`
			img {
				width: 160px;
				height: 230px;
				margin: 10px 15px 0 0;
				box-shadow: 5px 10px 10px -5px grey;
				rgba(#000, .25);
			}

			img:hover {
				animation-name: pulse;
				animation-duration: 1s;
			}

			@keyframes pulse {
				from {
					transform: scale3d(1, 1, 1);
				}
			
				50% {
					transform: scale3d(1.05, 1.05, 1.05);
				}
			
				to {
					transform: scale3d(1, 1, 1);
				}
			}
			
			.pulse {
				animation-name: pulse;
			}

		`}</style>
	</div>
);
```

## System information
 - OS: macOS High Sierra
 - Browser: All
 - Version of Next.js: 6.1.1

## Additional context

I wish I could remember which version of Next.js this used to work in. My guess would be ~5

**Comment by hsavit1** [comment]
Would it make more sense to file this issue under https://github.com/zeit/styled-jsx ?

**Comment by timneutkens** [comment]
Yes, but keyframes are working fine on zeit.co 🤔

**Comment by timneutkens** [comment]
zeit.co is something else than nextjs.org.

**Comment by hsavit1** [comment]
@timneutkens I'm going to close this. I got it to work on chrome (still need to adapt to firefox) with the code

```javascript
const Image = ({ width, src }) => (
	<div>
		<img width={width} src={`/static/${src}`} />
		<style jsx>{`
			img {
				width: 160px;
				height: 230px;
				margin: 10px 15px 0 0;
				box-shadow: 5px 10px 10px -5px grey;
				rgba(#000, .25);
				animation: none;
			}

			img:hover {
				animation: pulse;
				animation-duration: 1s;
			}

			@keyframes pulse {
				0% {
					transform: scale3d(1, 1, 1);
				}
			
				50% {
					transform: scale3d(1.05, 1.05, 1.05);
				}
			
				100% {
					transform: scale3d(1, 1, 1);
				}
			}
			

		`}</style>
	</div>
);
```

**Comment by hsavit1** [comment]
I had to set the initial animation to 'none'
