### ISSUE TITLE
Reducer does not update state after migrating to Next.js

### ISSUE THREAD

**Issue by mikaelmh** [zeit/next.js#5075]
After asynchronous Action get result from the server and do dispatch with responded data, reducer still doesn't update the state.

I console logged the reducer's action data, and the reducer **receives the correct responded data,** but the reducer does not update the state. But if I remove the asynchronous function and not update the data props (i.e. if I remove the async/await, meaning I'm not waiting for the server to respond), the state are updated.

Before moving to Next.js, this was working correctly with traditional non-server side React configuration. 

We are using `next-redux-wrapper` and `immutability-helper`

**Action**
```
export const data = ({builtQuery, ref, elasticURL, credentials}) => async dispatch => {
    const data = await queryElastic({
        query: builtQuery,
        elasticURL,
        credentials,
    });

    return dispatch(setElasticData({ref, data}));
}
```

```export const setElasticData = ({ref, data}) => ({type: SET_NAMED_QUERIES, ref, data});```

**Reducer**
```
import update from 'immutability-helper';
import {

    SET_NAMED_QUERIES, 

} from '../types/appTypes';

const initialState = {
namedQueries: {}
    },
};
export const opncityapiReducer = (state = initialState, action) => {
    switch (action.type) {
        case SET_NAMED_QUERIES:
            return update(
                state,
                {
                    namedQueries: {[action.ref]: {$set: action.data}},
                }
            );
       default:
            return state;
    }
};
```

**Comment by timneutkens** [comment]
Please follow the issue template. Questions should be posted on https://spectrum.chat/next-js.
