### ISSUE TITLE
Upgrading to v7.0.0.-* Throws "_JSXStyle" has already been declared error

### ISSUE THREAD

**Issue by ssylvia** [zeit/next.js#5080]
# Bug report

## Describe the bug
```
./pages/demo/card.tsx 3:7
Module parse failed: Identifier '_JSXStyle' has already been declared (3:7)
You may need an appropriate loader to handle this file type.
| var _jsxFileName = "/Users/user/path/packages/storymaps-app/pages/demo/card.tsx";
| import _JSXStyle from "styled-jsx/style";
> import _JSXStyle from "styled-jsx/style";
| import React from 'react';
| import { Card, CardBody, CardTitle, CardSubtitle, CardText } from 'storymaps-components/build';
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone this repo: https://github.com/ssylvia/styled-jsx-multi-declare
2. It's a monorepo, `yarn install` from root.
3. `cd packages/app`
4. `yarn dev`
5. Open browser at `localhost:3000`

## System information
 - OS: macOS 
 - Version of Next.js: 7.0.0-10

**Comment by timneutkens** [comment]
Sounds like a github.com/zeit/styled-jsx issue. Please follow the issue template and provide a reproduction.

**Comment by timneutkens** [comment]
Looks like you're adding styled-jsx on top of next/babel, next/babel has styled-jsx included and allows you to configure it as outlined here: https://github.com/zeit/next.js#customizing-babel-config

So the reason it's adding the import twice is that you have styled-jsx/babel effectively being ran 2 times.
