### ISSUE TITLE
most bundles do not have whitespace removed

### ISSUE THREAD

**Issue by brad-decker** [zeit/next.js#5082]
# Bug report

## Describe the bug

Most bundles in production mode do not have whitespace removed. From what I can tell in researching past issues and documentation whitespace is one of the primary benefits of minification and was the only option on by default in next. I am currently using canary, but this behavior is the same on 6.1.1
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. run `NODE_ENV=production next build`
2. run your app in production mode
3. visit index route
4. check network requests tab in chrome inspector
5. check request for _app.js, index.js, other-page.js, etc
6. See that the code isn't condensed to a single (or at least few) lines

## Expected behavior
Code should be reduced to take up as little white space/indentation as possible to get cost savings in terms of bundle size. 

## Screenshots
![image](https://user-images.githubusercontent.com/4448075/44991853-1a202880-af5b-11e8-882b-d304a35716ff.png)

![image](https://user-images.githubusercontent.com/4448075/44991877-302de900-af5b-11e8-913d-88a6c5b63a03.png)

## System information
 - OS: Linux
 - Browser: chrome
 - Version: 6.1.1, 7 canary 9

should I be setting up uglifyjs in userland and doing settings there or is this an actual bug? What is the best approach for production use cases with bundle size?

**Comment by timneutkens** [comment]
<img width="139" alt="screen shot 2018-09-03 at 16 33 33" src="https://user-images.githubusercontent.com/6324199/44992295-2033fa80-af97-11e8-8777-e033f14dc2a2.png">

I'm guessing you have chrome's pretty-print enabled.

If you check the source of https://create-next-example-app-ucaaapttgi.zeit.sh/ you'll see that everything is minified just fine.

**Comment by brad-decker** [comment]
@timneutkens i feel like a dummy on this one. Sorry for the issue report, confirmed i was looking at the preview tab and not the response tab.

**Comment by timneutkens** [comment]
No worries 🙏
