### ISSUE TITLE
All pages are rendered take long pending time at the first time! 

### ISSUE THREAD

**Issue by luffyZh** [zeit/next.js#5086]
All pages are rendered take long pending time at the first time! It will work better the second time!
A new learner for Next.js, Is there a sulution for this question?  
the first load index.js will take > 10s.
![default](https://user-images.githubusercontent.com/17840558/45012281-005d0f00-b049-11e8-8435-95df931e9e95.png)
the first load other page will take > 5s.
![default](https://user-images.githubusercontent.com/17840558/45012302-11a61b80-b049-11e8-9da1-9ad957c488cf.png)
```
"dependencies": {
    "@zeit/next-less": "^0.3.0",
    "antd": "^3.8.4",
    "babel-plugin-import": "^1.8.0",
    "express": "^4.16.3",
    "less": "^3.8.1",
    "next": "^6.1.1",
    "react": "^16.4.2",
    "react-dom": "^16.4.2"
  },
```
 [The repository url](https://github.com/luffyZh/next-antd-scafflod/tree/custom-server): https://github.com/luffyZh/next-antd-scafflod/tree/custom-server.

**Comment by luffyZh** [comment]
It's slow only in the development environment and it's become fast in the production environment! Maybe the issue can be closed! sorry~

**Comment by timneutkens** [comment]
This is possibly caused by antd + less.
