### ISSUE TITLE
chunk styles [mini-css-extract-plugin] conflicts

### ISSUE THREAD

**Issue by popugune** [zeit/next.js#5098]
![image](https://user-images.githubusercontent.com/19804652/45082402-eaf7eb80-b101-11e8-9a6f-9eb60868fb05.png)
What i should do to fix it in nextjs v7 ?

**Comment by popugune** [comment]
i update dependecies in zeit/next-css(sass) plugins and now i have 
![image](https://user-images.githubusercontent.com/19804652/45084767-c30b8680-b107-11e8-83a5-434be6293c39.png)

**Comment by popugune** [comment]
im add
```
 "node-sass": "^4.9.3",
    "css-loader": "^1.0.0",
    "sass-loader": "^7.1.0",
    "postcss-loader": "^3.0.0",
    "extracted-loader": "^1.0.7"
```
in package.json and scss build

**Comment by timneutkens** [comment]
Please follow the issue template when creating issues and provide a **reproducible** example. Otherwise, we'll have to close them every time.

**Comment by jixiaohongdw** [comment]
> ![image](https://user-images.githubusercontent.com/19804652/45082402-eaf7eb80-b101-11e8-9a6f-9eb60868fb05.png)
> What i should do to fix it in nextjs v7 ?

so how to resolve this problem? thu

**Comment by JBongars** [comment]
> > ![image](https://user-images.githubusercontent.com/19804652/45082402-eaf7eb80-b101-11e8-9a6f-9eb60868fb05.png)
> > What i should do to fix it in nextjs v7 ?
> 
> so how to resolve this problem? thu

Facing the same problem too.

**Comment by Javier1177** [comment]
> > > ![image](https://user-images.githubusercontent.com/19804652/45082402-eaf7eb80-b101-11e8-9a6f-9eb60868fb05.png)
> > > What i should do to fix it in nextjs v7 ?
> > 
> > 
> > so how to resolve this problem? thu
> 
> Facing the same problem too.

Me too...
