### ISSUE TITLE
What is the best and non-buggy configuration ?

### ISSUE THREAD

**Issue by mtrabelsi** [zeit/next.js#5103]
I used next with next-sass and next-css, then i needed to make custom document included some remote CSS.
then it seems that the page Routing is not properly working : the css is not there when you change the route - then you have to make full reload.

Someone from the community, that is fixed in Canary, so i upgraded everything next-canary, next-css@canary and next-sass@canary:
then i got a bug in chrome (Unhandled Rejection (TypeError): Cannot read property 'call' of undefined) when i change Route in the frontend ( navigate through Router.push )

Every path i go with seems to be buggy, I'm confused.

UPDATE
------------
I wanted also to highlight that I wanted to have this SCSS style : 
`import '../static/assets/scss/listPage.scss';
`
I needed this to re-use my SCSS to migrate to next.js app

**Comment by timneutkens** [comment]
Please follow the issue template when creating an issue. It's there to make sure we can help you correctly / reproduce the issue you're having.
