### ISSUE TITLE
exportPathMap + useFileSystemPublicRoutes: false doesn't work

### ISSUE THREAD

**Issue by walston** [zeit/next.js#5126]
# Bug report

## Describe the bug
attempting to use both `exportPathMap` and `useFileSystemPublicRoutes: false` in `next.config.js` doesn't work

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. `$ create-next-app example`
2. edit `next.config.js` w/ `useFileSystemPublicRoutes: false` & `exportPathMap: () => ({ "/": page: "/index" })`
3. run `npm run build` or `npm run dev`
4. all routes are `404`

## Expected behavior
- `useFileSystemPublicRoutes: false` should disable the default routes, not all routes
- using `exportPathMap` should not use the filesystem paths anyway (unless you `Object.assign` to passed in default pathMap)

## System information
 - OS: macOS
 - Version of Next.js: [e.g. 6.1.2]

**Comment by timneutkens** [comment]
Already fixed this locally, just adding a few tests 🙏

**Comment by timneutkens** [comment]
Created #5131 to address this 👍

**Comment by minzojian** [comment]
looks like this bug is still here
i use version 7.0.2 and 7.0.2-canary.49
