### ISSUE TITLE
Custom server no found service worker in production

### ISSUE THREAD

**Issue by CharlyJazz** [zeit/next.js#5134]
# Bug report

## Describe the bug

I wrote a custom server to serve two files, the service worker and workbox. It works correctly in development, but when I deploy in Heroku the server does not find these files.

When I run node server.js if the service worker in development environment works

``` Javascript
const { createServer } = require('http');
const { parse } = require('url');
const { createReadStream } = require('fs');
const next = require('next');

const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  createServer((req, res) => {
    const parsedUrl = parse(req.url, true);
    const { pathname } = parsedUrl;

    if (pathname === '/service-worker.js') {
      res.setHeader('content-type', 'text/javascript');
      createReadStream('./worker/service-worker.js').pipe(res);
    }
    else if (pathname === '/workbox-sw.js') {
      res.setHeader('content-type', 'text/javascript');
      createReadStream('./worker/workbox-sw.js').pipe(res);
    }
    else {
      handle(req, res, parsedUrl);
    }
  }).listen(3000, err => {
    if (err) throw err;
    console.log('> Ready on http://localhost:3000');
  });
});
```

These are the scripts

``` Javascript
  "scripts": {
    "dev": "node server.js",
    "build": "next build",
    "local-start": "NODE_ENV=production node server.js",
    "start": "next start -p $PORT",
    "heroku-postbuild": "npm run build",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
```

Browser console message: 

"TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script."

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Repository: https://github.com/CharlyJazz/NextPWAFirebase/
2. Check the deploy in: https://ecomerce-challenge.herokuapp.com/

## Expected behavior

The service worker should be on the server like in development enviroment

## System information
 - Ubuntu 16.04
 - Chrome 67.0.3396.99 (Official Build) (64-bit)
 - Version of Next.js: 6.1.1

**Comment by timneutkens** [comment]
I'm not sure how this would be considered a bug in Next.js itself as we don't touch service workers. But I'll add the good first issue / help wanted label if someone wants to have a look.

**Comment by CharlyJazz** [comment]
Thanks @timneutkens

**Comment by timneutkens** [comment]
`"start": "NODE_ENV=production node server.js",`

Note that your custom server has to read `process.env.PORT`, so `3000` should be changed to `process.env.PORT || 3000`.
