### ISSUE TITLE
a question about token from url 

### ISSUE THREAD

**Issue by junjie-lean** [zeit/next.js#5138]
hello, I use the Axiso as the Ajax framework to request data, but in my project，all requests need a token from the url to be signed.this leads me to have to be instantiation axios object  in client, and then ,my page can not render in server, so hot to resolve this case that i must instantiation axios object in client with a token from url?

**Comment by timneutkens** [comment]
Please follow the issue template. Which clearly says questions should be posted on https://spectrum.chat/next-js.
