### ISSUE TITLE
 Cannot set property 'toJSON' of undefined when using react-i18next example

### ISSUE THREAD

**Issue by szczepanbarszczowski** [zeit/next.js#5145]
# Examples bug report

## Example name
with-react-i18next

## Describe the bug
I have problem when running dev server. I've got `Cannot set property 'toJSON' of undefined` on server. It looks like there is no i18n on request in file `i18n.js`. Translation doesn't work. On production build everything works well. I've tried most of solutions on Github regarding react-i18next example and always getting this crappy `undefined` error. Any help will be appreciated.

## To Reproduce
Just clone this repository: https://github.com/szczepanbarszczowski/nextjs-starter

## Expected behavior
It should work without an error.

## Screenshots
<img width="1184" alt="zrzut ekranu 2018-09-12 o 13 51 03" src="https://user-images.githubusercontent.com/25323934/45423207-eb106200-b692-11e8-909f-8dba86bf03c8.png">

## System information
 - OS: Mac OS Mojave
 - Browser (if applies) Chrome 68
 - Version of Next.js: 6.1.2

**Comment by szczepanbarszczowski** [comment]
I've tried @next/cannary but still same error. Any thoughts why it's i18n is undefined on server?

**Comment by danielr18** [comment]
It's because you are not using your custom server on dev, try setting your dev script to `"dev": "node server.js"`.

**Comment by szczepanbarszczowski** [comment]
@danielr18 You're right. Thank a lot man. It works well.
