### ISSUE TITLE
Embeded widget at nextjs

### ISSUE THREAD

**Issue by michalbelas** [zeit/next.js#5148]
Hello guys i just wondering about if it is possibble to use next js to write standalone widget and then embed it to third part site as for example facebook sharing, like button.

Thanks for any advices.

**Comment by timneutkens** [comment]
Please post questions on https://spectrum.chat/next-js, that's where the whole community is at. Next.js is geared towards pre-rendering / dynamic apps, but @fouad did some work in a similar direction, so I'm pinging him here.

**Comment by fouad** [comment]
thanks for pinging @timneutkens! Still need to make a write up about this, but [here's my talk on this](https://www.youtube.com/watch?v=5CzOYDF0Hdk)

**Comment by lubos-gelanyi** [comment]
thanks guys both of them, i craeted message for this quiestion https://spectrum.chat/thread/7ad7d4ca-da31-4d02-9544-69f21684f424

**Comment by michalbelas** [comment]
thanks guys both of them, i craeted message for this quiestion https://spectrum.chat/thread/7ad7d4ca-da31-4d02-9544-69f21684f424
