### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by zpc7** [zeit/next.js#5156]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js
when i use 'createPortal' in component, this error happen. this is my component code:
```import React from "react";
import { createPortal } from "react-dom";
import classnames from "classnames";

export default ({ visible, onSwitch, children }) =>
  createPortal(
    <div
      className={classnames("modal", { "modal-show": visible })}
      onClick={onSwitch}
    >
      {children}
    </div>,
    document.body
  );
```

**Comment by danielr18** [comment]
`document` is only defined on client side. Take a look at [with-portals example](https://github.com/zeit/next.js/tree/85769c3d3296cdcddc0fb36f05058c8e451ca57f/examples/with-portals) to see how you can use them.

**Comment by timneutkens** [comment]
Awesome replies @danielr18 🙏

**Comment by zpc7** [comment]
@danielr18 thanks 🙏
