### ISSUE TITLE
Feedback regarding custom server

### ISSUE THREAD

**Issue by ryancole** [zeit/next.js#516]
First off, I want to say I'm loving the approach that next.js has taken. I think it's a great union of convention and configuration.

I wanted to give my brief feedback regarding the custom server, though.

I think that in most scenarios, a custom server is currently necessary. I think this is mostly due to a lack of convention regarding URL parameters out of the box. If some satisfactory convention can be agreed upon for that, then I think custom server becomes less of a requirement.

The custom server itself sits outside of next's underlying webpack and babel runtime, which means the custom server needs to be written without ES6 modules, and any other features that babel may provide. The custom server also does not benefit from reloading itself, so as you're developing custom routes, etc, you must restart the custom server. This is somewhat jarring because the rest of the application is free to use ES6 modules, reloading, etc. I could see custom server code becoming somewhat large in and of itself, depending on the number of custom route handlers needed, etc. Would be nice if there was no mental switch between babel and no babel.

Would it be possible to add a parameter to the `next` binary that accepts a custom server module? This way, next.js can load up said module, make it part of the webpack and babel build process and sort of make the custom server feel more like a first class concept? The custom server module could be a module that exports a function, and said function could accept the next application as parameter. Something like that?

Just some initial reactions to using next over the past few days.

**Comment by rauchg** [comment]
The idea behind the programmatic API is to be able to do `node x.js`. The goal is to _avoid_ all the pipelines, and to be able to start the next engine programmatically, with the Node runtime alone.

That said, what you're suggesting is something we can certainly consider in the future to enhance the developer experience. For example, `next -s server-file.js`. `server-file` would `export` a request handler. This is one of the first ideas I had for the programmatic API, before realizing that _we had to go deeper_ and enable even a lower-level abstraction as the starting point.

I'm closing this until I or you have a more concrete API idea for this. Maybe we can re-open is as `next --server` / `next -s` and more implementation details in the description.

Thanks for the awesome feedback!
