### ISSUE TITLE
`<Link />` doesn't work with hashes

### ISSUE THREAD

**Issue by trusktr** [zeit/next.js#5161]
This is the same as #2098, except for me it is backwards.

#2098 says

> it will only work when that link is pressed from another page.
> 
> When this link is pressed on the / page, Next will not scroll into that view

But what I experience is that it doesn't work from another page, and only works when on the page.

For example if I have `<Link href="/#who-we-are" />` and I am on `/about`, clicking it takes me to `/#who-we-are` but will not scroll me to the section. Once I am at `/#who-we-are` I can click the link a second time to make it take me to the section.

**Comment by trusktr** [comment]
I was able to fix it with a simple workaround. I've added the following to my code which seems to work, making it scroll to the section on has changes:

```js
    Router.onRouteChangeComplete = () => {
      setTimeout(() => {
        if (location.hash) location = location
      }, 0)
    };
```

**Comment by trusktr** [comment]
Also another problem: when clicking different `<Link />`s that vary only by hash, it is not trigger a route change event.

This is unexpected because it means it will not cause some components to re-render if they are observing route changes.

Any change to the browser history should be handled by Next.js router, so code can listen to it using Next.js Router API.

**Comment by trusktr** [comment]
`window.addEventListener('hashchange', console.log)` doesn't work while using Next.js Router, all the more reason for Next.js to trigger `onRouteChangeComplete` for hash changes.

If I click on a `<Link>` that has a has, there's no `hashchange` even fired. I can only trigger it by doing `location.hash = 'someValue'`, which means I would have to step outside Next.js Router and implement something else.

**Comment by trusktr** [comment]
Looks like the answer is https://github.com/zeit/next.js/issues/1609, "not supported".

So what do we do?

**Comment by trusktr** [comment]
I see https://github.com/zeit/next.js/pull/4676. I see some work _has_ gone into hashes.

What exactly should we expect (at the moment) from Next.js regarding hashes?

**Comment by trusktr** [comment]
For now, I'm doing the following, which works:

```js
import * as React from 'react'
import Router from 'next/router'

class MyComponent extends React.Component {
  constructor(props) {
    super(props)
    this.state = { path: '' }
  }

  render() {
    const {path} = this.state
    return (
              <Link href="/contact">
                <a
                  onClick={this.hashChangeTo('#someHash')}
                  className={classNames({
                    foo: path.includes('#someHash'),
                  })}
                >
                  Go to Somewhere
                </a>
              </Link>
    )
  }

  hashChangeTo = (targetHash: string) => {
      return () => {

          // if we clicked a link that takes us to the same hash, nothing to do.
          if (targetHash === location.hash) return

          const detectHash = () => {
              if (location.hash === targetHash) {
                  // the hash changed to the expected target
                  this.updatePath()
              }
              else {
                  requestAnimationFrame(detectHash)
              }
          }

          requestAnimationFrame(detectHash)
      }
  }


  updatePath() {
    this.setState({ path: Router.pathname + location.hash }); // Router doesn't have a .hash property

    // this small hack causes the page to scroll to a section when the route
    // contains a hash. Otherwise it doesn't work. See:
    // https://github.com/zeit/next.js/issues/5161
    setTimeout(() => {
        if (location.hash) location = location
    }, 0)
  }

}
```

All of this would not be needed if Next could have https://github.com/zeit/next.js/issues/5163.

**Comment by trusktr** [comment]
Other libs (f.e. Vue router) trigger a route change event when the hash changes, making this all simpler.

The following is the exact same in Vue:

```vue
<template>
            <router-link
              to='/#someHash'
              :class="path.includes(#someHash) ? 'foo' : ''"
             >
               Go to Somewhere
             </router-link>
</template>
<script>
    export default Vue.extend( {
        watch: {
            $route() { this.goToHash() },
        },
        data: () => ({ path: '' })
        methods: {
            goToHash() {
                this.path = this.$router.history.current.fullPath
                if ( this.path.includes( '#' ) ) (location = location) // scroll
            },
        },
    } )
</script>
```

Both Vue and Next need the `location = location` trick, though it'd be nice if they didn't. Next needs the more awkward polling for location.hash.

**Comment by trusktr** [comment]
I was also thinking of trying this trick, but I haven't yet: https://stackoverflow.com/questions/4570093/how-to-get-notified-about-changes-of-the-history-via-history-pushstate

It'd be the best for Router to fully encompass hashes.

**Comment by timneutkens** [comment]
Before reading all of this issue I'd like to point out the issue template is pretty clear right 🤔 Please use it when creating issues. It saves us a ***lot*** of time: https://github.com/zeit/next.js/issues/new/choose

**Comment by martpie** [comment]
Just faced this problem. Digging a bit into the Next.js codebase, I noticed it was supposed to be handled by Next.js itself here: https://github.com/zeit/next.js/blob/9547e77820305ac90a60d652f09ab29af53e11d3/packages/next/pages/_app.js#L49.

It can happen that scroll to hash does not work if you have a custom `_app.js`.

The (undocumented) solution now:

```
// app.js

// Container will scroll to hash on update
import App, { Container } from 'next/app'; 


...
class MyApp extends App {
  render() {
    const { Component } = this.props;
    // your you other stuff here

    return (
      <Container>
        <Component />
      </Container>
    );
  }
}

export default MyApp;
```

**Comment by timneutkens** [comment]
@martpie I wonder if we should deprecate/remove Container and move it up the tree outside of userland 🤔

**Comment by martpie** [comment]
I understand the separation of concern, but in the end, without documentation, developers will never understand what happens there.

Would you accept a PR for that?

**Comment by timneutkens** [comment]
@martpie we can make `_app.js` a lot simpler by rewriting a few bits, basically refactoring out all the logic around React context / the Container that implement scrolling, then what's left is "just" a React component. This would also be future-proof since React is moving to nearly fully functional style with Hooks and _app.js currently depends on class inheritance.

**Comment by timneutkens** [comment]
Created this issue wrt React context: https://github.com/zeit/next.js/issues/5716

**Comment by ijjk** [comment]
This appears to be resolved and we have a test for this behavior, so I am going to close this issue. If you are still experiencing this feel free to reply with more info.
