### ISSUE TITLE
How to save state of Redux on LocalStorage?

### ISSUE THREAD

**Issue by MontoyaAndres** [zeit/next.js#5162]
I want to save the state of redux on LocalStorage, I've try the package called redux-localstorage, like this:

```
import { createStore, applyMiddleware, compose } from "redux";
import { composeWithDevTools } from "redux-devtools-extension";
import persistState from "redux-localstorage";
import adapter from "redux-localstorage/lib/adapters/localStorage";
import thunk from "redux-thunk";

import reducers from "./reducers";

export default function initializeStore(initialState = {}) {
	const storage = adapter(window.localStorage);

	const enhancer = compose(
		composeWithDevTools(applyMiddleware(thunk)),
		persistState(storage, "state")
	);

	const store = createStore(reducers, initialState, enhancer);

	return store;
}
```

But I have one error, which is that the window does not exists...

**Comment by timneutkens** [comment]
You need to check if `window` is defined or not, redux is instantiated on the server side too.

**Comment by timneutkens** [comment]
Also, please follow the issue template.

**Comment by Abramovick** [comment]
@MontoyaAndres Did manage to get it to work?

**Comment by MontoyaAndres** [comment]
@Abramovick i haven't applied, just did that for curiosity. You can implement it manually using https://github.com/zeit/next.js/blob/canary/packages/next/README.md#dynamic-import in your componente
