### ISSUE TITLE
Expires header on _next/ resources

### ISSUE THREAD

**Issue by martpie** [zeit/next.js#5166]
# Feature request

## Is your feature request related to a problem? Please describe.

Related to #1791 

Next.js does not set expires header on static resources.

## Describe the solution you'd like

Though a lot of content in the app is served statically, and has an hash in its path, none is served with `Expires` HTTP header.

Because this hash is probably unique per build (cf. `Request URL` of the screenshot below) (tell me if I am wrong here), Expires headers should be set (365days?) on these to help Browsers cache resources that can be cached.

I don't know what is the best strategy for the `static/` folder though.

![screen shot 2018-09-14 at 11 41 16](https://user-images.githubusercontent.com/1311607/45542918-84668200-b813-11e8-8201-2bf3c729d284.png)

Nuxt.js make things quite easy for example:

![screen shot 2018-09-14 at 12 00 55](https://user-images.githubusercontent.com/1311607/45543828-ec1dcc80-b815-11e8-935d-192c905f673a.png)

## Describe alternatives you've considered

When using a custom server, I guess I could add a "if you're looking for something in `/_next`, add those headers", but I think this should be a default in Next.js.

Probably an HTTP server could do it too (nginx, apache, caddy...), but I am pretty sure a lot of persons expose their Node app directly with `npm start`.

## Additional context

_edit:_ I would be fine if this feature was not in Next's default, but if there was a documentation related to best practices in production: what the Next.js team recommend to do for those scenarios.

**Comment by timneutkens** [comment]
The reason for this is that assets are immutable. See the `Cache-Control` header, it sets `immutable` meaning the browser will cache it forever. This is because assets are by default unique (buildId in the url) for production builds. The commons bundles even have a contenthash so they're even more unique.

**Comment by martpie** [comment]
Oh I see, I think I got confused by multiple things there. Thank you! 👌

**Comment by Pavek** [comment]
There is issue with styles that are placed to `_next/` automatically since Next/7:
- JS (**OK**):
```
http://localhost:3000/_next/static/gfc9QoXSPawyLcB0eg9By/pages/index.js
http://localhost:3000/_next/static/gfc9QoXSPawyLcB0eg9By/pages/_app.js
...
Cache-Control: public, max-age=31536000, immutable
```

- CSS (**Bug?**)
```
http://localhost:3000/_next/static/css/commons.66af35b2.chunk.css
http://localhost:3000/_next/static/css/styles.b4564e85.chunk.css
...
Cache-Control: public, max-age=0
```
Having that CSS now has automatic hashes, I believe it it should have the same `Cache-Control` as JS.
