### ISSUE TITLE
NextJS as a kiosk mode (raspberry PI) - Interesting edge case.

### ISSUE THREAD

**Issue by lacymorrow** [zeit/next.js#5167]
# Bug report

I won't lie, I'm using next in a way that is likely not recommended but I don't think it is an unreasonable use case. Basically a static app (`npm run build && npm run export` exports to hackpack-server/out, which is sync'd to the hackpack - raspberry pi-based device.

I'm tasked with setting up a nextJS repo that can be exported via `build + export to SSR build and exported to a completely local pre-built nextJS app which (while mostly offline) pings rest APIs for updating specific pages and components.

The kicker: *This is a hardware device* (think gameboy) with hi res screen and more buttons, (lights too!)

I cannot post the code for another 3 weeks! (after the conference)

## Expected behavior
Clicking a <Link prefetch href="/load"> from a page loaded via a file like file:///Users/lacymorrow/repo/hackpack-server/out/index.html loads the correct page at file:///Users/tmorrow/repo/hackpack-server/out/load/index.html

## Current behavior
Clicking a <Link prefetch href="/load"> from file:///Users/lacymorrow/repo/hackpack-server/out/index.html takes me to file:///load

## System information
 - Browser (if applies) Python-based webview based on https://github.com/r0x0r/pywebview created on Raspberry pi ZeroW 
 - Version of Next.js: 8 LTS

**Comment by GloriousYellow** [comment]
What's the issue you're experiencing?

**Comment by lacymorrow** [comment]
Sorry, after some sleep I've edited the comment to be a bit more clear. I need links that currently look like `<Link prefetch href="/load">` to take me from file:///Users/lacymorrow/repo/hackpack-server/out/index.html loads the correct page at file:///Users/tmorrow/repo/hackpack-server/out/load/index.html instead of file:///load.

I'm starting to think I shouldn't be using absolute links in the `<Link prefetch href="/load">`, can someone with next SSR knowledge chime in?

Thanks for getting back @GloriousYellow! Any idea?

**Comment by lacymorrow** [comment]
Is it a matter of appending a (protocol and) url to the link?
Ex:
`<Link prefetch href="https://localhost:4000/load">`

**Comment by lacymorrow** [comment]
cc @timneutkens <3 you

**Comment by lacymorrow** [comment]
Is a server necessary? Would be question 3

**Comment by lacymorrow** [comment]
This touches on the subject of https://github.com/zeit/next.js/issues/2645, and currently to get resources loaded I'm using a similar technique in the comment in the first line `routing all _next/webpack/static/ requests to /.next/static`

**Comment by timneutkens** [comment]
I guess Next.js currently doesn't support the `file://` scheme for loading files. We never had someone create an issue for it anyway. Would have to investigate this further.

**Comment by lacymorrow** [comment]
It wouldn't be the worst workaround to run a server (Apache2, Lighttpd, NGinx, or even express locally), The CPU load of the server is non-zero, but should still allow us a relatively quick-navigating local app.

Another option would be to only have a single page app, and just create a linking system that will swap out the necessary components but never leave index.html

**Comment by lacymorrow** [comment]
I'm also having issues with loading assets locally via `file://`.

I have to run `sudo sed -i -e 's/\/_next/_next/g' /var/www/html/*` to get everything going. (start with `sudo sed -i -e 's/\/_next/_next/g' /var/www/html/index.html`)

**Comment by revolunet** [comment]
raspi should have the builtin `python -m SimpleHTTPServer` which should do the trick

**Comment by lacymorrow** [comment]
Right you are @revolunet! 

We are looking for ways to avoid running a server as even the simple python server has a noticeable performance hit, but that is the next-best option 👍

**Comment by timneutkens** [comment]
I'm going to close this issue as it's unlikely we'll tackle it in the near future.

**Comment by lacymorrow** [comment]
Thanks @timneutkens, it's really only an issue on IoT devices with limited CPU (like the Pi0)
