### ISSUE TITLE
Error: EACCES: permission denied, open '/tmp/update-check/next-latest.json

### ISSUE THREAD

**Issue by Enalmada** [zeit/next.js#5170]
# Bug report

## Describe the bug

When I "npm start" my example with-zones-app with a custom server, I see a
`Error checking updates { [Error: EACCES: permission denied, open '/tmp/update-check/next-latest.json']
`.  
...and then it goes away to show "DONE Compiled successfully..." a few seconds later.   As a new user, seeing "Error" trying to run examples is a bad user experience.  Now that I see the full error and suspect it is totally benign, I believe I would like to stop this flash of error from happening to new users.  I suspect that next.js is checking for updates every time I try and start it which seems unnecessary.  I think I saw a message on my screen once that there was a new version of next.js available.  
 
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. In Windows for linux, symbolic link a windows directory to a linux one.  (I do this as a workaround because due to path issues I can't build a next.js linux distribution from my windows terminal)  
2. Go to start next.js (on ubuntu under windows linux where who knows what permissions /tmp has for my current user)
3. See error flicker on screen for a moment 

## Expected behavior
I would expect no attempt to check for latest next since that is whan package.json version infrastructure is for.  If you do insist on the check, it would be nice if below the error there would be output of a message describing an easy way to disable the error message from happening again like "Latest check for next.js version can be disabled by putting 'updateCheck:false" in your next.config.js.

## Screenshots
> adam@Adam-PC:~/with-zones-app/blog$ npm start
>  with-zones-blog@1.0.0 start /with-zones-app/blog
>  PORT=5000 node server.js
> 
> Error checking updates { [Error: EACCES: permission denied, open '/tmp/update-check/next-latest.json']
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'open',
>   path: '/tmp/update-check/next-latest.json' }

## System information
 - OS: Windows 10 WSL (windows subsystem for linux) Ubuntu
 - Browser: n/a
 - Version of Next.js: "^6.1.2"

## Additional 
The most serious issue is that checking for new version is probably a blocking call?  If so, this is a performance penalty to the startup time of every next.js dev user in the world that most of them don't know about and don't need to pay.  If the call is async with the starting of the server that is less bad but I suspect it is not.  I believe that version check should be opt in somehow because for normal users, the version "^x.y.z" in package.json is sufficient.

**Comment by timneutkens** [comment]
update-check was removed already on next@canary.
