### ISSUE TITLE
Capitalized routes don't work with page refresh in dev mode (but works in production)

### ISSUE THREAD

**Issue by trusktr** [zeit/next.js#5171]
# Bug report

## Describe the bug

When you make a file like `pages/FooBar.jsx` it creates a route called `/FooBar`.

If you visit `localhost:3000` (starting at the `/` route), then you can successfully navigate to the `/FooBar` route after clicking a `Link`.

However, once you are on that route, if you refresh the browser, you'll get a `404` while in dev mode.

In other words, if you bookmark the `/FooBar` route and try to visit that page directly later, it does not load. You are only able to switch to it dynamically using client-side routing, but you must first be on another route that works (f.e. `/`).

This only happens in dev mode. It works fine in production mode with static `export`ed apps.

I haven't tested in server mode.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Make a CapitalizedRoute.
2. Go to it.
3. Refresh the page.

## Expected behavior

It should serve the initial payload based on that page, but instead it serves 404.

## Screenshots

None at the moment.

## System information
 - Version of Next.js: 6.1.1

---

@timneutkens Do you have a working CodeSandbox or StackBlitz I can fork?

**Comment by JWillZ94** [comment]
I'll look into this issue if no one's on it.

**Comment by JWillZ94** [comment]
That's odd, it works on my end.

**Comment by quietshu** [comment]
This is weird. I cannot reproduce the issue with either next 6.1.1 or 7.0.2. (under examples/hello-world and create pages/FooBar.js)

Could you make a minimal reproduction? 🙏
