### ISSUE TITLE
Tutorial does not work as expected in Getting Started

### ISSUE THREAD

**Issue by baljeet** [zeit/next.js#5175]
We get the following error while following the steps of tutorial:

`ModuleBuildError: Module build failed: Error: Cannot find module 'babel-preset-es2015'`

Was able to fix this creating .babelrc and adding the following:

`{
  "presets": ["next/babel"],
  "plugins": []
}
`

Expectation: There should be no error.

Either tutorial needs updation or there is some bug in next.js core.

**Comment by timneutkens** [comment]
Could you provide which page you're having trouble with?

**Comment by timneutkens** [comment]
Possibly you have a `.babelrc` somewhere above the directory where Next.js is running in.

**Comment by baljeet** [comment]
@timneutkens There is no .babelrc  in the project directory or the parent directory.

I created a new project with `npm init` and followed the tutorial.

I was able to guess the solution using this issue: https://github.com/zeit/next.js/issues/5096

**Comment by timneutkens** [comment]
> I created a new project with npm init and followed the tutorial.

Which tutorial were you following though? preset-es2015 is in not added by Next.js, we use `@babel/preset-env`.

**Comment by baljeet** [comment]
This one:
`https://nextjs.org/learn/`

**Comment by timneutkens** [comment]
The initial tutorial just lets you install `react react-dom next`, so I'm pretty sure you have a .babelrc somewhere up the tree, it can be anywhere, not just the parent directory, but any parent of that directory too.

**Comment by baljeet** [comment]
yeah! Found a .babelrc in parent to parent directory. Thanks.

**Comment by timneutkens** [comment]
💯 Great, exactly what I thought 😄
