### ISSUE TITLE
How do you build dir='./src'？

### ISSUE THREAD

**Issue by VanquisherMe** [zeit/next.js#5177]
Service Settings
`
next({ 
    dev,
    conf,
    dir: './src'
})`

How to start build？This is not to
`next build config/next.config`

**Comment by timneutkens** [comment]
`next build <same as dir>`

So in your case

`next build src`

**Comment by VanquisherMe** [comment]
![75f04659-0843-4523-8b4d-96eb7c5adfcf](https://user-images.githubusercontent.com/4927398/45591803-fca58280-b98e-11e8-9eca-cbab1c521f0d.png)
the next.config in config dir
I try to 
"build": "next build src --config config/next.config"
It doesn't seem right
