### ISSUE TITLE
Questions about less file compiling and build command

### ISSUE THREAD

**Issue by VanquisherMe** [zeit/next.js#5178]
1. I used @zeit/next-less, but the CSSs weren't fully loaded under the development mode.The style of current page doesn't exist in the style.css file when the client jumps to route, but it is then loaded after refreshing the current page.Is this the normal case? And can the CSSs be fully loaded  under the development mode? It seems that CSSs are fully loaded after building.

2. I set cssModules:true and used a third-part library Ant Design, and I found that all the imported third-party css files are compiled by the mode [name]__[local]__[hash:base64:5]. I need to apply  cssModules:true in my program, but not when importing third-party libraries. How can I import third-party libraries(like Ant Design) with cssModules:false while others still in cssModules:true mode?
![bf36a8d7-375d-48df-a0df-c86b1771e41b](https://user-images.githubusercontent.com/4927398/45592957-7cdae080-b9ad-11e8-862b-ef449768ffab.png)

 **#5180 Look at this in detail**

3. How to build when next.config is under config directory and pages is under src directory?  I tried "build": "next build src --config config/next.config" ,but it didn't work.
directory as follows
![75f04659-0843-4523-8b4d-96eb7c5adfcf](https://user-images.githubusercontent.com/4927398/45592964-a3991700-b9ad-11e8-8218-3c740167815f.png)

**Comment by timneutkens** [comment]
> How to build when next.config is under config directory and pages is under src directory? I tried "build": "next build src --config config/next.config" ,but it didn't work.

This is not possible and there are currently no plans to support it.

Regarding the rest, there's already an issue on github.com/zeit/next-plugins about having multiple configs, so I'm going to close this.
