### ISSUE TITLE
Failed to compile with export as

### ISSUE THREAD

**Issue by didierfranc** [zeit/next.js#518]
It seems we cannot compile with that kind of export, I'm using **2.0.0-beta** on a fresh app.

<img width="393" alt="capture d ecran 2016-12-25 a 22 46 33" src="https://cloud.githubusercontent.com/assets/14132464/21473009/f5b9b94e-caf4-11e6-84c9-7aa56656a0d8.png">

**Comment by nkzawa** [comment]
It looks this is still stage-1 then we wouldn't support it as default ?

https://github.com/leebyron/ecmascript-export-ns-from.

Related: https://github.com/zeit/next.js/issues/266

**Comment by arunoda** [comment]
@didierfranc Soon we'll support [`.babelrc` support](https://github.com/zeit/next.js/pull/493).
So, you could add support for this yourself.

**Comment by didierfranc** [comment]
@nkzawa Thanks I though it was included in `es2015-preset` nice shot 👌
