### ISSUE TITLE
Huge performance issue with 7.0.0-canary.6 onwards

### ISSUE THREAD

**Issue by matthewlilley** [zeit/next.js#5185]
# Bug report

## Describe the bug

Huge performance issues with 7.0.0-canary.6 onwards. Offending commit Iis https://github.com/zeit/next.js/commit/e1c544cd758d4410b0cd4c2548dc597bb5bda9f1

## To Reproduce
Install Next  7.0.0-canary.6 or above, and force some state updates, or anything that's going to use some resource to make the problem more obvious. (I used https://www.npmjs.com/package/react-countdown-now, and forced some state updates while that was running.)

## Expected behavior
Performance that's comparable to 7.0.0-canary.5 and earlier, the difference is huge.

## System information
 - OS: Windows
 - Browser: ALL
 - Version of Next.js:  7.0.0-canary.6 onwards

## Additional context

This problem was introduced by 7.0.0-canary.6, previous versions work perfectly.

**Comment by timneutkens** [comment]
"Performance issues" is extremely broad. Please provide a clear and concise reproduction and explain exactly what you mean.

**Comment by matthewlilley** [comment]
https://github.com/zeit/next.js/commit/e1c544cd758d4410b0cd4c2548dc597bb5bda9f1

That's the problem.
