### ISSUE TITLE
Electron integration example: show blank screen when using dist

### ISSUE THREAD

**Issue by KASOGIT** [zeit/next.js#5188]
# Bug report

## Describe the bug

On ubuntu 18.04.
Url example project: https://github.com/zeit/next.js/tree/canary/examples/with-electron
When using dist after building production within electron integration example project show blank screen after input text.

## To Reproduce

1. npm run dist
2. cd dist/linux-unpacked && ./electron-next-skeleton
3. input something and press enter

And voilà ! Blank screen appeared

## Expected behavior

I just want the same behavior than the development version.

## System information
 - OS: ubuntu 18.04
 - Version of Next.js: latest
 - Version of Electron: 2.0

**Comment by timneutkens** [comment]
I'm not sure how this relates to Next.js. Are you using an example? Please always write down exactly the environment you're using so that we can help you faster.

**Comment by KASOGIT** [comment]
Ofc, i'm talking about the example project tha you can find there: https://github.com/zeit/next.js/tree/canary/examples/with-electron

**Comment by KASOGIT** [comment]
No one could fix it or help me to fix it ? :/

**Comment by Phiiii** [comment]
I don't know much about Next.js, but if you are using React Router, it might be that you're using `BrowserRouter` which will break the build. Using `HashRouter` will fix this issue if that's the case.

**Comment by timneutkens** [comment]
I'm going to close this issue as it's stale.
