### ISSUE TITLE
Focus lost after every key stroke on input elements imported via next/dynamic

### ISSUE THREAD

**Issue by fi5u** [zeit/next.js#5191]
# Bug report

## Describe the bug

When typing in an input field in a component imported with next/dynamic, focus is lost after every key stroke.

## To Reproduce

[Please see minimum reproduction repository](https://github.com/fi5u/nextjs-dynamic-import-with-text-input)
1. Create a component with a text input element.
2. Import that component into a parent component using next/dynamic. The parent component should handle the state of the value of the input element and pass that value down.
3. Attempt to type into the imported component input field.

## Expected behavior
User should be able to type without focus leaving the input field.

## System information
 - OS: macOS
 - Browser: Chrome, Firefox
 - Version of Next.js: 6.1.2 and 7.0.0-canary.18

## Additional context

Note the state of the dynamic input component is handled in the parent component. When its state is managed and updated within the imported component, focus is not lost.

**Comment by klujanrosas** [comment]
That is happening because you are dynamically importing your component inside of `render`.
And it imports it again and again on each component update.

So instead of this:
```jsx
class MyComponent extends React.Component {
  render() {
    const DynamicInput = dynamic(import('../components/input-elements'))

    return <DynamicInput />
  }
}
```

You want this:
```jsx
const DynamicInput = dynamic(import('../components/input-elements'))

class MyComponent extends React.Component {
  render() {
    return <DynamicInput />
  }
}
```

**Comment by fi5u** [comment]
Oh of course. Makes sense. Many thanks.
