### ISSUE TITLE
Add Jet to Next showcase

### ISSUE THREAD

**Issue by icarlossz** [zeit/next.js#5193]
# Request to be added to the showcase on nextjs.org. 

![image](https://user-images.githubusercontent.com/5649014/45633940-bc193800-ba66-11e8-9e5e-034eab3f013a.png)

- Name of company: Jet.com
- Url: [https://jet.com/](https://jet.com/)

The launch of our redesign was in a lot of media.

[Techcrunch](https://techcrunch.com/2018/09/13/walmarts-jet-com-relaunches-site-with-focus-on-urban-shoppers-same-day-grocery-delivery/)
[Forbes](https://www.forbes.com/sites/andriacheng/2018/09/13/walmart-jet-redesign-new-york/)

 Thank you!

**Comment by timneutkens** [comment]
Already added it locally, you can expect to see it very soon 🙏

**Comment by icarlossz** [comment]
Thank you Tim!

**Comment by timneutkens** [comment]
It's here 😄 https://nextjs.org/showcase/

**Comment by icarlossz** [comment]
Awesome! The design of the new guy was amazing, thank you Tim, see you soon!
