### ISSUE TITLE
with-react-i18next example not render html content in page source

### ISSUE THREAD

**Issue by xilanhthanki** [zeit/next.js#5198]
I used i18next following this link: https://github.com/zeit/next.js/tree/canary/examples/with-react-i18next
But the content in page source is empty. So server rendering not working.
Remove i18n container then it works fine.

Do you know how to make server rendering work using i18next?
Thanks.
![image](https://user-images.githubusercontent.com/21329596/45695950-b0279600-bb8c-11e8-8c5f-88d000758b25.png)

**Comment by ztanner** [comment]
Should now be fixed on canary by https://github.com/zeit/next.js/pull/5265

**Comment by BoxmodelTim** [comment]
This is happening to me all of a sudden. Doesn't appear that server side rendering is working anymore. My page source has the `<div id="__next"><div data-reactroot=""></div></div>` and then the _NEXT_DATA_?

I am not using i18next though.

Thanks,
