### ISSUE TITLE
Link & Button (Material UI / Semantic ...)

### ISSUE THREAD

**Issue by romainquellec** [zeit/next.js#5199]
# Feature request

## Is your feature request related to a problem? Please describe.
When we use a Button from material ui or others, its recommanded to use the comp. like this : 
<Button component={Link} /> but we cant with Link from Next (works with React Router).

The solution is :
<Link href="/something"><Button>Hi</Button></Link>

But with this, we lose the href. Am I missing something ?

## Describe the solution you'd like
The href should persist

## Additional context
similar to the last one on : https://github.com/zeit/next.js/issues/3696

**Comment by timneutkens** [comment]
I think there's some code snippets missing here.

**Comment by romainquellec** [comment]
I missed passHref. I'm closing this.

**Comment by herr-vogel** [comment]
@romainquellec 

i got it working like this

https://gist.github.com/herr-vogel/0b5d4f3c28f08dc6cc4a2fd4f7b4a4df
