### ISSUE TITLE
Relative module was not found

### ISSUE THREAD

**Issue by richbai90** [zeit/next.js#5206]
# Bug report

## Describe the bug

After upgrading to next 7.0.0 I cannot run my application, it compiles without error but then when browsing to a page it says: 

>This relative module was not found:
>
>* ./Toolbar in ./pages/builder/components/ToolBar/index.tsx

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
* clone the repo at https://github.com/richbai90/Project-Shimmer/tree/ts
* git checkout ts
* npm i && npm run dev

## Expected behavior
I expect that if the application compiles, it should not throw an error that a module was not found

## System information
 - OS: macOS
 - Browser (if applies) NA
 - Version of Next.js: 7.0.0

## Additional context

I am using typescript with NextJS

**Comment by richbai90** [comment]
I'm just an idiot nevermind

**Comment by patientplatypus** [comment]
Well this is incredibly unhelpful. What was the issue?

**Comment by gavinsharp** [comment]
In my case, I ran into a similar error because I had broken the `Next.js` config (configuring a webpack loader I had failed to install).
