### ISSUE TITLE
components directory not being bundled? cannot find module.

### ISSUE THREAD

**Issue by ryancole** [zeit/next.js#521]
I'm using the latest beta release, `2.0.0-beta.2`. I'm also using a custom server module. I've got several re-usable react components inside of a `components` directory, next to the `pages` directory. I'm trying to use these components from a custom `_document.js`.

I'm getting a run-time error as follows ...

```
{ Error: Cannot find module '../components/Navbar'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Ryan\Projects\league\src\.next\dist\pages\_document.js:35:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
```

After looking in the `dist` folder, I can see that the `components` directory has not been bundled and moved into there. I'm not sure if this is supposed to occur as-needed, as that's why I'm not seeing it, or not. Regardless, it's not there and so the error makes sense.

[Here is my repository](https://github.com/ryancole/league/tree/nextjs/src). Below is my custom `_document.js` file ...

```js
import React from "react";
import Document, {Head, Main, NextScript} from "next/document";

import Navbar from "../components/Navbar";
import Masthead from "../components/Masthead";

export default class MyDocument extends Document {
  render () {
    return (
      <html>
        <Head>
          <title>eSports Amateur League</title>
          <link rel="stylesheet" href="/static/css/bootstrap-flex.css" />
        </Head>
        <body>
          <Masthead />
          <Navbar />
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

Any ideas?

**Comment by nkzawa** [comment]
Hmm, yeah this doesn't work since we don't transpile required modules for now. It should be supported.

**Comment by ryancole** [comment]
@nkzawa The shared modules example seems to work on `2.0.0-beta.2`. Is this issue due to the use of the custom server? The shared modules example does not use a custom server, so maybe that's why it works there?

**Comment by nkzawa** [comment]
@ryancole the problem happens only if modules are required only on `_document.js`.

**Comment by ryancole** [comment]
@nkzawa Oh alright, I see. Is this pretty difficult to add in, or not? I'm not very familiar with next.js code yet, but if you consider this one pretty straight forward I can make an attempt at providing a PR. Until this is working, I will just not use these components from `_document.js`.

**Comment by ryancole** [comment]
@nkzawa I just cloned and tested #534. It does indeed fix the component issue. Some other things I noticed is that now the server properly reloads when changes are made to `_document.js`, which is nice. It didn't reload before #534. Very nice!
