### ISSUE TITLE
Example "with-next-sass-app" fails w/ Next v7 & next-sass v1

### ISSUE THREAD

**Issue by rkrueger11** [zeit/next.js#5210]
# Examples bug report

## Example name
with-next-sass-app

## Describe the bug
Using with-next-sass-app with `next v7.0.0` and `@zeit/next-sass v1.0.0` fails _in development_ with 
```
./styles/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
```

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Update the example to use next v7 and next-sass v1.
2. `npm run dev`
3. See error

**Comment by rkrueger11** [comment]
with-next-css with next v7 and next-css v1 seems to work fine

**Comment by timneutkens** [comment]
Feel free to create a pull-request upgrading the dependencies next time 👍 I've pushed the new `@zeit/next-sass` version to the example.

**Comment by rkrueger11** [comment]
Sorry, thought there was a different error here (one that I'm having in a different repo) ... didn't realize it was just dependency updates causing the above error, and when I did, that's when I closed it.

But thanks!
