### ISSUE TITLE
Can we implement prefetching not using Service Worker?

### ISSUE THREAD

**Issue by irrigator** [zeit/next.js#522]
First of all, thanks for creating such an amazing tool! Next.js seems like a "dream framework" to me for building web apps, which "brings us the best of both worlds" (single page app and server side rendering).

To me the most important piece that helps Next.js fullfil its promise is the ability to prefetch all the components that the <Link /> tags point to in a page.

According to the documentation this feature is implemented using Service Worker, a API that only supports Chrome and Firefox. This means a great portion of web users just can't take advantage of this great feature. I don't know if I miss something.

Can we implement prefetching using other kinds of techniques, which support all modern browsers, instead of using Service Worker?

**Comment by arunoda** [comment]
> This means a great portion of web users just can't take advantage of this great feature

This is kind a untrue. See: http://caniuse.com/#feat=serviceworkers
Browsers going into this direction and will catch up soon.

Anyway, our current focus is shipping 2.0 and this prefetching solution is pretty neat for that.
This is something we might do later on. If someone could work on this, I think we have no reason to say no.

**Comment by sedubois** [comment]
I noted here some ideas to broaden the support, namely using AppCache: https://github.com/zeit/next.js/issues/24#issuecomment-258804529

**Comment by rauchg** [comment]
A principle that has served us well over the years is to provide _support_ for all browsers, but _optimizations_ for modern ones.

Prefetching is an optimization. To invest more and more code into an optimization that will be deprecated doesn't seem like a good area of focus.

If you want, feel free to create your own userland prefetching module that exposes the same API as `next/prefetch`. The neat thing is: if you don't use `next/prefetch`, it won't make it into the build. No bloat :)
