### ISSUE TITLE
Sub component couldn't trigger the HRM when I upgrade to v7.0.0

### ISSUE THREAD

**Issue by DevilZh** [zeit/next.js#5224]
as the title, today I upgrade to v7.0.0, every thing looks awesome, except the HRM, em...

specifically，I found the HRM couldn't repaint the document automatically when I change sth. in sub component.

but it works on the chrome dev tools(console log the text '[HMR] bundle rebuilding'), 
and it also works on the container components of pages/ dir.

System information
OS: macOS 10.13.4
Browser: Chrome v69.0.3497.81
Version of Next.js:  7.0.0

more information: I use typescript, and styled-components, next-router in my project.

**Comment by timneutkens** [comment]
We have tests for updating subcomponents. Please follow the issue template and provide a clear and concise reproduction so that we can help you.
