### ISSUE TITLE
Lastest Next version doesnt works with jest and next-css

### ISSUE THREAD

**Issue by randalmaia** [zeit/next.js#5236]
# Examples bug report

## Example name
with-jest

## Describe the bug
Conflict between webpack and next-css

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone next 'with-jest' example
2. Add ```"@zeit/next-css": "^0.2.0"``` to package json
3. Add 
```
const withCSS = require('@zeit/next-css')
module.exports = withCSS()
```
in ```next.config.js```

4. See error on build
<img width="1013" alt="screen shot 2018-09-20 at 11 40 55 am" src="https://user-images.githubusercontent.com/2751058/45826168-4f05dc80-bcca-11e8-8ce1-f1583215fc8a.png">

## Expected behavior
Run build with success

## System information
 - OS: macOS
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: latest

## Additional context

My current package.json
```
{
  "name": "with-jest",
  "version": "1.0.0",
  "dependencies": {
    "next": "latest",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "@zeit/next-css": "^0.2.0"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "enzyme": "3.4.3",
    "enzyme-adapter-react-16": "1.2.0",
    "jest": "23.5.0",
    "react-addons-test-utils": "15.6.2",
    "react-test-renderer": "16.4.2"
  },
  "scripts": {
    "test": "NODE_ENV=test jest",
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
}
```

Current next.config.js
```
const withCSS = require('@zeit/next-css')
module.exports = withCSS()
```

**Comment by danielr18** [comment]
"@zeit/next-css": "^0.2.0" isn't compatible with 7.0 as far as I know, you need to update it to "@zeit/next-css": "^1.0.1".
