### ISSUE TITLE
Prevent getInitialProps client-side

### ISSUE THREAD

**Issue by sebasgarcep** [zeit/next.js#524]
Currently getInitialProps runs once on the server and once on the client. Is there a way to disable it from running on the client or preserving the props it got from the server render on certain pages?

**Comment by nkzawa** [comment]
To make it clear, `getInitialProps` runs on server if it's server rendering, and does on client if page transition occurs by using `Link` component or `props.url.push()`.

If you don't want to provide props on client for example, you can write like the following.

```js
const isServer = typeof window === 'undefined'
static getInitialProps () {
  if (isServer) {
    return { value: 'hi' }
  } else {
    return {} 
  }
}
```

**Comment by sebasgarcep** [comment]
For some reason getInitialProps is running on the client as soon as it renders. Maybe it's because I'm using next programmatic API. I'll be looking into it to see if it's a problem on my end
