### ISSUE TITLE
Can someone please provide example with both react-helmet and styled-components?

### ISSUE THREAD

**Issue by ItsMrAkhil** [zeit/next.js#5240]
I'm facing an issue that I can't use the react-helmet and the styled-component together with next.js. Inside the examples provided by next.js, they are using each package in different repos. Can someone help me with this?

**Comment by timneutkens** [comment]
Please follow the issue template and post questions on https://spectrum.chat/next-js. 

In general you don't need react-helmet when using Next.js, as you can use `next/head`.
