### ISSUE TITLE
Could not freeze filename

### ISSUE THREAD

**Issue by mitrey** [zeit/next.js#5243]
Recently I've updated Next to version 7 and now when i run "npm run dev" and start changing and saving my files I see notifications in console "Could not freeze ./pages/_app.js: Cannot read property hash of undefined". 

The same notification are about several another files. What does it mean?

**Comment by danielr18** [comment]
It has happened to me, deleting the cache solved it.

`rm -rf node_modules/.cache`

**Comment by mitrey** [comment]
@danielr18 thank you. It works for me.
Why did this happen after update to version 7?

**Comment by tusbar** [comment]
Related to #5213

**Comment by timneutkens** [comment]
Will probably be fixed when mzgoddard/hard-source-webpack-plugin/pull/419 lands

**Comment by timneutkens** [comment]
Closing this as we removed hard-source due to above issues.
