### ISSUE TITLE
 Styled JSX error in <> shorthand

### ISSUE THREAD

**Issue by mvllow** [zeit/next.js#5245]
# Bug report

Upgraded to v7 and was excited to use the new `<>` shorthand for Fragment. Wrapping a component in `<Fragment>` allows Styled JSX to be added before `</Fragment>` (full code example below) but this is now throwing an error with the new syntax:
```
index.js:2178 Warning: Received `true` for a non-boolean attribute `jsx`.
```

**Working** (NextJS 6 & 7)
```
import React, { Fragment } from 'react';

export default () => (
    <Fragment>
        <h1>Stay mellow</h1>
        <p>Lorem ipsum sol dolar amit</p>

        <style jsx>{`
            h1 {
                color: salmon;
            }
        `}</style>
    </Fragment>
)
```

**Not working** (NextJS 7)
```
import React from 'react';

export default () => (
    <>
        <h1>Stay mellow</h1>
        <p>Lorem ipsum sol dolar amit</p>

        <style jsx>{`
            h1 {
                color: salmon;
            }
        `}</style>
    </>
)
```

## System information
 - OS: macOS
 - Browser: Chrome
 - Version of Next.js: 7.0.0

_Also at https://spectrum.chat/thread/a9662499-1cb2-45aa-9455-95dd1af26cfd_

**Comment by timneutkens** [comment]
This is a known styled-jsx issue: https://github.com/zeit/styled-jsx/issues/458
