### ISSUE TITLE
Error when run dev after upgrade to nextjs 7

### ISSUE THREAD

**Issue by ardyfeb** [zeit/next.js#5248]
I just upgraded nextjs to 7 (latest)

But after upgrading, when i running an error occurred

The error is (node:23695) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

And failed to start dev server

**Comment by ardyfeb** [comment]
Here my package.json

{
  "name": "KolabStack",
  "scripts": {
    "dev": "PORT=3003 node core/server.js",
    "build": "node node_modules/next/dist/bin/next build",
    "start": "NODE_ENV=production yarn dev"
  },
  "dependencies": {
    "@material-ui/core": "latest",
    "@material-ui/icons": "^3.0.1",
    "@zeit/next-css": "^0.2.0",
    "axios": "^0.18.0",
    "cookie-parser": "^1.4.3",
    "dotenv": "^6.0.0",
    "dotenv-webpack": "^1.5.7",
    "draft-js": "^0.10.5",
    "express": "^4.16.3",
    "js-cookie": "^2.2.0",
    "jss": "^9.8.7",
    "next": "latest",
    "next-images": "^1.0.0",
    "next-routes": "^1.4.2",
    "next-seo": "^1.2.0",
    "nprogress": "^0.2.0",
    "prop-types": "^15.6.2",
    "react": "^16.5.1",
    "react-content-loader": "^3.1.2",
    "react-dom": "^16.5.1",
    "react-jss": "^8.6.1",
    "react-mde": "^5.8.0",
    "react-quill": "^1.3.1",
    "remove": "^0.1.5"
  }
}

**Comment by timneutkens** [comment]
You're adding a custom webpack plugin that doesn't support webpack 4. You either have to upgrade it, fix the plugin, or use a different one. The most likely one from the list of dependencies is dotenv-webpack.

**Comment by timneutkens** [comment]
Also please follow the issue template in the future.

**Comment by JiiB** [comment]
@ardyfeb what was the issue?
