### ISSUE TITLE
[2.0 beta2] How to serve json content?

### ISSUE THREAD

**Issue by tpai** [zeit/next.js#525]
Now using 2.0.0 beta 2, now trying to create some API, but `renderToJSON()` seems not accept any custom data, any ideas?

**Comment by nkzawa** [comment]
We don't offer any APIs for serving JSON (`renderToJSON` is a private API.). You can implement it like:

```js
function handler(req, res) {
  if (/^\/api\//.test(req.url)) {
    ressetHeader('Content-Type', 'application/json') 
    res.end(JSON.stringify({ value: 'hahaha' }))
    return
  }
}
```  

Though we recommend to prepare a different API server instead of doing this.
