### ISSUE TITLE
Next 7 + Express not displaying server errors when pages/_document.js exists

### ISSUE THREAD

**Issue by gnarmedia** [zeit/next.js#5251]
# Bug report

## Describe the bug
In Next 7 with Express if you have a pages/_document.js it seems to silently swallow errors

## To Reproduce
1. npx create-next-app --example custom-server-express custom-server-express-app
2. add `throw new Error('error')` to line 24 in server.js
3. run the server
4. notice the server exits with an error
5. make a directory called 'pages' with a '_document.js' file inside it, it doesn't even need any content
6. restart the server
7. notice it doesn't exit with the error anymore, it just swallows it

## Expected behavior
It should exit with the error displayed, same as it does in Next 6

## System information
 - OS: Kubuntu 18.04
 - Version of Next.js: 7.0.0

I'd be happy to try contributing a fix, I'm just not sure what's going on.

**Comment by timneutkens** [comment]
Do you mean adding a `throw` here: https://github.com/zeit/next.js/blob/canary/examples/custom-server-express/server.js#L24

🤔

**Comment by gnarmedia** [comment]
@timneutkens Yes, but you can always simulate the error wherever, it doesn't matter

**Comment by HaNdTriX** [comment]
Thank you for reporting this. 🙏

I could reproduce your issue. We are working on it.

https://github.com/webpack/webpack-dev-middleware/issues/339

In the meantime you can at least show the warnings by adding the following code to your project:

```js
process.on('unhandledRejection', (reason, p) => {
  console.error(reason)
})
```
