### ISSUE TITLE
Next@7+ HRM does not work if using module with default exports

### ISSUE THREAD

**Issue by DevilZh** [zeit/next.js#5254]
# Bug report

## Describe the bug

Next 7, the HRM does not work when updated the module with default exports.
Specifically, document could not be repainted automatically
## To Reproduce
1. in pages/index
``` js
 import Header from './components/Header'
 // ...
```
2. in ./components/Header
```js
const Header = () => <h1>this is header.</h1>
export default Header
```
for the first load, the header could be rendered without error. 

3.then update the Header and save
```js
const Header = () => <h1>this is UPDATED header. </h1>
export default Header
```
the HRM does not work, except the dev-tools console log the text `'[HMR] bundle rebuilding'`

## Expected behavior
the HRM works well even if using module with default exports
or 
page couldn't render header components for the first load, and throw a error 'module could not be found.'

## my temporary solution
I change my code to this, and it works for me:
```js
 // pages/index
 import { Header } from './components/Header'
	
 // ./components/Header
 const Header = () => <h1>this is UPDATED header. </h1>
 export { Header }
```
## Additional context

maybe this is not a problem of next.js,  but is its own problem of [export default syntax](https://github.com/airbnb/javascript/issues/1365)
whatever, I think it would be better if you make no exception of them between first load and hot reload.

**Comment by timneutkens** [comment]
`'./components/Header'`

It seems like you have your components directory located in `pages` instead of outside it, this causes a *lot* of added compilation time + issues like you're experiencing now as every `.js` file inside of `pages` is a webpack entrypoint.

Doing this will also break code splitting / commons bundles since we calculate `totalpages * 0.5`

**Comment by DevilZh** [comment]
em...I' m sorry, I forgot sth.
I have this setting in next.config.js
```js
module.exports = {
  useFileSystemPublicRoutes: false
}
```
Besides, It's not important where the `Header` component is, I change the it to root directory.  such as:
```js
// pages/index
import  Header from '../Header'
```
the problem is still exist.

**Comment by DevilZh** [comment]
I'm sorry for the mistake,  I have a misunderstanding about the setting  option`useFileSystemPublicRoutes`

**Comment by DevilZh** [comment]
I thought `useFileSystemPublicRoutes: false` would resolve all about what you mentioned.

**Comment by timneutkens** [comment]
Just to clear this up for future readers:

`useFileSystemPublicRoutes` only disables 1 route on the Next.js server, it doesn't relate to building / compiling indeed 👍
