### ISSUE TITLE
Exported path lookup failure causes full page loads

### ISSUE THREAD

**Issue by slaskis** [zeit/next.js#5268]
# Bug report

## Describe the bug

When using an exported app it tries to load the wrong js file. This causes full loads when only a "history push" is expected (even when a link is shallow). 

Our specific use case is a modal controlled by the query parameters which now when a full page load happens scrolls up and does not animate in smoothly as expected. It also behaves "properly" in dev.

## To Reproduce

1. Go to https://out-pxzzcijwlg.now.sh/
2. Make sure to have persistent logs enabled as page load clears it
3. See how the logs contains a 404 for the missing export path and a full navigation:

```
GET https://out-pxzzcijwlg.now.sh/_next/static/0nKDPOy4frajWiZ9UFgj~/pages/hello.js net::ERR_ABORTED 404
Navigated to https://out-pxzzcijwlg.now.sh/hello/
```

4. Checkout repo from `git clone https://github.com/slaskis/test-next-export.git`
5. Build and run it with: `yarn && yarn build && yarn export && yarn serve` to try it locally 

## Expected behavior

I expected it to load the same js bundle as when visiting the root page and not a 404. 

## Screenshots
![image](https://user-images.githubusercontent.com/5991/45945418-c51d8280-bfed-11e8-955e-fd9b9371425d.png)

## System information
 - Version of Next.js: 7.0.0

**Comment by iTonyYo** [comment]
https://github.com/zeit/next.js/issues/2833#issuecomment-324202757
