### ISSUE TITLE
The default _document template, get rid of style.css?

### ISSUE THREAD

**Issue by VanquisherMe** [zeit/next.js#5271]
![image](https://user-images.githubusercontent.com/4927398/45966089-c639c880-c05c-11e8-9877-2c261ceb0a0a.png)
from [with-ant-design-less](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less)
The default **_document** template, get rid of **style.css**?

**Comment by ardyfeb** [comment]
in nextjs7 the plugin @next/css automatic injected to head
