### ISSUE TITLE
Static properties on React component are lost when imported with nextjs/dynamic

### ISSUE THREAD

**Issue by idungotnosn** [zeit/next.js#5274]
# Bug report

When I import a React Component using next/dynamic, I cannot access its static properties.

## Describe the bug

If I define a component like this:

```
export default class Foo extends React.Component {
  static foo = () => {
    console.log("foo");
  }
  constructor(props) {
    super(props);
  }
  render(){
     return <p>Foo</p>
  }
}
```

...and then I try to import it in another file like this:

```
const Foo = dynamic("some/path/to/Foo");

console.log(Foo.foo);
```

I get `undefined` as a log statement.  However, if I do the following:

```
import Foo from "some/path/to/Foo";
console.log(Foo.foo);
```

I would not get `undefined` but rather the function I defined previously.

## Expected behavior
I expected `console.log(Foo.foo)` to not return `undefined` when dynamically imported.  

## System information
 - OS: macOs
 - Version of Next.js: 4.2.3

## Additional context

I do understand that I am using an old and outdated version of Next/JS, but I haven't found any google search results that indicate this problem was fixed in a later version of Next/JS or even fixed at all.

**Comment by HaNdTriX** [comment]
This is because you are not using dynamic imports correctly:

This is how it should look like:

```js
const FooLoadable = dynamic({
  loader: () => import('../components/somePath/Foo')
})
```

Please note that `FooLoadable` will then be an instance of `<LoadableComponent />` wich eventually will resolve to `Foo`.

**More infos:** https://github.com/zeit/next.js/blob/canary/examples/with-dynamic-import/pages/index.js
