### ISSUE TITLE
Next.js With Express and Spdy

### ISSUE THREAD

**Issue by invisibled** [zeit/next.js#5275]
I've read the other issues pertaining to http2 and next, and how next shouldn't really interfere with you using spdy. However i've come across an error I can't get past, which seems to only come up with next.js in the mix. Maybe somebody will recognize the error or be able to provide me with some more info. I'll keep my code short:

app.js (start point of the server)

```
// Dependencies
const next        = require('next'),
      dev         = process.env.NODE_ENV !== "production",
      app         = next({ dev, dir: './app' }),
      handle      = app.getRequestHandler()

// Modules
const server      = require('./core/server'),
      error       = require('./core/error')

// Server
app
  .prepare()
  .then( () => server(handle) )
  .catch(error)
```

server.js (express and spdy config, irrelevant code removed)

```
// Export
module.exports = handle => {
  const server = express()

  server

    // .get('*', (req, res) => {
    //   res.status(200).json({message: 'ok'})
    // })

    .get('*', (req, res) => handle(req, res))

  spdy
    .createServer(spdyOptions, server)
    .listen(cf.port, listen)

}
```

When I run the app with the currently commented out  `get` request, the app runs, serves up with `h2` and displays the message on screen. However, when i run the app with `.get('*', (req, res) => handle(req, res))` i get the error

```
internal/stream_base_commons.js:62
  var err = req.handle.writev(req, chunks, allBuffers);
                       ^
TypeError: req.handle.writev is not a function
    at writevGeneric (internal/stream_base_commons.js:62:24)
    at Socket._writeGeneric (net.js:711:5)
    at Socket._writev (net.js:720:8)
    at doWrite (_stream_writable.js:408:12)
    at clearBuffer (_stream_writable.js:517:5)
    at Socket.Writable.uncork (_stream_writable.js:314:7)
    at connectionCorkNT (_http_outgoing.js:641:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

this leads me to believe it's coming from the `handle` function, which is necessary for next.js, am i correct in this? Maybe i'm just passing things around improperly? Can anybody see a potential fix for this? I'm happy to provide any more information or code at your request. Thanks!

**Comment by timneutkens** [comment]
Please follow the issue template and provide a reproducible example.
