### ISSUE TITLE
Flash of unstyled content / SSR styles not flushed to head in Next@7.0.0

### ISSUE THREAD

**Issue by pioul** [zeit/next.js#5283]
# Bug report

## Describe the bug

Styles aren't flushed to the head anymore in next@7.0.0 (they're nowhere to be found in the source served by the server), resulting in server-side source first rendered without styles, and then a client-side re-render showing those styles again.

next@6.* works great, and so does next@7.0.0-canary.0
next@7.0.0, and the latest canary (next@7.0.1-canary.0) do not

## To Reproduce

I was able to reproduce this with a typical next app using styled jsx, and (if that's meaningful in the current situation), the following HOC:

<details>
  <summary>See code</summary>

```js
const asPage = (WrappedComponent, pageTitle) => (
  class extends React.Component {
    static async getInitialProps(context) { /* ... */ }

    render() {
      return (
        <div>
          <Head>
            <title>{pageTitle && `${pageTitle} – `}Unspent</title>
            {/* various meta and link tags */}
            <link rel="stylesheet" type="text/css" href="/static/icons/iconfont.css" />
          </Head>

          <SessionContext.Provider value={this.props.session}>
            <WrappedComponent {...this.props} />
          </SessionContext.Provider>

          <style jsx>{`:global(body) { /* some global styles */ }`}</style>
        </div>
      );
    }
  }
);
```

</details>

## Expected behavior

Style tags to be flushed in the head on server-side render.

**Comment by timneutkens** [comment]
Could you create a minimal repository? There's a lot going on in your code, including context, getInitialProps, but you're creating a HOC, so I'd like to see the full usage 👍

**Comment by bergold** [comment]
Had the same bug.
I had `styled-jsx` listed as a dependency in my project (even the same version next@7.0.0 uses: `^3.0.3-canary.0`), but removing it and reinstalling all dependencies fixed the issue for me.

**Comment by pioul** [comment]
Hmm, I reinstalled next@7.0.0 today (I dropped the styled-jsx dependency yesterday), and things seem to be working with no meaningful changes from yesterday's setup. I did make a small test case before this, and couldn't reproduce in it either, so like @bergold mentioned it might very well be an issue with fully resetting deps!

I'll close since fully dropping deps and reinstalling them seems to indeed fix the issue! I'm unsure why that wasn't enough yesterday though.

**Comment by clayhan** [comment]
@pioul Would you be able to extrapolate the process to avoid this "bug"? I'm having this same behavior but having a hard time understanding what is happening that is causing it and what exactly I need to do. I just started trying to use the <style jsx global> concept but don't know if I'm entirely not doing something. Thanks a ton.
