### ISSUE TITLE
Can you use .htaccess redirect from http to https?

### ISSUE THREAD

**Issue by thomasbrown6** [zeit/next.js#5285]
# Question
This isn't really a bug at all and I'm probably asking this in the wrong place. But just a quick question, I've been working on this for a few days now. I'm using GoDaddy to host my Next.js site and my https secure line is up and working. But when a user clicks on the site from Google, it's the http url and sends them to the unsecure page. So I've been trying to use .htaccess to redirect all to https but does next.js support this? Or is there a better way to implement this?

**Comment by timneutkens** [comment]
First of all please follow the issue template in the future.

Next.js is a Node.js application, it implements the Node.js http server. In case you want to use htaccess you'll have to put apache in front of the Next.js server, or if you're using static export you'll have to host the static files on the apache server.
