### ISSUE TITLE
Next.js With Express and Spdy

### ISSUE THREAD

**Issue by invisibled** [zeit/next.js#5286]
# Bug report

## Describe the bug

I've read the other issues pertaining to http2 and next, and how next shouldn't really interfere with you using spdy. However i've come across an error I can't get past, which seems to only come up with next.js in the mix. Maybe somebody will recognize the error or be able to provide me with some more info.

When I run my app with a basic express only `get` request, `/plain` in the example, the app runs, serves up with `h2` and displays the message on screen. However, when i run the app with `.get('*', (req, res) => handle(req, res))` i get the error listed below.

This leads me to believe it's coming from the `handle` function, which is necessary for next.js, am i correct in this? Maybe i'm just passing things around improperly? Can anybody see a potential fix for this? I'm happy to provide any more information or code at your request. Thanks!

## To Reproduce

```
// Dependencies
const next        = require('next'),
      express     = require('express'),
      spdy        = require('spdy'),
      fs          = require('fs'),
      dev         = process.env.NODE_ENV !== "production",
      app         = next({ dev }),
      handle      = app.getRequestHandler()

// Spdy Setup
const spdyOptions = {
  key: fs.readFileSync( `server.key` ),
  cert: fs.readFileSync( `server.crt` )
}

// Server
app
  .prepare()
  .then( () => {

    const server = express()

    server

      // Plain Express Route
      .get('/plain', (req, res) => {
        res.status(200).json({message: 'ok'})
      })

      // Next.js Route
      .get('*', (req, res) => handle(req, res))

    spdy
      .createServer(spdyOptions, server)
      .listen(3103, err => {
        if (err) throw err
      })

  })
  .catch( ex => {
    console.error(ex.stack)
    process.exit(1)
  })
```

## Expected behavior
The server should start and serve the next app but instead I get this error:

```
internal/stream_base_commons.js:62
  var err = req.handle.writev(req, chunks, allBuffers);
                       ^
TypeError: req.handle.writev is not a function
    at writevGeneric (internal/stream_base_commons.js:62:24)
    at Socket._writeGeneric (net.js:711:5)
    at Socket._writev (net.js:720:8)
    at doWrite (_stream_writable.js:408:12)
    at clearBuffer (_stream_writable.js:517:5)
    at Socket.Writable.uncork (_stream_writable.js:314:7)
    at connectionCorkNT (_http_outgoing.js:641:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## System information
 - OS: macOS High Sierra
 - Version of Next.js:  7.0.0

**Comment by invisibled** [comment]
This actually works on node v8, i was running this on node v10. Closing this issue as it doesn't seem to have anything to do with next, rather a node issue.

**Comment by hitbiz** [comment]
Same problem (node v10) you can use something like this
```
https = dev ? require('https') : require('spdy')
```
