### ISSUE TITLE
Object doesn't support property or method 'find' in IE11

### ISSUE THREAD

**Issue by nagman** [zeit/next.js#5287]
Apparently, the `find` method is not transpiled by babel.

When I open my website in IE11 I see a big and beautiful error:
`Object doesn't support property or method 'find'`

Is it normal? Do I need to change the default babel config?

For information, I'm simply using a find on an array imported from my project with `import * as routes from '../routes.js';`
And this routes.js uses a `module.exports = [ ...whateverThatArrayIs ];`

**Comment by timneutkens** [comment]
Here's an example of how to add polyfills: https://github.com/zeit/next.js/tree/canary/examples/with-polyfills

Note that the `find` method is most likely used in a dependency, not Next.js itself.

**Comment by timneutkens** [comment]
Please follow the issue template next time 👍
