### ISSUE TITLE
Unexpected localStorage behavior

### ISSUE THREAD

**Issue by arherzf8er** [zeit/next.js#5293]
# Bug report

## Describe the bug

Weird behavior within ternary operators. It works only if there are other conditions.

## To Reproduce
THIS CODE gives an error
```
render() {
  return <div>{this.state.a === localStorage.getItem('a') ? true : false}</div>
}
```

THIS ONE works as intended
```
render() {
  return (
    <div> {this.state.b === 'b' 
          && this.state.a === localStorage.getItem('a') ? true : false}</div>
  )
}
```

## Expected behavior
Usual SSR & React-ish Web storage behavior.

## System information
 - OS: Ubuntu 18.04 / Win 10
 - Chome@latest
 - Version of Next.js: ^7.0.0

**Comment by timneutkens** [comment]
`localStorage` is only available on the client side, so you have to check if it's available before using it.

**Comment by timneutkens** [comment]
I'm not sure exactly, but my assumption is `this.state.b === 'b'` being `false` which results in the rest of the block not being executed.
