### ISSUE TITLE
forwardRef prevent data to be load server side in child component 

### ISSUE THREAD

**Issue by seb-saletes** [zeit/next.js#5299]
# Bug report

## Describe the bug

Starting from the with-apollo example it seems that React.forwardRef api is breaking SSR for query in child component.
I created a repo where I reproduced my use case: https://github.com/seb-saletes/next-apollo-forwardRef-issue

## To Reproduce

Go to pages/index.js and comment in and out the different version of the same HOC and disable javascript from your browser

## Expected behavior
Being able to forward ref and load data server side

## System information
 - OS: macOS
 - Browser: chrome
 - Version of Next.js: latest
- React: latest

**Comment by seb-saletes** [comment]
Ty for your feedback. I will post it on their repo as well

**Comment by timneutkens** [comment]
Looks like said issue was solved.
