### ISSUE TITLE
dynamic()  doesn't work with SSR in 7.0.1-canary.0

### ISSUE THREAD

**Issue by arthens** [zeit/next.js#5305]
# Bug report

## Describe the bug

https://github.com/zeit/next.js/pull/5249 fixed chunks being loaded even when not used, but it might have introduced a different bug.

I created a new app using `7.0.1-canary.0`, and `react-loadable` is not picking up any fragment. This causes the client to briefly display the loader. I spent some time debugging, and I think the problem might be with the babel compiler (I'm speculating - maybe the compiler doesn't recognise the chunk being loaded now that it's a function?).

If I use `dynamic(import(...))` the `react-loadable` compiler adds `modules` and `webpack` to `opts` (but then chunks are immediately loaded). 

If I use `dynamic(() => import(...))` the compiler doesn't add `modules` and `webpack`. `opts.modules` is always null, so it doesn't [report chunks](https://github.com/jamiebuilds/react-loadable/blob/master/src/index.js#L167).

## To Reproduce

I pushed a tiny example here:
https://github.com/arthens/nextjs-canary

Install deps, run it, open `http://localhost:3000`, and you should see `Welcome :)` quickly disappear and re-appear when react kicks in and load the missing chunk.

## Expected behavior

`Welcome :)` shouldn't disappear.

## System information

 - Version of Next.js: 7.0.1-canary.0

**Comment by Fumler** [comment]
We had this issue I think, at least for us the server delivered the correct html, but when the app mounted, every component turned into a loader and then back again.

The fix for us was turning this
```javascript
const ArticlePreview = dynamic({
	loader: () => import(/* webpackChunkName: "ArticlePreview" */ '../../components/ArticlePreview')
})
```

into this
```javascript
const ArticlePreview = dynamic({
	loader: () => import(/* webpackChunkName: "ArticlePreview" */ '../../components/ArticlePreview'),
	webpack: ['../../components/ArticlePreview']
})
```

Now everything works like it should.

**Comment by arthens** [comment]
> We had this issue I think, at least for us the server delivered the correct html, but when the app mounted, every component turned into a loader and then back again.

Yes, same problem.

> Now everything works like it should.

That fixes it because you are manually doing what `react-loadable` is meant to do for you:

https://github.com/jamiebuilds/react-loadable#declaring-which-modules-are-being-loaded

**Comment by timneutkens** [comment]
Good catch, fixed in https://github.com/zeit/next.js/pull/5308, also added tests for it so that we won't run into this in the future.
