### ISSUE TITLE
Router not updated before passing to getInitialProps of App

### ISSUE THREAD

**Issue by sheerun** [zeit/next.js#5311]
# Bug report

## Describe the bug

props.router.asPath of props from getInitialProps of App is lagging behind what's passed to Page or what's retrieved in withRouter

## To Reproduce

Go to https://github.com/sheerun/next-reproduce-router-lagging

And run `yarn dev`

If you click butten the asPath from getInitialProps or App is lagging behind.

## Expected behavior

Router instance passed to getInitialProps of App should be the same as in other places

**Comment by timneutkens** [comment]
We should remove router there, it has no added value there at the moment. Instead you should read from `ctx`, which holds immutable values. `router` holds the singletonrouter instance.

**Comment by sheerun** [comment]
Hey, not so fast :) There is a use case for me: I use router.asPath and other router data to fetch appropriate data asynchronously in getInitalProps of App.

**Comment by timneutkens** [comment]
Like I said, it's only confusing people. `asPath` is available on `ctx` and it's immutable

**Comment by sheerun** [comment]
I've updated reproduction and indeed ctx.asPath is keeping up the pace, just two comments:

1. I hope you'll push removing it to next.js 8 as it's breaking change. Maybe deprecate in this release
2. If server-side App component is supporting withRouter decorator, then why you won't opt for just fixing this behavior? It's nice to have access to router instance regardless. If for some reason it's not recommented then maybe also introduce warning when using withRouter on App

**Comment by timneutkens** [comment]
> I hope you'll push removing it to next.js 8 as it's breaking change. Maybe deprecate in this release

We're not introducing breaking changes between majors.

I guess we should wrap App into a provider component for the router, I was holding off on that to implement React 16.3 context.

**Comment by sheerun** [comment]
Just to make things clear: withRouter is currently working properly with App component

**Comment by sheerun** [comment]
Even if you remove router from appContext it would be still good to update singleton instance 
before getInitialProps of App is called, because users of Next.js can try to read from this instance in code that's running in getInitialProps of App. It's just not symmetrical that router singleton is already in good state in getInitialProps of Page, but not in getInitialProps of App..

**Comment by sheerun** [comment]
@timneutkens Is it removed?

**Comment by timneutkens** [comment]
@sheerun not removed, but I dropped it from the docs to avoid further confusion. I've also tracked down why we even pass it along to getInitialProps, it's for `getDataFromTree` in the with-apollo example. So I guess we'll have to create the object one level higher than _app.js and pass it into _app.js / getInitialProps there.

**Comment by timneutkens** [comment]
Closing this because of https://github.com/zeit/next.js/issues/6537
