### ISSUE TITLE
add feature to  pass props from getIntialProps to child component

### ISSUE THREAD

**Issue by contactyash** [zeit/next.js#5314]
# Feature request

## Is your feature request related to a problem? Please describe.
I am making a app which gets all data from firebase database on initial load and then use it many child components , so when I fetch data in getInitialProps I can only use it in that page only and can not pass it to child component . I mean I can pass but empty html tags will be sent to source html and then it will populated with content , which I think is not the purpose of nextjs.

## Describe the solution you'd like
I want returned object from getIntialProps should be sent to client the way it is used in the app formated in html , in all of child components also . and no __NEXTDATA__ kind of thing should be shipped to client

## Describe alternatives you've considered
I didn't find a solution to what I actually want

**Comment by contactyash** [comment]
I was maping props in componentdidmount in child component which was causing unexpected behaviour

**Comment by kyrolos** [comment]
yea I guess that I 'm facing the same problem right now

**Comment by heshamelmasry77** [comment]
Same here and I don't know what to do. Move back to CRA :s
