### ISSUE TITLE
Cannot alias React

### ISSUE THREAD

**Issue by lukeed** [zeit/next.js#532]
After #222 & using the latest `master` branch (`2.0.0-beta.3`) it's impossible to fully omit React from the next bundles. 

Using this `next.config.js`: 

```js
module.exports = {
  webpack: (cfg, { dev }) => {
		cfg.resolve.alias = {
			'react': 'preact-compat',
			'react-dom': 'preact-compat'
		}
    return cfg
  }
}
```

In doing so, the `commons.js` output contains all Next.js pre-built code, including React. It **also** contains `preact` and `preact-compat`. Having both React & Preact within the same bundle makes the alias redundant and pointless.

### Possible Solutions

1. Ship Next.js without the `dist` folder. Instead, build the library within `next build` _before_ building the application code. This will also require that the new `build` process adheres to the same `next.config.js` configuration (user + defaults) all throughout. 

2. Add a `jsnext:main` entry with a myriad of module`import`/`export` statements so that we may bypass the pre-builts & handle the build process ourselves (above).

Both venture further into "userland", but they're also both completely opt-in. The unaware / unwanting dev should not & will not be affected.

Also, I thought this was the promise of #222 until I saw that my bundles fattened. For a second, t'was comforting to know that it wasn't just me over the holidays...

**Comment by arunoda** [comment]
@lukeed I think the issue here is related to our babel config.
See [here](https://github.com/zeit/next.js/blob/master/server/build/babel/preset.js)

Here we use alias for react and react-dom in the babel level. That's why both are in the bundle.
(I hope we are doing that to support NPM2)

Anyway, you can write a custom `.babelrc` and get rid of this issue.

**Comment by arunoda** [comment]
@lukeed Yep you are correct. common.js has React itself and main.js has preact.

I really like the **solution 1** you suggested.

> Ship Next.js without the dist folder.

I think this is something we could do. We just need to let babel to parse our next's public API as well.

**Comment by arunoda** [comment]
I tried it now and we may don't need to change any core setup at all.
See: https://github.com/zeit/next.js/pull/543

**Comment by lukeed** [comment]
@arunoda Your PR does not work. While React is now missing from the `commons.js` file, it still exists in `main.js`.

**Comment by arunoda** [comment]
> fully removing/aliasing React is still broken.

What do you mean by this?

**Comment by arunoda** [comment]
Did you check the production source code? To my check React was not in either files.

**Comment by arunoda** [comment]
Could you tell me how you identify React in your build?
Or simply in here: https://hello-world-nrqihmdggp.now.sh

**Comment by lukeed** [comment]
I cleared cache & rebuilt; and it wasn't there 😄 

Thanks for taking care of this 👍 Now I have to investigate if `commons` can be smaller 😉
