### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by geekyme** [zeit/next.js#5328]
# Bug report

## Describe the bug

My app was on nextjs 6.1.2, and I updated to 7.0.0. Then production build will have a runtime error when I access the app. 

```
Super expression must either be null or a function, not undefined
```

## System information
 - OS: Mac
 - Browser: Chrome
 - Version of Next.js: 7.0.0

## Additional context

I am using an internal library, `X` compiled with webpack 4 as well. When I comment it out and build my nextjs app, then the error disappear. Not sure how upgrading nextjs 6.1.2 to 7.0.0 will break my library. 

Issue is very similar to https://github.com/airbnb/react-with-styles/issues/151. In that issue, it was mentioned that adding an option to uglifyjs will help. But not sure if we have that ability to do it here in nextjs.

**Comment by timneutkens** [comment]
I'm not sure what to do with this issue as there is no reproduction. So I'm going to close it as we can't really change anything based on this.

I suspect it might be something in webpack 4 / babel 7, but without a reproduction there is no way to say for sure.

**Comment by geekyme** [comment]
Well, is there at least a way to set the uglify settings `keep_fnames`? It was recommended in airbnb/react-with-styles#151

**Comment by timneutkens** [comment]
Do you run into this only in production builds though? Because we only run uglify in production builds

**Comment by geekyme** [comment]
Yes it is only in a production build, which is why I found the issue really strange.
