### ISSUE TITLE
Authentication (Facebook, Twitter, Google) using external API

### ISSUE THREAD

**Issue by zefexdeveloper** [zeit/next.js#5337]
I have a headless API using express and passport.js with a few strategies for OAuth authentication and also a local strategy for username and password with jwt + cookies. I was wondering how can I use my external API in next.js?
Am I supposed to redirect the user to my API routes for authentication and the API redirects the user back to the client?
I really need to understand the flow and how people usually do that.
Thank you in advance.

**Comment by timneutkens** [comment]
Please post questions on https://spectrum.chat/next-js, as you'll reach more people.
(As per the issue template)
