### ISSUE TITLE
Allow to dismiss default error overlay

### ISSUE THREAD

**Issue by yury** [zeit/next.js#5338]
# Feature request
Allow user to dismiss white error overlay or do not show it all and fallback to html from server.

## Is your feature request related to a problem? Please describe.
This is how  https://nextjs.org looks on webos tv browser:
![e70f9a49-0e2b-4be2-98c3-f2eac8b39bab](https://user-images.githubusercontent.com/5250/46254671-63509300-c49b-11e8-9bdb-7e662dd9e1bb.jpeg)

But before that I can see content from server for some time. [video](
https://youtu.be/Kl7LD-PXS8Q)

## Describe the solution you'd like

1. Do not show error overlay at all.
2. Add dismiss (ok) button to overlay

## Additional context

- browser - latest webos tv default browser.
- simple nextjs app works

**Comment by timneutkens** [comment]
Moved here: https://github.com/zeit/next-site/issues/68
As it seems like an issue with the website.
