### ISSUE TITLE
Multi Language Support with Custom Page Directories

### ISSUE THREAD

**Issue by ITforHome** [zeit/next.js#5348]
I have created a Website using NextJS and React. I want to provide the Website in several languages. To achieve this, I wanted to create in the page folder, subfolders, for example for the English language `/en` , for the German language, `/de` etc.

When a visitor then opens my Website, the correct subfolder is selected based on the public IP:

Example: Request comes from America : the `/pages/en` folder is selected, The request comes from Germany : the `/pages/de` folder is selected etc.

How can I do that? Since I have little experience in NodeJS environments, please show me concrete examples, many thanks...

### System Information:

- Chrome (last Version)
- NextJS Version 7.0.0
- React Version 16.5.2
- React Dom Version 16.5.2

**Comment by popugang** [comment]
In my project i using next-routes
and for each page add :locale 
`urls.forEach(({ file, path }) => routes.add(file, `/:locale${path}`));`

**Comment by popugang** [comment]
example
https://github.com/zeit/next.js/tree/canary/examples/custom-server-express

**Comment by ITforHome** [comment]
@popugang Thanks, I just looked at the example. The following code was used in the `server.js` file:

```js
server.get('/a', (req, res) => {
      return app.render(req, res, '/b', req.query)
    })
```
I already understood how that works. How can I use your code inside there?

**Comment by popugang** [comment]
siteUrl like localhost:3000/de/

    app.get('/:lang/', function(req, res) {
      res.send('lang' + req.params.lang);    
    });

**Comment by ITforHome** [comment]
@popugang Thank you, I'm sorry I might be a little stupid instead, but I still don't know how to use your code right now... My `server.js` looks so far:

```js
const express = require('express')
const next = require('next')
const bodyParser = require('body-parser')
const request = require('request')
const dev = process.env.NODE_ENV !== 'production'
var app = next({ dev })

const handle = app.getRequestHandler()

app.prepare()
    .then(() => {
        
        const server = express()

        //parse application
        server.use(bodyParser.urlencoded({ extended: false }))

        //parse application/json
        server.use(bodyParser.json())

        server.post('/', (req, res) => {
            addEmailToMailChimp(req.body.email, (error, response, body) => {
                // This is the callback function which is passed to `addEmailToMailChimp`
                try {
                    var respObj = {}; //Initial response object
                    if (response.statusCode === 200) {
                        respObj = { success: `Subscribed using ${req.body.email}!`, message: response.body };
                    } else {
                        respObj = { error: `Error trying to subscribe ${req.body.email}. Please try again.`, message: response.body };
                    }
                    res.send(respObj);
                } catch (err) {
                    var respErrorObj = { error: 'There was an error with your request', message: err.message };
                    res.send(respErrorObj);
                }
            });
        })

        server.get('*', (req, res) => {
            return handle(req, res)
        })

        server.listen(3000, (err) => {
            if (err) throw err
            console.log('> Ready on http://localhost:3000')
        })
    })
    .catch((ex) => {
        console.error(ex.stack)
        process.exit(1)
    })
```
Two Questions:
- Where and exactly how do I have to use your code in my file?
- How and where can I use my if query `if (req.body.code === 'DE')` ?

May I ask you to adjust my `server.js` accordingly? I wouldn't ask if I wouldn't need this help... thanks a lot

**Comment by tusbar** [comment]
You can do something like this:

```js
const localizedRouter = new Router()

localizedRouter.get('*', (req, res) => {
  app.render(req, res, `${lang}/${req.params[0]}`, req.query)
})

server.use('/:lang(de|en)', (req, res, next) => {
  req.i18n = {lang: req.params.lang}

  localizedRoutes(req, res, next)
})
```

**Comment by jamuhl** [comment]
there now is also a sample here using react-i18next: https://github.com/i18next/react-i18next/tree/master/example/nextjs

you can enable/disable language usage in paths in config: https://github.com/i18next/react-i18next/blob/master/example/nextjs/config.js#L11

**Comment by timneutkens** [comment]
Going to close this as per @jamuhl's example.

**Comment by ITforHome** [comment]
@jamuhl thank you for the Example, i follow up this and it works now. But i have few more questions about that... 

## 1. Different Names for Pages

How can i use different names for my Pages. For Example, i have a page called `privacy-policy` i can open this page like this:

`http://localhost:3000/en/privacy-policy
http://localhost:3000/de/privacy-policy` 

When i use German as Language, i want to display the PageName in German, in my case:

`http://localhost:3000/de/datenschutz`

How can i do that? 

## 2. SEO

I use the `next/head` Component to implemente SEO in my Application. How can i use it with `i18next`? There are disadvantages of this method?

## 3. Auto-detect Lang

When i open the `index.js`page on `http://localhost:3000` i get `http://localhost:3000` as URL, no matter if german oder english. But when i open the `index.js` page in german, i want to get this URL: `http://localhost:3000/de` or in english: `http://localhost:3000/en`

How can i do that?
Please show me a short detail example, so i can use it in my Code - thanks a lot...

**Comment by jamuhl** [comment]
@ITforHome please open an issue over at https://github.com/i18next/react-i18next so i can take a a look

**Comment by ITforHome** [comment]
@jamuhl please take a look at: https://github.com/i18next/react-i18next/issues/570
