### ISSUE TITLE
Webpack compiled assets disappearing from `.next`

### ISSUE THREAD

**Issue by dextermb** [zeit/next.js#5365]
# Bug report

## Describe the bug

I am attempting to load fonts from a third-party package css file. I do this by pushing a rule into the webpack config:

##### `next.config.js`
```js
module.exports = require('@zeit/next-sass')({
	webpack(config, {}) {
		config.module.rules.push({
			test: /\.(css|svg|eot|ttf|woff|woff2)$/,
			use:  [
				{
					loader:  'file-loader',
					options: {
						name:       'static/fonts/[hash].[ext]',
						publicPath: '/_next'
					}
				}
			]
		});

		return config;
	}
});
```

At first it generates correctly, putting the fonts in `.next/static/fonts` which can then be accessed at `_next/static/fonts` but after a second or so the fonts get removed. I assume this is because it re-compiles differently?

## Expected behavior

I'd expect the rule to be ran again, which would then find the fonts again and keep them in the their directory to be accessed. But it seems that `.next/static/fonts` gets deleted.

## System information
 - OS: OSX
 - Version of Next.js: `^7.0.0`

**Comment by dextermb** [comment]
I've noticed there's a [`next-fonts`](https://github.com/rohanray/next-fonts) package, so I have created a [PR to include SVG fonts](https://github.com/rohanray/next-fonts/pull/4). 

I do not seem to be getting the issue mentioned above by using this package. Although there are only [minor differences in code](https://github.com/rohanray/next-fonts/blob/master/index.js).

Although I have resolved the issue by using this package, I would like to know what was causing the issue in my code.

**Comment by timneutkens** [comment]
It should work in both cases based on the rules you're showing, however on the server (`isServer`) you should probably be using `ignore-loader` instead, so that the file is not compiled twice for nothing.

**Comment by dextermb** [comment]
@timneutkens hmm, okay. I'll have a look at using `ignore-loader`. Not sure what's making it delete the folder then 😅 I'll close this thread so it doesn't block issues with known fixes, but I'll post my findings if I do find out what was causing it
