### ISSUE TITLE
[2.0.0-beta.3] .babelrc breaks build

### ISSUE THREAD

**Issue by Zaiban** [zeit/next.js#538]
Updating to beta 3 broke the build system. Looks like the presets wont load at all, error:
```
> Using .babelrc defined in your app root
> Using "webpack" config function defined in next.config.js.
{ SyntaxError: unknown: Unexpected token (11:13)
   9 |     const styletron = flush();
  10 |     const css = styletron ? styletron.getCss() : null;
> 11 |     return { ...page, css };
     |              ^
  12 |   }
  13 | 
  14 |   render() {

``` 
.babelrc:
```
{
  "presets" : [
    "next/babel",
    "stage-0"
  ]
}
```
Reverting back to beta 2 fixes the issue. Removing .babelrc also fixes it, but then the tests wont work as they depend on babel. I also tried with various preset configs and even with just "next/babel" it still gives the same error.

**Comment by arunoda** [comment]
Seems like you are using a custom webpack config too.
I tried with a sample app and everything works.

Could you send us a sample repo to play with?

**Comment by Zaiban** [comment]
Yea sure, seems like it only affects _document. Here's a minimal reproduction:

https://github.com/Zaiban/next-babelrc-test

**Comment by arunoda** [comment]
Thanks @Zaiban.
This happens when introduced a custom document.
This will be fixed with https://github.com/zeit/next.js/pull/534
