### ISSUE TITLE
Dynamic require on local images disables HMR

### ISSUE THREAD

**Issue by mgershowitz** [zeit/next.js#5381]
# Bug report

## Describe the bug

I have a component that uses a dynamic require on local images and uses  a `url-loader` within the next config. I was experiencing some memory leaks by doing that, but have solved that by running `delete require.cache['path/to/file']`. This works great for dynamically loading the images, however after the image loads, all of the components related to the dynamically importing one will no longer trigger the HMR. If I restart the server, a change to any of these components will trigger it once, but then it becomes disabled. Am I reaching some sort of memory cap by dynamically requiring these images and is there a way to more efficiently import them

## To Reproduce

This is what my dynamic require looks like in my component. It requires a localized image path, deletes from the `require.cache`, and then returns the data to an `img` tag in the `render`
```
    const filename = `${localizedSrc.substr(2)}`;
    const src = this.props.isSVG ? `./${filename}` : `./assets/content/${filename}`;
    const imageData = require(`${src}`);
    const key = require.resolve(`${src}`);

    // Stop the server from repeatedly caching large images that make it run out of memory
    if (!require.cache[key]) {
      throw new AppError('Cache data for this image does not exist', {
        key,
        src
      });
    }

    delete require.cache[key];

    return imageData;
```

and this is how I'm handling images in the `next.config`
```
config.module.rules.push({
      test: /\.(jpe?g|png|svg|gif|ico)$/,
      use: [
        {
          loader: 'url-loader',
          options: {
            fallback: 'file-loader',
            publicPath: `/_next/static/images/`,
            outputPath: `${isServer ? '../' : ''}static/images/`,
            name: '[name]-[hash].[ext]'
          }
        }
      ]
    });
```
## Expected behavior
I want to be able to require images from a dynamic path and then allow for HMR to continue function as I develop locally

## System information
 - Version of Next.js: 6.0.3

**Comment by timneutkens** [comment]
Not really sure what we can change in Next.js to help with this, so I'm going to close the issue.
