### ISSUE TITLE
snapshot format for style is weird (styled-jsx)

### ISSUE THREAD

**Issue by oahehc** [zeit/next.js#5387]
# Examples bug report

## Describe the bug
the snapshot for style should be a string, but be formatted as an object.

## To Reproduce
1. use [with-jest](https://github.com/zeit/next.js/tree/canary/examples/with-jest) example
2. split style to `styles.js` and adjust pages/index.js as below
```
import styles from './style';

export default () => (
  <div>
    <p>Hello World!</p>
    <style jsx>{styles}</style>
  </div>
)

```
3. use enzyme for snapshot test
```
const app = shallow(<App />)
expect(app).toMatchSnapshot()
```

## Expected behavior
originally, the snapshot for style should be a string as below
![image](https://user-images.githubusercontent.com/13633490/46568800-c3ed3d80-c97d-11e8-91a8-24de06663b34.png)

## Screenshots
but now became an object
![image](https://user-images.githubusercontent.com/13633490/46568765-301b7180-c97d-11e8-9777-13d0168fcc66.png)

## System information
 - OS: macOS
 - Version of Next.js: 7.0.1

**Comment by timneutkens** [comment]
Could you post this on github.com/zeit/styled-jsx.
