### ISSUE TITLE
Plugins presets not applied to defaultLoaders.babel.options

### ISSUE THREAD

**Issue by martpie** [zeit/next.js#5393]
# Bug report

I am not sure if this a Next problem, a Next plugin problem, or a user problem (or maybe a feature?). I am really open to any feedback.

## Describe the bug

Similar to #5288. Found when debugging https://github.com/martpie/next-plugin-transpile-modules/issues/1

It looks like Next plugins's presets (like `next-typescript`) are not added to next.config.js's `options.defaultLoaders.babel.options`. 

I have not a lot of knowledge on how Next's build system actually work, but it _looks_ wrong to me. Because of this, Babel won't transpile specified packages in node_modules.

The two solutions (https://github.com/martpie/next-plugin-transpile-modules/issues/1#issuecomment-427749256 and https://github.com/martpie/next-plugin-transpile-modules/issues/1#issuecomment-425839242) are in my opinion lame, because the user should not have to worry about it.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `git clone git@github.com:martpie/monorepo-typescript-next-the-sane-way.git`
2. `cd monorepo-typescript-next-the-sane-way`
3. `npm install`
4. `cd website`
5. **remove `babel.config.js`**
6. `npm install & npm run dev`

Babel will throw an error because it cannot transpile files.

To fix it, you can re-enable the custom `babel.config.js` or add the following in your `next.config.js`: 

```
...
webpack(config, options) {
   ...
  options.defaultLoaders.babel.options.presets = [
    '@zeit/next-typescript/babel'
  ];
}
```

or create a `babel.config.js` with a similar content

## Expected behavior

The user should not have to write a (potentially error prone) `babel.config.js` or modify the Babel loaders to have this working.

Do you think this should be handled by this plugin or by Next.js (genuine question)? If this is a plugin issue, do you see how this could be automated (how could I get all the presets/plugins used by a user in `next.config.js`?

## System information
 - OS: n/a
 - Browser (if applies) n/a
 - Version of Next.js: 7.0.1

## Additional context

n/a

**Comment by martpie** [comment]
Any news on this? I would gladly submit a PR if I knew where to start (and if I knew if it is a bug or an intentional behavior)

 (cc @timneutkens)

**Comment by timneutkens** [comment]
I'm not really sure I understand the issue here, when adding next-typescript you're required to add the preset to your .babelrc, it might sound nice having Next.js handle that for you automatically, however then you run into issues with other tools that use babelrc / babel to compile being inconsistent, eg jest.

**Comment by timneutkens** [comment]
🙌

**Comment by martpie** [comment]
Then I think we can close this 👍

**Comment by timneutkens** [comment]
🙏 Lmk if you run into any other issues.
