### ISSUE TITLE
Errors in getInitialProps handles differently in _app.js compared to other pages

### ISSUE THREAD

**Issue by lydell** [zeit/next.js#5400]
# Bug report

## Describe the bug

Rejecting `static async getInitialProps` in _app.js is handled differently compared to other pages.

## To Reproduce

Repro repo: https://github.com/lydell/next.js-error-handling-bug

1. Clone the repo.
1. `npm ci`
2. `npm run dev`
3. Visit <http://localhost:3000>
4. `pages/index.js` causes an error, which Next.js handles as expected. The
error overlay is rendered in development and the 500 page in production.
5. Uncomment the indicated line in `pages/_app.js`.
6. Visit <http://localhost:3000>
7. `pages/_app.js` causes an error, which Next.js handles in a different way: It
just responds with “Internal Server Error” (both in development and production).

## Expected behavior
Render the error overlay in development and the 500 page in production, like on other pages.

## Screenshots

Page error:
![screenshot from 2018-10-08 12-32-49](https://user-images.githubusercontent.com/2142817/46604472-aa233600-caf6-11e8-81ae-ebdc43f32eee.png)

_app.js error:
![screenshot from 2018-10-08 12-33-04](https://user-images.githubusercontent.com/2142817/46604492-bdce9c80-caf6-11e8-8093-adbb1f09d4bc.png)

## System information
 - OS: Ubuntu 18.04
 - Version of Next.js: 7.0.2-canary.8

**Comment by sheerun** [comment]
It might be because _app.js is used for rendering error page as well..

**Comment by lydell** [comment]
Ah, I see, that might very well be the case. If so, I think it helps if I clarify my use case.

I load some data from an API in `getInitialProps` of `_app.js`, because I need it on _all_ pages. I don't bother handling the error of that request – if it fails, there's not much to show at all on the page – and instead let Next.js catch errors and display the error page.

Now I realize that I don't want to load the data from the API when rendering the error page. Hadn't thought about that before.

- Is it a bad practice to load data in `getInitialProps` of `_app.js`?
- Should I handle the error myself?
- Is there a way to _not_ load data for the error page (`_error.js`)?

**Comment by lydell** [comment]
I found a way.

```diff
diff --git a/pages/_app.js b/pages/_app.js
index 6e12f35..4537c5f 100644
--- a/pages/_app.js
+++ b/pages/_app.js
@@ -1,19 +1,28 @@
 import React from 'react'
 import App, { Container } from 'next/app'
+import ErrorComponent from './_error'
 
 export default class MyApp extends App {
   static async getInitialProps({ Component, router, ctx }) {
-    // Uncomment this and notice the difference compared to causing and error in
-    // pages/index.js. Here, the server just responds with “Internal Server
-    // Error”.
-    // await Promise.reject(new Error("_app.js error"))
-
     let pageProps = {}
 
     if (Component.getInitialProps) {
       pageProps = await Component.getInitialProps(ctx)
     }
 
+    // Do as little as possible when rendering the error page, in case something
+    // in this `getInitialProps` function fails. We don't want to error on the
+    // error page, so to speak.
+    if (Component === ErrorComponent) {
+      return { pageProps }
+    }
+
+    // Imagine doing an API request here: If that fails, we don't want that to
+    // fail the error page from rendering too. Besides, we probably don't want
+    // to make the API call on the error page in the first place.
+    await Promise.reject(new Error("_app.js error"))
+
+
     return { pageProps }
   }
```

Full code here: https://github.com/lydell/next.js-error-handling-bug/tree/fix

If we're rendering the error page, I do as little as possible in _app.js' `getInitialProps`.

Maybe this is only a docs issue, then?

**Comment by timneutkens** [comment]
@ijjk I think we need to handle a throw coming from rendering the error component (as a final handler).
