### ISSUE TITLE
 Array.prototype.some() returns " /_next/on-demand-entries-ping is not a function"

### ISSUE THREAD

**Issue by Hocoh** [zeit/next.js#5401]
# Bug report
I'm using Next with the custom server. I wished to check if some value exists in a pathArray in order to trigger the custom route process. Sadly the console returns me :
## Describe the bug

> Array.prototype.some() returns " /_next/on-demand-entries-ping is not a  function"

So I don't know what happens. 
## To Reproduce
Here my snippet.js: 

```
const array = ["a","b","c"]
app.prepare().then(() => {
  createServer((req, res) => {
    // Be sure to pass `true` as the second argument to `url.parse`.
    // This tells it to parse the query portion of the URL.
    const parsedUrl = parse(req.url, true)
    const { pathname, query } = parsedUrl

    if (array.some(pathname))  {
      app.render(req, res, '/post', query)
    } 
```

When you will run "node server.js" the console will return the above-mentioned message.

**Comment by timneutkens** [comment]
`.some` takes in a matcher function, not the value itself: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some#Parameters
