### ISSUE TITLE
Auto-Inject of CSS breaks AMP pages' validity

### ISSUE THREAD

**Issue by SahajR** [zeit/next.js#5407]
# Feature request
Allow devs to optionally opt out of injecting the CSS file into the Head

## Is your feature request related to a problem? Please describe.
[AMP](https://www.ampproject.org/learn/overview/) pages do not allow custom CSS. So when Next.js injects the CSS into the Document, the validity of the AMP page breaks.

I have an article page that conditionally render them as an AMP page. Since Next.js injects the CSS anyways, the only workaround I have currently is to extend the `Head` component and return `null` in its `getCssLinks` function.

```js
class AMPHead extends Head {
    getCssLinks = () => null
}
```

This works, but controlling this via a prop would be more convenient

## Describe the solution you'd like
Add a prop (something like `nocss`) in the `Head` component to conditionally render the CSS files

## Describe alternatives you've considered
Extending `Head` as shown above

## Additional context
Not required

**Comment by timneutkens** [comment]
Closing this in favor of the AMP support we're working on: https://github.com/zeit/next.js/milestone/5
