### ISSUE TITLE
Showcase: Material-UI

### ISSUE THREAD

**Issue by oliviertassinari** [zeit/next.js#5409]
### Request to be added to the showcase on nextjs.org

- Name of company: Material-UI
- Url: https://material-ui.com/
- Testimonial: Next.js is a great fit for building **documentation websites**. It can help in achieving insane performance:

![material-ui com_](https://user-images.githubusercontent.com/3165635/46631254-2e9da500-cb47-11e8-8178-ad69012193ad.png)
*800x460*

Speaking of performance, https://developers.google.com/speed/pagespeed/insights/
- *First Contentful Paint (FCP)*
- *DOM Content Loaded (DCL)*

**Bootstrap**
![capture d ecran 2018-10-08 a 22 05 41](https://user-images.githubusercontent.com/3165635/46630985-52acb680-cb46-11e8-9463-5b5096832fb6.png)

**React (Gatsby)**
![capture d ecran 2018-10-08 a 22 06 35](https://user-images.githubusercontent.com/3165635/46631022-73750c00-cb46-11e8-84d2-f270fec90ef3.png)

**Material-UI (Next.js)**
![capture d ecran 2018-10-08 a 22 05 00](https://user-images.githubusercontent.com/3165635/46630961-3872d880-cb46-11e8-906a-c5eae5fa80ac.png)

**Comment by ptdede** [comment]
Hi! I use material-ui and i love it. But, I have a question. Do you use `next export` for improving the web performance? or you serve it like usual react app?

**Comment by oliviertassinari** [comment]
This is a static website. I'm also using next for a dynamic one. You can see it in https://www.onepixel.com.

**Comment by quietshu** [comment]
The showcase has been added in https://github.com/zeit/next-site/pull/77, you will see it on the website soon 😉
