### ISSUE TITLE
export not found in file that it exists in

### ISSUE THREAD

**Issue by callensm** [zeit/next.js#5423]
# Bug report

## Describe the bug
I have a Typescript `interface` that is exported from a file for other uses, but when I compile and run in `dev` mode, I get: `"export 'ISnippetProps' was not found in './Snippet'`.

This warning should not be occurring at all as the `interface` _clearly_ is being exported within the file in question.

## Expected behavior
This should not cause a compile warning.

## Screenshots
![image](https://user-images.githubusercontent.com/13121516/46746415-09ab4e00-cc7d-11e8-94d2-67b37c4f90f9.png)

![image](https://user-images.githubusercontent.com/13121516/46746474-2051a500-cc7d-11e8-9cf5-6de508e81d92.png)

## System information
 - OS: macOS
 - Browser (if applies) Chrome
 - Version of Next.js: 7.0.1

**Comment by timneutkens** [comment]
I’m going to close this as it’s not reproducible.
