### ISSUE TITLE
with-apollo example errors in IE11

### ISSUE THREAD

**Issue by mintyfloss** [zeit/next.js#5426]
# Examples bug report

## Example name
`with-apollo`

## Describe the bug
Loading the `with-apollo` example in IE11 has the errors below:

```
SCRIPT438: Object doesn't support property or method 'assign'
File: _app.js, Line: 39168, Column: 17
```

I added a polyfill for `Object.assign`, and I get another error:

```
SCRIPT5007: Unable to get property 'get' of undefined or null reference
```

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Load `with-apollo` in IE11
2. Should see the error about `Object.assign`
3. Add `client/polyfills.js` file

    ```js
    // client/polyfills.js
    import "core-js/fn/object/assign";
    ```
4. Add `next.config.js` file

    ```js
    // next.config.js
    const withTM = require("next-plugin-transpile-modules");

    module.exports = {
      transpileModules: ["react-apollo"],
      webpack: config => {
        const originalEntry = config.entry;

        config.entry = async () => {
          const entries = await originalEntry();

          if (
            entries["main.js"] &&
            !entries["main.js"].includes("./client/polyfills.js")
          ) {
            entries["main.js"].unshift("./client/polyfills.js");
          }

          return entries;
        };

        return config;
      }
    };
    ```
5. `Object.assign` error is gone but now the browser console displays the error `Unable to get property 'get' of undefined or null reference`
6. App is stuck in loading state

<img width="397" alt="screen shot 2018-10-10 at 9 21 50 pm" src="https://user-images.githubusercontent.com/885453/46776722-887ea600-ccd2-11e8-9465-e164914c8e6c.png">

## Expected behavior
`with-apollo` example should be fully functional and display the fully loaded state with no console errors in IE11.

## Screenshots
What I'm seeing after polyfilling:

<img width="1679" alt="screen shot 2018-10-10 at 9 25 19 pm" src="https://user-images.githubusercontent.com/885453/46776868-1f4b6280-ccd3-11e8-87cf-ddcaaad50d47.png">

## System information
 - OS: macOS
 - Browser: IE11
 - Version of Next.js: 7.0.1

## Additional context

I also tried transpiling `react-apollo` and `apollo-boost` using `next-plugin-transpile-modules` but that didn't help.

**Comment by barnslig** [comment]
I experience the same bug. As a temporary workaround I installed `apollo-cache-inmemory@1.2.10` and manually used in in `init-apollo.js` like this:
```js
import { ApolloClient, HttpLink } from 'apollo-boost';
import { InMemoryCache } from 'apollo-cache-inmemory';
...
```

The problem seems to appear from `apollo-cache-inmemory@1.3.0` and newer so I guess it would be a good idea to open an issue [at their project](https://github.com/apollographql/apollo-client/issues).

**Comment by oliviertassinari** [comment]
https://github.com/apollographql/apollo-client/issues/4024

**Comment by timneutkens** [comment]
Let's close this then, as it's tracked in apollographql/apollo-client#4024
