### ISSUE TITLE
No release notes anymore

### ISSUE THREAD

**Issue by tusbar** [zeit/next.js#5430]
Hey,

Not sure if they were automated before, but [releases](https://github.com/zeit/next.js/releases) do not contain any description since the lerna switch.

I use [lerna-changelog](https://github.com/lerna/lerna-changelog) for most of my repos and automatically update the release on GitHub whenever a tag is pushed with a [CircleCI job](https://github.com/tusbar/circleci-samples/blob/master/.circleci/config.yml#L127-L139)

**Comment by klujanrosas** [comment]
From what I've seen, the changelog notes are added after a while each time there's a release.
