### ISSUE TITLE
doesn't work with file-loader

### ISSUE THREAD

**Issue by iamcco** [zeit/next.js#5438]
# Bug report

## Describe the bug

use file-loader but doesn't create the file to output directory when import file in _Document.jsx

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```bash
git clone https://github.com/iamcco/test-file-loader.git
cd test-file-loader
yarn build
```

next.config.js

```javascript
const withSass = require('@zeit/next-sass')

module.exports = withSass({
  pageExtensions: ['jsx'],
  webpack (config) {
    const { module = {} } = config
    return {
      ...config,
      module: {
        ...module,
        rules: [
          ...(module.rules || []),
          {
            test: /\.(png|woff|woff2|eot|ttf|gif|jpg|ico|svg)$/,
            loader: 'file-loader',
            options: {
              name: '[name]_[hash].[ext]',
              publicPath: `/_next/static/files`,
              outputPath: 'static/files'
            }
          }
        ]
      }
    }
  }
})
```

the `favicon_1195c05fc68d40d09ebbf24865a55b91.ico` files should create at `.next/static/` but it create at `.next/server/static/`

## Expected behavior

the `favicon_1195c05fc68d40d09ebbf24865a55b91.ico` files should create at `.next/static/`

## Screenshots
![image](https://user-images.githubusercontent.com/5492542/46865449-34013500-ce50-11e8-8fb2-a05308e3a9f7.png)

## System information
 - OS: [e.g. macOS]

**Comment by timneutkens** [comment]
_document is just for creating the html structure. Use _app.js for app logic.

**Comment by iamcco** [comment]
@timneutkens if i move to _app，the file will be create twice

```
.next/server/static/files
.next/static/files
```

what's the difference
