### ISSUE TITLE
Importing CSS files?

### ISSUE THREAD

**Issue by matthewmueller** [zeit/next.js#544]
Sometimes it's nice to break out your CSS into a separate `.css` file. I've tried to do the following:

```
pages/
└── index
    ├── index.css
    ├── index.js
    └── component.js
```

Then in the index.js, I've tried to do:

```js
import css from './index.css'
```

And in next.config.js:

```js
module.exports = {
  webpack: function (config) {
    config.module.loaders = (config.module.loaders || []).concat({
      test: /\.css$/, loader: 'raw'
    })
    return config
  }
}
```

But unfortunately, it keeps giving me:

```
 ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* ./index.css
```

Seems like it's not resolving to the right place for some reason, the local `component.js` works though via `import component from './component.js'`, so I'm not sure what's going on here.

**Comment by nkzawa** [comment]
You mean this doesn't work on server ?
I thinks we don't have workaround for this yet. cc @arunoda

**Comment by matthewmueller** [comment]
oh right, i guess there'd need to be a way for the webpack config to work on both sides in order for this to work.

**Comment by MikeDigitize** [comment]
I've got a kind of ballpark similar issue in that I just can't seem to get Next to play nicely with CSS or SASS. I have a `components` directory with standard React components in that I import into my pages but whenever I attempt to import in SASS (or CSS) files I get a ~"you need to use the appropriate loader for this file" type error message. 

Generally in React I import SASS files and have Webpack compile using style, css and sass loaders. I've attempted to add these to the `next.config.js` file (and NPM installed them) but still get the same error message.

My `next.config.js` file:

```javascript
module.exports = {
  webpack: (config, { dev }) => {
    config.module.rules.push({ test: /\.scss$/, loader: ['style-loader', 'css-loader', 'sass-loader'] });
    return config;
  }
}
```
Sorry if these questions sound dumb or I've missed something obvious in the docs that spell out the answers to them, but if anyone has a working example of importing / compiling SASS (or at the least CSS) into a component or a page with whatever's needed to add to the `next.config.js` to load / compile them, I'd massively appreciate it. Thanks!

**Comment by spacedragon** [comment]
I'm using [css-modules-require-hook](https://github.com/css-modules/css-modules-require-hook)
to make css work.

**Comment by kpuputti** [comment]
@spacedragon Do you have an example how to integrate css-modules-require-hook with Next.js? I'm having problems with getting it working.

**Comment by MikeDigitize** [comment]
I'm still having issues with getting SASS to compile if anyone could shed some light on how to do this or just import a CSS file within Next it would be appreciated (via a code example).

**Comment by spacedragon** [comment]
added my solution for css here  [https://github.com/spacedragon/next-css-load-example.git](url)
which is not so perfect.  Hope someone can find better one.

**Comment by MikeDigitize** [comment]
Interesting that the README file has been updated to remove the SVG loader example and changed to say adding loaders for file like SVG, CSS and SASS is discouraged. I'm not sure why inlined CSS is OK but imported CSS isn't but I'm sure there's a good reason why. I'm just currently uncertain about the best strategy to handle none JS defined / inlined CSS and SASS.

**Comment by kpuputti** [comment]
@MikeDigitize See [comment on #627](https://github.com/zeit/next.js/issues/627#issuecomment-270039476) and #638 .

**Comment by viktorbezdek** [comment]
It's actually possible and pretty easy to process styles on server side.

**directly in node:**
```js
require.extensions['.css'] = function(file) {
    console.log(file.id)
    return;
}
```

**via babel register:**
```js
// from https://babeljs.io/docs/core-packages/babel-register/
require("babel-register")({
  // Optional ignore regex - if any filenames **do** match this regex then they
  // aren't compiled.
  ignore: /regex/,

  // Ignore can also be specified as a function.
  ignore: function(filename) {
    if (filename === '/path/to/es6-file.js') {
      return false;
    } else {
      return true;
    }
  },

  // Optional only regex - if any filenames **don't** match this regex then they
  // aren't compiled
  only: /my_es6_folder/,

  // Setting this will remove the currently hooked extensions of .es6, `.es`, `.jsx`
  // and .js so you'll have to add them back if you want them to be used again.
  extensions: [".es6", ".es", ".jsx", ".js"]
});
```

**via webpack loaders:**
- ignore loader - https://www.npmjs.com/package/ignore-loader
- isomorphic-style-loader - https://www.npmjs.com/package/isomorphic-style-loader

I personally use isomorphic-style-loader as it allows me to inline critical CSS while rendering on server. Hot reloading and other DX related stuff works too. I'm not really fan of CSS in JS as it complicates using 3rd party components and and somehow takes away the C from CSS.

**Comment by noeljackson** [comment]
@viktorbezdek Have you successfully used isomorphic-style-loader with next.js?

**Comment by viktorbezdek** [comment]
@noeljackson Not really, but I intend to. Next.js looks promising and could save me lot of time if I make it work. Will look into it in next one or two weeks and submit pull request if I'm successful.

**Comment by noeljackson** [comment]
@viktorbezdek I will put a bounty on this one, as it's really crucial to a project I'm working on. I know I'm not inept, but I do not understand how to debug the babel transformations enough to figure this out. I've tried permutation of these ideas and nothing works 100%. I have been able to get raw-loader to pull in a data-encoded stylesheet using babel-plugin-webpack-loaders, but none of the style loaders work. Thanks for chiming in! :) Much appreciated.

**Comment by pencilcheck** [comment]
Is there a solution to this? I would like to see a solution so I don't have to include css globally.

**Comment by matthewmueller** [comment]
FWIW, I've just been putting my CSS files in the `/static` folder. Not great colocation, but not a huge deal either.

**Comment by viktorbezdek** [comment]
There will be a solution. I just didn't manage to finish it. I've locally very first prototype which seems to work, however it needs few hours to be finished. I'm pretty sure I'll be done after weekend. Stay tuned.

**Comment by viktorbezdek** [comment]
@matthewmueller You are using CSS modules?

**Comment by abelovic** [comment]
@viktorbezdek Thanks for working on this! CSS Modules support (or similar) is important for this project IMO. Styled jsx, is ok for simple situations but is hard to read for heavily styled components.

Would a babel plugin like this be an option (server side as well)? https://github.com/gajus/babel-plugin-react-css-modules

I tried to get this to work but but no luck :/

**Comment by stephenmathieson** [comment]
I got CSS modules sort of working with [`babel-plugin-css-modules-transform`](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform). See my hacky example in [my fork](https://github.com/stephenmathieson/next.js/tree/add/css-modules-example).

The downside is you have to kill the server & restart it every time you make a change to the CSS.

**Comment by mquandalle** [comment]
Some React components expose default styling though a `import`able static resource. For instance to import the default style of https://github.com/react-component/slider one would use:

```es6
import 'rc-slider/assets/index.css';
```

It sure is possible to copy paste this stylesheet in the `static/` directory but it won't stay in sync with the upstream style on a future component update, and it doesn't match what this component documentation recommend.

**Comment by rauchg** [comment]
The problem is that those CSS files introduce global effects. We need to be able to _capture_ the CSS and put it inside the React lifecycle, so that it gets unmounted, server-rendered, etc.

Many libraries do that, but I don't think it's a good pattern.

**Comment by mquandalle** [comment]
I'm not familiar with Zeit Next internals, but could some static analysis of the `import` be used to register/capture the CSS?

**Comment by rauchg** [comment]
We could, but it would be really strange. Similar to something that's outside of `render()` magically inserting itself inside your component lifecycle.

**Comment by auser** [comment]
Well... I just spent a bit too much time trying to hack CSS in here, BUT I landed on a solution that works (for me). Admittedly, it's a hack, but hot reloading works and so does server-side building.

Using (_shudder_) gulp, with this gulpfile (https://gist.github.com/auser/25e88e39d83413773c01f4c000ec2806) all `**/*.scss` files get concatenated together and shoved into a `Styles` component which I mount on the page as a "normal" element.

Hope this helps someone else until we can get true postcss support in next.

**Comment by brycejacobs** [comment]
Thanks for the hack @auser, I've been looking at the webpack config all day with no luck!

**Comment by auser** [comment]
Yes and no... I just use the `.scss` extension as a way to differentiate pure css files from pre-compiled ones. Since postcss (with `precss`) mimics sass well enough, I don't have one. Feel free to edit for yourself with a sass parser.

**Comment by bassbump** [comment]
Seems like that is currently the best solution, using gulp to compile css file and build it inline or just even in /static if you don't mind not having hot reloading.

**Comment by davibe** [comment]
I have been working on this

https://github.com/davibe/next.js-css-global-style-test

Please help me test and PRs are welcome

**Comment by iamstarkov** [comment]
@davibe thanks for your demo and babel-plugin-wrap-in-js

**Comment by khrome83** [comment]
In the example I see use of a CSS file, and a SCSS file. Do you know if this would work with postcss & cssnext?

**Comment by davibe** [comment]
@khrome83  I don't see why not, I think its just a matter of adjusting .babelrc and next.config.js

**Comment by tgoldenberg** [comment]
@davibe I found that I was unable to deploy my app based on your configuration. The build was unable to read `next/babel` in the `.babelrc` file. I submitted an issue, but I'm really hopeful that a solution emerges from all this. Missing the ease of `import file.css` from `create-react-app`, but I know there must be a solution coming :)

**Comment by rauchg** [comment]
The solution I want is likely along these lines:

https://github.com/zeit/styled-jsx/pull/100#issuecomment-277133969

We *might* support importing `.css` (by means of simply transpiling it into a module that exports a string) (and likewise we might support `.svg` by transpiling it into a pure react component)

**Comment by stephenmathieson** [comment]
> and likewise we might support .svg by transpiling it into a pure react component

This is a pretty simple trick. I'll create a basic example showing how I handled this in another project =)

**Comment by satazor** [comment]
Based on @davibe sample I've created https://github.com/moxystudio/next.js-style-loader that will hopefully ease out adding css files into next.js projects.

It supports vanilla css, `css-loader`, `postcss-loader`, `sass-loader` and possibly others. Note that when css-loader is used, its `url` option must be set to `false` beucase next.js images must live `/static`. You will find all this information in the README.

Enjoy and please give me feedback!

**Comment by pencilcheck** [comment]
Thanks for the repo! It worked for importing the css files. I am trying blueprintjs and it seems like the css is loading correctly! However the @font-face rule that the css is including doesn't seems to work. :\

**Comment by satazor** [comment]
@pencilcheck yes you must use paths pointing to /static, perhaps I will make that more clear in the README.

**Comment by pencilcheck** [comment]
Is there any workaround regarding relative path included in the css files such as fonts atm? Or I simply have to copy the whole font files and css into static folder in order for it to work?

**Comment by satazor** [comment]
@pencilcheck the CSS files can stay outside of static. Your images and fonts must be inside static and you reference them with `/static/file`.

**Comment by pencilcheck** [comment]
I get it. However I'm using blueprint, which is an npm package, I would like to be able to not have to modify any files inside node_modules.

**Comment by satazor** [comment]
@pencilcheck That's not possible unfortunately. next.js is very strict in how it handles images and other assets. Lets not pollute this conversation and please create an issue in next-style-loader repo if you may.

**Comment by davibe** [comment]
@tgoldenberg can you describe the problem better or tell me how to reproduce ? please refer to my repository. It's easyer for me to track issues there.

**Comment by tgoldenberg** [comment]
@davibe, it ended up being a problem using `yarn` over `npm install`. Yarn was throwing some inexplicable errors, but once I removed it the example worked fine in production.

**Comment by thomaslindstrom** [comment]
I just spent 4 hours trying to set this up and thought it might be of interest for anybody looking to save some time. It applies styles automatically, runs the CSS through PostCSS and gives you local module names from `css-loader`. The lack of the latter was a major deal breaker for me in the current state of the example.

*component.js*
```js
import React from 'react';
import stylesheet from './styles.css';

const [css, className] = stylesheet;
const Component = () => (
    <p className={className.paragraph}>bazinga</p>
);
```

*.bashrc*
```
{
    "presets": [
        "next/babel"
    ],
    "plugins": [
        ["wrap-in-js", {
            "extensions": ["css$"]
        }]
    ]
}
```

*next.config.js*
```js
module.exports = {
    webpack: (config) => {
        config.module.rules.push(
            {
                test: /\.css$/,
                use: [
                    {
                        loader: 'emit-file-loader',
                        options: {
                            name: 'dist/[path][name].[ext]'
                        }
                    },
                    {
                        loader: 'raw-loader'
                    },
                    {
                        loader: 'val-loader'
                    },
                    {
                        loader: 'exports-loader',
                        options: {
                            0: 'exports[0][1]',
                            1: 'exports.locals'
                        }
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                            minimize: true
                        }
                    },
                    {
                        loader: 'postcss-loader'
                    }
                ]
            }
        );

        return config;
    }
};
```

**Comment by jozanza** [comment]
I came up with a solution myself, which is very similar to what @satazor posted higher up in the thread: https://github.com/jozanza/next-css-json-loader.

Just add a few lines to your `next.config.js`:

```js
module.exports = {
  webpack: config => {
    config.module.rules.push({
      test: /\.css$/,
      loader: 'emit-file-loader',
      options: {
        name: 'dist/[path][name].[ext]',
      }
    }, {
      test: /\.css$/,
      loader: 'babel-loader!next-css-json-loader',
    });
    return config;
  },
};
```

Styles are imported as js objects so it's very easy to use with `glamor` and similar solutions:

```js
// .css files now conveniently expose all styles as js objects
import styles from 'some-package/styles.css';
import { css } from 'glamor';
// ...
<div {...css(styles)}>
  this is a nice box. 
</div>
```

Cheers! 🍻 :)

**Comment by kristojorg** [comment]
Is there a way to make this work for importing markdown files as strings? I am currently using raw-loader, but as it is a webpack plugin it doesn't work on the server.

**Comment by khrome83** [comment]
@kristojorg

I just wrote a babel plugin for markdown import. On my mobile right now, but if you view my GitHub you will see it.

**Comment by rauchg** [comment]
@khrome83 that sounds awesome. Looking forward to trying it out

**Comment by kristojorg** [comment]
Thank you @khrome83! I'll give it a shot

**Comment by khrome83** [comment]
I had to do this really quickly, so I did not update the readme. But you just include it as a babel plugin, and then use 

import File from 'File.md';

**Comment by kristojorg** [comment]
I got it to work, thank you !! Very helpful

**Comment by davibe** [comment]
This is offtopic but since the issue is closed i feel free to elaborate :)

For markdown there are 2 things you can do.

(1)
One is to include the markdown file as a string and then compile it to html at runtime. You can do this using the generic [`wrap-in-js` babel loader](https://github.com/davibe/babel-plugin-wrap-in-js) registering it for the markdown file extension just like it is used in the next.js example [`examples/with-globa-stylesheet/.babelrc`](https://github.com/zeit/next.js/blob/master/examples/with-global-stylesheet/.babelrc) for css.

(2)
Another thing you can do is to compile markdown at transpilation time using [markdown-in-js](https://github.com/threepointone/markdown-in-js)
This can be more interesting in some scenario because the markdown document is already pre-rendered therefore at runtime it is faster (it just executes js). Also, the library allows you to injiect custom React components. Unfortunately in this case you have to write markdown inline in your `source.js` [like this](https://github.com/davibe/next.js-markdown-in-js-example).

If you pick (2) also know that there is an atom plugin providing syntax hilight for markdown-in-js syntax and it's called `language-markdown-in-js`

**Comment by kristojorg** [comment]
@davibe thank you for the tip! I would rather the markdown parsed as build time, but the only problem I have with markdown-in-js is escaping the backticks while composing :(. Maybe I should try importing as string using babel and then feeding that to markdown-in-js?

**Comment by khrome83** [comment]
@kristojorg

There are out her markdown renders. The reason I wrote my plugin was the same thing. I pull markdown as a string, then I run that through react-markdown. This works increasingly well because I can pass in react components to represent markdown render pieces, like List component to handle all lists. Works good with Styled JSX.

**Comment by lenny0702** [comment]
Is there any update on this? Through the comments above, I see there is still no perfect solutions currently.

Is it possible to have a example using isomorphic-style-loader - https://www.npmjs.com/package/isomorphic-style-loader?

That would be perfect!

**Comment by Yuripetusko** [comment]
Anyone have a solution for when importing a react component from npm package that in turn imports .css or .scss file? so basically transpiling files that are imported from node_modules

**Comment by cr101** [comment]
I've been using Create-React-App (CRA ) for a few weeks but today I came across Next.js and I got really excited because CRA doesn't currently support server-side rendering (SSR) which is a real shame.
I'd love to switch to Next.js for its SSR support out of the box but not having support for a CSS Preprocessor like SASS is holding me back.
[CRA has great support for SASS and LESS](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc).
Has anyone found a way to integrate a CSS preprocessor?

**Comment by dakt** [comment]
Agreed with cr101, not having a support for CSS/SASS means I have to throw out css frameworks like foundation which is not an option for me.

**Comment by tgoldenberg** [comment]
I was using the repo provided by @davibe but he is no longer maintaining it, and the latest build [breaks with the solution he had](https://github.com/davibe/next.js-example-with-global-stylesheet/issues/8). 

Would love if someone has found a fix for this. Updating to 2.4.1 was absolutely necessary due to the security bug, so I don't have the option of going back down.

**Comment by dvakatsiienko** [comment]
@Yuripetusko @cr101 @tgoldenberg Absolutely agree. I think honestly that next is really awesome to be able to work out of the box. Everything is okay even hard-coded structure (like mandatory `/pages` directory, `/static` etc.). But totally unsupported `scss` modules breaks entire thing for us. We have a very complex `scss` structure with automatic breakpoints and aspect ratio recalculation of everything. We worked so hard to make our structure so perfect. Next is great be we can't just throw out all the `scss` stuff that we have at the moment of being. Unsupported `scss` is the only but the most crucial thing that stops us from migration to this beautiful tool.

**Comment by dvakatsiienko** [comment]
Actually, #1615 - there is some action going on. @timmywil is trying to setup`isomorphic-style-loader` to work with `next`. Everyone who interested is welcome to join and participate.

**Comment by almeynman** [comment]
I tried every solution, which this thread points to, however could make any of them work. So I decided to try to make my own attempt and I have documented it [here](https://medium.com/@almasakchabayev/next-js-and-css-modules-37e785a98bb0)

**Comment by dvakatsiienko** [comment]
@almeynman thank you! definitely going to see at your approach! 
By the way, I've managed to make `scss` modules work by following [this](https://github.com/zeit/next.js/tree/v3-beta/examples/with-scoped-stylesheets-and-postcss) example. All I've done is added `sass-loader` and enabled sourcemaps.

**Comment by mocheng** [comment]
I managed to make `next.js` suport CSS (even SCSS) in this way.

First, in `next.config.js` , tweak webpack config by adding given loaders and a `DefintPlugin` instance.
```
const webpack = require('webpack');

module.exports = {
  webpack: (config, {dev}) => {
    config.module.rules.push({
      test: /\.scss$/,
      use: [
        'style-loader',
        'css-loader',
        'sass-loader'
      ],
      exclude: /node_modules/,
    });

    config.plugins.push(
      new webpack.DefinePlugin({
        "process.env": {
          // flag to indicate this is for browser-side
          BROWSER: JSON.stringify(true),
       }
      })
    );

    return config;
  }
};
```
Then, in component code, require style file with condition. It makes sure only browser side bundling will have have style module.

```
if (process.env.BROWSER) {
  require("./style.scss");
}
```

If you don't mind the `if (process.env.BROWSER)`, it works perfectly.

**Comment by almeynman** [comment]
A good approach is [here](https://github.com/iaincollins/nextjs-starter)

**Comment by cr101** [comment]
@almeynman IMO that's not a very good approach as you are loading the CSS code for the entire website on every page instead of only loading the CSS file relevant to that page.

**Comment by almeynman** [comment]
@cr101 Hi, I did not know that. I have not really used that setup, just posted it for reference for others. I still use my approach described in [the blog post](https://blog.intellection.kz/next-js-and-css-modules-37e785a98bb0). If you could give me some feedback on that setup would be great

**Comment by cheshirecode** [comment]
More examples and discussions if anyone is interested:

https://github.com/iaincollins/nextjs-starter
https://github.com/zeit/next.js/issues/2534
https://github.com/zeit/next.js/tree/v3-beta/examples/with-global-stylesheet

Based on the above and this thread, I was able to use PostCSS to transform:
- Global SCSS (modules are the same, but you need an entry point in order to pre-compile all your CSS for production).
- Separate 3rd party CSS with custom fontfaces through relative URL.

into a single CSS file at `/static/styles/app.css` to serve in production, with hot reloading still working.

### postcss.config.js ###
```
module.exports = {
  plugins: [
    require("postcss-easy-import")({ prefix: "_" }), // keep this first
    require("postcss-url")({ url: "inline" })
  ]
};
```

### next.config.js ###
Loaders to transform .scss in dev mode for hot-reloading and extract to single .css file in prod. This gives me `build/app.css` so on Production build, I added `cp build/app.css static/styles/app.css` after `next build` to have it available in static export and embed in custom header as shown below.
```
const ExtractTextPlugin = require('extract-text-webpack-plugin');

export default {
  webpack: (config, { dev }) => ({
    ...config,
    module: {
      ...config.module,
      rules: [
        ...config.module.rules,
        {
          test: /\.(css|scss)/,
          loader: 'emit-file-loader',
          options: {
            name: 'dist/[path][name].[ext]'
          }
        },
        ...(dev
          ? [
              {
                test: /\.css$/,
                use: ['raw-loader', 'postcss-loader']
              },
              {
                test: /\.s(a|c)ss$/,
                use: [
                  'raw-loader',
                  {
                    loader: 'postcss-loader',
                    options: {
                      sourceMap: true
                    }
                  },
                  {
                    loader: 'sass-loader',
                    options: {
                      sourceMap: true
                    }                    
                  }
                ]
              }
            ]
          : [
              {
                test: /\.(css|scss)/,
                use: ExtractTextPlugin.extract({
                  use: [
                    {
                      loader: 'css-loader',
                      options: {
                        importLoaders: 2,
                        modules: false,
                        url: true,
                        minimize: true,
                        localIdentName: '[hash:base64:5]'
                      }
                    },
                    {
                      loader: 'postcss-loader'
                    },
                    {
                      loader: 'sass-loader'
                    }
                  ]
                })
              }
            ]),
        {
          test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2)(\?.*)?$/,
          loader: 'url-loader?limit=100000&&name=[name].[ext]?[hash:8]'
        }
      ]
    },
    plugins: [
      ...config.plugins,
      ...(dev ? [] : [new ExtractTextPlugin('app.css')])
    ]
  }),
};
```

## custom header ##
```
const inlineCSS =
  process.env.NODE_ENV !== ENV_PRODUCTION && require('styles/index.scss');
...
      <Head>
        {inlineCSS && <style jsx global> {__html: inlineCSS} </style>}
          {process.env.NODE_ENV === ENV_PRODUCTION &&
            <link
              rel="stylesheet"
              type="text/css"
              href={`/static/styles/app.css?${this.props
                .__NEXT_DATA__.buildId}`}
            />}
      </Head>
```

Hope this helps. Let me know if anyone needs more clarification.

**Comment by cr101** [comment]
Instead of extracting all your `.scss` files a single CSS file it would much better to compile each imported `.scss` file into into its own CSS file. That way you will only load the CSS styles you need on each page.
I'm not sure how you'd do that.

**Comment by pencilcheck** [comment]
Please checkout my pull request, I think I have a good solution:
https://github.com/zeit/next.js/pull/2638

**Comment by cheshirecode** [comment]
@cr101 that's true actually. We are importing our own internal UI library into different projects hence there is always a huge chunk of a file to load (not ideal I know, still working on modularising that beast).  It would be the next step, a scaled-up version from compile and serve 1 file to X number of files at X locations.

**Comment by chhuang** [comment]
Not sure if this has any performance issue, but this is a pretty simple solution if you are using styled-components or similar, just make a CSS wrapper:

```javascript
import styled from 'styled-components';

const Collapse = props => (
  <__Collapse>
    { props.children }
  </__Collapse>
);

export default Collapse;

/**
 * CSS
 */
const __Collapse = styled.div`
  .rc-collapse {
    background-color: #f7f7f7;
    border-radius: 3px;
    border: 1px solid #d9d9d9;
  }
  ...
`;
```

```jsx
import RcCollapse from 'rc-collapse';
import Collapse from '~/components/rc/Collapse';

const HelpPage = () => (
  <Collapse>
    <RcCollapse>
      <RcCollapse.Panel header="Title">Content</RcCollapse.Panel>
    </RcCollapse>
  </Collapse>
);
```

**Comment by stovmascript** [comment]
Here's a simple solution for importing CSS files using [babel-plugin-inline-import](https://github.com/quadric/babel-plugin-inline-import):

*.babelrc*
```json
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "inline-import",
      {
        "extensions": [".css"]
      }
    ]
  ]
}
```

*page/component*

```javascript
import "prismjs";

import { PrismCode } from "react-prism";
import prismGlobalStyles from "prismjs/themes/prism.css";

export default () => {
	return (
		<div>
			<style global jsx>
				{prismGlobalStyles}
			</style>
			<PrismCode className="language-javascript">
				{`function(noop) {
					return noop;
				}`}
			</PrismCode>
			{/* ... */}
		</div>
	);
};
```

**Comment by hilarykitz** [comment]
@stovmascript this is a beautiful solution but I still get errors (I'm importing the .css build from https://github.com/Hacker0x01/react-datepicker). Are you sure you don't have anything else in play here? From the errors it looks like it needs another level of CSS loading.

**Comment by Tzelon** [comment]
@hilarykitz , @stovmascript  solution works for me, can you send us the error you are getting?

**Comment by khrome83** [comment]
@stovmascript - how are you getting rid of the babel cache.

1. Make CSS file
2. Import File
3. Apply
4. Change CSS file - add new selector and style
5. Witness that Babel Cache keeps old version

**Comment by pungggi** [comment]
@khrome83  you'll need to clear the node_modules/.cache

**Comment by khrome83** [comment]
I found a better solution using babel-inline-loader plugin that clears the cache and works with the above. The issue with that method is that you can only apply global styles. When using in a non `<style jsx global>` tag, it will not add the data-jsx correctly defeating the purpose.

**Comment by chibicode** [comment]
> I found a better solution using babel-inline-loader plugin that clears the cache and works with the above. The issue with that method is that you can only apply global styles. When using in a non <style jsx global> tag, it will not add the data-jsx correctly defeating the purpose.

@khrome83 can you elaborate?

**Comment by chibicode** [comment]
I added an example using @stovmascript's solution:

https://github.com/zeit/next.js/pull/3157

**Comment by CHarnel** [comment]
How do you include more than one external css?
I use 2 libs that require it in the same component, each one works separately, but I don't know how to combine them.

```
import rtStyle from 'react-table/react-table.css';
import dpStyle from 'react-datepicker/dist/react-datepicker.css';
...
render() {
    return (
      <div>
        {/* <style jsx global>{ rtStyle }</style> */}
        <style jsx global>{ dpStyle }</style>
...
```

**Comment by almeynman** [comment]
@CHarnel try <style jsx global>{ rtStyle }{dpStyle}</style>

**Comment by CHarnel** [comment]
@almeynman getting this:
```
Module build failed: SyntaxError: C:/.../components/activeUsersTable.js: 
Expected one child under JSX Style tag, but got 2 (eg: <style jsx>{`hi`}</style>)
```

**Comment by almeynman** [comment]
@CHarnel try putting both in template string

**Comment by alanhr** [comment]
@CHarnel  try this approach 
`<style jsx global>{ `${rtStyle} ${dpStyle}`}</style>`

**Comment by comus** [comment]
@alanhr 

i try to put those css in one js file and export it

```
import bootstrap from 'bootstrap/dist/css/bootstrap.min.css'
import styles from './index.css'

export default bootstrap + styles
```

and then just

```
import styles from '../styles'
...
<style jsx global>{styles}</style>
```

**Comment by sheerun** [comment]
With https://github.com/sheerun/extracted-loader I've created you can use ExtractTextPlugin for both development and production, no need for different html in development or injecting css into js.

**Comment by CHarnel** [comment]
@comus I used your approach, works good, thank you.

**Comment by edmondnyaigoti** [comment]
@sheerun nice one thank you

**Comment by sheerun** [comment]
I've submitted even more comprehensive example to next.js:
https://github.com/zeit/next.js/pull/3451

**Comment by mihaiserban** [comment]
This used to work before nextjs v4

`<style jsx global>{style}</style>
        <style jsx global>{colors}</style>
        <style jsx global>{layout}</style>`

What's the reason for using this aproach to load jsx global styles? `<style jsx global>{ rtStyle }{dpStyle}</style>`

**Comment by nikolakanacki** [comment]
I've made myself a solution based on `emit-files-loader`. If anyone is interested I can post it here, but it relies on a custom server setup - basically you need to be able to statically serve single directory within `.next` build dir. It could probably be configured without a server by relying on the `/_next/...` path structure of the server.

Other than that you can write `import stylesheet from `./styles/style.[scss|less|stylus|w/e]`; and it will be the public path to your stylesheet file, so you can put it in a `<link>`. It includes `?[hash]` for permanent caching and it does hot-reload.

**Comment by timneutkens** [comment]
@nikolakanacki official support will be introduced very soon 🙏 https://github.com/zeit/next.js/pull/3578

**Comment by nikolakanacki** [comment]
@timneutkens I've seen this one, is there an estimation on "very soon"? I see it's in canary already.
I just needed a solution right away, spent 2-3 days looking for one, and managed to write up my own which is basically an "easy fix", I'm even thinking about combining it with `extract-text-webpack-plugin` so one could statically join all the separate `.[css|stylus|less|scss]` files and have them all available as a single static resource.

The main problem behind these issues I think is that there is a lot of "magic" going on in the background behind production and dev builds, with hot reloading and stuff... One could probably read the source and see how things are assembled together, but it would be awesome if someone who built it wrote some docs on that, I think more people could contribute.

**Comment by timneutkens** [comment]
@nikolakanacki very soon 🙏 🤐 

> 'm even thinking about combining it with extract-text-webpack-plugin so one could statically join all the separate .[css|stylus|less|scss] files and have them all available as a single static resource like it normally would without next.

The plugins that I wrote for next v5 already do this, they'll be open sourced soon 👍 

Regarding writing docs on the internals, we're planning to document how everything works after v5 is out 🙏

**Comment by jameskennethrobinson** [comment]
@timneutkens Thank you!

**Comment by nikolakanacki** [comment]
@timneutkens thank you for the update, please post an update here when this thing lands!

**Comment by rouxfeur** [comment]
Any news on this?

**Comment by nguyenvanphuc2203** [comment]
just create /static folder in root project, and put your file.css inside /static, then <link style /> to <Head> hock. and then use className anywhere!

**Comment by pavinduLakshan** [comment]
> @alanhr
> 
> i try to put those css in one js file and export it
> 
> ```
> import bootstrap from 'bootstrap/dist/css/bootstrap.min.css'
> import styles from './index.css'
> 
> export default bootstrap + styles
> ```
> and then just
> 
> ```
> import styles from '../styles'
> ...
> <style jsx global>{styles}</style>
> ```

Much comprehensive and smart..thank you for this..I have been searching this kind of solution all day..

**Comment by mrpeski** [comment]
> just create /static folder in root project, and put your file.css inside /static, then to Header html structure hock.
> 
> ```
> import Head from 'next/head';
> <Head>
>           <meta charset="utf-8" />
>           <link rel="stylesheet" href="/static/css/custom.css" />
> </Head>
> ```
> 
> and then use className anywhere!

Create a public folder in the root of your application(where package.json file is located).

**Comment by Timer** [comment]
Support is being added via #8626!
