### ISSUE TITLE
Next component in another component getInitialProps not being called

### ISSUE THREAD

**Issue by TheRealSmolt** [zeit/next.js#5444]
In advance, I apologize if this is a duplicate (I don't know how to search for "next displayed in next not called getInitialProps ...").

Basically, I have an index.js file that has nothing but html, a Layout class that does the standard thing with head etc, and a ChannelSelector.js file. The problem is that when I use ChannelSelector(CS) in the index file-<ChannelSelector/>-its getInitialProps won't run. But when I move the CS file into the pages folder and access it, the function does run. I'm probably missing something crucial, I am a beginner, so sorry if that's the case, but any help would be appreciated. Thanks.

**Comment by danielr18** [comment]
From the README:

> Note:  getInitialProps can not be used in children components. Only in pages.

**Comment by timneutkens** [comment]
Yeah as Daniel said, it's only executed on top level components.

**Comment by TheRealSmolt** [comment]
Then why does it work through my layout file?

**Comment by heavenlian** [comment]
@TheRealSmolt , How does it work in your loayout file.
