### ISSUE TITLE
NextJS- How handle redirect, meanwhile my strategy returns an error

### ISSUE THREAD

**Issue by Hocoh** [zeit/next.js#5445]
I'm trying to fetch the URL entered in the browser to make some redirect in my NextJS custom server. This error occurs only in dev mode, no in production mode , so is it normal ? there is some modification to do on the devmode to handle that ?  

_For info : I mean the production mode = NODE_ENV=production, even if I run it in my localhost, it's just about the NODE_ENV variable. Then when I'm testing on my localhost my production mode °NODE_ENV=production°, itworks well. that it. the production mode is built by NextJS, I can just change the NODE_ENV value._

I'm using a redirect in a blog 's context. On my blogpost grid -with the choice of blogpost inside, when I am in development mode, I get the custom page 's "404 error". 

I have tried to use the pathname object. Sadly when I first entered  an URL in my address bar, my pathname firstly returns:

>   /_next/static/chunks/0.js

I have tried with req.rawHeaders. But my console returns nothing till the 15th trial:

> req.rawHeaders path in next.server.js :
> 
> req.rawHeaders path in next.server.js : 
>
> req.rawHeaders path in next.server.js :
>
> req.rawHeaders path in next.server.js :
>
> req.rawHeaders path in next.server.js : 
>
> req.rawHeaders path in next.server.js :
>
> req.rawHeaders path in next.server.js : 
>
> req.rawHeaders path in next.server.js : 
> 
> req.rawHeaders path in next.server.js :
>
> req.rawHeaders path in next.server.js : 
>
> req.rawHeaders path in next.server.js : 
>
> req.rawHeaders path in next.server.js :
>
> req.rawHeaders path in next.server.js :
>
> req.rawHeaders path in next.server.js :
> 
> req.rawHeaders path in next.server.js : 
>
> req.rawHeaders path in next.server.js :  /pathTargeted // work ! but a little bit in late ..

I have also tried with req.headers.referer but even, the first path returns is not the path I have entered in the URL. 

The result is that I fall in a 404 error. So how avoid this and always fetch the real address entered in the browser ? That exactly my problem.

Any hint would be great,
thanks

## To Reproduce
 
Here my NextJS's frontend snippet: 

```
import React, {Component} from "react"; 
import style from "./BlogHubTemplate.module.css";

import storeWrapper from "../../HOC/storeWrapper/storeWrapper"
import {connect} from 'react-redux';

import Router from 'next/router'
 

class BlogHubTemplate extends Component { 

    redirectPost = (postCategory, postTitle) => { 
        Router.replace(`/${postCategory}/${postTitle}`) 
    }

```

Here my custom.next.server.js for log the variables:

```
app.prepare().then(() => {
 createServer((req, res) => {
 // Be sure to pass `true` as the second argument to `url.parse`.
 // This tells it to parse the query portion of the URL.
 const parsedUrl = parse(req.url, true)
 const { pathname, query } = parsedUrl; 

 console.log("req.headers in next.server.js : ", req.headers.referer.substr(22))
 console.log("req.rawHeaders path in next.server.js : ", req.rawHeaders[11].substr(22))
 
```

**Comment by giovannigiordano** [comment]
Can you provide a repository to clone?

**Comment by timneutkens** [comment]
I just read the whole post and I don't understand what you're trying to do. However you're probably looking for the `asPath` in `getInitialProps` 🤔 I'm going to close this as it's not following the issue template (questions should be posted on https://spectrum.chat/next-js)
