### ISSUE TITLE
KOA custom server alwasy hits error 'read ECONNRESET' when EDGE or IE refresh or close page

### ISSUE THREAD

**Issue by hebinhuang** [zeit/next.js#5449]
# Bug report

## Describe the bug
The **KOA** custom server always hits error 'read ECONNRESET' when **EDGE**or **IE** refresh page or close Tab window. 

## To Reproduce
Start KOA server from example '[custom-server-koa](https://github.com/zeit/next.js/tree/canary/examples/custom-server-koa)':

1. Go to 'http://localhost:3000' on EDGE or IE
2. Click on 'refresh' button or just close EDGE or IE
3. In cmd console window, see error below
```
  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
```

## Expected behavior
No error throw when EDGE or IE refresh or close

## System information
 - OS: Windows 10
 - Browser: EDGE and IE 11
 - Version of Next.js: 7.0.2
 - Version of Node.js: 10.12.0

## Additional context
Chrome does not have the issue

**Comment by timneutkens** [comment]
I doubt there's anything to fix in Next.js related to this 🤔
