### ISSUE TITLE
How to scope to the root when using service worker in Next

### ISSUE THREAD

**Issue by Alexisvt** [zeit/next.js#545]
Hi, first of all, great work! I have a noob question, currently I'm playing with Service Workers and I want to implement mine using Next, but the problem that I have is when I want to register the SW and define as a scope the root of the page ('/').

Currently What I did was to put my registration and service worker (sw.js) file in the static folder, then on the index.js file inside the pages folder Im calling the registration.js file, using the script component inside the head tag. Chrome is telling me the next message:

```cmd
The path of the provided scope ('/') is not under the max scope allowed ('/static/'). Adjust the scope, move the Service Worker script.
````
I understand this error, but How can I move the service worker to the root if the static folder is the only place to put it, thanks!

Code:

```js
// \static\register.js
if (navigator.serviceWorker) {
  navigator.serviceWorker.register('/static/sw.js', {scope: '/'})
    .then(reg => {
      console.log('Registration succeeded. Scope is ' + reg.scope);
    }).catch(function (error) {
      // registration failed
      console.log('Registration failed with ' + error);
    });
}

// \pages\index.js
// @flow
import * as React from 'react';
import Head from 'next/head';

import Header from '../components/header';
import Footer from '../components/footer';

import { somestyles, otherstyles } from '../styles/styles';

export default class HomePage extends React.Component {
  static async getInitialProps() {
    // code will go here to get data
  }

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div className={somestyles}>
        <Head>
          <title>Next -- {`will insert page title here`}</title>
          <script src='/static/register.js' />
        </Head>
        <Header>
          Page Title
        </Header>
        <div className={otherstyles}>
          <h2> A Header </h2>
          <p>Some text for my page</p>
        </div>
        <Footer />
      </div>
    );
  }
}
````

**Comment by rauchg** [comment]
You can use a custom server (through the programmatic API), to serve a file manually from the root. Please check the relevant section in the README and the associated examples
