### ISSUE TITLE
Remove/Disable HMR with Mobx

### ISSUE THREAD

**Issue by stephane-r** [zeit/next.js#5453]
# Question about Next.js

Is it possible to remove or disable HMR on Next@7 ? I use Mobx, and all `observer` is not rerendered. I need to rebuild my bundle. After `[HMR] bundle rebuilding` message, all state are updating in my DOM.

**Comment by timneutkens** [comment]
As per the issue template this should be posted on spectrum.chat, but no, it's not possible to disable HMR, and instead you probably have to implement `module.hot` for mobx.
