### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by MishaFrenkman** [zeit/next.js#5455]
# Bug report

## Describe the bug

`npm i next` fails

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. `npm i next`

## Expected behavior
Should install next modules

## Screenshots
<img width="850" alt="screenshot 2018-10-15 at 16 04 49" src="https://user-images.githubusercontent.com/8081364/46956299-3b655000-d095-11e8-943b-cdb3644e076f.png">
<img width="1165" alt="screenshot 2018-10-15 at 16 07 37" src="https://user-images.githubusercontent.com/8081364/46956300-3b655000-d095-11e8-985d-ecf7c67dafdd.png">

## System information
 - OS: macOS
 - node: v10.10.0
 - npm: v6.4.1
 - Version of Next.js: latest

## Additional context
Tried on another computer and got the same error.
Other modules (like react and react-dom) install without problems
Install tried in an empty folder

**Comment by timneutkens** [comment]
Sounds like an issue in npm, not Next.js, I'm not sure what we can change.

Here's the output of `npm i next`:

```
npm i next

> fsevents@1.2.4 install /Users/timneutkens/projects/sandbox/node_modules/fsevents
> node install

[fsevents] Success: "/Users/timneutkens/projects/sandbox/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN next@7.0.2 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN next@7.0.2 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-jsx@3.1.0 requires a peer of react@15.x.x || 16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN sandbox No description
npm WARN sandbox No repository field.
npm WARN sandbox No license field.

+ next@7.0.2
added 57 packages from 57 contributors, removed 79 packages, updated 574 packages and audited 6444 packages in 62.578s
found 0 vulnerabilities
```
