### ISSUE TITLE
How to remove x-frame-options: DENY

### ISSUE THREAD

**Issue by tantranlee** [zeit/next.js#5467]
Hello,
Please help me how to remove x-frame-options: DENY in my app.
My app use custom server express and i18next-express-middleware. In my custom server I never use x-frame-options. But this alway show in header. How to remove it. I try with res.removeHeader('x-frame-options'); But it not working.

**Comment by timneutkens** [comment]
Next doesn't set this header.

**Comment by diogoviannaaraujo** [comment]
Just stumbled upon this, I guess this is Now behavior.
