### ISSUE TITLE
path is undefined in `new Router` on all pages of client in production

### ISSUE THREAD

**Issue by Jauny** [zeit/next.js#5468]
EDIT: Seems like pinning the next package version fixed this. No idea why.
We have `^7.0.0`. I tried pinning to `7.0.0`, worked. Then `7.0.1` also worked. And now at `7.0.2` and it still works. I have no clue what's up there.

Sorry for the bug report - maybe it'll still be useful for someone else, or maybe the Next team will understand something relevant 👍 

# Bug report

## Describe the bug

When loading our next.js app in production (on elastic beanstalk) we are getting a client-side error of `TypeError: Cannot read property 'replace' of undefined`.  
This error comes from [toRoute(path)](https://github.com/zeit/next.js/blob/82d56e063aad12ac8fee5b9d5ed24ccf725b1a5b/packages/next-server/lib/router/router.js#L15) when the Router is getting initialised on the client side at [createRouter](https://github.com/zeit/next.js/blob/965f50beb238eab8aafa9be32833b0e7d2947574/packages/next/client/index.js#L94).  

Looking at the code, the `page` argument to `createRouter` is coming from `window.__NEXT_DATA__`, which seems to properly be storing the value as expected.
I'm able to log `window.__NEXT_DATA__` before the error occurs and see that the `page` is there (see screenshot below).

Interestingly, this error does not happen if we run the production build locally, only on elastic beanstalk, on which we upload a pre-built build. The only thing happening during deployment is EBS is running `npm install`.

We use
- custom server.js with express
- custom _app.js, wrapped in a with-redux-app

## Screenshots
<img width="1041" alt="screen shot 2018-10-17 at 09 03 54" src="https://user-images.githubusercontent.com/1719552/47068269-20592400-d1ec-11e8-874f-1d6c5f83cbd1.png">

## System information
 - OS: aws EC2 t2.small
 - Browser: chrome, safari tested 
 - Version of Next.js: 7

## Additional context
Some source code:

server/server.js
```javascript
const express = require('express')
const nextjs = require('next')

const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = nextjs({ dev })
const handle = app.getRequestHandler()

app.prepare()
  .then(() => {
    const server = express()

    server.get('/', (req, res) => {
      return app.render(req, res, '/shop')
    })

    server.get('/products/:id-:itemTitle?', (req, res) => {
      const params = Object.assign(req.params, req.query)
      return app.render(req, res, '/product', params)
    })

    server.get('/@:username', (req, res) => {
      return app.render(req, res, '/user', {username: req.params.username})
    })

    server.get('*', (req, res) => {
      return handle(req, res)
    })

    server.listen(port, (err) => {
      if (err) throw err
      /* eslint-disable-next-line no-console */
      console.log(` > Ready on http://localhost:${port}`)
    })
  })
```

pages/_app.js
```javascript
import App, {Container} from 'next/app'
import Head from 'next/head'
import React from 'react'
import withReduxStore from '../src/lib/with-redux-store'
import { Provider } from 'react-redux'

import * as Sentry from '@sentry/browser'
import getConfig from 'next/config'

import IntercomHead from '../src/components/head/_intercom-head'

class MyApp extends App {
  constructor (props) {
    super(props)

    if (getConfig().publicRuntimeConfig.prod) {
      Sentry.init({
        dsn: '<hidden>',
      })
    }
  }

  componentDidCatch (error, errorInfo) {
    if (getConfig().publicRuntimeConfig.prod) {
      Sentry.configureScope(scope => {
        Object.keys(errorInfo).forEach(key => {
          scope.setExtra(key, errorInfo[key])
        })
      })
      Sentry.captureException(error)
    }
  }

  render () {
    const {Component, pageProps, reduxStore} = this.props
    return (
      <Container>
        <Head>
          <IntercomHead />
        </Head>
        <Provider store={reduxStore}>
          <Component {...pageProps} />
        </Provider>
      </Container>
    )
  }
}

export default withReduxStore(MyApp)
```

src/lib/with-redux-store.js
```javascript
import React from 'react'
import {initializeStore} from '../store/store'
import {makeInitialState} from '../reducers/initialState'
import {getNavItemIndexFromURL} from '../utils/utils'

const isServer = typeof window === 'undefined'
const __NEXT_REDUX_STORE__ = '__NEXT_REDUX_STORE__'

function getOrCreateStore (initialState) {
  // Always make a new store if server, otherwise state is shared between requests
  if (isServer) {
    return initializeStore(initialState)
  }

  // Create store if unavailable on the client and set it on the window object
  if (!window[__NEXT_REDUX_STORE__]) {
    window[__NEXT_REDUX_STORE__] = initializeStore(initialState)
  }
  return window[__NEXT_REDUX_STORE__]
}

export default (App) => {
  return class AppWithRedux extends React.Component {
    static async getInitialProps (appContext) {
      // Get or Create the store with `undefined` as initialState
      // This allows you to set a custom default initialState
      const navIndex = getNavItemIndexFromURL(appContext.ctx.pathname)
      const state = makeInitialState({navIndex})
      const reduxStore = getOrCreateStore(state)

      // Provide the store to getInitialProps of pages
      appContext.ctx.reduxStore = reduxStore

      let appProps = {}
      if (typeof App.getInitialProps === 'function') {
        appProps = await App.getInitialProps(appContext)
      }

      return {
        ...appProps,
        initialReduxState: reduxStore.getState(),
      }
    }

    constructor (props) {
      super(props)
      this.reduxStore = getOrCreateStore(props.initialReduxState)
    }

    render () {
      return <App {...this.props} reduxStore={this.reduxStore} />
    }
  }
}
```

**Comment by ellell** [comment]
I had the same issue, and it seemed to be happening when I was building using one version (next@7.0.1) but actually running app with next@7.0.2

**Comment by Jauny** [comment]
Thanks! That would explain why the issue got fixed when I pinned the
versions then.

**Comment by timneutkens** [comment]
That explains, in 7.0.2 we no longer send `pathname` from the server to the client side as part of the XSS patch. There's not much we can change on the Next.js side now, so let's close this issue.
