### ISSUE TITLE
Create or substitution of page with page in html file

### ISSUE THREAD

**Issue by canotech** [zeit/next.js#5472]
Hi, my question is the next, I can detect when user input to  an url and  I cant subst that url with page write in html?for example something like that:

`  
    if (pathname === '/account/password-set') {
      app.render(req, res,'./set-password.html', query);
    } else {
      handle(req, res, parsedUrl);
    };`

thanks,  I await your response

**Comment by timneutkens** [comment]
First of all following the issue template questions should be posted on https://spectrum.chat/next-js.

So I'm not really sure what you're trying to do based on your description. But if you want to output a specific HTML file that is not coming from Next.js you will have to serve that manually.

**Comment by canotech** [comment]
Yes, I could only serve the file from file manually  from nodejs with custom serve routing, thx @timneutkens
