### ISSUE TITLE
Documentation for Dynamic import is outdated (in v7)?

### ISSUE THREAD

**Issue by williamli** [zeit/next.js#5473]
I tried to import a component by following the sample code in https://nextjs.org/docs/#dynamic-import

```
const DynamicComponent = dynamic(() => import('components/CarousalControllerComponent"'))
```

and I get errors complaining about 
`Error: loader is not a function`

Dynamic works again once I changed the code to

```
const CarousalControllerComponent = dynamic({
  loader: () => import("components/CarousalControllerComponent")
});
```

**Comment by timneutkens** [comment]
https://spectrum.chat/thread/5f731d67-a3e3-4716-82a9-b7f7f99d2062?m=MTUzOTg1MDQzNzA1Nw==

**Comment by pengshaosu** [comment]
`Dynamic import` is only for component?
How can used in somewhere only logic code(non-component).
Thx.
