### ISSUE TITLE
next/config not working on custom server

### ISSUE THREAD

**Issue by JonathanWbn** [zeit/next.js#5476]
# Bug report

## Describe the bug
When using next.js with a custom-server, `publicRuntimeConfig` is undefined in the client.

## To Reproduce
Check the logs on these Codesandboxes:
Working without a server: [hello-world](https://codesandbox.io/s/zxn9k1l483)
Not working with a custom server: [custom-server-express](https://codesandbox.io/s/rr1v861l2p)

## Expected behavior
`publicRuntimeConfig` to be as set in `next.config.js`.

## System information
 - Version of Next.js: 7.0.2

What am I missing here? Is `getConfig` not supposed to work with a custom server? What would be the alternative?

**Comment by timneutkens** [comment]
This example works fine when clicking both console and terminal though https://codesandbox.io/s/rr1v861l2p

**Comment by JonathanWbn** [comment]
Urgh, my bad. Thanks.

**Comment by danteissaias** [comment]
I can't access the sandbox anymore, can someone post the solution?

**Comment by rezanouri87** [comment]
@timneutkens I am facing the same issue and link that you've provided is broken. Could you please share your solution again?

**Comment by adamsoffer** [comment]
Hey @timneutkens ! I'm also running into this issue where getConfig() returns an empty object when running a custom express server. Do you remember what the solution was?

**Comment by timneutkens** [comment]
it holds state in a singleton, the only reason it wouldn't work is if you have duplicated next inside node_modules or something 🤔

**Comment by adamsoffer** [comment]
Hmm yeah that's a possibility. I ended up going with Now build env and secrets instead. Works like a charm.
