### ISSUE TITLE
[v7] Sometimes Links stop working.

### ISSUE THREAD

**Issue by trusktr** [zeit/next.js#5478]
I don't have much info. I updated to v7, and every once in a while `<Link>`s in the entire app stop being clickable, and nothing happens when clicking them.

I'm not doing anything special, just `<Link href="...">` and the only child elements in my Links are plain `<a>` tags with no attributes, except for `className` when I want to style them.

F.e.:

```jsx
<Link href="/products">
	<a className={classnames(classes.logo, 'nextLink')}>
		Products
	</a>
</Link>
```

Somethings up. But not sure how to reproduce.

**Comment by trusktr** [comment]
Not sure, but it seems to happen at some point after a hot reload.

**Comment by ahmadalfy** [comment]
I noticed the same thing after updating to 7 but it happens in development mode only. I am not sure if it  is related to HMR or not. My observation is that the server stop compiling the page and the link hangs.

Thankfully refresh fixes the issue.

**Comment by srdjan** [comment]
I can attest to that too... dev only, super random, page reload fixes it

**Comment by timneutkens** [comment]
Things missing:
- Issue template
- Clear and concise reproduction

We have a whole test suite that is literally clicking around every feature in chrome while in development mode:

https://github.com/zeit/next.js/blob/canary/test/integration/basic/test/client-navigation.js

**Comment by gaogao1030** [comment]
reopen issue 

> I can attest to that too... dev only, super random, page reload fixes it

me too, reopen issue?

**Comment by NgRuiYong** [comment]
I am having the same issue as well. The issue seems to appear after the user is inactive on the webpage after a while.

**Comment by timneutkens** [comment]
Just going to quote myself:

"
Things missing:

- Issue template
- Clear and concise reproduction

We have a whole test suite that is literally clicking around every feature in chrome while in development mode:

https://github.com/zeit/next.js/blob/canary/test/integration/basic/test/client-navigation.js
"

I'm not going to reopen this issue based on what I posted earlier.

**Comment by ahmadalfy** [comment]
@timneutkens I completely understand why we need a reproduction scenario but I do believe none of us can do that as the issue is happening randomly without any clear steps to do. When the HMR drops in and does it work suddenly links stop working and I refresh and bingo; it's resolved. Happen on a daily basis like 10 times during development and what I use is the same format I was using in the previous version.

I know it is hard to debug without a proper reproduction scenario maybe some of us need to spend more time investigating and coming up with it.

**Comment by andykay91** [comment]
I am using [next-routes](https://github.com/fridays/next-routes) and [material-ui](https://github.com/mui-org/material-ui) which I think could potentially be a source of the problem.

**Comment by malimccalla** [comment]
@timneutkens Thanks, I was able to reproduce with reproduction steps. Have opened a new issue here #5598

**Comment by ahmadalfy** [comment]
@iamandyk I am not using material-ui and I still see the problem

**Comment by Vladk2** [comment]
Same here, it's really annoying sometimes..

**Comment by g089h515r806** [comment]
same issue

**Comment by jeremylynch** [comment]
+1

**Comment by gzoreslav** [comment]
+1

**Comment by timneutkens** [comment]
Instead of posting `+1` on an issue that had **no reproduction**, making it essentially impossible to help you. You could also use GitHub's 👍 feature.

Assuming you're having the same issue as @malimccalla you can track #5598

**Comment by samundra** [comment]
I am also having this issue. Looks like the Links are intercepting the click but do not take to the desired page.

Links are created as

```
              <ul>
                {this.state.couponTypes.map(({id, path, label}) => (
                  <li key={id}>
                    <Link as={`/coupon/${label.toLowerCase()}`} href={`/coupon?type=${label.toLowerCase()}`}>
                      <a>{label}</a>
                    </Link>
                  </li>
                ))}
              </ul>
```

Then I tested the click intercept with 

```
import Router from 'next/router'
...
...
Router.events.on('routeChangeStart', url => {
  console.log('Navigating to:', url);
});

Router.events.on('routeChangeComplete', url => {
  console.log('Completed navigation to: ', url);
});
```

When I click on my Link I can see `Navigating to: /coupon/accounts` but it never completes.

**Comment by timneutkens** [comment]
Try next@canary

**Comment by samundra** [comment]
@timneutkens The problem is, this happens at random times. Anyway, I will give it a try and let you know asap. Thanks.

**Comment by timneutkens** [comment]
@samundra however #5598 actually had a reproduction that reliably reproduced this issue and I fixed it shortly after.

**Comment by Thuan2000** [comment]
I am still having issues with this.

**Comment by fandy** [comment]
Still having issues with this. It happens randomly but is fixed after a hard refresh.

**Comment by timneutkens** [comment]
Please create a new issue with a ***clear and concise reproduction***. Thanks 🙏

**Comment by bmtdh** [comment]
Happens all the time, after a period of inactivity (10 mins) or multiple hot reloads <Link> stops working in development mode.

**Comment by Timer** [comment]
Hi everyone, if you're still experiencing this issue on v8 please file a new issue. It is not feasible for us to track issue in old threads with outdated context.

Thank you for your cooperation.
