### ISSUE TITLE
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by slepets-a** [zeit/next.js#5480]
# Bug report

TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.

## Describe the bug

While trying to add `bootstrap.min.css` to the project with `styled-components` I'm getting an error described above.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Add `styled-components` support as described in [example](https://github.com/zeit/next.js/tree/canary/examples/with-styled-components)
```
import Document, { Head, Main, NextScript } from 'next/document';
import { ServerStyleSheet } from 'styled-components';

const script = `window.ENV = '${process.env.ENV || 'dev'}';`;

export default class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    const sheet = new ServerStyleSheet();
    const page = renderPage(App => props => sheet.collectStyles(<App {...props} />));
    const styleTags = sheet.getStyleElement();
    return { ...page, styleTags };
  }

  render() {
    return (
      <html>
        <Head>
          {this.props.styleTags}
          <script dangerouslySetInnerHTML={{ __html: script }} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```
2. Add `next-css`, `bootstrap` and try to set up `css` support from [example](https://github.com/zeit/next.js/tree/canary/examples/with-next-css)
`next.config.js`:
```
const withCSS = require('@zeit/next-css');
module.exports = withCSS();
```
`pages/index.js`
```
import { Query } from 'react-apollo';
import gql from 'graphql-tag';
import { Link, Router } from '../config/routes';
import { Button } from '@cni/tetris';
import Main from 'components/Main';

const Home = props => (
  <div>
    <h1>Home</h1>
    <Main />
    <Button>Submit</Button>
  </div>
);

export default Home;
```
3. Try to run `yarn dev`
4. See error in a console
```
yarn run v1.10.1
$ node server.js
/Users/user/Projects/b21-app-starter/node_modules/mini-css-extract-plugin/dist/index.js:20
  util: { createHash }
          ^

TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/user/Projects/b21-app-starter/node_modules/mini-css-extract-plugin/dist/index.js:21:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/user/Projects/b21-app-starter/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
```
5. Try to `yarn add webpack@latest`. Don't change any configs.
6. Try `yarn dev`
7. It works :tada:

## Expected behavior
Successfully started project with Bootstraps's styling.

## System information
 - OS: macOS
 - Version of Next.js: 7.0.0

## Additional context
Works with `"webpack": "^4.21.0"`

**Comment by slepets-a** [comment]
Any update related to this issue?

**Comment by Jero786** [comment]
+1 The same here!

**Comment by timneutkens** [comment]
Feel free to send a PR to upgrade webpack instead +1'ing the issue 😄

**Comment by Jero786** [comment]
@timneutkens Yes sorry, I didn't have time to do that. I would love to contribute on that!

**Comment by Jero786** [comment]
@timneutkens here is my [PR](https://github.com/zeit/next.js/pull/5623) !

**Comment by Jero786** [comment]
@timneutkens I update the [PR](https://github.com/zeit/next.js/pull/5623) again with the updated webpack version. Ley me know what do you think about that, Thanks!
