### ISSUE TITLE
The error overlay does not show up in Firefox for server errors

### ISSUE THREAD

**Issue by lydell** [zeit/next.js#5481]
# Bug report

## Describe the bug

The error overlay (from [react-error-overlay](https://github.com/lydell/next-error-overlay-firefox-issue)) does not show up in Firefox for server errors.

|Error happened in|Chrome|Firefox|
|-----------------|------|-------|
|Browser          |✅|✅|
|Server           |✅|❌|

## To Reproduce

**Repro repo:** https://github.com/lydell/next-error-overlay-firefox-issue

Steps to reproduce the behavior, please provide code snippets or a repository:
1. `git clone https://github.com/lydell/next-error-overlay-firefox-issue.git`
1. `npm ci`
2. `npm start`
3. Go to <http://localhost:3000> in Firefox. That page contains an error. The error overlay is not shown (but is shown in Chrome).
4. Go to <http://localhost:3000/link> in Firefox and click the link to the start page there. Now the error overlay _is_ shown (until you refresh the page).

## Expected behavior
The error overlay should display in Firefox even for server errors.

### Actual (Firefox)
![screenshot from 2018-10-19 19-09-51](https://user-images.githubusercontent.com/2142817/47233778-1134ca80-d3d4-11e8-8869-c2c2f0963822.png)

### Expected (Chrome)
![screenshot from 2018-10-19 19-19-27](https://user-images.githubusercontent.com/2142817/47233791-172aab80-d3d4-11e8-96f3-cd18f8301624.png)

## System information
 - OS: Ubuntu 18.04
 - Browser (if applies): Firefox
 - Version of Next.js: 7.0.2

**Comment by HaNdTriX** [comment]
@timneutkens This error also happens in the latest chrome (canary), since uncaught will stop the js process.

**Comment by timneutkens** [comment]
@Timer can we get that error reporting API into react-error-overlay?

**Comment by Timer** [comment]
I think we have 2 active PRs, which one would you need merged?

**Comment by timneutkens** [comment]
This one: https://github.com/facebook/create-react-app/pull/4709

The other one is not as important, but it's related to errors that come from SSR.

**Comment by Timer** [comment]
Merged and released in 2.1.1.

**Comment by timneutkens** [comment]
:100:

**Comment by timneutkens** [comment]
@ijjk let's implement `reportRuntimeError` instead of the throwing we currently do in next/client/index.js 💯
