### ISSUE TITLE
Server doesn't render head when a _document.js is provided

### ISSUE THREAD

**Issue by shawninder** [zeit/next.js#5482]
# Bug report

Server doesn't render `<head>` when a `_document.js` is provided, even if the document changes nothing (the identity document, if you will).

## To Reproduce

[This repo](https://github.com/shawninder/where-the-head) reproduces the bug, producing among other symptoms an easy to spot flash of unstyled content (FOUC).
- `git clone git@github.com:shawninder/where-the-head.git`
- `cd where-the-head`
- `npm i`
- `npm run dev`
- visit http://localhost:3000/ with any browser
- observe a FOUC on reloading the page
- visit `view-source:http://localhost:3000/`
- notice the absence of a `<head>` tag

## Expected behavior
Presence of `<head>` and no FOUC. You can achieve expected behaviour with following additional steps:
- `rm pages/_document.js`
- Kill dev server (Ctrl+C) and restart (`npm run dev`)
- issues have disappeared, this is the expected behavior

## System information
 - OS: macOS 10.13.4
 - Browsers: any
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
@wekkit is correct, as per the documentation: https://github.com/zeit/next.js#custom-document
