### ISSUE TITLE
Got a error when upgrade next from v6 to v7

### ISSUE THREAD

**Issue by chauduong1192** [zeit/next.js#5487]
# Bug report
.env["development"].presets[0][1] must be an object, false, or undefined

## Describe the bug

I was trying to upgrade my project with next from v6 to v7 and I'm getting an error described above.
## To Reproduce

Steps to reproduce the behavior, please provide 
code snippets or a repository:
1. `package.json`
<img width="480" alt="screen shot 2018-10-20 at 11 19 02 pm" src="https://user-images.githubusercontent.com/6010960/47257941-a3190200-d4be-11e8-9ed6-dd161180de60.png">
<img width="358" alt="screen shot 2018-10-20 at 11 23 36 pm" src="https://user-images.githubusercontent.com/6010960/47257985-3a7e5500-d4bf-11e8-8821-147c1e80e345.png">

2. See error
<img width="712" alt="screen shot 2018-10-20 at 11 07 06 pm" src="https://user-images.githubusercontent.com/6010960/47257829-f38f6000-d4bc-11e8-8900-a109d5b5a6c1.png">

## Expected behavior
Upgrade from v6 to v7 successfully

## System information
 - OS: macOS
 - Version of Next.js: 7.0.0

**Comment by timneutkens** [comment]
Your `.babelrc` probably has something wrong in it 🤔 under `"env"` `preset` and then the first preset's options are something that is not an object.

**Comment by chauduong1192** [comment]
Thanks you @timneutkens
