### ISSUE TITLE
ie10 Error of withRouter

### ISSUE THREAD

**Issue by VanquisherMe** [zeit/next.js#5492]
# Examples bug report

## Example name
ie10 Error of withRouter

## Describe the bug
Error when using _app.js with the using-with-router example under ie10 (router is undefined), but ie11 is ok

## To Reproduce
https://github.com/VanquisherMe/using-with-router-app

1. yarn
2. npm run dev

## Expected behavior
ie10 withRouter get router

## Screenshots
![sg mv914t _j nlhct cq](https://user-images.githubusercontent.com/4927398/47264155-1fedbf80-d543-11e8-9aaa-a196d2332997.png)

## System information
 - OS: Windows
 - Browser IE10
 - Version of Next.js: 7.0.2

## Additional context
If you delete the _app.js file then it is OK
 it seems like it's some limitation in Babel for hoisting static props. 
https://github.com/zeit/next.js/blob/canary/packages/next/pages/_app.js#L17
https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/router/with-router.js#L26
Maybe you should stop static hoisting

**Comment by hugotox** [comment]
IE10 is not supported since Jan, 2016
https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support

**Comment by timneutkens** [comment]
ie10 is not supported by default in Next.js
