### ISSUE TITLE
Running Yarn dev with the with-webassembly example shows crash 

### ISSUE THREAD

**Issue by PSPanesar** [zeit/next.js#5494]
# Examples bug report
When running the with-webassembly example the Yarn dev crashes

## Example name
with-webassembly

## Describe the bug
When running the Yarn dev command on the with-webassembly example the program crashes with the error message:

(node:16496) UnhandledPromiseRejectionWarning: Error: Invalid arguments
    at filesize

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Install yarn create next-app --example with-webassembly with-webassembly-app
2. Yarn
3. Yarn dev

## Expected behavior
Yarn dev server to start up and show the app with the wasm integration.

## System information
 - OS: macOS
 - Browser (if applies) chrome
 - Version of Next.js: 7.0.2

**Comment by JeroenKnoops** [comment]
I've tried to fix this by updating `webpack` (4.27.1) , `webpack-hot-middleware` (2.24.3) and `webpack-sources` (1.3.0), but unfortunately the wasm file is still saved as `[object ArrayBuffer]` in the static folder when dynamically loaded. Will investigate it further.

**Comment by meuwka** [comment]
it works on Next.js: 8.1.0

**Comment by timneutkens** [comment]
Thanks @meuwka!
