### ISSUE TITLE
Possible spelling mistakes

### ISSUE THREAD

**Issue by EdenLiang** [zeit/next.js#5496]
# Bug report

## Describe the bug
In the readme.md, at 'Routing | Intercepting popstate' section
There is a describe 'If you return a falsy value from beforePopState'

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to 'https://github.com/zeit/next.js#intercepting-popstate'
2. Search 'falsy'
3. See error

## Expected behavior
I suppose it should be changed from
If you return a **falsy** value from beforePopState
to
If you return a **false** value from beforePopState

## Screenshots

![falsy](https://user-images.githubusercontent.com/9131600/47271037-c3bc8700-d5a6-11e8-8317-6701ec3803a6.png)

**Comment by timneutkens** [comment]
Feel free to send a pull-request 😄

**Comment by zackkrida** [comment]
Yes @EdenLiang falsy is a valid term not a typo.

**Comment by curran** [comment]
IMO this issues should be closed. The sentence 'If you return a falsy value from beforePopState' is perfectly valid.

Falsy is the opposite of truthy. These are proper terms in JS. They are distinct from false and true. Falsy values act like `false` in `if` statement, and truthy values act like `true` in `if` statements.

**Comment by curran** [comment]
It seems a change has been merged that changes this https://github.com/zeit/next.js/pull/5513/files

IMO that phrasing

```
If you return a `false` value from `beforePopState`, `Router` will not handle `popstate`
```

is overly verbose, and could be simplified to

```
If you return `false` from `beforePopState`, `Router` will not handle `popstate`
```
