### ISSUE TITLE
Show meaningful error when using `module.exports`

### ISSUE THREAD

**Issue by kapv89** [zeit/next.js#552]
![screenshot from 2016-12-29 00-20-33](https://cloud.githubusercontent.com/assets/1023032/21529027/be09c164-cd5c-11e6-8398-a0096f2ee106.png)

Here is the relevant code, from `pages/index.js`
```js
const React = require('react');

const {sayHa} = require('app/actions');

module.exports = () => (
  <div>
    <h2>Welcome</h2>
    <h3>{sayHa()}</h3>
  </div>
);
```

And this is from `next.config.js`
```js
module.exports = {
  webpack: (config) => {
    config.resolve.modulesDirectories.push(__dirname);
    return config;
  }
};
```

**Comment by nkzawa** [comment]
I guess that's because of `module.exports`. Can you try `export default` instead ?

**Comment by kapv89** [comment]
changing to `export default` fixed this. Thanks!
