### ISSUE TITLE
ie11 Error of crypto-promise

### ISSUE THREAD

**Issue by newdoo** [zeit/next.js#5522]
# Bug report

## Describe the bug

example [with-polyfills](https://github.com/zeit/next.js/tree/canary/examples/with-polyfills)
ie11 Error of crypto-promise

## To Reproduce

1. yarn add crypto-promise
2. import crypto from 'crypto-promise'

## Expected behavior

No console error.

## Screenshots
![1](https://user-images.githubusercontent.com/37576416/47473952-d4435a80-d84f-11e8-87b3-71378b467462.PNG)
![2](https://user-images.githubusercontent.com/37576416/47473953-d60d1e00-d84f-11e8-8eb5-6ccbb518a384.PNG)

## System information
 - OS: Windows 10 Pro
 - Browser: IE11
 - Version of Next.js: "latest"

**Comment by timneutkens** [comment]
Seems like you're using a node.js only module on the client side.
