### ISSUE TITLE
Bluebird cancelation not compatible with Next.js 7

### ISSUE THREAD

**Issue by mherodev** [zeit/next.js#5527]
# Bug report

## Describe the bug

As far as I can tell, there is no top-level location to configure Bluebird promises to be cancellable. 

Previously in Next.js 6, the top of `_app.js` worked, but now it appears a promise is being dispatched before this file is referenced, blocking promise cancelation configuration.

## To Reproduce

Create an app with the following code at the top of `_app.js`:

```jsx
import Promise from 'bluebird';
Promise.config({ cancellation: true });
```

## Expected behavior
Promise cancellation is enabled, rather than a console error noting that cancellation cannot be enabled once a promise has been dispatched.

## System information
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
Promise cancellation is not a standard right 🤔 So I don't think we should change anything in Next.js to support this.

**Comment by timneutkens** [comment]
I assume the issue is that we call `import()` in dev mode because of a bundling issue.
