### ISSUE TITLE
Babel Language Ambiguity 

### ISSUE THREAD

**Issue by IanMitchell** [zeit/next.js#553]
The docs say "Although it's not required, you will need to add next/babel as a preset. That's the default preset we use for all Next.js apps."

'Not required' followed by 'need to' isn't clear. In the app I have, not including `next/babel` as a preset broke the compilation as well, so I think it might actually be required?

**Comment by rauchg** [comment]
+1 for re-wording. 

- It's not required to define a `babelrc`
- If it's defined, we're going to consider it _the source of truth, therefore it needs to define _what next needs as well_, which is the `next/babel` preset.

**Comment by timneutkens** [comment]
Fixed 👍
