### ISSUE TITLE
Suggestion needed about caching HTML using workbox

### ISSUE THREAD

**Issue by manishbhatt94** [zeit/next.js#5530]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

Link to question on Spectrum Chat:
https://spectrum.chat/thread/faba5491-db40-4721-97b5-2792e2fd763c

Need some suggestion on how to cache page HTML document generated by Next.js using workbox. Please refer above Spectrum Chat thread link

**Comment by timneutkens** [comment]
As per the issue template I'm going to close this issue.
