### ISSUE TITLE
Document the use of dependencies vs devDependencies

### ISSUE THREAD

**Issue by jrop** [zeit/next.js#5531]
# Question about Next.js

_(I posed a question [over in spectrum](https://spectrum.chat/?t=d2490141-0b5d-4ee3-8491-fc7f30de0184), but got no answer; I hope I am not spamming here)_

First things first: I am absolutely loving Next.JS!  It is so much simpler to use than other React frameworks out there, and gives a lot of stuff out-of-the-box in a simple-to-grasp way.  Thanks!

Now for my question: the documentation seems kind of slim on how production builds work: what is needed as far as dependencies go?  Are all the DevTools shipped (babel, WebPack, etc.) in production?  Also, when I add a framework, (say material-ui), does that need to be in my `dependencies` or `devDependencies`?

I ask because, when building for Docker, I would like to create the smallest image possible, and when I add a framework (such as `material-ui`) I am accustomed to adding it as a devDependency.  However, with NextJS, it is unclear to me what the runtime needs are: does NextJS need such dependencies for SSR, etc.?

If sufficient explanation is given here, I wouldn't mind condensing it into a PR for the docs, as I wish this was more clearly explained.

Thanks!

**Comment by timneutkens** [comment]
You can read this: https://github.com/zeit/next.js/issues/4496
