### ISSUE TITLE
Render serverside errors in dev mode to browser.

### ISSUE THREAD

**Issue by craigcbrunner** [zeit/next.js#5536]
# Feature request

## Is your feature request related to a problem? Please describe.
When you get errors on the server side in NextJS, it is annoying having to scroll through a bunch of logs in the console to figure out what went wrong.

## Describe the solution you'd like
It would be really nice if the server side in dev mode had a way of catching the server side errors and rendering them to the browser nicely, so you can quickly see the error(like client side does)

## Describe alternatives you've considered
Haven't thought of any others.

## Additional context
N/A

**Comment by timneutkens** [comment]
> It would be really nice if the server side in dev mode had a way of catching the server side errors and rendering them to the browser nicely, so you can quickly see the error(like client side does)

This already happens.

**Comment by craigcbrunner** [comment]
How come when I am using `npm run dev` and there is a server error I only see it on the console? The browser just renders "Internal server error."

**Comment by timneutkens** [comment]
It highly depends on what you're doing / where you cause a crash.
