### ISSUE TITLE
When deploying on heroku NODE_ENV starts as "production" then changes to "development" when requesting pages.

### ISSUE THREAD

**Issue by MatthewRandle** [zeit/next.js#5538]
# Bug report

When I deploy my app to heroku the NODE_ENV is set to production initially (as intended), but once I request a page it gets set to development.

## Expected behavior
NODE_ENV is set to production when deployed to heroku

## System information
 - Version of Next.js: [7.0.2]

## Additional context

This is what my heroku-postbuild, start and build scripts look like:

`"build": "NODE_ENV=production next build",
"start": "NODE_ENV=production node server/index.js",
heroku-postbuild": "next build"`

**Comment by HaNdTriX** [comment]
Looks like you are not setting the `dev` flag in your `server.js` file.

```js
const app = next({ 
  dev: process.env.NODE_ENV !== 'production'
})
```

You need to do this explicitly.


https://github.com/zeit/next.js#custom-server-and-routing

**Comment by MatthewRandle** [comment]
I was actually doing that but somehow managed to put NODE_DEV instead. God knows how... but thanks anyway would probably have took me a while to notice it
