### ISSUE TITLE
webpack-hmr never received on the Browser

### ISSUE THREAD

**Issue by james-ff** [zeit/next.js#5546]
# Bug report
Any time i start my Next.js app locally (haven't seen if this affects production yet) the tab remains permanently in a loading state even after everything is loaded. I opened dev tools and looked at networking and found that "http://localhost:3002/_next/webpack-hmr" is never returned (the only network call without any response).

## Describe the bug

http://localhost:3002/_next/webpack-hmr never gets returned to the browser, which is causing all sorts of issues.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Load Next.js app in dev mode

## Expected behavior
Loading state finishes in tab when everything works, and normal usage of Next.js app is possible.

## System information
 - OS: macOS
 - Browser Firefox
 - Version of Next.js: 7.0.1

## Additional context

Potential contributors?
- Version of Webpack: 4.23.1
- Version of dotenv-webpack: 1.5.7
- Version of ESLint: 5.8.0

**Comment by james-ff** [comment]
If anyone could suggest a quick fix, or has information about when a patch will be released that would be fantastic. Thanks

**Comment by timneutkens** [comment]
I've updated the title of this issue. If something is "critical" and a "bug" *always* provide a clear and concise reproduction.

There is no reproduction included and we have tests for HMR, these tests are passing.

If you're saying `webpack-hmr` is never finished, this is correct, it's an https://developer.mozilla.org/nl/docs/Web/API/EventSource endpoint that keeps sending data.

**Comment by james-ff** [comment]
Hello @timneutkens, Thank you for the feedback, I shall bear that in mind in future.

However, I'm not entirely sure how to offer a reproduction because I do not understand how to replicate the Issue I am seeing. But, I am still seeing it, and it is causing a lot of issues for me / halting my work (despite efforts to rollback dependency versions with no luck).

I believe that you are correct that I inaccurately identified webpack-hmr as the cause. What I am seeing, which was not the case before, is: 
- Much longer load times
- A continual loader on any tabs that my app is open on
- Unable to use dropdowns and other interactive inputs for some reason
- All routing functionality is unavailable

After waiting for a few minutes I see the following warning in the console:
```
Invalid HMR message: {"action":"reload","data":["/"]}
Error: No router instance found.
You should only use "next/router" inside the client side of your app.
```
- I haven't modified my usage of next/router in a long time, and it has been working as normal until today.

**Comment by timneutkens** [comment]
I'm not sure what we can do based on this description, we really need a reproducible example to be able to look into this issue, also for when there is an issue to add tests for an edge case (if there is any).

**Comment by mrtkrcm** [comment]
It's pretty strange that I'm having exact same issues as you describe and it started to happen after migrating to the 7.0.0 and continues with the 7.0.2

My app is pretty big and getting dynamically created by API's so, it will be pretty difficult to create a reproducible version but I will try whenever I find a time to mock API responses.

**Comment by sikhote** [comment]
Some info that may help debug: I am seeing the same issue within Firefox only within the last day or two, but Chrome continues to work as expected on the same `localhost` URL.

**Comment by timneutkens** [comment]
Like I said, I can't debug without a clear reproduction, so I'll probably have to close this issue as not reproducible.

**Comment by james-ff** [comment]
Issue hasn't re-appeared yesterday or today, consequently I'm not entirely sure what caused the issue, or even how it was resolved. Hopefully it was simply a firefox bug that was patched in the background.

**Comment by edelgado** [comment]
Hmm, have you folks noticed that the browser keeps doing a request GET request for `/_next/webpack-hmr` even after the app is stopped?

This is what happened to me:

1. Ran a next.js app.
2. Browsed to localhost:3000
3. Stopped the app.
4. Started a Rails app that also uses port 3000
5. The Rails app gets a GET "/_next/webpack-hmr" request every 10 seconds or so.

Weird!

**Comment by timneutkens** [comment]
@edelgado you probably still had a browser tab open, it tries to reconnect every few seconds when the connection is lost.

**Comment by edelgado** [comment]
@timneutkens 🤦‍♂️ you are right. Thanks 😄
