### ISSUE TITLE
getInitialProps returns an empty object

### ISSUE THREAD

**Issue by mlnor27** [zeit/next.js#5548]
Hi everyone, 

Sorry in advance if it's duplicated. Feel free to link me to the original issue

# Bug report

getInitialProps is called but doesn't return any props

## To Reproduce

I'm using a combination of all of the examples listed below :
- custom-server-express
- with-next-css
- with-next-routes
- with-react-i18next
- with-redux

## Expected behavior
Returning the props and access them in the render method and all the other lifecycle methods

## Code

My routes are declared in /src/routes.js and it looks like this
```
const routes = require('next-routes')

module.exports = routes()
  .add({ name: 'HomePage', pattern: '/', page: '/Home/Home' })
  .add('test')
```

and here is the code of my homepage in /src/pages/Home/Home 
```
class HomePage extends Component {
  static async getInitialProps({ reduxStore, query, req }) {
    const isServer = !!req
    if (isServer) {
      const locale = utils.parseLanguage(req.headers['accept-language'])
      const device = utils.parseUA(req.headers['user-agent'])
      const { pathname } = utils.parseUrl(req.url)
      await Promise.all([
        reduxStore.dispatch(detectDeviceType(device)),
        reduxStore.dispatch(updateAppRoute({ pathname, query })),
        reduxStore.dispatch(fetchChartsWeek(locale)),
        reduxStore.dispatch(fetchTrendings(locale)),
      ])
    }
    return { isServer, query }
  }

  componentDidMount() {
    console.log(this.props) // everything i need but no query or isServer...
```

a simpler exemple in /src/pages/test.js
```
  static async getInitialProps({ req }) {
    const isServer = !!req
    return { isServer }
  }

  render() {
    console.log(this.props) // {}
```

I really need to know whether the page is being rendered by the server or the client as i don't want to show placeholders when it is SSR and only display them when we naviguate to the page client side, so that in componentDidMount i would like to show placeholders and fetch data only when isServer = false if that makes sense.

Does anyone already accountered this issue ?
I really would like to switch to Nextjs. Currently we have our code base running in a CRA setup. We now have trouble with SEO so switching to nextjs seemed to be a great solution. However it is those kind of issues that are keeping me from adopting it completely :(

Any help or suggestions would be really appreciated

Thanks in advance

**Comment by mlnor27** [comment]
My bad, it was my mistake

In `_app.js` i forgot to pass pageProps to the page component, so i wrote <Component /> instead of <Component {...pageProps} />

Sorry for the inconvenience

**Comment by muco-rolle** [comment]
> My bad, it was my mistake
> 
> In `_app.js` i forgot to pass pageProps to the page component, so i wrote `<Component />` instead of `<Component {...pageProps} />`
> 
> Sorry for the inconvenience

Thank you bro
