### ISSUE TITLE
Ahead-of-time GZIP compression

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#555]
Upon `next build`. This is for the next major.
- [x] For main build files - https://github.com/zeit/next.js/pull/565
- [x] For JSON pages - https://github.com/zeit/next.js/pull/571
- [ ] Allow to extend compression via `next.config.js`- https://github.com/zeit/next.js/pull/657

**Comment by arunoda** [comment]
So, we detect the accept-gzip header and server gzipped version if so. 
Okay, that's a good idea.

**Comment by timneutkens** [comment]
Closing this in favor of #984
