### ISSUE TITLE
Nginx router mapping issues with nextJS

### ISSUE THREAD

**Issue by itranga** [zeit/next.js#5559]
Hi ,
I have the following issues with the deployment in Nginx .Please help me to sort out .

Ex: www.test.com ---->it will show wordpress site (this is working )
www.test.com/order/ ---->it should show nextJS site (this is the one need to be sort out.)

but in the current situation it shows the page not found.
"Page Not Found The page /_error does not exist."

My nginx configuration has been given below .

location /site {
gzip_static on;

proxy_pass http://127.0.0.1:3000;
proxy_redirect off;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_max_temp_file_size 0;
client_max_body_size 10m;
client_body_buffer_size 128k;
proxy_connect_timeout 90;
proxy_send_timeout 90;
proxy_read_timeout 90;
proxy_buffer_size 4k;
proxy_buffers 4 32k;
proxy_busy_buffers_size 64k;
proxy_temp_file_write_size 64k;
# proxy_cache STATIC;
proxy_cache_valid 200 30m;
proxy_cache_valid 404 1m;
proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
proxy_ignore_headers Set-Cookie;
proxy_hide_header Set-Cookie;
proxy_hide_header X-powered-by;
}

Thanks

**Comment by timneutkens** [comment]
Not sure what to do with this issue, it's not following the issue template.
