### ISSUE TITLE
Ability to enable minification for a non production build

### ISSUE THREAD

**Issue by tscritch** [zeit/next.js#5560]
# Ability to enable minification for a non production build

## Problem - Minification only enabled for when server is in production environment. 
My team has several servers for development, qa, uat, and production. The environment is set to their respective names within the server and custom next server. We are currently running into an issue where we are using variables based on the environment but cannot benefit from the minification (and WAY faster speed) in other environments besides production. Environments like qa and uat will need these speeds to test and use the site effectively. Unless I'm missing something in the docs or webpack config I don't currently see a way to enable this. 

## Solution
An array of environment names on which you would like minification to be run within `next.config.js`
OR
If there is already a solution for this I would love to submit a PR to the docs to add it in.

Any discussion or recommendations are welcome. I would love to hop in and make any of these changes. Thanks for the help!

**Comment by timneutkens** [comment]
It sounds like you're not deploying correctly and booting the development server in the qa environment. It basically comes down to running `next build` and setting `dev: false` in your custom server, assuming you have one. Otherwise use `next start`.
