### ISSUE TITLE
next.config.js is ignored for "next build" 

### ISSUE THREAD

**Issue by sheerun** [zeit/next.js#5564]
Next.js version: 7.0.3-alpha.0

# Bug report

With following next.config.js:

```
module.exports = {
  webpack(config, options) {
    throw new Error('sdfas')
  }
}
```

```
next build
```

finishes successfully. also any plugins in next.config.js are ignored

**Comment by timneutkens** [comment]
You should by no means be using the alpha version. It's highly experimental.

**Comment by sheerun** [comment]
Yeah I know I just wanted to reproduce issue with webpack configuration on newest version of next.js just to be sure it still happens, just to discover there's no webpack anymore
