### ISSUE TITLE
Webpack building logs swallows plugin/loader logs

### ISSUE THREAD

**Issue by egislook** [zeit/next.js#5570]
## Next swallows logs with Webpack building logs

Console.log gets swallowed by building logs while I'm trying to use it inside Webpack loaders or plugins.

## To Reproduce

Just try to use console log in custom Webpack loader or plugin. I get the file for every content but I can not get console.log

#### loader.js
```javascript
module.exports = function(content, map, meta) {
  console.log('loader log');
  fs.writeFileSync('./dump/loader_' + new Date().getTime() + '.css', String(content + ' CLASSES: '));
  return content;
};
```

#### next.config.js
```javascript
const withCSS = require('@zeit/next-css');

module.exports = withCSS({
  webpack: (config, { dir, dev, isServer, defaultLoaders }) => {
    
  config.module.rules.push({
      test: /\.(js|jsx)$/,
      exclude: [/node_modules/],
      include: [/components/, /elements/, /pages/],
      use: 'loader'
    });

    return config
  }
})
```

## System information
 - Next.js: v7.0.2
 - Node.js: v11.0.0

## Additional context

The problem can be avoided by turning of logs in nex.config.js but as much as I know there is no config/command that could do that.

I know it could be done this way but I dont want to use custom server in this case.
#### server.js
```javascript
const app = next({ dev, quiet: true });
```

**Comment by egislook** [comment]
Anyone else is facing the issue?

**Comment by IanMitchell** [comment]
I was just about to file an issue on this - I would love to have an option to output logs sequentially instead of using FriendlyErrorsWebpackPlugin

**Comment by timneutkens** [comment]
`FriendlyErrorsWebpackPlugin` actually doesn't delete output, webpackbar does however. I'm assuming this was fixed in the latest version of webpackbar, which is out on `next@canary`. I'll close the issue for now, feel free to verify and get back if this isn't the case.

**Comment by IanMitchell** [comment]
Is there a dependency coming in through FriendlyErrors? Disabling it definitely improves the log setup that I see. With it enabled there are still issues on Canary, although it's gotten better. I'm seeing a single Client / Server line now that doesn't swallow up things. With FriendlyErrors not stripped out, there are some weird spacing and padding issues including a post-compile terminal jump.

I'm using the Next API in an app with a bunch of `debug` logs for context - it's not a pure Next app.

**Comment by Soundvessel** [comment]
I am not using a custom server but instead exporting a static app to `/out` that is served on a Tomcat server. The export appears to consume all my console.logs. Is there some way to override this behavior?
