### ISSUE TITLE
Router sometimes not available to browser  

### ISSUE THREAD

**Issue by james-ff** [zeit/next.js#5577]
# Bug report

## Updates

1 - _This seems to only affect Firefox, (Tested with Safari and Chrome)_

## Describe the bug

Today my Next.js app worked fine until about 30 minutes in of use, after which it loads indefinitely and sends this error after some time.

Browser log:
```
Invalid HMR message: {"action":"reload","data":["/itinerary/builder"]}
Error: No router instance found.
You should only use "next/router" inside the client side of your app.
```

Server Log:
```
Using browser-only version of superagent in non-browser environment
```

## To Reproduce

In all honesty I don't know how exactly to reproduce this issue, as I don't uderstand how it has arrisen (the router system is somewhat a mystery to myself, a user of next.js not a contributor). I will include everything that I believe may be helpful however, and _**I will be forthcoming with anything else that would be helpful to someone in resolving this issue on request**_, (list of dependency versions which may be contributing to this for example).

In my experience:
1. Write Next.js app that uses withRouter per-component to access the router
2. Use next.js app for some time
3. App slows and loads indefinitely, sends warning message included above
4. App is rendered unusable, no interaction possible

Router per-component Example:
- (This is the only thing that I can think might be causing the issue, so I shall include an example of the pattern I am using to access router in many components within my app)

```jsx
import React from 'react'
import PropTypes from 'prop-types'

import { withRouter } from 'next/router'

class ExampleComponent extends React.Component {
  static propTypes = {
    router: PropTypes.object.isRequired
  }

  render () {
    const { router } = this.props
    return (
      {/*...Component Render*/}
    )
  }
}

export default withRouter(ExampleComponent)
```

## Expected behavior

Normal usage of Next.js app

## Screenshots

Indefinite Loading
![screen shot 2018-11-02 at 12 57 19](https://user-images.githubusercontent.com/1874352/47916736-15b2b600-de9f-11e8-84bb-c7674cf3e8a8.png)

Warning Message
![screen shot 2018-11-02 at 12 57 02](https://user-images.githubusercontent.com/1874352/47916733-12b7c580-de9f-11e8-9238-cbf603bf0f39.png)

## System information
 - OS: macOS@10.14
 - Browser Firefox@latest
 - Version of Next.js: 7.0.2

## Additional context

Have been developing my app since February and this is the first time this bug has arrisen. In the last month most changes have been top-level (not changing the setup of the app in respect to Next.js much, which leads me to believe this is due to a Next.js version change, or a dependency change)

**Comment by james-ff** [comment]
This issue has not re-occured yet, as such I will close this ticket. I will re-open if it does.

**Comment by corysimmons** [comment]
I got this `Using browser-only version of superagent in non-browser environment` message in terminal with `npx create-next-app foo` and a really simple implementation of Auth0.

In browser console I get `Warning: Text content did not match. Server: "Login" Client: "Logout"`
