### ISSUE TITLE
Next/less creating common chunk and page specific chunks

### ISSUE THREAD

**Issue by illogikal** [zeit/next.js#5578]
```
#/static/pageA.less
@import './common.less';
@import './pageA/stylename.less';
```

```
#/static/pageB.less
@import './common.less';
@import './pageB/stylename.less';
``` 

```
#/pages/A.js
import 'static/pageA.less';
...
``` 

```
#/pages/B.js
import 'static/pageB.less';
...
``` 

```
#/next.config.js
const withCSS = require('@zeit/next-css')
const withLess = require('@zeit/next-less')
module.exports = withCSS(withLess({
  lessLoaderOptions: {
    javascriptEnabled: true
  }
}))
```

Next Version: next.canary
Next Plugins: next.canary
How do I force the two page entry files to be separate chunks with a common chunk? I got the impression this was possible in next without too much hacking of the webpack config...

**Comment by timneutkens** [comment]
We have an issue template, please follow it 🙏 

Besides that you have to override the styles commonschunk, but that's going to be guaranteed to break in the near future.
