### ISSUE TITLE
Typescript-custom-server failing on windows and not using supplied tsconfig.server

### ISSUE THREAD

**Issue by TimoWestland** [zeit/next.js#5596]
typescript-custom-server: https://github.com/zeit/next.js/tree/canary/examples/custom-server-typescript

## Describe the bug
In the typescript-customer-server example, a nodemon.json and a tsconfig.server.json is supplied. This example has two issues: 
 1. It doesn't run on windows based machines (syntax issue) because of this line: https://github.com/zeit/next.js/blob/canary/examples/custom-server-typescript/nodemon.json#L4
 2. It doesn't actually use the supplied tsconfig.server.json

## To Reproduce
Scaffold a next.js app with the typescript-custom-server example on a windows machine. 
Run `npm run dev`
The following error will show up:
```
[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: server/**/*.ts
[nodemon] starting `ts-node --typeCheck --compilerOptions '{"module":"commonjs"}' server/index.ts`
undefined:1
'{module:commonjs}'
^

SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parse (C:\Users\wen.f.li\Documents\eyewishproject\eyewishv4\eyewish\node_modules\ts-node\dist\index.js:85:45)
    at Object.<anonymous> (C:\Users\wen.f.li\Documents\eyewishproject\eyewishv4\eyewish\node_modules\ts-node\dist\bin.js:72:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
[nodemon] app crashed - waiting for file changes before starting...
```

## Expected behavior
To be able to run on windows.
To actually use the tsconfig.server.json

If it uses the tsconfig.server.json, it wil set the compile target to commonjs, which makes `--compilerOptions '{"module":"commonjs"}'`  line redundant.

## System information
 - OS: Windows 10
 - Version of Next.js: 7.0.2

## Possible fix:
I've changed the nodemon.json config to look like this: 
```json
{
  "watch": ["server/**/*.ts"],
  "execMap": {
    "ts": "ts-node --project tsconfig.server.json --typeCheck"
  }
}
```

This fixes the build on windows, and uses the tsconfig.server.json. The compiled output is the same as with the original nodemon.json. I can make a PR to change this if this is the setup we want for this example.

**Comment by Tzelon** [comment]
Same issue with https://github.com/zeit/next.js/tree/canary/examples/with-ts-node
Same fix. 
thanks @TimoWestland
