### ISSUE TITLE
npm install -g next?

### ISSUE THREAD

**Issue by purplecones** [zeit/next.js#56]
Following the readme example, it indicates to install next with `npm install next --save`. I couldnt get the example to work this way.

`zsh: command not found: next`

Shouldn't this be `npm install -g next` so that the next command is global?

**Comment by davemo** [comment]
@purplecones I just added a script to `package.json` like so:

```json
"scripts": {
    "start": "next"
  },
```

and then ran `npm start`

**Comment by impronunciable** [comment]
@purplecones usually you use npm scripts. Npm knows how to locate next inside the package. It's recommended to install it locally mostly because you can have different versions in different projects

```
{
  "name": "my-app",
  "dependencies": {
    "next": "*"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
}
```

**Comment by purplecones** [comment]
@davemo @impronunciable oh ok. Any reason why this CLI from zeit should be used this way? `now` and `ns` that I use are all global.

**Comment by impronunciable** [comment]
@purplecones with now you are interfacing the `now` API and you'll want to be always at the last version. Is not the case of a front end framework

**Comment by fabricionaweb** [comment]
`next init` probably better work and sense for global installations

**Comment by purplecones** [comment]
@impronunciable @fabricionaweb thanks
