### ISSUE TITLE
nextjs parameterized-routing issue with multiple parameters

### ISSUE THREAD

**Issue by amit0shakya** [zeit/next.js#5603]
I tried parameterized-routing example for my project I need to declare 3 parameters so I add 2 more in this example, I am not getting correct way. I made few changes in example:

index.js

>  <ul>
    <li><Link href='/blog?id=first&uid=1&vals=abc' as='/blog/first/1/abc'><a>My first blog post</a></Link></li>
    <li><Link href='/blog?id=second&uid=2&vals=xyz' as='/blog/second/2/xyz'><a>My second blog post</a></Link></li>
    <li><Link href='/blog?id=last&uid=3&vals=aaa' as='/blog/last/3/aaa'><a>My last blog post</a></Link></li>
  </ul>

my Blog.js

> export default class extends React.Component {
  static getInitialProps ({ query: { id,uid,vals } }) {
    return { id,uid,vals }
  }
  render () {
    return 
    <div>
     <p> My {this.props.id} blog post </p>
      uid ={this.props.uid}<br /> vals ={this.props.vals}
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
      </p>
    </div>
  } }

Issue is when I navigate this through index.js it works fine, but when I directly put route with parameter on addressbar it shows error page could not be found. What should I need to do for impliment multiple . parameters, For my project I share links to user's email with dynamic parameter, and I want user can direcly reach to his dynamic content on my website with that link.

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/issues/2833#issuecomment-414919347
