### ISSUE TITLE
Next export takes a lot of time for ~240 pages

### ISSUE THREAD

**Issue by schoenwaldnils** [zeit/next.js#5605]
We use next.js for building our website (obviously).
Our website generates dynamic landingpages. This data comes from contentful.
We now count over 240 different pages.
Each page is staticly generated in our deployment build using the `exportPathMap`.

Our problem now is that each page uses time to generate. 
So each new page is adding up to our build time.

We started with a few pages and about **1:30min** build time in travis.
Now we're at about **6min** 😕

The exporting part of the build is for ~240 pages `181s`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Have about ~240 pages
2. `next build && next export`

## Expected behavior

We'd like that the pages would not been been generated serial but parallel to reduce the time to export

## System information
 - Node: `10.9.0`
 - Next.js: `7.0.2`

**Comment by timneutkens** [comment]
Feel free to revive this PR: https://github.com/zeit/next.js/pull/4765

**Comment by timneutkens** [comment]
Besides that there's this PR: https://github.com/zeit/next.js/pull/5597 that I merged yesterday

**Comment by schoenwaldnils** [comment]
@timneutkens 
I saw the multi-threading PR but could't find it while writing this issue ^^

#5597 sounds really good. Can I use it in the lates canary?

**Comment by timneutkens** [comment]
> #5597 sounds really good. Can I use it in the lates canary?

Yes, you'll have to cache `node_modules/.cache` and `.next/records.json`

**Comment by timneutkens** [comment]
Fixed in #5870
