### ISSUE TITLE
Pages reload in dev mode when using Link

### ISSUE THREAD

**Issue by paulomunoz** [zeit/next.js#5606]
Hi, I am having an same issue which I believe to be **very similar** to https://github.com/zeit/next.js/issues/2147. As 2147 is closed, and is related to a previous (much older) version, I am creating a fresh new issue ticket.

In dev mode **only**, clicking a Link to any page causes a reload of the **new page**.

# To Reproduce:
- Click a `<Link>` wrapping an `<a>` to a page

# Expected behaviour:
- Page compiles
- You go to that page

# Perceived behaviour:
- Page compiles
- New page appears briefly
- Browser reloads the **new** page's URL - that differs from 2147, which would load the previous page's instead.

# System information
- Node `8.11.3`
- Next.js `7.0.1`
- Express `4.16.4`

Seeing this in Chrome. I'm noticing that the server is showing a 200 to the new page's URL, so it's a full page load rather than just re-rendering client side.

-- Further information --
- I am using a custom server (express) and calling `nextjs({ dev }).render`

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/issues/2833#issuecomment-414919347
