### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by spacedragon** [zeit/next.js#561]
Following code  

```
import React from 'react'

export default class MyPage extends React.Component {
  static async getInitialProps({ req, res }) {
    if (!req.user) {
      res.redirect('/login')
      res.end()
    }
  }

  render() {
    return (
      <div>
      </div>
    )
  }
}
```

will throw a error

` Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:359:11)
    at sendHTML
`

**Comment by spacedragon** [comment]
I think problem is here :  
in  _render.js_

`
export async function render (req, res, pathname, query, opts) {
  const html = await renderToHTML(req, res, pathname, opts) // doRender returned here if response finished
  sendHTML(res, html)    // but this line will still run  
}

export function renderToHTML (req, res, pathname, query, opts) {
  return doRender(req, res, pathname, query, opts)
}
`

` 
async function doRender (req, res, pathname, query, {
.....
// the response might be finshed on the getinitialprops call
  if (res.finished) return
`

**Comment by nkzawa** [comment]
@spacedragon good catch !!!
