### ISSUE TITLE
next.js + react-native-web + react-native-vector-icons

### ISSUE THREAD

**Issue by kuznetsov-online** [zeit/next.js#5614]
How can I use next.js + react-native-web + react-native-vector-icons?

I have tried:
https://github.com/kuznetsov-online/next-web-icons

but have received error:
```
./node_modules/react-native-vector-icons/lib/create-icon-set.js 43:21
Module parse failed: Unexpected token (43:21)
You may need an appropriate loader to handle this file type.
| 
|   class Icon extends PureComponent {
>     static propTypes = {
|       allowFontScaling: PropTypes.bool,
|       name: IconNamePropType,
```

**Comment by timneutkens** [comment]
Sounds like the module is publishing untranspiled code, so you'll probably want to use https://github.com/martpie/next-plugin-transpile-modules
