### ISSUE TITLE
ERR_IPC_CHANNEL_CLOSED when run `yarn testonly`

### ISSUE THREAD

**Issue by Jero786** [zeit/next.js#5621]
# Question about Next.js

Hi, I'm trying to collaborate with my first PR in order to update but after install locally my project and follow all the steps from https://github.com/Jero786/next.js/blob/canary/contributing.md, 
Questions should be posted on https://spectrum.chat/next-js, but then when I execute `yarn testonly` I see the following error over and over again during test suit are exequiting: 
```


....


Error: an-expected-error-in-gip
    at Function.getInitialProps (/projects/forks/next.js/test/integration/basic/.next/server/static/development/pages/hmr/error-in-gip.js:155:19)
    at _callee$ (/projects/forks/next.js/packages/next-server/dist/lib/utils.js:100:30)
    at tryCatch (/projects/forks/next.js/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/projects/forks/next.js/node_modules/regenerator-runtime/runtime.js:288:22)
.....

events.js:167
      throw er; // Unhandled 'error' event
      ^
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:628:16)
    at reportSuccess (/projects/forks/next.js/node_modules/jest-worker/build/child.js:59:11)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:632:35)

```
I'm doing wrong? or just I miss some step which could be the cause of this bug?

**Comment by timneutkens** [comment]
Hmmm weird, I haven't seen that before, cc @HaNdTriX 

Feel free to open a pull-request and the tests will run in our CI so that you're unblocked.

**Comment by HaNdTriX** [comment]
Hmm haven't seen that. either. Can you provide some more infos about your setup (node version, os) etc?

**Comment by Jero786** [comment]
@HaNdTriX sure

```
Node: v10.10.0
NPM: 6.4.1
OS: MacOs Sierra 10.13.6 
```

**Comment by HaNdTriX** [comment]
can your try to run:

```js
yarn testonly --runInBand
```

Does this raise the same exception?

**Comment by Jero786** [comment]
Hi @HaNdTriX, not seems like raise other exception, let me upload a log file with the entire log after execute the command that you mention.
[log-faild-nextjs.txt](https://github.com/zeit/next.js/files/2558998/log-faild-nextjs.txt)

**Comment by HaNdTriX** [comment]
@Jero786 Thanks for providing the log file. In the meantime I could reproduce the non deterministic test failures on Mac OS. 

Until we fixed this issue you can restrict the tests by running only a sub-portion of the tests by using `testPathPattern` e.g.:

```
yarn testonly --testPathPattern "basic"
```

**Comment by Jero786** [comment]
@HaNdTriX Thank you!
