### ISSUE TITLE
HMR Stops Working If Project Name Has .next Suffix

### ISSUE THREAD

**Issue by troysandal** [zeit/next.js#5626]
# Bug report

## Describe the bug

If your next.js project folder has the suffix `.next` then HMR will not work in that project.  Changing the suffix fixes the problem.

## To Reproduce
I've [created a repository](https://github.com/troysandal/nextjs.next) with instructions on how to reproduce the bug.  TLDR - Rename any of your local next.js projects to have a suffix of `.next` then see if HMR keeps working, it won't.

## Expected behavior
HMR should work regardless of the parent folder name.

## Screenshots
n/a

## System information
 - OS: macOS 10.14.1
 - Browser (if applies): n/a
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
Fixed in #5544
