### ISSUE TITLE
next 7 does't work properly on every safari 10

### ISSUE THREAD

**Issue by sl5310** [zeit/next.js#5630]
I have iPhone 5c and iPhone 6 both are iOS 10 and just upgrade my project to next 7 recently.
iPhone 5c was getting error when access to our project
`SyntaxError: Cannot declare a let variable twice: 'l'.`
already added mangle option eg:
`     new UglifyJSPlugin({
          uglifyOptions: {
            compress: {
              drop_console: true
            },
            mangle: {
              safari10: true
            }
          }
        })
`
But the problem still existed

## System information
 - OS: iOS 10
 - Browser (if applies): Safari & Google Chrome
 - Version of Next.js: 7

**Comment by ilionic** [comment]
you need to pass it to `config.optimization.minimizer`
Our example ( but using TerserPlugin instead of UglifyJSPlugin )
```
        if (!isServer && !dev) {
          config.optimization.minimizer = [
            new TerserPlugin({
              parallel: true,
              cache: true,
              sourceMap: true,
              terserOptions: {
                safari10: true,
              },
            }),
          ];
        }
```

**Comment by teleginzhenya** [comment]
@timneutkens can I work on this issue? Should it works as option flag or add `safari10: true` for all cases?

**Comment by timneutkens** [comment]
Yes @teleginzhenya
