### ISSUE TITLE
Semantic ui css error

### ISSUE THREAD

**Issue by tete32153** [zeit/next.js#5632]
I'm trying to use semantic ui css in my next js application.. But I get an error failed to compile... Need an appropriate loader to handle this fyle type

**Comment by timneutkens** [comment]
Not sure what to do with this issue, so I'm going to close it. 

Please follow the issue template.

**Comment by tete32153** [comment]
And where can I find the issue template

**Comment by herudi** [comment]
same with me error => Module not found: Can't resolve 'semantic-ui-css/semantic.min.css'
