### ISSUE TITLE
externals breaks monorepo

### ISSUE THREAD

**Issue by rbalicki2** [zeit/next.js#5638]
# Bug report

## Describe the bug + reproduction

Say I have a mono repo with `marketing-site` (a nextjs project) and `button`, and `button/src/index.js` and `button/src/style.scss`.

I have loaders correctly set up to import scss files if they are within marketing-site, e.g. 

```js
{
  test: /\.scss$/,
  use: [
    {
      loader: 'css-loader',
      options: {
        modules: true,
      },
    },
    'sass-loader',
  ],
},
```

If, from `marketing-site`, I `import styles from '../button/src/styles.scss'`, everything works fine. However, if I import the same file from within `button/src/index.js`, it does not work.

It turns out that the culprit is the `externals` key. (I found this by comparing the two webpack configs. It was working if we were in `isServer: false` mode.)

Looks like this function https://github.com/zeit/next.js/blob/2e14b4491b555eb2a8103ffdcb76595fe3af5155/packages/next/build/webpack.js#L36 incorrectly causes the import of the scss file to not be processed by webpack.

Setting `config.externals = []` fixes the problem, it appears!

## System information
mac os

next 5.0.2. I apologize if this was fixed in a newer version.

**Comment by timneutkens** [comment]
Tracking this in #706
