### ISSUE TITLE
remote: [hardsource:60012cb1] Could not freeze ./node_modules/graphql/validation/rules/FieldsOnCorrectType.mjs: Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by TheoMer** [zeit/next.js#5639]
# Bug report

## Describe the bug

Upon attempting to deploy a next build to Heroku, the above mentioned errors are issued.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create/amend project files
2. git add -A
3. git commit -m "production-build"
4. git subtree push --prefix sick-fits/frontend heroku-frontend master

```
> git remote -v
heroku-frontend https://git.heroku.com/flamingo-next-production.git (fetch)
heroku-frontend https://git.heroku.com/flamingo-next-production.git (push)
```

## Expected behavior
The project, as was the case up until suddenly last night, would successfully build and be deployed to Heroku.

## Screenshots
![nextjs-buiold-error](https://user-images.githubusercontent.com/15969262/48256111-8a897100-e406-11e8-993a-2992a27ec354.jpg)

## System information
 - OS: Windows 10 Pro
 - Version of Next.js: ^7.0.0
 - Version of next-with-apollo: ^3.1.3

## Additional context

package.json script:

```
  "scripts": {
    "dev": "next -p 7777",
    "build": "next build",
    "start": "next start -p $PORT",
    "test": "SET NODE_ENV=test&& jest --watch",
    "heroku-postbuild": "next build"
  },
```

Doing `rm -rf node_modules/.cache` as recommended in another bug report about this issue, did not resolve my issue: `https://github.com/zeit/next.js/issues/5243`

**Comment by timneutkens** [comment]
Upgrade to latest stable Next.js
