### ISSUE TITLE
Production server breaks?

### ISSUE THREAD

**Issue by nealoke** [zeit/next.js#5640]
# Bug report

## Describe the bug

I currently have a project where I have a custom `server.js` file for the server and it works perfect and without any errors when running `node server.js` locally. However when trying to run the server in production mode I get thrown a lot of errors (see pic below). 

Could it be because of the routing i'm doing inside the `server.js`? But why does this not happen on a development server?

## To Reproduce

[Gist of my server
](https://gist.github.com/nealoke/d90bcb08577b68695f15a9aa16047916#file-server-js)

## Expected behavior
Should work as on development server.

## Screenshots
![errors](https://user-images.githubusercontent.com/17417414/48256508-223f8d00-e410-11e8-8504-1650ee380451.PNG)

## System information
 - OS: `Windows`
 - Version of Next.js: `7.0.2`

**Comment by timneutkens** [comment]
Replied on spectrum.chat/next-js
