### ISSUE TITLE
HMR removes CSS classes from components

### ISSUE THREAD

**Issue by cesarvarela** [zeit/next.js#5642]
# Bug report

## Describe the bug

CSS Classes get removed from components when HMR loads the component again 

## To Reproduce

Just modify any component like:

```
<Component className="sarasa" />
```

And after the first HMR reload it will lose the `sarasa` class, and just keep the `jsx-xxxxxx` generated class. 

## Expected behavior

Should keep the assigned `sarasa` CSS class.

## System information
 - OS: Mojave
 - Chrome (don't think it matters)
 - Version of Next.js: 7

**Comment by timneutkens** [comment]
I'm missing a reproduction, there's no styled-jsx involved in your example.

**Comment by cesarvarela** [comment]
I was using `class` instead of `className`
