### ISSUE TITLE
Next.js & Typescript test with Jest and Enzyme

### ISSUE THREAD

**Issue by Emiliano-Bucci** [zeit/next.js#5649]
Hi to all, i'm actually developing an app with Next.js, Typescript, Apollo, GraphQl and other cool stuff. The fact is that i have errors trying to test any component. I get all the time the same error, and i really don't know what/where to look: 
TypeError: The super constructor to "inherits" must have a prototype
Does anyone face this error before?
Thanks to all! :)

**Comment by timneutkens** [comment]
Please follow the issue template, I believe you already did and then posted here 🤔
