### ISSUE TITLE
Error not showing in browser + not reloading

### ISSUE THREAD

**Issue by bzuker** [zeit/next.js#5655]
# Bug report

## Describe the bug

I'm getting an 'Internal Server Error' instead of an error page. After I correct the error, I need to manually reload the page

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to 'https://codesandbox.io/s/xv70oz60qo'
2. There's a mistake (on purpose), on index.js, Items.
3. The 'Internal server error' page shows up
4. When I correct the error, I need to manually reload.

## Expected behavior
I've seen that similar errors show up like this:
![capture](https://user-images.githubusercontent.com/8533385/48305946-058b7e00-e512-11e8-956f-6f81ad643207.PNG)

## System information
 - OS: Windows 10
 - Browser: Chrome
 - Version of Next.js: 7.0.0

Thank you so much for an awesome library!!

**Comment by timneutkens** [comment]
Should be fixed in 7.0.1,7.0.2 or latest `next@canary`.

> Thank you so much for an awesome library!!

Thank you 🙏
