### ISSUE TITLE
Cannot download via curl

### ISSUE THREAD

**Issue by jesmarquez** [zeit/next.js#5660]
# Examples bug report
Download manually curl

## Example name
I run:
curl https://codeload.github.com/zeit/next.js/tar.gz/canary | tar -xz --strip=2 next.js-canary/examples/form-handler

## Describe the bug
Curl shows this message:
Error opening archive: Failed  to open '\\.\tape 0'
Failed to connect to codeload.github.com port 443: Connected refused

## System information
 - OS: Win10

**Comment by timneutkens** [comment]
`curl https://codeload.github.com/zeit/next.js/tar.gz/canary | tar -xz --strip=2 next.js-canary/examples/form-handler`

Just tried this and it works perfectly.
