### ISSUE TITLE
next-css in production

### ISSUE THREAD

**Issue by larafale** [zeit/next.js#5661]
Hello guys, can you help me understand something please :)

so my app was referencing multiple css (located in a `static/css`) in one of my layout component:
```
<link rel="stylesheet" type="text/css" href="/static/css/app.css" />
<link rel="stylesheet" type="text/css" href="/static/css/part-one.css" />
and many more
```
 this works as expected.

Now I'm in the process of optimizing my application, and want to merge/minify all the file into one. `next-css` seems to me the way to go. Instead of referencing them via multiple `Link` tag, I imported them directly : 

```
import '../static/css/app.css'
import '../static/css/part-one.css'
etc ...
```

running next in `dev` mode works fine. It looks like nextjs automatically inject the css via `<link rel="stylesheet" href="/_next/static/css/styles.chunk.css">` in the page. works great.

But in `production` mode, nothing. The css is not injected in the page, or maybe it is (but can't find it), but it results with no css applied.  

I would assume next would bundle everything for me, and auto inject the css (like in dev mode). Is that not the case ? What did I missed ? Am I stupid ? :)

Thanks for your help

info:
- "next": "^7.0.2"
- "@zeit/next-css": "^1.0.1
- running next in server mode, not directly via the `next` command

**Comment by timneutkens** [comment]
Can you try @zeit/next-css@canary

I'm going to close this issue as there is no reproduction included and it doesn't follow the issue template.

**Comment by larafale** [comment]
Hi Tim, of course, just wanted to know if this was intended or not. or if i had missed some extra conf for production. @canary did not change anything, still no css in production when using import along next-css.

thanks for the reply :)

**Comment by larafale** [comment]
can you confirm me that the attended behavior should work out of the box in production ? do i need to add a script link to the generated css or is it automatically injected as well (like in dev) ?

**Comment by timneutkens** [comment]
It should work, especially if it works in dev

**Comment by larafale** [comment]
For now I went with my own build step for combining the css (using clean-css).
I'm using a custom server with zeit micro, if you say it should work, then it's probably on my side with my custom now config that something is not working. I'll try it out in a fresh project to check if it's on my side. Thx for getting back, you are a tech animal :) glad we have you !

**Comment by prathameshnetake** [comment]
Also replicating for my project. CSS works in dev mode but distort in production mode
