### ISSUE TITLE
Can’t use webpack `context`

### ISSUE THREAD

**Issue by Swatinem** [zeit/next.js#5667]
# Bug report

## Describe the bug

The use case is that we have a monorepo, and we would like to have all the files (for example in sourcemaps) relative to the monorepo root.
But setting the webpack `context` option which is responsible for this leads to the following error:

```
{ Error: (client) multi ./pages/about.tsx
Module not found: Error: Can't resolve './pages/about.tsx' in 'XXX/next-monorepo'
 @ multi ./pages/about.tsx static/yi4a2FHcuhkYLlUQ3FRhu/pages/about.js[0]
```

## To Reproduce

Repo to reproduce:
https://github.com/Swatinem/next-monorepo/tree/context

## Expected behavior

I should be able to the `context` to whatever I like, things should just work.

## System information
 - OS: linux
 - Version of Next.js: next@7.0.2

## Additional context

Found this while trying a workaround for https://github.com/zeit/next.js/issues/5666

**Comment by timneutkens** [comment]
You shouldn't change these paths, it breaks a lot of webpack plugins, including the ones in Next.js itself. This is not a bug, we don't expose the webpack config to change anything in the webpack config.

If you want to transpile modules use something like https://github.com/martpie/next-plugin-transpile-modules

**Comment by jack-sf** [comment]
Next.js doesn't set the `context` variable now, right? Wouldn't it be nice to at least set it by default to sth like `path.join(__dirname, './');`, so it is set as root directory of the nextjs app? (So then we can do `import ... from 'components/...'` instead of `import ... from '../../components/...'`)

**Comment by timneutkens** [comment]
`context` is something very different than what you're mentioning. What you mean is `alias`, which you can override, even though I wouldn't recommend it as it breaks a lot of statical analysis tools.
