### ISSUE TITLE
[examples/with-react-helmet] <title> should not be used in _document.js's <Head>

### ISSUE THREAD

**Issue by joltmode** [zeit/next.js#5668]
# Examples bug report

## Example name
`with-react-helmet`

## Describe the bug
```
Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title
```

## To Reproduce
- hub clone zeit/next.js
- cd next.js/examples/with-react-helmet
- yarn install
- yarn next
- open http://localhost:3000

## Expected behavior
I expect that the example is set up in compliance with Next's functionality.

## Screenshots
`N/A`

## System information
 - OS: macOS
 - Browser (if applies): `N/A`
 - Version of Next.js: 7.0.2

## Additional context
I previously didn't get the `Warning`, but I noticed this in my production app.
Also, AFAIK, it's not only `<title>` related, but also `<meta>`'s and basically everything else that is page related rather than totally global?

I cannot seem to figure out a way how to use `react-helmet` in compliance with Next, though.

**Comment by lucleray** [comment]
I created a PR to fix that, you can have a look here : https://github.com/zeit/next.js/pull/5678

**Comment by joltmode** [comment]
Ok, but isn't there a reason why default `<Head>` prevents the setting of `<title>` in `_document`?  
I mean, with this you got rid of the warning, but doesn't it introduce other problems?

I don't know the intricacies of `<Head>`, that's why I'm being cautions here.

**Comment by lucleray** [comment]
The reason for the warning is explained here : https://github.com/zeit/next.js/issues/4596

`react-helmet` is basically an alternative of `next/head`. So when you use it, you shouldn't use `next/head` anymore and that's why `<Head>` should be removed from `_document` and replaced by Helmet's own `<head>` tag.

If you try to use `next/head` and `react-helmet` at the same time, they will probably conflict. Thankfully, `_document.js` allows you to opt-out of `next/head` and replace it by your preferred solution 🙂

**Comment by Enalmada** [comment]
Some off topic thoughts if anyone feels like chewing on them:
- Do you think the example readme should inform new users that next already has next/head feature to avoid people that are jumping into examples they think are relevant before reading all the docs?
- What are some things that react-helmet does that next/head doesn't?  As a new user, I am curious what reasons someone would choose to use it over next/head.
- I noticed this interesting alternative: https://www.npmjs.com/package/react-helmet-async.  Would new users be better off being shown that in the next example instead?

**Comment by timneutkens** [comment]
> Do you think the example readme should inform new users that next already has next/head feature to avoid people that are jumping into examples they think are relevant before reading all the docs?

Definitely, adding react-helmet would increase bundle size while it's not needed because we provide next/head

> What are some things that react-helmet does that next/head doesn't? As a new user, I am curious what reasons someone would choose to use it over next/head.

In pretty much all cases you don't want to use react-helmet, it's mostly for interoperating old and new code while moving from a different app to Next.js

> I noticed this interesting alternative: npmjs.com/package/react-helmet-async. Would new users be better off being shown that in the next example instead?

We could, but it doesn't make much difference until we implement streaming rendering.

**Comment by joltmode** [comment]
> In pretty much all cases you don't want to use react-helmet, it's mostly for interoperating old and new code while moving from a different app to Next.js

For instance, how would I add a class to `<html>` from anywhere in my code?

With `Helmet` I can:
```
<Helmet>
    <html className="classname-to-be-added" />
</Helmet>
```

That's the sole reason I looked upon `Helmet` as I couldn't find a way how to do it with native `Head`...

**Comment by timneutkens** [comment]
What's the reason for adding classes to html/body 🤔 Because of the way css inheritance works you could add classes on pages / _app.js and it'd work in the same way.

**Comment by lucleray** [comment]
Maybe adding `<html lang="fr">` ?

**Comment by MarchWorks** [comment]
I think that `<Head>` should work just with the head tag stuff and leave these special cases to `next.config.js` file for example adding `lang="fr"` to the html tag something like
```
module.exports = {
  html: {
    lang: "fr"
  }
}
```

**Comment by Timer** [comment]
Solved in https://github.com/zeit/next.js/pull/7483
