### ISSUE TITLE
Investigate using @reach/router

### ISSUE THREAD

**Issue by alexandernanberg** [zeit/next.js#5669]
# Feature request

## Is your feature request related to a problem? Please describe.
There are some open issues related to `next/router` or `next/link` atm that would be solved if we moved to `@reach/router`. I think the API would look a lot nicer as well, especially for the `next/link`. This would improve the overall a11y of all sites using `next`, which is a very nice thing 😉  

## Describe the solution you'd like
Use `@reach/router` instead of custom router implementation

## Describe alternatives you've considered
We could also "fix" the current implementation of the router, but I think it would be much more effective to rely on a 3:rd-party solution.

## Additional context
https://github.com/reach/router

I'd be happy to do some digging and create a PR if this is something you want to add 😄

**Comment by goldenshun** [comment]
Are you able to explain why reach router is better than the current router? I'm actually not even sure why it's better than react router.

**Comment by alexandernanberg** [comment]
I think the biggest selling point of reach router is the accessibility improvement that you get by default. It will automatically set the correct `aria` attributes on the navigation links and handle focus when navigating. It also has support for relative links which is pretty neat! 

It has some trade-offs though – as described [here](https://reach.tech/router/credits).

**Comment by revskill10** [comment]
@alexandernanberg Why not just adding features to `next/router` instead of adopting `reach/router`. I don't prefer adding an important dependencies like router for `next`, because upgrading version and compatibility could be painful.

**Comment by alexandernanberg** [comment]
We could absolutely do that, but then we’d have to maintain it (might be a good thing, I don’t know) and make sure it performes on an equal level as reach router

**Comment by alexandernanberg** [comment]
I'm going to close this in favor of #1632
