### ISSUE TITLE
CrossOrigin attribute not added to scripts loaded by PageLoader

### ISSUE THREAD

**Issue by jclem** [zeit/next.js#5674]
# Bug report

## Describe the bug

When I add the `crossOrigin` prop to my `Head` and `NextScript` components, I expect all scripts to have a `crossOrigin` attribute on them. This appears to be the case, except for scripts created by [`PageLoader`](https://github.com/zeit/next.js/blob/0d77dda28c8b0eaed38bb203de737ffc1235d42a/packages/next/lib/page-loader.js#L71).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Add a `crossOrigin` prop to `Head` and `NextScript`
2. View attributes of any script created by the `PageLoader` class.

## Expected behavior

A `crossOrigin` attribute is present on scripts created by `PageLoader`.

## Additional context

This was solved in the [original `crossOrigin` PR](https://github.com/zeit/next.js/pull/5150/files#diff-c7ddf3ad46bcb0938d6043ea0393d554R75), but not in [the one that was merged](https://github.com/zeit/next.js/pull/5646).

**Comment by jclem** [comment]
It looks like `PageLoader` also does not add the `nonce` attribute, which I believe should be happening, as well.

**Comment by Enalmada** [comment]
I added crossOrigin to everything that had a nonce so that would explain why I missed it.  I don't know what PageLoader is or how to test.  If you have a reproducible case already handy can you push a fix?

**Comment by timneutkens** [comment]
I'll fix it soon, pageloader is what next/router uses to load pages when routing using next/link for example.

What happens is:

```js
<Link href="/about">
```

Will `onClick` call

```
Router.push('/about')
```

That in turn (in reality it does more than this, but for example purposes)

```
PageLoader.loadPage('/about')
```

What `loadPage` does is inject a script tag:

```
<script src="/_next/static/<buildid>/pages/about.js" async>
```

`about.js` holds the page bundle wrapped in a function:

```
__NEXT_REGISTER_PAGE('/about', () => {
  // the compiled code from pages/about.js (holding Component exports) would be on this line

  return {
    comp: module.exports
  }
})
```

So `PageLoader` will wait for that function to be called and then resolve the `loadPage` Promise with the component


Hopefully this explains it a bit. @jclem is right in that it doesn't currently add nonce/crossOrigin, which should be fixed

**Comment by timneutkens** [comment]
@dav-is would you be able to have a look into this? It'd be a huge help. It should be relatively easy to fix by reading the crossOrigin attribute from the script tags 🤔

**Comment by dav-is** [comment]
With [this change](https://github.com/zeit/next.js/pull/4943/commits/d8cd11c083246704b134f7613ba1e387a4438489) a `crossOrigin` config option sets the crossOrigin attribute on the proper tags.

**Comment by dav-is** [comment]
@timneukens /_next/static/chunks/0 is the first one that shows up

**Comment by dav-is** [comment]
It's coming from [webpack's jsonp loader](https://github.com/webpack/webpack/blob/d5e26f728adb63a1fca080ef728fd627952a921d/lib/web/JsonpMainTemplatePlugin.js#L167) and can be changed with a [config option](https://webpack.js.org/configuration/output/#output-crossoriginloading) and can be set [here](https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack-config.js#L246).

I'll add it to the PR.
