### ISSUE TITLE
Broken link in `with-apollo-auth`

### ISSUE THREAD

**Issue by paulogdm** [zeit/next.js#5680]
# Examples bug report

## Example name
with-apollo-auth

## Describe the bug
There is a broken link in the [README.md](https://github.com/zeit/next.js/tree/canary/examples/with-apollo-auth#demo) of this example.
[https://next-with-apollo-auth.now.sh](https://next-with-apollo-auth.now.sh) does not exist or is not deployed.

## To Reproduce
1- Go to the demo section [here](https://github.com/zeit/next.js/tree/canary/examples/with-apollo-auth#demo).
2- Click in the demo link [https://next-with-apollo-auth.now.sh](https://next-with-apollo-auth.now.sh)

## Expected behavior
The source code and logs of the deployment should be available instead of a 404.
OR
The link should be removed from the README.md

**Comment by timneutkens** [comment]
Feel free to remove the link
