### ISSUE TITLE
Add subdomain routing example

### ISSUE THREAD

**Issue by ardyfeb** [zeit/next.js#5682]
Nextjs is awesome framework, but i have website with subdomain

* blog.domain.com
* forum.domain.com

I want to handle them with single app with nextjs, like laravel routing system allow use multiple subdomain on single app

**Comment by Enalmada** [comment]
Does [zones](https://github.com/zeit/next.js/#multi-zones) not cover your use case?

**Comment by svobik7** [comment]
Hello @ardyfeb,

did you find any solution for easy subdomain routing with `serverless` target app?

**Comment by xyNNN** [comment]
Any input for this topic? It's possible to create multiple zones with a differenz subdomain and not based on the URL path?

**Comment by janmallari** [comment]
Any updates on this topic? Would really love to have subdomain routing.

**Comment by khairulaffandy** [comment]
hopefully, Vercel will implement subdomain routing in the near future. a subdomain would be very useful in organizing links and pages.

**Comment by pie6k** [comment]
@dcangulo thank you for your example. However, your example assumes you create custom server. It will not work with serverless approach which has many benefits.

**Comment by kushthakker** [comment]
Any update on this??

**Comment by kushthakker** [comment]
I came across a thing called mono-repo, you can [check it out here](https://vercel.com/blog/monorepos). It's not the exact way we wanted it to have, like subdomains routes handled in single next.js project but it's kinda close to it.

**Comment by ihadabs** [comment]
Any updates on single next app with subdomains?
