### ISSUE TITLE
next build error: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by eldyvoon** [zeit/next.js#5687]
I got this error when doing npm run build, I suspect something is dated in the next.config.js?

(node:16224) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'push' of undefined

this is my repo https://github.com/eldyvoon/push-notifications-next-js

**Comment by timneutkens** [comment]
I mean, you do have `.push` in your next.config.js:

https://github.com/eldyvoon/push-notifications-next-js/blob/master/next.config.js#L10

So I guess that's the reason.
