### ISSUE TITLE
Async attribute when use <script> tag and <Head>

### ISSUE THREAD

**Issue by vDiFoung** [zeit/next.js#5697]
Hi there, 
The first, sorry for my English.
# Examples bug report
**In pages/index.js:**
```
import React from 'react';
import Link from 'next/link';

class Index extends React.Component {
  render() {
    return(
      <div>
	<Link href='/about'>
          <a href=""> Go to about </a>
       </Link>
     </div>
   )
  }
}
export default Index;
```
===================================
**In pages/about.js**
```
import React from 'react';
import Link from 'next/link';
import Head from 'next/head';

class About extends React.Component {
  render() {
	return(
	  <div>
		<Head>
		  <script async src='/static/xxx.js'></script>
		</Head>
		<Link href='/'>
                  <a className='example' href=""> go back </a>
               </Link>

               <button  id='button'  type='button'>Click me</button>
	  </div>
	)
  }
}
export default About;
```
=============================================
In pages/about.js, i'm embed   <script async src='/static/xxx.js'></script> within <Head> component of Nextjs.
**xxx.js content:**
```
console.log('xxx');
document.getElementById('button').addEventListener('click', function () {
  console.log('clicked');
})
```
=============================================
## Describe the bug
after that, in browser enter url localhost:port/about and then enable console i seen 'xxx' in console but is duplicated. So, when click to button element, console show two times 'clicked'.
When embeb xxx.js, if don't have async attribute, this does not happen but document.getElementById('button') is not found coz js loaded before element rendered.
I don't understand about async attribute in nextjs. If have "async" attribute, in Web Console -> Network tab, **xxx.js** loaded two times, else **xxx.js** loaded one time.

Please tell me why this bug appeared

Many thanks! 

## To Reproduce

1. Go to Browser
2. Enter url: localhost:port/about and hit Enter
3. Click in to "Click me" button
4. F12 find console tab
5. See error: duplicated text "clicked"

## Expected behavior
Just have one text: "clicked" in Console tab when click to button.

## System information
 - OS: macOS
 - Browser: safari
 - Version of Next.js: "^7.0.2"

**Comment by timneutkens** [comment]
`<Head>` elements are remounted on page switches / hydration, meaning that if you include a `<script>` like that it'll end up being executed multiple times. You can instead make it part of the initial html in _document.js.

**Comment by vDiFoung** [comment]
Hi @timneutkens ,
On each page, i need to embed different files.
maybe i will try something else.
Thanks for replying.
