### ISSUE TITLE
6x slower compile time when generating next/dynamic components dynamically

### ISSUE THREAD

**Issue by luddzo** [zeit/next.js#5699]
# Bug report

## Describe the bug

The compile time for both the server and client increases from 1-2s to 6-12s when generating next/dynamic components dynamically/functionally.

## To Reproduce

Below, the `dynamicComponent` function accepts a `path: string` prop and returns a LoadableComponent (generated by next/dynamic).

```
import React, { ComponentType } from "react";

import dynamic from "next/dynamic";
import { withProps } from "recompose";
import { LoadableComponent } from "react-loadable";

import Loader from "src/components/loader";

export const dynamicComponent = <T extends object>(path: string): LoadableComponent & ComponentType<T> =>
	dynamic<T>({
		modules: () => {
			const components: any = {};

			if (path) {
				components.InnerDynamicComponent = import(`../../routes${path}`);
			}

			return components;
		},

		loading: withProps({
			passedKey: path,
			essential: true,
		})(Loader),

		render: (passedProps, { InnerDynamicComponent }) =>
			InnerDynamicComponent ? <InnerDynamicComponent {...passedProps} /> : <div {...passedProps} />,
	});
```

## Expected behavior

When this function is utilized somewhere in the codebase (in my case in pages/_app.tsx), the compile time increases as described above.

## Screenshots

![](https://i.gyazo.com/0de0e553f15474f39305a245fdeb458a.png)

## System information
 - OS: macOS
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
It basically comes down to having `import(`../../routes${path}`)` causes **every single file in that directory** to be bundled by webpack.
