### ISSUE TITLE
Param shows as undefined at times

### ISSUE THREAD

**Issue by SylarRuby** [zeit/next.js#5705]
Nextjs: 7.0.2
Express: 4.16.4
Chrome: 70.0.3538.102 (Official Build) (64-bit)
OS: MacOS 10.14

Im getting `undefined` on few occasions and the examples are shown without a trailing forward slash.

```
const pathVisit = 'localhost:3000/p/welcome'

server.get('/p/:slug', (req, res) => {
 const pagePath = '/post
 const slug = req.params.slug
 console.log(slug) // sometimes welcome, other times undefined
})
``` 

<img width="565" alt="screenshot 2018-11-19 at 14 59 57" src="https://user-images.githubusercontent.com/7381195/48714991-d957b780-ec0b-11e8-90c0-180402ad3731.png">

Sometimes the issue goes away when no trailing slash (`/`) at the end. If this a bug?

**Comment by timneutkens** [comment]
Please follow the issue template and provide a full reproduction.
