### ISSUE TITLE
Wiki Permissions appear to be fully open

### ISSUE THREAD

**Issue by eyasukochi** [zeit/next.js#5709]
# Bug report 
There appear to be no restrictions around editing the wiki pages

## Describe the bug
I (or anyone else) can edit the wiki pages.
If you go to the wiki now, you will see someone had edited it, replacing the page with a joke.

## To Reproduce
Go to the github wiki

**Comment by timneutkens** [comment]
I've restricted the Wiki and reported the particular user for being a spammer. I'll decommission the Wiki at a later point in time, as the docs were moved to nextjs.org/docs.
