### ISSUE TITLE
Pass function as `scroll` for `Link`

### ISSUE THREAD

**Issue by markbrouch** [zeit/next.js#5711]
# Feature request

## Is your feature request related to a problem? Please describe.
If I want custom scrolling functionality on `Link` components, I have to set `scroll={false}` and then handle the `onClick` event to do the custom scrolling.

## Describe the solution you'd like
I'd like a shortcut so that instead of passing `scroll={false}` I can pass a function that will be executed when the scroll would normally happen instead of the default scrolling behavior.

## Describe alternatives you've considered
The alternative is to set `scroll={false}` then do the custom scrolling logic in the `onClick` handler.

**Comment by timneutkens** [comment]
I don't think we have to add that functionality since you can create your own custom `<Link>` component 🤔

**Comment by markbrouch** [comment]
@timneutkens true, and that's essentially what I'm doing here. I requested this feature since it would provide a convenience without breaking backwards-compatibility.

**Comment by timneutkens** [comment]
@markbrouch while that might be convenient, we don't want to increase the bundle size for all users by introducing this as a feature while it's possible to implement it yourself and even share that component on npm for example, I hope you understand that 🙏
