### ISSUE TITLE
Test reports are not being published to Azure Pipelines

### ISSUE THREAD

**Issue by vagisha-nidhi** [zeit/next.js#5713]
Tests are running in the pipeline, but results are not being published for reporting. Azure Pipelines provides excellent reporting capabilities that help you with:

Easy analysis and troubleshooting for failed tests - the test reports show all relevant details (error message, stack trace, failing for how long, etc.) to make it easy to analyze failed tests.
Timing analysis - Test duration information helps you figure out long running tests, so that you can improve test collateral to speed up the pipelines.
Build-on-build trends/analytics help you get rich insights, for e.g., easily identify top failing tests.
The fix required is to use an XML reporter for jest and update the YAML file to publish these test reports.

I am a Software Engineer on the Azure Pipelines team and will be happy to raise a PR to address this.

**Comment by timneutkens** [comment]
Hey Vagisha, I'd be happy to merge a PR solving this 👍

**Comment by timneutkens** [comment]
Fixed in #5715
