### ISSUE TITLE
Bug with onclick trigger when using custom server with non '*' route

### ISSUE THREAD

**Issue by Menouer** [zeit/next.js#5725]
# Bug report

## Describe the bug

Cannot trigger "onclick" when using a custom route with expressJS

## To Reproduce

I have created a minimal repository for you to recreate the bug that you can find here :
https://github.com/Menouer/NextJsBug
Start the project with:
`npm run dev`

Inside the custom server.js file you will find two handlers. One targeting precisely /test the other handling '*'.
When a request is handled by the /test handler then the onclick trigger won't work but it will work using the '*' handler.

## System information
 - OS: Ubuntu 16.04
 - Browser Firefox 63
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
Thanks for replying @ztanner 🙌 well explained.

**Comment by Menouer** [comment]
Hello, thank you for the answer ! 
It work with the '*' yes, thank you :) but there is till something weird when using custom routes because even with using this approach : 
`return app.render(req, res, '/test', req.query);`

The js files are still 404ing, that is not normal right ?

**Comment by ztanner** [comment]
As long as you also have a wildcard handler, you should not see any 404s. Here's the full example, using your config:

```js
app
  .prepare()
  .then(() => {
    const server = express();
    server.set("port", 8080);

    server.get("/test", (req, res) => {
      return app.render(req, res, "/test", req.query);
    });

    server.get("*", (req, res) => {
      return handle(req, res);
    });

    server.listen(server.get("port"), () => {
      console.log("server running on 8080");
    });
  })
  .catch(ex => {
    console.error(ex.stack);
    process.exit(1);
  });
```

**Comment by Menouer** [comment]
Oh i understand now, it make sense ! Thanks a lot ! :)

It's probably off topic but this fix seems to make my redux (redux saga) trigger an init on client side and so emptying the store on my main project. It does so only when using the wildcard handler.
