### ISSUE TITLE
 after `Link` to page and refresh then cannot go back

### ISSUE THREAD

**Issue by YUFENGWANG** [zeit/next.js#5726]
# Examples bug report

## Example name
with-ant-design

## Describe the bug
component can't navigate to previous one when refresh browser

## To Reproduce

1, create `about.js` in pages folder, with code below
```jsx
import React from 'react'
import Link from 'next/link'

export default () => {
  return (
    <div style={{ marginTop: 100 }}>
      <div>
        <Link href="/">
          <a>index page</a>
        </Link>
      </div>
    </div>
  )
}
```
2, add a `Link` in `index.js`, such as: 
```jsx
 <Link href="/about">
      <a>about page</a>
  </Link>
```
3, click link in `index.js` then it navigates to`/about` as expected
4, click link in `about.js` then it navigates to`/` as expected
5, click link in `index.js` again then it navigates to `/about` again
6, refresh the browser
7, click link in `about.js`, it can't navigate to`/` !

## Expected behavior
 click link in `about.js`, it can navigate to`/` after refresh browser

## Screenshots
nope

## System information
 - OS: macos mojave
 - Browser chrome latest
 - Version of Next.js: latest

## Additional context

no errors in browser console or terminal console

**Comment by YUFENGWANG** [comment]
anyone can help?

**Comment by ztanner** [comment]
I'm able to trace this issue back to https://github.com/zeit/next.js/pull/4034/files. The issue seems to be with babel-plugin-import, as the example works fine if you delete custom next.config.js and `import` plugin from babelrc.

I think the hack added here is causing the issue: https://github.com/notatestuser/next.js/blob/c96a7d2f98f4dc32c72faf0397b906f32d07ca53/examples/with-ant-design/next.config.js#L3-L6

When removing the hack, you run into the issue that was created over here: https://github.com/zeit/next-plugins/issues/85

This might be something the antd team needs to fix in their babel plugin.

**Comment by Enalmada** [comment]
Completely unrelated but just noting that it is my understanding that the with-ant-design-less example should be followed for best performance:

> With style: "css", pre bundled css files are imported as they are.  style: true can reduce the bundle size significantly, depending on your usage of the library.
~ https://github.com/ant-design/babel-plugin-import

**Comment by YUFENGWANG** [comment]
@Enalmada  with-ant-design-less just import the whole bundle of css , which is not good for performance

**Comment by YUFENGWANG** [comment]
@ztanner yep, 
> If you import the antd components in the about page, the page transition works fine (because the css is loaded).
this works, but not all page need antd components

**Comment by Enalmada** [comment]
@YUFENGWANG Make sure you are considering production build.  The bundle size is only cut down in production with `"style": true` in your .babelrc.  Also, look at issue 484 for some discussion on additional stuff that could be done to help.

**Comment by YUFENGWANG** [comment]
@Enalmada okay, I'll have a try

**Comment by YUFENGWANG** [comment]
@Enalmada import whole css comes with a production bundle of 453kb, while import whole less files comes with a production bundle of 382kb. here are the import code in `_app.js`
1, import all css
```js
import 'antd/dist/antd.css'
```
2, import all less
```js
import "antd/dist/antd.less";
```

**Comment by Enalmada** [comment]
Well you never want to import either of those manually in production...the whole point of babel-plugin-import is that it automatically imports only what is needed.  (Though you may need to conditionally do it during development if you are using some of the optimizations in issue 484.)

**Comment by YUFENGWANG** [comment]
@Enalmada  with-ant-design-less has the same issue that I mentioned above,  not only in with-ant-design. that's why I do `import "antd/dist/antd.less";` in my `_app.js`. so I think loading css or less on demand still have problem
