### ISSUE TITLE
Wrapping React component in withRouter causes graphql query fail on initial page load

### ISSUE THREAD

**Issue by TheoMer** [zeit/next.js#5730]
# Bug report

## Describe the bug

So I passs query parameters to a component (page), which I access as props `const { id, onToken } = this.props.router.query;` by wrapping the called component in a `withRouter`:
```
import { withRouter } from 'next/router'
export default withRouter(withApollo(Order));
```
But wrapping `withRouter` around my component causes grqphql query to fail on initial page load, and then to succeed.

## To Reproduce

```
const SINGLE_ORDER_QUERY = gql`
  query SINGLE_ORDER_QUERY($id: ID!) {
    order(id: $id) {
      id
      charge
      total
      createdAt
      user {
        id
      }
      items {
        id
        title
        description
        mainDescription
        price
        image
        quantity
        itemid
      }
    }
  }
`;

class Order extends React.Component {
  render() {
    return (
      <Query query={SINGLE_ORDER_QUERY} variables={{ id: id }}>
```

## Expected behavior
Without the component wrapped in withRouter the component works correctly without any generated errors.

## Screenshots
![query_fail](https://user-images.githubusercontent.com/15969262/48899313-30959c00-ee47-11e8-99e7-b6f82ec1f0b4.jpg)
![query_fail_2](https://user-images.githubusercontent.com/15969262/48899318-34292300-ee47-11e8-94a2-d96930696be2.jpg)

## System information
 - OS: Windows 10 Pro
 - next: "^7.0.2"
 - next-with-apollo: "^3.1.3"
 - react: "^16.5.2"

## Additional Info
The calling component creates the parameterised query as follows:

```
    Router.push({
      pathname: '/order',
      query: { id: order.data.createOrder.id, onToken: true },
    });
```

**Comment by goldenshun** [comment]
According to the docs for next-with-apollo, you should wrap your _app, not individual pages, with the withApollo HOC. That may be the root of your problem.

**Comment by revskill10** [comment]
Where's that `withApollo` stuff from ?

**Comment by goldenshun** [comment]
From the original issue:

> next-with-apollo: "^3.1.3"

**Comment by revskill10** [comment]
Try to output the `router` information before running the apollo stuff, you might find out if the `variables` for apollo got the right variables or not.

**Comment by TheoMer** [comment]
Refactoring code resolved the issue.
