### ISSUE TITLE
Defer prefetching after `onload`

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#5734]
Per suggestion of @cramforce, we should only start pre-fetching after `onload` triggers (unless `onload` has already triggered ;)).

This will prevent the tab spinner from rendering until we've prefetched all linked pages (via `<Link prefetch>` for example).

**Comment by rauchg** [comment]
It seems that we are not using `<link rel="preload">` as the implementation detail of `Router.prefetch`?

**Comment by cramforce** [comment]
Neat, left a couple comments on the merged PR.
