### ISSUE TITLE
Getting "Cannot read property 'state' of undefined" when using state in styled-jsx.

### ISSUE THREAD

**Issue by 422158** [zeit/next.js#5735]
# Bug report

## Describe the bug

I am getting weird behaviour when using nextjs with styled-jsx. Problem is that I am getting 
"_Unhandled Rejection (TypeError): Cannot read property 'state' of undefined_" 
when quering state in styled-jsx.

Minimal example of what i am talking about is here: 
https://github.com/422158/nextjs-bug-minimal/tree/master.
(All the code is inside pages/index.js)

You can install it with yarn

Weirdly when you remove this part of code:
```
{this.props.items.map((item) =>
                        <li className="item">
                            <span className="item-span"> {item.text} </span>
                        </li>
                    )}
```
or the part 
`height: calc(${this.state.listLength} * 50px);` 
in styled-jsx, everything works well. The problem only occurs when you use both at the same time.
## To Reproduce
clone https://github.com/422158/nextjs-bug-minimal/tree/master.

Install with yarn

yarn run dev
Steps to reproduce the behavior, please provide code snippets or a repository:

## System information
 - OS: [e.g. macOS, Windows]
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [e.g. 6.0.2]

**Comment by ztanner** [comment]
I think you're running into this: https://github.com/zeit/styled-jsx/issues/486

I was able to get your example to work by downgrading to Next@5. I was also able to get it to work in Next 7 by pulling `listLength` into a var, but it's just a hack since `this` should be resolving correctly. Ex:

```jsx
render() {
    const listLength = this.state.listLength;
    
    return (
      <div className="thumbnail-container">
      ...
       <style jsx>
          {`
            .thumbnail-container {
              width: 100%;
              height: 100%;
            }

            .main-img {
              width: 20%;
              height: calc(${listLength} * 50px);
            }
          `}
        </style>
      </div>
```

**Comment by 422158** [comment]
very nice, thank you for the workaround!
