### ISSUE TITLE
Share cookie/state between two browsers running same dev server

### ISSUE THREAD

**Issue by meathanjay** [zeit/next.js#5741]
# Examples bug report

## Example name
with-redux

## Describe the bug
On login, the API returns an access token and access token saved in cookie to use from with-redux-store.js to load initial redux state from API using that token.

I am getting an issue that sometimes two open browsers mix the cookie and redux states.

Example, two different user logged-in from Chrome and Safari and has a different token set as cookie and getting the token from `appContext.ctx.req.headers.cookie` in with-redux-store.js, but the Safari sometimes returns the cookie set in Chrome and vice-versa.

I believe am missing something or doing something wrong but can't figure out exactly what's wrong there and anything I should aware of?

## Expected behavior
Cookie should be different for the different browser.

## System information
 - OS: macOS
 - Browser: Chrome, Safari
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
Next.js doesn't handle cookies, neither does the redux example, so I'm not sure how to help here.

**Comment by pmg1989** [comment]
I also encountered, how can this bug be solved? Begging for a solution！

**Comment by rajesh-jublfood** [comment]
Getting same issue: next js sharing cookie with different browser.

**Comment by meathanjay** [comment]
I was actually doing it wrong and I believe you too. I am not sure whey states shared between browsers (didn't dig deeper) but got it working as expected.

What is doing now is get the access token from the cookie on server render and there a function responsible for fetching the initial states/data or undefined.

```
// Get initial state from the cookie.
const stateFromCookie = await initialStateFromCookie(
    appContext.ctx.req && appContext.ctx.req.headers.cookie,
    appContext.ctx.res,
 );

const reduxStore = getOrCreateStore(stateFromCookie);
```
 
Here `initialStateFromCookie` function fetches initial data from the server if valid cookie found or return `undefined` and in that case, redux create a store with reducers initial data.
