### ISSUE TITLE
Failed to compile next js app

### ISSUE THREAD

**Issue by darego1990** [zeit/next.js#5745]
I am testing out a simple next.js react app, although an error is showing up when I try to access it at localhost:300. On line 46 of my news.js page, I am trying to test if state.articles is empty then copy props to it, although next.js is telling me .length is undefined. Does anyone know why?

Error is as follows; TypeError: Cannot read property 'length' of undefined

any help is apprecaited
[pages.zip](https://github.com/zeit/next.js/files/2613641/pages.zip)

**Comment by timneutkens** [comment]
Questions should be posted on https://spectrum.chat/next-js as per the issue template.
