### ISSUE TITLE
Falling back to pure SSR

### ISSUE THREAD

**Issue by babakness** [zeit/next.js#575]
Hello, is it force SSR on all links based on a condition? For example, say a Bing searchbot visits (user agent contains " bing "), can we force all links to hit the server (SSR)? This could also be a nice fallback on text based browser as well.

**Comment by babakness** [comment]
More broadly, it would be nice to have an api to say "hey Next, render the next route as SSR" (and forget all the components you've downloaded). Basically like forcing a browser refresh but only upon entering the next route.

**Comment by rauchg** [comment]
That's how it works already. If you want only SSR and no client side, use `<a href>` instead of `<Link>`

**Comment by babakness** [comment]
Hmm.. maybe a mod to the Link component then. Basically you want CSR unless text only browser or a search bot. As far as I know Bing doesn't render Javascript.

**Comment by babakness** [comment]
Using <a> instead of <Link> mean ALL traffic will be SSR, which isn't the desire. Only in certain situations.

**Comment by arunoda** [comment]
@babakness you could use <a> when a BOT is using your site. You might have ways to identify a bot user from the client side.

Anyway, I don't think that's a good SEO practice.

If there's no JS, all `<Link>` tags will be `<a>` tags.
So, what you are asking is already there.
