### ISSUE TITLE
Unable to import module 'now__launcher'

### ISSUE THREAD

**Issue by lorenseanstewart** [zeit/next.js#5750]
# Bug report

## Describe the bug

When trying to build and deploy to `now`, everything seems to build fine but at the end of the build process I get the following error:

```
Unable to import module 'now__launcher': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/next.config.js:2:51)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone this repo `https://github.com/lorenseanstewart/next-blog-starter`
2. `npm i` from the root
3. `now`
4. To see the error, check logs with `now logs <url-provided-by-deploy>`

## Expected behavior
This project to deploy without errors.

## System information
 -  macOS
 - Version of Next.js: 7.0.2
 - Version of Now: 2
 - Version of now-cli: 12.1.6

**Comment by lorenseanstewart** [comment]
Moving this issue to the now-cli repo.

**Comment by jesstelford** [comment]
_Because this is the first result in google, and there is no link to the other issue, I will leave the fix I found here:_

The issue comes due to trying to run bundling work during the production serving phase of next ([details here](https://spectrum.chat/zeit/general/unable-to-import-module-now-launcher-error~2662f0ba-4186-402f-b1db-2e3c43d8689a?m=MTU0MjcyOTQ3NzkxMQ==)), such as `@zeit/next-css`, `@zeit/next-sass`, or `@zeit/next-typescript`.

The fix is to only run those during the build phase of running next:

`next.config.js`
```javascript
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : require('next-server/constants');

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production.
    return {};
  }

  const withCSS = require('@zeit/next-css');

  return withCSS();
};
```

**Comment by bel0v** [comment]
For anyone stumbling into this, the issue is not necessarily related to next-css.
I got the same problem having `withBundleAnalyzer(...)` returned from next.config.js.

Wrapping it the same way as described above helped.

**Comment by efleurine** [comment]
@jesstelford  thanks but I am still getting the error

by the way it should be `next/constants`

**Comment by TLevesque** [comment]
+1 Same probem as efleurine

**Comment by TLevesque** [comment]
Thank you very much @jesstelford for your help!

**Comment by TLevesque** [comment]
@efleurine Just for info, apparently next-compose-plugins package + next-sass doesn't work with this pattern suggested by jesstelford : https://github.com/cyrilwanner/next-compose-plugins/issues/13

**Comment by TLevesque** [comment]
Here is the content of the **next.config.js** file which is working for a complex example with several plugins like dotenv, next-images, next-sass, ... . 
@jesstelford, Just to make sure can you confirm that this is the correct syntax to use: 
```const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === "development"
    ? {}
    : require("next-server/constants");

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production.
    return {};
  }

  const sass = require("@zeit/next-sass");
  const images = require("next-images");
  require("dotenv").config();
  const path = require("path");
  const Dotenv = require("dotenv-webpack");
  const withBundleAnalyzer = require("@zeit/next-bundle-analyzer");
  const {
    WebpackBundleSizeAnalyzerPlugin
  } = require("webpack-bundle-size-analyzer");
  const withTM = require("next-plugin-transpile-modules");
  const { ANALYZE } = process.env;

  return withBundleAnalyzer(
    images(
      sass(
        withTM({
          analyzeServer: ["server", "both"].includes(
            process.env.BUNDLE_ANALYZE
          ),
          analyzeBrowser: ["browser", "both"].includes(
            process.env.BUNDLE_ANALYZE
          ),
          bundleAnalyzerConfig: {
            server: {
              analyzerMode: "static",
              reportFilename: "../bundles/server.html"
            },
            browser: {
              analyzerMode: "static",
              reportFilename: "./bundles/client.html"
            }
          },
          transpileModules: ["lodash-es"],
          webpack: config => {
            config.plugins = config.plugins || [];
            config.plugins = [
              ...config.plugins,
              new Dotenv({
                path: path.join(__dirname, ".env"),
                systemvars: true
              })
            ];
            if (ANALYZE) {
              config.plugins.push(
                new WebpackBundleSizeAnalyzerPlugin("stats.txt")
              );
            }
            config.externals = Array.isArray(config.externals)
              ? config.externals.map(fn =>
                  typeof fn === "function"
                    ? (context, request, callback) => {
                        if (request === "lodash-es") {
                          return callback(null, "commonjs lodash");
                        }
                        return fn(context, request, callback);
                      }
                    : fn
                )
              : config.externals;
            return config;
          }
        })
      )
    )
  );
};
```

**Comment by jesstelford** [comment]
It looks good to me, and if it works, then I'd say you're good to go 🎉

**Comment by humet** [comment]
@jesstelford thanks for these suggestions. However, I'm still getting this issue even after the fixes above. You can see my repo here https://github.com/media-chain/916-frontend. I've tried to strip it back as much as I can.

**Comment by jesstelford** [comment]
@humet Be sure to use `require('next-server/constants')`, not `require('next/constants')`.

**Comment by JFGHT** [comment]
@jesstelford, I'm getting this error at building:

> Cannot find module 'next-server/constants'

**Comment by jesstelford** [comment]
Ah, looks like that module doesn't exist locally.

I guess there should be a check for of its running on now's servers or not. I think there's `NOW` env var we could use?

Does this work both locally and when deploying for you?

```javascript
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !!process.env.NOW
        ? require('next/constants')
        : require('next-server/constants');
```

**Comment by alexedev** [comment]
Hi

Unfortunately, I still get that error.
My config is:

`require('dotenv').config();

const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW
    ? require('next/constants')
    : require('next-server/constants');

const config = {
  publicRuntimeConfig: {
    endpoint: process.env.ENDPOINT,
    username: process.env.USERNAME,
    password: process.env.PASSWORD
  }
};

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    return config;
  }

  const withCSS = require('@zeit/next-css');

  return withCSS(config);
};`

**Comment by jesstelford** [comment]
@alexedev what's in your `.env` file? I have a hunch `NODE_ENV` is being overwritten. It should be `development` locally, and `production` for deployment to now.

**Comment by revskill10** [comment]
@alexedev  Your code has problem in this line
```js
return withCSS(config);
```

The `config` is `undefined`.

**Comment by MaksKoseda** [comment]
@jesstelford The problem on local build is resolved but I still get a 502 in Now.
## My config
```
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW
      ? require('next/constants')
      : require('next-server/constants');

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production.
    return {};
  }

  // ✅ Put the require call here.
  const withCSS = require('@zeit/next-css');

  return withC
```
## Now logs
```
Unable to import module 'now__launcher': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/next.config.js:5:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by jesstelford** [comment]
😱 My apologies, I gave you a bum steer; the env var we should be checking against is `NOW_REGION` (not `NOW`). I've updated the examples above, and copied here for posterity:

```javascript
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW_REGION // ℹ️ Must be `NOW_REGION`, not `NOW` (my bad)
      ? require('next/constants')
      : require('next-server/constants');

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production.
    return {};
  }

  const withCSS = require('@zeit/next-css');

  return withCSS();
};
```

The only change is:

```diff
     ? {}
-    : !process.env.NOW
+    : !process.env.NOW_REGION
       ? require('next/constants')
```

**Comment by timneutkens** [comment]
Just opened #5846 to address this issue

**Comment by alexedev** [comment]
@revskill10 it is defined in the upper scope

**Comment by carlesandres** [comment]
@jesstelford that change:

```diff
     ? {}
-    : !process.env.NOW
+    : !process.env.NOW_REGION
       ? require('next/constants')
```

fixed my problem with deploying to now v2. Thanks!

**Comment by jesstelford** [comment]
And, err, in case anyone thinks otherwise; I don't work for @zeit, or on the `now` platform. I'm just someone who came up against this issue and wanted to share my knowledge on how to get past it.

Thank you everyone who has been thoughtful and helpful while we worked it out together ❤️

Hopefully a more official fix will come from @timneutkens in #5846 👍

**Comment by sheerun** [comment]
@timneutkens Will it ever be possible to run `@zeit/next-sass` with now 2? How can lambda support binary module?

**Comment by timneutkens** [comment]
Afaik it already works, you just have to change next.config.js as outlined by https://github.com/zeit/next.js/issues/5750#issuecomment-445575468

**Comment by alexedev** [comment]
well, I finally resolved my problem... 

lambda failed because I relied on `dotenv` package to take env values from .env
but two things went wrong:
1. .env is ignored by now
2. deployment is broken if `require('dotenv').config();` is called in now environment (I did not understand the reason yet).

Instead, env values should be referenced in now.json
see https://zeit.co/docs/v2/deployments/environment-variables-and-secrets/

So here is how the fixed config looks like:

```js
if (!process.env.NOW_REGION) {
  // for now-ci deployment env values are taken not from .env but from now.json
  // https://zeit.co/docs/v2/deployments/environment-variables-and-secrets/
  // now deployment breaks if dotenv used
  require('dotenv').config();
}

const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW_REGION
    ? require('next/constants')
    : require('next-server/constants');

const config = {
  publicRuntimeConfig: {
    endpoint: process.env.ENDPOINT,
    username: process.env.USERNAME,
    password: process.env.PASSWORD
  }
};

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production
    return config;
  }

  const withCSS = require('@zeit/next-css');

  return withCSS(config);
};
```

this can get a bit more readable by assigning `process.env.NOW_REGION` to a constant but I wanted to be explicit

If you have any other suggestions for more eloquent fix, please let me know

PS my `now.json` looks like

```json
{
  "version": 2,
  "builds": [{ "src": "next.config.js", "use": "@now/next" }],
  "env": {
    "ENDPOINT": "@endpoint",
    "USERNAME": "@username",
    "PASSWORD": "@password"
  }
}
```

**Comment by webpro** [comment]
An alternative to `dotenv` as @alexedev describes is `dotenv-webpack`:

```
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW_REGION
    ? require('next/constants')
    : require('next-server/constants');

module.exports = phase => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    return {};
  }

  const DotEnv = require('dotenv-webpack');

  return {
    webpack: config => {
      config.plugins.push(new DotEnv());
      return config;
    }
  };
};
```

Then you can use `process.env.*` directly as it will be read from `.env` and replaced during build.

**Comment by humet** [comment]
> @alexedev, @carlesandres, @MaksKoseda:
> 😱 My apologies, I gave you a bum steer; the env var we should be checking against is `NOW_REGION` (not `NOW`). I've updated the examples above, and copied here for posterity:
> 
> ```js
> const { PHASE_PRODUCTION_SERVER } =
>   process.env.NODE_ENV === 'development'
>     ? {}
>     : !process.env.NOW_REGION // ℹ️ Must be `NOW_REGION`, not `NOW` (my bad)
>       ? require('next/constants')
>       : require('next-server/constants');
> 
> module.exports = (phase, { defaultConfig }) => {
>   if (phase === PHASE_PRODUCTION_SERVER) {
>     // Config used to run in production.
>     return {};
>   }
> 
>   const withCSS = require('@zeit/next-css');
> 
>   return withCSS();
> };
> ```
> 
> The only change is:
> 
> ```diff
>      ? {}
> -    : !process.env.NOW
> +    : !process.env.NOW_REGION
>        ? require('next/constants')
> ```

This fixed the issue for me! Thanks @jesstelford

**Comment by go-diego** [comment]
@jesstelford  OMG I finally got this to work thanks to you!. Thanks a lot man!

@TLevesque Btw, I got mine to work with `next-compose-plugins` with:

```
const {PHASE_PRODUCTION_SERVER} =
    process.env.NODE_ENV === "development"
        ? {} // We're never in "production server" phase when in development mode
        : !process.env.NOW_REGION
        ? require("next/constants") // Get values from `next` package when building locally
        : require("next-server/constants"); // Get values from `next-server` package when building on now v2

const nextConfig = {
    webpack: config => {
        // Fixes npm packages that depend on `fs` module
        config.node = {
            fs: "empty"
        };

        config.module.rules = config.module.rules.map(rule => {
            if (rule.loader === "babel-loader") {
                rule.options.cacheDirectory = false;
            }
            return rule;
        });
        return config;
    }
};

module.exports = (phase, {defaultConfig}) => {
    if (phase === PHASE_PRODUCTION_SERVER) {
        return {};
    }

    //const withImages = require("next-images");
    const withSass = require("@zeit/next-sass");
    const {withPlugins} = require("next-compose-plugins");

    return withPlugins([[withSass]], nextConfig)(phase, defaultConfig);
};

```

**Comment by balupton** [comment]
Worth noting, that considering this issue, the documentation here is incorrect then:
https://www.npmjs.com/package/@zeit/next-typescript

**Comment by fillipvt** [comment]
> An alternative to `dotenv` as @alexedev describes is `dotenv-webpack`:
> 
> ```
> const { PHASE_PRODUCTION_SERVER } =
>   process.env.NODE_ENV === 'development'
>     ? {}
>     : !process.env.NOW_REGION
>     ? require('next/constants')
>     : require('next-server/constants');
> 
> module.exports = phase => {
>   if (phase === PHASE_PRODUCTION_SERVER) {
>     return {};
>   }
> 
>   const DotEnv = require('dotenv-webpack');
> 
>   return {
>     webpack: config => {
>       config.plugins.push(new DotEnv());
>       return config;
>     }
>   };
> };
> ```
> Then you can use `process.env.*` directly as it will be read from `.env` and replaced during build.

This is the exact same problem I had when trying to directly implement [`with-dotenv`](https://github.com/zeit/next.js/tree/canary/examples/with-dotenv) from the Next.JS examples.

Thank you @webpro and @jesstelford  !!! It worked perfectly. You don't know how many hours I've wasted in this and how many more I would've wasted without you guys. Thanks!

**Comment by mulholio** [comment]
Nothing on this thread seems to be working out. 

I can run locally, but @webpro 's solution to use Webpack dotenv doesn't seem to get my Now deployment working:

```
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW_REGION
    ? require('next/constants')
    : require('next-server/constants');

module.exports = phase => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    return {};
  }

  const DotEnv = require('dotenv-webpack');

  return {
    webpack: config => {
      config.plugins.push(new DotEnv());
      return config;
    }
  };
};
```
@jesstelford 's original solution does not work either.

The problem seems to be that I can't access my environment variables with `process.env.VARIABLE_NAME` when in production. Has anyone else had success with a now-deployed app that uses process.env with secrets successfully?

My small repo that I'm struggling with is here: https://github.com/mulholio/onboard

**Comment by webpro** [comment]
@mulholio I'm using it in https://github.com/webpro/bookstore

**Comment by mulholio** [comment]
@webpro do you have any secret variables? I'm starting to think that might be some of my problem.

**Comment by webpro** [comment]
@webpro No

**Comment by timneutkens** [comment]
Everyone in this issue will want to upgrade their application to this: https://github.com/zeit/now-examples/pull/214

- Much smaller lambdas
- Reproducible result
- No "custom" environment, just what you provide, we don't override `package.json` + don't drop yarn.lock/package-lock.json anymore. We don't add next-server anymore etc. 

More details here: https://github.com/zeit/now-builders/pull/150

**Comment by balupton** [comment]
@timneutkens can you provide details on how to use that with with-typescript and with-css, as most people in this issue ran into problems because of a mandatory useage of one of the with-* helpers. Are such helpers no longer necessary?

**Comment by timneutkens** [comment]
I'm not sure what the issue is 🤔 As per zeit/now-examples#214:

1. Add now.json

```
{
  "version": 2,
  "builds": [
    {"src": "package.json", "use": "@now/next"}
  ]
}
```

2. Upgrade to Next.js 8 canary

```
yarn add next@canary
```

3. Enable serverless target in next.config.js:

```
module.exports = {
  target: 'serverless'
}
```

Or when you're using plugins:

```
const withTypescript = require('@zeit/next-typescript')
module.exports = withTypescript({
  target: 'serverless'
})
```

You can read more about the serverless target here: https://github.com/zeit/now-builders/pull/150

And here: https://github.com/zeit/next.js/pull/5927

**Comment by balupton** [comment]
@timneutkens ok great, so none of the workarounds above that we had to do are necessary anymore! Fantastic! Thanks you for your hard work

**Comment by timneutkens** [comment]
Exactly 🙏 No workarounds and a lot of benefits 👍

**Comment by adamszeptycki** [comment]
@timneutkens 
After adding the changes you suggested I see:
```
Error: Cannot find module '<path>/src/.next/server/static/OJLfDlRyija6wxm_8Ywn4/pages/_document'
```
And it turns out that is really missing `OJLfDlRyija6wxm_8Ywn4` folder in static.

**Comment by adamszeptycki** [comment]
but it's missing `_document`
file in that path

**Comment by timneutkens** [comment]
Are you deploying to Now or your own hosting?

**Comment by adamszeptycki** [comment]
AWS lambda

**Comment by timneutkens** [comment]
Please read https://github.com/zeit/next.js/pull/5927. It sounds like you're deploying a Next.js `server`, instead you should deploy the standalone functions that come out of the Next.js serverless target build.

**Comment by webpro** [comment]
Example working migration: https://github.com/webpro/bookstore/commit/4879717dd0e358d558e04d3463637c60866a3b0e per @timneutkens guide. Thanks, Tim!

**Comment by akolybelnikov** [comment]
As it is explained [here](As explained [here](https://zeit.co/docs/v2/deployments/official-builders/next-js-now-next/#custom-server)  no custom server can be used with lambdas deployed with now v2. Does it mean next-routes cannot be used? What about dynamic pages with clean urls?
