### ISSUE TITLE
Tree Shaking doesn't work when using wildcard export

### ISSUE THREAD

**Issue by damianfrizzi** [zeit/next.js#5754]
# Bug report

We're trying to introduce a top level file which reexports named exports from its subfolders. Unfortunately this breaks Tree Shaking.

## To Reproduce
1. Clone https://github.com/damianfrizzi/next.jsTreeShaking
2. yarn && yarn analyze
3. have a look at the generated index.bundle (client)

## Expected behavior
The generated index bundle shouldn't contain myOtherComponent.tsx

## Screenshots
![image](https://user-images.githubusercontent.com/5004390/49102765-f6c6fa00-f279-11e8-805a-615b980fae6f.png)

## System information
 - OS: Windows
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
I believe you have to mark all modules as side-effect free `"sideEffects": false"` in your package.json would do it I guess

**Comment by damianfrizzi** [comment]
That did the job, thanks!
Although we're using next-css and therefore have to mark the CSS imports as side effects:
```
"sideEffects": [
  "*.css"
]
```
