### ISSUE TITLE
Secret exposed in 'publicRuntimeConfig' example in README.md

### ISSUE THREAD

**Issue by kozmic** [zeit/next.js#5758]
# Bug report

## Describe the bug

The `publicRuntimeConfig` example in README.md shows how to expose server-side secret to the frontend/client. This is an unfortunate example, as this may make developers belive that this is secure and a best practise, while in reality secrets should never be exposed to the client. The `publicRuntimeConfig` example should not contain any secrets.

Current example in README.md:
```
// next.config.js
module.exports = {
  serverRuntimeConfig: { // Will only be available on the server side
    mySecret: 'secret'
  },
  publicRuntimeConfig: { // Will be available on both server and client
    staticFolder: '/static',
    mySecret: process.env.MY_SECRET // Pass through env variables
  }
}
```

**Comment by eoftedal** [comment]
Yeah, line 1447 and line 1462 seem contradictory
