### ISSUE TITLE
Pre-rendering CSS?

### ISSUE THREAD

**Issue by dangodev** [zeit/next.js#576]
Since the release of #319 it seems like all the CSS is no longer pre-rendered. To my recollection, `next/css` was pre-rendering styles, but as of `1.2.3`, now that we can choose our own method, neither Glamor nor Styled Components seem to be pre-rendering CSS on initial load.

Currently, this means that when JS is disabled, nothing on the page is styled. And when JS is enabled, there’s a jarring FOUC while the styles load.

What are my current options for a CSS-in-JS method that allows for prerendering, other than throwing a giant CSS dump at `next/head`? Prerendering is kinda the big sell of what attracted me to Next over a simple create-react-app setup.

**Comment by rauchg** [comment]
@dangodev all the examples of CSS-in-JS for 2.0 do prerendering, and so does `<styled jsx>`

**Comment by dangodev** [comment]
Just want to make sure I’m doing this correctly. On `2.0.0-beta.8`, and following the [with-styled-components](https://github.com/zeit/next.js/tree/master/examples/with-styled-components) example. When I run the example separately, the 2.0 beta doesn’t pre-render (text is black with JS disabled when it should be red). I’m noticing the same on my personal, more complicated use case. Is this still in the works?

No pressure at all; I was just curious. As an aside, I’m really, really loving this repo. And I appreciate the time and thought put into everything. Thanks for all the great work!

**Comment by rauchg** [comment]
Gotcha! In that case, let's open an issue specifically to fix the styled-components example.
