### ISSUE TITLE
how to use async actions with axios in redux？

### ISSUE THREAD

**Issue by wsdo** [zeit/next.js#5765]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

![image](https://user-images.githubusercontent.com/9738969/49195333-9cd14c00-f3c1-11e8-830f-78cc1733a3cb.png)
`  static async getInitialProps({ reduxStore, req }) {
    const isServer = !!req
    // reduxStore.dispatch(serverRenderClock(isServer))
    await reduxStore.dispatch(list(isServer))
    // const store = initStore(reducer, null, isServer)
    // await store.dispatch(fetchDataFromApi())
    // console.log('reduxStore',req)
    // await this.props.dispatch(list())
    return { }
  }
//   Page.getInitialProps = async ({ store }) => {
//     await store.dispatch(fetchItems());
// };
  componentWillMount() {
    const { dispatch } = this.props
    list(dispatch)
    // startClock(dispatch)
    // this.timer = startClock(dispatch)
  }
`
**The problem: the posts state is empty when I view the source code in the browser**

![image](https://user-images.githubusercontent.com/9738969/49195363-c4c0af80-f3c1-11e8-9c08-3ae2898892bd.png)

How to operate correctly，how to use async actions with axios in redux？

**Comment by timneutkens** [comment]
> Questions should be posted on spectrum.chat/next-js

As per the issue template.
