### ISSUE TITLE
Cannot find module 'ajv/lib/compile/equal'

### ISSUE THREAD

**Issue by MicroBenz** [zeit/next.js#5768]
# Bug report

## Describe the bug

It throw error `Cannot find module 'ajv/lib/compile/equal'` when perform build via `next build`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Install dependencies by using `yarn`
2. Run `next build`
3. See the error

## Expected behavior
It should build successfully.

## Screenshots
On my Macbook

![image](https://user-images.githubusercontent.com/9103800/49206813-d3b95900-f3e5-11e8-91dc-94fb75b5d887.png)

Also on Drone in CI process.

![image](https://user-images.githubusercontent.com/9103800/49206835-eaf84680-f3e5-11e8-84af-fb16a9b82e77.png)

## System information
 - Version of Next.js: 7.0.2

## Additional context

I think the problem itself is because [ajv](https://github.com/epoberezkin/ajv) just bump it's version to 6.6.0 which remove `equal` function.

## Work around

For those who also get this error, you can add `ajv` as dependencies with exact version 6.5.5
```
"ajv": "6.5.5"
```

**Comment by timneutkens** [comment]
https://github.com/epoberezkin/ajv/issues/889

**Comment by felixbaron** [comment]
This is definitely a bug that needs to be resolved.

**Comment by Raftos18** [comment]
This solution works. I was having trouble all morning. Thank you!

**Comment by revskill10** [comment]
I got this error with `next@canary`, not `next@7.0.2` .

**Comment by timneutkens** [comment]
Should be fixed: https://github.com/epoberezkin/ajv/commits/master
