### ISSUE TITLE
Hot reloading resets component state

### ISSUE THREAD

**Issue by ajsharp** [zeit/next.js#5769]
# Bug report

## Describe the bug

When next hot reloads a component in development, it should maintain the existing component state. Currently, it completely re-mounts the component, resetting the state back to the initial state.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create a new next app: https://codesandbox.io/s/pnk28ml4m
2. Start the next server: `npx next`
3. Click the toggle button to change the component state
4. Change the component by adding a dom node to it, save the file.
5. When the component reloads, it will reset the state back to 'initial'

## Expected behavior
The state of the component should stay the same as it was before the reload

## Screenshots

<img width="1087" alt="hello-world_-_codesandbox" src="https://user-images.githubusercontent.com/12774/49213763-d8e0be80-f379-11e8-8c9a-cd55b534857f.png">
<img width="1097" alt="hello-world_-_codesandbox" src="https://user-images.githubusercontent.com/12774/49213830-0594d600-f37a-11e8-9095-10191f3c1338.png">
<img width="1163" alt="hello-world_-_codesandbox" src="https://user-images.githubusercontent.com/12774/49213911-3ecd4600-f37a-11e8-9219-fd2496a09af1.png">

## System information
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
This is by design, holding component state, with something like react-hot-loader, is very error prone and causes all kinds of HMR related issues, for example React component lifecycles behave very differently.

**Comment by ajsharp** [comment]
Well that's a bummer, as it's a pretty major productivity decrease in development. Apparently it was removed in 6.1? https://zeit.co/blog/next6-1

Is it possible to add it back as a babel plugin?

**Comment by timneutkens** [comment]
Yeah I guess you could add the react-hot-loader babel plugin, but like I said there's a reason this was removed.

**Comment by Nyadesune** [comment]
Then HMR doesn't work at all? Why is it still being listed as an Next.js feature? :(

**Comment by timneutkens** [comment]
It does work, and it's more correct than preserving React state, because keeping the state introduces all kinds of side-effects / unexpected behavior, which is the reason react-hot-loader was removed.
