### ISSUE TITLE
support reading from process.env.PORT

### ISSUE THREAD

**Issue by viankakrisna** [zeit/next.js#577]
currently we need to define which port next should start to with -p

**Comment by rauchg** [comment]
`next start -p $PORT` ?

**Comment by crcastle** [comment]
`-p $PORT` works for me in the current release (1.2.3).

**Comment by viankakrisna** [comment]
yes, but shouldn't it be the default?

**Comment by rauchg** [comment]
Explicit > implicit right?

**Comment by jaydenseric** [comment]
Can we rethink this? It would be much more elegant if `process.env.PORT` was respected as a default.

**Comment by jaydenseric** [comment]
I am having issues with the recommended approach when process.env.PORT is populated by a `.env` file: https://github.com/zeit/next.js/issues/1799.
