### ISSUE TITLE
<Head /> Titles Are Blank

### ISSUE THREAD

**Issue by geirman** [zeit/next.js#5774]
# Bug report

## Describe the bug
Bug #5635 was closed as a duplicate of #5628, but I don't think it actually was a duplicate. I can see why you'd think so at first glance though. Both seem to be related to the Fragment tag's usage, but at least for the case of #5635, I think that was a coincidence because the problem described there is something I'm also seeing.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Run `git clone https://github.com/geirman/nextjs-title-bug`
2. Run `cd nextjs-title-bug`
3. Run `Yarn` (duh!)
4. Run `npm run dev`
5. `Note` that the expected title flashes briefly, then becomes empty.
6. Now disable javascript and reload the page
7. `Note` the server rendered title persists as expected

## Expected behavior
The server rendered title should persist even after the client script is run

## Screenshots
![kapture 2018-11-29 at 18 16 59](https://user-images.githubusercontent.com/1640318/49264434-0d4c8d00-f403-11e8-946f-a3392436a7b7.gif)

## System information
 - OS: macOS
 - Browser (if applies) Firefox
 - Version of Next.js: 7.0.2

## Additional context
So you don't have to go through the repo code...here's a copy/paste of the relevant pages.

**Page.js** 

```
import Head from 'next/head'
import Title from './Title'

const Page = props => (
  <div>
    <Head>
      <Title title={props.title} />
    </Head>
    {props.children}
  </div>
)

export default Page
```

**Title.js**

```
export default ({ title }) => (
  <title>
    {`${title} | My Awesome Website`}
  </title>
)
```

**/pages/index.js** used like so...

```
import Page from '../layout/Page'

const Home = props => (
  <Page title="Home">
    <h1>Home</h1>
    <p>Hey home!</p>
  </Page>
)

export default Home
```

**Comment by lucleray** [comment]
Maybe this happens because `<title>` is nested inside `<Head>` 🤔

Have you tried with Title.js calling next/head directly itself ?
```jsx
import Head from 'next/head'

export default ({ title }) => (
  <Head>
    <title>
      {`${title} | My Awesome Website`}
    </title>
  </Head>
)
```

And removing Head from Page.js :
```jsx
import Title from './Title'

const Page = props => (
  <div>
    <Title title={props.title} />
    {props.children}
  </div>
)

export default Page
```

**Comment by geirman** [comment]
You're right. Since `Title` is just a stateless functional component, I would expect it to work. But if I remove the extra layer, it works. Why would that be? Are there nuances to React's composability at play here I'm not aware of? thx for your time @lucleray

**Comment by lucleray** [comment]
@geirman 
This is because of the implementation of next/head, and doesn't really have to so with react. next/head will loop over its direct children, but won't look recursively for nested title, meta, ... This is necessary so that next/head can help you do some useful things (order tags, deduplicate meta, title tags, ...)

**Comment by geirman** [comment]
Ah, that makes sense. Thanks for the explanation!
