### ISSUE TITLE
Integrate 3rd-party code snippet (HelpScout) inside nextjs HEAD or body

### ISSUE THREAD

**Issue by sshadmand** [zeit/next.js#5792]
I'm trying to integrate HelpScout in my next app, but I get syntax errors.

```
<script type="text/javascript">!function(e,t,n){function a(){var e=t.getElementsByTagName("script")[0],n=t.createElement("script");n.type="text/javascript",n.async=!0,n.src="https://beacon-v2.helpscout.net",e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],"complete"===t.readyState)return a();e.attachEvent?e.attachEvent("onload",a):e.addEventListener("load",a,!1)}(window,document,window.Beacon||function(){});</script>
```

I saw https://github.com/zeit/next.js/issues/3980,  and looked up the help docs mentioned there but still can't get it to work without errors. https://github.com/zeit/next.js/tree/canary/examples/head-elements, for example, is showing examples of meta tags, but my issue is more around the JS code within the tags are not getting accepted. Could someone give my a bit more specified guidance.

Thanks!

**Comment by alinchican** [comment]
Use [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) on a script element inside the Head component in a custom [Document](https://github.com/zeit/next.js#custom-document). You can view an example [here](https://github.com/zeit/next.js/blob/85769c3d3296cdcddc0fb36f05058c8e451ca57f/examples/with-google-analytics/pages/_document.js#L23
).

**Comment by sshadmand** [comment]
Yup that was it. 

For future readers...

I converted the OP to....

```
<script
            dangerouslySetInnerHTML={{
              __html: `!(function (e, t, n) { function a () { 
                var e = t.getElementsByTagName('script')[0], n = t.createElement('script'); 
                n.type = 'text/javascript', n.async = !0, n.src = 'https://beacon-v2.helpscout.net', e.parentNode.insertBefore(n, e) } 
                if (e.Beacon = n = function (t, n, a) { 
                  e.Beacon.readyQueue.push({method: t, options: n, data: a}) 
                }, n.readyQueue = [], t.readyState === 'complete') 
                return a(); e.attachEvent ? e.attachEvent('onload', a) : e.addEventListener('load', a, !1) 
              }(window, document, window.Beacon || function () {}))` }}
          />
```
