### ISSUE TITLE
Errors when trying the minimal setup

### ISSUE THREAD

**Issue by dmitriz** [zeit/next.js#581]
The minimal setup at the beginning of
https://zeit.co/blog/next

seems to generate cryptic errors:

```bash
ERROR  Failed to compile with 4 errors

These dependencies were not found in node_modules:

* ./pages/index.js?entry
* /Users/dmitrizaitsev/Dropbox/Sandbox/nextjs-test/node_modules/next/dist/pages/_error.js?entry
* /Users/dmitrizaitsev/Dropbox/Sandbox/nextjs-test/node_modules/next/dist/pages/_error-debug.js?entry
* /Users/dmitrizaitsev/Dropbox/Sandbox/nextjs-test/node_modules/next/dist/pages/_document.js?entry

Did you forget to run npm install --save for them?
> Ready on http://localhost:3000

```

`npm install` does not help :(

**Comment by nkzawa** [comment]
It looks weird. Let me know how your project directory looks like.

**Comment by dmitriz** [comment]
Here is the clone of my directory:

https://github.com/dmitriz/nextjs-test

**Comment by arunoda** [comment]
@dmitriz could you tell us your dev env?

* OS
* Node version
* NPM version

**Comment by cncolder** [comment]
@arunoda Same as me after upgrade to v2.0.0-beta6

**Comment by cncolder** [comment]
When I run `next build`. I saw an error like this:

> Module not found: Error: Can't resolve 'babel-loader'

And I change webpack config as below then resolve it.

```js
webpack: (config, { dev }) => {
    config.resolveLoader.modules.push(path.join(process.cwd(), 'node_modules'))
    return config
}
```

Maybe this is a difference between webpack@1 and webpack@2.

**Comment by dmitriz** [comment]
```bash
node -v; npm -v
v6.9.2
4.0.5
```

Mac OSX 10.8.5

**Comment by arunoda** [comment]
@nkzawa this happens when we install it from NPM or via `file:///`.
Works with `npm link`.

**Comment by arunoda** [comment]
@cncolder Thanks for the hint.
Yep. It was the issue.

I've added app's node modules dir into resolve loaders by default via #583.
It'll fix this issue.

**Comment by arunoda** [comment]
Guys, try: `next@2.0.0-beta.7`

**Comment by sarovin** [comment]
@arunoda Yes, it fix for me...

**Comment by dmitriz** [comment]
Works now!

Many thanks for fixing it so quick!
