### ISSUE TITLE
Support immutable deploys - aka immutablewebapps

### ISSUE THREAD

**Issue by radubrehar** [zeit/next.js#5824]
# Feature request

Support deployments as described by https://immutablewebapps.org/

**Comment by timneutkens** [comment]
What are you referring to exactly? Next.js follows most of these concepts already.

Please provide as much context as possible when creating issues.

**Comment by radubrehar** [comment]
Okay, I'll give it a try, and maybe I'll do a PR with an example? Hopefully it will help someone 😀

**Comment by Enalmada** [comment]
@radubrehar What do you feel next.js doesn't support from that page?

**Comment by timneutkens** [comment]
That's what confuses me too 😄

**Comment by radubrehar** [comment]
You're right! After carefully reading through, I think nextjs implements all of the principles behind immutable webapps 🎉!

**Comment by timneutkens** [comment]
💯
