### ISSUE TITLE
Hot code reloading with Google Amp

### ISSUE THREAD

**Issue by jlarmstrongiv** [zeit/next.js#5827]
# Bug Report

## Example name
with-amp
https://github.com/zeit/next.js/tree/canary/examples/with-amp

## Describe the bug
Hot code reloading does not work on the client side

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone and install the `with-amp` example
2. Make a simple change.  For instance, change The Cats to The Catzzzzzzz
3. Save change in code editor
4. Client on localhost does not refresh

## Expected behavior
I expected client on localhost to refresh.

## System information
 - OS: macOS
 - Browser (if applies): chrome
 - Version of Next.js: version from example and 7.0.2

## Additional context
While custom javascript would cause an amp page to be invalid, that’s fine for development where you can see the errors to fix and are constantly making changes. Is there a way to have Next.js hot code reloading in dev, but not in build or export?

**Comment by Capricair** [comment]
Hello, did you resolve this issue? @jlarmstrongiv

**Comment by jlarmstrongiv** [comment]
I resolved the issue by adding the next scripts in development mode only.  However, the error pages do not work on the [now-cli](https://github.com/zeit/now-cli/issues/1735), which I have been unable to fix.
