### ISSUE TITLE
Unexpected token import in node_modules using fontello.ttf

### ISSUE THREAD

**Issue by luizdotpro** [zeit/next.js#5830]
After solving problems with .ttf files through `webpack`. I still stuck in one issue after the building modules. For a week I receive this message: 

>
> ./node_modules/.../elements/styles/fonts/fontello.ttf:1
> (function (exports, require, module, __filename, __dirname) { 
>                                                               
> 
> SyntaxError: Invalid or unexpected token
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:616:28)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/Users/lcarneir/Documents/sport1_repos/ImfootballWebClient/node_modules/sport1-universal-components-lib/build/elements/index.js:2:15)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
> 

As I am aware that `nextjs  ignores the node_modules directory from being compiled by babel`, I would like to know at least from where should I keep my search to solve this issue or eventually hear from someone that faced the same message. Thanks in advance.

**Comment by timneutkens** [comment]
Please follow the issue template, questions should be posted on https://spectrum.chat/next-js as there are more people there that might be able to help.
