### ISSUE TITLE
Problem with getInitialProps() and onLoad()

### ISSUE THREAD

**Issue by zluo01** [zeit/next.js#5838]
I am new to next.js and during my development, I encounter couple questions.

First,  following is part of  codes from my index.js

`import Layout from '../components/layout';`
`import Recommend from './recommend';`
`import axios from "axios";`
`import React from 'react';`
`const Index = (props) => (`
`    <Layout>`
`           <Recommend/>`
`    </Layout>`
`);`

The problem is in the Recommend I implement getInitialProps function. However, when I load the page,  the getInitialProps function is never executed. I want to ask if in next.js, the only getInitialProps will load is the one in index.js one ?

Second question is I try to use onLoad in my layout.js when loading the page, but again, it is also never executed.

Thanks advance

**Comment by timneutkens** [comment]
`getInitialProps` can only be added on top level `pages`. 

`getInitialProps` is executed on the server side when requesting a page, the result is shipped to the client side and then used to hydrate the page. Then on subsequent `<Link>` clicks `getInitialProps` is executed on the client side.


Please follow the issue template in the future.

**Comment by zluo01** [comment]
Sorry, I do not know how to add the label to the issues....

About the question, I am developing a SPA, and trying to load the contends once when page load, I want to ask if there is any way I can execute or do request call in Recommend or I have to move all of them in the index.js in order to make them works since my `<Link>` is actually href to part of the page with `#` ???

Thank you
