### ISSUE TITLE
Implement tslint for core files

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#5845]
# Feature request

## Is your feature request related to a problem? Please describe.

`eslint` has a parser for typescript but it proves to be insufficient for all cases of typescript, so implement tslint is the way to go.

## Describe the solution you'd like

Implement `tslint` for both `next` and `next-server`, but keep standardjs/eslint for the `.js` files that are still there, we're gradually migrating to Typescript.

## Additional context

Feel free to reach out under this issue with questions if needed, I'd be happy to give advice.

**Comment by rauchg** [comment]
Does tslint provide significant value over strict mode + prettier? I was not able to ascertain this from my Twitter survey

**Comment by timneutkens** [comment]
For example by default even in strict mode return types are not required
