### ISSUE TITLE
Error: Cannot find module 'next-server/constants'

### ISSUE THREAD

**Issue by sc4224** [zeit/next.js#5854]
# Question about Next.js
Hi, when I run npm run build, I get an error above. How do I go about troubleshooting this? There isn't a way for me to understand what is going on with this error log.

Questions should be posted on https://spectrum.chat/next-js
Nobody replied so I'm posting it here.

**Comment by sheerun** [comment]
You need to use stable version of next.js, canary is not stable yet. btw. referencing https://github.com/zeit/next.js/issues/5406

**Comment by timneutkens** [comment]
Based on what you're saying I guess it's: https://github.com/zeit/next.js/issues/5750#issuecomment-445575468
