### ISSUE TITLE
Server Side Event is Not Working

### ISSUE THREAD

**Issue by poovarasanvasudevan** [zeit/next.js#5855]
# Bug report
Server Side Event is Not Working
## Describe the bug

i am using express-sse (https://www.npmjs.com/package/express-sse) for server side event server ,  i point to /stream as an endpoint to SSE

```
var SSE = require('express-sse');
var sse = new SSE(["array", "containing", "initial", "content", "(optional)"]);

nxt.prepare()
    .then(() => {
         app.get('/stream', sse.init);
   })

```

and in the client side

```
    componentDidMount() {
        this.source = new EventSource('/stream')
        this.source.onmessage = function(e) {
           console.log(e)
        }
    }

```

I able to Successully connected to (SSE)  server by when i emit from server side, i am not able to get from client side

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
Create blank nextjs project and install express and express-sse

in the server.js Create sse endpoint

```
var SSE = require('express-sse');
var sse = new SSE(["array", "containing", "initial", "content", "(optional)"]);

nxt.prepare()
    .then(() => {
         app.get('/stream', sse.init);
   })

```

and in index.js (Client)

```
    componentDidMount() {
        this.source = new EventSource('/stream')
        this.source.onmessage = function(e) {
           console.log(e)
        }
    }

```

## Expected behavior
i added console.log it was not printing, i am hitting from the server

## System information
 - OS: Windows
 -  Chrome, Firefox
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
This does not relate to Next.js / Is not a bug in Next.js.
