### ISSUE TITLE
Deploy failed on GCP due to build problems

### ISSUE THREAD

**Issue by arherzf8er** [zeit/next.js#5856]
# Bug report

## Describe the bug

Unable to build an app with custom server while trying to deploy on GCP.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Get custom server app
2. Install latest GCP
3. Run `gcloud app deploy`

## System information
 - OS: Linux 18.10
 - Version of Next.js: 7.0.2

## Additional context

![2018-12-11 11-21-18 png](https://user-images.githubusercontent.com/29209372/49782318-af3f7400-fd37-11e8-99eb-10495e7c0b5c.jpg)

package.json

```
"scripts": {
    "test": "mocha",
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  }
```

**Comment by timneutkens** [comment]
Sounds like `next build` was not executed.
