### ISSUE TITLE
Pre-render styled components

### ISSUE THREAD

**Issue by dangodev** [zeit/next.js#586]
Styled components doesn’t prerender styles as of `2.0.0-beta.8`, as evidenced by the [with-styled-components](https://github.com/zeit/next.js/tree/master/examples/with-styled-components) example. When JS is disabled, the text remains black when it should be red.

**Comment by nkzawa** [comment]
Closed via https://github.com/zeit/next.js/commit/64aa4454ace64c2982f53374334834c9f47bb491
