### ISSUE TITLE
error catching custom routes after deploy to production with now

### ISSUE THREAD

**Issue by hungtsou** [zeit/next.js#5863]
# Bug report
Error catching custom routes after deploy with now.

## Describe the bug
When reloading the page from a custom route I get a 404 page not found error, I have already setup the custom server and it works just fine when starting the server in production from my machine this just happens after I deploy the app with now.

## To Reproduce
repository: https://github.com/hungtsou/helloNext.js
1. deploy with now
2. go the the generated url
3. navigated to post details(for example)
4. reload the browser

## Expected behavior
It should keep and map the right view from the url.

## Screenshots
package.json
![package json hello-next 2018-12-11 14-50-55](https://user-images.githubusercontent.com/10926191/49829618-89749800-fd54-11e8-8a2a-cf2e45475dc2.jpg)
server.js
![server js hello-next 2018-12-11 14-54-30](https://user-images.githubusercontent.com/10926191/49829736-d2c4e780-fd54-11e8-8a08-fbae372c643e.jpg)
error: this only happens after I hard reload the page 
![404 the page could not be found 2018-12-11 14-57-04](https://user-images.githubusercontent.com/10926191/49829858-2f280700-fd55-11e8-8940-02145b28948a.jpg)
expected:
![https hello-next-iqxp5sk78 now sh post 975 2018-12-11 14-58-59](https://user-images.githubusercontent.com/10926191/49829946-73b3a280-fd55-11e8-837b-e6e105ed9f91.jpg)

## System information
 - OS: macOS
 - Browser: chrome latest
 - Version of Next.js: 7.0.2

Thanks in advance for the help, the framework is great!

**Comment by timneutkens** [comment]
Thanks for following the issue template, there is one thing missing here which is a reproduction repository or similar.

**Comment by hungtsou** [comment]
I found that a custom server does not fit the paradigm of Now 2.0 so that's why it could not catch the routes from server.js. 

https://spectrum.chat/zeit/now/deploying-next-js-app-with-custom-server~f6abdbd7-27af-4424-8d90-5e9d0b078188
