### ISSUE TITLE
Absolute paths used in '_app.js'

### ISSUE THREAD

**Issue by jackie19** [zeit/next.js#5874]
# Bug report

## Describe the bug

I use cnpm instead npm to install next and other pkg,
in node_modules dir, `next` is a linked file, real file is `_next@7.0.2@next`,
after run next build,  absolute path in `.next/server/static/BUILD_ID/pages/_app.js`:

```
module.exports = require("/Users/cccc/Documents/temp/next/examples/active-class-name/node_modules/_next@7.0.2@next/dist/pages/_app.js");
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Download the next example 
2. npm i -g cnpm
3. cnpm i
4. cnpm run build 

## Expected behavior
`module.exports = require("next/app");`

## Screenshots
![image](https://user-images.githubusercontent.com/2063608/49911811-c5c60680-fec2-11e8-8d1a-0dbdac9003d6.png)

![image](https://user-images.githubusercontent.com/2063608/49911847-ef7f2d80-fec2-11e8-9109-3e222fbd9fbd.png)

## System information
 - OS: macOs
 - Browser :chrome
 - Version of Next.js: 7.0.2
 - Version of cnpm: 5.1.1

**Comment by timneutkens** [comment]
This is because the path is not `node_modules/next/dist/pages/_app.js` so we can't really reliably mark it for compilation if the package installer doesn't follow npm's convention.
