### ISSUE TITLE
Dev and Production routes come out difference

### ISSUE THREAD

**Issue by carylaw** [zeit/next.js#5875]
# Bug report

## The dev routes got query, but not on production

The original path on DEV
```
localhost:3000/haha
```

on Production
```
example.com/haha/
```

And it leads the query not work, it supposed like this:

```
localhost:3000/haha?name=johndoe
```

But on Production, auto redirect like this
```
example.com/haha/?name=johndoe
```

And it make the query not work

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. create-next-app test
2. create a file under /pages named haha.js
```
import React, { Component } from 'react';
import PropTypes from 'prop-types';

class haha extends Component {
  
 render() {
  return (
   <div>Haha</div>
  );
 }
}

haha.propTypes = {

};

export default haha;
```

3. on dev will show as
```
localhost:3000/haha
```
4. on production will show as

```
example.com/haha/
```

## System information
 - OS: [e.g. macOS, Windows]
Windows
 - Browser (if applies) [e.g. chrome, safari]
Chrome 
 - Version of Next.js: [e.g. 6.0.2]
7.0.2-canary.22

**Comment by timneutkens** [comment]
Sounds like you're using next export, this is expected behavior.
