### ISSUE TITLE
Pass className into <Link>...</Link>

### ISSUE THREAD

**Issue by matthewmueller** [zeit/next.js#588]
Would probably be good to pass entire props in actually

```
<a {...props}>...</a>
```

**Comment by matthewmueller** [comment]
oh weird, seems like it does this. not sure what's going on then 😅

**Comment by matthewmueller** [comment]
Actually, I'm still running into issues with this on latest beta. Doesn't seem to work properly:

```js
<Link href="/" className="link">hi</Link>
```

**Comment by nkzawa** [comment]
@matthewmueller `Link` component accepts only `href` and `as` props. You can set `className` to `a`.

`<Link><a className="link">hi</Link>`

**Comment by matthewmueller** [comment]
Ahh interesting, does that do the same thing as `<Link href='...'>hi</Link>`?

**Comment by rauchg** [comment]
I'm pretty sure we should deprecate `<Link>text</Link>` for 2.0. (PR welcome)
It should just be HOC so that we can statically access (and decorate) children with `styled-jsx`, but also useful for css-in-js in general

**Comment by rauchg** [comment]
Also @matthewmueller that `/hi` would only apply to things like "command+tab". If what you want is to _use_ a certain page, but _decorate_ it differently in navigation, you want `<Link as>`

**Comment by impronunciable** [comment]
As @rauchg  stated we are deprecating `<Link>text</Link>` so the `className` should be applied always to the `<a>` tag

**Comment by matthewmueller** [comment]
I'm sorry but I'm still a little confused about this. Is the idea that you'd never add an `href` the the inside `<a>` tag? Or are there cases where you'd want to?

**Comment by rauchg** [comment]
We do pass down the `href` from `<Link>` to the case where you have an `<a>` child. What we're deprecating is inserting an `<a>` automagically.

You should be able to `<Link><img /></Link>` and no `<a>` is created, for example

**Comment by matthewmueller** [comment]
Got it – thanks!
