### ISSUE TITLE
deepForceUpdate is not a function 

### ISSUE THREAD

**Issue by sbatir** [zeit/next.js#5881]
# Question about Next.js

Hi everyone, 

I'm working on a webapp that uses Next.js, and everything internally works when I do a hard refresh. 
However, it's currently resulting in a poor user experience because I get the following error that appears anytime I click on a button or card. The routing and functionality work fine on the back-end, but I keep getting this error: 

I've searched around on Github and Stackoverflow, and the only solutions suggest upgrading my versions of react-dom, react, and next. Unfortunately, I have done this but nothing changes and I always get this error below. 

Additional context: My debugger also says... 

> AppContainer.dev.js?fd9b758:50 Uncaught TypeError: deepForceUpdate is not a function
>     at AppContainer.componentWillReceiveProps (AppContainer.dev.js?fd9b758:50)
>     at callComponentWillReceiveProps (react-dom.development.js?74df120:11528)
>     at updateClassInstance (react-dom.development.js?74df120:11720)
>     at updateClassComponent (react-dom.development.js?74df120:13154)
>     at beginWork (react-dom.development.js?74df120:13825)
>     at performUnitOfWork (react-dom.development.js?74df120:15864)
>     at workLoop (react-dom.development.js?74df120:15903)
>     at HTMLUnknownElement.callCallback (react-dom.development.js?74df120:100)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js?74df120:138)
>     at invokeGuardedCallback (react-dom.development.js?74df120:187)

and...

> The above error occurred in the <AppContainer> component:
>     in AppContainer (created by Container)
>     in Container (created by App)
>     in div (created by App)
>     in App
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, App.

```
deepForceUpdate is not a function
TypeError: deepForceUpdate is not a function
    at AppContainer.componentWillReceiveProps 
![screen shot 2018-12-13 at 10 54 46 am](https://user-images.githubusercontent.com/2170476/49974636-1f442a80-feef-11e8-968d-9ad6606dcb94.png)
(http://localhost:3000/_next/1544744362360/main.js:19066:7)
    at callComponentWillReceiveProps (http://localhost:3000/_next/1544744362360/commons.js:11534:14)
    at updateClassInstance (http://localhost:3000/_next/1544744362360/commons.js:11726:7)
    at updateClassComponent (http://localhost:3000/_next/1544744362360/commons.js:13160:20)
    at beginWork (http://localhost:3000/_next/1544744362360/commons.js:13831:14)
    at performUnitOfWork (http://localhost:3000/_next/1544744362360/commons.js:15870:12)
    at workLoop (http://localhost:3000/_next/1544744362360/commons.js:15909:24)
    at renderRoot (http://localhost:3000/_next/1544744362360/commons.js:15949:7)
    at performWorkOnRoot (http://localhost:3000/_next/1544744362360/commons.js:16567:22)
    at performWork (http://localhost:3000/_next/1544744362360/commons.js:16489:7)


    in AppContainer (created by Container)
    in Container (created by App)
    in div (created by App)
    in App

Questions should be posted on https://spectrum.chat/next-js

```

**Comment by timneutkens** [comment]
I'm just guessing here as there is no reproduction included and the issue template was not followed. Please always follow it so that there is enough context.

Again this is just guessing but:
AppContainer.dev.js makes it sound like you have react-hot-loader in your application, or that you have an old version of Next.js, react-hot-loader would try running deepForceUpdate or similar. This would mean that you're on a version below 6.2 (from the top of my mind), the solution would be upgrading Next.js.
