### ISSUE TITLE
High TTFB - renderToString executing multiple times 

### ISSUE THREAD

**Issue by hrdymchl** [zeit/next.js#5882]
# Bug report

## Describe the bug

We're running Next.js in Docker.

When building the image locally and using the production backend, TTFB is virtually zero, but when we deploy this image, TTFB can be up to 30 seconds in some cases. With smaller pages, TTFB is still around 1 second.

The production servers are warm servers that don't need to spin up.

I ran four tests to measure TTFB against the same route with the same production backend.

1. Locally in production mode with docker -> Low TTFB
2. Locally in production mode with yarn build && yarn start -> Low TTFB
3. Locally in dev mode with yarn run dev -> High TTFB
4. On production -> High TTFB

**Results**
• The logs show `renderToString` executing 3-4 times on a single route and `getInitialProps` taking about 1500ms
• TTFB anywhere from 1 to 30 seconds

## To Reproduce

**Dockerfile**
```
FROM node:10.13.0-alpine

WORKDIR /app

EXPOSE 8080

CMD [ "yarn", "start" ]

COPY . .

RUN yarn install

RUN yarn build
```

**Server.js snippet**

```
const express = require('express');
const next = require('next');
const cookieParser = require('cookie-parser');
const jwtDecode = require('jwt-decode');
const { join } = require('path');
const admin = require('firebase-admin');

// serviceAccount used for local development
// https://firebase.google.com/docs/admin/setup
const path = require('path');
const { fetchNewToken } = require('./src/services/Firebase');

let serviceAccount;
const dev = process.env.NODE_ENV !== 'production';
if (dev) {
  serviceAccount = require('./credentials/serviceAccountKey.json')
}
admin.initializeApp({
  credential: dev ? admin.credential.cert(serviceAccount) : admin.credential.applicationDefault(),
});

const app = next({ dev });
```

**Package.json snippet**

```
  "scripts": {
    "start": "NODE_ENV=production node server.js",
    "build": "next build",
    "dev": "NODE_ENV=development node server.js",
  },
```

## Expected behavior
I expect TTFB to be near zero.

## System information
 - OS: Mac
 - Browser: Chrome
 - Version of Next.js: 7.0.2

## Additional Context
• Dev machine and production machine are of comparable size
• There is a Loadbalancer in front of production but we've ruled that out
• I posted about this issue on [stackoverflow](https://stackoverflow.com/questions/53616324/weird-next-js-ttfb-issue)

**Comment by timneutkens** [comment]
I'm not sure what to do here, the reproduction is missing pages, package.json etc. Please provide a minimal reproduction. 

Are you using Apollo? Styled-components? Anything else that traverses the render tree?
