### ISSUE TITLE
Help Wanted! - Redux-saga action not updating state  when invoked from getInitialProps

### ISSUE THREAD

**Issue by drxwskx** [zeit/next.js#5884]
I've not been able to properly configure redux and more specifically redux sagas into my project. When dispatching an action in getInitialProps nothing happens. Here are the relevant files that I think are relevant to the issue.  I've also noted in comments where the code seems to stop executing.

And many thanks in advance! 

_document.js
![screen shot 2018-12-13 at 11 39 15 pm](https://user-images.githubusercontent.com/21091420/49983375-51c24780-ff30-11e8-8b63-e35bd0189755.png)
_app.js
![screen shot 2018-12-13 at 11 39 45 pm](https://user-images.githubusercontent.com/21091420/49983381-63a3ea80-ff30-11e8-83ec-7ab2186afaa3.png)

/pages/products.js
![screen shot 2018-12-13 at 11 40 44 pm](https://user-images.githubusercontent.com/21091420/49983414-9d74f100-ff30-11e8-8145-f0f1453d4463.png)

store.js
![screen shot 2018-12-13 at 11 37 48 pm](https://user-images.githubusercontent.com/21091420/49983337-23446c80-ff30-11e8-972f-8e0d22fb305b.png)

rootSaga.js
![screen shot 2018-12-13 at 11 43 08 pm](https://user-images.githubusercontent.com/21091420/49983462-e462e680-ff30-11e8-899e-9e28faf0490d.png)

rootSaga.js
![screen shot 2018-12-13 at 11 43 50 pm](https://user-images.githubusercontent.com/21091420/49983474-fe9cc480-ff30-11e8-9d59-6da27c21ed62.png)

example/action.js
![screen shot 2018-12-13 at 11 45 24 pm](https://user-images.githubusercontent.com/21091420/49983520-4c193180-ff31-11e8-9b66-98e9c4e11055.png)

example/saga.js
![screen shot 2018-12-13 at 11 45 14 pm](https://user-images.githubusercontent.com/21091420/49983530-59ceb700-ff31-11e8-9a80-5d5ee2e85f37.png)

**Comment by timneutkens** [comment]
Please follow the issue template.
