### ISSUE TITLE
Document how next/router works

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#5885]
# Feature request

## Is your feature request related to a problem? Please describe.

There's quite a bit of confusion on how Next.js handles routing as is slightly different from most routing frameworks out there. The reason for this is that Next.js by design has a constraint that we won't ship a routes manifest of every possible route in the application.

## Describe the solution you'd like

I've written a pretty complete comment about how `<Link>` works with custom parameters etc. It can be found here: https://github.com/zeit/next.js/issues/2833#issuecomment-414919347

Most of that comment can be used in the docs.

**Comment by timneutkens** [comment]
@paulina-grunwald definitely! You can add the docs in the readme in this repository and we automatically sync them to the docs on the website etc.

**Comment by jhoffmcd** [comment]
I would love to contribute to this as well!
