### ISSUE TITLE
next/head title should support translations

### ISSUE THREAD

**Issue by zbycz** [zeit/next.js#5888]
# Bug report

## Describe the bug

When <title> contains a react element, title is correctly shown in SSR code, but error is thrown on client. This would be very useful for some l10n components, which just return translated string.

```
import Head from 'next/head';
const Hello = () => "Hello";
...
<Head>
    <title><Hello/></title>
</Head>
```

Client throws:
```
Uncaught (in promise) TypeError: children.join is not a function
    at HeadManager.updateTitle (head-manager.js:68)
    at HeadManager.doUpdateHead (head-manager.js:55)
    at head-manager.js:41
```

## Expected behavior
I would expect the client to show the same as ssr.

## Discussion
Could we add here [head-manager.js#L45](https://github.com/zeit/next.js/blob/canary/packages/next/client/head-manager.js#L45) something like third option - to render a react element? I am not sure, if context,etc is ready.

## System information
 - Version of Next.js: 7.0.2

**Comment by ztanner** [comment]
`<title>` already supports translations if you integrate with [next-18next](https://github.com/isaachinman/next-i18next)

Ex:
```jsx
import React from "react";
import Head from "next/head";

import { i18n, withNamespaces } from "../i18n";

const Homepage = ({ t }) => (
  <React.Fragment>
    <Head>
      <title>{t("title")}</title>
    </Head>
    <button
      onClick={() => i18n.changeLanguage(i18n.language === "en" ? "de" : "en")}
    >
      {t("change-locale")}
    </button>
  </React.Fragment>
);

export default withNamespaces("common")(Homepage);
```

In other words, rather than using a component, use a function that will return a string.

**Comment by timneutkens** [comment]
Thanks @ztanner, great answer 👍

The reason you can't use components is that we render the exact children of `<Head>` into the document's `<head>` tag.

**Comment by zbycz** [comment]
Thanks for the idea.

We ended up using this, which is ugly, but works.
```
 <>
      <IntlConsumer>
        {intl => (
          <Head>
            <title>{intl.translate(__('site_title'))}</title>
          </Head>
        )}
      </IntlConsumer>
      <h1>My Page</h1>
    </>
```

**Comment by peacefulseeker** [comment]
@timneutkens , how should we act in case we are using `<Trans>` component, provided by `i18next`?
<title><Trans>Plain Title Text goes here</Trans></title>. 
Will this force to use locales files like `common.json`?
