### ISSUE TITLE
Redux-saga action not updating state when invoked from getInitialProps

### ISSUE THREAD

**Issue by drxwskx** [zeit/next.js#5889]
I've not been able to properly configure redux and more specifically redux sagas into my project. When dispatching an action in getInitialProps nothing happens. Here are the relevant files that I think are relevant to the issue. I've also noted in comments where the code seems to stop executing.

In the official example, Next.js getInitialProps seems to expect the store and isServer to be on the props.ctx object, but is present on props object directly. 

_document.js
![_document](https://user-images.githubusercontent.com/21091420/50015530-d5158480-ff94-11e8-868f-d471b3910d04.png)

_app.js
![_app](https://user-images.githubusercontent.com/21091420/50015547-dd6dbf80-ff94-11e8-89cd-921a0ff6d594.png)

/pages/products.js
![product](https://user-images.githubusercontent.com/21091420/50015587-efe7f900-ff94-11e8-91d1-b86f621130c2.png)

store.js
![store](https://user-images.githubusercontent.com/21091420/50015597-f8d8ca80-ff94-11e8-95bf-ee849289a595.png)

rootSaga.js
![rootsaga](https://user-images.githubusercontent.com/21091420/50015626-02623280-ff95-11e8-83b4-144805eb2927.png)

example/action.js
![action](https://user-images.githubusercontent.com/21091420/50015644-0db55e00-ff95-11e8-91e7-8544259a1f00.png)

example/saga.js
![saga](https://user-images.githubusercontent.com/21091420/50015665-186ff300-ff95-11e8-992b-2221f4ebb5da.png)

**Comment by timneutkens** [comment]
Again please follow the issue template, it clearly says questions should be posted on https://spectrum.chat/next-js and if you don't create the question there we have bug/feature template that ask for more context than you're currently are providing. It's close to impossible to help with screenshots of your code.
