### ISSUE TITLE
Unhandled Rejection (ReferenceError): Element is not defined

### ISSUE THREAD

**Issue by devsumanmdn** [zeit/next.js#5891]
## PropType.instanceOf(Element) throws ReferenceError: Element is not defined
```js
Component.propTypes = {
  domEl: PropTypes.instanceOf(Element)
};
```

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://codesandbox.io/s/1r729y8147
2. See error

## System information
 - Version of Next.js: [7.0.2]

**Comment by timneutkens** [comment]
`document.createElement("li")` does not work with server side rendering as Node.js doesn't have `document` `window` etc. Passing dom elements as props sounds like an anti-pattern. I'm not entirely sure what you're trying to do but here's an example of how to use `React.createPortal` that handles dom elements correctly https://github.com/zeit/next.js/tree/canary/examples/with-portals

**Comment by devsumanmdn** [comment]
Actually, I have to pass an `anchorEl` (anchor element) to correctly position another element, thanks for helping with the resource.
