### ISSUE TITLE
Route matching with params

### ISSUE THREAD

**Issue by nickdandakis** [zeit/next.js#59]
Is there any support for route params like so?
`/photos/:id`

If not, how would that look with the proposed `pages/*.js` structure?

**Comment by nodegin** [comment]
Similar question, what if I place a directory under `/pages`?

e.g. `/pages/test/profile.js` should mapping to `/test/profile` etc.

**Comment by impronunciable** [comment]
@nodegin yes, it maps that way
![screen shot 2016-10-25 at 7 40 59 pm](https://cloud.githubusercontent.com/assets/165799/19699371/ff343858-9aea-11e6-855d-182a1031b2fa.png)

@nickdandakis It's not possible right now. It doesn't mean it won't be possible in the future.

**Comment by CreepGin** [comment]
Since zeit.co is built with next.js, do all their blog urls just map to static files???

- `https://zeit.co/blog/next` -> `/pages/blog/next.js`
- `https://zeit.co/blog/now-certs` -> `/pages/blog/now-certs.js`

Anyhow, I do believe the majority of non-trivial sites depend on some form of dynamic routing (route params). So this should be pretty high up there in the future todo list, right?

**Comment by arunoda** [comment]
I'm so happy to (and want to) move a lot of apps to next once we've dynamic routing.

**Comment by nkzawa** [comment]
See also https://github.com/zeit/next.js/issues/25. It's the issue about custom server support which you can implement any routings.

**Comment by dstreet** [comment]
I'm proposing a change where parameterized routes can be defined in `package.json`. Mapping a parameterized route path to a specific file in the `paths` directory:

```javascript
{
    "next": {
        "routes": {
            "/posts/:id": "posts/post",
            "/posts/:id/comments": "posts/post/comments"
        }
    }
}
```

This implementation shouldn't interfere with existing routing logic. Parameters are also passed through the component props via `params`.

Implementation:
https://github.com/dstreet/next.js/commit/55d3173c7f47c598217f3af7662737b7e00c4637

**Comment by dlindenkreuz** [comment]
Related: #91

**Comment by nmuth** [comment]
@dstreet Personally, I think `package.json` should only contain NPM configuration (i.e. dependencies, scripts, and metadata). I'd prefer using a `next.conf.js` file for configuration specific to Next. Otherwise I like the idea 👍

**Comment by dstreet** [comment]
@nmuth, I completely agree. Not sure why I didn't think of that at first.

**Comment by sebasgarcep** [comment]
I have parametric routing working using the fantastic [https://github.com/hapijs/call](url). It allows me to define all sorts of parametric routes. For example a `/users/{name}.js` file will match to either of `/users/tom` or `/users/mark` without having to do any configuration. It is what HapiJS uses to do routing, so it's battle-tested.

**Comment by parkerproject** [comment]
@sebasgarcep do you have an example or docs on how to use this?

**Comment by arunoda** [comment]
Guys, now we've support for custom routes.
See: https://github.com/zeit/next.js#custom-server-and-routing

**Comment by sebasgarcep** [comment]
@arunoda I have some issues with the way custom routes work. Mainly that Next does not exposes its render methods and you have to pass it the raw request and response objects. Of course, that doesn't always plays nice with frameworks like Hapi when you want to embed Next.

@parkerproject If you're still interested you can email me.

**Comment by rauchg** [comment]
> Mainly that Next does not exposes its render methods and you have to pass it the raw request and response objects.

Requiring the raw request and response objects sounds like a good abstraction. Maybe Hapi should expose them, rather than us not require them?

**Comment by sebasgarcep** [comment]
They do expose them, so there's no issue with Hapi :smile:

Anyways, thanks for the input. It's a great project you have here.

**Comment by rauchg** [comment]
@sebasgarcep also, we *do* plan on exposing low-level APIs (they have been picked and designed with that in mind), but when we played around with them, they ended up being really *not ergonomic*. 

Furthermore, we found that `app.render` covers the majority of use cases (like caching, fancy routing, etc) without requiring more than just the raw, low-level HTTP request / response objects.

**Comment by sheerun** [comment]
I've prepared with-extracted-stylesheet example with custom routes that fallback to appropriate pages in both development and production, even for dynamic urls like described here: https://github.com/zeit/next.js/pull/3451

**Comment by hariantara** [comment]
how about this one. project 1 (SSR using next js) project 2 (the same), but project 1 front end call the project 2 server, how do i get the params in server of project 2 that url is rendered in project 1 on front end side?

**Comment by fortil** [comment]
if I want to export the routes to static files you  solution for `Custom server and Routing` works? @arunoda

**Comment by trusktr** [comment]
@fortil, I think it does not work with static routes and that it requires a server. A static server wouldn't be able to replace an ID in the URL with static-served content (if it could then it wouldn't be a static server anymore).

What I mean is, if we have a URL `/posts/some-post-from-a-database`, there's no way a static server could map that to a file that actually exists. The server is needed in a rider to fetch the data for the post and to serve content _not_ based on the filesystem.
