### ISSUE TITLE
router.asPath is different on server and client

### ISSUE THREAD

**Issue by leinelissen** [zeit/next.js#5901]
# Bug report

## Describe the bug

We are working on a fairly large application using Next 7 and custom express routing. Because of the size of the app, we've separated our routes into various files. The files are namespaced in express.js, and when server-side rendering any page in this namespace, it returns the URL without the namespace.

## To Reproduce

See this repo: https://github.com/leinelissen/nextjs7-req-url-issue.

Basically, the setup is:
```jsx
// /server.js
app.prepare()
  .then(() => {
    const server = express();
    server.use('/post', postRoutes(app));
  })

// postRoutes.js
module.exports = (app) => {
  router.get('/:postId', (req, res) => {
    app.render(req, res, '/post', req.params);
  });

  return router;
};
```

When accessing `/post/1234`, the asPath evaluates to `/1234` on the server and `/post/1234` on the client.

## Expected behavior
The asPath should match on the server and client

## System information
 - OS: macOS Mojave
 - Version of Next.js: 7.0.2

## Additional context

Separating routes in files is common practice in Express.js (see [this](http://catlau.co/how-to-modularize-routes-with-the-express-router/) for example). This has already been reported to cause issues with `req.url`, for example [here](https://stackoverflow.com/questions/12525928/how-to-get-request-path-with-express-req-object). The suggested fix is reading out [`req.originalUrl`](https://expressjs.com/en/api.html#req.originalUrl) instead of `req.url`. This is also mentioned in the Express.js docs.

I've already narrowed down the problem to [this line](https://github.com/zeit/next.js/blob/5e3bf6e537124107034a35c49fceb27415214fec/packages/next-server/server/render.tsx#L139). This should probably mention req.originalUrl.

**Comment by timneutkens** [comment]
> I've already narrowed down the problem to this line. This should probably mention req.originalUrl.

We should not change the current value, `originalUrl` is not standardized, it's a side-effect of using express, which adds a bunch of values to `req`.

I guess you could do something like:

```
server.use('/post', (req, res, next) => {
  req.url = req.originalUrl
  return postRoutes(app)(req, res, next)
});
```
