### ISSUE TITLE
Dynamic Pages componentDidMount

### ISSUE THREAD

**Issue by hoaminhit** [zeit/next.js#5905]
I have a dynamic Page "category":
`static async getInitialProps(context) {
		const {slug} = context.query;
		let category = {};
		if (slug) {
			const response = await Axios.get(`${connection.backend}/categories/${slug}`);
			const result = await response.data;
			category = await result.data;
		}
		return {
			category: category
		};
	}
	componentDidMount() {
		console.log(555);
	}`
Navigate between another page, the func "componentDidMount" work, but navigate between category A to category B func "componentDidMount" not work. How to resolve this? Thanks You!

**Comment by timneutkens** [comment]
This is normal behavior in React, when a component is mounted it doesn't get remounted. Pages are components, so they're not remounted if the same page is rendered. Instead componentDidUpdate is triggered with different props.
