### ISSUE TITLE
[react-jss] Layout with nextjs

### ISSUE THREAD

**Issue by jonathangiamp** [zeit/next.js#5908]
__Expected behavior:__
With [nextjs](https://nextjs.org/), I want to be able to call header / footer components only one time at the top of my tree. Every component styles must be managed by react-jss.

__Describe the bug:__
Only the style of my main component is manage by react-jss. When document is client-side rendered, styles for Header/Footer are randomly rendered. When document is server-side rendered, styles aren't apply to Header/Footer components.

__Codesandbox link:__ 
Here a codesandbox to reproduce this issue: [CodeSandbox](https://codesandbox.io/s/l4k2v5lq8z).
Navigate with link to test client-side rendering. Access to page directly by typing url in the url bar to test server-side rendering.

__Versions:__
 - react-jss: 8.6.1
- jss-preset-default: 4.5.0
- [nextjs](https://nextjs.org/): 7.0.2
- Chrome: 71
- Node: 10.13.0
 - OS: macOS Mojave 10.14.1

**Comment by timneutkens** [comment]
Here's an example of react-jss: https://github.com/zeit/next.js/tree/canary/examples/with-react-jss

If this example doesn't work correctly feel free to send a pull-request. If it does this is an issue with react-jss and not Next.js, so it should be raised on their repository.
