### ISSUE TITLE
Improve "pages/ not found error"

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#591]
Right now upon a quick look it kinda looks like success:

![image](https://cloud.githubusercontent.com/assets/13041/21580204/086d18c6-cf99-11e6-835b-df76f86fa4a2.png)

No need to start compilation, the server, etc, if that directory doesn't exist.

**Comment by aranajhonny** [comment]
@rauchg with 'next build', the same should send an alert that the ' pages ' don't exist.
![captura de pantalla 2017-01-02 a las 0 55 27](https://cloud.githubusercontent.com/assets/9091881/21584868/872de3a6-d08a-11e6-9f4c-9b5fa358c076.png)

**Comment by rauchg** [comment]
Yep. Great observation @aranajhonny

**Comment by aranajhonny** [comment]
it would be something like this ?
![git](https://cloud.githubusercontent.com/assets/9091881/21586261/5711be5c-d0a5-11e6-8e69-3eb80e648cee.png)
