### ISSUE TITLE
HMR does not work when exporting undefined

### ISSUE THREAD

**Issue by kylemh** [zeit/next.js#5911]
# Bug report

## Describe the bug

As described by @timneutkens -> https://github.com/zeit/next.js/pull/5857#issuecomment-447870847

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

- Change [this line](https://github.com/kylemh/next.js/blob/canary/test/integration/basic/test/error-recovery.js#L253) to

```javascript
aboutPage.replace('export default', 'export default undefined;\nexport const fn =')
```

and run `yarn testonly --testPathPattern="basic" -t "should recover after a bad return from the render function"`

## Expected behavior
Edit to test should pass

**Comment by canotech** [comment]
I am the same Issue with version ^7.0.0
