### ISSUE TITLE
Without source code it shows 404 after build and start

### ISSUE THREAD

**Issue by xucongli1989** [zeit/next.js#5919]
## Example name
https://github.com/zeit/next.js/tree/canary/examples/custom-server-koa

## Describe the bug
404 error in`http://localhost:3000/`

## To Reproduce
- npm i
- npm run build  
- Delete `pages` folder ,because I only want compiled files,like `.next` folder.
- npm run start     (Note:`set NODE_ENV=production && node server.js`)

## Expected behavior
The page should be available.

## Screenshots

![20181219200150](https://user-images.githubusercontent.com/9961428/50219088-05ac5280-03c9-11e9-81ed-22783143848a.jpg)

## System information
 - Win 7 x64
- Node 8.12
- Npm 6.4.1

**Comment by timneutkens** [comment]
I'm assuming the reason is that it actually booted in dev mode because `NODE_ENV=production` was not set correctly or something 🤔

**Comment by xucongli1989** [comment]
Good!It should be this `set NODE_ENV=production&& node server.js`.Remove space after `production`.
