### ISSUE TITLE
getInitialProps that with dynamic import, ssr is ok, but has error in client side

### ISSUE THREAD

**Issue by minzojian** [zeit/next.js#5920]
# Bug report

## getInitialProps that with dynamic import, ssr is ok, but have errors in client side

**pages/index.js**

    import React from "react";
    import dynamic from "next/dynamic";
    class Index extends React.Component {
      static async getInitialProps() {
        return { Hello: dynamic(import("../components/hello")) };
      }
      constructor(props) {
        super(props);
        console.log("props:", props);
      }
      render() {
        const { Hello } = this.props;
        console.log(this.props);
        return (
          <div>
            <Hello />
          </div>
        );
      }
    }
    export default Index;`

**components/hello.js**

    export default class hello extends React.Component{
    render () 
    {
        return (<div>
          <p>Hello Next.js</p>
        </div>)
      }
    }

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. just start run the dev npm script
2. http://localhost:3000
3. looks fine, but you will get lots of error in the browser console

## Expected behavior
i log out the props in the render method on purpose, we can see the content in compiler console, but got nothing in client side console.

## Screenshots
![image](https://user-images.githubusercontent.com/361781/50218743-f082f400-03c7-11e9-9ecd-52c7ffbe2470.png)

## System information
 - OS:Windows10
 - Browser: chrome
 - Version of Next.js:7.0.2

## Additional context

if we don't use dynamic import but do some simple data api request in getInitialProps, we found that the data recorded inside props would keeped in both server and client side, hope the componens that dynamic import can also shared both server side and client side

**Comment by zvictor** [comment]
@minzojian I was checking again the reproducible I made for #5347 and I believe that the problem you are having is not necessarily caused by the fact you are using `getInitialProps` specifically, but by the fact that  your `dynamic(import("../components/hello"))` is written inside a function executed in runtime.

You can verify it on https://github.com/zvictor/nextjs-issue-5347/blob/c370da10f38752669c60c08eec08fcc2f21f9d5b/pages/index.js#L8 by replacing the initialisation of `Component` by any of the alternative declarations of it and comparing the results in the logs.

A workaround for you is this:
```js
...
const Hello = dynamic(import("../components/hello"))

class Index extends React.Component {
  static async getInitialProps() {
    return { Hello };
  }
...
```

**Comment by timneutkens** [comment]
You need to use `next/dynamic` the result of getInitialProps is serialized into JSON. https://github.com/zeit/next.js#dynamic-import

If you want to wait for the dynamic import on page changes you can do this:

```js
import dynamic from 'next/dynamic'
// `dynamic(` always should be used at the top level, never inside a component
const DynamicComponent = dynamic(() => import('../components/hello'))

export default class extends React.Component {
  static async getInitialProps() {
    await DynamicComponent.preload()
    return {}
  }
  render() {
    return <div>
      <DynamicComponent />
    </div>
  }
}
```

**Comment by zvictor** [comment]
@minzojian  I see your point and I believe that most cases using dynamic import would have the same needs you have. What I meant with the workaround I proposed was not really that it would solve the issue in a more complex case, like your application or mine, but more for the sake of assessing if the issue you are reporting is the same of #5347 or not.

I might be wrong, but if you were able to make the changes I proposed in your reproducible and it solved the problem there, then I would assume that your issue is not new but a duplication of #5347.

**Comment by timneutkens** [comment]
> well, since i absolutely need to do runtime components loading and rendering,

I really don't understand what you're trying to solve here, loading the file inside getInitialProps does not have any difference from adding the dynamic call on the top of the file. It seems like you're trying to do something different than the code that you're writing. If you create a next/dynamic component it will only be required/included on the client side when you use it.

**Comment by minzojian** [comment]
![image](https://user-images.githubusercontent.com/361781/50319028-085d9380-0500-11e9-986f-fa536ea34114.png)

this is what i try to archive, build a “page loader(renderer)" which can load page's structure data from other api, and then import necessary components into it, then render out.

i need to load the structure data runtime, cause there is only one page (as a loader) at all, but has different page structure data to be load.

looks i almost done, with load and import twice inside getInitialProps(for ssr) and constructor(for csr). but i can't avoid that flashing screen, when page content switch from ssr initial content to csr.  cause components need to load again in client-side.

**Comment by timneutkens** [comment]
So as I outlined before you can just use this way of doing things:

To give you an illustration of this:

```
import dynamic from 'next/dynamic'
// `dynamic(` always should be used at the top level, never inside a component
const DynamicComponent = dynamic(() => import('../components/hello'))

export default class extends React.Component {
  render() {
    return null
  }
}
```

As you can see `render()` returns `null` "nothing"

`DynamicComponent` will only be loaded when it is **rendered**, so if you'd have logic that is like:

```
import dynamic from 'next/dynamic'
// `dynamic(` always should be used at the top level, never inside a component
const DynamicComponent = dynamic(() => import('../components/hello'))

export default class extends React.Component {
  static async getInitialProps() {
    return {homepage: true}
  }
  render() {
    return <div>
	  {this.props.homepage ? <DynamicComponent /> : null}
    </div>
  }
}
```

**Comment by minzojian** [comment]
@timneutkens 
oh no, still see the loading state, no matter which way to import components

    import React from "react";
    import dynamic from "next/dynamic";

    const Test = dynamic(import("../components/pageComponents/TestComp"));
    const Test2 = dynamic(import("../components/pageComponents/TestComp2"));
    const Test3 = dynamic(import("../components/pageComponents/TestComp3"));

    class Index extends React.Component {
      static async getInitialProps() {
        await Test.preload();
        await Test2.preload();
        await Test3.preload();
        return {};
      }

      render() {
        return (
          <div>
            <Test />
            <Test2 />
            <Test3 />
          </div>
        );
      }
    }

    export default Index;

![test](https://user-images.githubusercontent.com/361781/50336389-0a981000-0549-11e9-8604-02dc130ce4e3.gif)

**Comment by MartinMouritzen** [comment]
I have the same problem. Did you ever figure out a solution?

**Comment by huykon** [comment]
please give a solution of preloading page?

**Comment by japesh** [comment]
Hi Team,

I have the same use case. The problem with the dynamic import is, we will have to define static path in "import".
~~~
import('../src/components/Dashboard')
~~~

if we don't define the static path in import it will not work. Is there any way to define a component similar to dynamic but it can be use like:

~~~
class DynamciSample extends React.Component{
  render() {
    return this.props.paths.map((path, index) => <Dynamic key={index} src={path} />);
  }
}
~~~

This Dynamic component will load the required chunks which will be defined in specific folder and render the component after load.

**Comment by japesh** [comment]
Hi Team,
I have gone through the code of NextJS and find out that dynamic import can be implemented for production mode with following approach. 

Just for example i have concidered that component name will be defined in query params as follows.
`
http://localhost:3000/?component=PostLink1,PostLink,Select
`
where PostLink1, PostLink, Select are individual components created in pages folder itself.

**Can any one provide reviews on same suggest the best appraoch and improvements.**

**server.js**

~~~
const express = require('express')
const next = require('next')
const { resolve, join } = require('path');

const dev = process.env.NODE_ENV !== 'production';
const dir = '.';
const distDir = '.next';
const absDistDir = join(resolve(dir),distDir);
const app = next({ dev, dir, distDir });
const handle = app.getRequestHandler()
module.exports={app};
app
  .prepare()
  .then(() => {
    const server = express()
    server.get('*', (req, res) => {
      req.distDir = absDistDir;
      return handle(req, res)
    })

    server.listen(3000, err => {
      if (err) throw err
      console.log('> Ready on http://localhost:3000')
    })
  })
  .catch(ex => {
    console.error(ex.stack)
    process.exit(1)
  })
~~~

**index.js**

~~~
import React from "react";
import Layout from "../components/MyLayout.js";
import dynamic from "next/dynamic";
import Router from "next/router";
import { requirePage } from "next-server/dist/server/require";
import { LoadableContext } from "next-server/dist/lib/loadable-context";

export default class Home extends React.Component {
  constructor(props) {
    super(props);
    let { Components, isServer, distDir } = props;
    let _Component;
    if (typeof window === "undefined" && isServer) {
      _Component = Components.map(component => {
        return requirePage(component, distDir).default;
      });
    } else if (typeof window !== "undefined" && isServer) {
      _Component = Components.map(component => {
        return dynamic(() => import(`./${component}.js`));
      });
    }
    this.Components = _Component;
  }

  static contextType = LoadableContext;
  componentWillMount() {
    const { Components, isServer } = this.props;
    if (this.context && typeof window === "undefined" && isServer) {
      Components.forEach(moduleName => {
        this.context(`./${moduleName}.js`);
      });
    }
  }
  render() {
    let { Components, isServer} = this.props;
    if (isServer) {
      Components = this.Components;
    }
    return (
      <Layout>

          {Components.map((Component, index) => {
            return (
                <Component  key={index}/>
            );
          })}
      </Layout>
    );
  }
}
Home.getInitialProps = async function({ query, req }) {
  const { component} = query;
  let Components = component.split(",");
  if (typeof window !== "undefined" && component) {
    Components = await Promise.all(
      Components.map(async component => {
        return await Router.router.fetchComponent(`/${component}`);
      })
    );
  }

  return {
    Components,
    isServer: typeof window === "undefined",
    distDir: req && req.distDir
    };
};

~~~

Other then this i am facing an **issue** in **dev mode**. As we are pages are build at the run time in dev enviornment. It gives error file not found if it's not called before. Can you **help me with the best approach** to **build the required pages** before calling the index page in dev mode.

Version Used:
next: 8.1.0
react: 16.8.6
