### ISSUE TITLE
nextjs+pm2:  [PM2][ERROR] script not found

### ISSUE THREAD

**Issue by amandakelake** [zeit/next.js#5921]
I'm using pm2 to start my application in production

here's my script 
```json
  "scripts": {
    "dev": "cross-env NODE_ENV=development PORT=3000 node server/server.js",
    "build": "next build",
    "start": "next start"
  },
```

here's my `ecosystem.config.js` file
```js
module.exports = {
  apps: [
    {
      name: "ssr",
      script: "next",
      instances: 1,
      autorestart: true,
      watch: true,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "development"
      },
      env_production: {
        NODE_ENV: "production"
      }
    }
  ]
};
```

when I run `pm2 start ecosystem.config.js` in server, I got an error
![image](https://user-images.githubusercontent.com/25027560/50220363-16f75e00-03cd-11e9-902b-c134f6050748.png)

need some help, thanks

**Comment by timneutkens** [comment]
Please follow the issue template, questions should be posted on https://spectrum.chat/next-js as the community is there. However I doubt this is an actual issue with Next.js, and more related to the configuration 🤔
