### ISSUE TITLE
Server side rendering support gRPC?

### ISSUE THREAD

**Issue by congaductq** [zeit/next.js#5925]
I'm doing implement gRPC in Next JS project and finished on client side rendering by using
gRPC Web (https://github.com/grpc/grpc-web)

But I'm stuck when implement it on server side rendering.

Is there any solution?

Thanks in advance!

**Comment by dbrrt** [comment]
Do you have an example/project to reproduce?

**Comment by timneutkens** [comment]
Please follow the issue template and post this question on spectrum.chat/next-js.
