### ISSUE TITLE
unsafe npm package event-stream@3.3.6 used

### ISSUE THREAD

**Issue by tirthaguha** [zeit/next.js#5926]
# Bug report
`event-source-polyfill@0.0.12` used in next, uses infamous `event-stream@3.3.6`.

## Describe the bug
There has been reported vulnerabilities on `event-stream@3.3.6`

# #https://github.com/dominictarr/event-stream/issues/116

## System information
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
Just verified event-stream is **not installed** using:

```
yarn create next-app my-app
cd my-app
yarn why event-stream
```

```
yarn why event-stream
yarn why v1.12.1
warning package.json: No license field
[1/4] 🤔  Why do we have the module "event-stream"...?
[2/4] 🚚  Initialising dependency graph...
warning create-next-example-app: No license field
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.57s.
```

**Comment by tirthaguha** [comment]
Closing this. it was a false alarm. Apologies. I had it in my node_modules through another package `npm-run-all`

**Comment by timneutkens** [comment]
No worries, glad to see I didn't miss anything.
