### ISSUE TITLE
Next.js repeated loading the same js file, but the js file included the head tag.

### ISSUE THREAD

**Issue by LYfirstday** [zeit/next.js#5931]
# Question about Next.js

 I use next/link and nprogress, sometimes if I don`t operation the page a period of time. then I click the router-link, the page repeated loading the same js file, but this js file included the head tag. my page loading all the time. unless I refresh my page.

![image](https://user-images.githubusercontent.com/25970534/50335355-f999cf80-0545-11e9-8c7e-628170cfdae8.png)

**Comment by timneutkens** [comment]
Please follow the issue template and provide a full minimal reproduction. It's really hard to help based on a screenshot from your particular application.
