### ISSUE TITLE
See https://github.com/styled-components/styled-components/blob/master/src/utils/errors.md#1 for more information. Additional arguments: undefined

### ISSUE THREAD

**Issue by Rahulkishanm** [zeit/next.js#5932]
# Internal server error without file name or line number

**I use Styled component in next js app**
**I get an internal server error**
**See https://github.com/styled-components/styled-components/blob/master/src/utils/errors.md#1 for more information. Additional arguments: undefined**
It would be very helpful if the line number in which error occurs is shown.

## To Reproduce
When I run nextjs app using npm run dev mode is working fine.
BUT When I do 
1) npm run build 
2) npm start
When i hit local server i get the below **error** 

**ERROR:**
> Ready on http://localhost:3000
> Error: An error occurred. See https://github.com/styled-components/styled-components/blob/master/src/utils/errors.md#1 for more information. Additional arguments: undefined
>     at new StyledComponentsError (/Users/rahulkishan/Documents/React_Mobile_and_web/ReactWebV1/purchaseweb/node_modules/styled-components/dist/styled-components.cjs.js:161:58)
>     at constructWithOptions (/Users/rahulkishan/Documents/React_Mobile_and_web/ReactWebV1/purchaseweb/node_modules/styled-components/dist/styled-components.cjs.js:2182:13)

What really happens when build ?.
We made a large app. Difficult to find the line in which issue occurs.

## System information
 - OS: macOS 10.13.3
 - Browser Chrome
 - Version of Next.js: 7.0.0

## Additional context

It would be very helpful if the line number in which error occurs is shown. HELP, HELP
stackoverflow link: [stackoverflowLink](https://stackoverflow.com/questions/53884958/i-get-internal-server-error-while-running-next-js-app-with-styled-component)

**Comment by timneutkens** [comment]
I'm not sure how to help here as you're not providing a reproduction and you're using an external library (styled-components) that is throwing an error.

I'd be happy to have a look if you provide a reproduction.

When creating issues keep in mind that saying:

1. `npm run build`
2. `npm run start` 

Means that you're expecting the person that looks at your issue to do:

1. `npm run build`
which results in:

```
npm run build
npm ERR! path /Users/timneutkens/projects/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/timneutkens/projects/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/timneutkens/.npm/_logs/2018-12-21T13_35_53_857Z-debug.log
```

And then
2. `npm start`

Which results in:

```
npm ERR! path /Users/timneutkens/projects/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/timneutkens/projects/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/timneutkens/.npm/_logs/2018-12-21T13_36_39_005Z-debug.log
```

I'm just outlining this to make sure you understand that you're asking for help but it's very hard to help with just a stacktrace and 2 steps without any code to reproduce the issue, which is most likely an issue in your application and not in Next.js itself.

I'd be happy to help with a reproduction in place.

**Comment by pauldariye** [comment]
@Rahulkishanm this happens when you try to style a composed component. If you narrow down which component it is. Try doing what was recommended in this [comment](https://github.com/diegohaz/arc/issues/130#issuecomment-282408542)

like so
```
import styled from 'styled-components'
import ComposedComponent from '../components'

const MyStyledComposedComponent = styled(props => <ComposedComponent {...props>)`
	position: absolute;
	// Other styles
`
```

I hope this helps. And like @timneutkens mentioned, you gave very little information for others to be able to help you. I ran into this issue last night so I understood the issue a bit. Happy holidays!!!

**Comment by Rahulkishanm** [comment]
Thanks much, @pauldariye. I did not notice error log properly. It had its line number and its path, where in the styled component had undefined passed. Same issue [comment](https://github.com/diegohaz/arc/issues/130#issuecomment-282408542)
