### ISSUE TITLE
next6 with @zeit/next-less   Cannot destructure property `createHash` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by polo13999** [zeit/next.js#5933]
# Bug report

## Describe the bug

I use  next6 with  @zeit/next-less will show the error message 
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.

problem demo  repository:

https://github.com/polo13999/next6withantproblem

## Expected behavior
yarn dev   will show the error
 
## System information
 - OS: Mac
 - chrome, safari
 - Version of Next.js: 6.1.2

## Additional context

I try to use  @zeit/next-less 0.2 it still has problem

**Comment by timneutkens** [comment]
You'll have to use an older version of next-less or write your own if you're on Next.js 6.1.2. I'd highly recommend upgrading.
