### ISSUE TITLE
Web Performance Issue in Next upgrade

### ISSUE THREAD

**Issue by Ajeetlakhani** [zeit/next.js#5934]
# Question about Next.js
I have upgraded to next 7.0.2 and my site's  Start Render time increased from 2.9s to 9.8s in Slow 3G.
In this upgrade all js/css is getting loaded before browser start rendering.

Before upgrade
![screenshot 2018-12-22 at 12 07 43 pm](https://user-images.githubusercontent.com/8472589/50371589-ba21c080-05e3-11e9-8165-a721b08532d6.png)

After upgrade
![screenshot 2018-12-22 at 12 08 23 pm](https://user-images.githubusercontent.com/8472589/50371595-c9a10980-05e3-11e9-9103-8f7106d03191.png)

Start Render is an important factor in case of web performance.  Are there any hacks, workarounds or options to achieve it? How is this going to be handled  in next.js itself?

**Comment by timneutkens** [comment]
Can you provide a reproduction?

**Comment by timneutkens** [comment]
I'm going to close this as there was no reproduction provided.
