### ISSUE TITLE
Abort Event on Router

### ISSUE THREAD

**Issue by nkzawa** [zeit/next.js#594]
For now, an error is thrown with the `err.cancelled = true` when routing has been aborted, but I think Abort Event would be more standard on browser.

**Comment by arunoda** [comment]
I don't have any strong opinion on this.
But, for now, abort event for getInitialProps fired after it's completed. Not exactly after the abort command fired.

So in that case, catching that is meaning less.

**Comment by nkzawa** [comment]
My concern is the followings:

- abort is not exactly an error
- `onabort` is standard on browser (as far as I know)
- `err.cancelled` is something we invented.

**Comment by timneutkens** [comment]
As we haven't really had a need for this and there has been no community feedback I'm going to close this issue 👍
