### ISSUE TITLE
Extra character `/` added in path once app deployed

### ISSUE THREAD

**Issue by dbrrt** [zeit/next.js#5955]
# Bug report

## Describe the bug
When I'm deploying a nextjs app, I've got the character `/` appended at the end of the path, which is not appearing during development.

## To Reproduce

1) in pages folder, create a component (such as `home.js`)
2) In development, path will be `/home` if following structure `pages/home.js`
3) Once deployed (e.g. : `netlify`), path will be `/home/`

## System information
 - OS: macOS 10.13
 - Browser: chrome
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
Duplicate of #5214

**Comment by dbrrt** [comment]
Sounds great. Would be awesome to get such a feature.

**Comment by c0b41** [comment]
@dbrrt do you using Netlify [`Pretty Urls`](https://www.netlify.com/docs/redirects/#trailing-slash) ? maybe problem this

**Comment by dbrrt** [comment]
@c0b41 No, I'm not using any asset optimization. 
I think the solution is there : https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/router/router.js#L56

**Comment by martpie** [comment]
When using Caddy web server, you get the same problems. 

Nuxt.js solved it by providing an option for this: https://nuxtjs.org/api/configuration-generate#subfolders

**Comment by dbrrt** [comment]
Thanks !
