### ISSUE TITLE
SSR issues with styled-jsx and semver mismatch.

### ISSUE THREAD

**Issue by jamestalmage** [zeit/next.js#5958]
See: https://github.com/zeit/styled-jsx/issues/533

If there is a Semver mismatch between a project and `next.js` for `styled-jsx`, you end up with multiple copies of the StyleRegistry, and next-servers registry will be empty (meaning no styles get rendered server side).

The easiest option would be to declare `styled-jsx` as a peer dependency. Other more complicated options are discussed on the linked issue.

**Comment by timneutkens** [comment]
This is not really an issue with Next.js. Let's just discuss on styled-jsx.

**Comment by RoberMac** [comment]
Same issue, SSR with `styled-jsx` i will not works if I also install `styled-jsx` in project
