### ISSUE TITLE
Support /subpath/:parameter route

### ISSUE THREAD

**Issue by cctuan** [zeit/next.js#596]
Does next.js have a plan to support customized route like domain/path/:id and it will go to pages/path and use id as a query parameter?

I've made some rough changes in my forked repo
https://github.com/cctuan/next.js/commit/cb31cb00a38dab4dae0679f08cb25fb0a8c62e73
which support developer customize route in next.config.js

**Comment by nkzawa** [comment]
I believe you mean something like https://github.com/zeit/next.js/tree/master/examples/parameterized-routing.

We don't support built-in routings, but you can implement it with custom server API. 
See https://github.com/zeit/next.js/issues/291 for more details about this decision.

**Comment by cctuan** [comment]
thank you for your quick response

**Comment by bassbump** [comment]
I know you guys so far decided you won't support this out of the box, but this is such an obvious and "basic" feature I feel if you provide routing at all (which you do), this should be part of it and work automagically..

**Comment by arunoda** [comment]
@bassbump it's not like we don't support it. We do support it.
See: https://github.com/arunoda/coursebook-ui/blob/master/server.js#L40

**Comment by frol** [comment]
@bassbump there are quite a few extensions out there:

* https://github.com/BDav24/next-url-prettifier (the most recent; quite promising)
* https://github.com/fridays/next-routes (quite promising)
* https://github.com/matthewmueller/next-route
* https://github.com/zeit/next.js/pull/913
