### ISSUE TITLE
Deployment to appache

### ISSUE THREAD

**Issue by hecoderius** [zeit/next.js#5961]
Hello guys, I am beginner in Next JS I need to know how to deploy Next JS app on my server where I have Apache, should I get files there and run some command or something ?? Please help me ....

**Comment by timneutkens** [comment]
You'll have to run Node.js on the server and configure apache to proxypass to the Node.js server. It's similar to deploying on nginx: https://github.com/zeit/next.js/wiki/Deployment-on-Nginx's-reverse-proxy

You'll have to upload all files + node_modules then run `next build` and boot up the Node.js server. Please follow the issue template though and post your question on https://spectrum.chat/next-js, someone might have done this before.
