### ISSUE TITLE
Feature request: Add titleTemplate prop to Head

### ISSUE THREAD

**Issue by hugmanrique** [zeit/next.js#5964]
# Feature request

## Is your feature request related to a problem? Please describe.
There's currently no way to specify a `titleTemplate` string that standarizes the `<title>` tag shown in the browser by adding common prefixes or suffixes, e.g. `"Page - Site name"`.

## Describe the solution you'd like

Other document head management libraries such as [react-helmet](https://github.com/nfl/react-helmet) allow the programmer to pass a `titleTemplate` prop to any `<Head>` element used throughout the render tree that works as follows:

```js
<Head titleTemplate="%s | example.com">
  <title>My page</title>
</Head>
```

The title would now be `My page | example.com`. This allows users to declare the `titleTemplate` on their `_app.js` or layout files and then declare their page titles on each page.

## Describe alternatives you've considered
I've tried to hack into how the `Head` element gets rendered on the `_document.js` file, but I couldn't find any way to extract the logic without breaking page switching behavior.

**Comment by timneutkens** [comment]
I'm not sure why this would be needed, you could just do:

```jsx
function Title({title}) {
 return <Head>
   <title>{`${title} | example.com`}</title>
 </Head>
}
```

```
<Title title="Hello World">
```

Result would be `Hello World | example.com`

**Comment by hugmanrique** [comment]
Really nice solution! I hadn't thought about a simple solution and jumped straight off to a complex overengineered one 😅😛

**Comment by timneutkens** [comment]
😄💯

Yep sometimes it can be simple 😄
