### ISSUE TITLE
Feature Request: Option to use swc instead of babel

### ISSUE THREAD

**Issue by joshuaquek** [zeit/next.js#5965]
Question: Would it be possible in any way for NextJs to have the option of using swc instead of babel? (https://github.com/swc-project/swc)

Just wondering if it is possible. However, I can somewhat see the complexity involved in allowing for this option integrated into NextJs. 

It would be great though if this can be possible as an option, as swc runs at least 16 times faster than babel: https://github.com/swc-project/swc#performance

**Comment by timneutkens** [comment]
You'd need to implement a webpack loader and override next-babel-loader. It's unlikely that we'll switch Babel for swc at this point as it's not stable yet (just released, not all Babel features work, not enough documentation etc).
