### ISSUE TITLE
404 on Link

### ISSUE THREAD

**Issue by havenS** [zeit/next.js#598]
Hi,
Since beta 7 (beta 6 build didn't work at all for me) I have a message in chrome devtools saying:
```
Error: Failed to load JSON for /_next/pages/connexion
    at XMLHttpRequest.xhr.onload (router.js?23b135f:602)
```
while going navigating to `/connexion` works as expected. Any clue on which change could have break the old implementation and how is my code supposed to be changed ?
The result is the same using `'next/link'` or `'next/prefetch'`.

Thank you and happy new year to all of you.

**Comment by arunoda** [comment]
@havenS is there anyway we could have a sample app?

**Comment by havenS** [comment]
Here it is : 
https://github.com/havenS/sample-next-404

The `<Link />` to `/connexion` has a 404 while accessing `http://localhost/connexion` work as expected.

Thank you

**Comment by arunoda** [comment]
This is happening for pages in sub directories. I'm working on a fix.

**Comment by havenS** [comment]
This is what I figured out with the `/` Link working.

**Comment by nkzawa** [comment]
https://github.com/zeit/next.js/pull/595 should fix the issue.

**Comment by havenS** [comment]
Nice, I'll try it out as soon as it's been merged.

**Comment by arunoda** [comment]
@nkzawa I tried it seems like not working.
I'll check more.

**Comment by havenS** [comment]
@arunoda  #599 Resolves it for me

**Comment by havenS** [comment]
Thank you very much @arunoda and @nkzawa
