### ISSUE TITLE
The with-ant-design-less example does not support arrow functions

### ISSUE THREAD

**Issue by lanlan1128** [zeit/next.js#5985]
# Bug report

## Describe the bug
When I added a JS file containing the grammar of the arrow function to the pages folder of the with-ant-design-less example, the console and browser reported errors, as shown in the screenshot.

## Screenshots
![image](https://user-images.githubusercontent.com/13283444/50626415-0d432e00-0f69-11e9-91e7-31d55ac4e20d.png)

## System information
 - OS: [Windows]
 - Browser (if applies) [chrome,]
 - Version of Next.js: [e.g. 7.0.2]

**Comment by uedkx** [comment]
+1
