### ISSUE TITLE
`with-webassembly` fails with `wasm validation error: at offset 4: failed to match magic number`

### ISSUE THREAD

**Issue by indutny** [zeit/next.js#5995]
# Examples bug report

Getting:

```
wasm validation error: at offset 4: failed to match magic number
```

When running `with-webassembly` example.

## Example name

`with-webassembly`.

## Describe the bug

Web page displays `wasm validation error: at offset 4: failed to match magic number`, instead of running the actual web assembly. The wasm file delivered to browser consists of base64'd:

```
[object ArrayBuffer]
```

So I suppose there is some error along the path.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone example
3. `npm run dev`
4. Goto `http://localhost:3000/`
5. Observe error

## Expected behavior

I expected to see the result of WebAssembly execution, not error. :joy:

## Screenshots

Here you go:

<img width="587" alt="screen shot 2019-01-05 at 3 54 55 pm" src="https://user-images.githubusercontent.com/238531/50725728-4a8ef380-1102-11e9-958e-a85a2f90e625.png">

## System information
 - OS: macOS
 - Browser: Chrome
 - Version of Next.js: canary (`8.0.0-canary.2`)

## Additional context

I don't know what else to say. Perhaps I'll take a quick look at this myself too.

**Comment by indutny** [comment]
Oh, yeah. `.next/static/wasm/e19a968cddf73c54a7ae.wasm` contains: `[object ArrayBuffer]`.

**Comment by indutny** [comment]
Surprisingly, running `npm run build` results in proper contents of `.wasm` file, and everything works just fine.

**Comment by timneutkens** [comment]
I actually think this is a bug in webpack-dev-middleware 🤔 As we use their `writeToDisk` option 🤔 https://github.com/zeit/next.js/blob/canary/packages/next/server/hot-reloader.js#L365

**Comment by indutny** [comment]
https://github.com/webpack/webpack-dev-middleware/blob/master/lib/fs.js#L35 - `source` here is an `ArrayBuffer`, and it is not prepared to handle it. Looking further.

**Comment by indutny** [comment]
The culprit: https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L336-L338 . There is a discrepancy between webpack-dev-middleware and webpack. Sending a PR.

Thanks for the tip, @timneutkens !

**Comment by timneutkens** [comment]
🙌

**Comment by indutny** [comment]
https://github.com/webpack/webpack-dev-middleware/pull/356

**Comment by indutny** [comment]
Now I can finally work on my app again :joy: Nice framework, @rauchg and team!

**Comment by timneutkens** [comment]
🙏 Thanks!
