### ISSUE TITLE
App Extended Context Support

### ISSUE THREAD

**Issue by vzaidman** [zeit/next.js#6000]
# Feature request

## Is your feature request related to a problem? Please describe.
In short, I need context in my http service and i want to make it discreet to if it runs on the server or client.

For example i want to call "httpGet('/something')"
without providing `auth` to the function all the time.

Without nextjs, I'd go with the following initialization code:
```
import {setAuth} from './httpService';
import {getCookie} from './cookiesService';

const uid = getCookie('uid');
setAuth({uid});
```
that saves the auth somewhere in memory inside `httpService`.

Later i'd use it like this:

```
import {httpGet} from './httpService';

const response = await httpGet('/something');
```

But since the server side of nextjs is stateless,
the following code will be common to all the users in the system in this approach:
```
import {setAuth} from './httpService';
setAuth({uid});
```
so we need to initialize the service somehow.

For example in `_app.js`:
```
ctx.httpService = new HttpService({uid})
```
and later
```
const response = await ctx.httpService.httpGet('/something');
```
This would work on the server but only inside "getInitialProps".

I'd like to create a ctx that is discreet to being on the server or on the client and to pass it to the whole app
so any component would be able to get ctx from it's React Context:
```
class Something extends Component{
  componentDidMount() {
	this.props.ctx.httpService.httpPost('/something');
  }
  render() {
	//...
  }
}

export default withCtx(Something)
```

## Describe the solution you'd like
Is there a way to do it or is it a feature that needs to be added?

I thought of:
1. Passing `ctx` down to `_app`s "render" function as a property. (we need a smart serialization for this)
2. Adding a `CtxProvider` and `withCtx` to let the user pass the ctx in React Context.
3. `ctx` would need to be re-created on the client's init as well so what i propose is to add a
`extendCtx` static just like `getInitialProps` that would run both on server and client:
```
//_app.js
class MyApp extends App {

  //this should be called once on the server, once on the client's initialization, and on each local navigation.
  static async extendCtx(ctx) {
	const {req, res} = ctx;
	
	const uid = getCookie('uid', req); // get the cookie from the req if it exists or from document.cookie
	ctx.httpService = new HttpService({uid});
  }
  
  static async getInitialProps({Component, ctx, ctx: {req, res, store, query, pathname}}) {
    const something = ctx.httpService.httpGet('/something');
	return {something}
  }

  render() {
	const {ctx, something} = this.props
	
    return (
	  <CtxProvider ctx={ctx}>
	  	<InnerApp something={something}/>
	  </CtxProvider/>
	);
  }
}
```

**Comment by timneutkens** [comment]
We're not planning on allowing passing down the ctx to rendering, it's incredibly easy to misuse and generally not needed, eg you could return the values you need in getInitialProps and handle initializing `HttpService` in componentDidMount using setState or similar.
