### ISSUE TITLE
Unexpected identifier on next@canary

### ISSUE THREAD

**Issue by anthonyshort** [zeit/next.js#6004]
I'm upgrading a next app to use v8 canary for serverless target. I wasn't able to get next working on now before this. However, when I'm running my app locally I'm getting this error:

```
SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/anthonyshort/dev/github.com/bridge/app/dashboard/node_modules/next/router.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
/Users/anthonyshort/dev/github.com/bridge/app/dashboard/node_modules/next/dist/client/router.js:2
import _Router from 'next-server/dist/lib/router/router';
```

This error goes away when I revert back to v7. 

## To Reproduce

next.config.js looks roughly like this:

```
module.exports = {
  assetPrefix: isProd ? '/dashboard' : '',
  publicRuntimeConfig: config[process.env.NODE_ENV],
  target: 'serverless'
}
```

babelrc

```
{
  "presets": ["next/babel", "@babel/preset-flow"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    [
      "styled-components",
      {
        "ssr": true,
        "displayName": false
      }
    ],
    [
      "module-resolver",
      {
        "root": ["./"],
        "alias": {
          "@": "./"
        }
      }
    ]
  ],
  "env": {
    "test": {
      "presets": [
        [
          "next/babel",
          {
            "preset-env": {
              "modules": "commonjs"
            }
          }
        ],
        "@babel/preset-flow"
      ]
    }
  }
}
```

package.json

```
{
  "scripts": {
    "start": "next start",
    "dev": "next",
    "build": "next build",
  },
  "dependencies": {
    "@babel/runtime": "^7.1.5",
    "apollo-cache-inmemory": "^1.3.0-beta.6",
    "apollo-client": "^2.3.7",
    "apollo-link-context": "^1.0.7",
    "apollo-link-http": "^1.3.2",
    "array-move": "^1.0.0",
    "autosize": "^4.0.2",
    "autosize-input": "^1.0.0",
    "classnames": "^2.2.5",
    "clipboard-copy": "^1.2.0",
    "cookie": "^0.3.1",
    "currency-formatter": "^1.4.2",
    "dotenv": "^6.1.0",
    "fbemitter": "^2.1.1",
    "fecha": "^2.3.3",
    "formik": "^0.11.11",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.10.0",
    "hh-mm-ss": "^1.2.0",
    "isomorphic-fetch": "^2.2.1",
    "lodash": "^4.17.4",
    "moment": "^2.22.2",
    "ms": "^2.1.1",
    "next": "^8.0.0-canary.2",
    "next-nprogress": "^1.1.0",
    "rc-slider": "^8.6.1",
    "react": "^16.3.0",
    "react-adopt": "^0.6.0",
    "react-apollo": "^2.1.1",
    "react-click-outside-component": "^1.1.1",
    "react-desktop": "^0.3.3",
    "react-dom": "^16.3.0",
    "react-dropzone": "^4.0.1",
    "react-helmet": "^5.2.0",
    "react-keydown": "^1.9.6",
    "react-maskedinput": "^4.0.0",
    "react-modal": "^3.1.4",
    "react-powerplug": "^1.0.0-rc.1",
    "react-show": "^2.0.4",
    "react-sizeme": "^2.5.2",
    "react-sortable-hoc": "^0.8.3",
    "react-stripe-elements": "^1.4.1",
    "react-tether": "^0.6.1",
    "react-toggle-display": "^2.2.0",
    "react-transition-group": "^2.2.1",
    "round-to": "^3.0.0",
    "s-ago": "^1.2.2",
    "sentence-case": "^2.1.1",
    "simpleheat": "^0.4.0",
    "styled-components": "^2.2.1",
    "styled-jsx": "^3.1.2",
    "superagent": "^3.5.2",
    "unique-random-array": "^1.0.1",
    "yup": "^0.26.6"
  },
  "devDependencies": {
    "@babel/core": "^7.1.0",
    "@babel/plugin-proposal-decorators": "^7.1.0",
    "@babel/plugin-syntax-jsx": "^7.0.0",
    "@babel/plugin-transform-flow-strip-types": "^7.0.0",
    "@babel/plugin-transform-modules-commonjs": "^7.1.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^9.0.0",
    "babel-jest": "^23.6.0",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-styled-components": "^1.7.1",
    "eslint": "^4.18.2",
    "eslint-config-prettier": "^2.9.0",
    "eslint-config-standard": "^11.0.0",
    "eslint-plugin-flowtype": "^2.41.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jest": "^21.18.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-react": "^7.5.1",
    "eslint-plugin-standard": "^3.0.1",
    "flow-typed": "^2.5.1",
    "jest": "^23.6.0",
    "npm-run-all": "^4.1.3",
    "prettier": "^1.13.7",
    "prettier-eslint": "^8.8.0",
    "react-test-renderer": "^16.4.2",
    "react-testing-library": "^4.1.7"
  }
}
```

## System information
 - OS: macOS
 - Version of Next.js: next@8.0.0-canary.2

**Comment by timneutkens** [comment]
How do you run it locally? Just `npm run dev`? Are you using a custom server in development?

**Comment by anthonyshort** [comment]
`yarn dev` to run it locally. No custom server.

**Comment by timneutkens** [comment]
One hint of what might be the issue is that you're using `publicRuntimeConfig` which is not supported per the serverless target spec: https://github.com/zeit/next.js/pull/5927

I'll have a look in the morning.

**Comment by anthonyshort** [comment]
Gotcha! Thanks, I'll take a look at removing this and see how we go.

**Comment by anthonyshort** [comment]
Doesn't look like that's it. Still getting the same error.

**Comment by timneutkens** [comment]
Just tried to reproduce this issue based on the provided files and couldn't, probably because the issue is related to an imported dependency in a page 🤔 Could you provide a page so I can test it?

I basically did:

- Added package.json
- Added .babelrc
- Added next.config.js
- `yarn`
- Created `pages` directory
- Created `pages/index.js` holding `export default () => <div>test</div>
- `yarn dev` (equivalent of `npm run dev`)
- Errors showed up for `isProd` not being defined
- Changed `assetPrefix` in `next.config.js` to just hold `assetPrefix: ''`
- `yarn dev`
- Errors showed up for `config` not being defined
- Commented out `publicRuntimeConfig`
- `yarn dev`
- Opened `http://localhost:3000`
- `test` shows

**Comment by bryan** [comment]
Not sure my problem warrants another issue or spectrum chat, but I'm also running into an "Unexpected identifier" error on my [vanilla repo](https://github.com/bryan/kindling) - not sure if it may or may not be related to this issue. I've tried modeling it by following the with-jest example, but for some reason couldn't get it to work with my project.

```
Test suite failed to run

    /kindling/__tests__/index.test.js:12
    import React from "react";
           ^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
```

It looks like when the app is trying to shallow render my index page, it's erroring out?

**Comment by anthonyshort** [comment]
@timneutkens Thanks for checking that out in more detail. I might put together a small repo to see if I can reproduce it. I'm going to get ripping out things until it works so I can find the culprit. It might have something to do with server rendering, so I'll try and remove my custom _document, and I'll start ripping out components so I can find the culprit. 

If it ends up being some weird case that needs documenting, I'm happy to add a PR to the docs.

**Comment by timneutkens** [comment]
@bryan can you post on https://spectrum.chat/next-js, your issue seems to be a different one.

@anthonyshort that'd be great, thanks, I'd be happy to have a look a repository too if needed, it's definitely a weird case that I want to make sure we handle correctly 👍

**Comment by revskill10** [comment]
I got this issue and it's weird that, when i downgrade to next@8.0.0canary.0, the same problem happened also.

**Comment by timneutkens** [comment]
Please provide a reproduction @revskill10

**Comment by mulholio** [comment]
I've been running into the same issue. Here's the branch of my code that's causing it: https://github.com/mulholio/copy-that-front/tree/sw 

The issue occurred when upgrading to next canary and changing something in next.config.js

**Comment by mulholio** [comment]
Some further information that might be useful:

I continued to get this bug when I checked out my non-canary branch that I was previously working on. I fixed the bug on this branch by removing all `node_modules` and then running `yarn install`. However, returning to the [upgrade branch](https://github.com/mulholio/copy-that-front/tree/sw) caused the error to occur again.

**Comment by revskill10** [comment]
@timneutkens My reproduction is this [repo](https://github.com/Kms-Edu/next-app-config)
It's a npm package to package some production-ready NextJS application, so that i can just import it to reuse between my NextJS application.
If i upgrade that package for latest canary branches, whatever happens in my NextJS application, this issue happens.
The error message is unable to understand how to fix it.
@mulholio  I don't get you :D

**Comment by mulholio** [comment]
@revskill10 was wondering if the following would fix your issue (as in undo it, not allow you to upgrade properly):
1. `rm -rf node_modules`
2. `yarn install`

**Comment by anthonyshort** [comment]
FWIW I don't seem to be running into this issue after upgrading next and removing my node_modules

**Comment by timneutkens** [comment]
I guess that's a good thing 🤔 I still can't reproduce the issue. Maybe we can close this issue if it doesn't show up again.

Sidenote:
I noticed you have:

```
{
            "preset-env": {
              "modules": "commonjs"
            }
          }
```

Under the `test` env, in v7+ this is no longer needed as `next/babel` will detect `process.env.NODE_ENV === 'test'` and set that configuration accordingly 🙌

**Comment by anthonyshort** [comment]
Closing this as I haven't been able to reproduce it. Cleaning out node_modules and updating next seemed to fix the problem.

**Comment by timneutkens** [comment]
🙌 Let me know if you run into it again!

**Comment by amankakar** [comment]
i upgrade next from next@7.0.2 to next@8.0.0-canary-2 my npm run dev command is not working.

**Comment by timneutkens** [comment]
@anthonyshort I realized today that in Now's bootup error logging there is a missing sentence holding the `err.message`, I've created an internal issue / I'm having someone look into that and fix it, then if it happens again we'll know exactly what is breaking. 

Eg like in your first post it only shows `Unexpected identifier` instead of the whole message.

```
SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/anthonyshort/dev/github.com/bridge/app/dashboard/node_modules/next/router.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
/Users/anthonyshort/dev/github.com/bridge/app/dashboard/node_modules/next/dist/client/router.js:2
import _Router from 'next-server/dist/lib/router/router';
```

**Comment by paraboom** [comment]
I have the same issue. I think it happens because of the usage of `publicRuntimeConfig`.
I use the latest `"next": "^8.0.0-canary.17"`
Here is my configuration:

**next.config.js**
```
const {PHASE_PRODUCTION_SERVER} =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW_REGION
      ? require('next/constants')
      : require('next-server/constants');

module.exports = (phase, {defaultConfig}) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production.
    return {
      target: 'serverless'
    };
  }

  const withCSS = require('@zeit/next-css');

  return withCSS({
    target: 'serverless',
    publicRuntimeConfig: {
      apiURL: process.env.API_URL || '/'
    }
  });
};
```

And code that uses it:

```
import fetch from 'isomorphic-fetch'
import getConfig from 'next/config'
const {publicRuntimeConfig: {apiURL}} = getConfig()

export default async (url, method = 'GET', data = {}) => {
  let res
  if (method === 'POST' || method === 'PATCH') {
    res = await fetch(`${apiURL}${url}`, {
      method,
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    })
  } else {
    res = await fetch(`${apiURL}${url}`)
  }
  return res.json()
}
```

If I remove these lines
```
import getConfig from 'next/config'
const {publicRuntimeConfig: {apiURL}} = getConfig()
```
Everything working fine and deployment successfully finishes.

Otherwise I have following error:
```
module initialization error: TypeError
    at Module.2MX7 (/var/task/page.js:1:40963)
    at __webpack_require__ (/var/task/page.js:1:339)
    at module.exports.+EWW.module.exports.enumerable (/var/task/page.js:1:1757)
    at Object.<anonymous> (/var/task/page.js:1:1807)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

**Comment by hutber** [comment]
just to pour some more oil on the fire, I'm getting:

```/var/www/goldendemon.hutber.com/src/client/pages/admin/index.js:26
import React from "react";
       ^^^^^

SyntaxError: Unexpected identifier
``

There is firmly no `import` inside this file.

It has only popped up, if I remove the file, let it compile then add back in the contents of the file it will compile without fail. Only when i make a server file change does it do a `hard` reload and shows the error.

I'll try to figure out why though.

**Comment by hutber** [comment]
That was lucky. So my issue was as follows:
I copy pasted some code from `src/client/pages/admin/index.js` file into another file. 
Phpstorm then did a automatic import of `fetch` from `admin/index.js` as follows:

`import fetch from '../../client/pages/admin'`

Fetch is never exported from `admin/index.js` so the error is rather cryptic as its saying `React` isn't there, but actually its just some weirdas general error. Hope this helps :/
