### ISSUE TITLE
Using jquery plugin in Next.js

### ISSUE THREAD

**Issue by lanlan1128** [zeit/next.js#6005]
# Question about Next.js
When I try to load the jquery plugin width the following code to pages/myFullcalendar.js

`import React, { Component } from 'react';
import './App.css';

import $ from 'jquery';
import 'moment/min/moment.min.js';

import 'fullcalendar/dist/fullcalendar.css';
import 'fullcalendar/dist/fullcalendar.print.min.css';
import 'fullcalendar/dist/fullcalendar.js';` 

I got this trouble
![image](https://user-images.githubusercontent.com/13283444/50748331-e8ee9680-1273-11e9-954f-b283837fcd4c.png)

But In reacte-react-app project,It doesn't exists.
Can you offer me a solution?

Questions should be posted on https://spectrum.chat/next-js

**Comment by timneutkens** [comment]
> Questions should be posted on spectrum.chat/next-js

As per the issue template.

**Comment by stoplion** [comment]
Have same question, no one answered the spectrum chat
