### ISSUE TITLE
Scoped package used as external package throws "Uncaught SyntaxError: Invalid or unexpected token"

### ISSUE THREAD

**Issue by astenmies** [zeit/next.js#6006]
# Bug report

## Describe the bug

When a [scoped package](https://docs.npmjs.com/misc/scope) is set as external in next.config.js, an error is thrown.

Chrome:
> Uncaught SyntaxError: Invalid or unexpected token

Firefox:
> SyntaxError: illegal character

When checking in the build what's wrong, we can see that the `@` character is considered as invalid.

```js
/***/ "@myscope/mypackage":
/*!*************************************!*\
  !*** external "@myscope/mypackage" ***!
  \*************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = @myscope/mypackage;

/***/ }),
```

**next.config.js**
```js
config.externals.push(/^(@myscope).+/i);
```

## To Reproduce

1. Go to [https://github.com/astenmies/next-scope-starter](https://github.com/astenmies/next-scope-starter)
2. Clone the repo and run
```
git clone git@github.com:astenmies/next-scope-starter.git && cd next-scope-starter && make init
```
3. See error in the console

## System information
 - OS: macOS
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
Sounds like you're updating externals incorrectly, generally you have to return the request. This is not really a Next.js issue. I guess you could use this community plugin: https://github.com/martpie/next-plugin-transpile-modules
