### ISSUE TITLE
Page load issue

### ISSUE THREAD

**Issue by crushy26** [zeit/next.js#6010]
# Bug report

## Describe the bug

I have converted an html5 template to Nextjs project, seems like some elements of page are broken on initial load, but when I navigate to another page via Link and comeback again ( back and forth ), the elements loads just fine.  

Please check the screen recording via below link.

## Screen Recording
https://files.fm/f/usagtq75

## System information
 - OS: macOS
 - Browser: Chrome
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
Looks like a styling/mounting issue.
