### ISSUE TITLE
404 page displaying after adding custom route in server.js file.

### ISSUE THREAD

**Issue by PiyankaYadav** [zeit/next.js#6015]
# Bug report

404 page displaying after adding custom route in server.js file

I am adding custom route to my server.js file . After that if we restart our app and visit following page:
http://localhost:3000/p/hello-next-js 

then we should see the actual page not the 404 page but i am still seeing 404 page.
this is my server.js file->
``
const express = require('express')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare()
.then(() => {
  const server = express()

  server.get('/p/:id', (req, res) => {
    const actualPage = '/post'
    const queryParams = { title: req.params.id } 
    app.render(req, res, actualPage, queryParams)
  })

  server.get('*', (req, res) => {
    return handle(req, res)
  })

  server.listen(3000, (err) => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000')
  })
})
.catch((ex) => {
  console.error(ex.stack)
  process.exit(1)
})

and this is the package.json file->

  "name": "hello-next",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.4",
    "next": "^6.1.1",
    "react": "^16.4.2",
    "react-dom": "^16.4.2"
  }
}

## System information
 - OS: Linux
 - Browser chrome 
- Version of Next.js:  6.0.2

**Comment by timneutkens** [comment]
I doubt this is a bug in Next.js. Maybe you don't have `pages/post.js`?
