### ISSUE TITLE
example with AWS Lambda

### ISSUE THREAD

**Issue by mattdamon108** [zeit/next.js#6022]
- Url: https://github.com/mattdamon108/nextjs-with-lambda

Actually, this is not a bug report, I can't find other ways to share the new example here. This is an example about how to deploy Next.js app to AWS Lambda using the Apex up. It seems there is not any AWS Lambda example yet, so I hope this could be a tip for later researchers.

**Comment by romainquellec** [comment]
There are a lot of improvements with v8.0.0-canary.X (check the canary version).
Maybe check and try to make it work with up or serverless ? Thanks.

**Comment by timneutkens** [comment]
Feel free to add it to https://github.com/unicodeveloper/awesome-nextjs
