### ISSUE TITLE
Can I contribute a blog example?

### ISSUE THREAD

**Issue by jakelumetta** [zeit/next.js#6023]
# Feature request
Hi! I'd like to contribute a headless cms blog example to the Next.js docs. It would use ButterCMS API free developer account for the blog content.

Would the best place for this be https://nextjs.org/docs/#recipes or somewhere else in the docs? 

Let me know your thoughts! Thanks

**Comment by timneutkens** [comment]
Sure! Feel free to send a PR.

**Comment by jakelumetta** [comment]
Great will do.  Is https://nextjs.org/docs/#recipes as a link the best place or can I contribute a full guide  that lives in the https://nextjs.org/docs/  somewhere ?

**Comment by timneutkens** [comment]
I think the best way currently is adding it to https://github.com/unicodeveloper/awesome-nextjs

**Comment by jakelumetta** [comment]
Ok thanks!
