### ISSUE TITLE
Deploying local server for integration tests

### ISSUE THREAD

**Issue by DvirSh** [zeit/next.js#603]
Hi :)
Small question - I saw some tests with jest and enzyme for the react components, but what about server tests?
For example, looking at parameterized server example, assuming you are implementing some logic to retrieve blogs from somewhere, and you want to test the entire scope - you want to perform a GET /blog/:id request and see that you got the right react component rendered with the right properties.

What is the suggested way to do that? Is there an example / change to add one?

**Comment by timneutkens** [comment]
@arunoda added a new testing setup here: https://github.com/zeit/next.js/pull/640. Can you take a look there? There's some really good concepts there 😄 Feel free to re-open if this doesn't solve your question 👍

**Comment by arunoda** [comment]
And after 2.0, we'd like to ship a package called `test-next` (or a similar name) which allows you to test your app using the same tools we used for Next.

**Comment by KingScooty** [comment]
@arunoda What's the status on this? Having a hard time finding documentation regarding writing http tests for my next app.
