### ISSUE TITLE
[with-apollo] Reduce boilerplate

### ISSUE THREAD

**Issue by lucasconstantino** [zeit/next.js#6035]
Hi there.

I believe the current example for Apollo usage has an unnecessary boilerplate size. For instance, there is no need to make `_app.js` render method aware of Apollo - we can solve everything in the connector (`with-apollo-client`).

Are you guys open to pull-requests? I can either work on a pull-request with refactoring suggestions, or on an alternative example.

**Comment by timneutkens** [comment]
Sounds fine to me

**Comment by williamboman** [comment]
I think the current design is better. The `withApolloClient` container is not only meant to be used in `_app`, but can be used elsewhere if one needs to access the apollo client object. Your proposal would mean creating a container `withApolloProvider`, which would only have one valid use case (to enhance the `_app` component). All this to remove 2 lines of JSX? I also think it's easier to get an overview of the component tree if components are explicitly rendered, and not hidden in HOCs. Just my ¢2

**Comment by revskill10** [comment]
In case you need two or more apollo clients in the same application, then yes, but it should be another example. Current design is enough if your application needs only 1 apollo-client.

**Comment by timneutkens** [comment]
Feel free to open a PR to improve and we'll review it 👍
