### ISSUE TITLE
Navigating to non-existing route on client-side causes unknown error

### ISSUE THREAD

**Issue by williamboman** [zeit/next.js#6036]
# Bug report

## Describe the bug

When loading a non-existing route with SSR we get expected behaviour - `res.statusCode === 404` in `getInitialProps`. However, when navigating to a non-existing route on the client-side (for example loading a 404 route with SSR, navigate to an existing route, let's say `/`, then hitting the browser back button) the error document will be rendered, but in `getInitialProps` there are no accompanying `err` value. I feel like `gIP` should be called with an error object telling the route does not exist?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Use any existing Next.js app that has a custom error page that has any `<Link />` to an existing route.
2. Load an invalid route with SSR.
3. Click the `<Link />` to an existing route
4. Hit the browser back button
5. The error page has been rendered with no error data in `gIP`

## Expected behavior
An error object should've been passed to `gIP`, telling that the route does not exist.

## System information
 - Version of Next.js: 7.0.2

**Comment by ijjk** [comment]
We actually have a test for this and it's working on the latest version of Next.js using the below `_error` page. I'm going to close this issue since it doesn't appear to be a problem anymore. Feel free to comment if you are still having trouble with this. 

```jsx
import Link from 'next/link'
import NextError from 'next/error'
import React from 'react'

export default class Error extends React.Component {
  static getInitialProps (ctx) {
    const { statusCode } = NextError.getInitialProps(ctx)
    return { statusCode: statusCode || null }
  }

  render () {
    return (
      <div>
        <div id='errorStatusCode'>{this.props.statusCode || 'unknown'}</div>
        <p>
          <Link href='/'>
            <a id='errorGoHome'>go home</a>
          </Link>
        </p>
      </div>
    )
  }
}
```
