### ISSUE TITLE
Challenge compressing nextjs app

### ISSUE THREAD

**Issue by Siddharth2212** [zeit/next.js#6043]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

Here is the nextjs app I have developed http://nextfast.herokuapp.com/ . I have already enabled gzip compression and checked that it is enabled. But google lighthouse says I can save 4.95 seconds on mobile by enabling gzip compression. For example it says I can save  636 kbs by compressing this file 
 http://nextfast.herokuapp.com/_next/static/chunks/commons.f04c22c%E2%80%A6.js( 841kbs). I am a novice in reactjs and no experience in details webpack and its configuration if this is related to webpack. Please guide me what can I do here. Thanks!
  
-- | --

**Comment by timneutkens** [comment]
It looks like gzip is only enabled for the root url, everything else is not gzipped. This is an issue with Heroku and not Next.js, it's generally better to handle gzip on the fly.

**Comment by siddharthsogani** [comment]
I have implemented compression middleware to the express app. What else do I need to do?
