### ISSUE TITLE
want help about readme.md

### ISSUE THREAD

**Issue by junjie-lean** [zeit/next.js#6048]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

hello , i just interested in readme.md, how to generate hyperlinks like this:
![pic](https://user-images.githubusercontent.com/40194410/51094021-32933000-17e4-11e9-84db-7685c5adbe49.png)

Thanks~   ：）

**Comment by timneutkens** [comment]
They're provided by https://shields.io/#/

**Comment by junjie-lean** [comment]
oh, it's wonderful, thx.
