### ISSUE TITLE
 Compiled scripts become bigger without reason

### ISSUE THREAD

**Issue by nokisnojok** [zeit/next.js#6054]
# Bug report

## Describe the bug

add a page file, after next build, the file commons[hash].js is to big.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. add a file /pages/index.js 

> ```js-jsx
>import withStyles from '@material-ui/core/styles/withStyles'; 
>console.log({
>    withStyles
>});
>export default () => <div>index</div>;`

2. next build, then the /.next/static/chunks/commons[hash].js is 174kb;
3. add a file /pages/other.js
> ```js-jsx
>import withStyles from '@material-ui/core/styles/withStyles'; 
>console.log({
>    withStyles
>});
>export default () => <div>other</div>;`

4. next build, then the /.next/static/chunks/commons[hash].js is 248kb;

## Expected behavior
after next build, the /.next/static/chunks/commons[hash].js should be 174kb not 248kb;

## System information
 - OS: [Windows]
 - Browser (if applies) [not about browser]
 - Version of Next.js: [e.g. 7.0.2]

**Comment by timneutkens** [comment]
This is expected behavior. If a dep is used in 50% of all pages it'll be considered a common module and included in the commons bundle.
