### ISSUE TITLE
Issue when using Spread Operator in JSX

### ISSUE THREAD

**Issue by samholmes** [zeit/next.js#6057]
# Bug report

## Describe the bug

This is an error I get when trying to use the spread operator on properties from within JSX.

```
Uncaught (in promise) Error: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
TypeError: Cannot read property '0' of null
```

## To Reproduce

Return the following from a component:

```
return (<div {...{id: 'foo'}}>test</div>)
```

## Expected behavior
Div get's the property `id='foo'`.

## System information
 - OS: macOS
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
Works fine based on the reproduction:

```
yarn create next-app abcdef
```


updates `pages/index.js` to:

```
export default () => <div {...{id: 'foo'}}>test</div>
```
