### ISSUE TITLE
issue with micro instances in with-cookie-auth example

### ISSUE THREAD

**Issue by coetry** [zeit/next.js#6058]
## Example name
`with-cookie-auth`

## Describe the bug
The package.json in the `api` directory specifies `index.js` as the main entry point, but no such file exists in that directory, which is why when I run `npm run dev` (inside the api directory) I get the following error in my terminal: 

Error: The file or directory "index.js" doesn't exist!

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to `api` folder
2. install dependencies: `npm i`
3. start dev script: `npm run dev`

## Expected behavior

I was hoping that both endpoints would be up and running so i can hit them from the client. I'm assuming I have to just run them in two separate processes and adjust the client code for the ports accordingly? 

## System information
 - OS: macOS

**Comment by coetry** [comment]
<img width="1280" alt="screen shot 2019-01-14 at 5 18 27 pm" src="https://user-images.githubusercontent.com/10926503/51147627-95a2b800-1820-11e9-8fec-f7313bc06de5.png">

<img width="1280" alt="screen shot 2019-01-14 at 5 19 10 pm" src="https://user-images.githubusercontent.com/10926503/51147630-989da880-1820-11e9-9ced-da3d83ba1483.png">

**Comment by j0lv3r4** [comment]
Hey @coetry!

The example is structured as a monorepo and only works on Now v2.

I'm working on a pull request to make `npm run dev` run everything locally too.

**Comment by coetry** [comment]
oh gotcha, thank you! I deployed it and it works fine on v2
