### ISSUE TITLE
Document how to support ancient browsers

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#606]
It'd be nice to document how to add webpack / babel transformations that make it possible to support browsers back to IE6/7. In addition to being clear in the README about what browsers _are supported out of the box_

cc @basvdheijden @matthewmueller

**Comment by haohcraft** [comment]
Looks like these two examples together would demonstrate how it supports ancient browsers.

https://github.com/zeit/next.js/tree/master/examples/with-polyfills
https://github.com/zeit/next.js/tree/master/examples/with-configured-preset-env

**Comment by timneutkens** [comment]
@haohcraft thank 🙏
