### ISSUE TITLE
where is the code make next.js serve the async script?

### ISSUE THREAD

**Issue by hopperhuang** [zeit/next.js#6064]
# Question about the next-server

Hi, guys, recently, I am reading to source code of next. I am curious about that where the next/server serve the async scripts. 

You can see that when you build your project, you will get the production with async script attached at the end of the document like this: '/_next/2327f35a-8a2a-42ae-a92a-6b56f117fb2c/page/_error.js', with a unique buildId

But when i read the source code, i cant found the code do the job serve for the async scripts. In the next-server/server/next-server.ts i only found the serveStatic method. But it seems that this method only serve for the _next/static or /static file not the _next/${buildId} one.

Can someone indicate that where is the code make the next-server serve the async scripts.

I am curious about this. Thank you!

**Comment by timneutkens** [comment]
Only `.next/static` is served under `/_next/static`. The directory structure is like: `/_next/static/<buildid>/pages/index.js`
