### ISSUE TITLE
Dynamic import loadableGenerated.webpack error when using next export

### ISSUE THREAD

**Issue by bitriddler** [zeit/next.js#6065]
Getting this error when using `next export` with dynamic imports

![image](https://user-images.githubusercontent.com/2437315/51200367-93605c80-18f9-11e9-8f52-3366c212a93a.png)

I was able to reproduce this bug on the `with-dynamic-import` example in this branch bitriddler/next.js#1

Copy/Paste in terminal and open localhost:8080 to reproduce
```
git clone https://github.com/bitriddler/next.js
cd next.js/examples/with-dynamic-import
git checkout bug-reporting
yarn install
yarn build
yarn export
cd out
serve -p 8080
```

What's even more strange if you uncommented this dynamic import, the error will disapper
https://github.com/bitriddler/next.js/pull/1/files#diff-58b5f665c8c999328f7413dcae71aaddR9

**Comment by ijjk** [comment]
I just pulled down the code and tried out the reproduction steps and it doesn't appear to be causing any issues. I'm closing this seems it doesn't appear to be a problem anymore. Feel free to comment if you're still experiencing an issue.
