### ISSUE TITLE
False warning "invalid DOM property class" for preact

### ISSUE THREAD

**Issue by alexeypetrushin** [zeit/next.js#6066]
# Bug report

When next.js used with preact it show false warning "Warning: Invalid DOM property `class`. Did you mean `className`?"

## Describe the bug

read above

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Follow next.js documentation to use it with preact
2. Add any element with the class attibute `<p class="anything">`
3. Open and see that page rendered properly in the Browser
4. Check console and you'll see the false warning there

## Expected behavior
No warning

## System information
 - Version of Next.js: 7.0.2

**Comment by pollen5** [comment]
That doesn't look like a bug to me, `class` is a reserved keyword in JavaScript, therefore its `className` in jsx.

**Comment by timneutkens** [comment]
I guess it's not allowed to use `class` through preact-compat 🤔
