### ISSUE TITLE
Adding Typescript loader in next.config.js

### ISSUE THREAD

**Issue by jagreehal** [zeit/next.js#607]
With #222 merged any ideas how to add a loader for TypeScript in next.config.js?

I've tried adding a TypeScript specific loader like this 

```
const path = require('path');
const nextPagesDir = path.join(__dirname, 'pages');

const typescriptLoader = {
  test: /\.ts(x?)$/,
  loader: ['ts-loader'],
  exclude: /node_modules/,
  include: [
    nextPagesDir
  ]
};

module.exports = {
  webpack: (config) => {
    config.module.rules.push(typescriptLoader);
    return config;
  }
}
```

but assume additional changes need to be made as well as additional entries for hot loading etc.

Another question is should the TypeScript loader be used in with babel e.g.

`loaders: ['babel-loader', 'ts-loader']`

If so I'd need to apply the same babel options as in webpack.js.

**Comment by rauchg** [comment]
This would be a _terrific_ example to add! `./examples/with-typescript`

**Comment by giacomorebonato** [comment]
I think that now the problem is that Next is looking only for files with .js extension in the pages folder, but with TypeScript we have .tsx

**Comment by timneutkens** [comment]
Duplicate of #96. Closing in favor of that one.
Regarding the extensions (.ts/.tsx). There is a comment about adding custom extensions here: https://github.com/zeit/next.js/issues/544 (at the bottom)

**Comment by nelak** [comment]
I was able to get this working in https://github.com/zeit/next.js/pull/2250 if anyone wants to take a look a it
