### ISSUE TITLE
Child Component of <Head> doesn't update on Link trigger

### ISSUE THREAD

**Issue by chixor** [zeit/next.js#6074]
# Bug report

## Describe the bug

When I add a basic tag like `<title>{title}</title>` as a child to `next/head` it receives a `class="next-head"` prop and updates when I click on a `next/link`.

However when I add a component (called `BreadcrumbsSchema`) as a child to `next/head` it doesn't update on activating `next/link`. When I pass the `className` prop to its child (in this case, a `<script/>`) then the component doesn't render at all.

What is the advised way to add a child component to a `next/head` so that it gets updated as users navigate the site?

Sample code:

```
import NextHead from 'next/head';

const BreadcrumbsSchema = (props) => {
    const schema = {
      '@context': 'http://schema.org',
      '@type': 'BreadcrumbList',
      'class': props.className,
      'itemListElement': props.breadcrumbs.map((item, x) => { return {
         "@type": "ListItem",
         "position": x+1,
         "name": item.name,
         "item": item.url
      }})
    };
    return <script className={props.className} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}/>;
};

class Head extends React.Component<HeadProps> {
    render() {
        const props = this.props;

        return (
            <div>
                <NextHead>
                    <BreadcrumbsSchema breadcrumbs={props.breadcrumbs} />
                </NextHead>
            </div>
        );
    }
}
```

## Expected behavior
`BreadcrumbsSchema` gets rendered in the `<head>` and updates when navigating using `next/link`.

## Actual behaviour
`BreadcrumbsSchema` doesn't render at all. If I remove `className={props.className}` from the `<script>` tag then it'll render but not update.

**Comment by chixor** [comment]
This worked, thanks!

**Comment by timneutkens** [comment]
Happy to help!
