### ISSUE TITLE
Lowercase hashes

### ISSUE THREAD

**Issue by schoenwaldnils** [zeit/next.js#6077]
# Feature request
To support AWS static hosting in S3 the hashes for *.js and *.css files need to be lowercase.

## Is your feature request related to a problem? Please describe.
sometimes when the hashes include uppercase letters I get 404 as a response.

## Describe the solution you'd like
Either the hashes are lowercase by default, or there would be an option to configure this

## Additional context
- next@7.0.2

**Comment by timneutkens** [comment]
Could you provide a clearer description? Do you mean the `buildId` has uppercase characters? Do webpack hashes do? 🤔

**Comment by schoenwaldnils** [comment]
Yes, it seems to be the buildId
```
/_next/static/dyiRiQHHOk_t6RXne_yDs/pages/page.js net::ERR_ABORTED 404
```

We use a lambda function to lowercase the request url. So that the user can open either `.com/testurl` or `.com/TestUrl` and land on the same resource `.com/testurl`

But `/_next/static/dyiriqhhok_t6rxne_yds/pages/page.js` doesn't exist in the S3 bucket :P

**Comment by timneutkens** [comment]
Are you using `generateBuildId`?

**Comment by schoenwaldnils** [comment]
Thanks, that helped. I do now 👍
