### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Luktm** [zeit/next.js#6080]
## Window is not defined every time I was trying npm install reactjs modules
window is not defined after install react-chat-widget or any others reactjs modules

## Error of  Window is not defined when import react modules
when i import the module as picture below:

1) import module 
![import-widget](https://user-images.githubusercontent.com/24861458/51331277-58eeef00-1ab4-11e9-9fda-1fc74b4e4381.PNG)

2) use module into render function
![insert-render](https://user-images.githubusercontent.com/24861458/51331288-5ee4d000-1ab4-11e9-92d1-17a07e276f94.PNG)

3) next.config.js with zeit/next-css npm package
![capture](https://user-images.githubusercontent.com/24861458/51331356-850a7000-1ab4-11e9-984c-90b401e97052.PNG)

4) package.json
![package-json](https://user-images.githubusercontent.com/24861458/51330339-4a9fd380-1ab2-11e9-892c-b981bc89ff49.PNG)

## Step to get error
Steps to produce the error after install react modules:
1. Open cmd as administration
2. run "yarn run dev"
3. localhost:3000 started
4. open chrome browser, refresh
5. Unhandled Rejection (ReferenceError): window is not defined

## Expected behavior
I expect react-chat-widget it can do like this as picture below after installed module:
![react-chat-widget-snap](https://user-images.githubusercontent.com/24861458/51330541-b6823c00-1ab2-11e9-87a7-403ba2c641ac.PNG)

## Screenshots of Error shows in browser after run it
![capture](https://user-images.githubusercontent.com/24861458/51330597-cbf76600-1ab2-11e9-8e70-1143c1a7cf61.PNG)

## System information
 - OS: Windows
 - chrome
 - Version of Next.js: [e.g. 7.0.2]

**Comment by timneutkens** [comment]
Sounds like you'll want to use the `ssr: false` option for `next/dynamic`: https://github.com/zeit/next.js#3-with-no-ssr

It basically comes down to `window` not being available in a Node.js environment, so the code itself has to be required only on the client side, which is what `ssr: false` handles.

**Comment by Luktm** [comment]
> Sounds like you'll want to use the `ssr: false` option for `next/dynamic`: https://github.com/zeit/next.js#3-with-no-ssr
> 
> It basically comes down to `window` not being available in a Node.js environment, so the code itself has to be required only on the client side, which is what `ssr: false` handles.

I had tried before, but it doesn't work, could you please show me how you do it in code haha

**Comment by seymoe** [comment]
hi,  i have this problem and i use `ssr: false`, solved successful. But another problem is the Component i import have a static method, I cannot call that method, so how to deal with this, thanks!!

**Comment by BranceLee** [comment]
##  I meet the same problem and I have solved it.
I use the **HOC** to wrap a **img** tag, because I need use the `lazysizes` to render in the web client rather than the server, So I use the **HOC**, and Import it dynamic.

```js
import dynamic from 'next/dynamic';

const Image=dynamic(import ('../components/Image'),{ssr:false});
```

**Comment by yareyaredesuyo** [comment]
The answer for using react-chat-widget in nextjs.

```js
const Widget = dynamic(() => import("react-chat-widget").then(mod => mod.Widget), {
  ssr: false
});
```

**Comment by yareyaredesuyo** [comment]
And when loading function, it looks like not good way for loading (because it maybe converted to LoadableComponent)

So Have to load like this. 

```js
if (typeof window !== 'undefined') { 
  const { addResponseMessage } = require('react-chat-widget'); 
  addResponseMessage("test");
}  
```

Is there any good way for loading function ?

**Comment by adventurini** [comment]
Is there a workaround for using absolute positioning on a modal and a window click event to replace the onBlur method? 

I would typically use the following code to register an onBlur on a component with absolute positioning.

```
 window.onclick = (e) => {
    emojiClick && (e.target.className === "create-post-emoji-picker" ? null : setEmojiClick(false))
  }
```

**Comment by bradgreens** [comment]
I hit this problem using a NextJs stack and it makes complete sense window is not [yet] defined at the time of import. 

NextJs documentation identifies this issue clearly and helped me along. 
- https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by qnxdev** [comment]
How to solve this with ssr: true, I mean with Server side rendering.

**Comment by mayur-keswani** [comment]
> How to solve this with ssr: true, I mean with Server side rendering.
Hello, Did you solve this issue with  wssr=true?
