### ISSUE TITLE
Wiki for next components

### ISSUE THREAD

**Issue by matthewmueller** [zeit/next.js#609]
Finding myself making a bunch of little snippets to make things work on both client and server inside the `getInitialProps` – it'd be great to have a place to share these modules.

I'll start with one :-)

- https://github.com/matthewmueller/next-cookies

Here's a basic redirect one:

```js
function redirect (ctx, path) {
  if (ctx.res) ctx.res.writeHead(302, { Location: path })
  else document.location.pathname = path
}
```

Some other ideas:

- `alert(...)` : that opens up a nice modal or top banner on client, `console.error`'s on the server

**Comment by rauchg** [comment]
Just made the Wikis public 🎉
