### ISSUE TITLE
Link the home page with query

### ISSUE THREAD

**Issue by zefexdeveloper** [zeit/next.js#6092]
The title must be confusing because I really didn't think of a better description for that.

I want to create routes like twitter where the routes would be something like http://example.com/username

That is how I implemented so far (custom `server.js`):

```js
  server.get('/login', (req, res) => app.render(req, res, '/login', req.query));

  server.get('/register', (req, res) =>
    app.render(req, res, '/register', req.query)
  );

  server.get('/:username', (req, res) =>
    app.render(req, res, '/user', {
      username: req.params.username
    })
  );

  server.get('*', (req, res) => handle(req, res));
```

it's working normally if I try to access directly, but if I create a link like this:

```js
    <Link as="/johndoe" href="/?username=johndoe">
      <a>johndoe</a>
    </Link>
```

In a page it will put in the browser the url but it won't redirect automatically.

How can I accomplish that?

**Comment by timneutkens** [comment]
Your route definition in the server.js points to `/user` while your `href` points to `/`, I guess that's the issue:

```
    <Link as="/johndoe" href="/user?username=johndoe">
      <a>johndoe</a>
    </Link>
```
