### ISSUE TITLE
Integration with linaria

### ISSUE THREAD

**Issue by egorovli** [zeit/next.js#6097]
Hi. I'm trying to use [linaria](https://github.com/callstack/linaria), and currently have a couple of issues.

### Custom loader

First of all, I need to [add a custom loader](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md) for `/\.jsx?$/` files. I've (sort of) achieved it by doing so, but I'm not sure it's done 100% correctly:

```js
let withCSS = require('@zeit/next-css')
// ...

module.exports = withCSS({
  // ...
  webpack (config, { defaultLoaders, isServer }) {
    if (!isServer) {
      let rule = config.module.rules.find(rule => rule.use === defaultLoaders.babel)

      if (rule) {
        if (!Array.isArray(rule.use)) {
          rule.use = [ rule.use ]
        }

        rule.use.push({
          loader: 'linaria/loader',
          options: {
            preprocessor: 'none'
          }
        })
      }
    }

    return config
  }
})
```

It _seems_ to work, but I'm still seeing requests to styles-related `js` files, like:

![image](https://user-images.githubusercontent.com/5165202/51466056-5e7d5b00-1d7a-11e9-87e1-bc6c26e57a0a.png)

Although this file seems to be empty:

![image](https://user-images.githubusercontent.com/5165202/51466093-794fcf80-1d7a-11e9-9fa4-4511d5107a90.png)

So the question is: is correct to add a custom loader for `js`/`jsx` files this way and should there be `chunks/style.[hash].js` file in production when using [@zeit/next-css](https://github.com/zeit/next-plugins/tree/master/packages/next-css)?

### Critical CSS

In order to [extract critical CSS](https://github.com/callstack/linaria/blob/master/docs/CRITICAL_CSS.md) linaria provides a helper function which needs to read the contents of the compiled CSS file. To achieve that I need a list of compiled CSS files. I've tried reading `build-manifest.json` on each request (with custom server), find `.css` files, read them and concatenate together, but this approach seems a bit ugly, and moreover it doesn't really work in dev mode, because the `build-manifest.json` is only updated after the page render.

So the question is: which is the correct way to access stats of the page being rendered in order to get information about its related CSS files?

### A minor follow-up

Is it possible to opt out of injecting the link to the compiled `css` files in pages, if I can distinguish between critical and non-critical CSS and manually add a `link[rel=preload]` for the non-critical part of it?

**Comment by timneutkens** [comment]
Please follow the issue template. https://spectrum.chat/?t=95b2a6f9-1a1f-4dc7-b410-b9349bcbde21
