### ISSUE TITLE
Deploy next.js project with windows iis 10.0

### ISSUE THREAD

**Issue by IMSamuel** [zeit/next.js#6100]
Hey
Im quiet new to next.js and im trying to deploy my project to a windows webserver. Ive already installed node and iisnode but i really dont know how to get it work.

**Comment by timneutkens** [comment]
You'll have to run `next build` and `next start`. I'm not particularly experienced with iis, so I would suggest posting your question on https://spectrum.chat/next-js as per the issue template so that you reach more users.
