### ISSUE TITLE
Wrong cache growing page document size

### ISSUE THREAD

**Issue by gilbertosouza-hotmart** [zeit/next.js#6103]
# Bug report

## Descripton

As I (and other users) navigate through my Next.js application, all loaded data from the visited pages are appended into `_NEXT_DATA_` and css styles into header's `<style />` tag. 
If I reload the page, the data remains. If I haven't visited a page that someone else has visited, the data is delivered to me as well.
The only way to clear `_NEXT_DATA_` and `<style />` tag is restarting the server.

## To Reproduce

1. Start Next.js application
2. Check HTML document size
3. Navigate through other pages of the application (loading data from external server, loading inner components styles)
4. Check HTML document size again
5. Notice that page document size has increased

## Expected behavior
`_NEXT_DATA_` and `<style />` tag should be cleared when page is refreshed.
Maybe, we should have a cache limit.

## System information
 - OS: macOS Sierra
 - Browser: Any
 - Version of Next.js: 7.0.1

## Additional context
Some of my stack:

"@babel/cli": "7.0.0",
"@babel/core": "7.0.0",
"@babel/node": "7.0.0",
"@babel/plugin-transform-react-jsx": "7.0.0",
"@babel/preset-react": "7.0.0",
"@zeit/next-css": "1.0.1",
"babel-core": "7.0.0-bridge.0",
"babel-loader": "8.0.0",
"babel-plugin-dynamic-import-node": "2.2.0",
"babel-plugin-module-resolver": "3.1.1",
"babel-plugin-styled-components": "1.7.1",
"babel-plugin-transform-define": "1.3.0",
"babel-plugin-wrap-in-js": "1.1.1",
"compression": "1.7.0",
"express": "4.15.3",
"ignore-loader": "0.1.2",
"module-alias": "2.0.0",
"next": "7.0.1",
"next-routes": "1.4.2",
"react": "16.5.0",
"react-dom": "16.5.0",
"react-redux": "5.0.5",
"redux": "4.0.0",
"redux-logger": "3.0.6",
"redux-promise-middleware": "5.1.1",
"redux-thunk": "2.2.0",
"regenerator-runtime": "0.11.1",
"styled-components": "2.1.1",
"tlds": "1.196.0",
"uglify-es": "3.3.9",
"webpack": "4.20.2",

* I'm not sure if this is a Next.js bug. Maybe there's something i'm doing wrong.

**Comment by timneutkens** [comment]
It definitely sounds like you're doing something wrong, it sounds like you're creating a global store for all getInitialProps results that is then transcending requests.

**Comment by timneutkens** [comment]
```
"@babel/cli": "7.0.0",
"@babel/core": "7.0.0", => This is included by Next.js
"@babel/node": "7.0.0",
"@babel/plugin-transform-react-jsx": "7.0.0", => This is included by Next.js
"@babel/preset-react": "7.0.0", => This is included by Next.js
"@zeit/next-css": "1.0.1",
"babel-core": "7.0.0-bridge.0",
"babel-loader": "8.0.0", => Next.js includes babel-loader
"babel-plugin-dynamic-import-node": "2.2.0", => Make sure this is only applied in test environments
"babel-plugin-module-resolver": "3.1.1",
"babel-plugin-styled-components": "1.7.1",
"babel-plugin-transform-define": "1.3.0",
"babel-plugin-wrap-in-js": "1.1.1",
"compression": "1.7.0",
"express": "4.15.3",
"ignore-loader": "0.1.2",
"module-alias": "2.0.0",
"next": "7.0.1",
"next-routes": "1.4.2",
"react": "16.5.0",
"react-dom": "16.5.0",
"react-redux": "5.0.5",
"redux": "4.0.0",
"redux-logger": "3.0.6",
"redux-promise-middleware": "5.1.1",
"redux-thunk": "2.2.0",
"regenerator-runtime": "0.11.1", => Next.js handles this
"styled-components": "2.1.1",
"tlds": "1.196.0",
"uglify-es": "3.3.9", => Next.js does minification by default
"webpack": "4.20.2", => Next.js ships with webpack
```

**Comment by gilbertosouza-hotmart** [comment]
@timneutkens thanks for your response. I have the same feeling, but can't find anything. Everything I did was based on this repo's examples. Also, just removed those dependencies but nothing changed.

**Comment by timneutkens** [comment]
@gilbertosouza-hotmart it's impossible to help without seeing your code in this case.

**Comment by gilbertosouza-hotmart** [comment]
Ok, there is something I'm considering to be an issue.
This is an example of 'getInitialProps' that i'm doing:

```
static async getInitialProps ({ query, asPath, store, req }) {
  const userName = query.userName.toLowerCase()
  const hasFetched = !!store.getState().users.byUserName[userName]
  if (!hasFetched) {
    await store.dispatch(getUser({ userName }, req))
  } else {
    store.dispatch(getUser({ userName }, req))
  }
  return { userName }
}
```
Does the data persist if do dispatch like that, on the server?

**Comment by timneutkens** [comment]
Depends on how you're instantiating the `store`

**Comment by pruhstal** [comment]
@timneutkens what do you recommend to remove unnecessary packages (like the list you provided) above? `npm prune`?

**Comment by gilbertosouza-hotmart** [comment]
I'm using the [with-redux](https://github.com/zeit/next.js/tree/canary/examples/with-redux) example to set my store up.
Even having this piece of code: 
```
// Always make a new store if server, otherwise state is shared between requests
if (isServer) {
    return initStore(initialState)
}
```
It keeps the data on the server-side store.

**Comment by timneutkens** [comment]
I'm going to close this issue as I'm sure this is not related to the way Next.js works, but instead something in your code. Feel free to create a thread on https://spectrum.chat/next-js with a clear and concise reproduction so that it's easier to help you, it's really hard to "just guess" when you're using a bunch of other dependencies and state management.
