### ISSUE TITLE
RUNTIME CONFIG IN CLIENT-SIDE

### ISSUE THREAD

**Issue by octal-laurence** [zeit/next.js#6105]
# Question about Next.js
I planning to put my secretkeys on publicRuntimeConfig, I need to confirm if this is secured feature or is it necessary for that features., in your example you didnt put a secret so Im kinda assuming secret key is not to put there, please confirm

Questions should be posted on https://spectrum.chat/next-js

Exposing configuration to the server / client side
The next/config module gives your app access to runtime configuration stored in your next.config.js. Place any server-only runtime config under a serverRuntimeConfig property and anything accessible to both client and server-side code under publicRuntimeConfig.

// next.config.js
module.exports = {
  serverRuntimeConfig: { // Will only be available on the server side
    mySecret: 'secret',
    secondSecret: process.env.SECOND_SECRET // Pass through env variables
  },
  publicRuntimeConfig: { // Will be available on both server and client
    staticFolder: '/static',
  }
}

**Comment by timneutkens** [comment]
The docs are pretty clear about this, anything you add to `publicRuntimeConfig` will be sent to the browser / viewable in the html source of the page.
