### ISSUE TITLE
next tries to resolve modules that were removed from code

### ISSUE THREAD

**Issue by jackgray** [zeit/next.js#6108]
# Bug report

Whenever I change the folder name of a module or remove it from my code, next build still tries to resolve that path that has been removed from the code.

abridged error output: 

> { Error: (client) ./components/CreateComment.js
> Module not found: Error: Can't resolve './gql-tags/SINGLE_BILL_QUERY' in '/Users/jackgray/webapps/Adva
> nced-React/politicious/frontend/components'
>  @ ./components/CreateComment.js 47:0-61

>   [ '(client) ./components/CreateComment.js\nModule not found: Error: Can\'t resolve \'./gql-tags/SINGLE_BILL_QUERY\' in \'/Users/jackgray/webapps/Advanced-React/politicious/frontend/components\'\n @ ./components/CreateComment.js 47:0-61\n @ ./components/Bill/SingleBill.js\n @ ./pages/bill.js\n @ multi ./pages/bill.js',

import statements from CreateComment.js:
```
import React, { Component } from 'react';
import Router from 'next/router';
import { Mutation } from 'react-apollo';
import gql from 'graphql-tag';
import Form from './styles/Form';
import Error from './ErrorMessage';
import { perPage } from '../config';
```

This happens to me allll the time now. I've had some luck deleting the .next build folder but that hasn't been working lately. I've deleted and reinstalled node modules, then node_modules/cache to no avail.  

It is inconsistent. The error may arise weeks after making the change. Specifically in the most recent case, I received the error after a new git commit, started typing this issue, then after a git push, it went away. I have no earthy idea how those two things could be related. 

if you want to try to reproduce (although it may very well work for you), here is the repo:https://github.com/jackgray/govtrackr

running with next version 7.0.2 and next-with-apollo 3.1.3

here's the rest of my package.json dependencies:

```
"dependencies": {
		"apollo-boost": "^0.1.16",
		"apollo-cache-inmemory": "^1.3.12",
		"apollo-client": "^2.4.8",
		"apollo-link": "^1.2.6",
		"apollo-link-context": "^1.0.12",
		"apollo-link-error": "^1.1.5",
		"apollo-link-http": "^1.5.9",
		"apollo-link-state": "^0.4.2",
		"apollo-link-ws": "^1.0.12",
		"apollo-utilities": "^1.0.27",
		"babel-core": "^7.0.0-bridge.0",
		"babel-plugin-styled-components": "^1.7.1",
		"date-fns": "^2.0.0-alpha.7",
		"downshift": "^2.2.3",
		"enzyme": "^3.6.0",
		"enzyme-adapter-react-16": "^1.5.0",
		"graphql": "^14.0.2",
		"graphql-tag": "^2.9.2",
		"lodash": "^4.17.11",
		"lodash.debounce": "^4.0.8",
		"next": "^7.0.2",
		"next-with-apollo": "^3.1.3",
		"nprogress": "^0.2.0",
		"prop-types": "^15.6.2",
		"react": "^16.5.2",
		"react-adopt": "^0.6.0",
		"react-apollo": "^2.3.3",
		"react-dom": "^16.5.2",
		"react-stripe-checkout": "^2.6.3",
		"react-transition-group": "^2.5.0",
		"styled-components": "^3.4.9",
		"waait": "^1.0.2"
	},
	"devDependencies": {
		"babel-jest": "^23.6.0",
		"babel-plugin-module-resolver": "^3.1.1",
		"casual": "^1.5.19",
		"enzyme-to-json": "^3.3.4",
		"graphql-tools": "^4.0.0",
		"jest": "^23.6.0",
		"jest-transform-graphql": "^2.1.0"
	},
	"jest": {
		"setupTestFrameworkScriptFile": "<rootDir>/jest.setup.js",
		"testPathIgnorePatterns": [
			"<rootDir>/.next/",
			"<rootDir>/node_modules/"
		],
		"transform": {
			"\\.(gql|graphql)$": "jest-transform-graphql",
			".*": "babel-jest"
		}
	},
	"//": "This is our babel config, I prefer this over a .babelrc file",
	"babel": {
		"env": {
			"development": {
				"presets": [
					"next/babel"
				],
				"plugins": [
					[
						"styled-components",
						{
							"ssr": true,
							"displayName": true
						}
					]
				]
			},
			"production": {
				"presets": [
					"next/babel"
				],
				"plugins": [
					[
						"styled-components",
						{
							"ssr": true,
							"displayName": true
						}
					]
				]
			},
			"test": {
				"presets": [
					[
						"next/babel",
						{
							"preset-env": {
								"modules": "commonjs"
							}
						}
					]
				],
				"plugins": [
					[
						"styled-components",
						{
							"ssr": true,
							"displayName": true
						}
					]
				]
			}
		}
	}
```

**Comment by timneutkens** [comment]
I can't reproduce this issue. Please follow the issue template and provide a clear and concise minimal reproduction (with just `next` and a minimal amount of dependenies).
