### ISSUE TITLE
when I do HTTP request to custom api server in getInitialProps, it sends to 80port. Can I send it to 3000port which my server is listening.

### ISSUE THREAD

**Issue by ktjd123** [zeit/next.js#6111]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js <- doesn't work.

the code inside getInitialProps is
```js
static async getInitialProps({ query }) {
    const result = await axios.get('/api/account/check');
    console.log(result.data);
    return query;
  }
```

the result screen is 

![2019-01-24 9 04 15](https://user-images.githubusercontent.com/15044488/51645310-1139fd00-1fb7-11e9-9063-a3f948a4f026.png)
This.

I'm wondering why http request inside getInitialProps is sending to 80port.

![2019-01-24 9 05 37](https://user-images.githubusercontent.com/15044488/51645363-3af32400-1fb7-11e9-81b2-23789c3257f9.png)
I'm using simple express custom server(nothing special).

**Comment by timneutkens** [comment]
Please follow the issue template.
