### ISSUE TITLE
 r.isMemo is not a function

### ISSUE THREAD

**Issue by machester4** [zeit/next.js#6117]
# Bug report

## Describe the bug
after doing the deploy with now I get error 500. in the now logs I have seen this error ` r.isMemo is not a function`. in debug this function if it exists and no error has been obtained.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. run - `now`
2. run - ` now log <domain | alias>`

![captura de pantalla 2019-01-24 a la s 07 18 12](https://user-images.githubusercontent.com/25928946/51671793-8ce07d80-1fa8-11e9-8684-8141d5889320.png)

## System information
 - macOS
 - Browser all
 - Version of Next.js 7.0.2
- Now version 13.1.2-canary.3

**Comment by timneutkens** [comment]
`isMemo` doesn't exist in the Next.js codebase. I guess it's something in your codebase.

**Comment by davidohlin** [comment]
@machester4 Having the same issue and I'm not sure why, also in `../pages/index.js`. Mind sharing your package.json? Here's mine:

```
  "dependencies": {
    "@contentful/rich-text-html-renderer": "^12.1.2",
    "@zeit/next-css": "^1.0.1",
    "contentful": "^7.1.0",
    "dotenv-webpack": "^1.6.0",
    "express": "^4.16.4",
    "html-to-react": "^1.3.4",
    "next": "^7.0.2",
    "next-redux-wrapper": "^2.1.0",
    "postcss-easy-import": "^3.0.0",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-dom-confetti": "0.0.10",
    "react-pose": "^4.0.6",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.10.0",
    "styled-components": "^4.1.3"
  },
  "devDependencies": {
    "autoprefixer": "^9.4.5",
    "babel-plugin-styled-components": "^1.10.0",
    "cssnano": "^4.1.8",
    "postcss-import": "^12.0.1",
    "tailwindcss": "^0.7.3"
  }
```

**Comment by machester4** [comment]
try removing all my pages leaving only my index and the problem continues. try removing index and the problem continues. the strange thing is that it only happens in production.

**Comment by remiroyc** [comment]
Same problem here

**Comment by carlesandres** [comment]
Same. Something must have changed in a builder because I cannot event deploy versions of my code that I was able to deploy just fine just a few days ago. That is, I do `git checkout [...replace git commit hash here]` and deploying doesn't work.

@timneutkens can you consider re-opening this issue?

**Comment by timneutkens** [comment]
There is no reproduction, I can't really help or reopen any issue that has no way to be fixed.

**Comment by machester4** [comment]
@timneutkens you tried with your own _app.js?

**Comment by timneutkens** [comment]
@machester4 please provide a clear and concise reproduction so that I can have a look.

**Comment by jirikolarik** [comment]
Same problem here. Local build works just fine. Build on production seems to be fine, but once you try to open website, it breaks..

```
01/24 10:57 PM (34m)
patching https://api-bru1.zeit.co/v2/now/deployments/dpl_HZeYLLhXdnnjYbiQh8yu47emVcH9/builds/bld_fwskjgtet with {"readyState":"DEPLOYING"}
01/24 10:57 PM (34m)
finished
01/24 11:05 PM (26m)
TypeError: r.isMemo is not a function
    at s (/var/task/.next/server/static/dpP3VYfstY~spbSX5RmAK/pages/index.js:31:12018)
    at t (/var/task/.next/server/static/dpP3VYfstY~spbSX5RmAK/pages/index.js:31:12426)
    at t (/var/task/.next/server/static/dpP3VYfstY~spbSX5RmAK/pages/index.js:31:12374)
    at /var/task/.next/server/static/dpP3VYfstY~spbSX5RmAK/pages/index.js:20:50002
    at Module.23aj (/var/task/.next/server/static/dpP3VYfstY~spbSX5RmAK/pages/index.js:1:7808)
    at n (/var/task/.next/server/static/dpP3VYfstY~spbSX5RmAK/pages/index.js:1:225)
    at Object.36 (/var/task/.next/server/static/dpP3VYfstY~spbSX5RmAK/pages/index.js:12:467)
    at n (/var/task/.next/server/static/dpP3VYfstY~spbSX5RmAK/pages/index.js:1:225)
    at /var/task/.next/server/static/dpP3VYfstY~spbSX5RmAK/pages/index.js:1:1059
    at Object.<anonymous> (/var/task/.next/server/static/dpP3VYfstY~spbSX5RmAK/pages/index.js:1:1069)
```

**Comment by machester4** [comment]
I just found out the problem is with `react-redux`. to replicate it just create a clean project and connect a page with connect HOC.

**Comment by timneutkens** [comment]
@machester4 can you create a repository or something?

**Comment by machester4** [comment]
@timneutkens can solve it by downloading to version react-redux `^4.4.9`. Do you want me to upload the repository for you to investigate?

**Comment by remiroyc** [comment]
I tried to downgrade react-redux on my production but it didn’t work

**Comment by carlesandres** [comment]
Pinning `react-redux` to `4.4.9` sorts it out for me, but is far from ideal.

My app builds and runs fine in production mode on my machine with `react-redux` set to `^6.0.0`.  But it fails with the `r.isMemo...` error when deploying to `now`.

Old versions of my app that I deployed with no problem, fail to be deploy to `now` at the moment. And I they have a `yarn.lock` file. So, as @paulogdm mentions [here](https://spectrum.chat/zeit/now/typeerror-r-ismemo-is-not-a-function~86551bb9-4d50-43cb-b6c1-e27f62385495?m=MTU0ODMzODc0OTM4Mw==) it could be a regression in a now builder.

**Comment by machester4** [comment]
@carlesandres Hi, I do not think it's a bad idea to downgrade in this case. you can see this [https://github.com/reduxjs/react-redux/issues/1164](url)

**Comment by JamesBliss** [comment]
Hey, I'm having a similar issue all of a sudden but with `n.isMemo is not a function`

I don't have redux though and it's happened all of a sudden when I just updated some CSS on my project.

Any thoughts?

**Comment by timneutkens** [comment]
> There is no reproduction, I can't really help on or reopen any issue that has no way to be fixed.

I'd like to, once again, ask for a reproduction in a repository. 6 people in this issue have said they can reproduce but no one has provided a reproduction. Making it really hard for me to solve your issue, I'd be super happy to have a look into your issue and spend time on this, but it's hard to do that based on a "in my app it fails" type of conversation.

**Comment by machester4** [comment]
you are right @timneutkens  in my house I have a basic example in a couple of hours I can upload it. The only difference is that the problem is with `react-redux`, but maybe you can do something with it.

**Comment by JamesBliss** [comment]
@timneutkens just look at my https://github.com/jamesbliss/areliverpoolwinning that project is the one I needed to switch to use `@now/static-build` 👍

**Comment by timneutkens** [comment]
@JamesBliss I can't reproduce the issue both on your repo as-is nor when switching to `now/next` legacy mode, you'll want to use https://github.com/zeit/next.js/issues/5750#issuecomment-451607604

**Comment by sebastiansson** [comment]
@timneutkens

I'm experiencing the same issue. I created a [repo](https://github.com/Digitaliseringsbyran/next-ismemo) and deployed it with Now. I made it with `npx create-next-app --example with-redux-wrapper` The breaking seems to happen when I update the dependencies in my package.json file.

**Working versions on Now**
https://next-ismemo-hoyaaj0kt.now.sh ([commit](https://github.com/Digitaliseringsbyran/next-ismemo/commit/0a6958c))
https://next-ismemo-1ejnp2zr8.now.sh ([commit](https://github.com/Digitaliseringsbyran/next-ismemo/commit/881ea55))

**Broken version on Now**
https://next-ismemo-i7l0sp7lo.now.sh/ ([commit](https://github.com/Digitaliseringsbyran/next-ismemo/commit/a79efb4)).

See the log file below for information about the broken https://next-ismemo-i7l0sp7lo.now.sh deployment in Now.
[broken_logs.txt](https://github.com/zeit/next.js/files/2796756/broken_logs.txt)

**Comment by JamesBliss** [comment]
@timneutkens what is the best way to host a next / apollo project that isn't legacy if using `now/next` is legacy mode, or is that fine?

Additionally, if I do the tweaks in that issue/comment I should be good to go?

**Comment by timneutkens** [comment]
@JamesBliss `now/next` is not legacy, it *has a legacy mode* which is basically forcing a specific canary version and options / disregards lockfiles etc. You can read more about it here: https://github.com/zeit/now-builders/pull/150

I'm not sure if it will solve the issue for you, as I couldn't even reproduce in legacy mode / static build

**Comment by JamesBliss** [comment]
@timneutkens Okay cool, just tried again still same issue. I should note it only happens when you go to `/match`.

Here is a gist of what comes out in the logs: https://gist.github.com/JamesBliss/1270366d4b935ebce755b70ac9fcb3a8

**Comment by timneutkens** [comment]
Thanks to @sebastiansson I can reliably reproduce now, having a look right now.

**Comment by timneutkens** [comment]
Thank you very much @sebastiansson, because of your reproduction it was trivial to pinpoint the actual issue (took me 10 minutes). This is a great example of why providing a clear reproduction gets your issue solved faster 🙏 

I've just tagged a new canary release holding the fix, it will take ~15-20 minutes for it to become available on npm because of test runs etc.

Once it's available use this comment to upgrade your application: https://github.com/zeit/next.js/issues/5750#issuecomment-451607604

**Comment by victorsferreira** [comment]
Same happened to me, but i'm not using Zeit. I just found this thread. 
Downgrading Redux solved for me.

**Comment by sebastiansson** [comment]
@timneutkens That was the least I could do. Thank you for making Next.js even better!

OT: how did you debug? Is there someway to emulate the Now environment locally? Or did you just use a non-minified version of next.js or something?

**Comment by timneutkens** [comment]
@sebastiansson Happy to 🙏

Re debugging:
So you can run `next build` locally and it will output the serverless page bundles in `.next/serverless/pages`, then you can run the bundle using a simple Node.js HTTP server as described here: https://github.com/zeit/next.js#one-level-lower

With relation to how I knew what was going on, I knew that we added `react-is` to the dependencies of Next.js in the canary branch, `isMemo` sounded like something coming from there, so it made sense to check there. Then I noticed how there was no isMemo in the version of react-is that Next.js has so I noticed it must have been something in module resolution. I remembered another open issue related to module resolving with Next.js node_modules taking priority so I checked the node_modules resolve rules and indeed it was causing the issue. So removing it solved both this issue and the other open issue.

**Comment by sebastiansson** [comment]
@timneutkens Thanks for the explanation!

**Comment by JamesBliss** [comment]
@sebastiansson I know this is closed but I have tried all the steps you suggest and I still cannot get my `/match` route to work.

**Comment by ducdev** [comment]
I'm not using `redux`, but I'm still encountering this issue.

**Comment by timneutkens** [comment]
Did you upgrade to `next@canary`?

**Comment by afitterling** [comment]
Everyone as slow as me, the solution for this problem is just to install: next@canary. Even with redux it works quite fine. Also with now 14. However check at this, as you need to fix this because of the necessary next upgrade:
https://github.com/zeit/now-builders/blob/master/errors/now-next-no-serverless-pages-built.md

**Comment by timneutkens** [comment]
Just to check in here again, this has been released under stable 🙏
