### ISSUE TITLE
Nextjs 8.0.0-canary.12 this.context.updateHead is not a function

### ISSUE THREAD

**Issue by DmytroA** [zeit/next.js#6119]
Hello. I`m trying to upgrade nextjs version 7.0.2 to 8.0.0-canary.12. It seems like works correct and even page is loaded but then in few seconds i get this error:
![chrome_2019-01-24_18-02-12](https://user-images.githubusercontent.com/7725212/51690952-79fa9700-2002-11e9-8d85-609cc83c579e.png)

Do you have any thoughts? Thank you.

**Comment by timneutkens** [comment]
You're probably using an old version of React. Try upgrading.
