### ISSUE TITLE
question about pkg.

### ISSUE THREAD

**Issue by junjie-lean** [zeit/next.js#6124]
# Question about Next.js
os -v:macOS Mojave 10.14.2 
node -v: 10.14.2
pkg -v: 4.3.7
next -v:7.0.2
question description：
I use "PKG" to package my next app, and the packaged file can only be executed in the next app project path. If executed this file in another folder, an error will be reported "Could not find a valid build in the {process.cwd()} directory!" I guess my PKG configuration in package.json is wrong. It looks like this:
```javascript
...
"pkg" : {
  "assets" :[
      ".next/**/*", 
       "static/**/*"
   ],
  "scripts" : ".next/server/**/*. Js"
}
...
```
How to package a next application with a complex directory structure?

**Comment by timneutkens** [comment]
Please follow the issue template and post questions on https://spectrum.chat/next-js.
