### ISSUE TITLE
Cannot work with passport-google-plus-token

### ISSUE THREAD

**Issue by RuizhenMai** [zeit/next.js#6126]
#### Issue description
Potentially a bug? I tried to implement express js and use passport-google-plus-token strategy to login user. My react app works fine but nextjs always return 401 Unauthorized

#### To reproduce the issue

1. Use npm to install passport and passport-google-plus-token
2. 
```javascript
// server.js
const next = require("next");
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();
const PORT = process.env.PORT || 3000;
const passport = require("passport");
require("./passport");

const loadServer = () => {
  const express = require("express");
  const server = express();

  server.get("/", (req, res) => {
    app.render(req, res, "/");
  });

  server.get("/verify", passport.authenticate("google-plus-token"));

  server.get("*", (req, res) => {
    return handle(req, res);
  });

  server.listen(PORT, err => {
    if (err) throw err;
    console.log(`> Ready on http://localhost:${PORT}`);
  });
};

app
  .prepare()
  .then(loadServer)
  .catch(ex => {
    console.error(ex.stack);
    process.exit(1);
  });
```

```javascript
// passport.js
const GooglePlusTokenStrategy = require("passport-google-plus-token");
const passport = require("passport");

passport.use(
  new GooglePlusTokenStrategy(
    {
      clientID:
        YOUR_GOOGLE_CLIENT_ID,
      clientSecret: YOUR_GOOGLE_CLIENT_SECRET,
      passReqToCallback: true
    },
    function(req, accessToken, refreshToken, profile, next) {
      return next(error, { user: "1" });
    }
  )
);
```
3. Use postman or frontend to send request to localhost/verify in the body with 
```
{
	"access_token":YOUR_TOKEN
}
```
 token can be found from https://developers.google.com/oauthplayground/ under OAUTH2 api 

### What's the expected result?

If it's not registered through google it should return 500 Invalid credentials or something about Project xxx is not found and cannot be used for API calls and enable it on google developer

### What's the actual result?

401 Unauthorized

**Comment by timneutkens** [comment]
This is unrelated to Next.js, however this example might help you. https://github.com/zeit/next.js/tree/canary/examples/with-cookie-auth

**Comment by RuizhenMai** [comment]
Sorry I really can't get this to work. One is either I started with the server side with profile.js or login.js, I still cannot login to fetch the github profile. Second is it shows SSL_PROTOCOL_ERR on the browser. This example doesn't seem starter friendly. Third is this does not affect the fact that nextjs's server cannot correctly run the passportjs google plus token strategy.
