### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by IceeMC** [zeit/next.js#6141]
# Bug report

## Describe the bug

When trying to post the website in a discord channel. I keep getting TypeError: Converting circular structure to JSON. And it won't embed with the meta tags, it just throws that error, it pisses me off how next.js doesn't handle JSON errors.

## Expected behavior
When you post https://beta.discordsbestbots.xyz/ in a discord channel, you get the error

## Screenshots
![Screenshot](https://images.remixbot.ml/FQ21l0C7.png)
![Chat thing](https://images.remixbot.ml/8yynyLOT.png)

## System information
 - OS: linux (ubuntu 16.04)
 - Browser: chrome
 - Version of Next.js: [e.g. 7.0.2]

**Comment by IceeMC** [comment]
I can't continue with the development of my site until this is fixed.

**Comment by timneutkens** [comment]
I've added an explanation link for this particular error in #6149: https://github.com/zeit/next.js/blob/canary/errors/circular-structure.md

> it pisses me off how next.js doesn't handle JSON errors.

It actually does handle JSON errors, if serialization breaks it throws an error to bubbles up and renders the 500 page in production / the error overlay in development. There is no better way to handle this as the serialized object is needed for client hydration. You're also super welcome to send pull requests to improve error reporting / implement similar err.sh links to help other users.
