### ISSUE TITLE
ECONN refused when doing apollo graphQL query from getInitialProps

### ISSUE THREAD

**Issue by sc4224** [zeit/next.js#6159]
# Bug report

## Describe the bug
Following the *with-apollo-auth* example
Successful behavior when I do client-side ApolloConsumer query. I pass the client through and query works.

Unsuccessful behavior when I attempt to do a server side query through getInitialProps. I pass the client through a handler that calls the same query and I get a ECONN refused error as shown below.

<img width="817" alt="screen shot 2019-01-27 at 11 32 24 pm" src="https://user-images.githubusercontent.com/30026659/51814936-d1f7fe80-228b-11e9-81e0-2204d75f1443.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. I set up my ApolloClient in the init-apollo file as follows:
```
  const httpLink = createHttpLink({
    uri: 'http://localhost:8080/api/graphql',
    credentials: 'same-origin'
  })

  const authLink = setContext((_, { headers }) => {
    const token = getToken()
    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : ''
      }
    }
  })

  return new ApolloClient({
    connectToDevTools: process.browser,
    ssrMode: !process.browser, // Disables forceFetch on the server (so queries are only run once)
    link: ApolloLink.from([ authLink, httpLink ]),
    cache: new InMemoryCache().restore(initialState || {})
  })

```
2. I set up my query as follows:
```
import gql from 'graphql-tag'

export default apolloClient => {
  apolloClient
    .query({
      query: gql`
        {
          getUser {
            id
          }
        }
      `
    })
    .then(({data}) => {
      console.log(data);
      return { userDetails: data.getUser }
    })
    .catch((err) => {
      // Fail gracefully
      console.log(err);
      return { userDetails: {} }
    })
  }
```
3. I set up my getInitialProps function in the index.js file within the pages directory:
```
  import getUser from '../shared/services/get-user';

  static async getInitialProps (context) {
    const results = await getUser(context.apolloClient)
    console.log(results);
    return {}
  }
```
## Expected behavior
I expect to see a log of the user returned, however I get an ECONNREFUSED error as shown above.

## Screenshots
Screenshot above.

## System information
 - OS: macOS Mojave
 - Browser (if applies) Chrome
 - Version of Next.js: 7.0.2
 - Version of ApolloClient: 2.4.12l

## Additional context
 - Using Absinthe (Elixir+Phoenix) GraphQL API, url specified: http://localhost:8080/api/graphq
 - Using docker-compose to spin up multiple containers. API and NextJS client are in separate containers sitting behind nginx server. Nginx server routes to relevant container depending on the url endpoint specified. If url contains *api*, API container will be called.

**Comment by timneutkens** [comment]
ECONNREFUSED is a network error meaning there is nothing listening/replying on the specific url.

**Comment by sc4224** [comment]
@timneutkens How can it lose connection the moment I put it in getInitialProps is my question.

**Comment by K-JHC** [comment]
@sc4224 having the same problem, how did you solve it?

**Comment by wwwebman** [comment]
@timneutkens,  @K-JHC is right. Unfortunately if you are using docker-compose, containers can talk to each other by using service name or ip. So instead of using `localhost:3000/graphql` you have to use `serviceName|IP:3000/graphql` in your network. o now I found next solution:
1. .env + dynamic client.urldepends on browser/server request  (localhost:3000 || serviceName:3000)  -> sounds like workaround for me :(
2. Some proxy or mappping serviceName < - >  localhost inside containers.

Hard topic basically.

**Comment by sockol** [comment]
Ran into the same issue. Solved it by setting up an nginx container that is the main point of entry for all services, where /graphql maps to the API app, and / maps to the rest. 

docker-compose.yml
```
nginx-proxy:
        image: nginx:latest  
        volumes:
          - ./server.conf:/etc/nginx/nginx.conf
        depends_on:
          - client
        ports:
          - 80:80
  
    client:
        ...
        expose:
          - "82" 

    api: 
        ...
        expose:
          - "81"
```

nginx.conf
```
worker_processes 1;

events { worker_connections 1024; }

http {

    sendfile on;
  
    server {
        listen 80;

        location /graphql {
            proxy_pass         http://api:81; 

            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }

        location / {
            proxy_pass         http://client:82;

            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
    }
}
```
