### ISSUE TITLE
Http/2 Server Push for App/Common Bundles

### ISSUE THREAD

**Issue by fabb** [zeit/next.js#6163]
I only found [this old and seemingly outdated information](https://github.com/zeit/next.js/issues/2961#issuecomment-330156292) about http/2 server push support in next.js.

For our production next.js app, neither `_app.js` nor `commons.*.js` are loaded via http/2 server push. I checked using the Chrome 71 Network tab in column "Initiator".

Could server push of these resources bring performance improvements for the load time of a next.js app? How would it be possible to activate it, if at all?

**Comment by timneutkens** [comment]
Please follow the issue template when creating issues.

**Comment by timneutkens** [comment]
👍 sgtm!

**Comment by JonatanSalas** [comment]
@fabb you can use the following lib:
- [Next Preload Headers](https://github.com/Enalmada/next-preload-headers)

This lib needs for you to set up a custom server with express.

**Comment by fabb** [comment]
Thank you. Any idea why next.js does not put preload links to the header by default?

**Comment by Enalmada** [comment]
@fabb +1.  My "Next Preload Headers" module sometimes causes a "can't add headers to already sent response" message which I believe is harmless but could be an indication that next.js would be the best place to put preload links into the header.
