### ISSUE TITLE
next": "8.0.0-canary.17 acorn workaround does not work

### ISSUE THREAD

**Issue by steida** [zeit/next.js#6167]
```
error  in ./node_modules/next/dist/client/next-dev.js

Module parse failed: Unexpected token (34:6)
You may need an appropriate loader to handle this file type.
|
|
> import('./noop');
| var _window = window,
|     assetPrefix = _window.__NEXT_DATA__.assetPrefix;

 @ multi ./node_modules/next/dist/client/next-dev
```

But if I add "acorn": "^6.0.5" to dependencies, it works.

**Comment by steida** [comment]
I am not sure how to fix it. Leaving it here as a workaround.

**Comment by dav-is** [comment]
@steida I don't think this is an issue we can fix on our end. We tried adding `"acorn": "^6.0.5"` to `next`'s dependencies (https://github.com/zeit/next.js/pull/6137), but it doesn't seem to be making a difference.

Solutions:
https://github.com/webpack/webpack/issues/8656#issuecomment-456713191
NPM PR that fixes this issue:
https://github.com/npm/cli/pull/147
