### ISSUE TITLE
Execute getInitialProps from wrapper component

### ISSUE THREAD

**Issue by canotech** [zeit/next.js#6169]
# Execute getInitialProps from wrapper component

Hi I have a two components , a component wrapper and a  wrapped Component ,thw wrapped Component   ultimate it´s a Page of NextJS, So when  I recharge or change of page middly  with Router.push, the method getInitialProps of my wrapped component (nextjs page) it`s not execute, but if I write Component.getInitalProps() before return my <Component /> thats method is called correctly, I need what getInitialProps call in order correctly for what render component show data corresponding, but I can not do it. below that my code

```
import { connect } from 'react-redux'
import { Row, Col } from 'reactstrap'
import LoginForm from './loginForm'


function mapStateToProps(state) {
  return state.security
}

const LoginFormStyle = () => {
  return  (
    <div className="landingPage">
      <Row className="form-login">
        <Col sm={12} md={8} lg={4}>
          <LoginForm />
        </Col>
        <Col/>
      </Row>
    </div>
  )
}
const secureComponent = (options, Component) => connect(mapStateToProps, {})(props => {
  
  const Redirect = options.unauthenticatedComponent ? Component :  LoginFormStyle

  if (props.authenticated)
    return <Component />
  return <Redirect />
})
```

export const authenticated = options => Component => secureComponent(options, Component)

**Comment by timneutkens** [comment]
Please follow the issue template and ask questions on https://spectrum.chat/next-js, the Next.js community is there so your question is more likely to be answered.

I guess this example will help: https://github.com/zeit/next.js/tree/canary/examples/with-higher-order-component
