### ISSUE TITLE
Getting 500 error on my Now deployment (No errors during build)

### ISSUE THREAD

**Issue by leongaban** [zeit/next.js#6174]
# Bug report

I looked at all the other 500 error issues but none helped.

## 500 on deployment url

I deployed my project: https://github.com/leongaban/Async-Preloader here: https://preloaderbutton-ds3k9i10x.now.sh/ However I'm getting a 500 error.

My app runs fine locally, and during the build there were no errors and got

> Success! Deployment read

## To Reproduce

1. Clone repo: https://github.com/leongaban/Async-Preloader
2. run `npm install`
3. run `now`
4. click on deployment url (note error)
5. run `npm run dev`
6. preview in Chrome: http://localhost:3000/
7. App works fine locally

## Expected behavior
The deployment URL should look like my app running locally

## System information
 - OS: MAC 10.14.2
 - Latest Safari
 - `"next": "^7.0.2",`

## package.json

    {
      "scripts": {
        "dev": "next",
        "build": "next build",
        "start": "next start"
      },
      "dependencies": {
        "@zeit/next-sass": "^1.0.1",
        "next": "^7.0.2",
        "node-sass": "^4.11.0",
        "react": "^16.7.0",
        "react-dom": "^16.7.0",
        "react-redux": "^6.0.0",
        "redux": "^4.0.1",
        "redux-devtools-extension": "^2.13.7",
        "redux-thunk": "^2.3.0"
      },
      "devDependencies": {
        "babel-plugin-sass-vars": "^0.2.1",
        "babel-plugin-styled-components": "^1.10.0"
      }
    }

### next.config.js

    const { PHASE_PRODUCTION_SERVER } =
      process.env.NODE_ENV === 'development'
        ? {}
        : !process.env.NOW_REGION
          ? require('next/constants')
          : require('next-server/constants');

    module.exports = (phase, { defaultConfig }) => {
      if (phase === PHASE_PRODUCTION_SERVER) {
        // Config used to run in production.
        return {};
      }

      // ✅ Put the require call here.
      const withCSS = require('@zeit/next-sass');

      return withCSS();
    };

now.json

    {
      "version": 2,
      "alias": "preLoader",
      "builds": [
        { "src": "package.json", "use": "@now/next" }
      ]
    }

![screen shot 2019-01-29 at 4 36 40 pm](https://user-images.githubusercontent.com/191636/51945893-91ac9380-23e5-11e9-9c35-7ca9890966f0.png)

![screen shot 2019-01-29 at 4 15 46 pm](https://user-images.githubusercontent.com/191636/51945897-95d8b100-23e5-11e9-9648-c709528a3b69.png)

**Comment by leongaban** [comment]
Update I found some errors:

```
preparing lambda files...
01/29 05:13 PM (4m)
Error: No serverless pages were built. https://err.sh/zeit/now-builders/now-next-no-serverless-pages-built
    at Object.exports.build (/tmp/utils/build-module/node_modules/@now/next/index.js:285:13)
    at <anonymous>
01/29 05:13 PM (4m)
patching https://api-sfo1.zeit.co/v2/now/deployments/dpl_9EZHL8uZwswbi9iRjH7fCLzPcEAS/builds/bld_4jdkfpuj4 with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
```

**Comment by leongaban** [comment]
Found this link: https://github.com/zeit/now-builders/blob/master/errors/now-next-no-serverless-pages-built.md

I followed all their steps, but still run into the build error.

In my package.json
`"next": "^8.0.0-canary.17",`

Updated next.config
```
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW_REGION
      ? require('next/constants')
      : require('next-server/constants');

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production.
    return {
      target: 'serverless'
    };
  }

  // ✅ Put the require call here.
  const withCSS = require('@zeit/next-sass');

  return withCSS();
};
```

now.json
```
{
  "version": 2,
  "alias": "preLoader",
  "builds": [
    { "src": "package.json", "use": "@now/next" }
  ]
}
```

**Comment by timneutkens** [comment]
```
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW_REGION
      ? require('next/constants')
      : require('next-server/constants');

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production.
    return {
      target: 'serverless'
    };
  }

  // ✅ Put the require call here.
  const withCSS = require('@zeit/next-sass');

  return withCSS({
    target: 'serverless'
  });
};
```

**Comment by leongaban** [comment]
Thanks! Hmm but now no 500 error, but my deployment isn't showing my app... 

it's showing the build logs?

https://zeit.co/leongaban/preloaderbutton/deployment/w572zwelg

![screen shot 2019-01-29 at 5 33 22 pm](https://user-images.githubusercontent.com/191636/51947912-18646f00-23ec-11e9-9691-48484924b45c.png)

I see my console.logs at the end
```
01/29 05:31 PM (3m)
patching https://api-sfo1.zeit.co/v2/now/deployments/dpl_2wWP7QB7i38x6u9YNTD5ZwB4cZvw/builds/bld_gbpwdgnb3 with {"readyState":"DEPLOYING"}
01/29 05:31 PM (3m)
finished
01/29 05:31 PM (2m)
preloaders []
01/29 05:31 PM (2m)
loaders []
01/29 05:31 PM (2m)
REPORT RequestId: 16e1fbf9-e23f-4803-ad26-4a0694a368c8	Duration: 38.86 ms	Billed Duration: 100 ms 	Memory Size: 3008 MB	Max Memory Used: 29 MB	
```

**Comment by leongaban** [comment]
Oh it's working now, thanks! https://preloaderbutton-ix57e41xo.now.sh/
