### ISSUE TITLE
client side navigation using 'next/link' not working

### ISSUE THREAD

**Issue by tofaelahmed-dsi** [zeit/next.js#618]
My project structure is following :

```
components/
  signupform.js
  loginform.js
  requestform.js
  header.js
pages/
  index.js
  login.js
  registration.js
  request.js
```
In each page I am importing header.js and respective components for that page.

Code inside header.js is following :

```
import Link from 'next/link'

export default () => (
    <div>
        <Link href='/' >
            <a>Send Request</a>
        </Link>

        <Link href='/registration'>
            <a>Registration</a>
        </Link>

        <Link href='/login'>
            <a>Login</a>
        </Link>
    </div>
)

```

Now If I try to navigate clicking on the links the above code produces following error in my console :

```
router.js?f8a4861:348 TypeError: (0 , _inherits3.default) is not a function
    at eval (eval at evalScript (eval-script.js?35d7c7b:22), <anonymous>:82:29)
    at Object.eval (eval at evalScript (eval-script.js?35d7c7b:22), <anonymous>:138:3)
    at Object.491 (eval at evalScript (eval-script.js?35d7c7b:22), <anonymous>:169:31)
    at __webpack_require__ (bootstrap 29e1caa…?8749c36:585)
    at fn (bootstrap 29e1caa…?8749c36:109)
    at Object.0 (eval at evalScript (eval-script.js?35d7c7b:22), <anonymous>:8:19)
    at __webpack_require__ (bootstrap 29e1caa…?8749c36:585)
    at webpackJsonpCallback (bootstrap 29e1caa…?8749c36:21)
    at eval (eval at evalScript (eval-script.js?35d7c7b:22), <anonymous>:2:1)
    at evalScript (eval-script.js?35d7c7b:22)
```
If I import `next/prefetch` instead of `next/link` it works perectly. But I dont want ot prefetch always. Can you please tell me If I am using `link` incorrectly ?

Thanks

**Comment by nkzawa** [comment]
@tofaelahmed-dsi what version of next.js do you user ?

**Comment by tofaelahmed-dsi** [comment]
@nkzawa I am using version 2.0.0-beta.2

**Comment by nkzawa** [comment]
@tofaelahmed-dsi can you test with the latest beta (2.0.0-beta.12) ?

**Comment by tofaelahmed-dsi** [comment]
@nkzawa I just tested with 2.0.0-beta.12

Getting following error when I click on a router :

```
Uncaught TypeError: Cannot read property 'default' of undefined
    at router.js?ec4fae6:612
    at XMLHttpRequest.xhr.onload (router.js?ec4fae6:629)
```

**Comment by bestwestern** [comment]
Could you please post content of registration.js?

**Comment by tofaelahmed-dsi** [comment]
@bestwestern 

```
import React from 'react'
import Router from 'next/router'
import 'whatwg-fetch';

import Signupform from '../components/signupform'
import Header from '../components/header'

export default class extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            name:'',
            user_name:'',
            email:'',
            password:'',
            phone:'',
            account_type: 'consumer'
        };
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    handleChange(field, e) {
        this.setState({[field]: e.target.value});
    }

    handleSubmit(e){
        e.preventDefault();
    }

    render () {
        return  <div>
            <Header/>
            <Signupform
                handleChange={this.handleChange.bind(this)}
                handleSubmit={this.handleSubmit.bind(this)}
            />
        </div>

    }


}

```

**Comment by bestwestern** [comment]
Try replacing it with:
import React from 'react'
export default () => <div>Hello world!</div>
And try again

**Comment by bestwestern** [comment]
Try replacing with:
[helwo.txt](https://github.com/zeit/next.js/files/680642/helwo.txt)

**Comment by nkzawa** [comment]
@tofaelahmed-dsi I can't reproduce this issue. The error (`Uncaught TypeError: Cannot read property 'default' of undefined`) looks like an imported module has no `export`. Can you check your code again or can you provide a repository which we can reproduce ?

**Comment by tofaelahmed-dsi** [comment]
@nkzawa If I use 1.2.x version of next it works perfectly. But I dont get `next/router` in that case. Is there any way of doing imperative routing without using `next/router`.

It will be another way of solving my problem. Thats why I am asking.Thanks

**Comment by nkzawa** [comment]
@tofaelahmed-dsi It looks like a bug. There is no other way. I'd like to know how to reproduce. Is it possible to know the repository ?

**Comment by tofaelahmed-dsi** [comment]
@nkzawa here is the repository link [https://github.com/tofaelahmed-dsi/next-react](url)

**Comment by nkzawa** [comment]
@tofaelahmed-dsi Thanks, but I don't get any errors. I just clicked header navigations.

**Comment by arunoda** [comment]
@tofaelahmed-dsi it works for me as well.
