### ISSUE TITLE
Problems with dynamic urls

### ISSUE THREAD

**Issue by Javier1177** [zeit/next.js#6191]
Hello, I'm working on a project that uses a lot of different languages. So I need to change the language url. Example:

www.example.com/es/entradas
www.example.com/en/tickets
www.example.com/de/eintrittskarten

There are a lot of url and I'm working with a CMS, so my clients will be able to add more, so it can't be hardcoded. To make these routes I found next-routes (https://github.com/fridays/next-routes), but in case you know a different way to fix my problem, I'll listen to you.
I thought to pass the url with queries, like this:

const routes = require('next-routes');

module.exports = routes()
  .add('index', '/:lang?')
  .add('tickets', '/:lang?/:ticket')
  .add('hotel', '/:lang?/:hotel');
My surprise (as you might see), it doesn't work because routes doesn't see the difference between these two last routes. If I write:

www.example.com/en/tickets

It will go correctly to my page ### tickets but if I write

www.example.com/en/hotel

It will go again to my page ### tickets and not to ### hotel

Do you know any way about how could I make this?

**Comment by timneutkens** [comment]
This is how the router works:
https://github.com/zeit/next.js/issues/5885

In this case it seems you're trying to do 2 pattern matches that are equivalent so only one is used (tickets/hotel) You'll need some extra custom server logic - or use getInitialProps to distinguish and render a different layout based on the incoming page.

**Comment by timneutkens** [comment]
I'm going to close this issue as per the issue template questions should be posted on https://spectrum.chat/next-js 🙏
