### ISSUE TITLE
'npm run dev' fails silently using node version 10 after initial install, MacOSX, Mojave

### ISSUE THREAD

**Issue by 2hands10fingers** [zeit/next.js#6199]
# Bug report

## Describe the bug

'npm run dev' fails silently using node version 10 doing the initial setup on the next.js website.

Terminal produces:
```
> port-proj@1.0.0 dev /Users/antonionogueras/port-proj
> next

Compiling

● client

● server █████████████████████████ compiling (0%)  
✔ success server compiled in 202ms
```

No listening occurs.

## To Reproduce

mkdir hello-next
cd hello-next
npm init -y
npm install --save react react-dom next
mkdir pages
npm run dev

## Expected behavior

Hot reload, server running

## System information
 - OS: macOSX, Mojave
 - Browser: Chrome
 - Version of Next.js: 7.0.2

## Additional context

This worked fine on my Windows 10 machine

**Comment by timneutkens** [comment]
I think this was solved 🤔 If not try installing `next@canary` and trying again, if it still hangs we'd be happy to take a look!

**Comment by 2hands10fingers** [comment]
@timneutkens Hey there! So, I got it working with a blank project, but then I have issues with a pre-existing project. 

I get 
```
{ [Error: EACCES: permission denied, mkdir '/Users/my-directory/next-js-prac/node_modules/.cache']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/my-directory/next-js-prac/node_modules/.cache' }```

This is my project. I did `sudo npm run dev` and it worked. Just posting this for anyone who is having trouble like I was. 

Thanks!
