### ISSUE TITLE
Custom routing using Firebase Functions

### ISSUE THREAD

**Issue by jskidd3** [zeit/next.js#6202]
# Question about Next.js

How would one replicate custom routing as shown [here](https://nextjs.org/learn/basics/server-side-support-for-clean-urls/create-our-custom-route) when using Firebase Functions for SSR?

I have tried the code below but to no available (/track/123 returns 404).

Thanks in advance!

@jthegedus if you are able to help with this I'd be very grateful.

```
const functions = require('firebase-functions')
const next = require('next')

const dir = __dirname
var app = next({ dir, conf: { distDir: 'next' } })
var handle = app.getRequestHandler()

exports.next = functions.https.onRequest((req, res) => {
  console.log('File: ' + req.originalUrl) // log the page.js file that is being requested

  req.get('/track/:id', (req, res) => {
    const actualPage = '/track'
    const queryParams = { title: req.params.id } 
    app.render(req, res, actualPage, queryParams)
  })

  return app.prepare().then(() => handle(req, res))
})
```

**Comment by jthegedus** [comment]
Hi @jskidd3, I can take a look over the coming weekend. If you solve it in the meantime, let me know!

**Comment by jskidd3** [comment]
@jthegedus Thank you! I've spent most of the day trying to find a way - will keep going tomorrow. I can't help but feel it's going to be something stupidly simple. It's literally just so that I can make the `track.js` page return instead of 404 when requesting a subdirectory after (e.g. an ID).

Will keep you posted!
