### ISSUE TITLE
assetPrefix ignored by stylesheet when import from pages/index.js

### ISSUE THREAD

**Issue by rashidul0405** [zeit/next.js#6208]
# Examples bug report
This bug may be related to next-sass plugin

## Example name
[with-next-sass](https://github.com/zeit/next.js/tree/canary/examples/with-next-sass)

## Describe the bug
assetPrefix doesn't apply for stylesheets (same as https://github.com/zeit/next.js/issues/3967)
when import from `index.js` or `_app.js`, assetPrefix doesn't apply.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. set `assetPrefix` for `with-next-sass` example  and build
```
module.exports = withSass({
  assetPrefix: "assetPrefix"
})

**Comment by axsann** [comment]
Set config.output.publicPath.
```
module.exports = withSass({
  assetPrefix: '_foo',
  webpack: (config) => {
    config.output.publicPath = `/_foo/_next/`;
});
```
