### ISSUE TITLE
Running examples on windows w/o curl

### ISSUE THREAD

**Issue by bestwestern** [zeit/next.js#621]
The readme in many examples says:
curl https://codeload.github.com/zeit/next.js/tar.gz/master | tar -xz --strip=2 next.js-master/examples/ssr-caching

Anyone know how to do this on a simple Windows machine?

**Comment by DarkAdmiral** [comment]
install cygwin https://www.cygwin.com/ and add the bin folder to your System Variables. Then you can use curl right from your command line.

Without curl you could just download the entire repo as zip file.

**Comment by sedubois** [comment]
You could try out the new [Windows Bash](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)?

**Comment by impronunciable** [comment]
You can also just clone the repo and navigate to the folder. Closing for now, feel free to reopen.
