### ISSUE TITLE
gridTemplateAreas syntax error

### ISSUE THREAD

**Issue by anlexN** [zeit/next.js#6215]
## Expected Behavior 🤔
grid layout css is suppoted

## Current Behavior 😯
![image](https://user-images.githubusercontent.com/8686739/52177724-69b39a80-2800-11e9-98cb-3a9838b00c15.png)

## System information
 - OS: [e.g. macOS, Windows] windows
 - Browser (if applies) [e.g. chrome, safari] all
 - Version of Next.js: [e.g. 6.0.2] latest

**Comment by timneutkens** [comment]
This doesn't seem related to Next.js 🤔
