### ISSUE TITLE
serverless set only in Now 2 environment

### ISSUE THREAD

**Issue by steida** [zeit/next.js#6219]
What is the supposed way to set next.config.js serverless key only in Now 2 environment?

**Comment by timneutkens** [comment]
What do you mean exactly?

**Comment by steida** [comment]
I need next build both for local dev and for deploy.
This is what I used: https://github.com/este/este/blob/master/packages/web/next.config.js#L27

Locally, serverless does not work when I need to test app before deploy.

Switching it manually is not ideal.

**Comment by steida** [comment]
This once worked but does not work anymore.

```
const { BUNDLE_ANALYZE, NOW_REGION } = process.env;

module.exports = withCustomBabelConfig(
  withBundleAnalyzer(
    withTypescript(
      withTranspileModules({
        // TODO: Use serverless target only within Now. But how?
        ...(NOW_REGION ? { target: 'serverless' } : null),
        transpileModules: ['@este'],
      }),
    ),
  ),
);
```

**Comment by Timer** [comment]
We automatically set this target for you when deploying to Now, so you can just omit this entirely. 🙏

**Comment by Timer** [comment]
Also, you can now use `next start` with a serverless build!
