### ISSUE TITLE
Site Navigation Is Unusable

### ISSUE THREAD

**Issue by MaxwellGover** [zeit/next.js#6223]
I'm trying to navigate your site using the side nav. I click on a section the first time and nothing happens. I'm not scrolled anywhere. The second time a click it it scrolls a little bit but never to the right section. 

![n8mzuzbrvb](https://user-images.githubusercontent.com/11525891/52448877-4db34000-2b03-11e9-8e20-5256099922c3.gif)

**Comment by c0b41** [comment]
Duplicate https://github.com/zeit/next-site/issues/132

**Comment by timneutkens** [comment]
Solved in zeit/next-site#132
