### ISSUE TITLE
Speed up initial load times by adding support for Incremental Rendering

### ISSUE THREAD

**Issue by fabb** [zeit/next.js#6227]
# Feature request

## Is your feature request related to a problem? Please describe.
Initial load time could be improved even more by utilizing an Incremental Rendering technique. 

## Describe the solution you'd like
As described in the [blog post of the new SSR framework „Velocirender“](
https://www.bitovi.com/blog/announcing-velocirende), incremental rendering could more quickly deliver a non-interactive SSR page to make the perceived browser render time faster, and load interactive parts in a followup request and following DOM mutations. 

## Describe alternatives you've considered
Other unrelated techniques like aggressive caching, serverless, async scripts, improve code splitting by using styled components, etc.

## Additional context
None yet.

**Comment by timneutkens** [comment]
I'm confused by what you're asking for in this issue that Next.js doesn't provide. The link is a 404.

**Comment by fabb** [comment]
Sorry for the broken link, fixed it: 
https://www.bitovi.com/blog/announcing-velocirender
