### ISSUE TITLE
Outside pages folder can't fetch data

### ISSUE THREAD

**Issue by Chathula** [zeit/next.js#623]
i tried to fetch data outside pages folder. but i couldn't. why is that? is there any solution for this? i tried both axios and isomorphic-fetch

Directory Structure

```
components
-- App.js
-- Users.js
pages
-- index.js
```

**Comment by nkzawa** [comment]
What exactly did you try to do ? Can you post your code here or let us know your repository.

**Comment by Chathula** [comment]
```javascript
// pages/index.js

import React, { Component } from 'react'
import App from './_components/App'

export default class Home extends Component {

  render () {
    return (
      <div>
        <h1>Welcome to Next.js</h1>
        <App />
      </div>
    )
  }

}

```

```javascript
// components/App.js

import React, { Component } from 'react';
import Users from './Users'

export default class App extends Component {
  render () {
    return (
      <div>
        <p>This is App Component</p>
        <Users />
      </div>
    )
  }
}
```

``` javascript
// components/User.js

import React, { Component } from 'react'
import 'isomorphic-fetch'

export default class Users extends Component {

   static async getInitialProps () {
     const res = await fetch('https://api.github.com/repos/zeit/next.js')
     const json = await res.json()
     return { stars: json.stargazers_count }
  }

  render () {
    return (
      <div>
        <h3>Users List</h3>
        <p>Next.js has {this.props.stars} ⭐️</p>
      </div>
    )
  }
}
```

**Comment by Chathula** [comment]
first i tried to fetch my own API, it didn't work. so i tried example on in next.js

**Comment by nkzawa** [comment]
@Chathula `getInitialProps` has to be defined on files of `pages`. Move it to `pages/index.js` and pass the retrieved data to `components/User.js` as a prop.

**Comment by Chathula** [comment]
it worked, but why i can't do outside fetching? is there any way to implement it by changing webpack config

**Comment by arunoda** [comment]
@Chathula what do you mean by "outside fetching". May be you could provide us a sample repo. So, we could try to see what we can do about this.

**Comment by Chathula** [comment]
@arunoda i figured out i can't import component with fetched data! i have to fetch data when i am on that route path.i can't import component with fetched data. (i don't have a clear idea is this a next.js issue or react issue. i have to give a try for it)

i will put a repo later, i have already put my codes here!

**Comment by iamjacks** [comment]
@Chathula It's usually 'best practice' to handle data fetching in some parent/container component and pass the data to child/presentational components via props. [This article](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.gbksrlo3v) helped me understand it, when I began learning React and Redux.

**Comment by arunoda** [comment]
I hope we could close this issue since it's not 100% related to Next.js 

If so, reopen with more info.
