### ISSUE TITLE
jest error importing .css using next/babel

### ISSUE THREAD

**Issue by eldyvoon** [zeit/next.js#6241]
I got error of SyntaxError: Unexpected token . when trying to run jest.
in my implementation code
```
import 'react-dates/lib/css/_datepicker.css'
import 'semantic-ui-css/semantic.min.css'
```
those isn't in my spec.js but my implementation code, any clue why? I have no problem running my app but jest throw error when I try to run test.

**Comment by kinetifex** [comment]
See: https://jestjs.io/docs/en/webpack#handling-static-assets
