### ISSUE TITLE
parameterized-routing example does not deploy with now

### ISSUE THREAD

**Issue by johnpolacek** [zeit/next.js#6245]
# Examples bug report

## Example name
`parameterized-routing`

## Describe the bug
Deploying the parameterized-examples results in a directory listing rather than the example. See [https://parameterized-routing-app-50jj5mf6h.now.sh/](https://parameterized-routing-app-50jj5mf6h.now.sh/)

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:

(Assume now cli installed)
~~~~
npx create-next-app --example parameterized-routing parameterized-routing-app
cd parameterized-routing
npm install
now deploy
~~~~

## Expected behavior
When deploying you should see the blog post listings and be able to navigate to them.

**Comment by timneutkens** [comment]
This is expected because of serverless vs custom server, however I think we can add a link to the guide / example in now-examples for this 👍
