### ISSUE TITLE
v8 server build error

### ISSUE THREAD

**Issue by herrstucki** [zeit/next.js#6246]
# Bug report

With next.js 8, I get this unhelpful message and a 404 error on a page of my app:

```
✖ Server
  Compiled with some errors in 5.02s
```

When running a production build the error is more detailed and it seems that for the **server build**, next.js can't resolve a dependency's entrypoint if the `main` property is missing from package.json but the `module` property is specified.

The culprit seems to be this line:

https://github.com/zeit/next.js/blob/80cb91ec87f6d193899c19faaa89f3cddd87da85/packages/next/build/webpack-config.js#L192

## To Reproduce

One example of a package which defines `module` but not `main`: https://github.com/wereHamster/valde/blob/master/packages/iconography/package.json

## Expected behavior

In next.js 7 this worked, and I presume that using `module` as a main field in addition to `main` would also work in next.js 8, since the server part is also compiled with webpack.

## System information
 - OS: macOS 10.14.3
 - Version of Next.js: 8.0.0

**Comment by timneutkens** [comment]
I guess it's fine to add `module` as fallback, however I'm not sure if this will cause any weird side-effects on other modules.

**Comment by herrstucki** [comment]
@timneutkens Note that in v7 this worked with webpack's default setting which is `["module", "main"]` for the `node` target: https://webpack.js.org/configuration/resolve/#resolve-mainfields

**Comment by herrstucki** [comment]
So I'd say what caused the weird side-effect for me was rather removing "module" from the mainFields config in v8 😉

**Comment by timneutkens** [comment]
> So I'd say what caused the weird side-effect for me was rather removing "module" from the mainFields config in v8 😉

That's not really correct though, once you start compiling node_modules (like in the serverless target) you'd run into a *ton* of issues related to `module`, we saw this in `ncc`, so the order should be `main`, `module`.

**Comment by herrstucki** [comment]
@Timer @timneutkens thanks for fixing this, much appreciated! 🙇
