### ISSUE TITLE
Static export failed when upgraded to v8.0.0

### ISSUE THREAD

**Issue by YuriGor** [zeit/next.js#6251]
# 8.0.0(npm) Bug report

## Describe the bug

next app stopped to work on client side after upgrading next to v8.0.0
Coming back to v7.0.3 makes things work.

Here is a [broken version with 8.0.0](https://deepdashio-g8bnfrflm.now.sh/)
Here is a [working version with 7.0.3](https://deepdashio-r1kgpj3fg.now.sh/)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. this is [fixed commit](https://github.com/YuriGor/deepdash.io/commit/8f0e1233229aaf16b39e332b84101106427e903e)
it works well by `npm run dev`
2. do `npm i next@8.0.0` and run an app
3. menu button and smooth scrolling after side bar clicks do not work.
4.  In browser console you will see `Uncaught TypeError: Cannot read property 'textContent' of null`

## Expected behavior
No errors in console, all the buttons work, scrolling is smooth

## Screenshots
Full error:
```
Uncaught TypeError: Cannot read property 'textContent' of null
    at Object../node_modules/next/dist/client/index.js (index.js:66)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Object../node_modules/next/dist/client/next-dev.js (next-dev.js:23)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Object.0 (module.js:22)
    at __webpack_require__ (bootstrap:788)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
```

## System information
 - OS: Kubuntu 18.04
 - Browser: chromium
 - Version of Next.js: 8.0.0 from npm

## Additional context

CLI command 
`now init` creates nextjs-static example with optimistic package.json:
```json
{
  "scripts": {
    "now-build": "next build && next export -o dist"
  },
  "dependencies": {
    "next": "latest",
    "react": "latest",
    "react-dom": "latest"
  }
}
```
so it was surprise for me to become a tester of pre-release

**Comment by dav-is** [comment]
The issue is `@engineerapart/nextscript` doesn't support Next 8
https://github.com/engineerapart/nextscript

**Comment by YuriGor** [comment]
@dav-is Thank you for reply. 
Could you please recommend some 'official' way to include some polyfill into nextjs app?
In my case it's static app and I need [closest](https://caniuse.com/#feat=element-closest) selector.
That solution was fine for next 7, but now I see no signs of life in the project, so chances are low v8 will be supported in the nearest future..
May be I missed some docs about topic?

**Comment by timneutkens** [comment]
This should do 🤔 https://github.com/zeit/next.js/tree/canary/examples/with-polyfills
