### ISSUE TITLE
useFileSystemPublicRoutes is false but file based routing still work in next@8.0.0

### ISSUE THREAD

**Issue by BahmanBinary** [zeit/next.js#6254]
# Bug report

File based routing still can't be disabled in next@8.0.0

## Describe the bug

I updated next to 8.0.0 and set `useFileSystemPublicRoutes: false` in next.config.js
I was hoping that this problem solved in this version but still this option doesn't work.
is there any way for solving this annoying problem.
Help please!

## Expected behavior
File system routing be disabled.

## System information
 - OS: [Windows]
 - Browser (if applies) [chrome]
 - Version of Next.js: [8.0.0]

**Comment by BahmanBinary** [comment]
I read other similar issues but didn't find right solution for this problem.

**Comment by timneutkens** [comment]
Please provide a reproduction when creating issues. It's hard to help otherwise, we have tests for `useFileSystemPublicRoutes: false`.

**Comment by BahmanBinary** [comment]
> Please provide a reproduction when creating issues. It's hard to help otherwise, we have tests for `useFileSystemPublicRoutes: false`.

I have a file route: `/products/product`
and a custom route: `/products/:id` that render previous file route(`/products/product`).

1. go to next.config.js and set `useFileSystemPublicRoutes: false`
2. go to `/products/product` and browser shows this page

**Comment by timneutkens** [comment]
This is expected, we can't disable javascript bundles from being served.
