### ISSUE TITLE
Failed to compile after upgrading from 7 to 8

### ISSUE THREAD

**Issue by soffes** [zeit/next.js#6259]
# Bug report

```
ERROR  Failed to compile with 1 errors

 error  in ./node_modules/next/dist/client/next-dev.js

Module parse failed: Unexpected token (34:6)
You may need an appropriate loader to handle this file type.
| 
| 
> import('./noop');
| var _window = window,
|     assetPrefix = _window.__NEXT_DATA__.assetPrefix;

 @ multi ./node_modules/next/dist/client/next-dev
```

## Describe the bug

Upgraded from 7 to 8 and now seeing this error. I don't really understand what the issue is or what I should do to fix it.

## To Reproduce

```shell
$ git clone https://github.com/soffes/soff.es && cd soff.es
$ git checkout next-8
$ npm i && npm run dev
```

## Expected behavior

It starts the development server.

## System information

- macOS 10.14.3 (18D109)
- node 11.9.0
- next 8.0.0

**Comment by lednhatkhanh** [comment]
same problem here with nextjs 8

**Comment by dav-is** [comment]
@soffes Sorry I didn't recognize the bug from your tweet :man_facepalming: 

It's a known issue with `npm` and a newer version of `webpack`.
https://github.com/zeit/next.js/issues/6167#issuecomment-458331181

**Comment by soffes** [comment]
The steps in that comment didn't work for me. I just removed webpack altogether and it started working.

**Comment by timneutkens** [comment]
> I just removed webpack altogether and it started working.

Did you have it in your `dependencies` or `devDependencies`, if so, why'd you add it? I'm really curious about that because I've seen users do that before and I'm still not sure why and it's potentially breaking in many ways 😬.

**Comment by soffes** [comment]
Here's what I did: https://github.com/soffes/soff.es/commit/607a94237fd27f1d1354aa74ade3eef347414395

**Comment by blaiprat** [comment]
Had the same issue, in my case solved it by deleting `node_modules` and `package-lock.json` and installing everything again

**Comment by saltycrane** [comment]
For me, the solution was to remove `@zeit/next-bundle-analyzer` from my project. For reference, I created https://github.com/zeit/next.js/issues/6361

**Comment by jtomaszewski** [comment]
Solution: https://github.com/webpack/webpack/issues/8656#issuecomment-456713191
