### ISSUE TITLE
Hot reload doesn't work on Node 8, but does work on Node 10 (macOS 10.14.3 related?)

### ISSUE THREAD

**Issue by jedwards1211** [zeit/next.js#6261]
# Bug report

## Describe the bug

I noticed Next.js was no longer hot reloading for me.  I had switched from using Node 10 to Node 8 when I read that Now currently uses the latest Node 8 in the cloud.  After switching back and forth between Node 8 and Node 10, I determined that hot reloading works in Node 10 but not Node 8.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
0. Use a system with macOS Mojave 10.14.3?
1. `nvm install 8.15.0`
2. `git clone https://github.com/jedwards1211/breakout.git`
3. `cd breakout/docs`
4. `yarn dev`
5. Save change to `pages/index.js` -- **Next.js doesn't rebuild; no status in console or updates in browser**
6. Ctrl-C
7. `nvm install 10.15.0`
8. `yarn dev`
9. Save `pages/index.js` -- **Next.js rebuilds, browser hot reloads**

## Expected behavior
Hot reloading works in Node 8, since that's the version Now currently uses in the cloud...

## System information
 - OS: macOS 10.14.3
 - Browser (if applies) N/A
 - Version of Next.js: 8.0.0, 8.0.0-canary.21 (same issue with both)

**Comment by timneutkens** [comment]
Our tests run in Node.js 8 (https://github.com/zeit/next.js/blob/canary/.circleci/config.yml#L5), so I doubt that's the issue. But I'll have a look into what's going on here.

**Comment by Timer** [comment]
I just attempted this and couldn't reproduce it.
Could you please provide more concrete instructions? Would be happy to reopen this issue if you do so.

This wasn't necessary for me, but can you try deleting `node_modules` and re-running `yarn` after switching your Node version?

**Comment by dextermb** [comment]
This may be down to `fs.inotify.max_user_watches`. Are you watching other files as well as just the next script?

Could you have a go at increasing `fs.inotify.max_user_watches`?

**Comment by jedwards1211** [comment]
@timneutkens I thought file watching is too prone to OS-specific quirks for CI tests running in a docker container to be relevant here...did you guys try reproducing on macOS Mojave 10.14.3?  

@Timer I tried blowing away `node_modules` and `yarn.lock` and reinstalling with Node 8, but it didn't help.

@dextermb I think you didn't notice that I'm on macOS.  As far as I can tell `fs.inotify.max_user_watches` is only for Linux.  Some sites suggest `sudo sysctl -w kern.maxfiles=...` for macOS, but I'm not sure if it actually applies to file watching and it didn't help.

**Comment by jedwards1211** [comment]
@Timer I'm not sure what else to add to the repro instructions, did you have anything in mind?
The fact that GitHub markdown didn't indent `0. Use a system with macOS Mojave 10.14.3?` as part of the list may have caused you guys to miss it though, so I made the list start with 1.

**Comment by jedwards1211** [comment]
@Timer okay, I thought of some things and updated the repro steps to be more thorough.

Sadly, hot reload is no longer working for me on Node 10 either.  Maybe tweaking `kern.maxfiles` affected it, I don't know.  I'm going to try restarting.

**Comment by jedwards1211** [comment]
Now it's working on Node 8 too.  I know for a fact I had the browser open when I tried on both Node 8 and Node 10 the first time, but restarting my computer seems to have fixed Node 8.  Sigh...sorry to bother you guys

**Comment by dextermb** [comment]
> @dextermb I think you didn't notice that I'm on macOS. As far as I can tell `fs.inotify.max_user_watches` is only for Linux. Some sites suggest `sudo sysctl -w kern.maxfiles=...` for macOS, but I'm not sure if it actually applies to file watching and it didn't help.

Ah, my bad! [`ulimit`](https://ss64.com/osx/ulimit.html) is for macOS 👍
