### ISSUE TITLE
Building a specific directory is broken in 8.0.0

### ISSUE THREAD

**Issue by nwalters512** [zeit/next.js#6263]
# Bug report

## Describe the bug

`next build` is supposed to support an optional `<dir>` argument that specifies which directory will be built. In 8.0.0, that argument is ignored, and attempting to run a build with that argument specified will fail incorrectly.

## To Reproduce

Create a minimal Next.js project:
* `mkdir example && cd example`
* `npm init`, accept all defaults
* `npm install --save next react react-dom`
* `mkdir -p build/pages`
* `touch build/pages/index.js`
* Edit `build/pages/index.js` to include a minimum working page:
```jsx
function Home() {
  return <div>Welcome to next.js!</div>
}

export default Home
```

After creating this example, run `npx next build build` in the root of the `example` directory that was created. Observe the following output:

```
Couldn't find a `pages` directory. Please create one under the project root
```

## Expected behavior
In Next.js 7.0.3, running `npx next build build` with the above directory structure would build the site in `./build/.next/`. You can test this by running `npm i next@7.0.3` in the above example and then running `npx next build build`

## System information
 - OS: macOS
 - Browser: N/A
 - Version of Next.js: 8.0.0

## Additional context

I tried to do a little bit of debugging here. Adding `console.log(args)` right before https://github.com/zeit/next.js/blob/canary/packages/next/bin/next-build.ts#L29 shows that `args._` is an empty array, even with the `build` argument specified. It looks like this issue could somehow be caused by the switch to using the `arg` package, as v7.x used `minimist` instead.

**Comment by timneutkens** [comment]
I use this feature all the time to build `test/integration/<something>` in the Next.js repository though. Going to try and reproduce based on your example.

**Comment by timneutkens** [comment]
Ah it seems like this only happens when you do `next build build`, any variation like `next build ./build` or `next build someotherdir` works fine

**Comment by timneutkens** [comment]
Found the issue. Creating a PR.

**Comment by nwalters512** [comment]
Ah, suppose I should have tried some other directory names. Guess I was unlucky enough to have been using the one thing that didn't work 🙂 thanks Tim!
