### ISSUE TITLE
Cannot kill build process with Ctrl+C

### ISSUE THREAD

**Issue by sheerun** [zeit/next.js#6268]
# Bug report

In Next v7 I was able to kill build process with Ctrl+C. Now Ctrl+C exits to terminal but build process continues in background and outputs stuff to stdout

**Comment by ijjk** [comment]
@sheerun This appears to be fixed on the latest version of Next.js since we are no longer spawn a separate process. I'm going to close this, if this is still occurring after updating please leave another comment and I can look into it again.
