### ISSUE TITLE
Serverless build stuck at compilation

### ISSUE THREAD

**Issue by aswin-vb** [zeit/next.js#6269]
# Bug report

## Describe the bug

While building the app under serverless mode the compilation get stuck at `additional chunk assets processing (91%)` , whereas when the app is build without serverless mode the build is completed without any issue.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. In next.config.js file add
`module.exports = {
  target: "serverless",
};`
2. Run `yarn build`
3. Build get stuck at 91%

## Expected behavior
The build should be completed successfully

## Screenshots
![conemu64_rbebp5jnkg](https://user-images.githubusercontent.com/46859083/52632465-a6aa1c00-2ee7-11e9-8487-990496772f51.png)

## System information
 - OS: Linux
 - Version of Next.js: 8.0.0

**Comment by timneutkens** [comment]
Please provide a reproducible repository, it's impossible help without it as we can't debug your build otherwise.

**Comment by aswin-vb** [comment]
@timneutkens This was run on a basic project setup using create-next-app
