### ISSUE TITLE
asPath for Link - is it retired or never existed?

### ISSUE THREAD

**Issue by tima101** [zeit/next.js#6278]
# Bug report

## Describe the bug

Below code displays `/public/login` on the browser. But it should be `/login`.
```
  <Link
      prefetch
      href={{ pathname: '/public/login', asPath: '/login', query: { redirectUrl } }}
  >
      <a>Log in</a>
  </Link>
```

To fix it, I have to use `as`:
```
  <Link
      prefetch
      href={{ pathname: '/public/login', query: { redirectUrl } }}
      as={{ pathname: '/login', query: { redirectUrl } }}
  >
      <a>Log in</a>
  </Link>
```

Is it understood that `href` object does not have `asPath` parameter?
Was it retired or perhaps I don't use it right?
I checked type of `href` and do see `asPath` parameter.
Thanks!

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

You can start app at: https://github.com/builderbook/builderbook/tree/master/book/8-end
Edit code at: https://github.com/builderbook/builderbook/blob/c11f757ab5ece5bcdb67e392ec4b1dbe0a6f9620/book/8-end/components/Header.js#L90

## System information
 - OS: [e.g. macOS, Windows]
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [e.g. 6.0.2]

**Comment by timneutkens** [comment]
`asPath` has never been part of that object, we call `url.format` ([see API](https://nodejs.org/api/url.html#url_url_format_urlobject)). I wonder if we can do validation is development so that users won't add values to the object that don't belong there.

**Comment by tima101** [comment]
@timneutkens Thanks for clarifying! Feel free to close.

**Comment by timneutkens** [comment]
I think we can do better here though, so I'm leaving it open to improve!

**Comment by Jauny** [comment]
@timneutkens by improve are you saying it'd be good to make Link able to deal with `asPath` being part of the `href` prop?

**Comment by timneutkens** [comment]
> by improve are you saying it'd be good to make Link able to deal with `asPath` being part of the `href` prop?

That'd be a weird non-standard behavior, what I meant is in development we can throw an error that you're adding a property that is not allowed on the object, as we know all keys that are allowed (it's a standard)

**Comment by isaachinman** [comment]
@Jauny Are you picking this up? Otherwise, I will take this one.

**Comment by Jauny** [comment]
Go ahead! I dont wanna be a blocker and havent dived in the codebase yet.
Please tag me on the pr i'd love to see how you do it :)

**Comment by timneutkens** [comment]
💯

**Comment by isaachinman** [comment]
@Jauny It's not blocking as this is entirely new validation which became relevant due to a user question. There's no specific timeline - if you want to get involved this would be a great one to start with. Just let me know. In general, I'm interested in validation and type safety in this project - that's all.

**Comment by Jauny** [comment]
@isaachinman please go ahead. I'm familiar with Link, but not with next contributions best practices, and was a bit lost when trying to understand how testing and erroring worked. So I think looking at how you do this will be great for me to see! :)

**Comment by isaachinman** [comment]
@timneutkens To be clear, you mean getting typings out of `url` and performing validation against those, right?

**Comment by timneutkens** [comment]
@isaachinman correct!

**Comment by isaachinman** [comment]
@timneutkens Would you expect to see this validation just inside the link component, or would you prefer generalised `format` and `parse` functions used throughout the source that wrap the `url` methods and add validation?

**Comment by timneutkens** [comment]
@isaachinman I think a generic method might make sense, however I can't remember in how many places we do `url.format` (it's just relevant for `.format`) probably in `next/link` and `next/router` only? 🤔

**Comment by isaachinman** [comment]
@timneutkens Just checked, that's right. Good memory!

Off the top of my head, something like this would work inside `next-server/lib/utils`, and then could import from the `next` package as well:

```jsx
import { format } from 'url'

export const urlObjectKeys = ['auth', 'hash', 'host', 'hostname', 'href', 'path', 'pathname', 'port', 'protocol', 'query', 'search', 'slashes']

export function formatWithValidation(url) {

  if (typeof url !== null && typeof url === 'object') {
    Object.keys(url).forEach((key) => {
      if (!urlObjectKeys.includes(key)) {
        console.warn(`Unknown key passed via urlObject into url.format: ${key}`)
      }
    })
  }

  return format(url)

}
```

I did a search for `joi` and `validation` across the project and didn't see anything - do we have any more sophisticated tools at our disposal that I'm not aware of? The above isn't exactly satisfying.

**Comment by timneutkens** [comment]
I don't think we need something more than this.

**Comment by quantafire** [comment]
Question on this. Just updated to Next v8.

I am using the `as` prop on all my Links to clean up the URL but I'm getting this error ("Unknown key passed via urlObject into url.format: as") thrown multiple times in development on each page load. Is the `as` prop still supported in the <Link> component? Is there a new way to write it?

I'm using it just as it says to in the docs/learning site and neither client nor server ever threw anything like this before.

**Comment by timneutkens** [comment]
@quantafire could you show a reproduction? It generally means you're not setting it as a prop but as part of the `href` object, which is incorrect and would just do nothing, before it would be 100% ignored hence why we added that error because it will help you prevent issues with link.

**Comment by Jauny** [comment]
@quantafire FYI here is the [diff](https://github.com/zeit/next.js/pull/6379) @timneutkens is mentioning.

**Comment by quantafire** [comment]
@timneutkens Thank you that helped a lot, I just found the bug! It was my own error of accidentally putting both as/href into each as/href prop! Oops.

**Comment by timneutkens** [comment]
@quantafire exactly why this was introduced 😄🙏 Glad to see it's helping!
