### ISSUE TITLE
Issue deployment Next v8

### ISSUE THREAD

**Issue by Emiliano-Bucci** [zeit/next.js#6279]
# Bug report

## Describe the bug
Hi, i recently update a personal project to the last version of Next, 8.0, and i was trying to deploy using version 2; during deployment i face some issues (for example i had errors when trying to import an asset from the `/static` folder) or some WebpackWarnings `ModuleDependencyWarning: "export 'default' (imported as 'Component') was not found in` but, despite that, i manage to deploy the project. The fact is that is not working properly: if i navigate to a dynamic page, it throws a 404. Some features of the app (some interactions) do not work. 

https://emilianobucci.com/

As you can see, is pretty much an useless thing. 

Here is the log of the server 

https://zeit.co/xb7Px7VRCE1hXhcIHBf0cBBE/my-life-in-trek/deployment/e1beh69pz

This did not happen with version 7.

> {
  "name": "my-life-in-trek",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "dev": "node server.js",
    "test": "NODE_ENV=test jest --watch",
    "test:coverage": "NODE_ENV=test jest --coverage && open ./coverage/lcov-report/index.html",
    "build": "next build",
    "now-build": "next build",
    "start": "NODE_ENV=production node server.js",
    "docz:dev": "docz dev",
    "docz:build": "docz build",
    "graphql:get-schema": "apollo-codegen introspect-schema https://mylifeintrek.it/graphql --output schema.json",
    "graphql:gen-types": "apollo-codegen generate **/data.tsx --schema schema.json --target typescript --output ./src/graphql-types/index.ts"
  },
  "dependencies": {
    "@cedx/akismet": "^13.0.1",
    "@emotion/core": "^10.0.7",
    "@emotion/styled": "^10.0.7",
    "apollo": "^2.4.4",
    "apollo-cache-inmemory": "^1.4.2",
    "apollo-client": "^2.5.0-beta.1",
    "apollo-link-http": "^1.5.11",
    "auth0-lock": "^11.14.0",
    "cors": "^2.8.5",
    "express": "^4.16.4",
    "final-form": "^4.11.1",
    "graphql-tag": "^2.10.1",
    "imagemin-mozjpeg": "^8.0.0",
    "imagemin-optipng": "^6.0.0",
    "imagemin-svgo": "^7.0.0",
    "isomorphic-fetch": "^2.2.1",
    "js-cookie": "^2.2.0",
    "lozad": "^1.9.0",
    "mobile-detect": "^1.4.3",
    "moment": "^2.24.0",
    "next": "^8.0.0-canary.24",
    "next-compose-plugins": "^2.1.1",
    "next-ga": "^2.3.4",
    "next-images": "^1.0.4",
    "next-optimized-images": "^2.3.3",
    "next-seo": "^1.10.0",
    "next-with-apollo": "^3.3.2",
    "prop-types": "^15.7.1",
    "react": "^16.8.1",
    "react-dom": "^16.8.1",
    "react-final-form": "^4.0.2",
    "react-in-viewport": "0.0.36",
    "react-progressive-loader": "^0.2.1",
    "react-responsive": "^6.1.1",
    "react-responsive-ssr": "^0.4.0",
    "ts-graphql-plugin": "^1.1.2",
    "underscore.string": "^3.3.5",
    "what-input": "^5.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/plugin-transform-classes": "^7.2.2",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-react": "^7.0.0",
    "@types/auth0-lock": "^11.4.10",
    "@types/classnames": "^2.2.7",
    "@types/graphql": "^14.0.5",
    "@types/isomorphic-fetch": "0.0.34",
    "@types/jest": "^24.0.2",
    "@types/js-cookie": "^2.2.0",
    "@types/lozad": "^1.2.0",
    "@types/next": "^8.0.0",
    "@types/next-seo": "^1.10.0",
    "@types/react": "^16.8.2",
    "@types/react-dom": "^16.8.0",
    "@types/react-responsive": "^3.0.2",
    "@types/react-test-renderer": "^16.8.0",
    "@zeit/next-typescript": "^1.1.1",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^24.1.0",
    "babel-plugin-emotion": "^10.0.7",
    "babel-plugin-inline-react-svg": "^1.0.1",
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "docz": "^0.13.7",
    "docz-plugin-css": "^0.11.0",
    "docz-theme-default": "^0.13.7",
    "dom-testing-library": "^3.16.5",
    "email-validator": "^2.0.4",
    "husky": "^1.3.1",
    "jest": "^24.1.0",
    "jest-dom": "^3.1.1",
    "jest-emotion": "^10.0.7",
    "lint-staged": "^8.1.3",
    "react-addons-test-utils": "^15.6.2",
    "react-test-renderer": "^16.8.1",
    "react-testing-library": "^5.8.0",
    "ts-jest": "^23.10.5",
    "tslint": "^5.12.1",
    "typescript": "^3.3.3",
    "unstated": "^2.1.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "pre-push": "lint-staged && npm run test:coverage"
    }
  },
  "lint-staged": {
    "*.tsx": [
      "prettier --write",
      "tslint --fix --config tslint.precommit.json",
      "git add"
    ]
  }
}

And .babelsrc

> {
  "presets": [
    "next/babel",
    "@zeit/next-typescript/babel",
    "@babel/preset-react",
    "@babel/preset-env"
  ],
  "plugins": [
    [
      "emotion",
      {
        "hoist": false,
        "sourceMap": false,
        "autoLabel": false,
        "labelFormat": "[local]",
        "extractStatic": false,
        "outputDir": "",
        "importedNames": {
          "styled": "styled",
          "css": "css",
          "keyframes": "keyframes",
          "injectGlobal": "injectGlobal",
          "merge": "merge"
        }
      }
    ],
    [
      "module-resolver",
      {
        "root": ".",
        "alias": {
          "components": "./src/components",
          "modules": "./src/modules",
          "utils": "./src/utils",
          "theme": "./src/theme"
        }
      }
    ],
    ["@babel/plugin-proposal-class-properties"],
    "inline-react-svg"
  ],
  "env": {
    "development": {
      "presets": ["next/babel"]
    },
    "production": {
      "presets": ["next/babel", "@zeit/next-typescript/babel"]
    },
    "test": {
      "presets": [
        [
          "next/babel",
          {
            "preset-env": {
              "modules": "commonjs"
            }
          }
        ]
      ],
      "plugins": [
        [
          "emotion",
          { "sourceMap": true, "autoLabel": true, "labelFormat": "⚡[local]" }
        ]
      ]
    }
  }
}

Thanks :)

**Comment by dav-is** [comment]
The `/static` folder isn't meant for things that you import. Try renaming the folder/moving the things that you import to `/assets` or something

**Comment by Emiliano-Bucci** [comment]
@dav-is Why not?

**Comment by dav-is** [comment]
The static folder is typically served from a CDN. You wouldn't want to store the file in the static folder AND bundled with your app. So you separate `/static` for files that you would call from a url, for example: `<img src="/static/icon.png">`
If you are `import asset from '../assets/item'` then it's in most cases going to be bundled with your app so you wouldn't want to waste space on your CDN uploading it in `/static` too

**Comment by Emiliano-Bucci** [comment]
And this is the reason why my entire app fails? Because with v7 this doesn't happen

**Comment by dav-is** [comment]
I'm not sure, did you try it?

**Comment by timneutkens** [comment]
@Emiliano-Bucci could you provide a repository that we can look at? It'll be easier to help you that way.

**Comment by Emiliano-Bucci** [comment]
@timneutkens Yes, shure, and thanks for the time :)

https://bitbucket.org/emiliano-bucci/my-life-in-trek/src/master/

@dav-is I will try, thanks for the help :)

**Comment by Emiliano-Bucci** [comment]
@dav-is Tried but nothing change :/ The site still remain unusable, without any possible interaction

**Comment by Emiliano-Bucci** [comment]
@timneutkens Do you think that the issue could be the babel plugin module-resolvers?

**Comment by revskill10** [comment]
@Emiliano-Bucci Have you tried building locally, what's the error then ?

**Comment by Emiliano-Bucci** [comment]
@revskill10  Same error:
`ModuleNotFoundError: Module not found: Error: Can't resolve 'src/components/Comp' in '/Users/emiliano/Desktop/projects/blpt/pages'`

**Comment by Emiliano-Bucci** [comment]
By the way, if could be useful to anyone, the problems that i face were basically two:
- Absolute path imports.
- Pages files inside folder (**pages/Index/index.tsx**)

By using only relative imports and only single page file (**pages/index.tsx**) everything works fine.

**Comment by heshamelmasry77** [comment]
@Emiliano-Bucci  i have similar problem with now when i try to deploy.

i get that my images paths is not correct but locally its correct and works i dunno why :S 
![screenshot 2019-03-06 at 17 24 32](https://user-images.githubusercontent.com/15607302/53894193-59c5eb00-4038-11e9-93f2-ac7e137d97c9.png)
i used /static ./static ~/static  ....  ice-cream/static nothing is working

**Comment by timneutkens** [comment]
@heshamelmasry77 the `static` directory is not downloaded as it's intended for static files. If you want to compile them you'll have to move the files you want to compile into another directory.

**Comment by heshamelmasry77** [comment]
It worked I created another folder named images and I copied everything i put in my static and it worked.

**Comment by timneutkens** [comment]
🙌 It's basically done to speed up the builder as eg on most sites you could have a very large `static` folder that isn't used at all in the build process 🙏

**Comment by ijjk** [comment]
This appears to be resolved so I am going to close this issue. If you are still encountering a problem feel free to comment and I can re-open.

**Comment by cuonghv91** [comment]
Crazy how your file looks, why u make things up so difficult, pls simple is the best, writing some spaghetti complex code doesnt make u look cool for GOd sake :(

**Comment by timneutkens** [comment]
@cuonghv91 not sure what you're trying to say here and it sounds pretty random.

Furthermore:

- Not constructive
- Doesn't add anything to the issue
- This issue has been closed for 9 months.
