### ISSUE TITLE
Invalid GET route path for img when viewing certain pages and not others

### ISSUE THREAD

**Issue by LEscobar-Driver** [zeit/next.js#6294]
# Bug report
Source https://github.com/LEscobar-Driver/dKick
Video of the bug https://imgur.com/a/kp8V9Lr

My static header/footer icon image is broken within some pages and not others. 

> GET {incorrect file path} 404 Not Found

## Describe the bug

**Project Folder structure** https://imgur.com/a/nVDdTqC

As you can see from the imgur image, I have 5 pages. My header/footer icon image displays as its suppose to on all my pages expect the pages contained within the `pages/campaigns/request` folder. When I look at the console within mozilla I see that the code is attempting to GET the image with an invalid url. See picture below.

**Error msg displayed with an invalid GET picture url** https://imgur.com/a/7iQh597

It seems to be appending some of the folder names to the URL and therefore the picture is not found and nothing is displayed. I have no idea what is going on. 

## To Reproduce

Go to `https://decentalizedkickstarter.herokuapp.com/`

On the landing page you will be able to see within the console `Network` tab that my static picture is being GET with the correct url.

Hit on any `View Campaign`.

Hit on `View Requests`

Then suddenly, my header/footer icon is broken. You can see in console `Network` that the static png upload url suddenly has an appended folder name, thus making the url invalid and the image breaks...

## Expected behavior
Header/Footer should display normally.

## System information
 - OS: Ubuntu 18.04
 - Browser: Chrome/Mozilla
 - Version of Next.js: 4.1.4
- Node Version: 11.8.0

**Comment by timneutkens** [comment]
Could you post this on https://spectrum.chat/next-js? I don't think it's related to how Next.js works at this point 🤔 You're also using a really old version of Next.js.
