### ISSUE TITLE
HMR reloading page every 10 seconds

### ISSUE THREAD

**Issue by AlexOtero32** [zeit/next.js#6296]
# Bug report

## Describe the bug

After upgrading to next@8, HMR keeps reloading the page every ~10 seconds. The console throws the following error: 
Connection to https://mydomain.com/_next/webpack-hmr was interrupted while the page was loading.

## To Reproduce
Upgrade a project from next@7.0.2 to next@8.0.1 using

    yarn upgrade next@latest react@latest react-dom@latest

## Expected behavior
HMR only reloading page when changes are made

## Screenshots
![screenshot from 2019-02-14 14-06-50](https://user-images.githubusercontent.com/11923783/52788664-f280d080-3061-11e9-80da-430016349b67.png)

## System information
 - OS: Debian
 - Browser: Firefox Developer Edition
 - Version of Next.js: 8.0.1

**Comment by timneutkens** [comment]
Can you provide a reproduction?

**Comment by AlexOtero32** [comment]
What do you need exactly?

**Comment by timneutkens** [comment]
Anything that allows us to actually look into this issue. Like a GitHub repository.

**Comment by sarriaroman** [comment]
Same problem here, nothing changed, just updated to 8.0.1. The error I'm seeing is:

```WebSocket connection to 'wss://127.0.0.1:55580/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR```

And after it's thrown just reloads the page.

**Comment by Timer** [comment]
To clarify, we can't reproduce this with any of our projects. Please provide us with a project (lockfile and all) that has this reproducing. Thanks!

**Comment by timneutkens** [comment]
The on-demand-entries ping was moved to a websocket. It seems like you're using https in development, meaning that you'll have to configure your environment to allow websockets to connect, there's a few options that help you do this: https://nextjs.org/docs#configuring-the-ondemandentries

**Comment by sarriaroman** [comment]
Yes, that is the problem, I found that but there is no way to load custom certificates to prevent the SSL Error.

**Comment by haywirez** [comment]
@timneutkens can you shed more light on this? What do I have to configure to make websockets over SSL with local certs work?

**Comment by sarriaroman** [comment]
There is no current way to configure your certificates in the onDemandEntries config. The fix proposed will work on the short term but would be likely to have a way to set custom certificates on the config.
