### ISSUE TITLE
API abstraction using HOC does not work in getInitialProps

### ISSUE THREAD

**Issue by GiampaoloFalqui** [zeit/next.js#6297]
# Bug report

## Describe the bug

I am attempting to abstract my API calls by using a simple service that provides a very simple method, which is just an HTTP call. I store this implementation in a React Context, and use its provider inside my _app.js, so that the API is globally available, but I have a problem at actually consuming the context in my pages.

## To Reproduce
https://gist.github.com/GiampaoloFalqui/37bb01b0fb64327cb5e8c4df598ae473

## Expected behavior
`this.props.api` should not be undefined since it should use the context of the HOC.

## Screenshots
/

## System information
 - OS: macOS
 - Browser (if applies) Chrome
 - Version of Next.js: 8.0.0

## Additional context

**Comment by timneutkens** [comment]
Please ask questions on https://spectrum.chat/next-js. This is not a bug in Next.js.
