### ISSUE TITLE
switch from target:server to target:serverless from (npm-)scripts

### ISSUE THREAD

**Issue by romainquellec** [zeit/next.js#6306]
# Feature request

## Is your feature request related to a problem? Please describe.
I'm using "target:server" for development. I'm also testing "target:serverless" with serverless framework, and right now, i'm switching manually target:server to serverless manually.

Is there a way to switch that automatically ?
- I'm using custom server (server/index and server/lambda), so maybe, there is a way to load custom next.config to change conf on the fly ?
something like : 
server/index.ts
```
import config from 'next.config.js'
const conf = { ...config, target: 'server' };
const app = next({ dev, conf });
```
if so, right now, its not working or I'm doing something wrong.

(Maybe similar to https://github.com/zeit/next.js/issues/6219)

**Comment by timneutkens** [comment]
You can use phases like: https://github.com/zeit/next.js#custom-configuration
