### ISSUE TITLE
serverless mode: "Emitted warnings from webpack", long wait, followed by super verbose logging

### ISSUE THREAD

**Issue by sw-yx** [zeit/next.js#6307]
# Bug report

## Describe the bug

when i try to run `next build` in the new serverless mode, i get a message `Emitted warnings from webpack` and then it dumps out chunks representing in my node modules in my console forever (so i have to manually terminate the build)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. https://github.com/sw-yx/marvel-SSSR.git
2. `yarn`
3. `BUILD=serverless yarn next build`
4. See error in console

## Expected behavior
it should just build

## Screenshots
![nextjs](https://user-images.githubusercontent.com/6764957/52860087-91451580-30d2-11e9-89ab-7eb0f68b41e6.gif)

## System information
 - OS: [e.g. macOS, Windows] OSX
 - Browser (if applies) [e.g. chrome, safari] n/a
 - Version of Next.js: [e.g. 6.0.2] 8.0.0

## Additional context

it runs fine in local dev, and also builds fine in non-serverless mode. just serverless is weirdly broken. also i didnt have any issues until i started using `getInitialProps`

**Comment by Timer** [comment]
This should be fixed in the latest canary. 😄

**Comment by sw-yx** [comment]
sweeet!! side note, i didnt know you worked at Zeit! maybe im slow on the uptake haha. i just assumed you and Ian were both at facebook
