### ISSUE TITLE
Store state differs between first and successive ssr in with-redux-saga example

### ISSUE THREAD

**Issue by janjarfalk** [zeit/next.js#6308]
## Example name
with-redux-saga

## Describe the bug
Store state differs between first and second (actually all successive) server-side renders.

## To Reproduce
1. `npx create-next-app --example with-redux-saga with-redux-saga-app`
2. `cd with-redux-saga`
3. `npm install`
4. `npm run dev`
5. Open web browser and check the store value for `placeholderData` (has data)
6. Reload the web browser and check the store value for `placeholderData` (is null)

Only solution is to restart the server.

## Expected behaviour
I expected placeholderData to have the same value after every browser reload.

**Comment by janjarfalk** [comment]
Reverting #6300 solves this issue. In effect reverting back to.
```
"next-redux-saga": "3.0.0",
"redux": "4.0.0",
"redux-saga": "0.16.0"
```

**Comment by bbortt** [comment]
@janjarfalk i'll have a look at it.

**Comment by bbortt** [comment]
Well, obviously saga task is canceled on server side as seen [here](https://github.com/bmealhouse/next-redux-saga/pull/44/files) on lines `index.js:19-22`. Therefore, `takeLatest(actionTypes.LOAD_DATA, loadDataSaga)` is not caught and no data is loaded on second (and continuous) server side render. However the task was already canceled before this update, see `index.js:24-26`.
So, @bmealhouse I wonder how the task survived on server side within version `"next-redux-saga": "3.0."`?

**Comment by bbortt** [comment]
Ah probably because of what Andarist mentioned [here](https://github.com/bmealhouse/next-redux-saga/issues/27#issuecomment-464347081), that `dispatch(END)` would not propperly close the task. Then we're screwed.. The whole V3 API built on a bug and in order to run it we would have to change behaviour in `"redux-saga"`..

**Comment by bbortt** [comment]
I have te solution.. *facepalm* will implement it this evening! @bmealhouse @janjarfalk

**Comment by bbortt** [comment]
The error must be located in the example. See [this issue in `next-redux-saga`](https://github.com/bmealhouse/next-redux-saga/issues/48) for more information.

**Comment by janjarfalk** [comment]
You might be right, but I didn't find this issue in the `with-redux-saga` example. I just used it to reproduce it. I see it in several, unfortunately private, projects. The setup in those projects is however derived from `with-redux-saga` in one way or another.

I am having problems geting `my-little-streaming-dream` (the authserver) up and running. Do you have something smaller where it works?

**Comment by janjarfalk** [comment]
If I simplify the `requestUserInfo` in `my-little-streaming-dream` to...
```
function* requestUserInfo(action: RequestUserInfoAction) {
  yield put(setUserInfo({name:'Timon'}));
}
```
... it does reproduce the issue.

**Comment by bbortt** [comment]
Huh, heavy mistake on my side.. didn't run `yarn install` on my laptop and was still using `"redux-saga": "0.16.2"`..
You're right @janjarfalk, problem still exists.

**Comment by janjarfalk** [comment]
No worries! I appreciate the time and effort you are putting into this! I wish I could be of more help. My current knowledge of `next-redux-saga`, `next-redux-wrapper` and the changes in `redux-saga` is too little.

**Comment by bbortt** [comment]
@janjarfalk  I got the error and I even know how to fix it. Will update the example and the documentation on `next-redux-saga` shortly :)

**Comment by bbortt** [comment]
Can you test the example again @janjarfalk?

**Comment by janjarfalk** [comment]
@bbortt Works like a charm! Thank you very much!

**Comment by bmealhouse** [comment]
@bbortt - After looking through the PR it was a very straightforward solution. Excellent work!

**Comment by janjarfalk** [comment]
Just a short thing before you go...

As I said before my knowledge of `next-redux-saga`, `next-redux-wrapper` and the changes in `redux-saga@1.0` is little. So.. not knowing you would fix this so quickly (thanks again!) I decided to copy-paste-rewrite `next-redux-saga`, `next-redux-wrapper` from scratch.

I think it would make sense to drop `next-redux-wrapper` as a dependency. It doesn't do much and the code was easier for me to reason about when it was merge with `next-redux-saga`.

https://gist.github.com/janjarfalk/e0ed2566143d9ed02cae7c9a1c7bdcbb

**Comment by bmealhouse** [comment]
@janjarfalk - I definitely agree with this approach. However I don't plan to make those changes myself, since I'm not using redux or saga in any of my current projects. If anyone would like to submit a PR for this I would be happy to get this in.

**Comment by bbortt** [comment]
@janjarfalk can you submit a pr containing those changes?
I would collaborate on creating tests and I also see one or two things in your gist which I want to check first.

**Comment by janjarfalk** [comment]
@bbortt There are a lot of breaking changes in the gist - no config, no debug etc. I think we can and should drop `next-redux-wrapper` without breaking changes. Let me find some time and I'll do a proper merge and PR.
