### ISSUE TITLE
Issue with "Compiling…" triggering w/o fs changes

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#631]
![2017-01-02 18 26 42](https://cloud.githubusercontent.com/assets/13041/21598899/5f123374-d119-11e6-9c8b-775c3f25a525.gif)

Also: the server stops responding after while, possibly related to this

**Comment by nkzawa** [comment]
It seems opening a project dir with Finder app triggers this.

**Comment by arunoda** [comment]
@nkzawa does #636 fixes that?
