### ISSUE TITLE
Problem with dynamic routing example to static

### ISSUE THREAD

**Issue by zzrez** [zeit/next.js#6311]
## Example name
with-static-export

## Describe the bug
This example produces the static files for each of the posts (10 in total), but does not serve them. Instead the app makes a call to the api, eg https://jsonplaceholder.typicode.com/posts/3 for post3.

I also got this error the first time when using npm run start:-
A system error occurred (ENOENT: no such file or directory, stat 'c:\Users\...\nextjs-static-export\out\post')

## To Reproduce
1. Copy the example repo to a repository (in our case https://github.com/zzrez/nextjs-static-export) 
2. npm install to add all dependencies
3. Use the scripts in package.json, eg npm run build, npm run export, npm start
4. Open http://localhost:5000 and use Network tab of Chrome Dev Tools to check if a network call is made on open a post from the home page, or a static page.
5. I also added to Netlify to see: https://nextjs-static-export.netlify.com/

## Expected behavior
On the List of posts page, on clicking any "Read more..." link, it is expected that a static file from the Out folder is loaded. But instead a network call is made to the remote API, https://jsonplaceholder.typicode.com/posts/x. This was the case for both http://localhost:5000 and the Netlify case.

## System information
 - Windows
 - Chrome
 - Version of Next.js: 6.7.0

**Comment by ijjk** [comment]
@zzrez This isn't really a bug this is the expected behavior. It sounds like you could accomplish this with `babel-plugin-preval`. Here's [an example](https://github.com/zeit/next.js/tree/canary/examples/with-babel-macros)
