### ISSUE TITLE
next 8.0.1 throws error when `webpack` method is written as pure function

### ISSUE THREAD

**Issue by rudolph9** [zeit/next.js#6313]
# Bug report

## Describe the bug
Upon upgrading from next 7.0.2 to next 8.0.1 I received the following error:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'private-next-pages/_app.js'
```

After a little digging I identified that the issue had something to do with a webpack alias I had configured in my `next.config.js`:
```
module.exports = {
  webpack(config) {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.alias,
          _: __dirname,
        },
      },
    };
  },
};
```
__Background: Aliasing `_: __dirname` allows me to import files via very concise absolute references (e.g. `import Foo from '_/components/Foo'`).  `_` was chosen and npm packages are restricting from beginning with that character and I don't know of anything that might cause a conflict.__

Since the docs and examples specify and show that a config object should be return from the `webpack` method I would expect a pure function (generally a best practice when possible) to adjust the config as expect.  This was indeed the case in next 7.
This is no longer the case in next 8. 

I was able to make the alias config work as expected by adjusting the above to the following:
```
module.exports = {
  webpack(config) {
    // Nextjs 8 pukes if we don't do param-reassign
    // eslint-disable-next-line no-param-reassign
    config.resolve.alias._ = __dirname;
    return config;
  },
};
```

**Comment by timneutkens** [comment]
Both work, the issue here is that you probably weren't defining the aliases coming from Next.js's config object (making the assumption that Next.js would never add them in the future) so this is not a bug in Next.js and there's little we can do to resolve it.
