### ISSUE TITLE
React. map cannot be used to render content

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [zeit/next.js#6314]
<ItemGrid>

                        {
                            good_list.map((e, i) => {
                                return (
                                    <div className={classnames(styles.product_items, 'item', 'project-post', e.irregular_width ? 'project-post-width2' : '', 'grid-item')} key={e.goods_id}>
                                        <div className={styles.product_hover}>
                                            <div className={styles.product_cell}>
                                                <dl>
                                                    <dd>
                                                        <Link href={`product-info?id=${e.goods_id}`} >
                                                            <span className="ti-zoom-in fa-2x"></span>
                                                        </Link>
                                                    </dd>
                                                </dl>
                                            </div>
                                        </div>

                                        <img src={e.irregular_img_url} />

                                        <div className={styles.product_txt}>
                                            <a href="">{e.goods_name}</a>
                                            <p>￥{e.shop_price}</p>
                                        </div>
                                    </div>
                                )
                            })
                        }

                    </ItemGrid>

I used a lot of React. map methods, but when I looked at the source code, I didn't render it.

**Comment by timneutkens** [comment]
This doesn’t sound like a Next.js issue, please follow the issue template and provide a clear and concise reproduction.
