### ISSUE TITLE
with-redux example bug..

### ISSUE THREAD

**Issue by rajaraodv** [zeit/next.js#632]
I get the following warning in the browser when I run the example:
https://github.com/zeit/next.js/tree/master/examples/with-redux
﻿
```
next-dev.bundle.js:1379 Warning: Unknown prop `jsx` on <style> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in style (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by Connect(Component))
    in Connect(Component) (created by Counter)
    in Provider (created by Counter)
    in Counter (created by App)
    in AppContainer (created by App)
    in App
```

**Comment by timolins** [comment]
Examples are getting updated for Next.js 2.0 which uses `styled-jsx` by default. The package.json in the example sets the version to `*`, but since 2.0 isn't released yet, this won't work at the moment. Meanwhile you can install the Next.js 2.0 beta manually, to fix this issue.

**Comment by rajaraodv** [comment]
thanks
