### ISSUE TITLE
Custom assetPrefix will be broken with custom build directory

### ISSUE THREAD

**Issue by RoberMac** [zeit/next.js#6325]
# Bug report

## Describe the bug
As title.

## To Reproduce
I setup custom assetPrefix in server.ts (like [Dynamic assetPrefix](https://github.com/zeit/next.js#dynamic-assetprefix)) and custom build directory: `distDir: 'build'`
```ts
if (ASSET_PREFIX) {
  app.setAssetPrefix(ASSET_PREFIX)
}

app
  .prepare()
  .then(() => {
    const server = express()

```

But the client request `https://DOMAIN/assets/_next/static/runtime/xxx.js` instead of `https://DOMAIN/assets/assets/build/static/runtime/xxx.js`

## System information
 - Version of Next.js: 8.0.0

**Comment by timneutkens** [comment]
This is not an issue `_next` should serve the distDir 🤔

**Comment by RoberMac** [comment]
@timneutkens You mean all `_next` prefixed request will map to `distDir` (`build` here) ? Actually, I upload all build files to S3. so the URL will be like https://s3-ap-southeast-1.amazonaws.com/xxx/build/static/runtime/main-xxx.js

**Comment by timneutkens** [comment]
You can't change `_next` so if you build the files to a different distDir you have to make sure you're serving `<distdir>/static` as `/_next/static`

**Comment by RoberMac** [comment]
@timneutkens Thanks for your clarification.

**Comment by timneutkens** [comment]
Happy to 🙏👍
