### ISSUE TITLE
Cannot find module '../core-js/object/define-property'

### ISSUE THREAD

**Issue by demongodYY** [zeit/next.js#6332]
# Question about Next.js
I want to try install next.js to start a project, but when I finished steps on  tutorial, when I run `npm run dev`, I get a error 500 on my page by http://localhost:3000, and get error below:

![image](https://user-images.githubusercontent.com/17036920/52925188-e8651780-336a-11e9-812c-5c0f1b69f5fd.png)

my package.json like this:

``` 
 "dependencies": {
    "next": "^8.0.1",
    "react": "^16.8.2",
    "react-dom": "^16.8.2"
  },
    "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
```
Is there need import babel/core-js manually?

**Comment by ht1131589588** [comment]
I also encountered such a problem.

**Comment by Yzrsah** [comment]
Try "devDependencies": { "webpack": "^4.29.4" }

**Comment by Yzrsah** [comment]
Try "devDependencies": { "webpack": "^4.29.5" }

**Comment by timneutkens** [comment]
Please provide a reproduction when creating issues.

**Comment by ht1131589588** [comment]
![image](https://user-images.githubusercontent.com/24310479/52950589-9a780000-33ba-11e9-8ad8-6b6b5531543c.png)
@timneutkens

**Comment by timneutkens** [comment]
That is not really a reproduction, please provide a repository or similar. I can't reproduce based on these 3 deps.

**Comment by ht1131589588** [comment]
I will get an error when installing with cnpm, this error will not occur with npm，sorry for disturbance!

**Comment by forMine** [comment]
> I will get an error when installing with cnpm, this error will not occur with npm，sorry for disturbance!

but I want to know which package will affect it

**Comment by fXy-during** [comment]
The same thing happened to me on this project.  can you share some solutions to this problem?   @ht1131589588

**Comment by fXy-during** [comment]
fortunately, I solved this problem with a downgraded version. 
this is my packjson file: 
![image](https://user-images.githubusercontent.com/26021950/54194089-680f7d80-44f6-11e9-9330-b724e15a6a57.png)

**Comment by duuliy** [comment]
I also met this problem. It was cnpm that couldn't. It was really unfriendly.

**Comment by githubmann** [comment]
> I also met this problem. It was cnpm that couldn't. It was really unfriendly.

i use yarn that solve that

**Comment by aleccool213** [comment]
why is this closed? I am also getting this issue

**Comment by dimisus** [comment]
I am getting this issue all over the place as well!

After I updated to NEXT 8.0.3

**Comment by w01fgang** [comment]
It's babel's issue https://github.com/babel/babel/issues/9734#issue-423654875
I solved it by installing core-js
`yarn add core-js --exact`

**Comment by matthewlilley** [comment]
The babel issue was closed with - "I'm closing this issue, since it is caused by a lot of packages which we don't control and which use core-js without specifying it in their deps."
