### ISSUE TITLE
How to configure support for the following directory structure？

### ISSUE THREAD

**Issue by einsqing** [zeit/next.js#6334]
# Question about Next.js

How to configure support for the following directory structure？There are no pages directories, then go to /hello/hello to load the first hello.js, go to /hello2/hello to load the second hello.js

![image](https://user-images.githubusercontent.com/7685948/52937665-be2b4e00-339a-11e9-81e6-8df0c3e2618a.png)

**Comment by timneutkens** [comment]
Create a pages directory an re-export the component.

**Comment by einsqing** [comment]
@timneutkens No, I want to load pages directly from multiple non-pages directories
