### ISSUE TITLE
React not initialized in next@8 in index page

### ISSUE THREAD

**Issue by dimensi** [zeit/next.js#6337]
# Bug report

## Describe the bug
In development mode, the entire application works fine, but in the production assembly, the main page is not initialized. I get html, index.js, but the react is not initialized
There are no errors in the console.
The problem is only on next@8, on next@7 there are no problems.

## To Reproduce
I don't think I can repeat this case.
This problem appears on my computer and on the host machine.

## Expected behavior
I expect that react will make hydration and start working.

## Screenshots
On index page ![image](https://user-images.githubusercontent.com/11390039/52960536-1453bd80-33aa-11e9-813a-e8d4bc085db4.png)
On other pages ![image](https://user-images.githubusercontent.com/11390039/52960581-27ff2400-33aa-11e9-943c-d81a374d25e3.png)
![image](https://user-images.githubusercontent.com/11390039/52960761-84fada00-33aa-11e9-8f10-61e2393d89b5.png)
The screenshot shows that all the necessary scripts are connected to the page.

## System information
 - OS: macOs/linux
 - Browser: chrome, safari, firefox
 - Version of Next.js: 8.01

**Comment by timneutkens** [comment]
> I don't think I can repeat this case.
> This problem appears on my computer and on the host machine.

We won't be able to help with your issue without a reproduction. 
We have tests that cover nearly all features of Next.js.

Please provide a reproduction 👍

**Comment by dimensi** [comment]
@teleginzhenya i found where a problem. If i put index.js into /pages/index/ dir. 
https://github.com/dimensi/next-bug

**Comment by dimensi** [comment]
my issue is duplicate https://github.com/zeit/next.js/issues/6285
