### ISSUE TITLE
nextjs dont use stats.warningFilters

### ISSUE THREAD

**Issue by popuguytheparrot** [zeit/next.js#6349]
# Bug report

## Describe the bug
For fix issue with css and `Conflict order between` i must add options to stats
https://webpack.js.org/configuration/stats/#stats

Im add this code in next.config.js, but nothing happens
```javascript 
 config.stats = {};
    config.stats.warnings = false;
    config.stats.warningsFilter = warning =>
      /Conflicting order between/gm.test(warning);
```

What need to do for fix it in nextjs ?

**Comment by timneutkens** [comment]
This doesn't seem like a Next.js issue. We expose the webpack configuration and don't do anything else there. You can try `next@canary` as warning logging has changed there.

**Comment by koenpunt** [comment]
Related https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250

**Comment by zadzbw** [comment]
i have the same problem, i've added stats in config, it doesn't work

**Comment by egemon** [comment]
So I am also having this issue @timneutkens could u check it out please?

**Comment by egemon** [comment]
@timneutkens please reopen. I spent a lot of time with debugging to bones, and in any place i can reach with next.config.js stats key is presenting but not working.

**Comment by Timer** [comment]
Conflicting order is a real error. There's nothing to ignore here.
