### ISSUE TITLE
Testing Workplan

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#635]
This is about the testing setup of the Next.js project. 
(Not about the testing about apps created with Next.js, that's something we should address too.)

We believe in a integration/end-to-end rather a bunch of unit tests which gives us better code coverage. That being said, we may have to unit tests for few utilities we are using.
We can breakdown what kind of tests we as follows:

#### Unit Tests

For the some of the utilities we use. Things like [shallow-equals.js](https://github.com/zeit/next.js/blob/master/lib/shallow-equals.js) is a good example for that.

#### Isolated Tests (a form of integration tests)

We do this for the isolated utilities like [`server/resolve.js`](https://github.com/zeit/next.js/blob/master/server/resolve.js) which we are using internally.

#### Integration/E2E Tests

Here are checking the actual features of next. We do this by actually running Next.js apps. We can incorporate example apps for this. We can simply place some tests inside those apps.
We may have to do some client side tests as well. For that, we could use WebDriver.

#### Q/A (Human Testing)

It's not possible to automate tests for some cases. One such area is HMR related features. For that, we need to test them manually. 
At first, we may have bunch of these Q/A tests. Eventually, we could transform them into automated test cases.

**Comment by nkzawa** [comment]
Basically sounds awesome.

> Integration/E2E Tests

I prefer to use `jsdom` to make things simple and fast.

> Q/A (Human Testing)

I'd rather like to try automated tests even for HMR.

**Comment by arunoda** [comment]
Now we have this in the core.
