### ISSUE TITLE
TypeError: sheet.seal is not a function 

### ISSUE THREAD

**Issue by Farhanisto** [zeit/next.js#6350]
# Bug report

## Describe the bug

On copying the code for the example file _document the above error is encounted

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to 'examples/with-styled-components/pages/_document'
2. copy the code and run your application. 
3. check your console

## Screenshots
![screen shot 2019-02-19 at 13 04 57](https://user-images.githubusercontent.com/25313180/53006883-33ecf380-3447-11e9-995d-59837364c4b9.png)

## System information
 - OS: [e.g. macOS]
 - Version of Next.js: [e.g. 7.0.0]

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/pull/6207#issuecomment-460676919
