### ISSUE TITLE
Bug CSS in JS with !important rule

### ISSUE THREAD

**Issue by RapSherlock** [zeit/next.js#6352]
# Bug report

## Describe the bug
can't get CSS in JS with **!important** working

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create a div with some style
`<div style={{
margin: "200px",
                textAlign: "center",
                width: "100px",
                height: "100px",
                border: "1px solid black",
                background: "red !important"
              }}
            >
              some text
            </div>`
2. result 
![image](https://user-images.githubusercontent.com/22311760/53012824-ade8a100-3476-11e9-9040-e279b80f9c32.png)
3. when i'm inspect element, style rule for background is gone.
![image](https://user-images.githubusercontent.com/22311760/53013014-32d3ba80-3477-11e9-81b7-c3336905c65d.png)
4. if i remove the **!important** it works 

## Expected behavior
style rule is working with **!important** 

## System information
 - OS: Windows 10
 - Browser : Chrome Version 72.0.3626.109 
 - Version of Next.js: 8.0.0

**Comment by timneutkens** [comment]
This is an issue in React: https://github.com/facebook/react/issues/1881

**Comment by timneutkens** [comment]
You could use github.com/zeit/styled-jsx for this though.

**Comment by RapSherlock** [comment]
Thanks for the confirmation
