### ISSUE TITLE
ES Modules (still) can't be in server build

### ISSUE THREAD

**Issue by herrstucki** [zeit/next.js#6369]
# Bug report

## Describe the bug

This is a follow-up to #6246 which was fixed by @Timer in #6256 but unfortunately not completely (not sure why that test works and in a real scenario it doesn't).

.js files that contain ES module syntax (`import`, `export` etc) will result in an error during build.

The problematic piece of code seems to be this part where webpack bails out of bundling/resolving these modules:

https://github.com/zeit/next.js/blob/3db53610477ba5ab160e7bb8d97745872a2e99f3/packages/next/build/webpack-config.js#L58-L60

If I understand correctly, dependencies get treated as externals but only in the server bundle. This seems problematic to me because it would also break projects where you'd specify all dependencies as `devDependencies` and want to pre-build the app before deployment (not unlike the serverless case).

## To Reproduce

https://codesandbox.io/s/54kol5nm4 (somehow doesn't work on CodeSandbox but if you download and run it you get the following error:

![bildschirmfoto 2019-02-20 um 11 02 29](https://user-images.githubusercontent.com/70969/53083411-2e52e480-34ff-11e9-9db0-f674d4c49f47.png)

## System information
 - OS: macOS
 - Version of Next.js: 8.0.1

**Comment by herrstucki** [comment]
FWIW, when I remove the code that treats the node_modules as externals, it works.

**Comment by timneutkens** [comment]
Closing this in favor of https://github.com/zeit/next.js/issues/706

**Comment by herrstucki** [comment]
@timneutkens obviously I don’t know what your plans are for this but it looks to me as if #706 is a Babel-related tranpilation issue while this is a webpack bundling issue (and a breaking change from how next worked in v7).

Is there a specific reason why modules are treated as externals only in the server build (but _not_ in the serverless and client build)? As I mentioned before, in the case where one only has devDependencies – to publish only compiled code to a server – the current behavior would also not work, no?

**Comment by timneutkens** [comment]
@herrstucki it's all the same problem basically, I'm aware of the exact issues around this and will create a new issue tracking the solution to all of them once I'm able to figure out a solution for this. The main issue with the exclude is, that if you don't the `.next` size of the server target will skyrocket (maybe not a problem as you can leave out node_modules) but also it will load more code as every page will have common dependencies bundled.

**Comment by herrstucki** [comment]
@timneutkens Sounds great, thanks! 🙏
