### ISSUE TITLE
Get ENOENT when enable source map

### ISSUE THREAD

**Issue by tpai** [zeit/next.js#637]
I enable source map in `2.0.0-beta.11`, it works fine.

**next.config.js**

```
const webpack = require('webpack');

module.exports = {
    webpack: cfg => Object.assign({}, cfg, { devtool: 'cheap-module-source-map' })
};
```

But got error after I update to `2.0.0-beta.12`.

![](http://i.imgur.com/7iUkuPc.png)

Any idea?

**Comment by nkzawa** [comment]
To clarify, source maps is already enabled on dev mode. Do you like to change the setting or like to enable it on production ?
It looks like you have to set `sourceMapFilename` properly.

**Comment by tpai** [comment]
Got it, I found it enable `inline-source-map` on dev mode, no further question.

https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L208
