### ISSUE TITLE
next.js 8 HMR implementation

### ISSUE THREAD

**Issue by djskinner** [zeit/next.js#6370]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

I asked it here https://spectrum.chat/?t=855c5175-1ec5-40f7-aaba-94c8b6ded78a but got no feedback. Despite my issues with the new HMR being unusable for my use case I think there's possibly a bug when using `setAssetPrefix` as `websocketProxyPath` does not seem to respect it (particularly problematic if using dynamic asset prefix paths).

Here's the original post I made on spectrum:

We've got a complex setup involving multiple next.js apps with iframes. Additionally some parts of the apps are served on a different base URL depending on the scenario. We also use a containerised setup (docker-compose) for development.

Aside from the additional complexity having to wire up a second port for each application we've now hit an issue whereby when the app is being served from a base url the wss URL that is created is wrong. Aside from HMR not working this then causes the page to reload ad infinitum. This basically makes it unusable and I don't currently see a way of preventing it.

Is there a way to go back to the old, simple and straightforward way HMR used to work? I appreciate it was slightly annoying to have the console flooded but the additional complexity of this setup means it doesn't work for us.

Failing that, is there a way to turn HMR off? Of course we would like to avoid doing that but no HMR would be better than being stuck on next.js < 8 forever because we can't create a development environment that constantly reloads the page.

**Comment by Janpot** [comment]
HMR wasn't working for me when I added a `websocketPort` until I also set the `websocketProxyPath` to something.
FYI: In the meantime I came across https://github.com/zeit/next.js/pull/6354

**Comment by djskinner** [comment]
I had `websocketProxyPath` set but it was still constructing the wrong URL because of my complicated setup. Thanks for bringing #6354 to my attention, that sounds promising and likely to resolve my particular issue.

**Comment by timneutkens** [comment]
@djskinner just to be clear the websocket change had been on canary for over 1.5 month and no issue was filed similar to yours, so it helps if you try out canary releases and provide feedback 🙏

We've changed the websocket approach to use eventsource instead as it solves the consistent pinging with just 1 ping per page-change (that's kept open) and doesn't require running another server + it's less code 💯

**Comment by timneutkens** [comment]
This new approach is out on next@canary right now btw, let me know how it goes 👍

**Comment by djskinner** [comment]
Yep, `8.0.2-canary.5` fixes my issue 👍

**Comment by timneutkens** [comment]
Great 👍
