### ISSUE TITLE
JavaScript not working in serverless lambdas

### ISSUE THREAD

**Issue by LouisPetrik** [zeit/next.js#6371]
Currently it's possible to create lambdas and render them via NodeJS to a webpage. But all the JS functions and onclick events are not working on the webpage, even if its all working in the dev-mode of nextjs. Code Example:
This is working in ReactJS, NextJS dev and default build-version. But not as serverless.
```

class Test extends React.Component {
    state = {
        count: 1
    }

    increment = () => {
        this.setState(prevState => {
            return {
                count: prevState.count+1
            }
        });
    }
    render() {
        return (
            <React.Fragment>
                {this.state.count}
                <button onClick={this.increment}>
                    increment
                </button>
            </React.Fragment>
        )
    }
}

export default Test;


```

Server code:

```
const http = require("http");
const page = require("./.next/serverless/pages/Test.js");
const server = new http.Server((req, res) => page.render(req, res));
server.listen(3000, () => console.log("Listening on http://localhost:3000"));
export default Test;
```

MacOS 
NextJS 8

**Comment by timneutkens** [comment]
Sounds like you're not serving the static files, they have to be hosted separately.

**Comment by beheh** [comment]
Have you compiled and deployed the Javascript bundles using `next build`? Next.js will expect them to live under `_next/static/` (you can adjust that with an asset prefix).

**Comment by timneutkens** [comment]
Nice timing @beheh 😄

**Comment by LouisPetrik** [comment]
@beheh yes I used next build before starting the server.

**Comment by LouisPetrik** [comment]
Was able to solve it by using express.static to serve all the static files inside of /.next:
Thanks for the tip 👍 
```
const page = require("./.next/serverless/pages/index.js");
const express = require("express");
const app = express();

app.use("/_next", express.static(".next"))

app.get("/", (req, res) => {
    page.render(req, res);
})

app.listen(8080)
```
