### ISSUE TITLE
serverless: Compile time on CircleCI

### ISSUE THREAD

**Issue by romainquellec** [zeit/next.js#6375]
# Bug report

## Describe the bug
Compile time is close to 10 minutes on CircleCI on my project.
github : https://github.com/CuistotduCoin/front

## To Reproduce
not replicable or complicated.

## Expected behavior
I dont know about the environment of CircleCI, but the compile time seems suspiciously big.
Client time is 'almost' the same, but server is very long.

## System information
 - OS: Ubuntu on CircleCI
 - Version of Next.js: 8.0.2 & 8.0.5-canary

## Additional context
I was using razzle and compile time on my computer was somehow similar to CircleCI build.
For next, my compile time is around 130s (2m10) on my computer, and is almost 10 minutes on CircleCI.

**Comment by romainquellec** [comment]
Just to compare with Razzle + After.js : 

```
Creating an optimized production build...
Compiling client...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
Compiled client successfully.
Compiling server...
Compiled server successfully.
Compiled successfully.

File sizes after gzip:

  90.57 KB  build/static/js/bundle.205afe05.js
  58.33 KB  build/static/js/14.9746f63d.chunk.js
  34.07 KB  build/static/css/8.bundle.6aa4ddd9.css
  29.03 KB  build/static/js/8.c00ef418.chunk.js
  23.85 KB  build/static/js/6.5453f396.chunk.js
  19.08 KB  build/static/js/2.14705eb6.chunk.js
  18.72 KB  build/static/js/13.82ed002c.chunk.js
  15.71 KB  build/static/js/0.633bb9bb.chunk.js
  15.41 KB  build/static/js/3.a5659e90.chunk.js
  14.03 KB  build/static/js/9.0e988aff.chunk.js
  9.72 KB   build/static/js/1.19bb86a7.chunk.js
  8.44 KB   build/static/js/7.03b657b2.chunk.js
  6.13 KB   build/static/js/11.ff8263ab.chunk.js
  5.51 KB   build/static/js/4.fa21fd14.chunk.js
  5.38 KB   build/static/css/bundle.ef2d3416.css
  4.24 KB   build/static/js/5.623eda7e.chunk.js
  2.89 KB   build/static/js/12.69fcfb27.chunk.js
  828 B     build/static/css/3.bundle.7e72afaa.css

Done in 37.87s.
```

**Comment by timneutkens** [comment]
You can't compare razzle with serverless next imo, they do completely different things.

**Comment by timneutkens** [comment]
I'm assuming this is related to uglification on the serverless functions.

**Comment by romainquellec** [comment]
> I'm assuming this is related to uglification on the serverless functions

How can I help ? What can we do to make it quicker ?

**Comment by timneutkens** [comment]
For one you can try running this config to verify:

```
// next.config.js
module.exports = {
  webpack(config) {
     config.optimization.minimize = false
  }
}
```

**Comment by romainquellec** [comment]
Done in 26.37s ! So yes :)

**Comment by romainquellec** [comment]
So I guess, there is place for uglification and optimal compile time. How do we do that ?

**Comment by ijjk** [comment]
This might be associated with #6353

**Comment by adam187** [comment]
@ijjk I can confirm that `8.0.4-canary.10` improves build time on CircleCI in my case. @romainquellec You should give it a try.

**Comment by Timer** [comment]
Definitely associated with the above plugin. Closing as this should be resolved in `canary`. Thanks!

**Comment by romainquellec** [comment]
In my case, it's better but sometimes hiting the 10min limit on CircleCI.
