### ISSUE TITLE
Any MobX implementation planned  in the near future?

### ISSUE THREAD

**Issue by saniko** [zeit/next.js#639]
Saw that a MobX implementation is missing from the "examples" folder.
:)

**Comment by 0xCMP** [comment]
You can look at this for the current version: https://github.com/fdidron/mobx-next-example/

I've used it and it provides a good example to work off. Still requires experimenting.

**Comment by arunoda** [comment]
Guys, now we've a example.
Check this: https://github.com/zeit/next.js/tree/master/examples/with-mobx (via #676)
