### ISSUE TITLE
DevTool complains on first page load

### ISSUE THREAD

**Issue by chuyik** [zeit/next.js#6396]
# Bug report

After upgraded to Next 8.0.2 from 8.0.1, each time I open a page, the DevTool will complain `Unexpected token u in JSON at position 0` because the websocket receive a `undefined` data.

## Screenshots

![image](https://user-images.githubusercontent.com/6262943/53217549-507d6b80-3693-11e9-9929-24d2482a4180.png)

![image](https://user-images.githubusercontent.com/6262943/53217577-74d94800-3693-11e9-9a82-d0d8833e630e.png)

## Related code

![image](https://user-images.githubusercontent.com/6262943/53217585-7efb4680-3693-11e9-9f30-49f6872d6bac.png)

## System information
 - OS: macOS
 - Browser: chrome
 - Version of Next.js: 8.0.2

**Comment by ijjk** [comment]
@chuyik I just submitted a PR with a fix for this. Thanks for the detailed errors!
