### ISSUE TITLE
next command not found

### ISSUE THREAD

**Issue by cschep** [zeit/next.js#64]
Hey!

Really cool project. I was just following the demo on the site and I did the following:

```
brew install node
mkdir foo
cd foo
npm init
npm install next ---save
mkdir pages
vim pages/index.js
next
```

and then ! 

```command not found: next```

shoot

oh..

```
./node_modules/next/dist/bin/next
```

that works.

I'm a noob JavaScript developer, should I have some sort of relative path setup for that?

Just a heads up, thanks!

**Comment by impronunciable** [comment]
Hi @cschep

You can add

```
scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
```

And then run `npm run dev`

**Comment by nkzawa** [comment]
Fixed the instruction, thanks!
