### ISSUE TITLE
after each hot reload i see > Ready on http://localhost:8888

### ISSUE THREAD

**Issue by popuguytheparrot** [zeit/next.js#6404]
# Bug report

## Describe the bug
after each hot reload i see > Ready on http://localhost:8888

## To Reproduce

install basic example and next 8.0.2

## Screenshots
![image](https://user-images.githubusercontent.com/19804652/53237608-2b472800-36a8-11e9-9f5e-7f7de0725b70.png)

## System information
 - OS: [Windows]
 - Version of Next.js: [8.0.2]

**Comment by timneutkens** [comment]
This is expected behavior. The screen should be cleared though.

**Comment by popuguytheparrot** [comment]
>  The screen should be cleared 

No. Why it expected ?

**Comment by timneutkens** [comment]
What terminal are you using?

It's expected because we want to show users what url / port the app is running on

**Comment by popuguytheparrot** [comment]
> What terminal are you using?
bash
> It's expected because we want to show users what url / port the app is running on

Once is enough to show. Then the developer goes to this address and develops the application.

**Comment by timneutkens** [comment]
> bash with webstorm

Sounds like that is the issue, webstorm probably doesn't clear the screen.

> Once is enough to show. Then the developer goes to this address and develops the application.

I think it's fine to show it after compilation is done. We'll be change it in the future if needed, but as of now it's fine. The compilation output is going to show more information soon.
