### ISSUE TITLE
AWS lambda trying to start Next.js server with target 'serverless' and fails

### ISSUE THREAD

**Issue by ShayMalchi** [zeit/next.js#6406]
# Bug report
When configured with `target: serverless`, AWS lambda fails on:
```
Cannot start server when target is not server. https://err.sh/zeit/next.js/next-start-serverless');
```
This also happens locally when running `next start`.
I am running a custom express server, so instead i have to run locally `node server.js`.

## Describe the bug
Trying to deploy Next.js with a custom server (express) to AWS Lambda with `target: serverless`, and running into the above issue.

## To Reproduce
this is my `next.config.js`:
```
const withSass = require('@zeit/next-sass')
const withCSS = require('@zeit/next-css')

module.exports = withCSS(withSass({
  target: 'serverless',
  webpack(config) {
    config.module.rules.push({
      test: /\.(png|svg|eot|otf|ttf|woff|woff2)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 8192,
          publicPath: '/_next/static/',
          outputPath: 'static/',
          name: '[name].[ext]'
        }
      }
    })
    return config
  }
}))
```
And this is my `server.js`:
```
const express = require('express')
const next = require('next')
const pathMatch = require('path-match')
const path = require('path')
const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const route = pathMatch()
const handle = app.getRequestHandler()
const { parse } = require('url')

app.prepare().then(() => {
  const server = express()
  server.use('/_next', express.static(path.join(__dirname, '.next')))
  server.get('/', (req, res) => {
    const params = {
      ref: req.param('ref')
    }
    return app.render(req, res, '/', params)
  })

  server.get('*', (req, res) => {
    return handle(req, res)
  })

  server.listen(port, err => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
})
```
## Expected behavior
I'm not sure the next server should try to start on AWS lambda, but i'm new to this.

**Comment by timneutkens** [comment]
You can't combine the custom server API with the serverless target. The serverless target is a thing by itself as per the documentation: https://github.com/zeit/next.js#one-level-lower

**Comment by ShayMalchi** [comment]
@timneutkens Thanks. 
What would be the correct way to go about a custom server on using aws lambda?

**Comment by timneutkens** [comment]
You probably shouldn't do that, the serverless target was designed for Lambdas, routing should happen on the proxy layer. This way you get fast cold boot as the lambdas are optimized.

**Comment by ShayMalchi** [comment]
Actually i'm only using custom server for dynamic routing. Would be happy to throw it away...
Is there a known solution for `page/:slug` dynamic routing without using custom server?

**Comment by timneutkens** [comment]
So the way this is handled on Now for example is that you configure it on the proxy layer: https://zeit.co/guides/custom-next-js-server-to-routes/

You can do similar things with nginx, apache etc.

**Comment by ShayMalchi** [comment]
Oh nice! Do you know of a similar way/plugin that allows to do that using the serverless framework?

**Comment by timneutkens** [comment]
I haven't used serverless framework before. But they must have something for that.

**Comment by ShayMalchi** [comment]
Now that I removed the custom server and will handle the routing at the proxy level, how will the dynamic routing will work when running locally (`next`)?

**Comment by ShayMalchi** [comment]
@timneutkens I ended up using Now, thank you. Is there a way to use Now to deploy to AWS Lambda? I see that Universal Now was deprecated in V2.

**Comment by timneutkens** [comment]
Currently the focus is on making Now v2 platform work for all use-cases. It's also that AWS Lambda by itself doesn't cover everything, eg static files hosting, caching, routing etc.

**Comment by timneutkens** [comment]
I'll close this issue as it was resolved 👍

**Comment by ShayMalchi** [comment]
@timneutkens Sure. do you know when this will be available?

**Comment by timneutkens** [comment]
As said:

> Currently the focus is on making Now v2 platform work for all use-cases.
