### ISSUE TITLE
[2.0-beta12] Some dependencies not processed correctly by webpack

### ISSUE THREAD

**Issue by mattapperson** [zeit/next.js#641]
When installing a dependency of react-redux-firebase, web pack is requiring files based on the deps module field rather then the main field. This results in a compile error due to pulling in es6/es7 code without compile as module field points to code not processed by babel, and main points to babel processed code.
I mention this because in v 1.x.x of next.js this dep works just fine.

**Comment by arunoda** [comment]
It's great, if we can have a way to reproduce this issue.

**Comment by mattapperson** [comment]
@arunoda np, ill post an example repo this evening EST (remodeling my new house this afternoon 😊)

**Comment by timneutkens** [comment]
@mattapperson closing this issue for now. Feel free to re-open when you push the example repo ❤️
