### ISSUE TITLE
Require leads to wierd bundlesize overflow 

### ISSUE THREAD

**Issue by dmtrKovalenko** [zeit/next.js#6412]
# Bug report

## Describe the bug
There is no way to import components dynamicly and synchronously. And there no way to use `require.context` 

## To Reproduce
Just use dynamic `require` instead of import somewhere. 
I am developing documentation with next. And in examples I need to dynamicly import components. I want them to be rendered on server, and not just on client, how is `dynamic` doing. 

## Expected behavior
I want to be able use `require` context to restrict bundle of page.

## Screenshots
![2019-02-21 15 09 03](https://user-images.githubusercontent.com/16926049/53260301-cad0de80-36d9-11e9-9bc7-aad3a84d71a4.png)

## System information
 - OS: macOs | Linux 
 - Version of Next.js: ^8.0.0

**Comment by timneutkens** [comment]
Please follow the issue template and provide a clear and concise reproduction and clear description of your issue. It sounds like you want to be able to use `require` like `import()` but split out bundles. This is not a possibility by any of the official specs.

In general you should always use `import` or `import()` (esmodules) in Next.js apps, never `require()` as that is commonjs

**Comment by dmtrKovalenko** [comment]
@timneutkens but there is no way to make `import()` load bundles on server side. Without `...loading`

**Comment by timneutkens** [comment]
It depends on what you're doing, but definitely possible using `next/dynamic`. Alternatively you can use `import()` in getInitialProps.

**Comment by dmtrKovalenko** [comment]
I will be very grateful if you will link some demo of how it’s possible to prerender dinamicly imported component on server with next/dynamic. 
There is nothing about that in next docs and internet :(

**Comment by timneutkens** [comment]
https://nextjs.org/docs#dynamic-import

**Comment by dmtrKovalenko** [comment]
I am really sorry to bother you. But it will render the component like [here](https://material-ui-pickers.now.sh/api/datepicker). With wierd blinking :(

**Comment by timneutkens** [comment]
How does that relate to dynamic imports though 🤔

**Comment by dmtrKovalenko** [comment]
Anyway using import() do not allow you to prerender component on server. I think getInitialProps will help but it doesn’t work for child components. :(
