### ISSUE TITLE
next-manifest works in 8.0.1 but stopped working in 8.0.2

### ISSUE THREAD

**Issue by Yzrsah** [zeit/next.js#6414]
[next-manifest](https://github.com/ragingwind/next-manifest) stopped working @ 8.0.2

Next.js 8.0.1 - works
Next.js 8.0.2 - exporting withManifest() produces:

```
Entry module not found: Error: Can't resolve './src' in '/Users/foo/site'
_document.js chunk not found
```

Looks path.join() broke with webpack inside some dependencies. Some recent changes to webpack setup could have caused this- any ideas?

**Comment by timneutkens** [comment]
Please follow the issue template and provide a clear and concise reproduction of your issue. Preferably in a github repository.
