### ISSUE TITLE
Page hangs forever after upgrading to Next.js 8

### ISSUE THREAD

**Issue by andrerpena** [zeit/next.js#6419]
# Bug report

## Describe the bug

I upgraded from Next.js 7.* to 8.*, using TypeScript, and now the page hangs in `Compiling...`. On the browser, the page loads forever and never display anything. The compilation goes normally but as soon as I access the first page and it tries to compile, it hangs.

## Screenshots
![image](https://user-images.githubusercontent.com/1581429/53285314-5d679100-375f-11e9-946c-a2b1926a73b5.png)

## System information
 - Windows 10
 - Version of Next.js: 8.0.3
 - Version of @zeit/next-typescript: 1.1.1

**Comment by timneutkens** [comment]
Please provide a reproduction.

**Comment by andrerpena** [comment]
I will make a fresh install and try to reproduce. I will close this and open again when I do. Thanks.
