### ISSUE TITLE
nextConfig.publicRuntimeConfig Issue!

### ISSUE THREAD

**Issue by melvin2016** [zeit/next.js#6422]
# Bug

## Describe the bug
the values in the key-value pair of the object retrived from nextConfig.publicRuntimeConfig is automatically getting added a space in the value.

## Expected behavior
The values shouldn't have added space in them.

## System information
 - OS:  Windows
 - Version of Next.js: v8.0.1

**Comment by timneutkens** [comment]
The issue template asks for a reproduction as it's really hard to help / reproduce any issue you run into otherwise.
