### ISSUE TITLE
How do I change `__NEXT_DATA__` to `__INITIAL_STATE__` or other custom variable names?

### ISSUE THREAD

**Issue by Lizhooh** [zeit/next.js#6425]
# Feature request

## Is your feature request related to a problem? Please describe.
How do I change `__NEXT_DATA__` to `__INITIAL_STATE__` or other custom variable names ?

**Comment by revskill10** [comment]
I think you can do it in `getInitialProps` in `_app.js` on browser.

**Comment by timneutkens** [comment]
You can't. It's an internal variable, there's no need to change it.

**Comment by ahmedfaical** [comment]
With nuxt.js we can change this variable. Why can we do this in nuxt and not in next?
