### ISSUE TITLE
How to fetch data async at client-side

### ISSUE THREAD

**Issue by Feel-Joy** [zeit/next.js#6434]
When render at client-side, I want to fetch data async at getInitialProps() method, because this is faster, route switch immediately, at the same time to fetch data, how can I do ?
```js
Post.getInitialProps = async ({ query, req }) => {
  const { id } = query;
  const isServer = !!req;
  if ( isServer ) {
    const { data: show } = await fetchBatman(id);
    return { show }
  } else {
    // how can I do ?
  }
}
```

**Comment by JonatanSalas** [comment]
If you want to use the same method you can do it this way:

```javascript
Post.getInitialProps = async ctx => {
   const { data: show } = await fetchBatman(ctx.query.id);
   return { show }
}
```
`query` object will be available at server/client side, so you don't have to worry about it.

**Comment by timneutkens** [comment]
You could use `componentDidMount` to fetch.
