### ISSUE TITLE
Add example with mobx

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#644]
Some people have had issues using it, so it'd be great to have an example. It's a bit more involved than others since it requires decorator support, so it'll impose a `.babelrc`

**Comment by arunoda** [comment]
@rauchg I hope there's a way to use mobx without decorators too.

**Comment by fdidron** [comment]
Yes it is possible to use it without decorators, I have an example here:

https://github.com/fdidron/mobx-next-example | https://mobx-next.now.sh/

(It includes a lot of other stuff I discovered when using next for the first time :D, maybe a simpler example would be more suited)

**Comment by arunoda** [comment]
@fdidron the question is how many of mobx users decorators or not.
If most of the users use decorators, we need to use decorators in our example.

**Comment by mweststrate** [comment]
Yes it a majority that uses it, I did a poll a while back if I remember correctly it was 70-ish percent, so including decorators as example would be greatly appreciated!

Btw, [mobx-state-tree](https://github.com/mobxjs/mobx-state-tree/) might be very interesting in the future for next as well, as it provides a unified way how to serialize and transfer state (and it is decorator free ;-))

**Comment by arunoda** [comment]
@mweststrate cool. 

I think then we should add the example with a decorator.

**Comment by fdidron** [comment]
@arunoda I'm very happy to help on the example using decorators. Would it make sense to simply port the "with-redux" example ?

**Comment by arunoda** [comment]
@fdidron yeah! That'd be awesome.

**Comment by cncolder** [comment]
Is this so hard to add decorators?
I only put a `.babelrc` and it just worked.

```json
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    "transform-decorators-legacy"
  ]
}
```

**Comment by arunoda** [comment]
@cncolder Nope. It's not that hard :)

**Comment by aranajhonny** [comment]
simple example using decorators.
https://github.com/aranajhonny/next-with-mobx 
demo --> https://next-with-mobx-bnmkseetwa.now.sh/

**Comment by ugiacoman** [comment]
@aranajhonny Very simple, thank you!

**Comment by fdidron** [comment]
@arunoda Here is a PR #676

**Comment by arunoda** [comment]
We got the PR.
