### ISSUE TITLE
is it posible to import one css to each page?

### ISSUE THREAD

**Issue by ivanhuay** [zeit/next.js#6452]
# is it posible to import one css to each page?

I made [this question](https://spectrum.chat/next-js/general/is-it-posible-to-import-one-css-to-each-page~6151cb42-b88f-411a-ab64-a4e44d8c8759) in spectrum with no response.

i found a similar issue here https://github.com/zeit/next-plugins/issues/407

i create a basic example to reproduce the error

* go to `/` index page (red background - `index.css`)
* next to b page `/b` (blue background - `b.css`)
* back to index page `/` (blue background )

https://github.com/ivanhuay/next-css-conflict-example

@zeit/next-css": "^1.0.1", @zeit/next-sass": "^1.0.1", "next": "^8.0.1"

**Comment by jbsmith731** [comment]
See https://github.com/zeit/next-plugins/issues/282
