### ISSUE TITLE
"Rehydrates" NextJS's Static File

### ISSUE THREAD

**Issue by williamli** [zeit/next.js#6456]
When the NextJS's exported HTML file is first loaded into the browser, it does not try to call React's hydrate() to pull in new info from GraphQL. React only kicks in after browsing to other pages on the browser (client side rendering).

In GatsbyJS, their generated html will automatically hydrates once it is loaded in a browser. https://twitter.com/kylemathews/status/1043226318978998272?lang=en

Is there any way to achieve this on a staticly exported NextJS site?

**Comment by timneutkens** [comment]
I'm not sure what you mean, we call `React.hydrate`, there's no difference between SSR and static export there 🤔

**Comment by williamli** [comment]
@timneutkens can i call `React.hydrate` from within a component like inside componentDidMount or do I need to call it outside of the React app?

**Comment by williamli** [comment]
Right now, I have a News page and Home page.
The title of the News page is loaded from GraphQL.

1. Set GraphQL to return “News” as title
2. Build and Export sits to static files
3. Update GraphQL to return “Fake News” as title
4. Open page at news.html, the page loaded in browser, title of site is still “News”
5. Open page at home.html, the page loaded, click a link in home page and it does a client side page load to the news page. The news page is rendered with live data “Fake News” pulled from the GraphQL.

Expected results would be
1. open the news.html page
2. static page loaded with title “News”
3. Rehydrate occurs once everything is ready, “Fake News” is displayed

**Comment by williamli** [comment]
If the static html already does hydrate when rendered, i will double check my code tonight to see if there are any GraphQL caching going on that prevents data to be updated during hydration.

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/blob/canary/packages/next/client/index.js#L152-L160

As you can see we call `.hydrate` I'm assuming you're confusing that the getInitialProps result is part of the initial HTML. In case of Apollo that holds the apollo client cache. So maybe that's the issue you're having. It sounds like you want to trigger Apollo to refetch everything after hydration.

**Comment by timneutkens** [comment]
I'll close this issue as there's nothing to change on the Next.js side, as explained we hydrate the rendered DOM.

**Comment by williamli** [comment]
Yep, I think what I am seeing is indeed Apollo’s client cache.
