### ISSUE TITLE
How to remove hot-self-accept-loader on my old project, if it not work on nextjs v8

### ISSUE THREAD

**Issue by robyhuzwandar** [zeit/next.js#6463]
# Question about Next.js
I have a project with Extjs V6, I can't find any configuration related to Hot-Self-Accept-loader, so I have trouble fixing it

i have error : 

` ./node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?page=%2F&absolutePagePath=%2Fmedia%2Frobyhuzwandar%2FAkademik%2FMandaLabs%2Fproject%2Fshop%2Fweb%2Fpages%2Findex.tsx Module not found: Can't resolve 'hot-self-accept-loader`

package.json :

`{
  "name": "@katt/shop-web",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "dotenv -- nodemon server/index.ts",
    "build": "tsc --project tsconfig.server.json && dotenv -- next build",
    "start": "NODE_ENV=production dotenv -- node dist/",
    "deploy": "now -e GRAPHQL_URL=https://shop-api.kattcorp.co.uk/",
    "alias": "now alias"
  },
  "engines": {
    "node": "10.15.1"
  },
  "dependencies": {
    "apollo-client-preset": "1.0.8",
    "babel-plugin-inline-dotenv": "1.2.1",
    "babel-plugin-transform-inline-environment-variables": "0.4.3",
    "body-parser": "1.18.3",
    "cookie-parser": "1.4.4",
    "express": "4.16.4",
    "graphql": "0.13.2",
    "graphql-anywhere": "4.1.28",
    "graphql-tag": "2.10.1",
    "isomorphic-fetch": "2.2.1",
    "next": "^8.0.3",
    "react": "16.8.3",
    "react-apollo": "2.4.1",
    "react-dom": "16.8.3",
    "react-modal": "3.8.1",
    "request": "2.88.0",
    "request-promise-native": "1.0.7"
  },
  "devDependencies": {
    "@types/body-parser": "1.17.0",
    "@types/cookie-parser": "1.4.1",
    "@types/express": "4.16.1",
    "@types/graphql": "0.13.4",
    "@types/isomorphic-fetch": "0.0.35",
    "@types/lodash": "4.14.121",
    "@types/lodash.flowright": "3.5.5",
    "@types/next": "6.1.8",
    "@types/prop-types": "15.5.9",
    "@types/react": "16.8.5",
    "@types/react-modal": "3.8.1",
    "@zeit/next-typescript": "^0.1.1",
    "concurrently": "4.1.0",
    "dotenv-cli": "1.4.0",
    "nodemon": "1.18.10",
    "ts-node": "8.0.2",
    "typescript": "3.3.3333",
    "webpack-cli": "^3.2.3"
  },
  "now": {
    "alias": [
      "react-prisma-graphql-shopping-cart.kattcorp.co.uk",
      "react-prisma-graphql-shopping-cart.kattcorp.com",
      "shop.kattcorp.co.uk",
      "shop.kattcorp.com"
    ],
    "regions": [
      "bru"
    ]
  }
}
`
Questions should be posted on https://spectrum.chat/next-js

**Comment by timneutkens** [comment]
Sounds like you're adding something to next.config.js that is related to hot-self-accept-loader 🤔
