### ISSUE TITLE
Export crashes when page folder names contain "." character

### ISSUE THREAD

**Issue by azcn2503** [zeit/next.js#6467]
# Bug report

## Describe the bug

When exporting pages that contain a "." character in them, the export operation crashes with the following error:

```
{ Error: EISDIR: illegal operation on a directory, open '/Users/aington/git/next-export-example/out/product/v1.12'
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '/Users/aington/git/next-export-example/out/product/v1.12' }
{ errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '/Users/aington/git/next-export-example/out/product/v1.12' }
error Command failed with exit code 1.
```

Replacing the "." character with something else in the folder name exports successfully.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create a page: `/pages/v1.12/index.js` containing a valid React component.
2. Create a second page: `/pages/v1.12/video.js` containing a valid React component.
2. Run `next export`.
3. Observe the error.

## Expected behavior
The folders should be exported with the correct name, containing the "." character.

## System information
 - OS: MacOS Mojave 10.14.2
 - Version of Next.js: v8.0.3
 - Version of Node.js: v8.12.0

**Comment by azcn2503** [comment]
Thanks guys 👍  very impressed with this project.

**Comment by timneutkens** [comment]
🙌
