### ISSUE TITLE
require doesn't work on next 8, but work on next 7

### ISSUE THREAD

**Issue by dmitweb** [zeit/next.js#6469]
# Bug report

## Describe the bug

Require and import can't resolve files from node_modules, if require path generated dynamically

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Just run example with bug
2. See error

## Expected behavior
Require file without error

## System information
 - OS: Linux
 - Version of Next.js: 8.0.0 - 8.0.3

## Additional context

Git repo with bug: https://github.com/dmitweb/next.js-8-require-bug
Git repo without bug: https://github.com/dmitweb/next.js-7-no-require-bug

**Comment by timneutkens** [comment]
Using dynamic requires is not the best idea anyway as it causes webpack bundle bundle every possible file under that directory.

**Comment by timneutkens** [comment]
I wonder what happened that made it break though.

**Comment by ijjk** [comment]
@dmitweb I just submitted a PR addressing this issue. Thanks for the reproductions, they were very helpful!

**Comment by dmitweb** [comment]
@ijjk awesome, ty
