### ISSUE TITLE
Next8 build fails with: TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by klase** [zeit/next.js#6473]
I'm using webpack-s3-plugin to upload webpack assets to our CDN, but after upgrading to Next 8 the build fails with

`TypeError: path must be a string or Buffer     at Object.fs.open (fs.js:636:11)     at ReadStream.open (fs.js:1996:6)     at new ReadStream (fs.js:1983:10)     at Object.fs.createReadStream (fs.js:1931:10)     at t.exports.uploadFile (.../node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:6689)     at t.map.t (.../node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:6330)     at Array.map (<anonymous>)     at transformBasePath.then (...//node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:6318)     at <anonymous>`

Has anything changed in how next handles custom webpack configs that could cause this issue? The webpack-s3-plugin version and next.config.js are exactly the same as the one working in Next 7.

```
webpack: (config, { isServer }) => {

     config.push(new S3Plugin({
          include: /.*\.(css|js|jpg|gif|svg|png|ico|pdf)/,
          exclude: /.*\.map/,
          s3Options: {
            accessKeyId: 'XXX',
            secretAccessKey: 'XXX',
            region: 'XXX'
          },
          s3UploadOptions: {
            Bucket: 'XXX',
            CacheControl: 'max-age=86400'
          },
          basePathTransform: () => releaseString + '/_next'
        }));
    return config;    
}
```

**Comment by timneutkens** [comment]
Probably related to `futureEmitAssets` https://github.com/zeit/next.js/pull/6114

In theory you could disable it, but you'd opt-out of the massive memory optimization. I guess you'd probably want to use the aws cli to upload to s3 instead.
