### ISSUE TITLE
HMR `ReferenceError` and related errors should render as a red error on the screen

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#648]
Referencing a component that hasn't been `import`ed for example is yielding only an error in the web console, which makes things tedious to debug.

**Comment by nkzawa** [comment]
We do support rendering runtime errors as a red error on the screen, but it's only when it occurred on module loading.

I wonder exactly when we should do this:

- errors on lifecycle methods of React.
- any runtime errors (maybe caches them using `window.onerror`)

I guess you meant about lifecycle methods.

btw usually, we can't handle errors occurred on `render` of React (https://github.com/facebook/react/issues/2461). We'd have to monkeypatch React.
