### ISSUE TITLE
EnhancedComponent inside _document.js's renderPage() function not used to render if getInitialProps of _app.js returns Component key

### ISSUE THREAD

**Issue by ScripterSugar** [zeit/next.js#6480]
# Bug report

## Describe the bug

I found that EnhancedComponent in renderPage() function will not be used if initialProp of App has "Component" key in it, as `{...props}` will override `Component={EnhancedComponent}` row.

It was very hard to trace this as I'm not that familiar with next's resolution order. I was done found this bug after I traced all the way up and down to find out how next behaves, My getInitialProps of _app.js was returning Component key as I used relay-modern with next.js and example of relay-modern that I referenced has code that returns Component within its getInitialProps method in _app.js.

I'm not sure this is bug or not, as there's might be a chance that Component in returned value of _app.js should have some prior order than EnhancedComponent of renderPage() method. But I think it might be great if there's some instruction or warnings showing up when this behavior (Which there's two Component to reference inside renderPage() method) occurs, as it is fairly easy to detect with one or two lines of code, to save someone(like me)'s time.

Or maybe, it can be implemented in the way that EnhancedComponent references Component from App's InitialProps rather than Component itself If there's "Component" key inside InitialProps. Wonder if there's any problem within this implementation.

If there's error within my description please let me know. It's my first time to use next, so there might be some wrong information. Thanks!

**Comment by timneutkens** [comment]
Both `router` and `Component` should be overwritten, so `{...props}` first and then the other props, in development we should throw an error so that the user is aware that they can't override those two 👍

**Comment by timneutkens** [comment]
@ScripterSugar really interesting find btw, no one else has raised this issue before 🙌

**Comment by ScripterSugar** [comment]
@timneutkens  Thanks bro. that's maybe just because my server structure is very complicated, I think. :)
