### ISSUE TITLE
Weird behavior of file-loader with hash as a query string in development

### ISSUE THREAD

**Issue by egorovli** [zeit/next.js#6481]
# Bug report

## Describe the bug

Consider a custom `file-loader` in `next.config.js`:

```js
module.exports = {
  webpack: config => {
    config.module.rules.push(
      {
        test: /\.(?:woff2?)$/,
        include: path.join(__dirname, 'assets'),
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'static/[path][name].[ext]?h=[hash:8]',
              publicPath: `${assetPrefix}/_next/`
            }
          }
        ]
      }
    )
  
    return config
  }
}
```

Note the hash of a file appended as a query string parameter, an allowed way to use it as per https://github.com/webpack-contrib/file-loader.

Now, in production, everything is fine, the file is generated correctly:

```bash
$ ls -lah ./.next/static/assets/fonts/inter
[...] inter-regular.woff
[...] inter-regular.woff2
```

But in development I was getting 404s for requests to these files, and I found out it was generating wrong files:

```bash
$ ls -lah ./.next/static/assets/fonts/inter
[...] inter-regular.woff2?h=bffaed79
[...] inter-regular.woff?h=aebfbb3c
```

I have to mention that I'm using a setup with a custom server (Koa).

## To Reproduce

1. Set up a basic custom server,
2. Use the mentioned above `next.config.js`,
3. Import static files to trigger the `file-loader`,
4. Run your app in development.

## Expected behavior

Correct files are generated both in development and production.

## Screenshots

N/a.

## System information
 - OS: macOS 10.14.3 (18D109)
 - Version of Next.js: 8.0.3

## Additional context

I think the problem may be in using a custom server, although not really sure about it.

**Comment by timneutkens** [comment]
I think this is a bug in the write-file behavior of webpack-dev-middleware 🤔
