### ISSUE TITLE
Next.js 8 is breaking mobx-react-lite

### ISSUE THREAD

**Issue by programbo** [zeit/next.js#6490]
# Bug report

## Describe the bug

Mobx-react-lite `observer` and `useObserver` are silently failing in Next.js 8 + React 16.8.3

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a mobx store
2. Create a function component referencing an observable value from the store
3. Make the component an observer using mobx-react-lite's `useObserver` or `observer`
4. Mutate the observable value

*NOTE: Using a mobx-react (NOT lite) observer worked as expected but but is incompatible with React hooks.*

**Example here: https://codesandbox.io/s/m4l10j80vx?fontsize=14**

## Expected behavior

1. A mobx-react-lite observer should observe and render changes to observables.
2. A mobx reaction should react to mutated observables

Neither of these things 

## Screenshots
In the Next.js example, the observable value updates however neither the observer or reaction are triggered.

![image](https://user-images.githubusercontent.com/1026196/53610830-5af5b300-3c07-11e9-8069-fbe70f620119.png)

## System information
Tested on MacOS and Codesandbox.io (Next.js and CRA)
```
"mobx-react-lite": "1.1.0",
"next": "8.0.3",
"react": "16.8.3",
```

## Additional context

The same component is tested and working as expected with create-react-app - https://codesandbox.io/s/53m7j6y9wx?fontsize=14

**Comment by programbo** [comment]
@FredyC came up with a great working solution to use `useObservable` hook to create the store, rather than a class-based global store. Doesn't explain what went wrong in the first place, but I'm even happier with this style of observable, so hooray for that.

Happy for this issue to be closed unless someone really want to dig down into it.

**Comment by timneutkens** [comment]
I don't think we have an example for mobx-react-lite or do we 🤔 Could you contribute it? 😄

**Comment by timneutkens** [comment]
I'd still like to have an example for this though 🙏

**Comment by FredyC** [comment]
@timneutkens There is a repro in first comment ...

https://codesandbox.io/s/m4l10j80vx

**Comment by timneutkens** [comment]
@FredyC I meant feel free to contribute it to the next.js examples directory 👍

**Comment by FredyC** [comment]
@timneutkens And what about actually fixing it and then you don't need an example because it will work as usual? :) I don't know Next and I have no clue what is it doing with globally scoped variables to break observable behavior.

**Comment by programbo** [comment]
@FredyC Sorry I abandoned this conversation. I made an [example](https://github.com/zeit/next.js/tree/canary/examples/with-mobx-react-lite) a month ago using your solution.
