### ISSUE TITLE
How to remove subfolder name from Next Js URL?

### ISSUE THREAD

**Issue by kaloraat** [zeit/next.js#6495]
I have created bunch of files in pages/user/ folder. I can access them with the following URL:

http://localhost:3000/user/signup
http://localhost:3000/user/signin
http://localhost:3000/user/profile
What I would like to do is remove user/ part so that URL looks like this:

http://localhost:3000/signup
http://localhost:3000/signin
http://localhost:3000/profile
I will be adding more folders inside pages later for posts etc. What is the best way to achieve this?

**Comment by atis--** [comment]
These guides should help:
https://github.com/zeit/next.js#custom-server-and-routing
https://nextjs.org/learn/basics/server-side-support-for-clean-urls

**Comment by kaloraat** [comment]
Thanks atis, it works this way:

```
// for users
server.get("/signin", (req, res) => {
      app.render(req, res, "/user/signin");
    });
// for posts
server.get("/posts", (req, res) => {
      app.render(req, res, "/post/posts");
    });
```

However I have to do this manually for many urls that are in users or posts folder. Is there an easier way?

**Comment by atis--** [comment]
Sure, if there's a pattern to your URLs, you can use create an express route /path/:params/etc or regular expression match params (see express docs for this). If there's no pattern, then you can create a list of which URLs should be mapped to which pages, and then register them with Express within a loop. I mean, in the end, that's what the solution is -- rewriting URLs. In PHP/Apache setup you would put the same thing in .htaccess mod_rewrite rules.
