### ISSUE TITLE
Next Js Router.push is not a function error

### ISSUE THREAD

**Issue by kaloraat** [zeit/next.js#6496]
When I try to redirect using `Router.push()` I get the following error:
`TypeError: next_router__WEBPACK_IMPORTED_MODULE_3__.Router.push is not a function`

I am trying to migrate from create-react-app to next js.

```
const redirectUser = () => {
        if (redirectToSignin) {
            Router.push({
                pathname: "/user/signin",
                query: { message: "Please signin to view profile" }
            });
        }
    };
```

**Comment by timneutkens** [comment]
Not sure what's going on here. Please follow the issue template and provide a full reproduction.

**Comment by kaloraat** [comment]
I had to import like so:
```
// works
import Router from "next/router";
// dont
import { Router } from "next/router";
```
