### ISSUE TITLE
how to work with stateful dependencies

### ISSUE THREAD

**Issue by akoenig** [zeit/next.js#65]
First off, spot on! `next.js` is an awesome idea!

I tried the framework by hacking down an `Index` component which is hooked up to a `firebase` instance. Unfortunately the `firebase` library holds it's state internally, which brakes the component after performing a hard reload:

```js
import React, { Component } from 'react';
import firebase from 'firebase';

class Index extends Component {
  constructor() {
    super();

    this.state = {
      users: []
    };
  }

  componentWillMount() {
    firebase.initializeApp({
      apiKey: '...',
      authDomain: '...',
      databaseURL: '...',
      storageBucket: '...',
      messagingSenderId: '...'
    });

    firebase.database().ref('/users/').on('child_added', data => {
      this.setState({
        users: [...this.state.users, data.val()]
      });
    });
  }

  render() {
    const { users } = this.state;

    return (
      <div>
        {users.map(user =>
          <div key={user.id}>{user.name}</div>
        )}
      </div>
    );
  }
}

export default Index;
```

**Comment by impronunciable** [comment]
Hi @akoenig this is pretty cool. I think you should take a look at the static method `getStaticProps` and the redux example https://github.com/zeit/next.js/wiki/Redux-example

**Comment by akoenig** [comment]
Hi @impronunciable, thanks for your response. Sure, in a "normal" app I would do that with `redux` in combination with `redux-saga` (`eventChannel` + dispatching actions by taking from channel). But for sketching out a prototype it would be also valid to do it in the `componentWillMount` lifecycle hook. Anyways, `getStaticProps` is key here.

Thanks for all!

**Comment by FaridSafi** [comment]
did you mean `getInitialProps` instead of `getStaticProps` ?

**Comment by impronunciable** [comment]
@faridsafi Yes, it it `getInitialProps`. Good catch :)

**Comment by cweekly** [comment]
Nit (for posterity / SERP traffic) - there's no such "redux example" page on the wiki. Try:
https://github.com/zeit/next.js/tree/master/examples/with-redux
