### ISSUE TITLE
Expose Next.js version in next.config.js

### ISSUE THREAD

**Issue by martpie** [zeit/next.js#6507]
# Feature request

This is a highly subjective feature request and I am happy to discuss it.

## Is your feature request related to a problem? Please describe.
When writing Next.js plugins, you sometimes have to have different logic for different versions of Next.js (due to Webpack or Babel breaking changes for example, or even Next.js internal changes).

## Describe the solution you'd like
Expose the version (at least the major?) in `next.config.js` through a key, let's say `version` or `nextVersion` (I'm not inspired) so a plugin can change its behavior based on Next.js version.

## Describe alternatives you've considered
A solution to this problem is to maintain different branches for a plugin, and publish them separately with different major numbers. But it is quite painful and can be a lot of work for the plugin maintainer, and make backport fixes a pain too.

Dropping support for earlier version of Next.js is a alternative too, but transition takes time (I guess some projects can take months before upgrading Next.js)

Parsing `package.json` could be done too, but I do not want to install the `semver` package just for that.

## Additional context
n/a

**Comment by martpie** [comment]
In https://github.com/martpie/next-transpile-modules/issues/29, a user noticed this plugin broke with Next.js 8.1.0. After 2 minutes, I figured out it was because of this:

```
config.externals = config.externals.map(external => {
        if (typeof external !== 'function') return external;
        return (ctx, req, cb) => {
          return includes.find(include =>
            req.startsWith('.')
              ? include.test(path.resolve(ctx, req))
              : include.test(req)
          )
            ? cb()
            : external(ctx, req, cb);
        };
      });
```

which is a little bit annoying, but manageable.

@timneutkens Would you accept a PR for this feature request?

**Comment by Timer** [comment]
I'm not sure it's worth the extra API surface for this feature. I'd just `require('next/package.json').version) and go from there.

**Comment by martpie** [comment]
Fine with that :) thank you
