### ISSUE TITLE
Any plans to support something other then inline styles like PostCSS, CSS Modules and node-sass?

### ISSUE THREAD

**Issue by Ajar-Ajar** [zeit/next.js#651]
Is there any reason why all Styling examples use inline CSS solutions?
Are there any plans to support popular pre-processors like [node-sass](https://github.com/sass/node-sass), [PostCSS](http://postcss.org/) or [CSS Modules](https://github.com/css-modules/css-modules)?
Is there a way to preprocess and use those for universal/server rendering?

CSS Modules is a popular solution for modular CSS (obviously...:), Many [PostCSS plugins](http://postcss.parts/) like rucksack for [responsive font-size](http://simplaio.github.io/rucksack/docs/#responsive-type), [px-to-rem](https://github.com/cuth/postcss-pxtorem) and [autoprefixer](https://github.com/postcss/autoprefixer) among others are indispensable...

Is there a way to use postcss and add its configuration to the underlying webpack config? 

Is it possible to get an idea or better yet - an example or a guide that demonstrate how precompile/preprocess those solutions using them with Next 2.0.0-beta.xx ?

Thank you so much!
Ajar

**Comment by nkzawa** [comment]
I think you can just compile CSS before starting `next` and load the generated file using `<Head />` or custom `Document`. Do you like to know something else ?

**Comment by arunoda** [comment]
@Ajar-Ajar check this PR and issues mentioned in that.
See: https://github.com/zeit/next.js/pull/638

**Comment by iamjacks** [comment]
I stopped using sass and css files, but when I did use them I was doing what @nkzawa suggested. I made a head component that acted as a wrapper for next/head to handle easily loading defaults/globals such as a main.css stylesheet. It accepted props and children to change the page title and extend it (e.g: adding another stylesheet file to the head etc.)

**Comment by timneutkens** [comment]
Closing this based on given answers. Feel free to re-open when needed ❤️
