### ISSUE TITLE
Cause FOUC on V8 of production env

### ISSUE THREAD

**Issue by Cedcn** [zeit/next.js#6519]
**Perhaps the Dom is rendered before the style.**

 **I used packages:**
 "next": "^8.0.2",
 "@zeit/next-css": "^1.0.1",
 "@zeit/next-less": "^1.0.1",

Note: That's ok on V7 (i tested on 7.0.2)

**Comment by timneutkens** [comment]
Please follow the issue template and provide a clear and concise reproduction of your issue, otherwise it's hard for us to help you.
