### ISSUE TITLE
Use compose and process env

### ISSUE THREAD

**Issue by ShintaroNippon** [zeit/next.js#6522]
Hi there...
I have this code
and I'm using latest version of next js... 

```
const compose = require("next-compose");
const withCSS = require("@zeit/next-css");
const withSass = require("@zeit/next-sass");
const withImages = require("next-images");

module.exports = compose([
  withCSS,
  withSass,
  withImages,
  {
    env: {
      server: "http://localhost:3000"
    }
  }
]);

```

and I'm asking it is possible to use env with compose
because currently, I'm getting process env as undefined...!

Thanks in advance
Carlos Vieira

**Comment by timneutkens** [comment]
next-compose is a community plugin, so I'm not sure why it wouldn't work.
