### ISSUE TITLE
Disable stdout clearing

### ISSUE THREAD

**Issue by mcmillion** [zeit/next.js#6525]
(There may be a way to do this currently, but after asking a few times on Spectrum and looking through the changes for adding Webpackbar I haven't found anything)

## Is your feature request related to a problem? Please describe.
When running Next in something like docker-compose the refreshing output constantly clears and mangles the log output.

## Describe the solution you'd like
I'd like a way to disable this so that log output is just a stream and not constantly rerendered.

Edit: This includes local development as well.

**Comment by Timer** [comment]
@mcmillion what version of Next.js are you on?

**Comment by Yzrsah** [comment]
@Timer, he's looking for a solution to get easier console logging without control codes from Webpackbar clearing the screen

**Comment by Janpot** [comment]
🤔  For me, this behavior actually started when I went to version 8. Would love to have [more control](https://github.com/zeit/next.js/issues/4808) over logging altogether though.

**Comment by mcmillion** [comment]
Yeah I'm currently on `8.0.0`, so I'm not sure how trying `8.0.3` helps me unless it added some kind of configuration to disable this.

**Comment by mcmillion** [comment]
I guess I should add that my original question was specifically in regards to local development. When running a dev environment in docker (or something like Foreman) that merges the log output from multiple processes/containers, Webpackbar seems to obliterate that output every time it runs.

**Comment by ellisio** [comment]
@Timer I actually just came here trying to figure out how to get this progressbar back. We switched from 8.0.0 to 8.0.3 and noticed the progressbar was gone. Is it possible to enable this based on an envvar we set perhaps? That way it can be enabled for developer machines, but disabled on CI?

**Comment by mcmillion** [comment]
`8.0.3`'s output is _different_, but it still clears the log when rebuilding in dev

**Comment by Timer** [comment]
> Yeah I'm currently on 8.0.0, so I'm not sure how trying 8.0.3 helps me unless it added some kind of configuration to disable this.
> @mcmillion 

v8.0.2 completely changed the logging so it'll likely have a significant impact on the output you're seeing.

**Comment by radeno** [comment]
Same issue. It clears almost all output. With `webpackbar` we don't have any issues before. Very clear interface, good readable.
This new "profiler" removes a lot of debug informations.
For example all info from Webpack are cleared. No Info in terminal from `webpack-bundle-analyzer` or  `inspectpack` and so on.

**Comment by illarionvk** [comment]
I experience the same issue when running Next.js in dev mode with [Honcho](https://honcho.readthedocs.io/en/latest/) (Python port of [Foreman](https://github.com/ddollar/foreman)) alongside other processes.

Next.js clears the console every time it recompiles, and I cannot see log messages from my other processes that happened just before recompilation.

![missing-log-messages](https://user-images.githubusercontent.com/5012724/54629355-b46b3800-4a77-11e9-8979-253287c49e1f.png)

**Comment by jaycenhorton** [comment]
I would also appreciate this feature. 

Also (I'm not sure how related this is), was there a recent change that disabled to compilation time output? After upgrading to next8 I no longer get the `Compiled successfully in x ms` type logs in my console.

**Comment by Yzrsah** [comment]
As a workaround you can use `yarn dev 2> next-errors.log`.
Alternately with `yarn dev > next.log` the error pipe is not redirected so you will see only see errors.
Or log both with `yarn dev 2>&1 > next.log`

**Comment by zacksinclair** [comment]
+1 for this feature. A config option to disable this: https://github.com/zeit/next.js/blob/78bcfa07b2b3f495d7bf4d215b9f5442802fcdf6/packages/next/build/output/store.ts#L24-L27

**Comment by justinmchase** [comment]
Please 👍 my PR ^ for exposure.
