### ISSUE TITLE
Prefetch causing button to keep hover state

### ISSUE THREAD

**Issue by msauberPrincipal** [zeit/next.js#6536]
# Bug report

## Describe the bug

Prefetch causing button to keep hover state when navigating to same page with different query parameters. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. https://start-the-convo-app-staging.herokuapp.com
2. Click Take the Quiz
3. Click past name questions until you get to "Do you have children?" question. 
4. Click yes and notice yes button will be in hover state for "Do you have a house" question
5. This is only on IOS (Safari and Chrome). Currently we are removing the colors for hover state so you will have to inspect dom to see the button is in a hover state

## Expected behavior
The button will not be in hover state after navigating from page to page.

## System information
 - OS: IOS
 - Browser: [chrome, safari]
 - Version of Next.js: [e.g. 8.0.0]

## Additional context

We have been following this example for prefetching with nextjs and apollo using Router.push https://shaleenjain.com/blog/nextjs-apollo-prefetch/

**Comment by timneutkens** [comment]
This doesn't sound like a Next.js issue or bug, more like a usage issue. Can you post your question on https://spectrum.chat/next-js 🙏 Thank you!
