### ISSUE TITLE
Cannot find module SVG File

### ISSUE THREAD

**Issue by Gmulti** [zeit/next.js#6539]
# Bug report

## Describe the bug

Unable to deploy on now v2. I receive an error: 
**Error: Cannot find module '.../../../../static/img/logo.svg'**

I have no problems during development

## To Reproduce

The example with svg does not work either.
https://github.com/zeit/next.js/blob/canary/examples/svg-components/pages/index.js

## Expected behavior
Attempt to deploy on the v2 platform.
No problem on v1

## System information
 - macOS
 - Chrome
 - Version of Next.js: latest

## Additional context

Config now : 
`{
    "version": 2,
    "name": "test-staging",
    "public": false,
    "builds": [
        {
            "src": "next.config.js",
            "use": "@now/next"
        }
    ]
}`

**Comment by timneutkens** [comment]
The `static` directory is not downloaded as it's only static files and downloading them would be slow especially with a lot of assets in the static directory. If you want to import files you'll have to move them to another directory.
