### ISSUE TITLE
Please fix SSR bug with GraphQL with Apollo and update "with-apollo" examples

### ISSUE THREAD

**Issue by resdevd** [zeit/next.js#6542]
Using "with-apollo" example with Next v8 breaks SSR.
Can you please update it?

**Comment by MarchWorks** [comment]
Check with this package.json
`{
  "name": "with-apollo",
  "version": "2.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "apollo-boost": "^0.3.1",
    "graphql": "^14.0.2",
    "isomorphic-unfetch": "^3.0.0",
    "next": "^8.0.3",
    "prop-types": "^15.6.2",
    "react": "^16.8.4",
    "react-apollo": "^2.5.2",
    "react-dom": "^16.8.4"
  },
  "author": "",
  "license": "ISC"
}
`

**Comment by ijjk** [comment]
@resdevd I just pulled down the example using `yarn create next-app --example with-apollo with-apollo` and ran both dev mode and production mode and SSR is working fine for both.

I'm going to close this, if you're able to reproduce it somehow feel free to comment with additional details.
