### ISSUE TITLE
Proxy with different subpath?

### ISSUE THREAD

**Issue by aralroca** [zeit/next.js#6544]
I'm doing:

`npm run build && npm start`

And instead of open `http://localhost:3000`, I'm using a proxy with another subpath `http://localhost:8000/example`.

The proxy is simple:

```js
const express = require('express')
const proxy = require('http-proxy-middleware')

const options = {
  target:'http://localhost:3000/',
}
const exampleProxy = proxy(options)
const app = express()

app.use('/example', exampleProxy)
app.listen(8000)
```

However, when I open the `http://localhost:8000/example` url is loading the home page but without styles, statics, javascript... Anything...

How can I do it correctly?

Thank you so much!

**Comment by timneutkens** [comment]
Please follow the issue template and post questions on https://spectrum.chat/next-js
Thanks.
