### ISSUE TITLE
Missing a prefix option

### ISSUE THREAD

**Issue by cncolder** [zeit/next.js#656]
For now. I can't find a way to runing my next project under a sub path eg. `http://localhost:3000/myapp/`.
I try to write custom server by myself. But `/_next/main.js`, `/_next/commons.js` and `/static/` still read from root path.

If there is a `prefix` option that I can set `next start --prefix=/myapp` or `const client = next({dir: '.', dev, prefix: '/myapp'})`. It will work with nginx `proxy_pass` easily.
Similar prefix in react-router or homepage in create-react-app.

This make us can put more than one next project under same domain name also.

**Comment by arunoda** [comment]
Here's a previous related issue on this topic.
https://github.com/zeit/next.js/issues/596

**Comment by cncolder** [comment]
This is a different issue.
Param routing cannot custom internal scripts path.

Image this:
I have two next app running on `http://example.com/blog` and `http://example.com/product`. These two app cannot share `/_next/main.js` and another common files.

**Comment by nkzawa** [comment]
@cncolder this should be https://github.com/zeit/next.js/issues/257

**Comment by cncolder** [comment]
@nkzawa Yes I subscribe that.
