### ISSUE TITLE
Need to persist url params across pages

### ISSUE THREAD

**Issue by dhinezh** [zeit/next.js#6560]
Hi, we are using nextjs 7.0, we need to persist some parameters across certain pages and not get reset even when the page is refreshed. 

 Example: " /Home?data=somedata" has to be maintained when navigated to another page, like "/About?data=somedata". This has to be persisted across pages. And even when the page is refreshed, the data has to be there.

**Comment by timneutkens** [comment]
Please follow the issue template and point your question on https://spectrum.chat/next-js.
