### ISSUE TITLE
AMP - Add support for creating AMP pages

### ISSUE THREAD

**Issue by Timer** [zeit/next.js#6568]
AMP pages should be opt-in following convention.

The current proposed behavior is to create a file in the `pages/` directory with the `.amp.js` extension.

If a page exists as both `.js` and `.amp.js`, it should be able to be rendered with or without AMP-mode (toggled via `?amp=1`).

**Comment by timneutkens** [comment]
This behavior still needs to be discussed more though. We're not entirely sure yet on the `.amp.js` convention.
