### ISSUE TITLE
Build error inside alpine-node docker image: `Error: spawn git ENOENT at Process.ChildProcess._handle.onexit`

### ISSUE THREAD

**Issue by ccambournac** [zeit/next.js#6573]
# Bug report
`next build` command fails upon building artefact inside a Docker container prior to deployment. 

## Describe the bug
When building an artefact on Microsoft TFS inside a node-alpine docker image, build fails with the following error due to probably missing git dependency:
```
$ next build
Creating an optimized production build ...

> Build error occurred
{Error: spawn git ENOENT at Process.ChildProcess._handle.onexit 
(internal/child_process.js: 240: 19) at onErrorNT (internal/child_process.js: 415: 16) 
at process._tickCallback (internal/process/next_tick.js: 63: 19) errno: 'ENOENT', 
code: 'ENOENT', syscall: 'spawn git', path: 'git', 
spawnargs: ['--git-dir=/app/.git', '--work-tree=/app', 'rev-parse', 'HEAD'], 
cmd: 'git --git-dir=/app/.git --work-tree=/app rev-parse HEAD'}
```

## Expected behavior
Successful next.js build without the need of having git contained in the Docker container.
Indeed, when including Git to the Docker container, le build is successful.

## System information
 - OS : Alpine Linux
 - Version of Next.js: 8.0.3
 - Version of Node.js: 10.15.1

## Additional context
The build command is successful on other OS (tested on Windows, Mac, Ubuntu Linux).
[5_yarn build.txt](https://github.com/zeit/next.js/files/2944974/5_yarn.build.txt)

**Comment by timneutkens** [comment]
Looks like this is unrelated to Next.js, rather it's `Error: spawn git ENOENT` something you've added to your application is trying to run `git` which is probably not installed in the image.

**Comment by ccambournac** [comment]
Right, thanks! Indeed due to [next-build-id](https://github.com/nexdrew/next-build-id/issues/9) package.
