### ISSUE TITLE
Docs outdated about package.json 

### ISSUE THREAD

**Issue by DamianMoralesM** [zeit/next.js#6574]
# Bug report

 In the Learn and Docs section the package.json indicates that scripts should be like:

"scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
**but**  if you run the command **NPM RUN DEV** the app doesn´t work and shows the error:  _You may need an appropriate loader to handle this file type._

![image](https://user-images.githubusercontent.com/27656018/54028582-458f0480-4184-11e9-831c-9b998421b44b.png)

### Solution

In the scripts should be add **"export": "next export"** like this:

 "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "export": "next export"
  }

if you type again NPM RUN DEV it works: 

![image](https://user-images.githubusercontent.com/27656018/54028925-7f143f80-4185-11e9-91fc-a58f71ad781c.png)

**Comment by timneutkens** [comment]
it sounds like you have a `.babelrc` or `babel.config.js` somewhere up the directory tree from where you started the project 🤔
