### ISSUE TITLE
null Showing up in Nextjs console

### ISSUE THREAD

**Issue by abominab** [zeit/next.js#6580]
# Bug report

## Describe the bug

Right after running `npm run dev` without visiting any app pages in my browser, null will start to show up on my server console. 

## To Reproduce
1. `npm run dev`
2. Don't view any app pages
3. Just wait and watch server console

## Expected behavior
No null logs

## Screenshots
![image](https://user-images.githubusercontent.com/10157407/54047527-80993400-4194-11e9-96d4-2e7125157475.png)

## System information
 - OS: Windows 10
 - Version of Next.js: 8.0.3

**Comment by Timer** [comment]
We cannot reproduce this on `canary`. Are you sure this isn't caused by a customization in `next.config.js`?

The only way we'll be able to inspect this further is if you provide a repository with a reproduction.
Thanks!
