### ISSUE TITLE
Redirects to '/' on page refresh in production mode

### ISSUE THREAD

**Issue by dstrtop1** [zeit/next.js#6619]
Hi, all! I'm new to Next.js and got some problems with production. While developing app everything works fine! Routes are okay, 404 works fine too.

My routes are like: '/purchase/cart'.

However, in production, every url ends with '/' => '/purchase/cart/', was using 'next/link', after switching to 'next-router' the problem persisted.

Moreover, when i refresh page, the content is changed to content of '/' page, but the url is the same and it seems like the production mode doesn't see _error.js file (automatically loads the content of '/' page)

Unfortunately, i cant reproduce this behaviour and upload it somewhere since I don't know how to trigger these errors :(

**server.js**
```
const next = require('next')
const routes = require('./routes')
const app = next({ dev: process.env.NODE_ENV !== 'production' })
const handler = routes.getRequestHandler(app)
const express = require('express')
app.prepare().then(() => {
  express().use(handler).listen(3000)
})
```
**package.json**
```
"next": "^7.0.2",
"next-routes": "^1.4.2",
```
I will be thankful for any helpful information! Ping me for any extra information. Have a good day!

**Comment by MarchWorks** [comment]
Post your `routes` file and one example of a `Link` tag

**Comment by dstrtop1** [comment]
@MarchWorks 
**routes.js**
```
const routes = require('next-routes')

module.exports = routes()
  .add('catalog')
  .add('purchase/cart')
  .add('purchase/delivery')
  .add('purchase/payment')
  .add('history')
  .add({ name: 'thanks', pattern: '/purchase/thanks/:id', page: 'purchase/thanks' })
  .add({ name: 'confirm-email', pattern: '/accounts/confirm-email/:id', page: 'accounts/confirm-email' })
  .add('profile')
```
**Link example**
```
import { Link } from '../../routes'
...
<Link route="/purchase/cart">
   <a>
       Cart
   </a>
</Link>
```

**Comment by timneutkens** [comment]
Please follow the issue template and post the question on https://spectrum.chat/next-js Thanks! 🙏
