### ISSUE TITLE
Dynamic import inside getInitialProps  get undefined in browser

### ISSUE THREAD

**Issue by Hoofoo-WHU** [zeit/next.js#6623]
# Bug report

## Describe the bug

Dynamic import inside getInitialProps  get undefined in browser.

## To Reproduce
```tsx
static getInitialProps = async ({ query }: NextContext<{ title: string }>) => {
  const  Component = dynamic(() => import(`../components/${query.title}`))
  return { Component }
}
render() {
  const { Component } = this.props
  console.log('Component:', Component)
  return ''
}
```
## Expected behavior
Log the component object

## Screenshots
<img width="278" alt="image" src="https://user-images.githubusercontent.com/9783165/54195839-b757ad00-44fa-11e9-8c65-9bb49ff6b823.png">

## System information
 - OS: macOS
 - Version of Next.js: 8.0.3

## Additional context
It's work on server

<img width="634" alt="image" src="https://user-images.githubusercontent.com/9783165/54196404-4c0eda80-44fc-11e9-813c-b11a36859a7e.png">

**Comment by timneutkens** [comment]
`dynamic()` has to be used in the top level, otherwise it won't work.
