### ISSUE TITLE
.includes is called before polyfills are loaded

### ISSUE THREAD

**Issue by justinmchase** [zeit/next.js#6629]
# Examples bug report

## Example name
With Polyfills

## Describe the bug
This is a polyfill example but it is using `.includes` before it loads the polyfills. `.includes` itself is not available before ES2016 and so depending on how far back you go in testing this would crash I believe.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Run this example on any ES5 browser

## Expected behavior
The polyfills are loaded and the example works as expected

## Additional context

This line specifically, it seems like it should be using `.indexOf(...) < 0` since this is runs before the polyfills load.

https://github.com/zeit/next.js/blob/canary/examples/with-polyfills/next.config.js#L9

**Comment by timneutkens** [comment]
> This line specifically, it seems like it should be using .indexOf(...) < 0 since this is runs before the polyfills load.
> /examples/with-polyfills/next.config.js@canary#L9

`next.config.js` should never be loaded in the browser, at least it won't by default 🤔

**Comment by justinmchase** [comment]
I see, ok thanks. I didn't have time to fully vet this but wanted to double check the reasoning about it.
