### ISSUE TITLE
how can I debug the request?

### ISSUE THREAD

**Issue by robert7git** [zeit/next.js#6634]
1, I run yarn dev.
2, I refreshed my browser.
3, the browser still in loading state...
4, In terminal, I got nothing.
still says:
Compiled successfully!
  > Ready on http://localhost:3000
Note that pages will be compiled when you first load them.

here is the question.
how can I debug my code？
dose Next.js have a debug mode?

thanks.

**Comment by Timer** [comment]
Hi @robert7git! These general support requests [belong on Spectrum](https://spectrum.chat/next-js).

Please create a new thread there asking for help, thank you!
