### ISSUE TITLE
js error in client after next build

### ISSUE THREAD

**Issue by Yaxian** [zeit/next.js#6640]
# Bug report

## Describe the bug
js error in client after next build

## Expected behavior
In browse, it seems [line 22](https://github.com/zeit/next.js/blob/ff7299d1841be8a021bd4a707b98c78600422351/packages/next/client/index.js#L22) not work

## Screenshots
![image](https://user-images.githubusercontent.com/9707805/54266373-3bb93700-45b2-11e9-9634-c828034b7642.png)
![image](https://user-images.githubusercontent.com/9707805/54266417-4d024380-45b2-11e9-8038-f8777eb86ad4.png)

## System information
 - OS: macOS
 - Browser: chrome
 - Version of Next.js: 8.0.3

**Comment by timneutkens** [comment]
Please follow the full issue template and provide a reproduction.
