### ISSUE TITLE
Next 7.0.3 with .babelrc publish with "now" failed

### ISSUE THREAD

**Issue by aorsten** [zeit/next.js#6641]
# Bug report
Unsure whether this is a bug with Now, or with NextJS 7.0.3.

I am developing an app in next.js, and am using Zeit Now v2 for publishing it serverless to production.
It has been working great until yesterday.

Yesterday I made some changes to the project and tried to publish, but the now command failed at "next.config.js". The main change I had made was to add a custom .babelrc file and the dev-dependency `@babel/preset-env`:

```
{
    "presets": [
        ["next/babel", {
            "preset-env": {
                "targets": {
                    "browsers": [">0.03%"]
                },
                "useBuiltIns": "usage"
            }
        }]
    ],
    "plugins": []
}
```

Also, I had updated next (by accident) from 7.0.2 to 7.0.3. 

To resolve the issue, I just had to roll back to next 7.0.2 - and suddenly the "now" command worked.

I'm sorry I don't offer reproduction code for the bug, but I thought it worthwhile to report. Perhaps this is known already?

**Comment by Timer** [comment]
> I'm sorry I don't offer reproduction code for the bug, but I thought it worthwhile to report. Perhaps this is known already?

Sorry, but without reproduction there's nothing we can do to help. Others haven't reported a similar issue, so please provide a reproduction.

Thank you!

**Comment by aorsten** [comment]
That's completely fine, @Timer. I got it working on my end, and unfortunately don't have time to dig into what the issue is with Next 7.03 vs Now.
