### ISSUE TITLE
how to generate data for SEO from getInitaiProps

### ISSUE THREAD

**Issue by shipcake** [zeit/next.js#6645]
example URL https://material-ui.com/getting-started/comparison/ 
Data URL is Show in google index when searching. (getting-started/comparison/ )

i can't understand if i use getInitailProps fetch data from  Database with ExpressJS  (product/xxx/xxx) data might change  when i  update Database. Nextjs getInitialProps Cycle Fetch a new Data When User Get from URL (Cloud  Deployment Server PM2 Process + ExpressJS) And Google SEO can Detect Every URL  Like https://material-ui.com/getting-started/comparison/ in google index

(I found Idea To Generate Nextjs Sitemap when deployment. but a new Data from database in future how to tell the Nextjs know a new url)

**Comment by c0b41** [comment]
use custome server, send sitemap with proxy realtime

example
```js
server.use('/sitemap', proxy({
      target: `${process.env.API_URL}/sitemap`,
      pathRewrite: { '^/sitemap': '/' },
      changeOrigin: true
}))
```

**Comment by Huvik** [comment]
If you want to have everything for seo and you have dynamic content, there are two options:
* Redeploy on every change in database with public content (this could be really resource hungry with offten chnaged content)
* Have server what serves your routes and returns dynamic sitemap depending on your data

**Comment by lfades** [comment]
Hi @shipcake please follow the issue template 🙏 , also for questions go to our [Spectrum community](https://spectrum.chat/next-js)

All pages have SSR so as long as you use `getInitialProps` and the page has content by the time it's send to the browser, then you'll have SEO for the page, it doesn't matter if you're using dynamic urls, just make sure that your page renders properly without having to wait for javascript to load and that you have links for any additional content.

If you have any more doubts please feel free to join us in [Spectrum](https://spectrum.chat/next-js).
