### ISSUE TITLE
My non-next.js node app is loggin GET /_next/on-demand-entries-ping?page=/ when I start it?

### ISSUE THREAD

**Issue by federicosan** [zeit/next.js#6650]
# Bug report

## Describe the bug

1 - Learning Next.js tutorial on a different folder project on windows 10. So next.js is was installed locally to that project.
2 - Different project on a different folder, node.js app, with NO next.js when running with node app.js logs GET /_next/on-demand-entries-ping?page=/ nonstop.

## System information
 - OS: Windows 10
-console  CMD
 - Browser chrome

**Comment by federicosan** [comment]
-- self-resolved: had  to comment out the logger app.use.(morgan(dev)) the strange thing is that Morgan is installed on a different app with no next.js, so something is going on with this being logged by Morgan, I want to know why is this happening. This was not happening before installing next.js on a different project.

**Comment by timneutkens** [comment]
Not sure what happened here without a reproduction.

**Comment by federicosan** [comment]
> Not sure what happened here without a reproduction.

@timneutkens While working on windows 10, installing next on one project made the morgan package on a totally different node project constantly logged GET /_next/on-demand-entries-ping?page=/  to the console.
