### ISSUE TITLE
Cannot run `next export` with antd examples

### ISSUE THREAD

**Issue by ceddybi** [zeit/next.js#6653]
## Example name
All examples with antd

## Describe the bug
Cannot run `next export` 
Always gets an error with `SyntaxError: Invalid or unexpected token` with the antd css file from node_modules

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to any example with `antd`
2. Download and build example
3. Then export

## Expected behavior
Supposed to export static site

## System information
 - OS: Linux
 - Version of Next.js: 8.0.3

**Comment by kheruc** [comment]
I can confirm that antd examples don't work when `next export` is used.
This could be a related issue: https://github.com/zeit/next-plugins/issues/85

**Comment by timneutkens** [comment]
Duplicate of #6384
