### ISSUE TITLE
Error after deploying on NOW

### ISSUE THREAD

**Issue by numbofathma** [zeit/next.js#6657]
Hey guys,

I have my project:
https://github.com/numbofathma/roninmobile
successfully deployed on now:
https://roninmobile-boaxvpc5o.now.sh/
but in the console I get:
"TypeError: Cannot read property 'react' of undefined".

Any ideas? (Is my first project with next.js and now)

Thanks!

**Comment by ijjk** [comment]
@numbofathma This looks like it's due to the way you're handling `react-loader-spinner`. It works fine when removing `react-loader-spinner`. This also occurs locally and not just after deploying to now

**Comment by numbofathma** [comment]
Awesome! How did you identified that so I know were to look next time? What did you run? I've built the project locally and I just can get that error :( What did you do? :-S
Thank you! 👍

**Comment by numbofathma** [comment]
Fudge... I forgot I ran npm update last night :| Sorry :( Ummm I'll handle it, you can close it! Pffff!
Thank you very much!
