### ISSUE TITLE
no progress bar showing after v8.0.2

### ISSUE THREAD

**Issue by Fonger** [zeit/next.js#6662]
# Bug report

## Describe the bug
next.js shows no building progress after 8.0.2+

## To Reproduce
1. install next.js 8.0.1
2. run `next` and there's build progress
3. install next.js 8.0.2 or 8.0.3
4. run `next` and there's no build progress
5. install back next.js 8.0.1
6. run `next` and there's build progress.

so this breaks after 8.0.2

## Expected behavior
next.js should show building progress in 8.0.2 8.0.3

## Screenshots
8.0.1 `next`
![image](https://user-images.githubusercontent.com/5862369/54388337-7ae1a800-46d8-11e9-90c5-cf8a2e70560f.png)

8.0.2 or 8.0.3 `next`
![image](https://user-images.githubusercontent.com/5862369/54388521-d7dd5e00-46d8-11e9-878c-cdddd8402ecc.png)
![image](https://user-images.githubusercontent.com/5862369/54388538-e0ce2f80-46d8-11e9-93c8-1f0baef523e0.png)

## System information
 - OS: Ubuntu 18.04
 - Version of Next.js: 8.0.2, 8.0.3

**Comment by Timer** [comment]
This was done for performance reasons. You're welcome to add it back yourself (Webpack Bar).

Thanks!

See previous comment: https://github.com/zeit/next.js/issues/4016#issuecomment-471861486
