### ISSUE TITLE
Migration to Nextjs server-side rendering  from react client-side rendering - Help needed

### ISSUE THREAD

**Issue by vicky3399** [zeit/next.js#6676]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

the project was in written reactgo having in client-side rendering in mind, but after completion of the project, we realized that we need server-side rendering.  what are my options to get the server-side rendering without rewriting all code in nextjs. 

My project is a bit complex. I found one article, does this help. any information to solve my issue would be greatful.
https://medium.com/@vilvaathiban/nextjs-convert-client-side-react-app-to-server-side-rendering-in-5-mins-2106ad69f5a5.

Please help me if they are any other options.

**Comment by kheruc** [comment]
Questions like this should be posted only on Spectrum, I replied there.
