### ISSUE TITLE
How to strip flow notation from serveside custom code?

### ISSUE THREAD

**Issue by ValSol** [zeit/next.js#6679]
# How to strip flow notation from custom serverside code?

If define flow types, for example, in **server.js**:
`type Port = number;`

when run `yarn dev` get the error:

```
type Port = number;
     ^^^^
SyntaxError: Unexpected identifier
```
`babel-plugin-transform-flow-strip-types` strips flow notation only from regular client-side code. How to do it for serverside code such as **server.js**?

**Comment by timneutkens** [comment]
Next.js does not touch server.js, it's the entrypoint to Next.js itself.

**Comment by ValSol** [comment]
Very thanks! You helped me to come to that solution:

1. Create **serverside** and **serverside_withoutflow** folders
2. Move all serverside code into **serverside** folder
3. Install **flow-remove-types CLI**

`yarn add flow-remove-types`

4. Edit **package.json**

```
  "scripts": {
    "prepublish": "flow-remove-types serverside/ -d serverside_withoutflow",
    "dev": "yarn run prepublish && node serverside_withoutflow/server.js",
    "start": "yarn run prepublish && NODE_ENV=production node serverside_withoutflow/server.js",
  },
```
5. Add this line to **.gitignore**

`/serversidewithoutflow/*`
