### ISSUE TITLE
Drop user <script> tags

### ISSUE THREAD

**Issue by Timer** [zeit/next.js#6688]
When the user includes a custom `<script>` tag on an Amp page, we should remove it before streaming the response to the client.

This should probably happen before we run Amp validation because we can give a better error to the user about what's going on. We can swap these orders in the future.

This will ensure users don't see behaviors which shouldn't be possible.

**Comment by timneutkens** [comment]
Ideally this would be detected at compile time.

**Comment by BosenY** [comment]
I think we need a tag to determine if the page is an AMP page, so we can build both AMP and normal pages in one app.
