### ISSUE TITLE
Potential build performance regression

### ISSUE THREAD

**Issue by oliviertassinari** [zeit/next.js#6690]
# Bug report

## Describe the bug

We have noticed a +10min build increase upgrading from Next.js v8.0.1 to v8.0.2: https://github.com/mui-org/material-ui/pull/14924#issuecomment-473705316.

## To Reproduce

I'm not sure how to reproduce the problem. Are we the only one to notice a difference? (We have also noticed that webpackbar report is gone, it could be related).

## System information
 - Version of Next.js: 8.0.2

**Comment by timneutkens** [comment]
Try `next@canary` main difference is that we (unexpectedly) ran terser over the `server` build code too.

**Comment by oliviertassinari** [comment]
`Done in 146.09s`. vs `Done in 843.12s`. canary is 👌
