### ISSUE TITLE
Is there any example for Deploying NextJS 8 serverless on Azure, GCP or AWS?

### ISSUE THREAD

**Issue by imranweb** [zeit/next.js#6694]
It would be great help if there would be detailed documentation for deploying NextJS 8 on Azure, GCP or AWS.

**Comment by timneutkens** [comment]
This might help: https://github.com/danielcondemarin/serverless-nextjs-plugin

**Comment by imranweb** [comment]
But, this example still using the serverless framework. I believe NextJS 8 has its own capabilities to deploying serverless application on AWS or GCP without any external framework.
Correct me if I am wrong.

**Comment by timneutkens** [comment]
Next 8 gives the low level API to build a solution for specific platforms, the output has to be wrapped for each platform, which is what the plugin handles automatically.
