### ISSUE TITLE
'Getting started' guide is not working

### ISSUE THREAD

**Issue by Semigradsky** [zeit/next.js#6696]
# Bug report

Pass https://nextjs.org/learn/basics/getting-started/setup and https://nextjs.org/learn/basics/getting-started/first-page

you will see error
```
 ./pages/index.js
 Error: Plugin/Preset files are not allowed to export objects, only functions. In  /home/.../node_modules/babel-preset-es2015-ie/index.js
     at Array.map (<anonymous>)
     at Generator.next (<anonymous>)
```

**Comment by timneutkens** [comment]
Sounds like you have a `.babelrc` somewhere in the directory tree upwards from where you installed Next.js.
