### ISSUE TITLE
[RFC] Providing viewport tag by default

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#6698]
# Feature request

## Is your feature request related to a problem? Please describe.

By default Next.js doesn't add a `<meta name="viewport">` to the HTML document, meaning that browsers default to a behavior that you probably don't want in most cases because of media queries behaving unexpectedly, so @rauchg suggested adding `<meta name="viewport">` by default.

## Describe the solution you'd like

It's probably a good idea to mirror the AMP viewport tag:

```
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1" />
```

However I'd like to collect some more feedback around this.

**Comment by developit** [comment]
That seems like a sensible default to me. Will it still be possible to use a custom viewport tag?

**Comment by timneutkens** [comment]
> Will it still be possible to use a custom viewport tag?

Yes definitely!
