### ISSUE TITLE
Hot reloading fails when wrapping a component

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#670]
Let's say you're going from

```jsx
export default () => <div />
```

to

```jsx
import wrap from './some-decorator'
export default wrap(() => <div />)
```

The symptom is that all styles and head items are lost. Probably related to the identity of the component?

**Comment by nkzawa** [comment]
I can't reproduce. maybe https://github.com/zeit/next.js/pull/680 fixed the issue ?

**Comment by rauchg** [comment]
Likely
