### ISSUE TITLE
Error to build with preact. 

### ISSUE THREAD

**Issue by aranajhonny** [zeit/next.js#671]
generates the folder .next but always shows that error.
'next dev' - works without errors
![captura de pantalla 2017-01-05 a las 23 43 30](https://cloud.githubusercontent.com/assets/9091881/21707397/34e3dcea-d3a5-11e6-8567-0f66464a1f92.png)

**Comment by impronunciable** [comment]
There is a bigger issue. We are using the src version from preact (not the dist) and not transpiling. @arunoda ?

**Comment by impronunciable** [comment]
Related to #706

**Comment by aranajhonny** [comment]
Works fine with that alias but maybe should be so by default in the example.

**Comment by arunoda** [comment]
@impronunciable you are correct.
But for now, let's move example to use dist as you suggested.

This should be a common error for any webpack app by then. We might need to create an issue on the preact-compat side too.
