### ISSUE TITLE
next 8.0.3: JS in client side don't respond

### ISSUE THREAD

**Issue by shmulikkaminker** [zeit/next.js#6716]
# Bug report
In version 8.0.3 after running "next build" the client side does not respond in production mode.

## To Reproduce
1. Start a new next.js project.
2. add some client side code in the file, for example an "onClick" event on a button, etc. 
3. Run in dev mode  - all fine. 
4. Run "npm build" and then "npm start"  - the onClick event don't respond. no errors in the console.

## System information
 - OS: ubuntu 16.04
 - Version of Next.js: 8.0.3

**Comment by timneutkens** [comment]
Please provide a clear and concise reproduction. We have tests for the exact steps you're providing.
