### ISSUE TITLE
Immutable build artifacts

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#672]
If we produce build artifacts with hashes in them, we could send them with [immutable Cache-Control headers](http://bitsup.blogspot.com/2016/05/cache-control-immutable.html).

I think this is a better option than just naming it something like `build.js`

**Comment by arunoda** [comment]
Yep. I think that's doable and much needed in a production deployment.
I'll work on this.

**Comment by rauchg** [comment]
@arunoda ideally a prod-only behavior, as well

**Comment by timkendall** [comment]
Highly recommend doing this - fingerprinting builds has worked great for our team in the past.

**Comment by arunoda** [comment]
Okay. Now we have it via #745
