### ISSUE TITLE
Cors issue when using the with-dotenv example

### ISSUE THREAD

**Issue by philmetzger** [zeit/next.js#6720]
# Bug report

## Describe the bug

When I try to use this example to have a global variable:
https://github.com/zeit/next.js/blob/canary/examples/with-dotenv/next.config.js

And then when I do a request to a domain on a different port I get the following error message:
`Access to XMLHttpRequest at 'http://localhost:8000/api/tags/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

However without the dotenv stuff it works as is. Here is my next.config.js code:

```
require('dotenv').config();

const path = require('path');
const glob = require('glob');
const Dotenv = require('dotenv-webpack');

module.exports = {
  webpack: (config, { dev }) => {
    config.module.rules.push(
      {
        test: /\.(css|scss)/,
        loader: 'emit-file-loader',
        options: {
          name: 'dist/[path][name].[ext]'
        }
      }
    ,
      {
        test: /\.css$/,
        use: ['babel-loader', 'raw-loader', 'postcss-loader']
      }
    ,
      {
        test: /\.s(a|c)ss$/,
        use: ['babel-loader', 'raw-loader', 'postcss-loader',
          { loader: 'sass-loader',
            options: {
              includePaths: ['styles', 'node_modules']
                .map((d) => path.join(__dirname, d))
                .map((g) => glob.sync(g))
                .reduce((a, c) => a.concat(c), [])
            }
          }
        ]
      }
    );

    config.plugins = config.plugins || [];

    config.plugins.push(
        new Dotenv({
            path: path.join(__dirname, '.env'),
            systemvars: true
        })
    );

    return config
  }
};

```

What am I doing wrong?

## To Reproduce

See above.

**Comment by timneutkens** [comment]
The specific CORS error means that you're requesting a service that does not return the correct CORS headers, this is unrelated to the example itself.

**Comment by philmetzger** [comment]
but when I remove the dotenv stuff then it works again

**Comment by timneutkens** [comment]
Probably because you're reading an env var that holds the url? So it becomes a relative url because the value doesn't exist? It's probably something like that.

**Comment by philmetzger** [comment]
well in my chrome dev toolbar the request is this:
Request URL: http://localhost:8000/api/tags/
