### ISSUE TITLE
Get value from passHref

### ISSUE THREAD

**Issue by davidpmccormick** [zeit/next.js#6739]
# Feature request

## Is your feature request related to a problem? Please describe.

We have a `Control` component that conditionally renders either an `<a>` or a `<button>` based on whether it receives a `url` prop.

We're using this component within a Next `Link` component, so we want to render an `<a>` rather than a `<button>`, but we don't (as far as I can tell) have the ability to pass the href to the component's `url` prop.

Consequently, we're doing something like this

```
<Link href="blah">
  <a>
    <Control />
  </a>
</Link>
```

…and because the `Control` component isn't aware of the existence of the href, it renders a `<button>` within an `<a>`, which is invalid markup.

## Describe the solution you'd like

Possibly an option to receive the value of `passHref` so that it can be used as a different prop? `passHref="blah"`

## Describe alternatives you've considered

Rewriting the underlying component (would changing the `url` prop to `href` work?)

**Comment by timneutkens** [comment]
We can only pass it to the immediate child, for anything else you'll just have to do:

```
const url = '/blah'
<Link href={url}>
  <a>
    <Control url={url} />
  </a>
</Link>
```
