### ISSUE TITLE
Server stops responding

### ISSUE THREAD

**Issue by nkzawa** [zeit/next.js#674]
Server hangs when you reload any pages 7 times. This happens only on the following situation:

- run your server with dev mode
- ServiceWorker is running by using `next/prefetch`

It seems Server Sent Events of [`webpack-hot-middleware`](https://github.com/glenjamin/webpack-hot-middleware) and our Service Worker implementation is incompatible.

**Comment by arunoda** [comment]
Oh! Is that the problem here.
