### ISSUE TITLE
Docs/How to use: Setup error: Unhandled Rejection (ReferenceError): Home is not defined

### ISSUE THREAD

**Issue by majman** [zeit/next.js#6743]
Just running through the initial walk through: https://nextjs.org/docs#setup

Pretty sure the code for `./pages/index.js` should be

`export default Index` as `Home` is not defined (or, the function name should be `Home()`?)

**Comment by kheruc** [comment]
You are right, we'll fix this.

**Comment by kheruc** [comment]
Fixed
