### ISSUE TITLE
multiple stylus bundle extract to implement theme concept 

### ISSUE THREAD

**Issue by praveenkumarkrishnan** [zeit/next.js#6744]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

**Comment by praveenkumarkrishnan** [comment]
Hi,
i am trying to implement theme concepts using stylus sheet in nextjs, need to extract css bundles based on the varible.styl applied

**theme.styl**
      $carbon= black
      $red= #ff0011

**theme2.styl**
     $carbon= #333333
     $red= #ff0000
     $lime-green= #0abd3e
     $timberwolf= #d8d8d8

**stylus.styl**
.modal
  background: $carbon

**expected bundle file:**
**bundle file 1**
.modal {
  background: #000;
}

**bundle file 2**
.modal {
  background: #333;
}

**Comment by timneutkens** [comment]
As per the issue template I'm going to close this issue.
