### ISSUE TITLE
'Set' undefined in  ie10 & ie9

### ISSUE THREAD

**Issue by pheart** [zeit/next.js#6751]
# Question about Next.js

when I introduce the following code, can Run correctly in ie11
import 'core-js/stable';
but  have error in ie9 & ie10,
'Set'  undefined

**Comment by Lizhooh** [comment]
maybe you need babel-pollyfill

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/tree/canary/examples/with-polyfills

**Comment by pheart** [comment]
@timneutkens   thanks!

**Comment by TheoLin1212** [comment]
@pheart  I meet the same problem, but i can solve it use the answer from @timneutkens , how do you solve it?

**Comment by TheoLin1212** [comment]
@pheart fix it, but have new problem that arrow function in ansi-regex does not be compiled
