### ISSUE TITLE
Using koa as server side framework, status 404 occurs when load static files.

### ISSUE THREAD

**Issue by livoras** [zeit/next.js#677]
I am trying using Koa as server side framework of my project. And I followed the [example](https://github.com/zeit/next.js/#custom-server-and-routing) and got my koa's version below:

server.js:

```javascript
import Koa from 'koa'
import next from 'next'
import Router from 'koa-router'

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev: true })
const handle = app.getRequestHandler()

app.prepare().then(() => {
  const server = new Koa
  const router = new Router

  router.get('*', async (ctx) => {
    handle(ctx.req, ctx.res)
    ctx.respond = false
  })

  server.use(router.routes())
  server.listen(3000)
}).catch((e) => {
  console.log(e.stack)
})

```

But when load static files 'main.js' and 'common.js' in `.next`, the browser complains that these files are not found with status 404, but the content of the files are actually correct.

![image](https://cloud.githubusercontent.com/assets/6436132/21713276/0dadcbc4-d434-11e6-888d-89880457022d.png)

I read [the source](https://github.com/zeit/next.js/blob/master/server/render.js#L144-L161) code and found that next.js always tried to load gzip version of these files and if not found it would load the normal version.

So it actually run the [serveStatic](https://github.com/zeit/next.js/blob/master/server/render.js#L163-L170) function twice. But the first time it tried to load gzip version but it failed then the `res` object got 404 `statusCode`, and the second the status code still retained in `res` object of koa for some unknown reasons.

Reseting status code in `serveStaticWithGzip` function fixed this problem:

```javascript
export async function serveStaticWithGzip (req, res, path) {
  const encoding = accepts(req).encodings(['gzip'])
  if (encoding !== 'gzip') {
    return serveStatic(req, res, path)
  }

  try {
    const gzipPath = `${path}.gz`
    res.setHeader('Content-Encoding', 'gzip')
    await serveStatic(req, res, gzipPath)
  } catch (ex) {
    if (ex.code === 'ENOENT') {
      res.statusCode = 200 // code added
      res.removeHeader('Content-Encoding')
      return serveStatic(req, res, path)
    }
    throw ex
  }
}
```

I am using koa@2 and next@beta.

(Poor English, feel free to correct.)

**Comment by sedubois** [comment]
Would be great indeed to have a working Next-Koa example 🙂

**Comment by impronunciable** [comment]
Added example https://github.com/zeit/next.js/pull/800/files

closing this

**Comment by aga5tya** [comment]
The issue of serving static assets over Koa still exits on the latest master. I checked it through the example added by @impronunciable and can be reproduced.

<img width="1247" alt="screen shot 2017-01-18 at 12 32 47 am" src="https://cloud.githubusercontent.com/assets/17351163/22035484/24df85c2-dd16-11e6-8071-d91bf1e6bf2e.png">

**Comment by arunoda** [comment]
Yep it is. Here's the fix: https://github.com/zeit/next.js/issues/677
