### ISSUE TITLE
exportPathMap does not work as expected for built applications

### ISSUE THREAD

**Issue by KamalAman** [zeit/next.js#6773]
# Bug report

exportPathMap has no effect on built applications

## To Reproduce
Given a page named `/test`, a route for test_dummy is not generated when building an application

`next.config.js`
```javascript
module.exports = {
  exportPathMap: function () {
    return {
      '/test_dummy': { page: '/test' }
    }
  }
}
```

## Expected behavior
In dev mode, this works as expected. A user can navigate to `/test_dummy` and visit the `/test` page.

Navigating to `/test_dummy` in a build application the user should be directed to the `/test` page. However, they are directed to a 404 page. 

## Screenshots
![image](https://user-images.githubusercontent.com/2692357/54890939-f9c9a400-4e81-11e9-842c-c09e1d3f72e1.png)

## System information
 - OS: macOS
 - Browser: Chrome
 - Version of Next.js: 8.0.1

**Comment by kheruc** [comment]
The `exportPathMap` is used only when exporting to a static site using `next export`.
Are you using `next export` or `next start`? 

If you are using `next start` you need to set up a server.js with your custom routes for them to work on the server side:
https://nextjs.org/docs/#custom-server-and-routing

**Comment by KamalAman** [comment]
I am using `next start`.
The issue is the fact that `exportPathMap` works in `next dev` but does not work with `next build && next start`

**Comment by kheruc** [comment]
There are two ways to build a Next.js app to production: `next export` for a static site and `next start` for a SSR Node app. 
`exportPathMap` is used only for static sites built with `next export`
