### ISSUE TITLE
Sunset `X-Powered-By` header

### ISSUE THREAD

**Issue by Timer** [zeit/next.js#6776]
Next.js (by default) responds with a `X-Powered-By` set to `Next.js [version]`.

Selecting three sites at random from our showcase (Marvel, Hulu, and Ticketmaster), you'll find they all have this feature disabled.

We should just sunset this feature all together.

**Comment by timneutkens** [comment]
Also makes the response slightly smaller 👌

**Comment by Timer** [comment]
Also, we recently merged https://github.com/zeit/next.js/pull/6775 -- we should probably update these docs to note that it's not necessary after Next.js vx.x.x, and remove it [from the docs] sometime in the future.

**Comment by timneutkens** [comment]
@Timer I'd just remove it from the docs to be honest. We should probably have a version switcher in nextjs.org/docs though.
