### ISSUE TITLE
beforePopState unexpected behavior

### ISSUE THREAD

**Issue by mlnor27** [zeit/next.js#6784]
# Bug report

The `Router`'s `beforePopState` listener triggers and does its work nicely.
But as shown in the doc (https://github.com/zeit/next.js#intercepting-popstate), when returning `false`, it should not only prevent the history from changing but also keep the browser's URL intact, which is not the case unfortunately...

## To Reproduce

Here is a repo demonstrating the bug : 
https://github.com/mlnor27/nextjs-bug-to-reproduce

after starting the development server :
- Go to http://localhost:3000
- click on the "about" link
- click on the back button of the browser
==> The current page is still on the "about" page but the URL bar changes to http://localhost:3000 instead of staying on  http://localhost:3000/about

## Expected behavior
When the user clicks on the back button of the browser, the url appearing in the url bar of the browser shouldn't change

## System information
 - OS: macOS Mojave
 - Browser: Chromium/Firefox/Safari
 - Version of Next.js: 8.0.3

**Comment by mlnor27** [comment]
@timneutkens @Timer Hi guys,
I would like to reiterate on this, as it is making me a bit confused. Does this bug show up because the popstate event isn't cancelable when triggered by a user click on the back button, or is it because of some internal issues with next's router ?
If it isn't the router's fault, i think we should mention it in the doc. Because, to me and i'm sure for the majority, when we talk about "intercepting" an event, it means we have full control of what is going to come out of it.
So at the end what's making the browser url change ? I just want to have a little feedback to know why my issue hasn't been addressed if that's too much to ask. Thank you

**Comment by timneutkens** [comment]
This indeed doesn't seem like a bug, beforePopState expects you to direct to another page using hard linking when not following the Next.js convention.

**Comment by xfumihiro** [comment]
@timneutkens beforePopState should be able to **prevent** url change which will be useful for cases like 'closing modal dialogs on back clicked'

**Comment by Diljeetsinghsuri** [comment]
@timneutkens  @timer I am facing this issue too, What I notice is that, when I click on browser back button the beforePopState event is fired and nextJS app wait for my response, whether to change the route or not, But the URL in the browser's address bar get changes before this event is being called. So, suppose if I respond the app to don't change the route, then the change route will not occurs at nextJS app level but as the browser's address bar URL was already changed to previous one, So when I hit the reload button then it will load the content of previous page as browser will reload the URL which it contains in address bar. So with respect to this scenario the beforePopState function is not performing correctly. If you have any solution for that please let me know.

**Comment by NProtsenko** [comment]
@timneutkens I faced the same issue. I want to display popup when user has unsaved changes on the page and wants to leave by clicking the back button in the browser. I use beforePopState() to do this. But as was mentioned above there is no chances to keep url intact. If user clicks 2 times, the url changes 2 times and when he click "continue" in modal window, he gets not to the previous page but on the page which was 2 steps ago. So is there some chances to fix such behavior of beforePopState? It would be better to keep url unchanged and give programmers control it after beforePopState was fired. Thanks!

**Comment by lifedup** [comment]
Browsers don't let you stop the popstate event from going back or forward.

If you return false in next's beforePopState event you must also redirect. Doing this adds another history event and keeps everything in sync.  

The only way to achieve full stoppage and keep everything in sync is to do [a hacky solution](https://stackoverflow.com/questions/18141729/browsers-back-button-click-with-confirm-box).

**Comment by danvoyce** [comment]
I've just stumbled upon this same issue. I assumed `beforePopState` would behave in the same or similar way as the native `beforeunload` event callback, but it's far from it. 

As mentioned in a previous comment, when the user clicks back and we return false from `beforePopState`, the URL changes but the page remains in place. Surely this isn't supposed to happen? 

From the docs:

```
If cb returns false, the Next.js router will not handle popstate, and you'll be responsible for handling it in that case. See Disabling file-system routing.
```

This gives me the impression that we can prevent the url from changing.

**Comment by 2012shenghua** [comment]
me too, how to fix it

**Comment by achenPDFTron** [comment]
I am running into this issue as well. is there a workaround / fix for this?

**Comment by balazsorban44** [comment]
Please open a new issue with a reproduction.
