### ISSUE TITLE
AMP `[text]` tag is not supported?

### ISSUE THREAD

**Issue by PetrSnobelt** [zeit/next.js#6800]
## Example name
experimental-amp

## Describe the bug
I try to use a sample from https://ampbyexample.com/dynamic_amp/dynamic_content_after_user-interaction/ without luck. 
When I add `<div [text]="products[productId] + ' available'">Please select a product</div>` error while compiling occured `SyntaxError: /experimental-amp-app/pages/product.amp.js: Unexpected token (38:5)`

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create amp all
2. Add "product.amp.js" page with this content:
```
import Head from 'next/head'
import { useAmp } from 'next/amp'

export default () => {
  const isAmp = useAmp()

  return (
    <>
    <Head>
    <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
    </Head>
    <h1>AMP Product</h1>
    <a href="https://ampbyexample.com/dynamic_amp/dynamic_content_after_user-interaction/" />
<amp-state id="products"
  src="https://ampbyexample.com/json/products.json"></amp-state>

<amp-img on="tap:AMP.setState({ productId: 0})"
  src="https://ampbyexample.com/img/red_apple_1_60x40.jpg"
  width="60"
  height="40"
  role="button"
  tabindex="0">
</amp-img>
<amp-img on="tap:AMP.setState({ productId: 1})"
  src="https://ampbyexample.com/img/green_apple_1_60x40.jpg"
  width="60"
  height="40"
  role="button"
  tabindex="0">
</amp-img>
<amp-img on="tap:AMP.setState({ productId: 2})"
  src="https://ampbyexample.com/img/product1_alt1_60x40.jpg"
  width="60"
  height="40"
  role="button"
  tabindex="0">
</amp-img>
<div [text]="products[productId] + ' available'">Please select a product</div>
</>)
}
```
3. See error

## Expected behaviour
It should compile or suggest an alternative way how to write such AMP code

## System information
 - OS: latest macOS
 - Browser chrome
 - Version of Next.js: 8.0.4-canary.24

Is there any alternative way how to write `[text]` inside div?

**Comment by PetrSnobelt** [comment]
Workaround 
```
<div dangerouslySetInnerHTML={
  {__html: `<div [text]="products[productId] + ' available'">Please select a product</div>`}
} />
```

**Comment by timneutkens** [comment]
@Timer / @ijjk will answer this more thoroughly, but you can use `data-amp-bind-class="something"` instead of the syntax that is not supported by JSX.

**Comment by Timer** [comment]
As @timneutkens was explaining above, `[text]` is not valid XML, and by extension, not valid JSX.

For now, the suggested work around is to use `data-amp-bind-text` instead, e.g.:
```html
<div data-amp-bind-text="products[productId] + ' available'">Please select a product</div>
```

@ijjk maybe we can detect the Syntax Error on `[` and emit a message like:
```
It appears you are trying to use the `amp-bind` property syntax! This syntax is not valid XML, and by extension, not valid JSX.
Please use `data-amp-bind-<prop>` as an alternative.

Read more here: https://www.ampproject.org/docs/reference/components/amp-bind#bindings
```

**Comment by PetrSnobelt** [comment]
So the workaround is to use, thanks @timneutkens. I leave up to you if you close the issue, workaround with `data-amp-bind` is fine for me.
`<div data-amp-bind-text="products[productId] + ' available'">Please select a product</div>`

**Comment by timneutkens** [comment]
I've talked with @sebastianbenz and we've created an issue here: https://github.com/ampproject/amphtml/issues/21600
