### ISSUE TITLE
issues with NEXT js

### ISSUE THREAD

**Issue by piyush-zensar** [zeit/next.js#6802]
1. I have multi-site concept in my project (similar to multiple theme) and I am not able to segregate these multi-site CSS, I am also using Atomic design in our project(CSS are present at atom/molecule level components), this can be achieved using Webpack configuration but when I tried changing these configurations, NEXT wrapper did override all configurations with its default settings and I could not segregate multi-site CSS.

**Comment by timneutkens** [comment]
Please follow the issue template.
