### ISSUE TITLE
 Uncaught ReferenceError: ducument is not defined     at 

### ISSUE THREAD

**Issue by Flave1** [zeit/next.js#6813]
<input type="submit" class="btn" value="click here" id="follow" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    @section Scripts{

     <script type="text/javascript">
            $(ducument).ready(function () {
             $("#follow").click(function (e) {
             var foll = {};
            foll.ID = 222;
            foll.FName = "FRANK";
            foll.LName = "SANTA";
            foll.url = "@Url.Action("Follow", "FarmsCommunity")";
            foll.type = "POST";
            foll.dataType = "json";
            foll.data = JSON.stringify({ usr: foll });
            foll.contentType = "application/json";
            foll.success = function (response) {
                                    alert("success")
                   };
            foll.error = function (response) {
                                   alert("error");
                  };
                 $.ajax(foll);
                  });
              });
       </script>
    }

My Controller
              public ActionResult Follow(string userid, User usr)
                   {
                          return Json(new {
                          ResultValue = "Some Value"
                      });
                     }

**Comment by s4kh** [comment]
Shouldn't it be **document** not **ducument**?

**Comment by timneutkens** [comment]
This is unrelated to Next.js.
