### ISSUE TITLE
Abnormal display of first rendered page

### ISSUE THREAD

**Issue by anjohnlv** [zeit/next.js#6816]
# Question about Next.js

![Untitled](https://user-images.githubusercontent.com/20536760/55131954-abefbd00-515b-11e9-947a-26f86e2c2286.gif)

when refresh page ,the layout's display will strange

**Comment by timneutkens** [comment]
Sounds like a styling issue, please follow the issue template.

**Comment by anjohnlv** [comment]
With-ant-design demo,as long as this happens, it will reappear.
```

import { Layout } from 'antd';
const { Header, Sider, Content } = Layout;
```
```
<Layout className="mainLayout">
    <Sider>
    </Sider>
    <Layout>
        <Header>
        </Header>
        <Content>
            {this.props.children}
        </Content>
    </Layout>
 </Layout>
```
