### ISSUE TITLE
Using exportPathMap config breaks dev mode hot-reload

### ISSUE THREAD

**Issue by Soundvessel** [zeit/next.js#6819]
# Bug report

## Describe the bug

Hot-reloading breaks when exportPathMap config is added to next.config.js.

## To Reproduce

1. Open sandbox https://codesandbox.io/s/0y2q7162k0 and make changes to `Test.scss` in `/components`. Hot reloading works fine.
2. Open sandbox https://codesandbox.io/s/6wxwm2qx1w which is an exact copy but introduces exportPathMap config in next.config.js. Changes to `Test.scss` show recompile in terminal but hot-reload of actual output does not happen.

## Expected behavior
Hot-reloading shouldn't stop working when exportPathMap config is used.

## System information
 - OS: Windows 10 and https://codesandbox.io
 - Browser Chrome, latest
 - Version of Next.js: 8.0.3

**Comment by lfades** [comment]
Hi @Soundvessel your issue seems to be related to [this issue](https://github.com/zeit/next-plugins/issues/282), but for this case a easy fix is to just let Next.js decide the `exportPathMap` in development and only change it for production, e.g:

```js
exportPathMap: (defaultPathMap, { dev }) =>
    dev ? defaultPathMap : { "/": { page: "/index" } }
```

**Comment by timneutkens** [comment]
Actually it's exactly this issue: https://github.com/zeit/next.js/issues/6285

You have `/index` in the exportPathMap, which causes above issue that is already fixed on next@canary.
