### ISSUE TITLE
Using firebase.database() causes next build to hang forever.

### ISSUE THREAD

**Issue by robertgonzales** [zeit/next.js#6824]
# Bug report

## Describe the bug

Using `firebase.database()` causes `next build` to hang forever. The build still seems to compile successfully, but I can't reliably export and deploy my app because the build never finishes.

## To Reproduce

```js
// next.config.js
const firebase = require("firebase")

firebase.initializeApp({
  apiKey: "AIza....", // Auth / General Use
  authDomain: "YOUR_APP.firebaseapp.com", // Auth with popup/redirect
  databaseURL: "https://YOUR_APP.firebaseio.com", // Realtime Database
  storageBucket: "YOUR_APP.appspot.com", // Storage
  messagingSenderId: "123456789", // Cloud Messaging
})

const db = firebase.database()

module.exports = {
  useFileSystemPublicRoutes: true,
}
```

[I created a small example repo](https://github.com/robertgonzales/next-firebase) that demonstrates the issue with only `next.config.js` and `pages/index.js`. Running `npm run dev` works just fine, but `npm run build` hangs forever.

## Expected behavior
`npm run build` exits the process after successfully building.

## Screenshots
When I run `npm run build` it seems to build successfully but the process never exits.
<img width="533" alt="Screenshot 2019-03-28 17 21 10" src="https://user-images.githubusercontent.com/7729885/55193630-ec603280-517d-11e9-86bb-825fcca8e234.png">

## System information
 - OS: macOS
 - Version of Next.js: 8.03

**Comment by timneutkens** [comment]
I doubt this is related to Next.js, firebase probably doesn't close 🤔 Why are you initializing the connection like that? Is it for `exportPathMap`? Maybe move the connection into the function.

**Comment by kheruc** [comment]
Check this tutorial, it has some recommendations on how to load Firebase:
https://nextjs.org/learn/excel/lazy-loading-modules

**Comment by robertgonzales** [comment]
@kheruc this issue is specific to using firebase during export. I've had no trouble using firebase on the client.

@timneutkens I think you are correct — this is a firebase issue. 

In my actual use case I'm initializing firebase elsewhere (but still importing it into next.config.js so I can use the firebase query result to create pages for export). 

For now I've resorted to using firebase rest api since I can't get the database api to work.

**Comment by timneutkens** [comment]
We already have this for `export`: https://github.com/zeit/next.js/blob/7dc50f3867dff1a7ea4f51a8902262cb0e363c9e/packages/next/cli/next-export.ts#L66-L72

So I guess we can just add it here: https://github.com/zeit/next.js/blob/7dc50f3867dff1a7ea4f51a8902262cb0e363c9e/packages/next/cli/next-build.ts#L48

Feel free to send a PR 👍

**Comment by Timer** [comment]
Closing as global side effects are a bad idea -- if the user feels strongly about this they can send a PR. :pray:
