### ISSUE TITLE
Error: HTTP Error: 400, Request contains an invalid argument.

### ISSUE THREAD

**Issue by didymu5** [zeit/next.js#6826]
# Examples bug report

## Example name
with-firebase-hosting

## Describe the bug
After bootstrapping with create-next-app with-firebase-hosting, and all the npm deps are installed, when I try to run '''npm run serve''' I get 
Error: HTTP Error: 400, Request contains an invalid argument.

@jthegedus

## To Reproduce
create-next-app --example with-firebase-hosting

## Expected behavior
The server should run with npm run serve or yarn serve

## System information
 - OS: [e.g. macOS, Windows]
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [^8.0.3]

## Additional context

```

Error: HTTP Error: 400, Request contains an invalid argument.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! with-firebase-hosting@4.0.1 serve: `cross-env NODE_ENV=production firebase serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the with-firebase-hosting@4.0.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by didymu5** [comment]
https://nextjs.org/blog/next-8#serverless-nextjs

**Comment by myylow** [comment]
You get that error when running the example as-is, but you need to configure it with your Firebase account details first.

If you follow the 'Set up firebase' section on https://github.com/zeit/next.js/tree/canary/examples/with-firebase-hosting and update .firebaserc with the Firebase project name, it then works.

**Comment by didymu5** [comment]
@myylow thanks dude. will check it out.
