### ISSUE TITLE
nextjs + storybook in IE11

### ISSUE THREAD

**Issue by idw111** [zeit/next.js#6829]
# Bug report

## Describe the bug
component with Link breaks the IE11 render

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. clone https://github.com/idw111/nextjs-storybook-ie11.git and npm install
2. npm run storybook and browse to http://localhost:9001 (it'll work) 
3. uncomment "import Link from 'next/link'" in components/Color.js
4. storybook won't work in IE11

## Expected behavior
render correctly in IE11

## Screenshots
<img width="1478" alt="error-screenshot" src="https://user-images.githubusercontent.com/445464/55208550-ed4aa000-5221-11e9-9654-97714a2d22ae.png">

## System information
 - OS: macOS Mojave
 - Browser (if applies) IE11
 - Version of Next.js: 8.0.3

**Comment by timneutkens** [comment]
I doubt this is related to Next.js, as Next.js supports rendering in IE11.

**Comment by idw111** [comment]
You're right.
I could render the app in IE11, and it's not a nextjs bug.
It's a configuration issue with nextjs + storybook.
I'll put the question in spectrum.
Thank you.
