### ISSUE TITLE
With cookie auth not work

### ISSUE THREAD

**Issue by Gmulti** [zeit/next.js#6839]
I tried to set up the example: https://github.com/zeit/next.js/tree/canary/examples/with-cookie-auth

Whether in v1 or v2, I can't get my token back at the server side loading.
On the client side, everything is okay, but nothing on the server side... an idea?

**Comment by j0lv3r4** [comment]
hey @Gmulti, could you show me a repo to look at so I can try to replicate?

Also, I'm not sure what you mean about getting your token back at the server, if the client works fine (specifically the profile page) you should be getting the token in the server.

**Comment by Gmulti** [comment]
Unfortunately I can't provide you with the repo in public.
Here is an example of what I use : 
```
 static async getInitialProps(ctx) {
        const { store } = ctx

        const accessToken = auth(ctx)
        let projects
        console.log('AT : ', accessToken)
        if (accessToken) {
           // Get Projects
            console.log(success)
            projects = result
         
            }
        }

        return {
            accessToken
        }
    }
```

**Comment by Gmulti** [comment]
Unfortunately I can't provide you with the repo in public.
Here is an example of what I use :

Function `auth`
```

export const auth = ctx => {
  const { accessToken } = nextCookie(ctx)

  if (ctx.req && !accessToken) {
    ctx.res.writeHead(302, { Location: '/login' })
    ctx.res.end()
    return
  }

  // We already checked for server. This should only happen on client.
  if (!accessToken) {
    Router.push('/login')
  }

  return accessToken
}
```

HOC withAuthSync : 
```

```
import { Component } from 'react'
import { auth } from '../helpers/auth'

// Gets the display name of a JSX component for dev tools
const getDisplayName = Component =>
    Component.displayName || Component.name || 'Component'

export const withAuthSync = WrappedComponent =>
    class extends Component {
        static displayName = `withAuthSync(${getDisplayName(WrappedComponent)})`

        static async getInitialProps(ctx) {
            const accessToken = auth(ctx)

            const componentProps =
                WrappedComponent.getInitialProps &&
                (await WrappedComponent.getInitialProps(ctx))

            return { ...componentProps, accessToken }
        }

        render() {
            return <WrappedComponent {...this.props} />
        }
    }

export default () => {
    return target => withAuthSync(target)
}
```

My Page : 
```
@withAuthSync()
@Head()
@Page()
class PageHome extends Component {
 static async getInitialProps(ctx) {
        const { store } = ctx
        const accessToken = auth(ctx)
        console.log('AT : ', accessToken) // Null on server side / Good on client side
        if (accessToken) {
           // Get Projects
        }

        return {
            accessToken
        }
    }
}
```

In the meantime, I'll still try to give you a quick example in case it doesn't work

**Comment by Gmulti** [comment]
Okay, I got it! 
In development, I use a server node that already contains `isomorphic-fetch`.
However, this is not the case during the deployment on v2 and it no longer existed.... ! And no logs to find out.
I added it and it's all good
It's all right, I'm closing the issue

**Comment by j0lv3r4** [comment]
Awesome! I'm glad you figured it out
