### ISSUE TITLE
How to build custom server, like `server.bundle.js`.

### ISSUE THREAD

**Issue by krasevych** [zeit/next.js#6849]
# Question about Next.js
- I can not understand what is wrong, the point is to do the tar czf server part on Next.JS.
I created a webpack:
`{ mode: 'production', target: 'node' entry: './server/index.ts' output: { path: path.resolve (__ dirname, '../../server'), filename: 'server.js' }, module: { rules: [ { test: /\.ts?$/, exclude: [/ \ / node_modules \ //] use: { loader: 'awesome-typecript-loader' options: { // Use this to point to your tsconfig.json. configFileName: './tsconfig.server.1.json' } } } ] }, resolve: { extensions: ['.ts', '.js'] } } but when I launch webpack then I get: `` ERROR in ./node_modules/next/dist/build/output/store.js
Module not found: Error: Can not resolve 'readline' in 'D: \\\\' node_modules \ next \ dist \ build \ output '
@ ./node_modules/next/dist/build/output/store.js 17: 35-54
@ ./node_modules/next/dist/build/output/index.js
@ ./node_modules/next/dist/server/hot-reloader.js
@ ./node_modules/next/dist/server/next-dev-server.js
@ ./node_modules/next/dist/server/next.js
@ ./ server / index.tsand such 7-8 pieces with power modules that I do not turn off? for what I do it - I need to give the admin part of the server, now I do this: `` tar czf target / server.tar.gz .next node_modules server routes.ts config next.config. * tsconfig * package.json yarn .lock types but the file gets very large due to the extra modules.

Questions should be posted on https://spectrum.chat/next-js
- https://spectrum.chat/next-js/general/how-to-build-custom-server~3105bd61-6ae1-4d34-92c8-03d9a1b10c58

**Comment by Timer** [comment]
This question will be answered on Spectrum, thanks!
