### ISSUE TITLE
HTTP/2 example

### ISSUE THREAD

**Issue by shashkovdanil** [zeit/next.js#6850]
# Example request

## Example name

example with http/2

## Describe the bug

Add an example with http/2 server. It's better for production, but difficult to set up (express, koa, fastify, hapi and other server frameworks)

**Comment by timneutkens** [comment]
Please follow the issue template when creating issues.

**Comment by shashkovdanil** [comment]
@timneutkens, sorry, check it please

**Comment by shahzeb1** [comment]
@timneutkens is this issue still looking for a contributor? I'd be down to tackle it.

**Comment by shashkovdanil** [comment]
@shahzeb1, can you create example http/2 with most popular server frameworks (express, koa, fastify, hapi)? Most use a server built on them. You can also add compression (gzip, etc.) to the example. So we will get an example of a production ready server.

Thank you!

**Comment by shahzeb1** [comment]
Yes I can do that. But lets just confirm with @timneutkens that an HTTP/2 example using all those libraries is what they'd want.

**Comment by timneutkens** [comment]
I think it'd be too much / we already have examples using all those frameworks.

**Comment by shahzeb1** [comment]
This issue can now be closed at an example has successfully been merged in: https://github.com/zeit/next.js/commit/c97617fdf5bffefae864519ee3d2b9a757aa873c

😊

**Comment by timneutkens** [comment]
💯 Thank you very much @shahzeb1!
