### ISSUE TITLE
svg cache persist using inline-react-svg

### ISSUE THREAD

**Issue by eldyvoon** [zeit/next.js#6857]
I have svg imported and rendered. Later on I replace the svg with another svg but the filename is the same, but it's still showing the old svg. I don't know when the cache is going away, to see the new svg I have to add some attr like so

```<MySvg id="test" />```

I tried to restart ```npm run dev``` it doesn't have effect, cleared browser cache but it's still the same. I somehow have to modified the code in a file to see the changes, it's annoying, is it related babel? I'm curious.

**Comment by timneutkens** [comment]
This is not really a Next.js issue. It has to do with Babel not being a tool for bundling but for transformations. Meaning that the cache key consists of the original source file + options, not other options.

It's generally better to use custom webpack configuration for this case.
