### ISSUE TITLE
Routing on the client with Redux

### ISSUE THREAD

**Issue by vinceprofeta** [zeit/next.js#686]
The example provided gives you an idea on how to implement this with redux but does not illustrate how you would add multiple routes. Are you suggesting wrapping each route with <Provider>?

Any guidance would be great! Thanks.

**Comment by arunoda** [comment]
Good question. You need to do something like that.
We did the multi-page example for mobx: https://github.com/zeit/next.js/pull/676

I think we need to do the same for Redux as well.

**Comment by timneutkens** [comment]
Fixed in #691 👍
