### ISSUE TITLE
want to use window.history replace in some case

### ISSUE THREAD

**Issue by vcebotari** [zeit/next.js#6862]
# Bug report

## Describe the bug
i have a map project(one page app with some routing only to index), in some cases i use `Router.replace` and `Router.push`. after map move i change coordinates in url like: 
`/40.000/28.33` to `/38.00/28.22`, in this case i do not want to trigger getInitialProps, and use window.history.replaceState, after i click back button, i catch a next warning, and an error,

![Screen Shot 2019-04-02 at 16 38 28](https://user-images.githubusercontent.com/8831983/55406981-cb288900-5565-11e9-8cb3-742e304d9a6d.png)

how can i escape this problem? 
would be great if it's possible... thx

## Expected behavior
want to ignore next warning on popstate

## System information
 - OS: macOS
 - Browser [any]
 - Version of Next.js: [any]

**Comment by timneutkens** [comment]
You probably want to use the `shallow` option.

**Comment by vcebotari** [comment]
@timneutkens , 

![Screen Shot 2019-04-05 at 12 44 20](https://user-images.githubusercontent.com/8831983/55619046-9c4a2700-57a0-11e9-88c3-39af54707692.png)

it's not working, if i change the coords `/lat/lng` it think's what i change the whole page, but it is not what i want.

**Comment by dcalhoun** [comment]
@vcebotari you may need to utilize the `as` property [outlined in the Imperative Routing documentation](https://nextjs.org/docs#imperatively) when constructing your URL.

```js
Router.replace('/map?lat=10&lng=20', '/map/10/20', { shallow: true });
```
