### ISSUE TITLE
Update 8.0.4 breaks next and next build in with-typescript

### ISSUE THREAD

**Issue by git-no** [zeit/next.js#6863]
# Bug report

## Describe the bug

Yarn dev or Yarn build breaks with error.

### With yarn dev, aka next
> Failed to compile.
```
C:/Users/x/with-typescript-app/pages/index.tsx 5:15
Module parse failed: Unexpected token (5:15)
You may need an appropriate loader to handle this file type.
| import Layout from '../components/Layout'
|
> const IndexPage: React.FunctionComponent = () => {
|   return (
|     <Layout title="Home | Next.js + TypeScript Example">
```
### With yarn build , aka next build
> Failed to compile.

```
C:/Users/x/with-typescript-app/pages/list-class.tsx 10:5
Module parse failed: Unexpected token (10:5)
You may need an appropriate loader to handle this file type.
| import { findAll } from '../utils/sample-api';
|
> type Props = {
|   items: IDataObject[],
|   pathname: string,

> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (C:\Users\x\with-typescript-app\node_modules\next\dist\build\index.js:110:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Run ```yarn create next-app --example with-typescript with-typescript-app```
2. ```cd with-typescript-app``` 
3. ```yarn dev```

## Expected behavior
Website is accessable under http://localhost:3000/ without error.

## System information
 - OS: Windows 10
 - Browser Chrome (latest)
 - Version of Next.js: 8.0.4

**Comment by timneutkens** [comment]
I just tried reproducing and can't reproduce the issue.

**Comment by git-no** [comment]
Thanks. Now it works, after a restart of Visual Studio Code (I do use the terminal within VSC).
