### ISSUE TITLE
pageExtensions not respecting file extension

### ISSUE THREAD

**Issue by mattdell** [zeit/next.js#6878]
# Bug report

## Describe the bug

If I provide next.config.js a pageExtensions value of `pageExtensions: ['tsx']` I am having pages created for non-tsx pages.

## To Reproduce

I've provided full examples of my files here for visibility

```js
const withPlugins = require('next-compose-plugins');
const withTypescript = require('@zeit/next-typescript');
const withSass = require('@zeit/next-sass');
const withCss = require('@zeit/next-css');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

/* eslint-disable no-param-reassign */

module.exports = withPlugins(
  [
    [withTypescript],
    [withCss],
    [
      withSass,
      {
        cssModules: true,
        cssLoaderOptions: {
          importLoaders: 1,
          localIdentName: '[local]___[hash:base64:5]',
        },
      },
    ],
  ],
  {
    target: 'serverless',
    pageExtensions: ['tsx'],
    webpack(config, options) {
      if (options.isServer) {
        // Type checking on build
        config.plugins.push(new ForkTsCheckerWebpackPlugin());
      }

      return config;
    },
  },
);
```

And this is my pages tree I have

```
├── pages
│   ├── header
│   │   ├── HeaderPage.interfaces.ts
│   │   ├── HeaderPage.transformations.ts
│   │   ├── HeaderPage.tsx
│   │   └── index.ts
│   └── index.tsx
```

## Expected behavior

I would expect to only have an index page and a HeaderPage, given that these are the only `.tsx` files.

## Screenshots

Not a screenshot, but the output is

```node
$ next build
Creating an optimized production build ...

> Using external babel configuration
> Location: "/Users/mdell/Work/Repos/pistonheads.front-end/.babelrc"
Starting type checking service...
Using 1 worker with 2048MB memory limit
Compiled with warnings.

./node_modules/next/dist/build/webpack/loaders/next-serverless-loader.js?page=%2Fheader%2FHeaderPage.transformations&absolutePagePath=private-next-pages%2Fheader%2FHeaderPage.transformations.ts&absoluteAppPath=next%2Fdist%2Fpages%2F_app&absoluteDocumentPath=next%2Fdist%2Fpages%2F_document&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&distDir=private-dot-next&buildId=AGGlfU3e4MbxL9mW_T_RS&assetPrefix=&generateEtags=true
Attempted import error: 'private-next-pages/header/HeaderPage.transformations.ts' does not contain a default export (imported as 'Component').

 ┌ /
 ├ /_app
 ├ /_document
 ├ /_error
 ├ /header
 ├ /header/HeaderPage
 ├ /header/HeaderPage.interfaces
 └ /header/HeaderPage.transformations

✨  Done in 10.54s.
```

## System information
 - OS: MacOS Mojave
 - Version of Next.js: 8.0.3

**Comment by ijjk** [comment]
The `@zeit/next-typescript` plugin adds both `ts` and `tsx` to the `pageExtensions`. You could open an issue at https://github.com/zeit/next-plugins/ as a feature request for the behavior you're looking for.

**Comment by timneutkens** [comment]
Plugins enhance the config, so you could do something like:

```
const myconfig = withTypescript(withCss(//etc etc))
myconfig.pageExtensions = ['tsx']

module.exports = myconfig
```

However I would strongly recommend against putting anything but pages in the pages directory. `pageExtensions` was introduced so that you could have `.ts` etc be pages, not to allow non-pages to be in the pages directory.

**Comment by SnowFlowers** [comment]
![image](https://user-images.githubusercontent.com/16875486/55548094-51c79c80-5705-11e9-912d-00e63efe26e4.png)
Bug report
the same problem

**Comment by SnowFlowers** [comment]
why?i try everything i can

**Comment by mattdell** [comment]
> The `@zeit/next-typescript` plugin adds both `ts` and `tsx` to the `pageExtensions`. You could open an issue at https://github.com/zeit/next-plugins/ as a feature request for the behavior you're looking for.

Ah, cheers. I had considered that but didn't see any documentation around it.

One could reasonably assume that setting `pageExtensions` would override, and not augment, the page extensions. I'd expect that should be the behavior from next.config.js.

**Comment by timneutkens** [comment]
It's probably good to note that next.config.js is just a "dumb" module that exports an object or function. It doesn't do anything with the plugins you add, the plugins are enhancing functions on the object.
