### ISSUE TITLE
[Error][v8.0.4] TypeError: (0 , _typeof2.default) is not a function

### ISSUE THREAD

**Issue by wellyshen** [zeit/next.js#6879]
# Bug report

## Describe the bug

I am using v8.0.4. Everything OK in dev. But after I do `next build` and run my app the app stuck in server-side, then I get the `TypeError: (0 , _typeof2.default) is not a function` error. Does anyone has this issue?

## To Reproduce

1. Go to this [repo](https://github.com/wellyshen/next-debug)
2. Run `yarn install`
3. Run `yarn build`
4. Run `yarn start`
5. You can see the error

## Expected behavior

App can run without `TypeError: (0 , _typeof2.default) is not a function` error like as dev.

## Screenshots

<img width="1016" alt="螢幕快照 2019-04-04 上午12 46 00" src="https://user-images.githubusercontent.com/21308003/55498007-272e0300-5675-11e9-9eeb-a7cefc30bec8.png">

## System information

 - OS: macOS 10.14.2
- Node.js: 10.15.2
 - Browser: Chrome
 - Version of Next.js: v8.0.4

## Additional Information

Here's my packages.json :
```
{
  "name": "",
  "version": "",
  "description": "",
  "main": "app/index.js",
  "author": "",
  "scripts": {
    "dev": "nodemon app/server --exec babel-node",
    "build": "next build app",
    "start": "NODE_ENV=production node app"
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      "next/babel"
    ]
  },
  "dependencies": {
    "@babel/register": "^7.4.0",
    "express": "^4.16.4",
    "next": "^8.0.4",
    "next-routes": "^1.4.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "@babel/node": "^7.2.2",
    "nodemon": "^1.18.10"
  }
}
```

**Comment by timneutkens** [comment]
Please provide a full reproduction, it's impossible to help based on the description provided.

**Comment by wellyshen** [comment]
@timneutkens I create a simple reproduced repo, you can see the error [here](git@github.com:wellyshen/next-debug.git)

**Comment by wellyshen** [comment]
@timneutkens I found this error occurs along with customized `_app.js`.

**Comment by wellyshen** [comment]
The root cause is I use additional `@babel/preset-env` for babel preset. It's included in Next library already.

**Comment by devsnowy** [comment]
I'm having same issue on 8.0.4. Not sure but i think it looks related to: "next/babel" preset.

**Comment by arobert93** [comment]
Please show us your .babelrc file. I had the same problem and fixed by removing a @babel/preset-env. I show the updated documentation and it says:
