### ISSUE TITLE
8.0.4 weird issue with firefox & query parameters in the url

### ISSUE THREAD

**Issue by probablyup** [zeit/next.js#6882]
# Bug report

there seems to be a regression in 8.0.4 specifically for newer versions of Firefox relating to next/router code

## Describe the bug

when landing on a page that contains query parameters, the browser becomes "locked" to that page and programmatically or manually navigating to a different same-domain page insta-redirects back to the original. note that this does not start happening until a query parameter is involved in the url, totally bizarre

## System information
 - OS: macOS
 - Browser (if applies) firefox 66
 - Version of Next.js: 8.0.4

## Additional context

Downgrading to 8.0.3 fixes this issue, so it's definitely something in nextjs. The two ways my (private) project moves between pages is typical anchor links and using `window.location.assign`.

**Comment by ijjk** [comment]
Probably related to #3817 and #6630

**Comment by probablyup** [comment]
Yeah #6630 looks to probably be it. Can we revert?

**Comment by ijjk** [comment]
It has been reverted, thanks for the info 👍

**Comment by kachkaev** [comment]
@Timer @ijjk @timneutkens folks, when about are you planning to release the next stable version? If it's still at least a few days away, WDYT of marking next `8.0.3` on npm as `latest` instead of `8.0.4`? Otherwise, lot of folks are downloading a version that has a pretty serios issue on FF, one of the most popular browsers 😬

**Comment by helsner** [comment]
@kachkaev we're using 8.0.3 on a project and got the same issue - but i'm with you, that this issue is serious

**Comment by timneutkens** [comment]
Released in 8.1

**Comment by tiagopinheiro-kununu** [comment]
It would be nice to have this revert with on a 8.0.5 version since moving to version 8.1 has some problems with IOS9 :(
