### ISSUE TITLE
getInitialProps query data changes when come back using safari

### ISSUE THREAD

**Issue by shimika** [zeit/next.js#6887]
# Bug report

## Describe the bug

When come back from other site using safari browser (Mac, iPhone)
getInitialProps query data changes.

String, Array -> not changed
Boolean, Number -> into String
Object -> into Empty String

## To Reproduce

Express.js server code
```jsx
server.get('/test', (req, res) => {
  return app.render(req, res, '/test', {
    string: 'stringValue',
    boolean: true,
    object: {
      key1: 'key1Value',
      key2: true,
    },
    array: [
      'hello',
      1,
      false,
      { hello: 'world' },
    ],
  })
})
```

Page code
```jsx
/* External dependencies */
import React from 'react'

/* Internal dependencies */

class Test extends React.Component {
  static getInitialProps({ query }) {
    console.log(query)
    return { ...query }
  }

  render() {
    return (
      <div>
        <div>
          Hello
        </div>
        <a href="https://google.com">Go to google</a>
      </div>
    )
  }
}

export default Test
```

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Click 'Go to google'
2. Slide touchpad right to go back
3. See terminal and safari console

## Screenshots
<img width="436" alt="1" src="https://user-images.githubusercontent.com/4963314/55528450-dac7df00-56d7-11e9-9a42-0d8d58ebbf0a.png">

![2](https://user-images.githubusercontent.com/4963314/55528452-ddc2cf80-56d7-11e9-93cb-a5d0c191f2cb.png)

## System information
 - OS: macOS
 - Browser safari 10.0
 - Version of Next.js: 7.0.2 
 - Express.js: 4.14.0

## Additional context

Is this same issue?
https://github.com/zeit/next.js/pull/6652

**Comment by Timer** [comment]
This appears to be a different issue.

**Comment by shimika** [comment]
Also appear in next.js 8.0.4

**Comment by ijjk** [comment]
This does appear to be related to #6652

**Comment by lvsenlin** [comment]
waiting for 8.0.5 ?
