### ISSUE TITLE
`process` is only defined when referenced in _app getInitialProps

### ISSUE THREAD

**Issue by omonk** [zeit/next.js#6888]
# Bug report

## Describe the bug
I'm setting env variables in next.config.js and destructing within `_app.js` to create an aws-amplify Auth (Cognito) instance. I found some strange behaviour, ultimately `process` is not defined in _app.js at all unless its referenced in getInitialProps. I understand that console.log is a blocking operation. 

If this isn't actually a bug, any suggestions where to define the amplify configure so I can use it throughout the app? It's a serverless build so I'm not able to use the `publicRuntimeConfig` options

## To Reproduce

I've put a repo together: https://github.com/omonk/nextjs-process
1. clone, npm i / yarn etc.
2. `npm/yarn run start` then open page and dev tools, you'll see `process is not defined` error with stack trace.
3. go to _app.js and uncomment line 15 `console.log({ process });` 
4. refresh local running instance and error has disappeared.

## Expected behavior
process to be defined without referencing it in getInitialProps.

## System information
 - OS: macOS
 - Browser chrome
 - Version of Next.js: 8.0.4

**Comment by omonk** [comment]
The `process is not defined error` can also be resolved if just referencing `process;` within getInitialProps so it's not a matter of console.log blocking I don't think.

**Comment by timneutkens** [comment]
The problem is actually that you're trying to destructure values whereas environment variables are inline-replaced in the bundles using webpack `DefinePlugin`. Meaning you write the in full and they're replaced at build time. Eg `process.env.ABC` will become the literal value `'def'` if you add `env: {ABC: 'def'}`.

So basically this won't work:

https://github.com/omonk/nextjs-process/blob/master/pages/_app.js#L4-L9

**Comment by omonk** [comment]
Riiiight ok that makes sense, thank you for your prompt response. I've made that update and it is indeed all working. 

I'd like to make a PR into the docs to clarify this to anyone else who has the same issue

**Comment by omonk** [comment]
Although @timneutkens can you explain why referencing `process` in `getInitialProps` seems to work?

**Comment by timneutkens** [comment]
Depends on how it's called, on Node.js side of things (SSR) we call getInitialProps, meaning `process` is there from Node.js. Ideally we would just block people from using `process` but it might break a bunch of user's code so we haven't (yet). It would be `undefined` / polyfilled by webpack on the client routing.

I'd be happy to take in a PR explaining it :100:

**Comment by omonk** [comment]
@timneutkens https://github.com/zeit/next.js/pull/6889
