### ISSUE TITLE
Next swallows logs from custom servers

### ISSUE THREAD

**Issue by Huxpro** [zeit/next.js#690]
I loved next.js log, which indicated compiling status so well.
But It seems eat all `console.log` from [custom server](https://github.com/zeit/next.js#custom-server-and-routing) and might make debugging harder.

```
// version
"next": "^2.0.0-beta.13"
"node": 6.9.1
```

**Comment by arunoda** [comment]
I didn't exactly got the question.
But you could try something like this:

```js
const app = next({ dev, quiet: true })
```

If we get a better way to reproduce this, we could help more.

**Comment by timneutkens** [comment]
@arunoda just something cosmetic: 
`quiet (bool) Display error messages with server information - default false`

Shouldn't this behaviour be inverted? Since `quiet: true` would imply it not logging errors

**Comment by Huxpro** [comment]
@arunoda Hmm...It seems to work now. 
Just forget about it. Might get into some weird situation that day.
BTW, @timneutkens 's suggestion is nice ;)

**Comment by timneutkens** [comment]
@Huxpro @arunoda Opened #717 for that suggestion.
