### ISSUE TITLE
with cookie auth not working with create-next-app or with Deploy to Now

### ISSUE THREAD

**Issue by sfkiwi** [zeit/next.js#6905]
# Examples bug report

## Example name
with-cookie-auth

## Describe the bug
1. Trying to build and deploy the example using the "Deploy Now" button on the repo fails to build.

`Deploy failed, please check the repo and try again.`

2. Using create-next-app to install the example also fails.

```
yarn create next-app --example with-cookie-auth with-cookie-auth-app
yarn create v1.15.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-next-app@0.5.9" with binaries:
      - create-next-app
> Error! Error downloading with-cookie-auth files for with-cookie-auth-app
(node:94474) UnhandledPromiseRejectionWarning: HttpError: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}
    at response.text.then.message (/Users/mike/.config/yarn/global/node_modules/@octokit/rest/lib/request/request.js:72:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:94474) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:94474) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 17.74s.
```` 

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:

For "Deploy to Now" issue:
1. Go to [example repo](https://github.com/zeit/next.js/tree/canary/examples/with-cookie-auth) and click "Deploy to Now" button at top of Readme.md
2. Generate token from zeit account
3. Copy/paste token into field labelled `ZEIT API TOKEN: _______________`
4. Click on "DEPLOY" button

For create-next-app issue see above:

## System information
 - OS: macOS
 - Browser (if applies): chrome

**Comment by j0lv3r4** [comment]
I think this happens because the root folder of the example doesn't have a `package.json`. I might be wrong but I'll add one and test it. If that's the issue I'll submit a PR with the fix.

Thanks for the report, @sfkiwi!

**Comment by j0lv3r4** [comment]
Yep, that's it https://github.com/segmentio/create-next-app/blob/master/lib/utils/load-example.js#L14

I'll submit the FIX later Today.
