### ISSUE TITLE
Why next.js in production mode still reads the next.config.js?

### ISSUE THREAD

**Issue by ematipico** [zeit/next.js#6906]
# Question about Next.js

I am trying to run production Next using a *custom server*. I am using the snippet provided by the documentation which works perfectly.

Now, in an attempt to reduce the size of the `node_modules`, I remove all the development dependencies (`npm i --production`) *after* I compile next using the command `next build`.

The problem is that when I try to run the custom server, I get error of missing packages that are supposed to be just for development (webpack, zeit/next-css, webpack plugins for some custom things) and so on. I also tried to run `next-server` but I got the same issue.

My question is: **why next needs to read from `next.config.js` even after I built the application?** How I can prevent from pulling devDependencies for a production build? Ideally this custom server would run on serverless environment so I don't want to copy/install all the dev dependencies

**Comment by timneutkens** [comment]
`publicRuntimeConfig` and `serverRuntimeConfig` need to be loaded in case that they're configured.

the `serverless` target doesn't load next.config.js.

**Comment by ematipico** [comment]
I am not build next in serverless mode.

**Comment by timneutkens** [comment]
That's what I'm saying, if you use the `server` target it needs to load next.config.js in case that there is `publicRuntimeConfig` and `serverRuntimeConfig`.

**Comment by ematipico** [comment]
I get it now! Thanks
