### ISSUE TITLE
Router.reload inconsistent behavior when using parameterized routes

### ISSUE THREAD

**Issue by josephrussell** [zeit/next.js#692]
Really appreciate the work you guys have done on this project. It's looking great.

With 2.0.0-beta.16, using the programmatic API on a route like /person/1 I'm trying to refresh the page without a full page reload using Router.reload. getInitialProps is being called again as expected, but pathname=/person/1 with no query. This is inconsistent from getInitialProps being called when loaded via a client Link navigation or from a server reload. In those cases pathname=/person and query={id:1}. I wonder if its not aware of the link, 'as' stuff that's needed to get Link to work.

The use case for this is when saving a change to the resource I want to sync any changes from the server to the current screen. I'm depending on that id to fetch the updated resource.

As a workaround I'm just doing a full page reload for now. Let me know if there is something I'm missing.

Example:

**server.js**
```javascript
const express = require('express')
const next = require('next')

const app = next({ dir: '.', dev: true })
const handle = app.getRequestHandler()

app.prepare()
.then(() => {
  const server = express()

  server.get('/person/:id', (req, res) => {
    return app.render(req, res, '/person', req.params)
  })

  server.get('*', (req, res) => {
    return handle(req, res)
  })

  server.listen(process.env.PORT || 3000, (err) => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000')
  })
})
```

**pages/index.js**
```javascript
import React, { Component } from 'react'
import Router from 'next/router';
import Link from 'next/Link'

class Index extends Component {
  static async getInitialProps (ctx) {
      return {updated:Date.now().toString(), pathname:ctx.pathname, id:ctx.query? ctx.query.id : null}
  }
  constructor(props) {
    super(props)
    this.onReload = this.onReload.bind(this);
  }
  onReload(e) {
    e.preventDefault();
    Router.reload('/');
  }
  render () {
    return (
      <div>
        <p>Expecting no id since route has no parameters, pathname=/, looks good for this case</p>
        <button onClick={this.onReload}>Reload</button>
          <p>updated:{this.props.updated}, pathname:{this.props.pathname}, id:{this.props.id}</p>
        <ul>
          <li>
              <Link href="/person?id=1" as="/person/1" >
                  <a>Troy - /person/1</a>
              </Link>
          </li>
        </ul>
      </div>
    )
  }
}

export default Index
```

**pages/person.js**
```javascript
import React, { Component } from 'react'
import Router from 'next/router';
import Link from 'next/Link'

class Person extends Component {
  static async getInitialProps (ctx) {
    return {updated:Date.now().toString(), pathname:ctx.pathname, id:ctx.query? ctx.query.id : null}
  }
  constructor(props) {
    super(props)
    this.onReload = this.onReload.bind(this);
  }
  onReload(e) {
    e.preventDefault();
    Router.reload('/person');
    // Also tried Router.reload('/person?id=1');
   // Didn't see any reference of 'as'
  }
  render () {
    return (
      <div>
        <p>Expecting to see id:1 when clicking update, same as initial load. same as initial server page load, or client navigation</p>
        <button onClick={this.onReload}>Reload</button>
          <p>updated:{this.props.updated}, pathname:{this.props.pathname}, id:{this.props.id}</p>
        <Link href="/">
          <a>Home</a>
        </Link>
        <h1>troy</h1>
      </div>
    )
  }
}

export default Person
```

**Comment by arunoda** [comment]
I think the use of `Router.reload()` is not this. It's meant for reloading the JSON page inside the app. 
@nkzawa am I correct?

If that's so, we may need to set `Router.reload()` as an internal method.

**Comment by nkzawa** [comment]
yep, `reload()` is an internal method. I wonder if we have to implement public one, not sure when you'd like to use it though.

**Comment by arunoda** [comment]
I am against the .reload() method for a router. In SPAs, it could handle with the state layer in much better way.

Routes should be idempotent.

**Comment by josephrussell** [comment]
Ok, makes sense. The reason I tried Router.reload was simply looking for a way to have getInitialProps called again. I will reload the state from my API internally and accomplish the same thing.

**Comment by arunoda** [comment]
@josephrussell great. I'm closing this now.
