### ISSUE TITLE
Very unperformanced CaseSensitivePathsPlugin. 

### ISSUE THREAD

**Issue by Carduelis** [zeit/next.js#6927]
# Bug report

## Describe the bug

Very slow building time using `npm run dev`. CaseSensitivePathsPlugin takes a significant time to proceed.

Fast machine Core i7
![SMP](https://habrastorage.org/webt/12/y6/n3/12y6n3nwjtsehzf4sik4iloof7o.png "Performance Core i7")

Laptop Pentium
![SMP](https://habrastorage.org/webt/se/_v/lo/se_vlo1cbjoakqzz6xwlwmkydku.png "Performance Laptop Pentium")
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Install [SMP](https://www.npmjs.com/package/speed-measure-webpack-plugin) to detect the time
2. Wrap the config with `new SpeedMeasurePlugin().wrap(config)`
3. run `npm run dev`
4. See the screenshot above

## Expected behavior
The first plugin took a lot of time to execute. Should not be a issue in every repo.

## System information
 - OS: Windows
 - Version of Next.js: [ 8.0.3]

## Additional context
The issue could be caused by aliases, but no time to check.

**Comment by Carduelis** [comment]
I've tested this plugin with `{ debug: true }` and found that it's checking all of the modules including `node_modules`, so it does 2k+ reads every time
> [CaseSensitivePathsPlugin] Total filesystem reads: 2566

**Comment by timneutkens** [comment]
8.0.4 doesn't have CaseSensitivePathsPlugin for this reason.

**Comment by timneutkens** [comment]
Speed measure plugin looks nice btw, hadn't seen it before 💯

**Comment by Carduelis** [comment]
> Speed measure plugin looks nice btw, hadn't seen it before 💯

Could you include this measure, btw? The thing is when I wrap it, it breaks further work: next.js does not render anything and a browser does not open the app.

So, to measure I need to enable it, then disable to test is app loading ok. I think, the reason is SMP is not a plugin, but a config wrapper

**Comment by Carduelis** [comment]
@timneutkens 
After installing **next 8.0.4**
I've caught the SMP output (via ScreenToGif), cause you clear the console output xD.
![img](https://habrastorage.org/webt/me/er/1c/meer1c_xt_91i3psemjckfod8mw.png)

Thanks!

**Comment by timneutkens** [comment]
🙏
