### ISSUE TITLE
`now dev` ENOENT

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#6935]
`ENOENT: no such file or directory, chmod '/var/folders/ly/4jx0_c9x1271wrwsrvj_cngh0000gn/T/co.zeit.now/dev/workPaths/s66cb69o/node_modules/@babel/core/lib/config/files/types.js'`

When forcing a reload

**Comment by dav-is** [comment]
I can't reproduce this one

**Comment by timneutkens** [comment]
@TooTallNate said this is a bug in `now dev` I think.
