### ISSUE TITLE
`now dev` running `yarn` / `npm install` whenever refreshing

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#6937]
Every force refresh `yarn` is used while we already know it's not needed because the initial build installed dependencies. We should monitor `yarn.lock`/`package-lock.json`/`package.json` for changes.

**Comment by TooTallNate** [comment]
This shouldn't be an issue anymore now that `prepareCache()` is implemented in `now dev`.

**Comment by dav-is** [comment]
In this issue (https://github.com/zeit/next.js/issues/6936), you show `yarn` only taking `0.38s` to install.
```
yarn install v1.15.2
warning package.json: No license field
warning create-next-example-app: No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.38s.
```

Maybe this would be a good optimization for `@now/build-utils` later down the road
