### ISSUE TITLE
es6 stage?

### ISSUE THREAD

**Issue by webular** [zeit/next.js#694]
I'm getting the following:

```
Error in ./common/form
Module build failed: SyntaxError: Unexpected token, expected { (1:7)

> 1 | export Input from './Input';
    |        ^
  2 | export InputGroupButton from './InputGroupButton';
  3 | export Select from './Select';
  4 | export Select2 from './Select2';
```

I'm wondering if this has something to do with the default es6 stage next.js uses.  Is there a way for us to change this?  Or am I way off?  Thanks in advance.

**Comment by webular** [comment]
For future posterity:

Turns out you can simply add a custom .babelrc file at the root of the project.  

Here is what worked for me:
```
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": [
    "transform-async-to-generator",
    "transform-object-rest-spread",
    "transform-class-properties",
    "transform-runtime"
  ]
}
```

**Comment by adrianmcli** [comment]
@webular did you have to install those extra dependencies yourself? I assume that NextJS already has some of those presets.

**Comment by timneutkens** [comment]
@adrianmcli you need to include the `next/babel` preset too. Otherwise functionality might break.

**Comment by webular** [comment]
@adrianmcli Yes I did. 

npm install --save-dev babel-preset-stage-0

**Comment by webular** [comment]
**update** - use this instead:

```
{
  "presets": [
    "next/babel",
    "stage-0"
  ]
}
```
