### ISSUE TITLE
Could not get babel-root-import to work

### ISSUE THREAD

**Issue by kolpav** [zeit/next.js#695]
I would like to import modules as I was traversing from root directory so I don't need to do `../../../../../mymodule` but without success.
This is my `.babelrc` file. Did I miss something?
```javascript
// .babelrc
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    ["babel-root-import"]
  ]
}
```

**Comment by arunoda** [comment]
This is working pretty well. You need to use tidle(~) as the root when importing your module.
Like: `import Counter from '~/components/Counter'`

You need to use our beta version. Use `^2.0.0-beta` in the package.json for the "next".

If this doesn't fix your issue, send us a way to reproduce with the error you got.

**Comment by kolpav** [comment]
Thanks a lot! It is working now. Usually when you are using webpack root resolve you don't need to use `~`
