### ISSUE TITLE
Use case-sensitive-paths-webpack-plugin

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#696]
Mostly in macOs it resolves files without case-insensitively. This will cause errors in production.

Discussion on slack: https://zeit-community.slack.com/archives/next/p1483839382004382

**Comment by rauchg** [comment]
By the way, I haven't looked at the precise implementation details, but I'd like to make sure we handle this case:

- `./pages/index.js`
- `./pages/About.js`

Inside `./pages/index`:

```jsx
import Link from 'next/prefetch'
export default () => (
  <Link href="/about"><a>Hi</a></Link>
)
```

This will work on the mac but not Linux. We might want to add a check at the `/_next` routes handler for that case. Honestly, it might be the only case?

**Comment by arunoda** [comment]
@rauchg good point.

**Comment by arunoda** [comment]
But we still need to add this webpack plugin because it's related to imports.
We need to handle this with about page resolver too.

**Comment by rauchg** [comment]
Yeah good point
