### ISSUE TITLE
Dynamic module can't be applied without build?

### ISSUE THREAD

**Issue by markolofsen** [zeit/next.js#6974]
When I'm trying load dynamically component from different folder (with symlink) I getting an error. I think it happenings because my folder with other's components isn't builded.
How dynamically load my components without prebuilds?

```javascript
import dynamic from 'next/dynamic'
const DynamicComponentWithNoSSR = dynamic(
  () => import('./symlink_folder/my_component'),
  {
    ssr: false
  }
)
```

**Comment by timneutkens** [comment]
I'm not sure what you mean based on the description / no issue template + reproduction. But sounds like you're expecting `import()` to not be handled by webpack, which is currently not possible.
