### ISSUE TITLE
Flying Shuttle does not work with `index` pages

### ISSUE THREAD

**Issue by Timer** [zeit/next.js#6988]
Flying shuttle fails to load chunks for `index` pages, e.g. `pages/about/index.js`.
Naming the page `pages/about.js` allows chunks to be loaded just fine.

We need to identify why. I'm guessing we need to set `publicPath` in our webpack config.

**Comment by ijjk** [comment]
This has been resolved

**Comment by Timer** [comment]
By https://github.com/zeit/next.js/pull/6993
