### ISSUE TITLE
next.js fails when installed as a dependency with npm link

### ISSUE THREAD

**Issue by reel** [zeit/next.js#699]
If I install next.js as a dependency of a module, then `npm link` that module and try to use it in another project, I get the following error:

```
 ERROR  Failed to compile with 6 errors

These dependencies were not found in node_modules:

* ./pages/a.js?entry
* ./pages/b.js?entry
* ./pages/index.js?entry
* C:\Users\user\code\next-as-deps\with-next\node_modules\next\dist\pages\_error.js?entry
* C:\Users\user\code\next-as-deps\with-next\node_modules\next\dist\pages\_error-debug.js?entry
* C:\Users\user\code\next-as-deps\with-next\node_modules\next\dist\pages\_document.js?entry

Did you forget to run npm install --save for them?
> Ready on http://localhost:3000
```

I made a full reproduction in this repo: https://github.com/reel/next-as-deps

**Comment by arunoda** [comment]
I can what's going on here.

**Comment by reel** [comment]
What was your thoughts, @arunoda ?

**Comment by arunoda** [comment]
The root problem here is Webpack instance cannot find out NPM packages for it's loaders.
There are two ways to fix this issue.

### Solution 1

* Install `with-next` directly into the `main-app` once
* Then link `with-next` into `main-app`

You are good to go.

### Solution 2

Wait until this PR get merged: https://github.com/zeit/next.js/pull/778
Then run following command:

> NODE_PATH=../with-next/node_modules node index.js
