### ISSUE TITLE
After next build, - process.env.NODE_ENV !== 'production' returns true regardless of value

### ISSUE THREAD

**Issue by dougwithseismic** [zeit/next.js#7018]
# Bug report

## Describe the bug

After building using `next build` -  App `dev` always set to true even when declaring `process.env.NODE_ENV = production` using Express custom server. As a result, page compiles on every load and server isn't actually running in production mode.

I've deleted the .next folder and built fresh - still happens.

If you explicitly set `const dev = false` in server.js, it works as intended and build runs just fine, but running `yarn start` - `( "start": "set NODE_ENV=production & node server/server.js" )` then `dev` will always return true.

**EDIT- Yes . I am dumb. For windows users, try "set NODE_ENV=production&& node server/server.js" instead - Note the double & and no space beforehand.  Feel free to close this stupidity 👍** 

First noted that it was weird that I was getting the `Compiled successfully!` - `Note that pages will be compiled when you first load them.` message in console, despite setting node_env to production. Am I doing something wrong? It feels like I've done something stupid.
```
from server/server.js - 

console.log("NODE_ENV", process.env.NODE_ENV) // production
const dev = process.env.NODE_ENV !== 'production'
console.log("isDev?", dev) // returns true
const app = next({ dev }) // set to true as a result!
```

**Comment by Timer** [comment]
It sounds like you figured this out. Let us know if you're still having trouble.
