### ISSUE TITLE
Node v6 support for Next.js 8

### ISSUE THREAD

**Issue by pellejacobs** [zeit/next.js#7043]
# Bug report

## Describe the bug

It seems that next@8 files are not transpiled for node v6 support. Eg. https://unpkg.com/next@8.0.4/dist/server/next-dev-server.js uses async await. 

## To Reproduce

1. `nvm use 6.17.1` 
2. `npm install next@8.0.4` in a node project
3. It will error on `dist/server/next-dev-server.js` as it uses async await

## Expected behaviour
I would expect next to be transpiled to be supported on earlier versions of node, such as next@7 was. 

## System information
 - OS: Windows
 - Version of Next.js: 8.0.4

## Additional context

Currently, the only solutions are to either use next@7, as it is transpiled properly (https://unpkg.com/next@7.0.3/dist/server/next-dev-server.js) or transpile the next and next-server folders at runtime with babel, neither is ideal.

Thanks for a great project!

**Comment by timneutkens** [comment]
Next.js supports Node 8+

**Comment by pellejacobs** [comment]
Ok, thanks for the reply Tim.
