### ISSUE TITLE
next/head not applying the tags in the <Head>

### ISSUE THREAD

**Issue by webdevsyd** [zeit/next.js#7062]
So I have this code in my `_document.js`, In my pages file I try to add a meta tags but it seems it doesn't applied on the page

Here's the code in one my pages:

`return (`
  `<Head>`
    `<title>Testing</title>`
  `</Head>`
`)`

`_document.js`

`
	
	export default class MyDocument extends Document {
	  static async getInitialProps (ctx) {
	    const sheet = new ServerStyleSheet()
	    const originalRenderPage = ctx.renderPage
	    const {
	      req: { locale, localeDataScript }
	    } = ctx
	    try {
	      ctx.renderPage = () =>
	        originalRenderPage({
	          enhanceApp: App => props => sheet.collectStyles(<App {...props} />)
	        })
	
	      const initialProps = await Document.getInitialProps(ctx)
	      return {
	        ...initialProps,
	        locale,
	        localeDataScript,
	        helmet: Helmet.renderStatic(),
	        styles: (
	          <>
	            {initialProps.styles}
	            {sheet.getStyleElement()}
	          </>
	        )
	      }
	    } finally {
	      sheet.seal()
	    }
	  }
	  render() {
	    return (
	      <html>
	        <Head>
	          <meta chartSet="utf-8" />
	            <script
	              dangerouslySetInnerHTML={{
	                __html: this.props.localeDataScript
	              }}
	            />
	        </Head>
	        <body>
	          <Main />
	          <NextScript />
	        </body>
	      </html>
	    )
	  }
	}
`

**Comment by timneutkens** [comment]
Please follow the issue template and provide a *clear and full reproduction*.
