### ISSUE TITLE
Server return a 401 when trying to get manifest.json

### ISSUE THREAD

**Issue by HectorLS** [zeit/next.js#7067]
# Bug report

manifest.json located at `/static/assets/files/manifest.json` got 401

but in the `server.js` file
```js
server.use('/static', express.static(path.join(__dirname, 'static')));
```

I can access all the images stored in static/assets/images with that line so... there is a special config for no media files ?

**Comment by timneutkens** [comment]
This doesn't sound related to Next.js.
