### ISSUE TITLE
commons.js has syntax error on IE11

### ISSUE THREAD

**Issue by fchengpc** [zeit/next.js#7077]
showing blank page on ie11 with following error in console.

![Screen Shot 2019-04-18 at 3 33 18 PM](https://user-images.githubusercontent.com/6640631/56386283-5903a580-61ef-11e9-8220-b866ce33e4ab.png)

Running next 8.1.0

**Comment by timneutkens** [comment]
Please follow the issue template and provide a full reproduction. It's probably some code in your node_modules.
