### ISSUE TITLE
with-cookie-auth fails to deploy to now

### ISSUE THREAD

**Issue by kylemh** [zeit/next.js#7085]
# Examples bug report

## Example name
[with-cookie-auth](https://github.com/zeit/next.js/blob/canary/examples/with-cookie-auth)

## Describe the bug
Deployments to Now fail.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to [here](https://deploy.now.sh/?repo=https://github.com/zeit/next.js/tree/master/examples/with-cookie-auth)
2. Put in a Zeit API key
3. Click "Deploy"
4. Wait as ~3 minutes of `Initialising...` persists
5. Deploy fails.

## Expected behavior
Steps 1 thru 3 and then - after a short period of time - I see a link to the deployment.

## Screenshots
![Screen Shot 2019-04-19 at 1 01 54 AM](https://user-images.githubusercontent.com/9523719/56414230-c559c580-623e-11e9-9094-b2b45c396fe7.png)

## More Info
#6905

**Comment by huv1k** [comment]
Sorry, but https://deploy.now.sh is no longer supported for deployments. You should follow `readme`.
