### ISSUE TITLE
./static folder with hot code reload?

### ISSUE THREAD

**Issue by thebetterjort** [zeit/next.js#709]
I have video files that I serve out of the /static/ folder. As a user streams a video it gets added automatically to static. The issue is that the page doesn't refresh when a new video is added, forcing the user to hit refresh to get the new data.

Is there a fix that I can use to make the static folder force a render? Maybe I use componentDidMount() and just query the directory? Any thoughts on the best way to do this would be appreciated.

**Comment by arunoda** [comment]
We do hot-reload only un the dev mode only.
So, your original goal might not work here.

To clarify my above point, are you looking this as a production behaviour or only in dev mode?

**Comment by thebetterjort** [comment]
Looking for production. I think I'm going to rethink my approach.

**Comment by impronunciable** [comment]
@thebetterjort you can integrate next with the node.js ecosystem https://github.com/zeit/next.js#custom-server-and-routing or run another separate server. HMR is for code and your videos are more like your data rather than your code.

Since it seems to be a nofix I'm closing this issue but feel free to reopen

**Comment by andres314** [comment]
@arunoda & @impronunciable Sorry to bother with this closed issues, but I have a question related to this.  I have a global CSS compiled to the 'static' folder doing this:

`"scripts": {
    "build": "next build",
    "prestart": "next build",
    "start": "node server.js",
    "dev": "parallelshell \"node server.js\" \"yarn watch:css\"",
    "css": "node-sass --include-path css --output-style compressed styles/styles.scss static/css/bundle.css",
    "watch:css": "yarn css"
  },`

What I'm looking for is to have hot reload when the css file is compiled. Is there a way to do it?

**Comment by luisrudge** [comment]
I want to do the same thing as @andres314. Is it possible, @arunoda?

**Comment by programbo** [comment]
Turns out I need to do the same thing until the next major version of Grommet (with css-in-js) is released.
