### ISSUE TITLE
"findDOMNode was called on an unmounted component." error while deploy projects

### ISSUE THREAD

**Issue by lelong310590** [zeit/next.js#7092]
Hi everyone !

i got a error #44 while trying to deploy my project on the server

https://reactjs.org/docs/error-decoder.html/?invariant=44

I follow the tutorial in this link: https://gist.github.com/Kocisov/2a9567eb51b83dfef48efce02ef3ab06?fbclid=IwAR1BsJ0VVQvO9ELBG2vu9bHP2rNeltD9xUuczBFtyvasOnpIAnAifr-G9Mo

Everything works well on dev mode, but when i try to deploy with command:  `npm run start` , it got error !

Can anyone help me ?

**Comment by timneutkens** [comment]
This is probably not an issue with Next.js. Please post your question on spectrum.chat/next-js.
