### ISSUE TITLE
Bundling

### ISSUE THREAD

**Issue by imranweb** [zeit/next.js#7098]
# Question about Next.js bundling strategy.

I am using NextJS 8 version. After running the production build, i could see following bundles loading in browsers:
- index.js
-_app.js
- webpack-a79426b5e11f0ba5879d.js
- commons.5f6154c7f0c094cd3e44.js
- main-ea67ec1b1d4113e5d0f7.js

I want to understand on what logical basis these bundles are getting created? 
Is there any documentation about bundling strategy in NextJS?

**Comment by timneutkens** [comment]
main -> Next.js runtime
commons -> common modules (used in 50% of all pages currently)
webpack -> webpack runtime
_app -> App component
index -> Page component

**Comment by imranweb** [comment]
Sorry, its not clear to me.
How does nextjs decides which modules to go in **common** and which modules to go in **main**?
How can I configure it what all modules to go in main.js?
