### ISSUE TITLE
Next.js 8.1 has broken build: The "original" argument must be of type function

### ISSUE THREAD

**Issue by LoicVerrall** [zeit/next.js#7109]
# Bug report

## Describe the bug

Since upgrading my version of `next` from **8.0.4** to **8.1**, the next build command no longer works and the following is outputted:

> "(node:1055) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
> (node:1055) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

Can confirm that this is a new bug, as downgrading next version back to 8.0.4 resolves the issue. The issue is not only present in my apps, but also the examples.

## To Reproduce
1. Clone the next.js repo.
2. Change directory to `/examples/custom-server`.
3. `npm i`.
4. `next run build`.

And you'll end up with the above error.

## Expected behavior
A production-optimised build of the app is generated.

## System information
 - OS: macOS
 - Version of Next.js: 8.1

**Comment by MarchWorks** [comment]
Tested on custom-server-express example 
OS: Windows
No problem

**Comment by stovmascript** [comment]
I have the same problem. What is your node version @LoicVerrall? I'm running v11.10.0.

**Comment by stovmascript** [comment]
Hm, just tried building, starting and also running dev for `examples/custom-server` and `examples/custom-server-express` and they both work..

**Comment by LoicVerrall** [comment]
Ah, so I was running node `v8.1.4`. Updating to `v12.0.0` resolves the issue so I'll close this issue.
Thanks for the help @stovmascript!

**Comment by stovmascript** [comment]
I also tried node v12.0.0, but with that I get something even wilder:

```
$ yarn build
yarn run v1.15.2
$ rimraf .next && next build
Creating an optimized production build ...



#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ffeefbf2e00/bin/sh: line 1: 14501 Illegal instruction: 4  next build
error Command failed with exit code 132.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by stovmascript** [comment]
It seems to have been introduced in this version: https://github.com/zeit/next.js/releases/tag/v8.0.5-canary.12

**Comment by LoicVerrall** [comment]
Do you get that error on the example projects as well?
If so, perhaps you could try using `npm` instead of `yarn` to isolate the cause a little further?

**Comment by stovmascript** [comment]
Well the problem in the error I posted seems to be a bad value being passed into the `.update()` method of `createHash` from `crypto` here:

https://github.com/zeit/next.js/blob/09717e04562a48c6e88e75d16b218dd6cd429368/packages/next/build/webpack/plugins/hashed-chunk-ids-plugin.ts#L30

In my case the array of ids sometimes contains a number (`2`), which trips up this method expecting a string or a buffer, etc.

@Timer Converting the number to a string to be hashed works, but I have no idea if that will have any unintended side effects. I can submit a PR should this be an ok fix, tests are passing.

**Comment by Timer** [comment]
@stovmascript if you delete `.next/records.json` does this still reproduce?

**Comment by MarchWorks** [comment]
shouldn't you use the stable version of node `v10.15.3` it's the one that I used

**Comment by stovmascript** [comment]
@Timer I'm actually already doing that, my build script is `rimraf .next && next build`.

**Comment by stovmascript** [comment]
@MarchWorks I also tested on v10.10.0, but no go.

I think the examples are working because they don't generated chunks that have ids which are just numbers.

**Comment by MarchWorks** [comment]
> In my case the array of ids sometimes contains a number (2), which trips up this method expecting a string or a buffer, etc.

@stovmascript can't you convert them to string?

**Comment by Timer** [comment]
@stovmascript converting the ID to a string isn't the correct fix -- this is a webpack bug.

Can you please share a reproducible demo with me so we can fix the root cause? The module IDs _must_ be computed -- having an numerical module ID isn't going to work soon.

**Comment by stovmascript** [comment]
Thought so.

Currently it's happening on a private project, so can't share that, but
I'll try to derive a new demo from that somehow.

Dne st 24. 4. 2019 16:23 uživatel Joe Haddad <notifications@github.com>
napsal:

**Comment by Timer** [comment]
@stovmascript actually, can you hand edit your `webpack-config` in `node_modules` and find this line:
```js
!dev && selectivePageBuilding && new AllModulesIdentifiedPlugin(dir)
```

and change it to:
```js
!dev && new AllModulesIdentifiedPlugin(dir)
```

And report back if that fixes it?
Thanks!

**Comment by stovmascript** [comment]
@Timer Yup, that does it.

Also dumps some stuff into the console, along the lines of:

```
> module identifier: MultiModule multi private-next-pages/_app.js => 1TCz
> module identifier: MultiModule multi private-next-pages/_document.js => 5w0S
> module identifier: MultiModule multi private-next-pages/_error.js => Y0NT
```

**Comment by Timer** [comment]
Excellent @stovmascript, can you send a PR removing that switch from the plugin? 🙏

**Comment by brothatru** [comment]
Ran into same exact error on nextjs **v8.1.0**.

Was only happening on a new page I created.

**Issue:**

I was importing a **server-side** only node module on my new page component.

**Resolution:**

import the module only when nextjs is running server-side.

ie.
```
static getInitialProps() {
    if (!process.browser) {
         const server_side_module = require('path_to_module');
    }
}
```
