### ISSUE TITLE
Service worker error on Firefox - Response.Headers.getAll undefined

### ISSUE THREAD

**Issue by danhawkes** [zeit/next.js#711]
FF 52.0a2 (2017-01-09) 

Seems the issue is that `Response.Headers.getAll` is undefined on the latest firefox:

https://github.com/zeit/next.js/blob/0551dc90a14d4beda8dc64058c4ae2837cc61ec6/client/next-prefetcher.js#L19

Apparently it's been removed from the latest spec:

https://www.fxsitecompat.com/en-CA/docs/2016/headers-getall-has-been-removed-in-favour-of-get-now-returning-all-values/

**Comment by impronunciable** [comment]
@danhawkes thanks for reporting!
