### ISSUE TITLE
opt-out of @zeit/next-typescript

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#7115]
Since Next.js will know how to compile TS there is no need for the user to add it, however many users are using it today and we don't want to cause double-compiles because of this, so we should negate the effect of adding next-typescript to the project and show a warning.

**Comment by timneutkens** [comment]
@fonger I'm not sure about your reaction 🤷‍♂️

**Comment by Fonger** [comment]
> @Fonger I'm not sure about your reaction 🤷‍♂️

Does that mean we don't need it in the custom .babelrc in the future?

```diff
-  "presets": ["next/babel", "@zeit/next-typescript/babel"],
+  "presets": ["next/babel", "@zeit/next-typescript/babel"],
```

**Comment by timneutkens** [comment]
Yes
