### ISSUE TITLE
Can't go from a page not containing a css file to another containing one

### ISSUE THREAD

**Issue by MarchWorks** [zeit/next.js#7116]
# Examples bug report

## Example name
with-next-css

## Describe the bug
Impossible to go from one page which doesn't contain an imported css file to a one containing an imported css file

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository: https://github.com/MarchWorks/with-next-css-issue
1. Go to 'index page'
1. Click on 'About'
2. See error

## System information
 - Version of Next.js: 8.1.0

**Comment by timneutkens** [comment]
Duplicate of https://github.com/zeit/next-plugins/issues/282
