### ISSUE TITLE
Sub pages do not get built automatically when having changes

### ISSUE THREAD

**Issue by dukemai** [zeit/next.js#7122]
# Bug report

## Describe the bug

my pages are organized as the following
- Profile
--index.js
--SubPage.js

when any sub pages under Profile is changed but no update is made to front-end. I needed to restart the node process

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create several pages under a folder
2. Make changes to any of them
3. Expect changes updated on front immediately

## Expected behavior
Actually nothing gets updated

## System information
"next": "^8.1.0",
"react": "^16.8.6",
"react-dom": "^16.8.6",

**Comment by timneutkens** [comment]
Can you provide a reproduction repository?

**Comment by dukemai** [comment]
I can send you in private. I do not want to public here.

**Comment by MarchWorks** [comment]
@dukemai I tested the HMR in your repo and it's working in the sub pages without a problem

**Comment by dukemai** [comment]
did it work for you when you update something in sub pages? it worked for me with pages without folders.

**Comment by MarchWorks** [comment]
@dukemai you are speaking about the pages under the `profile` folder it worked without problem

**Comment by dukemai** [comment]
hmmm, it did not work properly for me. weird. I am using Mac, what kind of os are you using?

**Comment by MarchWorks** [comment]
window
node v10.15.3

**Comment by dukemai** [comment]
I think I know the reason now. because I have Uppercase for folders but I browsed with lowercase url. And on mac folders are not case sensitive :D. that confused webpack I guess. it seems to work well when I make all folders under pages lowercase
