### ISSUE TITLE
improve build

### ISSUE THREAD

**Issue by pmjhonwang** [zeit/next.js#7131]
# Feature request

## Is your feature request related to a problem? Please describe.
Our project is a large project and It at least 30 minutes to build, with sourcemap.
BTW we use sentry to catch errors only browser.
There is a way that only get sourcemap for browser assets to improve build fast.

## Describe the solution you'd like
* no idea.

## Describe alternatives you've considered
* server sider do not need sourcemap.

## Additional context
-

**Comment by timneutkens** [comment]
Questions should be posted on spectrum.chat/next-js.
