### ISSUE TITLE
Unexpected token when using "node server.js" with transpiled express server

### ISSUE THREAD

**Issue by angel200sdnot** [zeit/next.js#715]
I am using babel to transpile everything into a build folder, if i try running server.js with
`cd build`
`node server.js`
I get this error
`SyntaxError: C:/web-liga/node_modules/next/dist/pages/_error-debug.js?entry: Unexpected token (14:11)`
```javascript
  12 |     const { name, message, stack, path } = this.props
  13 |
> 14 |     return <div className='errorDebug'>
     |            ^
  15 |       <Head>
  16 |         <meta name='viewport' content='width=device-width, initial-scale=1.0' />
  17 |       </Head>
```
But if i run the server using "npm run dev"
```javascript
"scripts": {
    "build": "node_modules/.bin/babel ./ --out-dir build -s --ignore node_modules",
    "clean": "rm -rf build && mkdir build",
    "dev": "npm run clean && npm run build && npm run watch",
    "start": "NODE_ENV=production node build/server.js",
    "watch": "node_modules/.bin/babel-watch --exclude components --exclude pages --exclude .next build/server.js"
  }
```
Everything runs perfectly except that .next is getting compiled outside of the build folder because thats where im running npm from

All of this brings problems when trying to deploy to heroku or now

**Comment by aranajhonny** [comment]
could you show this file complete, gist or pastebin.

**Comment by angel200sdnot** [comment]
http://pastebin.com/jRHgar4Z

This is the file structure

-actions
-build
-components
-database
-layouts
-node_modules
-pages
-reducers
-services
package.json
server.js
store.js

**Comment by aranajhonny** [comment]
@angel200sdnot was the other file that contains the head.

**Comment by angel200sdnot** [comment]
@aranajhonny None of my files is has <Head>

**Comment by aranajhonny** [comment]
ok but so it is difficult to help you. there must be a syntax error somewhere.

**Comment by angel200sdnot** [comment]
Yeah i know, sorry i've been trying to fix this for days now, in the meantime ive been using the "npm run dev" to keep on developing
If you want the file the error is pointing at its located in the next module, which is this
```javascript
import React from 'react'
import Head from 'next/head'
import ansiHTML from 'ansi-html'

export default class ErrorDebug extends React.Component {
  static getInitialProps ({ err }) {
    const { name, message, stack, module } = err
    return { name, message, stack, path: module ? module.rawRequest : null }
  }

  render () {
    const { name, message, stack, path } = this.props

    return <div className='errorDebug'>
      <Head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      </Head>
      {path ? <div className='heading'>Error in {path}</div> : null}
      {
        name === 'ModuleBuildError'
        ? <pre className='message' dangerouslySetInnerHTML={{ __html: ansiHTML(encodeHtml(message)) }} />
        : <pre className='message'>{stack}</pre>
      }
      <style jsx global>{`
        body {
          background: #a6004c;
          margin: 0;
        }
      `}</style>
      <style jsx>{`
        .errorDebug {
          height: 100%;
          padding: 16px;
          box-sizing: border-box;
        }

        .message {
          font-family: "SF Mono", "Roboto Mono", "Fira Mono", menlo-regular, monospace;
          font-size: 10px;
          color: #fbe7f1;
          margin: 0;
          white-space: pre-wrap;
          word-wrap: break-word;
        }

        .heading {
          font-family: -apple-system, BlinkMacSystemFont, Roboto, "Segoe UI", "Fira Sans", Avenir, "Helvetica Neue", "Lucida Grande", sans-serif;
          font-size: 13px;
          font-weight: bold;
          color: #ff84bf;
          margin-bottom: 20pxl
        }
      `}</style>
    </div>
  }
}

const encodeHtml = str => {
  return str.replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

// see color definitions of babel-code-frame:
// https://github.com/babel/babel/blob/master/packages/babel-code-frame/src/index.js

ansiHTML.setColors({
  reset: ['fff', 'a6004c'],
  darkgrey: 'e54590',
  yellow: 'ee8cbb',
  green: 'f2a2c7',
  magenta: 'fbe7f1',
  blue: 'fff',
  cyan: 'ef8bb9',
  red: 'fff'
})
```

**Comment by aranajhonny** [comment]
everything looks good, apparently the error has nothing to do directly with next.js you can be on the other side.

**Comment by mattecapu** [comment]
try to wrap your returned value with ()

**Comment by arunoda** [comment]
@angel200sdnot can we have a sample repo of this? So, we could have a look at this quickly.

**Comment by angel200sdnot** [comment]
@arunoda https://github.com/angel200sdnot/web-liga

**Comment by arunoda** [comment]
I can see the error. It's kind a weird. I'm looking at it.

**Comment by arunoda** [comment]
@angel200sdnot here's how you can fix this issue.

First of all, remove everything in your `node_modules` directory.
Then remove `node_modules` from your babel ignore list.

**Comment by angel200sdnot** [comment]
@arunoda This fixed the issue, thanks

**Comment by arunoda** [comment]
@nkzawa we get this because, we don't transpile content inside our pages directory.
Then user explicitly asked to ign

**Comment by arunoda** [comment]
@angel200sdnot great.
But I want to do a proper fix: https://github.com/zeit/next.js/pull/731
