### ISSUE TITLE
static property inheritance complaining when it shouldn't

### ISSUE THREAD

**Issue by sheshtiwari** [zeit/next.js#7159]
# Bug report
I've seen that you've already closed many issues on this. But I'm reporting another one in hopes to wear you down.

It seems I can't change the signature of a static function in a derived class. The fact that the subclass is at all aware of the static functions on the super class is really strange.

The Error is - 

Class static side 'typeof MyApp' incorrectly extends base class static side 'typeof App'.
  Types of property 'getInitialProps' are incompatible.
    Type '({ apolloClient, ...ctx }: NextContextWithApollo) => Promise<{}>' is not assignable to type '(context: NextAppContext<Record<string, string | string[] | undefined>>) => Promise<DefaultAppIProps>'.
      Types of parameters '__0' and 'context' are incompatible.
        Type 'NextAppContext<Record<string, string | string[] | undefined>>' is missing the following properties from type 'NextContextWithApollo': apolloClient, pathname, query, asPath

## Describe the bug

Reduced the example to minimalistic, but still getting the error

interface NextContextWithApollo extends NextContext {
  apolloClient: ApolloClient<NormalizedCacheObject>;
}

interface Props {
  apolloClient: ApolloClient< NormalizedCacheObject >;
}

class MyApp extends App< Props > {

  static async getInitialProps({
    apolloClient,
    ...ctx
  }: NextContextWithApollo): Promise<{}> {
    
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    return {};
  }
}

## System information
 - OS: Ubuntu
 - Browser  chrome
 - Version of Next.js: 8.0.4

**Comment by timneutkens** [comment]
I'm not sure how this related to Next.js at this point 🤔
