### ISSUE TITLE
Invert `quiet` option

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#717]
Taken from https://github.com/zeit/next.js/issues/690

`quiet (bool) Display error messages with server information - default false`

Shouldn't this behaviour be inverted? Since `quiet: true` would imply it not logging errors

**Comment by nkzawa** [comment]
👍  I'd like to fix the document rather than the option.

**Comment by timneutkens** [comment]
@nkzawa I guess this involves changing both. Will have a look tonight 👍
