### ISSUE TITLE
beforePopState() does not fire at all

### ISSUE THREAD

**Issue by mkondel** [zeit/next.js#7175]
# Bug report

## Describe the bug

When the user clicks on their browser's back button, I want to execute some custom logic for my app. I tried using Router.beforePopState() in my React component, but it never gets called. My goal is to be able to detect when the back button is pressed. I found example code in #6784  that shows the behaviour that I am talking about.

## To Reproduce
Repo: https://github.com/mlnor27/nextjs-bug-to-reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. go to http://localhost:3000/
2. manually type out the link to the about page in your browser's url bar and press enter: http://localhost:3000/about
3. click your browser's back button
4. there is no alert popup, beforePopState never seems to get called

You can see that pop up if you click the link to 'about' page from the '/', instead of manually typing it into the url bar as in step 2.

## Expected behavior
I want to detect when the user clicks their back button. In the provided example I expect to see an alert popping up.

## Screenshots
Here is a screen capture:
1. manually typing into the address bar results in no popups
2. clicking the link, then pressing the back button to show that popup
![about](https://user-images.githubusercontent.com/3288757/56833696-36037200-683d-11e9-89c4-19e15144c324.gif)

## System information
 - OS: Linux
 - Browser (if applies) Firefox Version 64.0.2 (64-bit)
 - Version of Next.js: 8.1.0

**Comment by MarchWorks** [comment]
https://github.com/zeit/next.js/blob/00e8ba49819274564249cb55950841b3555d5929/packages/next-server/lib/router/router.ts#L110-L118


this will return true when visiting the page from the url bar
```
e.state.options && e.state.options.fromExternal
```

**Comment by MarchWorks** [comment]
@timneutkens should I make a PR to switch the first `if` with the second one? I don't think that there will be any problem in doing so.

**Comment by ijjk** [comment]
Hi, this doesn't appear to actually be a bug in Next.js. In the case you are describing popState isn't fired by the browser. This is to prevent a website from locking a user to a certain page I believe.

**Comment by ijjk** [comment]
@mkondel I'm gonna close this now. If you believe this is still an issue feel free to leave another reply with more info.
