### ISSUE TITLE
How to access component with ref when it wrapped by withRouter?

### ISSUE THREAD

**Issue by mahdijirofti** [zeit/next.js#7181]
I have a React component that I exported it like this:
```
class Child extends Component {
  getStatus() {
    return 'I am child!';
  }
  render() {
    return (<div>Child</div>);
  }
}

export default withRouter(Child)
```

And I have another class that needs the ref of "Child" component like this:

```
class Parent extends Component {
  constructor(props) {
  super(props);
  this.childRef = createRef();
  } 

  handleLogChildStatus = () => {
    if (typeof this.childRef.current.getStatus === 'function') {
      console.log(this.childRef.current.getStatus());
    } else {
      console.log(' Can not access to child component via ref! ');
    }
  }

  render() {
  return (
    <div>
      <Child ref={this.childRef} />
      <div onClick={this.handleLogChildStatus}>Log child status</div>
    </div>
  );
  }
}
```

This sample shows me I can not access to child component ref because it wrapped by withRouter HOC.

My question is How I can access to child ref component when it wrapped by nextjs withRouter>

**Comment by timneutkens** [comment]
Not sure what the question is 🤔

**Comment by mahdijirofti** [comment]
@timneutkens 
Hi, Thanks for your attention. I update my comment and explain my question.
Thank you very much.

**Comment by mahdijirofti** [comment]
@timneutkens Hey!
I have a React component that I exported it like this:
```
class Child extends Component {
  getStatus() {
    return 'I am child!';
  }
  render() {
    return (<div>Child</div>);
  }
}

export default withRouter(Child)
```

And I have another class that needs the ref of "Child" component like this:

```
class Parent extends Component {
  constructor(props) {
  super(props);
  this.childRef = createRef();
  } 

  handleLogChildStatus = () => {
    if (typeof this.childRef.current.getStatus === 'function') {
      console.log(this.childRef.current.getStatus());
    } else {
      console.log(' Can not access to child component via ref! ');
    }
  }

  render() {
  return (
    <div>
      <Child ref={this.childRef} />
      <div onClick={this.handleLogChildStatus}>Log child status</div>
    </div>
  );
  }
}
```

This sample shows me I can not access to child component ref because it wrapped by withRouter HOC.

My question is How I can access to child ref component when it wrapped by nextjs withRouter>

**Comment by adam187** [comment]
@mahdijirofti I think custom `withRouter` `hoc` like this should do the trick.

```javascript 
import { forwardRef } from 'react'
import { useRouter } from 'next/router'

const withRouter = (Component) => {
    const WithRouter = React.forwardRef((props, ref) => {
      const router = useRouter()

      return (<Component ref={ref} router={router} {...props} />))
    })
   
    return WithRouter
}
```

**Comment by KumarAbhirup** [comment]
@mahdijirofti, what's the error you are seeing? Is this solved for you now?

**Comment by Timer** [comment]
Assuming this is solved as @adam187 offered a solution.

**Comment by ranjith-s** [comment]
> I have a React component that I exported it like this:
> 
> ```
> class Child extends Component {
>   getStatus() {
>     return 'I am child!';
>   }
>   render() {
>     return (<div>Child</div>);
>   }
> }
> 
> export default withRouter(Child)
> ```
> 
> And I have another class that needs the ref of "Child" component like this:
> 
> ```
> class Parent extends Component {
>   constructor(props) {
>   super(props);
>   this.childRef = createRef();
>   } 
> 
>   handleLogChildStatus = () => {
>     if (typeof this.childRef.current.getStatus === 'function') {
>       console.log(this.childRef.current.getStatus());
>     } else {
>       console.log(' Can not access to child component via ref! ');
>     }
>   }
> 
>   render() {
>   return (
>     <div>
>       <Child ref={this.childRef} />
>       <div onClick={this.handleLogChildStatus}>Log child status</div>
>     </div>
>   );
>   }
> }
> ```
> 
> This sample shows me I can not access to child component ref because it wrapped by withRouter HOC.
> 
> My question is How I can access to child ref component when it wrapped by nextjs withRouter>

You can do it this way! This will work for sure👍

```
import { withRouter } from 'react-router';

//Just copy and add this withRouterAndRef HOC

const withRouterAndRef = (WrappedComponent) => {
class InnerComponentWithRef extends React.Component {    
      render() {
          const { forwardRef, ...rest } = this.props;
          return <WrappedComponent {...rest} ref={forwardRef} />;
      }
  }
  const ComponentWithRouter = withRouter(InnerComponentWithRef, { withRef: true });
  return React.forwardRef((props, ref) => {
      return <ComponentWithRouter {...props} forwardRef={ref} />;
    });
}

class MyComponent extends Component {
   constructor(props) {
      super(props);
   }
}

//export using withRouterAndRef

export default withRouterAndRef (MyComponent)
```
