### ISSUE TITLE
Nextjs-Grommet-Example not loading theme styles in production

### ISSUE THREAD

**Issue by sanderkooger** [zeit/next.js#7182]
# Bug report

## Describe the bug

On a fresh deployment grommet styles work fine when yarn dev. when running a yarn build and then a yarn start styles are not loaded. 
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Run 'yarn create next-app --example with-grommet with-grommet-app'
2. yarn run dev (check fonts on localhost:3000
3. end dev session and run yarn build
4. run yarn start
5 check localhost:3000

## Expected behavior
Expected theme to be loaded just like in dev. Instead no styles are loaded. 

## System information
 - OS: Windows
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: canary build

**Comment by sanderkooger** [comment]
Secondary question what is the best way to load fonts in the head of this deployment?

**Comment by sanderkooger** [comment]
After further testing I found out that styles are being loaded but fonts in production are not loading server side. only client side. 

Is this a problem with webpack not rendering correctly?

**Comment by huv1k** [comment]
Nice to hear you fixed your issue. Regardings fonts, you need to preload them. It has nothing to do with webpack. You can read more about that [here]( https://developers.google.com/web/tools/lighthouse/audits/preload).
