### ISSUE TITLE
Modules not found?

### ISSUE THREAD

**Issue by DarrylD** [zeit/next.js#719]
Getting this error with beta 16

```
 ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* fs

Did you forget to run npm install --save for it?
````

happens when after I install a module here and there. In this case it was [mapbox](https://github.com/uber/react-map-gl).

Kinda stumped with this one. Any idea whats going on?

**Comment by impronunciable** [comment]
@DarrylD we are using Webpack and it seems to have a conflict with react-map-gl. It seems you'll be able to use it along with next by customizing the webpack config via a `next.config.js` file https://github.com/zeit/next.js#custom-configuration

**Comment by DarrylD** [comment]
@impronunciable  this is maybe my 4 module to do this, any reason why? Not sure what I'm targeting by adding the custom config.

**Comment by impronunciable** [comment]
@DarrylD some modules needs some build process. In the case of react-map-gl there is an issue with webpack https://github.com/uber/react-map-gl/issues/21 some others might not work out of the box with a universal environment

**Comment by timneutkens** [comment]
@DarrylD @impronunciable can this be closed :thinking_face:
