### ISSUE TITLE
object destructuring on import fails build completion

### ISSUE THREAD

**Issue by jermsam** [zeit/next.js#7197]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js
I have this in method defined in my feathers.js file

> `
const app = feathers()
const  signin =  (data) =>console.log('signin with: ',data)
 export{
app,
signin
}
`
then When I do this in my component. signin.js  build compiles successfully but fails to terminate

`import {signin} from '../feathers'

onSubmit =(data)=>signin(data)`

yet with this it succeeds 
`onSubmit =(data)=>console.log('signin with: ',data)
`
here is my .babelrc

`{
    "presets": ["next/babel"],
    "plugins": [
        "@babel/plugin-transform-destructuring",
        ["@babel/plugin-proposal-class-properties", { "loose": true, "useBuiltIns": true }],
        ["@babel/plugin-proposal-object-rest-spread", { "loose": true, "useBuiltIns": true }]
    ]
  }`

and here is my next.config.js

`require('dotenv').config()

const path = require('path')
const Dotenv = require('dotenv-webpack');

const withCSS = require('@zeit/next-css');
/* Without CSS Modules, with PostCSS */
// module.exports = withCSS()

/* With CSS Modules */
// module.exports = withCSS({ cssModules: true })

/* With additional configuration on top of CSS Modules */

module.exports = withCSS({
 // cssModules: true,
  webpack (config) {
 config.plugins.push(
  new Dotenv({
    path: path.join(__dirname, '.env'),
    systemvars: true
  })
 );
config.module.rules.push(
  {
    test: /\.(png|svg|eot|otf|ttf|woff|woff2|icon)$/,
    use: {
      loader: 'url-loader',
      options: {
        limit: 8192,
        publicPath: '/_next/static/',
        outputPath: 'static/',
        name: '[name].[ext]'
      }
    }
  }
)
    return config; 
}

});`

Kindly help me fix this. Thanks

**Comment by jermsam** [comment]
I have considered my coding format and included all plugins that would support it. I have also droped `.babelrc` for `babel.config.js` as recomended in the babel docs. here is my new configuration:
`module.exports =  (api) =>{
    api.cache(true);
  
    const presets = ["next/babel"];

    const plugins = [
        "@babel/plugin-transform-destructuring",
       // "@babel/plugin-transform-classes",
        "@babel/plugin-transform-function-name",
        "@babel/plugin-transform-new-target",
        "@babel/plugin-transform-literals",
        "@babel/plugin-transform-object-super",
        "@babel/plugin-transform-parameters",
        "@babel/plugin-transform-shorthand-properties",
        "@babel/plugin-transform-spread",
        "@babel/plugin-transform-sticky-regex",
        "@babel/plugin-transform-template-literals",
        "@babel/plugin-transform-typeof-symbol",
        "@babel/plugin-transform-unicode-regex",
        ["@babel/plugin-proposal-class-properties", { "loose": true, "useBuiltIns": true }],
        ["@babel/plugin-proposal-object-rest-spread", { "loose": true, "useBuiltIns": true }],
        ["@babel/plugin-transform-arrow-functions", { "spec": true }],

    ];
  
    return {
      presets,
      plugins
    };
  }`

**Comment by jermsam** [comment]
however, issues still
![Capture](https://user-images.githubusercontent.com/11094475/56941194-cf45b900-6ac7-11e9-8630-fb390d3e83c4.PNG)
 remains

**Comment by timneutkens** [comment]
> Questions should be posted on spectrum.chat/next-js
