### ISSUE TITLE
next.config.js specified but no Content security meta-tag added to head after production build

### ISSUE THREAD

**Issue by TheoMer** [zeit/next.js#7198]
# Bug report

## Describe the bug

On project builds an `Content-Security-Policy` security meta-tag is not being added to the `<head />`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. next.config.js (root of project)
```
module.exports = {
 contentSecurityPolicy: "default-src 'none'; script-src 'self'; style-src 'nonce-{style-nonce}'; connect-src 'self'; img-src 'self'; font-src 'self'; base-uri 'self'; child-src 'self';"
}
```
2. Meta.js
```
import Head from 'next/head';

const Meta = () => (
  <Head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="referrer" content="no-referrer-when-downgrade" />
  </Head>
);
```
3. deploy to heroku
```
  "scripts": {
    "build": "next build",
    "heroku-postbuild": "./node_modules/next/dist/bin/next build"
  },
```

## Expected behavior
I expected, once a production version of the project had been built, for a `Content-Security-Policy` meta-tag to be added to the head.

What am I overlooking?

## System information
 - OS: Windows 10 Pro
 - Next.js: 8.0.4
 - React: 16.8.6
 - React-dom: 16.8.6

**Comment by timneutkens** [comment]
Doesn't seem like a bug, `contentSecurityPolicy` is not a property you can add to next.config.js.
