### ISSUE TITLE
Initially styling through modules not applied on 8.1.0

### ISSUE THREAD

**Issue by VMBindraban** [zeit/next.js#7199]
# Bug report

## Describe the bug

Modules (e.g `react-grid-system`) with styling are not initially loaded when building the production build. With `react-grid-system` if you resize the window to the mobile break-point it resolves the issue.

I was not sure where to post this issue since it works fine in `next` (dev)  and on `8.0.3`.
Only seems to happen on the build.

## To Reproduce

1. Execute `next build`
2. Inspect styling
3. Execute `next`
4. Inspect styling 

## Expected behavior
Initial styling to be applied.

## System information
 - OS: macOS
 - Browser (if applies): Chrome
 - Version of Next.js: 8.1.0

## Additional context
`next` on `8.1.0` doesn't seem to have the problem.
`8.0.3` seems unaffected by this issue.

No custom `.babelrc` and no custom `nextjs` config.

**Comment by huv1k** [comment]
You can check how it's done in SSR [example](https://github.com/gerbenmeyer/react-ssr-example). You need to provide an initial size of the screen. If still a problem please comment it again.
