### ISSUE TITLE
-bash: next: command not found

### ISSUE THREAD

**Issue by jb08** [zeit/next.js#72]
![screen shot 2016-10-25 at 5 29 37 pm](https://cloud.githubusercontent.com/assets/8146460/19706649/a1026168-9ad8-11e6-99ff-a5f139014d97.png)

where did I go wrong?

**Comment by impronunciable** [comment]
@jb08 you can add a run script

```
"scripts": {
  "run": "next"
}
```

and then `$ npm run dev`

**Comment by chrisjaure** [comment]
There's a gap in the docs currently. You say to install it locally:

```
npm install next --save
```

but a few lines later you say:

> and then just run `next`

hence the confusion.

Also @impronunciable has a typo in his comment above. It should be:

```
"scripts": {
  "dev": "next"
}
```

Then you can run `$ npm run dev`

**Comment by impronunciable** [comment]
good catch @chrisjaure, yes, it's `dev`, not `run`

**Comment by nkzawa** [comment]
Thanks for your report, fixed the instruction in README.
