### ISSUE TITLE
Pre-fetching does not working with Parameterized Routing

### ISSUE THREAD

**Issue by ugiacoman** [zeit/next.js#721]
Using the prefetch `Link`, the Service Worker attempts to fetch `./_next/pages/live/:param` instead of `./live/:param`. The API seems to be prepending the `/_next/pages/` to all links. May I suggest this be an optional parameter to disable for the prefetch API?

Relevant Code:

```js
export default class Video extends React.Component {

  render(){
    var chatUrl = '/live/'+this.props.videoId
    return (
      <Col m={3} s={12}>
       <Link href={chatUrl}>
          <a>
            <Card className='small' header={<CardTitle image={this.props.url}></CardTitle>}/>
          </a>
        </Link>
      </Col>
    )
  }
}
```

Result:
![2](https://cloud.githubusercontent.com/assets/9060741/21809641/9b1186ec-d716-11e6-9f82-3fb2cb2172e5.png)

**Comment by rauchg** [comment]
You need to use `as` on the `<Link>`. `href` should contain the _real_ `href`, `as` the _decoration_.

**Comment by arunoda** [comment]
I think this is same as https://github.com/zeit/next.js/issues/630
Let's discuss on it.

**Comment by ugiacoman** [comment]
Aha, thanks guys :)
