### ISSUE TITLE
PhoneGap build for Next.js application

### ISSUE THREAD

**Issue by awenwang** [zeit/next.js#7215]
Hi all, I have a next.js app and want to use phoneGap for building it into web apps, the way I am trying it this:

- added exportPathMap in next config js for the routes,
- build and export with _next build_ and _next export_, 
- dropped the phoneGap config file inside the _out_ directory before compressing it to a zip for phoneGap build upload

When I run the exported _out_ directory locally, it's mostly ok. But when I run the built app in my phone, nothing is working, clicking the links gives an application error - file not found, dropdown list no longer drops, radio buttons are no longer selectable, buttons don't work either etc.

I am new with next, thinking that I may not build build/export the app correctly for the use of phoneGap, appreciate your insights, thank you greatly!

**Comment by timneutkens** [comment]
Please use https://spectrum.chat/next-js for questions as per the issue template.
