### ISSUE TITLE
GetInitialProps doesn't work in some cases

### ISSUE THREAD

**Issue by RizziWilliam** [zeit/next.js#7216]
# Bug report

## Describe the bug

Can't make getInitialProps to work in 2 of my app pages, it does work in others page.

## To Reproduce

Acess the page (home) from any place. 

```
class Home extends Component {
  static async getInitialProps() {
    return {
      namespacesRequired: ['phrases'],
      title: 'Home',
    }
  }
  render() {
    return (
      <section id="home">
        <ContentComponent/>
        <ContentComponent/>
        <ContentComponent/>
        <ContentComponent/>
      </section>
    )
  }
}

export default withNamespaces('phrases')(withResponsive(withRouter(Home)))
```

This is the home page, i just wanna to return the title of the page in the getInitialProps, then in the _app.jsx i get that so i can set the html title. Current doing this on my _app.js to get the Component title

```
static async getInitialProps({ Component, ctx }) {
    let pageProps = {}

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }

    return { pageProps }
  }
```
Working fine in my others pages.

## Expected behavior

Should work like the others pages.

## Additional context

Make a little test, and the ```if(Component.getInitialProps)``` are returning false.

OBS: Can't link the entire repo because this is private.

**Comment by RizziWilliam** [comment]
Quick update, my page is wrapped in withResponsive, so is this case i no longer have the getInitialProps from Home.

**Comment by cedric-marcone** [comment]
Hello !

When you wrap a page component with an HOC (like withResponsive), it returns en enhanced component.

If this HOC doesn't implement getInitialProps, it will not auto-magically run getInitialProps declared on your page component .

To make it work, your HOC must implement getInitialProps and do the conditional chaining (as you did in your _app.js).

Example :

```js
const withNoop = Page => {
  const page = props => {
    return <Page {...props} />;
  };
  page.getInitialProps = ctx => {
    return Page.getInitialProps !== undefined
      ? Page.getInitialProps(ctx)
      : {};
  };
  return page;
};
```

Hope that helps :)

**Comment by timneutkens** [comment]
You probably want to do this though:
```
const withNoop = Page => {
  const noop = props => {
    return <Page {...props} />;
  };
	
  if(Page.getInitialProps) {
    noop.getInitialProps = Page.getInitialProps
  }
  return noop;
};
```

This makes sure `getInitialProps` is not added to pages that don't need it. This will be important for future optimizations.
