### ISSUE TITLE
Open a new tab with ctrl-click on links

### ISSUE THREAD

**Issue by gerbilsinspace** [zeit/next.js#7218]
Thank you guys for your hard work on next.js. It is a fantastic piece of software.

With traditional html links, when you hold control and click the link, it opens in a new tab. A client has realised that this doesn't happen to their site using ctrl-clicking on Link components.
I successfully replicated this on next.js docs.

I would like it so that we could open a new tab when holding down ctrl then clicking.

**Comment by timneutkens** [comment]
@lfades could you check if this is reproducible on Windows? We have handled this from one of the first released as far as I'm aware.

**Comment by gerbilsinspace** [comment]
For what it is worth, the website I can reproduce on is https://gatewaychurch.co.uk.

I am on mac, I'm pretty sure the lady who raised the bug is on windows

**Comment by timneutkens** [comment]
Looks like `Who We Are` etc don't have a `href` in the HTML markup, making the `<a>` not trigger `onClick` when doing `cmd + click`.

**Comment by gerbilsinspace** [comment]
Sorry, that's on me. Thanks again for your hard work, I'll fix my side soon.
