### ISSUE TITLE
Removed staticMarkup option from docs.

### ISSUE THREAD

**Issue by ehtb** [zeit/next.js#722]
684cc254c63a5294af9835e7b36639aefca09e6a reverted the documented feature to render static HTML (`staticMarkup`) without any additional info. 

Does this mean it will be deprecated in the future? The reason I am asking is because I want to render an AMP page and this could be the right direction. Although this is a setting that can better be handled on the page level: `app.renderToHTML(req, res, pagePath, queryParams, {staticMarkup:true})`.

Perhaps if not, this could be added as an example (happy to do that), just because the setting is a bit hidden.

**Comment by arunoda** [comment]
@ehtb for the AMP page, I assume you could use our custom document support as well.
See: https://github.com/zeit/next.js#custom-document

**Comment by ehtb** [comment]
@arunoda Thanks for the tip, that sounds very interesting as well! 
I am looking for a hybrid solution where both the regular as well as the amp pages are served from the same app, since they are still tightly coupled. 

I've created a pr which allows overriding the default render options per render request (`renderToHTML`). 

This allows for instance:
```
server.get('/blog-amp/:id', (req, res) => {
  app.renderToHTML(req, res, '/blog-amp', {}, { staticMarkup: true })
})

server.get('/blog/:id', (req, res) => {
  app.renderToHTML(req, res, '/blog', {})
})
```

**Comment by arunoda** [comment]
I'm not sure about the state of the `staticMarkup` option.
Let's ask from @nkzawa or @rauchg

**Comment by nkzawa** [comment]
I added `staticMarkup` just for testing and it's a private option. I'm not sure other use cases like AMP.

**Comment by timneutkens** [comment]
@ehtb could you have a look at #793 since it involves AMP 👍

**Comment by timneutkens** [comment]
Closing in favor of the AMP example.

**Comment by attapurposevc** [comment]
I would like to reopen this. Here is my pull request #3589
