### ISSUE TITLE
How can I run add html generate form nodejs (or webpack) to nextjs?

### ISSUE THREAD

**Issue by jenerse** [zeit/next.js#7228]
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js

I have a library to generate html but this library must run in node js or webpack, I try to run it in _document.js but it is fail, _document.js seems can not run node native.

How should I generate this html and pass it to _document.js?

Thanks.

**Comment by timneutkens** [comment]
Pretty hard to say based on the description. But please follow the issue template. 

> Questions should be posted on spectrum.chat/next-js
