### ISSUE TITLE
Duplicate og:see_also tag support 

### ISSUE THREAD

**Issue by ajaysinghj8** [zeit/next.js#7230]
# Feature request
Currently, only the following meta tags can be duplicate as per the next/head logic
```js
var ALLOWED_DUPLICATES = ['article:tag', 'og:image', 'og:image:alt', 'og:image:width', 'og:image:height', 'og:image:type', 'og:image:secure_url', 'og:image:url'];
```
So, it is not allowing me to render multiple og:see_also tag in meta using next/head.

It would be great if these ALLOWED_DUPLICATES can be configured/override using web-pack config/environment variable/nextconfig.

Please suggest.

**Comment by timneutkens** [comment]
Upgrade Next.js, this is no longer part of the codebase since Next.js 8.

To dedupe you can now add a `key` property if needed, but we no longer auto-dedupe tags.

**Comment by ajaysinghj8** [comment]
Thanks, @timneutkens, will try upgrading to next.js@8.
