### ISSUE TITLE
The mandatory attribute '⚡⚡' is missing in tag 'html'

### ISSUE THREAD

**Issue by TheoMer** [zeit/next.js#7241]
# Bug report

## Describe the bug

`npm run export` fails with the above mentioned error message, even after I have added `ampa to my `<html />` tag in my _document.js file.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. add `amp to html tag in _document.js as follows: `<html amp>`
2. add `"build": "next build&& next export"` to package scripts
2. `npm run build`
3. See listed errors

## Expected behavior
I expected, as there is an `amp` attribute added to the `<html>` tag, for the build to not fail the above mentioned error

## Screenshots
![missing-amp](https://user-images.githubusercontent.com/15969262/57168738-06370a00-6dfb-11e9-8954-2fb97323b790.jpg)

## System information
 - OS: Windows 10 Pro
 - Version of Next.js: 8.1.0
 - React/React-dom: 16.8.6

## Additional context

My _document.js file is as follows:

```
export default class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    const sheet = new ServerStyleSheet();
    const page = renderPage(App => props => sheet.collectStyles(<App {...props} />));
    const styleTags = sheet.getStyleElement();
    return { ...page, styleTags };
  }

  render() {
    return (
      <html amp>
        <Head>{this.props.styleTags}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

**Comment by ijjk** [comment]
Hi @TheoMer, you also need to use the `Html` component from `next/document` which will automatically add the `amp` attribute when rendering in AMP mode. See [here](https://github.com/zeit/next.js#custom-document) in the docs for more info.

**Comment by TheoMer** [comment]
@ijjk Many thanks 👍
