### ISSUE TITLE
Cannot use Material UI components in next/link on canary

### ISSUE THREAD

**Issue by jaycenhorton** [zeit/next.js#7242]
# Bug report

## Describe the bug

Material UI components in next/link break next in the latest canary builds

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Use material UI 3.9.3
2. Use next 8.1.1-canary-24 
3. Use a Material UI Component as the first child of `<Link>`

A code sandbox of the bug is available here: https://codesandbox.io/s/ll0qmmm0ql

## Expected behavior
You should be able to use Material UI component as the first child in a Link just as before (i.e. as was possible in next@8)

## Screenshots
![next-link-bug](https://user-images.githubusercontent.com/18407013/57170742-d4ef1780-6dc3-11e9-8b3a-9d97f3b6bb5a.gif)

## System information
 - Version of Next.js: 8.1.1-canary-24 

## Additional context

You can use a standard HTML element such as `<div>` (or another valid child such as `<>`) to wrap the Material UI child and the bug is subverted.

I think the bug was introduced by #7196 in canary-20.

The bug doesn't exist in canary-19 (after downgrading, using a material UI component as the first child works fine)

The error thrown in `next build` is
```
Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'
```

**Comment by oliviertassinari** [comment]
Material-UI v3 components don't forward the ref to the DOM node. They do in v4.
