### ISSUE TITLE
passport-twitter, express, next.js fails when in dev mode

### ISSUE THREAD

**Issue by pr1ntr** [zeit/next.js#7243]
# Bug report

When running in dev mode the twitter callback authentication method fails with `
Failed to find request token in session`  in `\passport-oauth1\lib\requesttoken.js#L13`

This setup is the same as standard [express-twitter example](https://github.com/passport/express-4.x-twitter-example)

 
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to [https://github.com/pr1ntr/next-auth-test](https://github.com/pr1ntr/next-auth-test)
2. Read the README.md

## Expected behavior
Should auth in dev mode

## System information
 - OS: Windows
 - Next 8
- Node 10

**Comment by timneutkens** [comment]
This doesn't seem related to Next.js. Please use https://spectrum.chat/next-js to ask questions.

**Comment by pr1ntr** [comment]
Maybe I should add that if I take out the next handler it works every time. Also does next proxy requests through webpack Dev server?  I don't see how this isn't a next issue if next just is the component that creates the issue. I am using the standard express next pattern afaik.

**Comment by pr1ntr** [comment]
For anyone who ever has this issue, my work around is to use some kind of persistent session storage. Log in in prod mode, then reuse the session in dev :/
