### ISSUE TITLE
meta charset is rendered "charSet"

### ISSUE THREAD

**Issue by keepcosmos** [zeit/next.js#7245]
# Bug report

## Describe the bug

meta tag for charset is rendered -> `<meta charSet="UTF-8" />`
It should be better if downcase -> `<meta charset="UTF-8" />`

**Comment by Janpot** [comment]
I'm also seeing duplicates when it's defined in `_document`, just like in https://github.com/zeit/next.js/issues/6919

**Comment by timneutkens** [comment]
I actually raised the attributes casing to the React repository before, however they said the spec allows for any casing:

https://github.com/facebook/react/issues/14216
