### ISSUE TITLE
with-styled-components fails on production build

### ISSUE THREAD

**Issue by bgaleotti** [zeit/next.js#7252]
# Examples bug report

## Example name
with-styled-components

## Describe the bug
The example fails to start after being built.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. `npx create-next-app --example with-styled-components with-styled-components-app && cd with-styled-components-app`
2. `npm run build && npm run start`
3. Open http://localhost:3000

## Expected behavior
The example should show a styled page.

## System information
 - OS: macOS 10.14.4 (18E226)
 - Version of Next.js: 8.1.0

## Additional context

It works when running `npm run dev`.

**Comment by ijjk** [comment]
Hi @bgaleotti, this was fixed in #7200 if you use the latest canary it works. I'm going to close this issue if you are still experiencing this feel free to reply with more info.
