### ISSUE TITLE
yarn dev get error with window is not defined

### ISSUE THREAD

**Issue by cabralada** [zeit/next.js#7260]
# Bug report

```
window is not defined
ReferenceError: window is not defined
```

## Describe the bug

Every time that I try to build my application I have this error.

Basically, the code is complaining about it:

```
const isLocalhost = Boolean(
  **window**.location.hostname === 'localhost' ||
    // [::1] is the IPv6 localhost address.
    **window**.location.hostname === '[::1]' ||
    // 127.0.0.1/8 is considered localhost for IPv4.
    **window**.location.hostname.match(
      /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
    )
);
```

I know that if is not in the browser, we do not have DOM. But anyway. I didn't create this project. I was running this project with my normal REACT application, and Now I'm converting to Next.JS

Before, was working?
Yes.

## Expected behavior
Run NextJS

**Comment by ozipi** [comment]
i think this wiki FAQ section can help you -> [**I use a library which throws window is undefined**](https://github.com/zeit/next.js/wiki/FAQ)

**Comment by cabralada** [comment]
@ozipi ... I had seen this post before. But unfortunately do not solve my issue.
I know the reason, but I wasnt expect this error. 

If you create a Next front zero, for instance, you do not need need of this: *serverWorker* file, for instance. 

so I expect that Next.Js can handle this file or give me another suggestion to work around, what I should do with this file.

**Comment by timneutkens** [comment]
Sounds like you have code in the global scope, which causes issues on it's own even in the app that you currently have. The solution would be to move it to `componentDidMount` or `useEffect`.

https://twitter.com/timneutkens/status/1124969466037776385
