### ISSUE TITLE
[Typescript] Upgrade to 8.1.0, dev build cannot find default export

### ISSUE THREAD

**Issue by tammo** [zeit/next.js#7267]
# Bug report

## Describe the bug
I ran into some issues when upgrading from 7.0.2 to 8.1.0.
Next cannot use the `exports.default = MyApp;` statement that is generated by Typescript.
If I change the output by hand to `export default MyApp` it works fine again.

Some context about the build steps:
I deleted all other stuff from my project repo to create the example. There is a custom express server (as described in the next examples). The `tsc` generates a `dist` folder and I import pages, the app and the document component from there.

## To Reproduce
You can use the **example repo**: https://github.com/tammo/next-ts-example.
There are 2 commits. The first one is the working 7.0.2 build. The second commit is the upgrade to 8.1.0.

Use `yarn tsc` to run the typescript compiler and `yarn dev` to run next.

## Expected behavior
It should work with `exports.default = MyApp;`

## Screenshots
CLI output when running `yarn dev`:

```
tammo@himalaya /V/P/next-ts-example> yarn dev
yarn run v1.5.1
warning package.json: No license field
$ nodemon .
[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node .`
[ warn ]  ./pages/_app.js
Attempted import error: '../dist/pages/_app' does not contain a default export (imported as 'App').
[ info ]  ready on null
NODE_ENV: undefined
PORT: 3000
[ event ] build page: /
[ wait ]  compiling ...
[ warn ]  ./pages/_app.js
Attempted import error: '../dist/pages/_app' does not contain a default export (imported as 'App').
[ info ]  ready on null
Error: The default export is not a React Component in page: "/_app"
    at Object.renderToHTML (/Volumes/Projects/next-ts-example/node_modules/next-server/dist/server/render.js:120:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
[ warn ]  ./pages/_app.js
Attempted import error: '../dist/pages/_app' does not contain a default export (imported as 'App').
[ info ]  ready on null
[ error ] Error: The default export is not a React Component in page: "/_app"
    at Object.renderToHTML (/Volumes/Projects/next-ts-example/node_modules/next-server/dist/server/render.js:120:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: The default export is not a React Component in page: "/_app"
    at Object.renderToHTML (/Volumes/Projects/next-ts-example/node_modules/next-server/dist/server/render.js:120:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
^Cfish: Job 1, 'yarn dev' terminated by signal SIGINT (Quit request from job control (^C))
```

## System information
 - macOS
 - Next.js: Upgrade from 7.0.2 -> 8.1.0
 - NodeJS: v10.15.0

Any help appreciated 👋

**Comment by timneutkens** [comment]
This doesn't really sound related to Next.js, you're compiling code using `tsc` and then feeding that into the Next.js app, it sounds like the tsconfig is probably not correct for the output that you want.

However Next.js is going to support TypeScript by default soon.

https://github.com/zeit/next.js/pull/7169
