### ISSUE TITLE
Starter and Inspiration project links thread

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#727]
Let's start collecting links, so we can later feature them in the 2.0 announcement and README / Wiki. These are some off the top of my mind:

- https://github.com/now-examples/next-news (https://next-news.now.sh)
- https://github.com/RelateNow/relate
- https://github.com/simplehub/henri
- https://github.com/rauchg/blog (https://rauchg.com)
- https://github.com/timneutkens/next-episode (https://next-episode.now.sh)
- https://github.com/dotcypress/password (https://password.now.sh)
- https://github.com/sergiodxa/react-wordpress (https://react-wp-test.now.sh)
- https://github.com/lipp/next-todos
- https://github.com/jorilallo/jsonbrowse (https://jsonbrowse.com)

**Comment by timneutkens** [comment]
https://github.com/timneutkens/next-episode ofcourse :smirk: https://next-episode.now.sh :)

**Comment by sergiodxa** [comment]
React+Next+WordPress.com API
https://github.com/sergiodxa/react-wordpress
https://react-wp-test.now.sh/

**Comment by sedubois** [comment]
👍 FYI I changed the URL RelateMind/Relate to RelateNow/relate

**Comment by lipp** [comment]
Next Todos https://github.com/lipp/next-todos 😀

**Comment by sedubois** [comment]
Also reminder about the awesome-nextjs list: https://github.com/unicodeveloper/awesome-nextjs

**Comment by sedubois** [comment]
npmjs.com runs Next.js according to https://github.com/zeit/next.js/pull/1177

**Comment by sedubois** [comment]
There's also https://github.com/zeit/nextgram

**Comment by reel** [comment]
https://github.com/simplehub/henri has been updated... added a few HOCs (thanks to @sedubois and many others for the inspiration)

**Comment by tpreusse** [comment]
An article cms prototype:
https://github.com/orbiting/cms-draft (pretty alpha though)

**Comment by iaincollins** [comment]
Folks might find the email and oauth based examples (along with a few other things, like async data fetching and layout and more advanced CSS handling) at https://github.com/iaincollins/nextjs-starter useful.

\* Working demo at https://nextjs-starter.now.sh
