### ISSUE TITLE
nextjs with rematch example, server render user list becomes empty array

### ISSUE THREAD

**Issue by BackToHappyBear** [zeit/next.js#7271]
open http://localhost:3000/github-users ，Server rendered github user list，At first the userlist has data, but it is immediately empty

![image](https://user-images.githubusercontent.com/20684300/57241490-b018cf80-7063-11e9-8877-db22067f31a7.png)
```bash
class Github extends Component {
  static async getInitialProps({ isServer, initialState }) {
    if (isServer) {
      await store.dispatch.github.fetchUsers()
    }
    console.log('isServer', isServer)
    return { isServer }
  }
  render() {
    return (
      <div>
        <Header />
        <h1> Github users </h1>
        <h2>isServer ? {this.props.isServer ? 'yes' : 'no'}</h2>
        <p>
          Server rendered github user list. You can also reload the users from
          the api by clicking the <b>Get users</b> button below.
        </p>
        {this.props.isLoading ? <p>Loading ...</p> : null}
        <p>
          <button onClick={this.props.fetchUsers}>Get users</button>
        </p>
        {this.props.userList.map(user => (
          <div key={user.login}>
            <Link href={user.html_url} passHref>
              <a>
                <img height="45" width="45" src={user.avatar_url} />
                <span> Username - {user.login}</span>
              </a>
            </Link>
            <br />
          </div>
        ))}
        <br />

        <CounterDisplay />
      </div>
    )
  }
}
```

**Comment by nataliemarleny** [comment]
Hi @BackToHappyBear !

I tried to reproduce this, but unfortunately there's just not enough information to do it. 

Most notably, the implementation of `fetchUsers` is missing - a reproducible example will make the issue easier to solve.

**Comment by BackToHappyBear** [comment]
> Hi @BackToHappyBear !
> 
> I tried to reproduce this, but unfortunately there's just not enough information to do it.
> 
> Most notably, the implementation of `fetchUsers` is missing - a reproducible example will make the issue easier to solve.

the case is from [nextjs/examples/with-rematch](https://github.com/zeit/next.js/tree/canary/examples/with-rematch)

**Comment by BackToHappyBear** [comment]
> Hi @BackToHappyBear !
> 
> I tried to reproduce this, but unfortunately there's just not enough information to do it.
> 
> Most notably, the implementation of `fetchUsers` is missing - a reproducible example will make the issue easier to solve.



> Hi @BackToHappyBear !
> 
> I tried to reproduce this, but unfortunately there's just not enough information to do it.
> 
> Most notably, the implementation of `fetchUsers` is missing - a reproducible example will make the issue easier to solve.

Didn't I make myself clear? Open the officially provided Example with-rematch, click Async Example, refresh the browser, the server side rendering data github users is not always saved in the rematch store, the page will flash quickly, the github users data will become empty, the above screenshot is very obvious

**Comment by timneutkens** [comment]
@BackToHappyBear I marked this issue as good first issue, there's no need to keep pinging on the issue, someone can have a look when they want to contribute.

Also note that it's generally better to provide a full reproduction in a GitHub repository instead of pointing to an example.

Besides that in the future please use the issue template.
