### ISSUE TITLE
[RFC] Control Babel version.

### ISSUE THREAD

**Issue by vzaidman** [zeit/next.js#7274]
# Feature request
Add a way to control the versions of babel packages.

## Is your feature request related to a problem? Please describe.
Yes.

I installed `@babel/preset-env` and passed 7.4.4 options (`core: 3`) to it but it used the old one. It really confused me. (Later I saw in docs it doesn't work indeed)

A potential problem might also be with plugins like `@babel/plugin-transform-flow-strip-types` that are not coming out of the box in `next.js`.

They are added with the **latest version** where the babel core is a pinned down a lower version.

This is a partial code from my `package.json`, I didn't know `@babel/core` is ignored and nothing warned me it is.
```
    "@babel/core": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "@babel/plugin-transform-flow-strip-types": "^7.4.4",
    "@babel/plugin-proposal-optional-chaining": "^7.2.0",
```

## Describe the solution you'd like
I think if a user adds `@babel/core` to his root project `package.json` next should use all babel versions from the user's code, and warn if he doesn't use all the expected in next.js babel plugins.

We should also consider adding a script to eject all babel dependencies from next to the user's project. For example: `next eject-babel` (somehow like in `create-react-app`)

## Describe alternatives you've considered
The readme documents the following:

> The next/babel preset includes everything needed to transpile React applications. This includes:
> 
> * preset-env
> * preset-react
> * plugin-proposal-class-properties
> * plugin-proposal-object-rest-spread
> * plugin-transform-runtime
> * styled-jsx
> These presets / plugins **should not** be added to your custom .babelrc. Instead, you can configure them on the next/babel preset:

But I think we should also tell the user he should use older versions of babel plugins and expose the babel version nextjs is using.

Also, we can warn the user that we ignore `@babel/core` and `@babel/preset-env` if he adds `@babel/core` to the project and runs next.

## Additional context
I'd be glad to add all these features if this feature is accepted.

**Comment by timneutkens** [comment]
> I installed @babel/preset-env and passed 7.4.4 options (core: 3) to it but it used the old one. It really confused me. (Later I saw in docs it doesn't work indeed)

The idea is that you shouldn't be doing this course of actions in the first place. You're trying to add something that doesn't have to be changed and is part of Next.js already.

> I think if a user adds @babel/core to his root project package.json next should use all babel versions from the user's code, and warn if he doesn't use all the expected in next.js babel plugins.

> We should also consider adding a script to eject all babel dependencies from next to the user's project. For example: next eject-babel (somehow like in create-react-app)

Actually this won't work, as then Next.js core plugins suddenly run on a newer version of Babel, that is untested (has not been ran against our test suite) etc.

The whole premise of Next.js is that it's a compiler that is in charge of compilation, meaning that Next.js makes sure that the input code has the correct optimized output.

When the user installs `@babel/core` it becomes impossible for us to upgrade Babel anymore in any version that is not a major version. 


Instead I think we should document in a clearer way the actual use-cases for adding a `.babelrc`, because there's a lot of misusage. For example `.babelrc` being added when it's really not needed.

**Comment by vzaidman** [comment]
A potential problem might also be with plugins like @babel/plugin-transform-flow-strip-types that are not coming out of the box in next.js.

They are added with the latest version where the babel core is a pinned down a lower version.

how can we best handle this?

**Comment by vzaidman** [comment]
> The idea is that you shouldn't be doing this course of actions in the first place. You're trying to add something that doesn't have to be changed and is part of Next.js already.

Why won't we leave it to the user to decide if he wants to do it? Updating babel is very legitimate.

> The whole premise of Next.js is that it's a compiler that is in charge of compilation, meaning that Next.js makes sure that the input code has the correct optimized output.

But for huge projects I'd like to eject this part and handle it myself.

**Comment by timneutkens** [comment]
> Why won't we leave it to the user to decide if he wants to do it

But why are you doing this in the first place, that's the point that I'm making, you probably shouldn't be.

> Updating babel is very legitimate.

You're very welcome to send a PR upgrading Babel. It's a much better course of action imo.

> But for huge projects I'd like to eject this part and handle it myself.

I mean, you already can, add in module-alias and alias to `@babel/core`. But as said it's at your own risk, and is very likely to break in the future, hence why we don't support it by default.

**Comment by vzaidman** [comment]
> You're very welcome to send a PR upgrading Babel. It's a much better course of action imo.
It's not the point of the RFC, babel versions will always be released after they are pinned in nextjs.

You have good points. What do you think about my main point?:
We got to find a solution to babel plugins that are added with the latest version, where the core is pinned to a version that was released around half year ago (Sep 29, 2018)?

**Comment by timneutkens** [comment]
As plugins are developed independently we only have to make sure we keep Babel sort of up-to-date in Next.js and then it'll be fine. The plugin API doesn't change at all, so using a newer version is not really an issue. The main point here is that we have a slightly older version of Babel in Next.js currently. Babel is super backwards compatible.

**Comment by schmod** [comment]
Would this be better if Next stopped pinning Babel to an exact version?

**Comment by Timer** [comment]
Hi! Unfortunately allowing users to customize the Babel version will make Next.js upgrades near impossible so this is not something we're looking at exploring right now.

We're more than happy to accept PRs to keep us up-to-date with the latest versions of Babel and `core-js` --- assuming they're stable and not betas.

If users _really_ need to do this, they can use `module-alias` as mentioned above. Thanks for your understanding!
