### ISSUE TITLE
Use named export for Next Components

### ISSUE THREAD

**Issue by suppayami** [zeit/next.js#7275]
# Feature request

## Is your feature request related to a problem?
In my opinion, default export is a really weird practise. It's really hard to refactor (in case future name changes) and does not support auto-import.

## Describe the solution you'd like
Use named export for Next Components instead of export default. For example, 
`import { Error } from 'next'` 
or 
`import { Error } from 'next/error'`.

**Comment by timneutkens** [comment]
At this point we're not planning to change the APIs exposed to users in this way, as it would be very breaking.
