### ISSUE TITLE
How to set proxy or get base url?

### ISSUE THREAD

**Issue by SarKurd** [zeit/next.js#7279]
I asked on spectrum but got no response so i'm asking here again. i apologize about that.

I want to use Now lambda with Nextjs for my next app  but i don't know how to set the proxy.

In CRA we simply add it to package.json but i don't know how to do it in Next.
I want to be able to dynamically change API_URL to localhost when testing lambdas locally

That's what i have for now.

**infra.config.json**
```
{
    "api_url": {
        "value": "https://test-nextjs.sarkurd.now.sh/api"
    }
}
```
**next.config.js**
```
const withSass = require('@zeit/next-sass')
const API_URL= require("./infra.config.json").api_url.value;

module.exports = withSass({
    target: "serverless",
    env: {
        API_URL
    }
});
```

**now.json**
```
{
    "version": 2,
    "name": "test-nextjs",
    "builds": [
        {
            "src": "next.config.js",
            "use": "@now/next"
        },
        {
            "src": "api/*.js",
            "use": "@now/node"
        }
    ]
}
```

I want to be able to dynamically change API_URL to localhost when testing lambdas locally

**Comment by Janpot** [comment]
two things
1. passing  environment variables is [currently broken](https://github.com/zeit/now-builders/issues/461) using `now dev` (should hopefully be published soon)
2. there's [some example](https://github.com/zeit/now-examples/blob/e9975b1485a06953615013976b13da4e64691ac9/monorepo/www/pages/index.js#L174) that "automatically" does what you want, but some [potential issues](https://github.com/zeit/next.js/pull/7262#issuecomment-490070989) with it .

**Comment by SarKurd** [comment]
Thanks @Janpot, that will do it for now

**Comment by Timer** [comment]
You seem to be [looking for `assetPrefix`](https://github.com/zeit/next.js#cdn-support-with-asset-prefix) -- this has the same behavior as CRA's `homepage` and `PUBLIC_URL`.

**Comment by SarKurd** [comment]
That's not really useful for Now deployments

**Comment by Timer** [comment]
Oh I'm sorry @SarKurd -- it seems I misunderstood.

In this regard the proper solution is a build time environment variable that is different on localhost than it is while deployed. You could use [phases](https://github.com/zeit/next.js#custom-configuration) to solve this.

**Comment by SarKurd** [comment]
I'm still not sure how to do that, is there an example?
