### ISSUE TITLE
Dynamic imports

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#728]
We should make it **really easy** to load modules dynamically. 
For example, to *only* load some code client side:

```js
componentDidMount () {
  import('./something').then(() => {
    // awesomeness!
  })
}
```

**Comment by arunoda** [comment]
@rauchg is this for pages or for anything?

**Comment by rauchg** [comment]
@arunoda anything. Might require whitelisting in config though

**Comment by impronunciable** [comment]
This already works

**Comment by arunoda** [comment]
@impronunciable oh really :)

**Comment by impronunciable** [comment]
https://dynamic-dfgzurjadh.now.sh

**Comment by arunoda** [comment]
I got an error. May be we need to bake something more into that.
![screen shot 2017-01-11 at 2 57 55 am](https://cloud.githubusercontent.com/assets/50838/21825441/c5e8c734-d7a9-11e6-8234-42bac9da0c5d.png)

**Comment by impronunciable** [comment]
yes, made a mistake. Rebuilding

**Comment by impronunciable** [comment]
Wow, it works on the dev server but not when build + start 🤔

**Comment by arunoda** [comment]
@impronunciable May be dev server serves necessary API endpoints. We may need to allow them in the production for exported chunks.

**Comment by impronunciable** [comment]
![2017-01-10 18 31 39](https://cloud.githubusercontent.com/assets/165799/21825591/1a4c06e8-d763-11e6-926b-25f0a1ab75fb.gif)

that could be

**Comment by arunoda** [comment]
I think this could be easily doable. May be this is the same functionality as `System.import` in webpack.

**Comment by mxstbr** [comment]
Webpack supports this out of the box and it works just like `System.import`, see https://github.com/webpack/webpack/pull/3413

**Comment by impronunciable** [comment]
@mxstbr We are using the webpack version but need to adapt our server to allow it

**Comment by arunoda** [comment]
Notes:

We need to support SSR with dynamic imports too. In that case, let's say user imported the component inside `getInitialProps` and pass it to the page via props. We need to support that case allow to do SSR.

**Comment by jesseditson** [comment]
Super excited for this to land - is https://github.com/zeit/next.js/compare/import-then getting PR'd any time soon so I can follow along on that thread?

**Comment by arunoda** [comment]
@jesseditson yes. We are doing a PR soon.

**Comment by mtford90** [comment]
Excited for this.

I've found that if server-side rendering with firebase you need to use `firebase-admin` and `google-storage` which are node libraries. Wouldn't want to load these in the client and so it would be nice to be able to load these dynamically if `isServer` is true when `getInitialProps` is called.

**Comment by neeraj022** [comment]
I was trying to import a client side library (react-leaflet), but was getting errors when this library was getting loaded on the server side for first time page rendering. Making the library to load conditionally was a easy option. 
But while conditionally loading the library on the client side, webpack tries to make the bundle again and I get a [error](https://github.com/webpack/webpack/issues/959) for the first load, thereafter it works well. 

Any workaround for this for the time being?

Code : 
```
render()
{
  console.log('Render called');
  let map=(<div></div>);

  //ui side check
  if(typeof window !== 'undefined' &&
  window.document && window.document.createElement){
    let reactleaflet=require('react-leaflet');
    let Map=reactleaflet.Map;
    let Marker=reactleaflet.Marker;
    let Popup=reactleaflet.Popup;
    let TileLayer=reactleaflet.TileLayer;
    //const { Map, TileLayer, Marker, Popup }=ReactLeaflet;


    map = (
    <Map center={this.state.centerPosition} zoom={this.state.zoomLevel}>
      <TileLayer
        url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
      />
      {this.state.markers.map((marker)=>{
        return (<Marker key={marker.key} position={[marker.position.lat, marker.position.lng]}>
          <Popup>
            <span>{marker.description}</span>
          </Popup>
        </Marker>);
      })}

    </Map>
  );
}


return(map)
}
```

**Comment by frol** [comment]
It seems that this issue is resolved in Next.js 3.0, isn't it?

**Comment by arunoda** [comment]
@frol  Yep. Thanks.
See more: https://zeit.co/blog/next3-preview
