### ISSUE TITLE
can't deploy gettig Directory Listing

### ISSUE THREAD

**Issue by mohamed-sultan** [zeit/next.js#7280]
i;m 
![Screenshot from 2019-05-07 22-30-00](https://user-images.githubusercontent.com/8412871/57330929-b5375680-7117-11e9-9df9-fab32711d150.png)
i have custom exporess server with code in server/app.js
const express = require("express");
const next = require("next");
const session = require("express-session");
const mongoose = require("mongoose");
const logger = require("morgan");
const mongoSessionStore = require("connect-mongo");
const expressValidator = require("express-validator");
const passport = require("passport");
const helmet = require("helmet");
const compression = require("compression");

/* Loads all variables from .env file to "process.env" */
require("dotenv").config();
/* Require our models here so we can use the mongoose.model() singleton to reference our models across our app */
require("./models/Post");
require("./models/User");
const routes = require("./routes");
require("./passport");

const dev = process.env.NODE_ENV !== "production";
const port = process.env.PORT || 3000;
const ROOT_URL = dev ? `http://localhost:${port}` : process.env.PRODUCTION_URL;
const app = next({ dev });
const handle = app.getRequestHandler();

const mongooseOptions = {
  useNewUrlParser: true,
  useCreateIndex: true,
  useFindAndModify: false
};

mongoose
  .connect(
    process.env.MONGO_URI,
    mongooseOptions
  )
  .then(() => console.log("DB connected"));

mongoose.connection.on("error", err => {
  console.log(`DB connection error: ${err.message}`);
});

app.prepare().then(() => {
  const server = express();

  if (!dev) {
    /* Helmet helps secure our app by setting various HTTP headers */
    server.use(helmet());
    /* Compression gives us gzip compression */
    server.use(compression());
  }

  /* Body Parser built-in to Express as of version 4.16 */
  server.use(express.json());
  /* Express Validator will validate form data sent to the backend */
  server.use(expressValidator());

  /* give all Next.js's requests to Next.js server */
  server.get("/_next/*", (req, res) => {
    handle(req, res);
  });

  server.get("/static/*", (req, res) => {
    handle(req, res);
  });

  const MongoStore = mongoSessionStore(session);
  const sessionConfig = {
    name: "next-connect.sid",
    // secret used for using signed cookies w/ the session
    secret: process.env.SESSION_SECRET,
    store: new MongoStore({
      mongooseConnection: mongoose.connection,
      ttl: 14 * 24 * 60 * 60 // save session for 14 days
    }),
    // forces the session to be saved back to the store
    resave: false,
    // don't save unmodified sessions
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      maxAge: 1000 * 60 * 60 * 24 * 14 // expires in 14 days
    }
  };

  if (!dev) {
    sessionConfig.cookie.secure = true; // serve secure cookies in production environment
    server.set("trust proxy", 1); // trust first proxy
  }

  /* Apply our session configuration to express-session */
  server.use(session(sessionConfig));

  /* Add passport middleware to set passport up */
  server.use(passport.initialize());
  server.use(passport.session());

  server.use((req, res, next) => {
    /* custom middleware to put our user data (from passport) on the req.user so we can access it as such anywhere in our app */
    res.locals.user = req.user || null;
    next();
  });

  /* morgan for request logging from client
  - we use skip to ignore static files from _next folder */
  server.use(
    logger("dev", {
      skip: req => req.url.includes("_next")
    })
  );

  /* apply routes from the "routes" folder */
  server.use("/", routes);

  /* Error handling from async / await functions */
  server.use((err, req, res, next) => {
    const { status = 500, message } = err;
    res.status(status).json(message);
  });

  /* create custom routes with route params */
  server.get("/profile/:userId", (req, res) => {
    const routeParams = Object.assign({}, req.params, req.query);
    return app.render(req, res, "/profile", routeParams);
  });

  /* default route
     - allows Next to handle all other routes
     - includes the numerous `/_next/...` routes which must    be exposedfor the next app to work correctly
     - includes 404'ing on unknown routes */
  server.get("*", (req, res) => {
    handle(req, res);
  });

  server.listen(port, err => {
    if (err) throw err;
    console.log(`Server listening on ${ROOT_URL}`);
  });
});
----------------------------------------------------------------------------
my next.config.js
const withSass = require("@zeit/next-sass");
module.exports = withSass();
------------------------------------------------------
my now.json
{
  "name": "oo",
  "alias": "next-connect",
  "dotenv": true,
  "version": 2,
  "builds": [{ "src": "server/app.js", "use": "@now/node" }],
  "routes": [{ "src": "/(.*)", "dest": "/" }]
}
--------------------------------------------------------------
working on localhost with the expected  but when deploy to now i get the listing directory 
----------------- my scripts------------------
"dev": "nodemon server/app.js --watch server",
    "start": "node server/app.js",
    "now-build": "next build",
    "deploy": "now --public",
    "alias": "now alias",

**Comment by ebrahimhassan121** [comment]
in next.config.js
const withSass = require("@zeit/next-sass");

module.exports = withSass({
  target: "serverless"
});

**Comment by ebrahimhassan121** [comment]
are you solved it ?

**Comment by mohamed-sultan** [comment]
> did you solved it ?

no i wish some one help

**Comment by msweeneydev** [comment]
Hello @mohamed-sultan, you usually see the directory listing page when your project is missing an `index.js` file or specified entrypoint. Can you try adding either of those to see if it resolves the issue?

**Comment by mohamed-sultan** [comment]
thanks for your replay i have resolved it but why building custom server is not possible 
as you said my second issue is 
https://next-admin-master.sultan00.now.sh/
i have change my now.json to 
{
  "version": 2,
  "builds": [{ "src": "*.js", "use": "@now/node" }]
}

**Comment by msweeneydev** [comment]
Hello @mohamed-sultan, a custom server is not possible because the builder separates your pages into individual serverless endpoints. Using a custom server would require that all pages be routed through that custom server and the application would lose out on many of the benefits of serverless Next.js.

**Comment by mohamed-sultan** [comment]
> Hello @mohamed-sultan, a custom server is not possible because the builder separates your pages into individual serverless endpoints. Using a custom server would require that all pages be routed through that custom server and the application would lose out on many of the benefits of serverless Next.js.

thanks again for your replay the main issue i'm facing is that i got this repo deployed successfully a month ago but now v2 came and i can't deploy any more 
thanks agin @msweeneydev

**Comment by Timer** [comment]
Closing this as stale, if it's still not working, please reach out! Do note that this is not a supported deployment pattern.

You _may_ be able to get this working by routing all routes to the `@now/node` server, though:
```json
"routes": [{ "src": "/(.*)", "dest": "/server/app.js" }]
```
