### ISSUE TITLE
npm run dev error while following tutorial

### ISSUE THREAD

**Issue by yarapolana** [zeit/next.js#7288]
# Bug report
npm run dev not working error: "cannot find module ../cli/next-dev"

## Description
I was following this tutorial: 
_Using Shared Components part 3: Using the header component_
There is a part where you test the comps vs components folder renaming
Everything was working fine, I stopped the app, renamed the folder, tried starting the app again and it gave me this error:

(node:7465) UnhandledPromiseRejectionWarning: Error: **Cannot find module '../cli/next-dev'**
Require stack:
- /appname/node_modules/.bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /appname/node_modules/.bin/next:34:70
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:54:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:828:11)
    at internal/main/run_main_module.js:17:11
    at async Object.dev (/appname/node_modules/.bin/next:34:22)
(node:7465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7465) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## To Reproduce

Stop app
Rename folder
Start app

## System information
    "next": "^8.1.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"

## Extra
I didn't expect this type of error from renaming a folder =/

**Comment by lfades** [comment]
@yarapolana I tried to replicate it following your steps and it worked, can you confirm that modules are installed properly ? I used `next@^8.1.1-canary.25` and `yarn`, if the issue persists even in the `canary` version can you create a reproduction for me please ? 🙏

**Comment by yarapolana** [comment]
Hi @lfades Thank you for the fast reply, I wish I saw it sooner.
I deleted and created a fresh app, I did the exact same steps and successfully managed to go through.
Couldn't figure out on my own, but hopefully this doesn't happen after adding all the api calls and such. =)
Have a great day.
