### ISSUE TITLE
onClick event doesn't exist in next/link ?

### ISSUE THREAD

**Issue by KingZee** [zeit/next.js#7304]
Fresh project, `npm install next react react-dom`, a single file in /pages/index.js :

```javascript
import Link from 'next/link';

const pizzaClick = () => console.log('Free pizza!')
const Index = () => (
    <div>
         <h4>Hello World</h4>
        <Link href="#" onClick={pizzaClick}><a className="input_icon">Click me for pizza</a></Link>
    </div>
);
export default Index;
```

Building gives me this : `Warning: Failed prop type: Link: unknown props found: onClick`

I thought this was fixed here ? https://github.com/zeit/next.js/pull/4474

**Comment by timneutkens** [comment]
```
import Link from 'next/link';

const pizzaClick = () => console.log('Free pizza!')
const Index = () => (
    <div>
         <h4>Hello World</h4>
        <Link href="#"><a onClick={pizzaClick} className="input_icon">Click me for pizza</a></Link>
    </div>
);
export default Index;
```

As the PR says, it has to be on the child of `<Link>` so the `<a>` tag itself.

**Comment by timneutkens** [comment]
Also you quite literally posted this on spectrum while following the issue template https://spectrum.chat/next-js/general/onclick-event-doesnt-exist-in-next-link~459a09b7-f3ac-4d86-8e49-8ff9cc6ff0fe

and then completely ignored the issue template.
