### ISSUE TITLE
arabic and persian url route not support

### ISSUE THREAD

**Issue by straxico** [zeit/next.js#7305]
when i use persian character for file and folder in `page` next js cant find it and i see error 404

when i change my filename to english its run well

for exm:

Not work
/سلام.js

work
/hello.js

**Comment by timneutkens** [comment]
I guess this is more-so related to the filesystem not matching the url, and not something we can easily fix.

**Comment by straxico** [comment]
hi
i need to routing with persian language like this "localhost:3000/help/سلام"
and i try to make folder like this
page
    - help
        -سلام

after faild i think and use this 

in other component
 <Link as="/help/سلام" href="/help?slug=سلام">hello</Link>

in server.js
server.get('/help/:slug', (req, res) => app.render(req, res, '/help', { slug: req.params.slug }));

in help component

Help.getInitialProps = async ({ query }) => {
  const pathname = query.slug;
  return { pathname };
};


and i now can use persian in url
tanks nextjs
