### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by david718** [zeit/next.js#7310]
# Bug report

HMR doesn't work.

## Describe the bug

I followed your Learn course in nextjs.org. HMR doesn't work at all.

package.json 
{
  "name": "hello-next",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "next"
  },
  "dependencies": {
    "next": "^8.1.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  }
}

## To Reproduce

just followed Learn course. All I did was just install react, react-dom, next packages, then made ./pages/index.js

## System information
 - OS: [WSL(bash)]
 - Browser (if applies) [chrome]
 - Version of Next.js: [e.g. 8.1.0]

**Comment by timneutkens** [comment]
Please provide more context, what was your `pwd`, we have tests covering all things HMR and they all pass before every single release.

**Comment by david718** [comment]
OS: [window]

and I use WSL also, I input CLI(ex) npm run dev("next") in bash in vscode

you need more information?

if you do, plz let me know those informations

thanks

**Comment by Timer** [comment]
Hi! Try setting the following environment variable:
```
CHOKIDAR_USEPOLLING=true
```

If this doesn't work, please let us know -- but we'll likely need a motivated Windows contributor to take a look at this.

**Comment by BiscuiTech** [comment]
Hello! I just had this issue and I can confirm that `CHOKIDAR_USEPOLLING=true` fixes it.
