### ISSUE TITLE
Inconsitent update on page roots

### ISSUE THREAD

**Issue by mortimr** [zeit/next.js#7314]
# Bug report

## Describe the bug

When using the `getInitialProps` method in a class to retrieve query informations, I can see the value changing properly when changing my route, the render method is called on the page root component, but props is not updating nested components ...

## To Reproduce

```
export default class extends React.Component<any> {
    static getInitialProps({query}: {query: any; }): any {
        return query;
    }

    render(): React.ReactNode {

        console.log(this.props.address); // this shows me that it's properly changing
        if (this.props.address && !isValidAddress(this.props.address)) {
            // this here is properly updated when condition is met
            return <InvalidAddress address={this.props.address}/>;
        }

        return (
            <AppGate>
                <ProviderGate>
                    <AuthGate>
                        <LocalWalletGate>
                            <VtxGate>
                                <AccountView address={this.props.address}/> // this one is NEVER updated
                            </VtxGate>
                        </LocalWalletGate>
                    </AuthGate>
                </ProviderGate>
            </AppGate>
        );
    }
}
```

## Expected behavior

Components update when props change

## Additional context

All the gates are dynamic components connected to a redux store, I tried everything: enable/disable ssr, make them static component, nothing works

**Comment by MarchWorks** [comment]
Can't you reproduce the issue with a minimal example?

**Comment by Timer** [comment]
Hi! Questions like this are better suited for our [Spectrum](https://spectrum.chat/next-js). Please repost this question there.
