### ISSUE TITLE
Add configurable static export directory (chrome extension incompatible with underscore)

### ISSUE THREAD

**Issue by asyncb** [zeit/next.js#7315]
**UPDATE**
After a ton of investigation, it looks like Chrome wasn't complaining about CSP, it just couldn't follow the underscore as part of the directory structure of the static export eg `out/_next` (silent error / very difficult to debug).

After manually renaming the folder to Znext and doing "Find All and Replace" then "Save All" with sublime, `E1-static-export` routing worked flawlessly in the chrome extension default_popup palette.

I'm not sure how to configure this (I don't think it can be), but it would be great if this was mentioned.

---

Also, regarding the static export tutorial: please remove the incorrect behavior of only exporting a single page. That threw me off for a while too, apparently I didn't actually have the required files.

# Feature request

## Is your feature request related to a problem? Please describe.
I'm developing a Chrome Extension and having issues with static Next.js export. I understand Next.js is typically used for the complete opposite context (SSR) from an 'all inline' sort of package that Chrome Extensions uses, but I think it could handle environments without `history` API and inline all scripts and shallow, client-side Links.

## Describe the solution you'd like
- Demo for exporting (E1-static-export) as a Chrome Extension
- When right clicking the browser icon Inspect Popup, no errors should be thrown, and routing should behave within it's own HTML palette
```
** manifest.json **
{
  "manifest_version": 2,
  "name": "E1-static-export",
  "version": "0.1",
  "description": "Demo static export with inline / CSP hashes",
  "browser_action": {
    "default_popup": "out/index.html"
  }
}
```

## Describe alternatives you've considered
<s>
I believe this is possible with additional Webpack plugins/loaders and a single index page (no routing).
Tried saving webpage as html, but resources are also still stored in an adjacent folder

## Additional context
<img height='200' src='https://imgur.com/8e2HAxd.png'/> 
<img src='https://imgur.com/mD9mTUR.png'/>
<img height='200' src=https://imgur.com/pc37GRj.png'/>

</s>

**Comment by asyncb** [comment]
More attempts, no success though
```
** manifest.json **
{
  "manifest_version": 2,
  "name": "E1-static-export",
  "version": "0.1",
  "description": "Demo static export with inline / CSP hashes",
  "browser_action": {
    "default_popup": "out/index.html"
  },
  "web_accessible_resources": [
    "out/*"
  ]
}
```
```
var HtmlWebpackPlugin = require('html-webpack-plugin');
var HtmlWebpackInlineSourcePlugin = require('html-webpack-inline-source-plugin');

module.exports = {
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    // Note: we provide webpack above so you should not `require` it
    // Perform customizations to webpack config
    // Important: return the modified config

    // Example using webpack option
    config.plugins.push(new HtmlWebpackPlugin({ inlineSource: '.(js|css)$' }));
    config.plugins.push(new HtmlWebpackInlineSourcePlugin());

    return config;
  },
  webpackDevMiddleware: config => {
    // Perform customizations to webpack dev middleware config
    // Important: return the modified config
    config.plugins.push(new HtmlWebpackPlugin({ inlineSource: '.(js|css)$' }));
    config.plugins.push(new HtmlWebpackInlineSourcePlugin());
    return config;
  }
};
```

**Comment by asyncb** [comment]
- A significant problem that I discovered after moving `manifest.json` into `out`:
- **The directory `_next` is invalid for Chrome Extension schema, and it says "underscore is reserved for system files"**
- I did a "Find All and Replace" `_next` with `Znext` and this fixed the problem "ERR could not find resource" or whatever, which I thought was due to CSP
- Removed `"web_accessible_resources"` and `"content_security_policy"` keys from manifest.json and it seems to work great
- Was doing compare/contrast with [this boilerplate](https://github.com/jhen0409/react-chrome-extension-boilerplate)

**Comment by asyncb** [comment]
**I can confirm this was the only issue**
Demo with `E1-static-export` routing inside of "default_popup" palette works perfectly.
I will look into a better way to rename `out/_next` to `out/Znext` or `out/nextDist` `/out/nextBuild` etc (just can't use underscore)

**Comment by Timer** [comment]
Hi, Chrome Extensions aren't our primary target so we'll likely not introduce configuration to handle them. You can probably get this working with some post processing of the build output, though.

Sorry!
