### ISSUE TITLE
Multiple Static File Routes

### ISSUE THREAD

**Issue by bryan** [zeit/next.js#732]
Is there anyway to configure multiple static file routes and also rename /static/ to something else? 

I can't seem to find any existing documentation regarding this and would appreciate any feedback.

**Comment by rauchg** [comment]
See the Custom Server and Routing section (2.0 beta):
https://github.com/zeit/next.js#custom-server-and-routing

You can in fact set up express and use its static middleware if you'd like: https://github.com/zeit/next.js/tree/master/examples/custom-server-express

**Comment by oyeanuj** [comment]
@rauchg @arunoda So to do static, and nested routes like RRv2/3 have, is the idea to use express code like [here](https://github.com/zeit/next.js/blob/master/examples/custom-server-express/server.js)?

And by static routes, I mean a long config of routes like -
```jsx
<Route>
  <IndexRoute component="Homepage" />
  <Route path="about" />
  <Route path="posts" >
    <IndexRoute component = "Feed" />
    <Route path = "(:postId)" component="Post" />
  </Route>
  <Route path="members" />
</Route>
```

In my app, there are over 50 routes and having a long if/else doesn't feel right, so wanted to check?

**Comment by arunoda** [comment]
@okuryu That's one way and you can also simply drop the file directly into the pages directory.
You can learn about our routing system here: https://learnnextjs.com/basics/create-dynamic-pages
