### ISSUE TITLE
Tool to Obfuscate project next js

### ISSUE THREAD

**Issue by ShintaroNippon** [zeit/next.js#7323]
Hi there, first of all, thanks by the support!

I'm just getting to know if there is an npm package or a tool in order to protect my next js app...

For example, the use of an obfuscate tool or
 license key like keygen SAAS app?

Can someone give me an idea?

Thanks in advance
Shintaro

**Comment by timneutkens** [comment]
I'm not sure what you mean.

Please follow the issue template and post questions on https://spectrum.chat/next-js.
