### ISSUE TITLE
with-loading should not display progress bar on certain browsers

### ISSUE THREAD

**Issue by jmayergit** [zeit/next.js#7327]
# Bug report

## Describe the bug
On certain browsers, like Chrome on iOS, there is already a progress bar in place causing duplicate progress bars when using the with-loading example repo.

## To Reproduce
1. Follow instructions on https://github.com/zeit/next.js/tree/canary/examples/with-loading to set project up.
2. Install and run locally
3. Navigate to the non-existing page using Chrome on iOS

## Expected behavior
NProgress should not be displayed for browsers that have default progress bars. This is a next.js issue because the example should account for the behavior of NProgress.

## Screenshots
![Image from iOS](https://user-images.githubusercontent.com/8594272/57685043-f7a9e780-7671-11e9-974a-8987908cdc5a.png)

**Comment by timneutkens** [comment]
There shouldn't be a browser loading bar, it would indicate a full page transition which next/link doesn't do.

**Comment by John-Spraul** [comment]
@timneutkens, if you mean changing
```
<Link href='/non-existing'>
  <a style={linkStyle}>Non Existing Page</a>
</Link>
```
to
```
<a href='/non-existing' style={linkStyle}>Non Existing Page</a>
```
then I can do that! 💪👶

**Comment by timneutkens** [comment]
Yep!

**Comment by jmayergit** [comment]
![Image from iOS (1)](https://user-images.githubusercontent.com/8594272/58068697-4fde6d80-7bcd-11e9-8fde-d34aa98ab322.png)

When navigating via the browser we still see both nprogress and the browser loading bar @timneutkens 

Thank you
