### ISSUE TITLE
Fundamentals on NextJS

### ISSUE THREAD

**Issue by techpanga** [zeit/next.js#7341]
Note: I could not post on spectrum.chat, as it shows "Internal Server Error" while posting. Pardon for posting here in this forum.

I am exploring NextJS and come across few questions.

1. Where console.log outputs to - server console or browser console.
2. How React Component Lifecycle methods are different here in nextjs? What methods to be used and what not to be used?
3. How the React State can be managed on Client side? how this can be done on server side?
4. Which part of code executes on server side and which part execute on client side?
5. Please point to any simple example for Login Page end to end working? - on entering userid and password, it updates state on clientside, calls ajax request using fetch on client side and then page refreshes to thank you page after validating on server side.

Please point to these in documentation? Appreciate your help.

**Comment by timneutkens** [comment]
Can you try posting it on spectrum again?
