### ISSUE TITLE
Just getting compiler errors when starting a new project

### ISSUE THREAD

**Issue by kellertobias** [zeit/next.js#7342]
# Bug report

## Describe the bug

I am new to next.js (because I searched for a lightweight non-agnostic alternative to meteor for a small side-project). However, I try to create a new Project (the final project will have 2 Pages and 2 express API Endpoints) but I always get a compiler error when trying to start next.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create a new Next Project (either doing the tutorial or by `create-next-app`)
2. Start the dev server with `npm run dev`
3. See Compiler Errors (looks like issues with ES6)

## Expected behavior

The Tutorial explains how to get a minimal *running* project.

## Screenshots

```
[keller@bkt testapp] npm run dev

> testapp@1.0.0 dev /home/myuser/repos/testapp
> next

/home/myuser/repos/testapp/node_modules/next/dist/bin/next:31
    build: async () => await Promise.resolve().then(() => __importStar(require('../cli/next-build'))).then((i) => i.nextBuild),
                 ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testapp@1.0.0 dev: `next`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testapp@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myuser/.npm/_logs/2019-05-15T13_38_44_069Z-debug.log
```

## System information
 - OS: Linux (4.18.16-arch1-1-ARCH)
 - Browser didn't come that far
 - Version of Next.js: 8.0.4, 8.1.0
 - Node Version: 6.11.2

## Additional context

I will try doing a node update first. If it has to do with the node version, it is a documentation bug. If not, it is some other weired bug.

**Comment by kellertobias** [comment]
It indeed seems to have to do with the old version of node.js. Maybe, it should be highlighted (or at least be displayed when starting that the version of node is not supported!)

**Comment by Janpot** [comment]
It's specified in the package.json https://github.com/zeit/next.js/blob/canary/package.json#L113.
Didn't `npm` print a warning when you installed `next`?

**Comment by Timer** [comment]
@kellertobias Node 6 is EOL as of two weeks ago so npm packages are probably going to start dropping support.

We don't control `create-next-app` so please file an issue with them to check the Node version before creating the app.

Sorry you ran into this!

**Comment by Timer** [comment]
BTW, Node 8 is already no longer LTS and will be EOL at the end of the year. You should be upgrading to Node 10! 😄

**Comment by timneutkens** [comment]
@janpot 
> Didn't npm print a warning when you installed next?

Actually because of using an older version of node, probably an older version of npm was also used which might not have these checks 😭

**Comment by kellertobias** [comment]
In my opinion, this should be stated in the first page of the tutorial,
that you check your node version. Many os do have node in their package
management and these versions could be outdated.

Frameworks that advertise, that they are easy to use should not crash when
starting without any helpful message.

Tim Neutkens <notifications@github.com> schrieb am Do., 16. Mai 2019, 11:34:
