### ISSUE TITLE
outdir line in typescript customer server example creates additional directory on build

### ISSUE THREAD

**Issue by mrispoli24** [zeit/next.js#7347]
# Bug report

I believe that the outdir line in the with typescript custom server example creates your server in `.next/server/server` which makes the production build and start commands as they stand break. You can remove this and the `/server` directory will build as intended or update the start script to `node .next/server/server`. I just removed that line from my project and all built as intended.

**Comment by timneutkens** [comment]
Feel free to send a pull request.

**Comment by mrispoli24** [comment]
Thanks @timneutkens sent one over for you here: https://github.com/zeit/next.js/pull/7362
