### ISSUE TITLE
TypeScript incorrectly detected in latest Canary build

### ISSUE THREAD

**Issue by seantimm** [zeit/next.js#7348]
The latest Canary build attempts to automatically detect TypeScript usage but is incorrectly identifying our project due to our use of the yarn cache:

"We detected TypeScript in your project (/.yarncache/microevent.ts-0.1.0.tgz) and created a tsconfig.json file for you."

Any way to tell it to ignore this?

**Comment by ijjk** [comment]
Just submitted a PR to catch that, thanks for the report
