### ISSUE TITLE
Prefetch pages 

### ISSUE THREAD

**Issue by mateuspv** [zeit/next.js#7351]
I'm building a "live preview" gallery with a few pages inside it, the ideia is to have the initial current page loaded via SSR and render some other pages later(after page load)

Example:
![Screenshot from 2019-05-15 14-49-09](https://user-images.githubusercontent.com/4995440/57808905-d4973a80-773a-11e9-830c-31e15c43f220.png)

Right now, it seems that there's no way get the `component` and `getInitialProps` data via API, except by trigger a `Router.push`, the problem is that `push` *changes*  the current page, which is not desired.

I've inspected the  `next/router` on the frontend and noticed some kinda of `cache` inside `Router.router.components`

![Screenshot from 2019-05-15 15-04-29](https://user-images.githubusercontent.com/4995440/57808916-d7922b00-773a-11e9-8626-bf16d1e5601f.png)

The ideia solution for my case, is to be able to prefetch  `Router.router.components` data via api, eg:
`Router.push('/projects', {prefetch: true})`

This would prefetch `Router.router.components` data, but * without replace the current page* 

Let me know if that makes sense, 
Best

**Comment by mateuspv** [comment]
I just discovery `getRouteInfo` that does exactly what I need(fetch the component responsible by the render and the props), is this method private ? I think we should include it on the docs and we can close this issue.

**Comment by timneutkens** [comment]
I'm going to close this issue as it doesn't follow the issue template. As provided in the issue template questions should be posted on https://spectrum.chat/next-js.
