### ISSUE TITLE
deploy to alibabacloud serverless function compute,got error "Cannot find module '/code/next.config.js'"

### ISSUE THREAD

**Issue by threem0126** [zeit/next.js#7352]
FC Invoke End RequestId: 2be70ab7-474c-4f6f-8417-4adeb462e6a3
{
  "errorMessage": "Cannot find module '/code/next.config.js'",
  "errorType": "Error",
  "stackTrace": [
    "Error: Cannot find module '/code/next.config.js'",
    "at r (/code/func.js:42:1848)",
    "at t.default (/code/func.js:680:8376)",
    "at t.default (/code/func.js:261:2653)",
    "at e.exports (/code/func.js:1079:23451)",
    "at e.exports.e (/code/func.js:467:122)",
    "at (/code/func.js:1107:23431)",
    "at r (/code/func.js:1:419)",
    "at (/code/func.js:1:1218)",
    "at (/code/func.js:1:1230)",
    "at t (/code/func.js:1:146)"
  ]
}

anyone else used nextJs project successfully in alibabacloud serverless ?

thx

**Comment by timneutkens** [comment]
Closing this as per the issue template.
