### ISSUE TITLE
How to implement next-with-apollo with react-apollo SSR?

### ISSUE THREAD

**Issue by KumarAbhirup** [zeit/next.js#7353]
I am using `react-apollo` with `Next.js` the way it is illustrated in the [example from the Next.js repo](https://github.com/zeit/next.js/tree/canary/examples/with-apollo).

Complete question detail on [Spectrum Next.js community](https://spectrum.chat/next-js/general/how-to-implement-next-with-apollo-with-react-apollo-ssr~20914c2c-b8ae-4bc7-aac0-45a14a1eacb7).

**Comment by timneutkens** [comment]
Going to close this as per the issue template.

**Comment by KumarAbhirup** [comment]
What? Did I not follow the issue template? I chose the forth one (Ask a question)

The template said to give link to the spectrum chat.. please let me know why this got closed. 😥

**Comment by timneutkens** [comment]
The issue template says questions should be asked on spectrum.chat, hence why I closed this issue as it's a question 👍

**Comment by KumarAbhirup** [comment]
oh

**Comment by KumarAbhirup** [comment]
I kindly request you to reopen this issue, because this is not just a question but a suggestion to complete an incomplete example that uses only `initialState` and not `headers` so that cookies can also be used in front-end with `react-apollo`: An essential thing needed for authentication.

 Please open this issue, spectrum won't get me any answers.

**Comment by hutber** [comment]
You ever figure it out @KumarAbhirup

**Comment by KumarAbhirup** [comment]
Yup, I did.

**Comment by steven-holloway** [comment]
I find it rather hilarious that spectrum.chat has the same broken cche "refetch" issues so common with zeit/next. 👎
