### ISSUE TITLE
Webpack not loading browser version of npm package

### ISSUE THREAD

**Issue by mellogarrett** [zeit/next.js#7359]
# Bug report
## Describe the bug

Not sure if this is specific to Next.js or is just a Webpack problem. 

When installing an npm package that has both a `main` and a `browser` file path in its `package.json`, Next.js ignores the `browser` version of the package. For instance, the `winston` logger package has both a browser and a Node version. When I add `winston` as a dependency and try to import it into my React app, I get an error:
```
[ error ] ./node_modules/winston/dist/winston/tail-file.js
Module not found: Can't resolve 'fs' in '/Users/garrett/Documents/lambda/forms/node_modules/winston/dist/winston'
```

## To Reproduce

CodeSandbox here: https://codesandbox.io/s/helloworld-wd6nd

Or to manually reproduce:
1. Create new Next.js app
2. Run `npm i winston`
3. Add `import winston from "winston";` in your React app somewhere
4. Run `npm run dev` and see error in console output

## Expected behavior
I would expect webpack to detect and load the browser compatible version of the winston package.

## System information
 - OS: [macOS]
 - Version of Next.js: [latest]

**Comment by ijjk** [comment]
Hi, this can be handled using webpack's `node` option which can be set in your `next.config.js`. 

```js
module.exports = {
  webpack: (config) => {
    config.node = {
      fs: 'empty'
    }
    return config
  }
}
```
