### ISSUE TITLE
next build doesn't exit after finish

### ISSUE THREAD

**Issue by dave-dm** [zeit/next.js#7364]
> next build
Creating an optimized production build ...
> Using external babel configuration
> Location: "/usr/app/.babelrc"
Compiled successfully.
 ┌ /_app
 ├ /_document
 ├ /_error
 ├ /create
 ├ /hello
 ├ /list
 └ /lists

edit: the issue appears to be intermittent. Not sure what causes it yet.

**Comment by timneutkens** [comment]
I'm going to close this issue as it doesn't follow the issue template and there is no reproduction provided, making it hard (if not impossible) for us to have a look.

**Comment by timneutkens** [comment]
Just pointing out this is the third time not following the issue template:
#7097
#7283
