### ISSUE TITLE
CDN url support?

### ISSUE THREAD

**Issue by livoras** [zeit/next.js#737]
I want to upload all my statics files to  CND, including statics files and built JavaScript files(files in `.next` folder after build).

Is there any way to change the urls to my CDN urls in build phase? For example, the `__next/commons.js` should be `http://mycdnurl.com/__next/v0.1.0/commons.js` after build, and also the static files in `static` folder.

**Comment by rauchg** [comment]
It could be a property of the `NextScripts` element when you override `<Document>`

**Comment by rauchg** [comment]
eg: `<NextScripts prefix="" />`

**Comment by nkzawa** [comment]
I wonder if we should support JSON files of page components too.

**Comment by rauchg** [comment]
@nkzawa yeah, might have to be a `next.config.js` setting in that case (which would also make things really easy)

**Comment by aviramga** [comment]
Hi @rauchg , assetPrefix doesn't support files located in the static folder.  If I want to serve my static files from S3/CDN how would I do it?

Thanks!

**Comment by sergiodxa** [comment]
@aviramga you can use the [with-universal-configuration](https://github.com/zeit/next.js/tree/canary/examples/with-universal-configuration) to set a CDN_PREFIX with the CDN only for production and then use things like `<img src={CDN_PREFIX + '/static/my-image.png'} />`. Or use [path aliases](https://zeit.co/docs/features/path-aliases) (or similar) to configure `domain.com/static` to be served through a CDN so you don't need to prefix the files.
