### ISSUE TITLE
Handle unknown methods as 405 Method Not Allowed

### ISSUE THREAD

**Issue by macalinao** [zeit/next.js#7372]
# Feature request

## Is your feature request related to a problem? Please describe.

500's usually mean it's the server's fault that something doesn't work. We get a lot of random people sending POST requests to Next, and Next responds with a 5xx when it should respond with a 405.

https://github.com/zeit/next.js/blob/fedfbd9d5c980ca8948ab7ee0f53846a660e4122/packages/next-server/server/next-server.ts#L305

## Describe the solution you'd like
Return 405 as above https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

## Describe alternatives you've considered
Wrote a simple middleware to catch this, but really it would be better if Next.js handled this like I mentioned above.

```

    // Handle Next.js 501's instead as 405's
    // https://github.com/zeit/next.js/blob/fedfbd9d5c980ca8948ab7ee0f53846a660e4122/packages/next-server/server/next-server.ts#L305
    server.use((req, res, n) => {
      if (!(req.method === "GET" || req.method === "HEAD")) {
        res.status(405);
        res.end("Method not allowed");
        return;
      }
      n();
    });
```

## Additional context
N/a

**Comment by timneutkens** [comment]
This check is no longer there in next@canary.
