### ISSUE TITLE
custom-server-typescript production build does not work

### ISSUE THREAD

**Issue by erikhofer** [zeit/next.js#7376]
# Examples bug report

## Example name
[custom-server-typescript](https://github.com/zeit/next.js/tree/canary/examples/custom-server-typescript)

## Describe the bug
Starting the app in production mode fails.

## To Reproduce    
```
$ npx create-next-app --example custom-server-typescript custom-server-typescript-app
$ npm install
$ npm run build
$ npm start

> @ start C:\custom-server-typescript-app
> cross-env NODE_ENV=production node .next/server

module.js:550
    throw err;
    ^

Error: Cannot find module 'C:\custom-server-typescript-app\.next\server'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

## Expected behavior
The server should be started.

## System information
 - OS: Windows 10
 - Version of Next.js: 8.1.0

**Comment by antonve** [comment]
I just had the same issue. In my case I forgot to configure the `outDir` in `tsconfig.server.json`.

It used to be there, but it seems to have been removed from the example in https://github.com/zeit/next.js/pull/7362

Commit in question: https://github.com/zeit/next.js/commit/69ef5d43d6fea620a8ea7405cb81ac3393fa139b#diff-49a7f4ecf6efce19ca858e4092c5ac89

**Comment by resir014** [comment]
I've attempted to cleanup the `custom-server-typescript` example [here](https://github.com/zeit/next.js/pull/7385). Server builds should now work again 🙏
