### ISSUE TITLE
TypeError: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by TheoMer** [zeit/next.js#7377]
# Bug report

## Describe the bug

Attempting to retrieve a users IP address causes the error to be thrown on initial page hit, but after about 15 seconds the site will load properly and the value of `userip`, which I have a console.log() on, is displayed as `undefined`. 

How do I resolve this?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

pages/_app.js
```
class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};
    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }
    pageProps.query = ctx.query;
    pageProps.userip = ctx.req.headers['x-forwarded-for'];
    return { pageProps };
  }
  render() {
    const { Component, apollo, pageProps } = this.props;

    return (
      <Container>
        <ApolloProvider client={apollo}>
          <UserContext.Provider value={{ userip: pageProps.userip }}>
            <Page>
              <Component {...pageProps} />
            </Page>
          </UserContext.Provider>
        </ApolloProvider>
      </Container>
    );
  }
}
```

## Expected behavior
I expected `pageProps.userip = ctx.req.headers['x-forwarded-for']` to return a users IP address, which I would then pass intov a react context.

## System information
 - OS: Windows 10 Pro
 - Version of Next.js: 8.1.0
 - Express server: 4.16.4

## Additional context

UserContext.js
```
import { createContext } from 'react';

const UserContext = createContext();

export default UserContext;
```

components/somepage.js

```
    const { userip } = useContext(UserContext);
    console.log("User IP = ", userip);
```

server.js (Custom express server)
```
const app = next({ dev })

const handle = app.getRequestHandler()

const ssrCache = cacheableResponse({
  ttl: 1000 * 60 * 60, // 1hour
  get: async ({ req, res, pagePath, queryParams }) => ({
    data: await app.renderToHTML(req, res, pagePath, queryParams)
  }),
  send: ({ data, res }) => res.send(data)
})

server.set('trust proxy', true);

// Header security. See: https://observatory.mozilla.org/
server.use(helmet());

// Sets "Referrer-Policy: same-origin".
server.use(helmet.referrerPolicy({ policy: 'same-origin' }));

// Sets Feature-policy
server.use(helmet.featurePolicy({
    features: {
      fullscreen: ["'self'"],
      vibrate: ["'none'"],
      payment: ['https://yyy.com'],
      syncXhr: ["'self'"],
      geolocation: ["'self'"]
    }
}));

app.prepare().then(() => {
  server.get('*', function(req,res,next) {
    if(req.headers['x-forwarded-proto'] != 'https' && process.env.NODE_ENV === 'production')
    res.redirect('https://'+req.hostname+req.url)
    else
    next() /* Continue to other routes if we're not redirecting */
  });

  server.get('/', (req, res) => ssrCache({ req, res, pagePath: '/' }))

  server.get('*', (req, res) => handle(req, res))

  server.listen(port, err => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
})
```

**Comment by ijjk** [comment]
Hi, it looks like you're trying to access `ctx.req` on the client side and it is not defined there only during SSR. You can wrap that in `if (ctx.req)` before trying to access the headers to prevent that. 

I'm gonna close this now if you're still having trouble with it feel free to reply.

**Comment by TheoMer** [comment]
@ijjk Hi,

`only during SSR`

are you saying that I can only access ctx.req.headers['x-some-value'] only from `_document.js`? Can you share specifically what you mean?

**Comment by ijjk** [comment]
So the `ctx.req` represents the request sent to the server. It is passed to `getInitialProps` during SSR that means either the `_app`, `_document`, or your page's `getInitialProps`. It's not available when `getInitialProps` is called in the browser since it's done client-side and thus no request to the server to be passed.
