### ISSUE TITLE
Allow to customize code splitting options

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#738]
See this comment: https://github.com/zeit/next.js/issues/659#issuecomment-271824223

Different apps needs different code splitting setup. So, we need to allow to modify code splitting options. Here's a list of stuff we should expose:

* Set of modules to include always in the common chunk
* White listed set of options used in the commonChunksPlugin

**Comment by rauchg** [comment]
Yep, this would be a simple yet really powerful option

**Comment by mmiszy** [comment]
Has there been any progress or new information on this?

**Comment by timneutkens** [comment]
Closing this in favor of #738
