### ISSUE TITLE
How to use external css files/links

### ISSUE THREAD

**Issue by arunkumar413** [zeit/next.js#7382]
# How to use external css files/links

Hi Team,

I'd like to use w3css library ( <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> ) in nextjs. Please let me know how to configure this library.

Thanks,
Arun

**Comment by vinzun** [comment]
You need to override _document.js by creating ./pages/_document.js. Read it in the documentation. Put this in the Head, <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

**Comment by timneutkens** [comment]
Closing this as it doesn't follow the issue template.
