### ISSUE TITLE
Proposal: porting custom-server-express to typescript

### ISSUE THREAD

**Issue by Gregcop1** [zeit/next.js#7386]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm working on a new Api Platform client generator related to Next.js. The idea is to create automatically Next.js pages using API Platform infos. The generator is almost finished but ATM, user has to combine himself "custom-express-server" and typescript configuration, and declare custom routes himself in the server. (without "official" configuration I don't know where is server configuration file so I can't customize it myself).
With a custom-server-express example compatible with typescript a user can generate an whole website related to his API info by using only two commands (next init with example then  ApiP generator)

## Describe the solution you'd like

I can work on this PR but I want to be sure it's ok for you first. If so, do I have to create a new example "custom-server-express-with-typescript" or do you have any idea to customize current examples with options (may be something to request example in JS or in TS) ?

## Describe alternatives you've considered
/

## Additional context
/

**Comment by timneutkens** [comment]
Closing this in favor of https://github.com/zeit/next.js/issues/7297
