### ISSUE TITLE
Splitting .js and .jsx for pages not reloading

### ISSUE THREAD

**Issue by burninggoose** [zeit/next.js#7388]
# Bug report

## Describe the bug

I am splitting pages as other my components by creating folder name PageName with PageName.jsx file containing all React code and index.js simply exporting PageName.jsx. Somehow hot reload doest not work. Even after manually reloading page it doesn't update.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create folder TestPage in /pages
2. Create file TestPage.jsx inside TestPage folder with some valid react component and export it as default
3. Create index.js inside TestPage folder with following code:
```
import TestPage from './TestPage.';

export default TestPage;
```
4. Launch dev server and try to update code inside TestPage.jsx

## Expected behavior
Page will refresh with new component

## Screenshots
none

## System information
 - OS: macOS Mojave 10.14.4
 - Browser Chrome
 - Version of Next.js: [e.g. 8.1.0]

**Comment by ijjk** [comment]
This folder structure is not ideal since each file in `pages` that has a matching `pageExtension` will be built as a page. If you want to break-up your pages it would be better to create a folder `components/TestPage` and import it in `pages/TestPage`.

**Comment by burninggoose** [comment]
Oh, ok then. Thank you for explaining.
