### ISSUE TITLE
next-prefetcher service worker present when next/prefetch not used

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#739]
I don't have any import of next/prefetch in my project, and yet I see this in DevTools:

<img width="406" alt="screen shot 2017-01-11 at 14 29 37" src="https://cloud.githubusercontent.com/assets/4217871/21848665/a09a3560-d80a-11e6-8f99-81118fa71118.png">

**Comment by arunoda** [comment]
Service workers a background worker runs beyond your web page's lifetime.
It seems like, you've registered a SW with a different version of the app running on this port and the server worker is still running.

But it won't do anything.

**Comment by sedubois** [comment]
OK indeed I see that the problem is only locally, the deployed version doesn't have such a service worker when next/prefetch isn't used.
