### ISSUE TITLE
import `promise-mysql` make a error

### ISSUE THREAD

**Issue by kunjiang** [zeit/next.js#7394]
Hello, In pages, I want get datas from mysql, so import node module 'promise-mysql'. but make an error, like this: 

```
Failed to compile
../node_modules/mysql/lib/protocol/sequences/Query.js
Module not found: Can't resolve 'fs' in 'd:\jk-work\dev-repos\dl-repos\dl-bs-ssr\node_modules\mysql\lib\protocol\sequences'
This error occurred during the build time and cannot be dismissed.
```

so , I want to know whether Next,js Pages can use node module to connect mysql in method `getInitialProps`. 

Thank you!

**Comment by timneutkens** [comment]
You'll have to create a separate API endpoint as mysql queries can't be ran inside of the browser and getInitialProps is ran in the browser.

Soon you'll be able to build APIs in Next.js: https://github.com/zeit/next.js/issues/7297

**Comment by kunjiang** [comment]
thanks so mouch. I will try it later！
