### ISSUE TITLE
Webpack.config override optimization

### ISSUE THREAD

**Issue by xiaofengbai** [zeit/next.js#7401]
# Feature request

## Is your feature request related to the issue? Please describe it.
When splitChunks, I don't need to package some modules in node_modules to commons.js. I need to write my own logic.

##Describe the solution you want
The parameters are exposed in next.config.js and the optimization attribute is modified.

##Describe the alternatives you have considered
It can be solved

**Comment by xiaofengbai** [comment]
![image](https://user-images.githubusercontent.com/23304049/58160473-23038680-7cb1-11e9-827f-c3f4c128b748.png)
I need rewrite this function

**Comment by KumarAbhirup** [comment]
Why does this need to rewritten?? Does the commented code not work with appropriate modules installed?

**Comment by timneutkens** [comment]
You can override the webpack config already: https://nextjs.org/docs#customizing-webpack-config
