### ISSUE TITLE
styled-jsx messed up when using .babelrc on root and using next on a subfolder

### ISSUE THREAD

**Issue by mattecapu** [zeit/next.js#743]
It's a weird issue I managed to downsize to [this minimal use case](https://github.com/mattecapu/test-next-styled-jsx-and-babelrc-issue).
Clone the repo and then run
```bash
npm install
npm start
```
and go to `localhost:3000`.

**Expected behaviour**: render a green, a red and a purple line of text.
**Observed behaviour**: renders 3 lines of green text.

It appears to be caused by running `next` inside a subdirectory, where it doesn't find a `.babelrc` file. Indeed, a temporary fix is to add a copy of your root `.babelrc` in the subdirectory as well.
The only effect seems to be messing up with styled-jsx encapsulation (confusing children and parent styles). Everything else is transpiled correctly.

**Comment by timneutkens** [comment]
@mattecapu I guess this is because of the .babelrc fallback. Can you how the `.babelrc` in your root folder?

**Comment by mattecapu** [comment]
it's all in the repo

**Comment by timneutkens** [comment]
@mattecapu oh sorry, I totally missed that <3

**Comment by mattecapu** [comment]
nothin on this? how can I fix?

**Comment by arunoda** [comment]
That seems like a weird bug. Let's see.

**Comment by arunoda** [comment]
@nkzawa any pointers?

**Comment by arunoda** [comment]
Research Notes.

Check these two gists: https://gist.github.com/arunoda/2307c8f6535a794185726ac8d5297bf1
Seems like `data-jsx` id getting set twice.
