### ISSUE TITLE
Webpack module CSP `unsafe-eval` issue

### ISSUE THREAD

**Issue by PrudviGali** [zeit/next.js#7457]
# Bug report

## Describe the bug

Webpack is injecting `unsafe-eval` code in next.js dev build. It will cause issues if you enabled Helmet CSP.

## To Reproduce

1. Clone  [Github Repo](https://github.com/PrudviGali/next.js-webpack-csp-issue)
2. Do `npm install` and `npm run dev`.
3. Open browser and load `http://localhost:8080`
4. Open browser developer console and see the issue.

## Expected behavior

We didn't have this issue with Next.js v6. It seems to be happening with Webpack upgrades in Next.js v8.x.x  

## Screenshots

![Screen Shot 2019-05-29 at 11 10 04 AM](https://user-images.githubusercontent.com/10725504/58573271-00b6bf00-8203-11e9-995f-19b9ae2fb56e.png)

## System information

- OS: macOS
- Browser: chrome
- Version of Next.js: [8.0.4]

## Additional context

Not sure if it needs to be reported to Webpack repo or not.

**Comment by dav-is** [comment]
Hey there :wave:

This is being caused by the webpack autodll plugin that we use to make dev builds faster. This issue does not occur in production builds. This will be solved whenever we migrate to Webpack 5.
