### ISSUE TITLE
Redirect to 404 page in getInitialProps()?

### ISSUE THREAD

**Issue by nodegin** [zeit/next.js#746]
As title mentioned, how can I redirect client to 404 in `getInitialProps()`?

for example, I cannot fetch results from API then the page should display "Not Found".

**Comment by nkzawa** [comment]
There is no way to render the default error page in this situation, but you can to do the following for now.

```js
static getInitialProps({ res }) {
  if (res) {
     res.statusCode = 404
     res.end('Not found')
     return
  }
}
```

**Comment by iest** [comment]
I'd really like to be able to do this.

How are you running this on `zest.co/blog` currently?

**Comment by nodegin** [comment]
@nkzawa This seems cannot render the 404 page?

**Comment by dizlexik** [comment]
My current workaround which is working well for now:

```js
import Error from './_error';

class Example extends Component {
  static async getInitialProps({ res }) {
    const data = await fetchSomeData();
    if (!data && res) res.statusCode = 404;
    return { data };
  }
  render() {
    const { data } = this.props;
    if (!data) return <Error status={404} />;
    return <div>data: {data}</div>;
  }
}
```

**Comment by nwshane** [comment]
@dizlexik Very useful, thanks!

Just a note: you have to pass the prop `statusCode` to error, not `status`. Updated code:

```
import Error from './_error';

class Example extends Component {
  static async getInitialProps({ res }) {
    const data = await fetchSomeData();
    if (!data && res) res.statusCode = 404;
    return { data };
  }
  render() {
    const { data } = this.props;
    if (!data) return <Error statusCode={404} />;
    return <div>data: {data}</div>;
  }
}
```

**Comment by moroshko** [comment]
@dizlexik @nwshane Where is `'./_error'` coming from?
Did you have to create a custom error page?

**Comment by timneutkens** [comment]
@moroshko in his case yeah. But you can also use `next/error` which is the build in error page 👍

**Comment by ilionic** [comment]
@moroshko it's per docs https://github.com/zeit/next.js#custom-error-handling If you want to customise it.
