### ISSUE TITLE
File structure 

### ISSUE THREAD

**Issue by knipferrc** [zeit/next.js#747]
So I'm thinking about making the switch from CRA to next.js. One question I have is what is folder structure like for a larger app. I have a modules folder now for my pages. So for example I have a login module that has the main login component, a folder for tests, a folder for any components that login needs and a folder for the mobx store. Is this possible with next, or do I need to go about it differently?

**Comment by nkzawa** [comment]
next.js doesn't require any file structures except `pages` dir and `static` dir. You can have any folders in your app.
