### ISSUE TITLE
Catching dynamic import errors

### ISSUE THREAD

**Issue by arunesh90** [zeit/next.js#7480]
# Feature request

## Is your feature request related to a problem? Please describe.

It would be handy to be able to catch any errors that may arise for dynamic imports, like a component not found, so we could handle the error and show a custom message for example.
I haven't seen a documented way of doing such a thing so that's why I'm requesting it.

## Describe the solution you'd like

An additional option to which a function can be passed to handle errors. Maybe that you can also return a element that will be shown then?

An rough example of what I had in mind:
```
import dynamic from 'next/dynamic'

const DynamicComponent = dynamic(
  () => import('../components/hello'),
  {
    loading     : () => <p>...</p>,
    errorHandler: (err) => {
      console.error('An issue has occured while loading a component', err)

      if (err.code === 'MODULE_NOT_FOUND') {
        return <p>Unknown item</p>
      }

      return <p>Unknown error..</p>
    }
  }
)
```

**Comment by ijjk** [comment]
Hi, one way you could currently handle this is adding a `.catch` on the `import` e.g.

```js
import dynamic from 'next/dynamic'

const Hello = dynamic(
  () => import('../components/hello').catch(err => {
    return () => <p>oops... this failed to load</p>
  }
}
```

**Comment by arunesh90** [comment]
Ah, yeah that totally works for me. Thanks!

**Comment by timneutkens** [comment]
The `loading` component gets an error prop if it fails to load btw.

**Comment by sakshambakshi** [comment]
Hi @ijjk ,
This doesnt seems to work in next "12.0.8", please see to it as it needed urgently.
![image](https://user-images.githubusercontent.com/18244721/151534531-77b7c119-cd97-474b-8efa-6750c4ef3a6f.png)

![image](https://user-images.githubusercontent.com/18244721/151534225-77030de2-e50a-4095-9d4a-c45ba304dccd.png)
 Thanks
 cc: @timneutkens

**Comment by gatewayweb** [comment]
Any chance of this being reopened or a new workaround? Running into the same issue as well.

**Comment by ijjk** [comment]
Hi, failing to resolve the import during build is different than failing to load it during runtime. During runtime `.catch()` can be used to handle the error but during build-time it can not and shouldn't be as the import should fixed instead to point to a valid path.

**Comment by malithmcr** [comment]
Yes, I'm having the same issue.
