### ISSUE TITLE
Advanced browser history manipulation

### ISSUE THREAD

**Issue by Rolan2772** [zeit/next.js#7495]
# Feature request

## Is your feature request related to a problem? Please describe.

At the moment we're rewriting legacy frontend application piece by piece, using the NextJs as a separate frontend microservice. Whole response from NextJs service is being composed (injected) into the legacy page. 

Right now I'm facing the issue with routing and browser history manipulation. During the client-side routing, I can use <Link .../> or Router.push(...) which change browser history according to the internal application routing rules. Let's imagine Next application is a part of the other app, with its own URL's rules (URL's are SEO sensitive). In that case, during the client-side routing, I need to manipulate browser history directly after routing in order to update the parent application URL. 

As an example let's imagine the pagination component, where each page adds a query parameter to the URL. 
NextJs app URL - https://next-app/component?page=1 (page=2, page=3, ....)
Parent app URL - https://parent-application/resource-a/resource-b/resource-c?page=1 (page=2, page=3, ....)

Unfortunately, I didn't find any suitable way of specific browser history manipulation using NextJs routing.

## Describe the solution you'd like

Let's imagine two use cases. 

First, NextJs application would be an independent service. The client-side routing should work the same way as now doing all manipulations with browser history under the hood. No changes needed. 

The second use case would be NextJs application is being part of the other application. In that case, the client-side routing should work with the same rules as now, but providing the possibility to set browser history respecting rules for the parent application.

## Describe alternatives you've considered

Any possible alternative.

**Comment by Timer** [comment]
Hi! A question like this is more suitable for our [Spectrum](https://spectrum.chat/next-js). Please repost this there!

In any case, the ["Custom routes" section](https://github.com/zeit/next.js#with-link) here may be interesting to you.

```js
<Link href="/component?page=1" as="/resource-a/resource-b/resource-c?page=1">
```

**Comment by Rolan2772** [comment]
Hi, thanks for the response! Router 'as' functionality working well, but unfortunately, it is not that trivial to realize. Maybe it would be valuable to add more examples to the documentation using <Link ...> or  Router.push({...}) and all the parameters with specific examples, e.g like a case for preserving SEO sensitive links.
