### ISSUE TITLE
Version 8.1 of Next.js is not working on Android 4.4, Android 5.0, Android 5.1... 

### ISSUE THREAD

**Issue by airamrguez** [zeit/next.js#7496]
# Bug report

## Describe the bug
It doesn't work on Android 4.4, Android 5.0, Android 5.1 and may be more 🤷‍♂️. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create an empty Next.js project and add a button with a listener that logs a text to the console
2. Run yarn dev
3. Open an Android 4.4 emulator and open the web page.
4. Click the button
5. Nothing appears in the console.

## Expected behavior

It should log the text in the console.

## Screenshots

<img width="1013" alt="Captura de pantalla 2019-06-04 a las 17 53 25" src="https://user-images.githubusercontent.com/1159448/58894106-af6e6a00-86f1-11e9-8b17-386d5e164855.png">

## System information

- OS: All
- Browser: Android Chrom(e|ium)
- Version of Next.js: [8.1.0] and [8.1.1-canary]

## Additional context

It works with Next.js 8.0.3.

I've tried to remove the code from the source related to asyncToPromises from the file `next-babel-loader` as @yanghuabei mentioned in #7178 without luck.

**Comment by Timer** [comment]
Thanks for the report! This should be fixed by https://github.com/zeit/next.js/pull/7554.

**Comment by airamrguez** [comment]
@Timer thanks for your support!! I will try to test the canary version tomorrow.

**Comment by Timer** [comment]
Published as `8.1.1-canary.51` 🙏
