### ISSUE TITLE
Objects stored in context.query are converted to empty strings after pressing back button

### ISSUE THREAD

**Issue by jamesnicholls** [zeit/next.js#7508]
# Bug report

## Describe the bug

Objects stored in `context.query` are converted to empty strings after pressing back button.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone this repo: https://github.com/jamesnicholls/nextjs-back-btn-bug-test-case
2. Run `npm install`
3. Run `npm run dev`
4. Navigate to http://localhost:3000
5. The page renders the query object as expected: `testString` is `hello world`, `testObject` is `{"type":"info","message":"hello world"}`
6. Click the link to page B
7. Click back button
8. The page no longer renders the query object as expected: `testString` is still `hello world` but `testObject` is an empty string

## Expected behavior

The `query` object is restored to its previous state.

## Screenshots

Query rendered correctly:

![Screenshot 2019-06-05 at 15 02 02](https://user-images.githubusercontent.com/1705375/58962389-f6686800-87a2-11e9-9b48-2b84b4fcaab4.png)

Query rendered incorrectly:

![Screenshot 2019-06-05 at 15 02 07](https://user-images.githubusercontent.com/1705375/58962407-02ecc080-87a3-11e9-9f30-b5f0f350ffb5.png)

## System information

- OS: MacOS
- Browser: Tested on Firefox 67.0.1 but believe it happens on all browsers
- Version of Next.js: 8.1.0

## Additional context

I've passed the `query` from an Express handler to a Next page component in this example, but I believe the issue will happen even if `query` is provided in the `href` prop of a `Link` component.

**Comment by timneutkens** [comment]
Nested objects are not supported as querystrings.
