### ISSUE TITLE
Error: "Warning: 'next/css' is deprecated." when importing Glamor.

### ISSUE THREAD

**Issue by frankalbenesius** [zeit/next.js#752]
The next/css deprecation warning displays even when you import your own Glamor. (BYOG).
I have no imports of next/css in my project.

<img width="1205" alt="next css warning" src="https://cloud.githubusercontent.com/assets/1828900/21904796/819ad35c-d8ca-11e6-8733-e35786595868.png">

**Comment by timneutkens** [comment]
Fixed in #754.
