### ISSUE TITLE
support Build watch for target serverless(use next.js as ssr view)

### ISSUE THREAD

**Issue by icai** [zeit/next.js#7528]
I try to use next.js as koa/express template engine. try to use serverless target to do this. but next.js don't provide `next build --watch`.

I try to mixin next.js, koa/express, for example the traditional architecture (MVC) in one server(process).

MC use koa/express, V use next.js build out template and then render it.

-----------

My workflow: 

I use spawn start next.js to build, out the file to View directory.

**Comment by Timer** [comment]
You should be able to accomplish this by editing the webpack configuration and make it watching. We'll likely not explore this as a default because it'd take a significant amount of time to rebuild and we encourage `next dev` for iteration.
