### ISSUE TITLE
with-redux-saga is bundling all sagas in _app bundle

### ISSUE THREAD

**Issue by Lokesh235** [zeit/next.js#7530]
This is causing _app bundle to be very heavy and seems like non scalable. Any comments.

**Comment by ku8ar** [comment]
What's weird about that? Redux (and sagas) is SSoT. Everything in one place.
You should add this issue in next-redux-wrapper repo btw.

**Comment by timneutkens** [comment]
Please post questions on https://spectrum.chat/next-js

**Comment by Lokesh235** [comment]
> Please post questions on https://spectrum.chat/next-js (as per the issue template)

I posted there too not a single but many questions from the last few months but never got any guidance.
