### ISSUE TITLE
Next.js Official Tutorial Bug

### ISSUE THREAD

**Issue by latteyo** [zeit/next.js#7538]
# Examples bug report
Next.js Tutorial Example Code bug
## Example name
Creating Our First Page

## Describe the bug

The example should include a return.

## Screenshots
![image](https://user-images.githubusercontent.com/46841257/59159652-dd93e580-8b07-11e9-9562-ee5386225d93.png)

![image](https://user-images.githubusercontent.com/46841257/59159599-36af4980-8b07-11e9-8707-c1dbfca71209.png)

![image](https://user-images.githubusercontent.com/46841257/59159616-783ff480-8b07-11e9-8b4f-88f090c4a509.png)

## System information

- OS: Windows
- Browser (if applies) chrome
- Version of Next.js: 8.1.0

## Additional context

In fact, it may not be a problem. For a more complete tutorial article, you might need to add a return to your code.

**Comment by MarchWorks** [comment]
There is no problem in the tutorial there is `const Index = () => (` and you are doing `const Index = () => {`
check the last character

**Comment by c0b41** [comment]
This is not a bug, you must be use brackets.

Checkout arrow function documentation https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by huv1k** [comment]
Yes, you need to use `(` if you want to use `{` you need to return value from this scope.

**Comment by latteyo** [comment]
Oh Thank you. I think I was mistaken.
