### ISSUE TITLE
with-typescript example 404s after build

### ISSUE THREAD

**Issue by imjared** [zeit/next.js#7539]
## Example name

with-typescript

## Describe the bug

Running `README.md` instructions results in 404 page showing up instead of an actual working typescript example

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run step in readme: `npx create-next-app --example with-typescript with-typescript-app`
2. `$ cd` into newly created directory
3. Load `localhost:3000` and get a 404 page
4. All paths that exist in `/pages` produce a 404 error

## Expected behavior

1. Upon running `yarn dev`, application is available at specified port (`:3000`).

## System information

- OS: macOS 10.14.5 (18F132)
- chrome
- Version of Next.js:
```bash
$ next --version
Next.js v8.1.0
```

**Comment by MarchWorks** [comment]
use Next 8.1.1-canary.28

**Comment by Timer** [comment]
Sorry for the noise -- but yes, for now please use the Next.js canaries. This will be released as stable soon!

**Comment by grrowl** [comment]
Not ideal but can confirm this works (with `next@8.1.1-canary.52`)
