### ISSUE TITLE
Next.js Development does not work well with ngrok

### ISSUE THREAD

**Issue by meenie** [zeit/next.js#7556]
# Bug report

## Describe the bug

When running Next.js in dev mode and then trying to load the app with ngrok.io everything kinda goes wonky. The CLI reports back `Warn: You are opening multiple tabs of the same site in the same browser, this could cause requests to stall. https://err.sh/zeit/next.js/multi-tabs`. That is not the case, I've got it open in one tab.  The reloading of the page/code sometimes doesn't happen.  I'm assuming it's because of the 2 connections that Next.js tries to keep open and ngrok is messing with that.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `$ next dev`
2. Start ngrok on the port Next.js reports back: `$ ngrok -p 3000`
3. Make changes to your app and navigate around while checking your terminal and the browser console.

## Expected behavior

Running the dev through ngrok should not have an issue.  I'm assuming this is a pretty low priority bug, but I thought I should file it nonetheless.

**Comment by adnanfajlur** [comment]
any update on this

**Comment by ijjk** [comment]
Hi, this was removed/updated in #7084. I'm going to close this, feel free to reply with additional info if you are still encountering trouble with this on an updated version.
