### ISSUE TITLE
dynamically import js files question

### ISSUE THREAD

**Issue by xiaomei991** [zeit/next.js#7558]
# Question about Next.js

I want to use baidu map js API, but I don't want to import the file globally. 
I only want to import the file in the page I use.
Whether it can be achieved.
How do I do that.

**Comment by Timer** [comment]
If you import the file in the page it won't be bundled into other pages. 😄 This should work for you OOTB.

**Comment by xiaomei991** [comment]
@Timer What is OOTB? I haven't used it. Can you give me an example or tutorial
