### ISSUE TITLE
how to code next.config.js in production environment.

### ISSUE THREAD

**Issue by heavenlian** [zeit/next.js#7559]
next.config:
```
const withTypescript = require('@zeit/next-typescript')
conf = {
  distDir: '../build',
  generateEtags: false
}
module.exports = withTypescript(conf)
```
when i deploy my project and npm run start.
I think withTypescript is useless. and i didn't install in package.json dependencies.
so how to code different next.config when i want to run in production environment

**Comment by SarKurd** [comment]
I think you can use `next/constants` and `next-server/constants` to get different phases
https://github.com/zeit/next.js/issues/5750#issuecomment-442313585

**Comment by Timer** [comment]
@heavenlian `next.config.js` is typically only used for the building step, and should be conceptually treated that way.

If you're using `target: 'serverless'` then this is already the case. Legacy server mode (unfortunately) loads this file, so you may need to use the above workaround.
