### ISSUE TITLE
with-react-relay-network-modern - non-functional example

### ISSUE THREAD

**Issue by d3vhound** [zeit/next.js#7565]
# Examples bug report

## Describe the bug
At first the data is there but then it disappears and is null thus throwing this error. 

```bash
TypeError: Cannot read property 'modern' of undefined
    at getNode (/Users/devionvillegas/Developer/NEXTGEN/with-react-relay-network-modern-app/node_modules/relay-runtime/lib/RelayModernGraphQLTag.js:25:71) ...
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. download the example with `npx create-next-app`
2. run `npm run schema`
3. run `npm run relay`
4. console.log props inside the BlogPosts.js component
5. run `npm run dev`
6.  error is thrown along with two console.log outputs 
<img width="830" alt="Screen Shot 2019-06-12 at 10 17 37 PM" src="https://user-images.githubusercontent.com/17565159/59401667-12e74000-8d61-11e9-992a-64fb52271f15.png">

## Expected behavior

You can see that on the first render, the data is there which means something else is triggering a re-render and making the array null. I can't exactly figure it out as I'm used to using apollo and this was my first time trying to see what relay was about. Hopefully the other examples work. Was hoping it would be trivial to use relay with nextjs.

**Comment by Timer** [comment]
We welcome a motivated contributor to fix this example (or debug what's wrong here). 😄
