### ISSUE TITLE
Next build app hangs forever after compiled successfully

### ISSUE THREAD

**Issue by sdelvalle57** [zeit/next.js#7567]
# Bug report

After running  `next build`, I got the  `Compiled successfully` message but It never ends.

So I was wondering if there is a way to debug that command or if there is already
a solution for this.

This is a project using Next 8.1.0 with babel 7.4.3

![1212](https://user-images.githubusercontent.com/12821552/59409058-bb94ae80-8df8-11e9-816a-b35d721f0406.PNG)

**Comment by Timer** [comment]
You'll have to debug this with the standard Node debugger --  have you customized webpack configuration at all?

**Comment by timneutkens** [comment]
Please follow the issue template and provide a full reproduction, then we can look into it, thanks 🙏
