### ISSUE TITLE
How to execute getInitialProps to double

### ISSUE THREAD

**Issue by smithyj** [zeit/next.js#7568]
Now, I use `export` to deploy and also have a timer to execute `export`, but `getInitialProps` won't execute again after opening the page. How can I get it to execute again? I don't want to do it again in `componentDidMount`

**Comment by timneutkens** [comment]
Please follow the issue template.

**Comment by smithyj** [comment]
can i use chinese?

**Comment by quietshu** [comment]
@smithyj 可以 😃
