### ISSUE TITLE
Server-side dynamic templated import()s work in development but not production

### ISSUE THREAD

**Issue by wilsonpage** [zeit/next.js#7569]
# Bug report

## Describe the bug

When you need to dynamically import some content (eg `.md` files) but you don't want them all to be part of the main bundle and don't want to maintain a list of hard-coded dynamic imports you can use `import()` with template string.

This works find in dev (via `now dev`) but fails in production.

## To Reproduce

```js
const articleId = 'faq';
const article = await import(`./articles/${articleId}.md`);
```

## Expected behavior

The `import()` should resolve, but it fails *only* server-side *only* production (via `now`).

## Screenshots

It fails with the following error:

```
article TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at webpackAsyncContext (/var/task/page.js:27734:34)
    at _callee$ (/var/task/page.js:14545:47)
    at tryCatch (/var/task/page.js:24367:40)
    at Generator.invoke [as _invoke] (/var/task/page.js:24593:22)
    at Generator.prototype.(anonymous function) [as next] (/var/task/page.js:24419:21)
    at asyncGeneratorStep (/var/task/page.js:12716:24)
    at _next (/var/task/page.js:12738:9)
    at /var/task/page.js:12745:7
    at new Promise (<anonymous>)
```

## System information

- OS: MacOS / Now
- Version of Next.js: 8.1.0

## Additional context

- I'm currently working around the issue by using [`codegen`](https://github.com/kentcdodds/babel-plugin-codegen) to print out hard-coded imports `import('./articles/foo.md'); …`.
- https://medium.com/front-end-weekly/webpack-and-dynamic-imports-doing-it-right-72549ff49234

**Comment by wilsonpage** [comment]
I'm unsure if this is a `next`, `now` or `@now/next` issue. Apologies if this is in the wrong place.

**Comment by Timer** [comment]
Hi! Without a fully reproducible demo we're not going to be able to help much. Can you please provide a repository?

**Comment by wilsonpage** [comment]
Dammit, I can't repro now and no idea why 🤦‍♂️ I'll reopen if I run into it again.
