### ISSUE TITLE
Hot reload on virtualbox with windows folder mount

### ISSUE THREAD

**Issue by kenji4569** [zeit/next.js#757]
Hot reload does not work on virtualbox with windows folder mount, probably due to disabled poll option of webpackDevMiddleware. The poll option is set to true when isWindowsBash is true, but isWindowsBash is not true on virtualbox with windows folder mount. The solution would be to allow to configure webpackDevMiddleware in next.config.js.

**Comment by rauchg** [comment]
😨

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/pull/823

**Comment by dillonraphael** [comment]
Have you found a work around?

**Comment by arunoda** [comment]
Yep. Closing this in favor of #823
