### ISSUE TITLE
Help: SyntaxError: Unexpected token '>'

### ISSUE THREAD

**Issue by sealzrt** [zeit/next.js#7572]
# Bug report

## Describe the bug

SyntaxError: Unexpected token '>'

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. install next.js 8.1.1-canary.50
2. build and start server
3. open page in ios8 safari

## Expected behavior

page should work.

## System information

- OS: ios8
- Browser: safari
- Version of Next.js: 8.1.1-canary.50

**Comment by sealzrt** [comment]
![image](https://user-images.githubusercontent.com/6469925/59452934-67fa8300-8e41-11e9-9088-82384a95f6ba.png)
![image](https://user-images.githubusercontent.com/6469925/59452961-7779cc00-8e41-11e9-9143-ecae17f28fcf.png)
![image](https://user-images.githubusercontent.com/6469925/59452985-8496bb00-8e41-11e9-8191-67058a7dabb4.png)
![image](https://user-images.githubusercontent.com/6469925/59453006-8d878c80-8e41-11e9-98da-1f00ff6f6f09.png)

**Comment by sealzrt** [comment]
examples: https://github.com/zeit/next.js/tree/canary/examples/with-polyfills
next: 8.1.0
error: SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.

![image](https://user-images.githubusercontent.com/6469925/59492588-db40db00-8ebb-11e9-888c-7e692ff26c6b.png)
![image](https://user-images.githubusercontent.com/6469925/59492635-f875a980-8ebb-11e9-80a7-131d2e26021a.png)
![image](https://user-images.githubusercontent.com/6469925/59492656-0297a800-8ebc-11e9-8f23-25517c6ed3cd.png)

**Comment by Timer** [comment]
> error: SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.

This is fixed in the latest canary -- not `8.1.0`.

---

As for the syntax issues, you'll need to compile the modules because they're not compatible with that old of a Safari.
