### ISSUE TITLE
    [TypeError: ampOptimizer.setConfig is not a function]

### ISSUE THREAD

**Issue by cesarvarela** [zeit/next.js#7573]
# Bug report
[TypeError: ampOptimizer.setConfig is not a function]

## Describe the bug
I'm getting this error in the production build
I have a custom _document and _app but I'm not sure if they are causing the error.

## To Reproduce
I'm working on an amp-first page.

## System information
- Version of Next.js: 8.1.0

**Comment by Timer** [comment]
Please provide a reproducible demo or there's not much we can do to help here.

**Comment by MarchWorks** [comment]
Try using the latest canary build

**Comment by cesarvarela** [comment]
I'll close this until I have time to make a repro case.
