### ISSUE TITLE
Nothing gets minified during production mode

### ISSUE THREAD

**Issue by patrykmaron** [zeit/next.js#7575]
# Bug report

## Describe the bug

When running 'next build' with NODE_ENV=production all css chunks and js files aren't minified, and I am seeing files as large as 300kb. Should this be done by itself? I am using next-sass in my config.next

## To Reproduce

**my package.json:** 
> {
>   "scripts": {
>     "dev": "node server.js",
>     "build": "cross-env NODE_ENV=production next build",
>     "start": "cross-env NODE_ENV=production node server.js",
>     "heroku-postbuild": "npm run build"
>   },
>   "dependencies": {
>     "@svgr/webpack": "^4.3.0",
>     "@zeit/next-css": "^1.0.1",
>     "@zeit/next-sass": "^1.0.1",
>     "animejs": "^3.0.1",
>     "bulma": "^0.7.5",
>     "bulma-divider": "^0.2.0",
>     "compression": "^1.7.4",
>     "express": "^4.17.1",
>     "hamburgers": "^1.1.3",
>     "next": "^8.1.0",
>     "node-sass": "^4.12.0",
>     "react": "^16.8.6",
>     "react-dom": "^16.8.6"
>   },
>   "devDependencies": {
>     "cross-env": "^5.2.0"
>   }
> }

**and my config.next.js file:**

> const withSass = require('@zeit/next-sass')
> 
> module.exports = withSass({
>     webpack(config) {
>       config.module.rules.push({
>         test: /\.svg$/,
>         use: ['@svgr/webpack'],
>       });
>   
>       return config;
>     }})

This set up will build, but nothing is minified. 

## Expected behavior

I expect my CSS and JS files to be minified

## System information

- OS: [Windows 10]
- Version of Next.js: [^8.1.0]

## Additional context

I could be doing something wrong? Do I need to pass in config options to next-sass to make this work? But how about the JS files? Those aren't minified neither. So I am not sure.

**Comment by Timer** [comment]
Be sure you're looking at the client JS bundles -- the server bundles aren't minified as it's not worth the CPU time and doesn't help performance in any significant way.

As for CSS minification, please open an issue on the plugins repository as CSS support in Next is only for `styled-jsx`.
