### ISSUE TITLE
Add rax example

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#758]
https://github.com/alibaba/rax

Impressive server-rendering performance

![image](https://cloud.githubusercontent.com/assets/13041/21919358/95d53ff8-d90e-11e6-8578-fc7b47cffc26.png)

**Comment by timneutkens** [comment]
@arunoda I can add it if you want 👍

**Comment by arunoda** [comment]
@timneutkens got for it. I'm also hacking into that.
If you got it working, ping me.

**Comment by timneutkens** [comment]
@arunoda sure thing, will try to do that tonight 😄

**Comment by arunoda** [comment]
@timneutkens I couldn't make it work. But I could get rid of error messages.
See: https://github.com/zeit/next.js/pull/759

**Comment by arunoda** [comment]
I think we are no longer going with this. https://github.com/zeit/next.js/pull/759
