### ISSUE TITLE
Move to something newer than react-loadable

### ISSUE THREAD

**Issue by ScriptedAlchemy** [zeit/next.js#7581]
# Feature request

## Is your feature request related to a problem? Please describe.

Hey, I was wondering if there were any plans to move onto a more maintained Universal component other than react loadable? It's been unmaintained for a while and the three remaining authors who are maintaining more up to date tools. 

## Describe the solution you'd like

Ideally, start to leverage Suspense with one of the more modern fallbacks on the server. 

## Additional context

I maintain all of faceyspacey's work and wrote the original code-splitting SSR system. 
Universal SSR & architecture has been my enterprise focus for a long time. 
Inspecting this codebase and just had some questions. If you are open to some collaboration - i can try to find a time to help maintain next.js.

**Comment by timneutkens** [comment]
Ask away, I don't think it makes sense right now to change to another implementation as we're not using react-loadable. I forked it very early on and made many improvements to it.

**Comment by ScriptedAlchemy** [comment]
Sorry for generalizing, I know the code has been internalized. I just saw it was based on loadable, wasn't sure how much. I'll add you on twitter and will DM you once I've composed my thoughts further :)
