### ISSUE TITLE
router not defined with custom express server

### ISSUE THREAD

**Issue by ScottAgirs** [zeit/next.js#7582]
Ever since I added custom Express server to handle clean URLs,  `withRouter` HOC doesn't inject `props.router`.

Navigating FROM a page where `withRouter` is not used, TO a page `withRouter`, `router` prop is present, however, if the page is refreshed, the `router` prop is gone.

This is my current `server.js` setup for the clean urls.:

```js
   server.get('/c/learn/:courseSlug/:lessonSlug', (req, res) => {
      const actualPage = '/course/learn';
      const queryParams = {
        courseSlug: req.params.courseSlug,
        lessonSlug: req.params.lessonSlug
      };
      app.render(req, res, actualPage, queryParams);
    });
```

How to user `withRouter` and `Router` methods with clean URLs?

**Comment by timneutkens** [comment]
Please provide a full reproduction. withRouter is unrelated to the custom server api.

**Comment by ScottAgirs** [comment]
> Please provide a full reproduction. withRouter is unrelated to the custom server api.

Would love to! Can you please elaborate on _how_ and _what_ is necessary from me? (haven't done this before)

**Comment by timneutkens** [comment]
A full repository would work 🙏

**Comment by ScottAgirs** [comment]
https://bitbucket.org/ScottAgirs/ijstobe/src/master/

https://bitbucket.org/ScottAgirs/ijstofe/src/master/

- sorry, if a bit messy.

The Component at stake is `ijstofe/src/components/SingleCourseLearn.js`
just noticed that `ijstofe/src/components/SingleCourse.js` works fine with Router and/or withRouter.

**Comment by lfades** [comment]
@ScottAgirs You need to change the import from
```js
import { SingleCourseLearn } from '../../components/SingleCourseLearn';
```
to
```js
import SingleCourseLearn from '../../components/SingleCourseLearn';
```
The default export is the one with `withRouter()`.
btw if you're using `Now` then you don't need the custom server you currently have, instead you can have a [serverless build](https://github.com/zeit/next.js#serverless-deployment) and add custom routes to `now.json` like [here](https://github.com/zeit/next-site/blob/master/now.json).
