### ISSUE TITLE
IE 11 - Syntax error around lib/utils/getLocationOrigin.js 

### ISSUE THREAD

**Issue by Vadorequest** [zeit/next.js#7587]
# Bug report

## Describe the bug

My website https://staging.skema.the-funding-place.org/ is broken on IE. When I investigate the bug, I notice it's due to a `Syntax error` somewhere in the `main.js` file.

![image](https://user-images.githubusercontent.com/3807458/59563839-54b50680-903f-11e9-8dda-2ad3ab93a204.png)

It's very hard to figure where the problem comes from, but I think it's related to https://github.com/zeit/next.js/pull/1142/files#diff-50e3aa130a4f97a42ee2cf111c7b1d9dR59

The issue lies within ```return`${e}//${t}${r?":"+r:""}`}```, where the `//` is -dumbly- treated by IE11 as a comment for the rest of the line.

## To Reproduce

Use IE 11 (or older?) and go to https://staging.skema.the-funding-place.org, nothing should work properly, the page is rendered by the server, but all the frontend actions are dead, like the buttons and links that rely on javascript.

## System information

- OS: Multiple versions of Windows (7-10)
- Browser (if applies) IE 11, may happen on older version too
- Version of Next.js: `5.0.1-canary.16` < YUP, that's quite old, I may upgrade IF it provides a fix. My main issue with upgrading Next has been with webpack and the compilation/transpilation chain.

---

I wonder what fix I could use there. Also, I believe it's an edge case scenario, because I have other versions of the same app running "fine" like https://my-budget-advisor.com/epsi which uses the same Next.js version. I looked into the compiled source code `main.js` and couldn't find any reference to ```return`${e}//${t}${r?":"+r:""}`}```.

I looked at package version differences but there is nothing related to Next.js nor webpack between https://staging.skema.the-funding-place.org and https://my-budget-advisor.com/epsi

So, I don't have a clue what caused this, nor why the older version of `main.js` for https://my-budget-advisor.com/epsi is compiled differently than the newer version for https://staging.skema.the-funding-place.org

So, I'm looking for advices about how to resolve this issue, I'm not sure upgrading to a newer version of Next would fix anything (but would very likely bring a whole lot of new issues)

**Comment by Timer** [comment]
Hey! We have IE 11 syntax support in Next 8+. Can you please upgrade to the latest version?

The problem here isn't the `//`, it's that a string literal has been defined using a backtick (`)!

**Comment by Vadorequest** [comment]
Upgrading from 5 to 8 isn't trivial. Do you know which commit fixed it?

**Comment by Timer** [comment]
I'm not aware which commit would've fixed this specific problem, sorry! You may need to adjust this file by hand in `node_modules`.

**Comment by Vadorequest** [comment]
Alright, thanks for your time and help though!
