### ISSUE TITLE
Help: TypeError: Cannot read property 'passport' of undefined on production build

### ISSUE THREAD

**Issue by apardo04** [zeit/next.js#7593]
# Bug report

## Describe the bug

Everything runs fine on development. The issue happens on production.

'npm run build' executes without issues, but once I 'npm run start' and visit the page (localhost:3000), I get an "Internal Server Error" on the DOM and my terminal says "TypeError: Cannot read property 'passport' of undefined".

The terminal is pretty much pointing at this being the issue inside _app.js:
```
    if (ctx.req && ctx.req.session.passport.user) {
      pageProps.user = ctx.req.session.passport.user;
    }
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I have config and .env file's required to connect to auth0 and my personal DB, so this may not work. Maybe someone can still help?

1. Go to My project's repo: https://github.com/apardo04/stock-market-react-app
2. clone it
3. npm install and go to directory
4. npm run build
5. npm run start
6. Go to localhost:3000
7. See error

## Expected behavior

Site runs with no issues

## Screenshots

Error I get on terminal:
https://imgur.com/a/LwyGUff

## System information

- OS: Both Windows 10 AND ubuntu 18.04
- Browser (if applies): All of them
- Version of Next.js: "8.1.0"

**Comment by robertistok** [comment]
@apardo04 
After cloning your project and trying to reproduce the bug, I think that the problem might come from the `session` object not being available on the `req`. 

If you add another check to the if statement you've linked, like the line below, it works:
`ctx.req && ctx.req.session && ctx.req.session.passport`

Does anyone have another thought?

**Comment by apardo04** [comment]
@robertistok 
Great! I added your code plus a try catch as well:
`try{
      if (ctx.req && ctx.req.session && ctx.req.session.passport) {
        pageProps.user = ctx.req.session.passport.user;
      }
    } catch(error) {
      console.log(error + " = error from _app get initial props")
    }`

This allows me to build and start the production version.

The new issue now is that when I go to /login to login, I get a nextjs rendered 404(meaning I see my header with a 404 body) instead of going to auth0 login lock portal.

I've tried messing with my routes, but I don't think thats the issue. Maybe I may need to do something with the user state in componentDidMount in _app.js?

**Comment by robertistok** [comment]
@apardo04 
That's happening because you don't have the `/login` page in the `pages` directory.
Read [this one]( https://github.com/zeit/next.js/#routing) in order to find out how routing works in nextjs.

**Comment by apardo04** [comment]
@robertistok Thanks again for the reply,

The problem is that I don't have or need a /pages/login.js, since it's supposed to redirect to auth0 login page. Again this is working perfectly fine on dev. Here is an example of a site that uses the auth0 lock login ( https://www.indianmotorcycle.com/en-us/ ).

If it helps this is the tutorial I used to setup auth0: https://auth0.com/blog/next-js-authentication-tutorial/

**Comment by apardo04** [comment]
OK, so to fix this new issue I had to run:

    "start2": "cross-env NODE_ENV=production node server.js"

instead of:

    "start": "next start -p 3000",

This allowed me to go to /login and work normally.
