### ISSUE TITLE
[Types - minor] - index signature on NextPageContext necessary

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [zeit/next.js#7601]
# Bug report

## Describe the bug

[This line in your example](https://github.com/zeit/next.js/blob/canary/examples/with-redux/lib/with-redux-store.js#L28) causes a TS error because [NextPageContext](https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/utils.ts#L73) doesn't have an index signature.

```
TS2339: Property 'reduxStore' does not exist on type 'NextPageContext'.
```

Unless the API has changed lately and you wouldn't recommend adding arbitrary data to the context any more, this could be easily resolved by simply adding `[key: string]: any;`.

**Comment by Janpot** [comment]
https://spectrum.chat/next-js/general/how-would-you-type-this~662bfdb5-b174-4503-94a6-e6ad83bca204

**Comment by s-h-a-d-o-w** [comment]
Oh, huh. Thanks!
