### ISSUE TITLE
Own tsconfig for custom server in 8.1.1 with internal typescript support

### ISSUE THREAD

**Issue by makarov-foot** [zeit/next.js#7613]
# Question about Next.js

After 8.1.1-*canary release there's own https://github.com/zeit/next.js/#typescript typescript support. How to provide node custom tsconfig ?

I have been using ts-node package:
node --require ts-node/register ./server/server.ts

How is it implemented for custom servers now?

**Comment by timneutkens** [comment]
Please follow the issue template.
