### ISSUE TITLE
API routes are broken in development for `serverless` target

### ISSUE THREAD

**Issue by kevva** [zeit/next.js#7617]
When creating API routes introduced in #7296 using the `serverless` target, they break in development because of [this](https://github.com/zeit/next.js/blob/canary/packages/next-server/server/next-server.ts#L328) line where it tries to resolve the files in the `serverless` folder which doesn't exist in development. The solution would be to add a check for `this.renderOpts.dev` as we do [here](https://github.com/zeit/next.js/blob/canary/packages/next-server/server/next-server.ts#L443).

You can reproduce this by doing the following:

1. Create a API route in `pages/api`
2. Run `now dev`
3. Try accessing the route
4. There should be an error

**Comment by lfades** [comment]
@huv1k Will your [PR](https://github.com/zeit/next.js/pull/7619) fix this ?

**Comment by huv1k** [comment]
@lfades yes :)
