### ISSUE TITLE
IE 11 "Expected Identifier" error in commons chunk

### ISSUE THREAD

**Issue by mherodev** [zeit/next.js#7625]
# Bug report

Our production build of our app breaks in IE 11 due to a syntax error:

![image](https://user-images.githubusercontent.com/1099139/59884646-ce196580-936d-11e9-9030-4363cd963cae.png)

## Describe the bug

Tracking down this code leads to the first instance of the spread operator in a function call, i.e.

![image](https://user-images.githubusercontent.com/1099139/59884740-0e78e380-936e-11e9-9562-0f5731f35424.png)

Looking into it, it appears IE 11 doesn't support any kind of spread operations:

![image](https://user-images.githubusercontent.com/1099139/59884765-205a8680-936e-11e9-8d25-19335de7d27d.png)

That said, no matter which `targets` values I pass to `['next/babel', { 'preset-env': ... }]`, the build output for next continues to contain these spread operators.

Tracking this spread operator down further, it looks like its coming from the npm `debug` package, i.e. https://github.com/visionmedia/debug/blob/master/src/common.js

I imagine this should be transpiled away normally. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install `debug` into your favorite Next.js project and import it into enough pages for it to end up in commons (although you can just check against a specific page's transpile), i.e.
```bash
npm i debug --save
```
```js
import debug from 'debug';
```

2. Build project for a production deployment, i.e.
```bash
npm run build # next build
```

3. Search `.next/static/chunks/commons.blah.js` or `.next/static/blah/pages/myPage.js` for `...` (you can verify you're in the right file by searching for `.skips` first which is code present in the `debug` package that doesn't change when transpiled).

## Expected behavior

All spread operators should be transpiled to something legacy browser compatible.

## System information

- OS: macOS
- Version of Next.js: Appears both in v7 and v8

## Additional Comments

I've tried various babel configs; tempted to manually transpile the transpiled code one more time using a plugin to specifically resolve this (haven't had luck reprocessing with `preset-env`... it seems to do too much).

Here's an example:

```js
module.exports = {
  presets: [['next/babel', { 'preset-env': { targets: { ie: '11' }}}]],
};
```

**Comment by lineape** [comment]
By default, babel doesn't transpile node_modules.

A possible solution would be to use [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules).

I've had to do this on my app, for debug specifically.

**Comment by Timer** [comment]
☝️ you need to compile specific `node_modules` if they use too new of a syntax.

**Comment by mherodev** [comment]
Thanks guys! I'll give this a shot.
