### ISSUE TITLE
redux persist is creating in persist in localstorage

### ISSUE THREAD

**Issue by LogeswariV** [zeit/next.js#7644]
# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.

Iam trying to add redux persit in nextjs project.But it is not creating persist in local Storage.It is also not giving any error.

//store.js

import { createStore, applyMiddleware, compose } from 'redux';
import nextConnectRedux from 'next-connect-redux'
import thunk from 'redux-thunk';
import reducers from './reducers';
import {persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage';
import { composeWithDevTools } from 'redux-devtools-extension';
// const storage = require('redux-persist/lib/storage').default;
console.log(storage,'storage')
const persistConfig = {
   key: 'root',
   storage,
 }
 console.log(persistConfig,'persistConfig')
const persistedReducer = persistReducer(persistConfig, reducers)
const initialState = {};

const middleware = [thunk];
//

const store = () => { return createStore(persistedReducer,
  initialState,
  composeWithDevTools(
   applyMiddleware(...middleware),

   ));
  }
const nextConnect = nextConnectRedux(store);

export default nextConnect;

//index.js

import React,{ Component } from 'react'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react';
import { persistStore } from 'redux-persist';
import nextConnect from '../store';
import Route from '../routes'

class App extends Component {
 render () {
    const persistor = persistStore(nextConnect);
    return (
     
        <Provider store={store}>
        <PersistGate loading={<Loading visibility='visible' />} persistor={persistor}>
          <Route/>
        </PersistGate>
        </Provider>
     
    )
  }
}
export default App;

I have created store.js in  project directory and index.js inside container folder in the  project directory.

**Comment by timneutkens** [comment]
As per the issue template I'm going to close this:

> GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on spectrum.chat/next-js.

You'll probably want to have a look at https://github.com/zeit/next.js/tree/canary/examples/with-redux-persist

**Comment by LogeswariV** [comment]
Here we are using reducers and actions in separate folders and importing in the store.
And we are not having the file with-redux-store.js file also
How can we solve this issue without this file

**Comment by timneutkens** [comment]
Feel free to post questions on https://spectrum.chat/next-js
