### ISSUE TITLE
Cant start "dev" server with custom distDir in next.config

### ISSUE THREAD

**Issue by nikolaykrashnikov** [zeit/next.js#7645]
# bug report

## **../** in next.config

if next.config.js have: 
`module.exports = { distDir: "../anyPath" };`
we hawe:
`Error: Cannot find module 'core-js/library/fn/object/define-property'`

## To Reproduce
add
`module.exports = { distDir: "../anyPath" };`
to next.config.js
**"next": "^8.1.0"**

**Comment by HaNdTriX** [comment]
The `distDir` needs to be inside your projects root directory otherwise node.js is not able to locate your 
`node_modules` directory.
