### ISSUE TITLE
Add next build [--output directory] option ?

### ISSUE THREAD

**Issue by zapkub** [zeit/next.js#765]
Hi,

I do some custom server load with babel,
so before goto production it need to be compiled to standard javascript in another build folder and it should include .next folder.

I wonder if this option may helpful ?

This is how I manage it now

```
#build.sh
#!/usr/bin/env bash

npm run clean

# next build ./src
npm run build 

cp -r ./src/.next ./build/.next
npm run build-server
```

**Comment by nkzawa** [comment]
I wonder why you'd like to move the `.next` directory since you wouldn't use it from custom server. Can you elaborate why you need to do that ?

**Comment by arunoda** [comment]
Also we need to have `next.config.js` relative to the app dir. It's kind a confusing to move it to another place as well.

I suppose current way is better.

**Comment by zapkub** [comment]
@nkzawa I put next inside my project src folder `next ./src/` with KeystoneJS and it will be compiled  and ship my build folder for deployment.

Is this what it suppose to be ?

Anyway I understand your point, will figure how to manage it properly.

Thanks

**Comment by timneutkens** [comment]
@zapkub seems like your question is answered, I'm closing this for now. Feel free to re-open if needed ❤️
