### ISSUE TITLE
[2.0-beta.17] HMR bundle has errors: exports is not allowed in EcmaScript module

### ISSUE THREAD

**Issue by Zaiban** [zeit/next.js#766]
Got the following error after updating to beta 17:

![sieppaa](https://cloud.githubusercontent.com/assets/9568791/21955517/57fa69fc-da75-11e6-9aaf-51960af73cb8.JPG)

Any clue to what might cause this?

**Comment by nkzawa** [comment]
It looks this warning was added on `webpack@v2.2.0-rc.4` which we introduced on beta 17.

Actually, it seems this is a bug of webpack since these modules (`lodash-es/_cloneBuffer` etc) don't use `exports`, but just check existence of it like `typeof exports == 'object' && exports`.

**Comment by nkzawa** [comment]
This is it. https://github.com/webpack/webpack/issues/3917

**Comment by nkzawa** [comment]
Anyway, I don't think `lodash-es` properly works since you can't use it on Server Side (no webpack compilation) for now.

**Comment by arunoda** [comment]
@nkzawa what's our plan for this?
If they didn't fix this sooner, are we going to revert back to the previous version? (Bring back our dynamic entry plugin stuff?)

**Comment by nkzawa** [comment]
I think we don't have to revert since `import/export` statements don't work on server anyway.

**Comment by arunoda** [comment]
@Zaiban FYI: You need to the normal version `lodash` instead of `lodash-es`

**Comment by Zaiban** [comment]
Actually I'm already using the normal lodash. Maybe this comes from a dependency? Need to do some digging.

**Comment by Zaiban** [comment]
Well grepping for lodash es reveals that redux-form, react-redux and babel-plugin-lodash all have lodash-es as a dependency. Tried to disable the babel plugin already but no effect. And getting rid of redux-form and react-redux is not really a valid option at this point :/

**Comment by arunoda** [comment]
@Zaiban That's a valid question.
I think we need to make issues for different upstream libraries for this.

**Comment by arunoda** [comment]
@nkzawa about the `lodash-es`.
I think it works fine for us.
This is how people use it.

They use it with the `module` target in `package.json`.
See how [react-redux](https://github.com/reactjs/react-redux/blob/master/package.json#L6) does it.

So, it only picks by webpack. For node, it still uses the `main` target and it works fine.
I didn't test this, but it should work fine.

**Comment by nkzawa** [comment]
Updated webpack https://github.com/zeit/next.js/commit/da8395883c52588f572c0515ea208b5a20d773e8
