### ISSUE TITLE
Bundle so huge

### ISSUE THREAD

**Issue by markolofsen** [zeit/next.js#7711]
After connecting over 100 components, the weight of my bundle is large (around 10 Mb). All components connected with next-dynamic. But somehow my bundle is really large. How possible to resolve my problem? I want to use differents components in one page with dependence of http request.

**Comment by ijjk** [comment]
Hi, this sounds like a question for our [Spectrum community](https://spectrum.chat/next-js?tab=posts). If you could post it there and if possible include a link to a repo with the problem you are encountering myself or someone from the community would be happy to take a look.
