### ISSUE TITLE
React "validateDOMNesting" warning appears to break component

### ISSUE THREAD

**Issue by richsilv** [zeit/next.js#773]
Thanks for all the fantastic work on this great project.  However, I think I've identified a bug.

Example repo:

https://github.com/richsilv/next-error-example

1. `npm i`
2.  `npm run dev` to observe the `validateDOMNesting` warning in the console and the fact that the button subsequently doesn't work when served by Next.
3. `npm run build-non-next` to browserify the same component, and then open the file `non-next.html` to see it working, despite the same warning.

Browsers: Chrome and Firefox running on Ubuntu

I know the warning is there for a reason, and the best resolution is to write something that compiles to valid HTML, but it was very surprising to me to find that the warning was also breaking my component.  This is particularly the case as these warnings can often be the result of imported components which work perfectly in isolation, but throw warnings when nested in your JSX.

The most logical explanation is that the SSR markup is being amended by the browser to conform to HTML spec, and this leads to a problem when it attempts to transition to the client-generated markup, which it expects to be the same.

**Comment by nkzawa** [comment]
It seems this is the issue of `React` since it occurs with no next.js if you do SSR.

**Comment by timneutkens** [comment]
@richsilv could you submit an issue to the React repo? That would be great ❤️
