### ISSUE TITLE
Canary branch - Cannot find module 'next-server/types'

### ISSUE THREAD

**Issue by TidyIQ** [zeit/next.js#7738]
Upgraded to canary branch (version 8.1.1-canary.64) and ran typescript check (tsc --noEmit). Returned the following error:

```
node_modules/next-server/dist/server/render.d.ts:7:28 - error TS2307: Cannot find module 'next-server/types'.

7 import { PageConfig } from 'next-server/types';
                             ~~~~~~~~~~~~~~~~~~~
```

**Comment by TidyIQ** [comment]
When I look at `node_modules/next-server/types/index.d.ts` it has:

[screenshot](https://i.imgur.com/zgoDSZW.png)
```
import { PageConfig } from 'next-server/types'
```
This shows an error as there is no `next-server/types` folder: [screenshot](https://i.imgur.com/yDncGDx.png)

**Comment by ijjk** [comment]
Hi, thanks for trying out the canary branch. It looks like the types weren't included in the release. A PR addressing this has been submitted [here](https://github.com/zeit/next.js/pull/7740)
