### ISSUE TITLE
How to handle hashes in URL?

### ISSUE THREAD

**Issue by astanciu** [zeit/next.js#779]
A lot of OAuth based callback urls will take the form of:
`http://site.com/login#state=123&code=123`

Is there any way to access that hash? Would be great if `props.url` had a `.hash` property (alongside `.query`)

Or is there an easier way to get this?

**Comment by timneutkens** [comment]
@astanciu there is one major problem here. Fragments (`#`) are unfortunately never sent to the server. So if you'd do a refresh you would lose the state. There is currently no property available to get the hash. Though you could do something like this:

```
  static getInitialProps ({ req }) {
    let hash = ''
    if(!req)
      hash = window.location.hash
    }

    return { hash }
  }
```

Then again, this will not get the hash when server side rendering.

@arunoda can you verify this? `getInitialProps` is only called once if I remember correctly, either server or client. So we can't implement this correctly.

**Comment by frol** [comment]
Browsers, by design, don't include URL hash in HTTP requests, so it is simply impossible to handle on the server side. I would just use `componentDidMount` instead of `getInitialProps`.

**Comment by timneutkens** [comment]
@frol you're right, using `componentDidMount` is way better. Since it is called on frontend render, thanks ❤️
