### ISSUE TITLE
Document that runtime configuration can't be used with prerendering

### ISSUE THREAD

**Issue by ivangabriele** [zeit/next.js#7827]
# Bug report

## Describe the bug

When I set the value of a `publicRuntimeConfig` property from an environment variable, it is `undefined` when buiding and starting a production bundle. It worked fine with Next.js v8.

## To Reproduce

**package.json**

```
  "scripts": {
    "build": "next build",
    "dev": "TEST_ENV='a value' next",
    "start": "TEST_ENV='a value' next start"
  },
  "dependencies": {
    "next": "^9.0.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0"
  }
```

**.babelrc**

```
{
    "presets": [
        "next/babel"
    ]
}
```

**next.config.js**

```
module.exports = {
  publicRuntimeConfig: {
    TEST_ENV: process.env.TEST_ENV
  }
}
```

**pages/index.js**

```
import getConfig from "next/config";

const TEST_ENV = getConfig().publicRuntimeConfig.TEST_ENV;

export default () => <div>{`TEST_ENV=${TEST_ENV}`}</div>;
```

Then run:

```
yarn build && yarn start
```

## Expected behavior

When running a `yarn build && yarn start`, the `TEST_ENV` value should appear in the index page as it does when downgrading to the version `8.1.0` or when running `yarn dev`.

**Comment by Timer** [comment]
Hi! Your application was probably automatically prerendered: https://github.com/zeit/next.js#automatic-prerendering.

In most cases, you do not need runtime configuration -- runtime configuration causes slower applications by always requiring a SSR and not allowing static optimization.

Please checkout [build time configuration](https://github.com/zeit/next.js#build-time-configuration).

If you _must_ use runtime configuration, you'll need to add a noop `getInitialProps` to the page to ensure it's server side rendered.

**Comment by ivangabriele** [comment]
Actually, in my case I use Docker with Docker Compose to setup my e2e tests, which seems a quite common way to setup e2e tests on a CI.

The best way to pass environment variables from the machine to the container when building the (client, server, db, etc) containers is to use [the building `args`](https://github.com/docker/compose/issues/1837#issuecomment-316896858). However the `build` part of a Docker Compose file can't access the network values yet (since it's only building and not running). So there is no other way to have the exact same bundle able to run withing both an e2e environment and a production environment without using the runtime config.

**Comment by Timer** [comment]
@ivangabriele Next.js produces identical output for successive builts, so this point is mostly moot.

> If you must use runtime configuration, you'll need to add a noop getInitialProps to the page to ensure it's server-side rendered.

**Comment by ivangabriele** [comment]
I understand but why did it work in Next.js v8 ?

**Comment by Timer** [comment]
@ivangabriele Prerendering [is a new feature in Next.js 9](https://github.com/zeit/next.js#automatic-prerendering). It has different performance characteristics, and is the reason it was released behind a major version.

**Comment by ivangabriele** [comment]
@Timer Just another note as I think about it: adding a warning while building in dev mode could also be useful, no? The fact that it "works" without any error in dev mode could be misleading.

**Comment by Timer** [comment]
Yes, this is a very inconvenient bug @ivangabriele. Will open an issue to fix.

**Comment by ivangabriele** [comment]
Thank you very much :)

**Comment by azizhk** [comment]
Is there any way we can disable this "Check if can be pre-rendered"?
It's only being used to show a symbol before the bundle right?

**Comment by timneutkens** [comment]
> It's only being used to show a symbol before the bundle right?

@azizhk I'm not sure what you're asking exactly. But you'll want to read this: https://github.com/zeit/next.js#automatic-prerendering

and https://nextjs.org/blog/next-9#automatic-static-optimization

**Comment by azizhk** [comment]
So for those who have a custom _app with custom getInitialProps, We can never have automatic pre-rendering right? So why even check for it? I should be able to specify that I don't want pre-rendering, I  want a faster build.

**Comment by timneutkens** [comment]
It'll take at most 1 second of the build considering we only require the code and don't execute any components if not prerendering. Even then it does more, like check if you are exporting a React component to make sure you're not deoptimizing by having other files inside your pages directory.
