### ISSUE TITLE
[Next 9] Internal server error when api request ends with /

### ISSUE THREAD

**Issue by sadmone** [zeit/next.js#7845]
# Internal server error when api url request ends with /

## Describe the bug
When you add / at the end of url, you get a internal server error - it cant find index page even when index page exists.

BTW I have only tested this with api routes, not the normal ones.

## To Reproduce
1. Go to https://github.com/sadmone/next-issue and clone the repo
2. Install all dependencies with **npm install**
3. Start the server with **npm run dev**
4. Go to localhost:3000/api/post - nothing happens
5. Change localhost:3000/api/post to localhost:3000/api/post/
6. See internal server error

## Expected behavior

It should find the index page, even when url ends with /, not return a internal server error

## System information

- OS: Windows
- Browser: chrome
- Version of Next.js: 9.0.0

**Comment by ijjk** [comment]
Hi, API routes support have been updated in the latest canary you can try it with `yarn add next@canary` or wait for v9.0.1. Also, routes are currently expected to return a 404 when they contain a trailing slash. This behavior is being discussed.

**Comment by joseph1125** [comment]
The internal server error is not gone but reappears after it exhausts all of the memory of my instance
