### ISSUE TITLE
Animation won't run using JSX inline styles

### ISSUE THREAD

**Issue by mallendeo** [zeit/next.js#785]
<img width="325" alt="screen shot 2017-01-15 at 11 32 41 pm" src="https://cloud.githubusercontent.com/assets/1578018/21969206/173048ea-db7b-11e6-8131-04ca830d2218.png">

The animation won't run since a css selector/property [can't start with a number](http://stackoverflow.com/a/449000/1625448).

**Comment by nkzawa** [comment]
What version of next.js do you use ? It looks `styled-jsx` is already fixed https://github.com/zeit/styled-jsx/commit/5377347e877aeb94ca74a8935922d6aa56ed4fc7.

**Comment by mallendeo** [comment]
@nkzawa Just upgraded to 2.0.0-beta.17
After the upgrade, this is the output:
<img width="323" alt="screen shot 2017-01-16 at 9 55 12 am" src="https://cloud.githubusercontent.com/assets/1578018/21983970/7c836c52-dbd2-11e6-8fc7-5df7b3bb0001.png">

Note that `forwards` also gets prefixed.

LoadingIndicator.js
```js
export default ({ active }) =>
  <div className={`loadingIndicator ${active ? 'active' : ''}`}>
    {
      [
        '#80DEEA',
        '#26C6DA',
        '#00ACC1',
        '#00838F',
        '#006064'
      ].map((color, i) =>
        <div
          style={{ backgroundColor: color, animationDelay: `-${1 - i / 20}s` }}
          key={`stripe${i}`}
          className='stripe'
        />
      )
    }
    <style jsx>{`
      .loadingIndicator,
      .stripe {
        left: 0;
        bottom: 0;
        width: 100%;
        position: absolute;
      }
      .loadingIndicator {
        color: #333;
        height: .2rem;
        opacity: 0;
        transition: opacity 1s 1s ease;
      }
      .stripe {
        height: 100%;
        animation: loading 1s ease infinite forwards;
      }
      .loadingIndicator.active {
        opacity: 1;
        transition-delay: 0s;
      }
      .loadingIndicator.active .stripe {
        animation: loading 1s ease infinite forwards;
      }
      @keyframes loading {
        0% {
          transform: scaleX(0);
          opacity: 1;
        }
        80% {
          transform: scaleX(100%);
        }
        100% {
          opacity: 0;
        }
      }
    `}</style>
  </div>
```

**Comment by nkzawa** [comment]
@mallendeo thanks for your feedback. I created the issue https://github.com/zeit/styled-jsx/issues/77.
I think you can define animations using non-shorthand properties like `animation-name` instead of `animation` for now.

**Comment by mallendeo** [comment]
@nkzawa Thanks!

**Comment by timneutkens** [comment]
This will be fixed in the next beta release.
