### ISSUE TITLE
hls.js fails to play in Next 9.0.0

### ISSUE THREAD

**Issue by justsee** [zeit/next.js#7873]
# Bug report

## Describe the bug

A video player using [hls.js](https://github.com/video-dev/hls.js) fails to play, throwing the following browser error when running [through this code path](https://github.com/video-dev/hls.js/blob/master/src/utils/get-self-scope.js):

```
adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:544 Uncaught ReferenceError: window is not defined
    at Object.getSelfScope (adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:544)
    at Object../src/utils/logger.js (adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:487)
    at __webpack_require__ (adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:20)
    at Object../src/crypt/decrypter.js (adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:3869)
    at __webpack_require__ (adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:20)
    at Object../src/demux/demuxer-inline.js (adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:679)
    at __webpack_require__ (adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:20)
    at Object../src/demux/demuxer-worker.js (adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:83)
    at __webpack_require__ (adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:20)
    at webpackBootstrapFunc (adaaa4b8-5111-4e0e-bd0f-1e6b09b7a320:72)
```

## To Reproduce

The issue first appears in the following commit: https://github.com/zeit/next.js/pull/7606/commits/c0e07ca2d314ea865f324cc658a9927cdf7cae80

## Expected behavior

The hls.js player should play without error.

**Comment by musps** [comment]
Hi,

Have you tried calling your script within `react/useEffect` ?

**Comment by justsee** [comment]
It appears like https://github.com/zeit/next.js/commit/c0e07ca2d314ea865f324cc658a9927cdf7cae80 unmasks an underlying webpack bug affecting `webworkers` and `window` usage discussed in:

* https://github.com/webpack/webpack/issues/6525
* https://github.com/webpack/webpack/issues/6642

The discussed workarounds (variations of setting [webpack's globalObject](https://webpack.js.org/configuration/output/#outputglobalobject)) such as:

```
output: {
  ...,
  globalObject: 'typeof self !== "undefined" ? self : this',
}
```
don't appear to work when modifying a local version of Next.js' [webpack-config.ts](https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack-config.ts#L335).

The above triggers the same `jsonpArray` errors outlined in https://github.com/webpack/webpack/issues/6525#issuecomment-452894839, and while placing parentheses around the statement resolves that error, the issue still exists.

My limited knowledge of webpack and next.js internals doesn't get me any further than this. I assume setting globalObject ensures `window` resolves to it in the case of `webworkers` but that appears to be a misconception on my part.

I see webpack handles various targets including `node`, `web` and `webworkers` but that next.js just sets target to either `node` or `web` depending on `isServer` and at this point realise I don't have the right knowledge to properly reason about the underlying issue at this stage.

**Comment by txantslusam** [comment]
Can confirm this bug. I get the same error with nextjs version `9.0.1` and hls.js version `0.12.4`.

**Comment by justsee** [comment]
For now I've patched 9.0.0 in the affected project:

1. fork and clone next.js repo
1. check out v9.0.0: `git checkout v9.0.0`
1. modify the webpack config file `./packages/next/build/webpack-config.ts` to set `window` back to `undefined` instead of `object`.
1. `npm pack` next within `packages/next`
1. copy to dependent project and reference it in package.json using a file reference: e.g. `"next": "file:next-9.0.0.tgz",`

**Comment by beshkenadze** [comment]
So, I fix it for v9.0.2 using `globalObject= 'typeof self !== "object" ? self : this';` instead of `globalObject= 'typeof self !== "undefined" ? self : this';`

**Comment by ifier** [comment]
I didn't get how you fixed it.

```
next: 9.0.3
hls.js: 0.12.4
```

And the same issue - `window is not defined`.

A part of my code:
```
  componentDidMount() {
    const { id } = this.props;

    this.getPlayback(id);
  }

  getPlayback = async id => {
    const urlCallback = await getVODPlaybackStream(id)
      .then(({ data }) => data.playerUrlCallback)
      .catch(({ response }) => {
        const { status } = response.data;

        if (status === 401) {
          auth().then(() => {
            this.getPlayback(id);
          });
        }
      });

    const hlsurl = await getHlsUrlByPlaybackUrl(urlCallback).then(
      ({ data }) => {
        const { hlsUrl } = data;

        return hlsUrl;
      }
    );

    if (Hls.isSupported()) {
      console.log(window);
      const video = document.getElementById('video');
      const hls = new Hls();

      hls.attachMedia(video);
      hls.on(Hls.Events.MEDIA_ATTACHED, () => {
        hls.loadSource(hlsurl);
        hls.on(Hls.Events.MANIFEST_PARSED, (event, data) => {
          // console.log("manifest loaded, found " + data.levels.length + " quality level");
        });
      });
    }
  };
```

next.config.js:
```
const config = {
  webpack(config) {
    config.output.globalObject = 'typeof self !== "object" ? self : this';

    return config;
  }
};

module.exports = config;
```

**Comment by cleverboy32** [comment]
how fixed this

**Comment by zallarak** [comment]
This still seems broken.

**Comment by jcohenho** [comment]
@Timer this is still broken - I'm getting `window is not defined` after using latest versions of NextJS, hls.js, and configuring `next.config.js` with  `config.output.globalObject = 'typeof self !== "object" ? self : this';`
