### ISSUE TITLE
[Next 9.0.0] Automatic Static Optimisation can't work with Redux

### ISSUE THREAD

**Issue by notiles** [zeit/next.js#7878]
# Feature request
Use Automatic Static Optimisation with Redux

## Is your feature request related to a problem? Please describe.
Based on this example: https://github.com/zeit/next.js/tree/canary/examples/with-redux

If we want to use Automatic Static Optimisation, we have to remove every getInitialProps, but Redux use getInitialProps in 'withReduxStore' classe used in App.js so it's impossible to use this really cool new feature with Redux.

**Comment by Timer** [comment]
Hi, this is a question better suited for our [Spectrum](https://spectrum.chat/next-js). You can accomplish this if you remove Redux usage from `getInitialProps`.
