### ISSUE TITLE
[v9 regression] react-ssr-prepass isnt bundled in serverless production and deployment fails, but works locally

### ISSUE THREAD

**Issue by iamstarkov** [zeit/next.js#7889]
# Bug report

## Describe the bug

Severe as in app doesnt start in prod.

react-ssr-prepass dependent app:
* (next.js@8) works fine in dev and prod
* (next.js@9) works fine in dev, but **fails in prod**

It fails with the following error:

```stdout
START RequestId: c1360c24-825d-4620-b70d-95a61da26a78 Version: $LATEST
2019-07-10T23:37:47.210Z	undefined	ERROR	Uncaught Exception	{
	"errorType":"Runtime.ImportModuleError",
	"errorMessage":"Error: Cannot find module 'react-ssr-prepass'",
	"stack":[
"Runtime.ImportModuleError: Error: Cannot find module 'react-ssr-prepass'",
"    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
"    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
"    at Object.<anonymous> (/var/runtime/index.js:36:30)",
"    at Module._compile (internal/modules/cjs/loader.js:701:30)",
"    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)",
"    at Module.load (internal/modules/cjs/loader.js:600:32)",
"    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)",
"    at Function.Module._load (internal/modules/cjs/loader.js:531:3)",
"    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)",
"    at startup (internal/bootstrap/node.js:283:19)"]}
END RequestId: c1360c24-825d-4620-b70d-95a61da26a78
REPORT RequestId: c1360c24-825d-4620-b70d-95a61da26a78	Duration: 239.19 ms	Billed Duration: 300 ms 	Memory Size: 3008 MB	Max Memory Used: 47 MB	
Unknown application error occurred
Runtime.ImportModuleError
```

Important to note: app [explicitly depends on `react-ssr-prepass`](https://github.com/iamstarkov/topics-manager/blob/master/package.json#L26)

## To Reproduce

* Working v8 demo https://topics-manager.now.sh/ (master)
* Failing v9 demo https://topics-manager-phz67x2ki.now.sh/ (only one bump commit ahead of master)
* Related PR https://github.com/iamstarkov/topics-manager/pull/93

You need `now` installed globally

```shell
npm i -g now # if you dont have now installed globally
git clone git@github.com:iamstarkov/topics-manager.git
cd topics-manager
git checkout renovate/major-nextjs-monorepo
yarn
cp .env.example .env
yarn dev # dev works
now deploy # in prod it wont start
```

## Expected behavior

Perhaps, should not fail in prod as far as it doesnt fail locally.

## System information

- OS: probably n/a, but macOS Mojave 10.14.5 (18F132)
- Version of Next.js: v8 vs v9

## Additional context

I see a lot of [back and forth issues/pull-requests regarding `react-ssr-prepass`](https://github.com/zeit/next.js/issues?utf8=%E2%9C%93&q=react-ssr-prepass+). Maybe some of them caused this problem. 

I cant replicate error locally, because next.js is set to `serverless` mode. Furthermore, i use `now dev` and didnt see `local prod` mode of it too. Is there any documentation on how can one debug production-only problems like this?

Maybe, i lack context and some documentation. If someone can help with those, then perhaps i can try try to fix this issue on my own

**Comment by sync** [comment]
same issues here, if it helps:
- reproduction: https://github.com/sync/next-level/pull/11
- deploy: https://next-level-m16h7hhqi.now.sh/
- logs: https://zeit.co/dblechoc/next-level/m16h7hhqi

**Comment by iamstarkov** [comment]
9.0.2 fixed it 👍

**Comment by tmilar** [comment]
Same issue, I could reproduce it following tutorial steps here https://nextjs.org/learn/excel/automatic-prerendering/serverless , by running `npm run build` locally

**Comment by Timer** [comment]
@tmilar please upgrade your Next.js version

**Comment by tmilar** [comment]
> @tmilar please upgrade your Next.js version

Sorry @Timer , forgot to mention I'm using lastets next version `9.0.2`
Node version `10.16.0`
Npm version `6.9.0`
Windows 10, if it matters.

**Comment by Timer** [comment]
Can you try `canary` @tmilar?

**Comment by tmilar** [comment]
@Timer , using canary (`9.0.3-canary.5`) the error is no longer reproducible. Now I get this warning though:
```
Compiled with warnings.

./node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in 'C:\tmilar\doup\doup-web-next\node_modules\node-fetch\lib'
```

**Comment by enzoferey** [comment]
I'm facing the same issue.

**Comment by Timer** [comment]
The warning can be ignored.

**Comment by andrey-semin** [comment]
Facing same issue on `9.0.3`
