### ISSUE TITLE
static content/js bundles not working with the hapi server example

### ISSUE THREAD

**Issue by mattapperson** [zeit/next.js#794]
Environment: Next beta 17, node v6.0.0, yarn 0.18.1

Expected result:
The page served serves up all static assets and the JS bundle loads into the SSR rendered page.

Actual result:
The SSR page loads, but times out on loading any static assets I add or even the js bundles for the page. No errors in the console output.

**Comment by impronunciable** [comment]
Confirmed, looking at it right now.

**Comment by mattapperson** [comment]
fixed
