### ISSUE TITLE
next export broken due to EEXIST: file already exists

### ISSUE THREAD

**Issue by mmiszy** [zeit/next.js#7964]
# Bug report

## Describe the bug

I updated my app from Next 8 to Next 9.
Unfortunately now when I try `next export`, it doesn't work any more. It exits with the following output:

```
> using build directory: /Users/mmiszy/htdocs/my-app/.next
  copying "static" directory
  copying "static build" directory
  launching 7 threads with concurrency of 10 per thread
  copying "public" directory
{ [Error: EEXIST: file already exists, copyfile '/Users/mmiszy/htdocs/my-app/public/static/style.css' -> '/Users/mmiszy/htdocs/my-app/public/static/style.css']
  errno: -17,
  code: 'EEXIST',
  syscall: 'copyfile',
  path:
   '/Users/mmiszy/htdocs/my-app/public/static/style.css',
  dest:
   '/Users/mmiszy/htdocs/my-app/public/static/style.css' }
```

or:

```
> using build directory: /Users/mmiszy/htdocs/my-app/.next
  copying "static" directory
  copying "static build" directory
  launching 7 threads with concurrency of 10 per thread
  copying "public" directory
{ [Error: EEXIST: file already exists, copyfile '/Users/mmiszy/htdocs/my-app/public/service-worker.js' -> '/Users/mmiszy/htdocs/my-app/public/service-worker.js']
  errno: -17,
  code: 'EEXIST',
  syscall: 'copyfile',
  path:
   '/Users/mmiszy/htdocs/my-app/public/service-worker.js',
  dest:
   '/Users/mmiszy/htdocs/my-app/public/service-worker.js' }
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

https://github.com/mmiszy/next-bug-example

1. `next build && next export -o public`

## System information

- OS: MacOS
- Version of Next.js: Next.js v9.0.1

**Comment by masives** [comment]
Do you have a repo in which I can reproduce this issue?

**Comment by mmiszy** [comment]
https://github.com/mmiszy/next-bug-example

**Comment by huv1k** [comment]
Hey @mmiszy `public` folder is reserved for the public directory, it's behind the feature flag. We should throw an error when building to `public` folder. Sorry about that.

**Comment by mmiszy** [comment]
Is that something new introduced in Next.js 9? That would explain it.

**Comment by huv1k** [comment]
Yes, but it's behind a feature flag, so it should work without it. I will make PR to fix this bug.
