### ISSUE TITLE
Error: Couldn't find preset "next/babel"

### ISSUE THREAD

**Issue by johnlindquist** [zeit/next.js#810]
Open:
https://github.com/zeit/next.js/tree/master/examples/with-mobx

Install:
`yarn`

Run:
`yarn run dev`

Upgrade to latest next:
`yarn upgrade next`

Run again:
`yarn run dev`

Compiles with error: `Error: Couldn't find preset "next/babel"`

So something has changed between now and beta.4...

**Comment by timneutkens** [comment]
`yarn upgrade next` actually installs 1.x instead of 2x beta. Please use `yarn upgrade next@beta` 👍

**Comment by johnlindquist** [comment]
Thanks @timneutkens . I've always had it set to "latest", brain fart on my part :)
