### ISSUE TITLE
Allow non-GET requests to pages

### ISSUE THREAD

**Issue by possibilities** [zeit/next.js#811]
Some scenarios (e.g. sign in flow) require some pages to execute on the server and should never run on the client (e.g. submitting sign in form). If we allowed e.g. `POST` requests to pages we could do everything we need in `getInitialProps` but it _feels_ a little hacky. We might consider adding a first class escape hatch for forcing some routes on the server. Admittedly a custom server might be the least crufty way to accomplish all of this but felt it was worth raising in case you guys had a vision for this and/or hadn't considered the use case(s).

**Comment by cia48621793** [comment]
Just create another API + any state control for that(Redux/Mobx)...I'm doing that right now, and I'm pro-zeit/micro guy...

**Comment by arunoda** [comment]
for this **custom server** is the ideal solution since this is a uncommon(or not so common) usage.
So, simply write a custom server.
That's we built it in the first place.
