### ISSUE TITLE
next:{cdn:true} is no work

### ISSUE THREAD

**Issue by ckken** [zeit/next.js#82]
```
{
  "name": "mistat",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "next": "latest"
  },
  "next":{"cdn":false}
}
```
when I run next build & next start or run next ,the cdn is not dispair,shall we style the cdn link in our  service ?

**Comment by flybayer** [comment]
@ckken here's a tip so your code displays better :wink: 

Use 3 backticks before and after your code to preserve spaces and line breaks. Like so:
```
#```
code
#```

But without '#'
```

**Comment by ckken** [comment]
@flybayer got it, thanks
