### ISSUE TITLE
Build errors when project contains a symlink

### ISSUE THREAD

**Issue by acifani** [zeit/next.js#8238]
# Bug report

## Describe the bug

Next commands `build` and `dev` error out whenever there is a symbolic link in a directory within the project

## To Reproduce

Either 

- use my example repo https://github.com/acifani/next-symlink-bug
- create a symbolic link (`ln -s source_file dest_file`) in an directory of an existing project

## Expected behavior

Build should not error out, whether or not it should follow the symlink I don't know

## Screenshots

Error output:

```shell
❯ npm run build

> next-symlink@1.0.0 build /path/to/repo/next-symlink-bug
> next build

> Build error occurred
{ [Error: ENOENT: no such file or directory, stat '/path/to/repo/next-symlink-bug/some_dir/some_symlink']
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   '/path/to/repo/next-symlink-bug/some_dir/some_symlink' }
```

## System information

- OS: macOS 10.14.5
- Version of Next.js: ^9

## Additional context

The exception is caused by the build checking for possible TypeScript files. More specifically, by [`fs.statSync`](https://nodejs.org/api/fs.html#fs_fs_statsync_path_options) in [this line](https://github.com/zeit/next.js/blob/master/packages/next-server/server/lib/recursive-readdir-sync.ts#L19). There's a separate command, [fs.symlinkLink](https://nodejs.org/api/fs.html#fs_fs_symlinksync_target_path_type), available for symlinks

**Comment by acifani** [comment]
Fixed recently 👍

**Comment by reflash** [comment]
Same appears to happen when I have a symlink to a folder:
```
Error! ENOENT: no such file or directory, stat '/home/runner/work/<projname>/<projname>/<symlink>
```

**Comment by kjmph** [comment]
This still happens to me with broken links.

For instance:

```shell
host:next.js kjmph$ ln -s notexists examples/basic-css/pages/testfile
host:next.js kjmph$ yarn next ./examples/basic-css/
yarn run v1.22.10
$ node --trace-deprecation packages/next/dist/bin/next ./examples/basic-css/
ready - started server on http://localhost:3000
[Error: ENOENT: no such file or directory, stat '/home/kjmph/next.js/examples/basic-css/pages/testfile'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/kjmph/next.js/examples/basic-css/pages/testfile'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by probablyup** [comment]
@acifani this should be reopened

**Comment by MaxiSantos** [comment]
in your next.config.js add this

```
const { i18n } = require('./next-i18next.config');

module.exports = {
  ...
  webpack: (config, { buildId, dev }) => {
    config.resolve.symlinks = false
    return config
  }
}
```

**Comment by kjmph** [comment]
Before this gets locked and unable to comment, like #15278, disabling symlinks isn't always appropriate. I believe `pnpm` uses them extensively, plus, new versions of Next.js use SWC extensively, and webpack isn't even installed with latest (v12.0.9 at this time).

The problem with broken links and emacs lock files is this code: https://github.com/vercel/next.js/blob/b60c943750ff63b086f6adaf20daac3aa6e23573/packages/next/lib/recursive-readdir.ts#L30-L31

When a symlink is encountered, recursiveReadDir tries and stat the file. This can lead to `ENOENT` exceptions. Either all callers of this function should pass in configurable parameters for the ignore RegExp. Which is unlikely, see here: https://github.com/vercel/next.js/blob/b60c943750ff63b086f6adaf20daac3aa6e23573/packages/next/lib/typescript/getTypeScriptIntent.ts#L29-L33

Or!!! recursiveReadDir should gobble those `ENOENT` exceptions and let us move along in the build. Please don't kill this thread too.
