### ISSUE TITLE
ReferenceError: withTypescript is not defined:  when upgrading from 8 to 9

### ISSUE THREAD

**Issue by napestershine** [zeit/next.js#8401]
HI

I am trying to upgrade my code from 8 to 9. and I am getting :

![Selection_017](https://user-images.githubusercontent.com/8603325/63209052-6f0d6e00-c0dc-11e9-8c5c-ceb1e511cc18.png)

Code: https://github.com/napestershine/education-web

**Comment by timneutkens** [comment]
Hi please follow the issue template in the future. You'll want to read the upgrading guide: https://github.com/zeit/next.js/blob/canary/UPGRADING.md#zeitnext-typescript-is-no-longer-necessary
