### ISSUE TITLE
Custom server preload scripts major issue.

### ISSUE THREAD

**Issue by RayLuxembourg** [zeit/next.js#8406]
I have route in my server /info/:name

At my client I have the next link
<Link href={“/info/”+item.title} as={“/info/”+item.title}

Now when I build and start server it tries to preload lots of JS files which at path info/:name.js
But it has to load only info.js 

Is there a way to fix this?

**Comment by timneutkens** [comment]
You're using `href` and `as wrong, see https://github.com/zeit/next.js#dynamic-routing


`href`: the path inside pages directory.
`as`: the path that will be rendered in the browser URL bar.

If this is a "major issue" for you in particular please follow the issue template in the future, it clearly says you should post questions on https://spectrum.chat/next-js.
