### ISSUE TITLE
Router.push(...) callback

### ISSUE THREAD

**Issue by matthewmueller** [zeit/next.js#843]
It'd be great to get a callback to know when the router has pushed the route and the loading of the next page is complete. 

Right now there's a noticeable pause between Router.push(...) and rendering the next page, which affects things like loading bars and whatnot.

**Comment by arunoda** [comment]
We already return a promise and you can use that. Also, we have router events as well. 

See: https://github.com/zeit/next.js/blob/master/README.md#router-events
