### ISSUE TITLE
Customizing babel config does not work as described

### ISSUE THREAD

**Issue by mcmunder** [zeit/next.js#844]
Hey! Thanks for next.js! It's great!

I guess my issue is related to #432

I ran into a problem when I wanted to add a new babel plugin (['markdown-in-js/babel']('markdown-in-js/babel')) to render markdown in my react components...

As described in the docs I added a `.babelrc` in the root of my project.

```js
{
  "presets": [
    "next/babel",
    "stage-0"
  ],
  "plugins": [
    "markdown-in-js/babel"
  ]
}
```

With this `.babelrc` I get the following error when running `npm run dev`: "Module build failed: Error: Couldn't find preset "next/babel" relative to directory"

When I copy the complete `.babelrc` from next.js and add the markdown plugin it works just fine! 

Am I getting something wrong or is there  a problem with `next/babel`?

**Comment by arunoda** [comment]
May be you are running with a older version of next.js. Try to use `^2.0.0-beta` as the `next` package version in your app's `package.json`.

If this is still there, create a sample repo and comment it here.

**Comment by mcmunder** [comment]
Yeah, thanks! That seems to solve the problem.

**Comment by arunoda** [comment]
Great.
