### ISSUE TITLE
Head does not inject tags on server

### ISSUE THREAD

**Issue by kristojorg** [zeit/next.js#846]
I am using a custom `Document`, and it appears `Head` is not injecting the tags when rendering SS. If I disable js in the browser, I still can see the `Head` component render, but nothing appears in my document `<head>`

**Comment by arunoda** [comment]
It's not exactly clear what you mean. Try to submit us a sample repo where we could reproduce it.

**Comment by kristojorg** [comment]
I was mistakenly using a `<head>` element instead of the `<Head>` component from `next/document` in my custom `Document`, which it seems was causing this error. All better now!
