### ISSUE TITLE
Redux example error while running build

### ISSUE THREAD

**Issue by VictorVolovik** [zeit/next.js#85]
[Redux example](https://github.com/zeit/next.js/wiki/Redux-example)

```
next build
next start
```
Error in browser console:

VM3895:2 You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

Is there a way to use NODE_ENV === 'production' with Next.js build/start scripts?

**Comment by nodegin** [comment]
Same issue here, this error message (`You are currently using minified code outside of NODE_ENV === 'production'.`) were printed on the console in a production environment.

**Comment by nodegin** [comment]
Have tried the following but no lucks:

```
  "scripts": {
    "dev": "next",
    "build": "NODE_ENV=production next build",
    "start": "NODE_ENV=production next start"
  },
```
