### ISSUE TITLE
`Head` overwrites injected head tag content in v9

### ISSUE THREAD

**Issue by malimccalla** [zeit/next.js#8534]
# Bug report

### Description

Since v9 (worked as expected v8.1.0) a weird issues started happening in which certain parts of my project were not behaving as expected. I have isolated it to the  `Head` element. My simplified reproduction repo uses [@tippy.js/react](https://github.com/atomiks/tippy.js-react) to display a tooltip which is getting affected by the issue. The tooltip library injects styles into the head that are getting removed by `next/head`

### Steps to reproduce

1. Clone this repo https://github.com/malimccalla/external-link-issue/
2. `yarn install`
3. `yarn run dev`
4. Hover over the button.

### Expected 

Tool tip should correctly animate in and display the text "Hello"

### Actually happens

The words "Hello" just appears in the dom

### Additional info

- If you remove the `<link>` tag from `pages/index.js` and refresh the page everything works as expected
- The link tag can be to any external resource and doesn't necessarily need to link to css (the tag simply being `<link />` will also cause this issue)
- If you downgrade to next.js v8.1.0 everything works as expected

## System information

- OS: macOS
- Browser (if applies): Latest chrome
- Version of Next.js: 9.0.5

**Comment by malimccalla** [comment]
Additional info:

It seems what is happening is that the `style` tag that was previously being injected into the head is now getting removed.

**Comment by malimccalla** [comment]
I see thank for the insight @ijjk. Is this unexpected behaviour of the `Head` element as it has previously worked or should tippy.js be handling the insertion of styles differently. Also I wonder if the removal a `class` on the head elements should be considered a breaking change when upgrading from v8 to v9?

cc: @atomiks

**Comment by timneutkens** [comment]
It wasn't a breaking change and yeah styles definitely shouldn't be injected using JavaScript, at least not in that way 👍

**Comment by atomiks** [comment]
@timneutkens  other libraries do it that way as well, e.g. `sweetalert` and `sweetalert2`. Shouldn't this style of CSS injection be accounted for?

**Comment by malimccalla** [comment]
> Styles definitely shouldn't be injected using JavaScript in that way

@timneutkens I don't think this is a case of should or shouldn't, what seems apparent is that they _are_. If thats good or not is subjective and it seems like a library (or individual developer) that wants to be able to do so should be able to. I think accounting for this would be great 🙏

**Comment by timneutkens** [comment]
> I think accounting for this would be great 🙏

Feel free to open a PR and we'll review it.
