### ISSUE TITLE
Write migration guide for next/css

### ISSUE THREAD

**Issue by lorensr** [zeit/next.js#854]
I'm getting this error in my console:

> Warning: 'next/css' is deprecated. Please refer to the migration guide: https://github.com/zeit/next.js/wiki/Migrating-from-next-css

but the wiki article is empty

**Comment by impronunciable** [comment]
@rauchg done. Let me know if you want changes on the wiki

**Comment by impronunciable** [comment]
Thanks @lorensr for reporting
