### ISSUE TITLE
Parameterized routes using the filesystem

### ISSUE THREAD

**Issue by justindeguzman** [zeit/next.js#859]
Just starting to try out next.js, really like it so far!

Are there any disadvantages to using the filesystem for parameterized routes? Since colons aren't allowed in filenames, I was thinking of using semicolons. For example, the following would be an implementation of GitHub's routes:

```
/* static routes */
/index.js
/explore.js
...

/* parameterized routes */
/;username
  /index.js
  /;repo
    /index.js
    /issues.js
    ...
    /pulls.js
```

I have a custom router that makes this work but I don't know if there are any issues that I'm not thinking about that could adversely affect prefetching or SSR. It would be nice if parameterized routes were supported by default and we wouldn't need to use a custom server. It would also eliminate the need for a separate routes file for most use cases.

**Comment by arunoda** [comment]
This is our offering of [custom routes](https://github.com/zeit/next.js#custom-server-and-routing).
Have a look at the example apps list under "Examples" section in the above link
