### ISSUE TITLE
A fully rendered next page is re-rendered to a 404 page after successfull initial render

### ISSUE THREAD

**Issue by sarukuku** [zeit/next.js#868]
I've been trying to track this down for a day now and I've managed to come up with a small example code and I know the version bump that caused this issue.

This happens in older versions of Safari and Mobile Safari. The newest version of Safari I've found to have this issue is version 8.0.8 that is the only bundled browser for Yosemite. It's not even that old comparing how long Mac's last. I haven't seen this bug in other browsers (Chrome, FF etc.) while testing.

In `beta.12` the app renders correctly and no issues arise. With `beta.13` the app is first rendered correctly and then very quickly re-rendered to a "404 This page could not be found.". I've tracked that the issue is related to next trying to load a URL `http://localhost:3000/_next/pages/fi` on Safari that leads to a 404 error that causes the app to render the 404 page. Why this is happening is some kind of internal issue with next, custom server and older Safaris (my best guess).

Here's what I can provide to help solve this issue:
- Still happens with `beta.18`
- [A video of the issue happening on Safari 8.0.8](https://dl.dropboxusercontent.com/u/36387431/next-issue.mov)
- [A repo branch with example code](https://github.com/sarukuku/next-custom-server-express/tree/double-redirect)
- [Version bump where the bug appeared](https://github.com/zeit/next.js/compare/43e2707e5dcb961189e2ddab3492c2ce8360758d...45bc4fe46550c8085f90173275dcbd57fb2f9acb) (`beta.12` -> `beta.13`)

**Comment by sarukuku** [comment]
I know that getting hold of a Safari 8 on Yosemite is a bit tricky but there are free tiers available for browserstack.com that will allow testing this easily.

**Comment by tpai** [comment]
Also happening on Safari 9.0.3 and `beta.18`.

**Comment by arunoda** [comment]
Hmm. It's a bug. Getting that browser is the hardest part.
Let see.

**Comment by arunoda** [comment]
Guys, found the issue and here's the fix: https://github.com/zeit/next.js/pull/870

**Comment by sarukuku** [comment]
Excellent work @arunoda. Hopefully this will make it to the next beta. :)
