### ISSUE TITLE
How can I use react-redux with next.js?

### ISSUE THREAD

**Issue by swrdfish** [zeit/next.js#872]
It tried to use react-redux with next and found that subscription to the store doesn't seem to work. Though the store initializes properly also the actions dispatch properly. Any suggestions?

**Comment by amonks** [comment]
What do you mean by "subscription to the store doesn't seem to work"?

What's happening vs what do you expect should be happening?

**Comment by amonks** [comment]
I've been working from the [with-redux](https://github.com/zeit/next.js/tree/master/examples/with-redux) example (which uses react-redux) and haven't had any issues

**Comment by swrdfish** [comment]
I have created my store in a separate module and have imported into index.js file. Also I call connect form a different module and import the connected component. 

Now this all works well on the server side (print logs in the console) but when it reaches the client the `mapDispatchToProps` function is not invoked when the store gets updated. 

So my guess is that the **connect** function subscribes to the store when server rendering occurs but doesn't do so once more in the client side. 

I looked at the redux example and they have created separate instances of the store for the server and the client. I'll do that and see if it works.

**Comment by ooade** [comment]
@swrdfish I did mine without creating separate instances of the store. Created an higher order component wrapped to each page then i called connect on my Component and it works fine.

**Comment by timneutkens** [comment]
Please close this if the redux example solves your problem ❤️

**Comment by swrdfish** [comment]
@ooade  yeah that works too.. what I did wrong was that I had made the reducer a impure function and that broke everything. My bad.  Thank you guys for the help ❤️

**Comment by pesakitan22** [comment]
any example with shared components?

**Comment by victorkane** [comment]
Please wait just another day or so before closing. At the latest this weekend I will post our example we are working on, which will either work and be a great help to everyone, or else will not work and will be appropriate for this issue.

**Comment by ooade** [comment]
@victorkane It's already closed. 
BTW: I have an example [here](https://github.com/ooade/NextSimpleStarter), just in case :wink:
