### ISSUE TITLE
Module not found: Can't resolve 'private-next-pages/about.js'

### ISSUE THREAD

**Issue by kaluabentes** [zeit/next.js#8748]
# Bug report

When I try to build I get the following error:

`Module not found: Can't resolve 'private-next-pages/about.js'`

Then build fails.

## To Reproduce

1. Create a page named `about.js` with a component exported.
2. Try to build.

## Expected behavior

My application built

## System information

- MacOS
- Chrome
- Next.js v9

**Comment by kaluabentes** [comment]
I just solved! The problem was with my `next.config.js`, I overwritten `config.resolve.alias` in the wrong way. The correct way is:

```javasscript
config.resolve.alias = {
  ...config.resolve.alias,
  ...myWebpackConfig.resolve.alias,
}
```

Just ;)

**Comment by hema1592** [comment]
@k4lux , I'm also facing the same issue and I'm  adding the components/pages path as well. The solution which you wrote resolve the module not found issue. But, we are getting 'private-next-pages/_apps.js not found' .Could you please help on resolving this?


webpack(config) {
 config.resolve.alias = {
 ...config.resolve.alias,
 Component: path.resolve(__dirname, './components'),
 Config: path.resolve(__dirname, './config'),
 Page: path.resolve(__dirname, './pages'),
 Model: path.resolve(__dirname, './adapters/model'),
 Static: path.resolve(__dirname, './static')
 }
 }

**Comment by timneutkens** [comment]
You can use https://nextjs.org/docs/advanced-features/module-path-aliases to do path aliases, no need to change the webpack config.
