### ISSUE TITLE
how to set .next in another folder?

### ISSUE THREAD

**Issue by sammkj** [zeit/next.js#875]
Hello,

I have my `pages` folder in `folder A` and would like `.next` folder in `folder B`. I see that `next build` only accepts one arg. Is it possible to do this?

**Comment by rauchg** [comment]
Can you elaborate on the usecase please ?

**Comment by sammkj** [comment]
I have a project with the following structure:

![image](https://cloud.githubusercontent.com/assets/9153498/22273677/f7655d4c-e26f-11e6-8111-5b92f66a6d9a.png)

whereby I place `pages` folder under `./src/web`. Ideally, I would like to place `.next` folder under `./web`

**Comment by nkzawa** [comment]
Unfortunately, there is no way to that unless you manually move it, like `mv src/web/.next web/.next`.
I'm not sure if we should support the setting since maybe it would be just a problem of preferences ?

**Comment by baba43** [comment]
I have changed my pages directory to `src/pages` and now the _.next_ directory is created within `src`. 

Is there still no option to keep it at root?

**Comment by timneutkens** [comment]
Wouldn't recommend it. But you can use `distDir`

**Comment by baba43** [comment]
Thank you very much.

You would not recommend moving `pages/` elsewhere? If I should not do it, I will not do it.

**Comment by timneutkens** [comment]
Well you're not moving pages, you're moving the Next.js root itself, hence the `.next` ending up in `src`

**Comment by baba43** [comment]
Well, I just would like to have my `pages/` within my `src/` directory. 
Is that not possible / not recommended, too?

**Comment by timneutkens** [comment]
It's not possible indeed. We're not planning on changing that 👍

**Comment by vladnicula** [comment]
I think the only thing missing is a way to specify the lookup folder when building the pages. The `distDir` and `dir` (from custom server config) props are not enough to allow us to take the pages out from `src` and bundle them in the `../src` folder.
