### ISSUE TITLE
Display bundle sizes after build

### ISSUE THREAD

**Issue by thisbejim** [zeit/next.js#876]
It would be great to see bundle sizes in the terminal after building a project, similar to the output of a create-react-app build.

**Comment by ntwcklng** [comment]
We could use a table formatter like https://github.com/Automattic/cli-table for this
I've created a draft which looks pretty nice:

<img width="413" alt="screenshot at jan 25 13-15-20" src="https://cloud.githubusercontent.com/assets/8714775/22290324/6f3f0116-e300-11e6-8a08-b69a75f3a8a0.png">

Any other ideas?

**Comment by arunoda** [comment]
This looks great. But this list could grow since we might have more pages. Here's my suggestion.

* Use a simple list rather a table. (It saves space)
* Only show top 5 files (or some good amount)
* When showing pages, show `pages/about.json` like that.
* I prefer the first design for the uncompressed and gzipped sizes
* May be it's better to show the time spend for the build (and time for webpack and time for gzipping)

**Comment by transcranial** [comment]
why not use https://github.com/FormidableLabs/webpack-dashboard?

**Comment by ntwcklng** [comment]
@arunoda why do we have to save space? A list would take as much space as the table - if we want to display it readable (sizes on the same tab etc.)
I think this table is the perfect solution for outputting data like the bundle size.
To make it more compact, we can adjust the padding/margin from the cells.

For me, this is the perfect example how _not_ to do it:
![](https://camo.githubusercontent.com/40cd0d37ec6c377113a50fbea82f5347f1d29db0/687474703a2f2f692e696d6775722e636f6d2f70317541716b442e706e67)

@transcranial this dashboard is maybe helpful when running next in `dev` mode. However, when you run `next build` you just need a lightweight list/table

**Comment by sedubois** [comment]
@ntwcklng I think he just means that the horizontal lines in the table aren't needed, they take up vertical space

**Comment by ntwcklng** [comment]
Okay, the alternative is `console.table`
Looks also pretty nice
<img width="442" alt="screenshot at jan 25 20-06-12" src="https://cloud.githubusercontent.com/assets/8714775/22304905/d4638e98-e339-11e6-945d-5e6fce982d62.png">


Should we log the 5 overall largest files, or all bundle files + the 3 largest in `pages/`?

**Comment by arunoda** [comment]
@ntwcklng this looks pretty nice.
Shall we sort (z-a) by the size. 
Ignore `_document.json`. It's a server only file.

**Comment by arunoda** [comment]
> all bundle files + the 3 largest in pages/?

I like this.

**Comment by sakulstra** [comment]
I'd love to see this, but why restrict the output to ~5pages?
The project i'm working on has only ~10 and it would make sense for me to monitor the size for all of them.

Btw. would it be possible to not only display the size, but also the size difference to the previous build?
`main.js    159kB (48.2kb) (+36.4kB)`

**Comment by arunoda** [comment]
I not against of displaying ~10 pages. But I fear that'll be too much info. In this case, we mostly need to figure out our heavy pages. We need to limit upto few pages.

> Btw. would it be possible to not only display the size, but also the size difference to the previous build?

I don't think this is possible. We do this only for production build (it doesn't make sense for the dev build) and it's not (most of the time) possible to compare with the previous bundle.

**Comment by ntwcklng** [comment]
I don't know if its a good idea to include the path in the output:
<img width="540" alt="screenshot at jan 26 12-43-13" src="https://cloud.githubusercontent.com/assets/8714775/22330163/18b58a0c-e3c5-11e6-9299-412b2f0643f3.png">

Should we just go with the basename for the pages?

**Comment by sakulstra** [comment]
@arunoda but even comparing prouction build sizes(like create-react-app does) would help a lot.

With this you can easily detect if you accidentally included the whole e.g. 'firebase' or 'lodash'... without a history the size is just a number, but if you can notice: "since last build my main.js is now 60kb bigger than before you can actually wonder where this comes from and figure out if the increasing file size is reasonable."

**Comment by nkzawa** [comment]
Btw, webpack2 supports options related to this topic. 

https://webpack.js.org/configuration/performance/

We disable `performance.hints` for now.

Additionally, I wonder if this feature can be implemented by a webpack plugin. Ideally, I hope `https://github.com/geowarin/friendly-errors-webpack-plugin` supports this.

**Comment by timneutkens** [comment]
I'm +1 for adding it to friendly-errors-webpack-plugin. Created an issue for it to discuss.

**Comment by oliviertassinari** [comment]
For anyone looking into preventing bundle size regression. I have been solving a part of the issue with [size-limit](https://github.com/ai/size-limit) running in the CI:

**.size-limit**
```
[
  {
    "path": ".next/app.js",
    "webpack": false,
    "limit": "302.1 KB"
  },
  {
    "path": ".next/bundles/pages/www/home.js",
    "webpack": false,
    "limit": "35.4 KB"
  }
]
```

![capture d ecran 2017-12-13 a 16 49 30](https://user-images.githubusercontent.com/3165635/33947871-ce1f0b5e-e025-11e7-943b-bbdf78b111b4.png)

**Comment by julmot** [comment]
@timneutkens Since https://github.com/geowarin/friendly-errors-webpack-plugin/issues/54 was closed and this ticke too, is there any follow-up ticket about this feature?

**Comment by dackers86** [comment]
Also keen to know if there has been any updates to this feature. 

ParcelJS also has this and it's proved to be very useful.

**Comment by vonwao** [comment]
What does this ticket have to do with friendly errors?  Anyways it looks like that got closed.  I hate when tickets get linked to somewhere else and then closed.  Seems like everyone liked this idea, why not merge it in?

**Comment by mmiszy** [comment]
Should this be reopened @timneutkens ?

**Comment by timmywil** [comment]
This ticket died for seemingly no reason. You can set `config.performance` to `"error"` to see the output for production builds in your `next.config.js`. However, the formatting is lost and it's just printed as an array of strings.

@timneutkens Would be great to either have an option to show webpack output during the build or have a hook for handling build errors so we can print these messages to the console (since webpack already made them pretty but they're stuck in an array).

**Comment by timneutkens** [comment]
Let's re-open it.

**Comment by lucleray** [comment]
I made a small plugin to do show bundle size when running `next build`. It's quite similar to some suggestions in this issue.

https://github.com/lucleray/next-size

![demo of next-size plugin](https://github.com/lucleray/next-size/blob/master/demo.png?raw=true)

@timneutkens Do you think it has its place in nextjs or it's better to keep it as a separate package ? `create-react-app` has something like that by default.

**Comment by timneutkens** [comment]
I think we should re-open this issue.

**Comment by lucleray** [comment]
@timneutkens It should be possible 🙂

There's 3 dependencies :
- gzip-size => [one line](https://github.com/sindresorhus/gzip-size/blob/c28bd44300b319d9462aa8e3a5070716b48f4e79/index.js#L15), using node's internal `zlib` library
- pretty-bytes => [~5 lines](https://github.com/sindresorhus/pretty-bytes/blob/9db9f7d0f8d8105329055bd02f33fcf9581e7aff/index.js#L55-L61), or maybe there's something like this already in next.js ?
- chalk => we could "reuse" the dependency in webpackbar with a loose version pin, or just drop the colors

**Comment by lucleray** [comment]
Here's the PR : https://github.com/zeit/next.js/pull/5664

**Comment by timneutkens** [comment]
@lucleray solved this really well 😌
