### ISSUE TITLE
Did not expect server HTML to contain a <div> in <div>.

### ISSUE THREAD

**Issue by qlaffont** [zeit/next.js#8773]
# Bug report
`Did not expect server HTML to contain a <div> in <div>`.

## Describe the bug

Page don't load.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

0. Clone https://gitlab.com/gamubs/gamubs-web 
1. switch to "soul" branch
2. do npm install and do npm run dev 
3. Go to 
- 'http://localhost:3000/users/login'
- http://localhost:3000/
- http://localhost:3000/404error

## Expected behavior

Display login page without css issues.

## System information

- OS: [e.g. macOS, Windows] Mac OS
- Browser (if applies) [e.g. chrome, safari] Chrome
- Version of Next.js: [e.g. 6.0.2] 9.0.5

## Additional context

As I can see, it's only a server issue not client (probably due to SSR ?)

**Comment by williamli** [comment]
@qlaffont just took a quick look at your site, it only has http://localhost:3000/users/signin and there is no http://localhost:3000/users/login

and http://localhost:3000/users/signin loaded fine:

<img width="1748" alt="image" src="https://user-images.githubusercontent.com/179761/65208960-2bd26080-dac9-11e9-9ca3-a4c100bfe822.png">

**Comment by qlaffont** [comment]
@williamli sorry, I didn't update the process but you need to check on "soul" branch ^^". I have update the url too (on initial message): 

'http://localhost:3000/users/login'
http://localhost:3000/
http://localhost:3000/404error

**Comment by qlaffont** [comment]
As you can see, you can found the error (on "soul" branch or on "master", i have sync branch :) ) :
<img width="1440" alt="Capture d’écran 2019-09-19 à 07 28 19" src="https://user-images.githubusercontent.com/10044790/65216167-4d731e00-dab0-11e9-8def-9889ec26ad8f.png">

**Comment by qlaffont** [comment]
same on index localhost:3000/

<img width="1440" alt="Capture d’écran 2019-09-19 à 07 38 53" src="https://user-images.githubusercontent.com/10044790/65216251-97f49a80-dab0-11e9-8240-bc44c842c05f.png">

**Comment by MarchWorks** [comment]
The function that logs this warning is called `warnForDeletedHydratableElement` it's in react-dom https://github.com/facebook/react/blob/924a305780eb71866eb0932027048237b6f5c3cd/packages/react-dom/src/client/ReactDOMComponent.js#L1210 and it gets executed here https://github.com/facebook/react/blob/924a305780eb71866eb0932027048237b6f5c3cd/packages/react-dom/src/client/ReactDOMHostConfig.js#L769 you may want to ask someone from React core team about it

**Comment by Timer** [comment]
Closing as this is a user-error and support requests do not belong in our issue tracker. Pretty sure I saw this same thing posted on our Spectrum (the right place).

It seems related to `next-i18next`, did you try opening a report with them? Also, you seem to not be running your dev server with the `next-i18next` wrapper.

**Comment by qlaffont** [comment]
I will open an issue at next-i18next. 

> Also, you seem to not be running your dev server with the next-i18next wrapper.

If you check, I have created the server.ts at the root. But you think that `npx next dev` don't use it ?

**Comment by deepakvishwakarma-hh** [comment]
please resolve the issue
