### ISSUE TITLE
help needs on error

### ISSUE THREAD

**Issue by spacedragon** [zeit/next.js#880]
I get this error when  upgrade next from 2.0.0-beta.13 to 2.0.0-beta.14 or newer.
![image](https://cloud.githubusercontent.com/assets/631261/22293448/7e01d6c0-e34a-11e6-8a86-8cdf6c50b704.png)

This error seems related with  https://github.com/react-component/m-list-view  and react-hot-loader ,   but I  can't find  version change of react-hot-loader between  beta.13 and beta14

**Comment by arunoda** [comment]
Does this available on the production build as well?
I'd like to have a sample repo for this case.

**Comment by spacedragon** [comment]
production also not work 
here is the repo  https://github.com/spacedragon/next_rmc_listview
thanks a lot!

**Comment by arunoda** [comment]
This is a bug. I'm on it.
