### ISSUE TITLE
Traditional Authentication With Next

### ISSUE THREAD

**Issue by guidiego** [zeit/next.js#881]
I was studying some approaches to implement a traditional authentications on Next. In my brainstorms I found a solution that the user need be authenticate only on the first server-side rendering, once a time that every requests on client-side can return a `Not Authenticate (403)` error to be treated later with a redirect.

Can you guys think another approaches for that?

**Comment by davibe** [comment]
This is what i do:
- when the user logs in client-side javascript sets a cookie in the browser conintaing the authentication bearer token
- when making authenticated requests server-side (next.js) code reads the bearer token in the headers of the request of the browser and uses it to contact the api server on behalf of the client

**Comment by rauchg** [comment]
Thanks @davibe for helping out! For the sake of having help from the community in one place, I'm forwarding you here: #153 and closing this thread.

@davibe would love it if you could replicate your message there if you haven't yet.
Thansk again!

**Comment by manishbalyan** [comment]
hi @davibe i am saving my auth token in localstorage and then adding in headers from there but when server side request goes it did not set my autherization header.
Can you please suggest me some other way to set headers

**Comment by davibe** [comment]
If you set it as a cookie the server can read that cookie form headers. Have a look at how cookies work.
