### ISSUE TITLE
Transpiling components outside /pages?

### ISSUE THREAD

**Issue by malexdev** [zeit/next.js#883]
Hello! I'm just now getting started with next (using version 1.2.3), and I have the following folder structure:

- package.json
- pages
  - index.js
- lib
  - components
    - Test.js

I have a symlink: `node_modules/lib -> ../lib`.
I import my `Test` component with `import Test from 'lib/components/Test'`.

This works fine, but it seems to not be transpiled: if I `import` anything from my `Test` component, I get the following error: `SyntaxError: Unexpected token import`.

Any guidance here? I'd be fine having my `/components` under `/pages` but I don't want them to be able to be served up standalone.

Thanks!

**Comment by timneutkens** [comment]
Duplicate of https://github.com/zeit/next.js/issues/706

**Comment by timneutkens** [comment]
Short term answer is use relative paths for now. So `import Test from 'lib/components/Test'` would become `import Test from '../lib/components/Test'`

**Comment by malexdev** [comment]
Ah, sorry for the duplicate, and makes sense about not transpiling node_modules. Thanks!

**Comment by timneutkens** [comment]
🙌
