### ISSUE TITLE
Global styles not applied until page refresh

### ISSUE THREAD

**Issue by thisbejim** [zeit/next.js#885]
When applying global styles to a custom document the styles are not applied until you refresh the page, example:

```
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  render () {
    return (
      <html>
        <Head>
          <meta charSet="utf-8" />
          <meta name="viewport" content="initial-scale=1.0, width=device-width" />
          <style jsx global>{`.welcome { color: red; }`}</style>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
};
```

index.js
```
export default () => (
  <div className="welcome">Welcome to next.js!</div>
)
```

If you close your localhost tab, `npm run dev`, then open up a fresh tab you will get this:
![snip20170126_1](https://cloud.githubusercontent.com/assets/10917363/22308659/f5f6ce00-e39b-11e6-87a6-ebed659f991b.png)

If you refresh the page you get this:
![snip20170126_2](https://cloud.githubusercontent.com/assets/10917363/22308679/06c1764a-e39c-11e6-97bf-5e079594e630.png)

This also happens when you serve a production build of the project.

**Comment by arunoda** [comment]
Not exactly sure about how this happens.
But you should not styles like this with the custom document.
Whole purpose of the custom document should to customize your HTML page. Inside the custom layout, we don't have access to the React app.

So, try to move your styles to a common layout.
See this related discussion: https://github.com/zeit/next.js/issues/873#issuecomment-275008448

**Comment by timneutkens** [comment]
@arunoda actually we've seen this before. using styled-jsx inside of `<Head>` is not supported. Since it won't render an element. In this case styled-jsx is obsolete since
`<style>{`.welcome { color: red; }`}</style>` will be global. Using just the `<style>` fixes your issue 👍

**Comment by nontachaiwebdev** [comment]
I fixed with <style /> thankyou @timneutkens but I have a question. 
Why it work?
