### ISSUE TITLE
onClick not attached to components in custom document

### ISSUE THREAD

**Issue by thisbejim** [zeit/next.js#886]
Currently any components that handle clicks do not work as expected in a custom document. In the example below onClick will be stripped out on render:
```
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  render () {
    return (
      <html>
        <Head>
          <meta charSet="utf-8" />
          <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        </Head>
        <body>
          <button onClick={() => console.log('hello!')}>click me</button>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
};
```

The use case for allowing this is a global navbar with a menu toggle, at the moment you can put a navbar in each page but it would be great if you could mount it in a single location.

**Comment by arunoda** [comment]
Here's my previous answer for this.

**Comment by mankins** [comment]
Please re-consider this use case. I think a custom nav is a common use case. How can we have onClick here?

**Comment by sedubois** [comment]
@mankins just create a page HOC and wrap each of your pages with that? E.g in my app https://github.com/relatenow/relate/blob/master/hocs/page.js
