### ISSUE TITLE
Add LICENSE file to master branch.

### ISSUE THREAD

**Issue by TrustyTexan** [zeit/next.js#89]

**Comment by hngiang** [comment]
@TrustyTexan so LICENSE will use ?, i can take this issue

**Comment by TrustyTexan** [comment]
Most projects have a license file at the root of their repo.  For example: https://github.com/reactjs/redux/blob/master/LICENSE.md.

This let's consumers know the legal implications when using your code.

**Comment by hngiang** [comment]
@TrustyTexan i open pull request to add that issue to project 👍
