### ISSUE TITLE
Expose next/utils

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#890]
I just saw in your [code](https://github.com/zeit/next.js/blob/master/lib/utils.js) that you have an utils lib with function `loadGetInitialProps`. This function is quite useful for end-users too, e.g I needed to make my own (see [here](https://github.com/relatenow/relate/blob/master/util/initialProps.js)). Would it be possible to expose it e.g at `'next/utils'`?

**Comment by arunoda** [comment]
You could always get it from dist. `next/dist/utils`.

But that's something we are not going to open as a public API. 
We might change them at any will completely remove them.

**Comment by sedubois** [comment]
OK understood 👍 This works for now: `import { loadGetInitialProps } from 'next/dist/lib/utils'`.
