### ISSUE TITLE
Remove warning when getInitialProps returns an empty object

### ISSUE THREAD

**Issue by lcswillems** [zeit/next.js#8919]
# Feature request

## Is your feature request related to a problem? Please describe.

I have a `withAuth` HOC that checks if the user is logged in and if not, redirects to the login page. This HOC adds a `getInitialProps` method even if the input component doesn't have one.

Hence, I get a warning message saying that an empty object is returned. But, I don't see how I could do otherwise. 

## Describe the solution you'd like

Remove the warning.

**Comment by Janpot** [comment]
Why not just return a non-empty object from the `getInitialProps` of the authentication component?

**Comment by timneutkens** [comment]
In general you'd return a prop to make sure you don't render the page content in those cases (as data is missing).

We're not planning to remove this warning as the majority of use cases where an empty object is returned are misuses of getInitialProps and cause a page to be deoptimized (SSR'ed on demand) even though there is no need for it to be SSRed on demand.
