### ISSUE TITLE
Not working with react-icons

### ISSUE THREAD

**Issue by reel** [zeit/next.js#893]
Trying to import react-icons and I get the following error:

```
ModuleParseError: Module parse failed: <path>\node_modules\react-icons\md\layers.js Unexpected token (6:4) You may need an appropriate loader to handle this file type. | | const MdLayers = props => ( | <Icon viewBox="0 0 40 40" {...props}> | <g><path d="m20 26.6c-5-3.8-10-7.7-15-11.6l15-11.6 15 11.6c-5 3.9-10 7.8-15 11.6z m0 4.3l12.3-9.6 2.7 2.1-15 11.7-15-11.7 2.7-2.1z"/></g> | </Icon>
ModuleParseError: Module parse failed: <path>\node_modules\react-icons\md\layers.js Unexpected token (6:4)
You may need an appropriate loader to handle this file type.
| 
| const MdLayers = props => (
|     <Icon viewBox="0 0 40 40" {...props}>
|         <g><path d="m20 26.6c-5-3.8-10-7.7-15-11.6l15-11.6 15 11.6c-5 3.9-10 7.8-15 11.6z m0 4.3l12.3-9.6 2.7 2.1-15 11.7-15-11.7 2.7-2.1z"/></g>
|     </Icon>
```

Steps to reproduce:

```
# npm install react-icons

Add the following to your file:

import MdLayers from 'react-icons/md/layers';

or any other icons
```

Seems to happen to non-UMD packages

**Comment by arunoda** [comment]
Here you are importing the source file which has ES2015+ code.
You need to import the transpiled version like this:

```js
import MdLayers from 'react-icons/lib/md/layers';
```

**Comment by reel** [comment]
Thank's @arunoda... missed that somehow

**Comment by tgdn** [comment]
This gives me: Cannot read property 'toLowerCase' of undefined

**Comment by sergiodxa** [comment]
@tgdn that happen most of the time because you're importing something it doesn't exists (`undefined`) and trying to render it. Check your imports if it really exists.

**Comment by tgdn** [comment]
Yep sorry, my bad, in this case the variable naming was wrong. Sorry for bothering you, thank you 👍

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/create-next-app/index.test.js** 
- create next app > valid example
- create next app > should allow example with GitHub URL
- create next app > should allow example with GitHub URL and example-path
- create next app > should use --example-path over the file path in the GitHub URL

<details>
<summary>Expand output</summary>

  ● create next app › valid example

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js valid-example --example basic-css

      64 |   it('valid example', async () => {
      65 |     const projectName = 'valid-example'
    > 66 |     const res = await run(projectName, '--example', 'basic-css')
         |                 ^
      67 |     expect(res.exitCode).toBe(0)
      68 | 
      69 |     expect(

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:66:17)

  ● create next app › should allow example with GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-app --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages

      81 |   it('should allow example with GitHub URL', async () => {
      82 |     const projectName = 'github-app'
    > 83 |     const res = await run(
         |                 ^
      84 |       projectName,
      85 |       '--example',
      86 |       'https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages'

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:83:17)

  ● create next app › should allow example with GitHub URL and example-path

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path --example https://github.com/zeit/next-learn-demo/tree/master --example-path 1-navigate-between-pages

      104 |   it('should allow example with GitHub URL and example-path', async () => {
      105 |     const projectName = 'github-example-path'
    > 106 |     const res = await run(
          |                 ^
      107 |       projectName,
      108 |       '--example',
      109 |       'https://github.com/zeit/next-learn-demo/tree/master',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:106:17)

  ● create next app › should use --example-path over the file path in the GitHub URL

    Command failed with exit code 1 (EPERM): node /home/runner/work/next.js/next.js/packages/create-next-app/dist/index.js github-example-path-2 --example https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages --example-path 1-navigate-between-pages

      129 |   it('should use --example-path over the file path in the GitHub URL', async () => {
      130 |     const projectName = 'github-example-path-2'
    > 131 |     const res = await run(
          |                 ^
      132 |       projectName,
      133 |       '--example',
      134 |       'https://github.com/zeit/next-learn-demo/tree/master/1-navigate-between-pages',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at Object.<anonymous> (integration/create-next-app/index.test.js:131:17)

</details>
