### ISSUE TITLE
Apollo example error

### ISSUE THREAD

**Issue by abelovic** [zeit/next.js#896]
When I first run this example I can get it to work but if refresh the page I get the following error:

TypeError: Cannot assign to read only property '1' of [object Array]
    at Array.sort (native)
    at PostList (C:\next.js\examples\with-apollo\components\PostList.js:20:27)
    at walkTree (C:\next.js\examples\with-apollo\node_modules\react-apollo\src\server.ts:76:15)
    at walkTree (C:\next.js\examples\with-apollo\node_modules\react-apollo\src\server.ts:80:7)
    at getQueriesFromTree (C:\next.js\examples\with-apollo\node_modules\react-apollo\src\server.ts:102:3)
    at getDataFromTree (C:\next.js\examples\with-apollo\node_modules\react-apollo\src\server.ts:123:17)
    at C:\next.js\examples\with-apollo\node_modules\react-apollo\src\server.ts:131:28
    at process._tickCallback (node.js:385:9)

It also works if I change the file and re-save it. If I refresh after that it stops working again.

I have set my graph.cool end point in initClient.js. Is there something I am not doing correctly?

**Comment by ads1018** [comment]
@abelovic Does it work with the graph.cool endpoint provided in the example? Seems like could be an issue with your graph.cool endpoint. GraphQL API's are self-documenting so you can see if the API used in the example matches up with the one you created using the [graphiql interface](https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn/graphiql).

**Comment by abelovic** [comment]
This does not work for me with the end point in the example. This is all I did:

1. clone next.js
2. navigate to with-apollo sample
3. run npm install
4. npm run dev
5. open on localhost:3000

This pulls up for me with an error and I experience the symptoms described in my initial post i.e. works once when saving :(

In the graphiql interface:

query allPosts($first: Int!, $skip: Int!) {
  allPosts(orderBy: createdAt_DESC, first: $first, skip: $skip) {
    id
    title
    votes
    url
    createdAt
  }
  _allPostsMeta {
    count
  }
}

variables:

{
  "first": 10,
  "skip": 0
}

And it returns data so I don't think its the endpoint. I'm on windows which would be the only other variable that may be different but don't see why that would cause an issue.

Can you try cloning this on your machine and running it? Maybe there is something different from what you deployed vs what's in github? Your demo link runs perfect.

**Comment by ads1018** [comment]
@abelovic Good spot. The error was due to the assignment of a read-only property in the array which was happening when sorting the array. Simply remove `sort()` fixed the issue. I just submitted a pull request. Not sure why this error is only getting thrown now.

**Comment by timneutkens** [comment]
#900
