### ISSUE TITLE
Module build failed: Error: Couldn't find preset "react-server" relative to directory 

### ISSUE THREAD

**Issue by kishanj918** [zeit/next.js#897]
Node version : 7.0.0
npm version: 3.10.8
I am getting "Module build failed: Error: Couldn't find preset "react-server" relative to directory"  error while running npm run dev.

**Comment by timneutkens** [comment]
Hi, could you please provide an example repository / steps to reproduce?

**Comment by kishanj918** [comment]
I was getting this error while running this https://github.com/zeit/nextgram app.

**Comment by timneutkens** [comment]
I'll check this 👍

**Comment by timneutkens** [comment]
Can't reproduce. Can you try to run `npm install` in the directory?

**Comment by kishanj918** [comment]
sure

**Comment by kishanj918** [comment]
still getting the same error.

**Comment by arunoda** [comment]
I think that's because of some `.babelrc` file in somewhere in a parent directory.
@kishanj918  add following `.babelrc` file into the app root.

```
{
  "presets": ["next/babel"]
}
```

**Comment by timneutkens** [comment]
Good catch @arunoda 👍
