### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by ChiperSoft** [zeit/next.js#90]
There appears to be no provision made in the Next code for terminating the application gracefully. I don't see any hooks into SIGTERM or SIGKILL events, and `server/index.js` doesn't offer a `stop()` function.

This means that any time the app receives a shutdown event from the host machine it will halt while in the middle of handling requests instead of waiting for the requests to complete and properly stopping the server.

This also makes it impossible to start and stop the server in integration tests.

**Comment by timneutkens** [comment]
This is included in the latest codebase:
https://github.com/zeit/next.js/blob/master/bin/next#L47

**Comment by ChiperSoft** [comment]
The code you referenced does not appear to be a graceful shutdown, it's just reacting to the termination of the subprocess?

**Comment by arunoda** [comment]
@ChiperSoft I don't like graceful shutdown at all since server don't shutdown gracefully specially in this cloud era.

But anyway, Next.js should not have databases and stateful things (That's what we recommend).
So, it's totally okay to kill it right away.

About integration testing, you don't need that too. Check our testing suite and how we do it. You don't need graceful shutdown.

**Comment by ChiperSoft** [comment]
@arunoda you should still be waiting for requests to complete before killing the process. a deploy will hang up on anything in flight.

**Comment by arunoda** [comment]
@ChiperSoft better option is to do that with a proxy. (with re-trying)
Most of the proxies does support that. And most of the cloud hosting servers.

Servers could fail at sudden.

**Comment by nkzawa** [comment]
I think it's nice to have graceful shutdown for programatic API, even though it's not must. Maybe there is no downside to implement ?

**Comment by CpuID** [comment]
I would argue graceful shutdown is still a relevant feature here, especially for rolling deployments where you don't want to kill in-flight requests.

**Comment by mraxus** [comment]
Are there any plans on opening this issue up again? I have the same problem like @ChiperSoft was having: integration tests. I'm not sure how to shutdown the server.
