### ISSUE TITLE
Demo Package Numbering is Off

### ISSUE THREAD

**Issue by cmurray21** [zeit/next.js#9011]
# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.

While working through the nextjs.org learning modules, I noticed that the numbering is off in the demo package. 5 is skipped or no longer included.

I downloaded a clean copy of the demo and made the changes. I'm not sure how to make this change in the project.

I know this is really minor, but I want to try to get more involved. 

![Screenshot from 2019-10-09 12-48-36](https://user-images.githubusercontent.com/8770989/66503250-e6380080-ea94-11e9-94f9-7a6f7a9f3600.png)
![Screenshot from 2019-10-09 13-01-14](https://user-images.githubusercontent.com/8770989/66503251-e6380080-ea94-11e9-8b36-7e69bc25afc9.png)

**Comment by lfades** [comment]
Hi @cmurray21. The order of the demos is not very important, neither trying to keep up that order updated. Some lessons don't even have a demo and so even if all the numbers were incrementing properly, it wouldn't match anyway.

We could remove the numbers in the future and just use the name of the lesson for the demo instead, but atm this is not a priority so I'm closing the issue for now, thank you 🙌 .
