### ISSUE TITLE
Use helmet (or something similar) by default

### ISSUE THREAD

**Issue by selbekk** [zeit/next.js#9013]
# Feature request

## Is your feature request related to a problem? Please describe.

I was removing my custom server to make my website's fully serverless , and I ended up removing the [`helmet` package](https://www.npmjs.com/package/helmet) in the process. This kind of sucks, because it adds a lot of cool security features.

## Describe the solution you'd like

I'd love to have all of these headers applied by default, by Next, or at the very least a simple way to apply them without creating a custom server.

## Describe alternatives you've considered

I can re-create a custom server, but I'd rather not.

**Comment by Janpot** [comment]
Would https://github.com/zeit/next.js/issues/7208 help you in achieving this?

**Comment by timneutkens** [comment]
You can add it in `getInitialProps` of _document 👍

**Comment by selbekk** [comment]
It would definitely help - great feature btw @timneutkens - but why can't these headers / best practices be the default as well?

**Comment by timneutkens** [comment]
Basically all cases require extensive configuration of headers.

**Comment by selbekk** [comment]
Hm, well I guess some of them do. But setting them up with the approach in #7208 would definitely help :)

I guess this can be closed then. Looking forward to see your RFC become a reality!
