### ISSUE TITLE
Dynamic routing to static page is not working in production mode

### ISSUE THREAD

**Issue by Shaquu** [zeit/next.js#9086]
# Bug report

## Describe the bug

Dynamic routing to static page is not working in production mode
I have a page which fetches some data using React.useEffect on mount
In dev navigation to this site is working.
In prod after clicking Link is not working, page stays the same.
Page loads in prod when I type url directly to the page.

In prod there are no errors in console or network.
js file for page is being fetched with status 304

**Comment by timneutkens** [comment]
Please follow the issue template.

https://github.com/zeit/next.js/issues/new/choose

https://github.com/zeit/next.js/issues/new?template=8.Question_about_next.md

```
# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.
```
