### ISSUE TITLE
Why Router.push added first query param with string

### ISSUE THREAD

**Issue by Baukaalm** [zeit/next.js#9122]
I added query params with Router.push, but always next/router convert my data types only string, if that parameter is first
 my construction = > [target.name]: [target.value]
 result => color:"Red"

```
useEffect(() => {
    console.info(props.router);
  });

  const handleChange = ({ target }) => {
    if (target.type === 'checkbox') {
      if (target.checked) {
        Router.push(
          {
            pathname: props.href,
            query: {
              [target.name]: [target.value]
            }
          },
          {
            pathname: props.as,
            query: {
              [target.name]: [target.value]
            }
          },
          { shallow: true }
        );
      }
    }
  };
```
<img width="163" alt="Screen Shot 2019-10-18 at 11 03 54 AM" src="https://user-images.githubusercontent.com/11878817/67067175-27b46400-f197-11e9-8353-c2ccdd40bfa8.png">

**Comment by Timer** [comment]
I'm not sure I understand the question. There was not enough context provided. Please open a support request on our Spectrum with a full example.

https://spectrum.chat/next-js
