### ISSUE TITLE
Error with onTouchTap and material-ui

### ISSUE THREAD

**Issue by tgoldenberg** [zeit/next.js#917]
A previous issue was closed dealing with how to initialize the `injectTapEventPlugin` function. However, after having solved that according to the issue, I'm still getting errors using a dropdown menu in material-ui.

Code:
```
const Header = (props) => {
  const { position, referralLink } = props;
  return (
    <AppBar
      className="flex-container-left appbar"
      title={(
        <a href="/" className="logo-title">
          <img src="/static/images/image.svg" height="50" alt="company logo"/>
        </a>
      )}
      iconElementLeft={<span />}
      iconElementRight={(
        <IconMenu
          className="navigation-close"
          iconButtonElement={<IconButton><NavigationMenu /></IconButton>}
          targetOrigin={{ horizontal: 'right', vertical: 'top' }}
          anchorOrigin={{ horizontal: 'right', vertical: 'top' }}
        >
          <MenuItem
            primaryText="Home"
            onTouchTap={() => console.log('/home')}
          />
          <MenuItem
            primaryText="Status & Leaderboard"
            onTouchTap={() => console.log('/status')}
          />
        </IconMenu>
      )}
    />
  );
}
```

Error:
<img width="723" alt="screen shot 2017-01-29 at 9 28 40 am" src="https://cloud.githubusercontent.com/assets/10930134/22404803/35e14fb0-e606-11e6-97b9-9c58994d7501.png">

<img width="306" alt="screen shot 2017-01-29 at 9 35 11 am" src="https://cloud.githubusercontent.com/assets/10930134/22404804/4156a840-e606-11e6-8252-89b07bfbb76b.png">

**Comment by arunoda** [comment]
@tgoldenberg is it possible to have a sample repo? It's quite hard to figure it out like this.

**Comment by tgoldenberg** [comment]
@arunoda sure, I'll try to get one ready.

**Comment by frol** [comment]
*I would like to just share my experience with React-MD, which is an alternative implementation of Google Material UI for React. [React-MD](http://react-md.mlaursen.com/) just works with Next.js like a charm for me.*

**Comment by tgoldenberg** [comment]
Here's a sample repo: https://github.com/tgoldenberg/next-sample

**Comment by ugiacoman** [comment]
@frol Are you using a custom webpack config to get it working?

**Comment by arunoda** [comment]
@tgoldenberg I'll have a look at this too.

**Comment by arunoda** [comment]
May be this issue is related too: https://github.com/zeit/next.js/issues/882#issuecomment-275940934

**Comment by frol** [comment]
@ugiacoman No, I have just installed it (`npm install --save react-md`), import it (`import ... from 'react-md/...'`), and added compiled CSS files and fonts using `<Head>`. That is it.

**Comment by tgoldenberg** [comment]
@frol, I'll checkout `react-md`, but I think the issue still remains. A lot of people use `material-ui`, and migrating isn't always that easy.

**Comment by alexedev** [comment]
@frol could you please elaborate on how you compile and add compiled files to Head? (I'm new to next.js)

**Comment by DarkAdmiral** [comment]
Hey, just update to next 2.0.0-beta.20 and adapt your jsx styling. For testing I commented out 

`import LandingPageContent from '../components/splash/LandingPageContent.js';
<LandingPageContent` />
<style jsx>{mainStyles}</style>`

Your button was working then.

/Jan

**Comment by frol** [comment]
@alexedev @tgoldenberg I have just PRed the example of using React-MD with Next.js: #940

**Comment by alexedev** [comment]
@frol great, thank you

**Comment by aaronshaf** [comment]
Still having this problem with 2.0.0-beta.24
