### ISSUE TITLE
(s)css in its own file?

### ISSUE THREAD

**Issue by arashsa** [zeit/next.js#919]
I really like the fact that we can use regular css, but I was just wondering if this could be separated in another file?

```
<style jsx>{`
      p {
        color: blue;
      }
      div {
        background: red;
      }
      @media (max-width: 600px) {
        div {
          background: blue;
        }
      }
`}</style>
```

So if we can have a styles folder, and then each file can include css and/or scss, and then we can access those by their filename in the jsx files. 

So we could instead have a file called 'name.scss', with the css code:

```
p {
    color: blue;
 }
div {
    background: red;
}
@media (max-width: 600px) {
    div {
        background: blue;
    }
}
```

And then use it in the jsx file like so:

```
<style jsx={name}></style>
```

So just like the routing, which uses the file system, we could do the same with the css. Would be neat to have the style and javascript separated in different files.

It would also be a great feature to have scss automatically included in next.

**Comment by nkzawa** [comment]
This is discussed here https://github.com/zeit/styled-jsx/issues/83
