### ISSUE TITLE
router replace not working

### ISSUE THREAD

**Issue by cleverboy32** [zeit/next.js#9193]
# Bug report

## Describe the bug

router replace not working

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1 i open page A
1. i open a page B
2. in page B , I use `Router.replace(link.href);` go another page
3. i use broswer history  back button 
4. the page still B, its should be page A 

## Expected behavior

its should be page A 

## System information

- OS: mac
- Browser chrome
- Version of Next.js: 9.0.2

**Comment by phil3903** [comment]
I'm experiencing this as well in 9.1.3. Specifically when using the router from the useRouter hook, then calling router.replace in a click handler. Pressing back will bring me back to my previous page, which is not expected behavior.

Conversely, if I do replace in getInitialProps, the behavior works as expected.

**Comment by imran1992** [comment]
yes same here too.
OS: microsoft windows10 1909
Browser: chrome v79.0.3945.88
Next.js: v9.1.6

**Comment by imran1992** [comment]
Same here.
Version of Next.js: 9.1.6

**Comment by timneutkens** [comment]
Going to close this as a full reproduction wasn't provided.

**Comment by naveendmd** [comment]
I'm also experiencing this issue in the history stack the previous URL is present

**Comment by mannoeu** [comment]
the same for me.

when using router.replace("/", router.asPath, { locale: router.locale }) the path of the old url is still present, despite taking me to "/"

**Comment by thaihoangminh** [comment]
> I'm also experiencing this issue in the history stack the previous URL is present even after replacing it returns the history.length = 2 , should be 1
> 
> Reproduced it in code sandbox - https://codesandbox.io/s/pensive-sinoussi-poe9j?file=/pages/index.js

+1

**Comment by meadow-tulips** [comment]
Works sometimes . Does not work most times.
