### ISSUE TITLE
Blog Typo

### ISSUE THREAD

**Issue by hnordt** [zeit/next.js#92]
In https://zeit.co/blog/next#data-fetching-is-up-to-the-developer, `export class exports React.Component {` should be `export default class extends React.Component {`.

**Comment by clintonhalpin** [comment]
+1

Also I'm not sure if I'm doing something wrong. But when I ran the example ( with correction ) Node `v.7.0` was complaining that fetch wasn't defined.

My solution was to import `axios` and use that instead of fetch. I'd be happy to open a PR for this in the examples folder!

```javascript
import React from 'react'
import axios from 'axios'

export default class extends React.Component {

  static async getInitialProps () {
    const response = await axios('https://api.company.com/user/123')
    return { username: response.data }
  }

}
```

**Comment by hnordt** [comment]
Yeah, same problem here @clintonhalpin, I think Node.js doesn't support natively fetch yet. A work around would be to install and import the package `isomorphic-fetch`.

**Comment by nodegin** [comment]
next.js should absolutely include the `isomorphic-fetch` polyfill!

**Comment by rauchg** [comment]
I was missing the `isomorphic-fetch` import. Thank you. We actually use that extensively for `www.zeit.co`

**Comment by rauchg** [comment]
We'll update the blog post

**Comment by hnordt** [comment]
Anyway, great job with Next.js, you and Zeit's team are brillant @rauchg.

**Comment by hnordt** [comment]
The blog was updated, I'm closing this issue.
