### ISSUE TITLE
<Link> should admit *any* element underneath

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#920]
What it shouldn't do is _create_ any element (for now we do, but we will show a warning)
The problem is that the current error message is misleading.

These should be possible:

```jsx
<Link><img /></Link>
<Link><a /></Link>
<Link><a><img /></a></Link>
```

This should wrap with `<a>` for now and *warn*:

```jsx
<Link>hi</Link>
<Link>{ ' woot' }</Link>
```

This should throw (dev-only, to ship less code)

```jsx
<Link></Link>
```

https://github.com/zeit/next.js/blob/master/lib/link.js#L73

**Comment by timneutkens** [comment]
Looking into this now 🙌

**Comment by timneutkens** [comment]
#921

**Comment by rauchg** [comment]
Thank you @timneutkens !
