### ISSUE TITLE
Port already being used  

### ISSUE THREAD

**Issue by agriboz** [zeit/next.js#927]
I have another app using port `3000`. So when i start the server, it fails with the following `Error: listen EADDRINUSE :::3000`

There was a discussion about this topic. 

I don't know what do you guys think about it?

https://github.com/facebookincubator/create-react-app/issues/85

**Comment by arunoda** [comment]
We want something simple like this: https://github.com/zeit/next.js/pull/68#issuecomment-260302239

PRs welcome.

**Comment by impronunciable** [comment]
Works as intended LGTM
