### ISSUE TITLE
Dynamic Routing

### ISSUE THREAD

**Issue by Ehesp** [zeit/next.js#929]
Hello,

I know this has been discussed in a few other places and also there is a example repo for express, however I'm struggling to get this working with the examples and help on slack:

I need two routes:
- `/notifications` (pages/notifications/index.js)
- `/notifications/:id` (pages/notifications/single.js)

My server (express) is setup to like so:

```
    server.get('/notifications/*', (req, res) => {
      return app.render(req, res, '/notifications/single', req.query);
    });
```

On the server `getInitialProps` I can grab the ID from `ctx.req.params`.  However, I'm struggling to navigate to the route using `Router`.

- The following changes the URL in my browser, but reloads the `/notifications` route.
```
Router.push(`/notifications?id=${id}`, `/notifications/${id}`);
```

- The following hits a 404 page:
```
Router.push(`/notifications/${id}`);
```

Is there anyway to handle this?

Cheers

**Comment by arunoda** [comment]
You server route should be something like this:

```js
server.get('/notifications/:id', (req, res) => {
  const params = { id: req.params.id }
  return app.render(req, res, '/notifications/single', params);
});
```

**Comment by fridays** [comment]
Maybe [next-routes](https://github.com/fridays/next-routes) can be helpful to you, you could use it like this:

```javascript
routes.add('notification', '/notifications/:id', 'notifications/single')
routes.add('notifications', '/notifications', 'notifications/index')

Router.pushRoute('notification', {id: 1})
Router.pushRoute('notifications')

<Link route="notification" params={{id: 1}}> ... </Link>
```

**Comment by Ehesp** [comment]
@arunoda that makes sense cheers :) Works!

**Comment by amotion** [comment]
I'm experiencing a similar issue but am unable to get it working. I'm linking from a route like `/photo/1` to `/photo/2` and I can see that the component is fetched and render is called inside of the component, but the page doesn't update. The URL does change, however, and reloading the page after following a link will load the new page.

```
Router.push(`/photo?id=${id}`, `/photo/${id}`)
```

```
const match = route('/photo/:id')

app.prepare()
.then(() => {
  createServer((req, res) => {
    const { pathname } = parse(req.url)
    const params = match(pathname)
    if (params === false) {
      console.log("params false")
      handle(req, res)
      return
    }
    console.log("render app")
    app.render(req, res, '/photo', params)
  })
  .listen(3000, (err) => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000')
  })
})
```

**Comment by amotion** [comment]
Doing the same thing with a different page works correctly (like linking to `/about`) but I'm unable to make one photo link to the next (like from `/photo/1` to `/photo/2`)

**Comment by amotion** [comment]
Nevermind!
