### ISSUE TITLE
import firebase error

### ISSUE THREAD

**Issue by sakulstra** [zeit/next.js#930]
Hello,
I the firebase docs there's a section about reducing bundle size by only importing/requiring the parts that you need e.g.:
```
const firebase = require('firebase/app');
require('firebase/auth');
```
which works perfectly fine on e.g. create-react-app.
On next.js i get an 
`{ [Error: The XMLHttpRequest compatibility library was not found.]
  code: 'auth/internal-error',
  message: 'The XMLHttpRequest compatibility library was not found.' }` error

Someone has an idea where this comes from?
I assume it has sth to do with not using webpack on the server-side and so running in some ssr issues?

Using
```
const firebase = require('firebase');
```
on the other hand works perfectly fine.

**Comment by Ehesp** [comment]
What firebase action are you trying to do? Or is this error thrown when trying to initilize the app?

**Comment by sakulstra** [comment]
@Ehesp i only initialize the app, but even if i comment it out it seems like adding the two require lines above is enough to let the server crash.

**Comment by arunoda** [comment]
@sakulstra I guess that's an issue.
May be you could try to mock the Node.js environment with the our custom server API and try to add what firebase is looking for.

Since firebase is not open source, that can be quite tricky. May be we could try to read the source code at `node_modules`

**Comment by timneutkens** [comment]
Could you try `const firebase = require('firebase')` as stated here https://firebase.google.com/docs/web/setup that's the way to call on the node.js side of things. I'm not sure if it will run in a browser. But with dynamic imports coming 🔜 that could be resolved.

**Comment by sakulstra** [comment]
@timneutkens this will most properly work as it's basically equivalent to:
`import firebase from 'firebase'` which also works, but like your require approach this increases build size a lot (with unnecessary things like messaging and database if you e.g. only need auth).

@arunoda i'll try to figure things out, but my hopes are low as it's not important enough to waste a lot of time with this :)

**Comment by Ehesp** [comment]
@sakulstra I do the general import, also does't work with specific importing.

On a side note with Firebase, just remember you can't do authentication with the client SDK on the server, or anything which requires user specific requests.

**Comment by ryanaponte** [comment]
@Ehesp with regards to your comment, do you know where I might learn more about server-side limitations of Firebase related to auth and ssr?

It's unclear to me what is/is not possible (e.g. [this repo](https://github.com/nyura123/mobx-firebase-store/tree/master/examples/next-example) 'shows firebase auth on server and client, and protected routes' ). Thank you .

**Comment by elrumordelaluz** [comment]
Same problem here, only solution using a general `import` (with unnecessary services in the final bundle) 🙁
