### ISSUE TITLE
Startup can't find index.js if "files" configuration is used 

### ISSUE THREAD

**Issue by taromero** [zeit/next.js#933]
I have the following now.json config:

```json
{
  "name": "sample-name",
  "files": [
    "bundle.js"
  ],
  "type": "npm",
  "engines": {
    "node": "7.0.0"
  }
}
```

Here I want to include the webpack bundle.js file, which I have listed within .gitignore.

If I try to deploy with this configuration, I get an `Error: Cannot find module '/home/nowuser/src/index'` error. When I remove the "files" section at the now.json file, I can deploy without problems, but the bundle.js file is not available.

I think the expectation would be that this configuration would *add* the listed files to the set of files already being uploaded, rather than just uploading that file.

**Comment by timneutkens** [comment]
This seems related to `now` not `next.js`. Please post your issue here https://github.com/zeit/now-cli ❤️

**Comment by taromero** [comment]
Sorry for that :joy:. Just created the [ticket](https://github.com/zeit/now-cli/issues/265) at the proper zeit/now-cli repo, thanks!
