### ISSUE TITLE
Check out next-routes - Universal named routes for next.js

### ISSUE THREAD

**Issue by fridays** [zeit/next.js#934]
Hello guys!

I just published **[next-routes](https://github.com/fridays/next-routes)** to npm and hopefully it can be useful for others. It let's you define named routes for a next.js project in an express-style syntax and provides a server middleware and wrapped `Link` and `Router` to generate the URLs:

```javascript
// Define routes like
routes.add('blog', '/blog/:slug')

// Use Link
<Link route="blog" params={{slug: 'hello-world'}}> ... </Link>

// Use Router
Router.pushRoute('blog', {slug: 'hello-world'})
```

Check out the [README](https://github.com/fridays/next-routes) for full details.

This is my first npm package, I appreciate any feedback, reviews and suggestions!

**Comment by arunoda** [comment]
This is a pretty nice project.
Good job.

**Comment by fridays** [comment]
Thank you!

**Comment by timneutkens** [comment]
This is cool! 👍 💯

**Comment by sstubbs** [comment]
This looks great! thank you.

**Comment by impronunciable** [comment]
This is great. It seems to be an [Awesome nextjs](https://github.com/unicodeveloper/awesome-nextjs) repo for this to be included. I'll close this issue but thanks for sharing :)
