### ISSUE TITLE
Remove propTypes in production build

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#937]
Implement something like this:
https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types

**Comment by carloscuatin** [comment]
or something like this
https://github.com/thejameskyle/babel-react-optimize

**Comment by timneutkens** [comment]
@carloscuatin cool! Will definitely look into that 👍

**Comment by rauchg** [comment]
I'm going to give this a priority boost
