### ISSUE TITLE
keep ‘Creating an optimized production build ...’ a long time

### ISSUE THREAD

**Issue by Yakovtam** [zeit/next.js#9410]
When I build my project with 'npm run build -> next build',
it's keeping  ‘Creating an optimized production build ...’ a long time.
What should I do?

![image](https://user-images.githubusercontent.com/23466613/68821766-21e46c80-06ca-11ea-8215-8973c0c0661c.png)

**Comment by jamesmosier** [comment]
Try deleting your `node_modules` and `.next` folder, then re-run `npm install` then `npm run build`

**Comment by Yakovtam** [comment]
Thanks!  Is't OK.

> Try deleting your `node_modules` and `.next` folder, then re-run `npm install` then `npm run build`

**Comment by gasparnd** [comment]
Sorry. I have the same problem but delete node_modules and .next and  not working for me. What can i do?

**Comment by jain1403** [comment]
I have the same problem but delete node_modules and .next and not working for me. What can i do?

**Comment by dimitrisnl** [comment]
Same issue here with the latest version `12.0.4`. Nothing fancy in the next.config. I have tried to use a single app.js & index.js files to test it, and it still hangs.

**Comment by agmitron** [comment]
The same issue. Removing .next and node_modules didn't help.

**Comment by balazsorban44** [comment]
If anyone is reporting the same issue, please open a separate issue and add your reproduction. :pray:
