### ISSUE TITLE
next fails to start without any message

### ISSUE THREAD

**Issue by vonwao** [zeit/next.js#942]
Nothing happens.  An error message would be good. 

```
$ npm run dev
> nextgram@ dev /Users/otto/github/nextgram
> next
otto at Ottos-MacBook-Pro-2 in ~/github/nextgram on master*
$ 
```

**Comment by timneutkens** [comment]
I'm assuming you have run `npm install` before the above `npm run dev`, I've just checked this and it builds the app for me 🤔

**Comment by vonwao** [comment]
Yes, npm install completed without any errors.

**Comment by arunoda** [comment]
@vonwao run it like this:

```
node node_modules/.bin/next
```

**Comment by yoonwaiyan** [comment]
@arunoda I have the same problem as OP, your suggested solution didn't work for me though. I'm running on node version v5.4.1 that yields the result. Before switching back to older version I've tried using newest version of node v7.5.0 but it has weirder error(error while parsing package.json).
