### ISSUE TITLE
Turn off source maps by default

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#943]
Actually, here's my key points for this:

* Babel errors (with HMR) works without source maps properly
* Stack traces don't know how to handle source maps
* This slows down the app by 4X or more (This is a big deal)
* One can turn on source maps with our custom `next.config.js`

**Comment by timneutkens** [comment]
The only place it is needed is styled-jsx. To show styling locations. I'm not sure if this is related to webpack's sourcemaps though.

**Comment by arunoda** [comment]
I think `styled-jsx` babel plugin does that. (not webpack)

**Comment by arunoda** [comment]
Another idea, for the dev build we can use https://github.com/babel/babel-preset-env to not to transpile a lot. So, we don't really need source maps.

**Comment by aesopwolf** [comment]
@arunoda do you have an example of how to turn on source maps with `next.config.js`?

**Comment by arunoda** [comment]
@aesopwolf check this: https://github.com/zeit/next.js/issues/918#issuecomment-275922407

**Comment by arunoda** [comment]
Even source-maps add some(considerable) overhead. It's pretty useful when debugging the code.
So, I'll close this issue.
