### ISSUE TITLE
make the error page component a public component useful for consumption

### ISSUE THREAD

**Issue by balupton** [zeit/next.js#945]
right now there is https://github.com/zeit/next.js/blob/ec2c8c6784aae680964a32ab7a5bc2b657e5cf98/pages/_error.js

it is the really pretty error page when a server-side error occurs

pretty much as error handling is super common, it would be nice if I could just do:

``` javascript
import React, {Component} from 'react'
import ErrorPage from 'next/error'

export default class SomePage extends Component {
	componentDidMount () {
		doSomething((error, result) => {
			this.setState({error, result})
		})
	}

	render () {
		const {error, result} = this.state || {}
		if ( error )  return <ErrorPage error={error} />
		return <div>{result ? `here is the result: ${result}` : 'waiting on the result'}</div>
	}
}
```

With error being a string, or an Error instance - if an error instance, message should be displayed, as well as the stack

**Comment by timneutkens** [comment]
Has been fixed a long time ago 😄
