### ISSUE TITLE
Infinitely refresh when visit on 127.0.0.1:3000

### ISSUE THREAD

**Issue by zhaoyao91** [zeit/next.js#955]
when run with `npm run dev`, if I visit it on `localhost:3000`, everything goes well. but if I visit on `127.0.0.1:3000`, the page gets refreshed infinitely.

**Comment by nkzawa** [comment]
Cannot reproduce. Can you prepare a sample repository which we can reproduce if possible ?

**Comment by zhaoyao91** [comment]
I should close this issue for now I don't have a repo to reproduce. Once I have a workable one, I will reopen it by the time.

**Comment by frol** [comment]
JFYI, I have seen such behavior on my end recently, but cold restart solved the issue for me so I didn't bother reporting it.
