### ISSUE TITLE
Failed to register a ServiceWorker: ServiceWorker script evaluation failed

### ISSUE THREAD

**Issue by sarukuku** [zeit/next.js#956]
We're getting this kind of error on latest Chrome on Android tablet. I quickly peeked the file that's causing the error and it seems that there's code written with ES6 syntax in the file. See the screenshot below. Should the service worker code be compiled to ES5?

![screenshot 2017-02-02 12 13 25](https://cloud.githubusercontent.com/assets/1204559/22545413/55ccabec-e941-11e6-923a-aabca302d84c.png)

The first thing related to the error when googling point to [this](http://stackoverflow.com/questions/33934498/domexception-failed-to-register-a-serviceworker-serviceworker-script-evaluatio). It also is talking about it being a syntax error.

**Comment by arunoda** [comment]
Yep. We are working on a new way to handle prefetching.
Let's try to find a fix soon.

**Comment by sarukuku** [comment]
Great! If we don't use the `import PrefetchLink from 'next/prefetch'` at all would this disable the service worker for now?

**Comment by sarukuku** [comment]
Tested. Not using the `next/prefetch` circumvents the issue.

**Comment by arunoda** [comment]
Yes. Sometimes it get started even you are not using it (But used it earlier).

**Comment by arunoda** [comment]
Guys check this: https://github.com/zeit/next.js/pull/957
