### ISSUE TITLE
Add typescript example

### ISSUE THREAD

**Issue by giladgray** [zeit/next.js#96]
this looks _awesome_ but I also really like TypeScript. 
is there any way to integrate typescript into the workflow?

**Comment by mmmeff** [comment]
Custom webpack config would make this happen: #40

**Comment by rossipedia** [comment]
You don't need a custom webpack config (althouh it _would_ be nice). There's nothing preventing you from using typescript as-is. For example:

<img width="158" alt="screen shot 2016-10-29 at 1 06 46 am" src="https://cloud.githubusercontent.com/assets/96213/19827879/fe30c47c-9d73-11e6-811f-7dc47fe933ff.png">

**tsconfig.json**:
``` json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "jsx": "react",
        "noImplicitAny": false,
        "sourceMap": false
    }
}
```

As I don't think next.js has any typings (yet), you might need a `next.d.ts` file in the `typings` folder to define some things:

**next.d.ts**:

**Comment by giladgray** [comment]
wow @rossipedia i have been doing literally this exact thing locally, and it works!

it occurred to me moments after i opened this issue that it should be quite possible to layer `tsc -p .` on top of `next`, and of course it's that easy. typings are proving a little more insidious than that because the library injects `props.url` into pages and treats `getInitialProps` slightly differently. so i'm still trying to figure out how to correctly type those.

**Comment by mcassie566** [comment]
Hope it's all good.  Give it to the COPs.  They r the real hero's!  Bedtime
;)

On Oct 29, 2016 00:58, "Gilad Gray" <notifications@github.com> wrote:
>
> wow @rossipedia i have been doing literally this exact thing locally, and
it works!
>
> it occurred to me moments after i opened this issue that it should be
quite possible to layer tsc -p . on top of next, and of course it's that
easy. typings are proving a little more insidious than that because the
library injects props.url into pages and treats getInitialProps slightly
differently. so i'm still trying to figure out how to correctly type those.

**Comment by rauchg** [comment]
When we add custom babel / webpack config, I would love to have a TypeScript example and a Flow example. @rossipedia thanks a lot for the temporary workaround. If you'd be up for documenting the temporary solution in the Wiki, I think a lot of people would appreciate it!

**Comment by giacomorebonato** [comment]
If you are using VSCode it is also possible to [hide derived JS file](https://code.visualstudio.com/Docs/languages/typescript#_hiding-derived-javascript-files).

**Comment by rossipedia** [comment]
@rauchg I'm traveling this weekend, but if nobody else gets to it I'd be happy to add a page to the wiki, I can whip it up during my flight tomorrow

**Comment by skhavari** [comment]
trying to get running with typescript - things were going great until I decided to configure the page header...

```
import Head from "next/head";
...
render() {
        return (
            <div>
                <Head>
                    <title>Yo!</title>
                </Head>
                <div>unicorn</div>
            </div>
        );
    }
```

`React.createElement` starts complaining that the element shouldn't be null.  It appears that the default export from "next/head" is null:

<img width="480" alt="screen shot 2016-11-02 at 1 05 43 pm" src="https://cloud.githubusercontent.com/assets/4343866/19945449/6cbfffb6-a0fd-11e6-8849-782417248af1.png">

anyone else seeing this in a typescript project?

**Comment by giacomorebonato** [comment]
Have you tried
```js
const Head = require('next/head')
```
?

**Comment by skhavari** [comment]
Of course

**Comment by giacomorebonato** [comment]
Ok, if you write it like this, it will work  
```js
const Head = require('next/head').default
```

**Comment by BLamy** [comment]
I found it pretty easy to just edit the gulpfile to also compile .ts files. 

https://github.com/zeit/next.js/blob/master/gulpfile.js#L123

Why not compile .ts files with typescript and .js files with babel by default?

**Comment by giacomorebonato** [comment]
With Webpack you mean?
I like TypeScript and I will be happy enough when we can customise the Webpack configuration.

**Comment by almilo** [comment]
@skhavari your issue is a known module interop issue and adding '.default' is not needed.
Try telling TypeScript to emit 'es6' code (which webpack will pick up) and use 'node' modules resolution:

```json
{
  "compilerOptions": {
    "target": "es6",
    "moduleResolution": "node",
    "jsx": "react"
  },
  "filesGlob": [
    "pages/**/*.tsx"
  ]
}
```

I also add 'tsc' in my scripts like so:
```json
...
    "dev": "tsc && next",
    "build": "tsc && next build",
    "start": "tsc && next start"
...
```

**Comment by gozes** [comment]
@rossipedia I think the same can be achieve by having your own gulp file that compiles ts files and move them to the page dir where next picks them up and reloads them right?

**Comment by rossipedia** [comment]
@gozes I don't see why not. I've rarely used gulp, but from what I know of it that seems like a fairly standard use case.

**Comment by jagreehal** [comment]
So here's my attempt https://github.com/jagreehal/next-typescript

It works fine apart from the page reloading twice as I don't think there is a way to configure files NOT to be watched by the hot-reloader.

If additional ignore entries could be added [here](https://github.com/zeit/next.js/blob/master/server/hot-reloader.js#L138) via next.config.js then a solution like this might work.

**Comment by timneutkens** [comment]
@jagreehal That's really cool 💯 I'll have a look into adding the ignore config option in next.config.js.

**Comment by OskarKlintrot** [comment]
I made a PR to @jagreehal example to separate the ts and js. Now the ts is in `src` but is there a way to point `next` to a different folder than the root? Then the output folder for `tsc` could be `dist` instead which would make the folder structure look much cleaner!

**Comment by jagreehal** [comment]
@timneutkens thanks. Let me know if I can help adding config option in next.config.js.

**Comment by timneutkens** [comment]
@jagreehal https://github.com/zeit/next.js/pull/823

**Comment by giacomorebonato** [comment]
I have created a PR with a TypeScript example that works with just running `npm run dev`.
Any suggestions is appreciated.  

https://github.com/zeit/next.js/pull/845

**Comment by giladgray** [comment]
@giacomorebonato awesome stuff! left you some review comments 🍰

**Comment by pbuda** [comment]
Any suggestion on how to use TS with custom server? I wanted to use Express and have some trouble. Basically doing `import next from "next"` fails with `server.ts(2,18): error TS2307: Cannot find module 'next'.` so I guess I'm missing some typings, right?

**Comment by OskarKlintrot** [comment]
With TS 2.1 and above (if I remember correct) you no longer need the typings, if it's in `node_modules` it can always be imported as `any`.
