### ISSUE TITLE
Allow classname prop on <Link>

### ISSUE THREAD

**Issue by bassbump** [zeit/next.js#966]
It looks like this isn't currently possible? Wouldn't it make sense though, since it directly renders as an `<a>`, to be able to style it?

**Comment by bassbump** [comment]
Okay, I figured you can put an `<a/>` tag inside the `<Link href="/"><a className="test">Test</a><Link>` and it will consume it and render it as a single `<a href="/" class="test">Test</a>`.

**Comment by stoplion** [comment]
Would be nicer if Link could take a className tho..
