### ISSUE TITLE
Cannot find module 'next'

### ISSUE THREAD

**Issue by renatorib** [zeit/next.js#967]
I'm trying to setup a custom server to handle some parametrized routes, and I used your example for that.
The problem is that when I run `node server.js`, It throws an error as if I had not installed `next` package.

![image](https://cloud.githubusercontent.com/assets/3277185/22576793/d95fbf4a-e9a4-11e6-8773-37abc9f3b1ea.png)

But, as you can see above, I've installed.

For investigate, I've noticed that package.json `main` is pointing to `dist/lib/index.js`, but when I go to `dist/lib` there is no `index.js` file inside folder.

![image](https://cloud.githubusercontent.com/assets/3277185/22576867/6607c884-e9a5-11e6-8351-a9b2c12ef59b.png)
> Pointing to `dist/lib/index.js`

![image](https://cloud.githubusercontent.com/assets/3277185/22576841/43926fd4-e9a5-11e6-9229-d58a9c798dbb.png)
> Don't have index.js as you can see.

I don't know if this has relation with the bug, but I found no issue reporting this problem.
So, wtf I doing wrong?

--- edit ---

It's about version `next@1.2.3` that has installed by `yarn add next` (probably latest stable)
I've installed `next@2.0.0-beta.22` and it worked (package `main` now pointing to an existing file `dist/server/next.js`)

--- edit ---

Yes, `next@1.2.3` is latest stable (non beta)
![image](https://cloud.githubusercontent.com/assets/3277185/22577332/0e81c53a-e9a8-11e6-8208-ffae438c5b1c.png)

**Comment by arunoda** [comment]
@renatorib `next@1.2.3` does not support custom server. So, you should use the beta.

**Comment by renatorib** [comment]
Oh, sure. It's not clear. Sorry for that.
