### ISSUE TITLE
Add decorator for pages to allow generic wrappers.

### ISSUE THREAD

**Issue by lixiaoyan** [zeit/next.js#971]
Something like this:

``` javascript
addDecorator(children => (
  <Provider store={getStore(...)}>
    {children}
  </Provider>
));
```

or

``` javascript
const App = ({ children }) => (
  <Provider store={getStore(...)}>
    {children}
  </Provider>
);

addDecorator(App);
```

**Comment by arunoda** [comment]
Could you provide more info about this?

**Comment by sakulstra** [comment]
@lixiaoyan not sure if i get your question, but it's pretty much possible to add wrappers around pages:
https://gist.github.com/sakulstra/f0d98ee45ac335f3cd694ed6123bd412#file-generic-get-initial-props-js
is what I personally use to make sure all stores are initialized on every entrypage.

**Comment by lixiaoyan** [comment]
@arunoda @sakulstra I think it would be great if we have a way to make all pages wrapped in something, rather than do it in each file of pages manually.

**Comment by sakulstra** [comment]
Not sure, but if it's really a super generic wrapper you want, you could probably use _document.js or?

Anways, it's basically a one-liner wherever you need it and you usually don't have a billion pages or?
https://github.com/sakulstra/firebase-nextjs-mobx/blob/master/pages/index.js

Could you provide some more information on what you want to archive exactly?

**Comment by lixiaoyan** [comment]
@sakulstra But it may be the only way to add transitions between pages (eg. wrap them into a `<TransitionGroup>`) for now.

**Comment by lixiaoyan** [comment]
@arunoda @sakulstra Any updates on this?

**Comment by lixiaoyan** [comment]
The problem is, when I jumped between the routes, React tree has been fully re-mounted (the root components exported by each page files has different types).

**Comment by arunoda** [comment]
We won't be exactly having something like this. But layout support or something similar will be there.
