### ISSUE TITLE
styled-jsx exported variables don't seem to work with hot reloading

### ISSUE THREAD

**Issue by bassbump** [zeit/next.js#977]
I have the following in Navigation.js component

```
.site-nav__list {
  ${utils.clearlist}
  overflow: visible;
}
```

and the following in theme.js

```
export const utils = {
 'clearlist':
   `list-style: none;
    padding: 0;
    margin: 0;`
}
```

This works on page reload, but doesn't work with hot reloading if I change something in theme.js

Is this intended?

**Comment by timneutkens** [comment]
For safe keeping, since I was about to say: please move this to styled-jsx 😅 

zeit/styled-jsx#104

**Comment by arunoda** [comment]
Ha ha. Anyway, we need some `styled-jsx` expert here.

**Comment by timneutkens** [comment]
cc @giuseppeg

**Comment by giuseppeg** [comment]
@bassbump can you put together a sample repo that I can clone to test and reproduce the issue?

**Comment by bassbump** [comment]
@giuseppeg https://github.com/bassbump/styledjsx-var

I also found out that in next 1.2.3 hot reload still works, it broke in ^2.0.0

**Comment by timneutkens** [comment]
@bassbump that's probably because 1.2.3 doesn't include styled-jsx. Which makes `<style jsx>` a normal `<style>` tag with a `jsx` prop that doesn't do anything.

**Comment by giuseppeg** [comment]
I know what is going on here.

If you have `.p { color: ${colors.blue}; }` the hash is not going to change when you tweak the constant in another file. Next.js sees the change in `theme.js` and recompiles but `components/Header.js` is not recompiled. 

Not sure how to solve this from the styled-jsx side. Next.js should probably recompile dependants too when there is a change on a dependency.

**Comment by giuseppeg** [comment]
@timneutkens @arunoda this might also be the case with external styles now. 
In the following case I imagine that `Button/index.js` is not recompiled when `Button/styles.js` changes

```
components/Button/index.js
components/Button/styles.js
```
Hot reloading should still work for modules inside of `pages` folder though.

You may want to check and in case confirm.
