### ISSUE TITLE
Better explanation of build tool

### ISSUE THREAD

**Issue by tgoldenberg** [zeit/next.js#979]
Would be great to get a better explanation of what exactly the `next build` command does. Just from poking around in the `.next` folder (which is where I assume the build is being produced, I was unable to understand what was created, or how to run the build locally.

@arunoda, you can probably explain this best to me, but coming from MeteorJS, the `build` command would produce a `main.js` file which could then be run locally or with `forever` on a server. Is that the case here as well? When I go in the `.next` folder and try to run the `main.js` file, it just errors out, so I assume something else is going on. 

Would appreciate any explanation on this. Thank you!

**Comment by arunoda** [comment]
Here we've a much node like experience.

We've `.next` directory always. That's we save stuff for SSR and other client side files.
When we run `npm run build` it optimize those files for the production build.

You don't have any executable there. Our `next` module will take care of them.
When you run `next start` it'll find that `.next` directory and start the app.

We need to write a lot on how next works. I'll do it soon.
