### ISSUE TITLE
Now cannot find module 'index.js'

### ISSUE THREAD

**Issue by alexofob** [zeit/next.js#986]
Hi there,

I am trying to deploy my next.js app on 'now' but I get this error:

> Error! Unexpected error. Please try later. (Cannot find module '/Users/alex/Labs/Nextjs/patient/index.js').

Below is my package.json config.
{
  "name": "patient",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "material-ui": "^0.16.7",
    "mobx": "^3.0.2",
    "mobx-react": "^4.1.0",
    "next": "2.0.0-beta.18",
    "react-icons": "^2.2.3",
    "react-slick": "^0.14.5",
    "react-tap-event-plugin": "^2.0.1"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "flow": "flow",
    "start": "next start",
    "test": "jest --watch --env=jsdom"
  },
I will appreciate help on how to resolve this.

Thanks.

BR
Alex

**Comment by alexofob** [comment]
Closing as this issue is related to now

**Comment by flieks** [comment]
@alexofob i see you could get react-slick to work with NextJS. How did you do that ?
https://github.com/akiran/react-slick/issues/842
