### ISSUE TITLE
Babel resolver Needed server side

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#987]
#963

**Comment by arunoda** [comment]
Can we have more info on this?

**Comment by timneutkens** [comment]
Haven't looked into the root cause yet. But this was the origin issue #962

**Comment by arunoda** [comment]
@timneutkens could you give me some re-producible steps. So, I can check this properly.

**Comment by timneutkens** [comment]
@arunoda 
1. download the `with-router` example
2. revert my changes in #963
3. Run the example

**Comment by timneutkens** [comment]
This has been resolved.
