### ISSUE TITLE
restrict files copied into .next/dist/pages

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#988]
I was playing around with the idea of placing a`__tests__` folder into my different directory areas.

So 
```
root
  |-pages
  |     `__tests__
  |             `index.test.js
  |     `index.js
  |-components
  |     `__tests__
  |     `Button.js
  |-layouts
        `__tests__
        `TwoColumn.js
```

But when I do this, I get duplicate issues because of files being copied into .next

`.next/dist/pages/__tests__/index.test.js`

What is the best way to solve this? I know I can omit the files from jest, but I don't think they should be copied over in general.

**Comment by arunoda** [comment]
I think best idea is to ignore `.next` directory from Jest.

**Comment by khrome83** [comment]
Ignoring in Jest just makes sure the test does not run. Does not prevent next from copying the files unneeded.

**Comment by arunoda** [comment]
@khrome83 currently it's possible to avoid sending those files.
They won't get added to webpack bundle or to the client code.

So, we don't need to worry about this issue.

**Comment by nkzawa** [comment]
Basically, you can't put any js files inside `pages` except components. I don't know if you can avoid this with webpack settings.

**Comment by khrome83** [comment]
That is kind of where I was going with this, if there was some configuration that should be opened up, or if by default `__tests__`, `*.tests.js`, `*Spec.js`, etc should not be copied.
