### ISSUE TITLE
Glamor present even when not used

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#989]
I have next@2.0.0-beta.23 and don't refer to glamor anywhere in [my code](https://github.com/relatenow/relate), and yet I see that glamor is in my yarn.lock, even after `yarn install --force`.

**Comment by timneutkens** [comment]
@sedubois it's something I have pointed out before in #next I believe. It's because next/css is deprecated but not removed. The real interesting thing here is, we still use Glamor here https://github.com/zeit/next.js/blob/c21531151f1578ede3699f3565e55553261bd92f/server/document.js#L3
