### ISSUE TITLE
Add GraphQL example to Wiki

### ISSUE THREAD

**Issue by luandro** [zeit/next.js#99]
Would it be possible to have an example on the wiki of how GraphQL data hydration/dehydration could be implemented using [apollo-client](http://dev.apollodata.com/react/server-side-rendering.html)?

**Comment by sedubois** [comment]
See https://github.com/zeit/next.js/issues/106

**Comment by nmaro** [comment]
Maybe #387 could be a candidate

**Comment by timneutkens** [comment]
Closing in favor of #106 and #387. Both are about adding graphql to next, and there has been a lot of discussion about it. Thanks for submitting the larger issue though ❤️
