### ISSUE TITLE
Use react as peer dependency 

### ISSUE THREAD

**Issue by arunoda** [zeit/next.js#997]
Ref: https://twitter.com/finneganswoke/status/828060921918529536

I think it's a pretty good idea to let the app to give us `react` and `react-dom`.
2.0 is a best place to do this, since this is a breaking change.

What do you guys think? @nkzawa @rauchg

**Comment by nkzawa** [comment]
👍  Actually, this is something I wanted to do from the first release.

**Comment by timneutkens** [comment]
I like this 👍  Only downside would be that you'd have to `npm install --save next react react-dom` but that's ok 😄

**Comment by arunoda** [comment]
@timneutkens I think that's totally fine. But we need to update a lot of examples :)

**Comment by eezing** [comment]
@arunoda, @timneutkens, @nkzawa

Just to clarify. . .

When starting fresh, I must do this:
``` $ npm install --save next react react-dom ```

If I want this to work:
``` $ node_modules/.bin/next ```

Is this correct? Thanks!

**Comment by nkzawa** [comment]
@eezing yep

**Comment by eezing** [comment]
@nkzawa  Sorry. . .  deleted my previous comment by mistake. You confirmed that ```$ npm install next react react-dom``` are required for ```$ node_modules/.bin/next ``` to run.

Is there a case where react & react-dom are not required for next to out of the box?

**Comment by nkzawa** [comment]
@eezing We used to have the idea of "default React" which would be used if you didn't explicitly install React on your app. We can discuss that or any other possibilities.
