### ISSUE TITLE
Redux state back to initial when navigate to other route

### ISSUE THREAD

**Issue by pesakitan22** [zeit/next.js#999]
i'm working on next + redux + redux saga + immutable

on the first route the redux and sagas are working normally, but when navigated to other route the state going back to Initial, anyone encountering this issue?

**Comment by pesakitan22** [comment]
sorry my bad, it's working fine. Just need persist state on the client side

**Comment by kowalsska** [comment]
Hey I'm having this problem. What's the way to solve it?
